templates/zerver/api/changelog.md
version.py
zerver/tests/test_users.py

api feature level: Bump level for peer_add/peer_remove.

---

scripts/lib/queue_workers.py
zerver/tests/test_queue_worker.py
zerver/worker/queue_processors.py

This is an incremental cleanup of #16566.

queue: Be more explicit about test/real queue division.

---

docs/subsystems/full-text-search.md

These were somewhat stilted as originally written; reword.

docs: Reword pgroonga sections.

---

tools/setup/bootstrap-aws-installer

Use the parts of the JSON to determine the files it should create.
**Testing plan:** Ran the shell code on a prod host.

provisioning: Support non-RSA SSH keys.

---

corporate/tests/test_stripe.py
tools/fetch-contributor-data
zerver/data_import/slack.py
zerver/lib/markdown/__init__.py
zerver/tests/test_auth_backends.py
zerver/tests/test_create_video_call.py
zerver/tests/test_custom_profile_data.py
zerver/tests/test_docs.py
zerver/tests/test_message_dict.py
zerver/tests/test_signup.py
zerver/tests/test_slack_importer.py
zerver/tests/test_subs.py
zerver/tests/test_thumbnail.py
zerver/tests/test_upload.py
zerver/tests/test_users.py
zerver/views/registration.py

This provides automatic URL encoding.

python: Pass query parameters as a dict when making GET requests

---

zerver/worker/queue_processors.py

Implements in code the grouping that is currently in configuration.

Sentry timeout grouping, bump timeouts

---

static/js/favicon.js

favicon: Invalidate favicon_state.image without a network request

---

frontend_tests/node_tests/dropdown_list_widget.js
frontend_tests/node_tests/settings_org.js
static/js/dropdown_list_widget.js
static/styles/app_components.css
static/styles/night_mode.css
static/styles/portico/billing.css
static/styles/zulip.css

styles: Convert [disabled], [read-only] attribute selectors to :disabled, :read-only pseudo-classes

---

static/styles/compose.css

Compose box css cleanup.

---

templates/zerver/api/dev-fetch-api-key.md
templates/zerver/api/fetch-api-key.md
templates/zerver/help/include/rest-endpoints.md
zerver/openapi/curl_param_value_generators.py
zerver/openapi/markdown_extension.py
zerver/openapi/zulip.yaml

api_docs: Document the /fetch-api-key endpoint.

---

static/styles/zulip.css

This should make no functional changes.
**Testing Plan:** 
**GIFs or Screenshots:**

navbar: clean up :not() selectors

---

frontend_tests/node_tests/widgetize.js
static/js/widgetize.js

widgetize: Don't warn for deleted tictactoe widget.

---

corporate/tests/test_stripe.py
tools/test-backend
zerver/lib/markdown/__init__.py
zerver/lib/markdown/api_arguments_table_generator.py
zerver/lib/markdown/api_return_values_table_generator.py
zerver/lib/markdown/fenced_code.py
zerver/lib/markdown/help_emoticon_translations_table.py
zerver/lib/markdown/help_relative_links.py
zerver/lib/markdown/help_settings_links.py
zerver/lib/markdown/nested_code_blocks.py
zerver/lib/markdown/tabbed_sections.py
zerver/management/commands/check_redis.py
zerver/migrations/0260_missed_message_addresses_from_redis_to_db.py
zerver/openapi/markdown_extension.py
zerver/tests/test_markdown.py
zerver/tests/test_queue_worker.py

This fixes many errors exposed by an attempted upgrade to mypy 0.790. The rest are typeshed bugs that I’m fixing in python/typeshed#4758.

Preparation for mypy 0.790 upgrade

---

frontend_tests/node_tests/general.js

node tests: Add more comments to general.js.

---

zerver/tests/test_decorators.py

https://github.com/zulip/zulip/issues/15331
Tested the entire backend test suite, including the test modified, and verified that it passed.
Modifications done were essentially just to migrate the decorators tests to use assertLogs instead of mock.patch.

Migrate to assertLogs in decorator tests

---

static/js/ui_init.js

This is equivalent because we cannot have `delta < 0 && delta > 0`.

ui_init: Unnest an if statement

---

templates/zerver/help/import-from-slack.md

slack-import: Explain current implementation about threads.

---

zerver/forms.py
zerver/tests/test_signup.py
zerver/views/registration.py

Fixes #17015
tested manually as well as using ./tools/test-backend

registration: Validate email to accounts/home

---

docs/production/ssl-certificates.md

docs: Say that certbot wildcard has been released.

---

docs/development/remote.md

typos Update remote.md

---

frontend_tests/puppeteer_lib/common.js

This commit fixes the broken assertions for checking if compose box is empty.
Fixes #17088 
Tested it locally by running that test.

puppeteer_test: Replace textContent to value for the compose box.

---

docs/tutorials/new-feature-tutorial.md
templates/zerver/api/changelog.md
version.py
zerver/lib/actions.py
zerver/lib/event_schema.py
zerver/lib/events.py
zerver/openapi/zulip.yaml
zerver/tests/test_archive.py
zerver/tests/test_events.py
zerver/tests/test_subs.py

This sets the stage for us to use better data structures over the wire.

Clean up backend subscriber code.

---

tools/push-to-pull-request

As Tim [requested](https://chat.zulip.org/#narrow/stream/44-git-help/topic/Automatically.20close.20issues/near/1101593).
**Testing plan:** Ran on a test repository.

push-to-pull-request: Add --merge option

---

zerver/lib/url_preview/preview.py

url preview: Update Zulip User-Agent.
Fixes #16970.

url preview: Update Zulip User-Agent.

---

docs/overview/changelog.md
frontend_tests/node_tests/message_edit.js
templates/zerver/api/changelog.md
templates/zerver/help/community-topic-edits.md
templates/zerver/help/configure-message-editing-and-deletion.md
zerver/models.py
zerver/tests/test_message_edit.py

Relevant conversation https://chat.zulip.org/#narrow/stream/2-general/topic/topic.20edit.20permission

Increase community topic editing time limit.

---

zerver/lib/redis_utils.py
zerver/management/commands/list_realms.py

Found by upgrading semgrep.
**Testing plan:**
```console
$ ./manage.py list_realms
id    string_id            name                           domain                                            
--    ---------            ----                           ------                                            
1     zulipinternal        None                           http://zulipinternal.zulipdev.com:9991            
2     zulip                Zulip Dev                      http://localhost:9991                             
3     analytics            Analytics                      http://analytics.zulipdev.com:9991                
```

python: Convert more percent formatting

---

frontend_tests/node_tests/muting.js
frontend_tests/node_tests/settings_muting.js

[3.x] node_tests: Fix suddenly failing tests for unknown reasons

---

static/js/blueslip.js
static/js/settings_emoji.js
static/js/settings_invites.js
static/js/stream_create.js
static/js/stream_edit.js
static/js/ui_report.js
tools/linter_lib/custom_check.py

Relevant conversation:
https://chat.zulip.org/#narrow/stream/49-development-help/topic/.2316932/near/1104644

ui_report: Add ui_report.client_error.

---

docs/subsystems/widgets.md
frontend_tests/node_tests/composebox_typeahead.js
static/js/composebox_typeahead.js

composebox: Add typeahead for /todo.

---

tools/push-to-pull-request

**Testing plan:** Ran on a test repository.

push-to-pull-request: Wait for GitHub background update before merge

---

frontend_tests/node_tests/upload.js

node_tests: Fix #comepose-textarea typo

---

zerver/webhooks/bitbucket2/fixtures/commit_comment_created.json
zerver/webhooks/bitbucket2/fixtures/commit_status_changed.json
zerver/webhooks/bitbucket2/fixtures/force_push.json
zerver/webhooks/bitbucket2/fixtures/fork.json
zerver/webhooks/bitbucket2/fixtures/issue_commented.json
zerver/webhooks/bitbucket2/fixtures/issue_created.json
zerver/webhooks/bitbucket2/fixtures/issue_updated.json
zerver/webhooks/bitbucket2/fixtures/more_than_one_push_event.json
zerver/webhooks/bitbucket2/fixtures/pull_request_approved_or_unapproved.json
zerver/webhooks/bitbucket2/fixtures/pull_request_comment_action.json
zerver/webhooks/bitbucket2/fixtures/pull_request_created_or_updated.json
zerver/webhooks/bitbucket2/fixtures/pull_request_created_or_updated_without_username.json
zerver/webhooks/bitbucket2/fixtures/pull_request_fulfilled_or_rejected.json
zerver/webhooks/bitbucket2/fixtures/push.json
zerver/webhooks/bitbucket2/fixtures/push_commits_above_limit.json
zerver/webhooks/bitbucket2/fixtures/push_more_than_one_tag.json
zerver/webhooks/bitbucket2/fixtures/push_multiple_committers.json
zerver/webhooks/bitbucket2/fixtures/push_multiple_committers_with_others.json
zerver/webhooks/bitbucket2/fixtures/push_one_tag.json
zerver/webhooks/bitbucket2/fixtures/push_remove_tag.json
zerver/webhooks/bitbucket2/fixtures/push_without_changes.json
zerver/webhooks/bitbucket2/fixtures/remove_branch.json
zerver/webhooks/bitbucket2/fixtures/repo_updated.json
zerver/webhooks/bitbucket2/tests.py
zerver/webhooks/bitbucket2/view.py

 bitbucket webhook: Fully deprecate username field.

---

zerver/lib/markdown/__init__.py

Commit 434094e599f928060e4296720ceb21c2d92c57f8 (#11321) changed this from an `Extension` to a subclass of `Markdown`, so it no longer has any reason to use a `config` dict structured like that of an `Extension`.
Alternative to #17194.

markdown: Explode config dict

---

frontend_tests/node_tests/components.js
static/js/components.js
static/js/compose.js
static/js/composebox_typeahead.js
static/js/hotspots.js
static/js/loading.js
static/templates/hotspot_icon.hbs

For consistency and correctness; probably not exploitable.

HTML escaping fixes

---

docs/translating/internationalization.md
docs/translating/translating.md
frontend_tests/node_tests/message_list.js
frontend_tests/node_tests/message_list_data.js
frontend_tests/node_tests/narrow_local.js
frontend_tests/node_tests/narrow_state.js
static/js/message_fetch.js
static/js/message_list.js
static/js/message_list_data.js
static/js/muting_ui.js
static/js/narrow.js
static/js/narrow_state.js
static/js/zulip.js

I have corrected grammatical and syntax error in translating.md and internationalization.md docs.

Grammatical error corrected

---

static/templates/subscription_members.hbs

Based on conversation in https://chat.zulip.org/#narrow/stream/31-production-help/topic/bulk.20add.20users.20to.20new.20stream

subscription_members: Make the help text more clear.

---

zerver/lib/actions.py

This makes the code easier to visually scan.

minor: Clean up code formatting for do_create_user.

---

zerver/lib/digest.py
zerver/tests/test_digest.py

Need to add tests
Related discussion https://chat.zulip.org/#narrow/stream/49-development-help/topic/hot.20topics

digest: Sort topics in descending order in get_hot_topics.

---

frontend_tests/node_tests/message_list.js
frontend_tests/node_tests/message_list_data.js
frontend_tests/node_tests/narrow_local.js
frontend_tests/node_tests/narrow_state.js
static/js/message_fetch.js
static/js/message_list.js
static/js/message_list_data.js
static/js/muting_ui.js
static/js/narrow.js
static/js/narrow_state.js
static/js/zulip.js

Prep changes for mute user and some minor bug fixes

---

frontend_tests/zjsunit/namespace.js

https://chat.zulip.org/#narrow/stream/92-learning/topic/node.20tests.3A.20When.20to.20run.20actual.20dependency.20code.3F/near/1117756

minor: Suggest with_field instead of override for non-functions.

---

static/js/message_viewport.js

ui: Fix detection of narrow window.

---

docs/production/requirements.md
docs/subsystems/index.rst
docs/subsystems/performance.md

This document is mainly an answer to a set of questions other
developers have been asking about Zulip's architecture and scalability
design.  It's intended for developers working on Zulip, to help with
thinking about where to prioritize further efforts to optimize
scalability.

docs: Add a performance design document.

---

static/shared/js/typing_status.js.flow
tools/lint

shared: Format our one Flow file with Prettier

---

static/js/message_flags.js
static/js/starred_messages.js
static/js/stream_popover.js
static/templates/topic_sidebar_actions.hbs
static/templates/unstar_messages_modal.hbs

Fixes #12194
This PR adds support to unstar all starred messages in a particular topic.
Most of this work was done by @Abhishek-Balaji in #14753 .
This is a updated and cleaned up version of the same.
**Testing plan:**  Tested manually.
<details><summary> Screenshots </summary>
</details>

Add support to unstar all messages in a topic.

---

zerver/data_import/import_util.py
zerver/lib/cache.py
zerver/lib/markdown/__init__.py
zerver/lib/test_helpers.py
zerver/lib/timeout.py
zerver/tests/test_report.py
zerver/tests/test_service_bot_system.py
zerver/tests/test_subs.py
zerver/views/streams.py
zerver/views/user_groups.py
zerver/webhooks/bitbucket3/view.py
zerver/webhooks/clubhouse/view.py
zerver/webhooks/gogs/view.py
zerver/webhooks/groove/view.py
zerver/webhooks/intercom/view.py
zerver/webhooks/jira/view.py

`Callable[..., T]` is for when we have no idea what arguments a function will be called with; mypy will not check them at all. When we do know, we should always be specific.

Mypy safety improvements related to Callable[..., T] misuse

---

static/styles/portico/markdown.css

Fixes part of #15967.
**Testing plan:** Manually tested on localhost.
**Earlier**: 
**Now**:

api docs: Improve readability of code and response blocks.

---

docs/development/setup-advanced.md

From discussion in https://chat.zulip.org/#narrow/stream/49-development-help/topic/Windows.2010.

wsl_docs: Inform user how to uninstall WSL.

---

docs/subsystems/performance.md

When reading through the doc, I figured it was worth to make some minor tweaks/typo fixes on the way. Not sure if all of these will be improvements, but at least some should be.

docs: Writing tweaks to performance.md.

---

docs/contributing/code-reviewing.md

Improvement to our code-reviewing docs based on the conversation here - https://chat.zulip.org/#narrow/stream/91-code-review/topic/code.20review.20guide/near/1121193
cc @showell

docs: Update author protocol section of the code-reviewing docs.

---

frontend_tests/zjsunit/zjquery.js

See 2nd commit for more details. @showell FYI.

Improve zjquery error message when users uses tag as a selector.

---

docs/production/management-commands.md

Added `./manage.py reactivate_realm` command within `Management commands` markdown referring to @timabbott <a href = 'https://chat.zulip.org/#narrow/stream/2-general/topic/how.20to.20reactivate.20a.20organization.20group.3F/near/1104443'>suggestion</a>.

docs: Added reactivate_realm management command.

---

.eslintrc.json
frontend_tests/node_tests/activity.js
frontend_tests/node_tests/drafts.js
frontend_tests/node_tests/fetch_status.js
frontend_tests/node_tests/list_cursor.js
frontend_tests/node_tests/message_fetch.js
frontend_tests/node_tests/message_list.js
frontend_tests/node_tests/message_list_data.js
frontend_tests/node_tests/message_list_view.js
frontend_tests/node_tests/narrow_activate.js
frontend_tests/node_tests/narrow_local.js
frontend_tests/node_tests/stream_data.js
frontend_tests/node_tests/stream_list.js
frontend_tests/node_tests/ui_init.js
static/js/activity.js
static/js/bundles/app.js
static/js/drafts.js
static/js/fetch_status.js
static/js/global.d.ts
static/js/list_cursor.js
static/js/localstorage.js
static/js/message_list.js
static/js/message_list_data.js
static/js/narrow.js
static/js/panels.js
static/js/reload.js
static/js/stream_list.js
static/js/ui.js

Some initial results from starting to teach modzulator (#10018) how to modify `node_tests`.

Convert more easy modules to ES6 modules

---

docs/contributing/gsoc-ideas.md

docs: Correct some spelling mistakes and add some missing full stops at end of the sentence.

---

frontend_tests/node_tests/compose_actions.js
frontend_tests/node_tests/hotkey.js
frontend_tests/node_tests/people_errors.js
frontend_tests/node_tests/poll_widget.js
frontend_tests/node_tests/presence.js
frontend_tests/node_tests/search.js
frontend_tests/node_tests/search_legacy.js
frontend_tests/node_tests/stream_events.js
frontend_tests/node_tests/stream_list.js

node tests: Clean up hotkey tests.

---

tools/check-provision
tools/lib/test_script.py
tools/lib/test_server.py
tools/lint
tools/pre-commit
tools/run-dev.py
tools/run-mypy
tools/test-all
tools/test-api
tools/test-backend
tools/test-help-documentation
tools/test-js-with-node
tools/test-js-with-puppeteer

issue: #17455 
**Testing plan:** Manually by tweaking provision version or by changing `assert_provisioning_status_ok` to intentionally fail.
Fixes: #17455

Clean --force arg

---

static/styles/settings.css
static/templates/edit_bot.hbs
static/templates/settings/dropdown_list_widget.hbs

Revert "edit_bot: Fixed dropdown username capitalization and other bugs."

---

static/js/timerender.js

**Testing plan:** Hacked timestamps to update every second.

Fix exponential timerender explosion

---

frontend_tests/node_tests/server_events.js
static/js/server_events.js

https://api.jquery.com/jQuery.now/

server_events: Replace deprecated $.now alias

---

docs/subsystems/events-system.md
docs/subsystems/index.rst
docs/subsystems/notifications.md
docs/subsystems/sending-messages.md
zerver/lib/email_notifications.py
zerver/lib/push_notifications.py
zerver/tornado/event_queue.py

@showell @mateuszmandera @hashirsarwar @amanagr @ryanreh99 @shubhamdhama @andersk @gnprice review is much appreciated!  
Feel free to just add commits fixing typos/restyling/etc or adding more content; I've probably spent all the bulk time I can on this document for the next while.

docs: Add a document explaining email/push notifications.

---

tools/check-schemas

tools: Add success message to check-schemas.

---

puppet/zulip_ops/manifests/ksplice_uptrack.pp

puppet: Add a warning if ksplice is enabled but has no key set.

---

static/js/panels.js
static/js/server_events_dispatch.js

Fixes #17463 
tested using ./tools/test-all

settings: Improve check for incomplete organization description.

---

static/js/avatar.js
static/templates/confirm_delete_user_avatar.hbs

avatar: Add confirmation dialog before deleting profile picture

---

templates/zerver/api/changelog.md
templates/zerver/api/get-user-presence.md
zerver/openapi/curl_param_value_generators.py
zerver/openapi/python_examples.py
zerver/openapi/zulip.yaml
zerver/tests/test_openapi.py
zerver/tests/test_presence.py
zerver/views/presence.py
zproject/urls.py

Fixes #14304
tested manually as well as using ./tools/test-backend

api: Support user_id in get_user_presence endpoint.

---

docs/testing/mypy.md

This is an expanded version of the [notes I posted in #learning](https://chat.zulip.org/#narrow/stream/92-learning/topic/mypy.20error/near/978210) last year.

docs: Document some mypy best practices

---

frontend_tests/puppeteer_tests/07-navigation.ts

puppeteer_test/7: Fix invalid selector for `waitFor`.

---

templates/zerver/app/left_sidebar.html

**Testing plan:** tested locally.

Rename "Add streams" to "Subscribe to more streams" in left-sidebar.

---

static/js/stream_list.js

Fixes: #16691
**Testing plan:**
Manually Tested

Stream list doesen't update after deleteing last stream.

---

static/js/settings_profile_fields.js

settings: Fix input mouse behaviour in custom profile fields.

---

zerver/lib/unminify.py

If the client has an old version of the code which is not present on
the server, don't throw a 500; instead, default to the same `unable to
look up in source map` message is used when the line numbers don't
line up.

unminify: Fix lookup if source map does not exist in disk.

---

static/js/click_handlers.js
static/js/hotkey.js
static/js/recent_topics.js
static/templates/recent_topics_filters.hbs

Fixes #17587
Checks 2nd and 3rd boxes of #15826. Thanks @pilgrim2308 !

Recent topics fix scroll position being reset.

---

frontend_tests/node_tests/popovers.js
static/js/hash_util.js
static/js/popovers.js

markdown: Fix a bug in query_and_reply.

---

templates/zerver/app/right_sidebar.html

**Testing plan:** tested locally
**Screenshot:**

change icon for invite-user-link to look more user-interactive.

---

docs/production/deployment.md
puppet/zulip/templates/nginx/zulip-enterprise.template.erb
puppet/zulip_ops/files/nginx/sites-available/zulip
puppet/zulip_ops/files/nginx/sites-available/zulip-org
puppet/zulip_ops/files/nginx/sites-available/zulip-staging
tools/droplets/zulipdev

**Testing Plan:** Tested on https://andersk.zulipdev.org.

nginx: Consistently listen on IPv6 and with HTTP/2

---

frontend_tests/node_tests/channel.js
static/js/channel.js
tools/test-js-with-node

Add 100% test coverage to channel.js

---

static/templates/recent_topic_row.hbs

correction: change area-label from mute to unmute.

---

zerver/webhooks/zabbix/doc.md

I have added a note about the fact these instructions are for Zabbix 5.2
and above and the workflow for other versions of Zabbix may be
different.
https://chat.zulip.org/#narrow/stream/127-integrations/topic/zabbix-integration
Linters

integrations: Update Zabbix Documentation.

---

requirements/common.in
requirements/dev.txt
requirements/prod.txt
scripts/lib/setup_venv.py
version.py
zerver/lib/email_mirror.py

https://github.com/mailgun/talon/pull/200
**Testing plan:** ???

requirements: Upgrade talon fork to 1.4.8

---

docs/translating/hindi.md

**Testing Plan:** 
**GIFs or Screenshots:**

Fixed translations and added comments in templates

---

zerver/tests/test_event_system.py

This should help @shanukun fix one of the commits in #17709

tests: Test send_restart_events.

---

templates/zerver/api/changelog.md
version.py
zerver/lib/message.py
zerver/openapi/zulip.yaml
zerver/tests/test_message_flags.py

Completes the PR #17696 by @timabbott

message: Record whether unread_msgs data is truncated.

---

docs/development/setup-advanced.md
scripts/lib/build-pgroonga
scripts/lib/setup-yum-repo
tools/lib/provision.py

**Testing plan:**
Tested manually using Vagrant with [Fedora 33 box](https://app.vagrantup.com/generic/boxes/fedora33). Tests ran successfully.

provision: Add support for Fedora 33.

---

zerver/lib/markdown/__init__.py
zerver/tests/test_markdown.py

Fixes: #17535
Testing is done in development server and by adding new markdown test for testing changes.
**For user mention:**
```
source:  @**Cordelia Lear**  @**invalid** and @**King Hamlet**
```
output:
**For user group mention:**
```
source:  @*hamletcharacters*  @*invalid group* @*hamletcharacters*
```
output:
**For stream mention:**
```
source:  #**invalid stream>first BOTS wasn't loading**, #**devel>invalid topic**, #**invalid stream>invalid topic**  #**devel>first BOTS wasn't loading**  and then #**support**
```
output:

Markdown mention bug

---

frontend_tests/node_tests/templates.js
frontend_tests/node_tests/templates/and.hbs
frontend_tests/node_tests/templates/numberFormat.hbs
frontend_tests/node_tests/templates/or.hbs
frontend_tests/node_tests/templates/rendered_markdown.hbs
static/js/templates.js
tools/test-js-with-node

Add 100% test coverage for template.js

---

docs/overview/changelog.md
static/templates/delete_topic_modal.hbs
static/templates/topic_sidebar_actions.hbs
templates/zerver/help/delete-a-topic.md

delete_topic: Change verbiage of "Delete all messages in topic" to "Delete topic".

---

docs/development/overview.md

#17721
Yes !! there is a method to setup a non-Vagrant environment on windows

non-Vagrant environment docs updated

---

templates/zerver/api/deactivate-own-user.md
templates/zerver/help/include/rest-endpoints.md
tools/test-api
zerver/openapi/python_examples.py
zerver/openapi/test_curl_examples.py
zerver/openapi/zulip.yaml

Fixes #16163 
1. Tested on localhost
2. Ran ./tools/test-api
3. Ran ./tools/test-backend

apidocs: Add documentation of deactivate-my-account endpoint.

---

templates/zerver/integrations/capistrano.md
templates/zerver/integrations/email.md
templates/zerver/integrations/nagios.md
templates/zerver/integrations/openshift.md
templates/zerver/integrations/phabricator.md
templates/zerver/integrations/puppet.md
templates/zerver/integrations/trac.md
templates/zerver/integrations/twitter.md
zerver/webhooks/deskdotcom/doc.md
zerver/webhooks/helloworld/doc.md
zerver/webhooks/zendesk/doc.md

Update documentation numbers

---

frontend_tests/node_tests/composebox_typeahead.js
frontend_tests/node_tests/filter.js
frontend_tests/node_tests/message_list_view.js
frontend_tests/node_tests/settings_user_groups.js
frontend_tests/node_tests/upload.js
static/js/attachments_ui.js
static/js/blueslip.js
static/js/compose.js
static/js/compose_ui.js
static/js/dropdown_list_widget.js
static/js/filter.js
static/js/message_list.js
static/js/message_list_data.js
static/js/poll_widget.js
static/js/reload.js
static/js/reminder.js
static/js/server_events.js
static/js/settings_ui.js
static/js/stream_color.js
static/js/stream_topic_history.js
static/js/subs.js
static/js/typeahead_helper.js
static/js/ui_report.js
static/js/upload.js
static/shared/js/typeahead.js

(MDN docs: [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters), [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring).)
**Testing plan:** Basic dev server testing.

js: Simplify code using default parameters and destructuring

---

static/js/resize.js

right-sidebar: Remove extra subtrahend from max-height of user-list.

---

frontend_tests/node_tests/dispatch.js
frontend_tests/node_tests/lib/events.js
frontend_tests/node_tests/settings_user_groups.js
static/js/server_events_dispatch.js
static/js/settings_user_groups.js

related to https://chat.zulip.org/#narrow/stream/9-issues/topic/Blueslip.20error.20in.20deleting.20user.20group.

user groups: Add remove event.

---

static/styles/rendered_markdown.css

rendered_markdown: Add horizontal scrollbar to overflowing ```math

---

zerver/lib/outgoing_webhook.py
zerver/tests/test_outgoing_webhook_interfaces.py
zerver/tests/test_outgoing_webhook_system.py
zerver/worker/queue_processors.py

**Testing plan:** Existing and modified tests.

Refactor outgoing bot requests to use a session object, set common headers.

---

frontend_tests/node_tests/example5.js
frontend_tests/node_tests/example7.js
frontend_tests/node_tests/message_fetch.js
frontend_tests/node_tests/narrow_activate.js
frontend_tests/node_tests/narrow_local.js
frontend_tests/node_tests/recent_senders.js
frontend_tests/node_tests/recent_topics.js
frontend_tests/node_tests/stream_events.js
frontend_tests/node_tests/stream_topic_history.js
static/js/all_messages_data.js
static/js/bundles/app.js
static/js/echo.js
static/js/local_message.js
static/js/message_events.js
static/js/message_fetch.js
static/js/message_list.js
static/js/message_live_update.js
static/js/message_util.js
static/js/narrow.js
static/js/recent_senders.js
static/js/stream_events.js
static/js/stream_muting.js
static/js/stream_topic_history.js
static/js/ui.js
static/js/unread_ops.js

Cc @showell @timabbott.
**Testing plan:** Did some simple tests with sending, receiving, and narrowing.

message_list: Downgrade message_list.all to MessageListData

---

frontend_tests/node_tests/dispatch.js
frontend_tests/node_tests/message_flags.js
tools/test-js-with-node

Add 100% coverage to message_flags.js

---

.github/workflows/production-suite.yml
.github/workflows/zulip-ci.yml
tools/ci/Dockerfile.template

Ref https://github.com/zulip/zulip/pull/17858#issuecomment-809621849

ci: Switch to hosting the CI images under Zulip on Dockerhub.

---

frontend_tests/node_tests/narrow.js
static/js/narrow_banner.js
tools/test-js-with-node

Add 100% test coverage to narrow_banner.js

---

static/js/setup.js

The start time of the last password change was the wrong time to use, because we could start a password change, start another request, finish the password change, and then observe that the other request failed due to the password change.
We could use the end time, but a counter is more robust to sub-millisecond race conditions.

setup: Use the number of completed password changes for race detection

---

static/templates/topic_muted.hbs

Bold popovers

---

static/templates/admin_user_group_list.hbs

template: change the delete button with delete icon frm user_group_list.

---

templates/zerver/for/working-groups-and-communities.md

docs: Add info on zulip-archive on for/working-groups-and-communities.

---

zerver/lib/bot_lib.py

This PR finishes a TODO to set storage_size_limit with the server configuration.
Tested with existing backend tests.

embedded bot: Use server settings for storage_size_limit.

---

zerver/lib/actions.py
zerver/tests/test_reactions.py

This PR rewriting zulip/zulip#16985.

Send message reaction event to all eligible users.

---

static/templates/recipient_row.hbs

Edit topic label

---

templates/zerver/help/invite-new-users.md

https://github.com/zulip/zulip/issues/16951
**Issue:** 
Documentation to be updated at Invite New Users part as ; only Realm Admins , Owners can "Generate Invite User Link " .
**Before :-** 
**After :-**

documentation: Change in invite new users part.

---

zerver/lib/outgoing_webhook.py
zerver/openapi/zulip.yaml
zerver/tests/test_outgoing_webhook_interfaces.py

Fixes: #12282
It has been tested by running `tools/test-backend` and by manually adding print statement to check the output.

api: Add bot name to outgoing webhook payload.

---

docs/development/authentication.md
docs/subsystems/settings.md
templates/zerver/team.html

portico: Update number of contributors listed on the website.
portico: Clean up authentication.md text; no content changes.

Website and doc minor cleanup

---

zerver/lib/test_classes.py
zerver/tests/test_subs.py

The tests for can_create_streams and can_subscribe_other_users shares a
lot of code and we deduplicate the code by extracting most of the code
as check_has_permission_policies which will now be called by the two
tests test_can_create_streams and test_can_subscribe_other_users.
This will also help in avoiding the duplication of code when we will
convert more policies to use COMMON_POLICY_TYPES.

tests: Extract a single function to test functions using has_permission.

---

static/templates/subscription_table_body.hbs

**Testing plan:** tested locally
Before
-------------
After
-------------

frontend: change create-stream btn design pattern with our current design pattern

---

frontend_tests/puppeteer_tests/user-deactivation.ts
static/js/avatar.js
static/js/settings_user_groups.js
static/js/starred_messages_ui.js
static/templates/delete_topic_modal.hbs
static/templates/settings/account_settings.hbs
static/templates/settings/deactivate_realm_modal.hbs
static/templates/settings/deactivation_stream_modal.hbs
static/templates/settings/deactivation_user_modal.hbs

Fixes #17926 .
<details>
</details>

confirm_dialog: Change the label to Confirm.

---

CODE_OF_CONDUCT.md
tools/documentation_crawler/documentation_crawler/spiders/common/spiders.py

#17928
Ran `tools/test-documentation` and linters.

Test documentation fix output spam

---

static/js/compose.js
static/js/reminder.js

(I have grand plans to make this kind of mistake lintable, but they are too grand for this PR.)

compose: HTML-escape errors from server for compose_error

---

docs/documentation/integrations.md
docs/documentation/overview.md
docs/documentation/user.md

This PR just makes a few grammar changes to documentation files.
N/A
N/A

Documentation grammar changes

---

frontend_tests/node_tests/composebox_typeahead.js
frontend_tests/node_tests/markdown.js
frontend_tests/puppeteer_lib/common.ts
frontend_tests/puppeteer_tests/compose.ts
frontend_tests/puppeteer_tests/drafts.ts
frontend_tests/puppeteer_tests/edit.ts
frontend_tests/puppeteer_tests/message-basics.ts
zerver/tests/fixtures/ldap/directory.json
zerver/tests/test_email_notifications.py
zerver/tests/test_import_export.py
zerver/tests/test_markdown.py
zerver/tests/test_message_edit.py
zerver/tests/test_message_edit_notifications.py
zerver/tests/test_message_send.py
zerver/tests/test_new_users.py
zerver/tests/test_push_notifications.py
zerver/tests/test_soft_deactivation.py
zerver/tests/test_users.py
zerver/webhooks/intercom/fixtures/conversation_admin_closed.json
zerver/webhooks/intercom/fixtures/conversation_admin_noted.json
zerver/webhooks/intercom/fixtures/conversation_admin_opened.json
zerver/webhooks/intercom/fixtures/conversation_admin_replied.json
zerver/webhooks/intercom/fixtures/conversation_admin_single_created.json
zerver/webhooks/intercom/fixtures/conversation_admin_snoozed.json
zerver/webhooks/intercom/fixtures/conversation_admin_unsnoozed.json
zerver/webhooks/intercom/tests.py
zilencer/management/commands/populate_db.py

Changed the name of the Default user Cordelia from `Cordelia Lear` to `Cordelia, Lear's daughter`.
This change will enable us to test users with escaping characters in their names.
Related Issue : #14991
CZO [Link Here](https://chat.zulip.org/#narrow/stream/9-issues/topic/quote.20and.20reply.20broken.20on.20zulip.20cloud/near/1159666)

default data: Add an escaping character to a default username.

---

static/js/message_edit.js
static/templates/copy_message_button.hbs

Fixes #18053
Tested manually for all cases.

message_edit: Fix copy paste bug on local-echo/pending message.

---

Vagrantfile
docs/development/setup-advanced.md

Fixes zulip/zulip#16994
**Testing**
Tested whether the provisioning is successful multiple times. It is.

Vagrant hyperv

---

frontend_tests/node_tests/muting.js

node tests: Clear muted users in test() wrapper.

---

static/js/typeahead_helper.js

Test this by creating a custom ":thank_you:" emoji for Iago.

emoji typehahead: Fix render_emoji.

---

frontend_tests/node_tests/recent_senders.js
static/js/message_events.js
static/js/recent_senders.js

(see commit message for explanation)

refactor: Simplify recent_senders code.

---

frontend_tests/node_tests/activity.js
frontend_tests/node_tests/pm_list.js
static/js/activity.js
static/js/pm_list.js
static/styles/left_sidebar.css

Fix unread count not being updated for PMs.

---

frontend_tests/node_tests/poll_widget.js

We also have Alice vote on the current user's poll.

node tests: Avoid people stubs for poll test.

---

analytics/tests/test_views.py
analytics/views.py
static/styles/portico/activity.css
templates/analytics/realm_details.html
zerver/models.py
zerver/tests/test_users.py

Show user role in /support page search results

---

zerver/lib/actions.py
zerver/lib/stream_subscription.py
zerver/lib/stream_topic.py
zerver/lib/streams.py
zerver/tests/test_reactions.py
zerver/tests/test_subs.py

Fixes #17922 , `subscriber_ids_with_stream_history_access` and some random minor code improvements.

Adjust semantics of get_active_subscriptions_for_stream_id and fix subscriber_ids_with_stream_history_access

---

static/templates/compose_all_everyone.hbs
static/templates/compose_announce.hbs

templates: Fix <br> → <br /> to be parseable by FormatJS

---

zerver/lib/soft_deactivation.py

There exists a logic bug (see #18236) which causes duplicate
usermessage rows to be inserted.  Currently, this stops catch-up for
all users.
Catch and record the exception for each affected user, so we at least
make catch-up progress on other users.

soft_deactivate: Log and continue on failure to catch up a user.

---

docs/development/authentication.md
frontend_tests/node_tests/common.js
static/js/common.js
static/js/portico/signup.js
static/js/settings.js
static/js/settings_account.js
static/js/settings_ui.js
static/styles/components.css
static/styles/settings.css
static/templates/settings/account_settings.hbs
static/templates/settings/api_key_modal.hbs
templates/zerver/login.html
templates/zerver/register.html
templates/zerver/reset_confirm.html

login: Add show password feature.

---

tools/linter_lib/custom_check.py
zerver/tests/test_auth_backends.py
zerver/views/auth.py
zerver/views/development/dev_login.py
zproject/dev_urls.py
zproject/urls.py

https://github.com/zulip/zulip/issues/18191#issuecomment-822650295
This refactor will help us make our development-related authentication
code to avoid production security impact.
Tested it by running backend tests. ✅ 

refactor: Split dev related code from `auth.py` into `dev_login.py`.

---

.eslintrc.json
frontend_tests/node_tests/password.js
static/js/common.js
static/js/copy_and_paste.js
static/js/password_quality.js
static/js/portico/help.js
static/js/portico/signup.js
static/js/settings_account.js
static/js/ui.js
tools/webpack.assets.json
webpack.config.ts

**Testing plan:** Tested Markdown conversion on copy and paste; tested password quality meter in app’s change password form and portico registration form, and checked that zxcvbn is loaded asynchronously for the former.

Module cleanup: SimpleBar, Turndown, jquery-validation, zxcvbn

---

frontend_tests/node_tests/list_widget.js
frontend_tests/node_tests/people.js
frontend_tests/puppeteer_tests/subscriptions.ts
static/js/list_widget.js
static/js/people.js
static/js/stream_create.js
static/styles/subscriptions.css
static/styles/zulip.css
static/templates/new_stream_user.hbs
static/templates/new_stream_users.hbs

Alternative approach to #18026
@timabbott just using list widget here makes the stream creation process very smooth for a 15k+ users realm.

Use `ListWidget` to render list of users in stream creation form.

---

docs/development/index.rst
docs/development/test-install.md

**Testing plan:** @adambirds used it!

docs: Document the `test-install` tooling.

---

frontend_tests/node_tests/compose.js
frontend_tests/node_tests/compose_video.js
frontend_tests/node_tests/upload.js
frontend_tests/puppeteer_tests/compose.ts
frontend_tests/puppeteer_tests/drafts.ts
static/js/click_handlers.js
static/js/compose.js
static/js/copy_and_paste.js
static/js/emoji_picker.js
static/js/giphy.js
static/js/lightbox.js
static/js/message_edit.js
static/js/popovers.js
static/js/rows.js
static/js/tippyjs.js
static/js/upload.js
static/styles/compose.css
static/styles/rendered_markdown.css
static/styles/zulip.css
static/templates/compose.hbs
static/templates/compose_control_buttons.hbs
static/templates/message_edit_form.hbs

Deduplicate common code between message edit and compose.

---

frontend_tests/node_tests/i18n.js

This was missed in commit cef2ecf00445fcff6ea40ddb910ffa3ddd3c5bbf (#18252).

node_tests: Fix (non-fatal) error from i18n test

---

frontend_tests/node_tests/input_pill.js
frontend_tests/node_tests/stream_pill.js
frontend_tests/node_tests/user_group_pill.js
frontend_tests/node_tests/user_pill.js
static/js/input_pill.js
static/js/stream_pill.js
static/js/user_group_pill.js
static/js/user_pill.js

Reference: [https://github.com/zulip/zulip/pull/17994#issuecomment-822886392](https://github.com/zulip/zulip/pull/17994#issuecomment-822886392) Point-1.
`node tests`
**GIFs or screenshots:** There should be no UI changes due to this.

Add type field to pill items.

---

docs/production/postgresql.md
docs/production/upgrade-or-modify.md
scripts/lib/install
scripts/setup/upgrade-postgresql

**Testing plan:** CI will test on Pg 13, and Bionic will test the upgrade from 10 -> 13.

postgresql: Switch to defaulting to PostgreSQL 13.

---

zerver/openapi/zulip.yaml

@WesleyAC @abhijeetbodas2001 @alya thoughts on this as the specification for how muted users should work?

api docs: Add design details for muted users.

---

frontend_tests/node_tests/compose.js
frontend_tests/node_tests/compose_video.js
static/assets/icons/zulip-icons.font.js
static/js/compose.js
static/js/giphy.js
static/js/message_edit.js
static/styles/components.css
static/styles/compose.css
static/styles/zulip.css
static/templates/compose_control_buttons.hbs
static/templates/me_message.hbs
static/templates/message_body.hbs
static/templates/message_controls.hbs
static/templates/stream_sidebar_row.hbs
static/templates/topic_list_item.hbs
static/templates/user_group_info_popover_content.hbs
static/templates/user_info_popover_content.hbs
static/templates/user_presence_row.hbs
templates/zerver/app/left_sidebar.html
templates/zerver/archive/single_message.html
templates/zerver/help/delete-a-topic.md
templates/zerver/help/emoji-reactions.md
templates/zerver/help/include/message-actions-menu.md
templates/zerver/help/include/stream-actions.md
templates/zerver/help/marking-messages-as-read.md
templates/zerver/help/mention-a-user-or-group.md
templates/zerver/help/mute-a-topic.md
templates/zerver/help/status-and-availability.md
templates/zerver/help/stream-notifications.md
templates/zerver/help/view-someones-profile.md

discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/giphy.20integration
@timabbott looks like I missed out some things while rebasing the giphy pr, sorry for the trouble. Added a commit to fix it too.

Fix giphy icon not being served by server.

---

frontend_tests/node_tests/lib/events.js
templates/zerver/api/changelog.md
zerver/lib/event_schema.py
zerver/lib/events.py
zerver/lib/test_helpers.py
zerver/openapi/zulip.yaml
zerver/tests/test_event_system.py
zerver/tests/test_events.py
zerver/tornado/event_queue.py

Fixes: #18205, #15541.
**Testing plan:** `tools/test-backend zerver.tests.test_event_system.RestartEventsTest.test_restart`

Add zulip_version and zulip_feature_level in restart event.

---

docs/production/management-commands.md
docs/subsystems/management-commands.md

docs: Add production documentation for custom management commands.

---

zerver/lib/events.py

events: Convert recursion to a loop in do_events_register

---

static/js/click_handlers.js
static/js/giphy.js
static/styles/compose.css
static/styles/night_mode.css
static/styles/zulip.css
static/templates/compose_control_buttons.hbs

Correct gif icon in night mode.

GIPHY followup fixes.

---

tools/build-docs

docs: Make tools/docs have a faster edit/refresh cycle.

---

templates/zerver/help/include/sidebar_index.md

user docs: Move "Create a poll" section in Sending messages.

---

static/styles/portico/markdown.css
templates/zerver/help/configure-message-editing-and-deletion.md
templates/zerver/help/stream-permissions.md

help center: Improved formatting for labels in stream permissions table.

---

templates/zerver/help/archive-a-stream.md
templates/zerver/help/change-your-name.md
templates/zerver/help/deactivate-or-reactivate-a-user.md
templates/zerver/help/deactivate-your-account.md
templates/zerver/help/deactivate-your-organization.md
templates/zerver/help/delete-a-topic.md
templates/zerver/help/edit-or-delete-a-message.md

docs: Fix typos in user docs.

---

tools/commit-message-lint

lint: Set repository variable in tools/commit-message-lint.

---

Vagrantfile
puppet/zulip/files/nagios_plugins/zulip_app_frontend/check_worker_memory
puppet/zulip/manifests/profile/rabbitmq.pp
puppet/zulip/manifests/supervisor.pp
puppet/zulip_ops/files/cron.d/camo
scripts/restart-server
tools/ci/Dockerfile.template

Marginally better solutions to the problems fixed by #18334. Cc @alexmv.

Replace ‘which’ utility with ‘command -v’ shell builtin; use ‘pgrep -x’ to avoid accidental matches

---

static/js/hotspots.js
static/js/settings_display.js
static/js/settings_notifications.js
static/js/settings_org.js
static/js/tutorial.js
templates/zerver/api/changelog.md
version.py
zerver/tests/test_create_video_call.py
zerver/tests/test_hotspots.py
zerver/tests/test_realm_domains.py
zerver/tests/test_settings.py
zerver/tests/test_subs.py
zerver/tests/test_tutorial.py
zerver/views/hotspots.py
zerver/views/realm_domains.py
zerver/views/streams.py
zerver/views/tutorial.py
zerver/views/user_settings.py
zerver/views/video_calls.py

Fixes #18035.
Backend tests, frontend tests, manual testing.

[WIP] api: Fix encoding of strings in endpoints.

---

zerver/lib/actions.py

We combine the two loops into one, so that we
can check our flags before creating the
UserMessageList object.
And we lift a few calculations out of the loop.
For 8k users, with 95% long-term-idle, this was
about a 10x speedup for me.  (~30ms -> 3ms)

send performance: Optimize create_user_messages.

---

docs/translating/translating.md
static/templates/default_language_modal.hbs
static/templates/settings/display_settings.hbs

https://chat.zulip.org/#narrow/stream/58-translation/topic/missing.20string

minor: Mark text for translation.

---

static/shared/README.md

This is mostly in preparation for moving the code for polls into shared, but should also be good in general.
I'm not sure what the process is for pushing this to npm, @showell, can you let me know what I need to do for that?

shared: Bump version to 0.0.5.

---

static/js/settings_display.js
static/js/stream_edit.js
templates/zerver/api/changelog.md
version.py
zerver/openapi/python_examples.py
zerver/openapi/zulip.yaml
zerver/tests/test_settings.py
zerver/tests/test_subs.py
zerver/views/streams.py
zerver/views/user_settings.py

Remove unnecessary `json_validator` for endpoints (update_display_settings, update_streams).
Fixes part of #18035.

Remove unnecessary `json_validator` for endpoints.

---

frontend_tests/node_tests/hash_util.js
frontend_tests/node_tests/stream_edit.js
frontend_tests/node_tests/subs.js
static/js/hash_util.js
static/js/hashchange.js
static/js/reload.js
static/js/settings_streams.js
static/js/stream_edit.js
static/js/subs.js

Based on Tim's comment  - https://github.com/zulip/zulip/pull/15650#discussion_r577226127

Extract window.location.hash references into hashchange.js.

---

.eslintrc.json
frontend_tests/node_tests/upgrade.js
static/js/emoji_picker.js
static/js/filter.js
static/js/hotkey.js
static/js/input_pill.js
static/js/lightbox.js
static/js/lightbox_canvas.js
static/js/message_edit.js
static/js/narrow.js
static/js/rtl.js
static/js/settings_org.js

The cleanup commits after the first commit are not strictly necessary, so we could delay them until after 4.0 if we want.

Upgrade JavaScript dependencies

---

frontend_tests/node_tests/people.js
frontend_tests/node_tests/poll_widget.js
static/js/people.js
static/js/poll_widget.js
templates/zerver/help/mute-a-user.md

[WIP] Follow-ups to `mute users` feature.

---

zerver/lib/send_email.py
zerver/tests/test_send_email.py

**Testing plan:** Existing and new tests.

send_email: Show more information about messages which failed to send.

---

frontend_tests/node_tests/people.js
frontend_tests/node_tests/recent_topics.js
static/js/muting_ui.js
static/js/people.js
static/js/recent_topics.js
static/styles/night_mode.css
static/styles/recent_topics.css
static/templates/recent_topic_row.hbs
templates/zerver/help/mute-a-user.md

recent topics: Handle muted user avatars in participants.

---

scripts/lib/upgrade-zulip-from-git
static/styles/night_mode.css
static/styles/zulip.css
templates/zerver/app/about-zulip.html
tools/cache-zulip-git-version
version.py
zerver/context_processors.py
zerver/tests/test_context_processors.py
zerver/views/home.py

This PR is as yet unfinished, but has plumbing that we'll want to display on the "About Zulip" version page to make it informative.
Here's a screenshot of its current state:
There's plenty of visual changes we'll want to make to this, but I think the hard part is the data plumbing.

Compute and display details on the Zulip version

---

frontend_tests/node_tests/composebox_typeahead.js
frontend_tests/node_tests/pm_conversations.js

node tests: Clear muted users before each test.

---

static/js/tippyjs.js
static/js/ui.js
static/templates/edit_content_button.hbs
static/templates/message_controls.hbs

Use tooltips for all message action buttons.
cc: @timabbott

Message action tooltip

---

scripts/lib/upgrade-zulip-from-git
scripts/purge-old-deployments

**Testing plan:** Tested in production (Ubuntu 18.04) on https://andersk.zulipdev.org.

upgrade-zulip-from-git: Create deployment directories with git worktree

---

static/styles/zulip.css

message_edit_form: Fix vertical aliments of bottom elements.

---

frontend_tests/node_tests/activity.js
frontend_tests/node_tests/list_cursor.js
frontend_tests/node_tests/user_search.js

The general theme here is to test modules more directly.

node tests: Prepare for activity.js cleanup

---

zproject/jinja2/__init__.py

**Testing plan:** Checked page-params on dev server.

jinja2: Serialize page-params with orjson

---

static/styles/portico/integrations_dev_panel.css
templates/zerver/development/integrations_dev_panel.html

It's primarily for style changes to improve the look of the integration devtool.
**Before**
**After**

devtools: Improve the appearance of dev_panel.

---

corporate/tests/test_stripe.py
templates/corporate/billing.html

billing: Show billing email in /billing page

---

frontend_tests/node_tests/message_list_view.js

node tests: Add test wrapper for message_list_view.

---

static/styles/zulip.css

Increasing the font size for clear visibility.
before:
after:

tippy: Increase font size from 12 to 13px.

---

requirements/common.in
requirements/dev.txt
requirements/prod.txt
version.py

pypi: Upgrade zulip/zulip-bots dependencies to version 0.8.0.

---

puppet/zulip_ops/files/postgresql/setup_disks.sh
puppet/zulip_ops/manifests/profile/base.pp
scripts/lib/install
tools/setup/install-aws-server

Improve some of the tooling around standing up new hosts internally in Zulip Cloud.
**Testing plan:** Deployed new internal hosts.

Clean up Zulip Cloud new host deployments

---

zerver/webhooks/pivotal/view.py

integrations: Add `label_create_activity` to unsupported pivotal events.

---

templates/zerver/help/import-from-slack.md

docs: Clarify that the Slack app and API token should be removed.

---

scripts/lib/node_cache.py

Appending data back-to-back without serializing it loses the
information about where the breaks between them lie, which can lead to
different inputs having the same hash.
---
Ref https://github.com/zulip/zulip/pull/18586#discussion_r641005892

node_cache: Serialize to structured data before hashing.

---

.eslintrc.json
frontend_tests/node_tests/activity.js
frontend_tests/node_tests/components.js
frontend_tests/node_tests/keydown_util.js
static/js/activity.js
static/js/components.js
static/js/info_overlay.js
static/js/keydown_util.js
static/js/keydown_util.ts
static/js/settings_panel_menu.js
static/js/stream_list.js

**Testing Plan**: Manually tested the last commit by trying out all keys in the settings panel since it uses all the keys you can specify.

Convert keydown_util to TypeScript.

---

zerver/lib/test_classes.py
zerver/tests/test_event_system.py
zerver/tests/test_message_flags.py
zerver/tests/test_message_send.py
zerver/tests/test_reactions.py
zerver/tests/test_realm.py
zerver/tests/test_submessage.py
zerver/tests/test_subs.py
zerver/tests/test_typing.py
zerver/tests/test_user_status.py
zerver/tests/test_users.py

Further improve `tornado_redirected_to_list`

---

docs/production/authentication-methods.md

To avoid future confusion like in https://chat.zulip.org/#narrow/stream/31-production-help/topic/SAML.20metadata/near/1191213

Tweak SAML doc regarding SP private key generation

---

static/templates/unsubscribe_private_stream_modal.hbs

Fix the incorrect warning message when unsubscribing from stream.

---

zerver/webhooks/pagerduty/doc.md

https://chat.zulip.org/#narrow/stream/9-issues/topic/doc/near/1197978
Fixing the documentation of the Pageduty webhook integration.

Change supported extension type to reflect the latest change in the Pageduty webhook.

---

zerver/management/commands/send_test_email.py

**Testing plan:** Broke SMTP auth, saw logs; with no errors, did not.

send_test_email: Capture and show SMTP log on errors.

---

frontend_tests/puppeteer_lib/common.ts
frontend_tests/puppeteer_tests/message-basics.ts
frontend_tests/puppeteer_tests/navigation.ts
frontend_tests/puppeteer_tests/realm-linkifier.ts
frontend_tests/puppeteer_tests/settings.ts
package.json
yarn.lock

CZO Thread: https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/upgrading.20puppeteer.20to.209.2E1.2E1
Tested the changes by running the test 100 times on [CI](https://github.com/Riken-Shah/zulip/actions/runs/869240562).
(Also https://github.com/Riken-Shah/zulip/actions/runs/873993710)

Upgrading puppeteer to 9.1.1.

---

corporate/models.py

The billing system has been mostly devoid of any documentation. This
commit is meant to add a basic documentation of the data model of this
system.

corporate: Add some basic documentation of the corporate/* models.

---

zerver/management/commands/delete_realm.py

**Testing plan:** I'm not sure the right way to test this, or that `get_current_plan_by_realm` is the right check.

delete_realm: Don't allow deletion of realms with current plans.

---

zerver/tests/test_docs.py
zerver/views/documentation.py

apidocs: Fix invalid API page bug. 

---

frontend_tests/node_tests/buddy_data.js
frontend_tests/node_tests/popovers.js
static/js/buddy_data.js

See https://chat.zulip.org/#narrow/stream/137-feedback/topic/usability.3A.20orange.20status.20indicator/near/1199989 for background.

Fix display of presence status in mouseover UI.

---

templates/zerver/features.html
templates/zerver/help/private-messages.md
templates/zerver/help/status-and-availability.md

Making `/features` have a complete set of links.
Manually tested in dev environment.

Features page

---

zerver/tests/test_example.py

The idea here is to quickly learn basic testing
idioms with code that's executed (unlike docs
which are prone to bitrot).

tests: Add test_example.py.

---

puppet/zulip_ops/manifests/apache.pp
puppet/zulip_ops/manifests/profile/base.pp
puppet/zulip_ops/manifests/profile/nagios.pp
puppet/zulip_ops/templates/nagios3/cgi.cfg.template.erb

51b985b40d made these unnecessary.

puppet: Remove now-unused basic auth support files.

---

puppet/zulip_ops/files/grafana/grafana.ini
puppet/zulip_ops/files/prometheus/prometheus.yaml
puppet/zulip_ops/files/supervisor/conf.d/grafana.conf
puppet/zulip_ops/files/supervisor/conf.d/prometheus.conf
puppet/zulip_ops/files/supervisor/conf.d/prometheus_node_exporter.conf
puppet/zulip_ops/manifests/profile/base.pp
puppet/zulip_ops/manifests/profile/grafana.pp
puppet/zulip_ops/manifests/profile/prometheus_server.pp
puppet/zulip_ops/manifests/prometheus/base.pp
puppet/zulip_ops/manifests/prometheus/node.pp

Adds basic prometheus monitoring and graphing.
**Testing Plan:** Spun up a host with it.

Prometheus

---

tools/webpack
webpack.config.ts

`--optimize-minimize` no longer exists. (Webpack 5 has `--optimization-minimize`.)

webpack: Fix run-dev.py --minify

---

static/js/popovers.js
static/styles/night_mode.css
static/styles/popovers.css
static/templates/user_group_list_item.hbs
static/templates/user_profile_modal.hbs
static/templates/user_stream_list_item.hbs

Fixes: #16233 .
**chat.zulip.org thread:** [https://chat.zulip.org/#narrow/stream/6-frontend/topic/add.20streams.20and.20user.20groups.20of.20an.20user.20in.20full.20profile.20mo.2E.2E.2E](https://chat.zulip.org/#narrow/stream/6-frontend/topic/add.20streams.20and.20user.20groups.20of.20an.20user.20in.20full.20profile.20mo.2E.2E.2E)
This completes work that was started by @Abhirup-99 in #16663.
@shubhamdhama  @pragatiagrawal31 FYI.

Show stream subscriptions and user groups in profile modal.

---

static/js/invite.js
static/js/popovers.js
static/js/stream_edit.js
static/js/stream_settings_data.js
static/js/todo_widget.js

A followup for #18671, based on [https://github.com/zulip/zulip/pull/18671#discussion_r650038695](https://github.com/zulip/zulip/pull/18671#discussion_r650038695).
**Testing plan:** node tests and manually

Localecompare migration

---

frontend_tests/node_tests/compose_validate.js
frontend_tests/node_tests/compose_video.js
frontend_tests/node_tests/drafts.js
frontend_tests/node_tests/popovers.js
frontend_tests/node_tests/settings_org.js
frontend_tests/node_tests/settings_profile_fields.js
frontend_tests/node_tests/settings_user_groups.js
frontend_tests/node_tests/stream_edit.js
frontend_tests/node_tests/subs.js
frontend_tests/node_tests/typeahead_helper.js
frontend_tests/zjsunit/namespace.js

Use `mock_template` in more node tests.

---

static/js/lightbox.js
static/templates/lightbox_overlay.hbs
templates/zerver/app/index.html

lightbox_overlay: Migrate to handlebars.

---

docs/production/troubleshooting.md
puppet/zulip/files/nagios_plugins/zulip_app_frontend/check_email_deliverer_process
puppet/zulip/manifests/profile/smokescreen.pp
puppet/zulip/manifests/supervisor.pp
puppet/zulip/templates/supervisor/zulip.conf.template.erb
puppet/zulip_ops/manifests/app_frontend.pp
puppet/zulip_ops/manifests/profile/grafana.pp
puppet/zulip_ops/manifests/profile/munin_server.pp
puppet/zulip_ops/manifests/profile/prometheus_server.pp
puppet/zulip_ops/manifests/profile/zmirror.pp
puppet/zulip_ops/manifests/prometheus/node.pp
scripts/lib/zulip_tools.py
scripts/refresh-sharding-and-restart
scripts/restart-server
scripts/stop-server

Supervisor cleanups

---

static/js/message_edit_history.js
static/js/ui_init.js
static/templates/message_history.hbs
templates/zerver/app/home.html

message_history: Migrate to handlebars.

---

static/js/about_zulip.js
static/js/ui_init.js
static/templates/about_zulip.hbs
templates/zerver/app/index.html
zerver/lib/home.py
zerver/tests/test_home.py
zerver/views/home.py

about_zulip: Migrate to handlebars.

---

templates/analytics/realm_summary_table.html

Based on the feedback @alya left at https://github.com/zulip/zulip/pull/18760#issuecomment-859919273
* Effective rate -> Rate
* Describe what the rate column shows.

/activity: Rename effective rate column to rate

---

zerver/context_processors.py
zerver/tests/test_docs.py

context_processors: Add test for `get_apps_page_url`.

---

static/js/stream_popover.js
static/templates/topic_sidebar_actions.hbs
zerver/lib/actions.py
zerver/tests/test_message_edit.py

This implements the design in #18751.

Add support for resolving a topic

---

docs/testing/testing-with-django.md
zerver/tests/test_example.py

Adds an example to illustrate the use of:
* self.settings()
* self.assertLogs()
* self.assert_in_success_response()

test_example: Add a few more common testing methods.

---

templates/zerver/api/add-reaction.md
templates/zerver/api/get-events.md
templates/zerver/api/get-messages.md
templates/zerver/api/get-streams.md
templates/zerver/api/get-subscriptions.md
templates/zerver/api/get-user-by-email.md
templates/zerver/api/get-user.md
templates/zerver/api/get-users.md
templates/zerver/api/mute-topic.md
templates/zerver/api/register-queue.md
templates/zerver/api/remove-reaction.md
templates/zerver/api/set-typing-status.md
templates/zerver/api/subscribe.md
templates/zerver/api/unsubscribe.md
templates/zerver/api/update-display-settings.md
templates/zerver/api/update-message.md
templates/zerver/api/update-notification-settings.md
templates/zerver/api/update-stream.md
templates/zerver/api/update-user-group-members.md
zerver/openapi/markdown_extension.py
zerver/openapi/openapi.py
zerver/openapi/test_curl_examples.py
zerver/openapi/zulip.yaml

openapi: Migrate curl examples' configs into OpenAPI data.

---

zerver/lib/upload.py

Fixes #18915
This was very slow, causing performance issues. After investigating,
generate_presigned_url is the cheap part of this, but the
session.client() call is expensive - so that's what we should cache.
Before the change:
```
In [4]: t = time.time()
...: for i in range(250):
...:     x = u.get_public_upload_url("foo")
...: print(time.time()-t)
6.408717393875122
```
After:
```
In [4]: t = time.time()
...: for i in range(250):
...:     x = u.get_public_upload_url("foo")
...: print(time.time()-t)
0.48990607261657715
```
So this may be good enough and lets us avoid doing something ugly like
replacing generate_presigned_url with some manual URL manipulation.

upload: Cache the boto client to improve performance.

---

static/js/blueslip.ts
static/js/global.d.ts
static/js/page_params.ts
static/js/zulip_test.js

Followup to https://github.com/zulip/zulip/pull/18840#discussion_r651354903

js: Export variables instead of setting them on window.

---

static/js/popovers.js
static/styles/popovers.css
static/templates/user_profile_modal.hbs

Cleanup user profile modal-related code. Preparatory work for #18879. 
These are small changes that I wanted to get focus so I opened a separate PR for these instead of having them as commits in the PR I open for #18879 .
**GIFs or screenshots:** This does not change UI in any way.

User profile modal refactor

---

static/js/loading.js
static/js/message_viewport.js
static/js/unread_ops.js

js: Simplify more code using default parameters and destructuring

---

static/js/tippyjs.js

discussion in https://github.com/zulip/zulip/pull/18856#discussion_r654726607

tippy: Clarify how to use `tippy-zulip-tooltip` class.

---

static/styles/user_status.css

user_status: Fix styling of modal.

---

zerver/lib/push_notifications.py
zerver/tests/test_push_notifications.py

https://github.com/zulip/zulip/issues/18713
**Testing plan:** "No need for tests for i18n tags"

Issue#18713: tag redacted message for i18n

---

static/js/user_profile.js
static/styles/popovers.css
static/templates/user_profile_modal.hbs
static/templates/user_stream_list_item.hbs

Fixes: #18879.
**Testing plan:** Manually.
* **Admin unsubscribing other user**
* **Unsubscribing for own profile**

Unsub button

---

docs/subsystems/index.rst
docs/subsystems/slash-commands.md
docs/subsystems/widgets.md

I also write about how to classify a feature as one of these two, but I'd like to hear thoughts on those definitions (which are mainly inspired by https://chat.zulip.org/#narrow/stream/101-design/topic/slash.20commands).

docs: Split widgets and slash command developer pages.

---

templates/zerver/api/changelog.md
templates/zerver/api/outgoing-webhooks.md
templates/zerver/api/rest-error-handling.md
zerver/openapi/zulip.yaml

Fix certain responses in API docs

---

static/js/settings.js
static/js/settings_toggle.js
static/templates/gear_menu.hbs
templates/zerver/api/deploying-bots.md
templates/zerver/api/incoming-webhooks-walkthrough.md
templates/zerver/api/outgoing-webhooks.md
templates/zerver/app/settings_overlay.html
templates/zerver/help/change-default-view.md
templates/zerver/integrations/google-calendar.md
zerver/lib/markdown/help_relative_links.py
zerver/lib/markdown/help_settings_links.py

Clearly differentiate personal settings from organization settings.

---

static/js/user_profile.js
static/styles/popovers.css
static/templates/user_profile_modal.hbs

Fixes: #18878.
**Testing plan:** manually.
**In mobile screen**

Add filter widget in profile modal stream list.

---

zerver/lib/upload.py

Addressing @andersk comment https://github.com/zulip/zulip/pull/18920#discussion_r656489441
This has some negative performance impact, but may still be acceptable - details in the commit messages.

upload: Don't use string formatting in public url creation.

---

static/js/user_profile.js
static/styles/popovers.css
static/templates/user_profile_modal.hbs

Followup for: https://github.com/zulip/zulip/pull/19039#issuecomment-872565482
**Testing plan:** Manually.

Stream name alignment fixes and minor refactors for ids in profile modal tabs.

---

templates/zerver/faq.html

Add two questions to the billing FAQ:
- What is the difference between automatic and manual billing?
- How will I be charged for temporary users (e.g. limited-time
clients)?
See guest pricing discussion: https://chat.zulip.org/#narrow/stream/191-kandra-support/topic/guest.20pricing
Previewed on dev and checked help page link.

portico: Extend billing FAQ.

---

.github/workflows/production-suite.yml

Create cache directories for the upgrade check
in the production-suite.

upgrade-check: Add create cache directory step.

---

zerver/lib/markdown/api_return_values_table_generator.py
zerver/openapi/markdown_extension.py
zerver/openapi/openapi.py
zerver/views/documentation.py

The absence of `__init__.py` was preventing mypy from following any of the `zerver.openapi` imports.  These errors were being silenced by `ignore_missing_imports`.

openapi: Add missing __init__.py; fix type errors hidden by its absence

---

requirements/common.in
requirements/dev.in
requirements/dev.txt
requirements/docs.txt
requirements/mypy.in
requirements/mypy.txt
requirements/prod.txt
version.py
zerver/lib/markdown/__init__.py
zerver/lib/rate_limiter.py
zerver/lib/test_console_output.py
zerver/lib/test_runner.py
zerver/management/commands/check_redis.py

* asgiref: 3.3.4 → 3.4.1
* black: 21.5b2 → 21.6b0
* boto3: 1.17.89 → 1.17.105
* botocore: 1.20.89 → 1.20.105
* django[argon2]: 3.2.4 → 3.2.5
* isort: 5.8.0 → 5.9.1
* line-profiler: 3.1.0 → 3.3.0
* moto[s3]: 2.0.8 → 2.0.10
* mypy: 0.812 → 0.910
* orjson: 3.5.3 → 3.5.4
* phonenumberslite: 8.12.24 → 8.12.26
* pip-tools: 6.1.0 → 6.2.0
* prompt-toolkit: 3.0.18 → 3.0.19
* psycopg2: 2.8.6 → 2.9.1
* pyrsistent: 0.17.3 → 0.18.0
* python-debian: 0.1.39 → 0.1.40
* regex: 2021.4.4 → 2021.7.1
* ruamel.yaml: 0.17.7 → 0.17.10
* ruamel.yaml.clib: 0.2.2 → 0.2.4
* semgrep: 0.54.0 → 0.57.0
* tlds: 2021060600 → 2021070101
* tqdm: 4.61.0 → 4.61.1
* twilio: 6.59.1 → 6.61.0
* types-boto: (new) → 0.1.2
* types-certifi: (new) → 0.1.4
* types-chardet: (new) → 0.1.3
* types-dataclasses: (new) → 0.1.5
* …

Upgrade Python requirements

---

static/templates/subscription_settings.hbs

Change icon and tooltip for Archive stream

---

frontend_tests/node_tests/rendered_markdown.js
frontend_tests/node_tests/timerender.js
static/js/rendered_markdown.js
static/js/timerender.js
static/js/tippyjs.js
static/templates/markdown_time_tooltip.hbs

czo discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/.3Ctime.3E.20widget.20tooltip.2E

<time>: Reformat and use tippyjs tooltip.

---

zerver/decorator.py
zerver/lib/test_classes.py
zerver/webhooks/travis/tests.py
zerver/webhooks/travis/view.py

webhooks: Allow event registration using webhook_view decorator.

---

zerver/lib/test_classes.py
zerver/webhooks/bitbucket2/tests.py
zerver/webhooks/travis/tests.py

Address https://github.com/zulip/zulip/pull/18525#issuecomment-871002091.
This PR is rebased onto #19059.

Add noop option for check_webhook.

---

static/js/condense.js
static/templates/message_body.hbs

See discussion on CZO:
https://chat.zulip.org/#narrow/stream/137-feedback/topic/.22Condense.22.20vs.20.22Collapse.22

message_body: Rename "Condense" to "Show less".

---

zerver/tests/test_realm.py

This PR removes the duplicated individual tests in `test_realm.py` as we test all those
values already in `do_test_realm_update_api`.

tests: Remove duplicated tests from test_realm.py.

---

frontend_tests/node_tests/compose_error.js
static/js/click_handlers.js
static/js/compose_error.js

Follow up #18982
Tested with node tests.

compose: Make a function to hide compose error.

---

static/js/tippyjs.js
static/templates/left_sidebar.hbs
static/templates/right_sidebar.hbs

See https://chat.zulip.org/#narrow/stream/9-issues/topic/.22Search.20people.22.20tooltip.20cut.20off.

tooltip: Improve tooltip placement for User sidebar.

---

package.json
version.py
yarn.lock

django-webpack/webpack-bundle-tracker#101
**Testing plan:** Edited `static/js/people.js` twice while the dev server is running.

webpack: Fix webpack-bundle-tracker hot update bug

---

frontend_tests/puppeteer_tests/admin.ts
frontend_tests/puppeteer_tests/message-basics.ts
frontend_tests/puppeteer_tests/subscriptions.ts
zerver/lib/actions.py
zerver/lib/cache.py
zerver/lib/retention.py
zerver/openapi/curl_param_value_generators.py
zerver/openapi/python_examples.py
zerver/tests/test_audit_log.py
zerver/tests/test_email_mirror.py
zerver/tests/test_event_system.py
zerver/tests/test_events.py
zerver/tests/test_home.py
zerver/tests/test_import_export.py
zerver/tests/test_message_fetch.py
zerver/tests/test_new_users.py
zerver/tests/test_push_notifications.py
zerver/tests/test_realm.py
zerver/tests/test_signup.py
zerver/tests/test_subs.py
zerver/tests/test_users.py
zilencer/management/commands/populate_db.py

Use do_create_realm in populate_db.py

---

zerver/tests/test_muting_users.py
zerver/views/muting.py

muting: Add support for muting deactivated users.

---

zerver/lib/push_notifications.py
zerver/tests/test_push_notifications.py

push_notifications: Send mentioned user group ID and name in payload.

---

scripts/lib/zulip_tools.py
scripts/restart-server
scripts/stop-server

Fixes for upgrades across ef6d0ec5caa3683931bf69b9ea8cad4b392b198e.

Restart old supervisor

---

frontend_tests/node_tests/compose.js
frontend_tests/node_tests/compose_validate.js
static/js/compose.js
static/js/compose_actions.js
static/js/compose_validate.js
static/js/composebox_typeahead.js
static/styles/compose.css

Fixes #19182
Tested on local env.
https://user-images.githubusercontent.com/63820270/125172506-c2f53480-e1d7-11eb-9459-6c050ff0393a.mov

compose: Improve compose box errors

---

zerver/tests/test_queue_worker.py
zerver/worker/queue_processors.py

The `# nocoverage` was unnecessary apart from for the compatibility code,
so add a test for that code and remove the `# nocoverage`.
The `message_id` -> `message_ids` conversion was done in
9869153ae80febf6dca29e4a136a7b4d20ea32f9.
Followup to https://github.com/zulip/zulip/pull/19170#issuecomment-876599752

worker: Ensure complete coverage for PushNotificationsWorker.

---

templates/zerver/for/open-source.md

Manual testing, but I'd appreciate a double-check on the links.

Clarify that Zulip Standard is free for open source

---

.github/workflows/cancel-previous-runs.yml
docs/development/remote.md
docs/production/install-existing-server.md
docs/production/install.md
docs/production/upgrade-or-modify.md
docs/tutorials/shell-tips.md
scripts/lib/build-pgroonga
scripts/lib/install-node
scripts/lib/install-yarn
scripts/setup/apt-repos/zulip/custom.sh
scripts/setup/sha256-tarball-to
templates/zerver/help/desktop-app-install-guide.md
tools/ci/Dockerfile.prod
tools/ci/send-failure-message
tools/push-to-pull-request
tools/setup/bootstrap-aws-installer
tools/setup/bootstrap-awscli.sh
tools/setup/dev-vagrant-docker/Dockerfile
tools/setup/install-shellcheck
tools/setup/install-shfmt

This makes `curl` exit with nonzero status on HTTP 4xx/5xx errors.

scripts: Use curl -f (--fail)

---

frontend_tests/node_tests/filter.js
frontend_tests/node_tests/narrow.js
frontend_tests/node_tests/narrow_local.js
frontend_tests/node_tests/narrow_unread.js
frontend_tests/node_tests/search_suggestion.js
frontend_tests/node_tests/search_suggestion_legacy.js
static/js/filter.js
static/js/narrow_banner.js
static/js/search_suggestion.js
static/templates/search_operators.hbs
templates/zerver/app/message_feed_errors.html
templates/zerver/help/search-for-messages.md
zerver/lib/actions.py
zerver/lib/narrow.py
zerver/lib/topic.py
zerver/tests/fixtures/narrow.json
zerver/tests/test_message_edit.py
zerver/tests/test_message_fetch.py
zerver/views/message_fetch.py

Fixes: #18990.
New test cases are added.

resolve topic: Add `is:resolved` search keyword/filtering support.

---

package.json
version.py
yarn.lock

Includes the SimpleBar fix needed for #18822.

dependencies: Upgrade JavaScript dependencies

---

tools/ci/Dockerfile
tools/ci/build-docker-images

**Testing plan:** Tested by renaming the images to anderskaseorg/zulip-ci: https://github.com/andersk/zulip/runs/3072625185

ci: Remove unused detritus from Docker images

---

static/js/portico/header.js
static/styles/portico/landing_page.css
static/styles/portico/portico.css
templates/zerver/landing_nav.html
templates/zerver/portico-header-dropdown.html
templates/zerver/portico-header.html

@timabbott, @amanagr, @alya: This took way way longer than I expected. But this is how I am hoping to implement dropdowns for the top-level navigation.

landing_page: Restructure top-level navigation.

---

static/styles/popovers.css
static/styles/zulip.css

message_edit: Fix the height of `stream_header_colorblock`.

---

zerver/tests/test_auth_backends.py
zproject/backends.py
zproject/prod_settings_template.py

This will be a tiny bit more complicated when we add multiple IdP support, but for now this should do it.

oidc: Add auto_signup configuration option.

---

tools/lib/test_script.py

**Testing plan:** Ran `tools/test-js-with-puppeteer message-basics` and `tools/test-js-with-puppeteer frontend_tests/puppeteer_tests/message-basics.ts`.

test_script: Fix path computation in find_js_test_files

---

zerver/openapi/markdown_extension.py

Most of the Markdown Preprocessors followed a common
template, and it was redundant to `run` and `init` code
multiple times for execution of the Preprocessor.
This commit adds a base class from which the preprocessors
following the pattern can inherit, and can override the
`render` function to execute the code.
**Testing plan:** Tested via diffs of HTML pages. No differences.

openapi: Make base class for Markdown Preprocessors.

---

zerver/lib/rate_limiter.py

This prevents a memory leak caused by the `SimpleLazyObject` instance of
`UserProfile` that create a reference loop with the request object
via `ZulipRequestNotes`.
A follow-up fix that comes after #19282 and #19322
context: [chat](https://chat.zulip.org/#narrow/stream/3-backend/topic/HttpRequest.20-.3E.20ZulipHttpRequest.20conversion/near/1232467)
This eliminates the reference loop shown below:

rate_limiter: Avoid strong reference to user.

---

static/styles/portico/landing_page.css
templates/zerver/landing_nav.html

@alya @timabbott FYI :) Here is a screenshot of what the dropdown looks like:

landing_page: Link to case studies in the top navigation.

---

frontend_tests/node_tests/settings_data.js
static/js/settings_data.js
static/js/ui_init.js

settings_data: Break circular dependency with people.

---

templates/zerver/for/tum-case-study.md
templates/zerver/for/ucsd-case-study.md

Fixed typos and added missing links.
Manual testing.

Typo fixes on case studies

---

.mailmap

Add mailmap entry for Sahil Batra.

mailmap: Add mailmap entry for Sahil Batra.

---

frontend_tests/node_tests/example3.js
frontend_tests/node_tests/example4.js
frontend_tests/node_tests/example8.js

`./tools/test-js-with-node example8.js`

node_tests: Add a mock_template example test.

---

static/styles/portico/landing_page.css
templates/zerver/for/tum-case-study.md
templates/zerver/for/ucsd-case-study.md
templates/zerver/tum-case-study.html
templates/zerver/ucsd-case-study.html

Minor changes to the tops and bottoms of the case study pages.
Manual testing.

Case study tweaks

---

templates/zerver/team.html

portico: Add Zoe.

---

frontend_tests/node_tests/widgetize.js
static/js/widgetize.js
static/styles/widgets.css

**Before**
**After**
**Before**
**After**
**Before**
**After**
CC @showell

Fix poll widget not working in `All messages` view.

---

analytics/management/commands/update_analytics_counts.py
analytics/views/stats.py
analytics/views/support.py
confirmation/models.py
corporate/lib/stripe.py
corporate/models.py
corporate/tests/test_stripe.py
zerver/lib/actions.py
zerver/lib/email_mirror.py
zerver/lib/export.py
zerver/lib/send_email.py
zerver/lib/soft_deactivation.py
zerver/tests/test_events.py
zerver/tests/test_message_fetch.py
zerver/tests/test_realm_export.py
zerver/views/auth.py
zerver/views/development/email_log.py
zerver/views/invite.py
zerver/views/registration.py

Part of #18777, a follow-up for #19376.

backend: Add None-checks with assertions and if-elses.

---

docs/production/authentication-methods.md
zproject/prod_settings_template.py

Requested in https://github.com/zulip/zulip/pull/19276#issuecomment-883903078

Advertise auto_signup OIDC setting in ReadTheDocs

---

templates/zerver/developer-community.html
templates/zerver/developer-community.md

Add join links (buttons) to the Zulip dev community page.
manual

portico: Add join links to the Zulip dev community page.

---

templates/zerver/help/resolve-a-topic.md

Cleanup pass on user docs for **Resolve topic**.
Manual

Resolve topic user docs edit pass

---

static/js/portico/help.js
templates/zerver/portico-header.html

help: Fix recently introduced sidebar and header bugs.

---

templates/zerver/help/include/rest-endpoints.md
zerver/openapi/python_examples.py
zerver/openapi/zulip.yaml
zerver/tests/test_openapi.py
zerver/views/streams.py

openapi: Document delete-topic endpoint.

---

templates/zerver/help/include/rest-endpoints.md
zerver/openapi/zulip.yaml
zerver/tests/test_openapi.py
zerver/views/streams.py

openapi: Document get-subscribers endpoint.

---

templates/zerver/help/include/sidebar_index.md
templates/zerver/help/message-a-stream-by-email.md
templates/zerver/help/using-zulip-via-email.md

Added workflow instructions for using Zulip via email.
Manual testing.

user docs: Add workflow instructions for using Zulip via email.

---

docs/documentation/api.md

Recently, the need for individual Markdown templates for
every endpoint's OpenAPI page was removed, as they are now
auto-generated from OpenAPI data. Further, as a part of this
migration, several new fields and Markdown extensions were added.
This commit updates the documentation to reflect the changes that
have occured as a result of the migration.

docs: Document the new APIDocs template system.

---

analytics/lib/counts.py
analytics/management/commands/populate_analytics_db.py
analytics/tests/test_support_views.py
analytics/urls.py
analytics/views/activity_common.py
analytics/views/installation_activity.py
analytics/views/realm_activity.py
analytics/views/stats.py
zerver/decorator.py
zerver/lib/actions.py
zerver/middleware.py
zerver/tests/test_decorators.py
zerver/views/auth.py
zerver/views/streams.py
zilencer/management/commands/populate_db.py

Fix type annotations for miscellaneous cases.

---

frontend_tests/node_tests/activity.js
frontend_tests/node_tests/buddy_data.js
frontend_tests/node_tests/dispatch.js
frontend_tests/node_tests/lib/events.js
frontend_tests/node_tests/popovers.js
frontend_tests/node_tests/user_status.js
frontend_tests/puppeteer_tests/user-status.ts
static/js/buddy_data.js
static/js/emoji_picker.js
static/js/popovers.js
static/js/server_events_dispatch.js
static/js/user_status.js
static/js/user_status_ui.js
static/styles/night_mode.css
static/styles/popovers.css
static/styles/right_sidebar.css
static/styles/user_status.css
static/templates/set_status_overlay.hbs
static/templates/status_emoji_selector.hbs
static/templates/user_info_popover_content.hbs
static/templates/user_presence_row.hbs

Completing the work of #16711.
TODO:
- ~Split the commits.~
- ~Add puppeteer test.~
- ~Add `YashRE42` as a co-author.~
Test by running `tools/test-all`.
https://user-images.githubusercontent.com/63820270/123843614-bba86e00-d92f-11eb-9a73-a8ba58bf3a9c.mov

user_status: Show emoji for common statuses

---

templates/zerver/for-research.html

portico: Fix copy-paste bug on /for/research.

---

templates/zerver/for-research.html

The image is aligned on left but should be on right.

for-research: Fix incorrectly aligned image.

---

templates/zerver/help/include/rest-endpoints.md
zerver/openapi/python_examples.py
zerver/openapi/zulip.yaml
zerver/tests/test_openapi.py

openapi: Document update-self-status documentation.

---

zerver/tests/test_create_video_call.py
zerver/views/video_calls.py

https://marketplace.zoom.us/docs/guides/stay-up-to-date/announcements#data-compliance
**Testing plan:** Not tested.

video_calls: Remove call to deprecated Zoom Data Compliance API

---

frontend_tests/puppeteer_tests/user-status.ts

As the right sidebar re-renders many times, often the
element puppeteer selected becomes stale, to avoid this
issue we are using javascript to click on the element.
This PR also ensures that the set user status modal
is completely open before we start clicking.
https://github.com/Riken-Shah/zulip/runs/3198877508

puppeteer: Fix the element becoming stale.

---

templates/zerver/api/changelog.md
templates/zerver/help/include/rest-endpoints.md
version.py
zerver/lib/actions.py
zerver/lib/drafts.py
zerver/lib/events.py
zerver/models.py
zerver/openapi/zulip.yaml
zerver/tests/test_drafts.py
zerver/tests/test_event_system.py
zerver/tests/test_events.py
zerver/tests/test_home.py
zerver/tests/test_openapi.py
zerver/tests/test_settings.py
zerver/views/user_settings.py
zilencer/management/commands/populate_db.py
zproject/default_settings.py
zproject/urls.py

Check out: https://github.com/zulip/zulip/pull/15880 for more info.

Re: Add an API for Syncing Drafts Across the Zulip Server

---

pyproject.toml
requirements/dev.txt
requirements/mypy.in
requirements/mypy.txt
tools/lib/provision_inner.py
version.py
zerver/lib/markdown/fenced_code.py
zerver/lib/queue.py
zerver/tests/test_queue.py

**Testing plan:** Sent some messages to myself.

mypy: Add pika-stubs, types-Pygments

---

.github/workflows/codeql-analysis.yml

As per github/codeql-action#297.
Context: https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/CodeQL/near/1243177

ci: Run CodeQL on merge commit

---

templates/zerver/for-education.html

Clarify education pricing special cases.
manual

portico: Add footnotes regarding /for/education pricing.

---

zerver/data_import/slack.py

Slack bot emails generated by us can be duplicate for two bots.
If such a case occur, append a counter to the email to make it
unique.
For maintaining the counter of duplicate emails and the final
email assigned to each bot, a class-based approach is used with
static variables and static (class) methods. This keeps all the
data related to slack bot emails at the same place and easily
accessible from anywhere inside the module (without defining any
class object and passing it around).
Fixes: #16793

data_import: Make slack bot emails unique.

---

zerver/lib/generate_test_data.py

Populate db - generate resolved topics.

---

puppet/zulip_ops/files/supervisor/conf.d/prometheus_node_exporter.conf
puppet/zulip_ops/manifests/prometheus/node.pp

**Testing plan:** Test-deployed on staging.

Monitor supervisord with prometheus

---

static/styles/portico/landing_page.css
templates/zerver/for-companies.html
templates/zerver/for-education.html
templates/zerver/for-events.html

Reported in https://chat.zulip.org/#narrow/stream/2-general/topic/new.20landing.20page.20for.20companies and https://chat.zulip.org/#narrow/stream/107-kandra/topic/.2Ffor.2Fcompanies.20.2319473

For companies minor bug fixes.

---

templates/analytics/realm_details.html
templates/analytics/support.html
tools/webpack.assets.json

support: Don't include app_components css in support page

---

zerver/lib/markdown/__init__.py

This way we can stop reading as soon as we get to the body. Also, send an `Accept` header, check that the request was actually successful, use `lxml.etree.iterparse` instead of a broken hand-rolled state machine, and support XHTML, all for negative 28 lines of code.
**Testing plan:** Ran `fetch_open_graph_image("https://opengraph.xyz")`.

markdown: Stream and parse incrementally in fetch_open_graph_image

---

zerver/lib/mention.py

**Testing plan:** Verified that this still uses equivalent SQL queries:
```pycon
In [1]: zulip_realm = get_realm("zulip")
In [2]: import logging; logging.getLogger('django.db.backends').setLevel(logging.DEBUG)
In [3]: d = MentionData(zulip_realm.id, "@*hamletcharacters* @*p-users*")
2021-08-05 01:53:48.382 DEBG [django.db.backends] (0.001) SELECT "zerver_usergroup"."id", "zerver_usergroup"."name", "zerver_usergroup"."realm_id", "zerver_usergroup"."description" FROM "zerver_usergroup" WHERE ("zerver_usergroup"."name" IN ('p-users', 'hamletcharacters') AND "zerver_usergroup"."realm_id" = 2); args=('p-users', 'hamletcharacters', 2)
2021-08-05 01:53:48.385 DEBG [django.db.backends] (0.000) SELECT "zerver_usergroupmembership"."id", "zerver_usergroupmembership"."user_group_id", …
```

mention: Simplify init_user_group_data using prefetch_related

---

static/js/portico/header.js
static/js/portico/landing-page.js
static/styles/portico/landing_page.css

@timabbott @alya @andersk FYI :)
@timabbott: You may not want to merge the second commit just yet. The commit description explains the bug that this "fix" introduces.

landing-page: Fix bugs in top-level navigation.

---

static/js/stream_edit.js
static/styles/subscriptions.css
static/templates/stream_settings/stream_settings.hbs

Clean up personal stream settings.

---

analytics/tests/test_support_views.py
analytics/views/support.py
corporate/views/billing_page.py
corporate/views/upgrade.py
templates/analytics/realm_details.html
zerver/lib/validator.py
zerver/views/auth.py
zerver/views/message_send.py
zerver/views/registration.py
zerver/webhooks/alertmanager/view.py

https://github.com/zulip/zulip/pull/19381#discussion_r676968979
This PR is for refactoring existing view functions to use `REQ` with `has_request_variables` decorator.
It has been tested with existing automated tests.

Refactor view functions with `has_request_variables` decorator.

---

analytics/views/support.py

This is a followup for #19432 that fixes a remaining issue of the
original PR.

support: Remove `is True` in comparisons.

---

zerver/openapi/openapi.py
zerver/openapi/zulip.yaml

apidocs: Remove automatically added : at end of response.

---

analytics/lib/counts.py
corporate/lib/stripe.py
zerver/lib/actions.py
zerver/lib/cache_helpers.py
zerver/lib/test_classes.py
zerver/lib/test_helpers.py
zerver/lib/upload.py
zerver/middleware.py
zerver/tests/test_bots.py
zerver/tests/test_logging_handlers.py
zerver/tests/test_openapi.py
zerver/tests/test_upload.py
zproject/dev_urls.py

Django stubs 

---

static/styles/portico/portico_signin.css
templates/zerver/register.html
zerver/forms.py
zerver/lib/actions.py
zerver/lib/create_user.py
zerver/lib/test_classes.py
zerver/tests/test_signup.py
zerver/views/registration.py

We should ask the user for consent before subscribing them to
marketing emails. The default should be for them to be unsubscribed.
@timabbott @alya FYI :)

marketing_emails: Ask for user's consent at sign-up.

---

templates/zerver/integrations/git.md
templates/zerver/integrations/mercurial.md
templates/zerver/integrations/openshift.md

https://github.com/zulip/python-zulip-api/commit/53e59c8c09fa13754273fd04682a23be76f80709

integrations: Document default branch name updates

---

templates/zerver/for/tum-case-study.md

See https://chat.zulip.org/#narrow/stream/2-general/topic/Zulip.20for.20Education.20launch/near/1249801.
tested manually

portico: Add link to CZO thread to TUM case study.

---

tools/fetch-contributor-data
zerver/lib/github.py
zerver/lib/markdown/__init__.py
zerver/lib/outgoing_http.py
zerver/lib/remote_server.py
zerver/lib/url_preview/oembed.py
zerver/lib/url_preview/preview.py
zerver/management/commands/register_server.py
zerver/tests/test_link_embed.py
zerver/tests/test_outgoing_http.py
zerver/views/video_calls.py

Use OutgoingSession more consistently.

Use outgoing_http session in more places

---

zerver/lib/import_realm.py
zerver/lib/upload.py

This is a new reimplementation of #19478.

import_realm: Adapt message upload file relative path depending on whether the backend is local or S3.

---

templates/zerver/development/dev_login.html
zerver/lib/actions.py
zerver/tests/test_signup.py
zproject/default_settings.py

This PR addresses some comments Tim left on one of my earlier commits, see [here](https://github.com/eeshangarg/zulip/commit/96d80cce3987391dbb962d2d6b69dcff5f6634c9#commitcomment-55190926).
@timabbott FYI :)

demo_orgs: Address follow-up comments from #19568.

---

zerver/lib/push_notifications.py
zerver/tests/test_push_notifications.py

aioapns already has a [retry loop](https://github.com/Fatal1ty/aioapns/blob/v2.0.2/aioapns/connection.py#L376). By default it retries forever on `ConnectionError` and `ConnectionClosed`, so our own retry loop would never be reached. Remove our retry loop, and configure aioapns to retry `APNS_MAX_RETRIES` times on `ConnectionError` like the previous version did. It still retries forever on `ConnectionClosed`; that’s not configurable but probably fine.
**Testing plan**: Not tested live.

push_notifications: Remove redundant APNs retry loop

---

static/styles/rendered_markdown.css

https://github.com/zulip/zulip/issues/19359
Development environment 5.0-dev+git, Ubuntu

minor: Refactor CSS for markdown headings.

---

zerver/lib/markdown/__init__.py

Ideally, we'd generate sample URI fixtures for each schemes?

Whitelist all of HTML spec safelisted schemes.

---

static/js/settings.js
static/js/settings_config.ts
static/js/settings_notifications.js
static/templates/settings/notification_settings.hbs

Complete custom email notification batching period feature.

---

docs/conf.py
docs/production/install.md
docs/production/upgrade-or-modify.md

Fixes #19695.
@timabbott, @alya: FYI :)

docs: Indicate latest Zulip version in installation and upgrade docs.

---

frontend_tests/node_tests/navbar_alerts.js
static/js/navbar_alerts.js
static/templates/navbar_alerts/demo_organization_deadline.hbs
templates/zerver/emails/followup_day1.source.html
templates/zerver/emails/followup_day1.txt
zerver/lib/email_notifications.py
zerver/lib/onboarding.py
zerver/lib/test_classes.py
zerver/tests/test_email_notifications.py
zerver/tests/test_signup.py

demo_orgs: Add support for creating temporary demo realms.

---

docs/conf.py
docs/production/install.md
docs/production/upgrade-or-modify.md
docs/subsystems/release-checklist.md
tools/oneclickapps/README.md

Backport of
* 7d7d727865ec1e7702e00e8c6a7e4b2a90f34659 (part of #19625)
* #19703

[4.x] docs: Indicate latest Zulip version in installation and upgrade docs

---

static/js/settings_config.ts
static/templates/settings/notification_settings.hbs

Restructure Personal settings > notifications section.

---

Vagrantfile

Vagrant 2.2.6 is the earliest version with the Docker usability test fix, and is also conveniently the version in the Ubuntu 20.04 repository.  Users with older versions will get a friendly error message from `Vagrant.require_version` (and can install an updated Vagrant from upstream).
**Testing plan:** Ran `vagrant up` with Vagrant 1.8.1 from Ubuntu 16.04:
```console
$ vagrant up
This Vagrant environment has specified that it requires the Vagrant
version to satisfy the following version requirements:
>= 2.2.6
You are running Vagrant 1.8.1, which does not satisfy
these requirements. Please change your Vagrant version or update
the Vagrantfile to allow this Vagrant version. However, be warned
that if the Vagrantfile has specified another version, it probably has
good reason to do so, and …
```

Vagrantfile: Remove workarounds for ancient Vagrant bugs

---

zerver/lib/email_notifications.py
zerver/lib/push_notifications.py
zerver/tests/fixtures/markdown_test_cases.json
zerver/tests/test_email_notifications.py

**Testing plan:** New and existing tests.
Ref #19559.

More fixes for empty rendered content

---

static/templates/settings/notification_settings.hbs
templates/zerver/help/configure-message-notification-emails.md

user docs: Document message notification email custom batching.

---

zerver/tests/test_signup.py

#7564 
Ran testing and linting.

refactor some signup tests

---

static/styles/portico/markdown.css
templates/zerver/help/finding-a-topic-to-read.md
templates/zerver/help/format-your-message-using-markdown.md
templates/zerver/help/getting-started-with-zulip.md
templates/zerver/help/include/compose-and-send-message.md
templates/zerver/help/include/how-to-start-a-new-topic.md
templates/zerver/help/include/left-sidebar-topics.md
templates/zerver/help/include/messaging-tips.md
templates/zerver/help/include/reading-pms.md
templates/zerver/help/include/reading-topics.md
templates/zerver/help/include/recent-topics.md
templates/zerver/help/include/replying-to-messages.md
templates/zerver/help/include/set-up-your-account.md
templates/zerver/help/include/sidebar_index.md
templates/zerver/help/include/starting-a-new-private-thread.md
templates/zerver/help/include/streams-and-topics.md
templates/zerver/help/include/when-to-start-a-new-topic.md
templates/zerver/help/messaging-tips.md
templates/zerver/help/open-the-compose-box.md
templates/zerver/help/reading-pms.md
templates/zerver/help/reading-strategies.md
templates/zerver/help/reading-topics.md
templates/zerver/help/recent-topics.md
templates/zerver/help/replying-to-messages.md
templates/zerver/help/review-your-settings.md
templates/zerver/help/set-up-your-account.md
templates/zerver/help/starting-a-new-private-thread.md
templates/zerver/help/starting-a-new-topic.md
templates/zerver/help/streams-and-topics.md
zerver/lib/markdown/tabbed_sections.py

user docs: Add a bundle of "getting stated" user docs.

---

templates/zerver/help/include/sidebar_index.md
templates/zerver/help/using-zulip-for-a-class.md

This does not include instructions for setting up your Zulip organization. That will be done as a follow-on to updating the general guide on setting up your org.
manual

Guide on using Zulip for a class

---

zerver/lib/actions.py
zerver/lib/types.py
zerver/lib/users.py
zerver/models.py
zerver/tests/test_custom_profile_data.py
zerver/tests/test_users.py
zerver/views/custom_profile_fields.py
zerver/views/users.py
zproject/backends.py

A few adjustment to the code, inspired by a dive into custom profile fields I've been doing as part of trying to finish #18642 Explanations of individual changes in the commit messages.

Minor custom profile fields code cleanups

---

.eslintrc.json
frontend_tests/puppeteer_lib/common.ts
frontend_tests/puppeteer_tests/navigation.ts
frontend_tests/puppeteer_tests/realm-creation.ts
frontend_tests/puppeteer_tests/subscriptions.ts
static/js/blueslip.ts
static/js/i18n.ts
static/js/loading.ts
static/js/password_quality.ts
static/js/spoilers.ts
static/js/sub_store.ts
static/js/timerender.ts
static/js/user_groups.ts

We already have some TypeScript-ESLint rules that require type checking, so we might as well enable the recommended ones.

Enable @typescript-eslint/recommended-requiring-type-checking

---

zerver/middleware.py
zerver/tests/test_decorators.py

Requests to the root subdomain weren't getting request_notes.realm set
even if a realm exists on the root subdomain - which is actually a
common scenario, because simply having one organization, on the root
subdomain, is the simplest and common way for self-hosted deployments.

request_notes: Set the realm appropriately for the root subdomain.

---

zerver/lib/actions.py
zerver/lib/message.py
zerver/lib/streams.py
zerver/lib/test_classes.py
zerver/models.py
zerver/tests/test_message_edit.py
zerver/tornado/django_api.py
zerver/views/message_edit.py
zproject/urls.py

The last commit is extracted from #18532, with some added refactoring to make it cleaner and have a clear, strict security check.

Add "View source" support for spectators.

---

static/styles/compose.css

**PR for issue #17842: UX improvement: display "user not found" for invalid user search query #17842**

UX improvement: display "user not found" 

---

static/styles/portico/portico.css
templates/zerver/for-open-source.html
templates/zerver/for/communities.md

Pushing for my convenience only; do not review.

portico: Revamp /for/open-source.

---

static/styles/rendered_markdown.css

rendered_markdown: Improve headings.

---

docs/production/upgrade-or-modify.md

docs: Document upgrade steps from buster to bullseye.

---

zerver/openapi/zulip.yaml

main is failing, this should fix it.

openapi: Fix broken link to documentation.

---

zerver/tests/test_events.py

We send three events when changing delivery email of a user - one for updating the `delivery_email` field
of user, one for avatar url change, and one for changing email field if `email_address_visibility` is set to `EMAIL_ADDRESS_VISIBILITY_EVERYONE`.
There is already a test for delivery_email and avatar_url event with the visibility setting set to `EMAIL_ADDRESS_VISIBILITY_ADMINS_ONLY`, but no test for verifying the email update event sent
when email address is public, so this PR adds a test for checking the schema of event for updating email field.

test_events: Test the email event when changing delivery_email.

---

static/js/message_list_view.js
static/templates/recipient_row.hbs

Fixes: https://github.com/zulip/zulip/issues/19880 
Tested manually

fix: Hide checkmark if user does not have permission to edit topic

---

static/styles/modal.css

modal: Remove focus ring from submit button.

---

templates/zerver/help/include/rest-endpoints.md
zerver/openapi/curl_param_value_generators.py
zerver/openapi/python_examples.py
zerver/openapi/zulip.yaml
zerver/tests/test_openapi.py

openapi: Document remove-attachment endpoint.

---

package.json
version.py
yarn.lock

https://github.com/webpack/webpack/issues/14514

dependencies: Downgrade webpack to avoid caching bug

---

zerver/lib/push_notifications.py

push_notifications: Truncate overly large remove events.

---

.vscode/extensions.json

Add Remote Development Extension
.ms-vscode-remote.vscode-remote-extensionpack

update .vscode: Add remote development extension.

---

zerver/forms.py
zerver/lib/email_mirror.py
zerver/tests/test_external.py
zerver/tests/test_signup.py
zerver/views/auth.py
zerver/views/registration.py
zerver/views/user_settings.py
zproject/computed_settings.py
zproject/test_extra_settings.py

**Testing plan:** Added tests.

Merge spam sources

---

.github/workflows/production-suite.yml
tools/ci/Dockerfile

These were missed in the doc updates in d78723b6e876, which were for
behavior changes in 16067bc4fc5c.

ci: Update outdated comments to generated Dockerfiles.

---

frontend_tests/node_tests/event_status.js

See also
* #16257
* #20180
Cc @eeshangarg

frontend_tests: Skip broken event_status test

---

templates/zerver/for-companies.html
templates/zerver/for-events.html
templates/zerver/for-open-source.html
templates/zerver/for-research.html
templates/zerver/for/ucsd-case-study.md
templates/zerver/help/format-your-message-using-markdown.md
templates/zerver/help/include/messaging-tips.md
templates/zerver/help/using-zulip-for-a-class.md

terminology: Use the term "global time" to refer to time widget.

---

templates/zerver/footer.html
templates/zerver/for-open-source.html
templates/zerver/for-research.html
templates/zerver/for/lean-case-study.md
templates/zerver/landing_nav.html
templates/zerver/lean-case-study.html
zerver/tests/test_docs.py
zproject/urls.py

portico: Add Lean case study.

---

frontend_tests/node_tests/message_events.js
static/js/message_edit_history.js
static/js/message_events.js
static/templates/message_history_modal.hbs

message_edit_history: Migrate modal to dialog_widget.

---

static/js/stream_edit.js
static/styles/subscriptions.css
static/templates/stream_settings/change_stream_info_modal.hbs

change_stream_info_modal: Migrate modal to dialog_widget.

---

frontend_tests/puppeteer_tests/settings.ts
static/js/settings_bots.js
static/styles/settings.css
static/templates/settings/edit_bot.hbs
static/templates/settings_overlay.hbs

edit_bot: Migrate modal to dialog_widget.

---

docs/production/deployment.md
docs/production/postgresql.md
docs/production/upgrade-or-modify.md
puppet/zulip/templates/postgresql/14/postgresql.conf.template.erb
scripts/lib/install
scripts/setup/upgrade-postgresql
tools/lib/provision.py

Test PostgreSQL 14.  Wey may want to add support without flipping the default to 14, so the last commit maybe should be skipped for now.
**Testing plan:** Looking at the upgrade test.

PostgreSQL 14 support

---

static/js/message_edit.js
static/js/stream_popover.js
static/styles/popovers.css
static/templates/move_topic_to_stream.hbs

move_topic_to_stream: Migrate modal to dialog_widget.

---

static/js/poll_widget.js
static/shared/js/poll_data.js

fixes: #20164
Visual Testing by creating multiple polls containing different options. The video below shows the behaviour.
https://user-images.githubusercontent.com/88431809/140957924-7f725894-63f0-4492-8e4d-1a8597a3d49b.mp4

poll: Handle duplicate poll options.

---

static/js/user_profile.js
static/styles/popovers.css
static/templates/user_profile_modal.hbs

user_profile_modal: Migrate modal to Micromodal.

---

zerver/lib/soft_deactivation.py

Race conditions in stream unsubscription may lead to multiple
back-to-back SUBSCRIPTION_DEACTIVATED RealmAuditLog entries for the
same stream.  The current logic constructs duplicate UserMessage
entries for such, which then later fail to insert.
Keep a set of message-ids that have been prep'd to be inserted, so
that we don't duplicate them if there is a duplicated
SUBSCRIPTION_DEACTIVATED row.  This also renames the `message` local
variable, which otherwise overrode the `message` argument of a
different type.

soft_deactivate: Handle multiple SUBSCRIPTION_DEACTIVATEDs.

---

static/js/click_handlers.js
static/js/recent_topics_ui.js

When user is scrolling, we simply keep the center element in
focus.
When user is using hotkeys, we keep the focused element in
center.
This gives a nice navigation experience for both the views.

recent_topics: Separate behaviour for scrolling and hotkeys.

---

frontend_tests/node_tests/drafts.js
frontend_tests/puppeteer_tests/drafts.ts
static/js/drafts.js
static/styles/left_sidebar.css
static/templates/compose.hbs
static/templates/draft_table_body.hbs
static/templates/left_sidebar.hbs

https://chat.zulip.org/#narrow/stream/101-design/topic/drafts.20in.20sidebar
**Testing plan:** Manually tested

Drafts in sidebar

---

templates/zerver/for/lean-case-study.md

portico: Link back to /for/X pages from Lean case study.

---

static/templates/settings/organization_permissions_admin.hbs

**Testing plan:** Ran dev server, confirmed link appears and works

settings: Link to help on restrict wildcard mentions

---

zerver/tests/test_email_change.py
zerver/views/user_settings.py

**Testing plan:** Added a test.

email_change: Show deactivated page if realm is now deactivated.

---

static/styles/modal.css

modal: Make the submit button look disabled when disabled.

---

docs/development/overview.md

This will possibly direct more users towards WSL setup on Windows.

docs: Separate recommend and vagrant setup sections for dev setup.

---

static/js/todo_widget.js
static/templates/widgets/todo_widget.hbs
static/templates/widgets/todo_widget_tasks.hbs

todo_widget: Fix /todo checkboxes to match style used in menus.

---

templates/corporate/jobs.html

The "Globally distributed" section is new.

/jobs page: Clarify that openings are remote-friendly.

---

frontend_tests/puppeteer_tests/settings.ts
static/js/settings.js
static/js/settings_display.js
static/styles/settings.css
static/templates/default_language_modal.hbs
static/templates/settings/display_settings.hbs

default_language: Migrate modal to dialog_widget.

---

docs/production/requirements.md

docs: Reccommend docker for installing alongside other services.

---

docs/contributing/code-style.md
docs/contributing/gsoc-ideas.md
docs/contributing/summer-with-zulip.md
docs/development/setup-advanced.md
docs/production/requirements.md
docs/production/settings.md
docs/production/upgrade-or-modify.md
docs/subsystems/performance.md
docs/tutorials/new-feature-tutorial.md
templates/zerver/api/client-libraries.md
templates/zerver/api/running-bots.md
templates/zerver/for/communities.md
templates/zerver/help/contact-support.md

links: Replace chat.zulip.org to /developer-community.

---

static/templates/settings/data_exports_admin.hbs
templates/zerver/help/export-your-organization.md

[CZO discussion](https://chat.zulip.org/#narrow/stream/2-general/topic/cancel.20an.20export/near/1284363)
manual

help and org settings: Rename "public export" to "export of public data".

---

frontend_tests/node_tests/composebox_typeahead.js
static/js/composebox_typeahead.js
zerver/lib/zcommand.py
zerver/tests/test_zcommand.py

Change description of `/light` command in typeahed and replace `mode` with `theme` in the popup.

---

static/styles/portico/portico_signin.css
templates/zerver/realm_redirect.html
templates/zerver/reset.html

portico: Center align moving label text in input.

---

frontend_tests/node_tests/message_list.js
frontend_tests/node_tests/peer_data.js
frontend_tests/node_tests/recent_topics.js
frontend_tests/node_tests/stream_data.js
frontend_tests/node_tests/stream_events.js
frontend_tests/node_tests/unread.js
static/js/compose_actions.js
static/js/compose_validate.js
static/js/message_list.js
static/js/message_list_view.js
static/js/narrow_banner.js
static/js/stream_bar.js
static/js/stream_data.js
static/js/stream_list.js
static/js/stream_settings_ui.js
static/js/unread.js
static/styles/compose.css
static/styles/zulip.css
static/templates/compose.hbs
static/templates/recipient_row.hbs

Indicate whether streams are web-public like we do for private streams

---

frontend_tests/node_tests/composebox_typeahead.js
frontend_tests/puppeteer_tests/drafts.ts
static/js/compose.js
static/js/composebox_typeahead.js
static/js/giphy.js
static/js/message_edit.js
static/styles/app_components.css
static/styles/compose.css
static/styles/dark_theme.css
static/styles/left_sidebar.css
static/styles/zulip.css
static/templates/compose.hbs
static/templates/compose_control_buttons.hbs

before:
after:
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/compose.20box.20formatting.20button

Refactor compose bottom and add formatting buttons.

---

templates/zerver/api/incoming-webhooks-overview.md

remove deprecated stash from docs

---

frontend_tests/puppeteer_tests/settings.ts
static/js/settings.js
static/js/settings_account.js
static/styles/modal.css
static/styles/settings.css
static/styles/zulip.css
static/templates/dialog_change_password.hbs
static/templates/settings/account_settings.hbs
tools/linter_lib/custom_check.py

change_password: Migrate modal to dialog_widget.

---

frontend_tests/puppeteer_tests/settings.ts
static/js/settings_account.js
static/styles/settings.css
static/templates/settings/api_key_modal.hbs

api_key_modal: Migrate modal to Micromodal.

---

CONTRIBUTING.md
tools/linter_lib/custom_check.py

dev docs: Improve contributor guide.

---

static/js/settings_data.ts
zerver/tests/test_message_edit.py

Follow-up tasks mentioned in #20340.
Will open a separate PR for live-update work.

Refactor web-public streams related code.

---

static/styles/subscriptions.css

stream_privacy_modal: Fix vertical alignment of radio inputs.

---

CONTRIBUTING.md

dev docs: Address feedback on Contributing guide.

---

.github/workflows/production-suite.yml
docs/subsystems/release-checklist.md
tools/ci/build-docker-images

This is an updated version of #19446.
**Testing plan:** We'll see how it fares!

Test upgrade from 4.7

---

static/js/click_handlers.js
static/js/spectators.js
static/styles/zulip.css
static/templates/login_to_access.hbs

login_to_access_modal: Migrate modal to Micromodal.

---

templates/corporate/jobs.html

jobs: Update designer job description.

---

tools/lib/capitalization.py
zerver/lib/onboarding.py
zerver/tests/test_tutorial.py

Fixes #19900.
Manually tested, no changes in tests.
This is how the bot works now:
Responses to user messages:
1. Apps (Tested for `Apps`, `Application`, and `<random text> app`:
2. Edit Profile (Tested for `edit profile`, `profile`, and `Profile`):

onboarding: Make Welcome Bot more interactive.

---

templates/zerver/help/index.md
zerver/tests/test_middleware.py

help center: Remove outdated intro from index page.

---

static/templates/left_sidebar.hbs

#20284 Updated tooltips in left_sidebar

---

static/js/dialog_widget.js
static/js/message_edit.js
static/js/stream_popover.js
static/styles/popovers.css
static/templates/move_topic_to_stream.hbs

---
For df0c0f82aff0c6b3278694e052d63e5d334789a7
**Before**
**After**
**Continuously clicking submit button**

move_topic_modal: Use `dialog_error` to display error.

---

static/js/stats/stats.js

https://github.com/zulip/zulip/issues/20416
I used inspect and console.log with different locales 

Replace hardcoded regex with toLocaleString #20416

---

frontend_tests/node_tests/people.js
frontend_tests/node_tests/popovers.js
static/js/people.js
static/js/popovers.js
static/js/user_profile.js

Created new function for fetching medium avatar URLs

---

frontend_tests/node_tests/compose.js
frontend_tests/node_tests/compose_error.js
frontend_tests/node_tests/compose_validate.js
frontend_tests/node_tests/compose_video.js
frontend_tests/node_tests/composebox_typeahead.js
frontend_tests/node_tests/dispatch.js
frontend_tests/puppeteer_lib/common.ts
static/js/click_handlers.js
static/js/compose.js
static/js/compose_error.ts
static/js/compose_ui.js
static/js/compose_validate.js
static/js/composebox_typeahead.js
static/js/emoji_picker.js
static/js/giphy.js
static/js/popover_menus.js
static/js/server_events_dispatch.js
static/styles/app_components.css
static/styles/compose.css
static/styles/dark_theme.css
static/styles/informational_overlays.css
static/styles/zulip.css
static/templates/compose.hbs
static/templates/compose_control_buttons.hbs
static/templates/compose_control_buttons_in_popover.hbs
static/templates/compose_control_buttons_popover.hbs
tools/lib/capitalization.py

Rearrange compose bottom elements.

---

frontend_tests/node_tests/compose.js
frontend_tests/node_tests/compose_video.js
static/js/compose.js
static/js/compose_ui.js
static/js/emoji_picker.js
static/js/giphy.js
static/styles/compose.css

Fix bugs reported in https://github.com/zulip/zulip/pull/20396#issuecomment-985077362 and https://chat.zulip.org/#narrow/stream/101-design/topic/compose.20box.20formatting.20button

Fix remaining bugs after compose box refactor.

---

static/js/recent_topics_ui.js

The bug fix for RT search, also needs to be applied to other
elements.
Fixes #19458.

recent_topics: Extend persistent focus bug to all RT elements.

---

puppet/zulip/manifests/postgresql_backups.pp

Upgrade wal-g to 1.1.1, cleanup old binaries.

Upgrade wal-g to 1.1.1

---

templates/corporate/jobs.html

Incorporate feedback on jobs page

---

static/templates/recipient_row.hbs
static/templates/stream_settings/stream_members.hbs
templates/corporate/zephyr-mirror.html
templates/corporate/zephyr.html
templates/zerver/app/index.html
tools/lib/template_parser.py

This also fixes a bug reported by @alya

templates: Fix some whitespace issues.

---

static/styles/dark_theme.css
static/styles/modal.css

discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/modal.20buttons.20in.20dark.20theme

Fix modal button colors in dark theme.

---

puppet/zulip/manifests/camo.pp
puppet/zulip/manifests/golang.pp
puppet/zulip/manifests/postgresql_backups.pp
puppet/zulip_ops/manifests/profile/grafana.pp
puppet/zulip_ops/manifests/profile/prometheus_server.pp
puppet/zulip_ops/manifests/prometheus/node.pp

puppet: Do not assume amd64 architecture.

---

zerver/lib/export.py
zerver/lib/import_realm.py
zerver/lib/test_classes.py
zerver/tests/test_import_export.py
zerver/tests/test_mattermost_importer.py
zerver/tests/test_rocketchat_importer.py

exports: Add MutedUser and UserStatus

---

zerver/tests/test_import_export.py

Clean up import tests.

---

static/styles/dark_theme.css

This is a part of #20289.
@timabbott FYI
@alya I chose the topic as `stream settings`, not sure if it should be more specific or whether all notifications should be grouped under the same topic? We also want to make sure that the topics are unique enough so that they don't collide with topics the user may already have. Thoughts?

streams: Add notifications for message retention policy updates.

---

puppet/zulip_ops/files/supervisor/conf.d/grafana.conf
puppet/zulip_ops/manifests/profile/grafana.pp
puppet/zulip_ops/templates/supervisor/conf.d/grafana.conf.erb

Upgrade internal Grafana to 8.3.1
**Testing plan:** Deployed.

Grafana 8.3.1

---

scripts/lib/upgrade-zulip-stage-2

Not yet tested in production; I plan to do so with chat.zulip.org shortly.

Improve handling of memory issues when upgrading from Git

---

tools/test-all

I accidentally checked in a change where I commented
out the test.

test-all: Call documentation tests again.

---

templates/corporate/jobs.html

portico: Update designer job description.

---

zerver/webhooks/ifttt/fixtures/invalid_payload_with_dict_content.json
zerver/webhooks/ifttt/fixtures/invalid_payload_with_dict_topic.json
zerver/webhooks/ifttt/tests.py
zerver/webhooks/ifttt/view.py

**Testing plan:** Added tests.

ifttt: Ensure topic and body are strings, and not dicts / arrays.

---

zerver/views/video_calls.py
zproject/default_settings.py

video_calls: Drop VIDEO_ZOOM_TESTING_ configurations.

---

docs/production/mobile-push-notifications.md

I didn't build the doc, so be sure to check the CI.

developer docs: Tweak ToS for push notifications wording.

---

zerver/lib/send_email.py
zerver/tests/test_send_email.py

**Testing plan:** Added tests.

Work around 320-character limit on To addresses

---

templates/zerver/emails/custom_email_base.pre.html
zerver/lib/send_email.py
zerver/management/commands/send_custom_email.py
zerver/tests/test_email_notifications.py

**Testing plan:** Local testing and new automated test.

Add support for sending custom emails to self-hoster contacts.

---

zerver/lib/actions.py

- First commit is for `do_create_user`.
- Second commit is for `do_change_user_role`.

Use `transaction.atomic` in `do_create_user` and `do_change_user_role`.

---

frontend_tests/node_tests/people.js
frontend_tests/node_tests/stream_edit.js
static/js/people.js
static/js/stream_edit.js
static/js/stream_settings_containers.js
static/js/stream_ui_updates.js

Upcoming:
* move all the subscriber management stuff to its own module
* make the subscriber-management stuff work for Create Stream as well as editing streams

Clean up stream-edit code.

---

zerver/lib/streams.py

To avoid the window between stream creation and creation of the `Recipient` object, we create the stream in an atomic transaction.
Fixes #20127

production: Create stream in an atomic transaction.

---

docs/overview/changelog.md
zerver/lib/integrations.py
zerver/webhooks/canarytoken/tests.py
zerver/webhooks/canarytoken/view.py
zerver/webhooks/clubhouse/view.py
zerver/webhooks/jotform/doc.md
zerver/webhooks/jotform/tests.py
zerver/webhooks/reviewboard/doc.md
zerver/webhooks/reviewboard/view.py
zerver/webhooks/teamcity/doc.md
zerver/webhooks/teamcity/tests.py
zerver/webhooks/teamcity/view.py
zerver/webhooks/thinkst/doc.md
zerver/webhooks/uptimerobot/doc.md
zerver/webhooks/uptimerobot/tests.py
zerver/webhooks/uptimerobot/view.py
zerver/webhooks/yo/doc.md
zerver/webhooks/yo/tests.py

* ClubHouse → Clubhouse
* JotForm → Jotform
* Thinkst Canarytoken → Thinkst Canarytokens
* MailChimp → Mailchimp
* ReviewBoard → Review Board
* Teamcity → TeamCity
* Uptime Robot → UptimeRobot
* Yo App → Yo

Correct integration names

---

docs/subsystems/release-checklist.md

Doc: fix removed repeated words

---

static/shared/js/fenced_code.js

`default_hander` --> `default_handler`

Fix:Fixed function name

---

puppet/zulip/manifests/camo.pp
puppet/zulip/manifests/common.pp
puppet/zulip/manifests/external_dep.pp
puppet/zulip/manifests/golang.pp
puppet/zulip/manifests/postgresql_backups.pp
puppet/zulip/manifests/smokescreen.pp
puppet/zulip_ops/files/supervisor/conf.d/prometheus.conf
puppet/zulip_ops/manifests/profile/grafana.pp
puppet/zulip_ops/manifests/profile/prometheus_server.pp
puppet/zulip_ops/manifests/prometheus/node.pp
puppet/zulip_ops/templates/supervisor/conf.d/prometheus.conf.template.erb
puppet/zulip_ops/templates/supervisor/conf.d/prometheus_node_exporter.conf.template.erb
tools/setup/bootstrap-awscli.sh

**Testing plan:** Installed a basic aarch64 host (with no postgresql, due to wal-g limitations mentioned in the commits)

Refactor external_deps in puppet, add aarch64 support

---

static/js/composebox_typeahead.js

`const topic_names = stream_topic_history.get_recent_topic_names(stream_id);
return topic_names;
}` 
we are not using `topic names`  further so we can directly return it like this 
`return stream_topic_history.get_recent_topic_names(stream_id);`

Fix:Refractored code and fixed a typo in comment

---

puppet/zulip_ops/manifests/profile/postgresql.pp
scripts/lib/install-yarn

**Testing plan:** Made `/srv` a symlink and ran `install-yarn`.

install-yarn: Use test -ef in case /srv is a symlink

---

templates/zerver/help/add-a-custom-linkifier.md

help: Document that linkifiers use re2.

---

puppet/zulip/manifests/common.pp
tools/setup/bootstrap-awscli.sh

Replaces #19617.
**Testing plan:** Deployed on a test server.

Upgrade external dependency versions

---

scripts/lib/upgrade-zulip-from-git
scripts/lib/upgrade-zulip-stage-2
scripts/lib/zulip_tools.py
scripts/restart-server

Allows calling upgrade-from-git with `--skip-tornado` or `--less-graceful`, which are threaded through to the restard command.
**Testing plan:** Tested an upgrade.

Pass arguments down from upgrade-from-git

---

templates/zerver/register.html
zerver/lib/test_classes.py
zerver/tests/test_signup.py
zerver/views/registration.py

Fixes #20595.
@timabbott @andersk FYI :)

signup: Stop prompting self-hosted customers for marketing emails.

---

scripts/setup/reindex-textual-data

This catches nine functional indexes that the previous query didn’t:
```diff
analytics_fillstate_property_69206ce5_like
analytics_fillstate_property_key
analytics_realmcount_property_end_time_3b60396b_idx
analytics_streamcount_property_realm_id_end_time_155ae930_idx
analytics_usercount_property_realm_id_end_time_591dbec1_idx
auth_group_name_a6ea08ec_like
auth_group_name_key
auth_permission_content_type_id_codename_01ab375a_uniq
confirmation_confirmation_confirmation_key_c1ba29ff
confirmation_confirmation_confirmation_key_c1ba29ff_like
confirmation_confirmation_type_confirmation_key_134e405d_uniq
confirmation_realmcreationkey_creation_key_b134749a
confirmation_realmcreationkey_creation_key_b134749a_like
corporate_customer_stripe_customer_id_b11e19b2_like …
```

reindex-textual-data: Reindex textual functional indexes too

---

SECURITY.md

**Testing plan:** Looked at it on Github.

SECURITY.md: Fix a broken markdown link.

---

static/templates/compose.hbs
static/templates/compose_select_enter_behaviour_popover.hbs

compose: Fix Enter to send switch internationalization

---

README.md

Not tested -- I wasn't sure how to get a preview.

Update README.md description.

---

static/js/settings_users.js
static/templates/settings/admin_bot_form.hbs

org edit_bot_modal: Fix styling issues.

---

zerver/lib/actions.py
zerver/tests/test_events.py

The subscriber list was not updating without a refresh on
reactivating user, because the subscriptions data with the
client was not updated on reactivation.
This commit adds code to send peer_add subscription events
on reactivating the user.
We do not send peer_remove events on deactivating the user,
but the subscriber list is still live-updated because we
have the data of the streams which the deactivated user is
susbcribed to and the clients itself updates the data and UI
on receiving event of deactivation of user, which it is not
possible when reactivating the user.
Fixes #20383.

users: Send peer_add subscription events on reactivating users.

---

zerver/tests/test_push_notifications.py

Fixes `ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>`.

test_push_notifications: Close event loops

---

zilencer/management/commands/profile_request.py

Fixes `RemovedInDjango40Warning: Passing None for the middleware get_response argument is deprecated.` from `LogRequests()`.
**Testing plan:** `./manage.py populate_db -n500; ./manage.py profile_request iago@zulip.com`

profile_request: Use modern Django middleware API

---

frontend_tests/puppeteer_tests/settings.ts

Disable test_invalid_edit_bot_form().

---

static/js/lazy_set.js
static/js/lazy_set.ts

**Testing plan:** Node tests, lint, and checking correct typescript annotations.

ts: Convert lazy_set module to typescript.

---

static/templates/widgets/todo_widget.hbs

https://chat.zulip.org/#narrow/stream/58-translation/topic/Missing.20string.3F

todo_widget: Tag "Task list" heading for translation.

---

docs/contributing/gsoc-ideas.md

developer docs: Update GSoC documentation.

---

templates/zerver/for/lean-case-study.md

Fixing a couple of minor issues, as reported by @rwbarton .
none

portico: Make minor fixes in Lean case study.

---

zerver/lib/markdown/api_arguments_table_generator.py

Adds a check for object in parameter type that will render the details of the object in the parameter description if they are in the object definition in the OpenAPI documentation.
I borrowed some of the code from `api_return_values_table_generator.py` since objects are being rendered in the documentation when they are return values. There is definitely some cleaning to do and I need to test on an object definition that contains another object, but I wanted to get feedback from folks who have worked on the api documentation markdown rendering for the changes made so far.
Fixes #19424.
**Testing plan:** [current diff of API endpoints html](https://pastebin.com/6Lw2e8ZU)

api_documentation: Render object details in parameter description.

---

docs/subsystems/api-release-checklist.md

docs: Update the release checklist for our PyPI packages.

---

docs/production/settings.md

developer docs: Clarify purpose of zulip-announce.

---

docs/contributing/gsoc.md

docs: Fix typos in GSoC guide.

---

static/js/settings_account.js
static/styles/settings.css
static/templates/change_email_modal.hbs
static/templates/settings/account_settings.hbs
static/templates/settings/api_key_modal.hbs

change_email: Migrate modal to dialog_widget.

---

frontend_tests/puppeteer_tests/user-status.ts
static/js/emoji_picker.js
static/js/user_status_ui.js
static/styles/user_status.css
static/templates/set_status_overlay.hbs

user_status: Migrate modal to dialog_widget.

---

zerver/tests/test_upload.py

We have been exclusively on Python 3 for quite some time.

test_upload: Uncomment subTest contexts

---

puppet/zulip/files/nagios_plugins/zulip_postgresql/check_postgresql_replication_lag
puppet/zulip/files/postgresql/pg_backup_and_purge
scripts/lib/check_rabbitmq_queue.py
scripts/lib/hash_reqs.py
scripts/lib/node_cache.py
scripts/lib/puppet_cache.py
scripts/lib/setup_venv.py
scripts/lib/sharding.py
scripts/lib/upgrade-zulip
scripts/lib/upgrade-zulip-stage-2
scripts/lib/zulip_tools.py
scripts/nagios/check-rabbitmq-consumers
scripts/setup/restore-backup
tools/diagnose
tools/i18n/process-mobile-i18n
tools/lib/pretty_print.py
tools/review
tools/test-queue-worker-reload
tools/update-zuliprc-api-field
zerver/lib/mdiff.py
zerver/lib/test_fixtures.py
zerver/lib/tex.py
zerver/logging_handlers.py
zerver/management/commands/compilemessages.py
zerver/openapi/javascript_examples.py
zerver/openapi/test_curl_examples.py
zerver/tests/test_email_mirror.py
zerver/views/report.py

This is supported in Python ≥ 3.7.

python: Replace universal_newlines with text

---

corporate/tests/test_stripe.py
zerver/decorator.py
zerver/lib/string_validation.py
zerver/migrations/0371_invalid_characters_in_topics.py
zerver/tests/test_push_notifications.py

Miscellaneous pyupgrade changes

---

babel.config.js
frontend_tests/zjsunit/mdiff.js
frontend_tests/zjsunit/namespace.js
frontend_tests/zjsunit/zpage_params.js
static/js/message_events.js
static/js/search_suggestion.js
static/js/server_events_dispatch.js
static/js/user_events.js
static/shared/js/emoji.js

https://github.com/tc39/proposal-accessible-object-hasownproperty

js: Shorten Object.prototype.hasOwnProperty.call to Object.hasOwn

---

babel.config.js
frontend_tests/node_tests/narrow_local.js
frontend_tests/zjsunit/mdiff.js
static/js/drafts.js
static/js/emoji_picker.js
static/js/floating_recipient_bar.js
static/js/message_fetch.js
static/js/message_list_data.js
static/js/message_list_view.js
static/js/portico/integrations_dev_panel.js
static/js/search_suggestion.js
static/js/stats/stats.js
static/js/upload.js
static/shared/js/fenced_code.js

https://github.com/tc39/proposal-relative-indexing-method

js: Simplify indexing arrays from the end with Array#at

---

README.md
docs/contributing/gsoc.md
templates/zerver/hello.html
templates/zerver/team.html

Note: I did not check whether we have numbers other than 700 that also need to be updated.
not tested

portico: Update contributor count from 700 to 1000.

---

.github/workflows/production-suite.yml

ci: Cache with the OS name, not the job name

---

static/js/composebox_typeahead.js

Added a placeholder key to the polls slash command object. This is selected and highlighted after being typed ahead in the compose box. For slash commands without placeholder, everything works as before.
Formatting hints can easily be added for other slash commands too, by adding a placeholder key to their object.
Fixes part of #20868
Tested manually for both types of slash commands - with and without placeholder, and also other things like emoji typeaheads to ensure no older functionality was broken. Temporarily added placeholders to other slash commands too, and tested the highlighting always worked as expected, to verify that this system is easily extendible if the need arises in the future for more formatting hints. Also ensured that the highlight worked both on …

compose: Add format hinting for polls.

---

zerver/lib/upload.py
zerver/tests/test_email_mirror.py
zerver/tests/test_message_fetch.py
zerver/tests/test_retention.py
zerver/tests/test_upload.py

https://chat.zulip.org/#narrow/stream/127-integrations/topic/bot.20can't.20download.20email.20attachments

upload: Pass the target realm to create_attachment.

---

zerver/lib/actions.py
zerver/tests/test_subs.py
zerver/tests/test_users.py

This PR may not manage to add transaction.atomic in each one of the functions that need it, but it should at least get us closer to it. More commits may be added over time.

Use transaction.atomic on various do_... functions in actions.py

---

CONTRIBUTING.md

docs: Clarify that only issues tagged "help wanted" should be claimed.

---

frontend_tests/node_tests/compose.js
frontend_tests/node_tests/compose_actions.js
static/js/compose.js
static/js/compose_actions.js
static/js/resize.js
static/styles/compose.css

Fix 2nd and 4th bugs mentioned in #19353.

Fix some compose bugs.

---

templates/corporate/jobs.html

Update the jobs page.
**Testing plan:** As currently deployed.

Changes to the jobs page

---

static/styles/portico/portico_signin.css
templates/corporate/zulipchat_migration_tos.html
templates/zerver/accounts_accept_terms.html
zerver/context_processors.py
zerver/tests/test_home.py
zerver/views/home.py
zproject/default_settings.py
zproject/dev_settings.py

Add even vertical space between elements.

accounts_accept_terms: Make elements looks similar to other pages.

---

static/js/ui_init.js
static/styles/app_components.css
static/styles/dark_theme.css
static/styles/right_sidebar.css
static/templates/right_sidebar.hbs

right_sidebar: Add realm description for spectators.

---

static/js/tippyjs.js
static/templates/compose.hbs

Discussion - https://chat.zulip.org/#narrow/stream/9-issues/topic/compose.20tabbing.20focus

Fix compose top keyboard focus order.

---

zerver/tests/test_message_fetch.py

test_message_fetch: Reorganize web-public tests.

---

templates/zerver/help/include/how-to-invite-users-to-join.md

manual
http://localhost:9991/help/invite-users-to-join:
http://localhost:9991/help/getting-your-organization-started-with-zulip#how-to-invite-users-to-join:

help center: Make it easier to learn that any auth method will work.

---

templates/zerver/for-business.html

portico: Update /for/business page title and tagline.

---

zerver/lib/sqlalchemy_utils.py
zerver/lib/test_runner.py
zerver/tests/test_message_fetch.py
zerver/views/message_fetch.py

**Testing plan:** Tested some narrows in the dev server.

Address SQLAlchemy deprecations

---

docs/overview/architecture-overview.md
docs/testing/manual-testing.md
frontend_tests/node_tests/reactions.js
static/js/click_handlers.js
static/js/compose_ui.js
static/js/message_list_view.js
static/js/message_scroll.js
static/js/reactions.js
static/js/resize.js
static/js/tippyjs.js
static/styles/dark_theme.css
static/styles/reactions.css
static/styles/rendered_markdown.css
static/styles/zulip.css
static/templates/compose.hbs
static/templates/edited_notice.hbs
static/templates/message_reaction.hbs
templates/zerver/help/edit-or-delete-a-message.md

UI-Improvement: Remove the parentheses around notice markers.

---

zerver/tests/test_new_users.py

The previous random strategy for picking 5 emails would result in collisions in 1 out of 10000.35 tests, leading to `psycopg2.errors.UniqueViolation`.
```pytb
======================================================================
ERROR: test_notify_realm_of_new_user_in_manual_license_management (zerver.tests.test_new_users.TestNotifyNewUser)
----------------------------------------------------------------------
File "/srv/zulip-py3-venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/srv/zulip/zerver/lib/db.py", line 46, in execute
return wrapper_execute(self, super().execute, query, vars)
File "/srv/zulip/zerver/lib/db.py", line 31, in wrapper_execute
return action(sql, …
```

test_new_users: Select test emails deterministically

---

static/templates/actions_popover_content.hbs
static/templates/gear_menu.hbs
static/templates/left_sidebar.hbs
static/templates/more_topics.hbs
static/templates/navbar.hbs
static/templates/remind_me_popover_content.hbs
static/templates/settings/admin_invites_list.hbs
static/templates/settings/admin_user_list.hbs
static/templates/stream_settings/new_stream_users.hbs
static/templates/topic_sidebar_actions.hbs

message-menu: Add tabindex attribute for anchor tag to allow focus.

---

zerver/migrations/0376_set_realmemoji_author_and_reupload_realmemoji.py

https://chat.zulip.org/#narrow/stream/18-tools/topic/provision.20error.20w.2Frealm.20emojis
The deferred_work events can't be processed in the test suite
environment, since it tries to make requests to the host <realm.uri>
which is "zulip.testserver" and obviously not going to work. The tests
can work without that work being done, so we just skip the problematic
step, but it seems best to recomment just rebuilding the test db.
This is only needed when applying the migration to an already
provisioned test db - because during an initial db set up there are no
realms yet, so no events get pushed by the migration.

migrations: Don't push events to deferred_work queue if TEST_SUITE.

---

puppet/zulip/manifests/camo.pp
puppet/zulip/manifests/common.pp
puppet/zulip/manifests/external_dep.pp
puppet/zulip/manifests/golang.pp
puppet/zulip/manifests/postgresql_backups.pp
puppet/zulip/manifests/smokescreen.pp

Restore ARM64 support to 4.x
**Testing plan:** CI, a deploy on an ARM64 host worked.

4.x arm64 support

---

zerver/views/auth.py

**Testing plan:** Tested /accounts/logout and /saml/metadata.xml.

auth: Some kwargs fixes

---

tools/lib/provision.py

Fixes #20910.
This is dev-only because binary-patching in production with `sed` is ludicrous, and production systems can just use Debian 11.
**Testing plan:** Provisioned a new dev environment on M1 Mac.

provision: Binary-patch OpenSSL ARM64 assembly bug

---

frontend_tests/node_tests/compose.js
frontend_tests/node_tests/compose_video.js
static/js/click_handlers.js
static/js/compose.js
static/js/compose_ui.js
static/js/message_scroll.js
static/js/tippyjs.js
static/js/ui_init.js
static/styles/compose.css
static/styles/dark_theme.css
static/styles/zulip.css
static/templates/compose.hbs

Show/hide scroll to bottom button when the last message is
not visible in the current scroll position.
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/autoscroll.20when.20sending.20off.20screen
Issue #19862

message_scroll: Show scroll to bottom button.

---

zerver/management/commands/deliver_scheduled_emails.py

Replace the 2 second sleep with a 10s one.

deliver_scheduled_emails: Sleep 10s.

---

docs/tutorials/new-feature-tutorial.md

docs: Update internationalization statement in new feature tutorial.

---

static/js/drafts.js
static/js/message_edit_history.js
static/js/popovers.js
static/styles/rendered_markdown.css

Fixes: #16029 
**Testing plan:** Manually on dev server.
* **Update of stream/usergroup/user-mentions if their name changes.**
**Previous**
**Current**

Render dynamic elements in drafts and edit-history.

---

static/styles/recent_topics.css

**Before ->** 
https://user-images.githubusercontent.com/76561593/155665102-5047144f-7438-4262-a1ed-212fd7daac6c.mov
**After ->**

Add `width` CSS property in filter check icon for recent-topics table

---

.github/workflows/production-suite.yml
tools/ci/build-docker-images

ci: Test upgrades from 4.10.

---

frontend_tests/node_tests/alert_words_ui.js
frontend_tests/node_tests/dispatch.js
static/js/alert_words.js
static/js/alert_words_ui.js
static/js/server_events_dispatch.js
static/js/settings_muted_topics.js
static/js/settings_muted_users.js
static/js/settings_sections.js
static/styles/settings.css
static/templates/muted_topic_ui_row.hbs
static/templates/muted_user_ui_row.hbs
static/templates/settings/alert_word_settings.hbs
static/templates/settings/alert_word_settings_item.hbs
static/templates/settings/muted_topics_settings.hbs
static/templates/settings/muted_users_settings.hbs

stream_settings: Use ListWidget  instead of using list to render Alert Words table

---

tools/lib/test_script.py
tools/test-js-with-puppeteer

Manually tested by running the command.

Enhancements to test-js-with-puppeteer

---

.github/workflows/production-suite.yml
.github/workflows/zulip-ci.yml

https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/CI.20failure.20Ubuntu.2022.2E04/near/1337990

ci: Temporarily disable Ubuntu 22.04

---

frontend_tests/node_tests/rendered_markdown.js
static/js/click_handlers.js
static/js/popover_menus.js
static/js/rendered_markdown.js
static/js/timerender.ts
static/js/tippyjs.js
static/js/ui_util.ts
static/templates/compose.hbs
static/templates/compose_control_buttons.hbs
static/templates/recent_topic_row.hbs
static/templates/right_sidebar.hbs
tools/linter_lib/custom_check.py

**Testing plan:** Tested various tooltips in the dev server.

tippyjs: Avoid unsafe allowHTML API in favor of <template> elements

---

static/styles/settings.css
static/templates/settings/alert_word_settings.hbs
static/templates/settings/attachments_settings.hbs
static/templates/settings/bot_list_admin.hbs
static/templates/settings/data_exports_admin.hbs
static/templates/settings/deactivated_users_admin.hbs
static/templates/settings/default_streams_list_admin.hbs
static/templates/settings/emoji_settings_admin.hbs
static/templates/settings/invites_list_admin.hbs
static/templates/settings/linkifier_settings_admin.hbs
static/templates/settings/muted_topics_settings.hbs
static/templates/settings/muted_users_settings.hbs
static/templates/settings/playground_settings_admin.hbs
static/templates/settings/profile_field_settings_admin.hbs
static/templates/settings/user_list_admin.hbs

This affects any settings panel (personal or org) that has some kind of list of items, so the best way to QA it is to log in as Iago and hit every panel.

settings: Make list header sections consistent.

---

static/js/dialog_widget.js
zerver/lib/actions.py

Was reading code to understand how moving messages across streams work. I think having these could've made things clearer. Please feel free to change the wording if necessary.

Add code comments for dialog_widget.js and `do_update_message().`

---

zerver/tests/test_auth_backends.py
zerver/tests/test_rate_limiter.py

It was there to work around https://bugs.python.org/issue17519. This workaround with `del` seems like a partial improvement.

tests: Avoid use of Python internal __unittest_skip__ flag

---

frontend_tests/node_tests/people.js
frontend_tests/node_tests/stream_create_subscribers_data.js
frontend_tests/puppeteer_tests/subscriptions.ts
static/js/people.js
static/js/stream_create.js
static/js/stream_create_subscribers.js
static/js/stream_create_subscribers_data.js
static/js/zulip_test.js
static/styles/subscriptions.css
static/styles/zulip.css
static/templates/new_stream_user.hbs
static/templates/stream_settings/add_subscribers_form.hbs
static/templates/stream_settings/new_stream_user.hbs
static/templates/stream_settings/new_stream_users.hbs
static/templates/stream_settings/stream_creation_form.hbs
tools/test-js-with-node

This is for issue #20499 and replaces #21069

stream create: Modernize create-stream add-subscribers UI.

---

static/styles/dark_theme.css
static/styles/settings.css
static/styles/user_circles.css
static/styles/zulip.css

**Testing plan:** Who knows, this probably breaks whatever has been depending on these declarations not to parse…

styles: Fix some invalid CSS

---

static/js/stream_create.js
static/js/stream_data.js
static/js/stream_edit.js
static/styles/subscriptions.css
static/templates/stream_settings/new_stream_users.hbs
static/templates/stream_settings/stream_creation_form.hbs
static/templates/stream_settings/stream_types.hbs

stream settings: UI changes in stream create/edit form.

---

templates/zerver/for/use-cases.md
templates/zerver/use-cases.html
zerver/tests/test_docs.py
zproject/urls.py

manual (clicked on all the links)

portico: Create use cases index page.

---

templates/zerver/help/status-and-availability.md
templates/zerver/help/web-public-streams.md

Updated version of #21405
Fixes https://github.com/zulip/zulip/issues/21369.
manual

 help_docs: Add documentation for status emoji

---

zerver/forms.py

Using mark_safe on errors with content in them taken from user-input is
a clearly bad idea. With that said, this code
was not exploitable in the current state, given that username is a value you
have to POST to /login/, and the endpoint is CSRF-protected.
We also remove use of mark_safe from the errors without user input them,
but that are just plaintext and thus don't need it.

forms: Remove incorrect use of mark_safe on some errors.

---

docs/production/deployment.md
puppet/zulip/manifests/profile/postgresql.pp
puppet/zulip/templates/postgresql/12/postgresql.conf.template.erb
puppet/zulip/templates/postgresql/13/postgresql.conf.template.erb
puppet/zulip/templates/postgresql/14/postgresql.conf.template.erb
puppet/zulip/templates/postgresql/recovery.conf.template.erb

puppet: Support password-based PostgreSQL replication, and ssl_mode verification.

---

templates/zerver/help/configure-who-can-create-streams.md
templates/zerver/help/configure-who-can-edit-topics.md
templates/zerver/help/configure-who-can-invite-to-streams.md
templates/zerver/help/create-a-stream.md
templates/zerver/help/custom-emoji.md
templates/zerver/help/invite-new-users.md

Also adds some links to related articles.
manual

help center: Remove unnecessary lists of possible roles for permissions.

---

.github/workflows/production-suite.yml
tools/ci/build-docker-images

**Testing plan:** CI on this PR.

ci: Test upgrades from 4.11.

---

zerver/lib/actions.py
zerver/lib/user_topics.py
zerver/tests/test_message_edit.py

When a user edits topic name then that topic is unmuted for the users who have muted it. This commit fixes such problem and ensures that `orig_topic_name` is removed from `MutedTopic` and new topic name is added to it.
Fixes #15210.

message_edit: Fix unmute of topic when topic name is edited.

---

templates/zerver/help/change-the-color-of-a-stream.md

Updates instructions for changing a stream's color so that there are no missing or incorrect steps.
**Screenshot of updated instructions**:

help_docs: Update instructions for change stream color.

---

static/js/settings_config.ts
zerver/openapi/zulip.yaml

[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/Rename.20unread.20count.20setting)

settings_config: Rename "Unread count summary" to "Unread count badge".

---

puppet/zulip/manifests/common.pp
puppet/zulip_ops/files/tornado_process_exporter.yaml
puppet/zulip_ops/manifests/app_frontend_monitoring.pp
puppet/zulip_ops/manifests/profile/chat_zulip_org.pp
puppet/zulip_ops/manifests/prometheus/rabbitmq.pp
puppet/zulip_ops/manifests/prometheus/tornado.pp
puppet/zulip_ops/templates/supervisor/conf.d/prometheus_tornado_exporter.conf.template.erb

**Testing plan:** Test-deployed both commits directly on CZO.

Add more monitoring to CZO, including tornado CPU monitoring

---

puppet/zulip/manifests/profile/postgresql.pp

**Testing plan:** Re-discovered in prod.

puppet: Fix the PostgreSQL paths to recovery.conf / standby.conf.

---

docs/production/authentication-methods.md

Docs: restrict ldap group for login #338

---

static/styles/settings.css
static/templates/settings/account_settings.hbs
static/templates/settings/bot_list_admin.hbs
static/templates/settings/deactivated_users_admin.hbs
static/templates/settings/invites_list_admin.hbs
static/templates/settings/linkifier_settings_admin.hbs
static/templates/settings/profile_field_settings_admin.hbs
static/templates/settings/user_list_admin.hbs

settings: Place the saving indicator in the header.

---

static/styles/settings.css

This PR is based on the work done previously in #20506.
Fixing part of #20484 
Manual Testing

settings: Improve help icons in settings.

---

static/js/lightbox.js
zerver/lib/upload.py
zerver/tests/test_upload.py
zerver/views/upload.py
zproject/urls.py

Fixes #19238.
**Testing plan:** Configured a test prod host to use S3 buckets, verified that the "Download" link worked.

Fix download links from S3 uploads

---

templates/zerver/help/desktop-notifications.md
templates/zerver/help/pm-mention-alert-notifications.md

This PR is on top of and replaces #21514.
manual

Help center: notifications pages

---

templates/zerver/help/include/sidebar_index.md
templates/zerver/help/move-content-to-another-stream.md
templates/zerver/help/move-content-to-another-topic.md

Help center: Add details regarding moved content.

---

templates/zerver/help/include/move-content-subset-options.md
templates/zerver/help/move-content-to-another-stream.md
templates/zerver/help/move-content-to-another-topic.md
templates/zerver/help/rename-a-topic.md

This PR updates and replaces #21511.
manual

help center: Rewrite documentation on moving content

---

docs/subsystems/release-checklist.md

From notes on the last release.

docs: Update release steps.

---

requirements/dev.in
requirements/dev.txt
requirements/docs.txt
requirements/mypy.in
requirements/mypy.txt
requirements/pip.txt
requirements/prod.txt
version.py
zerver/lib/db.py

* async-timeout: (new) → 4.0.2
* boto3: 1.21.20 → 1.21.26
* boto3-stubs[s3]: 1.21.20 → 1.21.26
* botocore: 1.24.20 → 1.24.26
* botocore-stubs: 1.24.20 → 1.24.26
* dataclasses-json: 0.5.6 → 0.5.7
* itemadapter: 0.4.0 → 0.5.0
* jinja2: 3.0.3 → 3.1.0
* jmespath: 0.10.0 → 1.0.0
* line-profiler: 3.4.0 → 3.5.0
* moto[s3]: 3.1.0 → 3.1.1
* mypy: 0.941 → 0.942
* mypy-boto3-s3: 1.21.7 → 1.21.23.post1
* pytz: 2021.3 → 2022.1
* redis: 4.1.4 → 4.2.0
* responses: 0.18.0 → 0.20.0
* ~~semgrep: 0.84.0 → 0.85.0~~
* sentry-sdk: 1.5.7 → 1.5.8
* setuptools: 60.9.3 → 61.0.0
* sqlalchemy2-stubs: 0.0.2a20 → 0.0.2a21
* stripe: 2.67.0 → 2.68.0
* tlds: 2022031400 → 2022032300
* tqdm: 4.63.0 → 4.63.1
* twilio: 7.7.1 → 7.8.0
* types-beautifulsoup4: 4.10.14 → 4.10.16
* types-boto: 2.49.9 → 2.49.10
* types-pillow: …

requirements: Upgrade Python requirements

---

zerver/lib/actions.py
zerver/lib/user_topics.py
zerver/tests/test_message_edit.py
zerver/tests/test_muting_users.py
zerver/views/muting.py

We were not handling this case, which resulted in failure.
discussion - https://chat.zulip.org/#narrow/stream/101-design/topic/Moving.20muted.20topics

message_edit: Fix bug moving muted topic to already muted topic.

---

static/styles/compose.css
static/styles/left_sidebar.css
static/styles/zulip.css

discussion - https://chat.zulip.org/#narrow/stream/101-design/topic/globe.20icon.20for.20world-public.20streams

Adjust alignment of globe and lock icon.

---

templates/zerver/asciidoctor-case-study.html
templates/zerver/footer.html
templates/zerver/for/asciidoctor-case-study.md
templates/zerver/for/use-cases.md
templates/zerver/landing_nav.html
zerver/tests/test_docs.py
zproject/urls.py

We will also need to link to this from `/for/x` pages, but I'll do that as a follow-up commit.
manual

portico: Add Asciidoctor case study.

---

CONTRIBUTING.md

docs: Clarify stages of PR review.

---

tools/total-contributions

Tested locally while preparing the 5.0 release.

tools: Rework check-contributions to use commits rather than releases.

---

tools/semgrep.yml
zerver/migrations/0387_reupload_realmemoji_again.py

The blockquote explains the motivation for this change in detail.
Fixes #21608.

migrations: Repeat part of migration 0376.

---

tools/semgrep.yml
zerver/migrations/0376_set_realmemoji_author_and_reupload_realmemoji.py
zerver/migrations/0387_reupload_realmemoji_again.py

migrations: Remove the possibly-duplicated emoji re-uploading.

---

zerver/tests/test_mirror_users.py
zerver/views/message_send.py

Instead of using request.POST to get any potential `sender` parameters for `send_message_backend`, moves it to the REQ framework parameters as `req_sender`.
Also, updates `create_mirrored_message_users` to take specific parameters instead of an HTTP request parameter, which then accessed parameters via request.POST.
Part of ongoing project to [implement `ignored_parameters_unsupported`](https://chat.zulip.org/#narrow/stream/3-backend/topic/ignored_parameters_unsupported/near/1286694) array as a possible return value from `json_success` and `JsonableError`. See [this CZO conversation](https://chat.zulip.org/#narrow/stream/3-backend/topic/tests.20with.20client.20parameter/near/1334915) for more context about moving the `sender` parameter to REQ framework.
**Testing plan:** Updates existing …

message_send: Move `sender` parameter to REQ.

---

frontend_tests/node_tests/linkifiers.js
frontend_tests/node_tests/markdown.js
frontend_tests/node_tests/markdown_parse.js
static/js/linkifiers.js
static/js/markdown.js
static/js/markdown_config.js
static/js/zcommand.js
static/third/marked/lib/marked.js

This also includes a tiny bug fix.

refactor: Prepare markdown.js for code reuse.

---

docs/production/install.md

We don't suggest self-hosing, unless via a sprinkler in warm weather.

docs: Fix typo.

---

static/shared/js/typeahead.js.flow

Adds flow types for get_emoji_matcher and sort_emojis so they can be
utilized in mobile.

shared: Add flow types for emoji typeahead funcs.

---

frontend_tests/node_tests/pm_list_data.js
static/js/pm_list.js
static/js/pm_list_data.js
static/js/pm_list_dom.js
static/js/topic_list.js

This is preparatory commit for functionality of Collapsible Private messages (#21102)

left-sidebar: Add logic for pm_list_data parallel to topic_list_data.

---

templates/zerver/features.html

manual; tested all the new links

portico: Update /features.

---

tools/test-backend
zerver/lib/timeout.py
zerver/tests/test_timeout.py

**Testing plan:** Added tests.

Improve tracebacks from zerver.lib.timeout

---

zerver/middleware.py
zerver/tests/test_decorators.py

If an API request specified a `client` parameter, we already prioritize that value over parsing the HTTP `UserAgent` for setting the `client_name` in the `RequestNotes`.
In order to also have these parameters logged in the `RequestNotes` as processed parameters instead of ignored parameters, we add the `has_request_variables` decorator to `parse_client` and then process the potential `client` parameter through the REQ framework.
Part of ongoing work for [implementing `ignored_parameters_unsupported`](https://chat.zulip.org/#narrow/stream/3-backend/topic/ignored_parameters_unsupported/near/1323714) array to all endpoints. See [this CZO conversation](https://chat.zulip.org/#narrow/stream/3-backend/topic/tests.20with.20client.20parameter/near/1360475) for more context for the potential …

middleware: Add `client` REQ parameter to `parse_client`.

---

static/shared/package.json

Bump @zulip/shared to 0.0.13 for release.

shared: Bump version to 0.0.13.

---

.github/workflows/production-suite.yml
tools/ci/build-docker-images

**Testing plan:** CI on this PR.

ci: Test upgrades from 3.x, 4.x and 5.x.

---

puppet/zulip/manifests/common.pp

puppet: Upgrade Grafana to 8.4.6.

---

docs/contributing/gsoc.md

The underlined [link](https://github.com/zulip/zulip/labels/area%3A%20admin) in the GSoC ideas section in docs/gsoc.md led to a page with 0 results. This has now been replaced with the [correct link](https://github.com/zulip/zulip/issues?q=is:open+is:issue+label:%22area:+settings+(admin/org)%22,%22area:+settings+(user)%22,%22area:+stream+settings%22) leading to a list of issues with the mentioned labels.

docs: Update broken link in gsoc.md.

---

templates/zerver/help/desktop-app-install-guide.md
templates/zerver/help/include/sidebar_index.md
templates/zerver/help/view-zulip-version.md

docs: Add "View Zulip version" help center page.

---

templates/zerver/help/include/web-public-streams-intro.md

This provides an easy way to preview the feature.
- I didn't describe the "Access without an account" button, because we plan to remove that step.
- I chose not to go into the details of what to do if you're already logged into CZO.
Note that this text also appears on `/help/moderating-open-organizations`.

docs: Link to chat.zulip.org from /help/web-public streams.

---

zerver/lib/digest.py
zerver/tests/test_digest.py

https://chat.zulip.org/#narrow/stream/9-issues/topic/Errors.20when.20sending.20a.20message.20to.20a.20deactivated.20user

Skip digest emails to deactivated users

---

zerver/actions/create_realm.py
zerver/actions/realm_settings.py
zerver/actions/users.py
zerver/management/commands/delete_user.py
zerver/tests/test_users.py

No manual testing plans; I expect CI to catch any issues.
Fixes: #14808.

Fix remaining acting_user issues with RealmAuditLog

---

zerver/management/commands/sync_ldap_user_data.py

Discussion around https://chat.zulip.org/#narrow/stream/31-production-help/topic/ldap/near/1364155
It doesn't make sense to run sync_ldap_user_data if user_profiles list
is empty. Otherwise this misleading exception gets raised:
```
raise Exception(
"LDAP sync would have deactivated all users. This is most likely due "
"to a misconfiguration of LDAP settings. Rolling back...\n"
"Use the --force option if the mass deactivation is intended."
)
```

sync_ldap_user_data: Show a proper error if no relevant users exist.

---

zerver/tornado/event_queue.py

When `update_message` events were updated to have a consistent format for both normal message updates/edits and special
rendering preview updates (#20803), the logic used in the tornado event queue processor to identify the special events for sending notifications no longer applied.
Updates that logic to use the `rendering_only` flag that was added to the `update_message` event format to identify if the event processor should potentially send notifications to users.
Fixes #16022. …

update_message: Use `rendering_only` flag for notifications logic.

---

analytics/tests/test_counts.py
analytics/tests/test_support_views.py
confirmation/models.py
static/js/invite.js
static/js/settings_config.ts
static/styles/settings.css
static/styles/zulip.css
static/templates/invite_user.hbs
templates/zerver/api/changelog.md
version.py
zerver/actions/invites.py
zerver/models.py
zerver/tests/test_auth_backends.py
zerver/tests/test_events.py
zerver/tests/test_i18n.py
zerver/tests/test_queue_worker.py
zerver/tests/test_signup.py
zerver/tests/test_users.py
zerver/views/development/email_log.py
zerver/views/invite.py
zerver/worker/queue_processors.py
zproject/computed_settings.py

This PR currently contains commits of #20410 as well to make this easy to rebase after #20410 is merged.

Add custom option for invite expiration time.

---

puppet/zulip/manifests/common.pp

puppet: Upgrade external dependencies.

---

zerver/tests/test_populate_db.py
zilencer/management/commands/populate_db.py

populate_db: Add support for creating messages older than 5 days ago.

---

static/styles/subscriptions.css

subscriptions: Fix web-public icon vertical alignment.

---

Dockerfile-postgresql

https://github.com/zulip/zulip/issues/21211
* I tested this image together with our [helm chart PR](https://github.com/zulip/docker-zulip/pull/325), installing zulip from scratch
* I did not test any upgrade from current postgres 10 to 14

Upgrade docker-postgresql to v14

---

puppet/zulip/manifests/profile/app_frontend.pp

It is possible to have previously installed certbot, but switched back
to using self-signed certificates -- in which case renewing them using
certbot may fail.
Verify that the certificate is a symlink before running
`fix-standalone-certbot`

puppet: Check that certbot certs are in use before fixing them.

---

zerver/lib/email_notifications.py
zerver/lib/notification_data.py
zerver/lib/push_notifications.py
zerver/lib/soft_deactivation.py
zerver/lib/test_classes.py
zerver/tests/test_email_notifications.py
zerver/tests/test_push_notifications.py
zerver/worker/queue_processors.py

email_notifications: Soft reactivate mentioned users.

---

zerver/tests/test_upload.py
zerver/views/users.py

avatar: Add rate limit similar to attachments on medium avatars.

---

frontend_tests/node_tests/dropdown_list_widget.js
frontend_tests/node_tests/settings_org.js
static/js/dropdown_list_widget.js
static/js/message_edit.js
static/js/settings_bots.js
static/js/settings_org.js
static/js/settings_users.js
static/js/stream_popover.js

I did some basic testing of `DropdownListWidget` instances in organization settings. We currently have no `MultiSelectDropdownListWidget` instances to test outside of the Node tests.
`git show -w` (`--ignore-all-space`) recommended for reviewing.
Cc @aryanshridhar (#18954)

Convert DropdownListWidget, MultiSelectDropdownListWidget to ES6 classes

---

tools/droplets/README.md
tools/droplets/cleanup.py
tools/droplets/create.py
tools/droplets/new-droplet-image

Make it easier to regenerate the DigitalOcean base image, and give it a little more flexibility (IPv6 addresses, selectable regions so it can be closer to the user).

Droplet improvements

---

zproject/prod_settings_template.py

Fix quotes in prod_settings_template

---

zerver/webhooks/slack_incoming/tests.py
zerver/webhooks/slack_incoming/view.py

Fixes: https://github.com/zulip/zulip/issues/19056

slack_incoming: Process request payload directly in view.py

---

scripts/setup/compare-settings-to-template

compare-settings-to-template: Paginate through tags

---

zerver/lib/import_realm.py

This matches the metadata that we store in the database, and means
that the S3 metadatata invariant of always having a `user_profile_id`
in the metadata.
This does not fix existing imports, which may still have missing
`user_profile_id`s.

import: Default the S3 metadata user of emoji to the first owner.

---

zerver/openapi/zulip.yaml

Fixes a reference link in `realm_enable_spectator_access` description in `/register-queue` endpoint documentation.

openapi: Fix reference link in `/register-queue` documentation.

---

.github/workflows/production-suite.yml
.github/workflows/zulip-ci.yml

Comments out the steps in 'Create cache directories' that use `actions/cache@v2` so that the CI can pass while Github support issue is processed.

ci: Remove actions/cache@v2 steps.

---

.github/workflows/production-suite.yml
.github/workflows/zulip-ci.yml

This reverts commit ae24fe69ed6f386240147ebbcecf4cf7696997ed.
The problem was fixed by GitHub.

Revert "ci: Remove actions/cache@v2 steps from run due to failures."

---

scripts/setup/apt-repos/ksplice/jammy.list
scripts/setup/apt-repos/teleport/jammy.list

Add zulip_ops apt repo support for 22.04.

---

scripts/lib/zulip_tools.py
scripts/log-search

This is a script to search log files by server hostname, client IP
address, or userid, and output matching lines, all while skipping
common and less-interesting request lines.

scripts: Add a tool to search logs by IP/hostname/userid.

---

puppet/zulip/manifests/common.pp
puppet/zulip_ops/manifests/profile/chat_zulip_org.pp
puppet/zulip_ops/manifests/profile/redis.pp
puppet/zulip_ops/manifests/prometheus/redis.pp
puppet/zulip_ops/templates/supervisor/conf.d/prometheus_redis_exporter.conf.template.erb

puppet: Add a redis exporter.

---

.github/workflows/production-suite.yml
tools/ci/build-docker-images

ci: Update upgrade test to 5.2, from 5.1.

---

docs/production/deployment.md
zproject/computed_settings.py

Tested all three documented proxies.

Improve proxy docs

---

zerver/actions/message_edit.py
zerver/actions/message_send.py
zerver/tests/test_link_embed.py
zerver/tests/test_message_edit.py
zerver/worker/queue_processors.py

Solve a race condition with embed_links / deleted messages

---

frontend_tests/node_tests/settings_user_groups.js
static/js/settings_user_groups.js
static/styles/settings.css
static/templates/settings/add_user_group_modal.hbs
static/templates/settings/user_groups_admin.hbs
templates/zerver/help/include/how-to-create-a-user-group.md
tools/test-js-with-node

user_groups: Convert inline form to modal.

---

frontend_tests/node_tests/composebox_typeahead.js
frontend_tests/node_tests/dispatch.js
frontend_tests/node_tests/lib/events.js
frontend_tests/node_tests/markdown_parse.js
frontend_tests/node_tests/settings_user_groups.js
frontend_tests/node_tests/user_groups.js
static/js/markdown.js
static/js/markdown_config.js
static/js/rendered_markdown.js
static/js/server_events_dispatch.js
static/js/settings_user_groups.js
static/js/user_groups.ts

Commit summary -
- Add `subgroups` field to user group objects.
- Add functions to update subgroups in user group objects on receiving events.
- Rename `is_member_of` function to `is_direct_member_of`.
- Add `get_recursives_subgroups` function.
- Add `is_user_in_group` function
Fixes part of:  #19525 

Add functions to update subgroups in user group objects and `is_user_in_group` function.

---

templates/zerver/footer.html
templates/zerver/for-communities.html
templates/zerver/for-education.html
templates/zerver/for-events.html
templates/zerver/for-open-source.html
templates/zerver/for/communities.md
templates/zerver/for/recurse-center-case-study.md
templates/zerver/for/use-cases.md
templates/zerver/landing_nav.html
templates/zerver/recurse-center-case-study.html
zerver/tests/test_docs.py
zproject/urls.py

Manually tested links and pages, but might be worth taking another look.

portico: Add Recurse Center case study.

---

templates/zerver/for/recurse-center-case-study.md

Makes all quotation marks pretty.

portico: Fix quotation marks in Recurse Center case study.

---

requirements/common.in
requirements/dev.txt
requirements/mypy.in
requirements/mypy.txt
requirements/prod.txt

requirements: Require boto3-stubs packages only in development

---

docs/production/upgrade-or-modify.md

docs: Clarify nginx extension points.

---

docs/production/troubleshooting.md
docs/subsystems/logging.md

Follow up to https://github.com/zulip/zulip/pull/22008#issuecomment-1121584060

docs: Document the ./scripts/log-search tool.

---

zerver/middleware.py
zerver/tests/test_decorators.py
zerver/tests/test_docs.py
zerver/views/portico.py

middleware: Fix URL encoding of next parameter

---

zerver/webhooks/freshdesk/view.py

From https://github.com/zulip/zulip/pull/21581/commits/4ef33e1a34ff1441ae8a21af3cf58b48ed7abc22#r869911287.

freshdesk: Remove unsafe TicketDict class

---

zerver/webhooks/front/view.py
zerver/webhooks/gci/view.py
zerver/webhooks/gitlab/view.py

From https://github.com/zulip/zulip/pull/21581/commits/10b4db02f5dd5e8a7c130207fcf4b7961954eb30#r869915355.

front: Fix get_body_based_on_event type

---

zerver/actions/streams.py
zerver/tests/test_subs.py

Previously, we were marking messages of all the streams passed
to bulk_remove_subscriptions even if user was not subscribed
to some of them and those streams would ideally not have
any unread messages. This code was added in 766511e5193.
This PR changes the code to only mark messages of actually
unsubscribed streams as read.

streams: Mark messages as read only for unsubscribed streams.

---

zerver/actions/message_flags.py
zerver/tests/test_events.py
zerver/tests/test_subs.py

Omit sending an event, and updating the database, if there are no
matching messages.

message_flags: Short-circuit if no messages changed.

---

corporate/views/webhook.py
templates/zerver/api/incoming-webhooks-walkthrough.md
zerver/decorator.py
zerver/lib/i18n.py
zerver/lib/logging_util.py
zerver/lib/rest.py
zerver/lib/webhooks/common.py
zerver/middleware.py
zerver/signals.py
zerver/tests/test_decorators.py
zerver/tests/test_i18n.py
zerver/tests/test_integrations_dev_panel.py
zerver/tests/test_message_fetch.py
zerver/tests/test_signup.py
zerver/tests/test_webhooks_common.py
zerver/views/auth.py
zerver/views/compatibility.py
zerver/views/development/registration.py
zerver/views/home.py
zerver/webhooks/beanstalk/view.py
zerver/webhooks/bitbucket2/view.py
zerver/webhooks/bitbucket3/view.py
zerver/webhooks/gitea/view.py
zerver/webhooks/github/view.py
zerver/webhooks/gitlab/view.py
zerver/webhooks/gogs/view.py
zerver/webhooks/groove/view.py
zerver/webhooks/netlify/view.py
zerver/webhooks/reviewboard/view.py

django: Use HttpRequest.headers

---

zerver/lib/email_mirror.py
zerver/tests/test_email_mirror.py

There's some sloppiness in the RFCs, in that it's not at all clear what to do in case the charset isn't recognized. The closest is https://tools.ietf.org/html/rfc2046#section-4.1.4, which says:
> Unrecognized subtypes of "text" should be treated as subtype "plain"
> as long as the MIME implementation knows how to handle the charset.
> Unrecognized subtypes which also specify an unrecognized charset
> should be treated as "application/octet- stream".
...which might argue that in cases of invalid charset, we should treat it as `application/octet- stream` and thus not text, so `continue` and let the other text parts, if present, be used.  But read narrowly, that's only for "unrecognized subtypes," and we very much recognize the `plain` subtype, just not the charset. …

email_mirror: Handle invalid `charset="..."` values.

---

frontend_tests/node_tests/composebox_typeahead.js
frontend_tests/node_tests/dispatch.js
frontend_tests/node_tests/lib/events.js
frontend_tests/node_tests/user_groups.js
static/js/server_events_dispatch.js
static/js/user_groups.ts
templates/zerver/api/changelog.md
zerver/actions/user_groups.py
zerver/lib/event_schema.py
zerver/lib/events.py
zerver/lib/user_groups.py
zerver/openapi/zulip.yaml
zerver/tests/test_user_groups.py
zerver/views/user_groups.py

Commit summary -
- Rename `subgroups` and `subgroup_ids` field to `direct_subgroup_ids` in user group objects.
- Rename subgroups parameter to `direct_subgroup_ids` in `do_send_create_user_group_event` function.
- Rename `existing_subgroups` variable to `existing_direct_subgroup_ids` in `add_subgroups_to_group_backend` and `add_subgroups_to_group_backend` functions.

Rename `subgroups` and `subgroup_ids` to `direct_subgroup_ids` for readability.

---

zerver/lib/name_restrictions.py

This is used as a placeholder in the mobile app.

name_restrictions: Add your-org.zulipchat.com as a reserved name.

---

templates/zerver/api/changelog.md
zerver/openapi/zulip.yaml

Adds `create_web_public_stream_policy` to the `get-events` API documentation for the `realm op:update` event. See [this CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/event.20with.20.60create_web_public_stream_policy.60.3F/near/1381274) for more context.
Also, fixes changelog entries for feature levels 103 and 104, which are related to the API documentation changes or fix an error in references to the undocumented endpoint `PATCH /realm`. …

api-docs: Add `create_web_public_stream_policy` to realm update.

---

puppet/zulip/manifests/common.pp

Tested by applying the changes.

Upgrade grafana, smokescreen, wal-g deps

---

scripts/lib/upgrade-zulip-stage-2
scripts/restart-server
scripts/stop-server
scripts/zulip-puppet-apply
zerver/management/commands/fill_memcached_caches.py

Reduce the amount of downtime that servers have when upgrading, via a variety of tricks.
**Testing plan:** Upgraded a server a few times, in various configurations.

Shorten critical period in upgrade

---

zerver/webhooks/github/view.py

https://github.com/octokit/webhooks/blob/v5.6.0/payload-schemas/api.github.com/common/issue.schema.json#L84
https://github.com/octokit/webhooks/blob/v5.6.0/payload-schemas/api.github.com/common/pull-request.schema.json#L78
Cc @yuroitaki (#21581)

github: Accept null for issue and pull request body

---

zerver/openapi/zulip.yaml

Updates made:
- Adds **Changes** notes for feature level 58 where support was added for stream messages for the `/set-typing-status` endpoint parameters. Relevant [CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/audit.20for.20change.20entries.20vs.2E.20central.20changelog/near/1324944) for this part of the  changes.
- Updates formatting for references to the `type` parameter in the descriptions of other endpoint parameters.
- Improves readability of and updates links in the endpoint's main description.
--- …

api-docs: Update `/set-typing-status` endpoint documentation.

---

templates/zerver/help/restrict-permissions-of-new-members.md

help: Clarify potentially confusing wording.

---

zerver/lib/response.py
zerver/middleware.py
zerver/tornado/handlers.py
zerver/tornado/views.py

This is a replacement for #22125 (part of #18777).

response: Replace response.asynchronous attribute with new class

---

docs/subsystems/sending-messages.md
zerver/forms.py
zerver/lib/soft_deactivation.py
zerver/tests/test_signup.py

password_reset: Soft reactivate upon password reset

---

templates/corporate/jobs.html

- Makes location info easier to find, same as we did for the Infra job.
- Removes backend Python from the tech stack list, as discussed with @gnprice and @chrisbobbe .

portico: Make minor updates to Senior Mobile Engineer job listing.

---

puppet/zulip_ops/files/nagios4/commands.cfg

Since this is what chrony is sync'ing to, it lessens the chance of
spurious firings of this alert.
See https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/

puppet: Switch to checking time against the AWS timeserver.

---

static/js/stream_create.js

[5.x] stream_create: Fix crash on stream creation error

---

templates/zerver/help/add-or-remove-users-from-a-stream.md
templates/zerver/help/include/right-sidebar-view-full-profile.md
templates/zerver/help/include/sidebar_index.md
templates/zerver/help/manage-user-stream-subscriptions.md
templates/zerver/help/view-someones-profile.md

Adds a new help center article focused on managing a single user's stream subscriptions.
Creates a shared file for instructions to navigate to a user's full profile via the right sidebar, which is used in three help center articles.
Fixes #21795.

help-docs: Add manage a user's stream subscriptions article.

---

zerver/openapi/zulip.yaml

Prep commit for adding `ignored_parameters_unsupported` to `json_success` responses.
Uses `SimpleSuccess` response schema for all endpoints that were already returning a success (`200`) response without any data beyond the `response` and `msg` fields, which are standard for all endpoint responses.
```yaml
responses:
SimpleSuccess:
description: Success.
content:
application/json:
schema:
allOf:
- $ref: "#/components/schemas/JsonSuccess"
- $ref: "#/components/schemas/SuccessDescription"
```
Note the example (`{"msg": "", "result": "success"}`) is in the `JsonSuccessBase` shared schema, which is referenced by the `JsonSuccess` schema.
Confirmed there is no diff in the API docs HTML with this change.
---
Communicate …

api-docs: Expand use of `SimpleSuccess` response schema.

---

templates/zerver/api/changelog.md
zerver/openapi/zulip.yaml

Adds a 2.1 release changelog entry for adding support for user and stream IDs in search/narrow options. Also, adds a Changes note in the narrow parameter in the OpenAPI `get-messages` endpoint definition.
Both link to the api documentation for [constructing a narrow](https://zulip.com/api/construct-narrow), where the 2.1 release update is already mentioned.
Fixes #9474 because completes final API documentation task related to issue. …

api-docs: Add changelog entry for user/stream ID narrow options.

---

zproject/computed_settings.py
zproject/default_settings.py
zproject/dev_settings.py

This can be useful if one wants a third-party authentication system to
apply first.
Fixes: 

settings: Allow customizing HOME_NOT_LOGGED_IN.

---

puppet/zulip/manifests/app_frontend_base.pp
puppet/zulip/templates/uwsgi.ini.template.erb

**Testing plan:** Deployed on a test prod server.

UWSGI config updates

---

zilencer/management/commands/populate_db.py

We do not allow keeping vacant private streams as we deactivate them
when all users are unsubscribed, so it is better to add at least one
user in the initial private stream created while creating realm.
Noticed this while trying to making changes as
mentioned in https://github.com/zulip/zulip/pull/22050#issuecomment-1126342466

populate_db: Add users to initial private stream in mit and lear realm.

---

zerver/webhooks/gitlab/fixtures/repository_update.json
zerver/webhooks/gitlab/view.py

94457732c178 changed this from:
```py
event_name = payload.get("event_name", payload.get("object_kind")).tame(check_string)
```
...to:
```py
event_name = payload.get("event_name", payload["object_kind"]).tame(check_string)
```
Which causes a failure when `event_name` exists but `object_kind` does
not, since the default is evaluated first.
Switch to an `if` statement to clarify the fallbacks better.

gitlab: Fix event_name -> object_kind defaulting.

---

static/js/emojisets.js

Followup to commit f743dda0080af578cecdc6d5167b91c47a24b71d (#19672).

emojisets: Use Google modern for emoji picker with text theme

---

scripts/lib/upgrade-zulip-from-git

Stop making a working copy in /srv/zulip.git, edge cases in de-mirror'ing

---

.github/workflows/production-suite.yml
tools/ci/build-docker-images

ci: Update upgrade test to 5.3, from 5.2.

---

templates/corporate/jobs.html

portico: Remove Senior Infrastructure Engineer position from /jobs.

---

zerver/management/commands/compilemessages.py

This makes the generated data more consistent.

compilemessages: Use a consistent ordering for the languages list.

---

corporate/tests/test_stripe.py
pyproject.toml
tools/lib/capitalization.py
tools/lib/template_parser.py
tools/run-dev.py
zerver/actions/message_send.py
zerver/lib/integrations.py
zerver/lib/mention.py
zerver/lib/scim.py
zerver/lib/users.py
zerver/lib/webhooks/common.py
zerver/tests/test_bots.py
zerver/tests/test_custom_profile_data.py
zerver/tests/test_import_export.py
zerver/tests/test_transfer.py
zerver/tornado/handlers.py
zerver/webhooks/jira/view.py

This is the branch where I found CVE-2022-31017 (20f9293f1f5a95c17ba82cfcd24dc182475d66a8) due to `truthy-bool`.

Enable more mypy strictness options

---

tools/upload-release

`zulip-server-6.0-pre0.tar.gz` should not be copied to
`zulip-server-latest.tar.gz`.

upload-release: Only copy full releases to zulip-server-latest.tar.gz.

---

docs/overview/changelog.md

Make changelog entries consistent

---

zerver/decorator.py
zerver/lib/request.py
zerver/lib/test_helpers.py
zerver/tests/test_decorators.py
zerver/tests/test_event_queue.py
zerver/tests/test_event_system.py
zerver/tests/test_tornado.py
zerver/tornado/event_queue.py
zerver/tornado/handlers.py
zerver/tornado/views.py

Thinking about #22296 revealed some simplifications. Cc @PIG208.

Type fetch_events parameters; replace tornado_handler weak reference with tornado_handler_id

---

zerver/actions/create_realm.py
zerver/management/commands/change_realm_subdomain.py
zerver/tests/test_signup.py

Add the ability to skip redirects for renamed realms

---

zerver/data_import/mattermost.py
zerver/lib/email_notifications.py

Run html2text as a subprocess

---

zerver/webhooks/gitlab/doc.md

Noted when reviewing #22315.
**Screenshot of updated GitLab integration documentation**:
**Screenshot of previous GitLab integration documentation**:

integrations-docs: Add line break in GitLab integration doc.

---

docs/documentation/integrations.md
templates/zerver/help/include/zulip-config.md

The content in `zulip-config.md` was moved (in #22315) to `change-zulip-config.file.md`. This removes the now out-of-date
reference to this macro in the documentation for writing integrations and removes the file as it is no longer in use.

integrations-docs: Remove `zulip-config.md`.

---

docs/production/deployment.md

Addresses a question from https://github.com/zulip/zulip/issues/19073#issuecomment-1166983743

docs: Document that loadbalancer.ips can be CIDR ranges.

---

tools/setup/bootstrap-aws-installer
tools/setup/bootstrap-awscli.sh
tools/setup/install-aws-server

Improve AWS installer

---

static/templates/announce_stream_docs.hbs

Changed the Announce stream hint tooltip message to the following: "Organization administrators can change the announcement stream in the organization settings."
Follow-up to commit bbda7a5bb05898fd87b99e8b20176ea6bce88aa3.

stream_settings: Modify the message of the "Announce stream" hint tooltip.

---

scripts/log-search

Fix a log-search bug, add a minor feature

---

zerver/lib/retention.py

<del>Passing an `SQL` (`Composable`) object into `cursor.execute` is
an idiomatic practice for psycopg2 not understood by django-stubs.
<del>The `.as_string` method automatically gets invoked upon execution,
so the resulting query will be unchanged.
This ensures that all the keyword arguments in `move_rows`
have the correct types. Note that `returning_id` is supposed to be a
flag instead of a `Composable` `Literal`.
This is a part of the django-stubs refactorings #18777.
Completed …

retention: Guarantee type-safeness when calling move_rows.

---

zerver/data_import/import_util.py
zerver/lib/create_user.py
zerver/lib/logging_util.py
zerver/lib/soft_deactivation.py
zerver/lib/user_groups.py

This is an accumulating branch of refactorings for minor typing errors throughout the codebase if django-stubs is enabled.

django-stubs: Fix miscellaneous typing errors

---

zerver/decorator.py
zerver/forms.py
zerver/tests/test_signup.py
zerver/views/registration.py

Fixes attribute errors associated with `HttpRequest`
This is a part of #18777.

django-stubs: Fix attribute errors with `HttpRequest`

---

zerver/tornado/event_queue.py
zerver/tornado/handlers.py

This was also hidden until 81f7192ca3f59f326c6d8c2fc584d35346314c6f (#22301).

tornado: Ignore StreamClosedError

---

zerver/webhooks/slack_incoming/fixtures/attachment.json
zerver/webhooks/slack_incoming/fixtures/attachment_blocks.json
zerver/webhooks/slack_incoming/fixtures/attachment_fields.json
zerver/webhooks/slack_incoming/fixtures/attachment_pieces.json
zerver/webhooks/slack_incoming/fixtures/complicated.json
zerver/webhooks/slack_incoming/tests.py
zerver/webhooks/slack_incoming/view.py

Fixes: #21944.
See also #22228, which this does not solve, but assuming we can decide
which compromises to make, becomes a reasonably uncomplicated follow-up.
Slack:
----
Zulip:

Handle more slack syntax, use WildValue

---

zerver/actions/realm_settings.py

prep commit as per this review:
https://github.com/zulip/zulip/pull/21821#discussion_r887400868
(report message setting will be added with following commit...)

realms: refactor do_set_realm_stream().

---

docs/production/requirements.md

docs: Specify which CPU architectures are supported.

---

zerver/actions/realm_settings.py
zerver/lib/markdown/__init__.py

- python/mypy#3004
- python/mypy#10197

mypy: Add links to specific mypy bugs

---

frontend_tests/node_tests/dispatch.js
frontend_tests/node_tests/settings_org.js
frontend_tests/node_tests/settings_realm_domains.js
static/js/server_events_dispatch.js
static/js/settings_org.js
static/js/settings_realm_domains.js
static/styles/settings.css
static/templates/settings/admin_settings_modals.hbs
static/templates/settings/organization_permissions_admin.hbs
static/templates/settings/realm_domains_modal.hbs
tools/test-js-with-node

realm_domains_modal: Migrate modal to dialog_widget.

---

templates/zerver/help/view-and-edit-your-message-drafts.md

Updates help center article on viewing and editing drafts of messages for current documentation styles (less use of bold text, no Mac keys, tabs for Desktop/Web vs sub-headers, etc), which also preps page for mobile app documentation when drafts are supported.
<details>
<summary>Current help center page</summary>
</details>
<details>
<summary>Updated version</summary>
</details>

help-docs: Update article about message drafts.

---

zerver/models.py

To help contributors who are adding a new user setting for the first time, adds a clarifying comment about not adding any new settings to legacy settings dicts / groups.
Follow-up on [this PR comment / discussion](https://github.com/zulip/zulip/pull/21013#discussion_r853612033).

models: Add comment about where to add new user settings.

---

zerver/lib/email_notifications.py

[5.x] email_notifications: Give absolute path to html2text

---

static/js/stream_settings_ui.js

Fixes: Issue #21785 
https://user-images.githubusercontent.com/86338542/172916606-ca77ccb7-9ee3-4079-ae66-21eda22be7bf.mp4

Fix resetting of "Create Stream" form when clicked on header of "Manage Streams"

---

zproject/backends.py

`realm_access_control` is always a `dict`.

ldap: Remove unused isinstance check.

---

zerver/lib/emoji.py
zerver/tests/test_realm_emoji.py

This change tells the user what a valid emoji name looks like, so that
they know what to fix if the name they chose doesn't pass the validator.
CZO discussion [here](https://chat.zulip.org/#narrow/stream/137-feedback/topic/emoji.20validation/near/1399317)

emoji: Update emoji validation error messages with more information.

---

zerver/lib/markdown/__init__.py
zerver/lib/thumbnail.py
zerver/views/thumbnail.py

The doc was removed in 405bc8dabff9d8e602b12e53a7855a815e425b95

docs: Remove some outdated references to thumbnailing.md doc.

---

static/js/compose_ui.js
static/js/hotkey.js
static/js/message_scroll.js
static/styles/zulip.css
static/templates/compose.hbs

Fixes:  https://github.com/zulip/zulip/issues/21844
CZO: https://chat.zulip.org/#narrow/stream/49-development-help/topic/Scroll.20to.20bottom.20button.20flashes.20repeatedly.20after.20scrolling.20.E2.86.91 
Updated Animation from jQuery to CSS,
https://user-images.githubusercontent.com/63820270/177474318-eb43c15e-265f-408d-b813-418c5015fd73.mov

message_scroll: Hide scroll to bottom button with using keypress.

---

analytics/views/support.py

Two of the callers of `get_confirmations` uses a `QuerySet` of confirmation
objects instead of their ids to filter the confirmations. This refactors
`get_confirmations` so that it is typed to accept `QuerySet` of
confirmation objects as well.
Note that `Iterable[ConfirmationObjT]` does not work here because only
`QuerySet` can be dynamically resolved when passed to the RHS of the `in`
lookup.
This is a followup to #22292.
<del>TODO: Refactor to pass `QuerySet` only.</del> (probably not feasible, since we need to mutate `realms`.) …

confirmation: Refactor get_confirmations to accept confirmation objects.

---

zerver/actions/streams.py
zerver/management/commands/merge_streams.py
zerver/tests/test_realm.py

prep commit as per this code review:
https://github.com/zulip/zulip/pull/21821#discussion_r887398851

merge_streams: refactor and reorder.
