templates/zerver/help/manage-user-stream-subscriptions.md
templates/zerver/help/unsubscribe-from-a-stream.md

Fixes: Based on discussion at https://chat.zulip.org/#narrow/stream/14-GSoC/topic/Purushottam.20Tiwari/near/1402848.

help: Cross link help center docs for managing stream subscriptions.

---

static/js/pm_list_data.js

This is slightly more efficient and easier to read.

Move function declaration out of for loop.

---

zerver/context_processors.py
zerver/lib/test_helpers.py
zerver/middleware.py
zerver/tests/test_decorators.py
zerver/tests/test_event_system.py
zproject/computed_settings.py

`request.user` gets set in Django's `AuthenticationMiddleware`, which
runs after our `HostDomainMiddleware`.
This makes `hasattr` checks necessary in any code path that uses the
`request.user` attribute. In this case, there are functions in
`context_processors` that get called in the middleware.
Since neither `CsrfMiddleware` nor `HostDomainMiddleware` are required
to run before `AuthenticationMiddleware`, moving it two slots up in
`computed_settings` is sufficient to avoid the `hasattr` checks.
[Relevant discussion](https://chat.zulip.org/#narrow/stream/3-backend/topic/request.2Euser.20being.20nonexistent)
Individual …

middleware: Reorder middleware to avoid hasattr checks.

---

puppet/zulip/manifests/common.pp

Upgrade puppet versions

---

tools/tail-ses

This fixes having incompatible types of different items in the dictionary and makes `**identity_args` type-safe.

tail-ses: Add IdentityArgsDict.

---

zerver/actions/message_send.py

django-stubs types the return type of `query.values(...)` as a `TypedDict`.
This makes `Dict[str, Any]` that we have been using incompatible with it.
This PR addresses this issue by creating `TypedDict`s.
We use TypeGuard to ensure that `service_bot_tuples` is correctly
inferred to be `Tuple[int, int]` instead of `Tuple[int, Optional[int]]`.
Given that `bot_type` is optional for `ActiveUserDict`, we need to
narrow `row` to `ActiveBotUserDict` to make sure that `bot_type` is
non-optional. An advantage of this approach is that no assertions or
type casts are needed.
```diff
2c2
< Found 296 errors in 95 files (checked 1394 source files)
---
> Found 293 errors in 95 files (checked 1394 source files)
34,36d33
< zerver/actions/message_send.py error Argument 1 has incompatible type …
```

message_send: Extract ActiveUserDict for accurate typing.

---

corporate/lib/stripe_event_handler.py

<del>`GenericForeignKey` allows access from `Event` to attributes in a foreign model. django-stubs does not recognize that, and it likely involves some complexity to implement this feature. We can access these attributes after performing type narrowing with a `TypeGuard`.</del>
It turns out that the correct type annotation should be `PaymentIntent`. So `TypeGuard` is unnecessary. There is room for improvement for the decorator `error_handler`, given that it fails to catch this discrepency. …

corporate: Fix type annotation for decorated error handler function.

---

templates/zerver/help/change-the-default-language-for-your-organization.md
templates/zerver/help/change-your-language.md
templates/zerver/help/include/translation-project-info.md

This is a revision pass on #22353.

Update "Change your language" help center page

---

docs/documentation/helpcenter.md

Adds a section for writing and style guidelines to the [tutorial for writing help center articles](https://zulip.readthedocs.io/en/latest/documentation/helpcenter.html). 
[Relevant CZO discussion](https://chat.zulip.org/#narrow/stream/19-documentation/topic/format.20of.20keyboard.20shortcuts.20in.20help.20center.20docs/near/1384523)
**Notes about changes**:
- Moves the sections on 'Voice' and 'User interface' to be in the new section.
- Adds a section on 'Keyboard shortcuts'.
- It doesn't go into uppercase vs lowercase letters to represent keyboard keys, as that's still pending being made consistent in the help center documentation (#21753).
- The plus (+) sign is currently used in shortcuts with multiple keys and therefore documenting it now as such, but that is also pending removal as …

docs: Add 'Writing style' section to writing help doc tutorial.

---

static/js/message_edit.js

Fixes #19196
This immediately shows the menu for which messages to move when
the user can not edit the content of the message.
I also changed the visibility so that the menu stays visible once it was shown once, to avoid it getting shown and removed all the time, which would confuse the user.
How it looks when the message is not editable:
How it looks when the message is editable:

message-editing: Immediately show menu.

---

.github/workflows/production-suite.yml
docs/subsystems/release-checklist.md
tools/ci/Dockerfile.prod
tools/ci/build-docker-images
tools/ci/production-install
tools/ci/production-verify
tools/documentation_crawler/documentation_crawler/spiders/common/spiders.py

Test upgrades from .0 versions (or the earliest installable minor of each major)

---

zerver/actions/message_send.py

The type safety of a `TypeGuard` is unchecked by mypy.  While this particular `TypeGuard` is safe given the current context, one could imagine future changes that make it unsafe, so it’s preferable to avoid unchecked constructs whenever possible.

message_send: Remove TypeGuard

---

tools/release

`tools/build-release-tarball` respects `OUTPUT_DIR`, not `OUTDIR`.

release: Use the right variable to build predictable tarball path.

---

static/js/reload.js
static/js/server_events.js

Attempt to prevent reload loops

---

zerver/worker/queue_processors.py

This change was added in
https://github.com/zulip/zulip/commit/c93f1d4eda71ddcca5ba05d0bf9fbfc8895829e2#diff-d88010b113b79080cab5885fdfbbb56ae2d380cb601d8f520621b3361ad8cebc.
`message.content` cannot be `None` by the model definition.
```diff
5c5
< Found 205 errors in 74 files (checked 1400 source files)
---
> Found 204 errors in 74 files (checked 1400 source files)
227d226
< zerver/worker/queue_processors.py error Statement is unreachable  [unreachable]
```
Fixes:  …

queue_processor: Remove unreachable code.

---

static/js/admin.js
static/templates/settings/organization_settings_admin.hbs
templates/zerver/help/change-the-default-language-for-your-organization.md
templates/zerver/help/change-your-language.md
templates/zerver/help/configure-multi-language-search.md
templates/zerver/help/configure-notification-bot.md
templates/zerver/help/create-a-stream.md
templates/zerver/help/digest-emails.md
templates/zerver/help/disable-welcome-emails.md
templates/zerver/help/include/customize-settings-for-new-users.md
templates/zerver/help/include/sidebar_index.md
templates/zerver/help/invite-new-users.md
zerver/openapi/zulip.yaml

Revised version of #22342.
Updates made:
- Squashed **Organization settings** UI changes into 1st commit.
- All help center and API documentation updates in 2nd commit.
**Notes**:
- For the help center left sidebar title for the **Organization language for automated messages and invitation emails**, I went with the shortened version of **Configure organization language**. I felt like the article itself makes it clear what the setting is doing. See screenshot below.
- I also used that shortened version for the header for the instructions block on that page. While I removed 'Configure' from the main article title and instead used **Organization language for automated ...**; again see same screenshot below.
- This PR does not rename / redirect the URL / file name for …

Update org settings and help center "Notifications" terminology

---

zerver/views/documentation.py

- The calling arguments here are completely wrong. The first argument
should be `request`, and `self` should never get passed to `.get`.
Because `TemplateView` happened to not use `request`, and we happened
to pass `article` as a keyword argument, this error slipped through.
- The supertype contains `*args` and `**kwargs`, this adapts the signature
of the `get` method to make MarkdownDirectoryView compatible with it.
```diff
5c5
< Found 205 errors in 74 files (checked 1400 source files)
---
> Found 203 errors in 73 files (checked 1400 source files)
212,217d211
< zerver/views/documentation.py error Signature of "get" incompatible with supertype "TemplateView"  [override]
< zerver/views/documentation.py note          def get(self, request HttpRequest, *args Any, **kwargs …
```

documentation: Fix MarkdownDirectoryView.get.

---

puppet/zulip_ops/files/grafana/grafana.ini

This avoids the need to explicitly create new users in Grafana, by
simply trusting Teleport.

grafana: Enable auto-sign-up.

---

templates/zerver/help/import-from-slack.md

docs: Document that you need to copy slack-data.zip onto the server.

---

docs/production/export-and-import.md
scripts/setup/restore-backup

Various small improvement to restore-backup

---

zerver/views/development/email_log.py

Instead of using `request.POST` to access `forward_address` for the parameter used in `set_forward_address` in `email_page`, adds `has_request_variable` decorator and an optional `forward_address` parameter through the `REQ` framework.
Adds an assertion that `forward_address` is not `None` for `POST` requests.
**Notes**:
- Because the `GET` requests will not have `forward_address`, the default is `None` and the parameter is `Optional[str]`.
- Because the `POST` requests should always have a `forward_address` parameter, I added an assert statement after the request method is checked. Some sort of check/assertion is needed here so that the parameter for `set_forward_address` is `str`.
- Another option here would be to put `and forward_address is not None` with the request method check. I …

email-log: Move `forward_address` to `REQ` framework.

---

zerver/tests/test_email_log.py

Previously if `test_forward_address_details` failed, the file created when setting the `forward_address` may not have been removed, which would then cause an `EmailNotDeliveredException` to be raised when then creating a new user in the dev environment.
Wraps the test in a `try` block, with a `finally` block for the call to remove the file.
**Notes**:
- To recreate the issue, I added a failing assertion statement in the test (e.g. `self.assertFalse(True)`) before the `os.remove` call, ran the test (here I verified the file hadn't been deleted on the file system), and then started the development server and tried to create a new user.
- Adding the try/finally structure with the failing assertion statement resulted in the test failing, but the file was deleted from the system. In this case, …

tests: Remove `FORWARD_ADDRESS_CONFIG_FILE` created in test.

---

docs/overview/changelog.md
version.py

Release Zulip Server 5.5.

---

docs/subsystems/hashchange-system.md

Fixes missing bracket in the [URL hashes and deep learning documentation](https://zulip.readthedocs.io/en/latest/subsystems/hashchange-system.html) page.

docs: Fix typo in `hashchange-system.md`.

---

templates/zerver/help/include/mobile-profile-menu.md
templates/zerver/help/include/self-user-actions-menu.md
templates/zerver/help/status-and-availability.md

Adds step-by-step instructions for mobile app users reusing the `{!mobile-profile-menu.md!}` macro from #22423.
<details>
</details>

help-docs: Document "Status and availability" mobile features.

---

zerver/tests/test_urls.py

`_callback_str` was removed in Django in 1.10, and other logic relevant
to that particular attribute was removed in
32849b80ad96ce898c4aab10b1029b398c353c99, but not to its entirety. It
does not make sense to fall back to `_callback_str`. The
`get_callback_string` helper is no longer needed.
```diff
5c5
< Found 200 errors in 71 files (checked 1401 source files)
---
> Found 199 errors in 70 files (checked 1401 source files)
204d203
< zerver/tests/test_urls.py error Argument 1 to "get_callback_string" of "URLResolutionTest" has incompatible type "Union[URLPattern, URLResolver]"; expected "URLPattern"  [arg-type]
``` …

test_urls: Remove legacy hasattr check.

---

zerver/views/development/integrations.py

Since we in fact are using the django test client to generate a response
here, the return type should be `TestHttpResponse` instead.
```diff
5c5
< Found 202 errors in 71 files (checked 1401 source files)
---
> Found 200 errors in 70 files (checked 1401 source files)
211,212d210
< zerver/views/development/integrations.py error Incompatible return value type (got "_MonkeyPatchedWSGIResponse", expected "HttpResponse")  [return-value]
< zerver/views/development/integrations.py error Argument 5 to "post" of "Client" has incompatible type "**Dict[str, str]"; expected "bool"  [arg-type]
``` …

integrations: Use TestHttpResponse to type send_webhook_fixture_message. 

---

zerver/lib/user_status.py
zerver/tests/test_user_status.py

This adds a new `TypedDict` to type `format_user_status` more accurately.
The shared fields of `RawUserInfoDict` and `UserInfoDict` could have
been reused if they both require all keys or none. This is unfortunately
not the case, because subclassing does not override `__total__`.
```diff
141d140
< zerver/lib/user_status.py error Argument 1 to "format_user_status" has incompatible type "TypedDict({'user_profile_id' int, 'status' int, 'status_text' str, 'emoji_name' str, 'emoji_code' str, 'reaction_type' str})"; expected "Dict[str, Any]"  [arg-type]
``` …

user_status: Add UserInfoDict.

---

zerver/lib/users.py

These default values are unused by the callers and incompatible with the
`Service` model.
```diff
5c5
< Found 201 errors in 73 files (checked 1403 source files)
---
> Found 198 errors in 72 files (checked 1403 source files)
136,138d135
< zerver/lib/users.py error Incompatible type for "base_url" of "Service" (got "Optional[str]", expected "Union[str, Combinable]")  [misc]
< zerver/lib/users.py error Incompatible type for "interface" of "Service" (got "Optional[int]", expected "Union[float, int, str, Combinable]")  [misc]
< zerver/lib/users.py error Incompatible type for "token" of "Service" (got "Optional[str]", expected "Union[str, Combinable]")  [misc]
``` …

users: Remove default values for add_service.

---

zerver/actions/user_groups.py

We create a `TypedDict` `MemberGroupUsersDict` to better type the lists of `ValuesQuerySet`.
```diff
5c5
< Found 202 errors in 71 files (checked 1401 source files)
---
> Found 195 errors in 70 files (checked 1401 source files)
27,37d26
< zerver/actions/user_groups.py error Argument 1 to "list" has incompatible type "_QuerySet[UserProfile, TypedDict({'id' int, 'role' int, 'date_joined' datetime})]"; expected "Iterable[Dict[str, Union[int, datetime]]]"  [arg-type]
< zerver/actions/user_groups.py error Argument 1 to "list" has incompatible type "_QuerySet[UserProfile, TypedDict({'id' int, 'role' int, 'date_joined' datetime})]"; expected "Iterable[Dict[str, Union[int, datetime]]]"  [arg-type]
< zerver/actions/user_groups.py error Argument 1 to "list" has incompatible type …
```

user_groups: Add MemberGroupUsersDict.

---

static/js/admin.js
static/js/stream_edit.js
static/js/stream_settings_ui.js
static/styles/app_components.css
static/styles/dark_theme.css
static/templates/settings/upgrade_tip_widget.hbs
zerver/models.py

- First commit only updates the backend error message sent for limited plans.
- Second commit updates the banner in webapp to mention about sponsorship.
Fixes:  #22161

Update upgrade banner to mention about sponsorship to non-business orgs.

---

zerver/views/users.py

The `RateLimited` exception can be caught by `JsonErrorHandler`, so it
is not necessary to have the try block here. It is also invalid to pass
a string to initialize `RateLimited`.
```diff
5c5
< Found 200 errors in 71 files (checked 1401 source files)
---
> Found 199 errors in 70 files (checked 1401 source files)
216d215
< zerver/views/users.py error Argument 1 to "RateLimited" has incompatible type "str"; expected "Optional[float]"  [arg-type]
``` …

avatar: Remove unnecessary try...except statement.

---

static/styles/settings.css

PR for [issue#21410: Improve styling for bot editing modals
](https://github.com/zulip/zulip/issues/21410)
In this PR the font style and appearance are made consistent through edit bot(personal) and manage bot(org) settings.
First, commit :
- Font style is made consistent.
- added consistent spacing between components.
Second commit : 
- Spacing to avatar component(because it was left out in the previous commit).

fonts style and spacing between components changed.

---

frontend_tests/node_tests/bot_data.js
static/js/bot_data.js
static/js/settings_users.js
static/templates/confirm_dialog/confirm_deactivate_user.hbs

confirm_deactivate_user: Provide additional information about user.

---

zerver/tests/test_email_mirror.py

Fixes #22585.
core team: up to you if you think these extra tests are helpful. I found them useful in debugging this issue.

unittests: add a couple of tests for inbound email edge case.

---

static/styles/modal.css

modal: Use font-weight 600 for modal title.

---

templates/corporate/jobs.html

1. First commit removed technical writer posting.
2. Second commit adds senior frontend engineer job posting.

Update /jobs page

---

static/templates/invite_subscription.hbs
zerver/openapi/zulip.yaml

Fixes some in-app and documentation references to to new user announcements and new stream announcements that were still using 'notifications' to refer them. These were missed in the original pass for updating this language.
This is a follow-up to #22516.
---
<details>
<summary>Invite users modal</summary>
</details>
<details>
<summary>API Get events updates</summary>
[Current documentation](https://zulip.com/api/get-events#realm-update_dict)
</details>
--- …

Fix references to new user and stream announcments.

---

static/js/settings_user_groups.js
static/templates/confirm_dialog/confirm_delete_user.hbs

Confirmation modal message is changed for user group delete to improve user experience.
Fixes: #22593
Screenshot of Result:

settings: Improve delete user group confirmation modal.

---

static/js/message_edit.js
static/templates/confirm_dialog/confirm_delete_message.hbs

delete message: Updated modal text.

---

frontend_tests/node_tests/upload.js
static/js/upload.js

This warns the user when the upload fails because it is too big. I added a check so that the user will know why the upload failed.
Fixes: 
issue fixed #21978. 
**Before**
**After**

fix:Checking if file size is too big

---

templates/zerver/help/using-zulip-via-email.md

Updates the 2nd instruction block in the "Using Zulip via email" help center article to directly reference the section header (**Notifications triggers**) for clarity and consistency with other help center references to this user settings area.
Compare with similar instruction blocks for current help center article on [PMs, mentions, and alerts](https://zulip.com/help/pm-mention-alert-notifications)
[Current documentation](https://zulip.com/help/using-zulip-via-email#setup-instructions-for-email-users)
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/versi …

help-docs: Clarify instructions for setting email notifications.

---

zerver/lib/test_runner.py

This reverts part of commit 143206795949d85545d1a76f634d23b5b780898f (#17047). The spooky warnings foretold by the comment don’t seem to show up.
Inspired by #22577.

test_runner: Remove _destroy_test_db monkey patch

---

zerver/tests/test_logging_handlers.py

We refactor test cases with `mock.patch` and `delattr` to avoid setting attributes of `HttpRequest` with incompatible types.
```diff
6c6
< Found 134 errors in 40 files (checked 1405 source files)
---
> Found 131 errors in 39 files (checked 1405 source files)
122,124d121
< zerver/tests/test_logging_handlers.py error Cannot assign to a method  [assignment]
< zerver/tests/test_logging_handlers.py error Cannot assign to a method  [assignment]
< zerver/tests/test_logging_handlers.py error Incompatible types in assignment (expression has type "None", variable has type "Union[UserProfile, AnonymousUser]")  [assignment]
```
Fixes:  …

test_logging_handlers: Fix type errors in test_request.

---

zerver/lib/upload.py
zerver/views/upload.py

This replaces `File` with `UploadedFile` as appropriate.
```diff
6c6
< Found 136 errors in 40 files (checked 1405 source files)
---
> Found 134 errors in 39 files (checked 1405 source files)
87,88d86
< zerver/lib/upload.py error Missing type parameters for generic type "File"  [type-arg]
< zerver/lib/upload.py error Missing type parameters for generic type "File"  [type-arg]
```

upload: Improve type annotations for files

---

zproject/email_backends.py

The base class of `EmailLogBackEnd` has the methods to accept `Sequence` of
`EmailMessage`.
Because our implementation in fact only supports `EmailMultiAlternatives`,
isinstance checks with assertions need to be added along with the
signature change.
Errors affected:
```diff
6c6
< Found 136 errors in 40 files (checked 1405 source files)
---
> Found 134 errors in 39 files (checked 1405 source files)
156,159d155
< zproject/email_backends.py error Incompatible types in assignment (expression has type "Tuple[Union[bytes, EmailMessage, Message, str], ...]", target has type "Tuple[Union[bytes, EmailMessage, Message, SafeMIMEText, str], str]")  [assignment]
< zproject/email_backends.py error Argument 1 of "send_messages" is incompatible with supertype "BaseEmailBackend"; supertype defines the …
```

email_backends: Improve type annotations for EmailLogBackEnd. 

---

zerver/data_import/import_util.py

We construct model instances in the import tool solely for the purpose
of using them with the `model_to_dict` helper that returns a
dictionary. Passing `float` to these models' `DateTimeField` is not
accepted by the type checker. Modifying the dictionary instead avoids
this typing issue.
Modifying the dictionary value should yield the same behavior from
[`model_to_dict`](https://github.com/django/django/blob/2aa6fb2121fb6dee1b65e90c85660d6bfab66334/django/forms/models.py#L93-L115), where attributes like `date_created` were simply access with `value_from_object` before.
However, it feels wrong in the first place to pass `float` to the `DateTimeField` given that
Django does not automatically handle `float` for this field as far as I know. This code has no
coverage in `test_import_export` so …

import_util: Post-modify date fields with float values.

---

zerver/lib/types.py
zerver/tests/test_auth_backends.py
zproject/backends.py
zproject/default_settings.py
zproject/prod_settings_template.py
zproject/test_extra_settings.py

In https://github.com/zulip/zulip/commit/3b4f8cc85b532554054fe9c1b895ff978ce23e90,
we added support to `auto_signup`, but this field was not defined in
`SAMLIdPConfigDict`, causing mypy type error in
`SAMLAuthenBackendTest.test_social_auth_registration_auto_signup`.
There is also another error
oidc_setting_dict = copy.deepcopy(settings.SOCIAL_AUTH_OIDC_ENABLED_IDPS)
idp_settings_dict = list(oidc_setting_dict.values())[0]  # Incompatible types in assignment (expression has type "bool", target has type "Optional[str]")  [assignment]
idp_settings_dict["auto_signup"] = True
that I'm uncertain about what to do with it. As `settings.SOCIAL_AUTH_OIDC_ENABLED_IDPS` does not have the same structure as `SOCIAL_AUTH_SAML_ENABLED_IDPS`. …

types: Fix auto_signup related errors.

---

zilencer/management/commands/rundjangoserver.py

So that we can remove our `FakeStdout` wrapper.
```diff
16c16
< Found 104 errors in 34 files (checked 1406 source files)
---
> Found 103 errors in 34 files (checked 1406 source files)
116d115
< zilencer/management/commands/rundjangoserver.py error Incompatible types in assignment (expression has type "Writable", base class "BaseCommand" defined the type as "OutputWrapper")  [assignment]
```

rundjangoserver: Use style_func for output filtering.

---

zerver/lib/cache_helpers.py

This adds an assertion ensuring the type of `store` before accessing the
`cache_key` attribute that does not exist in the base class. Also note
that `.decode` returns `Dict[str, Any]` instead of a `str`.
Fixes: 

cache: Fix type annotation for session_cache_items.

---

zerver/lib/onboarding.py

Initializing a dictionary from an iterable requires the each item to be
a tuple containg a key and a value. `mypy_django_plugin` cannot infer
the number of items in an queryset with annotated values, so we have to
explicitly unpack each row with a dictionary comprehension here.
```diff
2c2
< Found 82 errors in 29 files (checked 1406 source files)
---
> Found 80 errors in 28 files (checked 1406 source files)
45,46d44
< zerver/lib/onboarding.py error Need type annotation for "bot_counts" (hint "bot_counts Dict[<type>, <type>] = ...")  [var-annotated]
< zerver/lib/onboarding.py error Argument 1 to "dict" has incompatible type "_QuerySet[WithAnnotations[zerver__models__UserProfile], Tuple[Any, ...]]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
``` …

onboarding: Use dictionary comprehension for dict initialization.

---

zerver/lib/upload.py
zerver/tests/test_upload.py
zerver/views/upload.py

Instead of using `request.GET` to access `mimetype` when getting information about the uploaded file, adds `has_request_variable` decorator to outer view function (`upload_file_backend`) and an optional `mimetype` parameter through the `REQ` framework.
**Notes**:
- Currently marks `mimetype` as `documentation_pending = True` as the endpoint documentation does not include that possible url parameter. Do we want to add this to the documentation now / in the future? If not, then should this be `intentionally_undocumented = True`?
Relevant [CZO conversation](https://chat.zulip.org/#narrow/stream/3-backend/topic/ignored_parameters_unsupported/near/1412794). …

upload: Remove `mimetype` url parameter in `get_file_info`. 

---

zerver/data_import/rocketchat.py

Fix three odd bugs found in a large rocketchat export.
It's not clear if these are database corruption or intentional edge cases.  As such, I'm not sure if it makes sense to make tests for them.

Rocketchat import weird edge cases

---

zerver/models.py
zerver/tests/test_realm_emoji.py

In certain cases, we call `RealmEmoji.save()` before the filename
becomes available. This result in getting invalid urls generated and
flushed. Normally we call it again shortly after, making it harder to
trigger this bug.
Fixes #22552
```diff
5c5
< Found 74 errors in 27 files (checked 1406 source files)
---
> Found 72 errors in 27 files (checked 1406 source files)
57,58d56
< zerver/models.py error Argument 1 to "get_emoji_url" has incompatible type "Optional[str]"; expected "str"  [arg-type]
< zerver/models.py error Argument 1 to "get_emoji_url" has incompatible type "Optional[str]"; expected "str"  [arg-type]
``` …

cache: Avoid flushing invalid cache for realm emoji.

---

templates/zerver/help/include/rest-endpoints.md
zerver/openapi/python_examples.py
zerver/openapi/zulip.yaml
zerver/tests/test_openapi.py

This documents the `/default_streams` API endpoint.

api: Document /default_streams API endpoint.

---

frontend_tests/node_tests/message_list_view.js
frontend_tests/puppeteer_tests/message-basics.ts
static/js/message_list_view.js

narrow: /streams/public should not have bookends.

---

frontend_tests/puppeteer_tests/message-basics.ts

It was introduced in
https://github.com/zulip/zulip/commit/56b2b838ee17cbce191f40704df4cfec710a2ece commit.
It fixes `test_narrow_public_streams` test which checks
that, there are no bookends in ` /streams/public`. The
issue was there were no bookends by default when we
were checking in the Denmark stream. We fix this by
unsubscribing from the Denmark stream which will
create a bookend.
Fixes: 

puppeteer: Fix `test_narrow_public_streams` test  in `message-basics.ts`.

---

zerver/lib/user_topics.py

This ensures type safety by not mutating the original queryset values,
that django-stubs to type as a TypedDict without total=False.
```diff
2c2
< Found 20 errors in 9 files (checked 1407 source files)
---
> Found 17 errors in 8 files (checked 1407 source files)
7,9d6
< zerver/lib/user_topics.py error TypedDict key "stream__name" cannot be deleted  [misc]
< zerver/lib/user_topics.py error Value of "last_updated" has incompatible type "int"; expected "datetime"  [typeddict-item]
< zerver/lib/user_topics.py error Incompatible return value type (got "List[TypedDict({'stream_id' int, 'stream__name' str, 'topic_name' str, 'last_updated' datetime, 'visibility_policy' int})]", expected "List[UserTopicDict]")  [return-value]
``` …

user_topics: Refactor the construction loop for UserTopicDict.

---

static/styles/settings.css

Fixes #20583 
It took me a little bit of time but i was able to figure it out , here is the proof of work for the same.
https://user-images.githubusercontent.com/72331432/148014863-3aff992f-ddb5-4f4f-b113-7a14f4fbf617.mp4

Fix: Fixes #20583 button alignment issue

---

frontend_tests/node_tests/top_left_corner.js
static/js/narrow.js
static/js/pm_list.js
static/js/top_left_corner.js

This commit is a preparatory commit for #20870, it introduces
`handle_narrow_deactivated` and `handle_narrow_activated`
functions in pm_list.js, separately from top_left_corner.js,
to reduce the complexity of handling private messages section
separately.
Fixes: 

pm_list: Handle narrow functions separately for pm_section.

---

zerver/migrations/0043_realm_filter_validators.py

This adds a one-off decorator that discards the return value of the
validator before using it for migration operations.
See also: https://github.com/typeddjango/django-stubs/pull/1078.
```diff
6c6
< Found 136 errors in 40 files (checked 1405 source files)
---
> Found 134 errors in 39 files (checked 1405 source files)
95,96d94
< zerver/migrations/0043_realm_filter_validators.py error List item 0 has incompatible type "Callable[[str], Pattern[str]]"; expected "Callable[[Any], None]"  [list-item]
< zerver/migrations/0043_realm_filter_validators.py error List item 0 has incompatible type "Type[URLValidator]"; expected "Callable[[Any], None]"  [list-item]
``` …

migrations: Remove unnecessary migration operations.

---

zerver/actions/bots.py
zerver/actions/streams.py
zerver/decorator.py
zerver/lib/export.py
zerver/lib/import_realm.py
zerver/lib/logging_util.py
zerver/lib/topic.py
zerver/lib/types.py
zerver/models.py
zerver/tests/test_signup.py
zerver/tests/test_zephyr.py
zerver/views/auth.py
zerver/views/zephyr.py
zproject/legacy_urls.py

django-stubs: Fix miscellaneous typing errors. 

---

frontend_tests/node_tests/dispatch_subs.js
frontend_tests/node_tests/stream_events.js
frontend_tests/puppeteer_lib/common.ts
static/js/server_events_dispatch.js
static/js/stream_events.js
static/js/stream_list.js
static/styles/left_sidebar.css
static/templates/left_sidebar.hbs
static/templates/subscribe_to_more_streams.hbs

Add Stream Count Information to Left sidebar

---

zerver/tests/test_message_fetch.py

search: add unittests for pgroonga parts-of-URL search.

---

frontend_tests/node_tests/alert_words_ui.js
frontend_tests/puppeteer_tests/settings.ts
static/js/alert_words_ui.js
static/styles/settings.css
static/templates/settings/add_alert_word.hbs
static/templates/settings/alert_word_settings.hbs
tools/test-js-with-node

alert word: Convert inline form to modal.

---

static/js/info_overlay.js
static/styles/widgets.css

documentation (user): Document `/poll` in `?` help widget.
To make it easier for users to make polls, their syntax is documented
using an example along with its (non dynamic) rendered version.
Fixes: #18588.

documentation (user): Document /poll in ? help widget.

---

docs/production/multiple-organizations.md

Inspired by https://chat.zulip.org/#narrow/stream/31-production-help/topic/realm.20creation.20link.20with.20pre-set.20name/near/1420432.

Improve documentation for multiple subdomains

---

frontend_tests/puppeteer_tests/navigation.ts

The reason for the flake was we were not waiting for the
settings modal to open completely.
To fix this we now wait until the profile tab is focused to
detect if the settings modal is open completely (i.e ready
for the interaction).
Tested the code by running in loop for 100 times in [CI](https://github.com/Riken-Shah/zulip/runs/7870293534?check_suite_focus=true).
Fixes: 

puppeteer: Fix flake in`navigation.ts`.

---

static/js/message_view_header.js

We forgot to add logic to construct the correct selector here when we
switched from a font awesome globe icon to a .zulip-icon, which resulted
in the new globe icon only having the default color.
This commit adds the missing piece to fix that.
Fixes: The globe icon not being colored according to the stream in the navbar.
Before:
After:

message_view_header: Color web public stream globe icon.

---

frontend_tests/node_tests/compose.js
frontend_tests/node_tests/echo.js
frontend_tests/node_tests/event_status.js
frontend_tests/node_tests/people.js
frontend_tests/node_tests/stream_list.js
frontend_tests/node_tests/watchdog.js
frontend_tests/zjsunit/index.js
frontend_tests/zjsunit/test.js
tools/test-js-with-node

Support asynchronous Node tests; reenable event_status test

---

static/js/settings_org.js

Follow up of #21837 as [discussed](https://github.com/zulip/zulip/pull/21837#discussion_r944978098)

Deduplicate code for enabling and disabling message delete limit setting.

---

frontend_tests/zjsunit/namespace.js

zjsunit: Support asynchronous overrides

---

static/js/read_receipts.js

The previous logic was just using the `.avatar_url` field on objects
returned by `people.js`, which can be null/undefined.
Fixes: 

read_receipts: Fix rendering of avatars for some Gravatar users.

---

static/js/settings_config.ts

This PR updates the label for realm-level default of send_read_receipts as discussed [here](https://chat.zulip.org/#narrow/stream/101-design/topic/read-receipts.20UI.20.2318935/near/1422017).

settings: Update label for realm-level default of send_read_receipts.

---

static/js/settings_account.js

user profile modal: Don't close settings.

---

static/js/message_lists.js
static/js/recent_topics_ui.js
static/js/unread_ops.js

I can't actually prove this fixed the bug in https://chat.zulip.org/#narrow/stream/9-issues/topic/Lost.20unreads.20in.20recent.20topics/near/1422941, but I think it may.

Partially revert recent topics logic from #22452

---

static/images/help/mobile-info-circle-icon.svg
static/styles/portico/markdown.css
templates/zerver/help/include/mobile-stream-settings-menu-tip.md
templates/zerver/help/view-someones-profile.md

Refactors the instructions for Desktop/Web and adds instructions for mobile app users.
Consolidates the two ways of viewing a user profile into one set of instructions under a single Desktop/Web tab.
<details>
</details>

help-docs: Document "View user profile" mobile app feature.

---

README.md
frontend_tests/node_tests/copy_and_paste.js
templates/zerver/footer.html

We should rearrange Zulip's developer docs to make it easier to find the documentation that new contributors need.
Name changes
Rename [Code contribution guide](https://zulip.readthedocs.io/en/latest/contributing/index.html) section -> "**Contributing to Zulip**".
Rename [Contributing to Zulip](https://zulip.readthedocs.io/en/latest/overview/contributing.html) page -> "**Contributing guide**".
Organizational changes to the newly-named "**Contributing to Zulip**":
Move the newly-named "**Contributing guide**" to the top of this section.
Move up "**Zulip code of Conduct**", as the second link of this section.
Move down "**Licensing**", as the last link of this section.
Move "**Accessibility**" just below "**HTML and CSS**" in **Subsystems** section.
Update all links according to the changes …

docs: Reorganize sections and pages about contributing to Zulip.

---

zerver/actions/presence.py
zerver/actions/user_settings.py
zerver/tests/test_event_system.py
zerver/tests/test_events.py

Fixes #21180.
(issues resolved)
see CZO discussion: https://chat.zulip.org/#narrow/stream/2-general/topic/.22unavailable.22.20status

Send presence update event when user toggles presence_enabled user setting

---

tools/test-backend
zerver/tests/test_email_notifications.py

responding to [code review](https://github.com/zulip/zulip/pull/21835/files#r865444153)

testing: 100% test coverage for zerver/lib/email_notifications.py

---

templates/zerver/help/import-from-slack.md
zerver/lib/markdown/tabbed_sections.py

Testing:
- I tested the export process with a Slack org (on the Free plan).
- I previewed the page and manually tested the links.
The page is too long to be easy to share as a screenshot, so please pull down the PR to preview.

help center: Rewrite Import from Slack documentation.

---

frontend_tests/node_tests/drafts.js
frontend_tests/puppeteer_tests/drafts.ts
static/js/drafts.js
static/styles/drafts.css
static/templates/draft_table_body.hbs

 Create a section to show drafts from the current conversation. 

---

corporate/urls.py
corporate/views/portico.py
static/js/portico/communities.js
static/styles/portico/integrations.css
static/styles/portico/landing_page.css
templates/corporate/communities.html
templates/zerver/integrations/index.html
tools/webpack.assets.json
zerver/lib/templates.py
zerver/tests/test_docs.py

Page link - /open-organizations/
Fixes #22020

Open Organizations landing page

---

.github/workflows/production-suite.yml

Caught by [actionlint](https://github.com/rhysd/actionlint).

ci: Fix custom database name test

---

zerver/webhooks/lidarr/view.py
zerver/webhooks/mention/view.py
zerver/webhooks/netlify/view.py
zerver/webhooks/newrelic/view.py
zerver/webhooks/opencollective/view.py
zerver/webhooks/opsgenie/view.py
zerver/webhooks/pagerduty/view.py
zerver/webhooks/pingdom/view.py
zerver/webhooks/radarr/view.py
zerver/webhooks/raygun/view.py
zerver/webhooks/reviewboard/view.py
zerver/webhooks/semaphore/view.py
zerver/webhooks/solano/view.py
zerver/webhooks/sonarqube/view.py
zerver/webhooks/sonarr/view.py
zerver/webhooks/splunk/view.py
zerver/webhooks/statuspage/view.py
zerver/webhooks/stripe/view.py
zerver/webhooks/taiga/view.py
zerver/webhooks/teamcity/view.py
zerver/webhooks/thinkst/view.py
zerver/webhooks/trello/view/__init__.py
zerver/webhooks/trello/view/board_actions.py
zerver/webhooks/trello/view/card_actions.py
zerver/webhooks/updown/view.py
zerver/webhooks/uptimerobot/view.py
zerver/webhooks/zabbix/view.py
zerver/webhooks/zapier/view.py

This PR consists of a WIP migration of integrations to use the WildValue system, starting from the end.
Fixes part of #21525.

[WIP] Integrations' Wildvalue migration (from the end)

---

static/js/user_status_ui.js

The new option "At the office" is now displayed to user to set it as their status.
Fixes:  #22828 

user_status_ui: Add "At the office" option.

---

templates/zerver/help/zulip-cloud-billing.md

Testing: Tested link and previewed changes.
Current page: https://zulip.com/help/zulip-cloud-billing

help center: Add question about Free plan to Zulip Cloud Billing page.

---

static/styles/zulip.css

This issue is probably with the upstream bug in
`flatpickr` but we can fix it for us by specifying minimum
height to the input.
Fixes #22698
Before | After
-- | --

timepicker: Fix hours and minutes input getting squeeze in safari.

---

zerver/actions/message_flags.py
zerver/lib/push_notifications.py
zerver/models.py
zerver/tests/test_message_flags.py
zerver/worker/queue_processors.py

Fixes https://github.com/zulip/zulip/issues/19054
Was able to reproduce the deadlock situation by 
1. Increase the number of messages in the database by `./manage.py populate_db -n1000000`
2. Mark all messages unread by `./manage.py mark_all_messages_unread`
3. Call `/mark_stream_as_read?stream_id=<foo_stream_id>` — which will take few minutes when stream has ~100k unread messages
4. While the call above is running, repeatedly call `/messages/flags?messages=[<some messages ids in foo_stream>]&op=add&flag=read` until deadlock is hit

usermessage: Use select for update with order by in bulk usermessage update.

---

frontend_tests/puppeteer_tests/realm-playground.ts
static/js/settings_playgrounds.js
static/templates/confirm_dialog/confirm_delete_playground.hbs

delete code playground: Add confirmation dialog.

---

static/js/settings_exports.js
static/templates/confirm_dialog/confirm_delete_data_export.hbs

delete data exports: Add confirmation dialog.

---

frontend_tests/puppeteer_tests/realm-linkifier.ts
static/js/settings_linkifiers.js
static/templates/confirm_dialog/confirm_delete_linkifier.hbs

delete linkifier: Add confirmation dialog.

---

static/js/hash_util.js
static/js/stream_edit_subscribers.js
static/js/ui_init.js
static/js/user_group_edit.js
static/js/user_group_edit_members.js
static/js/user_group_ui_updates.js
static/js/user_groups_settings_ui.js
static/styles/dark_theme.css
static/styles/subscriptions.css
static/templates/confirm_dialog/confirm_unsubscribe_private_stream.hbs
static/templates/stream_settings/stream_member_list_entry.hbs
static/templates/user_group_settings/change_user_group_info_modal.hbs
static/templates/user_group_settings/user_group_members.hbs
static/templates/user_group_settings/user_group_settings.hbs
tools/test-js-with-node

Added features for user group name/description and member ship edit on right panel of `#groups` overlay.  Tried to replicate the behavior of members table and member add remove feature similar to stream settings but varies slightly due to difference in behavior of API of user group member add/remove endpoint.
Fixes a part of : #19526

Implement edit features in user group settings overlay.

---

webpack.config.ts

webpack: Add a hook to print a compilation successful message.

---

docs/documentation/integrations.md
templates/zerver/help/include/create-bot-construct-url.md
templates/zerver/help/include/event-filtering-instruction.md
zerver/lib/integrations.py
zerver/views/documentation.py
zerver/webhooks/uptimerobot/doc.md

We create `event-filter-instruction.md` and add it to
`create-bot-construct-url.md`. This allows the user to keep track of the
supported event types for most of the integrations that implement this
feature. Note that not all integrations use `create-bot-construct-url.md`.
This revives #19262 and is a part of #18392.
For example, the documentation for `front` looks like this:
`UptimeRobot` (that does not use `create-bot-construct-url.md`): …

integrations: Add documentation for the event filtering system.

---

frontend_tests/puppeteer_tests/admin.ts

The reason for the flake was we were not waiting enough time for the dropdown to render search results when we type `rome`.
To fix this, We are waiting until the dropdown input value evaluates to be `rome`.
We also update variable name from
`verona_in_dropdown` to correct `rome_in_dropdown`.
Tested the changes by running [100x in CI](https://github.com/Riken-Shah/zulip/runs/8269348475?check_suite_focus=true).
Fixes: 

puppeteer: Fix dropdown click flake in `admin.ts`.

---

static/js/read_receipts.js

This is a proposed fix to allow the pluralization forms to correctly show up in Transifex's UI for the translators.
Context can be found here:
https://chat.zulip.org/#narrow/stream/58-translation/topic/ICU.20Message.20syntax/near/1431813
This is a followup to #22837.
Signed-off-by: Zixuan James Li <p359101898@gmail.com>

read_receipts: Alter translation string in accordance with Transifex.

---

corporate/views/portico.py
templates/corporate/communities.html

discussion: https://chat.zulip.org/#narrow/stream/57-core-team/topic/open.20communities.20directory/near/1434114

Minor changes to communities page.

---

zerver/lib/export.py
zerver/lib/import_realm.py
zerver/tests/test_import_export.py

We do not need direct_members and direct_subgroups field of UserGroup objects in the export data since we already have UserGroupMembership and GroupGroupMembership object data.
While importing we keep these fields empty when creating UserGroup objects and direct_members and direct_subgroups fields will get set when UserGroupMembership and
GroupGroupMembership objects are created.
This change will also help us in further changes when we will change the order of importing to import UserGroup objects just after Realm objects.
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/version-control.html) …

export: Do not export direct_members and direct_subgroups field.

---

static/templates/settings/organization_permissions_admin.hbs

org settings: Move invitations required checkbox to the top.

---

zerver/models.py

An attempt to improve the  documentation for these models
https://chat.zulip.org/#narrow/stream/19-documentation/topic/Doc.20on.20the.20Message.2FRecipient.20model

models: Improve comment documentation around Recipients and Huddles.

---

templates/corporate/jobs.html

Tested by previewing the page.

corporate: Add request for cover letter to job application instructions.

---

frontend_tests/puppeteer_tests/admin.ts
static/js/settings_emoji.js
static/templates/confirm_dialog/confirm_deactivate_custom_emoji.hbs
templates/zerver/help/custom-emoji.md
templates/zerver/help/moderating-open-organizations.md

delete custom emoji: Add confirmation dialog.

---

static/js/stream_settings_ui.js

Fixes: [](https://chat.zulip.org/#narrow/stream/9-issues/topic/missing.20text.20in.20unsubscribe.20confirmation)

stream_edit: Fix warning in confirm dialog modal from sub-unsub modal.

---

zerver/forms.py
zerver/tests/test_signup.py

Followup to commit c0287473b9dce376325df0ba5bc2d111ad6ff40f (#22723).

forms: Fix another 500 error on realm creation with invalid email

---

frontend_tests/node_tests/settings_org.js
static/js/settings_config.ts
static/js/settings_org.js
static/js/settings_realm_user_settings_defaults.js
static/templates/settings/notification_settings.hbs
static/templates/settings/organization_permissions_admin.hbs

Currently rebased on top of #22835, will remove this commit once that PR is merged.
Skipping the commit from #22835-
- First three commits are prep commits such that we can use common code.
- Last commit is the actual commit which disables save button for invalid inputs.
Behavior is same as for the message edit and delete limit settings.

Disable save button for invalid values in custom input of realm-default of email notification batching setting.

---

zerver/lib/events.py
zerver/lib/external_accounts.py

Fixes: [CZO](https://chat.zulip.org/#narrow/stream/378-api-design/topic/Name.20and.20Hint.20editable.20of.20default.20external.20account.20.2322371/near/1434321)

i18n: Add translation tags to default external accounts name.

---

static/styles/settings.css
static/templates/settings/admin_profile_field_list.hbs

We move display_in_profile_summary checkbox in the custom profile fields table to center. We also need to move heading subsequently to the center.
As discussed here - https://github.com/zulip/zulip/pull/21588#issuecomment-1253037469

settings: Move display_in_profile_summary checkbox to center.

---

templates/zerver/help/edit-a-bot.md
templates/zerver/help/include/sidebar_index.md
templates/zerver/help/view-all-bots-in-your-organization.md

Fixes: https://github.com/zulip/zulip/issues/21641
I took a revision pass on #22974, and also played with the sidebar ordering of bots articles.
Current docs: https://zulip.com/help/view-all-bots-in-your-organization

Revision pass on #22974 (document how to edit a bot)

---

templates/zerver/help/add-a-bot-or-integration.md
templates/zerver/help/bots-and-integrations.md
templates/zerver/help/deactivate-or-reactivate-a-bot.md
templates/zerver/help/request-an-integration.md
templates/zerver/help/restrict-bot-creation.md
templates/zerver/help/view-all-bots-in-your-organization.md

Adds or extends the "Related articles" lists that are either missing or incomplete in the following articles:
- [Bots and integrations](https://zulip.com/help/bots-and-integrations)
- [Add a bot or integration](https://zulip.com/help/add-a-bot-or-integration)
- [Request an integration](https://zulip.com/help/request-an-integration)
- [Deactivate or reactivate a bot](https://zulip.com/help/deactivate-or-reactivate-a-bot)
- [Restrict bot creation](https://zulip.com/help/restrict-bot-creation)
- [View all bots in your organization](https://zulip.com/help/view-all-bots-in-your-organization)
* Includes links to the new "**Edit a bot**" article that will be added via PR #22981.
<details> …

help: Fix "Related articles" in the bots section.

---

zerver/data_import/slack.py

Fixes: If a Slack export contains non .json files (e.g. MacOS rezips) don't attempt to process them.
Alternatively, one could use a glob filter, but as it wasn't already imported I opted for the .endswith() method instead.

slack: Filter out non-.json files for processing.

---

static/js/stats/stats.js

Removes a click handler in `populate_messages_sent_by_client` for anchor links that start with a hash.
I think this goes back to when there was a sidebar navigation on the stats page ([sidebar was added in this commit](https://github.com/zulip/zulip/commit/0a39e354dc2043b100ba4f4e6e5aecce00601aac#diff-fdf13868f4a957019803c1f93a8fce7f5d16751d84c5f29d46f4c42abe8b105aR9)), which no longer exists. The [only anchor link](https://github.com/zulip/zulip/blob/8fc811dfa92a7212bcf7e807f95603ea82fe19bd/templates/analytics/stats.html#L137) in the current HTML is to the help center documentation and not part of the Plotly charts. …

analytics: Remove unused click handler in populate messages by client.

---

zerver/models.py
zilencer/management/commands/populate_db.py

Small follow-up to d86e4ac34d4e38a3c5261bc2c202a91329367bc7. get_ makes it sound like it doesn't have side-effects, when these are actually much like the django ORM .get_or_create function.

models: Rename get_huddle to get_or_create_huddle.

---

static/js/admin.js
static/js/settings.js
static/js/settings_config.ts
static/templates/settings/account_settings.hbs
static/templates/settings/organization_settings_admin.hbs
static/templates/settings/organization_user_settings_defaults.hbs
static/templates/settings/settings_checkbox.hbs
tools/lib/capitalization.py

- First commit is for adding option to `settings_checkbox` and also to use this option for `enable_read_receipts` setting.
- Second commit is to change the parens text for `presence_enabled` to be in italics.
https://github.com/zulip/zulip/pull/23025#issuecomment-1256575882

Add option to settings_checkbox for adding text in italics to the checkbox label.

---

templates/zerver/documentation_main.html
zerver/tests/test_middleware.py

Makes the footer content on documentation pages more contextually appropriate for self-hosted organizations, when `settings.CORPORATE_ENABLED` is false.
When `settings.CORPORATE_ENABLED` is true (i.e., for Zulip Cloud organizations), there is specific footer content for the policy documentation pages, and for the help center and API documentation pages.
Fixes #23068.
---
**Notes**:
- As noted above, this uses the value of `settings.CORPORATE_ENABLED` to distinguish between self-hosted servers and Zulip Cloud organizations.
- Because no other URLs use `documentation_main.html` and no templates extend `documentation_main.html`, these updates should only impact these three main types of documentation pages.
- I didn't mark any of these strings for translation because, in general, we do not …

templates: Improve footer content on documentation pages.

---

docs/production/upgrade-or-modify.md

Fixes: #22284   
As noted in the issue, the only outstanding question is the necessity of item 6. As it's been over 24 hours I figured to ship the commit as it's safer with the possibly superfluous item than without.

help: Document upgrading Ubuntu 20.04 to 22.04

---

templates/corporate/for/communities.md
templates/corporate/for/open-source.html
templates/corporate/for/research.html

I manually previewed the changes:

portico: Minor updates to /for/X pages.

---

static/js/popovers.js

Fixes: [CZO topic](https://chat.zulip.org/#narrow/stream/6-frontend/topic/.22Manage.20this.20bot.22.20broken.20for.20Welcome.20Bot)

user_info_popover: Not displaying "Manage this bot" for system bots.

---

templates/zerver/emails/missed_message.source.html
templates/zerver/emails/missed_message.txt
zerver/lib/email_notifications.py
zerver/tests/test_email_notifications.py

Fixes: https://github.com/zulip/zulip/issues/22885.
Change mention's priority: personal mention > group mention > wildcard mention > stream notification.
Include ``realm_name`` into "Reply to this email directly...".
*personal mention*
*group mention*
*wildcard mention*
*stream notification*

email_notifications: Improve missed message email notifications. 

---

static/js/attachments_ui.js
static/templates/confirm_dialog/confirm_delete_attachment.hbs

delete attachments: Add confirmation dialog.

---

frontend_tests/puppeteer_tests/settings.ts
static/js/settings_account.js
static/styles/settings.css
static/templates/settings/profile_settings.hbs

settings: Prevent page reload when user presses `Enter` on full name input.

---

zerver/middleware.py
zerver/tests/test_scim.py

This removes everything from SCIMClient except the "is_authenticated`
method. Previously, "realm" and "name" were only needed for logging
purposes. It is the best to keep SCIMClient as minimal as possible, as
it is only intended to be used for authenticating requests to SCIM
views.
This change also gurantees that the "LogRequests" middleware will not
rely on the type unsafe access of the format_requestor_for_logs method
on SCIMClient.
Signed-off-by: Zixuan James Li <p359101898@gmail.com>
Fixes: 
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/version-cont …

scim: Slim down SCIMClient

---

static/styles/portico/integrations.css
templates/corporate/communities.html

discussion: https://chat.zulip.org/#narrow/stream/57-core-team/topic/open.20communities.20directory
Followup after #22081

Open communitie revision

---

static/js/message_edit.js
static/js/popovers.js
static/templates/actions_popover_content.hbs
static/templates/message_edit_form.hbs
templates/zerver/help/move-content-to-another-stream.md
templates/zerver/help/move-content-to-another-topic.md
templates/zerver/help/rename-a-topic.md

Remaining commits from #22652.

Update message actions popover.

---

docs/testing/mypy.md

docs: Fix a typo in mypy documentation.

---

templates/zerver/help/add-custom-profile-fields.md
templates/zerver/help/include/customize-settings-for-new-users.md

Current (deployment not up to date): https://zulip.com/help/add-custom-profile-fields
Current:
https://zulip.com/help/customize-settings-for-new-users
https://zulip.com/help/getting-your-organization-started-with-zulip
Give pronouns as an example field:

help center: Document new "Pronouns" custom profile field type.

---

static/styles/portico/integrations.css

discussion: https://chat.zulip.org/#narrow/stream/57-core-team/topic/open.20communities.20directory
before: 
after:

communities: Add more space between realm rows.

---

zerver/data_import/slack.py

Fixes: Skip files where file_access: access_denied. These stubs are incomplete and should be treated akin to tombstones (sample below).
`"files": [
{
"id": "FILEID",
"file_access": "access_denied",
"created": 0,
"timestamp": 0,
"user": "USERID"
}
],
`

slack: Skip files where file_access: access_denied.

---

static/js/settings_panel_menu.js

When trying to open settings overlay with invalid hash or hash of a section which the user cannot view, for example non-admins cannot view custom profile field section, then we open the first section by default.
While if a user changes to a invalid hash by typing when the overlay is already opened, then the previous section remains open.
Fixes: #23163.

settings_panel_menu: Open first section if hash is invalid.

---

puppet/zulip/manifests/common.pp

Fixes: https://grafana.com/blog/2022/10/12/grafana-security-releases-new-versions-with-fixes-for-cve-2022-39229-cve-2022-39201-cve-2022-31130-cve-2022-31123/

puppet: Bump Grafana version.

---

zerver/lib/cache.py
zerver/models.py

Slimmer memcached

---

static/styles/settings.css
static/templates/settings/admin_user_list.hbs

We set minimum width for role column in users list, deactivated users list and bots list such that role value always fits in one line.
Fixes #23218.

settings: Set min width of role column.

---

zerver/openapi/zulip.yaml
zerver/tests/test_markdown.py

Follow-up to #22975. Relevant [CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/event.20queue.20IDs/near/1448741).
I used the same uuid example string for all updates/changes.
<details>
<summary>API docs diff</summary>
```diff
diff -r -B -u current_api_html/delete-queue.html new_api_html/delete-queue.html
--- current_api_html/delete-queue.html	2022-10-13 17:08:54.697519240 +0200
+++ new_api_html/delete-queue.html	2022-10-13 17:08:00.165161571 +0200
@@ -308,7 +308,7 @@
<div data-language="curl" markdown="1"></p>
<div class="codehilite" data-code-language="curl"><pre><span></span><code>curl -sSX DELETE http://localhost:9991/api/v1/events \
-u BOT_EMAIL_ADDRESS:BOT_API_KEY \
-    --data-urlencode queue_id=1375801870:2942
+    --data-urlencode …
```

api-docs: Update examples of `queue_id` for uuid format.

---

templates/zerver/help/include/event-filtering-instruction.md

docs: Add commas to list of event types supported by integrations.

---

templates/zerver/help/include/sidebar_index.md
templates/zerver/help/marking-messages-as-read.md
templates/zerver/help/marking-messages-as-unread.md
templates/zerver/help/read-receipts.md
templates/zerver/help/reading-strategies.md
templates/zerver/help/star-a-message.md

This PR is an update on #23172.
Fixes #23052.

Document "Mark unread" feature

---

frontend_tests/node_tests/gear_menu.js
static/js/gear_menu.js
static/styles/dark_theme.css
static/styles/zulip.css
static/templates/gear_menu.hbs
tools/lib/capitalization.py

Fixes #22205
<details>
<summary><strong>Self-hosted users</strong></summary>
</details>
<details>
<summary><strong>Zulip Cloud Free users</strong></summary>
</details>
<details>
<summary><strong>For Zulip Cloud Standard users</strong></summary>
</details>
<details>
<summary><strong>For sponsored Zulip Cloud Standard users</strong></summary>
</details>

gear menu: Add organization info.

---

static/templates/user_info_popover_content.hbs

Fixes: chat.zulip.org [topic](https://chat.zulip.org/#narrow/stream/101-design/topic/profile.20menu.3A.20.22your.22.20vs.2E.20.22my.22)

user_info_popover: Change text of "View private messages to myself" to "View messages with yourself".

---

static/styles/dark_theme.css

There is some old CSS that was only being applied to some buttons and not others. This deletes those lines so that only the opacity changes on hover and not also the color.
Following up from #23059.
before:
bb366e.png">
after:

compose: Use consistent hover color for buttons in dark mode.

---

zerver/lib/import_realm.py

On my data (about 10 million messages in 1600 streams) this used to take about 40 hours, while the improved statement completes in roughly 30 seconds.
The old solution had postgres go through the entire table until the first match for each stream. Thus, the time spent scanning the table got longer and longer for each stream because postgres always started at the beginning (and somehow it did not use any indices) and had to skip over all rows until it found the first message from the stream that is was looking for each time.
This new statement just performans a bulk operation, scanning the table only once and then inserts the results directly into the destination table.
Slightly more verbose inforation about this change can be found in: …

import_realm: Speed up first_message_id calculation.

---

analytics/management/commands/populate_analytics_db.py
analytics/views/stats.py
corporate/lib/stripe.py
static/js/stats/stats.js
templates/analytics/stats.html

Adds the count of users with the role of guest to the stats view `page_params` via a database query. This information is then added to the summary statistics section of the analytics page after being formatted by `stats.js`.
Creates Bassanio as a guest user in the database for the analytics realm.
Fixes #20162.
---
**Notes**:
- Because we're not currently planning on adding a chart, or extending an existing chart, with the guest users over time, I went with making a database query for the current count of non-bot guest users, which is the same query that's used in `stripe.py`.
---
<details>
<summary>Updated summary stats section</summary>
</details>
--- …

analytics: Add summary statistic for guest users in realm.

---

static/js/reload.js
static/js/server_events.js

Prevent reload loops, 5.x backport

---

templates/zerver/help/change-a-users-name.md
templates/zerver/help/change-a-users-role.md
templates/zerver/help/deactivate-or-reactivate-a-user.md
templates/zerver/help/emoji-reactions.md
templates/zerver/help/include/message-actions-menu.md
templates/zerver/help/include/profile-summary-three-dot-menu.md
templates/zerver/help/include/right-sidebar-profile-menu.md
templates/zerver/help/include/right-sidebar-view-full-profile.md
templates/zerver/help/include/self-user-actions-menu.md
templates/zerver/help/include/stream-actions.md
templates/zerver/help/include/topic-actions.md
templates/zerver/help/marking-messages-as-read.md
templates/zerver/help/mention-a-user-or-group.md
templates/zerver/help/mute-a-topic.md
templates/zerver/help/mute-a-user.md
templates/zerver/help/stream-notifications.md

This documents how to access the options from the three-dot menu in a user's profile summary.
- Refactors and updates the steps for muting a user into a single set of instructions similar to [View someone's profile](https://zulip.com/help/view-someones-profile).
- Updates instructions for the "Manage this user" option.
- Migrates instructions for accessing the profile menu via the right sidebar to a new macro.
- Adds macro with instructions for accessing the three-dot menu in the profile summary.
Fixes #23204.
- https://zulip.com/help/mute-a-user
- https://zulip.com/help/change-a-users-name
- https://zulip.com/help/change-a-users-role
- https://zulip.com/help/deactivate-or-reactivate-a-user
<details>
Communicate …

help: Update documentation for "Mute this user" and "Manage this user". 

---

static/templates/settings_overlay.hbs

The icons in the organization settings sidebar are improved to represent them precisely.
Fixes:  #23248 

settings_ui: Change icons in organization settings sidebar.

---

zerver/migrations/0419_backfill_message_realm.py

With this, the migration will start by deleting dangling Recipient objects and the associated Messages (which can't be handled in any reasonable way by the .realm backfill logic).
.delete()ing Recipients feels kind of scary, I wish this would do a dry run first showing the Recipients up for deletion, or prompted the user for confirmation before deleting - but we probably don't want that kind of thing in a migration :disappointed:

migrations: Remove bugged Recipients in 0419.

---

static/js/recent_topics_ui.js

Misc fixes to recent topics.

---

docs/translating/translating.md

As the title says. Minor edit.

docs: Update Zulip version mentioned and remove extraneous comma.

---

frontend_tests/node_tests/popovers.js
static/js/popovers.js
static/styles/popovers.css
static/styles/zulip.css
static/templates/user_info_popover_content.hbs

Fix overflow of bot owner list item.
Wrap overflowing content of tippy tooltips.
Fixes: [chat.zulip.org](https://chat.zulip.org/#narrow/stream/9-issues/topic/bot.20owner.20name.20spills.20out)
BEFORE:
AFTER:

user_info_popover: Fix overflow of bot owner list item.

---

static/templates/settings_overlay.hbs

Reorganize organization settings sidebar.

---

static/styles/subscriptions.css
static/templates/stream_settings/stream_creation_form.hbs

This changes the stream create form so that it uses simplebar.
Resolves #21307
Dark theme:

stream-create: Use simplebar.

---

static/js/settings_realm_domains.js

realm_domains: Populate the table only if the modal is open.

---

zerver/lib/test_classes.py

Output message should talk about both the cases:
`actual_count > expected_count` and `actual_count < expected_count`.
The message now includes information for the case where `actual_query_count < expected_query_count`.
Fixes: #23325
- <details>
<summary>Output Message</summary>
</img>
</details>

test_classes: Improve assert_database_query_count output message.

---

static/js/settings_bots.js
templates/zerver/help/deactivate-or-reactivate-a-bot.md

Confirmation modal is added for reactivating a bot in personal settings to allow users a second chance and prevent from accidentally reactivating bot.
Fixes:  #23265
https://user-images.githubusercontent.com/53159963/196584377-6a9711b8-d26b-4035-8be6-03226761f0b0.mov

Add confirmation modal for reactivating a bot in personal settings

---

static/js/hotkey.js
static/js/recent_topics_ui.js
static/js/ui_init.js

discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/hotkey.20bug

Fix errors when processing user input before app loads.

---

.github/workflows/production-suite.yml
.github/workflows/zulip-ci.yml
tools/ci/Dockerfile
tools/ci/Dockerfile.prod
tools/ci/build-docker-images
tools/ci/production-upgrade

Remove RabbitMQ from Docker CI images

---

frontend_tests/node_tests/dispatch.js
frontend_tests/node_tests/pm_list.js
frontend_tests/node_tests/recent_topics.js
frontend_tests/node_tests/stream_list.js
frontend_tests/node_tests/vdom.js
frontend_tests/puppeteer_tests/compose.ts
frontend_tests/puppeteer_tests/message-basics.ts
frontend_tests/puppeteer_tests/navigation.ts
static/js/click_handlers.js
static/js/pm_list.js
static/js/pm_list_dom.js
static/js/recent_topics_ui.js
static/js/resize.js
static/js/scroll_util.js
static/js/stream_list.js
static/js/tippyjs.js
static/js/top_left_corner.js
static/js/topic_list.js
static/js/ui_init.js
static/styles/dark_theme.css
static/styles/left_sidebar.css
static/styles/zulip.css
static/templates/left_sidebar.hbs
static/templates/more_pms.hbs
static/templates/pm_list_item.hbs
tools/lib/capitalization.py

This would be a followup of #21357 and would contain a bunch of `prep commits` for #21102 .
Fixes #20870.

Collapsible PM section.

---

static/js/dialog_widget.js
static/js/loading.ts
static/styles/modal.css

Improve visuals of the dialog_widget disabled buttons while a loading spinner is showing.
These changes remove the odd looking grey colour from the dialog buttons while they are disabled and also keeps the size of the buttons unchanged.
Fixes: #22002
Video:
https://user-images.githubusercontent.com/86338542/197326979-68ef1bb8-7a11-4559-8d08-843cd5204fd9.mp4

style: Improve visuals of the dialog_widget disabled buttons while a loading spinner is showing.

---

scripts/setup/apt-repos/teleport/focal.list
scripts/setup/apt-repos/teleport/jammy.list
tools/setup/bootstrap-aws-installer

Fixes Teleport on new AWS hosts, and adjusts the deb URL for Teleport going forward.

AWS bootstrap updates

---

static/js/composebox_typeahead.js
static/shared/js/typeahead.js
static/shared/js/typeahead.js.flow

This is a series of small pure refactors, which simplify this code and will also be helpful for mobile to re-use more of it.
---
typeahead [nfc]: Push toLowerCase down into query_matches_string.
This prepares us to dissolve query_matches_source_attrs in favor
of making its call sites simpler and more transparent.
typeahead [nfc]: Dissolve `query_matches_source_attrs`.
This makes each of the call sites more straightforward and
transparent.  In `query_matches_person` it also opens up further
simplifications, which we'll make next.
Since we're now exporting `query_matches_string` from this
shared module, we write its type in the `.js.flow` file.
typeahead [nfc]: Use people.get_visible_email abstraction.
Best to centralize this logic -- makes the intention clearer at the
use site, and also …

typeahead: Simplify away `query_matches_source_attrs`

---

docs/subsystems/schema-migrations.md

Inspired by #23377. We document a convention maneuver to avoid adding
noop migrations, which involves modifying the latest migration related
to the fields in question.

docs: Document handling noop migrations.

---

zerver/actions/invites.py

These should only ever happen together, so should be wrapped in atomic().

invites: Add atomic() around some invite-revoking blocks.

---

puppet/zulip/lib/puppet/parser/functions/zulipconf.rb
puppet/zulip_ops/files/nagios_ssh_config
puppet/zulip_ops/manifests/profile/nagios.pp
puppet/zulip_ops/templates/nagios4/hosts.cfg.template.erb
puppet/zulip_ops/templates/supervisor/conf.d/munin_tunnels.conf.erb

This will hopefully resolve issues with connectivity problems to hosts causing spurious pages.

Use SSH master socket over autrossh for nagios connections

---

static/js/unread.js

discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/unread_mention_topics.20bug

unread: Use unread_topic_counter to get message details. 

---

static/templates/gear_menu.hbs

gear_menu: Change sponsored plan name.

---

static/js/popovers.js

In the message actions popover menu, adds an additional check for whether the mark as unread option should be displayed based on if the message is a stream message and if the user is subscribed to the message's stream.
See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/378-api-design/topic/unreads.20in.20unsubscribed.20streams/near/1456546).
---
**Notes**:
- There's a `TODO` comment at the end of the frontend node test `popovers.js` to test all the properties of the message actions popover. I imagine that's where we'd add tests for this? For now, I've just done a thorough manual test of the changes.
- This change does not address the error that arises in an interleaved view, like "All messages" or a search for all public streams, when a user selects the **Mark as unread …

popovers: Do not show option to mark unread for unsubscribed streams.

---

static/templates/stream_settings/change_stream_info_modal.hbs
static/templates/stream_settings/stream_creation_form.hbs

**stream_settings: link to /help/change-the-stream description from stream settings**
Add help link to stream description
Fixes: #23376 

stream_settings: link to /help/change-the-stream description from stream settings

---

zerver/lib/import_realm.py

On multi-realm systems this results in traversal of all messages in all realms and returns a massive payload of at least 1 row per realm but in practice many more (possibly 1 per stream per realm?).
Fixes: 

import: Narrow the id-window to just the current realm.

---

static/js/search_suggestion.js
static/js/stream_data.js

Normally a user will not have any stream data for private streams that they are not subscribed to, but admin users do have access to basic information about these private streams for admin purposes.
When building search suggestions, instead of assuming that a user with the basic stream information has access to the message data for the stream, check first to see if the user is subscribed before sending the request to the server for more stream topic data.
---
<details>
<summary>Pre-changes: 400 stack trace in dev environment</summary>
</details>
--- …

search: Check if user is subscribed before requesting stream data.

---

static/js/resize.js

discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/left_side_userlist.20broken

Set correct `max-height ` for left-sidebar blocks.

---

templates/zerver/api/construct-narrow.md

Updates to the article:
- Fixes small error in the example at the top of the article (the keyword search is for two words and not a phrase)
- Adds a short statement about narrows searching the current user's personal message history with a link to the help center article (this matches the update in the linked PR to the [get messages narrow parameter](https://zulip.com/api/get-messages#parameter-narrow)  documentation
- Gives the final section a subheader and adds the two other narrow operators that take an ID
Follow up to #23347.
---
[Current documentation](https://zulip.com/api/construct-narrow)
--- …

api-docs: Update 'construct-narrow' article.

---

static/templates/settings/notification_settings.hbs

Fixes: #23369.
- Added Links to open help center articles for notification settings
**Demo Video:**
https://user-images.githubusercontent.com/66828942/198753289-0ba4bdc7-8d8e-4016-a955-a352ad801d96.mp4

add: Links to help center articles for notification settings.

---

static/js/pm_list.js
static/js/stream_list.js
static/styles/dark_theme.css
static/styles/left_sidebar.css
static/templates/left_sidebar.hbs

discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/private.20messages.20section.20.2320870
Attached images to each to commit, so viewing commit by commit will be helpful.

Show PMs header in topics zoom.

---

puppet/deps.yaml
puppet/zulip/manifests/common.pp
tools/setup/bootstrap-awscli.sh

Upgrade puppet dependencies.

---

docs/tutorials/new-feature-tutorial.md

Made some small changes to new feature tutorial documentation to match the code in current `admin.js`
Fixes: There was no related issue for this fix.

docs: Update to match current admin.js

---

templates/zerver/help/desktop-notifications.md
templates/zerver/help/email-notifications.md
templates/zerver/help/mobile-notifications.md

Documents the top checkboxes section for controlling mobile, desktop, and email notifications.
Fixes #23371.
<details>
</details>

help center: Document notification triggers.

---

templates/corporate/features.html

It would be great to get a careful review on this one.

portico: Add new features to /features page.

---

templates/zerver/help/analytics.md
templates/zerver/help/include/sidebar_index.md
templates/zerver/help/public-access-option.md

- Renames the page to "Usage statistics" (title & left sidebar).
- Adds an intro section that outlines the types of information that can be found on the stats page.
Fixes #23449.
- https://zulip.com/help/analytics
<details>
</details>

help center: Improve "analytics" article.

---

templates/zerver/help/import-from-slack.md
templates/zerver/help/include/import-get-your-organization-started.md
templates/zerver/help/include/import-how-users-will-log-in.md
templates/zerver/help/include/import-into-a-self-hosted-zulip-server.md
templates/zerver/help/include/import-into-a-zulip-cloud-organization.md
templates/zerver/help/include/import-self-hosted-server-tips.md
templates/zerver/help/include/import-workspace-to-zulip.md
templates/zerver/help/include/import-your-data-into-zulip.md
templates/zerver/help/include/import-zulip-cloud-organization-warning.md

- We can reuse the content from multiple sections of the Slack article in order to update "Import from Mattermost/Gitter/Rocket.Chat".
- Creates a few Markdown macros for reusability, making small wording tweaks e.g. "Slack" -> "workspace" and rearranging tips/warnings.
<details>
<summary>Import from Slack</summary>
<details>
</details>

help center:  Update "Import from Slack/Mattermost/Gitter/Rocket.Chat".

---

static/styles/popovers.css
static/templates/user_profile_modal.hbs

Moving the last active status icon to the modal header, we obtain a cleaner visual design for the user profile modal which is more consistent with other parts of UI.
Fixes: [Link to CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/bad.20avatar.20alignment.20in.20full.20profile)

user_profile_modal: Move presence activity status to modal header.

---

frontend_tests/node_tests/settings_org.js
static/js/settings_org.js
static/templates/settings/organization_settings_admin.hbs

- First commit is to fix the bug for save-discard widget not hiding in `Other settings` section.
- Second commit is to refactor the code for realm message retention setting and this also fixes the bug for save-discard widget not hiding in `Message retention` section

settings_org: Fix bug of save-discard widget not hiding correctly and refactor code for message retention setting.

---

zerver/lib/compatibility.py
zerver/tests/test_event_system.py
zerver/views/events_register.py

register: Not all clients send a User-Agent header.

---

zerver/management/commands/export_search.py

q
```
$ ./manage.py export_search --output foo.json --force \
-r zulip \
--after '2022-11-01 00:00:00' --before '2022-11-06 14:00:00' \
server
2022-11-07 20:48:03.908 INFO [] Finished writing foo.json
```
```json
{
"zerver_message": [
{
"id": 85,
"sender": 9,
"recipient": 6,
"subject": "file server",
"content": "We motivate the need for public-private key pairs. On a similar note, to fulfill this ambition, we verify that even though the famous empathic algorithm for the emulation of erasure coding by G.",
"rendered_content": "<p>We motivate the need for public-private key pairs. On a similar note, to fulfill this ambition, we verify that even though the famous empathic algorithm for the emulation of erasure coding by G.</p>",
"date_sent": …
```

Add a tool to export a subset of messages, for compliance

---

templates/zerver/help/status-and-availability.md

Updates the mobile instructions to **Toggle invisible mode** on the help center article for [status and availability](https://zulip.com/help/status-and-availability#toggle-invisible-mode) for the correct text.
---
---

help-docs: Update mobile instructions for invisible mode.

---

zerver/webhooks/gocd/view.py
zerver/webhooks/gosquared/view.py
zerver/webhooks/greenhouse/view.py
zerver/webhooks/groove/view.py
zerver/webhooks/harbor/view.py
zerver/webhooks/hellosign/view.py
zerver/webhooks/homeassistant/view.py
zerver/webhooks/insping/view.py
zerver/webhooks/intercom/view.py
zerver/webhooks/jira/view.py
zerver/webhooks/jotform/view.py
zerver/webhooks/opbeat/tests.py
zerver/webhooks/opbeat/view.py
zerver/webhooks/wekan/view.py

This PR consists of a migration of the remaining integrations to use the WildValue system.
Fixes: 

Migrate remaining webhooks to use WildValue.

---

zerver/webhooks/grafana/fixtures/alert_new.json
zerver/webhooks/grafana/fixtures/alert_new_multiple.json
zerver/webhooks/grafana/tests.py
zerver/webhooks/grafana/view.py

Adds support for Grafana's new alerting system. The proposed integration
update wouldn't require explicit configuration and would support both old
and new notifications parallelly. Internally, we differentiate between versions
based on the structure of the incoming payload.

grafana: Support notifications from Grafana Alerting.

---

puppet/zulip/files/nginx/zulip-include-common/proxy
zerver/management/commands/runtornado.py

[5.x] tornado: Fix Tornado CSRF check with X-Forwarded-Proto.

---

static/js/realm_logo.js
static/js/ui_init.js

We already re-rendered the realm-logo when the user selects either the light or dark color scheme, but on `color-scheme-automatic`, we didn't have any event handlers to trigger a render. This commit adds a handler to listen for changes to `prefers-color-scheme` property.
Fixes #23548.
Fixes: 

dark_theme: Re-render realm-logo on prefers-color-scheme changes.

---

tools/setup/emoji/build_emoji
zerver/data_import/slack.py

Previously, emoji.json was read from
"$ZULIP_PATH/node_modules/emoji-datasource-google/emoji.json". This path doesn't exist in production when installing from scratch from a release tarball. And so, we ensure emoji.json exists by copying it to `static/generated/emoji`.
Fixes: #23469

Slack import: Cache emoji.json in static/generated/emoji.

---

zerver/webhooks/ifttt/tests.py
zerver/webhooks/ifttt/view.py
zerver/webhooks/papertrail/tests.py
zerver/webhooks/papertrail/view.py

ifttt/papertrail: Strengthen types using WildValue.

---

static/third/bootstrap-typeahead/typeahead.js

We now explicitly check whether the keycode was 13 and not
some IME selection enter event that also use e.key = "Enter"
behavior.
Fixes #22062.
Fixes: 

keydown_util: Add is_enter_event check for IME edge cases.

---

zerver/data_import/slack.py

Fixes: The naive solution #23465 creates situations where the same user can have multiple reactions as the base emojis are not unique, e.g. +1::skin2 and +1::skin4 would both reduce to +1 but the userlists are separate. This solution handles the reduction, merges the same-base reactions, and deduplicates the userlist.

slack: Merge same-base emoji reactions, and deduplicate resulting userlists

---

docs/subsystems/release-checklist.md

Release step updates

---

frontend_tests/node_tests/popovers.js
static/js/common.ts
static/js/popovers.js
static/js/ui_report.ts
static/js/unread.js
static/js/unread_ops.js
static/styles/alerts.css
static/styles/dark_theme.css
static/styles/zulip.css
templates/zerver/app/index.html
zerver/tornado/event_queue.py

Use improved /messages/flags API to mark messages read / unread.

---

docs/production/export-and-import.md
zerver/management/commands/export_search.py

Document compliance exports, extend with sender search

---

docs/overview/changelog.md
templates/zerver/api/changelog.md
version.py

I'm not sure why Prettier decided to reformat the upgrade notes bullets in this commit, but it seems harmless.
Fixes: 

Release Zulip Server 6.0.

---

docs/overview/changelog.md
templates/zerver/api/changelog.md
version.py

Update version following 6.0 release.

---

docs/production/upload-backends.md

Improve AWS bucket documentation

---

docs/development/setup-advanced.md

**DOCUMENTATION UPDATE**
Updated (corrected) the location of the `provision` script in Zulip codebase docs [here](https://zulip.readthedocs.io/en/latest/development/setup-advanced.html#installing-directly-on-ubuntu-debian-centos-or-fedora:~:text=You%20can%20just%20run%20the%20Zulip%20provision%20script%20on%20your%20machine.). Helpful for new contributors and users.
Fixes: #23615 

updated location of `provision` script in setup-advanced.md

---

static/js/stream_list.js

Fixes https://github.com/zulip/zulip/issues/23241.
This bug is related to this PR https://github.com/zulip/zulip/pull/22859. That fix https://github.com/zulip/zulip/commit/dd39a9747d968a1a4cf8e07edc821008a3f55d7c doesn't consider the muted streams while implementing the logic for when to show/not show the section divider.
https://user-images.githubusercontent.com/87542880/201394268-71aff007-c653-455a-a2d7-8e68539c7082.mp4

left_sidebar: Fix section divider not shown when all streams are muted.

---

static/js/message_fetch.js

In 16c45aa, the check for an empty narrow was updated to no longer confirm if no messages were returned by the message fetch request.
Updates that same the empty narrow check to confirm now that the messages fetched, and being processed are for the current / narrow message list before showing an empty narrow.
**Question**: Is the `page_params.narrow` that's noted in `message_fetch.load_messages` still something that needs to be migrated to the `Filter` object construction, as noted in [this commit](https://github.com/zulip/zulip/commit/d3ebfce4aec4e3cb70e55208445d68d3e5ab0d2c)?
--- …

message-fetch: Update empty narrow check to include opts message list.

---

templates/zerver/help/mention-a-user-or-group.md

Current page: https://zulip.com/help/mention-a-user-or-group
Updated:

help center: Document @everyone and @stream mentions.

---

docs/production/authentication-methods.md

Follow-up to PR #23264.
<details>
</details>

docs: Fix link to "Custom profile fields".

---

.github/workflows/production-suite.yml

ci: Test upgrades from Zulip Server 6.0.

---

templates/zerver/help/message-a-stream-by-email.md

Updates the documentation to reflect recent changes to the UI.
Fixes #23471.
- https://zulip.com/help/message-a-stream-by-email#message-a-stream-by-email
<details>
</details>

help center: Update "Message a stream by email" to reflect new UI.

---

zerver/migrations/0376_set_realmemoji_author_and_reupload_realmemoji.py

Django compiles this to the (single) SQL query
```sql
UPDATE "zerver_realmemoji"
SET "author_id" = (
SELECT U0."id" FROM "zerver_userprofile" U0
WHERE (
U0."is_active"
AND U0."realm_id" = ("zerver_realmemoji"."realm_id")
AND U0."role" = 100
)
ORDER BY U0."id" ASC LIMIT 1
)
WHERE "zerver_realmemoji"."author_id" IS NULL;
```
Fixes this crash: https://chat.zulip.org/#narrow/stream/31-production-help/topic/upgrade-zulip.204.2Ex.20-.3E.205.2E7/near/1469760

migrations: Fix Python-looped SQL in 0376; don’t crash if no user found.

---

frontend_tests/node_tests/message_store.js
frontend_tests/node_tests/recent_senders.js
frontend_tests/node_tests/recent_topics.js
frontend_tests/node_tests/typeahead_helper.js
static/js/message_helper.js
static/js/recent_senders.js
static/js/recent_topics_ui.js
static/templates/recent_topic_row.hbs

Fixes https://github.com/zulip/zulip/issues/23563

recent: Sort PM recipients by their last sent message id. 

---

static/js/stream_edit.js

We were not passing `max_stream_description_length` and `max_stream_name_length` parameters to `change_stream_info_modal` template and thus the maxlength attribute was not being set correctly for the stream name and description input.
This PR updates the code to pass these parameters to template. This PR also removes these parameters from the data passed to `stream_types` template, since these parameters are not required there.

streams: Pass max-length parameters to stream info modal.

---

templates/zerver/help/include/create-bot-construct-url.md

Revises the text about including a stream and a topic incoming webhook URLs in `create-bot-construct-url.md` for clarity and consistency.
<details>
<summary>Current text</summary>
</details>
<details>
<summary>Revised text</summary>
</details>
---

integrations-docs: Update text in `create-bot-construct-url.md`.

---

zerver/webhooks/slack_incoming/fixtures/attachment_fields.json
zerver/webhooks/slack_incoming/tests.py
zerver/webhooks/slack_incoming/view.py

Fix a couple small bugs with slack_incoming webhooks

---

puppet/zulip/manifests/common.pp

grafana: Upgrade to 9.3.0.

---

templates/corporate/jobs.html

portico: Drop Marketing/Growth Lead position from /jobs.

---

static/js/settings_org.js

settings: Fix custom input for user email-notification-batching setting in 6.x.

---

CODE_OF_CONDUCT.md

contributor docs: Add guidelines on moderating the Zulip community.

---

analytics/tests/test_activity_views.py
analytics/views/activity_common.py
analytics/views/installation_activity.py
analytics/views/realm_activity.py
templates/analytics/activity.html
templates/analytics/realm_summary_table.html

Updates the links on the activity page:
- Removes the copy link for a realm's owners. This is available on the support page.
- Adds a link to the realm's Zulip.
- Updates the realm's stats page link so that it is just the pie chart icon.
- Adds a link to the realm's support page.
---
*Note hovering so that the link url is shown in the bottom left of each screenshot*
<details>
<summary>Hover over the house icon link to the realm's Zulip</summary>
</details>
<details>
<summary>Hover over the pie chart icon link to the realm's stats page</summary>
</details>
<details>
<summary>Hover over the realm name to the realm's support page</summary>
</details>
--- …

activity: Update realm links on server admin activity page

---

zerver/management/commands/scrub_realm.py

https://github.com/zulip/zulip/pull/23745#discussion_r1039172925

scrub_realm: Exit unsuccessfully when asked to scrub an active realm

---

.github/workflows/production-suite.yml
.github/workflows/zulip-ci.yml

Targeted fix for regression introduced in #23719 wherein failure reports were attempted for all CI failures, including those from forked pull requests, which don't have access to Actions Secrets. Since undefined Secrets are empty strings at interpolation time [^1], the underlying `send-message` Action was being called with no API Key, causing a failure in the failure handler.
This fix is, per discussion in both a comment on #23719 and later on CZO [^2], prefered to restoring the prior guard against ZULIP_BOT_KEY being an empty string that had been in the shell script as it is more explicit in its intent.
[^1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-secrets
[^2]: https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/all …

ci: Only report failures to CZO on branch pushes.

---

static/styles/recent_topics.css
static/styles/right_sidebar.css

css: Add min-width to user presence dot.

---

docs/subsystems/release-checklist.md

(This is intended to be a brief reminder of the necessary steps, not a self-contained tutorial for users with no prior knowledge, which would be dozens of times longer. We’ll figure it out.)

release-checklist: Update blog post checklist for Astro

---

tools/setup/apns/csr.conf
tools/setup/apns/prep-cert

This prepares server certificates for talking to APNs.

tools: Add script apns/prep-cert.

---

zerver/webhooks/zabbix/doc.md

Since the removal of `CurlHttpRequest` in Rabbix 6.2, the old script for setting up the Zabbix integration no longer works.
https://www.zabbix.com/documentation/6.2/en/manual/installation/upgrade_notes_620?hl=CurlHttpRequest#curlhttprequest-removed
This updates the documentation to use `HttpRequest` instead and keeps it up-to-date with the latest Zabbix server. We raise the minimum supported version from 5.2 to 5.4 because `HttpRequest` was introduced in 5.4.
[CZO Discussionn](https://chat.zulip.org/#narrow/stream/127-integrations/topic/zabbix-integration/near/1474897)
<details> …

webhooks: Update Zabbix integration documentation.

---

analytics/views/stats.py
static/js/stats/stats.js

analytics: Pass the right value for realm.

---

static/js/message_edit.js

This PR changes the way streams are shown in the "Move topic" and the "Move messages" dropdowns. A sort function (which ignores the capitalization) was added to change the stream list order. 
Fixes: #23283 
The stream list is sorted in both modals

popovers: Ignore capitalization when sorting streams.

---

static/styles/settings.css
static/templates/settings/profile_settings.hbs

Having the preview profile button always visible makes it more accessible when the user is at a random scroll positon in the profile settings.
Fixes: [Link to CZO](https://chat.zulip.org/#narrow/stream/137-feedback/topic/Make.20preview.20profile.20sticky)
- Widescreen
- Narrow Screen size

user_profile: Convert preview profile to sticky button.

---

.github/pull_request_template.md
CONTRIBUTING.md
templates/zerver/api/incoming-webhooks-walkthrough.md

Updates `.html` links as a follow-up to #23750.
<details>
</details>

contributing docs: Update "Version Control" > "Commit discipline" links.

---

static/templates/message_view_header.hbs

See https://chat.zulip.org/#narrow/stream/9-issues/topic/search.20box.20button.20is.20a.20.3Cspan.3E
search button is a span; it should be a button or a, or at least marked that it's clickable using aria
Fixes: 
<details>
</details>

add role=button to search btn

---

static/templates/settings/organization_profile_admin.hbs

In Organization settings > Organization profile, change "A wide image for the upper left corner of the app." to "A wide image (200×25 pixels) for the upper left corner of the app."
Fixes part of #22121.
<details>
Individual commits are ready for review (see [commit discipline]([https://zulip.readthedocs.io/en/latest/contributing/version-control.html](https://zulip.readthedocs.io/en/latest/contributing/version-control.html?fbclid=IwAR3l3tBi1buicebocs2KRajHgx19ztlm6ROvzhG3lbvcJXc6DNVeOWOpfN4))).
</details>

settings: Add "(200×25 pixels)" to wide organization logo description.

---

static/js/drafts.js

No functional changes. Moves functions so that other code in this file can access them.
See the final commit of #22104 to see how the functions will be used.

drafts: Move functions out of `launch()` context, for other use.

---

static/styles/compose.css
static/styles/modal.css
static/styles/portico/billing.css
static/styles/portico/integrations_dev_panel.css
static/styles/portico/portico_signin.css
static/styles/settings.css
static/styles/zulip.css
static/templates/confirm_dialog/confirm_deactivate_user.hbs
static/templates/invite_user.hbs
static/templates/settings/custom_user_profile_field.hbs
static/templates/settings/organization_profile_admin.hbs
static/templates/stream_settings/change_stream_info_modal.hbs
static/templates/user_group_settings/change_user_group_info_modal.hbs
static/third/bootstrap/css/bootstrap.css

- First commit is to add CSS rules for textarea elements in settings using `settings_textarea` class.
- Next two commits is to add a couple of CSS rules which are applied to only one element.
- Next three commits are to add CSS rules for textarea elements in protico pages - devtools integrations panel, support page and sponsorship page.
- Next two commits are to add CSS rules for compose and message edit textarea elements.
- Next commit it to add CSS rules for textarea in invite modal.
- Last commit is to remove CSS rules for textarea from `bootstrap.css`.
<details> …

Remove bootstrap CSS rules for textarea elements.

---

static/styles/portico/portico_signin.css
zerver/tests/test_email_change.py
zerver/views/user_settings.py

Fixes: #23654 
[Screencast from 01-12-22 12:15:03 AM IST.webm](https://user-images.githubusercontent.com/99073049/204914068-27c1c7d3-ff4d-485c-8b4c-4cb990b42b4e.webm)

css: Fix spilling out of long email on email change confirmation

---

static/js/stream_data.js
static/styles/zulip.css
static/templates/invite_subscription.hbs

Fixes part 1 of #23496 
Before - 
After - 

invite_users: Remove "#" in private streams and add globe icon in Web-public streams

---

frontend_tests/node_tests/narrow.js
frontend_tests/node_tests/recent_topics.js
static/js/narrow.js
static/js/recent_topics_ui.js

Refactors update_narrow_title so that it can be used for the "All messages" and "Recent conversations" views, both of which have a `narrow_state.current_filter` of `undefined`.
Part of #23812.
**Notes**:
- The first commit is the update that is relevant to the issue noted above, which focuses on the "All messages" view.
- The second commit is the update for "Recent conversations" and may not be a change we want to do.
- `narrow_state.reset_current_filter()` is what sets the current filter to be `undefined` for these views.
- I feel like there should probably be a frontend test for `update_narrow_title`.
---
<details> …

narrow: Refactor update narrow title for recent and all messages views.

---

frontend_tests/node_tests/compose.js
frontend_tests/node_tests/compose_actions.js
frontend_tests/node_tests/compose_state.js
frontend_tests/node_tests/compose_validate.js
frontend_tests/node_tests/composebox_typeahead.js
frontend_tests/node_tests/drafts.js
frontend_tests/node_tests/narrow.js
frontend_tests/node_tests/stream_data.js
static/js/compose_actions.js
static/js/compose_fade.js
static/js/compose_state.js
static/js/stream_data.js
static/js/stream_settings_ui.js

prep commits for "Change stream field in composebox to be a dropdown"

---

static/third/bootstrap/css/bootstrap.css
templates/corporate/for/research.html

This PR is part of the efforts to [remove Bootstrap CSS resets](https://chat.zulip.org/#narrow/stream/6-frontend/topic/bootstrap.20CSS.20reset.20removal). The scope of the change here is the removal of the Bootstrap CSS resets for `<figure>`  elements and the CSS resets for `@media print`.
There was only one `<figure>` element in the whole code base, and that element being a text bubble, using a `<figure>` element there seemed inappropriate. So while at it I replaced it with a `<div>`.
I verified that there are no visual changes by comparing the `/for/research` page side by side with and without the changes here, as well as by inspecting the applied styles in the devtools.
As for the removal of Bootstrap's CSS rules applied to print media, @timabbott and I compared several of the logged …

 css: Remove Bootsrap CSS reset for figue elements and print media

---

zerver/lib/export.py

`logging.warning("Naive datetime:", item)` is an invalid call that crashes with `TypeError: not all arguments converted during string formatting`. I take that to mean this check has not been tripped in the six years it’s been there, and can safely be replaced with an error.

export: Replace broken naive datetime warning with assertion

---

corporate/views/portico.py
templates/zerver/help/include/set-up-your-account.md
zerver/context_processors.py
zerver/tests/test_docs.py
zproject/urls.py

Fix /apps redirect, clean up corporate portico code, remove unnecessary zulip.com from link

---

static/styles/compose.css

Fixed a bug in expanded compose box preview mode, which lead to buttons at the bottom of the compose box being pushed off the screen and text overflowing.
Manually tested for different screen sizes.
Fixes: https://github.com/zulip/zulip/issues/23493
Screen capture - 
[expanded compose preview mode fixed.webm](https://user-images.githubusercontent.com/96468766/206170711-24e5fdd1-583c-40fe-a4b6-0cadc8b46bea.webm)
**_Inspiration for the code was taken from [this](https://github.com/zulip/zulip/pull/23649) PR._**
<details> …

compose: Fix overflow in expanded compose box preview mode.

---

static/styles/portico/billing.css
static/styles/portico/integrations_dev_panel.css

We set `font-family` for `select`, `input` and `textarea` elements in upgrade and integrations-dev-panel pages to be consistent with majority of the app.
<details>
</details>

Make bootstrap font consistent for upgrade and integerations-dev-panel pages.

---

templates/zerver/help/include/all-messages.md

Follow up to #23875.
<details>
</details>

help center: Add "All messages" icon for mobile.

---

templates/corporate/jobs.html

portico: Remove Senior Mobile Engineer job posting.

---

.eslintrc.json

https://eslint.org/docs/latest/user-guide/configuring/configuration-files#cascading-and-hierarchy

eslint: Add root: true

---

zerver/webhooks/slack_incoming/tests.py
zerver/webhooks/slack_incoming/view.py

Fixes: #22228.
<details>
</details>

Support Slack section fields

---

puppet/zulip/manifests/golang.pp

Unlikely, but possibly may fix #23974.
<details>
</details>

puppet: Go's website is officially go.dev, not golang.org.

---

README.md

Because Ruff is awesome.
[![Ruff](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/charliermarsh/ruff/main/assets/badge/v0.json)](https://github.com/charliermarsh/ruff)

README: Add Ruff badge

---

templates/corporate/jobs.html

Change on https://zulip.com/jobs

portico: Emphasize cover letter requirement for job applications.

---

docs/production/install.md

[CZO thread](https://chat.zulip.org/#narrow/stream/31-production-help/topic/.22from.22.20email.20address.20.2323942)
Can we resolve #23942?

docs: Clarify --email installation option.

---

templates/zerver/help/restrict-name-and-email-changes.md
templates/zerver/help/restrict-profile-picture-changes.md

Updates the articles on restricting email and avatar changes to that it is clear that administrators can always change these settings for themselves.
Also, fixes a broken link and a few grammar errors.
<details>
<summary>Restrict name and email changes</summary>
[Current documentation](https://zulip.com/help/restrict-name-and-email-changes)
</details>
<details>
<summary>Restrict profile picture changes</summary>
[Current documentation - note the broken link](https://zulip.com/help/restrict-profile-picture-changes)
</details>
---
<details> …

help-docs: Update articles for restricting email and avatar changes.

---

zerver/actions/message_send.py
zerver/tests/test_event_queue.py
zerver/tests/test_messages.py

I had wanted to do the test split since a long time!
This should make it a lot easier to read the tests and/or add more tests.

Misc notifications cleanup

---

templates/zerver/api/missing.md

Previously, `templates/zerver/api/missing.md` was a symlink to the file in the help center documentation.
Prep commit for moving the help center documentation to a top level directory.
See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/19-documentation/topic/help.20center.20directory.20structure/near/1480704).
---
<details>
</details>

api-docs: Add `missing.md` file specifically for API documentation.

---

templates/zerver/api/incoming-webhooks-walkthrough.md
templates/zerver/development/dev_tools.html
templates/zerver/help/gdpr-compliance.md
zerver/openapi/zulip.yaml

Adds links to the documentation about management commands in the API documentation for creating users, as well as the development environment `/devtools` documentation, GDPR compliance article and incoming webhooks tutorial.
See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/management.20commands/near/1434014).
**Notes**:
- Audited `templates` directory for references to `manage.py`. There were some help center docs that didn't seem to need a link added to the documentation.
- `templates/zerver/help/change-organization-url.md:1` : Already links to documentation.
- Import instructions:
- `templates/zerver/help/import-from-gitter.md:3`
- `templates/zerver/help/import-from-mattermost.md:8` 
- `templates/zerver/help/import-from-rocketchat.md:3`
- …

docs: Link to management commands documentation in user facing docs.

---

docs/overview/changelog.md

Fixes: https://github.com/zulip/zulip/pull/23713#discussion_r1063803234
<details>
</details>

changelog: Add entry for S3 nginx proxying.

---

static/js/settings_bots.js
static/styles/settings.css
static/templates/settings/bot_avatar_row.hbs
static/templates/settings/bot_settings.hbs
static/templates/settings/profile_settings.hbs

- First commit removes unnecessary "hide" class from `h3` element in profile settings.
- Second commit removes a couple of unused functions from `settings_bots.js`.
- Last two commits are to remove unused error elements in bot settings templates.
<details>
</details>

Remove unsused code in bot settings. 

---

CONTRIBUTING.md

Removes a paragraph about posting in the **#new members** stream to get help finding issues to work on from the first contribution part of the contributing guide.
Also updates the remaining section about posting to **#new members** as a way to introduce yourself with a link to the community norms and offering positive feedback as well as constructive criticism.
See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/19-documentation/topic/contributing.20guide/near/1489509) for more context.
---
<details>
<summary>Updated "Picking an issue to work on" section</summary>
[Current documentation](https://zulip.readthedocs.io/en/latest/contributing/contributing.html#picking-an-issue-to-work-on)
</details>
<details>
<summary>Updated "Your first …

docs: Remove paragraph about getting help finding issues in contributing guide.

---

zerver/lib/markdown/__init__.py
zerver/tests/test_markdown.py

Addresses bumping the preview limit part of #23999.
The max inline preview limit was previously increased to 10 by #20789. However, as issue #23624 shows, it's still causing confusion for users when they include more than 10 links.
Bumping this limit up to 24, which is a multiple of the 4 image preview per line logic.
Added automated test and ran the markdown suite:
```
./tools/test-backend zerver.tests.test_markdown
```
Including 24 links:
Including 25 links:
<details> …

markdown: Update max inline preview from 10 to 24.

---

zerver/lib/email_mirror.py
zerver/tests/test_email_mirror.py

When the email mirror gateway is sending messages "as" a user (as triggered by having access to the missed-message email address), attachments were still created as the Email Gateway bot.  Since the sender (the end-user) was not the owner of those attachments (the gateway bot), nor were they referenced yet anywhere, this resulted in the attachments being "orphaned" and not allowed to be accessed by anyone -- despite the attachment links being embedded in the message. This was accompanied by the error:
```
WARN [] User 12345 tried to share upload 123/3LkSA4OcoG6OpAknS2I0SFAQ/example.jpf in message 123456, but lacks permission
INFO [zerver.lib.email_mirror] Successfully processed email from user 12345 to example-stream
```
We solve this by creating attachment objects as the users the …

email_mirror: Create attachments as the message sender.

---

templates/zerver/help/scim.md

Updates the [SCIM provisioning](https://zulip.com/help/scim) page to match help center documentation patterns, and to use the newly added macros.
Fixes: #22890.
**Concerns:**
The wording should be double-checked for accuracy as I'm not familiar with SCIM provisioning.
<details>
</details>

help center: Update "SCIM provisioning" page.

---

static/templates/settings/admin_user_list.hbs
templates/zerver/help/user-cards.md
zerver/lib/markdown/tabbed_sections.py

- Associated a bot's name with its user card in Organization settings > Bots.
- a card opens when you click the bot's name.
Fixes: #23970
**ScreenShot (bot_user_card):**
**Demo Video:**
<details>
</details>

organization_settings: Link bot's user card to bot name.

---

scripts/lib/install-yarn
tools/ci/production-build
tools/setup/optimize-svg

Fixes check_version function in install-yarn script so that it does not give an error if the user has another version of yarn installed in their system path.
Before when running the provision script if a user had already another version of yarn installed it was giving an error since it was comparing the `version` required for zulip with the user-installed yarn.
This fixes it by improving the logic for checking version!
Fixes: #23993 
<details> …

provision: Fix bug in install-yarn script.

---

docs/production/requirements.md

docs: Mention probably needing to allow port 22 for SSH access.

---

static/js/stream_settings_ui.js

The logic for hash redirects for stream settings did not check for deleted or non-existent streams. Thus a hash of the form `/#streams/{invalid_stream_id}/*` gave gave a blueslip error.
This change fixes that logic to treat such hashes equivalent to streams whose settings cannot be accessed by that user and redirects such invalid hashes to `/#streams/subscribed/`.
Fixes: 
<details>
</details>

streams: Fix hash redirect for deleted/invalid stream ids.

---

templates/zerver/help/using-zulip-for-a-class.md

Converts the bullets at the top of the page into section links.
<details>
</details>

help center: Add section links in "Using Zulip for a class".

---

static/third/bootstrap-typeahead/typeahead.js

Fixes: #23681
https://user-images.githubusercontent.com/72064462/206907909-24f1b722-b73a-4364-b6ac-3c494c6a68b5.mov
https://user-images.githubusercontent.com/72064462/206907946-bee9d4f3-795d-48a5-8788-33d5a952be14.mov
https://user-images.githubusercontent.com/72064462/206907933-2745bb70-e68d-40f5-a18c-30fe065d65b1.mov

typeahead: Fix suggestion box positioning on window resize

---

static/templates/settings/organization_permissions_admin.hbs

Fixes #23801
<details>
</details>

fix: info icon size in organization settings permissions page.

---

tools/upload-release

In the very infrequent case that we re-upload a file, the logic for upload-release would have the existing SHA256SUM take precedence over the new one -- despite uploading the new file.
Skip existing filenames (i.e. from the new file) when gathering SHA256SUM metadata used to assemble `SHA256SUMS.txt`.
Fixes: 
<details>
</details>

upload-release: Update SHA256SUM for existing files if changed.

---

.github/workflows/update-oneclick-apps.yml

This is now a required dependency.

do: Install pynacl in the oneclick job.

---

frontend_tests/puppeteer_tests/realm-creation.ts
static/js/portico/signup.js
static/styles/portico/portico_signin.css
templates/zerver/accounts_send_confirm.html
zerver/lib/test_classes.py
zerver/tests/test_management_commands.py
zerver/tests/test_signup.py
zerver/views/registration.py
zproject/urls.py

urls: Convert email into a GET parameter.

---

puppet/zulip_ops/manifests/profile/base.pp
puppet/zulip_ops/manifests/profile/prometheus_server.pp
puppet/zulip_ops/manifests/prometheus/node.pp

puppet: Remove "ensure => absent" rules which have all been applied.

---

zerver/lib/email_mirror.py
zerver/tests/test_email_mirror.py

The content of a message is truncated to `MAX_MESSAGE_LENGTH`, which is 1000 characters.  Since the email gateway places attachments at the very end of the extracted body, that means that they are the first thing to get truncated off.
That is, if an incoming email message contains 1000 `a`s and an image attachment, the link that attaches the attachment to the message will get truncated off, leaving it dangling in the database.
Truncate the message body content separately from the attachment links which are included at the end of the body.
<details> …

email_mirror: Ensure that attachments get space to be included.

---

tools/release

release: Add tests for spelling and links in changelog.

---

tools/test-run-dev
zerver/lib/debug.py
zerver/middleware.py
zerver/tests/test_realm_export.py
zerver/worker/queue_processors.py
zproject/computed_settings.py

This is all debugging and test code, but it will be good to have this rule enforced going forward.

ruff: Fix S108 Probable insecure usage of temporary file

---

zerver/actions/create_user.py
zerver/actions/invites.py
zerver/actions/message_send.py
zerver/actions/realm_export.py
zerver/actions/streams.py
zerver/lib/onboarding.py
zerver/lib/test_classes.py
zerver/tests/test_event_queue.py
zerver/tests/test_event_system.py
zerver/tests/test_events.py
zerver/tests/test_message_send.py
zerver/tests/test_realm_export.py
zerver/views/realm_export.py

This PR changes the `do_reactivate_user` such that the complete function
is called inside an atomic transaction and events are called after the
transaction is commited using on_commit helper. This is a prep commit
for unsubscribing the bots of unaccessible private streams when reactivating
them (#22109).

create_user: Use transaction.atomic as decorator with do_reactivate_user.

---

static/styles/components.css
static/styles/modal.css
static/styles/portico/activity.css
static/styles/portico/billing.css
static/styles/portico/integrations_dev_panel.css
static/styles/portico/portico_signin.css
static/styles/settings.css
static/styles/subscriptions.css
static/styles/zulip.css
static/templates/invite_user.hbs
static/templates/move_topic_to_stream.hbs
static/templates/settings/add_new_bot_form.hbs
static/templates/settings/add_new_custom_profile_field_form.hbs
static/templates/settings/admin_human_form.hbs
static/templates/settings/custom_user_profile_field.hbs
static/templates/settings/display_settings.hbs
static/templates/settings/notification_settings.hbs
static/templates/settings/organization_permissions_admin.hbs
static/templates/settings/organization_profile_admin.hbs
static/templates/settings/organization_settings_admin.hbs
static/templates/settings/profile_settings.hbs
static/templates/stream_settings/stream_types.hbs
static/third/bootstrap/css/bootstrap.css
templates/corporate/upgrade.html
templates/zerver/development/dev_login.html
templates/zerver/development/integrations_dev_panel.html
templates/zerver/register.html
zerver/tests/test_signup.py

- First two commits are some refactor commits.
- Next nine commits add bootstrap CSS rules to the specific elements in different files.
- Next commit is to add `bootstrap-focus-style` class such that we can avoid duplicating the CSS in different files.
- Next commit removes the CSS for select elements from `bootstrap.css`.
- Last commit is to remove some redundant CSS.
<details>
</details>

Remove bootstrap CSS rules for select elements.

---

help/include/supporting-zulip-motivation.md
help/support-zulip-project.md

Notes:
- I can't actually see any difference between regular and bold font in links.

help: Tweak Support the Zulip project page.

---

puppet/zulip/manifests/app_frontend_base.pp
puppet/zulip/manifests/nginx.pp
puppet/zulip/manifests/postgresql_common.pp
puppet/zulip/manifests/profile/base.pp
puppet/zulip_ops/files/supervisor/conf.d/zmirror.conf
puppet/zulip_ops/manifests/apache.pp
puppet/zulip_ops/manifests/profile/base.pp
puppet/zulip_ops/manifests/profile/grafana.pp
puppet/zulip_ops/manifests/profile/prometheus_server.pp
puppet/zulip_ops/manifests/profile/zmirror_personals.pp
scripts/lib/upgrade-zulip-from-git

Various small puppet cleanups I just noticed.
<details>
</details>

Puppet cleanup

---

corporate/lib/stripe.py
corporate/tests/test_stripe.py

Updates the message sent by the notification bot when an organization is approved for full sponsorship on Zulip Cloud Standard to include a request to list and link to Zulip on any acknowledgement or sponsorship pages.
**Updated message**:
**Hovering over the link**:
---
<details>
</details>

notification-bot: Update message for approved full sponsorship.

---

static/third/bootstrap-typeahead/typeahead.js

Break on `keyup` for case of `shift` key, instead of letting it trigger the typeahead.
Fixes: #24152.
Before:
https://user-images.githubusercontent.com/68962290/214800322-966f7d08-ade9-4a21-8281-81780913a708.mp4
After:
https://user-images.githubusercontent.com/68962290/214802293-0ea146f9-290a-46ac-b9ee-f62d1271a323.mp4
<details>
</details>

typeahead: Fix bug where typeahead showed momentarily on shift + tab.

---

docs/production/deployment.md
puppet/zulip/manifests/profile/base.pp
puppet/zulip/manifests/timesync.pp

puppet: Allow choice of timesync tool.

---

frontend_tests/node_tests/dispatch.js
frontend_tests/node_tests/example4.js
frontend_tests/node_tests/people.js
static/js/people.js
static/js/server_events_dispatch.js
static/js/settings_users.js

As stated in the [help documentation](https://zulip.com/help/view-all-bots-in-your-organization), the user should be able to see all bots in the organization. This extends `people.js` to provide a way to access all bot users, and update organization settings to display all bots for non-admin users as well.
[chat](https://chat.zulip.org/#narrow/stream/9-issues/topic/Settings.20.2F.20.20Bots/near/1498137)
<details> …

settings: Show all bots in organization settings.

---

static/js/settings_emoji.js
static/shared/js/typeahead.js
static/templates/confirm_dialog/confirm_emoji_settings_warning.hbs
zerver/tests/test_realm_emoji.py
zerver/views/realm_emoji.py

emoji_settings: Only allow admins to override default emojis.
Uptil now, any user could add a custom emoji with the same name as a
default emoji, thus overriding it (with a confirmation after warning).
To create more friction for this action, now only admins are allowed to
add custom emojis that override default ones. All users can still add
custom emojis with other names.
Fixes: part of #24120
emoji_settings: Reword modal to confirm overriding default emoji.
Better explain what exact effects overriding a default emoji name has.
emoji: Fix code that checks if new custom emoji may override default.
<details> …

emoji_settings: Only allow admins to override default emojis.

---

scripts/setup/upgrade-postgresql

The `pg_upgrade` tool uses `pg_dump` as an internal step, and verifies that the version of `pg_upgrade` is the same exactly the same as the version of the PostgreSQL server it is upgrading to.  A mismatch (even in packaging versions) leads to it aborting:
```
/usr/lib/postgresql/14/bin/pg_upgrade -b /usr/lib/postgresql/13/bin -B /usr/lib/postgresql/14/bin -p 5432 -P 5435 -d /etc/postgresql/13/main -D /etc/postgresql/14/main --link
Finding the real data directory for the source cluster      ok
Finding the real data directory for the target cluster      ok
check for "/usr/lib/postgresql/14/bin/pg_dump" failed: incorrect version: found "pg_dump (PostgreSQL) 14.6 (Ubuntu 14.6-0ubuntu0.22.04.1)", expected "pg_dump (PostgreSQL) 14.6 (Ubuntu 14.6-1.pgdg22.04+1)"
Failure, exiting
```
Explicitly …

upgrade-postgresql: Also upgrade postgresql-client.

---

static/js/popovers.js
static/templates/stream_settings/stream_member_list_entry.hbs

Fixes part 1 of #18880.
This links user or bot names in stream -> subscribed users list to their respective user card.
The idea was taken from [this](https://github.com/zulip/zulip/commit/4901a0d19b70d959bd67f660dc66df760d8ea863).
**Screen captures:**
[streams_profile_popover.webm](https://user-images.githubusercontent.com/96468766/213846325-5750c000-19f2-448b-9287-2399ac7e196f.webm)
<details>
</details>

popovers: Link subscribed users to user cards.

---

tools/tail-ses

Minor bugfixes for tail-ses

---

templates/zerver/app/index.html

Using z-logo as inline SVG,
as fetching an external SVG doesn't serves the purpose.
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Loading.20screen-circle.20misaligned) 
Fixes: 
No Change in UI
<details>
</details>

index: use z-logo as inline svg.

---

corporate/lib/stripe.py
pyproject.toml
tools/linter_lib/custom_check.py
tools/semgrep.yml
zerver/lib/queue.py
zerver/management/commands/sync_ldap_user_data.py
zproject/backends.py

https://github.com/charliermarsh/ruff#flake8-logging-format-g

ruff: Enable logging format rules

---

static/styles/popovers.css

The top border on the avatar wasn't showing up since there wasn't enough space.
Added top margin to fix the issue
Fixes #24210
Before: 
After:
<details>
</details>

popovers: Add top margin to avatar in user profile

---

static/js/click_handlers.js

Prep commits for #23355. More information in commit messages.

compose dropdown prep commits

---

confirmation/models.py
zerver/views/auth.py
zerver/views/registration.py

This will help us track if users actually clicked on the email confirmation link while creating a new organization.

registration: Track create organization page in GA.

---

frontend_tests/node_tests/dispatch.js
static/js/admin.js
static/js/server_events_dispatch.js
static/js/settings_invites.js
static/templates/settings/invites_list_admin.hbs

Fixes: #24158
This PR fixes both the part of #24158. I have created a new function `update_invite_users_setting_tip` in `invite.js` for handling the permissions banner.
Screenshot for a non-admin user who can invite users.
Screenshot for a non-admin user who cannot invite users.
Screenshot for a admin for each possible permission configurations.
<details>
</details>

settings: Improve permissions banners on Invitations panel.

---

help/desktop-notifications.md
help/do-not-disturb.md
help/include/sidebar_index.md
help/mobile-notifications.md
help/pm-mention-alert-notifications.md
help/stream-notifications.md

This is an update on #24193.
Fixes #24169.

help: Document Do Not Disturb feature in Desktop app.

---

zerver/lib/upload/base.py

https://pillow.readthedocs.io/en/stable/deprecations.html#constants

upload: Replace deprecated PIL.Image.ANTIALIAS with LANCZOS

---

docs/production/deployment.md
puppet/zulip/manifests/profile/memcached.pp
puppet/zulip/templates/memcached.conf.template.erb

This is necessary for organizations with extremely large numbers of members (20k+).
<details>
</details>

memcached: Allow overriding the max-item-size.

---

frontend_tests/node_tests/composebox_typeahead.js
frontend_tests/node_tests/typeahead.js
static/js/composebox_typeahead.js
static/js/emoji_picker.js
static/js/search_suggestion.js
static/js/typeahead_helper.js
static/shared/js/typeahead.js
static/shared/js/typeahead.ts

We add a `.d.ts` file for `typeahead.js` so that `people.js` has the types when importing it.
Because Zulip Mobile also relies on the shared module, we do not directly convert `typeahead.js` to TypeScript to avoid transpilation.
This change also comes with some quick refactorings:
- Removed the default value to the `get_item` parameter of `triage`, since that default is incompatible with the type signature we expect.
- Removed `is_unicode_emoji`. So we don't need a user-defined type guard to type narrow `Emoji`, which might have undefined `emoji_code`.
<details> …

typeahead: Add type definitions for `shared/js/typeahead.js`

---

zerver/lib/markdown/__init__.py
zerver/tests/test_markdown.py

This also adds support for the new YouTube Shorts URLs.

markdown: Rewrite YouTube URL parser without regex spaghetti

---

static/templates/status_emoji.hbs

Fixes: #23516 
<details>
</details>

css: Fix Handle emoji not loading gracefully in PM list.

---

static/styles/components.css

https://github.com/Grsmto/simplebar/commit/030b89b94e463f9efa4d6b3d21ed14c921937c6a

styles: Fix horizontal SimpleBar height for SimpleBar 6

---

zilencer/management/commands/populate_db.py

The post-delete signal on AlertWord clears the realm cache; when it is called repeatedly, this results in re-fetching the realm object O(n) times, where n scales by number of users in the database.
Disconnect this cache-clearing signal before removing the AlertWord entries, and reconnect it afterwards.  This is not thread-safe, but this section is single-threaded.  It is also probably unnecessary to re-connect the signal, as rest of `./manage.py populate_db` does not delete AlertWord objects, but cleanliness dictates doing the re-connection.
This drops the time to repeatedly run:
python3 ./manage.py populate_db --num-messages=0 --extra-users=1000
...from 47 seconds to 36 seconds.
<details> …

populate_db: Temporarily remove post-delete signal on AlertWord.

---

zerver/lib/queue.py
zproject/default_settings.py
zproject/prod_settings_template.py

See zulip/docker-zulip#377.
<details>
</details>

rabbitmq: Add a RABBITMQ_PORT setting.

---

static/js/spectators.js
static/templates/navbar.hbs

spectators: Save a redirect to /register/.

---

static/js/click_handlers.js
static/js/compose_closed_ui.js
static/js/hotkey.js
static/js/message_list_view.js
static/js/message_scroll.js
static/js/muted_topics_ui.js
static/js/narrow_state.js
static/js/recent_topics_ui.js
static/js/tippyjs.js
static/js/ui_init.js
static/js/unread_ops.js

Just some prep commits towards #22408, I might push more commits here.

Minor refactors for inbox view.

---

static/styles/modal.css
static/styles/settings.css
static/styles/subscriptions.css
static/templates/move_topic_to_stream.hbs
static/templates/settings/account_settings.hbs
static/templates/settings/add_new_bot_form.hbs
static/templates/settings/add_new_custom_profile_field_form.hbs
static/templates/settings/admin_human_form.hbs
static/templates/settings/custom_user_profile_field.hbs
static/templates/settings/display_settings.hbs
static/templates/settings/edit_bot_form.hbs
static/templates/settings/edit_custom_profile_field_form.hbs
static/templates/settings/edit_outgoing_webhook_service.hbs
static/templates/settings/notification_settings.hbs
static/templates/settings/organization_permissions_admin.hbs
static/templates/settings/organization_profile_admin.hbs
static/templates/settings/organization_settings_admin.hbs
static/templates/settings/organization_user_settings_defaults.hbs
static/templates/settings/profile_settings.hbs
static/templates/stream_settings/stream_types.hbs

- First two commits are to add `settings_select` class to select elements and settings and streams settings pages.
- Next commit is to add `modal_select` class to select elements in modals.
- Next commit is to remove some duplicate CSS.
- Next commit adds `bootstrap-focus-style` class to some elements.
- Last commit is to fix disabled select elements in modals.
Followup of #23934.
For last commit changes -
Before -
After - 
<details> …

Refactor CSS for select elements and fix disabled select element in modals.

---

templates/zerver/reset.html

reset: Tag "forgot password" text for translation.

---

zerver/webhooks/sentry/doc.md

Before:
After:
<details>
</details>

sentry: Fix accidental blockquote by escaping >.

---

static/styles/popovers.css
static/templates/user_custom_profile_fields.hbs
static/templates/user_info_popover_content.hbs
static/templates/user_profile_modal.hbs

This PR deduplicates template code for showing custom profile fields in user info popover and full profile modal by extracting it in a new file and then using that template file to render the fields in user info popover and full profile modal.
This PR  does not change the design or behavior and they are same as before.
Discussion - https://github.com/zulip/zulip/pull/21588#discussion_r975883185
Before -
After -
<details> …

user_profile: Deduplicate code for showing custom profile fields.

---

scripts/log-search

```
2023-02-11 16:38:23.011 (start)
2023-02-11 16:38:23.012     1ms          301 GET    https://chat.zulip.org/register
------------   199ms gap ------------
2023-02-11 16:38:23.211 (start)
2023-02-11 16:38:23.233    22ms          200 GET    https://chat.zulip.org/register/
==========    9 second gap ==========
2023-02-11 16:38:32.920 (start)
2023-02-11 16:38:32.921     1ms          302 GET    https://chat.zulip.org/accounts/register/social/google
------------   302ms gap ------------
2023-02-11 16:38:33.223 (start)
2023-02-11 16:38:33.225     2ms          302 GET    https://chat.zulip.org/login/google/
============  2278ms gap ============
2023-02-11 16:38:35.503 (start)
2023-02-11 16:38:36.187   684ms          302 GET …
```

log-search: Add a --timeline option to show gaps and overlaps.

---

api_docs/changelog.md

[Current documentation](https://zulip.com/api/changelog)
<details>
<summary>Feature levels 164 & 163</summary>
</details>
<details>
<summary>Feature level 160</summary>
</details>
<details>
<summary>Feature level 150</summary>
</details>
<details>
<summary>Feature level 148</summary>
</details>
<details>
<summary>Feature level 43</summary>
</details>
---
<details>
</details>

api-docs: Fix small typos and copy/paste errors in API changelog.

---

scripts/log-search

Fixes: A silly mistake (no output when piped through `cat`) that I made by before-push "cleaning up" the code and not testing afterwards.
<details>
</details>

log-search: Fix precedence in no-color case.

---

zerver/tornado/event_queue.py

tornado: Speed up hot path by removing use of asdict

---

help/dark-theme.md

- Documents "Night mode" option.
- Adds Related articles section.
- https://zulip.com/help/dark-theme
<details>
</details>

help: Document dark-theme mobile feature.

---

zerver/lib/timestamp.py

This is quite a bit faster:
```
%timeit calendar.timegm(now.timetuple())
2.91 µs ± 361 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
%timeit int(now.timestamp())
539 ns ± 27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
This is particularly important for the presence endpoint, which is a tight loop of serializing datetimes.
<details>
</details>

timestamp: Switch to a slightly faster datetime_to_timestamp.

---

help/change-your-language.md
help/include/mobile-stream-settings-menu-tip.md
help/include/send-group-pm.md
help/mute-a-topic.md
help/private-messages.md
help/view-someones-profile.md
static/images/help/mobile-chevron-left.svg

- https://zulip.com/help/change-your-language
<details>
</details>

help: Document how to change the language of the Zulip mobile app.

---

static/templates/user_custom_profile_fields.hbs

Previously, we showed the icons for "Twitter" and "Github" type external account custom profile fields in the user-info popover. This PR changes the code to show the icons in full profile modal as well.
<details>
</details>

user_profile: Show icons for external account fields in full modal.

---

help/stream-notifications.md

- Documents how to set default notifications for all streams and single streams.
- https://zulip.com/help/stream-notifications
<details>
</details>

help: Document stream notifications mobile feature.

---

docs/production/export-and-import.md

This documentation was written in 9ece4c9f5148, which predated the `./manage delete_realm` command added in bff503feb4a1.
<details>
</details>

docs: Update instructions for realm deletion to use management command.

---

web/styles/portico/markdown.css

Some code blocks in the help center have lines that are too long to fit, and wrap onto the next line. This can look awkward, and may cause confusion. An horizontal scroll bar is added to the code blocks to help fit everything into their own lines and clear up confusions.
Fixes #24004.
Before: 
After: 
<details>
</details>

documentation: Add a horizontal scroll bar to code blocks in help center.

---

templates/corporate/security.md

portico: Clarify encryption at rest information on /security.

---

puppet/deps.yaml
scripts/lib/puppet_cache.py

puppet: Pin with sha256sum verification.

---

api_docs/changelog.md

api-docs: Fix changelog formatting for feature level 165.

---

templates/zerver/integrations/hubot.md
templates/zerver/integrations/irc.md
zerver/webhooks/dropbox/doc.md
zerver/webhooks/wekan/doc.md

Fixes some integrations documentation so that code blocks and images are rendered in the correct HTML list elements.
**Notes**:
- I only did a visual audit of the integrations documentation pages for alignment and list numbering errors. I did not go through the actual text / content of these pages.
---
<details>
<summary>Hubot integration - indentation error</summary>
[Current documentation](https://zulip.com/integrations/doc/hubot)
</details>
<details>
<summary>IRC integration - code blocks being rendered as inline code elements</summary>
[Current documentation](https://zulip.com/integrations/doc/irc)
</details>
<details>
<summary>Dropbox integration - numbering error</summary>
[Current documentation](https://zulip.com/integrations/doc/dropbox) …

integrations-docs: Fix indentation issues in existing documentation.

---

zerver/lib/onboarding.py

The inital Welcome bot message has an extra section if the user is joining a demo organization, but the link in that section was not being formatted correctly. Fixes the formatting so that the link works.
**Notes**:
- Used the `organization_setup_text` as a model for these changes.
---
<details>
<summary>Current main branch when a demo organization is created</summary>
</details>
<details>
<summary>After changes</summary>
</details>
---
<details> …

demo-orgs: Fix link to help center in Welcome bot message.

---

puppet/zulip/files/cron.d/delete-old-unclaimed-attachments
puppet/zulip/manifests/app_frontend_once.pp

As discussed around https://chat.zulip.org/#narrow/stream/31-production-help/topic/Message.20retention/near/1389970

Add notes on how archive cleaning works and add cronjob to run delete_old_unclaimed_attachments

---

api_docs/changelog.md

**Notes**:
- Fixes spacing in markdown file so list element is rendered correctly.
- Also, updates the entry to note that the removed `realm_str` parameter was undocumented, which is why there is no corresponding **Changes** note in the specific `/send-message` endpoint documentation
- Replaces "it'll" with "it will".
---
---
<details>
</details>

api-docs: Fix changelog formatting for feature level 166.

---

zerver/actions/invites.py

invites: Limit invites per day as a function of current users.

---

web/styles/subscriptions.css

made stream-header div a flex
change max-width of .sub-stream-name to take 100% of available space 
add 1rem margin-left to button-group for space.
Fixes: 
#24507
Before:
After:
<details>
</details>

Fix: Long stream names abbreviated too early in stream settings.

---

analytics/tests/test_support_views.py
templates/zerver/register.html
tools/test-api
zerver/lib/test_helpers.py
zerver/tests/test_event_system.py
zerver/tests/test_events.py
zerver/tests/test_message_send.py
zerver/tests/test_mirror_users.py
zerver/tests/test_presence.py
zerver/tests/test_signup.py
zerver/tests/test_subs.py
zerver/tests/test_users.py
zerver/views/registration.py

Follow-ups discussed in #22994 and #24394.
Fixes: 
- https://github.com/zulip/zulip/pull/24394#discussion_r1113454316
- https://github.com/zulip/zulip/pull/22994#discussion_r1091298810
<details>
</details>

Rename `reset_emails_in_zulip_realm` function.

---

web/src/dialog_widget.js
web/src/settings_users.js
web/styles/components.css
web/styles/portico/email_log.css
web/templates/confirm_dialog/confirm_deactivate_user.hbs
web/third/bootstrap/css/bootstrap.css

- First commit is just a refactor commit to move the code to correct module.
- Next two commits are to remove some CSS selectors which have no such elements.
- Next commit is to make checkbox in user deactivation modal same as others.
- Next commit is to add bootstrap CSS for checkbox in emails page.
- Next commit is to add bootstrap CSS for ".checkbox" elements.
- Last two commits are to remove the bootstrap CSS for checkbox elements.
Updated checkbox in user deactivation modal -
<details> …

Remove bootstrap CSS for checkbox inputs.

---

web/src/settings_users.js
web/src/stream_create_subscribers.js
web/src/stream_edit_subscribers.js
web/templates/stream_settings/new_stream_users.hbs
web/templates/stream_settings/stream_members.hbs

Tables in create stream UI and stream subscribers can now be sorted on the basis of USER ID, Email and Name.
Fixes: #21341 
<details>
</details>

streams: Allow sorting of stream members.

---

help/support-zulip-project.md

Also minor tweaks to the details below.
Current page: https://zulip.com/help/support-zulip-project

help: Expand introduction on /help/support-zulip-project.

---

web/src/muted_topics_ui.js

This was broken by 6e6fb47e20ef690ddeae276de8c3d38f88d9073d (#24386).

muted_topics_ui: Rename mute_topic parameter to fix shadowing bug

---

docs/subsystems/analytics.md

The correct path for the stats file has been updated in the docs.
<details>
</details>

docs: Fix update correct path for stats file

---

web/src/user_group_create_members.js
web/src/user_group_edit_members.js
web/templates/user_group_settings/new_user_group_users.hbs
web/templates/user_group_settings/user_group_members.hbs

As mentioned in #24493 this PR adds support for sorting of subscribers.
<details>
</details>

user groups: Enabled sorting of subscribers.

---

web/styles/popovers.css

When someone hovers over the Github username in the popover with 
dark theme, a background will appear. These changes ensures that 
the `background-color` isn't overwritten by other CSS.
<details>
<Summary>Before:</Summary>
</details>
<details>
<Summary>After:</Summary>
</details>
<details>
</details>

popovers: Remove background when hovering Github username.

---

web/templates/confirm_dialog/confirm_emoji_settings_warning.hbs

Adds a `div` wrapper with the `rendered_markdown` class to the content in `confirm_emoji_settings_warning.hbs`, so that the inline code element has the intended CSS rules applied.
Because the `p` element also has the `rendered_markdown` class, the margins for this element in the modal are slightly changed (3px on top/bottom). Previously, the margins for this element were being set from a bootstrap rule (10px on bottom).
**Notes**:
- This change would allow us to move the `code` rules in `rendered_markdown.css` to all be in the `rendered_markdown` class block.
| --- | --- |
| ![Screenshot from 2023-03-03 17-19-39](https://user-images.githubusercontent.com/63245456/222780144-05663b31-3a85-4a08-a1b3-24f23d2f922f.png) | ![Screenshot from …

templates: Add `rendered_markdown` class to confirm emoji warning.

---

web/e2e-tests/admin.test.ts

Fixes a small console logging error in `web/e2e-tests/admin.test.ts` that was likely a copy and paste error.
<details>
</details>

puppeteer: Fix small logging copy and paste error in `admin.test.ts`.

---

web/src/linkifiers.ts

This converts `linkifers.js` to TypeScript.
For Verification of the Types used, I went on to create an
Organization on Zulip to test the linkifiers endpoint on it. 
These are the results from the API Call.
The `linkifiers` key has an array of objects of the following 
structure:
```
{
pattern: string,
url_format: string,
id: string
}
```
The same can be verified in the docs. [Link to Docs](https://zulip.com/api/get-linkifiers#response)
<details> …

ts: Convert linkifiers.js to TypeScript.

---

tools/lib/capitalization.py
zerver/lib/events.py
zerver/models.py

Before:
After:
<details>
</details>

i18n: Add translation to giphy integration options.

---

zproject/test_extra_settings.py

7ad06473b6d9 split out `LOCAL_AVATARS_DIR` and `LOCAL_FILES_DIR` as derived values from `LOCAL_UPLOADS_DIR`.  However, this means that all places which set `LOCAL_UPLOADS_DIR` need to potentially propagate that change into the derived values if they come *after* `computed_settings.py` is applied.  It did this successfully in `zerver/lib/test_runner.py` and the `use_s3_backend` decorator, but did not adjust the late-set `zproject/test_extra_settings.py`.
This causes tests to share a single common set of avatars and attachments directories.  In puppeteer tests, this leads to assertion failures checking `assert_is_local_storage_path`; in backend tests, this leads to races when checking the contents of the local storage directory when run in parallel mode.
Set `LOCAL_AVATARS_DIR` and …

tests: Set LOCAL_AVATARS_DIR / LOCAL_FILES_DIR in tests.

---

zerver/actions/message_edit.py
zerver/actions/message_send.py
zerver/actions/user_topics.py
zerver/lib/notification_data.py
zerver/lib/stream_topic.py
zerver/lib/user_topics.py
zerver/tests/test_event_queue.py
zerver/tests/test_events.py
zerver/tests/test_import_export.py
zerver/tests/test_message_edit.py
zerver/tests/test_message_flags.py
zerver/tests/test_user_topics.py
zerver/tests/test_users.py
zerver/views/user_topics.py

This carries forward the work in #22923 
Fixes #2517.

Unmute topic

---

web/styles/modal.css

Updated modal.css to make button background color look disabled.
Fixes #24567
Fixes: 
<details>
</details>

popovers: Make primary action button in modals look disabled in light theme.

---

help/support-zulip-project.md

Current: https://zulip.com/help/support-zulip-project (prior changes in `main` have not been deployed yet)
<details>
<summary>Updated screenshots</summary>
</details>
---
Current: https://zulip.com/help/linking-to-zulip-website
<details>
<summary>Updated screenshot</summary>
</details>

help: Add context/motivation to Support the Zulip project help page.

---

zerver/lib/test_classes.py

test_classes: Provide path to test-backend for ease of copy/paste.

---

analytics/tests/test_counts.py
zerver/actions/invites.py

Follow-up to #24524.
<details>
</details>

Tune invite logging

---

zerver/openapi/zulip.yaml

Discussed in https://github.com/zulip/zulip/pull/24313#issuecomment-1426565317
<details>
</details>

openapi: Add links to email_address_visibility help documentation.

---

web/styles/subscriptions.css

Added css for .hide class on screen width < 575px.
Fixes: 
#24589
Before: 
https://user-images.githubusercontent.com/64723994/222980970-94d4a8bc-a325-43a9-852f-b014dbc49591.mp4
After:
<details>
</details>

stream_settings: Fix bug save changes button show on screen width< 575px.

---

web/src/hashchange.js

Till now, whenever the hash was updated using the `set_hash` function, the new url was always pushed into the browser history, even if the current hash was same as the new hash. This lead to multiple duplicate entries in the browser history, when using the `z` hotkey to zoom to a message repeatedly, which is very inconvenient when navigating through history.
This is now fixed by simply returning prematurely from `set_hash` if the new hash is same as the current one. This fix will also prevent any future features like `z` from causing duplicate browser history entries.
Fixes: #24468.
<details> …

hashchange: Ensure no duplicate entries in browser history.

---

web/styles/right_sidebar.css

[CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/search.20people.20ui.20not.20looking.20good.20on.20small.20width.20devices)
**before -**
**after -**
<details>
</details>

css: Fix search bar width in right sidebar.

---

templates/corporate/development-community.md

Adds a sub-section in the Zulip [development community](https://zulip.com/development-community/) landing page about using the custom linkifiers in chat.zulip.org for the different Zulip project repositories on GitHub.
See [relevant conversation in CZO](https://chat.zulip.org/#narrow/stream/137-feedback/topic/linkifier.20visibility/near/1513440).
---
<details>
<summary>New linkifiers section</summary>
</details>
<details>
<summary>Updated "Anything else to keep in mind?" section</summary>
[Current page](https://zulip.com/development-community/#anything-else-to-keep-in-mind)
</details>
---
<details> …

landing-pages: Add section on chat.zulip.org custom linkifiers.

---

help/configure-how-links-open.md
help/include/sidebar_index.md

- Documents "Open links with in-app browser" option.
- Adds new page right below “View and browse images”.
<details>
</details>

help: Add “Configure how links open” page.

---

api_docs/api-keys.md
web/templates/settings/api_key_modal.hbs

This PR changes the wording of "Show API key" modal. The changes are shown below.
Fixes: #24506.
Before:
After:
This PR also changes the documentation of API keys. The changes are shown below.
Before:
After:
<details>
</details>

settings : Refactor "Show API key" modal for improved wording.

---

scripts/lib/zulip_tools.py

Before:
```
+ ./tools/webpack --quiet
Error running a subcommand of ./tools/update-prod-static: ./tools/webpack --quiet
Actual error output for the subcommand is just above this.
```
After:
```
+ ./tools/webpack --quiet
Subcommand of ./tools/update-prod-static died with SIGKILL: ./tools/webpack --quiet
```

zulip_tools: Improve error for `run` subprocess killed by signal

---

web/src/overlays.js
web/src/popovers.js
web/src/ui_init.js

This is a Prep PR for [#24426](https://github.com/zulip/zulip/pull/24426).
Removes direct dependency cycle between 'popover.js' and overlays.js by creating popover.initialize method called from 'ui_init.js' that calls
overlays.register_pre_open_hook(hide_all) and
overlays.register_pre_close_hook(hide_all).
Created a function call_hook that loop call all
registered hooks at the start of 'open_overlay' and 'close_overlay'.
Fixes: 
<details> …

overlays: Fix dependency cycle between popover.js and overlays.js.

---

help/configure-how-links-open.md
help/include/sidebar_index.md

- Moves page to the "Apps" section of the sidebar.
- Adds "in mobile apps" to the top-of-page title.
Follow-up to #24447.
<details>
</details>

help: Move "Configure how links open" to the Apps section.

---

help/include/mobile-view-user-profile-tip.md
help/status-and-availability.md
help/view-someones-profile.md

- Adds instructions blocks for web/desktop and mobile.
- https://zulip.com/help/status-and-availability#view-a-status
<details>
</details>

help: Add instructions for viewing status.

---

web/src/admin.js
web/src/settings.js
web/src/settings_bots.js
web/templates/settings/bot_list_admin.hbs
web/templates/settings/bot_settings.hbs
web/templates/settings/bot_settings_tip.hbs

As mentioned in #24188 this PR is an updated version of #24198
Fixes: #24155
<details>
</details>

bots: Improve bots permission banner.

---

web/styles/portico/portico.css

https://chat.zulip.org/#narrow/stream/19-documentation/topic/.2Fhelp.20sidebar.20wrapping/near/1522006

styles: Fix layout shifting for highlighted help sidebar link

---

help/import-from-slack.md

Previously, the help center has a broken link that just points to Slack's help center. With this change, we will remove and replace the link to their OAuth scope section.
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Slack.20import.20help)
Before: https://slack.com/help/articles/115005265703-Create-a-bot-for-your-workspace
After: https://api.slack.com/authentication/basics#scopes
<details>
</details>

help: Update broken link in `import from slack`.

---

web/styles/app_components.css
web/styles/settings.css
web/styles/subscriptions.css

- First commit is to fix width of select elements in settings page. The width is set to auto so that they can be wide enough for different languages with minimum width set to 325px.
- Second commit is to fix width of select elements in stream settings page. The width is set to auto so that they can be wide enough for different languages with minimum width set to 325px.
- Third commit is to fix the width of dropdown-list-widget for long options.
https://chat.zulip.org/#narrow/stream/101-design/topic/select.20elements.20in.20settings
<details> …

Fix width of select elements in settings.

---

api_docs/changelog.md

As discussed in https://chat.zulip.org/#narrow/stream/378-api-design/topic/update_message.20default.20notifications/near/1523875.

API changelog: Fix an omission and clarify individual endpoint documentation is more detailed

---

help/deactivate-your-account.md
zerver/tests/test_middleware.py

Testing:
- Manually tested links.
Current page: https://zulip.com/help/deactivate-your-account
Updated version:

help: Improve "Deactivate your account" help page.

---

zerver/webhooks/github/doc.md

The list of supported events for filtering itself does not document what
each of the events does. Adding a link to GitHub's documentation would
be a pointer to get people started. But ideally we need to establish a
better system to document the events in general.
[Relevant chat](https://chat.zulip.org/#narrow/stream/9-issues/topic/GitHub.20bot.20missing.20events/near/1520438)
<details>
</details>

integrations: Add a link to GitHub webhooks documentation.

---

package.json
version.py
web/src/people.js
web/src/settings_data.ts
web/src/util.ts
web/tests/people.test.js
yarn.lock

This is a sequence for changes to prepare for #24653.
<details>
</details>

ts: Prepare for converting people.js to people.ts

---

scripts/lib/install-node
version.py
web/tests/drafts.test.js
web/tests/rendered_markdown.test.js
web/tests/timerender.test.js

Maybe this will help dodge nodejs/nodejs.org#5149.

install-node: Upgrade Node.js from 18.14.1 to 18.15.0

---

puppet/zulip_ops/manifests/app_frontend.pp

puppet: Enable sentry hooks for production and staging.

---

requirements/dev.txt
requirements/prod.txt
version.py
zerver/lib/cache.py

Previously, `QuerySet` did not support `isinstance` check since it was defined to be generic in `django-stubs`. In a recent update, such a check is possible by using `QuerySetAny`, a non-generic alias of `QuerySet`.
This is a follow-up to https://github.com/zulip/zulip/pull/23215#discussion_r993961077 after the integration of https://github.com/typeddjango/django-stubs/pull/1199.
<details>
</details>

cache: Use QuerySetAny for isinstance check.

---

web/src/portico/integrations_dev_panel.js

(Did basic testing of http://localhost:9991/devtools/integrations/.)

integrations_dev_panel: Fix unsafe use of innerHTML

---

api_docs/incoming-webhooks-walkthrough.md

The documentation at this [link](https://zulip.com/api/incoming-webhooks-walkthrough#step-3-create-an-api-endpoint-for-the-webhook) says:
> In order for an incoming webhook to be externally available, it must be mapped to a URL. This is done in zerver/lib/integrations.py.
> Look for the lines beginning with:
> `WEBHOOK_INTEGRATIONS = [`
But no such line **exactly** exists in `zerver/lib/integrations.py` instead, the line that exists now is:
`WEBHOOK_INTEGRATIONS: List[WebhookIntegration] = [`
This PR updates the code snippet to the current line that exists.
<details>
<summary> Hello world walkthrough </summary>
[Link to the Page](https://zulip.com/api/incoming-webhooks-walkthrough#step-3-create-an-api-endpoint-for-the-webhook)
</details>
<hr></hr>
<details> …

docs: Change python code snippet to the existing one.

---

zerver/actions/invites.py

The RealmCount statistics will be empty if the realm was created since the last daily aggregation.  In cases where the daily stats have no rows, it is likely fast enough to do the real count in the messages table.  This stops unduly penalizing folks who have actually sent messages, and are just inviting people within the first day.
<details>
</details>

invite: Be more fair about the no-messages-sent warning flag.

---

web/styles/portico/portico.css

styles: Extend help sidebar heading links like list links

---

zerver/webhooks/azuredevops/tests.py
zerver/webhooks/azuredevops/view.py

This is a follow up to #24673, we want to modify every webhook events to follow the same pattern and consistency where branch name should only show on opened and merged events.
<details>
</details>
<details>
</details>
<details>
<details>
</details>

integration: Add branch names to Azure Devops merged PR event.

---

web/src/composebox_typeahead.js
web/templates/topic_typeahead_hint.hbs

With the autocomplete dropdown, some users face trouble or uncertainty while selecting topics. The autocomplete dropdown may encourage users to find and select an existing topic rather than starting a new topic. The changes adds a hint text to the topic typeahead dropdown to encourage users to either start a new topic or select an existing topic.
Fixes [#23295](https://github.com/zulip/zulip/issues/23295).

compose: Add hint text to topic typeahead dropdown

---

docs/documentation/api.md

Updates this section to use the shared `api-doc-template.md` as a guide, as well as the current documentation for the `render-message` endpoint. Previously, this section referred to a file that had been removed with the transition to a shared template file.
Fixes #24485.
**Notes**:
- Ideally, this section and the following would be converted to be more like the new feature tutorial, with this section as the general process and the next section following a specific example.
<details>
<summary>Updated "How it works" section</summary>
</details>
---
<details> …

docs: Update "How it works" section in writing REST API documentation.

---

zerver/management/commands/send_welcome_bot_message.py

We should consider doing this step automatically for imports which don't have a welcome bot user (i.e. conversions from other systems, but not imports from other Zulip systems).
<details>
</details>

management: Add a command to send initial welcome bot messages.

---

templates/zerver/create_realm.html

The string "Or import from Slack, Mattermost, Gitter, or Rocket.Chat." in create_realm.html was not tagged for translation before. This PR fixes it to tag the string for translation.
<details>
</details>

create_realm: Tag import string for translation.

---

scripts/log-search

log-search: Support HTTP method limits.

---

web/third/bootstrap-typeahead/typeahead.js

Removed a redundant call to bootstrap typeahead's `lookup` function when the `automated` function returns true, which was causing the streams typeahead to show up briefly before the topic typeahead on pressing `>` immediately after a stream name.
Fixes: [issue described on CZO here](https://chat.zulip.org/#narrow/stream/9-issues/topic/stream-topic.20typeahead/near/1529503)
Before:
After:
https://user-images.githubusercontent.com/68962290/226888521-5c3691b9-370b-4cb3-970c-932ff746a6cc.mp4
<details> …

typeahead: Fix stream typeahead flashing before topic typeahead.

---

zerver/actions/create_realm.py
zerver/tests/test_signup.py

When a new realm is created, a notification message is sent to the realm configured as the `settings.SYSTEM_BOT_REALM` if there is a stream in that realm named "signups". The topic of the message is the name of the new realm and the message content is always "Signups enabled" (translated into the default language of the new realm).
In order to make these messages more useful for an organization that's hosting multiple realms (like Zulip Cloud), the topic for these notification messages is changed to be "new organization registrations" and is translated into the default language of the admin realm.
The content of these messages is updated to have the new realm name (with a link to the admin realm activity support page for the new realm) and the organization type of the new realm. …

create-realm: Update notification message sent to admin realm.

---

puppet/deps.yaml
puppet/zulip/manifests/common.pp

puppet: Update dependencies.

---

web/src/sentry.ts

We have the information about all of these failures from the server side, and Sentry groups all 5xx failures together with no stacktrace, which makes them very difficult to get signal out of.
<details>
</details>

sentry: Drop HttpClientIntegration.

---

web/src/localstorage.js

The localstorage machinery can fail for totally arbitrary reasons, including filesystem breakages on the part of the client, or capricious access control.
Wrap accesses to localstorage with try/catch blocks to do our best, but continue execution in the event that the localstorage API errors out; it is better to continue with the rest of our intended actions than get hung up on those failures.
<details>
</details>

localstorage: Accesses can fail randomly; make best-effort.

---

web/src/click_handlers.js

Added condition for when a user clicks anywhere in a typeahead menu, be it the header or empty space at the top and bottom, to not collapse the compose box.
This fixes the bug where clicking anywhere on the typeahead except the options would result in the compose box collapsing, but the typeahead menu staying open and still working (on selecting a option in this state, it would be inserted at the start, as visible on reopening the compose box).
Fixes: [Issue described on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/.22Start.20a.20new.20topic.22.20closes.20compose.20box)
https://user-images.githubusercontent.com/68962290/227606609-782f3a18-7754-48f7-bbad-da275d18842b.mp4
<details> …

click_handlers: Ensure typeahead clicks do not collapse compose box.

---

templates/zerver/portico-header.html

discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/account.20pages.20nav.20bar.20not.20translated

portico-header: Tag all links for translation.

---

web/src/tippyjs.js

message_controls: Fix "undefined" tooltip content.

---

docs/translating/index.md
docs/translating/japanese.md
docs/translating/translating.md

Added a Japanese translation style guide.
Current contents are based on discussions at [#translation](https://chat.zulip.org/#narrow/stream/58-translation) in the Zulip development community server.
Fixes: [no issue]
<details>
</details>

docs: Add a Japanese translation style guide.

---

web/src/message_list_view.js

message_list_view: Initialize status_message even for hidden messages

---

web/styles/subscriptions.css

Long stream description makes the sub-stream-description section scrollable, which doesn't looks good on the UI part.
Instead of this, the description should wrap to the next line.
To do so, we add the ```word-break: break-all``` property into the CSS of its corresponding class.
Previous Behavior:
New Behavior:
<details>
</details>

stream_settings: Fix stream description overflow in stream settings.

---

web/src/server_events_dispatch.js
web/tests/dispatch.test.js
web/tests/lib/events.js

server_events_dispatch: Fix live-update of email_address_visibility.

---

web/src/settings_users.js
web/templates/settings/admin_user_list.hbs

Disabled "Edit bot" and "Deactivate" action buttons for system bots as they cannot be edited or deactivated. 
Fixes: #24425
<details>
</details>

bots: Disable edit button for system bots.

---

web/src/settings_bots.js

bots: Disable `Save changes` button until user makes some changes.

---

puppet/zulip_ops/files/nagios4/commands.cfg
puppet/zulip_ops/files/nagios4/conf.d/services.cfg

Swap usage is not a high signal thing to alert on, and is likely to flap.
<details>
</details>

nagios: Remove swap check.

---

web/styles/app_components.css

- First commit is to fix the dropdown menu for short options.
- Second commit is to make the menu wide enough to fit the options in stream creation form.
Fixes - https://chat.zulip.org/#narrow/stream/9-issues/topic/.22who.20can.20unsubscribe.22.20dropdown
First commit changes -
Before
After
<details>
</details>

Fix dropdown-list-widget menu in settings and stream creation form.

---

web/styles/rendered_markdown.css

Previously, the emoji size was fixed to 20px by 20px irrespective of
whether the emojis were inside a heading or not. This looked weird when
a small emoji was rendered next to a large h1 text.
This commit fixes that by proportionately increasing the size of the
emojis as the text size increases for different headings.
Fixes: #12857 
Before
After
<details> …

markdown: Render larger emojis inside headings

---

web/src/settings_notifications.js
web/templates/confirm_dialog/confirm_disable_all_notifications.hbs

Fixes: #24151 
Modal shown when all notifications are about to get disabled.
<details>
</details>

notifications:Added modal to warn when all notifications are about to get disabled.

---

docs/production/install.md

This PR is inspired by (and replaces) #24765. From #24765:
>The first question in this guide first surprised me.
Then I understood how clever it is. 👍
> However, none of the bullets felt like they applied to me, so the
question was unanswered and I had to resort to guessing. Here's my
guess, in hopes that it's correct.
Current page: https://zulip.readthedocs.io/en/latest/production/install.html
Updated screenshot:

docs: Clarify "Should I follow this installation guide?" instructions.

---

web/src/read_receipts.js

-----------------------
Fixes: #24778 
--------------------------
**Demo**:
<details>
</details>

Read receipts: Open read receipts help link in new tab

---

package.json
pnpm-lock.yaml
scripts/lib/node_cache.py

https://chat.zulip.org/#narrow/stream/2-general/topic/pnpm/near/1529915

More effective workaround for pnpm failures on Docker for Mac?? 🤷

---

puppet/zulip/manifests/common.pp
puppet/zulip_ops/manifests/profile/chat_zulip_org.pp
puppet/zulip_ops/manifests/profile/postgresql.pp
puppet/zulip_ops/manifests/prometheus/postgresql.pp
puppet/zulip_ops/manifests/prometheus/rabbitmq.pp
puppet/zulip_ops/manifests/prometheus/redis.pp
puppet/zulip_ops/manifests/prometheus/tornado.pp
puppet/zulip_ops/manifests/prometheus/uwsgi.pp
puppet/zulip_ops/templates/supervisor/conf.d/prometheus_postgres_exporter.conf.template.erb

prometheus: Add a postgresql exporter.

---

web/styles/compose.css

Figma: https://www.figma.com/file/jbNOiBWvbtLuHaiTj4CW0G/Zulip-Web-App?node-id=2441%3A180271&t=tFynBT5Akes5HJ95-0

compose: Reduce height of compose banners to better match designs.

---

web/src/stream_edit.js
web/src/stream_settings_ui.js

Now when we archive a stream even while switching between tabs the archived stream is removed from the right panel.
Fixes: #23855
**Before**
https://user-images.githubusercontent.com/86338542/210631451-5e199c7a-09b1-4b8d-bc5d-0a0e3fd17edf.mp4
**After**
https://user-images.githubusercontent.com/86338542/210632773-fb7bf33f-45d3-4434-8187-02ff82d113da.mp4
<details>
</details>

fix: While archiving a stream the page does not get updated.

---

web/templates/settings/organization_permissions_admin.hbs

settings: Point the "moving messages" help link to the right place.

---

tools/test-js-with-node
web/src/scroll_bar.ts

This PR addresses the migration of file `web/src/scroll_bar.js` to typescript.
Fixes: 
<details>
</details>

ts: Migrate scroll_bar.js to typescript.

---

tools/test-js-with-node
web/src/debug.ts

This pull request converts `web/src/debug.js` to typescript
In making that possible,I added `interface Collisions ` in `function check_duplicate_ids` to specify the strict parameter types to define the types of the collisions parameter of `check_duplicate_ids`  which is an object and   also add the required `return types` to all the functions
<details>
</details>

ts : Migrate debug.js to typescript

---

docs/overview/changelog.md

docs: Update changelog to cover changes already staged for 7.0.

---

web/styles/zulip.css

Remove unnecessary `relative` positioning from the invite link.
Fixes: https://chat.zulip.org/#narrow/stream/9-issues/topic/misaligned.20link.20in.20invite.20users.20modal
Before:
After:
<details>
</details>

css: Fix misaligned invite link.

---

pyproject.toml

mypy: Remove exclusions for unused cssutils and premailer packages

---

api_docs/changelog.md
version.py
zerver/openapi/zulip.yaml
zerver/tests/test_auth_backends.py
zerver/views/auth.py
zerver/views/development/dev_login.py

Adds the user ID to the return values for the `/fetch_api_key` and `/dev_fetch_api_key` endpoints. This saves clients, like mobile, a round trip to the server to get the user's unique ID as it is now returned as part of the login flow.
See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/378-api-design/topic/user.20ID.20in.20fetch-api-key/near/1540592) for more details.
Fixes #24980.
<details>
<summary>API changelog note</summary>
</details>
<details>
<summary>Response documentation</summary>
</details>
---
<details> …

backend-auth: Add user ID to fetch api key responses.

---

web/src/hashchange.js

Observed in prod.
<details>
</details>

hashchange: Handle when history object has been marked dead.

---

.github/workflows/production-suite.yml
.github/workflows/zulip-ci.yml

[6.x] ci: Only report failures to CZO on branch pushes

---

web/templates/markdown_help.hbs
web/tests/lib/handlebars.js
web/webpack.config.ts

https://handlebarsjs.com/api-reference/compilation.html
https://chat.zulip.org/#narrow/stream/6-frontend/topic/handlebars.20undefined.20variables

templates: Enable Handlebars strict mode

---

puppet/zulip/files/hooks/common/sentry.sh
puppet/zulip/files/hooks/common/zulip_notify.sh
puppet/zulip/files/hooks/post-deploy.d/push_git_ref.hook
puppet/zulip/files/hooks/post-deploy.d/sentry.hook
puppet/zulip/files/hooks/post-deploy.d/zulip_notify.hook
puppet/zulip/files/hooks/pre-deploy.d/sentry.hook
puppet/zulip/files/hooks/pre-deploy.d/zulip_notify.hook
puppet/zulip/manifests/hooks/base.pp
puppet/zulip/manifests/hooks/file.pp
puppet/zulip/manifests/hooks/push_git_ref.pp
puppet/zulip/manifests/hooks/sentry.pp
puppet/zulip/manifests/hooks/zulip_notify.pp
puppet/zulip_ops/manifests/profile/prod_app_frontend.pp
scripts/lib/upgrade-zulip-stage-2
scripts/lib/zulip_tools.py

There's too much repetition in these two files, but it's not clear where the common code should live.  Maybe make a `/etc/zulip/hooks/common/`? Sentry has some common code that could be pulled out.
But there's also a common theme between the two hooks of "get the merge-base of the commits" and/or "get the actual git commit SHA of the deploy" which we shouldn't have to re-compute in the hooks.  We can extend the "API" to be:
```
hook-script OLD_DEPLOY_NAME NEW_DEPLOY_NAME [OLD_MERGE_BASE_SHA OLD_COMMIT_SHA NEW_MERGE_BASE_SHA NEW_COMMIT_SHA]
```
...but 6 arguments is getting cumbersome.  The other option is to pass them in via env vars, though those are easier to typo.
<details> …

hooks: Refactor, add a Zulip notification, and a post-deploy git push hook.

---

web/src/hotkey.js
web/src/muted_topics_ui.js
web/src/popover_menus.js
web/src/popover_menus_data.js
web/src/popovers.js
web/src/starred_messages.js
web/src/stream_popover.js
web/src/topic_list.js
web/styles/dark_theme.css
web/templates/topic_sidebar_actions.hbs
web/tests/hotkey.test.js
web/tests/starred_messages.test.js

------------------------
Fixes: #23891
--------------------------
<details>
<summary> Topic Sidebar popover: </summary>
<br>
</details>
<details>
<summary> Demo: </summary>
<br>
</details>
---------------------------
<details>
</details>

Port topic sidebar menu popover to tippy

---

web/src/portico/header.ts

This PR addresses the migration of file `web/src/portico/header.js` to typescript.
`labelID` is of type `string|undefined`. `undefined` should not be used inside template literals as it's not the intended behaviour. So, fixed it using an `if block`:-
```ts
if(labelID){
$(`#${labelID}`).trigger("click");
}
```
Fixes: 
<details>
</details>

ts: Migrate header.js to typescript.

---

requirements/common.in
requirements/dev.txt
requirements/prod.txt
version.py
zerver/lib/db.py
zerver/lib/user_groups.py
zproject/computed_settings.py
zproject/test_extra_settings.py

[Django 4.2 release notes](https://docs.djangoproject.com/en/4.2/releases/4.2/)

requirements: Upgrade Django to 4.2

---

web/styles/zulip.css

The dropdown icon for direct messages is partially visible on small screens. This was due to removing padding when the screen size is below a certain size by media query.
This PR adds only the padding-left for left-sidebar so that the dropdown is clearly visible.
Before:
After:
<details>
</details>

style: Fix dropdown icon partially visible on small screens.

---

zerver/openapi/curl_param_value_generators.py
zerver/tests/test_user_groups.py
zerver/views/user_groups.py

Fixes: #23642
Notification message sent when `Desdemona` removes and adds a user to user group `hamletcharacters`
<details>
</details>

user_groups:Sends a notification message to users when someone else add them to user group.

---

web/src/stream_settings_ui.js
web/styles/subscriptions.css
web/templates/stream_settings/stream_settings_overlay.hbs
web/tests/stream_events.test.js
web/tests/stream_settings_ui.test.js

Fixes: #21870 
<details>
<summary>Subscribed</summary>
</details>
<details>
<summary>All Streams</summary>
</details>

Frontend: Add a message and button when there are no streams to show.

---

web/src/filter.js
web/tests/filter.test.js

Updates `Filter.describe_is_operator` to use switch/case instead of if/else and adds case for "is:resolved" narrow so that it is not shown as invalid when used with other search narrow filters.
---
<details>
<summary>Current is:resolved with additional input</summary>
</details>
<details>
<summary>After changes</summary>
</details>
---
<details>
</details>

narrow-filter: Update `Filter.describe_is_operator` for "resolved".

---

web/src/dropdown_list_widget.js

- First commit is just to rename and existing function.
- Second commit is the main commit to select first option on pressing "Enter" in search input.
- Third commit is again a refactoring commit.
Fixes: #25024
<details>
</details>

dropdown_list_widget: Select first option on pressing "Enter" in search input.

---

web/src/hotkey.js

Fixes:  #24417
Added functionality to toggle the gear_menu with the ```g``` hotkey press.
Toggle the gear_menu with ```g``` hotkey :
<details>
</details>

hotkey: Toggle gear_menu on clicking `g` hotkey.

---

web/styles/popovers.css

Discussion - [CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Clicking.20outside.20profile.20overlay)
When a user opens a profile modal, the overlay is clicked through in responsive mode, which results in unintended button/link clicks. This pull request removes the causing CSS property `pointer-events:none;` which was passing pointer-events to other elements.
***Before***
https://user-images.githubusercontent.com/71015892/227767979-dd3cfb93-35bd-4491-865e-c56948d5fb0a.mov
***After***
https://user-images.githubusercontent.com/71015892/227767943-c1fa8fdb-990b-45fe-a0c7-37a7e7b096f6.mov
<details> …

user-profile: Prevent unintended clicks through profile modal overlay.

---

web/src/top_left_corner.js
web/src/unread_ui.js

This PR breaks the cyclic dependency between `top_left_corner.js` and `unread_ui.js`.
It achieves this by shifting the `animate_mention_changes` function from `unread_ui.js` to `top_left_corner.js`, which was the only function required from `unread_ui.js` and was independent of other functions as well.
[CZO Link](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1543137)
<details>
</details>

js: Break cyclic dependency between top_left_corner and unread_ui.

---

web/src/invite.js
web/templates/invite_user_modal.hbs

Removes undefined `time_input` from  `invite_users_modal.hbs`. The default input value for the expiration custom time limit is not set until the "custom" option is selected from the dropdown.
Removes the undefined `csrf_input` from the same template. And imports `csrf.ts` into `invite.js` to get the csrf token and add it to the request data, which is the current pattern used in other `/web/src` modules.
See relevant CZO conversations in [issues](https://chat.zulip.org/#narrow/stream/9-issues/topic/issue.20in.20opening.20invite.20modal/near/1543589) and [frontend](https://chat.zulip.org/#narrow/stream/6-frontend/topic/handlebars.20undefined.20variables/near/1529727) streams.
---
<details>
Communicate …

templates: Update `invite_users_modal.hbs` for undefined variables.

---

web/src/narrow.js

When there are no operators to narrow down
the search to, pass into `deactivate()` if
we're in `recent conversations`.
If we are, it will go to `all messages`.
This is done by using `is_visible()`
function of `recent_topics_util`.
<details>
</details>

search: Fix selecting all messages from recent conversations.

---

web/src/flatpickr.js

get_keydown_hotkey in hotkey.js doesn't always return a value. By adding a check to ensure that 'hotkey' is defined (in flatpickr.js), the code no longer throws errors if an unsupported key or key combination is pressed.  This also allows us to eliminate the existing check for the keypress of a number, because it is now handled just like any other key that results in an undefined value.
Fixes #24773
Fixes: 
<details>
- [x ] Explains differences from previous plans (e.g., issue description).
- [ x] Highlights technical choices and bugs encountered. …

time_picker: Add check for undefined 'hotkey' to fix type errors.

---

web/src/settings_emoji.js
web/templates/settings/bot_settings_tip.hbs
web/templates/settings/emoji_settings_admin.hbs
web/templates/settings/emoji_settings_tip.hbs
web/templates/settings/user_groups_admin.hbs

Fixes: #24157
Banners for Custom emoji permissions.
Banners for User groups permission
Banners for adding bot permission.
<details>
</details>

settings: Improve permissions notice banners.

---

web/src/tippyjs.js

tippyjs: Only destroy tippy popups if they exist at all.

---

web/tests/topic_list_data.test.js

With commit f0d1332ba2f4, we no longer need to mock `topic_list.js` in the `topic_list_data` node test.
Instead, we can pass a string directly to that function. The default is an empty string unless there is search input. Also, updates the default zoom to be `false` instead of `undefined` in the tests.
**Test output before changes**:
```console
$ tools/test-js-with-node topic_list_data
Starting node tests...
running test topic_list_data
test: get_list_info w/real stream_topic_history
test: get_list_info unreads
You asked to mock /srv/zulip/web/src/topic_list.js but we never saw it during compilation.
Test(s) passed. SUCCESS!
```
---
<details> …

node-tests: Remove mock of `topic_list` in `topic_list_data.test`.

---

puppet/zulip_ops/manifests/prod_app_frontend_once.pp

puppet: Add prod hooks to push zulip-cloud-current and notify CZO.

---

web/src/upload.js
web/templates/compose_banner/upload_banner.hbs
web/templates/message_edit_form.hbs
web/tests/upload.test.js

Just one remaining question noted below and on CZO.
<details>
<summary>Screenclips</summary>
regular upload, plus an error for file size
editing a message
compose box full height
https://user-images.githubusercontent.com/5634097/228405116-d54d296b-9bde-4887-b2a0-f3dd8e3cd27b.mp4
multiple errors, and duplicate file error
https://user-images.githubusercontent.com/5634097/229973976-4a880aee-e9dc-4ed8-9fac-017fe41b2c4b.mp4
</details>
<details> …

upload: Separate uploads into one upload bar per file.

---

zproject/jinja2/__init__.py

jinja2: Make sure that 500 pages have support_email set.

---

confirmation/models.py
corporate/models.py
pyproject.toml
tools/semgrep.yml
zerver/models.py

https://beta.ruff.rs/docs/rules/#flake8-django-dj

ruff: Enable Django rules

---

web/src/flatpickr.js

After some discussions in CZO, it was decided that we should reduce the increment of minutes to one because the up/down arrow isn't very helpful at all. Most of the time, users would manual type their desired time and micro adjust with the arrow keys if needed.
This change also solves the issue where the time picker only counts multiples of 5s as valid time as it was tied to the increment of minutes.
<details> …

time_picker: Reduce increment of minutes to one.

---

version.py

e536a14b617e left off the required major PROVISION_VERSION bump.
<details>
</details>

version: Bump PROVISION_VERSION for previous change.

---

zerver/lib/events.py

Changed `one` to `want` so that the sentence make sense.
<details>
</details>

typo: Fix a typo in block comment

---

templates/zerver/app/index.html
web/src/stream_edit.js
web/src/stream_edit_subscribers.js
web/src/stream_settings_ui.js
web/src/stream_ui_updates.js
web/src/user_group_edit.js
web/src/user_group_edit_members.js
web/src/user_groups_settings_ui.js
web/tests/stream_events.test.js
web/tests/stream_settings_ui.test.js

- First commit changes the ID of stream settings overlay container element.
- Second commit changes the ID of group settings overlay container element
https://github.com/zulip/zulip/pull/23670#discussion_r1167344307
<details>
</details>

Change ID of overlay container elements.

---

web/styles/rendered_markdown.css

Following up to #24961, it was discovered that emojis looked worse with the new changes as the spacings became uneven with each emojis. These changes aim to remove exclude emojis from the new changes.
Before: 
After:
<details>
</details>

compose: Prevent removal of margin on Emojis in preview markdown.

---

puppet/zulip/files/hooks/common/zulip_notify.sh
puppet/zulip/files/hooks/post-deploy.d/zulip_notify.hook
puppet/zulip/files/hooks/pre-deploy.d/zulip_notify.hook

Example: https://chat.zulip.org/#narrow/stream/7-test-here/topic/production.20deploy/near/1551212
Starting production deploy of [84 new commits](https://github.com/zulip/zulip/compare/b3a185103d7d948a8741c36deffc7cf105797d27...938b7917d3c62e6ceb216009e665c5075ec66cb1) on alexmv-prod.zulipdev.org
<details>
</details>

hooks: Give a bit better Zulip deploy message.

---

scripts/zulip-puppet-apply

The existing `except subprocess.CalledProcessError` only catches if there are syntax errors which prevent the `lastrun` file from being written; it does not handle if there are properly-defined resources which fail to evaluate (e.g. due to a missing dependency or file).
Check the `failed` resource count, and exit 2 if there are any such resources.  This will cause `zulip-puppet-apply --force --noop` (which is used as a pre-flight check during upgrades) to properly detect and signal on more types of invalid puppet configurations.  In turn, this will cause `upgrade-zulip` to not attempt to power through upgrades it knows are destined to fail.
<details> …

zulip-puppet-apply: Any resources failing to apply should exit 2.

---

web/src/message_events.js

Previously, we didn't notify the starred messages code path when processing the event that a message was deleted, resulting in the displayed counter potentially being stale until the app is reloaded.
Fixes #25190.
Fixes: 
<details>
</details>

events: Fix live update when deleting a starred message.

---

web/src/admin.js
web/src/hashchange.js
web/src/settings.js
web/tests/hashchange.test.js

There was a direct dependency between `admin.js` and `settings.js` which was due to the fact that we needed to call `build_page` of both modules in each other's `launch` function.
This is solved by lifting those `build_page` calls up from both modules to `hashchange.js` which is the module which calls the `launch` function of both modules.
<details>
</details>

js: Break cyclic dependency between `admin.js` and `settings.js`.

---

.eslintrc.json
web/e2e-tests/delete-message.test.ts
web/e2e-tests/lib/common.ts
web/e2e-tests/user-status.test.ts
web/src/blueslip_stacktrace.ts
web/src/debug.ts
web/src/dialog_widget.ts
web/src/emoji.ts
web/src/fold_dict.ts
web/src/global.d.ts
web/src/group_permission_settings.ts
web/src/keydown_util.ts
web/src/message_parser.ts
web/src/muted_users.ts
web/src/overlays.ts
web/src/portico/header.ts
web/src/portico/tabbed-instructions.ts
web/src/portico/team.ts
web/src/sentry.ts
web/src/settings_config.ts
web/src/spoilers.ts
web/src/types/stacktrace-gps/index.d.ts
web/src/typing_data.ts
web/src/url-template.d.ts
web/src/util.ts
web/webpack.config.ts

https://typescript-eslint.io/linting/configs/#strict

eslint: Enable @typescript-eslint/strict configuration

---

help/disable-welcome-emails.md

Drop unnecessary details about number and content of welcome emails, which were no longer accurate.
Current page: https://zulip.com/help/disable-welcome-emails
Updated:

help: Update "Disable welcome emails" help page.

---

docs/_templates/layout.html

Updates the warning banner displayed on some of the **development version** documentation pages to be more explicit. See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/9-issues/topic/incorrect.20development.20version.20warning/near/1529335).
<details>
</details>

docs: Update development version warning text to be more explicit.

---

web/src/narrow_banner.js
web/tests/narrow.test.js

Updates the empty narrow banner when there are no starred messages for a more general use case. Previously, it indicated that the user hadn't starred anything yet, which could be confusing for an experienced user who had just cleared out their starred messages.
See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/137-feedback/topic/starred.20anything.20yet/near/1550511).
<details>
</details>

empty-narrow: Update banner for no starred messages.

---

templates/zerver/emails/confirm_registration.txt
templates/zerver/emails/followup_day1.txt
templates/zerver/emails/invitation.txt
templates/zerver/emails/onboarding_zulip_guide.html
templates/zerver/emails/onboarding_zulip_guide.txt
templates/zerver/emails/realm_reactivation.txt

This is a continuation of https://github.com/zulip/zulip/issues/24260 where we have redrafted the "contact us"
line in various emails, but the plain-text versions of those emails remains
untouched. We want to also update those versions and ensure that they match
with our emails.
Fixes: https://github.com/zulip/zulip/issues/25198
<details>
<summary>Confirm Registration</summary>
```
You recently signed up for Zulip. Awesome!
Click the button below to complete registration.
<http://localhost:9991/accounts/do_confirm/uvmzizvovqs5w74vvvhr4si6>
If you have any questions, please contact this Zulip server's administrators at desdemona+admin@zulip.com.
```
</details>
<details>
<summary>Follow up day 1</summary>
```
Welcome to Zulip!
You've joined the Zulip …
```

emails: Fix "contact us" line in plain-text versions of emails. 

---

templates/corporate/development-community.md

There was a typo in the **Streams for code contributors section** of the Development Community page. 
Fixes: 
<details>
</details>

Fix typo in "Streams for code contributors section"

---

help/start-a-call.md
web/src/compose.js
web/tests/compose_video.test.js

Earlier it was "Click here to join video call".
Fixes: https://github.com/zulip/zulip/pull/25002#discussion_r1163143096
<details>
</details>

compose: Change video call url text to "Join video call."

---

templates/zerver/emails/confirm_registration.txt

Previously, the email had a line that says "Click the button below". This sounds weird as the plain text emails don't have buttons and only had links. We should change "Click the button below" to "Click the link below" which makes more sense.
<details>
</details>

emails: Update phrasing in `confirm_registration.txt`.

---

web/src/narrow.js

Previously, when a user marks messages as unread in the all messages view then enters another view and finally back to the all messages view, they'll notice that the reading state in all messages view is still paused. This change will explicitly resume the reading state when we enter all messages view/message_lists.
<details>
</details>

narrow: Explicitly resume the reading state when `narrow.deactivate`.

---

templates/zerver/emails/followup_day2.html
templates/zerver/emails/followup_day2.txt
templates/zerver/emails/onboarding_zulip_guide.html
templates/zerver/emails/onboarding_zulip_guide.txt

Updates:
- Changes the call to action at the end of `followup_day2` from "It's time to chat." to "Go to Zulip."
- Revises the text before the link/button in the `onboarding_zulip_guide` email.
<details>
<summary>Follow-up day 2 email</summary>
</details>
<details>
<summary>Onboarding Zulip guide email</summary>
</details>
---
<details>
</details>

welcome-emails: Small revisions to followup_day2 and onboarding_zulip_guide emails.

---

web/src/message_list.js
web/src/message_list_view.js
web/src/stream_settings_ui.js
web/styles/zulip.css
web/templates/bookend.hbs

bookend: Add stream icons to subscribed/unsubscribed divider line.

---

web/templates/recipient_row.hbs

Discussion: https://github.com/zulip/zulip/pull/25212#issuecomment-1520639015
Corrected the hotkey info in mute topic icon tooltip in message header to be `Shift + M`(which is the correct keyboard shortcut) instead of only `M`.
Fixes: 
**Before:**
**After:**
<details>
</details>

recipient_row: Correct hotkey for mute icon tooltip.

---

help/marking-messages-as-read.md

As a follow up to #24309, we want to add a new tab with desktop/web instructions to the "Configure whether messages are automatically marked as read" section. The paragraph has also been tweaked to accommodate the new feature.
New: 
<details>
</details>

help: Add instructions for `do not mark messages as read`.

---

web/styles/input_pill.css

Fixes: #21807.
This PR fixes the text overflow bug for pill values by adding a maximum width of 100% for the pill along with the ellipsis property on text overflow.
<details>
<summary>Manage user UI</summary>
Large width screen - 
Small width screen - 
</details>
<details>
<summary>Personal settings UI</summary>
Large width screen - 
Small width screen - 
</details>
<details>
</details>

css: Fix text overflow bug for pill values.

---

web/src/todo_widget.js

Fixes: #25064
https://user-images.githubusercontent.com/72064462/233706309-27923ade-c034-4ea4-b460-6f031d53391c.mov

todo_widget: Fix cursor focus in todo lists.

---

docs/testing/manual-testing.md
help/create-a-stream.md
web/src/server_events_dispatch.js
web/src/stream_create.js
web/src/stream_settings_ui.js
web/src/stream_ui_updates.js
web/templates/stream_settings/announce_stream_checkbox.hbs
web/templates/stream_settings/stream_creation_form.hbs
web/templates/stream_settings/stream_types.hbs

Fixes: #23327
New `help` docs
UI when announce stream is disabled.
UI when announce stream is enabled.
<details>
</details>

streams: Make stream settings and create stream UI more consistent.

---

web/third/bootstrap-typeahead/typeahead.js

Until now, the typeahead was hidden on clicking outside only if the last click was not on the header. This happened because clicking the header would blur the input, and any other click then would not trigger the blur event (which is responsible for hiding the typeahead).
Now we refocus the input after clicking the header, so that clicking elsewhere blurs the input and hides the typeahead.
Fixes: [issue described here](https://chat.zulip.org/#narrow/stream/9-issues/topic/.22Start.20a.20new.20topic.22.20closes.20compose.20box/near/1536064)
A very minor side effect is that we cannot now select the text in the header, but there should not be a need to do that anyway.
https://user-images.githubusercontent.com/68962290/229151512-ca360d3f-875a-4750-8b64-7655e …

typeahead: Hide typeahead on clicking outside after clicking its header.

---

web/src/compose.js
web/src/compose_banner.ts
web/src/compose_ui.js
web/src/reminder.js
web/templates/compose.hbs
web/tests/compose.test.js

- First commit is for refactoring the existing code.
- Second commit adds loading indicator to "Schedule" button.
Fixes:  #25182
<details>
</details>

Add loading indicator to "Schedule" button.

---

templates/zerver/emails/digest.html
templates/zerver/emails/email.css
templates/zerver/emails/email_base_default.html
templates/zerver/emails/email_base_marketing.html
templates/zerver/emails/missed_message.html
templates/zerver/emails/sponsorship_request.html
templates/zerver/emails/support_request.html
zerver/tests/test_email_notifications.py

Related [CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/regression.20in.20email.20styling)

emails: Fix style regression for dynamically generated content.

---

pyproject.toml
requirements/common.in
requirements/dev.txt
requirements/prod.txt
tools/test-backend
version.py
zerver/actions/message_flags.py
zerver/actions/presence.py
zerver/actions/user_activity.py
zerver/decorator.py
zerver/lib/cache.py
zerver/lib/email_notifications.py
zerver/lib/markdown/__init__.py
zerver/lib/push_notifications.py
zerver/lib/queue.py
zerver/lib/rate_limiter.py
zerver/lib/url_preview/preview.py
zerver/lib/utils.py
zerver/middleware.py
zerver/tests/test_report.py
zerver/tornado/event_queue.py
zerver/views/home.py
zerver/views/message_fetch.py
zerver/views/report.py
zproject/computed_settings.py
zproject/default_settings.py

⚠️ **Note:** The major `PROVISION_VERSION` bump will incorrectly clean-merge if this is rebased on #25283, and will need to be manually replaced.
---
https://chat.zulip.org/#narrow/stream/3-backend/topic/statsd

Remove statsd support

---

web/src/dropdown_list_widget.js
web/templates/inline_decorated_stream_name.hbs
web/templates/settings/dropdown_list.hbs
web/tests/settings_org.test.js

This PR adds code to colorize the stream privacy icons in dropdown list widget.
Both the selected option in button and options in the menu are colorized as per the stream color.
Fixes: #25282.
<details>
</details>

dropdown_list_widget: Colorize stream privacy icons.

---

zerver/views/auth.py

Fixes: 
Shifted REQ to top-level functions to allow our OpenAPI documentation test suite to detect the REQ variables and not create an error if added to the documentation. Solves issue #25015
<details>
</details>

Refactored code to push REQ to top level functions

---

api_docs/changelog.md
version.py
zerver/actions/message_send.py
zerver/actions/presence.py
zerver/actions/user_settings.py
zerver/lib/export.py
zerver/lib/import_realm.py
zerver/lib/presence.py
zerver/migrations/0443_userpresence_new_table_schema.py
zerver/migrations/0444_userpresence_fill_data.py
zerver/migrations/0445_drop_userpresenceold.py
zerver/models.py
zerver/openapi/curl_param_value_generators.py
zerver/openapi/zulip.yaml
zerver/tests/test_event_system.py
zerver/tests/test_events.py
zerver/tests/test_import_export.py
zerver/tests/test_message_edit_notifications.py
zerver/tests/test_messages.py
zerver/tests/test_presence.py
zilencer/management/commands/populate_db.py
zproject/default_settings.py

This is a continuation of #15030 - I accidentally closed that PR and GitHub doesn't allow me to reopen.

presence: Rewrite the backend data model.

---

templates/corporate/values.md

portico: Tweak wording on /values.

---

tools/test-js-with-node
web/src/dark_theme.ts

Nothing change essentially. Just renamed the file suffix. However, `dark_theme.ts` depends on `localstoraeg.ts` which has not been fixed and merged into `main`. So once the dependency has been converted, we can continue to finish up or merge `dark_theme.ts` into `main` branch.
<details>
</details>

ts migration: Convert `dark_theme.js` to `dark_theme.ts`

---

web/styles/settings.css

We show the stream privacy icon for the selected option in dropdown list widget even if the widget is disabled.
It is fixed by changing the CSS to hide only the "i" element used for the arrow toggle button and not all the "i" elements in disabled state.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/stream.20privacy.20icon.20not.20shown.20in.20disabled.20field
<details>
</details>

dropdown_list_widget: Show stream icons when widget is disabled.

---

docs/subsystems/email.md
templates/zerver/documentation_main.html
templates/zerver/emails/confirm_new_email.html
templates/zerver/emails/confirm_registration.html
templates/zerver/emails/custom_email_base.pre.html
templates/zerver/emails/deactivate.html
templates/zerver/emails/digest.txt
templates/zerver/emails/email_base_default.html
templates/zerver/emails/email_base_marketing.html
templates/zerver/emails/find_team.html
templates/zerver/emails/followup_day1.html
templates/zerver/emails/followup_day2.html
templates/zerver/emails/invitation.html
templates/zerver/emails/invitation_reminder.html
templates/zerver/emails/notify_change_in_email.html
templates/zerver/emails/notify_new_login.html
templates/zerver/emails/onboarding_zulip_guide.html
templates/zerver/emails/password_reset.html
templates/zerver/emails/realm_auto_downgraded.html
templates/zerver/emails/realm_reactivation.html
templates/zerver/integrations/include/webhook-url-with-bot-email.md
zerver/context_processors.py
zerver/lib/send_email.py
zerver/tests/test_docs.py
zerver/tornado/django_api.py
zerver/tornado/sharding.py
zerver/views/auth.py
zerver/views/documentation.py
zerver/webhooks/stripe/doc.md
zproject/email_backends.py

In #23380 we want to change all occurences of uri with url in order to follow the URL standard. Previous PRs #25038, #25045 and #25141 changed most occurences of `uri` with `url`. This PR focuses on replacing the remaining miscellaneous occurrences, such as html templates, constants, comments, documentation. Occurrences that affect api endpoints remain unchanged.
<details>
</details>

miscellaneous: Replace all ocurrences of `uri` with `url`

---

web/src/info_overlay.js

Before there was a bug which was responsible for not focusing the correct tab when we opened info overlay. This was simply due to incorrect order of things we were doing, we first was setting up toggler and then opened overlay. Due to this when we triggered focus event on an element when setting up toggler it was getting ignored since overlay was hidden.
Fixed this behaviour by reordering the execution of things, now we first open the overlay to make sure that the content is available to be focused when setting up the toggler.
Discussion - [CZO](https://chat.zulip.org/#narrow/stream/137-feedback/topic/keyboard.20help)
<details>
Individual …

info_overlay: Fix a bug related to incorrect order of function calls.

---

templates/zerver/accounts_send_confirm.html
zerver/models.py
zerver/tests/test_management_commands.py
zerver/tests/test_signup.py
zerver/views/realm.py
zerver/views/registration.py

Previously clicking on "Resend" link was not working correctly and it again took to empty realm details form. This PR fixes it to resend the email again.
- First two commits are prep commits.
- Last commit is to fix the behavior for "resend" link. 
Fixes: #25249
<details>
</details>

Fix "resend" link behavior during realm creation.

---

docs/development/setup-advanced.md

This PR reorganizes and attempts to provide clarity on direct installation setups. Specifically, python3 issues that are largely of concern only to CentOS, Fedora, and RHEL users have been separated into running copy and a new example terminal session that is separate from the provisioning and `tools/run-dev` commands.
To help users better work through the section, the warning about uninstallation appears the top of the section, and also provides a link to the recommended setup instructions that rely on Vagrant.
For posterity, see the brief discussion on [CZO](https://chat.zulip.org/#narrow/stream/19-documentation/topic/advanced.20setup.20clarification).
<details> …

docs: Direct-install clarification

---

zerver/actions/message_edit.py

Also includes a couple commits to improve readability.

Fix quadratic Python work when moving messages between streams.

---

web/styles/left_sidebar.css

This fixes the bug where the schedule message whole row was not clickable and had some padding issues. By adding the same styles as all other rows in the left sidebar we eliminate those bugs.
| ![Screenshot 2023-04-28 143730](https://user-images.githubusercontent.com/84276404/235106137-1c9b7303-1ff9-4d53-ac5b-7fd98fded4b3.png) | ![Screenshot 2023-04-28 143625](https://user-images.githubusercontent.com/84276404/235106262-a3be9cf6-bfb6-4cbb-be22-2d7cd9daa6d4.png) | 
<details> …

left_sidebar: Add same styles to schedule messages row as all other rows in left sidebar.

---

web/src/invite.js
web/src/recent_topics_ui.js
web/src/timerender.ts
web/src/tippyjs.js
web/tests/recent_topics.test.js
web/tests/timerender.test.js

Separating these concepts allows us to provide a much nicer format for contexts where ultra-specific clarification is not a priority.
This new variant is currently only used in the scheduled messages UI.
Fixes: 
<details>
</details>

timerender: Extract new variant of get_full_datetime.

---

.gitlint
docs/contributing/commit-discipline.md

This PR changes the recommended commit summary length to 72 characters in both the documentation as well as in `gitlint`.
<details>
<summary> Commit summary, part 2 </summary>
[Link to the page](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html#commit-summary-part-2)
</details>
<hr>
<details>
</details>

docs: Update recommended commit summary length to 72 characters.

---

web/shared/src/resolved_topic.ts

This PR converts `shared/src/resolved_topic.js` to TypeScript.
<details>
</details>

ts: Convert resolved_topic.js to TypeScript.

---

docs/production/requirements.md
docs/production/security-model.md
docs/subsystems/performance.md
docs/tutorials/life-of-a-request.md

Update a couple out-of-date production documentation pieces

---

web/styles/zulip.css

This PR adds the `margin-top` property to sender info to make sure that it doesn't overlap with the edit compose area.
CZO [Link](https://chat.zulip.org/#narrow/stream/9-issues/topic/status.20message.20edit.20bug)
<hr/>
|![image](https://user-images.githubusercontent.com/35286603/235522828-b4509d97-e247-4b7d-bdbf-1f311dcb3732.png)|![image](https://user-images.githubusercontent.com/35286603/235522781-4f82b080-313f-4035-b77b-fe3fb04fe966.png)|
<hr>
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributin …

status-message: Add margin-top to sender info to avoid overlap.

---

docs/overview/architecture-overview.md
docs/tutorials/new-feature-tutorial.md

This PR introduces a handful of minor docs fixes that I noticed while reading today.
<details>
</details>

docs: Minor surface fixes.

---

web/templates/stream_settings/stream_settings.hbs

Fixes the issues discussed in https://chat.zulip.org/#narrow/stream/9-issues/topic/extraneous.20tooltip.20in.20stream.20settings/near/1559142.

Fix minor issues with stream settings tooltips

---

web/src/typeahead_helper.js
web/tests/composebox_typeahead.test.js

As discussed in the comment, this resulted in the many inactive users in chat.zulip.org with "Tim" as their full display name from being incorrectly prioritized over me in a stream where I've been active; and this class of problem seems like it will be common in large open communities.
This reverts a portion of 4dc1b2f81273b17ea4d6e422c49782dfb0fa7324, with explanatory comments for why this behavior is preferred.
The stream name changes in the original PR remain very helpful.
Fixes: 
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing …

typeahead: Do not prioritize exact name matches for users.

---

web/styles/left_sidebar.css

Fixes: 
#25359
Before:
After:
<details>
</details>

left_sidebar: Drop underlined behaviour on focus for <a> elements.

---

web/src/util.ts
web/templates/right_sidebar.hbs

util: Speed up clean_user_content_links by persisting an inert document

---

web/src/popover_menus.js
web/src/scheduled_messages.js
web/src/server_events_dispatch.js
web/src/ui_init.js
web/styles/compose.css
web/styles/dark_theme.css
web/templates/compose_banner/success_message_scheduled_banner.hbs

[![Image from Gyazo](https://i.gyazo.com/456156201352dcc27108a3d0bf794af8.gif)](https://gyazo.com/456156201352dcc27108a3d0bf794af8)

send_later_modal: Disable interaction with modal when flatpickr is open.

---

web/src/scheduled_messages.js

Previously, if one had started working on a message from a draft, and then schedules it to be sent later, the draft would not be cleared when the server accepts the request to schedule the message.
Fixes: 
<details>
</details>

send_later: Fix leaking drafts for scheduled messages.

---

zerver/openapi/zulip.yaml

Updates the topic parameter in `/create-or-edit-scheduled-message` endpoint to match the topic parameter for `/send-message` endpoint, except that it doesn't have the **Changes** note from Zulip 2.0 about the change from subject to topic.
Also fixes a missing period in the `/send-message` topic parameter description.
---
**Send message:**
---
**Create or edit scheduled message**:
--- 
<details>
</details>

api-docs: Clarify topic parameter for create-or-edit-scheduled-message.

---

help/hide-message-content-in-emails.md
web/templates/settings/organization_settings_admin.hbs

- First commit is to just move all the settings inside `organization-settings-parent` div without any visual changes.
- Second commit is to reorder settings.
- Third commit is to move "Allow message content in message notification emails" setting.
Fixes:  #25339
<details>
</details>

Reorganize SETTINGS > ORGANIZATION SETTINGS > Automated messages and emails.

---

web/src/top_left_corner.js
web/src/unread_ui.js
web/tests/top_left_corner.test.js

Apparently some past refactor caused the animation for new mentions to be triggered when initialization the app.
(This seems pretty clearly unintentional: A user loading the app doesn't need their attention specifically drawn to the @-mentions view in the same way that a user who is using the app and receives a mention right now does.)
Fixes: 
<details>
</details>

top_left_corner: Fix new mention animation when loading app.

---

web/templates/unread_banner/mark_as_read_disabled_banner.hbs
web/templates/unread_banner/mark_as_read_only_in_conversation_view.hbs

https://chat.zulip.org/#narrow/stream/101-design/topic/unread.20banners/near/1559353

unread_banner: Fix awkward phrasing and split infinitive

---

web/src/scheduled_messages.js

Fixes #25401
This affects both "Undo" in compose banner and "Edit" in scheduled messages overlay.

scheduled_messages: Don't narrow to recipient when starting an edit.

---

scripts/log-search

log-search: Filter out /error_tracing endpoints.

---

web/src/message_edit.js
web/src/message_events.js
web/src/message_fetch.js

- First commit will be removed after #25387 will be merged.
- Second commit is to update the message data and view if the message is not locally available with client.
- Third commit is to return "first_unread" as anchor when there are no messages in the list.
- Last commit is to move all messages when editing topic using message header.
<details>
</details>

Edit full topic when renaming topic from message header bar.

---

web/templates/settings/emoji_settings_admin.hbs

Fixes: #24918
`Normal user`
`Owner' profile`

template: Hide "Add a new emoji" button for unauthorized users.

---

web/src/scheduled_messages.js
web/tests/scheduled_messages.test.js

This corrects the scheduled message test to ensure that each relative day (today, tomorrow) has the correct GMT timestamp for 9am and 4pm.
This set of tests needs to be improved further, along the lines of [this comment](https://github.com/zulip/zulip/pull/25427#discussion_r1185402569), but this commit should restore to a passing state.
<details>
</details>

scheduled_messages: Prepare proper sending timestamps in Node test.

---

.mailmap

This PR consolidates the two email addresses I've committed under (future commits will of course use my `@zulip.com` address).

mailmap: Add entry for Karl Stolley.

---

.mailmap

This PR combines commits from me(Hardik Dharmani) from 2 versions of my email(different capitalization).
Fixes: 
<details>
</details>

mailmap: Add entry for Hardik Dharmani.

---

zerver/lib/export.py
zerver/lib/import_realm.py
zerver/tests/test_import_export.py

Closes #25130 by addressing the import/export part of it.
Added some automated test code plus verified manually in dev env by export->import and verifying in database and UI.

scheduled_message: Make export/import work.

---

.mailmap

This PR combines my commits from two different email addresses.
<details>
</details>

mailmap: Add entry for Ujjawal Modi.

---

.mailmap

mailmap: Add entry for Joseph Ho.

---

.mailmap

mailmap: Add entry for Satyam Bansal.

---

.mailmap

This PR combines my commits from two different versions of my email address and fixes the issue of my name being associated differently with the same email.
<details>
</details>

mailmap: Add entry for Palash Baderia

---

templates/zerver/app/index.html
web/styles/compose.css
web/styles/dark_theme.css
web/styles/input_pill.css
web/styles/left_sidebar.css
web/styles/recent_topics.css
web/styles/right_sidebar.css
web/styles/zulip.css
web/templates/navbar.hbs

Fixes: #21750
in comments below

UI redesign: Change background color.

---

web/styles/zulip.css

https://user-images.githubusercontent.com/110852085/235502181-1e5c41d0-d9b2-4513-9f3e-b2e72e2f19f4.mp4
`Version` and `Forked from` copy buttons now will change color to blue when hovered over. This allows the copy button to pop out more when hovering over it. Fixes part of #23210.
Fixes: 
<details>
</details>

about_zulip: Change icon to blue color when copy button is hovered.

---

api_docs/changelog.md
version.py
web/src/invite.js
web/templates/invite_user_modal.hbs
zerver/actions/create_user.py
zerver/tests/test_invite.py
zerver/views/invite.py

We now allow users to invite without specifying any stream to join.
In such cases, the user would join the default streams, if any, during
the process of account creation after accepting the invite.
It is also fine if there are no default streams and user isn't subscribed to any stream initially.
<details>
</details>

invites: Allow users to invite without specifying any stream to join.

---

templates/zerver/app/index.html

#23724 was not correctly rebased onto #25504.

app: Fix automatic-scheme loading color for rebased background change

---

help/include/how-to-start-a-new-topic.md
help/include/send-group-dm.md
help/mastering-the-compose-box.md
help/quote-and-reply.md
help/replying-to-messages.md
zerver/lib/markdown/tabbed_sections.py

Note: I decided not to add a tip about switching the compose destination on a couple of pages that could potentially have it, as it seemed like too much complexity given the context.
- https://zulip.com/help/replying-to-messages
- https://zulip.com/help/start-a-new-topic
<details>
<summary>
/help/mastering-the-compose-box
</summary>
Current: https://zulip.com/help/mastering-the-compose-box
</details>
<details>
<summary>
/help/starting-a-new-topic
</summary>
Current: https://zulip.com/help/starting-a-new-topic
</details>
<details>
<summary>
/help/starting-a-new-private-thread
</summary>
Current: https://zulip.com/help/starting-a-new-private-thread
</details>
<details>
<summary>
/help/quote-and-reply
</summary>
Current: https://zulip.com/help/quote-and-reply
</details>

help: Document compose box stream dropdown.

---

web/src/dropdown_widget.js
web/styles/compose.css
web/styles/zulip.css
web/templates/dropdown_list.hbs
web/templates/dropdown_list_container.hbs

discussion https://chat.zulip.org/#narrow/stream/101-design/topic/stream.20dropdown.20changes.20.2325446

Dropdown widget misc fixes.

---

web/third/bootstrap/css/bootstrap-btn.css

Currently, we are in the process of removing bootstrap out of the current Zulip codebase. A quick git grep on btn-info shows that the class is only used in `templates/corporate/billing.html` and a couple unread banners in `web/templates/unread_banner`. But it doesn't take advantage or use most of the styling rules that are set.
We should get rid of those rules as it's not being used and help simplify the process in removing bootstrap.
<details> …

bootstrap: Remove unused stylings for `btn-info`.

---

zerver/lib/events.py
zerver/tests/test_events.py

We were missing a few checks for raw_unread_msgs being present before trying to parse and update it.
The test only covers 2/3 of the cases, but I wasn't convinced it was worth adding another test just for the corner case of removing a message flag; this seems fairly unlikely to regress.
Fixes: 
<details>
</details>

events: Fix apply_events when raw_unread_msgs not present.

---

web/src/popovers.js

In ab0c5f3092e75857ba85195ce948c504174816a3, it was missed that this code depended on the sender_info_hover CSS class, which is no longer an empty element on messages without a message sender avatar/name element.
The logic is still hacky, as it relies on the position of an invisible element, but we're rewriting the positioning logic using Tippy anyway, so it's not worth doing much to make it nicer.
Fixes #25496.
Fixes: 
<details> …

popovers: Fix 'u' keyboard shortcut on messages without avatars.

---

help/include/mute-unmute-intro.md

help: Fix typo in mute-unmute-intro.md.

---

zerver/webhooks/front/fixtures/gmail.json
zerver/webhooks/front/fixtures/rule.json
zerver/webhooks/front/tests.py
zerver/webhooks/front/view.py

webhooks: Add support for gmail and rules sources to Front integration.

---

zerver/webhooks/harbor/fixtures/scanning_completed_no_tag.json
zerver/webhooks/harbor/tests.py
zerver/webhooks/harbor/view.py

integrations: Support scans of untagged images in Harbor.

---

docs/production/export-and-import.md

docs: Update documentation on compliance exports.

---

zerver/lib/validator.py
zerver/webhooks/radarr/fixtures/radarr_application_update.json
zerver/webhooks/radarr/fixtures/radarr_movie_added.json
zerver/webhooks/radarr/fixtures/radarr_movie_deleted.json
zerver/webhooks/radarr/fixtures/radarr_movie_file_deleted.json
zerver/webhooks/radarr/tests.py
zerver/webhooks/radarr/view.py

Add more supported Radarr event types

---

tools/test-backend
zerver/actions/create_realm.py
zerver/actions/message_edit.py
zerver/tests/test_message_edit.py
zerver/tests/test_realm.py

- First commit is to remove unused code.
- Second commit adds coverage to `actions/create_realm.py`.
- Third commit adds coverage to `actions/message_edit.py`.
- Fourth commit is to add "nocoverage" comment from unreachable code.
<details>
</details>

Add test coverage to `actions/create_realm.py` and `actions/message_edit.py` files.

---

puppet/zulip/manifests/common.pp

puppet: Fix checksum of sentry-cli binary.

---

web/src/bundles/app.ts

https://github.com/flatpickr/flatpickr/issues/2468 was fixed in flatpickr@4.6.10.

app: Use ES module from flatpickr

---

zerver/views/upload.py

The code for this was merged in Django 4.2:
https://code.djangoproject.com/ticket/34194
<details>
</details>

upload: Use content_disposition_header from Django 4.2.

---

docs/production/deployment.md
puppet/zulip/lib/puppet/parser/functions/zulipconf.rb
puppet/zulip/manifests/app_frontend_base.pp
puppet/zulip/templates/uwsgi.ini.template.erb
scripts/lib/zulip_tools.py
scripts/restart-server

Re-add `rolling_restart`, make it a bool

---

templates/corporate/attribution.html
templates/corporate/jobs.html
templates/corporate/team.html
templates/corporate/zephyr.html
web/styles/portico/landing_page.css

This PR ensure that all elements targeted by URL fragments will remain visible below the portico's menu bar at all viewport sizes and also when a user zooms in.
The PR also includes adjustments to the shared structure across similar portico landing pages by introducing an `inner-content` div on the few pages missing one, and it also orrects some incidental missing heading IDs.
Thanks to @andersk for suggesting the use of `scroll-margin-top`.
Before:
With this PR:
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.ht …

portico: Keep targeted elements below menu bar.

---

templates/corporate/features.html

Add:
- Scheduled messages (new feature)
- Mute stream or topic
- Compliance exports (as part of "data exports")
- Help center
Links were manually tested.
Feedback on wording and any additions/subtractions is welcome.

portico: Add features to /features.

---

web/src/channel.js
web/src/sentry.ts
web/tests/channel.test.js

Sample uninteresting Sentry spans

---

static/js/invite.js
static/templates/invite_subscription.hbs
templates/zerver/api/changelog.md
version.py
zerver/actions/create_user.py
zerver/tests/test_signup.py
zerver/views/invite.py

Copy of #25455 for 6.x
I have not included the typo commit in this PR.
<details>
</details>

invites: Allow users to invite without specifying any stream to join in 6.x.

---

zerver/lib/push_notifications.py
zerver/tests/test_push_notifications.py
zilencer/views.py

Backport of https://github.com/zulip/zulip/pull/25053/files.

Backport duplicate push registration bug fix

---

tools/test-js-with-node
web/src/all_messages_data.js
web/src/fetch_status.js
web/src/message_feed_loading.ts
web/src/message_fetch.js
web/src/message_list_data.js
web/src/message_scroll.js
web/src/narrow.js
web/tests/fetch_status.test.js
web/tests/message_fetch.test.js
web/tests/message_list.test.js
web/tests/message_list_data.test.js
web/tests/narrow_activate.test.js

This PR contains two commits:
1) Lifts up the formation of the `Filter` object from `message_list_data` to `all_messages_data` by removing the default parameter.
2) Extracts `message_scroll_loading` from `message_scroll` to remove dependency on `message_scroll` from `fetch_status` which allows us to easily convert `fetch_status` into typescript.
<details>
</details>

Break dependencies between message_scroll and fetch_status.

---

web/templates/scheduled_message_stream_pm_common.hbs

discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/scheduled.20message.20error.20handling

scheduled_message: Change tooltip of failure icon.

---

docs/overview/release-lifecycle.md
docs/production/export-and-import.md

Fixes: #25482
<details>
</details>

Document zulip-cloud-current branch

---

requirements/common.in
requirements/dev.txt
requirements/prod.txt
version.py

https://chat.zulip.org/#narrow/stream/9-issues/topic/TypeScript.20highlighting.20bug/near/1568937

Fix jsx-lexer to avoid breaking Pygments TypeScriptLexer

---

help/quote-and-reply.md
web/templates/actions_popover_content.hbs
web/tests/i18n.test.js

This removes the previous "or forward" text from the message actions popover, and keeps the documentation in sync with the new text. Internationalization tests are updated, too.
Fixes #25603.
Popover with the shorter item:
Updated documentation, including "Quote and reply" menu and keyboard shortcuts (cf. [current documentation](https://zulip.com/help/quote-and-reply)):
<details>
- [] Highlights technical choices and bugs encountered.
- [] Calls out remaining decisions and concerns. …

popovers: Shorten 'Quote or reply' label.

---

templates/zerver/accounts_accept_terms.html
templates/zerver/change_email_address_visibility_modal.html
templates/zerver/new_user_email_address_visibility.html
templates/zerver/register.html
web/styles/portico/portico.css
web/styles/portico/portico_signin.css
zerver/actions/user_settings.py
zerver/forms.py
zerver/lib/import_realm.py
zerver/lib/scim.py
zerver/management/commands/create_realm.py
zerver/management/commands/create_user.py
zerver/management/commands/send_custom_email.py
zerver/models.py
zerver/tests/test_home.py
zerver/tests/test_users.py
zerver/views/home.py
zerver/views/users.py
zproject/backends.py

- First two commits are prep commits to extract html code into new template files.
- Third commit is to update the heading and button of terms of service page.
- Fourth commit is to set `tos_version` to "-1" when creating users.
- Fifth commit is to show option to change email visibility on terms of service page.
Fixes:  #25720.
<details>
</details>

Prompt user to set email visibility during first login.

---

zerver/data_import/rocketchat.py

Fixes: #25596.
<details>
</details>

rocketchat: Handle users with no email address set.

---

zerver/middleware.py

If a host is in REALM_HOSTS, it has its own domain name.  Redirect access from other domain names to that name.
<details>
</details>

middleware: Redirect non-canonical realm domain names.

---

zerver/openapi/zulip.yaml

In commit 38f6807af1a, we updated the `POST /scheduled_messages` endpoint to only accept user IDs for direct messages. The endpoint alread only accepted a stream ID for stream messages.
But the API documentation was not updated for the errors returned when either a stream or user with the specified ID does not exist.
Updates the API documentation for the correct error responses.
---
<details>
<summary>Create or edit scheduled message: error responses for unknown stream or user ID</summary>
[Current documentation](https://zulip.com/api/create-or-update-scheduled-message#response)
</details>
---
<details> …

api-docs: Update create/edit scheduled message errors for IDs.

---

api_docs/changelog.md
zerver/openapi/zulip.yaml

Adds **Changes** notes for the API changelog feature level 3 entry about `zulip_version` and `zulip_feature_level`.
Original API changelog note was made in commit 2c63130195ed5b. Part of work on #22102.
---
<details>
<summary>Updated API changelog entry</summary>
[Current documentation](https://zulip.com/api/changelog#changes-in-zulip-30)
</details>
<details>
<summary>Register response: `zulip_version` and `zulip_feature_level`</summary>
[Current documentation](https://zulip.com/api/register-queue#response)
</details>
---
<details> …

api-changelog: Add notes for feature level 3 `zulip_version` change.

---

.github/workflows/production-suite.yml
.github/workflows/zulip-ci.yml
docs/development/setup-advanced.md
docs/development/setup-recommended.md
docs/production/requirements.md
docs/production/upgrade.md
scripts/lib/build-pgroonga
scripts/lib/install
scripts/lib/upgrade-zulip-stage-2
scripts/setup/apt-repos/zulip/bookworm.list
scripts/setup/apt-repos/zulip/custom.sh
tools/ci/build-docker-images
tools/lib/provision.py
tools/setup/postgresql-init-dev-db
zerver/lib/timeout.py
zerver/tests/test_timeout.py

https://chat.zulip.org/#narrow/stream/3-backend/topic/Debian.20bookworm

install: Support Debian 12

---

zerver/lib/push_notifications.py

Deleting a message can race with sending a push notification for it. b47535d8bb67 handled the case where the Message row has gone away -- but in such cases, it is also possible for `access_message` to succeed, but for the save of `user_message.flags` to fail, because the UserMessage row has been deleted by then.
Take a lock on the Message row over the accesses of, and updates to, the relevant UserMessage row.  This guarantees that the message's (non-)existence is consistent across that transaction.
Partial fix for #16502.
<details> …

push_notifications: Lock message while we mark it pending for push.

---

help/status-and-availability.md

- Documents the "User list style" (under Settings > Display settings)
- Adds new section to [/help/status-and-availability#statuses](https://zulip.com/help/status-and-availability#statuses)
Fixes #23492.
<details>
</details>

help: Document "User list style" display setting.

---

zerver/views/sentry.py

The default for Javascript reporting is that Sentry sets the IP address of the user to the IP address that the report was observed to come from[^1].  Since all reports come through the Zulip server, this results in all reports being "from" one IP address, thus undercounting the number of affected unauthenticated users, and making it difficult to correlate Sentry reports with server logs.
Consume the Sentry Envelope format[^2] to inject the submitting client's observed IP address, when possible.  This ensures that Sentry reports contain the same IP address that Zulip's server logs do.
[^1]: https://docs.sentry.io/platforms/python/guides/logging/enriching-events/identify-user/
[^2]: https://develop.sentry.dev/sdk/envelopes/
<details> …

sentry: Add the observed user's IP address before forwarding.

---

web/src/portico/signup.js

This PR fixes a typo in the selector used to
validate registration, support, realm creation,
password reset and terms of service forms. This
typo also resulted in a bug where "This field is
required" error message was shown at incorrect
position and this change fixes it.
This commit also fixes the client side error
handling of these forms which did not work
perfectly due to the selector being wrong.
Fixes: https://github.com/zulip/zulip/pull/25618#issuecomment-1550160063
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-disci …

signup: Fix selector used for validating the forms.

---

api_docs/changelog.md
zerver/openapi/zulip.yaml

Part of 7.0 API changelog audit; see [this CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/7.2E0.20API.20changelog.20audit/near/1572510) for more context.
Updates API changelog entry and related parts of API docs for: **Feature level 176**.
**Notes**:
- Revises API changelog entry for missing endpoint method and to clarify the overall text.
- Generally, updates **Changes** notes for feature level 176 to not have repetitive text, so that the descriptions were clearer and more concise.
- Fixes an alignment issue in the `client_capabilities` parameter description in the `POST /register` doc.
- The original commit with the changes related to this API changelog entry is commit 268f858f39bcd0.
---
<details>
<summary>API …

api-changelog: Update and clarify docs for feature level 176 entry.

---

web/src/people.js
web/tests/people.test.js
web/tests/popovers.test.js

We need to append the `version` parameter when constructing the urls for medium-sized images so that the browser updates the image in real time when the user uploads a new avatar.
Discussion: [CZO](https://chat.zulip.org/#narrow/stream/137-feedback/topic/avatar.20live.20update)
Fixes #25558.
<details>
</details>

people: Add `version` parameter for medium sized avatar urls.

---

templates/zerver/app/index.html

Extracted from #25639, with a minor addition.

Move elements that don't belong in .app.

---

help/schedule-a-message.md

[CZO discussion](https://chat.zulip.org/#narrow/stream/137-feedback/topic/Scheduling.20Messages.20-.20Feedback/near/1566383)
I wrote this so that we wouldn't have to update it when more options are added to the same menu (i.e., when it's no longer dedicated just to message scheduling).
Current page: https://zulip.com/help/schedule-a-message

help: Document keyboard navigation for scheduling a message.

---

docs/subsystems/release-checklist.md

Update release checklist

---

tools/test-js-with-node
web/src/assets.d.ts
web/src/emojisets.ts

Declared types for '*.png' modules and '!style-loader?*' modules in `assets.d.ts` and used them in `emojisets.ts`.
<details>
</details>

ts: Convert `emojisets` module to TypeScript.

---

templates/corporate/jobs.html

portico: Add Senior Flutter Engineer position to `/jobs` page.

---

web/styles/portico/activity.css
web/styles/portico/billing.css
web/styles/portico/portico_signin.css
web/third/bootstrap/css/bootstrap-btn.css
web/third/bootstrap/css/bootstrap.css

- First 10 commits are to remove the bootstrap CSS for unused input types like "button", "datetime", etc.
- Next two commits are to remove bootstrap CSS for elements with class "input-large" and "input-xxlarge".
- Next commit is to remove bootstrap CSS for "submit" type inputs and add them to specific elements.
- Last 3 commits are to remove bootstrap CSS for "number" type inputs and add them to specific elements.
Note that we still have CSS for some of the input types that we do not use in `zulip.css` and probably `dark_theme.css` as well. Wanted to keep this PR for removing bootstrap CSS only so did not include that here.
<details> …

Remove bootstrap CSS for different input elements.

---

web/styles/dark_theme.css
web/styles/modal.css
web/styles/subscriptions.css
web/styles/zulip.css

Reported here: https://chat.zulip.org/#narrow/stream/9-issues/topic/settings.20overlay.20dark.20mode/near/1573482
Fixes #25708.

settings: Fix narrow-screen background color, use color variable.

---

tools/commit-msg

https://chat.zulip.org/#narrow/stream/9-issues/topic/commit-msg.20script/near/1573079

commit-msg: Don’t change the current directory for non-Vagrant

---

web/styles/app_components.css
web/styles/dark_theme.css
web/styles/informational_overlays.css

modals: Fix background color bug from background color changes.

---

web/src/info_overlay.js

<details>
<summary> Adding "---" in message formatting tips </summary>
</details>
<details>
<summary> Removing a line from emoji formatting tip </summary>
| ![Screenshot from 2023-05-25 00-55-30](https://github.com/zulip/zulip/assets/35286603/2dbe287b-1cca-4463-83ca-80016c8c6886) | ![Screenshot from 2023-05-25 00-55-11](https://github.com/zulip/zulip/assets/35286603/dcf14f2f-9ad7-44f1-bfc3-d739cc4a55fd) | 
</details>
<hr/>
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html …

message_formatting: Add a row for "---" in message formatting tips and Remove line from emoji formatting tips.

---

web/src/info_overlay.js

<details>
<summary> Screenshots: </summary>
| ![Screenshot from 2023-05-25 01-47-58](https://github.com/zulip/zulip/assets/35286603/cfc2e874-d8ab-499e-972b-3b06c1c996cd) | ![Screenshot from 2023-05-25 01-56-29](https://github.com/zulip/zulip/assets/35286603/ab093b73-9c76-4c92-9cd3-6cd113e96004)  |
| ![Screenshot from 2023-05-25 09-51-18](https://github.com/zulip/zulip/assets/35286603/efb07ada-98ab-45f2-bd8c-a41e0ec0c27d) | ![Screenshot from 2023-05-25 12-21-30](https://github.com/zulip/zulip/assets/35286603/dcc3de3b-8c5e-4e01-8b59-f26e547d304b)  |
</details>
Fixes #25743.
This should be merged after #25650 to avoid merge conflict.
<hr>
<details>
Communicate …

message_formatting: Reorder items to prioritize more useful ones.

---

api_docs/changelog.md
version.py
zerver/lib/events.py
zerver/models.py
zerver/openapi/zulip.yaml
zerver/tests/test_home.py

This PR removes realm_community_topic_editing_limit_seconds field from register response since topic edit limit is now controlled by move_messages_within_streams_limit_seconds setting. We also remove DEFAULT_COMMUNITY_TOPIC_EDITING_LIMIT_SECONDS constant since it is no longer used.
<details>
</details>

events: Remove realm_community_topic_editing_limit_seconds.

---

templates/corporate/case-studies/end-point-case-study.md

portico: Replace "GChat" with "Google Chat" on case study.

---

web/templates/stream_settings/new_stream_user.hbs

When creating new streams or groups, open up user card when a user's name is clicked on. This behavior now matches other settings tables elsewhere.
Fixes #25725.
<details>
<summary>Opening up user card when creating a stream</summary>
</details>
<details>
<summary>When creating a user group</summary>
</details>
<details>
</details>

settings: Link to user card in new stream/group tables.

---

web/src/tippyjs.js

This commit adds a long hover delay [750,20] to recipient bar icons. Doing this prevents the situation when the tippy tooltips are left floating when the icons suddenly disappear as you enter the topics according to the organization settings and the references are removed. Adding an additional delay ensures that the icons disappear and then the tooltips appear.
---------------------------------------
Fixes: [CZO Thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/tooltip.20present.20when.20reference.20not.20visible)
<details> …

tippy: Add delay for recipient bar icons.

---

web/src/message_list_view.js

discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/new.20message.20top.20of.20feed.20scrolling/near/1579820
This fixes an incorrect comparison introduced in 05f4493f3da1e811553efcf2e2481b684bd6d69d

message_list_view: Fix incorrect comparison. 

---

web/templates/settings/add_new_bot_form.hbs
web/templates/settings/edit_bot_form.hbs

This PR renames "Full name" label to "Name" in bot creation and bot edit modal.
Fixes:  Discussed in https://github.com/zulip/zulip/pull/21427#issuecomment-1109385793
<details>
</details>

settings: Rename "Full name" label to "Name" in bot modals.

---

web/src/linkifiers.ts

This is a follow-up to #23125.
<details>
</details>

linkifier: Remove unused debug message.

---

web/src/compose.js
web/src/message_edit.js
web/src/popover_menus.js
web/src/ui_report.ts
web/styles/alerts.css
zerver/actions/message_edit.py
zerver/tests/test_message_edit.py

- First commit is to show the error.
- Second commit is to fix alignment of "x" button.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/Mark.20as.20resolve.20do.20nothing
<details>
</details>

Show error received by server when resolving topic from sidebar.

---

docs/subsystems/release-checklist.md

https://chat.zulip.org/#narrow/stream/438-release-management/topic/beta.20branches/near/1580566

release-checklist: Purge unneeded beta branch

---

docs/production/deployment.md
docs/subsystems/logging.md

docs: Fix link to sentry deploy hook.

---

docs/production/deployment.md
docs/production/upgrade.md

Update docs for deploy hooks

---

help/import-from-slack.md
zerver/data_import/slack.py
zerver/management/commands/convert_slack_data.py
zerver/tests/test_slack_importer.py

Slack import: Add option to convert threads to Zulip topics.

---

zerver/views/scheduled_messages.py

Updates the `scheduled_message_id parameter` for [deleting scheduled messages](https://zulip.com/api/delete-scheduled-message) to use the `to_non_negative_int` converter function for validation, which is used in other endpoints/views with an ID in the request path.
This is a follow-up that was noted in #25628.
---
<details>
</details>

scheduled-messages: Update scheduled_message_id parameter for DELETE.

---

templates/corporate/apps.html
web/src/portico/landing-page.js
web/styles/portico/landing_page.css

https://apps.microsoft.com/store/detail/XP8HN41S4PLGZ3

landing-page: Add Microsoft Store download link

---

docs/production/authentication-methods.md
docs/production/deployment.md
docs/production/email-gateway.md
docs/production/requirements.md
docs/production/scim.md
docs/production/upgrade.md

Found using [`markdownlint`](https://github.com/DavidAnson/markdownlint).  We should maybe start using it with a subset of its rules.
<details>
</details>

Docs fixes

---

api_docs/changelog.md
docs/overview/changelog.md
version.py

Update version following 7.0 release.

---

version.py

https://chat.zulip.org/#narrow/stream/16-desktop/topic/desktop.20minimum.20versions/near/1581545

version: Increase DESKTOP_MINIMUM_VERSION, DESKTOP_WARNING_VERSION

---

templates/zerver/emails/email.css
templates/zerver/emails/email_base_marketing.html

This pull request adds the functionality to apply custom styles to the content of marketing emails.

emails: Apply different styles to marketing headings.

---

scripts/lib/install

https://chat.zulip.org/#narrow/stream/31-production-help/topic/Problem.20with.20initial.20install.20Debian.20bookworm.20.28sid.29.20and.20node/near/1583257

install: Check CPU and OS architecture

---

zerver/migrations/0443_userpresence_new_table_schema.py

It turns out that for some some deployments, there exists a second foreign key
constraint for user_profile_id. The logic below would try to rename both to the same name,
so we just eliminate one of them to clean things up. This logic could be written more generally to detect duplicate constraints overall,
but so far we expect the issue to only affect this foreign key specifically.
Fixes the migration issue in https://chat.zulip.org/#narrow/stream/31-production-help/topic/.E2.9C.94.20presence.20migration.20upgrading.206.2E2.20to.207.2E0

migrations: Handle duplicate fk constraint in 0443.

---

zerver/tests/test_push_notifications.py
zilencer/views.py

This prepares for the audit log migration (#23116) which requires us to populate a JSONField from the extra_data field. "data" is not representative of the actual extra_data field for RealmAuditLog entries of event types in SYNC_BILLING_EVENTS.
We intentionally leave the test cases unchanged without further verifying if the `extra_data` arrives as-is to keep the change minimal in the first commit.
This is the 1st of a sequence of 4 migration pull requests for migrating `extra_data` to use `JSONField`.
<details> …

zilencer: Prepare for audit log models migration

---

zproject/prod_settings_template.py

This was in docs/production/multiple-organizations.md, but not the settings template.
<details>
</details>

prod_settings_template: Document REALM_HOSTS configuration.

---

help/invite-new-users.md
web/src/invite.js
web/src/tippyjs.js
web/styles/zulip.css
web/templates/invite_user_modal.hbs

This PR is an updated version of [#24729](https://github.com/zulip/zulip/pull/24729) as it address all the changes suggested in review.
Fixes #24692.
<details>
</details>

invite: Restructure "Invite user" modal for improved user experience.

---

pnpm-lock.yaml
version.py

dependencies: Upgrade zxvcbn-ts to restore Safari support

---

tools/semgrep.yml

This raises an error when we forget to make migration non-atomic when doing it in batches. `BATCH_SIZE` seems to be a good indicator for when we do batching with few early exceptions.
Semgrep playground: https://semgrep.dev/playground/s/Y6XW
Resolves https://github.com/zulip/zulip/pull/25879#discussion_r1222065537
<details>
</details>

semgrep: Check if a batched migration is made atomic.

---

web/styles/dark_theme.css
web/styles/zulip.css
web/templates/navbar.hbs

Followup to https://github.com/zulip/zulip/pull/25697#discussion_r1204799732
First put in place in #23724
I visually checked that things still look the same.

navbar: Remove top_navbar_full_width now that scrollbar is on html.

---

help/direct-messages.md
help/include/send-group-dm.md

- Updates the help center to use "direct messages" in mobile instructions.
Fixes #25870.
Current docs:
- https://zulip.com/help/direct-messages
- https://zulip.com/help/starting-a-new-direct-message
<details>
</details>

help: Rename private messages -> direct messages in mobile docs.

---

web/src/flatpickr.js

Easy −2 for [cycle-analysis](https://github.com/andersk/cycle-analysis).

flatpickr: Cut dependency on hotkey.js

---

zerver/lib/user_groups.py

We want to make sure that the system groups, once created, will always have the `GroupGroupMemberships` fully set up.
Prepares #23634
<details>
</details>

user_groups: Make system groups creation atomic.

---

tools/linter_lib/custom_check.py

They were deleted in commit 2d52463b61614ad17f029a34433303d61989521d.

custom_check: Remove checks for deleted ui_report aliases

---

docs/outreach/experience.md

Updates the first point in the section on prioritization in the outreach section of the documentation to cover fixing important bugs / regressions that are assigned or that the contributor picks up.
[Relevant CZO discussion](https://chat.zulip.org/#narrow/stream/14-GSoC/topic/priorities.20board/near/1590086).
[Current documentation](https://zulip.readthedocs.io/en/latest/outreach/experience.html#prioritization)
---
<details> …

docs: Update first point in outreach prioritization section.

---

web/templates/confirm_dialog/confirm_disable_all_notifications.hbs
web/templates/settings/data_exports_admin.hbs

Updates the two remaining references to private messages in the `web/templates` directory that are also translated strings.
See [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/2-general/topic/private.20messages.20.3D.3E.20direct.20messages/near/1588731).
---
<details>
<summary>Data export tab in organization settings</summary>
</details>
<details>
<summary>Notifications warning in personal settings</summary>
</details>
---
<details> …

web-templates: Update instances of "private message" to "direct message".

---

web/styles/message_row.css

This PR introduces additional padding to the top and bottom of the date row. See [CZO discussion](https://chat.zulip.org/#narrow/stream/137-feedback/topic/date.20separators).
| --- | --- |
| <img width="914" alt="date-row-before" src="https://github.com/zulip/zulip/assets/170719/4c88dd07-412e-4a4c-b575-6302d6675e87"> | <img width="914" alt="date-row-after" src="https://github.com/zulip/zulip/assets/170719/756e7ebc-b38e-4e2a-abe4-58fc4b802731"> |
<details> …

date_row: Expand padding around date reference.

---

zerver/lib/rate_limiter.py
zerver/lib/test_helpers.py
zerver/tests/test_auth_backends.py
zerver/tests/test_external.py
zerver/tests/test_rate_limiter.py
zerver/tests/test_settings.py
zerver/tests/test_signup.py
zerver/tests/test_thumbnail.py
zerver/tests/test_upload.py
zerver/views/upload.py
zproject/backends.py
zproject/urls.py

This was mistakenly left off of b799ec32b0ed.
<details>
</details>

uploads: Allow access to the /download/ variant anonymously.

---

docs/production/email-gateway.md
scripts/lib/install
scripts/lib/upgrade-zulip-stage-2
scripts/setup/upgrade-postgresql
web/src/popover_menus.js
web/src/ui_init.js
zerver/lib/user_groups.py
zerver/migrations/0443_userpresence_new_table_schema.py
zerver/tests/test_user_groups.py
zerver/views/user_groups.py
zproject/prod_settings_template.py

This backports the following PRs:
* #25987 and #25970 (latter to avoid merge conflicts)
* #25924 
* #25923 
* #25909 
* #25908
* #25891
* #25887 
* #25882 
* #25868

Backport changes for the 7.1 release

---

docs/production/upgrade.md
scripts/setup/upgrade-postgresql

Fixes: #25853.
<details>
</details>

Document PostgreSQL compatibility, and check we do not upgrade past what we support.

---

zerver/webhooks/sentry/doc.md
zerver/webhooks/sentry/fixtures/event_for_exception_rails.json
zerver/webhooks/sentry/fixtures/event_for_exception_vue.json
zerver/webhooks/sentry/fixtures/sample_event.json
zerver/webhooks/sentry/tests.py
zerver/webhooks/sentry/view.py

This PR makes the following changes to the Sentry Integration:
- Updates the documentation to be more accurate.
- Adds support for the "Rails" backend for Sentry Integration.
- Limits the check for Raven SDKs only to Python.
- Adds an exception fixture for "Vue".
- Adds support for sample events (previously, the integration used to send 400).
Regarding the support for "Vue", I created a sample Vue App, and the value of the `platform` field in the captured payload was `javascript`, which is already included in the integration. Hence, no change was required for this.
The sample event for `python` had a `version` equal to `5`. Hence, I had to use `pass` for that.
Fixes: #25778
<details>
<summary>Documentation Changes</summary>
| …

integrations: Improve Sentry Integration.

---

docs/overview/architecture-overview.md
docs/subsystems/release-checklist.md
docs/translating/internationalization.md
docs/translating/translating.md
help/include/translation-project-info.md
templates/corporate/for/business.html
templates/corporate/for/education.html
templates/corporate/for/events.html
templates/corporate/for/open-source.html
templates/corporate/for/research.html
tools/documentation_crawler/documentation_crawler/spiders/common/spiders.py

https://help.transifex.com/en/articles/7171815-web-application-s-domain-change

docs: Update Transifex URLs

---

api_docs/changelog.md
version.py
web/src/popovers.js
zerver/openapi/zulip.yaml
zerver/tests/test_muted_users.py
zerver/views/muted_users.py

We intentionally disallow muting bots previously upon a pending design decision in #16915.
This lifts that constraint.
Fixes #22693.
<details>
</details>

muted users: Add support to muting bots.

---

web/templates/settings/admin_user_list.hbs
web/templates/settings/bot_avatar_row.hbs

Fixes #25977
Fixes: 
<details>
</details>

bot_profile_card: Convert tooltips to Tippy.

---

web/styles/app_components.css
web/templates/draft.hbs
web/templates/scheduled_message.hbs

Fixes #25892
Fixes: 
<details>
</details>

tooltips: Use tippy tooltips for drafts and schedule message overlays.

---

zerver/models.py

"This consistent ordering is important to prevent to prevent" -> "This consistent ordering is important to prevent"
<details>
</details>

models: Fix typo in comment.

---

analytics/tests/test_counts.py

See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/2-general/topic/private.20messages.20.3D.3E.20direct.20messages/near/1588731).
This takes care of instances of "private message" and "PM" in the `analytics/` directory. This is a small change / PR, but as some of the other directory updates are very large, I felt it was cleaner to just put up this as a separate update.
---
<details>
</details>

analytics: Replace "private message" with "direct message".

---

zerver/middleware.py

`streaming_content` is an iterator. Consuming it within middleware prevents it from being sent to the browser.
https://docs.djangoproject.com/en/4.2/ref/request-response/#streaminghttpresponse-objects
“The `StreamingHttpResponse`…has no `content` attribute. Instead, it has a `streaming_content` attribute. This can be used in middleware to wrap the response iterable, but should not be consumed.”

middleware: Do not consume StreamingHttpResponse.streaming_content

---

api_docs/changelog.md
version.py

Revises the API changelog feature level 189 entry for formatting error and to clarify the text. Also, bumps the `API_FEATURE_LEVEL` to 189 in `version.py`.
The original pull request for these changes was #25640.
<details>
<summary>API changelog entry for feature level 189 - before changes</summary>
</details>
<details>
<summary>API changelog entry for feature level 189 - after changes</summary>
</details>
---
<details> …

api-changelog: Update feature level 189 entry and bump API_FEATURE_LEVEL.

---

docs/overview/changelog.md
docs/production/deployment.md

Previously, `X-Forwarded-Proto` did not need to be set, and failure to set `loadbalancer.ips` would merely result in bad IP-address rate-limiting and incorrect access logs; after 0935d388f053, however, failure to do either of those, if Zulip is deployed with `http_only`, will lead to infinite redirect loops after login.  These are accompanied by a misleading error, from Tornado, of:
Forbidden (Origin checking failed - https://zulip.example.com does not match any trusted origins.): /json/events
This is most common with Docker deployments, where deployments use another docker container, such as nginx or Traefik, to do SSL termination.  See zulip/docker-zulip#403.
Update the documentation to reinforce that `loadbalancer.ips` also controls trust of `X-Forwarded-Proto`, and that failure to set …

docs: Clarify that trust of X-Fowarded-Proto is also necessary.

---

web/shared/src/typing_status.js
web/shared/src/typing_status.ts
web/tests/typing_status.test.js

Migrates `web/shared/typing_status.js` to TypeScript.
<details>
</details>

ts: Convert `web/shared/typing_status.js` to TypeScript.

---

web/src/settings_account.js

Disconnection of pop-up of date-picker for birthday on scroll of settings is prevented.
Fixes #24924
<details>
</details>

settings: Remove disconnection of date-picker pop-up on scroll.

---

zerver/data_import/slack.py
zerver/management/commands/convert_slack_data.py
zerver/tests/test_slack_importer.py

slack: Provide more information when a Slack token fails to validate.

---

web/src/rendered_markdown.js
web/tests/rendered_markdown.test.js

before: 
after:
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/UI.20redesign.3A.20mentions

wildcard_mention: Don't highlight for unsubbed users.

---

web/styles/modal.css
web/styles/portico/portico_signin.css
web/styles/search.css
web/styles/settings.css
web/styles/zulip.css
web/templates/compose_control_buttons.hbs
web/templates/copy_code_button.hbs
web/templates/copy_invite_link.hbs
web/templates/dialog_change_password.hbs
web/templates/settings/add_new_custom_profile_field_form.hbs
web/templates/settings/api_key_modal.hbs
web/templates/settings/custom_user_profile_field.hbs
web/templates/settings/edit_custom_profile_field_form.hbs
web/third/bootstrap/css/bootstrap-btn.css
web/third/bootstrap/css/bootstrap.css

- First commit is to remove the bootstrap CSS for `input-block-level` class.
- Next two commits are to remove bootstrap CSS for `fieldset` elements.
- Next two commits are to remove `pull-left` and `pull-right` class and its CSS.
- Next six commits are to remove the bootstrap CSS and re-add these CSS rules to the specific elements for email, file, image, password, url type inputs.
- Last two commits are to remove unnecessary classes from password and url type inputs.
There is no change in visual appearance of any of the elements due to changes in this PR.
<details> …

Remove bootstrap CSS for different input type elements.

---

web/templates/gear_menu.hbs
web/templates/tooltip_templates.hbs

Added accessibility label to gear menu toggle.
Fixes: [#25664](https://github.com/zulip/zulip/issues/25664)
</details>

gear_menu: Add accessibility label to gear menu toggle.
