zulip/zulip

zerver/tests/test_openapi.py, zproject/urls.py
urls: Move `jwt_fetch_api_key` endpoint to `v1_api_mobile_patterns`.
Moves `jwt_fetch_api_key` endpoint to `v1_api_mobile_patterns` so
that `tools/test-api` detects it as an API endpoint that is pending
documentation.
Fixes #24982.
=> urls: Move jwt_fetch_api_key endpoint to v1_api_mobile_patterns.

web/src/upload.js, web/tests/upload.test.js
Fixes: #24654
This commit changes the way compose box responds to a file drop or paste. 
Currently, the compose box expands only after the file is uploaded to the server, which can cause confusion if the upload fails and there is also no progress bar. 
With the update, the compose box will expand immediately upon drop or paste events showing the status of upload.
***Before***
https://user-images.githubusercontent.com/71015892/224507579-7c7bc2e8-c22e-431f-ae46-ebf04626c248.mp4
***After***
https://user-images.githubusercontent.com/71015892/224507580-7eab3847-4f6d-4dfd-8954-68160005a9c8.mp4
<details> …
=> file_drop: Open compose immediately on file drop or paste event.

zerver/actions/message_edit.py, zerver/lib/user_topics.py, zerver/tests/test_message_edit.py
follow-up: [#24742 (comment)](https://github.com/zulip/zulip/pull/24742#discussion_r1142623662)
This PR updates the logic for migrating user_topic rows during the move-messages operation when the target topic
already has messages.
[Previously](https://github.com/zulip/zulip/blob/main/zerver/actions/message_edit.py#L808), the `target_topic's visibility_policy` was simply set to the `original_topic's visibility_policy`, and the `original_topic's visibility_policy` was set to `INHERIT`.
This PR updates the move-messages code path to determine the `new_visibility_policy` depending on the visibility policies
of the original and target topics. The `target_topic's visibility_policy` is then updated.
The number of db queries has increased by two:
* One query corresponds to determining if …
=> user_topics: Update 'do_update_message' to handle 'merge userTopic states'.

web/src/server_events_dispatch.js, web/src/stream_settings_ui.js
This fixes regression in 55bd3220b6ea8ebb694d87400c27ce95e2f38054, Where notice gets rendered even when there are streams shown in panel. Now the check var to render message conditionally checks for both `subscribed` and `all streams` tabs. We are avoiding the fully use of DOM in this context because if the filter results in no stream, then also it will display a notice. Also this commits swaps order of calling `stream_data.delete_sub()` and `stream_settings_ui.remove_stream()` functions in server_events_dispatch because `update_empty_left_panel_message` uses stream_data, which was giving outdated data.
Fixes: 
***Before***
***After***
https://user-images.githubusercontent.com/71015892/232916113-f516349c-b899-45e5-9ec7-2e8b6e309046.mov
<details> …
=> streams: Fix notice appears even when the panel is not empty.

web/src/message_viewport.js, web/src/popover_menus.js
Previously, when a user scrolls down a long text of message and presses the hotkey for viewing the message actions, the popover menu would continue to open where the message actions button. Thus, the popover menu would be cut short and sometimes off the screen. These changes will scroll the client to the top of the message and ensure that the popover menu is always visible.
This is a rebase of #23830 to continue and push forward the progress on the issue. No additional changes were made from it.
Fixes: #23774.
<details>
</details>
<details>
</details>
<details> …
=> popover: Scroll to top of long message when viewing message actions.

zerver/openapi/zulip.yaml
Cleans up the API documentation for get events with a `message_type` value: `delete_message`, `typing op:start` and `typing op:stop`.
Noted when working on #25154.
<details>
<summary>Delete message event</summary>
[Current documentation](https://zulip.com/api/get-events#delete_message)
</details>
<details>
<summary>Typing op:start event</summary>
[Current documentation](https://zulip.com/api/get-events#typing-start)
</details>
<details>
<summary>Typing op:stop event</summary>
[Current documentation](https://zulip.com/api/get-events#typing-stop)
</details>
---
<details> …
=> api-docs: Clean up documentation of API events with `message_type`.

puppet/zulip/manifests/app_frontend_base.pp, puppet/zulip/manifests/profile/app_frontend.pp, puppet/zulip_ops/manifests/app_frontend.pp
7c023042cfbb moved the logrotate configuration to being a templated file, from a static file, but missed that the static file was still referenced from `zulip_ops::app_frontend`; it only updated `zulip::profile::app_frontend`.  This caused errors in applying puppet on any `zulip_ops::app_frontend` host.
Prior to 7c023042cfbb, the Puppet role was identical between those two classes; deduplicate the rule by moving the updated template definition into `zulip::app_frontend_base` which is common to those two classes and not used in any other classes.
<details> …
=> puppet: Move logrotate config into app_frontend_base.

web/src/tippyjs.js, web/templates/compose.hbs
before:
after (remove padding on right side of compose to reproduce it):
Also, we adding delay when showing send later and narrow to topic tooltips.
=> Fix send later tooltip being cutoff by the new design of compose box deployed on CZO.

web/src/recent_topics_ui.js, web/tests/recent_topics.test.js
-----------------------------------
Fixes part of #24243 
- This PR fixes the 5th point of #24243
-----------------------------
<details>
<summary>Recent Conversations</summary>
<br>
</details>
-------------------------
<details>
</details>
=> unmute_topic: Show all unmuted topics within muted streams in `Recent conversations`. 

web/src/tippyjs.js, web/templates/compose.hbs
Added a tippy tooltip in `tippyjs.js` that delegates to `#compose-send-button`.
The content of tippy tooltip is changed dynamically as per the value of `user_settings.enter_sends`.
`user_settings.enter_sends` returns true if send shortcut is `Enter` and flase if shortcut is `Ctrl + Enter`.
Fixes: 
#24619
<details>
</details>
=> tooltips: Change `compose-send-button` tooltip dynamically.

web/src/tippyjs.js, web/templates/left_sidebar.hbs
Added tippy tooltips for all_messages, recent_topics, mentions, drafts, and show_all_private_messages
in the left sidebar by adding a class `.tippy-left-sidebar-tooltip` which adds tooltips with LONG_HOVER_DELAY 
and default placement right with fallback placement equal to bottom.
removed tooltips from Mentions and Starred_messages.
Fixes part of #24311
Fixes: 
#24311
All messages:
Recent Conversations:
Drafts:
Show all private messages:
Fallback placement for mobile devices:
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit- …
=> tooltips: Add tippy tooltip for left sidebar elements.

web/src/reload.js, web/src/server_events.js
`reload.js` and `server_events.js` was forming a 2-way cyclic import. To break the cycle, I passed `server_events.cleanup_event_queue` to reload module via its initialization function in `ui_init` and stored this function in a global variable to be later used by `reload` module without having us import `server_events` and hence breaks the cycle.
<details>
</details>
=> js: Break cyclic dependency between `reload` and `server_events`.

web/src/channel.js, web/src/dialog_widget.ts, web/src/types.ts
Follow-up PR for #24909 
Changed `AjaxRequest` name to a clearer one `AjaxRequestHandler`, also moved this type to `types.ts` with a comment to move it into `channel.js` once it migrates to typescript.
Took reference from jQuery docs: https://api.jquery.com/Jquery.ajax/ for correct types for `success` and `error` callbacks.
<details>
</details>
=> dialog_widget: Refactor `AjaxRequest` type and moved it to `types.ts`.

web/styles/components.css, web/styles/settings.css
- First commit is to change the focus outline on dropdown button.
- Second commit is to remove underline for the focussed option.
Fixes:  https://chat.zulip.org/#narrow/stream/6-frontend/topic/dropdown.20keyboard.20behavior/near/1550252
<details>
</details>
=> Fix focus behavior for dropdown list widgets.

scripts/lib/install, scripts/lib/update-git-upstream, scripts/lib/upgrade-zulip-from-git, scripts/lib/zulip_tools.py
Installs which are upgrading to current `main`, and are upgrading for
the very first time from an install which was originally from git,
have a `/home/zulip/deployments/current` which, unlike all later
upgrades, is not a `git worktree` of `/srv/zulip.git`, but rather a
direct `git clone` of some arbitrary URL.  As such, it does not have
an `upstream` remote, nor a cached `zulip-git-version` file.
This makes later attempts to determine the pre-upgrade revision of
git (for pre-deploy hooks) fail, as without a `zulip-git-version`
file, `ZULIP_VERSION` is insufficiently-specific (e.g. `6.1+git`), and
there is no guarantee the necessary tags exist either.
Make fresh git installs set up an `upstream` and run
`./tools/cache-zulip-git-version` going forward; however,
that does not address the …
=> upgrade-zulip-from-git: Backfill a zulip-git-version as needed.

templates/zerver/emails/confirm_registration.html, templates/zerver/emails/followup_day1.html, templates/zerver/emails/invitation.html, templates/zerver/emails/macros.html, templates/zerver/emails/realm_reactivation.html
Improve "contact us" line in onboarding emails
as per the issue:
-> make macros
-> use different lines for self hosted and cloud
-> alter the line in follow-up html
Fixes:
https://github.com/zulip/zulip/issues/24260
<details>
<summary>confirm registration</summary>
</details>
<details>
<summary>Follow up day 1</summary>
</details>
<details>
<summary>Invitation</summary>
</details>
<details>
<summary>realm reactivation</summary>
</details>
<details>
<summary>confirm registration</summary>
</details>
<details>
<summary>Follow up day 1</summary>
</details>
<details>
<summary>Invitation</summary>
</details>
<details>
<summary>Realm reactivation</summary>
</details>
<details> …
=> emails: Improve "contact us" line in onboarding emails.

help/rename-a-topic.md
Documents option introduced in #25149.
Note: The "If you do not see this option,..." phrasing and placement for the note is consistent with https://zulip.com/help/move-content-to-another-topic and related pages.
Current page: https://zulip.com/help/rename-a-topic
Updated instructions:
=> help: Document new "Rename topic" option.

web/e2e-tests/lib/common.ts
https://pptr.dev/api/puppeteer.page.waitfortimeout
https://nodejs.org/api/timers.html#timerspromisessettimeoutdelay-value-options
=> e2e-tests: Replace deprecated page.waitForTimeout

help/require-topics.md
After #21739, there is no longer a special permissions exception for adding a topic to messages without one.
Current page: https://zulip.com/help/require-topics
Updated:
=> help: Update /help/require-topics.

web/styles/components.css
This commit sets the transition to "none" for the dropdown list widget element during focus to remove a weird fade-in effect. We have to set this to none as the existing CSS sets transition for all button elements inside ".new-style" div. This commit adds the CSS for select element too, as both are using same CSS, but since there was no transition effect for select elements before as well, we can do this change safely.
Fixes: https://github.com/zulip/zulip/pull/25175#issuecomment-1515177026
<details> …
=> dropdown_list_widget: Fix fading transition during focus.

zerver/openapi/zulip.yaml
Updates areas in the API documentation that reference the maximum length of a stream message topic to note the `max_topic_length`.
Updates areas in the API documentation that reference the maximum length of a stream name to note the `max_stream_name_length` and areas that reference the maximum length of a stream description to note the `max_stream_description_length`.
All of these maximum values are sent by the `POST /register` response.
See relevant CZO conversations:
- [#api documentation > direct message search operators](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/direct.20message.20search.20operators/near/1552433)
- [#api documentation > max size](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/max.20message.20size/near/1508146)
**Notes**:
- In …
=> api-docs: Update docs to reference max lengths in register response.

web/src/message_list.js, web/src/message_list_view.js, web/src/unread_ops.js, web/tests/example7.test.js
Not having this check caused `Mark as unread from here` to not work for message which was selected when the list was rendered since we marked it as read again via `this.list.select_id` after marking it as unread.
Steps for reproducer:
* Narrow to a topic / PM with plenty of messages.
* Mark some messages as unread in that narrow.
* Reload the page.
* Now the message which was selected will remain "read" even upon marking it as unread.
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/unable.20to.20mark.20message.20as.20read
=> message_list_view: Don't select message if the list is not current.

web/src/topic_list_data.js, web/tests/topic_list_data.test.js
This PR fixes part 4 of the Left sidebar section of https://github.com/zulip/zulip/issues/24243:
Created a new function `choose_topics` that loops through the topics and push filtered topics using `should_show_topic` function to `items` array if not zoomed else just push all topics directly to array.
If stream is muted and not zoomed call the `choose_topics` function twice, first with passing `unmuted_topics` and second time with passing remaining topics. else, call it only once with `topic_names`.
Fixes: 
#24243
https://user-images.githubusercontent.com/64723994/231698353-b1737eb4-cbd8-4c04-9d83-2196427ca812.mp4
example case: In muted stream(ビデオゲーム), Topics 1 to 10 are unmuted, topic 1 doesn't have unread hence it only shows 2-10(9 topics), and topics …
=> left_sidebar: Prioritize unmuted topics in non-zoomed topic list.

web/src/filter.js, web/src/message_list.js, web/src/stream_muting.js
------------------------------------------------------------------------
Fixes: #24243
- This PR fixes point 6 of #24243. 
--------------------------------------------------------------
<details>
<summary>All Messages</summary>
<br>
</details>
------------------------------------------------
<details>
</details>
=> unmute_topic: Show all unmuted topics within muted streams in `All messages` narrow.

web/src/muted_topics_ui.js, web/src/recent_topics_ui.js, web/tests/recent_topics.test.js
This is a prep PR for #25140 and this enables to update of the visibility policy of the topic in a muted stream by clicking on unmute icon in Recent conversations in real-time without any page reload.
Renamed and updated get_muted_topics to `get_user_topics_for_visibility_policy()` to work for all visibility policies by taking visibility policy as a parameter to get topics having that visibility policy.
Added rerender_for_unmuted_topic function similar to rerender_for_muted_topic function that updates unmuted topics in Recent conversations.
Renamed update_topic_is_muted to update_topic_visibility_policy as it now updates unmuted topics as well.
**Feedback Required:**
Should I merge `rerender_for_unmuted_topic` and `rerender_for_muted_topic` and convert them into one general function? …
=> user_topics: Rerender unmuted topics in Recent conversations.

web/src/invite.js
This PR aims to replace the custom datetime format in the invite modal with one of the standard formats from `timerender.js`.
Related discussion at [CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/date.20and.20time)
=> timerender: Fix expiration date on invite modal.

web/templates/recent_topic_row.hbs
CZO discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/mute.20icon.20tooltip.20in.20recent.20conversation
Set data-tippy-trigger="mouseenter" on the mute icon in a recent conversation to prevent the tippy from staying on when the mute icon is focused on clicking the mute icon.
Fixes: 
<details>
<summary><b>Before<b></summary>
<br>
https://user-images.githubusercontent.com/64723994/233964906-9337c773-1aa0-4c5b-acea-dd2b1c3c87ee.mp4
</details>
<details>
<summary><b>After<b></summary>
<br>
https://user-images.githubusercontent.com/64723994/233965320-d2ef4d0e-a379-4f0d-aa05-89c95943f1ee.mp4
</details>
<br>
<details> …
=> recent_conversations: Fix mute icon tooltip on focus in recent conversersations.

web/src/hotkey.js
Without this, if there was a success compose banner and user pressed escape key, no banners were hidden, and the same behaviour was repeated without compose ever closing.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/esc.20after.20creating.20scheduled.20msg
=> hotkey: Clear message sent success banners too on escape keypress.

web/src/notifications.js
When we send a message (for which notifications are enabled) in the format `[](file_url)`. A blank notification is sent.
Fixing this by checking if there is no `text` and adding a message in that case.
The below mentioned PR also includes the checking for `user_uploads` to be present in the URL but
I am not sure if that should be required since probably there is going to be an empty text in those cases only.
Inspired from: #8796.
Fixes: #8087.
Before (without text)
Message: `[](https://upload.wikimedia.org/wikipedia/commons/4/44/Subhas_Chandra_Bose_NRB.jpg)`
After (without text)
Message: `[](https://upload.wikimedia.org/wikipedia/commons/4/44/Subhas_Chandra_Bose_NRB.jpg)`
Before & After (with text)
Message: `[Subhas Chandra …
=> notifications: Fix blank notification sent when no text specified.

web/src/compose_recipient.js
We should trigger click event to open up the dropdown popup instead of using `.dropdown("toggle")` because we want to clear the search state when opening up the popup and the logic for that is registered in `on-click` handler defined in `dropdown_list_widget`.
Fixes: #25218
Before:
https://user-images.githubusercontent.com/84276404/233763252-ac779afa-1bdb-4a87-8177-d729d74543df.mp4
After:
https://user-images.githubusercontent.com/84276404/233763291-8c957f48-77c2-4d49-96dc-9e26149a1c36.mp4
<details> …
=> compose: Clear search filter when opening new stream picker in compose box.

web/src/stream_list.js, web/src/topic_list_data.js, web/src/unread.js, web/styles/dark_theme.css, web/styles/left_sidebar.css, web/templates/topic_list_item.hbs, web/tests/stream_list.test.js, web/tests/topic_list_data.test.js, web/tests/unread.test.js
This PR fixes parts 2 and 3 of the Left sidebar section of #24243: 
Commit 1[fbd1befa9c1202b89b7cc6f1b8a9841debc9772e]: Changed CSS for fading the muted stream. This will allow us to add
feature in the next commits in this PR to set the opacity of unread_count to 1 while keeping it at 0.5/0.75. 
Commit 2[8a05d9ba119cda6319dc44d7cbf38b62c60b7f92]: If unread messages of unmuted topics in muted stream>0, show stream_unmute_count in .unread_count and show it in regular font(not faded).
Commit 3[4cce16dcf6942118095a3f30b4836f1d0eed542b]: Add class unmuted_topic to li.bottom_left_row element if the topic is unmuted. Add relevant CSS for .unmuted_topic to display unmuted topics in regular font.
Note: In commit 2 8a05d9ba119cda6319dc44d7cbf38b62c60b7f92, the unread messages count of unmuted …
=> left_sidebar: Implement new unread_count logic and font styling for muted streams.

web/src/compose_closed_ui.js, web/src/tippyjs.js, web/templates/compose.hbs, web/tests/compose.test.js
----------------------------------------
Fixes: #25096
----------------------------
<details>
<br>
</details>
<details>
<br>
- Closed Compose  Box
<br>
- disabled button
</details>
-----------------------------------
Reference for tippy issue mentioned in the commit message: https://github.com/atomiks/tippyjs/issues/286
--------------------------------
<details> …
=> tooltips: Convert compose box  tooltips to tippy tooltips.

tools/test-js-with-node, web/src/localstorage.ts, web/tests/navbar_alerts.test.js
Added function parameter types, return type, and types of local varaibles. 
Added a `null` check for `raw_data` before `JSON.parse`.
Created a type `FormDataObject` and  an export type `LocalStorage`   to
imporve conciseness and clearity. Type `LocalStorage` is `export` because
it might be used in other files based on an observation that many files
has imported `localstorage`.
One thing to note is that the return type of a member function `setExpiry` 
in type `LocalStorage` is currently `object`, rather than a more specific type.
This is because I am not able to infer what the type `this` is in the `setExpiry`
funtion body.  
I checked a six-year-ago commit 8b22b94ab1613f523be01572787a13e3d49c50fd which created the original js file 
`localstorage.js`. Seems there was few clues on why the …
=> TS migration: Convert `localstorage.js` to `localstorage.ts`.

web/src/click_handlers.js
If a user is editing a message or viewing the message source, they'll notice that clicking on the messsage doesn't move the blue box to it while the keyboard works just fine. We want to allow the message to be selected while not triggering the reply function.
**Note:**
Since we don't want to open the compose box when clicking the messages being edited/viewed, clicking on the message won't trigger the message fading effect like how other messages do when in stream views.
<details>
<summary>View source UI</summary> 
</details>
<details>
<summary>Edit message UI</summary> 
</details>
<details>
Individual …
=> click_handlers: Allow messages being edited/viewed to be clicked.

web/src/user_group_edit.js, web/src/user_groups_settings_ui.js, web/styles/modal.css, web/styles/subscriptions.css, web/templates/user_group_settings/change_user_group_info_modal.hbs, web/templates/user_group_settings/user_group_creation_form.hbs
This PR does following improvements in #streams and #groups overlay.
* Adds word break in the title in the right pane to handle long stream and group names.
* Handle long group/stream names in group/stream name edit dialog box header.
* Fix positioning of edit (pencil) button to the right end and provide maximum available space for stream/group name.
Follow-up for: #24514 (and edit for #24583, originally worked by @Ddharmani3).
Long stream name title on right pane:
Long group name title in right pane:
<details> …
=> user groups: Minor fixes in CSS common to #groups and #streams overlay.

web/src/message_view_header.js
Popovers hide while clicking on the search bar/icon and settings icon now.
Fixes: #24318
<details>
</details>
=> popovers: Fix hide all popovers when clicked on search or settings.

web/src/search.js, web/styles/search.css, web/styles/zulip.css, web/tests/search_future.test.js, web/tests/search_now.test.js, web/third/bootstrap-typeahead/typeahead.js
Previously the typeahead container was being created at the bottom of `body`, and its width (and `top` and `left`) were being set to move it to the right position.
Now it sits in the search box container, which gives it the correct position and width by default. This is better for DOM readability, and is also better for the new 100% width (which is part of the search bar redesign) because it can change width more smoothly with the search bar when the page changes width.
prep for #24345
=> search: Put typeahead under search bar in the DOM with full width.

scripts/lib/upgrade-zulip-from-git
96e42b8e811f broke this when it split out the steps to reset the upstream.
<details>
</details>
=> upgrade-zulip-from-git: CWD will be the cache directory.

web/src/stream_color.js, web/styles/zulip.css
discussion: https://chat.zulip.org/#narrow/stream/431-redesign-project/topic/redesign.20tweaks.20.2325247
Fixes `Recipient bar color correction` and  `Dark mode DM background` parts of #25247
before:
after:
before:
after:
=> Change recipient bar colors and PM background colors.

web/src/search.js, web/third/bootstrap-typeahead/typeahead.js
When search bar is empty and we've reached that state by using the `backspace` key. There are no suggestions as there are when you select an empty search bar.
The cause of this was an explicit prevention of this suggestion box in `typeahead.js` so that the
`backspace` key is free to interact with the other elements.
The fix here is to add an optional `hideOnEmpty` option so that if we want this suggestion box to appear we can set this option to `false` and this behavior will be prevented.
Fixes: #25062
<details> …
=> search: Fix display of suggestion box when search bar empty.

templates/zerver/unsubscribe_success.html
Removes the bottom padding in the last `<p>` tag with content in `unsubscribe_success.html`.
Follow-up to #25074.
**Notes**:
- Another option was to add the `account-creation` class, which also removes the padding from the final `<p>` tag. But that also impacts the font-weight. Added example screenshots of that below for comparison.
---
<details>
<summary>Before and after changes</summary>
| --- | --- |
| ![Screenshot from 2023-04-14 12-29-58](https://user-images.githubusercontent.com/63245456/232790420-19c269fb-c31b-4a40-a436-f6b88cf4f1bd.png) | ![Screenshot from 2023-04-18 13-01-40](https://user-images.githubusercontent.com/63245456/232790510-69e09421-930c-419b-8fd7-5a20d173529a.png)
| ![Screenshot from 2023-04-14 …
=> template: Fix padding in `unsubscribe_success.html`.

web/src/pm_list_data.js, web/tests/pm_list_data.test.js
Increases the max numbers of private/direct conversations and stream topics displayed in the left sidebar to be:
- 8 max conversations/topics with all messages read
- 12 max conversations/topics when there are some/all with unread messages
See [this CZO conversation for more context](https://chat.zulip.org/#narrow/stream/137-feedback/topic/customize.20number.20of.20private.20messages/near/1504593).
**Notes**:
- There is a prep commit that cleans up the node test for `pm_list_data.js` to make increasing these max numbers easier in that test.
---
<details>
<summary>Some unreads in direct/private messages</summary>
</details>
<details>
<summary>All read in direct/private messages</summary>
</details><details>
<summary>All unread in direct/private messages</summary>
</details> …
=> left-sidebar: Increase max conversations/topics shown to 8 (no unreads) and 12 (unreads).

web/src/emoji.ts, web/src/input_pill.js, web/src/input_pill.ts, web/tests/input_pill.test.js
This PR contains two commits:
1) Breaks a fairly simple import cycle between `compose.js` and `input_pill.js`.
2) Migrates the `input_pill` module to TypeScript and leverages TypeScript generics to make it a generic module.
Fixes: #25022 
<details>
</details>
=> ts: Convert `input_pill` to TypeScript and break import cycle.

web/src/popover_menus_data.js, web/templates/topic_sidebar_actions.hbs
This PR solves the First part under Left sidebar section of #24243:
For topics in muted streams, replace the "Mute topic" option in the three-dot topic menu with an "Unmute topic" option, which should make the topic unmuted. For unmuted topics in muted streams, show the regular "Mute topic" option, which should specifically mark the topic as muted, as usual.
Fixes part of #24243
- Topic in an unmuted stream(same as before):
- Muted topic in an unmuted stream(same as before):
- Topic in a muted stream[New behaviour]:
- Unmuted topic in a muted stream[New behaviour]:
<details> …
=> topic_sidebar_actions: Revamp topic mute/unmute UI in sidebar actions menu.

web/src/compose.js, web/src/compose_banner.ts, web/src/hotkey.js, web/src/message_scroll.js, web/src/notifications.js, web/src/user_topics.js, web/styles/compose.css, web/styles/dark_theme.css, web/templates/compose_banner/unmute_topic_banner.hbs, web/tests/lib/compose_banner.js
We add a new banner informing the user if and when they send a message to a muted topic / stream. It also has a button to unmute the topic.
Fixes: #24246.
<details>
</details>
=> compose: Add banner for unmuting the muted topic a message is sent to.

.github/workflows/zulip-ci.yml
New in pnpm 8.3.0, this replaces the yarn-deduplicate check that was removed in commit 3a27b12a7dc9580e565946d3252720cbdce08934 (#24731).
Sample failure:
```console
$ pnpm dedupe --check
 WARN  deprecated json-schema-ref-parser@9.0.9: Please switch to @apidevtools/json-schema-ref-parser
 WARN  deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated mumath@3.3.4: Redundant dependency in your project.
 WARN  deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
 ERR_PNPM_DEDUPE_CHECK_ISSUES  Dedupe --check found changes to the lockfile
Packages
/@formatjs/icu-messageformat-parser/2.3.1
└── …
```
=> ci: Run `pnpm dedupe --check`

docs/production/deployment.md, puppet/zulip/files/nagios_plugins/zulip_postgresql_backups/check_postgresql_backup, puppet/zulip/files/postgresql/pg_backup_and_purge
I funbled around for a while to try to find a way to have the replicas know about each other, so they could, say, pick the first alphabetic one as the one which would take the backup.
However, the replicas don't have information about each other, and they only only have ACLs to connect to the primary for replication, which doesn't allow arbitrary SQL (to inspect `pg_stat_replication`), only [a limited set of commands](https://www.postgresql.org/docs/current/protocol-replication.html).
At least this errs on the side of too many backups, rather than too few.
<details> …
=> Take PostgreSQL backups on replicas, if possible

tools/test-js-with-node, web/src/compose_actions.js
This PR adds the code to remove the `invalid` class (which is responsible for showing the error border on the compose box) from the compose text area when the compose box is closed. 
Before this, if someone clicks on "Send" on an empty compose box then a red border will appear indicating that there is no message but when the compose box was re-opened the border was still there, this PR fixes that.
[CZO Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/empty.20message.20indicator.20not.20clearing/near/1555466)
Before:
[Before_1.webm](https://user-images.githubusercontent.com/35286603/234382349-2517e077-4f28-448b-969f-d09a5c879008.webm)
After:
[After_1.webm](https://user-images.githubusercontent.com/35286603/234382340-84c18b26-b5a3-442a-8ab …
=> compose: Remove empty message warning border after closing.

corporate/urls.py, templates/corporate/case-studies/atolio-case-study.html, templates/corporate/case-studies/atolio-case-study.md, templates/corporate/case-studies/end-point-case-study.md, templates/corporate/case-studies/idrift-case-study.md, templates/corporate/for/business.html, templates/corporate/for/use-cases.md, templates/zerver/landing_nav.html, zerver/tests/test_docs.py
Testing:
- Clicked on links
- Tested top banner area on narrow screens for /for/business and /case-studies/atolio.
Highlight for review:
- All the link names, especially in the top nav
- Subtitle and PAGE_DESCRIPTION on the new page
- Wording for links to other business case studies (bottom of case study pages). In particular, I worry a bit that it's not clear that we're linking to a case study, as opposed to the company's home page. We can increase how much of the text is in the link; not sure if that would help.
Follow-ups:
- Figure out which quote(s) to feature on other pages
<details>
<summary>
Top nav screenshot
</summary>
</details>
<details>
<summary>
Screenshots of changes on other pages
</summary>
</details>
=> portico: Add Atolio case study

templates/zerver/invalid_email.html, templates/zerver/no_spare_licenses.html, templates/zerver/unsubscribe_link_error.html, zerver/tests/test_invite.py
Updates 3 templates that had not been updated for the `white-box` style for redirects when there is an error:
- `invalid_email.html`
- `no_spare_licenses.html`
- `unsubscribe_link_error.html`
See relevant [CZO conversation](https://chat.zulip.org/#narrow/stream/9-issues/topic/email.20unsubscribe.20error.20page/near/1550064).
**Notes**:
- Also uses the `account-creation` class to remove any padding on the final `<p>` tag with the `white-box` class, which also makes the font-weight 400.
---
<details>
<summary>Unsubscribe link error</summary>
</details>
<details>
<summary>No Zulip Cloud licenses available</summary>
</details><details>
<summary>Invalid email - several variants</summary>
**No emails with "+"**:
**No disposable emails**:
**Limited subdomain …
=> templates: Update redirects that didn't have CSS formatting.

puppet/zulip/files/postgresql/wal-g-exporter, puppet/zulip_ops/manifests/profile/prometheus_server.pp, puppet/zulip_ops/manifests/prometheus/wal_g.pp, puppet/zulip_ops/templates/supervisor/conf.d/prometheus_wal_g_exporter.conf.template.erb
Since backups may now taken on arbitrary hosts, we need a blackbox monitor that _some_ backup was produced.
Add a Prometheus exporter which calls `wal-g backup-list` and reports statistics about the backups.
This could be extended to include `wal-g wal-verify`, but that requires a connection to the PostgreSQL server.
<details>
</details>
=> prometheus: Add an exporter for wal-g backup properties.

templates/zerver/emails/email.css, templates/zerver/emails/email_base_default.html, templates/zerver/emails/email_base_marketing.html, templates/zerver/emails/email_base_messages.html, zerver/lib/send_email.py
This commit places the email CSS into the `style` tag located in the `head` section. This resolves the issue of being unable to apply certain CSS styles that cannot be inlined, such as media queries and pseudo-classes.
=> emails: Fix some css not being applied to emails.

web/src/notifications.js
UNMUTED topics in muted streams obey stream-specific notification settings and global notification settings as fallback.
A user receives or does not receive email or push notifications for messages in UNMUTED topics depending on the email or push stream-specific notification settings configured, and global notification settings are used as a fallback.
This commit updates the logic to send or not send desktop notifications for messages in the UNMUTED topic depending on the corresponding stream-specific notification settings configured and global notification settings as a fallback.
Corresponding backend logic for reference:
```python
def user_allows_notifications_in_StreamTopic(
stream_is_muted: bool,
visibility_policy: int,
stream_specific_setting: Optional[bool],
global_setting: bool,
) …
```
=> notifications: Enable desktop notifications for the UNMUTED topic.

tools/test-js-with-node, web/src/compose_banner.ts, web/src/compose_validate.js, web/src/notifications.js, web/src/scroll_util.ts, web/src/upload.js
This PR contains two commits:
1) Migrating `scroll_util` to TypeScript.
2) Moved `append_compose_banner_to_banner_list` from `compose_validate.js` to `compose_banner.ts`.
<details>
</details>
=> ts: Migrate `scroll_util.js` to TypeScript.

web/styles/message_row.css, web/templates/me_message.hbs, web/templates/message_avatar.hbs, web/templates/message_body.hbs
Previously, the hover effect on the sender name in the message list would apply to the entire row, which was causing unexpected behavior. This commit updates the CSS to only apply the hover effect to the sender name itself, which resolves the issue.
Fixes: 
#25276
https://user-images.githubusercontent.com/64723994/234387401-385c9448-5c1b-478b-ae23-80c27ab5a945.mp4
Unable to add still screenshot as screenshot don't capture mouse position.
<details> …
=> messages: Fix sender name hover.

web/templates/left_sidebar.hbs
This provides a basic link to view scheduled messages. At present, the link is always visible, and it does not yet include a scheduled-message count.
There is [a discussion about a proper icon on CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/view.20scheduled.20messages/near/1556366), but for now I have used the basic calendar icon from FontAwesome. See the screenshot below.
While I have included the translation-string syntax, I don't understand how that system works yet, so I might need guidance.
Fixes part of: #25101 
<details> …
=> left-sidebar: Provide link to scheduled messages.

puppet/zulip/files/cron.d/pg-backup-and-purge, puppet/zulip/manifests/postgresql_backups.pp
Otherwise, this output goes into `/var/spool/mail/postgres`, which is not terribly helpful.  We do not write to `/var/log/zulip` because the backup runs as the `postgres` user, and `/var/log/zulip` is owned by zulip and chmod 750.
<details>
</details>
=> wal-g: Write out a logfile.

web/src/compose_actions.js, web/src/compose_recipient.js, web/src/tippyjs.js, web/styles/compose.css, web/styles/dark_theme.css, web/tests/compose.test.js, web/tests/compose_actions.test.js, web/tests/composebox_typeahead.test.js
- First commit is to show all accessible streams, including the ones to which user cannot post, in the dropdown.
- Second commit is to show the banner on opening compose box or changing the stream, if user is not allowed to post.
Fixes:  #25219 
<details>
</details>
=> Improve compose box behavior when user does not have permission to post in a stream.

web/shared/src/typeahead.ts, web/src/typeahead_helper.js, web/tests/composebox_typeahead.test.js
We refactor the triage function to optionally take in a comparator function, and use this to sort the results, except any exact match, which is placed highest. Now we don't need to sort the results of triage for streams, languages and slash commands since we just pass in the comparator function. The overall effect is same as before, except that exact matches are always shown first.
For users, since those are sorted in a complex way, we just find any exact matches and place them at the top of the list post all the sorting.
Fixes: #25123.
Normal order according to activity when there's no exact match:
In case of exact match, even an unsubscribed stream comes up 1st (user is not subscribed to #support):
<details> …
=> typeahead: Always show exact matches first for streams and users.

help/add-a-custom-linkifier.md
- Structure page around linkifier use cases.
- Add documentation (with examples) for advanced lnkifier types.
- Put examples in to tabs blocks.
This PR replaces #25317.
Notes:
- The `\` in `{\#var}` needs to be removed from the user-visible output, but we need to fix the fact that `{#var}` was breaking the page.
https://zulip.com/help/add-a-custom-linkifier (latest version in `main` is not currently deployed)
<details>
<summary>Screenshots (updated page)</summary>
<details>
=> help: Improve /help/add-a-custom-linkifier page.

corporate/lib/stripe.py
Python evaluates default values once when the function is defined, not when it is called.
(I haven’t attempted to evaluate the consequences of this bug. It’s probably minimal since this is currently invoked only in management commands?)
=> stripe: Fix invoice_plans_as_needed default value

zerver/tests/test_auth_backends.py, zerver/tests/test_signup.py, zerver/views/auth.py, zerver/views/registration.py
Entering an organization via `accounts/go` with web-public stream enabled
takes the user to the web-public view even if the user is not logged in.
Now, a user is always redirected to `login_page` with the next parameter.
`login_page` view is updated to redirect an authenticated user based on
the `next` parameter, instead of always redirecting to `realm.uri`.
Minor updates in a few test cases to align with the changes.
Fixes: #23344
**Help and Questions**
1. On [this line](https://github.com/zulip/zulip/pull/23362/files#diff-940c870652d79870a457600e9cde59f74a5b9980268c9df6e62e0c0d846b7e66R6182), do we need to clean the url `http://zephyr.testserver/login/?next=` i.e omitting the next parameter if next is empty or is it fine?
2. For more thorough testing, I need a help which I have [asked …
=> realm_redirect: Redirect always to the login page with the next parameter.

web/src/tippyjs.js
By default, tippyjs uses a trigger value of 'mouseenter focus', which means that the tooltips can appear either when the element is hovered over or when it receives focus (e.g., by being clicked). Because of this, if you click on the button to open the popover, the tooltip also appears. To prevent this behavior, we need to remove the 'focus' trigger from the buttons so that the tooltips don't appear when the buttons are clicked.
-------------------------------------------------
Fixes: #25277
CZO: [Thread](https://chat.zulip.org/#narrow/stream/6-frontend/topic/tooltip.20opens.20on.20click)
-----------------------------------
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> tippy: Remove the focus trigger from the compose-control-buttons.

templates/zerver/app/index.html, web/src/tippyjs.js, web/templates/gear_menu.hbs, web/templates/left_sidebar.hbs, web/templates/me_message.hbs, web/templates/message_avatar.hbs, web/templates/message_body.hbs, web/templates/message_view_header.hbs, web/templates/navbar.hbs, web/templates/stream_settings/stream_settings.hbs, web/templates/stream_settings/stream_settings_overlay.hbs, web/templates/tooltip_templates.hbs
use a modern tippy tooltip style for remaining tooltip elements advertising a keyboard shortcut.
Fixes: 
#24311
- Gear Menu:
- with fallback placement:
- Dark there:
- User List:
- Search_open icon:
- Search_close_button:
- Search_query input field:
- on fallback placement:
- Search_close icon:
- Manage stream settings: 
- create new stream button: 
- Toggle subscription:
- View stream:
- Message Expander/condenser:
- View user card:
- Correction of hotkey for `All direct messages` tooltip:
<details> …
=> tooltips: use tippy tooltips for elements advertising a keyboard shortcut.

web/src/scheduled_messages.js
"pm-with" was deprecated in #25003. This addition for scheduled messages must have gotten missed in the overlap of that change.
---
<details>
</details>
=> narrow: Fix "pm-with" narrow in scheduled messages.

web/src/dark_theme.ts, web/src/ui_init.js
Since, we didn't update `user_settings.color_scheme` for spectators and our recipient bar color calculations were based on it, this resulted in a wrong recipient bar color if the OS default color scheme of the user was different from `spectator-theme-preference` set by the user using the gear menu.
To reproduce the bug:
* Set preferred color scheme to `dark` in your OS settings / Chrome dev tools.
* Login as spectator in Incognito.
* Switch to light theme.
You will see dark background colors in recipient bars.
before:
after:
=> dark_theme: Fix dark recipient background in light theme for spectators.

web/styles/compose.css, web/templates/compose.hbs
This pull request:
* Changes the upward chevron to a vertical ellipsis, and repads/positions for fit with 9px of horizontal padding.
* Introduces 12px of horizontal padding around the Send button for clicking comfort, thanks to a larger target area.
* Changes the border separating the Send and vertical ellipsis buttons to be very light, almost white (pure white looked a little garish).
Note that I have used the same vertical-ellipsis icon behind `.zulip-icon-ellipsis-v-solid`, which is used in the sidebars.
Finally, although I was seeing some problems with button placement in the gutter on CZO, in development there was no such issue. It would be helpful if others could verify this at a 768px-width breakpoint. (The screenshots below were taken at 768px.)
Fixes: #25303. …
=> compose: Visual send button tweaks

web/src/message_list_view.js, web/src/recent_topics_ui.js, web/styles/zulip.css
This is a more natural place for this extra padding than below the navbar. Padding below navbar was primarily needed to hide the message content above the sticky header while scrolling the message feed. We are still able to do with this change without partially hiding the loading message indicator.
Fixes #25159
discussion: https://chat.zulip.org/#narrow/stream/137-feedback/topic/zulip.20logo.20cut.20by.20navbar.20margin
before: 
after:
Above should be the only visual change expected after this PR.
=> css: Move `10px` navbar bottom padding above message header.

web/e2e-tests/compose.test.ts, web/templates/edited_notice.hbs, web/templates/recipient_row.hbs
Comment: https://github.com/zulip/zulip/pull/25047#issuecomment-1526814834
Fixes: 
Recipient row:
Edit Notice:
<details>
</details>
=> tooltips: Convert recipient row and edit notice tooltips to tippy. 

web/styles/popovers.css
CZ) Discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/message-info-popover.20has.20opaque.20background
Previously, in the dark theme, the `background-color: #18222f` of the `.popover` class took precedence over the
`background-color: hsla(0,0%,0%,.7)` of the `.message-info-popover` and `.user-info-popover` classes. This commit fixes this issue by adding !important to the background-color property of `.message-info-popover, .user-info-popover` classes.
Fixes: 
- Before: 
- After:
- Message Info popover:
- User Info popover:
<details> …
=> user_card: Fix user_card background for dark theme on device width < $md_min.

web/src/popover_menus.js, web/styles/dark_theme.css, web/styles/popovers.css, web/templates/send_later_modal.hbs, web/templates/send_later_popover.hbs
This PR picks up from @amanagr's #25261:
The commits I have added to Aman's work address all of [Alya's feedback](https://github.com/zulip/zulip/pull/25261#issuecomment-1522062860), I believe, minus one point (the banner indications; more on that in a moment). Specifically:
* This removes "Now" from the popover menu once a message has been scheduled
* This adds "Cancel scheduling" to the popover menu insetad
* This adds "Custom time" as the last-listed option in the scheduling modal, which now opens the time widget
* This removes the former `send_later_input_group` structures, including the read-only `<input>` element that a) triggered opening the time widget and b) displayed the selected time
There are ~~three~~ two remaining issues here:
* The minor issue is that while clicking the …
=> send_later: Move some options to a modal (continued)

web/src/pm_list_data.js, web/src/recent_topics_ui.js, web/styles/left_sidebar.css, web/styles/popovers.css, web/styles/recent_topics.css, web/templates/pm_list_item.hbs, web/templates/recent_topic_row.hbs, web/templates/user_profile_modal.hbs, web/tests/pm_list_data.test.js
--------------------------------------------
Fixes: #25066 
CZO: [Thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/Visual.20indicator.20discrepancy/near/1539650)
-------------------------------
| Before: | After: |
|------------|----------|
| ![Screenshot from 2023-04-11 18-30-09](https://user-images.githubusercontent.com/66828942/231173369-802912ec-703b-4762-861c-d4c4131c6d8f.png) | ![Screenshot from 2023-04-11 22-47-07](https://user-images.githubusercontent.com/66828942/231244271-c8aa0cc8-2c3d-425b-a25a-c2aa5cd2e235.png) |
| ![Screenshot from 2023-04-18 04-46-35](https://user-images.githubusercontent.com/66828942/232630595-b5835d4f-9ecc-4afc-9224-ee8e15a05e78.png) |![Screenshot from 2023-04-18 …
=> bots: Replace / remove the display presence dot for bots with the zulip-bot icon.

web/src/popover_menus_data.js
This PR hides the "Add emoji reaction" from the message action menu while a user is not logged in, that is when the user is in public access mode.
Fixes: #25331
| ![Screenshot 2023-04-29 080552](https://user-images.githubusercontent.com/84276404/235279777-11f72baa-2cf1-4cac-96f6-ec0d251aec49.png) | ![Screenshot 2023-04-29 080504](https://user-images.githubusercontent.com/84276404/235279784-1331d1ef-3bdc-4a8e-9bf3-13dc98b54c35.png) | 
<details> …
=> actions_popover: Hide "Add emoji reaction" in action menu in spectator mode.

web/styles/zulip.css
=> css: Fix loading spinner position for messages loading indicator.

web/templates/scheduled_message.hbs
This PR removes the keyboard shortcut from tooltips that can be seen when hovering over the two buttons in
`View Scheduled Messages` modal.
This is a temporary change as the keyboard shortcut will be added to the tooltips when the shortcuts are actually working.
<hr>
| Before| After |
|![image](https://user-images.githubusercontent.com/35286603/235308471-0d6703d3-49b9-45f9-ac3c-8fbb69b46f35.png)|![image](https://user-images.githubusercontent.com/35286603/235308434-92c8cff0-21ab-4cee-b754-80af11038147.png)|
| Before| After |
|![image](https://user-images.githubusercontent.com/35286603/235308476-dab8c5ba-0b27-4054-99ea-98e119986e49.png)| ![image](https://user-images.githubusercontent.com/35286603/235308452-76f9f18b- …
=> tooltips: Remove keyboard shortcuts from "View Scheduled Messages" modal.

web/src/dialog_widget.ts, web/src/settings_account.js
Add an optional dialog_widget parameter that takes a boolean value. If set to true, it activates the "Confirm" button on a state change of any input field in the modal and also disables it again if the input field value is changed back to the original value.
Implementation: Store all the originalValues of input fields in the modal once it is rendered and add an event listener to all the input fields that listen for input and check if the new value is different from the original value. It activates the "Confirm" button if the new value is different, and makes it disabled if it is the same.
In this PR, I have only used the new option for the email change modal. I will soon create an Issue as a follow-up to this PR, that will use it everywhere else, such as the bot edit modal and move topic …
=> dialog_widget: Add optional parameter `update_submit_on_state_change`.

web/src/message_list.js, web/src/message_list_view.js, web/src/tippyjs.js
---------------------------------------------
Fixes: [CZO Thread](https://chat.zulip.org/#narrow/stream/6-frontend/topic/tippy.20sticking.20around)
------------------------------------------------
**Reference**: https://github.com/atomiks/tippyjs/issues/745#issuecomment-607531942
---------------------------------
<details>
</details>
=> tippy: Support globalStore plugin for tooltips.

templates/zerver/emails/email.css, templates/zerver/emails/email_base_default.html, templates/zerver/emails/email_base_marketing.html
During the Premailer migration, font sizes increased in emails based on the `email_base_messages` template. This PR narrows the CSS selector to apply styles only to the `body` tag with the `default-email-font-settings` class, rather than the entire `body` tag. This ensures that the styles are only applied to the intended emails.
=> emails: Fix body tag styles being applied in messages template.

zerver/actions/invites.py, zerver/actions/realm_settings.py, zerver/context_processors.py, zerver/views/registration.py
In commit fc58c35c0, we added a check in various emails for the `settings.CORPORATE_ENABLED` value, but that context is only always included for views/templates with a request (`zulip_default_context`).
The check was added to adjust the text for the "contact us" line in various emails based on whether the organization is on Zulip Cloud or a self-hosted server.
Here we add that to `common_context`, which is often used when there is not a request (like with emails). And we manually add it to the email context in various cases when there is not a user account to call with `common_context`: new user invitations, registration emails, and realm reactivation emails.
```
$ git grep corporate_enabled templates/zerver/emails
templates/zerver/emails/confirm_registration.html:    {% if …
```
=> emails: Add "corporate_enabled" to context for emails.

web/src/compose_banner.ts
This PR addresses an issue where buttons on error containers were not clickable due to error banners being incorrectly appended to the DOM. To resolve this, I have utilized the `append_compose_banner_to_banner_list` function to properly append error banners to the appropriate DOM element. This change ensures that error banners appear in the correct container, allowing buttons to be clickable.
=> compose: Fix buttons in error banners is not clickable.

web/styles/zulip.css
When there was an unread message below date row, the date row overlaps with the message header.
This was a result of #23538 not adjusting the message header z-index along with the z-index of date row.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/date.20seperator.20cuts.20off.20topic.20header
before: 
after:
=> css: Fix date row overlapping with message header.

zerver/actions/create_user.py, zerver/lib/onboarding.py, zerver/management/commands/send_welcome_bot_message.py, zerver/tests/test_signup.py
Because education organizations and users have slightly specialized use cases, we update the Welcome Bot message content sent to new users and new organization admins for these types of organizations to link to help center articles/guides geared toward these users and organizations.
Also, updates the demo organization warning to only go to the new demo organization owner because the 30 day deletion text is only definitely accurate when the organization is created. If we want that warning sent to all users for demo organizations, then we should update the message to either not have the number of days until deletion or accurately format the string for the number of days left (like we do the warning banner at the top of the web app).
Fixes #21694.
--- …
=> onboarding: Specialize Welcome Bot message for education organizations.

help/keyboard-shortcuts.md, web/src/deprecated_feature_notice.js, web/src/hotkey.js, web/templates/keyboard_shortcuts.hbs, web/tests/hotkey.test.js
Earlier, the `s` hotkey just narrowed to the stream of the selected message (to a topic), while `shift+s` narrowed to the conversation view (topic / pm) of the selected message.
Now, the `shift+s` hotkey has been removed (but retained for toggling subscription to a stream when the stream overlay is active), and the `s` hotkey takes on double duty: if the current view is not topic / pm, it narrows to that, else when in topic view, it switches to stream view. It has no effect when in pm view. Documentation has been updated for this both in the help center, and the in-app `Keyboard shortcuts` menu.
Fixes: #24226.
<details> …
=> hotkey: Repurpose `s` to toggle conversation view and remove `shift+S`.

web/src/topic_list.js, web/src/topic_list_data.js, web/styles/left_sidebar.css, web/templates/more_topics.hbs, web/tests/topic_list_data.test.js
When all the unread messages in a muted stream are in specifically muted topics, this ensures that the total unread count for the stream that the user sees before clicking "more topics" will match the total unreads number for the stream itself.
This behavior is limited to muted streams, since in a normal / not muted stream, we don't display a "muted topics only" faded unread count by the stream's summary line to avoid distracting the user with it, we match that behavior for the "more topics" line.
We also now display the `@` , again to ensure the stream's summary line never displays an `@` without some topic row having one.
Fixes: 
<details> …
=> topic_list: Show muted unread counts in muted streams.

web/src/composebox_typeahead.js, web/src/zcommand.js, web/tests/composebox_typeahead.test.js
This commit removes `/fixed-width` and `/fluid-width` slash commands from the typeahead and also hides the slash commands `/light` and `/dark` in production.
Fixes #25374.
<details>
</details>
=> typeahead: Delete display mode slash commands.

web/src/billing/upgrade.js, web/src/dialog_widget.ts, web/src/invite.js, web/src/portico/integrations_dev_panel.js, web/src/portico/signup.js, web/src/settings_bots.js, web/src/stream_create.js
[`:input`](https://api.jquery.com/input-selector/), [`:checkbox`](https://api.jquery.com/checkbox-selector/), [`:radio`](https://api.jquery.com/radio-selector/), and [`:selected`](https://api.jquery.com/selected-selector/) are jQuery-specific selector extensions that prevent jQuery from using native `querySelectorAll` and force it into the Sizzle slow path. These are easy to avoid; do so.
[`:animated`](https://api.jquery.com/animated-selector/), [`:visible`](https://api.jquery.com/visible-selector/), and [`:hidden`](https://api.jquery.com/hidden-selector/) have the same problem, but will need some more use-specific attention.
https://chat.zulip.org/#narrow/stream/6-frontend/topic/clean_user_content_links.20perf/near/1559809
=> web: Avoid slow jQuery `:input`, `:checkbox`, `:radio`, `:selected` selectors

web/src/compose.js, web/src/compose_actions.js, web/src/compose_banner.ts, web/src/compose_ui.js, web/src/composebox_typeahead.js, web/src/popover_menus.js, web/src/scheduled_messages.js, web/src/scheduled_messages_overlay_ui.js, web/src/server_events_dispatch.js, web/src/tippyjs.js, web/src/ui_init.js, web/styles/compose.css, web/styles/dark_theme.css, web/styles/scheduled_messages.css, web/templates/compose.hbs, web/templates/compose_banner/success_message_scheduled_banner.hbs, web/templates/scheduled_message.hbs, web/templates/scheduled_messages_overlay.hbs, web/templates/send_later_modal.hbs, web/templates/send_later_popover.hbs, web/tests/dispatch.test.js, web/tests/lib/events.js
Fixes #25340
This means that we now schedule the message simply after selecting time if the message is valid.
Also, editing scheduled messages will now delete the scheduled message and open compose with scheduled message.
TODO:
=> schedule: Remove 'Schedule' state of compose box.

web/styles/compose.css, web/templates/compose.hbs
CZO: https://chat.zulip.org/#narrow/stream/101-design/topic/send-button.20separator
Added a div inside `#send_later` button with class separator-line, height 70%, width 1px, and `background-color: hsl(0deg 0% 100% / 65%)` to make it look like a line also made #send_later a flex with `align-items: center` so that separator line is vertically centered.
Fixes: 
- **Before:**
- **After:**
<details>
</details>
=> compose: Shorter the separator line between Send and 3-dot buttons.

tools/test-js-with-node, web/src/compose_recipient.js, web/tests/compose.test.js, web/tests/compose_actions.test.js, web/tests/compose_state.test.js, web/tests/composebox_typeahead.test.js, web/tests/drafts.test.js, web/tests/lib/compose.js
=> compose recipient: Move cursor to end of topic input after stream selection.

web/e2e-tests/compose.test.ts, web/src/tippyjs.js, web/templates/recipient_row.hbs, web/templates/tooltip_templates.hbs
CZO Discussion: https://chat.zulip.org/#narrow/stream/137-feedback/topic/title.20tips.20in.20recipient.20bar
Added hotkey hint to Narrow to stream/topic/DM tooltips by creating new tippy for `tippy-narrow-tooltip` with LONG_HOVER_DELAY which appends `S` hotkey to the existing tippy content set by data-tippy-content attribute on the element.
Using this approach instead of a `<template>` with
data-tooltip-template-id avoids issues with context, where `{display_recipient}/{topic}/{display_reply_to}` inside `<template>` would always show the same stream/topic name regardless of the actual stream/topic being hovered over.
Fixes: 
- **Before:** 
- **After:**
- 2-line tippy tooltip:
<details> …
=> tooltips: Add `S` hotkey hint to `narrow-to` tippy tooltips.

web/src/compose.js, web/src/compose_banner.ts, web/src/compose_recipient.js, web/src/compose_validate.js, web/src/composebox_typeahead.js, web/src/notifications.js, web/src/scheduled_messages.js, web/src/upload.js, web/src/zcommand.js, web/tests/compose_validate.test.js
This PR addresses an issue where banners intended for the edit form were appearing in the compose box. The fix involves updating the banner listeners element from `#compose_banners` to `body`. This change was necessary because the `#edit_form_banners` container did not exist during initialization, preventing listeners from being applied to it. Additionally, the `append_compose_banner_to_banner_list` function was refactored to accept the banner list container as a parameter, allowing for more flexibility in adding banners. 
Overall, this PR ensures that banners are properly displayed in the intended form and should improve user experience.
Fixes: #25230.
=> #25230: Fix banner display issue in message edit form.

web/src/scheduled_messages.js, web/src/server_events_dispatch.js, web/src/top_left_corner.js, web/src/ui_init.js, web/styles/left_sidebar.css, web/tests/dispatch.test.js, web/tests/top_left_corner.test.js
This PR adds a count to the "Scheduled messages" item in the lefthand sidebar.
Additionally, it hides the "Scheduled messages" item when the scheduled-message count is zero.
Fixes: #25101 
TODO:
<details>
</details>
=> scheduled_message: Update count in lefthand sidebar

web/src/hashchange.js, web/tests/hashchange.test.js
Fixes #24641
When the user clicks on a link which has `stopPropagation` and doesn't trigger `scroll`, then we don't hide any existing popovers if the element being clicked doesn't hide popovers explicitly.
To fix this, we hide all popovers on change in hash, which makes sense on its own given how we use hashes.
Bug reproducer:
1. Open a topic with few messages (1-3).
2. Copy URL
3. Open a different topic with few messages (1-3).
4. Click anywhere to open a user profile popover.
5. Go to the copied URL.
=> hashchange: Hide popovers on change in hash.

web/src/unread.js
Comment: https://github.com/zulip/zulip/pull/25103#issuecomment-1520652900
Deduplicated logic for calculating unread message counts and stream counts for subscribed streams by refactoring `get_counts` to use `get_stream_count` function for calculating unread message counts for each subscribed stream.
This is a follow-up PR for #25103.
Fixes: 
<details>
</details>
=> unread: Deduplicate the logic for adding up unread counts.

zerver/migrations/0436_realmauthenticationmethods.py
This was doing bulk_create in a loop for each realm, which is too slow on very large servers. Just do a single bulk_create with a reasonable batch_size at the end.
From my understanding this is already applied on Zulip Cloud, but might still be worth tweaking the code anyway, if only to  not leave a bad example of doing things inefficiently that someone might copy when writing a future migrations.
https://github.com/zulip/zulip/pull/25146#discussion_r1183171485
=> migrations: Fix performance of migration 0436.

web/src/popover_menus.js
In commit e89cbf0ac1fc5c34, the only use of this template variable was removed from `send_later_popover.hbs`.
<details>
</details>
=> scheduled-messages: Remove unused `send_later_custom` template variable.

web/src/unread.js
Private messages with mentions are included in unread_mentions_counter, but of course don't have a stream ID, so should be skipped when calculating which streams contain unread mentions.
This code has always been wrong, it put `undefined` in the set of stream IDs with unread mentions.
What changed recently is that in 98162b7a3a01ef97aed935908e43c42ebd950bb9, we started using the `stream_id` to do an additional lookup in the unmuted version of the function, and doing that lookup with `undefined` threw an exception.
Fixes: 
<details> …
=> unread: Fix exception handling mentions in private messages.

tools/i18n/sync-translations, tools/lib/provision_inner.py, tools/update-prod-static
We explicitly configure `LOCALE_PATHS`, so we can safely disable [this search](https://github.com/django/django/blob/4.1/django/core/management/commands/compilemessages.py#L92-L100
) of the entire tree for other `locale` directories.
=> provision: Disable compilemessages searching for locale directories

web/src/compose_closed_ui.js, web/src/hotkey.js, web/src/message_fetch.js, web/src/message_list.js, web/src/message_list_data.js, web/src/message_list_view.js, web/src/message_scroll.js, web/src/narrow.js, web/src/navigate.js, web/src/server_events.js, web/tests/compose_closed_ui.test.js, web/tests/hotkey.test.js, web/tests/narrow_activate.test.js, web/tests/narrow_local.test.js
The individual commit messages detail this, but I found a cluster of bugs all related to incorrect handling of the difference between _items and _all_items in message list data structures. I did pretty extensive manual testing, but I'll want this to have some bake time on chat.zulip.org before we release a beta containing it.
Fixes the complex muting-related issue reported in https://chat.zulip.org/#narrow/stream/101-design/topic/can't.20distinguish.20muted.20topics.20in.20muted.20streams/near/1559718, as well as several other bugs.
=> Fix buggy message list data structures handling of stream narrows

web/src/popover_menus.js, web/src/scheduled_messages.js, web/templates/send_later_modal.hbs, web/tests/scheduled_messages.test.js
On Fridays and Saturdays, users will be presented with the option to schedule a message to send on Monday at 9:00 am.
The logic I've written uses the `getDay()` method on JavaScript Date instances. I believe that that method returns `0` for Sunday, for example, regardless of a user's locale settings. But I wanted to raise a possible internationalization issue here.
Fixes: #25402.
Result, on Fridays and Saturdays:
<details>
</details>
=> scheduled_messages: Show Monday option on Fridays and Saturdays.

help/custom-emoji.md, help/include/sidebar_index.md, help/schedule-a-message.md, help/view-and-edit-your-message-drafts.md
Fixes #25407.
Notes:
- I put the page right after "Message drafts" in the "Sending messages" sidebar section.
Follow-ups:
1. I didn't deal with cross-linking related pages. @drrosa would be great if you could post a follow-up PR for this.
2. Can we offer links to "Drafts" and "Scheduled messages" for logged in users? If so, that's probably a good follow-up for @drrosa as well.
<details>
<summary>
Screenshots
</summary>
</details>
The `custom-emoji.md` change is trivial. For the drafts page, I think always numbering instruction steps (even if there's just one) looks better?
Current: https://zulip.com/help/view-and-edit-your-message-drafts
<details>
<summary>
Updated
</summary>
</details>
=> help:  Add "Schedule a message" help center page + minor tweaks.

web/src/narrow.js
Previously, we've been assuming that when a user narrows to a topic or recipient, that the target message would be marked as read in resulting view. This is no longer a safe assumption because a user can have their personal display settings to never mark messages as read, even in conversation views.
Removes the call to `unread_ops.notify_server_message_read` in both `narrow.by_topic` and `narrow.by_recipient` in the web app.
If the messages normally would be marked as read in the narrow based on the user's settings, they still will be once that narrow view is loaded, see second set of screencasts below.
<details>
<summary>Before changes - user has marked never mark as read on scroll</summary>
[Screencast from 03-05-23 …
=> narrow: Do not mark as read when narrowing by topic or recipient.

web/src/channel.js, web/src/message_edit.js, web/templates/message_edit_form.hbs, web/tests/channel.test.js
This PR aims to update the old-style custom error banners in the message edit form to the ones we are currently using. It also fixes the placement of the banners.
Fixes: #25412.
=> message_edit: Update placement and styling of server message edit banners.

web/src/popover_menus.js, web/src/scheduled_messages.js, web/templates/send_later_modal.hbs, web/tests/scheduled_messages.test.js
This commit ensures that user-locale and 24-hour preferences are respected in the message-scheduling modal. It also simplifies the translation of text strings in the scheduling modal.
Available scheduling options and their time values, including whether the options are allowed, are now calculated every time a user opens the scheduling modal.
In order to achieve those things, additional interrelated fixes here accomplish the following:
1. Modal-scheduling opts now have data- attributes containing timestamps for the time a message will be scheduled to send.
2. With those timestamps in place, the logic for setting the scheduled send-time is simplified.
3. There are no more `send_later_xxx` global variables in the `schedule_send` module.
Fixes #25403.
Screenshot showing proper display of …
=> scheduled_messages: Respect localization and user preferences.

web/tests/unread.test.js
This is a follow-up to #25428.
Comment: https://github.com/zulip/zulip/pull/25428#issuecomment-1533644005
In the "mentions" test, an additional unread message with the type "private" and directly mentioning me has been added. This test case checks for the scenario when the stream_id is null during the reverse_lookup, which would have caused the test to fail before the bug fix was implemented which now passes after the fix is applied.
Fixes: 
<details>
Completed …
=> node_tests: Extend unread.test.js to catch private message mentions bug.

web/src/tippyjs.js
I noticed a floating "Go to direct message ..." on chat.zulip.org, and then found out that these don't use message_list_tooltip.
I am not able to reproduce, but this change makes sense on its own.
=> tippyjs: Hide recipient bar tooltips on msg_list rerender.

web/src/popover_menus.js
Previously, the option texts were split into 2 lines due to the lack of space in the message menu. We want to fix this by increasing the max-width of the menu so it can support the entire text in 1 line while also providing additional space for longer text.
Since, 320px is the maximum supported supported width for mobile, we will allow the max-width value to flex from 320px to 350px depending on the window_width
Before:
After:
<details> …
=> popover: Allow message actions menu to support larger max-width.

web/src/popover_menus.js, web/src/scheduled_messages.js, web/tests/scheduled_messages.test.js
This introduces a function that checks for both the existence and the expiration of the `selected_send_later_timestamp`.
The logic it supports prevents users from scheduling a message to send in the past, at least the level of the UI: the popover on the \vdots component of the Send button.
**One question:** Would it make sense to look for a difference of 30 seconds or a minute to decide whether the scheduled time has expired? Currently the function checks only for a non-negative (greater than 0) difference between the timestamps for the scheduled send time and now.
I could imagine a potential corner-case where a user schedules a message just seconds before the send time is in the past, especially given browser or network latency, etc., or just having a user interrupted while opening the …
=> scheduled_messages: Don't offer to reschedule in the past.

help/marking-messages-as-read.md, web/src/message_list.js, web/templates/settings/display_settings.hbs
Previously, the user setting "Mark messages as read on scroll" sounded quite awkward and possibly confusing at times. We should update the text to something more clear and concise. This change will change "Mark messages as read on scroll" to "Automatically mark messages as read".
<details>
</details>
=> user_setting: Update wording for "Mark messages as read on scroll"

zerver/lib/scheduled_messages.py, zerver/models.py
Updates:
- `DirectScheduledMessageAPI` -> `APIScheduledDirectMessageDict`
- `StreamScheduledMessageAPI` -> `APIScheduledStreamMessageDict`
See [this CZO conversation](https://chat.zulip.org/#narrow/stream/3-backend/topic/scheduled.20message.20API.20dicts/near/1560746) and [this PR comment](https://github.com/zulip/zulip/pull/25318#discussion_r1180705325) for more context.
---
<details>
</details>
=> models: Update the references for API dicts for scheduled messages.

web/templates/compose.hbs, web/templates/compose_control_buttons.hbs, web/templates/draft.hbs, web/templates/gear_menu.hbs, web/templates/left_sidebar.hbs, web/templates/message_body.hbs, web/templates/message_controls.hbs, web/templates/message_view_header.hbs, web/templates/navbar.hbs, web/templates/recipient_row.hbs, web/templates/right_sidebar.hbs, web/templates/scheduled_message.hbs, web/templates/stream_settings/stream_settings.hbs, web/templates/stream_settings/stream_settings_overlay.hbs, web/templates/tooltip_templates.hbs
Refactored all tooltip templates with static content to be in `tooltip_templates.hbs` to avoid duplicate IDs and DOM elements.
Almost all the tooltip templates have static content, shifted them all to `tooltip_templates.hbs` except the `recent_topics_participant_overflow_tooltip` template from recent_topic_row.hbs which had dynamic content.
Fixes #25324
Fixes: 
<details>
</details>
=> tooltips: Shift all tooltip templates to tooltip_templates.hbs.

zerver/actions/scheduled_messages.py, zerver/openapi/zulip.yaml, zerver/tests/test_scheduled_messages.py, zerver/views/scheduled_messages.py
For scheduled stream messages, we already limited the `to` parameter to be the stream ID, but now we return a `JsonableError` in the case of a `ValueError` when the passed value is not an integer.
For scheduled direct messages, we limit the list for the `to` parameter to be user IDs. Previously, we accepted emails like we do when sending messages.
See [this CZO conversation](https://chat.zulip.org/#narrow/stream/378-api-design/topic/scheduled.20messages/near/1560744) for more context.
**Notes**:
- I added a `JsonableError` for the case where a client sends a stream name instead of the stream ID. The message string is slightly different from the one in the send message path:
- "Invalid data type for stream ID" instead of "Invalid data type for stream".
- If the distinction of "ID" isn't …
=> scheduled-messages: Limit `to` parameter to user and stream IDs.

web/styles/zulip.css, web/templates/draft.hbs, web/templates/recipient_row.hbs, web/templates/scheduled_message.hbs
Fixes: 
#25353 
- **Before:**
- **After:**
- Topic Name in Drafts and scheduled message overlays:
- DM recipient names in message headers:
<details>
</details>
=> message_headers: Consistently abbreviate recipient name/topic name.

web/src/stream_popover.js, web/styles/popovers.css, web/styles/zulip.css, web/templates/move_topic_to_stream.hbs, web/templates/topic_edit_form.hbs
In move_topic modal, Renamed inline_topic_edit to move_messages_edit_topic to be more specific selector as inline_topic_edit is also used in message header.
If user has permissions to move the message(s) to a different stream and can't edit topic name then focus stream input; else, focus topic input on "Move messages" and "Move topic" modals render by `ui_util.place_caret_at_end($(".move_messages_edit_topic")[0])` to position the cursor at end on focus.
Fixes: #24805
https://user-images.githubusercontent.com/64723994/227015227-8809e01d-6264-4d93-b0c9-f828bbea3092.mp4
<details> …
=> Focus topic input in "Move messages" and "Move topic" modals.

web/src/compose.js, web/src/compose_actions.js, web/src/compose_banner.ts, web/src/compose_validate.js, web/src/message_edit.js, web/src/message_store.js, web/tests/compose_validate.test.js, web/tests/lib/compose_banner.js, web/tests/message_events.test.js, web/tests/message_store.test.js
This PR is intended to implement client-side checking of wildcard mentions in message edit mode, while preserving the existing behavior from the compose box. The main changes made to accomplish the goal is:
1. Added a `$banner_container` parameter to certain functions, such as `show_wildcard_warnings` in the `compose_validate` module. This allows for their reuse in both the compose box and edit context.
2. Significantly changed the way wildcard banners are tracked. The system has become more complex, as we now need to track banners not only for the compose box but also for multiple edit inputs. The system now checks if the banner has been displayed for each input. If the banner has already been shown, we skip displaying it, return true for validation, and proceed with the API request.
3. …
=> compose: Add wildcard mentions check on client side.

web/src/overlays.ts, web/src/popover_menus.js, web/src/user_profile.js
This will be used to avoid this code syntax:
```
if (overlays.is_modal_open()) {
overlays.close_modal("send_later_modal");
}
```
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/overlays.2Eclose_modal_if_open
=> overlays: Add method to check if the correct modal is open.

web/src/scheduled_messages.js
Fixes #25441
`remove` event is triggered when scheduled message is sent and when the scheduled message is removed, so this will remove success banner in both cases.
=> scheduled_message: Hide success compose banner on `remove` event.

scripts/lib/install-node, tools/setup/install-shellcheck, tools/setup/install-shfmt, tools/setup/install-transifex-cli
This makes it clearer which step failed if there’s an error.
Output when successfully installing all four of these:
```console
$ tools/provision 
No changes to apt dependencies, so skipping apt operations.
+ sudo -H -- env http_proxy= https_proxy= no_proxy= scripts/lib/install-node
++ mktemp -d
+ tmpdir=/tmp/tmp.cMCgAPGGmc
+ trap 'rm -r "$tmpdir"' EXIT
+ cd /tmp/tmp.cMCgAPGGmc
+ curl_opts=(-fLO --retry 3)
+ '[' -n '' ']'
+ curl -fLO --retry 3 https://nodejs.org/dist/v18.16.0/node-v18.16.0-linux-x64.tar.xz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 22.6M  100 22.6M    0     0  36.8M      0 --:--:-- --:--:-- --:--:-- 36.8M
+ sha256sum -c
node-v18.16.0-linux-x64.tar.xz: OK
+ rm -rf /srv/zulip-node
+ mkdir -p …
```
=> install: Use set -x when installing node, shellcheck, shfmt, tx

templates/corporate/billing.html, templates/corporate/event_status.html, templates/corporate/upgrade.html
These classes seem to have been copy-pasted from other portico pages when styling was first done in
122dcc9760d375816cb4664c41db7a340dd942cf. With the current styles, which are just a handful of rules not scoped to a specific page, it just makes the billing pages look broken.
Without this change, there's a weird white stripe at the top of the screen: 
With this change:
=> billing: Remove unintended portico-landing classes.

docs/production/deployment.md, docs/production/postgresql.md, docs/production/upgrade.md, puppet/zulip/manifests/profile/postgresql.pp, puppet/zulip/templates/postgresql/zulip.conf.template.erb, scripts/lib/install, scripts/setup/upgrade-postgresql
Instead of copying over a mostly-unchanged `postgresql.conf`, we transition to deploying a `conf.d/zulip.conf` which contains the only material changes we made to the file, which were previously appended to the end.
While shipping separate while `postgresql.conf` files for each supported version is useful if there is large variety in supported options between versions, there is not no such variation at current, and the burden of overriding the entire default configuration is that it must be keep up to date wit the package's version.
<details> …
=> puppet: Add PostgreSQL 15 support.

web/src/message_edit.js
hotkey.js is the file that handles the 'e' keyboard shortcut. It maps to the 'edit_message' event and will simply call message_edit.start().
message_edit.start() doesn't check whether it's already been opened previously, so it will go through and try to register handler for the clipboard button again. When the clipboard button gets clicked, the handler will be called twice. Once with a properly target element, and once with null.
Fixing this issue by checking if message_edit.start() has already operated on the given $row.
Fixes: #25462
<details> …
=> message_edit: Avoid registering duplicate events

web/src/popover_menus.js, web/src/scheduled_messages.js, web/templates/send_later_modal.hbs, web/templates/send_later_modal_options.hbs, web/tests/scheduled_messages.test.js
This PR introduces two changes. 
Firstly, it extracts the send later options to a separate template, allowing for the rendering of options for the send-later modal separately. This is necessary to ensure that the user can keep the modal open and still have access to actual sending options.
Secondly, it ensures that the send later options are re-rendered at a specific time.
Fixes: #25451.
<details>
<summary>rerender at 15:55</summary>
<br>
</details>
<details>
<summary>rerender at 08:55</summary>
<br>
</details>
<details>
<summary>rerender at midnight</summary>
<br>
</details>
=> Rerender send later options at specific times.

web/src/compose.js, web/src/compose_banner.ts, web/src/compose_validate.js, web/src/message_edit.js, web/src/popover_menus.js, web/templates/compose_banner/compose_banner.hbs, web/tests/compose_validate.test.js
Before it was impossible to schedule a message if it had a wildcard @-mention because we were showing a warning banner and on clicking "Yes, send" the message was sent immediately.
Fixed this by doing:
Fixes: #25426 
<video src="https://user-images.githubusercontent.com/84276404/236234896-2c5a9a4e-f0c3-4bc4-8454-523311936d12.webm">
<details>
</details>
=> compose: Make it possible to schedule messages with wildcard mention confirmation.

web/src/narrow_banner.js, web/tests/narrow.test.js
Previously, when a user enters a empty dm-including view, they'll notice the "Why not start the conversation" action line and click on the link. When this happens, the compose box would open but the receipent box is never populated.
Since the dm-including view is a search view, we should drop that phrase from dm-including views altogether. It also isn't super natural to have a button that starts the conversation with the user anyways.
Fixes: #25524.
<details> …
=> narrow_banner: Drop empty action line from empty `dm-including:` views.

tools/test-backend, zerver/tests/test_scheduled_messages.py
Adds test coverage for the error sent for editing a scheduled message that was successfully sent.
`zerver/actions/scheduled_messages.py` now has 100% test coverage again. Part of fixing #25498.
---
<details>
</details>
=> tests: Add coverage for error when editing a sent scheduled message.

web/styles/left_sidebar.css
This PR attempts to tweak the positioning of DM-box icons and the size of the Zulip-bot icon, which may appear too low relative to the text, and in the bot icon's case, too large relative to other icons.
While the screenshots below are from MacOS, [the original CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/alignment.20of.20DM.20icons) shows a greater existing discrepancy.
Before, 100% zoom (Firefox, MacOS)
After, 100% zoom (Firefox, MacOS)
Before, 110% zoom (Firefox, MacOS)
After, 110% zoom (Firefox, MacOS)
<details> …
=> left_sidebar: Adjust size and position of DM icons.

web/styles/portico/billing.css
This was hidden following #25518
Events
Billing and upgrade page:
=> billing: Making /upgrade page header visible.

web/styles/left_sidebar.css
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/highlighting.20with.20stream.20filter
before:
after:
=> left_sidebar: Don't change active stream color on filter highlight.

web/src/debug.ts
https://developer.mozilla.org/en-US/docs/Web/API/console#timers
=> debug: Remove print_elapsed_time in favor of console.time

web/styles/subscriptions.css, web/templates/stream_settings/stream_creation_form.hbs
CZO Discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/bug.20in.20create.20stream.20UI
This commit addresses `#stream-creation .modal-footer` becoming transparent after an error in creating a stream due to overlapping with `.stream-creation-body`. Instead of adding `data-simplebar` on `.stream-creation-body`, added it to a new div
`stream-creation-simplebar-container` which contains 3 divs:
`stream_create_info, stream_creating_indicator and stream-creation-body`.
This solved the issue as now the `stream_create_info` error banner won't shift down the simple bar container (which previously resulted in overlapping) since now  `stream_create_info` is now also part of the simple bar container.
Additionally, fixed the `border-radius` of the modal footer on the bottom left side for …
=> stream_settings: Fix bugs with `#stream-creation .modal-footer`.

web/styles/zulip.css
before: 
after:
Reproducer: This can happen at a random zoom level for you, or you can decrease the `left` position of `.unread_marker` to see it.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/unread.20marker.20spilling.20out
=> css: Fix unread marker leaking through message header.

web/src/recent_topics_ui.js
row_focus cannot be equal to `$topic_rows.length` since it follows 0 array indexing.
=> recent_conversation: Fix incorrect `if` condition.

scripts/lib/supervisor.py
If `zulip-puppet-apply` is run during an upgrade, it will immediately
try to re-`stop-server` before running migrations; if the last step in
the puppet application was to restart `supervisor`, it may not be
listening on its UNIX socket yet.  In such cases, `socket.connect()`
throws a `FileNotFoundError`:
```
File "./scripts/stop-server", line 53, in <module>
services = list_supervisor_processes(services, only_running=True)
File "./scripts/lib/supervisor.py", line 34, in list_supervisor_processes
processes = rpc().supervisor.getAllProcessInfo()
File "/usr/lib/python3.9/xmlrpc/client.py", line 1116, in __call__
return self.__send(self.__name, args)
File "/usr/lib/python3.9/xmlrpc/client.py", line 1456, in __request
response = self.__transport.request(
File …
```
=> Retry supervisor socket

zerver/actions/streams.py, zerver/tests/test_subs.py
=> streams: Prevent already-deactivated streams from being deactivated.

api_docs/changelog.md, version.py, zerver/actions/scheduled_messages.py, zerver/models.py, zerver/openapi/zulip.yaml, zerver/tests/test_scheduled_messages.py
Adds sending a message from Notification Bot to the user who scheduled the message if/when there is an error sending the message. The only errors that do not send these notification messages are when the realm or user sending the message has been deactivated.
Also, updates the API scheduled message dicts to have a `failed` field that will be `True` in the case that the server tried to send the scheduled message but there was an error. The same commit fixes two colons in the feature level 179 API changelog entry as well.
This is part of work on #25501. After these changes, the remaining task in that issue is to update the scheduled messages overlay and UI for the new icon.
---
<details>
<summary>Example of Notification Bot message</summary>
</details> …
=> backend: Add failed scheduled message notification and update API dict for `failed` boolean.

web/templates/left_sidebar.hbs
Since tippy relies on the `blur` event of `target` to hide the toolips, it is important that the tooltip is triggered by the element that receives that focus in keyboard navigation which is `a` tag for left sidebar elements.
reproducer: [Issue replication](https://chat.zulip.org/user_uploads/2/be/z_eKJODeWzhezkLnPp5_hg5t/errors-Zulip-Dev-Zulip-Google-Chrome-2023-05-02-18-50-15.mp4)
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/more.20sticky.20tooltips
=> left_sidebar: Move tooltips to the `focus` element.

zerver/actions/message_send.py, zerver/actions/scheduled_messages.py, zerver/tests/test_scheduled_messages.py
The only reasonable intent for such a scheduled message is to remind
oneself of something at that time, which requires it being unread.
Fixes #25523.
=> message_send: Don't mark scheduled messages to self as read.

web/styles/compose.css, web/templates/compose.hbs
This PR changes the `select_recipient_widget` inside the compose section to use a `button` tag instead of `div`. This makes sure that when the user hovers over the select recipient button a hand pointer is shown instead of mouse/text pointer.
Fixes #25592.
<hr>
<details>
<summary> Before </summary>
</details>
<details>
<summary>  After </summary>
</details>
<hr>
<details>
</details>
=> select_recipient_widget: Use "button" tag instead of "div".

tools/test-js-with-node, web/src/drafts.js, web/src/hotkey.js, web/src/messages_overlay_ui.js, web/src/scheduled_messages_overlay_ui.js, web/styles/app_components.css, web/templates/tooltip_templates.hbs, web/tests/drafts.test.js, web/tests/hotkey.test.js
The main goal of this pull request is to make the keyboard navigation created for the drafts modal reusable, so we can use it in the scheduled messages modal as well.
The first commit refactors the keyboard functions in the `drafts.js` module for reusability, in preparation for implementing keyboard navigation in the message scheduling modal. The `modals_handle_events` function has been made reusable by extracting context-related variables and using a more neutral term "item" instead of "draft". The function also now accepts a `context` parameter to work in different modal contexts. 
The second commit adds keyboard navigation to the scheduled messages modal using the `modals_handle_events` function from the `drafts.js` module, along with some helpful functions from the same module. …
=> scheduled_messages: Add keyboard navigation.

web/src/hotkey.js, web/src/list_util.ts, web/src/popover_menus.js, web/src/scheduled_messages.js, web/templates/send_later_modal_options.hbs, web/tests/hotkey.test.js
This PR aims to add keyboard navigation to the message scheduling modal. 
Fixes: #25404.
=> send_later: Add keyboard navigation to scheduling modal.

web/src/stream_settings_ui.js
Updates the left-over ID in a5580264eb00cc47bbec680f0a50bf974e7cabcb.
<details>
</details>
=> stream: change ID in selector to match updated one.

web/src/portico/help.js, web/styles/portico/portico.css
This PR aims to make the help documentation more user-friendly by highlighting links targeted by URL fragments. It also ensures that targeted headings are not obscured by the floating menu bar at the top of the help pages.
~~One caveat: While the approach here works fine when loading a new docs page whose URL includes a fragment, there appears to be something about `simplebar` that clears out the `:target` reference. If you click a heading link on a help page, for example, you might momentarily see the highlighted style appear before it disappears.~~ Highlighting is also available for on-page targets of URL fragments.
See [CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/help.20page.20highlighting).
Highlighted and properly …
=> help_pages: Highlight headings targeted by URL fragments.

tools/i18n/sync-translations, tools/lib/provision_inner.py, tools/update-prod-static
=> [6.x] provision: Disable compilemessages searching for locale directories

web/styles/dark_theme.css, web/styles/zulip.css, web/templates/unread_banner/mark_as_read_disabled_banner.hbs, web/templates/unread_banner/mark_as_read_only_in_conversation_view.hbs, web/templates/unread_banner/mark_as_read_turned_off_banner.hbs
In https://github.com/zulip/zulip/issues/22524, we have updated the compose banner to the new, updated design
while the unread banners have remained the same. When comparing them side
by side, they look rather old and outdated. We should apply the updated
design to the unread banners as well.
Fixes: https://github.com/zulip/zulip/issues/25551.
<details>
<summary>Warning banner</summary>
</details>
<details>
<summary>Info banner</summary>
</details>
<details> …
=> unread_banner: Apply updated design to message feed banners. 

help/getting-started-with-zulip.md, help/include/send-group-dm.md, help/include/sidebar_index.md, help/include/starting-a-new-direct-message.md, help/messaging-tips.md, help/open-the-compose-box.md, help/replying-to-messages.md, help/starting-a-new-direct-message.md, help/starting-a-new-topic.md, zerver/lib/url_redirects.py
With the private messages -> direct messages migration, we should rename the "[Starting a new private thread](https://zulip.com/help/starting-a-new-private-thread)" help center article.
- Renames article to "Starting a new direct message"
- Updates relevant section in [/help/getting-started-with-zulip](https://zulip.com/help/getting-started-with-zulip#starting-a-new-private-thread)
- Fixes typo in /help/send-group-dm
- Updates file names and adds URL redirect.
Fixes #25506.
<details> …
=> help: Rename "Starting a new private thread" to "... new direct message".

help/include/mute-unmute-intro.md, help/mute-a-topic.md
- Create separate sections for muted vs. unmuted streams.
- Combine instructions for muting/unmuting topics.
Feedback is appreciated on the difference between mobile instructions for unmuted vs. muted streams. I kept the more detailed instructions for muted streams that were suggested in #25591, because topics in muted streams are harder to find than in unmuted streams.
Fixes https://github.com/zulip/zulip/issues/25311.
Current page: https://zulip.com/help/mute-a-topic
The intro changes also affect https://zulip.com/help/mute-a-stream.
<details>
Desktop/web:
Mobile:
</details>
=> help: Restructure /help/mute-a-topic.

zerver/lib/outgoing_webhook.py
The use of the setting was accidentally removed in b88d7a741e17, and replaced with a static 10 seconds.
<details>
</details>
=> outgoing_webhook: Respect settings.OUTGOING_WEBHOOK_TIMEOUT_SECONDS.

web/src/narrow_state.js, web/tests/narrow_state.test.js
This likely needs further refactoring to switch to using stream IDs rather than names in this code path, but this change fixes an exception that would be throw when opening the compose box while viewing a narrow to an invalid stream name/ID.
Fixes: 
<details>
</details>
=> compose: Fix opening compose box when viewing invalid stream.

web/src/popover_menus_data.js, web/templates/actions_popover_content.hbs
This pull request does two things:
1. Adds the `(:)` keyboard shortcut to the "Add emoji reaction" popover menu option.
2. Hides the "Add emoji reaction" menu item on the popover of other users' messages, as there is already a button to add an emoji on hover.
Fixes: #25602. 
<details>
<summary>Keyboard shortcut</summary>
</details>
<details>
<summary>Hide redundant "Add emoji reaction" menu item</summary>
_Own message_
_Another user's message_
</details>
<details> …
=> popovers: Improve "Add emoji reaction" three-dot menu option.

web/src/compose_actions.js, web/src/compose_recipient.js, web/src/tippyjs.js, web/tests/compose_actions.test.js, web/tests/stream_data.test.js
Prior this commit, changing the message type from a stream (where posting was not allowed) to a direct message using the compose box dropdown, did not changed the state of the submit button from disabled to enabled even though direct messages were allowed in the organization. Now, it checks if direct messages are allowed or not, and depending on that, it updates the send button's state, tooltip and displays a relevant banner.
<details> …
=> compose: Check posting policy for direct messages.

web/styles/zulip.css
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/no.20blue.20box.20on.20message.20menu
=> css: Allow `actions_hover` icon to have a focus outline.

analytics/tests/test_support_views.py, analytics/views/support.py, templates/analytics/support.html, web/src/analytics/support.ts
Mimics the implementation of "scrub realm" for /activity/support
Uses a double prompt popup to confirm both email and realm to avoid accidental deletion of a user in a different organization than supposed to :neutral_face: 
Video:
[Screencast from 2023-05-15 23-42-05.webm](https://github.com/zulip/zulip/assets/45007152/3adb8e6f-0d49-4bf6-8937-088ec450297e)
=> support: Add option to delete user from /activity/support.

web/src/compose_banner.ts, web/src/scheduled_messages.js
This pull request addresses the issue of notifying users via a compose banner when a scheduled message has been unscheduled. To implement this feature, a new function called `show_message_unscheduled_banner` has been added, which shows the warning banner. This banner will be displayed whenever a scheduled message is unscheduled, either by editing it from "Scheduled messages" or by clicking "Undo" on the scheduling confirmation banner.
Fixes: #25614.
<details>
</details>
=> scheduled_messages: Add banner for unscheduled message.

puppet/zulip_ops/files/apt/apt.conf.d/50unattended-upgrades
When upgraded, the `erlang-base` package automatically stops all services which depend on the Erlang runtime; for Zulip, this is the `rabbitmq-server` service.  This results in an unexpected outage of Zulip.
Block unattended upgrades of the `erlang-base` package.
<details>
</details>
=> puppet: Prevent unattended upgrades of erlang-base.

web/styles/modal.css, web/styles/portico/activity.css, web/styles/portico/billing.css, web/styles/portico/integrations_dev_panel.css, web/styles/portico/portico_signin.css, web/styles/settings.css, web/styles/zulip.css
The issue was extra padding on a fixed-height box.
Before:
After:
<details>
</details>
=> css: Fix dropdown text alignment centered.

web/src/message_edit.js, web/styles/zulip.css, web/templates/message_edit_form.hbs
The old code was disabling the save button wrong by using `.addClass("disabled")` instead of `prop()`.
Added tooltip for the disabled save button as per issue https://github.com/zulip/zulip/issues/25413.
The textbox readonly logic was changed to no longer becoming readonly. Reason being there are edge cases involving the compose buttons such that simply marking the textbox as readonly is not sufficient.
E.g. using the compose buttons after readonly still modifies the content.
One solution might be to just hide the compose buttons visually. However, there are edge cases for that too. If preview mode was previously active, then perhaps that state needs to be reverted. If any modal is open, such as the emoji picker, then that needs to be closed. Solving these edge cases doesn't improve the …
=> message_edit: Disable save btn after edit time limit

tools/test-js-with-node, web/src/confirm_dialog.ts, web/src/dialog_widget.ts
Converts `confirm_dialog` module to TypeScript. 
<details>
</details>
=> ts: Convert `confirm_dialog` module to TypeScript.

zerver/actions/scheduled_messages.py, zerver/openapi/zulip.yaml, zerver/tests/test_scheduled_messages.py
A few commits with some small clean ups I noted while working on #25628.
- Use "direct" instead of "private" in tests and comments.
- Simplify type for `message_to` since user emails can no longer be sent for direct message recipients.
- Add explicit test for sending user emails.
- Add link to help center article on scheduled messages for `GET` and `DELETE` endpoints now that we have one to link to.
<details>
</details>
=> scheduled-message: Update small errors and inconsitencies.

web/src/compose_state.js, web/src/compose_validate.js, web/src/hash_util.js, web/src/message_edit_history.js, web/src/rendered_markdown.js, web/src/scheduled_messages.js, web/src/scheduled_messages_overlay_ui.js, web/src/starred_messages_ui.js, web/src/stream_color.js, web/src/stream_data.js, web/src/stream_list_sort.js, web/src/stream_popover.js, web/src/sub_store.ts, web/src/user_topics.js, web/tests/stream_data.test.js
This PR moves `maybe_get_stream_name` function from `stream_data` to `sub_store` as it didn't have any dependency on `stream_data` and it also helps us to cut off dependency on `stream_data` for some of the modules including `user_topics`.
<details>
</details>
=> refactor: Move `maybe_get_stream_name` from `stream_data` to `sub_store`.

api_docs/changelog.md, zerver/openapi/zulip.yaml
Part of 7.0 API changelog audit; see [this CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/7.2E0.20API.20changelog.20audit/near/1571838) for more context.
Updates API changelog entry and related parts of API docs for: **Feature level 178**.
**Notes**:
- Updates the descriptions and examples for there only being two key values: "website" and "aggregated".
- Also, clarifies that email keys are the Zulip display email.
- And removes any descriptive text that says presence objects have information about the clients the user is logged into.
---
<details>
<summary>Updated API changelog feature level 178 entry</summary>
[Current documentation](https://zulip.com/api/changelog#changes-in-zulip-70)
</details>
<details> …
=> api-changelog: Update and clarify docs for feature level 178 entry.

help/add-or-remove-users-from-a-stream.md, help/configure-who-can-invite-to-streams.md, help/create-a-stream.md, help/include/sidebar_index.md, help/stream-permissions.md
- Renames [Restrict stream invitation](https://zulip.com/help/configure-who-can-invite-to-streams) page title.
- Renames section about "Who can add users to streams" setting.
- Adds new section "Configure who can remove users" from [help/add-or-remove-users-from-a-stream](https://zulip.com/help/add-or-remove-users-from-a-stream).
- Updates "Add others" in [help/stream-permissions](https://zulip.com/help/stream-permissions) tables.
- Consolidates all the references to permissions on https://zulip.com/help/add-or-remove-users-from-a-stream to an intro section about what's possible, with a link to the newly updated "Restrict stream membership management" page.
Fixes #25264.
<details> …
=> help: Update "Restrict stream invitation" page.

docs/production/deployment.md, puppet/zulip/manifests/supervisor.pp, puppet/zulip/templates/supervisor/supervisord.conf.erb
1c76036c61d8 raised the number of `minfds` in Supervisor from 40k to 1M.  If Supervisor cannot guarantee that number of available file descriptors, it will fail to start; `/etc/security/limits.conf` was hence adjusted upwards as well.  However, on some virtualized environments, including Proxmox LXC, setting
`/etc/security/limits.conf` may not be enough to raise the system-level limits.  This causes `supervisord` with the larger `minfds` to fail to start.
The limit of 1000000 was chosen to be arbitrarily high, assuming it came without cost; it is not expected to ever be reached on any deployment.  262b19346e4e already lowered one aspect of that changeset, upon determining it did come with a cost.  Potentially breaking virtualized deployments during upgrade is another cost of that change. …
=> supervisor: Drop minfds back down from 1000000 to 40000.

web/styles/zulip.css
Apply border and top margin on the same element so that browser has no way to introduce a gap between them.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/topic.20header.20bar.20sometimes.20off.20aligned
This change should fix the bug of message header border being overlapped by its own padding-top.
I couldn't reproduce the bug so no way to test it.
=> css: Move message header padding to the element with border.

web/styles/portico/portico.css
These changes ensure that only headings targeted by URL fragments are highlighted in full. Div elements will have their immediate first child element highlighted instead (e.g., the first element of an API parameter box).
The repeated `& hN.scroll-target` selectors look repetitive, but I believe they're necessary to keep from having to repeat the actual style declaration on what would be a separate block targeted just to the immediate first-child of the div.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/help.20page.20highlighting/near/1571689).
[Current API docs](http://zulip.com/api/update-message#parameter-propagate_mode)
Before:
After:
[Current help docs](http://zulip.com/help/getting-your-organization-started-with-zulip#advantages-of-zulip-cloud)
Before:
After …
=> help_pages: Improve anchor highlights.

docs/production/deployment.md, puppet/zulip/files/nginx/uwsgi_params, puppet/zulip/files/nginx/zulip-include-common/proxy, puppet/zulip/manifests/nginx.pp, puppet/zulip/templates/nginx/trusted-proto.template.erb, puppet/zulip/templates/nginx/zulip-enterprise.template.erb
This has been required since a change in Django 4.0
This did not come out until people had http zulip servers accessed over https proxies.
Fixes: 
- https://github.com/zulip/zulip/issues/24599
- https://chat.zulip.org/#narrow/stream/9-issues/topic/Zulip.206.2E0.20behind.20reverse.20proxy.20-.20CSRF.20verification.20failed
<details>
(variable names, code reuse, readability, etc.). *Not Applicable*
</details>
=> docs: Tell people to set X-Forwarded-Proto

web/src/ui_init.js
If the spectator registration call fails, properly log the error and call `reject` with an error object, not the xhr that `channel.post` calls its error callback with.
This does nothing to address the UI question of what to do should this request fail.
<details>
</details>
=> ui_init: Properly call reject with an error, not an xhr.

api_docs/changelog.md, zerver/openapi/zulip.yaml
Adds an API changelog note to 2.1 for the addition of `realm_default_external_accounts` to the `/register-queue` response. Also adds a Changes note to the field in the endpoint's response API documentation.
The original commit that added it to that endpoint's response was commit d7ee2aced17ecf81b.
See [this CZO message/conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/audit.20for.20change.20entries.20vs.2E.20central.20changelog/near/1393419) for more context.
**Notes**:
- Because this is more of a server setting and does not have any equivalent events in the `GET /events` endpoint, I didn't use the convention we settled on in [this #api documentation conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/realm.20settings.20names/near/1 …
=> api-changelog: Add 2.1.0 entry for realm_default_external_accounts.

web/styles/dark_theme.css
discussed on CZO [here](https://chat.zulip.org/#narrow/stream/101-design/topic/settings.20design.20.28dark.20theme.29/near/1570436)
Reverts some of the effects of #23724
=> settings: Revert dark mode background color changes.

stylelint.config.js
This adds a CSS stylelint rule that will catch erroneous quotation marks around [named grid-areas](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-area), which should be [&lt;custom-ident&gt;](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident) values, not strings. So, for example, `grid-area: "my_area"` is an error. It should be `grid-area: my_area`.
This is not just a cosmetic issue: `grid-area` will not work if areas are presented in quotation marks.
Because there will likely be more use of CSS Grid on the redesign, because the Zulip project ought to encourage the use of named areas, and because quotation marks look "natural" on `grid-area` even though they are in error, it makes sense to preserve this knowledge in the linter configuration.
<details> …
=> linter: Lint grid-area names for quotation marks.

web/styles/rendered_markdown.css
Added styling to change the UI for the copy-to-clipboard button to remove the rectangular outline that appears on click.
Fixes: issue #25533 
</details>
=> message feed: removed copy code button outline

web/styles/dark_theme.css, web/styles/zulip.css, web/templates/single_message.hbs
This change enables the unread marker to participate as a grid item, rather than the product of various absolute/relative positioning hacks. The intention is to therefore prevent the blue active-message box from disappearing on browsers that have zoomed out (~80% zoom).
With grid in place, this also makes for a more robust presentation of each message row, and named grid areas should make it possible to modify and extend the grid into the future.
Finally, this change removes styles that are no longer necessary in the context of CSS Grid.
[CZO Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/blue.20box.20cut.20off).
Because this PR has potentially significant impact to the Zulip interface, particularly message rows, it needs a lot of eyeballs to make sure it breaks nothing. …
=> css: Present message_row as CSS Grid.

web/src/stream_list.js, web/src/unread.js, web/styles/left_sidebar.css, web/tests/stream_list.test.js
The above point also fixes the below point as it will automatically align @ mention, as no @ align will be possible without an unread counter after executing above:
Fixes: #25382 
- Unmuted stream having an unmuted mention in a muted topic:
- Unmuted stream having an unmuted mention in a muted topic also having an unread message in a normal topic:
- Unmuted stream having unmuted mentions in a muted and normal topic both:
<details> …
=> left_sidebar: Improve display of @-mentions and unread counters for muted topics in unmuted stream.

web/src/settings_playgrounds.js, web/templates/settings/playground_settings_admin.hbs
Removed the sorting functions which were sorting under the assumption that our comparison items were a list instead I used the generic sort functions functionality of our `list_widget` module.
Discussion: [CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Sorting.20issue.20in.20code.20playgrounds.2E)
| ![Before](https://github.com/zulip/zulip/assets/84276404/d8f84ff8-af97-4031-a23a-fa62b06f5563) | ![Screenshot 2023-05-21 142132](https://github.com/zulip/zulip/assets/84276404/3c244476-2b3c-49a9-8094-93c82c0c99dc) | 
<details> …
=> settings_playground: Fix sorting issues in code playgrounds table.

web/styles/dark_theme.css, web/styles/rendered_markdown.css, web/styles/zulip.css
Implements the mention pill part of #22022
before:
after:
=> css: Change mention text and background colors.

api_docs/changelog.md, zerver/openapi/zulip.yaml
Part of 7.0 API changelog audit; see [this CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/7.2E0.20API.20changelog.20audit/near/1572765) for more context.
Updates API changelog entry and related parts of API docs for: **Feature level 175**.
**Notes**:
- Revises API changelog entry and related API documentation for new user setting to clarify language around "client" and "user".
- Updates the related **Changes** notes to clarify language around which Zulip apps are being referenced.
---
<details>
<summary>Updated API changelog 175 entry</summary>
[Current documentation](https://chat.zulip.org/api/changelog#changes-in-zulip-70)
</details>
<details>
<summary>Example of updated user setting in API documentation</summary> …
=> api-changelog: Update feature level 175 entry and related changes notes.

zerver/openapi/zulip.yaml
Part of 7.0 API changelog audit; see [this CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/7.2E0.20API.20changelog.20audit/near/1573157) for more context.
Updates API changelog entry and related parts of API docs for: **Feature level 176**. Follow-up for review feedback on #25684 that was made after that PR was merged.
**Notes**:
- Adjusts the descriptions of `realm_linkifiers` (and deprecated `realm_filters`) events and register response fields so that the description of the current API is complete without the feature level 176 **Changes** notes.
- Fixes a few typos noted in the review feedback referenced above.
---
<details>
<summary>Events: realm_linkifiers</summary>
| --- | --- |
| ![Screenshot …
=> api-docs: Make realm_linkifiers current API clear in description.

web/src/rtl.ts
This pull request converts `rtl.js` to TypeScript.
Thanks to @xoldyckk for working on this one at #24859.
- I had to adjust one or two things here, mostly related to type assertion and type definitions. 
<details>
</details>
=> ts: Convert rtl.js to TypeScript.

web/styles/dark_theme.css, web/styles/message_row.css, web/styles/zulip.css
This PR addresses post-merge feedback from #25644.
1. It updates comments in the CSS to be more useful to future readers of the code, by not referencing the state of the CSS before that PR.
2. It moves CSS from #25644 and related selectors into the `message_row.css` file.
The one piece of feedback from #25644 not implemented here is Tim's [comment about animating unread markers](https://github.com/zulip/zulip/pull/25644#discussion_r1199346069). From studying the code, all of the visual and interactive aspects of the unread marker are kept with the `.unread_marker` class. The two new classes from #25644, `date_unread_marker` and `message_unread_marker`, have only information about grid positioning and a couple of conditional styles.
My thinking is that those two new classes can probably …
=> css: Message-row css fixes leftover from #25644.

tools/total-contributions
This adds zulip/zulip-flutter to the list of repositories canvassed by the `tools/total-contributions` script.
It also fixes a bug that would cause us to leave out a repo's history when the start date is older than the oldest commit in the repo — so in particular we'd leave out a repo's history whenever what we actually wanted was the repo's *entire* history.
<details>
</details>
=> Add zulip-flutter to total-contributions script

puppet/zulip/files/nginx/uwsgi_params, puppet/zulip/files/nginx/zulip-include-common/proxy, puppet/zulip/manifests/nginx.pp, puppet/zulip/templates/nginx/trusted-proto.template.erb, puppet/zulip/templates/nginx/zulip-enterprise.template.erb
Django has a `SECURE_PROXY_SSL_HEADER` setting[^1] which controls if it examines a header, usually provided by upstream proxies, to allow it to treat requests as "secure" even if the proximal HTTP connection was not encrypted.  This header is usually the `X-Forwarded-Proto` header, and the Django configuration has large warnings about ensuring that this setting is not enabled unless `X-Forwarded-Proto` is explicitly controlled by the proxy, and cannot be supplied by the end-user.
In the absence of this setting, Django checks the `wsgi.url_scheme` property of the WSGI environment[^2].
Zulip did not control the value of the `X-Forwarded-Proto` header, because it did not set the `SECURE_PROXY_SSL_HEADER` setting (though see below).  However, uwsgi has undocumented code which silently …
=> nginx: Set X-Forwarded-Proto based on trust from requesting source.

web/styles/message_row.css, web/styles/zulip.css
We had the `3px 0 1px` padding before migration to use grid, then I switched it to use `4px 0 1px` since we were planning to use blue box border which seemed to have helped that case.
Since we switched to using outline for blue box, it makes sense to just use equal padding.
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/Centering.20in.20message.20row
before:
after:
=> message_row: Use equal top/bottom padding in message content.

web/styles/message_row.css, web/styles/rendered_markdown.css
This just ensures that the mention-pill color selectors are children of `rendered_markdown`, which class appears both in the message- preview area as well as individual message rows.
Fixes #25720.
| Before, light mode | After, light mode |
| --- | --- |
| <img width="858" alt="before-light-preview" src="https://github.com/zulip/zulip/assets/170719/df24a0d5-33e6-4c3e-bd3b-b24769cd3045"> | <img width="858" alt="after-light-preview" src="https://github.com/zulip/zulip/assets/170719/7418e0ff-69d4-427c-84d9-0d9e7e19dc95"> |
| Before, dark mode | After, dark mode |
| --- | --- |
| <img width="858" alt="before-dark-preview" src="https://github.com/zulip/zulip/assets/170719/d22aa805-68ec-41c4-8daf-ef8dbf79f5fb"> | <img width="858" alt="after-dark-preview" …
=> css: Move mention-pill colors under rendered markdown.

web/styles/search.css, web/styles/zulip.css
The nav bar's bottom border was being hidden by the search bar. This makes the search bar slightly less high to fix this issue.
Soon this code will be replaced with the changes in #24345.
Reported on CZO [here](https://chat.zulip.org/#narrow/stream/9-issues/topic/search.20box.20bottom.20border)
=> search: Make search box bottom border visible again.

web/e2e-tests/settings.test.ts, web/src/flatpickr.js, web/src/settings.js
When the user has a date-picker on the screen in the settings menu and if the user closes the settings modal using the `Esc` key then the date-picker does not go away instead it is still there on the screen. 
This PR adds the code to remove the date-picker when the settings modal is closed.
Fixes part of #25097. 
CZO Discussion [Link](https://chat.zulip.org/#narrow/stream/9-issues/topic/Date.20picker.20bug)
<hr>
<details>
<summary>Before</summary>
[Before.webm](https://user-images.githubusercontent.com/35286603/234287344-0dbe523b-698c-4b0e-ac72-91e99edeb909.webm)
</details>
<details>
<summary>After</summary>
[After.webm](https://user-images.githubusercontent.com/35286603/234287363-083bd167-436b-4ee3-8950-3b95166418fe.webm)
</details>
<hr>
<details> …
=> settings: Close date-picker when settings modal is closed.

web/shared/src/internal_url.js
zulip-mobile currently requires Android ≥ 7 and iOS ≥ 14, both of which support `replaceAll`. The code change was in commit 54f90e41c07645e34d49967cdb2e0c2089390b9f (#25554).
=> internal_url: Remove obsolete TODO comment

web/src/feedback_widget.ts, web/styles/zulip.css
Fixes #25376
Animating `box-shadow` and `top` is slow since the browser drops frames when animating them. We can fix it by using `will-change` property, but it is just better to not animate them and instead use transform.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/topic.20muted.20notification.20issue
before: 
after:
=> feedback_widget: Don't use non-optimal animation properties.

web/src/billing/helpers.js, web/tests/billing_helpers.test.js
This uses `Intl.NumberFormat` to format the converted amount. 
It is 96.92 % supported across various browsers. Source: [caniuse.com](https://caniuse.com/?search=Intl.NumberFormat)
<details>
</details>
=> billing-helpers: Add commas to formatted amount.

api_docs/changelog.md, zerver/openapi/zulip.yaml
Part of 7.0 API changelog audit; see [this CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/7.2E0.20API.20changelog.20audit/near/1574948) for more context.
Updates API changelog entry and related parts of API docs for: **Feature level 168**.
**Notes**:
- Updated API changelog entry to note that this is a user setting that's being updated. Otherwise, the fact that the setting starts with `realm_` could be a little bit confusing.
- Updates the **Changes** note for the deprecated global notifications setting to be in descending order.
- Original API changelog entry from commit ae72777c77.
---
<details>
<summary>Updated API changelog entry for feature level 168</summary>
[Current …
=> api-changelog: Update feature level 168 entry and changes notes.

web/src/stream_edit.js, web/src/stream_ui_updates.js, web/src/user_group_ui_updates.js
This pull request migrates tooltips created in `stream_ui_updates.js` to use `tippy.js` instead of Bootstrap popovers. Manual testing has been done for all tooltips created in the above-mentioned file.
It also fixes a bug in which no tooltip was shown when the `Subscribe` button for a private stream was disabled.
Fixes: #25627
- To test the `Add Subscribers` and `Disabled Subscriber Button` tooltips, first log in as an `Administrator` and then create a private stream with members being you and some more people. Now, Unsubscribe yourself from that stream. After this, if you hover over the subscribe button you will be able to see the tooltip. Click on the `Subscribe` tab on that same window and now you can see the disabled input and the `Add` button, hover over these to see the tooltip.
- …
=> stream_settings: Migrate popovers to tippy. 

web/src/settings_bots.js
CZO: https://chat.zulip.org/#narrow/stream/9-issues/topic/bot.20owner.20dropdown.20bug
Fixes: 
<details>
</details>
=> edit_bot: Include current bot owner to bot owner dropdown.

help/edit-or-delete-a-message.md, help/message-retention-policy.md
This PR extends #25067, which added mobile instructions to /help/edit-or-delete-a-message, with a rewrite pass to make the page more clear and better aligned with current documentation patterns.
Note that moving the permissions warnings in-line in the instructions in consistent with `/help/rename-a-topic`, etc.
I didn't try to split out my changes into separate commits. I think we can squash everything together when merging.
Current page: https://zulip.com/help/edit-or-delete-a-message
<details>
<summary>
Updated page
</summary>
</details>
=> help: Document "Edit message" mobile feature.

web/src/compose_validate.js, web/tests/compose_validate.test.js
This PR addresses the issue of relying on `compose_state` for retrieving the `stream_id` to display warning banners. Previously, when the compose box was closed, the warnings were not shown in the message edit box. Now, we utilize the `get_stream_id_for_textarea` function to obtain the correct `stream_id` value and resolve this problem.
Fixes: #25410.
<details>
<summary>Warning with compose box closed</summary>
| ![before](https://github.com/zulip/zulip/assets/53193850/5e0f5f17-03df-44ca-974c-95f6cbdbbd45) | ![after](https://github.com/zulip/zulip/assets/53193850/bae67cba-071a-43f8-a37c-2d2778e96508) | 
</details>
<details>
<summary>Private stream mention with compose box closed</summary> …
=> compose_validate: Use correct stream_id value for different context.

templates/zerver/app/index.html, web/src/compose_actions.js, web/src/compose_recipient.js, web/src/compose_ui.js, web/src/emoji_picker.js, web/src/giphy.js, web/src/hashchange.js, web/src/message_edit.js, web/src/message_list_view.js, web/src/message_scroll.js, web/src/message_viewport.js, web/src/narrow.js, web/src/navbar_alerts.js, web/src/overlays.ts, web/src/popovers.js, web/src/reload.js, web/src/resize.js, web/src/scroll_bar.ts, web/src/setup.js, web/src/ui_init.js, web/styles/recent_topics.css, web/styles/tooltips.css, web/styles/zulip.css, web/templates/navbar.hbs, web/tests/compose_ui.test.js, web/tests/narrow_activate.test.js, web/tests/popovers.test.js, web/third/bootstrap-tooltip/tooltip.js, web/third/bootstrap-typeahead/typeahead.js
We scroll on `html` instead of `.app`. This introduces three major issues:
* All our `offset` values have `$("html").scrollTop()` added to them, and `$element.position()` values will change for some elements too. This is addressed in the first commit.
* empty hash `#` scrolls to top of the feed. To address this, we avoid setting empty hash via JS in any case. If user types in `<org url>/#` then we will scroll to top but just `<org url>/` will work fine.
* Messages scroll when overlays/modal is active. When user scrolls, we instantly scrollback to the previously scrolled position if there is an overlay/modal active. This seems to fix the issue without any visual bugs.
=> Scroll on `html` instead of `.app`.

zerver/openapi/zulip.yaml
In the register response (`POST /register`) properties deprecated at feature level 89, updates the descriptions to link to the `client_capabilities` parameter when referenced.
Also, moves the `enter_send` property to be in the same section of the register response as other properties deprecated at this feature level.
These descriptions were originally added to these properties in commit e6f828a8e25. Follow-up from #25721.
<details>
<summary>Example of a few of the changed descriptions</summary>
[Current documentation](https://zulip.com/api/register-queue) - *search for feature level 89*.
</details>
---
<details> …
=> api-docs: Link `client_capabilities` parameter in register response property descriptions.

api_docs/changelog.md
Part of 7.0 API changelog audit; see [this CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/7.2E0.20API.20changelog.20audit/near/1575884) for more context.
Original API feature level 164 entry from commit a593089770.
[Current documentation](https://zulip.com/api/changelog#changes-in-zulip-70) - *search for Feature level 164*
---
<details>
</details>
=> api-changelog: Revise feature level 164 entry.

api_docs/changelog.md
Part of 7.0 API changelog audit; see [this CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/7.2E0.20API.20changelog.20audit/near/1575920) for more context.
Original API feature level entry from commit ff895905586.
[Current documentation](https://zulip.com/api/changelog#changes-in-zulip-70) - *search for Feature level 160*
<details>
</details>
=> api-changelog: Revise feature level 160 entry.

CONTRIBUTING.md, docs/contributing/code-reviewing.md, docs/contributing/index.md, docs/contributing/review-process.md, docs/contributing/reviewable-prs.md
- Move the "Submitting a pull request" and "Stages of a pull request" sections of the contributing guide to a dedicated page.
- 2nd and 3rd commits link to the new page from related pages.
Links were manually tested.
=> docs: Add a page documenting review process for pull requests.

web/styles/compose.css, web/styles/zulip.css, web/templates/compose.hbs
While this PR fixes the height of the topic-box elements by relying heavily on flexbox's behavior to manage the height of the elements and vertical centering, where necessary, rather than positioning hacks or vertical padding. 
This PR also removes some additional styles that do not make sense (e.g., `min-width: 0`) or that do not need to be set (e.g., `width: 100%`, which is the same as the `width: auto` default on block-level elements).
Finally, this PR also addresses text-color portions of #24878, ensuring the uniform use of the default body color on the compose bar and message-compose box.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/Compose.20box.20topic.20input.20box)
Possible points of further discussion:
1. In a narrow group-DM window, the piled pills will …
=> compose_box: Topic input box fixes.

web/styles/dark_theme.css
=> drafts: Darken background in drafts overlay.

tools/test-js-with-node, web/src/compose_textarea.ts, web/src/global.d.ts
Added type definitions for `jquery-caret-plugin` third party package and converted `compose_textarea.js` to TypeScript.
I took reference types for `jquery-care-plugin` from here: https://github.com/acdvorak/jquery.caret#api
<details>
</details>
=> ts: Convert `compose_textarea.js` to TypeScript.

web/styles/message_row.css
This PR introduces a 2px linear gradient background to present the unread marker.
See [the CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/UI.20redesign.3A.20unread.20style/near/1575708).
| Before, light mode | After, light mode |
| --- | --- |
| <img width="578" alt="before-marker-light" src="https://github.com/zulip/zulip/assets/170719/7b01bf68-8d6f-4c06-b5a0-eba38fef3cca"> | <img width="578" alt="after-marker-light" src="https://github.com/zulip/zulip/assets/170719/422c8b20-a451-43f9-8210-f5a8684d5108"> |
| Before, dark mode | After, dark mode |
| --- | --- |
| <img width="578" alt="before-marker-dark" src="https://github.com/zulip/zulip/assets/170719/334cb542-81b7-4a71-8d94-205e81d3baa4"> | <img width="578" …
=> unread_marker: Style as subtle linear gradient.

CONTRIBUTING.md
These links could not be merged without breaking CI in the previous commits.
=> CONTRIBUTING: Add links to new review process guide.

.eslintrc.json, web/shared/src/fenced_code.ts, web/shared/src/internal_url.js, web/shared/src/typeahead.ts
The JavaScript engine used by zulip-mobile on Android is still some four years out of date, apparently.
This reverts commit a3d6c47b7d8b7ff1c51554f60f93295e3460f01b (#25734) and part of commit 54f90e41c07645e34d49967cdb2e0c2089390b9f (#25554).
=> shared: Avoid replaceAll again

web/src/server_events_dispatch.js, web/tests/dispatch.test.js
This causes the app to scroll to top and causes slow paint.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/changing.20theme
=> server_events_dispatch: Remove body fade out on changing theme.

api_docs/changelog.md, zerver/openapi/zulip.yaml
Part of 7.0 API changelog audit; see [this CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/7.2E0.20API.20changelog.20audit/near/1576702) for more context.
**Notes**:
- Makes the switch from "Zulip display email" to "Zulip API email" in the API documentation; discussed [here](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/api.20send.20message.20using.20mail.20addresses/near/1572194) on CZO.
- Updates the main description of the documentation for [Get a user by email](https://zulip.com/api/get-user-by-email) for the email address visibility change from an organization-level setting to a user-level setting.
- Fixes examples that were now missing the always present `delivery_email` field, though sometimes it is `null`.
- General updates …
=> api-docs: API feature level 163 revisions and related changes.

api_docs/changelog.md, zerver/openapi/zulip.yaml
See [this CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/prev_stream.20in.20message.20history/near/1575857) for more context.
**Notes**:
- Updates API changelog feature level 118 entry to clarify that the `prev_stream` field existed before these changes.
- Adds API changelog feature level 1 documentation for `stream_id` parameter for `PATCH /messages/{message_id}` and for `prev_stream` in message edit history information.
<details>
<summary>API changelog feature level 118</summary>
[Current documentation](https://zulip.com/api/changelog#changes-in-zulip-50)
</details>
<details>
<summary>API changelog feature level 1</summary>
[Current documentation](https://zulip.com/api/changelog#changes-in-zulip-30)
</details> …
=> api-docs: Update API changelog for more history about moving messages between streams.

web/src/browser_history.js, web/src/click_handlers.js, web/src/hashchange.js, web/src/server_events_dispatch.js, web/templates/navbar.hbs, web/tests/browser_history.test.js, web/tests/dispatch.test.js, web/tests/hashchange.test.js
We use named hashes like `#all_messages` for all views and never try to set empty hash to avoid user scrolling to the top.
This avoids scrolling to the top of `All messages` on pressing `esc` when user has set `all messages` set as the default view.
=> haschange: Never set empty hash.

api_docs/changelog.md, api_docs/create-scheduled-message.md, api_docs/include/rest-endpoints.md, version.py, zerver/actions/scheduled_messages.py, zerver/openapi/zulip.yaml, zerver/tests/test_events.py, zerver/tests/test_home.py, zerver/tests/test_import_export.py, zerver/tests/test_scheduled_messages.py, zerver/tests/test_upload.py, zerver/views/scheduled_messages.py, zilencer/management/commands/populate_db.py, zproject/urls.py
Adds a new separate endpoint for editing scheduled messages: `PATCH /scheduled_messages/<int:scheduled_message_id>`.
Also, removes the `scheduled_message_id` parameter from `POST /scheduled_messages`, and updates that endpoint's `operationId` to be `create-scheduled-message`. Previously, it was `create-or-edit-scheduled-message`.
See [this CZO conversation](https://chat.zulip.org/#narrow/stream/378-api-design/topic/scheduled.20messages/near/1561281) for more context.
---
**Notes**:
- There is a prep commit that adds a second scheduled message to `populate_db.py` for Iago. This is because the `api-test` goes through the `operationId`s in alphabetical order, so the delete curl example happens before the update/edit curl example happens.
- The final three commits can all be squashes before …
=> scheduled-messages: Add separate endpoint for editing existing scheduled messages.

web/src/popovers.js, web/tests/popovers.test.js
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/user.20group.20info.20popover.20not.20opening
Open in playground when there are multiple playgrounds for the same language.
=> Hide popovers on scrolling and show them at correct position.

web/styles/message_row.css
This fix prevents the active-message outline from being obscured under certain conditions, such as when setting a browser to zoom out at 90% or less.
See [CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/blue.20box.20cut.20off)
While this PR introduces no visual changes, here is a set of screenshots that mimic its effects by artificially increasing the active-message outline to 5px. Before this PR, the border gets cut off; after, it does not. Again, this is only to demonstrate the effects. Other than the edge case of zooming out, this PR should have NO effect on ordinary display of active messages.
| Before (mimicking a zoomed-out state) | After (mimicking a zoomed-out state) |
| --- | --- |
|  <img width="984" alt="faux-active-before" …
=> css: Remove superflous background color on date row.

web/src/message_list_view.js, web/src/message_viewport.js, web/src/scroll_bar.ts, web/src/ui_init.js, web/styles/zulip.css
Tim and Steve saw their message feed scroll to top when a new message arrived. This could be related to it.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/new.20message.20top.20of.20feed.20scrolling
=> message_list_view: Only update scroll position for current msg list.

web/src/overlays.ts, web/styles/compose.css, web/styles/zulip.css
When overlay / modal is displayed, scrollbar is hidden due to the disabled scrolling on `html`. Reduce width of fixed elements that will be visible in background and `html` so that they don't occupy that extra space.
Also, I was over-thinking how we can get the scrollbar width. The moment we allowed scrolling on `html`, it was easy to get the scrollbar width.
before:
after:
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/opening.20a.20modal.20.2F.20overlay.20causes.20scrollbar.20to.20hide
Tested:
Safari, chrome and firefox on mac and  windows + scrollbar always visible / hidden + narrow width / wide width
=> overlays: Stop document from occupying the extra scrollbar width.

web/styles/alerts.css
This uses fixed positioning to ensure that the alert box and its contents remain in the viewport, regardless of any scrolling activity.
While I revealed additional alerts by adding `show` classes to the DOM in manual testing, I would appreciate additional pokes and verification that there are no unexpected side-effects here (there shouldn't be, as `position: fixed` and `position: absolute` behave almost identically...but there's always that possibility).
Fixes #25791.
| --- | --- |
| ![alert-before](https://github.com/zulip/zulip/assets/170719/4710993b-1eda-425c-b27a-c40b7b6f89a6) | ![alert-after](https://github.com/zulip/zulip/assets/170719/860506fc-510a-46fb-8d4c-b0df346494e6) |
<details> …
=> alert_box: Maintain alert-box position despite scrolling.

zerver/actions/realm_settings.py, zerver/tests/test_realm.py
Opening this in favor of https://github.com/zulip/zulip/pull/14967 which we ended up kind of forgetting about without merging. I tweaked it to also use `message.realm`  (which we didn't have denormalized back then yet) for filtering to be more robust against accidentally deleting too much, which might alleviate the concern in https://github.com/zulip/zulip/pull/14967#discussion_r425436484 and in general reduce uncertainty since we're filtering by both `recipient` and `realm` with redundancy
=> actions: Handle cross-realm messages in do_scrub_realm.

help/keyboard-shortcuts.md, web/templates/keyboard_shortcuts.hbs
- Adjust the order in keyboard shortucts help menu and help center.
- Make minor wording improvements.
This PR removes wording and ordering differences between the two docs that don't seem helpful to me.
<details>
<summary>`?` menu before/after</summary>
| --- | --- |
| ![image-before](https://github.com/zulip/zulip/assets/2090066/f4b31158-5a0d-43ab-a156-e8aff7722794) | ![image-after](https://github.com/zulip/zulip/assets/2090066/f9f17d3c-3295-42eb-af51-a0008a616522)
</details>
Current help center page: https://zulip.com/help/keyboard-shortcuts#composing-messages
<details>
<summary> Help center changes (screenshot)</summary>
</details>
=> help: Tweak docs on keyboard shortcuts for composing messages.

web/src/resize.js
This fixes a bug where reducing the height of the window, reduces the size of textarea and doesn't instroduce scrollbars, making the textarea not scrollable.
before:
after:
=> resize: Use autosize on window resize.

web/src/overlays.ts
It is unusal to use a hack to close overlays when there is a method to do it.
This fixes a bug where user is unable to scroll message feed after opening an overlay and then using browser back button.
This could have easily cause other bugs too.
Bug reproducer:
Open an overlay and then press the browser back button. You will not be able to scroll messages.
=> overlays: Use `close_overlay` to close overlays!

help/view-zulip-version.md, zerver/lib/markdown/tabbed_sections.py
Version number was added to top section of gear menu in 4df8c6610f19f08be1564d755aacb6c544eadbbc.
Version number was added to "About Zulip" in 668b5137b005c915da5f00950fdc3288f76ec0fd.
Questions:
- Is "Zulip 6.0+" fine for the tab name given the context, or should it be "Zulip Server 6.0+"?
Current page: https://zulip.com/help/view-zulip-version#view-zulip-server-and-web-app-version
Updated:
=> help: Document quick way to check Zulip version.

web/src/scroll_bar.ts, web/styles/zulip.css
Fixes  #25779
We move the simplebar scroll on the right sidebar to a little left when there is an overlay scrollbar present so that user can drag either of them.
before: 
after:
Tested:
Fluid layout and window width above or below 1420px. Mac browsers and firefox on windows. 
I haven't tested anything on linux.
=> scroll_bar: Fix overlapping right sidebar and browser scrollbars.

web/src/compose_recipient.js, web/src/dropdown_widget.js, web/templates/compose.hbs
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Focus.20after.20picking.20stream
Here the cases I checked:
* When recipient selection dropdown is open and `escape` is pressed, we select the recipient dropdown button.
* When a stream is selected, we focus at the end of topic.
* When a DM is selected, we focus on users box if it is empty else we focus on compose.
=> Fix post recipient selection focus behaviour.

zerver/webhooks/github/view.py
The regex check is replaced with a simpler "startswith" function. This was suggested in [#25746(comment)](https://github.com/zulip/zulip/pull/25746#discussion_r1204824013).
<details>
</details>
=> integrations: Simplify regex checks in GitHub Integration.

docs/contributing/code-reviewing.md, docs/contributing/commit-discipline.md, docs/contributing/review-process.md
This clarifies for readers where PR labels are described in the document.
It also includes a commit that addresses a small nit, correcting the documentation's handful of instances of "code base" with the closed form "codebase," which is far and away the preferred form in the docs:
```
$ cd docs
$ git grep "code base" | wc
4      59     447
$ git grep "codebase" | wc
95     955    8532
```
[Original documention](https://zulip.readthedocs.io/en/latest/contributing/review-process.html#labels-for-managing-the-stages-of-pull-request-review):
Revised form:
<details> …
=> docs: Minor fixes around review-process doc.

help/support-zulip-project.md
I tested the new links.
Current page: https://zulip.com/help/support-zulip-project#help-others-find-zulip
Updated:
=> help: Update suggested review sites on Support the Zulip project page.

web/styles/compose.css
This allows the recipient box to take 100% of the available horizontal space, up to 175px. The effect is that the compose-box buttons are available to users at mobile scales (viewports of 400px wide or less).
See [CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/Small.20device.20compose.20icons); this also relates to #24889 and the work @shameondev has in progress (who should just remove the `max-width: 175px` declaration).
| Before, 325px viewport | After, 325px viewport |
| --- | --- |
| ![small-topics-bar-before](https://github.com/zulip/zulip/assets/170719/077f4233-7b7a-44e3-a605-aa017e484fcf) | ![small-topics-bar-after](https://github.com/zulip/zulip/assets/170719/b0ec1eb4-20b3-4a4c-89f9-96b444794c40) |
<details> …
=> css: Size stream recipient box for small screens.

help/all-messages.md, help/inbox.md, help/include/sidebar_index.md, help/recent-conversations.md, static/images/help/mobile-expand-less-icon.svg, static/images/help/mobile-expand-more-icon.svg, static/images/help/mobile-inbox-icon.svg
- Adds a new page under the "Reading messages" section documenting
the Inbox view on mobile.
- Adds Inbox, expand more, and expand less SVG mobile icons.
- Cross-links with "Recent conversations" and "All messages".
<details>
</details>
=> help: Document "Inbox view" mobile feature.

api_docs/changelog.md, zerver/openapi/zulip.yaml
[CZO Discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/muted.20topics/near/1557615)
This commit adds the missing `UNMUTED` visibility policy to the documentation for `api/get-events` and `api/register-queue`.
It replaces `INHERIT` with `NONE` for a clearer name in the `api/update-user-topic` documentation.
<hr>
<details>
<summary>
<b>api/get-events</b>
</summary>
</details>
<details>
<summary>
<b>api/update-user-topic (main description)</b>
</summary>
</details>
<details>
<summary>
<b>api/update-user-topic</b>
</summary>
</details>
<details>
<summary>
<b>api/mute-topic (main description)</b>
</summary>
</details>
<details>
<summary>
<b>api/register-queue</b>
</summary>
</details>
<details>
<summary>
<b>api/changelog</b>
</summary> …
=> user_topics: Update API documentation.

web/src/compose.js, web/src/recent_topics_ui.js, web/src/resize.js, web/styles/recent_topics.css, web/styles/zulip.css, web/tests/recent_topics.test.js
CZO discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/can't.20see.20all.20recent.20topics.20with.20open.20compose.20box
- Fixed Height of `#recent_topics_filter_buttons`: The height of the #recent_topics_filter_buttons div is now fixed at `87.2px`. This ensures consistent display across different device widths.
- Consistent Display of `#recent_topics_filter_buttons`: Previously, the #recent_topics_filter_buttons div displayed as 2 lines for device width < 1040px and 1/2 line for greater device width. Additionally, it displayed more than 2 lines for device width < 560px when filters spread to multiple lines. The behavior is now consistent, always displaying in 2 lines.
- Horizontal Simplebar for `#recent_filters_group`: To handle scenarios where all filters cannot fit within …
=> Recent topics bug fix

help/include/recent-conversations.md, help/marking-messages-as-read.md
Also link to definition from /help/marking-mesages-as-read.
If we like this approach, we can link to /help/recent-conversations from some other pages as well.
Current:
https://zulip.com/help/recent-conversations
https://zulip.com/help/finding-a-topic-to-read#from-recent-conversations
https://zulip.com/help/reading-strategies#finding-a-topic-to-read
https://zulip.com/help/getting-started-with-zulip#finding-a-topic-to-read
Current: https://zulip.com/help/marking-messages-as-read#configure-whether-messages-are-automatically-marked-as-read
=> help: Define "conversation" in /help/include/recent-conversations.md.

web/src/stream_ui_updates.js
If the stream settings is open but the stream which was subscribed/unsubscribed wasn't open (say user unsubscribed from a different tab), `$settings_button` would
be `undefined` here.
Reproducer for bug:
* Open stream settings.
* Open a new tab.
* Unsubscribed to a stream
* See error message in the previous tab.
=> stream_ui_updates: Only update UI if the stream is being edited.

docs/contributing/commit-discipline.md
=> docs: Add section about mentioning others to commit discipline doc.

web/src/people.js, web/src/server_events.js
As noted in the comment, this condition is expected to happen for spectator users.
=> people: Downgrade late added user errors for spectators.

web/styles/tooltips.css
* Remove `box-sizing` and `min-width` properties which have no effect on `inline` positioned element. Modified class selector to add `span` which reflects this while reading the CSS.
* Remove `2px` vertical padding and `line-height` which combined are fighting for space??
80% zoom:
before:
after:
100% Zoom
before:
after:
=> hotkey-hint: Fix text not middle aligned at different zoom levels.

.github/workflows/production-suite.yml, .github/workflows/zulip-ci.yml
This would ordinarily be determined by running `pnpm store path`, but pnpm is not installed yet at that point.
https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/CI.20pnpm.20cache.20broken.3F/near/1581885
=> ci: Fix pnpm store path for GitHub Actions

zerver/migrations/0439_fix_deleteduser_email.py
This code clearly meant to return host and returning realm.host is a mistake. realm.host is not accessible in a migration due to being a @property-decorated method. The code constructs the host var value just above this line.
=> migrations: Fix bug in migration 0439.

web/src/popover_menus.js
It was throwing error while schudiling a message having wildcard mention, because the function `open_send_later_menu` uses instance to track down interval, but the parametere instance was not passed from when it was called from warning banner action. This commit sets a default instance to an empty object.
Fixes: https://chat.zulip.org/#narrow/stream/9-issues
<details>
</details>
=> send_later: Wildcard mention throwing error on send later.

web/src/drafts.js, web/tests/drafts.test.js
Previously, if the drafts modal was open in two different tabs and if the user deletes one or more drafts in one tab then the count of drafts didn't get updated on the other tab. This can be fixed by moving the drafts from local storage to the cloud. But for now, this PR updates the count whenever the modal is opened or closed.
CZO Discussion: [Link](https://chat.zulip.org/#narrow/stream/9-issues/topic/drafts.20counter.20off)
<hr>
**Screen captures:**
**Before:** [Before_Drafts.webm](https://github.com/sbansal1999/zulip/assets/35286603/9d6bf8f8-19ea-45a1-980d-ee0fb818c149)
**After:**  [After_Drafts.webm](https://github.com/sbansal1999/zulip/assets/35286603/c68ceed4-e837-4fbb-b27d-be74fb7f77fb) 
<hr>
<details> …
=> drafts: Update drafts count when opening and closing the overlay.

zerver/openapi/zulip.yaml
Before this commit our docs mentioned `string[]` data type for `submessages` field on the `message` object. This commit changes the type to `object[]` and correctly mentions all fields of the `submessage` object.
<details>
</details>
=> docs: Fix data type for `submessages` field on `message` type.

web/styles/portico/billing.css
As of 9427fb72301c0674fdbfd75b1903e2c9d0966769, the billing page needs a proper value for --color-background-modal.
Before:
After:
=> billing: Fix css for popups on the billing page.

zerver/tests/test_example.py, zerver/tests/test_users.py, zerver/views/users.py
This reduces confusion when an admin user tries to create users.
This responds to an issue mentioned on CZO with a suggested improvement [here](https://chat.zulip.org/#narrow/stream/127-integrations/topic/REST.20API.3A.20create.20user.20fails/near/1485972).
<details>
</details>
=> users: Use a less generic response for unauthorized user creation.

web/templates/settings/admin_user_list.hbs, web/templates/settings/deactivated_users_admin.hbs, web/templates/settings/user_list_admin.hbs, web/templates/stream_settings/new_stream_user.hbs, web/templates/stream_settings/new_stream_users.hbs, web/templates/stream_settings/stream_member_list_entry.hbs, web/templates/stream_settings/stream_members.hbs, web/templates/user_group_settings/new_user_group_users.hbs, web/templates/user_group_settings/user_group_members.hbs
Remove User ID Column from tables in the following locations in settings:
-  `Manage Streams // Subscriber Tab`
- `Manage Streams // New Stream // Subscribers`
- `Organization Settings // Users`
- `Organization Settings // Deactivated Users`
The original Issue mentions linking cards to user names where they aren't already
>  Stream settings -> Create stream > Subscribers
> As a prerequisite for this one, we should make user names in this table link to user cards as well.
But this was fixed by a separate issue, [#25725 ]([https://github.com/zulip/zulip/issues/25725](https://github.com/zulip/zulip/issues/url))
**Fixes:** [#25483 ](https://github.com/zulip/zulip/issues/25483)
<details> …
=> Drop User ID Column from Tables in Settings (Issue #25483)

scripts/lib/upgrade-zulip-stage-2, scripts/setup/upgrade-postgresql
This does a little raise the question of if we need to store `postgresql.version` in `/etc/zulip/zulip.conf` if we just explode whenever it disagrees with what Django is running.
An alternate form of this would set a Puppet variable as a default for the initial install, and otherwise have Puppet (which is I think the only thing which cares?) shell out to Django to ask what version it's using.  That's probably fiddlier than this band-aid, though, and preventing data loss is a good thing to get a fix for quickly.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-d …
=> Additional protections and checks on PostgreSQL version

web/src/starred_messages_ui.js, web/src/ui_init.js
We need to call `rerender_ui` once on the initial page load, hence we need to initialize `starred_message` module and call `rerender_ui` together.
Fixes #25935.
<details>
</details>
=> starred_messages_ui: Add initialize method for this module.

web/styles/zulip.css
This PR subtly darkens the text-message color in the light theme to the HSL equivalent of a dark gray (`#262626`). See [CZO discussion](https://chat.zulip.org/#narrow/stream/431-redesign-project/topic/light.20theme.20text.20color.20change).
(Note that that color was already stored on an unused CSS variable, `--color-default-text`, which was not only unused but clashed hard with `--color-text-default`, which _is_ in use.)
This is the first time in the Zulip codebase where one CSS custom property is set to another: the dark theme preserves its use of `--color-text-default` in this way, but can be adjusted independently of the rest of the theme in the future by setting a different color value on `--color-text-message-default`. Related reading on this technique: …
=> css: Darken light-theme message text.

web/src/popover_menus.js
These changes appear to correct the keyboard-navigation repro from #25907, and it makes it possible for users without the permission to create streams to exit the streams modal by
hitting Esc.
This reorganizes logic within the Tippy `onShow` method to ensure that nothing is set or called for those users without stream-creation privileges.
These changes probably require broader testing to determine whether the fix addresses only that specific reproducer, or the broader problems #25907 addresses with malfunctioning j, k, Esc, and Return keys (when Ctrl + Return to send is enabled).
Fixes a part of #25907.
Before, user (Polonious) without stream-create permissions:
1. Open Streams modal (no tooltip)
2. Type `jkjkjk` in Filter streams box
3. Attempt to …
=> popovers: Improve Tippy-based stream-popover UI lifecycle.

web/src/portico/help.js, web/styles/portico/markdown.css
Added a copy-to-clipboard button to the code blocks in the API and Help Center docs. Previously, copying code from the docs required manual copying, which was cumbersome.
Used the same copy-to-clipboard svg icon as the one used in web/src but manually created the button within the js function instead of using a template. Updated the `pre` CSS element to have relative positioning and gave the `copy-codeblock` element absolute positioning to ensure the button stayed in the top-right corner.
Fixes: #25726.
<details> …
=> docs: Add copy code button to portico docs.

zerver/lib/user_groups.py, zerver/tests/test_user_groups.py, zerver/views/user_groups.py
The user group depedency graph should always be a DAG. This PR adds code to make sure we keep the graph DAG while adding subgroups to a user group.
https://chat.zulip.org/#narrow/stream/3-backend/topic/UserGroup.20cycles
Fixes:  #25913
<details>
</details>
=> user_groups: Prevent cycles when adding subgroups for a user group.

docs/production/deployment.md, docs/production/upload-backends.md, puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf, puppet/zulip/lib/puppet/functions/resolver_ip.rb, puppet/zulip/manifests/app_frontend_base.pp, puppet/zulip/templates/nginx/s3-cache.template.erb
puppet: Explicitly enable systemd-resolved.
04cf68b45ebb make nginx responsible for downloading (and caching)
files from S3.  As noted in that commit, nginx implements its own
non-blocking DNS resolver, since the base syscall is blocking, so
requires an explicit nameserver configuration.  That commit used
127.0.0.53, which is provided by systemd-resolved, as the resolver.
However, that service may not always be enabled and running, and may
in fact not even be installed (e.g. on Docker).  Switch to parsing
`/etc/resolv.conf` and using the first-provided nameserver.  In many
deployments, this will still be `127.0.0.53`, but for others it will
provide a working DNS server which is external to the host.
In the event that a server is misconfigured and has no resolvers in
`/etc/resolv.conf`, it …
=> puppet: Read resolver from /etc/resolv.conf.

zerver/tests/test_markdown.py, zproject/dev_settings.py, zproject/test_extra_settings.py
`THUMBNAIL_IMAGES` was previously set to true as there were tests on a new thumbnail functionality. The feature was never stable enough to remain in the codebase and was left enabled. This setting also doesn't reflect how the production deployments are and it is in our best interest to turn it off.
`THUMBNAIL_IMAGES` has been removed from:
`zproject/dev_settings.py`
`zproject/test_extra_settings.py`
**Note:**
Since the removal of `THUMBNAIL_IMAGES` in `test_extra_settings`, there was some coverage lost in `zerver/lib/markdown/__init__.py`. To prevent this, I reordered the checks at the call site to ensure that the function that lost coverage is tested. 
<details> …
=> dev_settings: Remove THUMBNAIL_IMAGES from dev_settings.

.github/ISSUE_TEMPLATE/1_discussed_on_czo.md, .github/ISSUE_TEMPLATE/2_bug_report.md, .github/ISSUE_TEMPLATE/3_feature_request.md, .github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md, help/support-zulip-project.md
Follow-up to #25998, pushed as a separate PR so that the original one can pass CI.
This PR creates templates for filing issues. The templates are intentionally quite light-weight. Note that I'm specifically not using [forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) for creating issues, as the UI for filling out such a form does not include GitHub's helpful formatting buttons and preview mode.
More importantly, users will be presented with the following options when creating an issue:
A major goal is to guide users towards starting a CZO conversation when that's more appropriate than filing a GitHub issue.
Note that the config makes it possible to create a blank …
=> github: Configure templates for filing issues.

zerver/lib/send_email.py, zerver/tests/test_users.py
9d97af6ebba9 addressed the one major source of inconsistent data which would be solved by simply re-attempting the ScheduledEmail row.  Every other instance that we have seen since then has been a corrupt or modified database in some way, which does not self-resolve.  This results in an endless stream of emails to the administrator, and no forward progress.
Drop this to a warning, and make it remove the offending row.  This ensures we make forward progress.
----
See also #26018, #24081.
<details> …
=> send_email: Delete ScheduledEmail objects with no recipients.

zerver/actions/bots.py, zerver/actions/create_user.py, zerver/actions/default_streams.py, zerver/actions/message_delete.py, zerver/actions/reactions.py, zerver/actions/realm_domains.py, zerver/actions/realm_emoji.py, zerver/actions/realm_export.py, zerver/actions/realm_icon.py, zerver/actions/realm_linkifiers.py, zerver/actions/realm_logo.py, zerver/actions/realm_playgrounds.py, zerver/actions/realm_settings.py, zerver/actions/streams.py, zerver/actions/submessage.py, zerver/actions/user_groups.py, zerver/actions/user_settings.py, zerver/actions/users.py, zerver/tests/test_message_edit.py, zerver/tests/test_reactions.py, zerver/tests/test_submessage.py, zerver/tornado/django_api.py
django-stubs 4.2.1 gives `transaction.on_commit` a more accurate type annotation, but this exposed that mypy can’t handle the `lambda` default parameters that we use to recapture loop variables such as
```python
for stream_id in public_stream_ids:
peer_user_ids = …
event = …
transaction.on_commit(
lambda event=event, peer_user_ids=peer_user_ids: send_event(
realm, event, peer_user_ids
)
)
```
https://github.com/python/mypy/issues/15459
A workaround that mypy accepts is
```python
transaction.on_commit(
(
lambda event, peer_user_ids: lambda: send_event(
realm, event, peer_user_ids
)
)(event, peer_user_ids)
)
```
But that’s kind of ugly and potentially error-prone, so let’s make a helper function for this very common pattern.
```python
send_event_on_commit(realm, event, peer_user_ids)
```
=> django_api: Extract send_event_on_commit helper

puppet/zulip/files/hooks/pre-deploy.d/sentry.hook
This is necessary if one has different deployments (with different commit ranges) using the same projects.
See https://docs.sentry.io/product/releases/associate-commits/#using-the-cli for the API of the `sentry-cli` tool.
---
Tested with a test prod instance.  We run into this with chat.zulip.org and Zulip Cloud, where their deploy ranges step on each other unless we are explicit about the commits that each deploy contains.
<details>
</details>
=> hooks: Tell Sentry the explicit commit range.

web/styles/zulip.css
This changes prevent popover closure when scrolling of popover reaches the top or bottom.
Fixes: #25967 .
Related CZO discussion: [#issues > Incorrect scrollbar behavior in groups popover #25967](https://chat.zulip.org/#narrow/stream/9-issues/topic/Incorrect.20scrollbar.20behavior.20in.20groups.20popover.20.2325967)
=> popovers: Prevent the popover from closing on scroll.

web/styles/zulip.css
Followup to d0c1668399fd773bef7b569069dc2146e3c79a8a
fixed:
=> navbar: Fix regression where navbar didn't extend all the way.

web/src/compose.js, web/src/compose_actions.js, web/src/compose_pm_pill.js, web/src/composebox_typeahead.js, web/src/ui_init.js, web/tests/compose.test.js, web/tests/compose_actions.test.js, web/tests/compose_pm_pill.test.js, web/tests/compose_validate.test.js, web/tests/composebox_typeahead.test.js
This breaks some import cycles and brings down the metrics `126, 69` to `118, 66` measured by the https://github.com/andersk/cycle-analysis.
- For breaking import cycles for `compose_actions` module with `compose` module I used the hooks pattern.
<details>
</details>
=> Break some import cycles.

zerver/openapi/zulip.yaml
See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/2-general/topic/private.20messages.20.3D.3E.20direct.20messages/near/1588731).
This takes care of instances of "private message" and "PM" in `zerver/openapi/zulip.yaml`.
Posting this as a separate PR because this updates the API documentation, which is user-facing, as there may be more rounds of review for content/text changes than there will be for the changes in the rest of the files in the `zerver/` directory.
**Notes**:
- These changes impact 12 API documentation pages. See diff below for detailed changes.
- create-drafts
- edit-draft
- get-drafts
- get-events
- get-message
- get-messages
- get-scheduled-messages
- mute-user
- outgoing-webhooks
- register-queue
- update-realm-user-settings-defaults
- update-settings …
=> api-docs: Update `zulip.yaml` for "direct message".

analytics/tests/test_support_views.py, zerver/lib/name_restrictions.py, zerver/tests/test_external.py, zerver/tests/test_management_commands.py, zerver/tests/test_signup.py
This is primarily to prevent impersonation, such as `zulipteam`.  We
only enable these protections for CORPORATE_ENABLED, since `zulip` is
a reasonable test name for self-hosters.
<details>
</details>
=> name_restrictions: Reject anything with zulip or kandra in it.

web/styles/compose.css, web/styles/dark_theme.css
This PR aims to fix the styles of the keyboard indicator in send shortcut.
<details>
<summary>Box shadow issue:</summary>
| ![image](https://github.com/zulip/zulip/assets/53193850/614bb9e2-06dc-416b-93a3-ef379ccda975) | ![image](https://github.com/zulip/zulip/assets/53193850/dd87ae7a-41ac-4841-a689-7b2378e938bc) | 
</details>
<details>
<summary>Vertical alignment issue:</summary>
| ![image](https://github.com/zulip/zulip/assets/53193850/6fb0d96f-56b4-4748-9890-858447e347d5) | ![image](https://github.com/zulip/zulip/assets/53193850/280c7fc8-a684-48f7-88a8-6b9304386693) | 
</details>
=> compose: Fix the styles of the keyboard indicator in send shortcut.

zerver/openapi/zulip.yaml
Did a small audit of the **Streams** section in the API documentation for adding information about [stream permissions](https://zulip.com/help/stream-permissions) and about needing to be an organization administrator to use the endpoint.
See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/Peer.20subscribe.20permissions/near/1434182).
**Notes**:
- Updates the `api/subscribe` and `api/update-stream` endpoint docs to note that streams' permissions impact whether a user/admin can subscribe users and/or update a stream's permissions settings.
- Updates the `api/archive-stream` and `api/delete-topic` endpoint docs to note that they are only available to org admins.
- The `api/get-stream-topics` is updated in a separate pull request; see #26017.
--- …
=> api-docs: Update endpoints in streams section for permissions info.

web/styles/subscriptions.css
Previously, we used to have top and bottom paddings of 4px to the select elements but it was removed in a208da9c4d0 to make sure that text for the selected option is aligned properly.
All other select elements have height set to 30px, but the select elements in stream settings page had height set to "fit-content" and so they looked ugly after removing the padding.
This PR sets the height of select elements in stream settings to 30px.
Before -
After - 
<details> …
=> stream_settings: Fix height of select elements.

web/src/dialog_widget.ts, web/src/stream_edit.js
Fixes: #24535
https://user-images.githubusercontent.com/72064462/222686226-0bde482f-54c8-4d88-ab1f-f77266f9385f.mov
=> stream_edit: Remove Saving/Saved Notices and Use Loading Spinner

puppet/zulip/lib/puppet/functions/resolver_ip.rb, puppet/zulip/manifests/app_frontend_base.pp
The syntax in `/etc/resolv.conf` does not include any brackets:
```
nameserver 2001:db8::a3
```
However, the format of the nginx `resolver` directive[^1] requires that IPv6 addresses be enclosed in brackets.
Adjust the `resolver_ip` puppet function to surround any IPv6 addresses extracted from `/etc/resolv.conf` with square brackets.
Fixes: #26013.
[^1]: http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver
<details>
</details>
=> puppet: Support IPv6 nameservers.

web/src/message_view_header.js
No functional changes. This change is more consistent with how this expressions looks in other parts of the codebase.
A little cleanup commit that came out of https://github.com/zulip/zulip/pull/24345
=> search: Invert double negative with De Morgan's law.

web/templates/navbar.hbs
A little cleanup commit that came out of https://github.com/zulip/zulip/pull/24345
=> search: Remove unused `search_open` classname.

web/src/narrow.js, web/tests/narrow_activate.test.js
The `initialize` function registers a click handler, and previously it was being registered another time each time one of these calls to `initialize()` happened. The only other thing that happens in `initialize` is a call to `render_title_area`, so this commit replaces the extra calls to initialize with that.
=> message view header: Don't initalize multiple times.

web/src/compose.js, web/src/compose_actions.js, web/src/compose_banner.ts, web/src/compose_recipient.js, web/tests/lib/compose_banner.js
The reason for these changes is that we had a bug where upload banners were not cleared after closing the compose box. This change will make the code simpler and help us clear all the banners with less effort.
Related CZO discussion: [#issues > Incomplete Upload banner remains on closing compose](https://chat.zulip.org/#narrow/stream/9-issues/topic/Incomplete.20Upload.20banner.20remains.20on.20closing.20compose)
=> compose_banner: Remove uploads banners when clearing compose box.

web/src/narrow.js
In commit #25837, we added in a check for the user's mark as read policy in the frontend for `by_topic` and `by_recipient` narrowing. In that change, the assumption was that for both functions, it was sufficient to check only for whether the user policy was to never mark as read.
But because the `by_recipient` function may narrow to an interleaved stream view, it is possible that message will be marked as read when the user did not expect it to be when they have conversation views only as their mark as read  policy.
For example, the user marked all the messages in a topic narrow as unread and then used the `S` key shortcut to navigate back to the stream view. Currently, the message that was selected in the topic narrow would be marked as read even though the user has navigated to a stream …
=> narrow: Mark as read in `by_recipient` based on case ("dm" or "stream").

puppet/zulip/manifests/postgresql_base.pp, puppet/zulip/templates/postgresql/pgroonga_setup.sql.template.erb, scripts/lib/upgrade-zulip-stage-2, scripts/setup/create-pgroonga.sql, scripts/setup/pgroonga-config, tools/setup/postgresql-init-dev-db
Updating the pgroonga package is not sufficient to upgrade the extension in PostgreSQL -- an `ALTER EXTENSION pgroonga UPDATE` must explicitly be run[^1].  Failure to do so can lead to unexpected behavior, including crashes of PostgreSQL.
Expand on the existing `pgroonga_setup.sql.applied` file, to track which version of the PostgreSQL extension has been configured.  If the file exists but is empty, we run `ALTER EXTENSION pgroonga UPDATE` regardless -- if it is a no-op, it still succeeds with a `NOTICE`:
```
zulip=# ALTER EXTENSION pgroonga UPDATE;
NOTICE:  version "3.0.8" of extension "pgroonga" is already installed
ALTER EXTENSION
```
The simple `ALTER EXTENSION` is sufficient for the backwards-compatible case[^1] -- which, for our usage, is every upgrade since 0.9 -> 1.0.  Since …
=> pgroonga: Run upgrade SQL when pgroonga package is updated.

web/styles/dark_theme.css
Followup to 239b6737c0a58e3d86d2c0d1c9e684fe994ad72b
I forgot to add darkmode support to my previous followup, sorry about that.
Current state of main:
with this PR:
=> header: Fix dark mode header box-shadow.

web/styles/components.css, web/styles/zulip.css
This PR darkens both the light- and dark-mode bot icons for better, more consistent contrast with the bot username text. (The dark-mode adjustment is subtler than the one for light mode.)
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/bot.20icon)
| Before, light mode | After, light mode |
| --- | --- |
| <img width="674" alt="bot-icon-light-before" src="https://github.com/zulip/zulip/assets/170719/3806baf4-353e-4088-9483-4fb8b835a9eb"> | <img width="674" alt="bot-icon-light-after" src="https://github.com/zulip/zulip/assets/170719/858289fc-598b-427a-acf9-ea2646837304"> |
| Before, dark mode | After, dark mode |
| --- | --- |
| <img width="674" alt="bot-icon-dark-before" …
=> bot_icon: Adjust bot-icon color for light and dark modes.

web/src/portico/help.js, web/src/portico/tabbed-instructions.ts, zerver/lib/markdown/tabbed_sections.py, zerver/tests/test_templates.py
The `tabbed_instructions` widget used for both language toggles in our API documentation and app toggles in our Help Center documentation misleadingly calls the identifier for the tab `language` in local variables and its interface.
- Renames local variable `language` -> `tab_key`.
- Renames HTML data attributes `data-language` -> `data-tab-key`.
- Updates variable names in `tabbed_sections.py`.
Fixes #24669.
Replaces #25007 and #24760.
**Remarks**
I split the work into two commits to make the PR a bit easier to review, but maybe it would be better to put all the changes in a single commit?
<details> …
=> widgets: Rename confusing variable name in `tabbed_instructions.ts`.

web/src/portico/help.js, web/styles/portico/markdown.css
This traverses the DOM to the `<pre>` element containing the copyable material of interest.
The button is attached to the `.codehilite` element to ensure that the button does not move with horizontally-scrolling code content that exceeds the width of the content column, as happens frequently at mobile scales or for very long lines of content.
See [CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/copy.20code.20button.20on.20mobile)
Fixes #26093.
<details> …
=> docs: Correct scope of copied material from copy button.

scripts/setup/pgroonga-config
dc2726c81465 removed these statements, but c8ec3dfcf6dd accidentally brought one back.  Remove it.
Fixes: https://github.com/zulip/zulip/pull/26097#discussion_r1240435764
<details>
</details>
=> pgroonga: Remove 'GRANT USAGE' statement again.

web/src/filter.js, web/src/search_suggestion.js, web/tests/filter.test.js
Changing this since wobbly naming on HTML variables is dangerous.
A little cleanup commit that came out of #24345
=> filter: Rename describe to describe_html.

help/bots-and-integrations.md, zerver/openapi/zulip.yaml
Updates the main description for the [`/api/get-stream-topics`](https://zulip.com/api/get-stream-topics) endpoint so that it is clear that the topics for private streams with protected history are limited to the topics / messages the user has access to.
And updates that documentation and the help center documentation for bot permissions / abilities, to clarify that bots have the same restriction and can only access messages / topics that are sent after the bot (not the bot's owner) subscribed to the stream.
See [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/API.20get.20topics/near/1592168).
---
<details>
<summary>Get topics in a stream</summary>
[Current documentation](https://zulip.com/api/get-stream-topics) …
=> api-docs: Clarify what topics are returned by `/api/get-stream-topics`.

web/src/rendered_markdown.js
Updates a new code comment to use "direct message" instead of "private message" in `web/src/rendered_markdown.js`. 
After this change, `git grep 'private message web/` returns no matches. This was missed in the original audit done in #26060 because the changes that added the comment were not merged yet.
=> rendered-markdown: Update reference to "private message" in comment.

zerver/data_import/slack.py, zerver/tests/test_slack_importer.py
This is a follow-up to 4c8915c8e4aef037736e8024faf0457f07a81e1e, for the case when the `team:read` permission is missing, which causes the `team.info` call itself to fail.  The error message supplies information about the provided and missing permissions -- but it also still sends the `X-OAuth-Scopes` header which we normall read, so we can use that as normal.
<details>
</details>
=> slack: Handle the special case of permissions denied on team.info call.

zerver/openapi/zulip.yaml
Updates the main descriptions for the [mute a user](https://zulip.com/api/mute-user) and [unmute a user](https://zulip.com/api/unmute-user) endpoint documentation. Also, revises the `muted_user_id` parameter description and **Changes** note for feature level 188.
The feature level 188 changes were made in #26005.
<details>
<summary>Mute a user - main description</summary>
[Current documentation](https://zulip.com/api/mute-user)
</details>
<details>
<summary>Unmute a user - main description</summary>
[Current documentation](https://zulip.com/api/unmute-user)
</details>
<details>
<summary>muted_user_id parameter</summary>
[Current documentation](https://zulip.com/api/mute-user#parameter-muted_user_id)
</details>
---
<details> …
=> api-docs: Update mute and unmute user endpoint documentation.

api_docs/changelog.md, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_openapi.py
As noted in [this discussion on CZO](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/peer_add.2Fremove.20examples.20.26.20changes/near/1595427), the examples for the different events returned in the [`GET /events`](https://zulip.com/api/get-events) endpoint documentation were not being tested, and therefore prone to becoming out-of-date when/if the API for a particular event was changed/updated.
Here we add test coverage that validates the event example in the documentation against the event schema in the documentation. There are 5 prep commits with updates/fixes that were found through adding the test coverage.
**Notes**:
- If there was an API feature level changelog entry or **Changes** note that also needed to be updated/added for the example event that was being …
=> api-docs: Fixes errors in example events and adds test coverage for documented events.

web/styles/dark_theme.css
CZO thread: https://chat.zulip.org/#narrow/stream/9-issues/topic/top.20navbar.20bottom.20border/near/1598791
=> navbar: Fix background-color inconsistency in dark theme.

zerver/tests/test_user_groups.py
This improves the user group test cases by verifying that changes are indeed made via API calls.
This extracts helpers and adds additional checks when appropriate for test cases where updates occur.
<details>
</details>
=> user_groups: Improve test cases for user groups.

web/src/server_events.js, web/tests/server_events.test.js
In commit 92ad98814429c8, we removed the local echo code that tried to re-render locally echoed messages that were rendered right before a server/browser restart. These changes removed the only event triggered by `"home_view_loaded.zulip"`.
This removes the remaining `"home_view_loaded.zulip"` event trigger in `web/src/server_events.js` since it no longer triggers any events.
This is was noted when working on #26023.
---
<details>
</details>
=> server-events: Remove unused "home_view_loaded.zulip" event trigger.

api_docs/changelog.md, api_docs/include/rest-endpoints.md, version.py, zerver/openapi/openapi.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_realm_emoji.py, zerver/views/realm_emoji.py, zproject/urls.py
This endpoint was previously marked as `intentionally_undocumented` but that was a mistake.
Removed `intentionally_undocumented` and added proper documentation with valid `python_example` for this Endpoint.
Fixes: #24084
[CZO](https://chat.zulip.org/#narrow/stream/378-api-design/topic/Endpoint.20for.20delete.20emoji)
<details>
</details>
=> docs: Add documentation for delete emoji endpoint.

web/src/settings_emoji.js, web/templates/settings/add_emoji.hbs
Before this commit if a user pressed enter to submit the add emoji form the uploaded emoji was getting cleared.
This was happening because when we pressed enter the browser tried to submit the form, because we had two buttons inside that form one for clearing uploaded emoji and one for uploading emoji they were being treated as "submit" button and hence their callback ran which in result was responsible for the bug.
Fixed this by explicitly setting the `type` attribute for those buttons to `type=button` so that they will not be treated as "submit" button. Also added the `form_id` option for `dialog_widget` which is needed if we do want to correctly submit the form by pressing enter.
Fixes: #24972
<details> …
=> settings_emoji: Fix file upload bug in upload emoji modal.

zerver/tests/test_docs.py
I also do some general cleanup.
=> Improve api doc tests by eliminating 218 Zephyr-related checks

zerver/lib/webhooks/git.py, zerver/webhooks/github/tests.py, zerver/webhooks/github/view.py
The URL is not the correct one and redirects to an API page. Also, the [payload](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=labeled#issues) has no `html_url` for the label so we cannot show a URL for that.
<details>
</details>
=> integrations: Remove label URL from GitHub issue labeled notifications.

web/src/hashchange.js, web/src/narrow.js, web/src/search.js, web/styles/search.css, web/tests/hashchange.test.js, web/tests/narrow_activate.test.js, web/tests/search.test.js
This is logic from 10 years ago (dbc4798594c4aa859013e46fcbe94977fd43cdf4) that is no longer relevant. It seems like we used to show the search bar open all the time and only showed the buttons when there was focus in the search bar. Now we close the search bar when it's not being used, and no longer need to update button visibility or disable the search close button.
I tested this visually and it seemed to make no difference, but would appreciate another person trying it as well.
=> search: Stop disabling and enabling the search close button.

web/src/input_pill.ts
This fixes a bug reported here:
https://chat.zulip.org/#narrow/stream/9-issues/topic/compose.20box.20placeholder/near/1591988
before:
after:
=> compose: Update textbox placeholder text when selecting a recipient.

web/src/message_list_view.js
This PR fixes the bug where the edited notice is not displayed for edited/moved messages when the edit_history is disabled for the organization. However, this is incorrect because the edited notice should still be shown for messages that are edited/moved, even if the edit_history is disabled. This issue occurred because the edit_history variable was not set in the message object when the edit_history is disabled. Therefore, in this case, we check for the availability of last_edit_timestr. If it is available, we display the edited notice. Since we cannot determine if the message was moved or edited, we show the edited notice for both cases.
-----------------
Fixes: [CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/edited.20notice.20disappears.20on.20refreshing)
------------- …
=> message_feed: Fix edited notice to appear for disabled edit_history.

tools/test-backend
If the number of threads is not specified while profiling then use a single thread. This is because profiling across multiple threads (earlier default behaviour) may obscure the accurate measurement of which functions are the most costly due to thread blocking.
More context: https://chat.zulip.org/#narrow/stream/3-backend/topic/test-backend.20performance/near/1601293.
=> test-backend: Enable single-threaded profiling when thread count is unspecified.

puppet/zulip/files/nginx/uwsgi_params, puppet/zulip/files/nginx/zulip-include-common/proxy, puppet/zulip/manifests/app_frontend_base.pp, puppet/zulip/templates/nginx/trusted-proto.template.erb, zerver/middleware.py, zproject/computed_settings.py, zproject/test_extra_settings.py
Combine nginx and Django middlware to stop putting misleading warnings
about `CSRF_TRUSTED_ORIGINS` when the issue is untrusted proxies.
This attempts to, in the error logs, diagnose and suggest next steps
to fix common proxy misconfigurations.
See also #24599 and zulip/docker-zulip#403.
<details>
</details>
=> middleware: Detect reverse proxy misconfigurations.

web/src/click_handlers.js, web/src/server_events_dispatch.js, web/src/zcommand.js, web/tests/dispatch.test.js
`update_recipient_bar_background_color` changes in a paint after change in theme without using `requestAnimationFrame` to make sure they happen in the same paint.
I am not able to capture this change in my GIF tool properly but color changes are definitely happening together now with the message header.
discussion: https://github.com/zulip/zulip/pull/25777#issuecomment-1564652487
=> theme: Change recipient bar color and theme in the same paint.

web/src/setup.js
This error is logged if there are 0 or 2+ elements, so the generic language here is meant to cover both cases.
[CZO discussion](https://chat.zulip.org/#narrow/stream/464-kandra-js-errors/topic/Error.3A.20Expected.20one.20element.20in.20jQuery.20set.2C.20found.20more/near/1600194)
<details>
</details>
=> blueslip: Simplify expectOne error message.

web/src/popover_menus.js
This addresses an edge case where a user viewing a message in an edit mode (either as editable or source) triggers the `i` hotkey to trigger the message controls, which are not present and therefore not triggerable.
[CZO discussion](https://chat.zulip.org/#narrow/stream/464-kandra-js-errors/topic/Error.3A.20Expected.20one.20element.20in.20jQuery.20set.2C.20found.20more/near/1600194)
<details>
</details>
=> message_edit: Suppress message controls popover in edit views.

docs/production/scim.md
add_scim_client was removed in 55342efd33cc482daecdf9d0f560b4f32122540f.
This is trivial enough that I don't think needs any other review, so will tag `integration review`
=> docs: Update SCIM doc to not mention add_scim_client.

web/src/compose_tooltips.js, web/src/giphy.js, web/src/popovers.js, web/styles/compose.css, web/styles/popovers.css, web/templates/compose_control_buttons.hbs, web/templates/giphy_picker.hbs
This pull request introduces an API for popovers that can be utilized outside of `popover_menus`. Currently, it is relatively straightforward, as we are simply exporting the `register_popover_menu` function from `popover_menus`. However, there are a few questions worth discussing:
1. In this PR, I have removed the line that was hiding the Giphy popover from the `hide_all_except_sidebars` function. This change was necessary because the popover was closing itself due to being called inside the `onShow` method of the Giphy popover. It would be beneficial to discuss the approach we take regarding hiding popovers. Perhaps we should consider having a function called `hide_all_except_instance` to be used in the `onShow` method of the tooltip. I am currently uncertain about the best way to …
=> Migrate giphy popover to tippy.

tools/setup/generate_zulip_bots_static_files.py
This PR adds code to copy `assets` subdirectory of individual bots that are present in our `python-zulip-api` repository to `static/generated/bots/` folder. This is required as the documentation of some integrations require these asssets but are not being loaded due to the absence of the `assets` in their directory.
For eg. `zulip_bots/zulip_bots/bots/xkcd/assets/xkcd-help.png` will be copied to `/static/generated/bots/xkcd/assets/xkcd-help.png` 
- Some changes were required to the `copyfiles` function as unlike `doc.md` the images are present inside `assets` subdirectory.
CZO Discussion: [Link](https://chat.zulip.org/#narrow/stream/9-issues/topic/http.20500.20in.20xkcd.20bot.20docs)
<details> …
=> tools: Copy "assets" subdirectory of bots to "static/generated/bots/".

web/src/stream_ui_updates.js
It might be possible that an event can come while we are in the middle of rendering the stream settings overlay. This can cause `hash_util.is_editing_stream(sub.stream_id)` to be `true` while the `sub/unsub` button still hasn't been rendered yet.
=> stream_ui_updates: Check if sub/unsub button is rendered.

web/src/stream_edit.js, web/styles/modal.css, web/templates/confirm_dialog/confirm_deactivate_stream.hbs
Archiving a user/stream notification stream disables user/stream notifications.This commit adds a warning that notifications will be disabled while archiving any notification stream.
This PR address the review comments of #23735.
Fixes: #22110.
<details>
</details>
=> streams: Warn when archiving a notification stream.

web/src/upload.js, web/styles/compose.css, web/styles/dark_theme.css, web/templates/compose_banner/upload_banner.hbs, web/tests/upload.test.js
-  Add a cancel button to the upload banner, replacing the previous close icon. Now, the cancel button is used to cancel the upload process, while the close icon is used to remove the upload banner without interrupting the upload
- To maintain consistency with other banners, the cancel button's dimensions and color have been adjusted to match the style of other buttons present in different banners.
--------------------------------
Fixes: #21156
CZO: [Thread](https://chat.zulip.org/#narrow/stream/137-feedback/topic/disable.20send.20while.20uploading)
---------------------------------
<details>
<summary>Demo:</summary>
<br>
</details>
<details>
<summary>New Banner:</summary>
<br>
</details>
<details>
<summary>Cancel Button:</summary>
<br>
</details> …
=> upload_banner: Add a cancel button.

web/src/portico/help.js, web/styles/portico/markdown.css
In this PR, I set the cursor style of the copy code button in portico pages to pointer, added a hover effect and added a "Copy code" tooltip to the button.
Fixes: https://github.com/zulip/zulip/issues/25962
Before:
After:
<details>
</details>
=> Polish UI for portico pages copy-codeblock button

tools/test-js-with-node, web/shared/src/poll_data.js, web/shared/src/poll_data.ts
Migrates `poll_data` to TypeScript.
- I used zod schemas for validating incoming/inbound data types.
- Refactored to declare `handle` object inside the constructor of the class.
<details>
</details>
=> ts: Migrates `web/shared/poll_data` to typescript.

web/src/composebox_typeahead.js, web/tests/composebox_typeahead.test.js
Users are permitted to see  wildcard mentions for all/everyone during message composition in large streams according to `restrict wildcard mentions` policy.
Fixes #25429
</details>
=> compose: Show wildcard mentions according to policy.

zerver/openapi/zulip.yaml, zerver/tests/test_submessage.py
Added an additional test case to `test_submessages.py` for testing the message object containing `submessages` meta data.
Previous to this commit we were never validating the `submessage` schema in the `message` objects.
Fixes #25896.
<details>
</details>
=> tests: Improve automated tests for submessages.

web/src/compose_ui.js, web/src/upload.js, web/tests/upload.test.js
Fixes #26037.
> If you are uploading something and you erase the placeholder from the textarea of the uploading file, the banner still remains and shows as if the upload is running. It even appears to finish until the last step, but nothing can be seen in the textarea. Consequently, the message can't be sent due to the empty textarea.
>
> The proposed solution: if an upload finishes and there's no placeholder text in the composebox, the file markdown is appended to the end of the message that's currently in the composebox.
Demo for composebox:
Demo for message edit:
I confirmed regular upload still inserts the file markdown as it did before.
=> upload: Append file markdown to textarea when placeholder is missing.

web/src/message_edit.js, web/src/upload.js, web/tests/upload.test.js
This change aims to resolve a bug where canceling message editing during uploading incorrectly displays that the file already exists. However, you can still safely send the file. The issue here is the erroneous error message appearing when it shouldn't.
Related CZO [discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/additional.20upload.20if.20the.20edit.20is.20cancelled).
=> uploads: Delete uppy files on message edit cancel.

docs/images/architecture_simple.svg, static/images/landing-page/why-zulip/slack-unreads.svg, static/images/landing-page/why-zulip/zulip-reply-later.svg, static/images/landing-page/why-zulip/zulip-topics.svg, web/src/bundles/common.ts, web/styles/app_components.css, web/styles/compose.css, web/styles/left_sidebar.css, web/styles/lightbox.css, web/styles/popovers.css, web/styles/portico/billing.css, web/styles/portico/landing_page.css, web/styles/portico/markdown.css, web/styles/portico/portico.css, web/styles/portico/portico_signin.css, web/styles/portico/stats.css, web/styles/search.css, web/styles/settings.css, web/styles/subscriptions.css, web/styles/tooltips.css, web/styles/zulip.css
This is to overcome the limitations of previous static font, which didn't allow us to use various font widths.
There are no visual changes that I can see.
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/font.20weight.20500
=> css: Use Source Sans 3 VF.

zerver/actions/create_user.py, zerver/actions/default_streams.py, zerver/actions/streams.py, zerver/lib/default_streams.py, zerver/lib/events.py, zerver/lib/streams.py, zerver/tests/test_invite.py, zerver/tests/test_signup.py, zerver/tests/test_subs.py, zerver/views/streams.py
This improves `test_events.py` by about 10%, and it does so by fixing the actual app.
=> page load: Replace expensive default streams query with a sane query.

zerver/views/sentry.py
This helps reduce the impact on busy uwsgi processes in case there are slow timeout failures of Sentry servers.  The p99 is less than 300ms, and p99.9 per day peaks at around 1s, so this will not affect more than .1% of requests in normal operation.
This is not a complete solution (see #26229); it is merely stop-gap mitigation.
<details>
</details>
=> sentry: Reduce http timeout.

web/e2e-tests/navigation.test.ts, web/styles/zulip.css, web/templates/message_view_header.hbs
This bad rendering was the result of unwanted css applied in the stream description. In message view header, the stream link (title) we have defined has css defined but the markdown rendered stream link in stream description had the same class resulting in unwanted css applied to it.
Fixes: #25961.
=> message_view_header: Fix bad rendering of stream links in description.

web/src/compose_recipient.js, web/src/message_edit.js, web/src/stream_data.js, web/src/stream_popover.js, web/styles/compose.css, web/styles/popovers.css, web/templates/move_topic_to_stream.hbs, web/tests/stream_data.test.js
I was trying to abstract and migrate everything at once but it was driving me insane, so instead a better approach would be to just migrate everyone one by one and then abstract it so that the abstraction can benefit from all the use cases and it is easier to do.
=> Migrate stream selection dropdown in move topic modal to use tippy dropdown library.

zerver/decorator.py, zerver/lib/exceptions.py, zerver/lib/response.py, zerver/tests/test_decorators.py, zerver/webhooks/github/tests.py, zerver/webhooks/github/view.py, zerver/webhooks/pagerduty/tests.py, zerver/webhooks/updown/fixtures/unknown_event.json, zerver/webhooks/updown/tests.py
The webhook now logs a message instead because adding new event types unrecognized by it would be expected.
Fixes #24721.
<details>
</details>
=> webhooks: Ignore unknown events from updown.io.

help/disable-welcome-emails.md, zerver/actions/create_user.py, zerver/lib/email_notifications.py, zerver/management/commands/deliver_scheduled_emails.py, zerver/tests/test_email_notifications.py, zerver/tests/test_example.py, zerver/tests/test_realm.py, zerver/tests/test_signup.py, zerver/tests/test_users.py, zerver/views/development/email_log.py, zproject/urls.py
Separates the `followup_day1` email from the scheduled welcome emails, and instead sends the email directly when a new user account is created.
Fixes #25268.
**Notes**:
- There are 4 small prep commits with minor updates to tests and code comments.
- Did the changes to `followup_day1` email in two steps:
- First, I removed it from `enqueue_welcome_emails`, creating a specific function for the `followup_day1` email and always scheduling it (without delay) when a new (human) user is created/processed.
- Then, I switched it from being scheduled (without delay) to being sent via `send_email` in a separate commit. If we want to keep the email as a scheduled email, then it is easy to drop this commit, but it seemed cleaner for the implementation to make this change.
- I didn't change the email …
=> welcome-emails: Separate followup_day1 email from welcome emails.

web/src/message_list_view.js
When a message list view rerenders a locally echoed message the message recipient header is also rerendered, which then removes the `"sticky_header"` class if it was present. If rerendering the message triggers a scroll event, then the `"sticky_header"` class is updated.
<details>
<summary>console trace on message_list_view._rerender_header</summary>
</details>
But it is possible that the rerendering of the message will not trigger a scroll event, which means the recipient header is no longer updated and the next calculation for the message list view's `_scroll_limit` for the top of the feed will not include the sticky header and the currently selected message may be scrolled partially or completely under the message header recipient bar.
Here we add a check for the current message list …
=> message-list-view: Update sticky header in rerender_messages.

web/src/message_list_tooltips.js, web/src/message_list_view.js, web/templates/edited_notice.hbs, web/templates/message_edit_notice_tooltip.hbs
- First line: Last {moved/edited} [date/time]. [note: no parens around date, don't capitalize date unless required by rules of English, i.e., "today", not "Today"]
- Second line, shown only if edit history is enabled in the organization: Click to view edit history.
---
Fixes: #23075
----------------------
<details>
<br>
<br>
</details>
<details>
<br>
<br>
</details>
<details> …
=> message_feed: Improve edited/moved tooltip.

web/src/scheduled_messages.js, web/src/scheduled_messages_overlay_ui.js
This PR changes the datatype of scheduled_messages from an array to a dictionary type.
The aim of this PR is to reduce the higher cost of updation & deletion in array type.
With the dictionary datatype, we can perform operations on the data with the use of the message_id.
The dictionary stores a message object which is referenced by a key.
The key format is "message-<scheduled_message_id>".
Fixes: #25557 
<details>
</details>
=> scheduled_messages: Update datatype from array to dictionary

zerver/decorator.py, zerver/lib/logging_util.py, zerver/lib/request.py, zerver/middleware.py, zerver/tests/test_decorators.py, zerver/webhooks/bitbucket2/tests.py, zerver/webhooks/bitbucket2/view.py, zerver/webhooks/github/view.py, zproject/computed_settings.py, zproject/sentry.py
This mechanism was a source of confusing magic and a correctness issue in the presence of asynchronous tasks. It was only used in the Sentry context builder and the webhook logging formatters, and it’s easy to replace in both.
Cc @alexmv
=> Remove get_current_request and RequestContext middleware

web/src/compose.js
Previously the flatpickr was always set to show at the top but this led to it being cut off when the message was at the top of the screen -- happens only when someone is editing a message.
The `position` option change is documented [here](https://flatpickr.js.org/options/).
| ![Screenshot from 2023-07-10 01-50-11](https://github.com/sbansal1999/zulip/assets/35286603/cef0b9a8-772b-477a-8714-fdc1d5ee7e23) | ![Screenshot from 2023-07-10 01-49-27](https://github.com/sbansal1999/zulip/assets/35286603/3e4f567d-3c00-4af1-83e9-ea1bd55952b9)  |
| ![Screenshot from 2023-07-10 01-50-00](https://github.com/sbansal1999/zulip/assets/35286603/ed93e95b-324c-4ba8-bb67-0fc75430e959) | ![Screenshot from 2023-07-10 …
=> compose: Allow flatpickr to automatically choose the direction.

web/src/message_list.js
Users won't press accidentally "mark topic as resolved" and "mute this topic" buttons while renaming topic.
Fixes #25840
</details>
=> narrow: Hide inconsequential buttons while renaming topic.

web/src/info_overlay.js, web/src/popovers.js, web/styles/message_row.css, web/styles/zulip.css, web/tests/popovers.test.js
This PR removes remaining references to a class (`.sender_name-in-status`) that was eliminated as part of #25997.
It also aligns the info-overlay example for me-messages to use the `.sender_name` class, along with the `status-message` class, so that the example always remains in concord with live code. (In the screenshots below, you can see the extra space after Iago's name is no longer present because of how usernames are now run inline with the me-message text.)
| --- | --- |
| ![info-overlay-before](https://github.com/zulip/zulip/assets/170719/45e843fa-d45b-453e-8a8e-8c191aa7e34e) | ![info-overlay-after](https://github.com/zulip/zulip/assets/170719/75e00f93-0bd3-45a6-a6c5-bdd70d1cef07) |
<details> …
=> me_messages: Sender-name cleanup.

api_docs/changelog.md, version.py, zerver/actions/streams.py, zerver/openapi/zulip.yaml, zerver/tests/test_events.py, zerver/tests/test_subs.py
We did not send the stream creation events when subscribing guests to public streams while we do send them when subscribing non-admin users to private streams.
This commit adds code to send the stream creation events when subscribing guests to public streams, so the clients can know that stream exists and fixes the bug where client tries to process a subscription add event for a stream which it does not know about.
<details>
</details>
=> streams: Send stream creation events when subscribing guests.

zerver/webhooks/grafana/doc.md
This updates the documentation for Grafana Integration -- the process for creating an integration has changed since Grafana 8.3.
<details>
<summary> <b>Screenshots:</b> </summary>
|---|---|
|![image](https://github.com/sbansal1999/zulip/assets/35286603/89baf286-a1c8-4f77-9a16-f570f909908c) | ![Screenshot from 2023-06-20 01-01-48](https://github.com/sbansal1999/zulip/assets/35286603/8f5b8b4b-37cd-456b-9dbe-07c99a6522fa)
|![image](https://github.com/sbansal1999/zulip/assets/35286603/73143919-4125-416c-a259-69f2c40a282d)|![Screenshot from 2023-06-20 01-01-58](https://github.com/sbansal1999/zulip/assets/35286603/40bf3908-d12b-4c0c-be8b-2404d26d2ef7) |
</details>
<details>
[Self-reviewed](https://zulip.readthedocs.io/en/latest/contribu …
=> integrations: Update documentation for Grafana Integration.

templates/zerver/emails/missed_message.html, templates/zerver/emails/missed_message.txt, web/src/markdown.js, web/tests/markdown.test.js, zerver/actions/message_edit.py, zerver/actions/message_send.py, zerver/lib/email_notifications.py, zerver/lib/markdown/__init__.py, zerver/lib/message.py, zerver/lib/notification_data.py, zerver/lib/push_notifications.py, zerver/lib/soft_deactivation.py, zerver/lib/test_classes.py, zerver/migrations/0331_scheduledmessagenotificationemail.py, zerver/models.py, zerver/tests/test_email_notifications.py, zerver/tests/test_event_queue.py, zerver/tests/test_events.py, zerver/tests/test_message_edit.py, zerver/tests/test_message_edit_notifications.py, zerver/tests/test_message_send.py, zerver/tests/test_notification_data.py, zerver/tests/test_push_notifications.py, zerver/tests/test_soft_deactivation.py, zerver/tornado/event_queue.py
This carries forward the work in #22855
* **First Commit**: [Review comment](https://github.com/zulip/zulip/pull/22855#discussion_r962193044)
* **Second & Third Commit**: [Comment](https://github.com/zulip/zulip/pull/22855#issuecomment-1239758013)
* **Fourth Commit**: [Review Comment](https://github.com/zulip/zulip/pull/25828#discussion_r1210158168), [CZO](https://chat.zulip.org/#narrow/stream/3-backend/topic/.40topic.20mention/near/1581610)
* **Fifth Commit**: Adds a 'has_topic_wildcards' instance variable to the 'MentionData' class for the detection of - possible topic wildcards mentions.
* **Sixth Commit**: Fetch users to be notified of @topic mentions.
Note:
Meaning of '**possible** topic wildcards mention': Here, the 'has_topic_wildcards' flag is set to true when there is a …
=> mention: Implement notification part of @topic mention.

web/src/stream_list.js, web/tests/stream_list.test.js
The `stream_list.build_stream_list()` function is responsible for rendering the stream list in the left sidebar. Previously, it uses `topic_list.clear()` to clear the `active_widgets` that tracks active stream(s) in the left sidebar. This led to a bug where rendering stream list after adding or removing a stream through `build_stream_list()` while a stream was zoomed in ("more topics" clicked) didn't fully exit the "more topics" view. So clicking "BACK TO STREAMS" throws an exception with the message "Error: Unexpected number of topic lists to zoom out" because `active_widgets`, cleared by `topic_list.clear()`, became inaccessible.
To address this issue, instead of clearing the topics list with `topic_list.clear()`, the code now ensures the closure of the zoomed stream by using …
=> Fix exception exiting "more topics" after losing access to a stream

web/src/peer_data.ts, web/tests/peer_data.test.js
This converts the module `peer_data.js` to TypeScript.
<details>
</details>
=> ts: Migrate `peer_data.js` module to TypeScript.

web/src/input_pill.ts, web/src/user_group_pill.ts, web/src/user_groups.ts, web/tests/user_group_pill.test.js
Converts `user_group_pill` widget to typescript. Uses generic type definitions from `input_pill` widget module.
<details>
</details>
=> ts: Migrate `user_group_pill` module to TypeScript.

web/src/click_handlers.js, web/src/hotkey.js
Previously clicking on a message in search results opened the compose box. This was not great, because search views show messages outside of their context, and replying to a message without the context of possible more recent messages sent to that narrow can result in a bad experience.
This commit prevents the composebox from opening on click and instead moves the user to a near view for the message.
Fixes #21217.
=> search: Link messages in search results to near view.

web/src/filter.js, web/src/search.js, web/src/search_suggestion.js, web/templates/search_description.hbs, web/tests/filter.test.js, web/tests/search_suggestion.test.js
This comes out of a request Vlad had in #24345
before:
after:
=> search: Bold text in first search suggestion

tools/test-js-with-node, web/src/stream_settings_containers.js, web/src/stream_settings_containers.ts
Added assertion to enforce `sub` is not `undefined` and thus type safe for the rest.
Added type annotation to function parameter and return value.
=> ts: Convert `stream_settings_containers.js` to TypeScript.

zerver/actions/streams.py, zerver/management/commands/reactivate_stream.py, zerver/tests/test_subs.py
Fixes #601.
<details>
</details>
=> management: Add a reactivate-stream command.

docs/subsystems/caching.md, zerver/data_import/rocketchat.py, zerver/lib/avatar_hash.py, zerver/lib/cache.py, zerver/lib/utils.py, zerver/migrations/0032_verify_all_medium_avatar_images.py, zerver/models.py
It’s unclear what was supposed to be “safe” about this wrapper. The `hashlib` API is fine without it, and we don’t want to encourage further use of SHA-1.
=> utils: Remove make_safe_digest wrapper

docs/production/deployment.md, puppet/zulip/files/postgresql/env-wal-g
Using S3's "infrequent access" storage class can save some money on larger backups.
Tested in a test production instance.  Note that this changes the storage class for _new_ backups but does not adjust old ones.  You can `aws cp --storage-class STANDARD_IA --recursive s3://some-bucket-name/ s3://some-bucket-name/` to adjust the storage class on existing files.
<details>
</details>
=> wal-g: Support alternate S3 storage classes.

web/styles/recent_topics.css
Looks like some changes actually improved aligned of this icon so that we don't need this hacky margin.
before:
after:
=> recent_topics: Fix clear search button misaligned.

scripts/lib/check-database-compatibility, scripts/lib/upgrade-zulip-stage-2
The claim in the comment from c8ec3dfcf6dd, that we can and should use the current deploy's venv, misses one key case -- when upgrading the operating system, the current deploy's venv is unworkable, since it was configured for a previous version of Python.  As such, any attempt to load Django to verify the version of PostgreSQL it is talking to must happen after the venv is configured.
Move the database version check into `scripts/lib/check-database-compatibility`, which also moves it after the new venv is configured.
Because we no longer reliably know, at `apt-get upgrade` time, what version of PostgreSQL is installed, we hold all versions of the pgroonga packages.
<details> …
=> upgrade: Check PostgreSQL versions after venv setup.

puppet/zulip/files/postgresql/wal-g-exporter
The `time` field is based on the file metadata in S3, which means that touching the file contents in S3 can move backups around in the list.
Switch to using `start_time` as the sort key, which is based on the contents of the JSON file stored as part of the backup, so is not affected by changes in S3 metadata.
<details>
</details>
=> wal-g: Use "start_time" field, not "time" which is S3 modified-at.

docs/production/upload-backends.md, zerver/lib/transfer.py, zerver/lib/upload/s3.py, zproject/default_settings.py, zproject/prod_settings_template.py
Uploads are well-positioned to use S3's "intelligent tiering" storage class.  Add a setting to let uploaded files to declare their desired storage class at upload time, and document how to move existing files to the same storage class.
<details>
</details>
=> uploads: Allow uploads to set storage class.

web/shared/src/poll_data.ts
According to this [CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/poll.20responses.20removed.20or.20missing.3F) we have a bug in `poll_widget` which causes it to not show vote counts on old polls.
This was most probably introduced in this commit [ae6063807b64484a1162def4750037e341c75820](https://github.com/zulip/zulip/commit/ae6063807b64484a1162def4750037e341c75820).
<details>
</details>
=> poll_data: Revert to using "canned" instead of -1.

puppet/zulip/templates/nginx.conf.template.erb
=> nginx: Remove gzip_disable "msie6"

api_docs/changelog.md, api_docs/construct-narrow.md, version.py, web/src/message_fetch.js, zerver/lib/narrow.py, zerver/tests/test_message_fetch.py
Expands support for the message ID operands for "near" and "id" operators to be either a string or an integer. Previously, these operands were always validated as strings.
Also, checks that the value for the operand of the "near" operator is an integer and returns the same error as the "id" operator if it is not.
See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/378-api-design/topic/.60id.3A123.60.20narrow.20in.20.60GET.20.2Fmessages.60/near/1591465)
**Notes**:
- The `id` parameter already was written to support both string and integer formats, so mostly just extended the tests for both cases and adjusted the documented operators that accept integer IDs.
- Expanded the `near` operator to mirror the `id` operator in the check for the error case.
- Manually tested via …
=> narrow: Support string and integer encoding "id" operator.

web/src/filter.js, web/tests/filter.test.js
[CZO conversation](https://chat.zulip.org/#narrow/stream/101-design/topic/mentions.20narrow)
Reverts 399dc5046b27ecd92e4fe2885064cda2e14eb5b5 which reverted 5e97ec9ad95ea8ab6810b2fea7ce423f5a4462a2, which we can bring back now that we display a banner when messages can't be marked as read.
=> message view: Don't mark message as read in mentions view.

help/format-your-message-using-markdown.md, help/include/all-messages.md, help/include/invite-users.md, help/include/open-recent-conversations.md, help/include/reading-topics.md, help/include/recent-conversations.md, help/invite-new-users.md, help/keyboard-shortcuts.md, help/marking-messages-as-read.md, help/search-for-messages.md, zerver/lib/markdown/help_relative_links.py
As discussed in https://github.com/zulip/zulip/pull/26124#discussion_r1252000330, this PR adds the following relative help links:
`{relative|message|recent}`
`{relative|message|all}`
`{relative|gear|keyboard-shortcuts}`
`{relative|gear|message-formatting}`
`{relative|gear|search-filters}`
and replaces `{relative|gear|invite}` with a Markdown include since we no longer use the `#invite` hash in the web-app.
**Notes:**
- Maybe we should add the corresponding gear menu icon to each item name in `gear_info`? If so, we could add all of them as a separate commit.
- https://zulip.com/help/recent-conversations
- https://zulip.com/help/all-messages
- https://zulip.com/help/keyboard-shortcuts#keyboard-shortcuts-reference
- …
=> help: Offer relative links to in-app overlays for logged in users.

zerver/webhooks/gitea/view.py
=> gitea: Support missing head/base refs.

web/tests/topic_generator.test.js
This function takes the stream name (a string) and using numbers makes it seem like it's actually using a stream id, which is confusing. This change adjusts `stream` to always be a string.
=> topic generator test: Use strings for stream name instead of numbers.

web/styles/dark_theme.css, web/styles/search.css, web/templates/navbar.hbs
The terminology "arrows" comes from historical functionality that is no longer relevant, so search_input is a more clear and accurate name.
No functional changes.
=> search: Rename search_arrows to search_input.

templates/corporate/for/communities.md, templates/corporate/for/open-source.html
Reference https://github.com/zulip/zulip/pull/26304#issuecomment-1646979611
This tweet was deleted since user moved to mastodon from twitter and used a tool to delete all their tweets.
- In `/for/open-source` page-
before:
after:
- In `/for/communities` page-
before:
after:
=> open-source: Convert deleted tweet into a quote.

zerver/actions/message_send.py, zerver/lib/email_notifications.py, zerver/lib/notification_data.py, zerver/lib/soft_deactivation.py, zerver/tests/test_email_notifications.py, zerver/tests/test_message_edit_notifications.py, zerver/tests/test_notification_data.py, zerver/tests/test_outgoing_webhook_interfaces.py, zerver/tests/test_push_notifications.py, zerver/tests/test_service_bot_system.py
[#25828 (comment)](https://github.com/zulip/zulip/pull/25828#discussion_r1259828715)
> Would be great if we didn't have any stray trigger strings in this file, as well as in test_notification_data.py, although not a blocker :)
> Included in my TODO list. -- stray trigger strings have been used in a lot of places in this file and a few others. I'll change all of them in a separate mini PR.
---
This commit removes the stray strings used to refer to various types of notification triggers.
We use the attributes of the `NotificationTriggers` class instead.
<details> …
=> notifications: Remove the stray notification trigger strings.

tools/test-js-with-node, web/src/realm_playground.js, web/src/realm_playground.ts, web/src/ui_init.js, web/tests/realm_playground.test.js
This PR migrates `realm_playground` module to TypeScript with some prep commits.
- Passes the comparator function for comparing `pygments_language` via the initialization function to remove direct dependency on `typeahead_helper.js` which was the only file blocking the conversion.
- Removes the parameter `generated_pygments_data`  for initialization function because `realm_playground.js` was already directly importing the data so it does not make sense to pass it around.
- Main conversion commit.
<details> …
=> ts: Migrate `realm_playground.js` to TypeScript.

web/styles/dark_theme.css
Followup to #26340.
We get the right background-color from line 487 in the same way as Chrome.
=> dark_theme: Remove Firefox override for dropdown appearance

web/styles/zulip.css
This PR removes unnecessary right padding from the message box; this will give 15px back to displaying message content at mobile scales.
This also removes padding on .message_content that wasn't actually rendered due to its low specificity. It was likely also leftover from an earlier, non-grid-based layout.
| Mobile Before | Mobile After |
| --- | --- |
| ![mobile-time-before](https://github.com/zulip/zulip/assets/170719/ba39eac1-0198-4bb1-8cf6-20963fec7e51) | ![mobile-time-after](https://github.com/zulip/zulip/assets/170719/a7f463b6-63cd-4cbc-aca2-1ccdd160aaa6) |
| Medium Before | Medium After (no change) |
| --- | --- |
| ![medium-time-before](https://github.com/zulip/zulip/assets/170719/54681a30-5eb3-41c9-a3f4-3ab8bfecb443) | …
=> grid: Remove unnecessary mobile-scale padding.

web/src/vdom.ts
Added type annotations for variables, function params, and return values. Created custom types that help with clean type annotations.
Notes on `attrs` field in custom `Option` type:
`attrs` is an `Iterable` where each element is a pair of string, i.e a string array with two elements. `attrs` is tranformed into a `Map` at some point. `Map` constructor takes in `Iterable` object so has no problem unifying with `attrs`. However, at some point `attrs` is transfomed using `.map(...)` which is an array method, and `Iterable` does not support `.map(...)`. So at this point, I cast `attrs` into array before using `.map(...)` by this syntax:
`[..attrs].map(...)`
Much inference is inspired by `vdom.test.js`.
<details> …
=> ts: Migrate `vdom.js` to TypeScript

web/src/message_feed_loading.ts, web/styles/dark_theme.css, web/styles/zulip.css
CZO thread: https://chat.zulip.org/#narrow/stream/101-design/topic/logo.20in.20message.20feed
note: this does not change the color of the loading spinner, only the logo when it is not loading.
=> message feed: Change color of zulip logo at top of feed.

docs/testing/manual-testing.md, help/collapse-a-message.md, web/src/click_handlers.js, web/src/condense.js, web/src/resize.js, web/styles/zulip.css, web/templates/message_body.hbs
This commit encompasses the following changes:
* Replace the [More...] link with a button titled "Show more".
* Replace the [Show Less...] link with a button titled "Show less".
* Add various on-hover interactions to the buttons.
* In the condensed view, add fading to the bottom of the message to visually communicate that the message is truncated.
Fixes #22801.
CZO design discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/UI.20redesign.3A.20show.20more.2Fless
Continuation of #25119 which has now been closed.
<details>
<summary>screencaptures</summary>
**highlight for group and plain messages**
light mode:
dark mode:
**highlight for direct mention**
light mode:
dark mode:
**focused with unread marker showing**
</details>
=> message view: Redesign the more-less message interaction.

web/src/compose_ui.js
Fixes #25950.
Focus area is mostly determined by finding the first relevant field that is *empty*, and selecting empty fields has no effect.
The only situation where the field might not be empty is when the textarea already has text in it, since that's the default option. We don't want to select the composebox textarea because this can lead to people losing their messages if they start typing right away.
Screen capture of behavior after this change:
=> compose: Don't select compose input field after focus.

docs/production/deployment.md, scripts/lib/sharding.py
Fixes:
The value of variable `$http_host` header will be empty string when using http/3: https://github.com/nginx-quic/nginx-quic/issues/3
Anyone using a browser that supports http/3 requests the nginx for the first time with http/2 will get an expected HTTP 200, but any succeeding requests will fail with HTTP 400 response by the zulip since the browser has chosen to upgrade to http/3 then the zulip reject with an empty value for `Host` header: https://github.com/zulip/zulip/issues/9552#issuecomment-392219083
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-dis …
=> replace the variable `$http_host` to `$host` in nginx conf example

web/src/bundles/app.ts, web/styles/print.css
This adds some essential print styles via a new `print.css` stylesheet to ensure better printing especially of Zulip topics.
There are still things that could be improved, given enough time. In particular, there are slight differences when printing from light vs. dark mode; some additional work could be done on borders and things, but this PR is really about trying to faithfully present the content of topics and their messages as faithfully and accessibly as possible.
[CZO Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/printing.20Zulip.20conversations/near/1614108)
| Before, Emoji (invisible) | After |
| --- | --- |
| <img width="1136" alt="emoji-before" src="https://github.com/zulip/zulip/assets/170719/74a3aa96-dd82-4680-83d4-5682a3 …
=> print: Add print styles targeted at topics.

web/src/compose_pm_pill.js
Before this change, the cursor left the DM recipient box after selecting a pill from the typeahead. This was only the case with mouse clicks and not with keyboard selection.
This change ensures we always return focus to the input field after selection.
=> compose: Return focus to DM input after pill selection.

.mailmap
I ran `git config --local user.email evy@zulip.com` locally and added a line to `.mailmap` to show that both my emails are the same person.
=> mailmap: Add evy@zulip.com.

web/src/people.ts, web/src/presence.js, web/src/rendered_markdown.js, web/tests/presence.test.js
We revert to use `ignore_missing` parameter for `maybe_get_user_by_id` function to avoid sending unnecessary `blueslip.error()` calls to sentry.
This bug was introduced in the commit [1c8bf4f050475073d641f6f4b5f27b143e8b1dd6](https://github.com/zulip/zulip/commit/1c8bf4f050475073d641f6f4b5f27b143e8b1dd6).
Discussion - [CZO](https://chat.zulip.org/#narrow/stream/6-frontend/topic/people.2Ejs.20typescript.20migration/near/1618488)
<details>
</details>
=> people: Revert to using `ignore_missing` parameter.

pyproject.toml, zerver/actions/message_send.py, zerver/lib/cache_helpers.py, zerver/lib/events.py, zerver/lib/users.py, zerver/tests/test_invite.py, zerver/tests/test_signup.py, zerver/tests/test_upload_local.py, zerver/tests/test_upload_s3.py, zerver/tests/test_user_topics.py, zerver/views/message_send.py, zerver/views/report.py, zerver/views/sentry.py, zproject/urls.py
isort did this by default, though it’s unclear whether that was intended; see https://github.com/astral-sh/ruff/issues/4153.
=> ruff: Collapse short multi-line import statements

zerver/lib/event_schema.py
A trailing comma [suffices](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma) to tell Black to force vertical formatting. (This Black feature is newer than these comments.)
=> event_schema: Remove useless “force vertical” comments

web/tests/compose_ui.test.js
This fixes a spelling error on a test variable.
=> tests: Correct the spelling of 'caret'.

web/styles/dark_theme.css, web/styles/print.css, web/styles/zulip.css
This PR improves topic-printing in multiple ways:
1) it isolates all dark-mode CSS to screen media only (`@media screen`), meaning that printed topics should always only ever apply the light mode--keeping the print CSS free from a whole bunch of adjustments that we'd have to make otherwise.
2) it fixes a bug with Firefox, where print output can appear pixelated/fuzzed out on text with opacity set, such as the EDITED/MOVED messages and timestamps.
3) it saves paper by setting `height: auto` in the print styles for `html` and `body`, which were otherwise creating a blank N+1th page--even on topics with a single short message.
4) it overrides some additional things (primarily margins) that Safari was accounting for, based on how wide the viewport was at the time of printing.
[CZO …
=> print: Fix dark mode, opacity issues.

zerver/actions/uploads.py, zerver/lib/retention.py, zerver/models.py, zerver/tests/test_delete_unclaimed_attachments.py, zerver/tests/test_retention.py, zerver/tests/test_upload.py
Previously, this code:
```python3
old_archived_attachments = ArchivedAttachment.objects.annotate(
has_other_messages=Exists(
Attachment.objects.filter(id=OuterRef("id"))
.exclude(messages=None)
.exclude(scheduled_messages=None)
)
).filter(messages=None, create_time__lt=delta_weeks_ago, has_other_messages=False)
```
...protected from removal any ArchivedAttachment objects where there
was an Attachment which had _both_ a message _and_ a scheduled
message, instead of _either_ a message _or_ a scheduled message.
Since files are removed from disk when the ArchivedAttachment rows are
deleted, this meant that if an upload was referenced in two messages,
and one was deleted, the file was permanently deleted when the
ArchivedMessage and ArchivedAttachment were cleaned up, despite being
still …
=> retention: Prevent deletion of partially-archived messages.

web/src/settings_user_topics.js, web/src/user_topics.js, web/templates/settings/user_topics_settings.hbs, web/tests/settings_user_topics.test.js
[#26016 (comment)](https://github.com/zulip/zulip/pull/26016#issuecomment-1639063408)
> I think the settings "topics" UI is missing a loading...saved indicator interaction to show you that your changes are saved; right now you get no feedback at all that your change works. But that feels like something that'd be OK as an immediate follow-up.
---
This commit adds a 'saving...' - 'saved' indicator to the 'SETTINGS/TOPICS' UI.
This improves the UX by reflecting that the changes are saved.
---
[screen-capture.webm](https://github.com/zulip/zulip/assets/56781761/fc0e4368-3fdc-4b96-a5bf-8191c5e180d1)
<details> …
=> settings: Add a saving-saved indicator to the 'SETTINGS/TOPICS' UI.

web/src/dropdown_widget.js, web/src/settings_org.js
It is possible that the current value of a dropdown widget is valid but not present in options since the current user doesn't have access it. So, we show [disabled] as value in that case.
This can be reproduced by setting a private stream for notifications in org settings and then opening org settings as a user which doesn't have access to the private stream.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/organisation.20settings.20dropdown.20widgets.20not.20initializing
=> dropdown_widget: Show disabled if value not in options.

web/src/compose.js, web/src/scheduled_messages.js
Currently we unschedule messages as soon as they're opened for editing. Users have requested a way to easily reschedule, especially for situations where they didn't end up wanting to edit the messages in the first place.
This commit adds an action button to reschedule the message for the time it was originally scheduled for.
CZO:
https://chat.zulip.org/#narrow/stream/9-issues/topic/Scheduled.20message.20sent.20to.20draft.20if.20no.20changes
=> scheduled messages: Allow user to reschedule quickly from edit window.

api_docs/changelog.md, version.py, web/tests/lib/events.js, zerver/actions/streams.py, zerver/lib/default_streams.py, zerver/lib/event_schema.py, zerver/lib/events.py, zerver/lib/streams.py, zerver/lib/types.py, zerver/models.py, zerver/openapi/zulip.yaml, zerver/tests/test_event_system.py, zerver/tests/test_events.py, zerver/tests/test_subs.py, zerver/views/streams.py
- First two commits are prep commits to include stream traffic information in `Stream` objects.
- Last commit adds stream traffic information to `Stream` objects.
<details>
</details>
=> streams: Add stream traffic data to `Stream` objects.

web/e2e-tests/compose.test.ts, web/e2e-tests/copy-and-paste.test.ts, web/e2e-tests/drafts.test.ts, web/e2e-tests/edit.test.ts, web/e2e-tests/lib/common.ts, web/e2e-tests/message-basics.test.ts, web/e2e-tests/stars.test.ts
Doing this as part of my work to move towards `stream_id` -- though this should stay as a name because end-to-end tests do things visually and need to look for the string on the screen.
=> puppeteer: Use `stream_name` instead of `stream` for clarity.

zerver/tests/test_users.py
Follow-up : [#25828 (comment)](https://github.com/zulip/zulip/pull/25828#discussion_r1244652123)
> This should use `do_change_user_settings`.
(Maybe it would be nice to change all of this test in a sweep in a prep commit, since this test uses the `.save()` anti-pattern.)
While working on the follow-up, I noticed a small improvement, and the same has been included as a prep commit in this PR. The commit message explains the reasoning in detail. (Skipping to explain again in the PR description.)
<details> …
=> test_users: Use 'do_change_user_setting' instead of '.save()'.

web/src/hashchange.js
Recent Topics is hidden when we switch to a narrow view or the All Messages view, so this call is not needed. It will also become actively unhelpful when we build a stream-specific recent topics page, because then it will be possible to have a hash change that shouldn't close the recent topics view.
Manually tested switching between All Messages, Recent Topics, and narrow views.
=> hashchange: Remove hiding of recent topics.

zerver/lib/event_schema.py, zerver/lib/events.py, zerver/tests/test_events.py
Follow-up noted in #22103, see [this comment](https://github.com/zulip/zulip/pull/22103#issuecomment-1138853085) for particular context.
Adds a test for removing the value set for a user's custom profile setting without adding another value.
When adding the test coverage, found two bugs in the events logic for the "realm_user" case in `apply_event`:
- First, the updates to these custom profile fields, as well as other fields in the event's `"person"` object, were being done in a loop over the fields in the state's `"raw_user"` object, which was unnecessarily making the same update multiple times.
- So the first commit unnests those updates so that they are only updated once.
- The commit that introduced the nesting was  https://github.com/zulip/zulip/commit/649fccde6ba438a213c6c43688462e35 …
=> events: Add test for removing custom profile field data.

zerver/lib/markdown/help_relative_links.py, zerver/tests/test_docs.py
As discussed in , https://github.com/zulip/zulip/pull/26313#issuecomment-1646130071 this PR adds icons to the following relative help links:
```
{relative|gear|manage-streams}
{relative|gear|settings}
{relative|gear|organization-settings}
{relative|gear|stats}
{relative|gear|keyboard-shortcuts}
{relative|gear|message-formatting}
{relative|gear|search-filters}
{relative|gear|integrations}
{relative|gear|plans}
{relative|gear|billing}
```
**Notes:**
- I also tested not including the icon as part of the link, but I think it looks better the other way around as shown above.
<details> …
=> help: Add gear menu icons to relative links.

web/src/pm_conversations.ts
- Migrates `pm_conversations.js` module to typescript.
<details>
</details>
=> ts: Migrate `pm_conversations` module to typescript.

web/styles/message_row.css, web/styles/zulip.css
As @timabbott pointed it out in #26346 highlighted messages when collapsed by `-`  it gets unusual line-like artifact. This PR fixes that issue.
Fixes: #26346
**To Discuss** : 
- If the blank line above "Show More" should be removed or not, the screen recording below has blank line removed and the code doesn't.
- If a user sends multiple message and one of the message in between is collapsed it still leaves a blank line, if removed I figured it was looking kind of cluttery so I've not removed that blank line in this pr. 
https://github.com/zulip/zulip/assets/91622060/4768c9db-a5c9-43d3-97b1-18b665048288
<details> …
=> Message Feed: Fix collapsed messages for highlighted texts.

api_docs/changelog.md, version.py, web/src/server_events_dispatch.js, web/src/settings_org.js, web/src/stream_create.js, web/src/stream_edit.js, web/src/stream_settings_ui.js, web/src/stream_ui_updates.js, web/src/tippyjs.js, web/styles/subscriptions.css, web/templates/stream_settings/stream_settings.hbs, web/templates/stream_settings/stream_types.hbs, web/tests/dispatch.test.js, zerver/lib/streams.py, zerver/openapi/zulip.yaml, zerver/tests/test_subs.py, zerver/views/streams.py
To add or remove a stream as default for new users the admin has to navigate to a separate menu. To address this, added a [checkbox] Default stream for new users in the stream creation and editing UIs.
We prevent users from creating an incompatible configuration in both the stream creation and stream edition UIs.
For the front-end (stream_ui_updates.js > `update_default_stream_and_stream_privacy_state`):
- If the private stream option is selected, the default stream option is disabled with a tooltip that states, 'Private streams cannot be default streams for new users.'
- If the default stream option is checked, the private stream options are disabled with a tooltip that states, 'Default streams for new users cannot be made private.'
For the back-end (streams.py > …
=> stream_settings: Add an option to make a stream default for new users in stream creation and editing UIs.

web/e2e-tests/settings.test.ts
This disables the `test_edit_bot_form` Puppeteer test that, like its already-disabled `test_invalid_edit_bot_form` cousin, is failing nondeterministically, including on GitHub CI runs.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/flaky.20settings.2Etest.2Ets.3F/near/1619848)
I opened issue #26442 to track the proper debugging of these tests so they're not simply disabled and forgotten about.
=> tests: Disable flaky test_edit_bot_form test.

web/styles/print.css
This catches and hides a little piece of UI that was still printing: the X to close the search bar.
Note that this change will still be viable even after #24345 is merged.
| --- | --- |
| <img width="1257" alt="search-results-before" src="https://github.com/zulip/zulip/assets/170719/3b3d40bc-9d39-4baa-924e-37fa8ee4234d"> | <img width="1257" alt="search-results-after" src="https://github.com/zulip/zulip/assets/170719/bb3d2605-67eb-4ed8-8a4c-1772a9c86a0c"> |
=> print: Hide closing X on search bar.

package.json, pnpm-lock.yaml, web/src/compose_ui.js, web/src/copy_and_paste.js, web/tests/copy_and_paste.test.js
This PR enables URL-pasting onto selected compose text. The logic checks for the presence of a URL on the clipboard following a `"paste"` event, and equally for a text selection in the compose area. Absent either of those things, no action is taken. Otherwise, a Markdown string of the selected text is formatted using the selection in the textarea, and the cursor is placed at the end of the new Markdown string.
The PR opens with a testing-related prep commit to remove brittle, self-referential event-testing logic from the copy-and-paste tests, which will break anyway once there is need to reach into the event object--as this PR does in retrieving the textarea in question.
Fixes: #18692
[Recent CZO discussion](https://chat.zulip.org/#narrow/stream/137-feedback/topic/Linkify.20text.20when.20p …
=> compose: Allow URLs to be pasted onto selected text.

.github/workflows/zulip-ci.yml
We need some of the frontend and API tests, which developers don't run locally, to run first and know about the possible errors fast.
discussion: https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/Zulip.20CI.20.2F.20Ubuntu.2020.2E04.20.28Python.203.2E8.2C.20backend.20.2B.20frontend.29
=> ci: Move backend tests further late in the queue.

help/include/sidebar_index.md, help/printing-messages.md
This adds a new page to the documentation for documenting the printing feature. It links to the documentation under the "Streams & topics" section.
This is ready to merge, now that #26374 has been merged.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/printing.20Zulip.20conversations/near/1616218)
**Screenshot**
<details>
</details>
=> docs: Document printable conversations.

tools/test-backend
It's relatively rare that you want to read the coverage report if the coverage tests pass. This allows devs to get quicker feedback. Particularly on tricky rebases this can be a real time saver. It takes about a minute to write the coverage report on my box.
=> tests: Defer writing coverage report.

help/star-a-message.md, static/images/help/mobile-star-icon.svg, zerver/lib/markdown/help_relative_links.py
- Updates [Star a message](https://zulip.com/help/star-a-message) mobile instructions.
- Updates "View your starred messages" section.
- Adds instructions block and relative link to Starred messages.
- Adds "Toggle starred messages counter" subheading.
-  Documents "Starred messages" mobile feature.
- Adds "Searching for messages" as a related article.
<details>
</details>
=> help: Update "Star a message" and document mobile features.

help/include/sidebar_index.md
As discussed in [#user community > mentinoning users vs. linking to topics](https://chat.zulip.org/#narrow/stream/138-user-community/topic/mentinoning.20users.20vs.2E.20linking.20to.20topics), we should have a clear reference in the "Writing messages" sidebar section on linking to conversations below "Mention a user or group" to clarify mentioning users vs linking to conversations.
This adds a link to the "Link to a message or conversation" article with a different heading.
<details> …
=> help: Add heading on linking to messages in "Writing messages" section.

web/src/ui_init.js, web/styles/settings.css
Removes the "dropdown-list-body" CSS class and reference in event handler in `ui_init.js` as it is no longer used in the new `DropdownWidget`.
The previous uses of the class were removed in commit 875d564f2d. A `git-grep` for "dropdown-list-body" after these changes returns nothing.
@amanagr - Could you double-check that I'm not missing anything here since you did the migration to the new `DropdownWidget`?
---
<details>
</details>
=> dropdown-list-widget: Remove "dropdown-list-body" class and reference.

web/src/condense.js
This PR aims to add a focus on the message after clicking "Show more" or "Show less".
Related [CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.22Show.20more.22.20doesn't.20select.20the.20message).
=> condense: Focus on the message after condensing/expanding it.

web/e2e-tests/drafts.test.ts, web/src/drafts.js, web/src/messages_overlay_ui.ts, web/src/rows.js, web/src/tippyjs.js, web/styles/app_components.css, web/styles/dark_theme.css, web/styles/drafts.css, web/templates/draft.hbs, web/templates/draft_table_body.hbs, web/tests/drafts.test.js
This PR adds functionality to bulk delete drafts quickly.
Special thanks to @juliaBichler01 for working on this one at #19943.
Fixes #19360.
- The `Select All Drafts` checkbox doesn't align with other checkboxes if a scrollbar is present on the drafts window. That can be fixed by using a function like this:
```
function adjust_select_drafts_button() {
const $drafts_list = $(".drafts-list");
const scroll_bar_width = $drafts_list[0].offsetWidth - $drafts_list[0].clientWidth;
$(".select-drafts-button").css("margin-right", 25 + scroll_bar_width + "px");
}
```
But I am unsure if that's the best way to do it.
- I am not sure if I need to add any node/puppeteer tests for this one.
<hr>
**Light Theme:**
<details>
<summary>Delete All Drafts</summary>
</details>
<details>
<summary>Delete Some …
=> drafts: Add functionality to bulk delete drafts.

web/src/settings_org.js, web/src/stream_edit.js, web/templates/stream_settings/stream_settings.hbs
Organization owners can make streams private even if they're not subscribed to them, but cannot access private streams they're not subscribed to. This means they're able to lock themself out of streams.
This change warns users of this and give them a chance to subscribe.
Fixes #26437.
Things I've tested:
* Clicking subscribe updates the button at the top of the stream settings menu and the checkmark on the left menu, and closes the banner.
* Close button closes the banner.
* Banner shows up under the correct conditions.
Pending UI feedback [on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Owner.20locked.20out.20from.20private.20stream)
=> stream settings: Warn users before locking them out of a stream.

zerver/lib/topic.py
The number of affected objects may be quite high, and they are
selected by `id IN (...)` query, and updated with a giant `CASE`.
This turns out to be quadratic, and can cause large queries to take
hours, in a state where they cannot be terminated, when PostgreSQL >11
tries to JIT the query.
Set a batch_size as a stopgap performance fix before moving to `.update()` as a real fix.
<details>
</details>
=> topic: Set a max batch_size on bulk_upate call.

zerver/tests/test_openapi.py
Each unittest subTest can fail without interrupting the other subTests. By wrapping the test for each view function, we can get all validation errors at once, which can be useful if multiple endpoints are updated.
More importantly, if the test fails anywhere inside test_openapi but before the formatted output is printed, we will not lose the information of which view function fails the validation. Because we attach the name of the function to the subTest:
```
FAIL: test_openapi_arguments (zerver.tests.test_openapi.OpenAPIArgumentsTest) [zerver.views.alert_words.add_alert_words]
```
<details> …
=> test_openapi: Use subtests for arguments test.

web/babel.config.js, web/src/page_params.ts, web/src/stream_data.js, web/src/stream_data.ts, web/src/sub_store.ts
Migrates `stream_data` module to TypeScript and also refines the existing types for stream and subscription objects present in `sub_store` module.
The main crux of this module is `create_sub_from_server_data` which generates `sub` objects which we use in web client from the data we get from the server.
The type for it's parameter `attrs` which I called `StreamAttrs` is defined as union of three types:-
1)  `NeverSubscribedStream & Pick<ExtraStreamAttrs, "subscribed" | "previously_subscribed">`
2) `ApiStreamSubscription & Pick<ExtraStreamAttrs, "subscribed" | "previously_subscribed">`
Both of these types are inferred by me by looking at the `populate_subscriptions` method which calls this function with attrs confirming to the types mentioned above.
3) `Stream & {stream_weekly_traffic: …
=> ts: Migrate `stream_data.js` module to TypeScript.

tools/test-js-with-node, web/src/browser_history.ts, web/src/hash_util.ts, web/src/spectators.ts
This PR migrates 3 modules:-
- `hash_util`
- `browser_history`
- `spectators`
<details>
</details>
=> ts: Migrate `hash_util`, `browser_history`, `spectators` to TypeScript.

help/direct-messages.md, help/typing-notifications.md, zerver/lib/markdown/help_relative_links.py
- Corrects documentation to reflect that [typing notifications](https://zulip.com/help/typing-notifications) work when narrowing to all direct messages as well, adding a link to a new section in [Direct messages](https://zulip.com/help/direct-messages).
<details>
</details>
=> help: Fix "Typing notifications" intro paragraph.

web/src/list_widget.ts, web/src/settings_linkifiers.js, web/templates/settings/admin_linkifier_list.hbs, web/tests/list_widget.test.js
This is a follow-up to #26464. Linkifier items are no longer draggable if the filter value is non-empty. This is implemented by extending list widget to pass the filter value to the modifier.
<details>
</details>
=> linkifiers: Disable dragging when a filter is applied

api_docs/changelog.md, web/src/navbar_alerts.js, web/src/timerender.ts, web/templates/navbar_alerts/profile_incomplete.hbs, web/tests/navbar_alerts.test.js, web/tests/timerender.test.js, zerver/lib/events.py, zerver/openapi/zulip.yaml, zerver/tests/test_home.py
Currently, we are displaying the "Complete the organization profile"
banner immediately after the organization was created. It's important to
strongly encourage orgs to configure their profile, so we should delay
showing the banner if the profile has not been configured after 15 days.
Thus also allows the users to check out Zulip and see how it works before
configuring the organization settings.
Previously, the reason to complete the organization profile on the banner
wasn't clear and at times confusing. With the updated wording, it clears
up the confusion and improves the explaination of "why" as well.
Fixes: #24122.
<details> …
=> navbar_alerts: Improve "Complete the organization profile" banner.

web/src/about_zulip.js, web/src/message_edit.js, web/src/popover_menus.js, web/src/tippyjs.js, web/styles/dark_theme.css, web/styles/message_row.css, web/styles/zulip.css, web/templates/message_body.hbs
This PR properly displays Tippy Copied! alerts in three cases:
1) On the clipboard icon when copying message source.
2) On the hover controls when copying the link to a message.
3) In the About Zulip modal when copying the Zulip version number.
With those complete, the PR removes the `.alert-msg` styles and fragment of the message-body template, which are no longer needed.
Fixes: #21036, #23210.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/inconsistent.20Copied!.20alerts/near/1615056)
| Copy message source, before | Copy message source, after |
| --- | --- |
| ![copy-source-before](https://github.com/zulip/zulip/assets/170719/0f033ec6-9f49-4433-9e38-eb75ba381c3b) | ![copy-source-after](https://github.com/zulip/zulip/assets/170 …
=> alerts: Display copied alerts with Tippy.

zerver/tests/test_message_fetch.py, zerver/views/message_fetch.py
The `messages_in_narrow_backend` function was directly calling `NarrowBuilder` instead of utilizing the
`add_narrow_conditions` method like `fetch_messages` does. This behaviour was not combing any search operands together as it happens inside the `add_narrow_conditions`.
Fixes: https://chat.zulip.org/#narrow/stream/3-backend/topic/messages_in_narrow_backend.20calling.20NarrowBuilder.20directly/near/1611193.
=> Refactor: Use `add_narrow_conditions` in `messages_in_narrow_backend`.

zerver/lib/narrow.py, zerver/tests/test_message_fetch.py, zerver/views/message_fetch.py
This commit addresses the issue where the topic highlighting in search results was offset by one character when an apostrophe was present. The problem stemmed from the disparity in SQL-style HTML escaping used to obtain topic_matches and the escaping performed by Django utils or other libraries for apostrophes (').
sql_escape | django_escape
-----------+---------------
`&#39;`   |     `&#x27;`
To resolve this, a manual replacement was implemented to achieve a similar HTML escape result.
Fixes: #25633.
=> narrow: Fix topic highlighting issue with apostrophes in search results.

web/src/portico/help.js
This PR uses ```CSS.escape()``` on ```hash``` in ```scrollToHash``` function to resolve possible exception in some browsers.  
Fixes: #26249
<details>
</details>
=> docs: Avoid exception in scrollToHash()

web/src/hotkey.js, web/src/recent_topics_ui.js, web/src/recent_topics_util.js, web/tests/hotkey.test.js
This better fits how this function is used, and cuts unnecessary dependencies from recent_topics_util.js.
Fixes: 
<details>
</details>
=> recent_topics: Move is_in_focus to UI module.

web/styles/modal.css
Previously, the modal content bottom border sometimes got hidden due to subpixel rounding. 
This happens only at some Zoom levels and on Google Chrome.
<details>
<summary> <b>Screenshots and screen captures:</b> </summary>
<table>
<tr>
<th colspan="2">On 75% Zoom - Chrome 110</th>
</tr>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/sbansal1999/zulip/assets/35286603/5996a059-8945-4b8d-948f-180e544296ca)" alt="image"></td>
<td><img src="https://github.com/sbansal1999/zulip/assets/35286603/45b67ef3-3c7c-4394-ad73-c20f544287de" alt="image"></td>
</tr>
</table>
</details>
CZO Discussion: [Link](https://chat.zulip.org/#narrow/stream/6-frontend/topic/border.20disappearing.20on.20zooming.20out/near/1625327)
<details> …
=> dialog_widget: Add horizontal padding to the modal content.

web/styles/portico/portico_signin.css
This is only visible on desktop app.
before:
after:
=> portico_signin: Fix back to login button alignment.

web/styles/widgets.css, web/styles/zulip.css
=> Fix poll and todo input focus box-shadow being cropped.

zerver/actions/message_edit.py, zerver/actions/message_send.py, zerver/lib/message.py, zerver/tests/test_message_edit.py, zerver/tests/test_message_send.py, zerver/tests/test_users.py
**First commit:**
message_send: Fix `wildcard_mentioned` flag unset for few participants.
Earlier, the flag was set if the `user_profile_id` exists in `all_topic_wildcard_mention_user_ids`.
`all_topic_wildcard_mention_user_ids` contains the ids of those users who are topic participants **and** have enabled notifications for '@topic' mentions.
The earlier approach was incorrect, as it would set the `wildcard_mentioned` flag only for those topic participants who have enabled the notifications for '@topic' mention instead of setting the flag for all the topic participants.
---
**Second commit:**
message_edit: Fix `wildcard_mentioned` flag set for all user-messages.
Earlier, for topic wildcard mentions, the `wildcard_mentioned` flag was set for all the user-messages. (similar to stream …
=> topic_mentions: Fix the incorrectly set `wildcard_mentioned` flag.

zerver/openapi/zulip.yaml, zerver/tests/test_event_system.py
Fixes the `/api/register-queue` endpoint documentation so that the `realm_emoji` has the correct type, an object that contains objects that describe custom emoji in an organization.
By correcting the API documentation, we also fix an error in the test for the events system, which had been relying on the API documentation having a list as a possible type for `realm_emoji` in the register response.
See [relevant CZO disucssion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/register.3A.20shape.20of.20.60realm_emoji.60.20object/near/1626354).
<details>
<summary>Updated realm_emoji in register response</summary>
[Current documentation](https://zulip.com/api/register-queue) - search for "realm_emoji" on page
</details>
---
<details> …
=> api-docs: Fix documentation of `realm_emoji` in register response.

tools/linter_lib/custom_check.py, web/src/settings_users.js, web/templates/confirm_dialog/confirm_reactivate_bot.hbs, zerver/actions/bots.py, zerver/actions/create_user.py, zerver/actions/streams.py, zerver/lib/queue.py, zerver/lib/streams.py, zerver/tests/test_bots.py, zerver/tests/test_events.py, zerver/tests/test_message_flags.py, zerver/tests/test_subs.py
Commit summary -
- First commit is to extract events code into a function.
- Next commit is to re-parent the bot to the admin reactivating the bot in case the original owner is deactivated.
- Next two commits are to unsubscribe bot from inaccessible private streams on changing bot owner.
- Last commit is to update the confirmation modal for reactivating bot.
Fixes part of  #21700
=> Reparent bot to the admin on reactivating if owner is deactivated and unsubscribe it from inaccessible private streams.

zerver/openapi/zulip.yaml
Removes a response example in the `POST users/me/subscriptions` documentation that was listed in `zerver/openapi/zulip.yaml` as a 400 error response. It is actually a variation on the success response for this endpoint.
The current rendering of our API documentation is not set up to support `"anyOf"` which would allow for validating examples that match multiple response schemas. Adding that support can be a follow-up issue to fixing this error.
The updated documentation for the endpoint's response does clearly document that the `unauthorized` list of stream names that weren't subscribed is only present if `"authorization_errors_fatal": false`. And the unique error for when that parameter is `true` is still documented.
<details>
<summary>Subscribe to a …
=> api-docs: Remove incorrect error response from `/api/subscribe`.

web/src/message_scroll.js
This is functionally the same, but semantically more relevant. It will also be helpful if some day in the future these two function calls are no longer perfect opposites of each other.
=> message scroll: Check message feed visibility instead of recent topics.

web/styles/app_components.css
Related [CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/unread.20count.20horizontal.20aligning)
<details>
| ![before](https://github.com/zulip/zulip/assets/53193850/c60143b8-fad8-4df7-996e-ebfd2c389fd3) | ![after](https://github.com/zulip/zulip/assets/53193850/a4d233c1-e288-48bb-8458-0e4e7546511f) |
</details>
=> unread_count: Remove letter spacing for better horizontal alignment.

web/src/message_list.js, web/styles/message_row.css
This PR employs better control over line-heights to fix a couple of related issues spread across different message modes (viewing, collapsing, editing/viewing source), resulting in a more robust message and grid presentation.
* It removes an apparent empty line of space with collapsed messages, as noted by Tim in #26433, by allowing the SHOW MORE button to occupy the grid area ordinarily occupied by the message itself. This produces what is likely user intent: collapsing messages into their smallest possible footprint.
* It eliminates a small shift in EDITED/MOVED markers and timestamps, as [also noted](https://github.com/zulip/zulip/pull/26433#issuecomment-1670109935) in #26433.
* It fixes [a regression](https://chat.zulip.org/#narrow/stream/6-frontend/topic/message.20edit.20form.20height …
=> grid: Handle layout across multiple message modes.

web/styles/message_row.css, web/styles/reactions.css
This PR tightens up how reactions are laid out. Most notably, that means setting `.message_reactions` as a flex container (rather than floats on individual reactions, as had beeen used previously) and letting the individual reactions participate in the flexbox as first-class flex items--meaning that they are spaced from one another via gaps, not margins. Judicious use of the `flex-wrap` property ensures that this presentation is responsive across all viewport sizes.
The previous margins were set as 0.15em. Given that the font-size on reactions is the 14px inherited from the body, that works out to 2.1px margins, which I have rounded down to 2px for the sake of the 4px grid-gap. There is no visual difference from that, predictably.
Space at the bottom of the message box is still preserved …
=> reactions: Improve reactions layout.

docs/development/setup-advanced.md, scripts/lib/build-groonga, tools/lib/provision.py
Tweaked provision script to run successfully in Fedora 38 and included a script to build the groonga libs from source because the packages in Fedora repos are outdated.
There is a major version jump from the last supported version (F34) which is EOL so references and support for older versions were removed.
Fixes: #20635
<details>
</details>
=> Add provision support for Fedora 38

web/src/narrow.js
In commit 846b470b99, `narrow.by_topic` was missed for getting the stream name via the stream ID in the message data. Updates function to get the stream name to pass in the filter terms to `narrow.activate`.
In that same commit, `narrow.by_recipient` was updated to not pass the message ID to `then_select_id`. Updates call to `narrow.activate` to include that opts parameter so that the selected message doesn't change.
---
<details>
</details>
=> narrow: Fix by_topic and by_recipient for stream and message ID.

docs/overview/release-lifecycle.md
Previously I've wanted to have this page spell out the concrete version number that our clients support, rather than the policy we use for determining that version number, because that's the sort of question that I feel like as a user I'd want a straight answer to and would be annoyed if I couldn't get one.
But as the text stands, it's come to look more like it's the policy (something that's heavyweight to change) than like the value that the policy currently happens to work out to.  Also, because this page is kind of chaotically organized (and fixing that is a bigger yak than I want to shave right now), it repeats the 18-month rule in three separate places and the current value (version 4.0) is in a fourth separate place, so it looks internally inconsistent.
Let's therefore take a …
=> docs: Consistently say "18 months" on compatibility, no specific version numbers.

web/src/server_events_dispatch.js, web/src/stream_data.ts, web/src/stream_events.js, web/src/user_profile.js, web/tests/dispatch_subs.test.js, web/tests/stream_data.test.js, web/tests/stream_events.test.js
- This is a prep PR to continue to work further on #26183.
------------
Fixes: https://github.com/zulip/zulip/pull/26183#discussion_r1262884954
-----------
<details>
</details>
=> user_profile: Render the streams list dynamically.

web/styles/zulip.css
Source Sans 3 [defaults](https://github.com/adobe-fonts/source-sans/issues/236#issuecomment-983224391) to lining (lnum), tabular (tnum) figures, the latter of which is necessary to have times like 11:11 and 11:18 line up in short, adjacent messages (much the way other numerals in the interface align from row to row, such as unread counts).
Because `lnum` is the default, there's no need to set it, which is why this PR just deletes the entire line (for reference, `pnum` is the opposite of `tnum`--it's impossible to have both).
CZO discussion:
https://chat.zulip.org/#narrow/stream/6-frontend/topic/redesigned.20hover.20icons.20.2326283/near/1629117
| --- | --- |
| <img width="312" alt="proportional-numerals" …
=> time: Revert to Source Sans lnum, tnum defaults.

tools/test-js-with-node, web/src/hashchange.js, web/src/narrow.js, web/src/narrow_history.js, web/src/ui_init.js, web/tests/narrow_activate.test.js
This saves the blue box position as state on the location in brower history, with `history.replaceState`.
The position is restored when a narrow is activated.
Fixes #20066.
=> narrow: Save blue box position and restore on navigation.

.github/workflows/zulip-ci.yml
The comment logic doesn’t make sense.  Every build gets to write to the caches; some builds do in fact add new items, and without `clean_unused_caches.py` there’s no way for them to remove items.
[Discussion](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/CI.20skipping.20Debian.2011/near/1629980).
=> ci: Restore commented `clean_unused_caches.py` invocation

docs/subsystems/typing-indicators.md, zerver/openapi/zulip.yaml
This is a follow-up PR to #26477 and should be merged after those changes.
Updates the main description of the [`api/set-typing-status`](https://zulip.com/api/set-typing-status) endpoint for the new fields in the `POST register` response for the typing start, stop, expired time intervals. Previously these were hardcoded by the client-side code and not the server-side code.
Also updates the developer documentation for [typing indicators](https://zulip.readthedocs.io/en/latest/subsystems/typing-indicators.html) in the subsystems docs. This refreshes a few parts of that doc that were already out of date, as well as adds the information about the new register response fields noted above.
See the Read the Docs build in CI for the updates to the subsystems documentation. …
=> typing: Update main typing notifications protocol documentation.

requirements/common.in, requirements/dev.txt, requirements/prod.txt, version.py
https://chat.zulip.org/#narrow/stream/49-development-help/topic/puppeteer.20migration.20two_factor/near/1630646
I’m not sure if we strictly need this as no real symptoms have been observed, but it does silence a distracting message from the dev server after `tools/rebuild-dev-database`:
```
You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): two_factor.
Run 'python manage.py migrate' to apply them.
```
=> requirements: Fix transitively replaced two_factor migrations

web/src/compose.js, web/src/message_edit.js, web/src/server_events_dispatch.js, web/templates/compose_control_buttons.hbs, web/tests/compose_video.test.js
This PR adds the feature to add an audio call (video call with video muted by default) to the compose box.  Right now, the button to add that is only shown when the video call provider is set to `Jitsi Meet`. 
Fixes: #12207
Right now the PR does not have tests but I can add them once the design is finalized.
---
<details>
<summary>Adding Audio Call to the Chat</summary>
[Screencast from 07-06-23 04:49:20 PM IST.webm](https://github.com/sbansal1999/zulip/assets/35286603/86d068b0-a0dd-4a58-a362-53d718756ea6)
</details>
<details>
<summary>Changing Video Call Provider to None</summary>
[Screencast from 07-06-23 05:06:07 PM IST.webm](https://github.com/sbansal1999/zulip/assets/35286603/a6ca8fa0-5d45-4eaa-bd4c-abbd5d84490e)
</details>
---
<details> …
=> compose: Add functionality for audio call.

web/styles/recent_topics.css, web/styles/zulip.css, web/templates/recent_topic_row.hbs
This PR adds a little polish to the actions icon in the Recent Conversations view.
1. It adds a tooltip to the @ indicator
2. It introduces appropriate cursor: a default/arrow cursor for @, and a pointer for the bell icon.
One known remaining rough edge here is that the Tippies on @ and the unread count display with only the default short Zulip delay, whereas the bell icon is presented with the extra-long delay.
[CZO Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/aligning.20actions.20in.20Recent.20conversations/near/1629960)
| --- | --- |
| ![icon-interactions-before](https://github.com/zulip/zulip/assets/170719/a4ac7d3f-0ca4-4903-a8f5-5fbb1f00e56f) | ![icon-interactions-after](https://github.com/zulip/zulip/assets …
=> actions: Icon pointers and tooltips in Recent conversations.

help/keyboard-shortcuts.md, help/view-a-messages-edit-history.md, web/src/hotkey.js, web/src/popover_menus.js, web/src/popover_menus_data.js, web/templates/actions_popover_content.hbs, web/templates/keyboard_shortcuts.hbs
--------------
Fixes: #23077
-------------
<details>
<br>
<br>
</details>
<details>
<br>
<br>
</details>
<details>
<summary>Keyboard Shortcuts dialog:</summary>
<br>
</details>
---------------
<details>
</details>
=> message_feed: Remove the view edit history option from the three-dot menu & add shortcut.

web/src/admin.js, web/src/settings.js, web/templates/settings/bot_list_admin.hbs, web/templates/settings_overlay.hbs
This avoids some confusion around how users might feel about the permission they have for bots when viewing the org settings for bots.
Fixes: #24154
<details>
</details>
=> settings: Improve organization settings for bots

.github/workflows/zulip-ci.yml, tools/linter_lib/custom_check.py, zerver/actions/user_groups.py, zerver/lib/test_classes.py, zerver/lib/test_helpers.py, zerver/lib/user_groups.py, zerver/tests/test_events.py, zerver/tests/test_user_groups.py, zerver/transaction_tests/test_user_groups.py, zerver/views/development/user_groups.py, zerver/views/user_groups.py, zproject/dev_urls.py
**Background**
User groups are expected to comply with the DAG constraint for the
many-to-many inter-group membership. The check for this constraint has
to be performed recursively so that we can find all direct and indirect
subgroups of the user group to be added.
This kind of check is vulnerable to phantom reads which is possible at
the default read committed isolation level because we cannot guarantee
that the check is still valid when we are adding the subgroups to the
user group.
**Solution**
To avoid having another transaction concurrently update one of the
to-be-subgroup after the recursive check is done, and before the subgroup
is added, we use SELECT FOR UPDATE to lock the user group rows.
The lock needs to be acquired before a group membership change is about
to occur before any …
=> user groups: Fix race conditions in user group membership changes

web/src/ui_init.js
oes what it says on the tin; there doesn't appear to be a plain `enter_sends` class any more in the compose area, so this is hopefully the fix for a long-standing regression.
Although I did not screenshot it, the popup menu is unaffected by these changes, as its keyboard rendering is updated in separate logic.
| --- | --- |
| <img width="398" alt="ctrl-before" src="https://github.com/zulip/zulip/assets/170719/ac23496b-6a2f-4c8f-b312-27a453a40b17"> | <img width="398" alt="cmd-after" src="https://github.com/zulip/zulip/assets/170719/1cd05674-beb9-4853-97c2-fc8339dca503"> |
<details> …
=> compose: Render Mac Cmd button and Return at compose bottom.

help/star-a-message.md, help/view-a-messages-edit-history.md
- Adds `keyboard_tip` to [View a message's edit history](https://zulip.com/help/view-a-messages-edit-history#via-the-main-message-feed).
- Adds `keyboard_tip` to [Star a message](https://zulip.com/help/star-a-message#star-a-message_1).
Fixes: #26573.
<details>
</details>
=> help: Document keyboard shortcuts for starring messages and viewing message edit history.

web/src/settings_profile_fields.js, web/src/settings_streams.js, web/templates/settings/profile_field_choice.hbs
While editing select type profile field, if we submit empty or zero
choices it fails silently, current implementation for this issue does
not work for some cases, and this commit will fix that.
This will disable dialog submit button in case of empty field choices.
Also removing code of all calls making to `update_choice_delete_btn`
as that function have no more use-case for empty field choices, still
keeping the function because it gets used in `settings_streams.js`..
Fixes: GH [comment](https://github.com/zulip/zulip/pull/22818#issuecomment-1239000262)
**Screenshot/Gifs**: …
=> custom_profile_fields: Fix empty field choices issue of select field.

puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf
All `X-amz-*` headers must be included in the signed request to S3; since Django did not take those headers into account (it constructed a request from scratch, while nginx's request inherits them from the end-user's request), the proxied request fails to be signed correctly.
Strip off the `X-amz-cf-id` header added by CloudFront.  While we would ideally strip off all `X-amz-*` headers, this requires a third-party module[^1].
[^1]: https://github.com/openresty/headers-more-nginx-module#more_clear_input_headers
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-di …
=> nginx: Do not forward X-amz-cf-id header to S3.

zerver/openapi/zulip.yaml
Fixes various issues in the `POST /register` documentation for the `unread_msgs` object. See two relevant CZO conversations:
- [Missing changes note conversation in #api documentation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/register.3A.20When.20was.20.60unread_msgs.2Epms.5B.5D.2Eother_user_id.60.20added.3F/near/1623961)
- [Incorrect field name conversation in #api documentation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/register.3A.20.60unread_msgs.2Epms.5B.5D.2Eunread_message_ids.60/near/1623940)
Specific changes:
- Fixes incorrectly named `message_ids` fields in `pms` and `huddles` objects to be `unread_message_ids`.
- Adds **Changes** note for when `other_user_id` was added to `pms` object.
- Changes a few uses of "you" to be "current …
=> api-docs: Fix documentation of `unread_msgs` object in `POST /register` response.

templates/corporate/features.html, templates/corporate/for/business.html, templates/corporate/for/events.html, templates/corporate/for/open-source.html, templates/corporate/for/research.html, web/src/message_edit.js, web/templates/settings/organization_permissions_admin.hbs, zerver/openapi/zulip.yaml
This PR is a follow-up to #26166.
=> docs: Update help center links to "Edit a message" and "Delete a message".

api_docs/changelog.md, version.py, web/src/compose.js, web/tests/compose_video.test.js, zerver/tests/test_create_video_call.py, zerver/views/video_calls.py
This PR implements the audio call feature for Zoom. This is done by explicitly telling Zoom to create a meeting where the host's video and participants' video are off by default.
Another key change is that when creating a video call, the host's and participants' video will be on by default. The old code doesn't specify that setting, so meetings actually start with video being off. This new behavior has less work for users to do. They don't have to turn on video when joining a call advertised as "video call". It still respects users' preferences because they can still configure their own personal setting that overrides the meeting
defaults.
The Zoom API documentation can be found at https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingCreate
Fixes: #26549 …
=> compose: Add support for Zoom audio call

zerver/tests/test_create_video_call.py
Verify that Zoom meeting creation logic sends the expected request payload for configuring host_video and participant video.
Addresses feedback from #26588.
<details>
</details>
=> compose: Verify request payload in Zoom meeting creation test

zerver/lib/push_notifications.py, zerver/tests/test_push_notifications.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/notification.20emails/near/1609672)
> Given that context, I think the same "mentioned everyone" text actually works well for all four of those scenarios.
The exact scope of "everyone" is different between different scenarios: everyone in the stream, or in the topic. But that distinction can be seen in the @-mention in the text (unless it comes so late in a long message that it's cut off).
> And I think it's best to get pretty quickly to the content of the message without a lot of extra text explaining precisely what settings you have that caused it to notify you.
* First commit: Remove the stale `user_profile` parameter.
* Second commit: Remove the TODOs from `get_apns_alert_subtitle`.
* Third commit: Add a test to …
=> push_notifications: Remove TODOs from 'get_apns_alert_subtitle'.

web/styles/left_sidebar.css, web/templates/left_sidebar.hbs
This PR is meant to fix the layout of the `global_filters` in the left sidebar.
Related [CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/long.20names.20of.20.60global_filters.60.20break.20the.20layout).
<details>
| ![b_no](https://github.com/zulip/zulip/assets/53193850/c9ef0cf8-713c-43cb-baf4-cb699afeb589) | ![a_no](https://github.com/zulip/zulip/assets/53193850/e0758061-26a9-43ac-8f74-6a7dfa65822d) |
| ![b_yes](https://github.com/zulip/zulip/assets/53193850/8f7a1f39-2990-4a2c-aceb-fde2af881d9c) | ![a_yes](https://github.com/zulip/zulip/assets/53193850/700a382e-6e35-4f48-a400-52b62291a5b4) |
</details>
=> left_sidebar: Fix the layout for filter names that are long.

help/unsubscribe-from-a-stream.md, static/images/help/mobile-check-icon.svg
- Updates [Unsubscribe from a stream](https://zulip.com/help/unsubscribe-from-a-stream) to follow current help center documentation patterns.
- Adds Desktop/web instructions to unsubscribe from a stream via the stream settings panel.
- Adds mobile instructions to unsubscribe via long-press menu, all streams, and stream settings.
<details>
</details>
=> help: Add mobile instructions to "Unsubscribe from a stream".

zerver/lib/push_notifications.py
`logging.exception` should only be called from an exception handler.
https://docs.python.org/3/library/logging.html#logging.exception
Cc @alexmv
=> push_notifications: Fix logging.exception misuse

templates/zerver/base.html, templates/zerver/documentation_main.html, web/src/portico/help.js, web/styles/portico/markdown.css, web/styles/portico/portico.css
This commit removes the simplebar implementation for the right.
Thus using the default browser scrollbar. Removes simplebar class
and functions scrollToHash with this commit.
Fixes #10732 
Tested manually and with node-tests.
How it looks now
=> user docs: Replace right simplebar with browser scrollbar

api_docs/changelog.md, zerver/openapi/zulip.yaml
Specific changes:
- Updates the last remaining reference to "private messages" in the API changelog to be "direct messages", which was in the feature level 11 entry for `POST /typing`.
- Adds a **Changes** note to `is_owner` in the `POST /register` response for when it was added in feature level 11.
- Fixes the feature level for when the `GET /users/{user_id}/subscriptions/{stream_id}` endpoint was added from feature level 11 to feature level 12.
- Does a sweep of the formatting for endpoints in the API changelog for missing backslashes and a few other inconsistencies.
Addresses feature level 11 and 12 points in #22102.
---
<details>
<summary>Updated feature level 11 and 12 entries</summary>
[Current documentation](https://zulip.com/api/changelog#changes-in-zulip-30) …
=> api-docs: Fix endpoint formatting in API changelog and feature levels 11 and 12 changes/entries.

web/src/portico/help.js, web/src/portico/tabbed-instructions.ts, web/styles/portico/markdown.css, web/styles/portico/portico.css, zerver/lib/html_to_text.py, zerver/lib/markdown/tabbed_sections.py, zerver/tests/test_templates.py
As discussed in https://github.com/zulip/zulip/pull/26092#issuecomment-1603037633, this is a follow-up PR to rename misleading identifiers using  the term "code section" to refer to tabbed sections in both the API docs and help center docs.
=> widgets: Rename confusing identifiers for tabbed sections in API/help docs.

web/styles/settings.css, web/templates/settings/notification_settings.hbs
This PR vertically aligns the notification-sound play button in a flex layout.
This allows the select to flex, keeping the buttons position on screen even at mobile-scale viewports.
While other most other controls are currently not so responsive, this might provide some direction (along with a TODO) on how to go about moving controls in that direction.
One note here is that previously, the play button was presented as an inline element. That means that whitespace in the HTML was keeping the button separate from the select element. Rather than try to eyeball that value, I allowed the space to collapse down to the 4px specified in the CSS--and open a discussion on how far that button ought to appear from the select.
One other note is that there's a commit that aligns the `for` attribute on …
=> settings: Play button alignment.

web/src/channel.ts, web/src/message_edit.js, web/src/ui_report.ts, web/tests/channel.test.js
We should reuse the `channel.xhr_error_message` in `ui_report` to reduce code duplication.
Also, I changed the type of `message` parameter to `string` instead of `string | null` so that we do not need to alter the types of the functions that depends on the return value of `xhr_error_message`.
<details>
</details>
=> ui_report: Reuse `channel.xhr_error_message` function in `error` method.

api_docs/changelog.md, version.py, zerver/openapi/zulip.yaml, zerver/tests/test_subs.py, zerver/views/streams.py
Updates the API error response when there is an unknown or deactivated user in the `principals` parameter for either the [`/api/subscribe`](https://zulip.com/api/subscribe) or [`/api/unsubscribe`](https://zulip.com/api/unsubscribe) endpoints. We now use the `access_user_by_email` and `access_user_by_id` code paths, which return an HTTP response of 400 and a `"BAD_REQUEST"` code.
Previously, an HTTP response of 403 was returned with a special `"UNAUTHORIZED_PRINCIPAL"` code in the error response. This code was not documented in the API documentation and is removed as a potential `JsonableError` code with these changes.
Fixes #26593.
**Notes**:
- Started a conversation on CZO to double check these changes won't impact how either the mobile or terminal clients handle these error responses …
=> subscribe-unsubscribe: Improve error response for unexpected users.

templates/zerver/emails/confirm_demo_organization_email.html, templates/zerver/emails/confirm_demo_organization_email.subject.txt, templates/zerver/emails/confirm_demo_organization_email.txt, web/src/admin.js, web/src/invite.js, web/src/page_params.ts, web/src/settings.js, web/src/settings_account.js, web/src/settings_data.ts, web/src/settings_org.js, web/src/tippyjs.js, web/styles/settings.css, web/templates/demo_organization_add_email_modal.hbs, web/templates/invite_user_modal.hbs, web/templates/settings/account_settings.hbs, web/templates/settings/admin_auth_methods_list.hbs, web/templates/settings/auth_methods_settings_admin.hbs, web/tests/settings_data.test.js, zerver/actions/create_user.py, zerver/actions/user_settings.py, zerver/lib/email_notifications.py, zerver/signals.py, zerver/tests/test_email_change.py, zerver/tests/test_signup.py, zerver/views/development/registration.py, zerver/views/registration.py, zerver/views/user_settings.py
Revision of the 1st commit in #19741, based on [Tim's review comment here](https://github.com/zulip/zulip/pull/19741/commits/f662b0834cb157e4ba161534ee88290a28fa55c3#r932756049).
Working specifically towards this part of #19523:
- We intend to allow you to initially create a demo organization without setting an email address, to make it feel super lightweight.
---
**Notes**:
- **1st commit**: Implements Tim's plan for not queuing welcome emails when the realm for the demo organization is being created since the owner's email is an empty string.
- **2nd commit**: I noted that without an email, key parts of the web-app in the new demo organization did not work, such as sending private messages to the welcome bot or to the new owner/user themself. I thought one option would be creating the …
=> demo-orgs: Create demo organization without setting an email.

zerver/lib/push_notifications.py, zerver/tests/test_push_notifications.py
[CZO Discussion:](https://chat.zulip.org/#narrow/stream/101-design/topic/notification.20emails/near/1609662)
> Fun fact about these (the gcm_alert function specifically): I believe these strings do not get used at all, and have not been used since at least 2019. On Android, we construct the notification UI ourselves in the client, and we ignore the alert string which that function is used to compute.
> So these can be whatever we like. Separately, a good PR would be to remove alert from the Android/FCM notification payloads entirely. We'd want to run that as an experiment for a bit on [chat.zulip.org](http://chat.zulip.org/) just to double-check I haven't missed some way it matters.
This should be test deployed on CZO
<details> …
=> push_notifications: Remove 'alert' field from the payload for android.

puppet/zulip_ops/templates/supervisor/conf.d/prometheus_postgres_exporter.conf.template.erb
Some of the collectors (e.g. `pg_stat_user_tables`) don't appear to work with `--auto-discover-databases`, which is deprecated since version 0.13.0[^1].
Explicitly set the database name.
[^1]: https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.13.0
<details>
</details>
=> postgres_exporter: Explicitly specify the zulip database.

web/e2e-tests/user-status.test.ts, web/src/click_handlers.js, web/src/emoji_picker.js, web/src/hotkey.js, web/src/popover_menus.js, web/src/popovers.js, web/styles/dark_theme.css, web/styles/popovers.css, web/styles/reactions.css, web/styles/tooltips.css, web/styles/zulip.css, web/templates/compose_control_buttons.hbs, web/templates/emoji_popover.hbs, web/templates/message_controls.hbs, web/templates/message_reactions.hbs, web/tests/hotkey.test.js
This PR is part of our ongoing effort to migrate from Bootstrap-based popovers to Tippy.
_I've spent a lot of time trying to debug why it only opens on the second click, but I haven't had any results. I would really appreciate any help here._
---
=> popovers: Migrate emoji popover to Tippy.

zerver/migrations/0244_message_copy_pub_date_to_date_sent.py, zerver/migrations/0245_message_date_sent_finalize_part1.py, zerver/models.py
Commit cf0eb46afcb22a236211ee2b3e3d23b8ef924eab (#21222) added this to let Django understand the `CREATE INDEX CONCURRENTLY` statement that had been hidden in a RunSQL query in migration 0244.  However, migration 0245 explained that same index to Django in a different way by setting `db_index=True`.  Move that to 0244 where the index is actually created, using `SeparateDatabaseAndState`.
Also remove the part of the SQL that was mirrored by dummy `state_operations`, and replace it with real operations.
[Discussion](https://chat.zulip.org/#narrow/stream/3-backend/topic/django.20migrations/near/1636383).
=> models: Remove duplicate index definition for date_sent

web/src/notifications.js, web/src/user_topics.js
[**CZO Report**](https://chat.zulip.org/#narrow/stream/9-issues/topic/muted.20stream.20notice/near/1635312)
Earlier, when a message was sent in a `followed topic` in a `muted stream`, a compose banner warning with a suggestion to `UNMUTE` the topic was shown.
<details><summary>Compose banner warning</summary>
">
</details> 
This PR fixes the incorrect behavior. No warning is shown in the case mentioned above.
[compose-banner.webm](https://github.com/zulip/zulip/assets/56781761/f548d4e3-af16-4178-a410-6384854de7ab)
<details> …
=> compose_banner: Remove the warning for messages sent in FOLLOWED topics in muted stream.

corporate/tests/test_stripe.py, templates/corporate/billing.html
We call this Free on the /plans page, not Limited
This is for this page when trying to downgrade, which says "Downgrade to Zulip Limited", which can be confusing (and we had a customer complain about not being whether this downgrade will cancel their subscription)
=> billing: Rename a few confusing references to "Zulip Limited".

web/templates/recent_view_row.hbs, web/templates/subscribe_to_more_streams.hbs, zerver/management/commands/makemessages.py
Corrects the formatting of translated strings in two Handlebars templates: `subscribe_to_more_streams.hbs`,  `recent_topic_row.hbs`.
Fixes #26640.
**Recent topics - Direct messages**:
| --- | --- |
| ![Screenshot from 2023-09-06 12-16-14](https://github.com/zulip/zulip/assets/63245456/80c19e22-8c47-4669-b8b0-c4f4052946ad) | ![Screenshot from 2023-09-06 12-16-01](https://github.com/zulip/zulip/assets/63245456/3a713c17-0589-479a-bbce-2e7ebdb5bd09) |
---
<details> …
=> i18n: Fixes formatting of translated strings in `subscribe_to_more_streams` and `recent_topic_row` templates.

web/src/narrow.js
As stated in the deactivate function comments, it should be called via `browser_history.go_to_location` so that all the correct functions are called like recent view being hidden.
This fixes a bug where searching for nothing results in activating all messages narrow without hiding recent view. Now, all messages should be activated as expected.
See #26592 for some discussion.
=> narrow: Don't call deactivate directly.

tools/test-js-with-node, web/src/emoji.ts, web/src/settings_emoji.js, web/src/settings_emoji.ts
This PR migrates `settings_emoji.js` module to TypeScript.
<details>
</details>
=> ts: Migrate `settings_emoji.js` to TypeScript.

zerver/lib/markdown/tabbed_sections.py
This REDOS was not exploitable, as its content is only read from checked-in files; regardless, simplify it to not backtrack.  We also do not actually have any location which use leading or trailing whitespace, so remove those optional bits.
<details>
</details>
=> tabbed_sections: Fix a backtrack-able regex.

web/src/input_pill.ts, web/src/messages_overlay_ui.ts
The `$` prefix on jQuery object variable names is important for our linter to be able to recognize them (see [eslint-plugin-no-jquery](https://github.com/wikimedia/eslint-plugin-no-jquery)).
FYI: @shameondev (#25569), @Lalit3716 (#25039).
=> Fix `$` prefix for jQuery object variable names

help/demo-organizations.md, templates/zerver/emails/account_registered.html, templates/zerver/emails/account_registered.txt, web/src/navbar_alerts.js, web/templates/invite_user_modal.hbs, web/templates/navbar_alerts/demo_organization_deadline.hbs, web/templates/settings/auth_methods_settings_admin.hbs, web/tests/navbar_alerts.test.js, zerver/lib/email_notifications.py
This PR takes care of a few follow-up issues from ongoing demo organizaiton work:
- Updates references in the code base with the shortened "demo org" to be the unabbreviated "demo organization" version. See https://github.com/zulip/zulip/pull/19741#discussion_r932758538.
- Makes all tooltips and tip banners for the demo organization owner needing to set an email address consistent, to reduce extra work for translators. See https://github.com/zulip/zulip/pull/22666#discussion_r1312328910.
- Adds a section to the demo organizations help article (which is still in draft state) about configuring an email for the organization owner, and link to that subheader in the tip banners (invite users modal and authentications methods tab). See …
=> demo-orgs: Fix shortened references in codebase and update help article draft.

zerver/lib/widget.py
When there was no space right after `/todo` but there was content on a new line, the message would be rendered plainly, not as a todo widget. This was because we split on only the space character to then check if the first token was a valid widget.
Now we split on both spaces and newlines to extract the widget name, irrespective of whether it is followed by a space or a newline. This results in the message being rendered as a todo widget as expected.
Fixes: [Issue's CZO thread here](https://chat.zulip.org/#narrow/stream/9-issues/topic/.2Ftodo.20list.20bug.3F) …
=> widgets: Fix bug where a new line right after /todo broke rendering.

zerver/lib/markdown/__init__.py, zerver/tests/test_markdown.py
When searching for links inside a topic name, the question mark (?) was used to split the topic. If a URL had a query after the URL (e.g., "?foo=bar"), then the query was trimmed from the URL.
Removing the question mark from `basic_link_splitter` is sufficient to fix this issue. The `get_web_link_regex` function then removes the trailing punctuation if any, including literal question marks.
[ZCO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/URL.20link.20for.20topic.20name.20not.20exact.20match.2C.20.2326368).
Fixes #26368 
<details> …
=> markdown: Fix URL link topic skipping query.

docs/production/troubleshooting.md
restart-server is almost always the way to go, so we can be clearer about it.
https://chat.zulip.org/#narrow/stream/31-production-help/topic/LDAP.20.2F.20Active.20Directory.20infinite.20page.20refresh.20after.20login/near/1617120 for some context
=> docs: Add a warning about restarting individual services.

docs/documentation/overview.md, tools/lint, tools/linter_lib/custom_check.py
Commit b53e67686011f7ed16c36dbb5d9a25f2aabaf052 (#19600) removed the last of our reST.
=> docs: Remove obsolete mentions of reStructuredText

tools/test-js-with-node
Fixes #25741
@timabbott  looks like this is the only things that needs to removed from [that](https://github.com/zulip/zulip/issues/25741#issuecomment-1712331240) list.
=> test-js-with-node: Remove deleted dropdown-list-widget module.

web/src/dropdown_widget.js, web/src/subscriber_api.js, web/src/user_profile.js, web/styles/popovers.css, web/templates/dropdown_list_container.hbs, web/templates/user_profile_modal.hbs, web/templates/user_profile_subscribe_widget.hbs
-------------------
Fixes: #18883 
CZO: [Topic](https://chat.zulip.org/#narrow/stream/101-design/topic/User.20profile.20popover.3A.20Subscribe.20widget.2E)
-----------
<details>
<summary>SS:</summary>
</details>
<details>
<summary>Overall DEMO:</summary>
</details>
------------------
<details>
</details>
=> user_profile: Add subscribe widget to user profile.

tools/test-js-with-node, web/src/hotkey.js, web/src/popovers.js, web/src/ui_init.js, web/src/user_group_popover.js
Main goal of this work is to help us migrate popovers to Tippy by separating `user_group_popover` from a huge `popovers.js` module. This will also help to reduce complexity of #26613.
=> popovers: Extract `user_group_popover` into separate module and refactor it. 

web/e2e-tests/settings.test.ts, web/src/popovers.js, web/src/settings_bots.js, web/src/settings_users.js, web/src/tippyjs.js, web/src/user_profile.js, web/styles/dark_theme.css, web/styles/modal.css, web/styles/popovers.css, web/styles/settings.css, web/templates/settings/admin_human_form.hbs, web/templates/settings/edit_bot_form.hbs, web/templates/user_profile_modal.hbs
- Migrate Manage user to full profile modal.
- Migrate Manage bot to full profile modal.
- Disable the deactivate user button if the owner is the only user in the organization.
- Redirect edit pencil to manage user tab.
---------------
Fixes: #21806 
Czo: [Bot icon feedback](https://chat.zulip.org/#narrow/stream/137-feedback/topic/list.20of.20streams.20for.20another.20user)
------------------
<details>
<summary>Manage user:</summary>
<br>
</details>
<details>
<summary>Manage bot:</summary>
<br>
</details>
<details>
<summary>Disabled button:</summary>
<br>
</details>
<details>
<summary>System bot:</summary>
<br>
</details>
<details>
<summary>Edit Pencil:</summary>
<br>
</details>
-----------------
<details> …
=> settings_users: Migrate "Manage user" and "Manage bot" modal to full profile modal.

puppet/zulip/manifests/common.pp, puppet/zulip_ops/manifests/prometheus/postgresql.pp, puppet/zulip_ops/templates/supervisor/conf.d/prometheus_postgres_exporter.conf.template.erb
This builds prometheus-community/postgres_exporter#843 to track per-index statistics.
<details>
</details>
=> postgres_exporter: Build from source for per-index stats.

web/src/topic_list_data.js, web/styles/dark_theme.css, web/styles/left_sidebar.css, web/styles/zulip.css, web/templates/topic_list_item.hbs, web/tests/topic_list_data.test.js
---
[CZO Discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/Follow.20Topics.20UI/near/1629130)
> When we follow a topic in a muted stream. It should not stay faded and also moves to the top in the topics list.
>  yeah, basically a followed topic is not correctly being treated as also unmuted in muted streams (being a tier of interest above being unmuted).
* First commit: It should not stay faded
* Second commit: moves to the top in the topics list
https://github.com/zulip/zulip/assets/56781761/b4cb1d2b-7e70-4903-9fee-88e8c9527507
<details> …
=> topic_list: Add icon, update color, and order of 'Followed Topics'.

analytics/views/installation_activity.py, pyproject.toml, requirements/common.in, requirements/dev.txt, requirements/prod.txt, tools/lib/pretty_print.py, tools/lib/template_parser.py, tools/semgrep.yml, version.py, zerver/data_import/import_util.py, zerver/lib/subscription_info.py, zerver/lib/test_runner.py, zerver/management/commands/check_redis.py, zerver/tests/test_events.py, zerver/tests/test_invite.py, zerver/tests/test_upload.py, zerver/tornado/django_api.py, zerver/views/video_calls.py, zerver/webhooks/bitbucket2/view.py, zerver/webhooks/bitbucket3/view.py, zerver/webhooks/clubhouse/view.py, zerver/webhooks/github/view.py, zerver/webhooks/gitlab/view.py, zerver/webhooks/groove/view.py, zerver/webhooks/intercom/view.py, zerver/worker/queue_processors.py, zilencer/management/commands/queue_rate.py
* python: Replace `functools.partial` with type-safe `returns.curry.partial`.
The type annotation for `functools.partial` uses unchecked `Any` for all the function parameters (both early and late). [`returns.curry.partial`](https://returns.readthedocs.io/en/latest/pages/curry.html
) uses a mypy plugin to check the parameters safely.
* ruff: Enable `B023` Function definition does not bind loop variable.
Python’s loop scoping is misdesigned, resulting in a very [common gotcha](https://docs.python-guide.org/writing/gotchas/#late-binding-closures) for functions that close over loop variables. The general problem is so bad that even the Go developers plan to break compatibility in order to [fix the same design mistake](https://go.dev/s/loopvar-design) in their language.
Enable the Ruff rule …
=> Replace functools.partial with type-safe returns.curry.partial; enable B023 bound-loop-variable

puppet/zulip/templates/nginx/trusted-proto.template.erb, zerver/middleware.py
This is common in cases where the reverse proxy itself is making health-check requests to the Zulip server; these requests have no X-Forwarded-* headers, so would normally hit the error case of "request through the proxy, but no X-Forwarded-Proto header".
Add an additional special-case for when the request's originating IP address is resolved to be the reverse proxy itself; in these cases, HTTP requests with no X-Forwarded-Proto are acceptable.
[CZO discussion](https://chat.zulip.org/#narrow/stream/31-production-help/topic/x-forwarded-proto.20in.207.2E3/near/1634982)
<details> …
=> nginx: Suppress proxy warnings when the proxy itself sent the request.

zerver/lib/typed_endpoint.py
This is alarming—apparently mypy doesn’t type-check the extra expressions in `Annotated` at all?
I think the symptom here will be that `update_message_backend` accepts aliases of `s`, `u`, `b`, `j`, `e`, `c`, `t` for `topic` instead of `subject`.
Cc @PIG208
=> typed_endpoint: Add missing tuple comma for OptionalTopic aliases

web/src/hotkey.js, web/src/popover_menus.js, web/src/popovers.js, web/src/stream_popover.js, web/styles/popovers.css, web/tests/hotkey.test.js
This PR is part of our ongoing effort to migrate from Bootstrap-based popovers to Tippy.
---
=> popovers: Migrate stream popover to tippy.

web/src/giphy.js, web/styles/popovers.css, web/templates/giphy_picker_mobile.hbs
We should render the giphy popover as a centered overlay for mobile-sized screens.
<details>
| broken | ![image](https://github.com/zulip/zulip/assets/53193850/2257c6a2-0793-4c56-a98c-02e05c5890ce) |
</details>
=> giphy: Fix giphy popover rendering on narrow screens.

web/src/emoji_picker.js, web/templates/emoji_popover_content.hbs, web/templates/emoji_popover_emoji_map.hbs
Fixes #25744
By rendering the emojis after initializing the simplebar container, the rendering time is decreased by ~30% as observed at 6x CPU cooldown on mac i7.
=> emoji_picker: Improve rendering time of emoji picker by ~30%.

web/src/compose.js, web/src/popover_menus.js, web/styles/compose.css, web/templates/compose_control_buttons.hbs, web/templates/compose_control_buttons_in_popover.hbs, web/templates/compose_control_buttons_popover.hbs, web/tests/compose.test.js
compose: Disable unneeded control buttons in preview mode.
Buttons which change the content in the compose textarea were so far
enabled even in preview mode, and would work, but those changes would
not be reflected in the visible preview. This is extremely confusing,
and can lead to the possibility of a user accidentally changing the
content of the compose textarea while previewing, and sending that.
Now we disable those buttons in preview mode, both when composing a new
message and when editing an existing one. We still show the tooltips,
but grey them out and make them unclickable.
Fixes: #20962
<details> …
=> compose: Disable unneeded buttons in preview mode.

package.json, patches/source-sans@3.46.0.patch, pnpm-lock.yaml
https://github.com/adobe-fonts/source-sans/pull/262
[Discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/Font.20Rendering.20Issues/near/1622093).
=> dependencies: Patch source-sans to correct `format()` for variable fonts

web/src/filter.js, web/src/narrow.js, web/tests/filter.test.js, web/tests/narrow.test.js
- Display title to the search bar in `sender:` narrow:
-   for me: Messages sent by you
-   for any user: Messages sent by User
- Rewrite the `is_common_narrow`
---------------------
Fixes: #18690
Czo: [is_common_narrow topic](https://chat.zulip.org/#narrow/stream/6-frontend/topic/is_common_narrow.20rewrite)
--------------
<details>
<br>
</details>
<details>
<br>
-------------------
</details>
-------------
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html)) …
=> search: Add title to the search bar when in "sender:" narrow & rewrite is_common_narrow.

api_docs/changelog.md, zerver/openapi/zulip.yaml
In commit ada2991f1c, when a user gains access to a stream due to a role change, in addition to sending `stream op: create` events, `subscription op: peer_add` events are sent for streams that the user gains access to due to their role change.
Updates the API changelog entry for feature level 205 and the `subcription op: peer_add` event documentation for this change.
**Notes**:
- I updated the `user_ids` and `stream_ids` field descriptions in the event documentation for the role change case as the general case description wasn't quite accurate.
- This API change has been merged, but I don't know if it warrants a discussion in **#api design** since the definition of the `subcription op: peer_add` event has changed a bit.
@sahil839 mentioning you for a review of these documentation udpates, …
=> api-docs: Update `subscription` event for `op: peer_add` in feature level 205.

web/styles/compose.css, web/templates/compose_banner/compose_banner.hbs, web/templates/compose_banner/success_message_scheduled_banner.hbs
By implementing a careful flexbox declaration on a new banner-element container, this presents banners accessibly across the full range of possible viewports--and relies only on a single, small media query to do so.
This also corrects the vertical center-alignment of the banner text, button (if any) and closing X button (if any).
Fixes: #25847
| Before, Unresolve banner | After, Unresolve banner |
| --- | --- |
| ![resolve-english-before](https://github.com/zulip/zulip/assets/170719/e8940c51-5c61-48f4-8ba4-49b7f129d311) | ![resolve-english-after](https://github.com/zulip/zulip/assets/170719/de70ef31-6409-4fda-81f9-9e12867219c6) |
| Before, Unresolve banner (Russian) | After, Unresolve banner (Russian) |
| --- | --- |
| …
=> compose: Present banners with intrinsic layout.

help/emoji-reactions.md, help/include/message-actions-menu.md, help/include/right-sidebar-user-card.md, help/include/self-user-card.md, help/include/stream-actions.md, help/include/topic-actions.md, help/include/user-card-three-dot-menu.md, help/marking-messages-as-read.md, help/schedule-a-message.md, web/styles/compose.css, web/styles/left_sidebar.css, web/styles/popovers.css, web/styles/right_sidebar.css, web/templates/compose.hbs, web/templates/compose_control_buttons.hbs, web/templates/left_sidebar.hbs, web/templates/presence_row.hbs, web/templates/stream_sidebar_row.hbs, web/templates/topic_list_item.hbs, web/templates/user_info_popover_content.hbs
This PR swaps out the remaining references to `ellipsis-v-solid`, whose middle dot was ever so smaller than the top and bottom dots. Adjustments to the CSS keep the layout as it was, with the exception of the left sidebar dots, which now share perfect alignment with the anchor point that is the + icon adjacent the STREAMS label.
Help documents have also been updated, including the new `more-vertical-spread` icon that appears in the redesigned hover controls and was merged there in #26283. 
The icon used for the vdots in this PR was added back in bf7cdc8f7af7d676873fa76d7e688295c128c1f6.
TODO:
| Sidebars, Before (temporary CSS used to display all dots) | Sidebars, After |
| --- | --- |
| ![vdots-before](https://github.com/zulip/zulip/assets/170719/ea3d5c …
=> vdots: Place new more-vertical icon across UI.

web/src/click_handlers.js, web/src/compose.js, web/src/popover_menus.js
This is a follow up to #26728, which disables buttons in preview mode for any message being edited.
Care is taken to pass the correct preview state (compose vs the message row being edited) to the popover menu so the buttons in it too can be disabled as needed.
<details>
</details>
=> compose: Disable unneeded control buttons in preview mode while editing.

.github/workflows/production-suite.yml
This works around a failure in the current postgresql-client-common and postgresql-client-15 packages; it exists primarily to improve the signal on our CI builds, as the failure is a real failure caused by the package upgrade process.
<details>
</details>
=> ci: Temporarily upgrade postgresql-client-common before upgrading.

tools/test-js-with-node, web/src/hotkey.js, web/src/playground_links_popover.js, web/src/popovers.js, web/src/ui_init.js, web/styles/reactions.css, web/templates/view_code_in_playground.hbs
This PR is part of our ongoing effort to migrate from Bootstrap-based popovers to Tippy.
- Keyboard Navigation
- Positioning
- Visual Appearance
- Dark/Light Theme Compatibility
- Scrolling Behavior
- Narrow/Wide Screen Rendering
<details>
| Narrow screen |
| ![image](https://github.com/zulip/zulip/assets/53193850/40f48c06-195e-40d6-8311-adbd68ebc871) | ![image](https://github.com/zulip/zulip/assets/53193850/26d40aea-a3e1-4f51-aa61-56775f493355)  |
</details>
---
=> Extract into separate module and migrate to Tippy playground links popover.

web/src/notifications.js, web/src/pm_list.js, web/src/unread.js, web/src/unread_ui.js, web/tests/pm_list.test.js, web/tests/unread.test.js
Created a new set `mentions_in_direct_message` which stores direct messages containing mentions. In `new_message_count`, direct messages with mention were added twice, once by res.mentioned_message_count and once by res.private_message_count so subtracting the intersection of both `mentions_in_direct_message` now gives an accurate count.
Fixes: #25453
Reproducer for this Issue:
1) In personal settings> notification setting, set "Unread count badge (appears in desktop sidebar and browser tab)" to `Direct messages and mentions` like this:
2) Then if you have a mention in DM it shows (2) in browser tab count even though there is only one unread message.
- Before:
- After:
<details> …
=> unread: Fix double counting of mentions in direct messages.

help/scim.md, zerver/actions/users.py, zerver/lib/scim.py, zerver/tests/test_scim.py
This adds support for syncing user role via the newly added "role" attribute, which can be set to either of
['owner', 'administrator', 'moderator', 'member', 'guest'].
Removes durable=True from the atomic decorator of do_change_user_role, as django-scim2 runs PATCH operations in an atomic block (https://github.com/15five/django-scim2/blob/33e7caa0c996d1977cb70a0f7463ba31d5ee24b8/src/django_scim/views.py#L393). We could also override the upstream's `PatchView.dispatch` if we really needed to - or just not support role sync via PATCH at all, since Okta doesn't need it. But I kind of don't see why `do_change_user_role` should intrinsically be prohibited form being called in a nested `atomic`, so it makes sense to me to just remove that resitrction :thinking: 
Tested manually with Okta.
=> scim: Add supporting for syncing the user role.

zerver/openapi/zulip.yaml
For arrays of objects in return values of API endpoints, any general description of the objects in the arrays should be documented in the description of the array. A description at the level of the items in the array will not be rendered in the API documentation. Descriptions of each property of the object will be rendered, but these are specific to the property and not the object as a whole.
Updates the `pms`, `streams` and `huddles` arrays of objects included in the `unread_msgs` object of the register response so that these general descriptions are at the array level in the OpenAPI documentation.
See these relevant CZO discussions:
- [#api documentation > unread_msgs.pms ...](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/register.3A.20.60unread_msgs.2Epms.5B.5D.2Eunr …
=> api-docs: Clean up descriptions in `unread_msgs` object register response.

web/styles/recent_view.css
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/sorting.20by.20unread.20count.20.2322790
=> recent_view: Reduce width of unread header.

templates/zerver/emails/confirm_new_email.subject.txt, zerver/actions/user_settings.py, zerver/tests/test_email_change.py
Updates the email subject for confirming an email change to include the realm information.
Noted in demo organization work in [this comment in #22666](https://github.com/zulip/zulip/pull/22666#issuecomment-1438816323):
> For the confirm email change subject, maybe the following would work well?
> 
> 1. For non-demo orgs, change it to: "Verify your new email address for `<organization name>`"
---
<details>
</details>
=> emails: Update subject for confirm_new_email to have realm information.

web/src/inbox_ui.js, web/src/recent_view_ui.js, web/styles/inbox.css, web/templates/inbox_view/inbox_list.hbs, web/templates/recent_view_table.hbs
Fixes #26746
Inbox:
Recent topics
=> Add explanation when Inbox view and Recent conversations views are empty

web/src/stream_popover.js, web/styles/dark_theme.css, web/styles/left_sidebar.css, web/styles/right_sidebar.css, web/styles/zulip.css, web/templates/left_sidebar.hbs, web/templates/presence_row.hbs, web/templates/stream_sidebar_row.hbs, web/templates/topic_list_item.hbs
This expresses the colors for vdots icons in just three variations, all as CSS variables. The colors are all derived from the existing design, and the dots colors in the streams/topics area was used as as reference. The only visual change here, then, is to the global filters area, whose vdots were the outliers prior to this change.
The three variations are:
1. hint: for touchscreens where a :hover state is not available
2. visible: for all screens when a parent element is highlighted/hovered
3. hover: for when the vdots themselves are hovered
The hint is a new color variation, which makes the always-visible dots considerably less distracting on touch screens, as the iPad screenshots below show.
Of course, now that those are expressed as variables--and any opacity shifts are part of the …
=> vdots: Simplify color states across UI.

web/src/click_handlers.js, web/src/message_edit.js, web/styles/zulip.css, web/templates/recipient_row.hbs
**First Commit**
A spinner is shown when the request is in progress for inline topic edit.
Earlier, the spinner was not visible in the dark theme.
**Before**
[old.webm](https://github.com/zulip/zulip/assets/56781761/f5922fc4-39ab-4114-848d-bfdbaa86d2e4)
**After**
[new.webm](https://github.com/zulip/zulip/assets/56781761/e159ace5-07c0-4196-be39-2cbf9b9f2306)
**Second Commit**
We replace the check icon for "Mark as resolved/unresolved" with a spinner while the request is still ongoing.
This helps to prevent double-clicking and reduce possible race conditions.
Fixes: #26190 
[spinner-2.webm](https://github.com/zulip/zulip/assets/56781761/5029c736-b691-46d7-94e7-3c1c67dd7926)
Note: To replicate the "request in progress" behavior for testing, comment out the …
=> toggle_resolve_topic: Display spinner while request is in progress. 

api_docs/changelog.md, version.py, web/src/message_edit.js, zerver/lib/response.py, zerver/openapi/openapi.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_flags.py, zerver/tests/test_message_topics.py, zerver/views/message_flags.py, zerver/views/streams.py
In feature levels 153 and 154, a new value for `result` was added for two endpoints that process messages in batches: [/api/delete-topic](https://zulip.com/api/delete-topic) and [/api/mark-all--as-read](https://zulip.com/api/mark-all-as-read#mark-all-messages-as-read).
Prior to these changes, `result` was either "success" or "error" for all responses, which was a useful API invariant to have for clients.
So, here we remove "partially_completed" as a potential value for "result" in a response. And instead, for the two endpoints noted above, we return a boolean field "complete" to indicate if the response successfully deleted/marked as read all the targeted messages (`complete: true`) or if only some of the targeted messages were processed (`complete: false`).
When only some messages were …
=> response: Remove "result: partially_completed" for success responses.

web/src/hash_util.ts, web/src/server_events_dispatch.js, web/src/tippyjs.js, web/src/user_group_edit.js, web/src/user_group_edit_members.js, web/src/user_group_ui_updates.js, web/src/user_groups_settings_ui.js, web/styles/dark_theme.css, web/styles/subscriptions.css, web/templates/user_group_settings/user_group_settings.hbs, web/templates/user_group_settings/user_group_settings_overlay.hbs
Implments changes suggested in #24443. Following changes are completed:
Fixes: Partially addresses #24443.
<details>
</details>
=> Improvements to groups UI.

docs/production/management-commands.md, help/add-or-remove-users-from-a-stream.md, help/archive-a-stream.md, zerver/actions/streams.py, zerver/management/commands/unarchive_stream.py, zerver/tests/test_subs.py
As discussed in [CZO thread](https://chat.zulip.org/#narrow/stream/101-design/topic/unarchiving.20streams/near/1636451), this PR updates the [Archive a stream](https://zulip.com/help/archive-a-stream) help center page, and documents the `unarchive_stream` [management command](https://zulip.readthedocs.io/en/latest/production/management-commands.html#other-useful-manage-py-commands) in the contributor docs.
<details>
</details>
=> help: Document `unarchive_stream` management command.

puppet/zulip/manifests/app_frontend_base.pp, puppet/zulip/templates/nginx/healthcheck.conf.template.erb, zerver/lib/exceptions.py, zerver/middleware.py, zerver/tests/test_health.py, zerver/views/health.py, zproject/urls.py
This endpoint verifies that the services that Zulip needs to function are running, and Django can talk to them.  It is designed to be used as a readiness probe[^1] for Zulip, either by Kubernetes, or some other reverse-proxy load-balancer in front of Zulip.  Because of this, it limits access to only localhost and the IP addresses of configured reverse proxies.
[^1]: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
<details> …
=> views: Add a /health healthcheck endpoint.

zerver/actions/message_send.py
message.realm is always already set at this point in the codepath. message.sender.realm not necessarily, so that access can trigger a query. In particular it does here in populate_db in send_messages:
```
for message in messages:
message_dict = build_message_send_dict(message=message)
```
causing a useless realm fetch in a loop.
The assert is tweaked to go by id instead of object comparison - right now it doesn't make a difference because as mentioned, message.realm is always already fetched, but might avoid a fetch in the future and is just a better practice in general in these query-count sensitive codepaths.
Eliminating this query in a loop in populate_db reduces the amount of time taken up by this message_dict block in `manage.py populate_db` in my machine by 1 second - from ~7.5s to …
=> build_message_send_dict: Tweak message.realm access.

templates/zerver/emails/account_registered.html, templates/zerver/emails/macros.html
As noted in [this CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.22contact.20us.22.20link.20in.20email.20not.20working/near/1642615), the new macros introduced for contact us links in commit dcea17eb4496ffa708c90b2d57dd7bc56b2400a2 were missing the "mailto:" in the anchor tags.
**Notes**:
- Updates the `contact_us_zulip_cloud` and `contact_us_self_hosted` email macros to have the "mailto:" scheme in the anchor tag for the support email address.
- Also updates the Zulip Cloud version of the support email anchor tag for the `account_registered` email, which has a slightly different format/text than the macro.
- Did a sweep of all anchor tags in the `templates/zerver/emails` directory to make sure there are no other email links that are broken. …
=> emails: Fix contact_us macros for "mailto" in email links.

zerver/openapi/zulip.yaml
Updates various parts of the endpoint response documentation, with a big focus on error responses.
**Notes**:
- The error responses are currently not validated in the backend `test_openapi` tests. There are a couple of reasons why, which I'll start a conversation about in CZO so we can hopefully get a plan/issue up to track fixing that.
- These changes update many error responses for the `code` field that's currently returned.
- Most of them are the generic `"BAD_REQUEST"` string.
- For non-generic `code` strings added to the documentation in these changes, I didn't go back to see when they were added to that error response for a feature level **Changes** note. I thought that could be a follow-up issue after these changes are merged.
- Removes the `JsonErrorBase` and `JsonError` shared …
=> api-docs: Update various areas of endpoint response documentation.

web/styles/message_row.css, web/styles/zulip.css
This PR primarily corrects a sneaky discrepancy between messages with and without a sender a mobile scales. I discovered this while confirming it was safe to close #17986. This fix is essential for both RTL and LTR languages; it was just more obviously a problem with an RTL language.
In fixing that discrepancy, it now also extends across all viewports a more generous area for message editing and message source views. That was originally available only in very narrow message-feed views, as part of a fluke with `max-content`. But this is now no longer a fluke, but a deliberate design choice (which can be adjusted further, of course). See [the discussion on CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/adjusting.20the.20message-edit.20form/near/1643675).
The PR also does a bit …
=> grid: Mobile-scale message area tweaks.

web/styles/left_sidebar.css
This shifts the 8px of margin to the wrapper, preserving the space to the right of the + icon, but no longer allowing it to shift the hover state or trigger the tooltip when clicking actually activates the search filter.
Fixes #11494 (at least the one fixable part; the rest should be closed as wontfix)
See [CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/clickable.20sidebar.20headings.20and.20icons/near/1643752).
| Before | After (no change to layout) |
| --- | --- |
| ![streams-icons-before](https://github.com/zulip/zulip/assets/170719/8fe5548b-2915-4132-977d-3edee95435f3) | ![streams-icons-after](https://github.com/zulip/zulip/assets/170719/cbfc54be-bbfe-4546-b96d-47243cb4cf78) |
| Hover States, Before | Hover States, After |
| …
=> left_sidebar: Hold hoverable area to + icon.

web/src/hotkey.js, web/src/popovers.js, web/src/user_card_popover.js, web/tests/hotkey.test.js
This PR is part of our ongoing effort to migrate from Bootstrap-based popovers to Tippy.
- Keyboard Navigation
- Positioning
- Visual Appearance
- Dark/Light Theme Compatibility
<details>
<summary>manage menu popover</summary>
| Light theme |
| ![image](https://github.com/zulip/zulip/assets/53193850/c198558c-cdb8-49d3-941a-ac6bc8c58c23) | ![image](https://github.com/zulip/zulip/assets/53193850/8ff794b7-4741-49ef-acfa-427359007018) |
| Dark theme |
| ![image](https://github.com/zulip/zulip/assets/53193850/e2e48acd-5c5f-488c-a798-5a90733de852) | ![image](https://github.com/zulip/zulip/assets/53193850/268af4ee-dbf5-49df-857a-0e6b9ca9fc59) |
</details>
---
=> Migrate user card manage menu popover.

help/dark-theme.md
This fixes a formatting bug on https://zulip.com/help/dark-theme since the info after the last instruction shouldn't be inside the instructions block.
=> help: Fix formatting issue in "Dark theme" page.

zerver/tests/test_decorators.py, zilencer/urls.py
These don't make sense (because authentication here is not based on sessions) and aren't used.
https://chat.zulip.org/#narrow/stream/378-api-design/topic/Push.20bouncer.20endpoints.20namespaces
Tested in dev env by accessing `http://localhost:9991/api/v1/remotes/push/notify` or `http://localhost:9991/json/remotes/push/notify` and verifying the `/json` endpoint stops existing, while the `/api/v1` run still works.
=> zilencer: Remove /json versions of push bouncer endpoints.

web/src/typeahead_helper.js, web/tests/typeahead_helper.test.js
Earlier mid word parts matching with the search query were also
highlighted (made bold), but since actual matching for showing search
suggestions is based on prefix matching, this highlighting logic is
now made to be in sync with the search suggestions matching logic.
---------------------------------------------------------------------------
`make_query_highlighter` called `highlight_with_escaping_and_regex`
once for each word in the phrase, due to which only 1 word searches
could be highlighted. For example searching for `two wo` resulted
in no highlighting at all in `two words`.
One call per word in the phrase was also redundant since the called
function can handle a multi word query. So now the entire phrase is
passed to the called function just once.
Follow up to …
=> typeahead: 2 highlighting bugs fixed

web/src/settings_linkifiers.js, web/styles/settings.css, web/templates/settings/admin_linkifier_list.hbs
So that the user can still select and copy text from the body of the
linkifier rows. It might be helpful if we extend this behavior to other
draggable rows, like those for custom profile fields settings.
Fixes:
#26798
https://chat.zulip.org/#narrow/stream/6-frontend/topic/Reordering.20linkifiers/near/1644433 
<details>
</details>
=> linkifiers: Use only the handle for dragging.

web/src/message_scroll.js
To make the date change in recipient header more smooth, we update it with throttled scroll event. This can cause some performance regressions on slow computers during scrolling but nothing I can notice even with 6x CPU slowdown on Intel i7 on mac.
This is an alternative to #25163 since implementing it seems harder than expected. The date changing animation cannot be made smooth without serious structural changes to how messages are rendered.
=> message_scroll: Update sticky header date more frequently.

web/src/compose_recipient.js, web/src/people.ts, web/tests/compose_actions.test.js
After the changes in https://github.com/zulip/zulip/pull/25572, users were no longer able to start a direct
message with bots if the organization disabled direct messages. However,
we should allow direct messages to bots regardless of the policy because
it's a useful interface for users to interact with various classes of
bots.
user_ids_string_to_ids_array was also modified to prevent cases where
the split function returned an array of [0] rather than [] when dealing
with a empty id string of "".
Fixes: #21896.
<details> …
=> compose: Allow the user to direct message bots despite of policy.

help/mobile-notifications.md
This is a follow-up PR (https://github.com/zulip/zulip/pull/26655#issuecomment-1710364566) to add instructions for getting to the "Troubleshooting" screen, and a short intro paragraph for context.
<details>
</details>
=> help: Document troubleshooting screen for mobile notifications.

web/src/hotkey.js, web/src/inbox_ui.js, web/src/message_edit.js, web/src/popover_menus.js, web/src/stream_popover.js, web/styles/inbox.css, web/templates/inbox_view/inbox_row.hbs, web/templates/inbox_view/inbox_stream_header_row.hbs
Fixes https://github.com/zulip/zulip/issues/26773
Now unread count of header is a sum of non hidden topics / DMs
unread count.
=> inbox: Calculate unread count of headers based on active filters.

web/e2e-tests/admin.test.ts
This test has been flaking for a couple months, and it hasn't felt worth it for anyone to debug, so we should disable or delete it.
I chose deletion, since I don't think this settings panel is a high-value place for end-to-end testing.
=> puppeteer: Remove flaky default streams test.

web/src/compose_fade_helper.ts, web/src/compose_fade_users.js, web/src/compose_fade_users.ts, web/src/hash_util.ts, web/src/recent_view_util.ts, web/src/types.ts, web/src/util.ts
[Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/typescript.3A.20message.20type/near/1640680).
This replaces part of #26505, but in a way that allows `compose_fade_helpers.should_fade_message` to correctly accept `Message`.
Cc @jychen630 @Lalit3716 @shameondev.
=> Use TypeScript unions for message types; convert compose_fade_helper, compose_fade_users to TypeScript

web/tests/typeahead_helper.test.js
We refactor the tests to check if a multi word query's result is correctly highlighted (multi word highlighting fixed in e2c23b656ecac7cd78ab2584dd462d7ed309b3e1).
The test case was already present, but the setup was not correct, and has been corrected now to safeguard against regression in the future.
<details>
</details>
=> typeahead: Improve tests for multi word match's highlighting.

zerver/lib/event_schema.py, zerver/openapi/zulip.yaml
See [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/.60all.60.20in.20update_message_flags.2Fremove/near/1638953) about these changes.
**Notes**:
- Clarifies that the `all` field in the `op: "add"` event is only relevant for the `"read"` message flag, and that it will be false for all other specified flags in theses events.
- Deprecates the `all` field in the `op: "remove"` event and document that it is false for all specified flags.
- Updates the deprecated `operation` field description and makes a few other small revisions to the event text for clarity and accuracy.
**Questions**:
- We have a handful of **Deprecated** notes in the API documentation without a feature level, and I add one here as we're not changing the server/backend code, but only …
=> api-docs: Update the add and remove `update_message_flags` events.

web/styles/rendered_markdown.css
This reverts commit d899c03da62988ab96753154f028fc80171f2489 (#25094, cc @N-Shar-ma). It broke the display of list items with inline formatting.
[Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/numbered.20list.20rendering.20broken/near/1645728).
=> Revert "markdown: Fix 3+ digit marker lists retaining alignment for 2 digits."

web/src/hotspots.js, web/src/popovers.js
Previously, this function was used by other bootstrap popovers, but such popovers have all been migrated to Tippy.
Hotspots uses some of that machinery but I think doesn't actually use the Bootstrap popovers system.
=> hotspots: Move compute_placement to only module using it.

web/src/navbar_alerts.js, web/templates/navbar_alerts/bankruptcy.hbs
Improves the alert message to clearly state that "You have at least 50,000 unread messages."
**TODO:** Write a help center doc - **/help/marking-messages-as-read#bankruptcy**
Fixes #17469.
---
<details><summary>At least 50K</summary>
</img>
</details> 
<details><summary>500 < unreads < 50K and more than 2 days of inactivity</summary>
</img>
</details> 
---
<details>
</details>
=> navbar_alerts: Improve info for users having at least 50K unreads.

help/configure-unread-message-counters.md, help/include/sidebar_index.md
- Adds a new page in the "Reading messages" section to document this new feature (#24237).
<details>
</details>
=> help: Document "Show unread count for" display preference.

web/styles/portico/portico.css
This restores the styling previously added by commit ceec61ba109b87d5de8c2c7aa05fd45028e28e3c (#25573). The .scroll-target class of commit b852da6eedc5776a94ba65a8e69543f1698bf494 (#25573) was removed by commit 8dba4cbba6ccd17810a27edbb26fa8a4738a8a40 (#15713, merged later) and is unnecessary.
NB I never liked the way this looks and especially the way the extra border causes the header height to change on click, but I’m restoring it as-is since its removal was unintended.
=> help: Restore scroll target styling

web/src/unread.js
In the muted stream, the unreads from followed topics were not adding up to the total unread count of the stream if both unmuted and followed topics had unreads.
</img>
</details> 
</img>
</details> 
<details>
---
</details>
=> unread_msgs: Fix the unread count in muted streams.

web/src/message_list_view.js, web/templates/recipient_row.hbs
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/follow.20topic.20in.20unsubscribed.20stream/near/1635049)
> currently the UI for following topics in the message header bar of the web app appears if I look at a public stream that I'm not subscribed to.
> Select a public stream Iago isn't subscribed to and view the stream (Shift V). Iago can now follow a topic in the stream view via a message header bar without suscribing to the stream.
> I feel like we should probably not have that option displayed until the user subscribes to the stream
<details><summary>Dummy ImageNot subscribed</summary>
</img>
</details> 
---
<details>
Communicate …
=> message_header: Remove the widget to change the visibility policy.

analytics/tests/test_support_views.py, zerver/forms.py, zerver/management/commands/import.py, zerver/tests/test_realm.py, zerver/tests/test_signup.py
Fixes: #23896.
<details>
</details>
=> realm: Differentiate reserved realms from in-use realms.

corporate/lib/stripe.py, corporate/tests/test_stripe.py
Fixes two bugs involving organization with
exempt_from_license_number_check enabled:
1. If the organization had e.g. 100 users and upgraded their plan, specifying 50 licenses, the generated `LicenseLedger` and thus the corresponding invoice was still for 100 users.
2. The organization was unable to use the `billing/plan` endpoint (update plan endpoint) to make their number of licenses less than the current number of users.
Organizations with exempt_from_license_number_check are supposed to be able to declare whatever license number they want, as this attribute allows having pricing schemes where an organization only pays us for a subset of their users.
Tested with the automated tests, making sure that without the changes in `stripe.py`, the tests would fail in a way demonstrating the bug.
=> billing: Fix license counting in exempt_from_license_number_check case.

web/src/recent_view_data.ts, web/src/recent_view_util.ts
Since `msg.to_user_ids` is always defined when `msg.type === "private"`, return type is just string.
discussion: https://github.com/zulip/zulip/pull/26813#discussion_r1334598844
=> recent_view_util: Fix return type of get_key_from_message.

web/src/search.js
Fixes issue reported here: https://chat.zulip.org/#narrow/stream/9-issues/topic/search.20keyboard.20UI.20regression/near/1646401
I wish I could remember why these if statements were here, but I don't think we need them (or at least not anymore?).
=> search: Always select search bar text when initiating search.

zerver/lib/hotspots.py, zerver/models.py
Fixes part of #26874 
Finished renaming 'display settings' -> 'preferences' in the following files to finish out the work started in https://github.com/zulip/zulip/issues/25945
zerver/lib/hotspots.py
zerver/models.py
=> Rename some references to display settings -> preferences

help/add-a-custom-linkifier.md
Current: https://zulip.com/help/add-a-custom-linkifier#reorder-linkifiers
Updated section: 
Note that the wording in the instruction is designed to match custom profile fields:
=> help: Tweak wording in help/add-a-custom-linkifier.

web/styles/search.css, web/styles/zulip.css
This corrects an issue where long DM conversations collided or were overlapped by the collapsed search inputs.
Additionally, it expresses the fixes along with existing styles, previously applied only to stream descriptions, as calculations around CSS variables. Values were derived from the existing design.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/availability.20and.20status.20emoji.20in.20DM.20views/near/1648122)
| Group DMs, Before | Group DMs, After |
| --- | --- |
| ![group-dms-before](https://github.com/zulip/zulip/assets/170719/83ea8693-9424-4e2a-baac-4b722c990ec3) | ![group-dms-after](https://github.com/zulip/zulip/assets/170719/2e911b53-3830-40bc-b2ab-1867815e2f31) |
| Stream Descriptions, Before | Stream …
=> navbar: Avoid collisions with title content and search elements.

docs/testing/manual-testing.md, web/e2e-tests/message-basics.test.ts, web/src/filter.js, web/tests/filter.test.js
This PR changes the top-navbar title from "Direct messages" to "All direct messages."
Developer documentation (apparently the only docs that mention this view by name) has also been updated to reflect this change.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/availability.20and.20status.20emoji.20in.20DM.20views/near/1647277)
| All DMs view, before | All DMs view, after |
| --- | --- |
| ![all-dms-before](https://github.com/zulip/zulip/assets/170719/9bf69ede-0c45-4b05-a97b-6b5ddc7ca2b2) | ![all-dms-after](https://github.com/zulip/zulip/assets/170719/0ea4272a-9a63-41ad-956a-858fbc662072) | 
| [Dev docs, before](https://zulip.readthedocs.io/en/latest/testing/manual-testing.html) | [Dev docs, …
=> view_labels: Change 'Direct messages' to 'All direct messages'.

api_docs/changelog.md, version.py, zerver/lib/message.py, zerver/lib/user_topics.py, zerver/openapi/zulip.yaml, zerver/tests/test_events.py, zerver/tests/test_message_flags.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/register.3A.20.60unread_msgs.2Ementions.60/near/1645170)
</img>
</details> 
</img>
</details> 
The count is still not correct as we don't use `unread_msgs.count` directly;  PR to show count correctly: #26849
**Updated Docs**
<details><summary>Count</summary>
</img>
</details> 
<details><summary>Streams</summary>
</img>
</details> 
<details><summary>mentions</summary>
</img>
</details> 
---
<details>
- [] Highlights technical choices and bugs encountered. …
=> unread_msgs: Fix all unreads in muted stream being treated as muted.

web/src/topic_list.js, web/styles/left_sidebar.css, web/templates/more_topics.hbs, web/templates/stream_sidebar_row.hbs, web/templates/topic_list_item.hbs
This PR is the first of a few closely-related planned PRs to introduce grid-based layout to all the different rows in the left sidebar. I'm beginning with topics because they're the innermost rows, and getting them right will make it easier to move up the tree to headings and DM rows (which will increase in number in [the redesigned left-sidebar](https://zulip-sidebar.vladkorobov.repl.co/) and [collapsing views PR](https://github.com/zulip/zulip/pull/26035)).
CZO discussions:
* [UI design: left sidebar](https://chat.zulip.org/#narrow/stream/101-design/topic/UI.20redesign.3A.20left.20sidebar/near/1644570)
* [Left sidebar rows as grids](https://chat.zulip.org/#narrow/stream/6-frontend/topic/Left.20sidebar.20rows.20as.20grids/near/1645034)
<details>
<summary><b>Explanation and theory behind …
=> left_sidebar: Gridded stream and topic rows.

web/src/search.js, web/tests/search.test.js
Previously clearing the search box and pressing enter would redirect the user to All Messages. This commit changes the behavior so that the search bar closes with no other effects.
More discussion on this on CZO here:
https://chat.zulip.org/#narrow/stream/101-design/topic/recent.20conversations.20for.20streams/near/1621501
=> search: Close search box when searching for an empty string.

web/templates/recent_view_table.hbs
=> recent_view_table: Add a tooltip to unread sort header.

zerver/openapi/zulip.yaml
In commit 3e369bcf9, the `code` field for [api/deactivate-own-user](https://zulip.com/api/deactivate-own-user) was incorrectly documented as `"BAD_REQUEST"`, which is the code for the similar error returned by [api/deactivate-user](https://zulip.com/api/deactivate-user).
Corrects the error code to be `"CANNOT_DEACTIVATE_LAST_USER"` and adds documentation for the two other fields returned by this error response: `is_last_owner` and `entity`.
Note that the descriptions for the fields are added in the error response schema will not be rendered in our current documentation. They are rendered in other third-party tools and are therefore good to have in our OpenAPI documentation. The description that will be rendered in our documentation is the general error response schema description and that …
=> api-docs: Correct error documentation for api/deactivate-own-user.

web/src/unread.js, web/tests/unread.test.js
CZO: https://chat.zulip.org/#narrow/stream/6-frontend/topic/Wildcard.20mentions.20in.20direct.20messages
Wildcard mentions in direct messages were not being counted as mentions due to incorrect calculation of the `is_unmuted_mention` variable in the `update_message_for_mention()` function in `unread.js`. Fixed this by correcting the calculation of the `is_unmuted_mention` variable to be equal to the `message.mentioned && (message.type === "private" || !user_topics.is_topic_muted(message.stream_id, message.topic))`.
Fixes: 
<details> …
=> unread: Fix logic for wildcard mentions in direct messages.

web/src/copy_and_paste.js, web/styles/dark_theme.css, web/styles/zulip.css, web/templates/edited_notice.hbs, web/templates/message_avatar.hbs, web/templates/message_body.hbs
This allows message content in `/me` messages to be selected as well since the content in `/me` messages is a part of `sender_name`.
=> message_body: Allow sender name to be selected.

web/src/bulleted_numbered_list_util.js, web/src/compose_ui.js, web/src/composebox_typeahead.js, web/styles/app_components.css, web/templates/compose_control_buttons.hbs, web/templates/compose_control_buttons_in_popover.hbs, web/tests/compose_ui.test.js, web/tests/composebox_typeahead.test.js
A formatting button below the compose box can format the selected text
by bulleting or unbulleting the selected (partially or completely)
lines. The behaviour is modelled closely after how GitHub's bullet
list format button works.
A formatting button below the compose box can format the selected text
by numbering or unnumbering the selected (partially or completely)
lines. The behaviour is modelled closely after how GitHub's numbered
list format button works.
When the user is typing a numbered / bulleted list in the compose box,
on pressing Enter the list syntax will be inserted automatically on
a new line, and removed if Enter is pressed after an empty line.
Fixes: #20305.
Formatting buttons: …
=> Make it easier to work with numbered and bulleted lists

web/styles/compose.css
This ensures uniform display and flexing of different bits of banner content, including:
* Banners like Sent! Scroll down to view...) that have only a classless `<p>` marking their content
* Banners like the unscheduled message allert, which puts a .banner_content class right on the paragraph
* Banners like the Your message was sent to a stream you have muted", which tuck a `<p>` into a div with the .banner_content class
This carries forward the intrinsic design from #26730, but takes care of other banner structures that that PR neglected.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.22Unmute.20topic.22.20button.20placement/near/1649325)
| --- | --- |
| …
=> compose_banners: Explicitly target banner content, child p.

docs/production/authentication-methods.md
https://chat.zulip.org/#narrow/stream/127-integrations/topic/LDAP.20advanced.20realm.20control for motivation
This fixes the explanation of the setting's syntax to be more precise (which doesn't mean "easily understandable" - because the setting is a bit tricky) as well as an example to illustrate it.
=> ldap: Improve doc on AUTH_LDAP_ADVANCED_REALM_ACCESS_CONTROL.

zerver/actions/user_groups.py, zerver/tests/test_audit_log.py, zerver/tests/test_events.py, zerver/views/user_groups.py
Adds support for bulk-adjusting a single user's membership in multiple user groups in a single transaction in the low-level actions functions, for future use by work on #9957.
@mateuszmandera can you review? Feel free to merge if you're happy with the implementation.
=> user_groups: Improve bulk membership change logic.

zerver/management/commands/delete_old_unclaimed_attachments.py
42f1cb3444e1 updated the default up, from 1 week to 5 weeks, but did not adjust the documentation.
<details>
</details>
=> delete_old_unclaimed_attachments: Update docs on default max age.

zerver/lib/soft_deactivation.py, zerver/tests/test_soft_deactivation.py
Rather than fetch all UserMessage rows for all streams, and subtract those out in Python-space from the list of all Message rows the user may have received -- do this via a "NOT EXISTS" subquery.  This is much better indexed (performing in fractions of milliseconds rather than hundreds), and also consumes much less memory.
<details>
</details>
=> soft_deactivation: Stop computing "new messages" in Python.

zerver/lib/push_notifications.py, zerver/tests/test_push_notifications.py
This reverts b8581e2895e242208beb3ac9fe0c2cf1de233ac3.  The mobile client on Android parses this field using:
```kotlin
timeMs = data.require("time").parseLong("time") * 1000
```
This throws an error if value is not `long` (i.e. an integer), resulting in dropped notifications on Android from servers which had deployed b8581e2895e242208beb3ac9fe0c2cf1de233ac3.
Switch back to sending an integer, but keep the behaviour from fd6091ad17b5 where we send the timestamp in the payload of both Android and Apple push notifications.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributin …
=> push_notifications: Send timestamp with only second granularity.

tools/lib/provision_inner.py
Refactor tools/lib/provision_inner to conditionally write activation commands to the user's bash profile based on the machine type. Activation commands are now skipped for non-Vagrant/Droplet/Docker setups. 
This pull request refactors the `tools/lib/provision_inner` script to enhance machine type detection. Activation commands for the Zulip environment are now conditionally written to the user's bash profile, specifically targeting Vagrant, Droplet, and Docker setups. This change ensures that the activation script is only added for dedicated Zulip environments.
Fixes:  #15029
<details> …
=> Refactoring Provisioning Logic for Improved Activation

web/src/recent_view_ui.js, web/tests/recent_view.test.js
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/followed.20topics.20in.20muted.20streams/near/1649298)
> followed topics in muted streams are missing from Recent conversations, unless "Include muted" is selected. They should show up there, like unmuted topics.
---
<details><summary>Recent conversations</summary>
</img>
</details> 
---
<details>
</details>
=> recent_view: Show 'followed topics in muted streams' in recent view. 

tools/semgrep-py.yml, zerver/tests/test_delete_unclaimed_attachments.py, zerver/tests/test_invite.py
The default is `tick=True` (https://github.com/adamchainz/time-machine#traveldestination--ticktrue), which I think we generally don't want as it introduces unpredictability. So the first commit fixes existing instances where we didn't set `tick`, and the second proposes a semgrep rule to avoid this pattern of forgetting to set the kwarg.
=> tests: Eliminate instances of time_machine.travel without tick=False.

zerver/actions/create_user.py, zerver/tests/test_users.py
These do not represent users who were ever active, so they should not be able to be reactivated.
See also #26703.
<details>
</details>
=> users: Prevent mirror dummy users from being "reactivated."

templates/corporate/for/open-source.html
- Visually, the new bottom quote is shorter, but I think it's OK.
- The Lean quote doesn't really match the theme of the section it's under (MIXX was a better fit). I think it's OK?
<details>
<summary>
New quote
</summary>
</details>
<details>
<summary>
New quote (mobile width)
</summary>
</details>
<details>
<summary>
Lean quote (moved)
</summary>
</details>
=> portico: Update quotes on /for/open-source.

zerver/actions/create_user.py, zerver/lib/bulk_create.py, zerver/lib/create_user.py, zerver/lib/i18n.py, zerver/tests/test_auth_backends.py, zerver/tests/test_mirror_users.py, zerver/tests/test_signup.py, zerver/tests/test_users.py, zerver/views/registration.py
This fixes a regression introduced in
9954db4b59f5b3565a998e0f8e03013669e7fb8a, where the realm's default
language would be ignored for users created via API/LDAP/SAML,
resulting in all such users having English as their default language.
The API/LDAP/SAML account creation code paths don't have a request,
and thus cannot pull default language from the user's browser.
We have the `realm.default_language` field intended for this use case,
but it was not being passed through the system.
Rather than pass `realm.default_language` through from each caller, we
make the low-level user creation code set this field, as that seems
more robust to the creation of future callers.
See https://chat.zulip.org/#narrow/stream/31-production-help/topic/default.20language.20for.20new.20users/near/1648829 for …
=> i18n: Fix default language for users created via API/LDAP.

web/styles/settings.css, web/templates/settings/account_settings.hbs
- Improves the readability of alert notification banners by breaking long words into multiple lines and wrapping the content to fit the viewport.
- Prevent the notification banner content from spilling over by wrapping it inside the notice.
- Decrease the gap between the account heading and the 'account-alert-notification' banner. 
Fixes: #23653
------------------
<details>
<br>
</details>
**New Changes:**
<details>
<summary>When the  email is short:</summary>
<br>
</details>
<details>
<summary>When the  email is long:</summary>
<br>
</details>
<details>
<summary>View port changes:</summary>
<br>
</details>
<details>
Communicate …
=> settings: Prevent long email spills over in notice.

CONTRIBUTING.md
Implements https://github.com/zulip/zulip/pull/23718#discussion_r1036829056.
I tested the link.
=> docs: Add a note about "good first issue" label to contributing guide.

web/tests/popover_menus_data.test.js
Added test file to cover new static/js/popover_menus_data.js file.
Current test cases include:
Message popover in which user has all actions available on the message.
Message popover in which user has only view actions on the message.
Message popover in which user can move and view but not edit the message.
User is not admin in any test case.
Fixes: 
Increased line/statement coverage from 0 --> 100%.
Increased branch coverage from 0 --> 88.33%.
Tooling tips: https://zulip.readthedocs.io/en/latest/tutorials/screenshot-and-gif-software.html …
=> Improve test coverage for popover_menus_data. 

docs/production/authentication-methods.md
Url to authentik documentation regarding zulip integration is waiting to be merged. It should be available soon at the url I provided. (https://goauthentik.io/integrations/services/zulip/)
I haven't tested signed saml request. I might be able to add that part later.
=> added documentation  for saml with authentik

web/src/popover_menus.js
This caused a bug where input keys were not working since `compose_mobile_button` was always set.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/j.2C.20k.2C.20and.20Esc.20broken.20again
=> poopover_menus: Set correct instance as undefined.

web/src/integration_url_modal.js, web/styles/settings.css, web/templates/settings/generate_integration_url_modal.hbs, zerver/lib/events.py, zerver/openapi/zulip.yaml
This PR makes the following improvements to the integration URL modal:
- Migrates the integration input from typeahead to a dropdown widget.
- Disables the `Copy URL` button when the topic input is empty
Fixes: #26797
<hr>
<details> 
<summary>Integration input </summary>
| ![typeahead](https://github.com/sbansal1999/zulip/assets/35286603/28655e9d-51b6-4965-a8eb-7740a9062654) | ![dropdown widget](https://github.com/sbansal1999/zulip/assets/35286603/154de25b-8bdc-48d1-8dc2-32892ef6e2b8) | 
</details>
<details>
<summary> "Copy URL" button when topic input is empty </summary>
| ![image](https://github.com/sbansal1999/zulip/assets/35286603/db202417-0401-4784-b111-6ff51a046224)  | …
=> Improvements to integration URL modal.

tools/test-js-with-node, web/src/copied_tooltip.js, web/src/copied_tooltip.ts
=> copied_tooltip: Remove incorrect $ prefix from non-jQuery variable; convert module to TypeScript

web/src/compose.js, web/src/compose_actions.js, web/src/compose_state.js, web/src/drafts.js, web/src/message_edit.js, web/src/message_list_view.js, web/tests/popover_menus_data.test.js
This PR is a fixed and updated version of #24680 
<details>
</details>
=> compose: Refactor drafts restoration code to reduce duplication

web/src/compose.js
Builds off of #21848, from this [CZO Topic](https://chat.zulip.org/#narrow/stream/101-design/topic/topic.20box.20width)
I chose "input" over a keyboard event. At first I tried "keydown", since I want the placeholder to always match the input, but that was being caught in an event handler somewhere (I'm guessing?) when I selected the input and cleared it. Input worked more reliably.
=> compose: Update recipient placeholder when topic input changes.

tools/check-schemas, web/tests/lib/events.js, zerver/lib/event_schema.py, zerver/openapi/zulip.yaml, zerver/tests/test_events.py
On current main, `tools/check-schemas` has the following output:
```console
$ tools/check-schemas
WARNING - NEED SCHEMA: scheduled_messages__add
WARNING - NEED SCHEMA: scheduled_messages__remove
WARNING - NEED SCHEMA: scheduled_messages__update
WARNING - NEED SCHEMA to match OpenAPI realm_filters_event
WARNING - NEED SCHEMA to match OpenAPI drafts_add_event
WARNING - NEED SCHEMA to match OpenAPI drafts_update_event
WARNING - NEED SCHEMA to match OpenAPI drafts_remove_event
WARNING - NEED SCHEMA to match OpenAPI scheduled_messages_add_event
WARNING - NEED SCHEMA to match OpenAPI scheduled_messages_update_event
WARNING - NEED SCHEMA to match OpenAPI scheduled_messages_remove_event
Successful check. All tests passed.
```
Adds/corrects the following missing events schema:
- Adds schemas for …
=> tools: Add missing event schema checks.

help/demo-organizations.md, tools/lib/capitalization.py, tools/test-js-with-node, web/src/admin.js, web/src/demo_organizations_ui.js, web/src/navbar_alerts.js, web/styles/app_components.css, web/styles/dark_theme.css, web/styles/settings.css, web/templates/navbar_alerts/demo_organization_deadline.hbs, web/templates/settings/convert_demo_organization_form.hbs, web/templates/settings/demo_organization_warning.hbs, zerver/views/development/registration.py
Revision of the 3rd commit in https://github.com/zulip/zulip/pull/19741.
Adds warning banner to organization settings overlay/tabs for demo organizations, which is also a button for opening the modal to convert the demo organization into a permanent organization.
---
**Notes**:
- Tim's comment in the above PR about this commit:
> The last commit can be its own independent PR; it looks like it's not too distant from the final shape that we want, but I think probably the first N rounds of iteration for it will be with @alya to get the language/flow right.
- Currently, the only updates I've made to this work is cleaning up "org" to be "organization" in settings and templates, and a small update to some jQuery formatting.
- Because we've moved the creation of demo organizations without an …
=> demo-orgs: Add UI for converting to permanent organization.

web/src/popover_menus.js
I checked for stream, topic and message action popovers.
I don't recall how we used to do it earlier or what we changed, but this seems to work well.
=> popover_menus: Fix enter keypress not working on some popovers.

web/src/compose.js
Commit 57340a888c4aed129be004f155e7aed02a05007f (#19003) separated it from the variable it was commenting, and commit
8ced075643c96fedaf73661210b810fd87017258 (#22754) changed that to a different variable, so I infer that nobody thought this documentation was important.
=> compose: Delete obsolete comment

web/src/settings_notifications.js, web/src/stream_edit.js, web/src/stream_popover.js, web/src/stream_settings_ui.js
`stream_muting.update_is_muted` will be called when the event comes back from the server.
(79, 37) → (78, 35). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1653379).
=> stream_settings_ui: Remove set_muted wrapper

web/styles/compose.css, web/templates/buddy_list_tooltip_content.hbs, web/templates/change_visibility_policy_button_tooltip.hbs, web/templates/message_edit_notice_tooltip.hbs, web/templates/message_inline_image_tooltip.hbs, web/templates/narrow_to_compose_recipients_tooltip.hbs, web/templates/tooltip_templates.hbs
This PR consists of the following changes:
- Replace `<span>` tags with `<p>` tags inside the tooltip's inner content to remove the redundancy of having to use break tags to separate the tooltip's title and its content.
- Add the hotkey hints in the tooltip of the view edit history option, the shortcut (Shift + H) for which was added in PR #26245 
- Swap "Click to view edit history." and the edit status string (EDITED/MOVED/SAVING) to make the tooltip consistent with other tooltips across the web app.
- Rename "Click to view edit history." to "View edit history", since the "Click to view" part is evident from the icon as well as the the keyboard shortcut hints.
Fixes: #26581
<details> …
=> tooltips: Add hotkey hints and modify edit history tooltip.

analytics/tests/test_activity_views.py, analytics/urls.py, analytics/views/activity_common.py, analytics/views/installation_activity.py, templates/analytics/activity_details_template.html, templates/analytics/realm_summary_table.html
Moves the "Remote Zulip servers" tab in the "/activity" page for an installation to a separate page, "/activity/remote".
Prototype for moving other tabs in "/activity" to separate pages.
**Notes**:
- Updates tests for new query counts. Not sure what other testing we might want to add.
- Adds linking to/from the main activity page and the remote servers activity page.
- Reorganizes the bulleted list in the main activity page slightly for clarity.
- Changed the link to the remote server's stats page to be only the pi chart icon; prep for having the hostname link to the remote server support page.
- Same manual testing procedure as outlined in #27033; copy/pasted below.
<details>
<summary>Manual testing procedure</summary>
- Set up test data in manage.py shell:
```
n = 20
from …
```
=> activity: Add separate page for remote server information/table.

web/src/scheduled_messages_ui.js
We remove redundant code when editing a scheduled message in the compose box, for resetting the compose box, as it anyway gets reset on calling `compose_actions.start()`.
Besides ending `scheduled_messages_ui.js`'s dependency on `compose.js` and `compose_ui.js`, this also fixes the bug where on editing a scheduled message when there was content in the compose box, it would be irretrievably lost. The old content is now drafted.
Fixes: [Issue described here](https://github.com/zulip/zulip/pull/26991#issuecomment-1745673474)
<details> …
=> compose: Remove redundant code from scheduled_messages_ui.js.

tools/test-js-with-node, web/src/settings_notifications.js, web/src/stream_edit.js, web/src/stream_popover.js, web/src/stream_settings_api.js, web/src/stream_settings_ui.js
(78, 35) → (77, 36). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1653379).
=> stream_edit: Move set_stream_property to new stream_settings_api module

puppet/zulip_ops/files/nginx/zulip-include-app.d/well-known.conf, puppet/zulip_ops/manifests/app_frontend.pp
Note this is only for `zulip_ops`, not for default installs.
<details>
</details>
=> puppet: Serve /etc/zulip/well-known/ in nginx as /.well-known/.

analytics/tests/test_support_views.py, analytics/urls.py, analytics/views/support.py, templates/analytics/remote_server_support.html, tools/linter_lib/custom_check.py
No automated tests yet.
I figured that if in the default view we want to be able to just browse remote servers, it should be displayed in a table:
And you can search by hostname or contact email in the top bar, similar to regular `/activity/support`.
How to test this:
- Set up test data in `manage.py shell`:
```
n = 20
from zilencer.models import RemoteZulipServer
import uuid
for i in range(0, 20):
hostname = f"zulip-{i}.example.com"
RemoteZulipServer.objects.create(hostname=hostname, contact_email=f"admin@{hostname}", plan_type=1, uuid=uuid.uuid4())
```
- Log in as `Iago` (this user has `.is_staff` enabled) and go to http://localhost:9991/activity/remote/support
=> support: Add basic support endpoint for remote servers.

zerver/middleware.py, zerver/openapi/openapi.py, zerver/tests/test_health.py, zerver/tests/test_integrations_dev_panel.py, zerver/tests/test_push_notifications.py, zerver/views/development/integrations.py
This is ordinarily emitted by Django at https://github.com/django/django/blob/4.2.6/django/core/handlers/exception.py#L139 and received by Sentry at https://github.com/getsentry/sentry-python/blob/1.31.0/sentry_sdk/integrations/django/__init__.py#L166.
=> middleware: Send got_request_exception signal for JSON 500 errors

web/third/bootstrap-typeahead/typeahead.js
From a bug reported here:
https://chat.zulip.org/#narrow/stream/9-issues/topic/Typeahead.20fails.20to.20automatically.20close/near/1655321
=> typeahead: Only return early from blur if parentElement is specified.

web/styles/portico/markdown.css
This PR restores the icons in the legend for the Stream permissions tables that disappeared somehow.
Fixes CZO issue: [missing help center icons](https://chat.zulip.org/#narrow/stream/9-issues/topic/missing.20help.20center.20icons).
- **Before:**
- **After:**
=> help: Fix missing icons in "Stream permissions".

web/src/portico/landing-page.js, web/styles/portico/landing_page.css
The content that this affected was removed in acd0c5568a96.
<details>
</details>
=> portico: Remove now-unnecessary twitter-tweet CSS and JS.

web/src/overlays.ts, web/src/popover_menus.js, web/src/user_profile.js
Since tippy popovers hide on click outside themselves, we don't
need call `popovers.hide_all` separately for them.
=> Remove popovers.hide_all calls after a click event.

web/src/rows.js
In #23900, the floating recipient bar was replaced with a sticky recipient bar. The logic in `id_for_recipient_row` was not updated for that change, so we update that function to just get the first message in the group and return that message ID.
---
<details>
</details>
=> recipient-row: Remove logic for floating recipient bar.

templates/zerver/register.html, web/styles/portico/portico_signin.css
This is just a temporary fix. We probably need redesign these pages for mobile widths.
=> Fix registration pages for small widths.

web/src/compose_actions.js
Up until now, we unconditionally saved any message content as a draft whenever the composebox was `start`ed. This led to a lot of unnecessary saving of drafts even when the composebox stayed undisturbed.
To fix this, now we only save the draft when the compose state is about to be overidden, which is by either changing the recipient narrow or by restoring another draft.
Fixes: #26976.
[can add a video by tomorrow]
<details> …
=> compose: Only save as draft when the compose state is about to change.

web/src/sent_messages.js
Commit 3cc2adcd3bd894f8ad8e42ea475d908594c07d54 (#25423) missed this in the rename, resulting in extra creation of no-op timers.
=> sent_messages: Finish .received → .saw_event rename

web/src/inbox_ui.js
There were 2 issues:
* Wrong format for creating new Map object used.
* Use of `topic_dict` instead of `topics_dict`, which resulted in `stream_key` being present in `topics_dict` even after stream has been marked as read. This made inbox believe that the stream was already rendered even though it was not.
=> inbox_ui: Fix unable to insert new stream.

tools/test-js-with-node, web/src/browser_history.ts, web/src/hashchange.js, web/src/narrow.js, web/src/reload_setup.js, web/tests/hashchange.test.js, web/tests/narrow_activate.test.js
(48, 15) → (46, 14), and reduces the cyclic component of 49 to three components of 33, 5, 2.
=> narrow: Cut import of hashchange

web/src/bundles/hello.ts
Since GA was only imported in portico bundle which we don't use in hello page due to bootstrap, GA was not loaded.
Checked network tab in dev tools to verify it being loaded. Not sure how to check if it is actually working.
=> hello: Fix google analytics not working.

web/src/compose_ui.js, web/src/composebox_typeahead.js, web/tests/compose_ui.test.js, web/tests/composebox_typeahead.test.js, web/third/bootstrap-typeahead/typeahead.js
This fixes the bug where on pressing enter after the last line in a textarea, the cursor would go to the new line but the textarea would not scroll it into view unless more was typed. This was observed on chromium browsers.
A new function `insert_and_scroll_into_view` is added to `compose_ui.js` which blurs and refocuses the textarea after inserting the content, then autosizes the textarea.
Fixes: [CZO thread of bug report and debugging](https://chat.zulip.org/#narrow/stream/9-issues/topic/scrollbar.20issue.20in.20compose.20box)
<details> …
=> compose: Ensure cursor is scrolled into view after content is inserted.

zerver/webhooks/zapier/doc.md
Current page: https://chat.zulip.org/integrations/doc/zapier
Updated:
[CZO discussion](https://chat.zulip.org/#narrow/stream/127-integrations/topic/DM.20Zap/near/1655505)
- I tried to put the tip just after step 12, but it reset the numbering, and I could figure out how to fix it. The current placement seems basically fine to me, but flagging it anyway.
=> integrations docs: Clarify instructions for direct messages from Zapier.

web/src/stream_topic_history.js, web/src/stream_topic_history_util.js, web/tests/stream_topic_history.test.js
This PR updates the `get_server_history` function to return early if a request is already in progress for a given stream_id, thus preventing concurrent requests for a single stream_id.
We maintain a set `request_pending_stream_ids`, which contains all the stream IDs for whom requests are in progress.
Using this set, we return early.
Fixes: #26915.
<details>
</details>
=> server_history: Prevent concurrent requests for the same stream_id.

web/src/upload.js, web/styles/compose.css, web/templates/compose_banner/message_sent_banner.hbs, web/templates/compose_banner/not_subscribed_warning.hbs, web/templates/compose_banner/private_stream_warning.hbs, web/templates/compose_banner/stream_does_not_exist_error.hbs, web/templates/compose_banner/unmute_topic_banner.hbs, web/templates/compose_banner/upload_banner.hbs, web/templates/compose_banner/wildcard_warning.hbs, web/tests/upload.test.js
This PR introduces a number of fixes to the compose banners. It:
1. Adds missing `.banner_content` classes to elements that needed it, including the upload banner, helping to make banner styles apply uniformly.
2. Adds a new `.banner_message` class to paragraph elements that are children of `.banner_content` elements, which makes it possible to remove Bootstrap-inherited styles without use of a `p` element selector.
3. Introduces an improved top-aligned style for action and cancel buttons, which give a more uniform, less jumbled look to the vertical alignment of banner elements.
4. Fixes the display of the upload progress banner when an upload fails by removing the progress banner in the error condition.
Fixes: #26922
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/un …
=> compose banners: Improve padding, layout, and behavior.

templates/zerver/accounts_home.html, web/styles/portico/portico_signin.css
I added "Already have an account? Login" to bottom of the register page.
This change makes it easier to move from the registration page to the login page.
=> register page:Add link for login page

web/src/settings_users.js
(29, 8) → (28, 7).
It’s effectively unused since commit 2d5c6786143e775712f43f8f78cddcb3b5aaeedb (#25061), as predicted by commit d45f0171cb8067dbcae2284ff2e72786613567bc (#14919).
=> settings_users: Remove get_status_field

tools/test-js-with-node, web/src/admin.js, web/src/settings_components.js, web/src/settings_display.js, web/src/settings_notifications.js, web/src/settings_org.js, web/src/settings_realm_user_settings_defaults.js, web/src/stream_edit.js, web/tests/settings_org.test.js
(27, 6) → (25, 5).
This resolves all cycles through `settings_org` except one: `settings_realm_user_settings_defaults.set_up` → `settings_org.register_save_discard_widget_handlers` → `settings_org.discard_property_element_changes` → `settings_org.update_dependent_subsettings` → `settings_realm_user_settings_defaults.realm_default_settings_panel`. That could be resolved in a few ways, such as by moving `set_up` or `realm_default_settings_panel`.
[Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/Splitting.20settings_org/near/1653389).
=> settings_org: Extract settings_components module

web/src/stream_settings_ui.js, web/src/stream_ui_updates.js
(17, 4) → (12, 3). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1659157).
(These moved items could also go to a new module instead of `stream_settings_ui`, but then we’d need to name it something.)
=> stream_ui_updates: Cut import of stream_settings_ui

web/styles/compose.css
This restoration also includes a comment for future contributors, explaining why these styles are necessary.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/upload.20banners.20issue/near/1659117)
=> compose_banner: Restore CSS overzealously removed in #27097.

corporate/lib/stripe.py
Upgrading stripe to 6.0.0 in e32366638aa1b7cfca0fa460a2b4f8e7fb90f331 breaks our Stripe integration due to API version change making us fail to finalize creating an invoice and charge the customer.
For the upstream details see:
https://github.com/stripe/stripe-python/blob/60ab6ac7d7fcfc5774c44490d3a581593ab6ad55/CHANGELOG.md#600---2023-08-16
6.0.0 uses 2023-08-16 Stripe API version unless specified otherwise. We want to use 2020-08-27.
Setting stripe.api_version in corporate/lib/stripe.py is sufficient for it to be set everywhere else. This is supported by the fact that we also only set stripe.api_key in that file.
=> Unbreak our Stripe integration

web/e2e-tests/stars.test.ts, web/src/click_handlers.js, web/src/list_util.ts, web/src/resize.js, web/styles/app_components.css, web/styles/dark_theme.css, web/styles/left_sidebar.css, web/styles/popovers.css, web/styles/zulip.css, web/templates/left_sidebar.hbs, web/templates/starred_messages_sidebar_actions.hbs, web/templates/topic_sidebar_actions.hbs
This PR provides needed prep work on the left sidebar ahead of the collapsed-views feature.
Specifically, the commits in this PR:
* Clean up some color inconsistencies, including CSS color variables
* Restructure the "filters" area of the left sidebar using `left-sidebar-navigation` class and ID references
* Place the new custom Zulip star icon in the left sidebar and star-related popovers on Starred messages and any topic containing starred messages
Apart from the new star icon, there are no visual changes introduced by this PR.
Fixes a small part of: #25902 
| Left-sidebar nav area, before | Left-sidebar nav area, after (star icon only difference) |
| --- | --- |
|  <img width="280" alt="lsb-prep-before" src="https://github.com/zulip/zulip/assets/170719/d5d7cfcc-a73c-476f-ad7b-f00d4f4f0f …
=> left sidebar: Collapsed views prep.

api_docs/changelog.md, version.py, web/tests/lib/events.js, zerver/actions/scheduled_messages.py, zerver/actions/typing.py, zerver/lib/event_schema.py, zerver/lib/recipient_parsing.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_recipient_parsing.py, zerver/tests/test_scheduled_messages.py, zerver/tests/test_typing.py, zerver/views/scheduled_messages.py, zerver/views/typing.py
[CZO discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/stream.20typing.20indicator/near/1649887)
> For https://zulip.com/api/get-events#typing-start, I think we should change the value "private" to "direct" --
> We could also remove the "private" compatibility support in [/api/set-typing-status](https://chat.zulip.org/api/set-typing-status) -- assuming we confirm that the mobile and terminal clients don't actually send the value "private"
---
<details><summary>set-typing-status</summary>
</img>
</details> 
<details><summary>get-events#typing-start</summary>
</img>
</details> 
---
<details> …
=> typing_indicator: Update APIs for stream typing notifications.

docs/subsystems/typing-indicators.md, web/shared/src/typing_status.js.flow, web/shared/src/typing_status.ts, web/src/narrow_state.js, web/src/typing.js, web/src/typing_data.ts, web/src/typing_events.js, web/tests/dispatch.test.js, web/tests/example8.test.js, web/tests/lib/events.js, web/tests/narrow_state.test.js, web/tests/typing_data.test.js, web/tests/typing_events.test.js, web/tests/typing_status.test.js, zerver/lib/home.py
Rebased #17040 and minor changes.
[typing.webm](https://github.com/zulip/zulip/assets/56781761/b6e4867a-0ac1-4ff6-951b-b066961389aa)
<details>
</details>
=> typing_indicators: Add typing indicators for streams.

web/e2e-tests/drafts.test.ts, web/e2e-tests/message-basics.test.ts, web/src/compose_actions.js, web/src/compose_closed_ui.js, web/src/compose_popovers.js, web/src/compose_recipient.js, web/src/compose_setup.js, web/src/compose_tooltips.js, web/src/compose_ui.js, web/src/hotspots.js, web/src/narrow.js, web/src/recent_view_ui.js, web/styles/compose.css, web/styles/dark_theme.css, web/styles/zulip.css, web/templates/compose.hbs, web/templates/popovers/mobile_message_buttons_popover.hbs, web/tests/compose.test.js, web/tests/compose_actions.test.js, web/tests/compose_closed_ui.test.js, web/tests/compose_ui.test.js, web/tests/narrow_activate.test.js, web/tests/recent_view.test.js
This PR is a rewrite of what was previously known as the "New topic" button.
Some relentless QA is needed here, especially as concerns the tooltips and actions triggered by the "Start new conversation" button when moving from narrow to narrows, or from a narrow to an unnarrowed view.
Fixes: #24889
TODOs:
Tooltip and button in Recent converesations view:
Tooltip and button in an interleaved stream view:
After clicking the Start new conversation button in an interleaved stream view; tooltip on the clear-topic-box button (X):
<details> …
=> compose: Add contextually-aware "Start new conversation" button

help/printing-messages.md
Current page: https://zulip.com/help/printing-messages
Revised:
=> help: Tighten content on /help/printing-messages.

zerver/management/commands/backup.py
`/usr/bin/pg_dump` on Ubuntu and Debian is actually a tool which
attempts to choose which `pg_dump` binary from all of the
`postgresql-client-*` packages that are installed to run.  However,
its logic is confused by passing empty `--host` and `--port` options
-- instead of looking at the running server instance on the server, it
instead assumes some remote host and chooses the highest versioned
`pg_dump` which is installed.
Because Zulip writes binary database backups, they are sensitive to
the version of the client `pg_dump` binary is used -- and the output
may not be backwards compatible.  Using a PostgreSQL 16 `pg_dump`
writes archive format 1.15, which cannot be read by a PostgreSQL 15
`pg_restore`.
Zulip does not currently support PostgreSQL 16 as a server.  This
means that backups …
=> Fix PostgreSQL backups when postgresql-client-16 is installed

zerver/tests/test_signup.py, zerver/views/registration.py
Two registration requests for the same email address can race, leading to an IntegrityError when making the second user.
Catch this and redirect them to the login page for their existing email.
<details>
</details>
=> registration: Handle race conditions with duplicate emails.

web/src/resize.js, web/src/stream_settings_ui.js, web/styles/subscriptions.css, web/styles/zulip.css
Fixes #26823
Fixes user card not displayed on last item in the subscribers list. This was happening because there wan not enough space below the user name for the popover to be displayed (as far as I understand this).
Regardless of the fix above, this seems like a nice change.
=> stream_settings_ui: Avoid two scrollbars.

zerver/worker/queue_processors.py
This commit changes the url of the notification message to point to settings/data exports instructing the user to follow the link to download the exported data.
Fixes:#26923
<details>
</details>
=> queue_processors: Link to SETTINGS/DATA EXPORTS from data export completion notification

zerver/tests/test_event_queue.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/Flaky.20backend.20test/near/1658021)
Fixes the [flaky backend test failures](https://github.com/zulip/zulip/actions/runs/6442021073/job/17492406447?pr=27110#step:19:4628) we noticed recently.
<details>
</details>
=> test_event_queue: Add missing "super call" in 'MissedMessageHookTest'.

api_docs/changelog.md, web/src/typing.js, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_typing.py, zerver/views/typing.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/stream.20typing.20indicator/near/1659961)
This PR adds a `stream_id` parameter to the `POST /typing` endpoint.
Now, `to` is used only for "direct" type. In the case of "stream" type, `stream_id` and `topic` are used.
---
<details><summary>Changelog</summary>
</img>
</details> 
<details><summary>/api/set-typing-status</summary>
</img>
</details> 
---
<details>
</details>
=> typing_indicator: Add a 'stream_id' parameter to 'POST /typing'.

puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf, web/src/lightbox.js
If the video was playing, it didn't stop playing even after the lightbox was closed. We could pause it but removing it from DOM seems like the better thing to do.
A video for testing it.
https://github.com/zulip/zulip/assets/25124304/3ac52c5b-cd23-4840-99fe-e5eb5e6fe3cf
discussion: https://chat.zulip.org/#narrow/stream/137-feedback/topic/Inline.20video.20preview
=> lightbox: Fix video playing in background after closing.

corporate/views/portico.py, templates/corporate/communities.html, web/src/portico/communities.ts, web/styles/portico/integrations.css, zerver/tests/test_docs.py
Org category filters were hidden in
https://github.com/zulip/zulip/commit/60eb408bb069e7990e7e16cadedf69b723c2b66c.
**First commit is to help with testing. Should be dropped before merging this.**
=> communities: Allow user to filter orgs by type.
