zulip/zulip

scripts/lib/install
scripts/lib/upgrade-zulip-stage-2

This ensures that the next `upgrade-zulip-from-git` has access to the
commit history of the initial install, if it was from a forked
repository.  `/home/zulip/deployments/current` and `/srv/zulip.git`
are not quite organized into the steady-state that they will have
after one `upgrade-zulip-from-git`:
- `/home/zulip/deployments/current` is its own clone, not a worktree
- `/srv/zulip.git` has an origin of `/home/zulip/deployments/current`
- `remote.origin.mirror` is set on `/srv/zulip.git`
- `remote.origin.fetch` is `+refs/*:refs/*`
All but the first are automatically cleaned up by
`upgrade-zulip-from-git` when it is next run, using the code added in
30457ecd02b5.  The additional complexity of making an existing
independent clone into a worktree seem not worth solving the first
point. …

install: Use the initially-cloned repo as the base /srv/zulip.git.

---

web/src/popovers.js

This was missed in #26005. The user popover button does not appear for bot users. We complete the TODO here and simplify the calculation for show_manage_menu so that we always show it if not in spectator view and not showing the popover for self.
Previously, the option for muting bot users was only visible to admins.
<details>
</details>

mute users: Remove leftover check for muting bot users.

---

docs/translating/spanish.md

- Updates instances of "private message" and "PM", improving wording and translating to Spanish where needed.
- https://zulip.readthedocs.io/en/stable/translating/spanish.html#terminos
<details>
</details>

docs: Rename private message -> direct message in Spanish style guide.

---

docs/development/setup-recommended.md

Previously, there was a missing space in setup-recommended.md that I noticed when reading it. It made me double take and need to reread the sentence. Fixing the space improves potential understanding of the doc and ensures professionalism.
Fixes: Missing space in setup-recommended.md
<details>
</details>

docs: Fix missing space in setup-recommended.md

---

docs/contributing/reporting-bugs.md
docs/contributing/suggesting-features.md

This PR improves the new [bug-reporting]() and [feature-suggestion]() docs. For easier review, I've split it into two commits: the first is (hopefully) non-controversial wording and mechanical fixes. The second has a bit more of a heavy editorial hand to clean up some phrasing.
I've tried to ensure parallel changes on parallel parts of these documents, but would appreciate a review that confirms that :)
Changes are minor and document-wide, so I'm opting to share links to live and built docs in lieu of screenshots:
* Reporting bugs: [current](https://zulip.readthedocs.io/en/latest/contributing/reporting-bugs.html), [updated](https://zulip--26045.org.readthedocs.build/en/26045/contributing/reporting-bugs.html)
* Suggesting features and improvements: …

docs: Make updates to new bug-reporting and feature docs.

---

zerver/webhooks/stripe/fixtures/customer_subscription_created_no_nickname.json
zerver/webhooks/stripe/tests.py
zerver/webhooks/stripe/view.py

stripe: Nicknames are optional on plans.

---

zerver/lib/queue.py
zerver/tests/test_queue_worker.py
zerver/worker/queue_processors.py

For tests that use the dev server, like `test-api`, `test-js-with-puppeteer`, we don't have the consumers for the queues. As they eventually timeout, we get unnecessary error messages. This adds a new flag, disable_timeout, to disable this behavior for the test cases.
We can further verify the fix by comparing `test-js-with-puppeteer`'s output with that from a previous run [here](https://github.com/zulip/zulip/actions/runs/5381781411/jobs/9766300546). No `ERROR` level log messages should be generated now.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipl …

queue_processors: Avoid queue worker timeouts in tests.

---

zerver/lib/alert_words.py
zerver/lib/cache.py
zerver/lib/import_realm.py
zerver/lib/types.py
zerver/models.py
zerver/tests/test_upload.py
zerver/tests/test_user_groups.py
zerver/views/streams.py

User groups prep commits

---

web/styles/subscriptions.css
web/styles/zulip.css

Simplebar seems unaware of the `max-height: 1000px` on `.subscriptions-container`, and therefore does not properly provide a scrollbar when it's needed.
This commit adds a `max-height` to the stream Simplebar container, ensuring that otherwise hidden content that Simplebar believes to be visible can be scrolled to.
Fixes #26107.
Before:
After:
<details>
</details>

stream_settings: Fix scroll at max-height.

---

templates/zerver/accounts_send_confirm.html
web/styles/portico/portico_signin.css
zerver/tests/test_invite.py
zerver/tests/test_management_commands.py
zerver/tests/test_signup.py

This PR updates the text on email confirmation page to make it more clear what's going on
and why the user needs to check their email.
Fixes:  #25900
<details>
</details>

templates: Improve email confirmation page.

---

web/tests/compose_pm_pill.test.js

While running test for `compose_pm_pill` we get warning that `compose_recipient` is mocked but never used. This bug was introduced in #26052.

compose_pm_pill: Fix `compose_recipient` being mocked but not used.

---

web/styles/portico/portico.css

The CSS for modals uses "--color-background-color" to set background color of modal. But the variable is defined in zulip.css which is not available for portico pages and thus the email visibility modal was not rendering as expected in "Terms of service" page.
This PR defines the "--color-background-color" variable in portico.css such that it is available for portico pages as well.
Before
After
<details> …

portico: Define variable for modal background color.

---

zerver/lib/upload/base.py
zerver/tests/test_upload.py

upload: Provide a default upload file name, rather than 500.

---

web/templates/unread_banner/mark_as_read_turned_off_banner.hbs

Previously, some unread banners were warning banners, but it made more sense for all the unread banners to match and display as more of an info/notice banners instead. This change matches all unread banners to be info/notice banners.
<details>
</details>

unread_banner: Update all unread banners to an info/notice banner.

---

web/src/alert_words_ui.js
web/src/dialog_widget.ts
web/src/settings_account.js
web/src/settings_bots.js
web/src/settings_emoji.js
web/src/settings_user_groups_legacy.js
web/src/stream_edit.js
web/src/user_group_edit.js

We should prevent the default html behavior when submitting the forms in the dialog_widgets to avoid reloading the whole page when the user clicks the submit button.
Fixes: #26104
https://github.com/zulip/zulip/assets/84276404/9af91f6b-66d9-4d85-bc1b-dc5da8e99581
https://github.com/zulip/zulip/assets/84276404/84e965d0-a4ce-4d9b-b245-8f2ed187fea8
<details>
</details>

dialog_widget: Prevent default action when submitting the form.

---

docs/production/export-and-import.md

This extends 8ede54fb1b7c, in the specific backups section, rather than just in the overview.
<details>
</details>

docs: Reference PostgreSQL version in "Restoring backups" section.

---

zerver/tests/test_upload.py
zerver/views/upload.py

Changed the message from “File not found.” to “This file does not exist or has been deleted.” for improving deleted file experience
Fixes part of https://github.com/zulip/zulip/issues/23739
Overview of the Chat under consideration with an image that has been deleted from the uploaded files menu in Personal Settings.
Before Message:
After Message:
<details>
</details>

uploads: Improve file not found message.

---

web/tests/popovers.test.js

While running test for `popovers.js` we get warning that `giphy` is mocked but never used.
This bug was introduced in #25676.
<details>
</details>

popovers: Fix giphy being mocked  but not used.

---

tools/test-backend
zerver/lib/test_classes.py

By relocating helper methods into a mixin class, we can be more flexible with managing transactions in test cases, without always forcing the `django.test.TestCase` behavior of always putting the test case into an atomic transaction.
This helps us with testing database transactions specifically in the cases of locking and race conditions.
<details>
</details>

test_classes: Do not necessary wrap test cases in a transaction.

---

docs/overview/changelog.md
tools/release

release: Make GitHub release notes just point to ReadTheDocs.

---

web/e2e-tests/admin.test.ts
web/src/dropdown_list_widget.js
web/src/settings_profile_fields.js
web/src/settings_streams.js
web/src/stream_data.js
web/styles/settings.css
web/templates/settings/add_default_streams.hbs
web/templates/settings/default_stream_choice.hbs
web/templates/settings/default_streams_list_admin.hbs
web/tests/stream_data.test.js

default_streams: Convert inline form to modal.

---

web/src/people.js
web/src/pill_typeahead.js
web/src/settings_account.js
web/src/settings_bots.js
web/src/settings_users.js
web/src/user_pill.js
web/tests/people.test.js

Fixes: [#25092](https://github.com/zulip/zulip/issues/25092)
Captures from the web DEV environment, bots get filtered out
- Mentor field in Personal settings
- Mentor field in Manage user modal
**checklist**
<details>
</details>

typeahead: Remove bots in person picker custom profile fields.

---

zerver/lib/markdown/__init__.py
zerver/tests/test_markdown.py

markdown: Only attempt to adjust /wiki/File: paths on Wikipedia.

---

zerver/lib/markdown/__init__.py
zerver/tests/test_markdown.py

Updates `find_proper_insertion_index` to check for the inline image classes as substrings in the element's `attrib["class"]` so that cases where an inline preview image has multiple classes, like YouTube video previews, will have the correct insertion index.
Fixes #26186.
<details>
<summary>Current main</summary>
</details>
<details>
<summary>After changes</summary>
</details>
---
<details>
</details>

markdown-processor: Check for inline image classes as substrings.

---

zerver/webhooks/sentry/doc.md

Updates the documentation for the Sentry integration to:
- Emphasize the note about the alternative set-up via Sentry webhooks.
- Breaks the text in step 3 into two paragraphs.
- Updates steps 3 and 4 instructions to have better flow and use commas more effectively.
*Note there are no changes to the introduction text or steps 1 & 2.*
[Current documentation](https://zulip.com/integrations/doc/sentry)
<details> …

sentry-webhook: Revise documentation page to be clearer.

---

docs/production/upgrade.md

Users can, quite understandably, assume that upgrading Zulip upgraded the underlying PostgreSQL version.  Though it is mentioned at the top of the page, mentioning it here clarifies that it is an additional step.
<details>
</details>

docs: Mention the PostgreSQL upgrade in the release upgrade section.

---

zerver/tests/test_scheduled_messages.py

Fixes: https://github.com/zulip/zulip/issues/25497
<details>
</details>

tests: Use time_machine for testing scheduled message delivery.

---

web/src/info_overlay.js

The CSS class `spacer` was required or else there was very little spacing between the input elements in the `/poll` widget. 
<table>
<thead>
<tr>
<th colspan="2">Use of <q>spacer</q> class</th>
</tr>
<tr>
<th>Header</th>
</tr>
</thead>
<tbody>
<tr>
<td><img src="https://github.com/zulip/zulip/assets/35286603/9db7d74e-86b2-49f9-bfd5-46ee157ff1aa" alt="image"></td>
<td><img src="https://github.com/zulip/zulip/assets/35286603/d840cdc0-fdab-4f4f-af2f-16febaeb01c2" alt="image"></td>
</tr>
</tbody>
</table>
Fixes: #25780
<details>
| ![Screenshot from 2023-05-27 16-01-50](https://github.com/sbansal1999/zulip/assets/35286603/efd98a53-4fec-47b9-8e81-c1b1aa5ff855) | ![Screenshot from 2023-05-27 …

message_formatting: Improve the message formatting tips table.

---

zerver/actions/create_user.py

(instead of a week)
There are still caps like 1000 messages total and 20 unread, but we're a bit more flexible about time.

onboarding: Backfill a month of messages for new users.

---

web/src/markdown.js
web/styles/rendered_markdown.css
web/tests/markdown.test.js
zerver/actions/message_edit.py
zerver/actions/message_send.py
zerver/lib/markdown/__init__.py
zerver/lib/mention.py
zerver/lib/stream_subscription.py
zerver/lib/topic.py
zerver/tests/test_email_notifications.py
zerver/tests/test_markdown.py
zerver/tests/test_push_notifications.py
zerver/tests/test_soft_deactivation.py
zerver/tests/test_users.py

[#25828 (comment)](https://github.com/zulip/zulip/pull/25828#pullrequestreview-1514442343)
> I think the group of first 6 commits would be a good prefix to split into a new PR so that it can be merged off. The notifications commit is pretty large and would be easier to review independently :)

mention: Fetch users to be notified of @topic mentions.

---

zerver/actions/create_user.py

This is just as clear in terms of intent, and it's robust to us tweaking the number of weeks.

onboarding: Rename variable to cutoff_date.

---

scripts/setup/apt-repos/teleport/focal.list
scripts/setup/apt-repos/teleport/jammy.list

puppet: Upgrade Teleport to the 13.x series.

---

puppet/zulip/files/logrotate/smokescreen
puppet/zulip/manifests/smokescreen.pp
puppet/zulip/templates/supervisor/smokescreen.conf.erb
puppet/zulip_ops/manifests/profile/smokescreen.pp

Smokescreen logs and metrics

---

zerver/lib/email_notifications.py
zerver/tests/test_email_notifications.py
zerver/worker/queue_processors.py

Lock missedmessage rows, other cleanup

---

scripts/log-search

See https://docs.python.org/3/library/signal.html#note-on-sigpipe
<details>
</details>

log-search: Prevent BrokenPipeError exceptions when run with `head`.

---

web/styles/message_row.css

This satisfies the linter's desire for the `grid-template` shorthand while keeping the illustrative template areas in their own little diagram-like property.
A follow-up PR should document this style, since it is not enforced by the linter beyond its disallowing of all three longhand properties (`grid-template-rows`, `grid-template-columns`, and `grid-template-areas`) in the same declaration block.
This introduces no visual differences; the Before and After screen captures are identical.
| --- | --- |
| ![message-row-before](https://github.com/zulip/zulip/assets/170719/a62a9611-a591-4c2d-b3e6-25e9d51ee604) | ![message-row-after](https://github.com/zulip/zulip/assets/170719/9f240eb9-4a86-4921-bbdc-4514ad89cc1d) |
<details> …

message_grid: Refactor row grid for readability.

---

web/styles/message_row.css
web/styles/zulip.css

Beyond centering the first/only line of text in a me-message, this commit also demonstrates how precise line-heights contribute to a design: by matching the line-height on the avatar's grid area to the dimensions of the square avatar image, it's possible to center the first line of text (me-messages, in this case) with a non-text element.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/me-message.20layout/near/1609547)
| --- | --- |
| ![me-message-before](https://github.com/zulip/zulip/assets/170719/8c77a91e-67f0-47a8-adbb-84fefc86ff92) | ![me-message-after](https://github.com/zulip/zulip/assets/170719/ee95633f-53b9-499c-b856-930ea285598e) |
<details> …

me_message: Center first line with center of avatar.

---

zerver/actions/message_edit.py

Fundamentally, we should take a write lock on the message, check its validity for a change, and then make and commit that change. Previously, `check_update_message` did not operate in a transaction, but `do_update_message` did -- which led to the ordering:
- `check_update_message` reads Message, not in a transaction
- `check_update_message` verifies properties of the Message
- `do_update_message` starts a transaction
- `do_update_message` takes a read lock on UserMessage
- `do_update_message` writes on UserMessage
- `do_update_message` writes Message
- `do_update_message` commits
This leads to race conditions, where the `check_update_message` may have verified based on stale data, and `do_update_message` may improperly overwrite it; as well as deadlocks, where other (properly-written) …

message_edit: Lock the Message row in check_update_message.

---

tools/test-js-with-node
web/src/alert_words_ui.js
web/src/attachments_ui.js
web/src/dropdown_list_widget.js
web/src/dropdown_widget.js
web/src/list_widget.js
web/src/list_widget.ts
web/src/recent_topics_ui.js
web/src/settings_emoji.js
web/src/settings_exports.js
web/src/settings_invites.js
web/src/settings_linkifiers.js
web/src/settings_muted_users.js
web/src/settings_playgrounds.js
web/src/settings_streams.js
web/src/settings_user_topics.js
web/src/settings_users.js
web/src/stream_create_subscribers.js
web/src/stream_edit_subscribers.js
web/src/user_group_create_members.js
web/src/user_group_edit_members.js
web/src/user_groups_settings_ui.js
web/src/user_profile.js
web/tests/alert_words_ui.test.js
web/tests/list_widget.test.js
web/tests/recent_topics.test.js
web/tests/settings_muted_users.test.js
web/tests/settings_user_topics.test.js

Migrates the `list_widget` to TypeScript.
<details>
</details>

ts: Migrate `list_widget` to TypeScript.

---

tools/test-js-with-node
web/src/drafts.js
web/src/hotkey.js
web/src/messages_overlay_ui.js
web/src/messages_overlay_ui.ts
web/src/scheduled_messages_overlay_ui.js

Migrates `message_overlay_ui` module to TypeScript.
<details>
</details>

ts: Migrate `message_overlay_ui` to TypeScript.

---

web/src/compose.js
web/src/compose_recipient.js
web/src/compose_state.js
web/src/compose_validate.js
web/src/stream_data.js
web/tests/compose_validate.test.js

There should be no functional changes of this PR.
This partially fixes #25742.

use stream_id instead of stream_name

---

zerver/lib/export.py
zerver/lib/import_realm.py

Fix exports and imports with deleted users and huddles

---

help/include/sidebar_index.md
help/schedule-a-message.md
help/view-and-edit-your-message-drafts.md
zerver/lib/markdown/help_relative_links.py

This PR addresses the follow-ups noted in #25450.
- Adds support for relative links to `/#drafts` and `/#scheduled` for logged-in users.
- Revises "Schedule a message" help center page, adding `{relative|scheduled}`, keyboard tips, and related articles.
- Updates "Message drafts" to follow current help center documentation patterns (tweaks intro, splits instructions into multiple sections, adds `{relative|drafts}`, keyboard tips, and related articles).
<details>
<summary>Scheduled a message</summary>
- **Current docs: https://zulip.com/help/schedule-a-message**
</details>
<details>
<summary>Draft messages</summary>
- **Current docs: https://zulip.com/help/view-and-edit-your-message-drafts**
</details>
<details> …

help: Offer links to "Drafts" and "Scheduled messages" for logged in users.

---

puppet/zulip_ops/manifests/profile/chat_zulip_org.pp

puppet: Allow access to smokescreen metrics on CZO.

---

api_docs/changelog.md
zerver/openapi/zulip.yaml

Adds an entry to the API changelog for feature level 193. The changes documented here are from commit 3802503a8a8.
Follow-up to #26287.
<details>
<summary>API changelog entry for feature level 193</summary>
</details>
<details>
<summary>Add reaction - error response documentation</summary>
</details>
<details>
<summary>Delete reaction - error response documentation</summary>
</details>
---
<details>
</details>

api-changelog: Add entry for feature level 193 updates.

---

web/src/hotkey.js
web/src/narrow.js

Adds including a trigger to the opts for `narrow_to_next_topic` and `narrow_to_next_pm_string` when called from `web/src/hotkey.js`.
See [relevant CZO conversation](https://chat.zulip.org/#narrow/stream/6-frontend/topic/narrowed.20trigger.20unknown/near/1580832).
<details>
<summary>Firefox devtools console - before changes</summary>
</details>
<details>
<summary>Firefox devtools console - after changes</summary>
</details>
---
<details> …

narrow: Add hotkey trigger for navigation to new topic/direct message.

---

web/styles/compose.css
web/styles/left_sidebar.css
web/styles/portico/activity.css
web/styles/portico/landing_page.css
web/styles/portico/markdown.css
web/styles/rendered_markdown.css
web/styles/right_sidebar.css
web/styles/subscriptions.css
web/third/bootstrap/css/bootstrap-btn.css
web/third/bootstrap/css/bootstrap.css

- First commit removes bootstrap CSS rules for some unused classes in `bootstrap-btn.css`.
- Second commit removes bootstrap CSS rules for `.input-append` elements.
- Third commit removes bootstrap CSS rules for `small` elements.
- Fourth commit removes bootstrap CSS rules for `.label` elements.
- Fifth commit removes some unnecessary CSS for `blockquote` elements from `landing_page.css`.
- Remaining commits are to re-add bootstrap CSS rules for `blockquote` elements using more specific selectors and to remove the CSS from `bootstrap.css`.
<details> …

Remove bootstrap CSS for different elements like `blockquote`, `small`, `.input-append`, etc.

---

web/src/huddle_data.ts

Added type annotations.
Fixes: 
<details>
</details>

ts: Migrate `huddle_data.js` to TypeScript.

---

zerver/worker/queue_processors.py

An exception which escapes from this loop can kill the background worker thread; this results in consuming the queue (leading to the illusion of progress) but more and more rows silently piling up in the ScheduledMessageNotificationEmail table.
Wrap the inside of the `while True` loop in a try/catch to make sure that no exceptions escape and kill the background thread.  To prevent even more indentation, the inner loop is extracted into its own function.  It returns true/false to signal if the `self.stopping` was set to tell the loop to stop; we cannot check it ourselves in the outer loop because it needs to hold the lock to be examined.
<details> …

missed-message: Add a try-catch to prevent killing background thread.

---

templates/zerver/change_email_address_visibility_modal.html
web/e2e-tests/realm-linkifier.test.ts
web/e2e-tests/settings.test.ts
web/src/dialog_widget.ts
web/src/invite.js
web/src/stream_edit.js
web/styles/dark_theme.css
web/styles/modal.css
web/templates/dialog_widget.hbs

This PR changes the button text from "Cancel" to "Close", since it is weird to click on "Cancel" button after having copied the email address and might confuse users. Using "Close" makes it clear that the button is to just close the modal.
Fixes:  https://github.com/zulip/zulip/pull/26206#issuecomment-1648555158
<details>
</details>

stream: Change button text to "Close" in copy email address modal.

---

api_docs/changelog.md
version.py
web/src/settings_org.js
web/src/stream_create.js
web/src/stream_data.js
web/src/stream_edit.js
web/src/stream_events.js
web/src/stream_settings_ui.js
web/src/user_groups.ts
web/templates/stream_settings/stream_creation_form.hbs
web/templates/stream_settings/stream_settings.hbs
web/tests/composebox_typeahead.test.js
web/tests/lib/events.js
web/tests/stream_data.test.js
web/tests/stream_events.test.js
web/tests/stream_settings_ui.test.js
web/tests/user_groups.test.js
zerver/actions/streams.py
zerver/actions/user_groups.py
zerver/lib/event_schema.py
zerver/lib/subscription_info.py
zerver/lib/types.py
zerver/lib/user_groups.py
zerver/models.py
zerver/openapi/zulip.yaml
zerver/tests/test_events.py
zerver/tests/test_subs.py
zerver/tests/test_user_groups.py
zerver/views/streams.py
zerver/views/user_groups.py

This PR renames the API fields `can_remove_subscribers_group_id` and `can_mention_group_id` to `can_remove_subscribers_group` and `can_mention_group`. 
Related Discussion: https://chat.zulip.org/#narrow/stream/378-api-design/topic/single.20user.20groups/near/1607964
<details>
</details>

api: Rename API fields related to stream and group level group settings.

---

web/src/alert_words.ts

Added type annotations for function params, return values and local variables.
Fixes: 
<details>
</details>

ts: Migrate `alert_words.js` to TypeScript.

---

web/src/stream_data.js
web/tests/lib/zjquery_element.js

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield*)

stream_data: Use `yield*`

---

puppet/zulip_ops/files/process_exporter.yaml
puppet/zulip_ops/files/tornado_process_exporter.yaml
puppet/zulip_ops/manifests/prometheus/process.pp
puppet/zulip_ops/templates/supervisor/conf.d/prometheus_process_exporter.conf.template.erb

Exporting stats about all of the various Zulip processes is useful for tracking memory leaks, etc.
<details>
</details>

puppet: Rename and generalize Tornado process exporter.

---

zerver/views/user_groups.py

Earlier while changing group level group based settings there was no check if the new value for setting is same as the current value.
This PR adds this check now a setting value will be only changed when it is not equal to present value.
This PR is a followup work for changes in #26243.
<details>
</details>

user_groups: Update code for changing group level settings.

---

web/src/settings.js
web/src/settings_display.js
web/src/settings_org.js
web/templates/settings/display_settings.hbs
web/templates/settings/language_selection_widget.hbs

- First commit fixes the bug for "Automated messages and emails" section.
- Second commit fixes the bug for case when default code block language is disabled.
Before - 
After -
<details>
</details>

Fix bugs with save-discard widget not hiding on resetting the setting to original value.

---

templates/analytics/ad_hoc_query.html
web/src/settings_profile_fields.js
web/styles/app_components.css
web/styles/dark_theme.css
web/styles/popovers.css
web/styles/portico/activity.css
web/styles/portico/portico.css
web/styles/recent_topics.css
web/styles/rendered_markdown.css
web/styles/settings.css
web/templates/settings/profile_field_settings_admin.hbs
web/third/bootstrap/css/bootstrap.css

- First three commits are to remove unnecessary table related CSS from `bootstrap.css`.
- Next two commits are to re-add bootstrap CSS rules defined using `table-bordered` class.
- Next commit is to fix border for heading in tables of informational overlay.
- Next commit is to remove bootstrap CSS for `.table-bordered` from `bootstrap.css`.
- Next three commits are to re-add the bootstrap CSS for `.table-striped`, `.table-condensed` and `<table>` elements and also remove them from `bootstrap.css`.
- Next two commits are to re-add bootstrap CSS defined using `.table` selector and remove them from `bootstrap.css`.
- Last commit is to make the custom profile field table similar to other tables in settings.
<details> …

Remove table related bootstrap CSS and update the custom profile fields table.

---

zerver/tests/test_event_queue.py

Follow-up : [#25640 (comment)](https://github.com/zulip/zulip/pull/25640#issuecomment-1590251661)
> https://github.com/zulip/zulip/pull/25640#discussion_r1228823795 might be worth a follow-up to make it easier to see why those tests are correct.
[#25640 (comment)](https://github.com/zulip/zulip/pull/25640/commits/18e1d42f81f50f12d678ad8b5539b924b9c9d564#r1228823795)
> It would also be good to explicitly set `enable_followed_topic_email_notifications` to True at the start of the first test.
<details> …

test_event_queue: Set the notification settings explicitly.

---

pyproject.toml
tools/webpack
zerver/lib/request.py
zerver/lib/upload/local.py
zerver/lib/upload/s3.py
zerver/migrations/0149_realm_emoji_drop_unique_constraint.py
zerver/tests/test_invite.py
zerver/tests/test_message_fetch.py

https://beta.ruff.rs/docs/rules/static-join-to-f-string/

ruff: Fix FLY002 Consider f"…" instead of string join

---

api_docs/changelog.md

changelog: Fix incorrect documentation link.

---

docs/subsystems/caching.md
zerver/lib/cache_helpers.py
zerver/lib/drafts.py
zerver/lib/email_mirror.py
zerver/lib/export.py
zerver/lib/message.py
zerver/lib/narrow.py
zerver/lib/recipient_users.py
zerver/lib/topic.py
zerver/models.py
zerver/openapi/curl_param_value_generators.py
zerver/tests/test_email_mirror.py
zerver/tests/test_message_edit.py
zerver/tests/test_message_flags.py
zerver/tests/test_message_send.py

- First commit is to fix `get_user` function in documentation.
- Next commit is to pass arguments to `select_related` call for `Huddle` objects.
- Next two commits are to access `recpient_id` instead of `recipient` object.
- Next commit is to pass arguments to `select_related` call in `get_stream_by_id_in_realm`.
- Next commit is to pass arguments to `select_related` call for `MissedMessageEmailAddress` objects.
- Next commit is to pass arguments to `select_related` call for `Subscription` objects.
- Last four commits are to pass arguments to `select_related` call for `Message` objects including the ones used in tests.
<details>
Individual …

Pass required arguments to `select_related`.

---

docs/production/index.md
docs/production/multiple-organizations.md

Adds the existing article about **Hosting multiple organizations** to the production section of the RTD table of contents.
See [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/19-documentation/topic/Production.20documentation.20for.20hosting.20multiple.20organizations/near/1621245).
**Notes**:
- Instead of screenshots, one can look at the [RTD build for this pull request](https://zulip--26467.org.readthedocs.build/en/26467/) to see the updated table of contents (*though the index page hasn't been updated in that build*).
---
<details> …

docs: Add `multiple-organizations.md` to production section of RTD table of contents.

---

zerver/webhooks/bitbucket3/doc.md
zerver/webhooks/deskdotcom/doc.md
zerver/webhooks/helloworld/doc.md
zerver/webhooks/homeassistant/doc.md
zerver/webhooks/json/doc.md
zerver/webhooks/lidarr/doc.md
zerver/webhooks/netlify/doc.md
zerver/webhooks/pingdom/doc.md
zerver/webhooks/radarr/doc.md
zerver/webhooks/rundeck/doc.md
zerver/webhooks/sentry/doc.md
zerver/webhooks/sonarr/doc.md
zerver/webhooks/trello/doc.md
zerver/webhooks/zendesk/doc.md

This is a prep PR for #26201.
It just makes sure that the spacing and numbering in the list are consistent for each integration documentation. So that it can help in future refactoring of the documentation.
<details>
</details>

Make integration documentation consistent with each other.

---

zerver/tests/test_openapi.py

Previoulsy, `test_openapi_arguments` had assumed that an endpoint not using `rest_dispatch` used the GET method for the request. This was not the case for the `"/fetch_api_key"` and `"/dev_fetch_api_key"` endpoints, which is why those endpoints were marked as pending even though they were documented in `zerver/openapi/zulip.yaml`.
Updates `test_openapi_arguments` to check a set of endpoints that are documented, don't use `rest_dispatch`, and don't use the GET method so that these endpoints can be tested and removed from the `pending_endpoints` set.
**Notes**:
- The `"/dev_fetch_api_key"` entry in `pending_endpoints` had a note about a "tracking bug", which dates back to when the entry was updated in commit cfe3ba31f5ee509bfbea023642dc1678ebaea500. I couldn't find a particular issue about …

test-openapi: Add coverage for documented fetch API key endpoints.

---

zerver/actions/uploads.py

This improves clarity of the comment.
Fixes: 
<details>
</details>

uploads: Fix double negation in do_claim_attachments comment.

---

tools/test-js-with-node
web/src/settings_ui.ts

ts: Migrate `settings_ui.js` to TypeScript.

---

web/src/page_params.ts
web/src/presence.ts

Migrates `presence.js` module to TypeScript.
<details>
</details>

ts: Migrate `presence.js` module to typescript.

---

web/src/compose.js
web/src/message_edit.js
web/src/ui_init.js
web/src/upload.js
web/tests/upload.test.js

Rebases #15735 
Fixes: #14579.
<details>
</details>

upload: Support drag and dropping files anywhere on message viewport.

---

package.json
pnpm-lock.yaml
tools/test-js-with-node
version.py
web/src/plotly.js.d.ts
web/src/stats/page_params.ts
web/src/stats/stats.js
web/src/stats/stats.ts

This PR focuses on migrating `stats.js` to `stats.ts`. Commits done earlier are prep commits such as refactoring the code structure a bit, fixing the wrong code, and installing type packages.
In migration, I created custom types for type annotations throughout helper functions (all functions in front of `populate_*` functions are helpers). For `populate_*` functions parameters, I add `zod` schemas to valdiate the raw data coming from backend. Use `blueslip` error reporting utility to throw errors if data from backend does not match the schema.
<details> <summary>Self-review Checklist</summary> …

ts: Migrate `stats.js` to TypeScript

---

tools/test-js-with-node
web/src/people.ts
web/src/stream_create_subscribers_data.ts
web/src/user_group_create_members_data.ts

`stream_create_subscribers_data.js` and `user_group_create_members_data.js`  are very similar.
Fixes: 
<details>
</details>

ts: Migrate `stream_create_subscribers_data.js` and `user_group_create_members_data.js` to TypeScript.

---

zerver/middleware.py

In servers with `application_server.http_only = true` and `loadbalancer.ips` set, the DetectProxyMisconfiguration middleware prevents access over HTTP from IP addresses other than the loadbalancer.
However, this misses the case of access from localhost over HTTP, which is safe and expected -- for instance, the `email-mirror-postfix` script used in the email gateway[^1] will post to `http://localhost/` by default in such configurations.  With the
DetectProxyMisconfiguration installed, this will result in a 403 response.
Make an exception for requests from `127.0.0.1` and `::1` from proxy-misconfiguration rejections.
[^1]: https://zulip.readthedocs.io/en/latest/production/email-gateway.html
<details> …

middleware: Allow HTTP from localhost, not through a reverse proxy.

---

docs/documentation/api.md
zerver/openapi/zulip.yaml

This makes it slightly easier to automatically generate an api client directly from the OpenAPI specification. There were a couple of changes which I wanted to make but didn't as it would regress the generated api docs. For example merging `BasicStream` and `DefaultStream`.
Fixes: 
<details>
</details>

Slightly simplify the OpenAPI specification

---

templates/zerver/base.html
templates/zerver/documentation_main.html
web/src/portico/help.js
web/styles/portico/portico.css
zerver/views/documentation.py

The API and user documentation pages gain nothing from being a single page application other than a bunch of random errors.
- Fixes #15706.
- Fixes #26249.
- Fixes https://github.com/zulip/zulip/pull/26473#discussion_r1295309255.
**Testing Plan:** Dev server.

help: Stop pretending to be a single page application

---

web/styles/app_components.css
web/styles/informational_overlays.css
web/styles/settings.css
web/templates/keyboard_shortcuts.hbs
web/templates/markdown_help.hbs
web/templates/search_operators.hbs
web/templates/settings/admin_profile_field_list.hbs
web/templates/settings/alert_word_settings.hbs
web/templates/settings/attachments_settings.hbs
web/templates/settings/bot_list_admin.hbs
web/templates/settings/data_exports_admin.hbs
web/templates/settings/deactivated_users_admin.hbs
web/templates/settings/default_streams_list_admin.hbs
web/templates/settings/emoji_settings_admin.hbs
web/templates/settings/invites_list_admin.hbs
web/templates/settings/linkifier_settings_admin.hbs
web/templates/settings/muted_users_settings.hbs
web/templates/settings/notification_settings.hbs
web/templates/settings/playground_settings_admin.hbs
web/templates/settings/profile_field_settings_admin.hbs
web/templates/settings/realm_domains_modal.hbs
web/templates/settings/user_list_admin.hbs
web/templates/settings/user_topics_settings.hbs

- First two commits are to remove `table-condensed` class and its CSS.
- Next commit is to fix the border in headings for striped tables.
- Next commit is to make custom profile fields table consistent with other tables.
- Last commit is to reduce width of `Actions` column in various tables.
<details>
</details>

Fix table related CSS and make custom profile field table consistent with other tables.

---

templates/zerver/app/index.html
web/src/lightbox.js
web/src/message_list_tooltips.js
web/src/message_lists.js
web/src/narrow.js
web/src/reactions.js
web/src/rows.js
web/src/ui_init.js
web/styles/dark_theme.css
web/styles/print.css
web/styles/zulip.css
web/tests/lightbox.test.js
web/tests/reactions.test.js

This begins the very earliest work on #23812. This also preps the way for other work, including [moving more of the message-row-oriented CSS](https://chat.zulip.org/#narrow/stream/6-frontend/topic/expanding.20and.20renaming.20message_row.2Ecss/near/1624608) now in `message_row.css`, which will ultimately become something like `message_feed.css`
The only change from the guidance there is to use hyphens rather than underscores for the renamed classes and IDs, in keeping with [stated Zulip style](https://zulip.readthedocs.io/en/latest/subsystems/html-css.html#use-clear-unique-names-for-classes-and-object-ids).
<details> …

feeds: Modify classes and IDs for feed and message lists.

---

zerver/actions/streams.py
zerver/lib/stream_traffic.py
zerver/lib/streams.py
zerver/lib/subscription_info.py
zerver/tests/test_subs.py
zerver/views/streams.py

- First commit is a refactor commit to check whether realm is a zephyr mirror realm in `get_streams_traffic`.
- Second commit is to set `stream_weekly_traffic` to `null` for Subscription objects in Zephyr mirror realm.
<details>
</details>

Set `stream_weekly_traffic` to `null` for Subscription objects in Zephyr mirror realm.

---

web/src/bot_data.ts

According to zulip [`/register` API doc](https://zulip.com/api/register-queue#:~:text=owner_id%3A%20integer%20%7C%20null), `realm_bots[].owner_id` should be nullalbe.
Fixes commit [71401493738e28ea90203a667b307816a5e4feed](https://github.com/zulip/zulip/commit/71401493738e28ea90203a667b307816a5e4feed).
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/bot_data.2Eowner_id.20type)
<details>
</details>

bot_data: Fix `owner_id` field to allow null value.

---

templates/corporate/jobs.html

And go back to the note about not currently having any open positions.
<details>
</details>

portico: Remove Senior Flutter Engineer position from jobs page.

---

web/styles/recent_topics.css
web/styles/zulip.css

**EDIT: This should be considered WIP at the moment; this would introduce some side-effects in Recent conversations that have yet to be accounted for.**
This gives better positioning control over this new icon, while not inviting the side-effects and headaches of introducing another flexbox.
| --- | --- |
| ![before-controls-bell](https://github.com/zulip/zulip/assets/170719/8d98c7e2-af2d-4d02-841b-1a8ee302cc69) | ![after-controls-bell](https://github.com/zulip/zulip/assets/170719/57d3d57f-f091-4a17-829c-b836d08a0f07) |
| Before | After (perfect centering) |
| --- | --- |
| ![before-centered-bell](https://github.com/zulip/zulip/assets/170719/557bcf9a-d907-4d05-87ad-c169ceac73c6) | …

controls: Present bell icon as a block.

---

zerver/lib/send_email.py

send_email: Use a consistent order when sending custom emails to users.

---

zerver/actions/message_edit.py
zerver/actions/message_send.py
zerver/actions/reactions.py
zerver/lib/message.py
zerver/lib/onboarding.py
zerver/models.py
zerver/tests/test_link_embed.py
zerver/tests/test_markdown.py
zerver/tests/test_scheduled_messages.py
zerver/tests/test_signup.py
zerver/tests/test_subs.py
zerver/tests/test_users.py
zerver/views/reactions.py

- First commit is just a prep commit to pass realm to `Message` obejcts created in markdown tests.
- Second commit is to access realm directly from `Message` object.
- Third commit is to access realm field directly from `SendMessageRequest`. 
- Fourth commit is to pass `realm` to `wildcard_mention_allowed`.
- Fifth commit is to directly access `realm` from `ScheduledMessage` object.
- Sixth commit is to remove "sender__realm" argument from `select_related` call for message objects.
<details>
Completed …

Access realm directly from `Message` objects.

---

scripts/lib/check-database-compatibility

https://chat.zulip.org/#narrow/stream/49-development-help/topic/puppeteer.20migration.20two_factor/near/1630340

check-database-compatibility: Ignore twofactor typo

---

web/webpack.assets.json

In commit 640de3ad2946db388a2d816bd8cc0ac0b9884062, a separate `page_params.ts` was added for the stats/analytics page, but adding it to the `web/webpack.assets.json` for "stats" was missed, so we add that here.
Confirmed via manually testing in the dev environment that the stats page loads for the "Analytics" realm with these changes.
---
<details>
</details>

stats: Add stats `page_params` to `webpack.assets.json`.

---

help/browse-and-subscribe-to-streams.md
help/include/mobile-all-streams-view.md
static/images/help/mobile-plus-icon.svg

- Updates [Browse and subscribe to streams](https://zulip.com/help/browse-and-subscribe-to-streams) to follow current help center documentation patterns.
- Documents stream list sorting feature on Desktop/web.
- Documents mobile instructions.
<details>
</details>

help: Document "Browse and subscribe to streams" mobile feature.

---

api_docs/changelog.md
version.py
zerver/actions/users.py
zerver/lib/events.py
zerver/lib/streams.py
zerver/lib/test_classes.py
zerver/openapi/zulip.yaml
zerver/tests/test_events.py
zerver/tests/test_users.py

- First commit is to fix the api docs taken from #26160.
- Second commit is to include web public streams in `streams` field of register response.
- Third commit is to fix `apply_event` code.
- Fourth commit is to add code to sends stream creation or deletion events on changing role.
<details>
</details>

Send stream creation or deletion event on changing role.

---

api_docs/changelog.md
zerver/openapi/zulip.yaml

This is a collection of small documentation fixes, including:
- Missing changelog entry for muted_users (https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/muted_users.20.28POST.20.2Fregister.29)
- Clarify changelog entry for moving topics @ 152 (https://chat.zulip.org/#narrow/stream/378-api-design/topic/update_message.20default.20notifications)
- Lack of `realm` required for a giphy register value (https://chat.zulip.org/#narrow/stream/378-api-design/topic/.60giphy_rating_options.60.20in.20.2Fregister.20response)
- Some typos noticed along the way
<details> …

API documentation fixes

---

api_docs/changelog.md

Updates API changelog feature level 119 entry for clarity. Follow-up to #26590.
**Notes**:
- This changelog entry originally would have been written before the rename of "private messages" to "direct messages". I used the current name in the updates (see screenshot below). If this is fine, then another follow-up to this would be to update the one remaining textual reference to "private messages" in feature level 11. All other uses of "private" in the API changelog are either references to private streams or a field, name, enum in the actual API.
[Current documentation](https://zulip.com/api/changelog#changes-in-zulip-50)
---
<details> …

api-changelog: Update feature level 119 entry for clarity.

---

templates/corporate/development-community.md

corporate: We have switched to DMs, from PMs.

---

web/src/messages_overlay_ui.ts

This fixes a regression from a240280c12fbbce34d8bab63e33abb996f3d4d06 that resulted in a duplicated, incorrect check for parent and child elements within `scroll_to_element`.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/drafts.20keyboard.20navigation/near/1632782) 
<details>
</details>

scroll: Correct element checks before activation.

---

zerver/lib/send_email.py
zerver/management/commands/send_custom_email.py
zerver/tests/test_email_notifications.py

send_email: Provide the realm and string_id, for ease of "if" logic.

---

requirements/dev.txt
requirements/prod.txt
version.py
zerver/lib/push_notifications.py
zerver/tests/test_push_notifications.py

aioapns upgrade and performance tweak

---

help/create-a-stream.md
help/create-streams.md
help/include/create-a-stream-instructions.md

- Updates [Create a stream](https://zulip.com/help/create-a-stream) and [Create streams](https://zulip.com/help/create-streams) to follow current help center documentation patterns.
- Moves Desktop/Web instructions instructions to a Markdown include-block.
- Adds mobile instructions.
<details>
</details>

help: Add mobile instructions to "Create a stream".

---

web/src/copy_and_paste.js

This PR introduces checks for two edge cases where the paste-URL logic should not apply:
1. On text selections already in or adjacent likely Markdown link syntax
2. Over top of existing links
[CZO discussion](https://chat.zulip.org/#narrow/stream/191-kandra-support/topic/embedded.20links.20broken.3F/near/1630237)
<details>
</details>

compose: Prevent undesired link-pasting behavior.

---

api_docs/changelog.md
zerver/openapi/zulip.yaml

Updates API changelog entries for feature level 205 for minor revisions and the addition of help center links. Also, revises the **Changes** notes for the stream creation and deletion events for the same feature level.
Follow-up from https://github.com/zulip/zulip/pull/26234#discussion_r1306094950.
<details>
<summary>Updated API changelog - feature level 205</summary>
</details>
<details>
<summary>Event - stream op: create</summary>
</details>
<details>
<summary>Event - stream op: delete</summary>
</details>
---
<details> …

api-docs: Update feature level 205 changelog entry and changes notes.

---

docs/overview/changelog.md
web/src/settings_bots.js
web/src/settings_users.js
web/tests/upload.test.js
zerver/tests/test_events.py
zerver/tests/test_message_fetch.py
zerver/tests/test_muted_users.py
zerver/tests/test_signup.py
zerver/transaction_tests/test_user_groups.py

https://github.com/crate-ci/typos

docs: Fix typos caught by ‘typos’

---

web/src/user_profile.js

This commit fixes the issue of reordering the stream list when the user unsubscribes from a stream. The issue was caused because, on rendering, we sorted the list by name but did not sort it while updating the stream list on any update.
--------
Fixes: [CZO Thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/unsubscribing.20reorders.20streams)
--------
<details><summary>Before:</summary>
</details>
<details><summary>After:</summary>
</details>
------------
<details> …

user_profile: Sort the stream list on update and Prevent unwanted reordering.

---

tools/test-js-with-node
web/src/attachments_ui.js
web/src/attachments_ui.ts
web/src/page_params.ts

Migrates `attachments_ui` module to TypeScript.
<details>
</details>

ts: Migrate `attachments_ui` to typescript.

---

web/src/upload.js
web/tests/upload.test.js

This PR prevents the browser from dropping in a plaintext version of a file name when an image or other file is pasted into the compose box before being handled by the file-upload logic.
CZO discussion:
https://chat.zulip.org/#narrow/stream/191-kandra-support/topic/embedded.20links.20broken.3F/near/1635730
| --- | --- |
| ![image-paste-before](https://github.com/zulip/zulip/assets/170719/1e386e69-92e3-4e4a-aaf8-86db2b340cb7) | ![image-paste-after](https://github.com/zulip/zulip/assets/170719/efdd1740-1ee6-4cd7-bbb2-07197bb81238) |
<details> …

images: Prevent default browser behavior on paste.

---

tools/test-js-with-node
web/src/avatar.ts
web/src/global.d.ts
web/src/page_params.ts
web/src/setup.ts
web/src/upload_widget.ts

Migrates `avatar.js` module to TypeScript.
<details>
</details>

ts: Migrate `avatar.js` module to TypeScript.

---

web/src/avatar.ts
web/src/global.d.ts
web/src/setup.ts

setup: Fix wildly unsafe cast in $.fn.expectOne

---

tools/test-js-with-node
web/src/page_params.ts
web/src/realm_icon.ts
web/src/realm_logo.ts

Migrates two similar modules:
- `realm_icon`
- `realm_logo`
<details>
</details>

Migrate `realm_icon` and `realm_logo` modules to typescript.

---

tools/test-js-with-node
web/src/fold_dict.ts
web/src/ui_init.js
web/src/user_topics.js
web/src/user_topics.ts
web/tests/user_topics.test.js

Migrates `user_topics.js` module to TypeScript.
<details>
</details>

Migrate `user_topics` module to typescript.

---

puppet/zulip/manifests/common.pp
puppet/zulip_ops/manifests/prometheus/postgresql.pp

The branch from the PR is somewhat stale, and was missing important bugfixes.
<details>
</details>

postgres_exporter: Rebase the per-index stats branch.

---

docs/development/request-remote.md
docs/production/install-existing-server.md
docs/production/maintain-secure-upgrade.md
docs/production/password-strength.md

https://myst-parser.readthedocs.io/en/latest/faq/index.html#sphinx-specific-page-front-matter

docs: Use MyST syntax for Sphinx metadata

---

scripts/lib/zulip_tools.py

While working on emoji earlier, I noticed we need to regenerate emoji when this file changes, so I'm adding it to the sha1sum.

emoji: Add unified_reactions.json to the sha1sum.

---

zerver/tests/test_widgets.py

Follow up to #26643, adds test case for the bug fix.
<details>
</details>

widgets: Add test for tokenizing widget type on newline.

---

tools/test-js-with-puppeteer

We already allowed reruns for failing tests, and this adds the ability to rerun tests that succeeded as well, which is helpful for debugging flaky tests.
Tested manually.

puppeteer: Allow reruns in interactive mode when tests succeed.

---

help/change-a-users-name.md
help/change-a-users-role.md
help/deactivate-or-reactivate-a-user.md
help/include/manage-this-user-via-user-profile.md
zerver/lib/markdown/tabbed_sections.py

This is a follow-up PR (https://github.com/zulip/zulip/pull/26031#issuecomment-1712986779) to document how to access the "Manage user" tab via a user's profile to [Change a user's role](https://zulip.com/help/change-a-users-role), [Change a user's name](https://zulip.com/help/change-a-users-name), and [Deactivate or reactivate a user](https://zulip.com/help/deactivate-or-reactivate-a-user)
<details>
</details>

help: Update user management pages.

---

web/src/notifications.js
web/src/settings_notifications.js
web/src/settings_org.js
web/src/settings_realm_user_settings_defaults.js

Fixes: #26598
This PR fixes the issue of play button not playing the selected sound in dropdown in default user settings.
Fixes: 
#26598 
https://github.com/zulip/zulip/assets/119798962/fcdd6ab8-07b2-4fed-9f9c-3f610e06a8ef
<details>
</details>

default_user_settings: Fix play button not playing selected sound.

---

zerver/lib/digest.py
zerver/lib/email_notifications.py
zerver/tests/test_digest.py

Digest improvements

---

puppet/zulip_ops/files/nagios4/commands.cfg
puppet/zulip_ops/files/nagios4/conf.d/services.cfg

Load monitoring alerts are extremely noisy, and do not reliably indicate an issue which is affecting users.
<details>
</details>

nagios: Remove load monitoring.

---

web/src/tippyjs.js
web/templates/user_info_popover_content.hbs

This commit will add a tooltip whenever the user hovers on the status-emoji in the user card popover.
The tooltip will display the name of status-emoji.
This proposal came into action when working on   #19821 
<details>
</details>

tooltips: added a tooltip to display the name of status-emoji

---

web/src/message_edit.js

This passes a missing parameter to the message-edit rendering function, so that a Giphy GIF button is displayed when a message is being edited (and Giphy is available).
While there are some additional things to fix up with the editing form and its layout, those will require [additional discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/adjusting.20the.20message-edit.20form/near/1640698) and follow-up PRs.
[Original CZO issue discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/no.20GIF.20button.20when.20editing/near/1639551)
| --- | --- |
| ![gif-button-before](https://github.com/zulip/zulip/assets/170719/84232ca3-c7cd-4d20-9c96-d14e52ab7730) | ![gif-button-after](https://github.com/zulip/zulip/assets/17071 …

message_edit: Display GIF button when Giphy is enabled.

---

.github/workflows/production-suite.yml
docs/production/troubleshooting.md
puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf
puppet/zulip/templates/nginx/trusted-proto.template.erb
web/src/ui_init.js
web/styles/left_sidebar.css
web/templates/left_sidebar.hbs
zerver/middleware.py
zerver/tests/test_integrations_dev_panel.py

Backports the following previous staged for backporting:
* https://github.com/zulip/zulip/pull/26468
* https://github.com/zulip/zulip/pull/26707
* https://github.com/zulip/zulip/pull/26591
* https://github.com/zulip/zulip/pull/26628
* https://github.com/zulip/zulip/pull/26376
* https://github.com/zulip/zulip/pull/26572
* https://github.com/zulip/zulip/pull/26744

Backport changes to the 7.x branch from main for the 7.x release

---

help/add-or-remove-users-from-a-stream.md

As discussed in https://github.com/zulip/zulip/pull/26645#issuecomment-1711558473, this is a follow-up PR to update [Remove users from a stream](https://zulip.com/help/add-or-remove-users-from-a-stream#remove-users-from-a-stream) to follow current help center documentation patterns, adding Desktop/web instructions to unsubscribe users via stream settings.
<details>
</details>

help: Update "Remove users from a stream".

---

web/src/typeahead_helper.js
web/tests/composebox_typeahead.test.js
web/tests/typeahead_helper.test.js

We suggest only the first matching wildcard mention, irrespective of how many equivalent wildcard mentions match.
</img>
</details> 
Fixes: #25613
[typeahead.webm](https://github.com/zulip/zulip/assets/56781761/8d722c8f-ea56-47d7-9290-0b0082fbf509)
<details>
</details>

typeahead: Suggest only the first matching wildcard mention.

---

.github/workflows/zulip-ci.yml

[7.x] ci: Restore commented clean_unused_caches.py invocation

---

web/src/hashchange.js
web/src/hotkey.js
web/src/inbox_ui.js
web/src/narrow.js
web/src/settings_config.ts
web/styles/inbox.css
web/styles/zulip.css
zerver/openapi/zulip.yaml
zerver/tests/test_events.py
zerver/tests/test_realm.py
zerver/views/realm.py
zerver/views/user_settings.py

Add inbox view to set of allowed default views.

---

puppet/zulip/templates/uwsgi.ini.template.erb

The rolling restart configuration of uwsgi attempted to re-chdir the CWD to the new `/home/zulip/deployments/current` before `lazy-apps` loaded the application in the forked child.  It successfully did so -- however, the "main" process was still running in the original `/home/zulip/deployments/current`, which somehow (?) tainted the search path of the children processes.
Set the parent uwsgi process to start in `/`, so that the old deploy directory cannot taint the load order of later children processes.  We also shift all deployments to be lazy-apps, as this does not appear to alter the memory footprint in any way.
<details>
Individual …

uwsgi: Ensure that the master process cannot load the application.

---

web/styles/dark_theme.css
web/styles/zulip.css
web/templates/message_edit_form.hbs

Fixes: #26759
This PR removes ```?``` icon after edit timer-text and moves the tippy tooltip to the timer-text itself in the message-edit-form.
Fixes: 
Fixes: #26759
<details>
</details>

message_edit_form: Remove question mark icon after edit-timer-text.

---

web/src/user_group_edit.js
zerver/lib/user_groups.py
zerver/tests/test_user_groups.py

- First commit is to restrict empty group names in API.
- Second commit is to show error, if any, inside the modal iteself when editing user group info.
Fixes: 3rd point in https://github.com/zulip/zulip/pull/26782#issuecomment-1726542908
<details>
</details>

Do not allow empty user group names.

---

web/tests/stream_events.test.js
web/tests/upload.test.js

tests: Fix direct mutation of ES modules again

---

help/include/sidebar_index.md
help/view-all-bots-in-your-organization.md
help/view-your-bots.md

- Adds new page with instructions for how to view your personal bots.
Fixes #26796.
<details>
</details>

help: Add "View your bots" page.

---

web/templates/settings/display_settings.hbs

Adds a help link to https://zulip.com/help/configure-emoticon-translations under preferences, the Emoji section, to explain the rules around converting `:)` to 😄 , etc.
- Fixes: #18147
<details>
</details>

settings: link to list of emoticon translations (e.g. :) for 😄)

---

tools/test-js-with-node
web/e2e-tests/message-basics.test.ts
web/src/message_view_header.js
web/src/search.js
web/styles/dark_theme.css
web/styles/search.css
web/styles/zulip.css
web/templates/message_view_header.hbs
web/templates/navbar.hbs
web/tests/search.test.js
web/third/bootstrap-typeahead/typeahead.js

Fixes: https://github.com/zulip/zulip/issues/21798
<details>
<summary>screen captures (outdated)</summary>
updated screenshot with correct option hover color:
https://github.com/zulip/zulip/assets/5634097/99bb9d46-f1e1-427c-bea0-dc2a0b5dd104
https://github.com/zulip/zulip/assets/5634097/9ff75dea-bd74-426b-8e04-996cd5179b83
https://github.com/zulip/zulip/assets/5634097/16284475-5f12-4edb-875a-ee4e473a99fa
https://github.com/zulip/zulip/assets/5634097/f781bd9b-b3b1-400a-9ea4-b150349dcfc3
https://github.com/zulip/zulip/assets/5634097/34cd9d25-e581-4edc-a1a9-3fb4abb01f41
https://github.com/zulip/zulip/assets/5634097/5ba289b5-37e2-4a08-9be1-3c9fc9f7fde2
</details>

search: Redesign the search bar.

---

web/styles/rendered_markdown.css

Until now, lists with 3+ digit markers would have their beginnings cut off to align with 2 digit markers. We fix that by having custom styling for markers where we align markers only up to 2 digits, and let larger numbers take up more space pushing the list item content forward as required to fit the marker. Also works for multiline / paragraph list items.
Fixes: https://chat.zulip.org/#narrow/stream/9-issues/topic/large.20numbered.20lists
<details> …

markdown: Fix lists with 3+ digit markers retaining alignment for 2 digits

---

zerver/lib/narrow.py
zerver/tests/test_message_fetch.py

The unique index on `(user_id, message_id)` that is the `zerver_usermessage` table is rather specific, and even the PostgreSQL extended statistics are not enough for it to realize there is a correlation between the `realm_id` in the message table and the `user_id` in the usermessage table.  This means that adding the `realm_id` limit when there is a join to `zerver_usermessage` flips the query plan from a nested loop of unique usermessage index-only scan, with an index scan of the messages pkey -- to a parallel hash join of the messages limit with a index scan of just the user_id limit on usermessages.  It thinks this is necessary because it thinks that the `realm_id` limit may remove a large number of messages from the usermessage set -- which is totally untrue.
Remove the `realm_id` …

narrow: Skip the realm_id limit on joins across to usermessage.

---

web/src/message_view_header.js
web/src/search.js

Discussed on CZO [here](https://chat.zulip.org/#narrow/stream/6-frontend/topic/search.20code.20files/near/1644428).

search: Move search code from message_view_header to search.js.

---

web/src/settings_users.js

When changing name of users, the name was updated corectly in the "Users", "Deactivated users"
and "Bots" list but it removed the "<a>" element, used to open the user popover, and instead
changed it to plain text.
This PR updates the code to just update the text inside "<a>" tag so that the popover can still be
opened by clicking on the name.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/Renaming.20a.20deactivated.20user
<details> …

settings: Fix live-update bug when changing user names.

---

web/src/narrow_banner.js
web/tests/narrow.test.js

Previously we showed "no search results".
CZO conversation:
https://chat.zulip.org/#narrow/stream/9-issues/topic/.22no.20search.20results.22.20in.20topic.20view/near/1637289

stream view: Show "start a conversation" for a topic with no messages.

---

puppet/zulip/manifests/app_frontend_base.pp
puppet/zulip/manifests/postgresql_client.pp
puppet/zulip_ops/manifests/prometheus/postgresql.pp
scripts/setup/pgroonga-config

Found when installing with `--no-overwrite-settings` on a new CZO host.
<details>
</details>

Fix puppet bugs when installing complex configs from scratch

---

tools/test-js-with-node
web/src/global.d.ts
web/src/hbs.d.ts
web/src/invite.ts
web/src/page_params.ts
web/src/rtl.ts
web/src/stream_data.ts

I made this look only a little bit insane by improving the type of jQuery `.val()` (submitted upstream as DefinitelyTyped/DefinitelyTyped#66801). I suspect this insanity is going to be pretty common in jQuery code dealing with input controls.

invite: Convert module to TypeScript

---

web/src/settings_data.ts
web/src/user_group_edit.js
web/src/user_group_edit_members.js
web/src/user_group_ui_updates.js
web/tests/settings_data.test.js

Fixes two import cycles involving the user_group_edit module.

Fix `user_group_edit` module import cycles

---

zerver/lib/push_notifications.py
zerver/tests/test_push_notifications.py
zilencer/views.py

zilencer: Log how long the remote server delayed the push notification.

---

tools/test-js-with-node
web/src/integration_url_modal.js
web/src/settings_bots.js
web/src/settings_data.ts
web/src/settings_users.js
web/src/user_deactivation_ui.js
web/src/user_profile.js
web/tests/settings_data.test.js

- First commit is to move `type_id_to_string` function to `settings_data.ts`.
- Next two commits are to move `show_edit_bot_info_modal` and `show_edit_user_info_modal` to `user_profile.js`.
- Next commit is to extract some code to `custom_profile_fields_ui.js`.
- Next commit is to move `show_generate_integration_url_modal` to `user_profile.js`.
- Last two commits are to move `confirm_bot_deactivation` and `confirm_deactivation` to `user_profile.js`.
Fixes:  https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1645525
<details> …

Re-arrange code related to bot and user settings.

---

templates/zerver/emails/confirm_demo_organization_email.html
zerver/tests/test_email_notifications.py
zerver/views/development/email_log.py

Some small clean-ups related to recent onboarding and demo organization email changes.
- Updates any "day1" or "day2" references to previous names for onboaring emails
- Fixes a typo in the email confirmation for demo organization owners.
<details>
</details>

emails: Fix outdated email references and typo.

---

web/src/settings_config.ts
zerver/openapi/zulip.yaml

This commit updates the text for a dropdown option `Unmuted streams` to `Unmuted streams and topics` for `Show unread counts for` user preference settings for better clarity.
CZO: https://chat.zulip.org/#narrow/stream/101-design/topic/show.20unread.20counts.20setting
Fixes: 
Before:
After:
<details>
</details>

user_preferences: Change option text for "Show unread counts for".

---

web/styles/portico/portico.css

Changing `100vh` to `100%` makes the markdown div take up the full height of the page, even when the page is scrolled. This fixes the bug where the lower right corner of the page was not covered by the markdown div and the background was visible.
Fixes: [Issue's CZO thread](url)
Before:
After:
<details>
</details>

documentation: Make the markdown div take up all available height.

---

zerver/lib/message.py
zerver/lib/narrow.py
zerver/lib/topic.py
zerver/models.py
zerver/tests/test_message_fetch.py
zerver/views/streams.py

Add more realm limits

---

web/src/settings_bots.js
web/src/settings_config.ts
web/src/settings_users.js
web/src/user_card_popover.js
web/src/user_deactivation_ui.js
web/src/user_profile.js
web/templates/settings/admin_human_form.hbs
web/templates/settings/edit_bot_form.hbs
zerver/openapi/zulip.yaml

This PR adds "Reactivate user" option in "manage user" panel if the user is deactivated.
Fixes: #26693
https://github.com/zulip/zulip/assets/119798962/08dc2806-60ef-4532-a62c-c3cbe26baacf
<details>
</details>

settings_users: Add "Reactivate  user" option in "manage user" panel.

---

help/view-a-messages-edit-history.md

- Drop unnecessary heading.
- Reorganize and tighten content.
Current page: https://zulip.com/help/view-a-messages-edit-history
New:

help: Improve /help/view-a-messages-edit-history.

---

help/create-a-stream.md

Option was introduced in #24216.

help: Document option to add stream to default streams when creating.

---

web/styles/left_sidebar.css

This fixes a regression introduced in #26807, where a padding adjustment spilled over to the privacy icon display in message headers.
This fix should prevent future spillover by isolating left-sidebar stream icon styles to just the streams list.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/Left.20sidebar.20rows.20as.20grids/near/1648849)
| --- | --- |
| ![privacy-icon-before](https://github.com/zulip/zulip/assets/170719/45c77662-36c6-4603-b36e-92bbacfcf560) | ![privacy-icon-after](https://github.com/zulip/zulip/assets/170719/9dcb457f-7b9a-4393-8583-a3e5cbb175a7) |
<details> …

left_sidebar: Limit privacy icon styles to streams list.

---

web/src/settings_org.js
web/src/util.ts
web/tests/util.test.js

Extracted from #20449 and improved; @amanagr FYI.

util: Implement is_valid_url more correctly, with tests.

---

web/src/inbox_ui.js

This will also work for page up/down naturally.

inbox: Move focused row to visible area on scroll.

---

web/src/user_card_popover.js
web/styles/popovers.css
web/styles/settings.css
web/templates/settings/bot_avatar_row.hbs
web/templates/user_custom_profile_fields.hbs

Abbreviated long URL for custom field in the user profile.
Added copy to clipboard icon at end of the field with tippy on hover that says `Copy URL`.
Clicking on the copied button shows a `Copied!` tippy tooltip for 1 sec.
Fixes: 
#21680
https://user-images.githubusercontent.com/64723994/228928380-e2f95be3-110e-42a5-be19-f47606efe509.mp4
<details>
</details>

user_profile_modal: Abbreviate long URLs of custom fields.

---

tools/test-js-with-node
web/src/message_list_hover.js
web/src/ui_init.js

This is https://github.com/zulip/zulip/pull/26167 with the CI node coverage failure fixed. I had to make a new PR because of https://github.com/zulip/zulip/pull/26167#issuecomment-1740161162.

message_list_view: Fix hover on new message. (New PR for #26167)

---

zerver/data_import/slack.py

data_import: Skip Slack "Posts" which we don't otherwise support.

---

web/src/user_group_popover.js

Users could see members of group in descending order of characters in alphabet.
Fixes: [this](https://github.com/zulip/zulip/issues/25963)
<details>
</details>

popovers: Alphabetize group members in user group

---

web/src/inbox_ui.js

discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/inbox.20view.20.2322408/near/1647407

inbox: Focus on entire row instead of stream name on show.

---

docs/development/remote.md

Update development docs

---

web/src/buddy_data.js
web/src/user_search.js
web/tests/buddy_data.test.js
web/tests/user_search.test.js

We should search for what the user asked us to search for. 
CZO conversation:
https://chat.zulip.org/#narrow/stream/101-design/topic/search.20buddy.20list.20for.20self/near/1630454

buddy list: Show self in search results.

---

analytics/tests/test_support_views.py
docs/production/authentication-methods.md
docs/production/management-commands.md
help/archive-a-stream.md
zerver/actions/create_user.py
zerver/actions/streams.py
zerver/forms.py
zerver/lib/bulk_create.py
zerver/lib/create_user.py
zerver/lib/i18n.py
zerver/management/commands/delete_old_unclaimed_attachments.py
zerver/management/commands/import.py
zerver/management/commands/unarchive_stream.py
zerver/tests/test_auth_backends.py
zerver/tests/test_mirror_users.py
zerver/tests/test_realm.py
zerver/tests/test_signup.py
zerver/tests/test_subs.py
zerver/tests/test_users.py
zerver/views/registration.py

* #26684
* #26357
* #26853
* #26933
* #24284
* #26853

Backport several changes to the 7.x branch.

---

tools/test-js-with-node
web/src/hotkey.js
web/src/inbox_ui.js
web/src/inbox_util.js
web/src/message_scroll.js
web/src/message_scroll_state.ts
web/src/message_viewport.js
web/src/server_events_dispatch.js
web/src/sidebar_ui.js
web/src/ui_init.js
web/tests/dispatch.test.js

(120, 61) → (113, 57). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1651204).

Import decycling

---

tools/test-js-with-node
web/src/activity.js
web/src/add_stream_options_popover.js
web/src/click_handlers.js
web/src/giphy.js
web/src/hashchange.js
web/src/hotkey.js
web/src/message_list.js
web/src/message_lists.js
web/src/popover_menus.js
web/src/popovers.js
web/src/resize.js
web/src/sidebar_ui.js
web/src/stream_list.js
web/src/stream_popover.js
web/src/topic_zoom.js
web/src/ui_init.js
web/src/user_card_popover.js
web/src/user_group_popover.js
web/src/user_search.js
web/templates/navbar.hbs
web/templates/stream_sidebar_actions.hbs
web/templates/user_card_popover_content.hbs
web/tests/activity.test.js
web/tests/user_search.test.js

Based on Tim's comment in #26884

Simplify popovers library.

---

web/src/activity.js
web/src/ui_init.js
web/tests/activity.test.js

Fix sidebars not closing when navigating to a conversation via the keyboard

---

web/styles/app_components.css
web/styles/dark_theme.css

[CZO report](https://chat.zulip.org/#narrow/stream/101-design/topic/followed.20topic.20left.20sidebar/near/1638613)
On hovering the not-selected option in the left sidebar topic popover widget to change visibility policy, a wiggle effect was observed.
This PR fixes the wiggle effect.
---
**Before**
[wiggle.webm](https://github.com/zulip/zulip/assets/56781761/417a3c0e-6524-4308-abfc-adcd6f397584)
**After**
[no-wiggle.webm](https://github.com/zulip/zulip/assets/56781761/fbf675c4-a011-4698-9bf8-892afba4232e)
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipl …

topic_popover: Fix the wiggle on hovering visibility policy buttons.

---

docs/tutorials/life-of-a-request.md

Correct the `PUT` to `POST` in the `/docs/tutorial/life-of-a-request.md` to match it with the actual code in `zproject/urls.py` route: '/users'
Fixes: 
The documentation
Actual Code
<details>
- [x ] [Self-reviewed](https://zulip.readthedocs.io/en/latest/contributing/code-reviewing.html#how-to-review-code) the changes for clarity and maintainability
</details>

documentation: small correction in tutorial docs

---

zerver/webhooks/zapier/doc.md

Current page: https://zulip.com/integrations/doc/zapier
Notes:
- We need to update some details in Zapier, and then follow up by updating these instructions.
- I left the `{!create-stream.md!}` instruction, though it's not actually required if you are setting up incoming DMs instead. I wasn't sure if it's something we should adjust here, or across all the integrations that use this instruction, or ...?
<details>
<summary>
Updated page
</summary>
</details>
<details>
<summary>
Zapier flow sreenshots
</summary>
</details>

integrations: Update Zapier documentation.

---

web/src/compose.js
web/src/message_edit.js
web/src/ui_init.js
web/src/upload.js
web/tests/compose.test.js
web/tests/compose_video.test.js
web/tests/upload.test.js

(78, 35) → (76,33). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1652665).

Move upload objects to upload module

---

web/src/narrow.js

Introduced by commit 00ea197744913fbfe4e62691da3e4be241df4357 (#25423).

narrow: Don’t swallow errors in narrow.activate

---

tools/test-js-with-node
web/src/compose.js
web/src/scheduled_messages.js
web/src/scheduled_messages_overlay_ui.js
web/src/scheduled_messages_popover.js
web/src/scheduled_messages_ui.js
web/src/server_events_dispatch.js
web/src/ui_init.js
web/tests/scheduled_messages.test.js

left_sidebar_navigation_area: Cut scheduled_messages import

---

web/src/compose.js
web/src/compose_call.js
web/src/message_edit.js
web/src/server_events_dispatch.js

compose: Extract compose_call module

---

docs/translating/index.md
docs/translating/urdu.md

A style guide based on the the conventions established by existing style guides of other languages.

translation: Add Urdu translation guide.

---

web/src/flatpickr.ts

Fixes https://github.com/zulip/zulip/pull/26826#issuecomment-1746811330.

flatpickr: Fix Tab key handler for 24-hour time

---

web/src/search.js

Reported here:
https://chat.zulip.org/#narrow/stream/9-issues/topic/search.20bar.3A.20selection.20jumping.20to.20whole.20query/near/1652562

search: Don't "initiate search" if it's already open.

---

web/src/settings_config.ts
web/src/settings_data.ts
web/src/settings_org.js
web/src/stream_data.ts
web/src/stream_edit.js
web/src/stream_settings_ui.js
web/tests/compose_validate.test.js
web/tests/recent_view.test.js
web/tests/stream_data.test.js
web/tests/stream_events.test.js

Cut settings_org → stream_edit import

---

zilencer/views.py

zilencer: Handle very old server push notifications.

---

web/src/compose_actions.js
web/src/compose_recipient.js
web/src/compose_state.js
web/src/server_events_dispatch.js
web/tests/compose.test.js
web/tests/compose_fade.test.js
web/tests/compose_state.test.js
web/tests/compose_validate.test.js
web/tests/composebox_typeahead.test.js
web/tests/drafts.test.js
web/tests/narrow.test.js

(67, 29) → (62, 28). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1655497)

compose_recipient: Move selected_recipient_id to compose_state

---

web/src/activity.js
web/src/activity_ui.js
web/src/click_handlers.js
web/src/hotkey.js
web/src/muted_users_ui.js
web/src/server_events_dispatch.js
web/src/ui_init.js
web/src/user_events.js
web/tests/activity.test.js
web/tests/dispatch.test.js
web/tests/example4.test.js
web/tests/hotkey.test.js
web/tests/user_events.test.js
web/tests/user_search.test.js

activity: Extract new activity_ui module

---

tools/lib/provision_inner.py
tools/update-prod-static

Follow-up to [#27048](https://github.com/zulip/zulip/pull/27048).
<details>
</details>

Adjust provision comment, only generate landing page images if necessary

---

tools/test-js-with-node
web/src/resize.js
web/src/resize_handler.js
web/src/ui_init.js

(60, 26) → (59, 25). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1655948).

resize: Move handler to new resize_handler module

---

templates/corporate/billing.html
templates/corporate/upgrade.html
templates/zerver/development/email_log.html
templates/zerver/development/integrations_dev_panel.html
web/src/billing/billing.ts
web/src/bundles/portico.ts
web/src/portico/email_log.js
web/src/portico/portico_modals.ts
web/src/portico/signup.ts
web/styles/portico/billing.css
web/styles/portico/email_log.css
web/styles/portico/integrations_dev_panel.css
web/templates/user_profile_subscribe_widget.hbs
web/tests/billing.test.js
web/third/bootstrap/css/bootstrap-btn.css
web/webpack.dev-assets.json

- First commit is to update the modal on billing page.
- Second commit is to update modal on "/emails" page.
- Third commit is to remove bootstrap CSS for `.btn-primary`.
- Fourth commit is to remove bootstrap CSS for `.btn-success`.
- Fifth commit is to update the code to use `overlays` module instead of directly using `Micromodal`.
Before:
After:
<details>
</details>

Remove bootstrap modal uses and also remove some bootstrap CSS for buttons.

---

zerver/webhooks/newrelic/fixtures/incident_acknowledged_new.json
zerver/webhooks/newrelic/fixtures/incident_active_new.json
zerver/webhooks/newrelic/fixtures/incident_closed_new.json
zerver/webhooks/newrelic/fixtures/incident_created_new.json
zerver/webhooks/newrelic/fixtures/incident_default_fields_new.json
zerver/webhooks/newrelic/fixtures/incident_malformatted_time_new.json
zerver/webhooks/newrelic/fixtures/incident_missing_state_new.json
zerver/webhooks/newrelic/fixtures/incident_missing_timestamp_new.json
zerver/webhooks/newrelic/fixtures/incident_state_not_recognized_new.json
zerver/webhooks/newrelic/fixtures/incident_time_too_large_new.json
zerver/webhooks/newrelic/tests.py
zerver/webhooks/newrelic/view.py

The previous fixtures were not generated from New Relic directly, so incorrectly implied that `id` was an integer.  See the examples for `issueId` in their documentation[^1].
[^1]: https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/message-templates/
Fixes: 
<details>
</details>

newrelic: ids are uuids, not integers.

---

analytics/tests/test_activity_views.py
analytics/urls.py
analytics/views/activity_common.py
analytics/views/installation_activity.py
analytics/views/remote_activity.py
templates/analytics/realm_summary_table.html

Either moves or removes remaining tabs in the main installation `/activity` page.
- The "Integrations by clients" tab is moved to `/activity/integrations`.
- The "Andriod usage", "ZulipiOS usage", "Desktop users", and "Integrations by realm" tabs are all removed.
- The code for `/activity/remote` is moved to a separate views file as well in a prep commit.
---
<details>
<summary>Integrations by client page - no data</summary>
</details>
<details>
<summary>Updated activity main page</summary>
</details>
---
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipl …

analytics: Remove or move tabs from main activity page.

---

web/src/stream_color.js
web/src/stream_events.js
web/src/stream_settings_api.js
web/src/stream_settings_ui.js
web/tests/stream_events.test.js

stream_settings_ui: Move set_color to stream_settings_api

---

web/src/inbox_ui.js
web/src/unread.js
web/templates/inbox_view/inbox_list.hbs
web/templates/inbox_view/inbox_stream_container.hbs

Inbox sort by rows by latest msg id.

---

docs/production/authentication-methods.md
zerver/tests/fixtures/ldap/directory.json
zerver/tests/test_auth_backends.py
zproject/backends.py
zproject/default_settings.py
zproject/prod_settings_template.py

This is a very simple implementation to synchronize LDAP Usergroups to Zulip Usergroups.
* It mirrors the name of the group 1:1
* If configured, automatically creates groups inside specified realms
* Adds a user to a group if inside an ldap group but not inside a zulip group
* Removes a user from a ldap group if inside a zulip group but not inside a ldap group
* Currently uses an allowlist for ldap groups
Fixes: #9957
This patch only uses settings from `settings.py` and extends the `sync_ldap_user_data` management command. …

implement group sync, fix #9957

---

tools/test-js-with-node
web/src/narrow.js
web/src/narrow_title.js
web/src/notifications.js
web/src/server_events_dispatch.js
web/src/ui_init.js
web/src/views_util.js
web/tests/dispatch.test.js
web/tests/narrow.test.js
web/tests/narrow_activate.test.js
web/tests/recent_view.test.js

(58, 24) → (57, 24). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1656120).

narrow: Extract narrow_title module

---

tools/test-js-with-node
web/src/drafts.js
web/src/drafts_overlay_ui.js
web/src/hashchange.js
web/src/hotkey.js
web/src/ui_init.js
web/tests/drafts.test.js
web/tests/hashchange.test.js
web/tests/hotkey.test.js

drafts: Extract drafts_overlay_ui module

---

docs/subsystems/hashchange-system.md
tools/test-js-with-node
web/src/compose.js
web/src/compose_call_ui.js
web/src/compose_state.js
web/src/reload.js
web/src/reload_setup.js
web/src/server_events_dispatch.js
web/src/ui_init.js
web/src/user_events.js
web/tests/user_events.test.js

Cut {reload, server_events_dispatch} → compose import paths

---

tools/test-js-with-node
web/src/click_handlers.js
web/src/compose_actions.js
web/src/compose_closed_ui.js
web/src/compose_reply.js
web/src/hotkey.js
web/src/message_actions_popover.js
web/src/ui_init.js
web/src/upload.js
web/src/user_card_popover.js
web/tests/compose_actions.test.js
web/tests/compose_ui.test.js
web/tests/hotkey.test.js
web/tests/upload.test.js

Seems to be a minor improvement, (56, 23) → (56, 21).

compose_actions: Extract compose_reply module

---

web/src/portico/hello.js
web/src/portico/landing-page.js
web/webpack.assets.json

Since `zulip.com` doesn't has `/hello` in URL, the JS code for hello page events was not running. We extract it to a new file and just always run it.

hello: Fix client logos not changing on hello page.

---

web/src/echo.js
web/src/sent_messages.js
web/src/transmit.js
web/src/ui_init.js
web/src/widgetize.js
web/src/widgets.js
web/tests/transmit.test.js
web/tests/widgetize.test.js

(51, 17) → (50, 16), and this also shrinks the strongly connected component from 66 modules to 49.
- echo ↛ transmit → server_events → echo
- echo → sent_messages ↛ server_events → echo
- echo → notifications → narrow → widgetize ↛ zform → transmit → server_events → echo

Cut echo → server_events import paths

---

web/src/recent_view_ui.js
web/src/ui_init.js

recent_view_ui: Cut import of user_card_popover

---

web/src/compose_recipient.js
web/src/message_lists.js
web/src/narrow.js
web/src/narrow_state.js
web/src/views_util.js
web/tests/narrow_activate.test.js
web/tests/recent_view.test.js

(38, 11) → (35, 10). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1657831).

views_util: Cut import of narrow

---

web/src/hashchange.js
web/src/message_viewport.js
web/src/navbar_alerts.js
web/src/navigate.js
web/src/recent_view_ui.js
web/src/resize.js
web/src/resize_handler.js
web/src/ui_init.js
web/src/views_util.js

(38, 11) → (36, 10).
- recent_view_ui → {left_sidebar_navigation_area, sidebar_ui, views_util} → resize ↛ navbar_alerts → unread_ops → recent_view_ui
- recent_view_ui ↛ unread_ops → recent_view_ui
- recent_view_ui → views_util ↛ navigate → unread_ops → recent_view_ui

Cut recent_view_ui → unread_ops import paths

---

web/src/settings.js
web/src/settings_panel_menu.js

settings: Move set_settings_header to settings_panel_menu

---

web/src/compose_reply.js
web/src/hotkey.js
web/src/inbox_ui.js
web/src/recent_view_ui.js
web/styles/inbox.css
web/templates/inbox_view/inbox_list.hbs
web/templates/inbox_view/inbox_row.hbs
web/templates/inbox_view/inbox_stream_header_row.hbs

discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/inbox.20view.20.2322408

Show similar outline around all focusable elements in inbox view.

---

tools/test-js-with-node
web/src/stream_edit.js
web/src/stream_edit_toggler.js
web/src/stream_ui_updates.js

(25, 5) → (17, 4). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1659060).

stream_edit: Extract toggler to new stream_edit_toggler module

---

web/src/settings_notifications.js
web/src/settings_org.js

(27, 6) → (26, 5). Discussion: https://github.com/zulip/zulip/pull/27131#issuecomment-1754077589.

settings_org: Cut import of settings_realm_user_settings_defaults

---

.eslintrc.json
tools/test-js-with-node
web/src/compose_setup.js
web/src/stream_create.js
web/src/stream_edit.js
web/src/stream_popover.js
web/src/stream_settings_components.js
web/src/stream_settings_ui.js

(11, 2) → (0, 0). [Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/simple.20import.20cycles/near/1659066).

Extract stream_settings_components module; enable import/no-cycle rule

---

zerver/views/sentry.py

See also #26229.
<details>
</details>

Drop failures to submit client-side Sentry errors, and circuit-breaker them

---

web/src/settings.js
web/templates/settings/account_settings.hbs

[CZO Discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/typing.20notifications.20for.20stream.20messages/near/1659938)
This PR removes the `page_params.development_environment` guard for the setting `send_stream_typing_notifications` and makes it available outside the development environment.
---
---
<details>
</details>

stream_typing_indicator: Remove the dev environment guard in settings.

---

web/src/settings.js
web/src/settings_bots.js
web/src/settings_emoji.ts
web/src/user_events.js
web/templates/settings/bot_list_admin.hbs
web/templates/settings_overlay.hbs

- First commit is to update tooltip for lock icon on "Custom emoji" panel.
- Second commit is to update the tooltips on lock icons to use tippy tooltips.
- Third commit is to live-update lock icon on changing role.
- Fourth commit is to live-update lock icon when "Who can add custom emoji" setting changes.
- Fifth commit is to live-update text on admins bot list page.
- Sixth commit is to live-update lock icon when "Who can add bots" setting changes.
Fixes #24393.
<details> …

Fix live update of lock icon in settings sidebar.

---

web/templates/edited_notice.hbs

This PR adds a period `.`  after the last edited/moved notice which appears in the tooltips.
See https://github.com/zulip/zulip/issues/26581#issuecomment-1742395614
<details>
</details>

tooltips: Add period (.) to last edited/moved notice.

---

templates/zerver/app/index.html
tools/check-templates
tools/lib/template_parser.py
tools/test-js-with-node
tools/tests/test_pretty_print.py
tools/tests/test_template_parser.py
web/src/narrow.js
web/src/scheduled_messages_feed_ui.js
web/src/server_events_dispatch.js
web/styles/scheduled_messages.css
web/templates/scheduled_messages_indicator.hbs
web/tests/dispatch.test.js

These changes adds a new scheduled message indicator in conversation views which informs the user of the number of messages that are scheduled to be sent to the current view. This indicator is also filtered to exclude messages that has been failed to be sent to provide an more accurate indicator of scheduled messages to be sent.
Fixes: #25584.
<details>
</details>

scheduled_message: Indicate scheduled messages in conversation views.

---

tools/test-js-with-node
web/src/compose.js
web/src/compose_actions.js
web/src/compose_setup.js
web/src/compose_state.js
web/src/compose_validate.js
web/src/drafts_overlay_ui.js
web/src/pill_typeahead.js
web/src/stream_bar.js
web/tests/compose.test.js
web/tests/compose_actions.test.js
web/tests/compose_ui.test.js
web/tests/stream_data.test.js
web/tests/typeahead_helper.test.js

Following up on https://github.com/zulip/zulip/pull/26817#discussion_r1336213300

stream_id: Replace empty string with undefined.

---

analytics/tests/test_support_views.py

[Discussion](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/Flaky.20backend.20test/near/1661261).

test_support_views: Move incorrectly class-scoped code inside method

---

web/e2e-tests/mention.test.ts
web/src/composebox_typeahead.js
web/styles/zulip.css
web/tests/composebox_typeahead.test.js
web/third/bootstrap-typeahead/typeahead.js

With the autocomplete dropdown, some users face trouble or uncertainty while selecting topics. These changes adds a new
indicator to the topic typeahead dropdown while typing to the topic box. This ensures users that they are on track and they are doing the right things. We also suggest the current query even if it doesn't match a topic to continue providing the new indicator.
Fixes: #23296.
<details>
</details>

compose_typeahead: Add new indicator to topic items in typeahead.

---

web/src/add_subscribers_pill.js
web/src/stream_create_subscribers.js

stream_edit: Disable add button when input field is empty.

---

docs/translating/french.md

Prompted by mentioning it in chat:
https://chat.zulip.org/#narrow/stream/58-translation/topic/French.20translations/near/1662320
<details>
</details>

docs: Document stream `#translation/fr`.

---

CONTRIBUTING.md

This question comes up, especially during the Outreachy/GSoC application periods. Please free to tweak when merging.

contributor docs: Explain what to do if issue assignee is unresponsive.

---

web/e2e-tests/lib/common.ts

[Discussion](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/main.20failing/near/1663362).

e2e-tests: Fix stack traces from Puppeteer page errors

---

analytics/tests/test_stats_views.py
analytics/urls.py
analytics/views/stats.py

Fixes part of #19653.
We currently do not have the support in our API to fetch the count of messages in a particular
stream based on stream_id. This commit adds support for the same. This can later be used to
show a dropdown on /stats to show the data for the same as described in #19653.
<details>
</details>

stats: Add fetch data from StreamCount based on stream_id.

---

templates/zerver/app/index.html
web/src/info_overlay.js
web/src/ui_init.js
web/styles/app_components.css
web/styles/dark_theme.css
web/styles/informational_overlays.css
web/styles/modal.css
web/styles/subscriptions.css
web/styles/zulip.css
web/templates/about_zulip.hbs
web/templates/draft_table_body.hbs
web/templates/keyboard_shortcuts.hbs
web/templates/markdown_help.hbs
web/templates/scheduled_messages_overlay.hbs
web/templates/search_operators.hbs
web/templates/settings_overlay.hbs
web/templates/stream_settings/stream_creation_form.hbs
web/templates/stream_settings/stream_settings_overlay.hbs
web/templates/user_group_settings/user_group_creation_form.hbs
web/templates/user_group_settings/user_group_settings_overlay.hbs

- First commit is to rename `modal-footer` class.
- Second commit is to rename `modal-body` class.
- Third commit is to rename `modal-bg` class.
- Fourth commit is to rename CSS variables for heights in subscriptions overlay.
Fixes:  https://chat.zulip.org/#narrow/stream/6-frontend/topic/renaming.20modal-*.20classes
<details>
</details>

Rename `modal-*` classes to better names.

---

web/src/user_profile.js
web/styles/app_components.css
web/styles/inbox.css
web/styles/popovers.css
web/styles/recent_view.css
web/styles/right_sidebar.css
web/templates/empty_list_widget_for_list.hbs
web/templates/empty_list_widget_for_table.hbs
web/templates/inbox_view/inbox_list.hbs
web/templates/inbox_view/inbox_view.hbs

Image for reference of inbox row width.

inbox: Use new style to show empty inbox text.

---

web/src/message_fetch.js
web/src/recent_view_data.ts
web/src/recent_view_ui.js

It is hard to verify this on localhost. So, I couldn't verify if they actually work but they should.

Recent view displays non-contiguous conversations

---

api_docs/changelog.md
version.py
zerver/actions/message_send.py
zerver/actions/scheduled_messages.py
zerver/lib/message.py
zerver/lib/onboarding.py
zerver/lib/test_classes.py
zerver/openapi/zulip.yaml
zerver/tests/test_message_send.py
zerver/views/message_send.py
zilencer/management/commands/add_mock_conversation.py

[CZO Discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/.2326900.20compose.20banner.20on.20automatic.20follow.2Funmute/near/1655888)
In the success response of [/api/send-message](https://zulip.com/api/send-message), added an optional `enum` parameter `automatic_new_visibility_policy`.
Prep PR for #26900 
---
<details><summary>/api/send-message</summary>
</img>
</details> 
<details><summary>Changelog</summary>
</img>
</details> 
---
<details> …

send_message: Add an optional parameter in the success response.

---

api_docs/changelog.md
help/all-messages.md
help/configure-default-new-user-settings.md
help/configure-home-view.md
help/inbox.md
help/include/all-messages.md
help/include/sidebar_index.md
help/keyboard-shortcuts.md
help/recent-conversations.md
web/src/settings_config.ts
web/templates/keyboard_shortcuts.hbs
web/templates/settings/display_settings.hbs
zerver/lib/url_redirects.py
zerver/openapi/zulip.yaml

This PR renames "default" views to "home" views in the setting labels, keyboard shortcuts list, help documentation and its urls.
This PR does not do changes in variable and class names, setting field in database, API docs and changelog.
Fixes part of #27251.
<details>
</details>

settings: Rename "default" views to "home" views in settings and docs.

---

web/src/stream_data.ts
web/src/user_profile.js
web/tests/stream_data.test.js

- First commit is to remove unnecessary code.
- Second commit is to show the subscription widget in user's own profile when user is not allowed to subscribe others.
- Third commit is to show subscription widget for other users' profile when user is allowed to subscribe others.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/Stream.20filtering/near/1663509
<details>
</details>

Fix subscription widget in user profile modal.

---

web/templates/compose_banner/automatic_new_visibility_policy_banner.hbs

follow-up: [#27229 (comment)](https://github.com/zulip/zulip/pull/27229#discussion_r1365875436)
<details>
</details>

compose_banner: Fix the incorrect translation tags.

---

web/styles/zulip.css
web/templates/empty_feed_notice.hbs
web/tests/narrow.test.js

| after | before |
| --- | --- |
| <img width="1336" alt="Screenshot 2023-10-20 at 5 11 40 PM" src="https://github.com/zulip/zulip/assets/25124304/b3974792-86b0-40c3-8eb8-a82ab716421f"> |  <img width="1336" alt="Screenshot 2023-10-20 at 5 16 35 PM" src="https://github.com/zulip/zulip/assets/25124304/7893caee-fad8-4805-b426-bf9c88bfaff6"> |
| <img width="1336" alt="Screenshot 2023-10-20 at 5 12 02 PM" src="https://github.com/zulip/zulip/assets/25124304/3971e8e6-c702-4813-b0c6-59e1e3f04055"> |  <img width="1336" alt="Screenshot 2023-10-20 at 5 16 20 PM" src="https://github.com/zulip/zulip/assets/25124304/b23faac4-a80e-49e9-a4b9-a30bca320e53"> |
| <img width="1336" alt="Screenshot 2023-10-20 at 5 12 57 PM" src="https://github.com/zulip/zulip/assets/25124304/a45dfe29-90ea-47b2-bda1-7fdf1779b36 …

empty_feed_notice: Style empty message feed similar to other views.

---

help/include/trying-out-zulip.md

Current:
- https://zulip.com/help/trying-out-zulip
- https://zulip.com/help/getting-your-organization-started-with-zulip#trying-out-zulip
Updated:
Testing:
- I tested all the new links.

help: Expand guide on trying out Zulip.

---

web/src/inbox_ui.js
web/src/message_list_view.js
web/src/popover_menus_data.js
web/src/recent_view_ui.js
web/src/settings.js
web/src/settings_user_topics.js
web/templates/inbox_view/inbox_row.hbs
web/templates/recent_view_row.hbs
web/templates/recipient_row.hbs
web/templates/settings/notification_settings.hbs
web/templates/topic_sidebar_actions.hbs
web/templates/user_topic_ui_row.hbs
web/tests/recent_view.test.js

Changes visible on CZO:
* Follow a topic from the left sidebar three-dot menu.
* Follow a topic from the message header.
* Follow a topic from the recent conversations UI.
* A "Followed Topics" row in the "Notification Triggers" table.
* Followed Topics visible in the 'SETTINGS / TOPICS' panel.
Get notifications for messages in "Followed Topics" as per the notification settings in the "Notification Triggers" table.
This should be deployed on chat.zulip.org branch.
<details> …

follow_topics: Remove the 'development' guard.

---

tools/check-schemas
zerver/openapi/openapi.py
zerver/openapi/zulip.yaml

I’m not going to ask someone to explain this. Just…make it go away.

openapi: Remove fix_events

---

tools/test-js-with-node
web/shared/src/poll_data.ts
web/src/keydown_util.ts
web/src/poll_widget.js
web/src/poll_widget.ts

ts: Migrate `poll_widget.js` to TypeScript.
Added type annotations.
poll_data: Define outbound data types for each message type.
This commit introduces specific outbound data types for each
message type for reusability. For example, `poll_widget.ts` reuses
these types.
keydown_util: Extend event type for `is_enter_event` function.
To accommodate both keydown and keyup events, this commit updates
the function signature to accept both `JQuery.KeyDownEvent` and
`JQuery.KeyUpEvent` types. An example of using keyup event is in
`poll_widget.ts`.
poll_widget: Use `.prop()` but not `.attr()` for button disabled state.
This commit sets the "disabled" property of buttons using `.prop()`
method instead of `.attr()`. The `.prop()` method satisfies type
check requirements for boolean properties like …

 ts: Migrate `poll_widget.js` to TypeScript.

---

web/src/keydown_util.ts
web/src/poll_widget.ts

Cc @N-Shar-ma, @jychen630 (#27317)

poll_widgets: Fix types used for jQuery .val()

---

web/src/tippyjs.js
web/templates/left_sidebar.hbs
web/templates/tooltip_templates.hbs

Fixes: #27325.
<details>
</details>

left_sidebar: Add "This is your home view." to the home view's tooltip.

---

zerver/openapi/zulip.yaml

Document that the `unread_message_ids` lists in the various unread message data structures in `unread_msgs` are sorted in ascending order.
See [CZO discussion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/register.3A.20.60unread_message_ids.60.20sorted.3F/near/1647932).
@chrisbobbe - Would you be up for reviewing these updates?
<details>
<summary>Updated section of register response - with unread_message_ids highlighted</summary>
[Current documentation](https://zulip.com/api/register-queue) - search for "unread_message_ids" on page.
</details>
---
<details> …

api-docs: Note that unread_message_ids are sorted in unread_msgs data.

---

web/src/unread.js
web/src/unread_ui.js
web/styles/search.css
web/styles/zulip.css
web/templates/navbar.hbs

discussioN: https://chat.zulip.org/#narrow/stream/101-design/topic/unread.20counts.20in.20top.20bar

navbar: Remove userlist unread count.

---

web/styles/left_sidebar.css

This fixes a regression where positioning context was accidentally dropped from the condensed navigation items under certain circumstances (e.g., navigating away from a non-Inbox view). A comment helps ensure this is better understood and preserved in the future.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/inbox.20unread.20dot.20only.20present.20in.20view/near/1668976)
Unread dots are now present on the condensed-view row, regardless of the active narrow or view:
<details> …

left_sidebar: Restore and note positioning context for unread dots.

---

web/styles/left_sidebar.css

Topic and navigation labels were missing a 3px padding to keep them from colliding with unreads or other markers. Those are added here.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/unread.20marker.20space.20in.20sidebar/near/1668344)
Note well the "Invalid HTTP DELETE requests" topic in the before & after screenshots.
| --- | --- |
| <img width="275" alt="lsb-marker-spacing-before" src="https://github.com/zulip/zulip/assets/170719/709d00f7-2937-44b6-b653-766c6f1a8a75"> | <img width="275" alt="lsb-marker-spacing-after" src="https://github.com/zulip/zulip/assets/170719/e079adcd-1d19-480c-91db-9263571bdc30"> |
<details> …

left_sidebar: Include right-hand padding on topic, nav labels.

---

web/src/popover_menus_data.js
web/src/user_card_popover.js
web/styles/popovers.css
web/templates/personal_menu.hbs
web/templates/popovers/user_card/user_card_popover.hbs

Show placeholder in personal menu when no status text is set

---

analytics/management/commands/update_analytics_counts.py
zerver/lib/remote_server.py
zerver/tests/test_push_notifications.py

Quick, tiny tweaks, explained in the commit messages.

analytics: Rename send_analytics_to_remote_server and fix a comment

---

help/keyboard-shortcuts.md
web/styles/right_sidebar.css
web/templates/right_sidebar.hbs
web/templates/tooltip_templates.hbs

Discussion: [CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/drop.20keyboard.20shortcuts.20button.3F)
Fixes: #27381
- Right Sidebar Icon removed.
- Reference from help/keyboard-shortcuts removed.
<details>
</details>

right_sidebar: Drop keyboard shortcuts button from right sidebar.

---

analytics/views/installation_activity.py

Use analytics_realmcount to improve query runtime. There are two known difference with previous query:
- Messages that are deleted after hourly stats are aggregated are not decremented in new query.
- Messages sent since the hourly aggregation last ran are not counted.
@timabbott and I did some investigation, and believe that the two points above account for all the differences between the new vs. old query results.

analytics: Replace get_realm_day_counts with a faster query.

---

web/src/user_profile.js
web/styles/dark_theme.css
web/styles/modal.css
web/styles/popovers.css
web/templates/user_profile_modal.hbs

Fixes: #26861
This PR adds deactivated indicator in user-profile header if the user is deactivated.
https://github.com/zulip/zulip/assets/119798962/b220e8c8-3ace-4363-a196-5cb2439dc99a
<details>
</details>

user_profile: Add deactivated user indicator in the profile header.

---

web/src/left_sidebar_navigation_area.js

This fixes an issue where the left sidebar was not properly resized immediately upon toggling between expanded and condensed views.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/left.20sidebar.20cut.20off/near/1670313)
| Expanded to condensed, before | Expanded to condensed, after |
| --- | --- |
| ![expanded-to-condensed-before](https://github.com/zulip/zulip/assets/170719/fce58b99-480a-41d5-a87f-192445fc85d9) | ![expanded-to-condensed-after](https://github.com/zulip/zulip/assets/170719/8ef141b2-9828-4cbd-99aa-165661f5367b) |
| Condensed to expanded, before | Condensed to expanded, after |
| --- | --- |
| ![condensed-to-expanded-before](https://github.com/zulip/zulip/assets/170719/6c3b80a5-6c21-42d4-a15b-251cc334314d) | …

left_sidebar: Resize scroll container when toggling condensed views.

---

web/src/user_status.ts

Cc @Lalit3716 (https://github.com/zulip/zulip/pull/26776)

user_status: Use unknown, not object, for unvalidated type

---

puppet/zulip/manifests/common.pp

Fixes wrong checksum from #27440.
<details>
</details>

puppet: Fix SHA256sum of sentry-cli binary.

---

web/src/recent_view_data.ts
web/src/recent_view_ui.js
web/tests/recent_view.test.js

From a comment: https://github.com/zulip/zulip/pull/26409#issuecomment-1780253167

recent view: Import module instead of separate functions.

---

web/src/message_fetch.js

See also 69e10b4dae6dd6c5e7387305e96a183a9d856771.
<details>
</details>

message_fetch: opts.msg_list can be undefined.

---

analytics/views/installation_activity.py
templates/analytics/activity.html
templates/analytics/realm_summary_table.html

Follow-up to #27411. Use `templates/analytics/activity_details_template.html` for main installation activity page.
**Notes**:
- Changes to `templates/analytics/activity.html` (from PR noted above) are undone. And with these changes, this template is now only used for views that still have bootstrap tabs: realm_activity and user_activity.
- Fixes capitalization of title ("Installation activity") of the main installation activity page.
- https://github.com/zulip/zulip/pull/27411#issuecomment-1783360854 suggested creating a new template (`installation_activity.html`), which could be preferred to the reuse of the newer `activity_details_template.html` in this PR. The template used in this PR was created when the `activity/remote` and `activity/integrations` pages were split from the main …

analytics: Use `activity_details_template.html` for installation activity page.

---

tools/test-js-with-node
web/src/people.ts
web/src/user_sort.ts

Migrates:  `user_sort.js` to TypeScript.
<details>
</details>

ts: Migrate ‘user_sort.js’ to TypeScript.

---

templates/zerver/portico.html
zerver/context_processors.py
zerver/tests/test_i18n.py

portico: Skip footer and adjust header on invalid realm.

---

analytics/views/activity_common.py

Instead of making a database query for each realm, use `realm_str` to generate the URL.
<details>
</details>

analytics: Use `realm_str` to generate per realm URL.

---

zerver/views/sentry.py

sentry: Circuit-break on 429s and 500s from Sentry.

---

tools/test-backend

`test-backend StripeTest` now works.

test-backend: Fix testing via shortcuts outside zerver/.

---

web/src/sidebar_ui.js
web/src/ui_init.js

from this comment: https://github.com/zulip/zulip/pull/26717#discussion_r1378224179

sidebar_ui: Move initializing functions to module file.

---

web/src/user_card_popover.js

Fixes #27459
discussioN: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.93.82.20bug.20when.20reactivating.20user.20via.20user.20card

user_card_popover: Fix reactivate user button not working.

---

web/src/list_widget.ts
web/src/recent_view_ui.js

Fixes #27365
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/recent.20topics.20load.20more.20messages/near/1664315

Fix "Load more" banner flashing in Recent conversations

---

zerver/lib/mention.py

Previously, cross realm bots were not displayed as mention Pills.
This is because, the data set for validating mentions considers only the realm id which is None in case of cross realm bots.
Hence, adding an ```or``` Q object to it, to also check if the email is a part of the cross realm bots email, in case the realm id returns None.
Fixes:  #26913 Display mentions of cross realm bots as mention pills
<details> …

mention_dataset: Add query to mention cross realm bots as pill.

---

help/mobile-notifications.md

Current page: https://zulip.com/help/mobile-notifications
Updated:

help: Add instructions to check whether push notifications are configured.

---

zilencer/management/commands/populate_billing_realms.py

Having a `next_invoice_date` for the `CustomerPlan` is expected for the support view of the organization.
<details>
<summary>support view for standard-automatic-card after changes</summary>
</details>
---
<details>
</details>

populate_billing_realms: Add next_invoice_date to CustomerPlans.

---

web/src/recent_view_ui.js

discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Recent.20conversations.20not.20loading

Handle topics_widget being undefined.

---

analytics/tests/test_support_views.py
analytics/views/support.py
corporate/lib/stripe.py
corporate/lib/stripe_event_handler.py
corporate/lib/support.py
corporate/tests/test_stripe.py
corporate/views/upgrade.py
zilencer/management/commands/populate_billing_realms.py

**1st commit**: Refactors `update_or_create_stripe_customer` to use a wrapper class, `BillableUser`, around the user as prep for being able to pass data that's connected to a `RemoteZulipServer` instead of a `Realm`. No changes to testing coverage.
**2nd commit**: Updates `BillableUser` class and methods for `remote_server` case. Missing test coverage.
---
<details>
</details>

stripe: Refactor billing to use BillingSession abstract base class.

---

web/src/upload.js

Previously, when uploading of a file fails, the same file couldn't be re-uploaded again without re opening the compose box. This is because, the default behaviour of uppy is that it won't allow re-upload of same files.
This could be fixed by removing the uploaded file when the upload-error event is invoked for it.
Fixes: #27495 Allow files that failed to upload to be reuploaded
<details>
</details>

file_upload_error: Fix re-upload of files when upload fails.

---

web/styles/dark_theme.css
web/styles/popovers.css
web/templates/popovers/change_visibility_policy_popover.hbs

This PR improves the CSS of popovers in the `recipient bar`, `recent conversations`, and `Inbox`, which are used to change the visibility policy.
| ![Screenshot from 2023-10-23 15-24-27](https://github.com/zulip/zulip/assets/56781761/404968a2-7de7-44a4-91b4-74bb96a8cc48) | ![Screenshot from 2023-10-23 15-28-42](https://github.com/zulip/zulip/assets/56781761/5499c1c5-993a-412b-b19c-02aa5b22a671) |
| ![Screenshot from 2023-10-23 15-23-04](https://github.com/zulip/zulip/assets/56781761/97f244db-a39d-4c56-92f3-c75d2787fe13)| ![Screenshot from 2023-10-23 15-27-35](https://github.com/zulip/zulip/assets/56781761/121a660f-de3b-45ae-aa16-329a5b30284b) |
---
<details> …

css: Improve the css of popover used to change visibility policy.

---

web/src/left_sidebar_navigation_area_popovers.js
web/src/stream_popover.js
web/src/topic_popover.js
web/src/ui_util.ts
web/styles/left_sidebar.css

Show left sidebar ellipsis icon while popover for the row is visible.

---

docs/translating/german.md

This PR includes changes to update the German translation style guide to reflect [the decision on gender-inclusive language on CZO](https://chat.zulip.org/#narrow/stream/58-translation/topic/More.20gender-inclusive.20German.20translation/near/1671887). 
It also removes and updates some outdated information, such as integrating the PM→DM transition. Specifically, it gives motivation for abbreviating „Direktnachricht“ (direct message) as _DM_ as opposed to _DN_ to align with [Slack](https://slack.com/intl/de-de/help/articles/212281468-Direktnachrichten-verstehen) and [X/Twitter](https://help.twitter.com/de/using-x/direct-messages) (no platform known to me uses “DN”).
**Screenshots and screen captures:** N/A
<details> …

docs: Update German style guide: Gender-inclusive language, direct messages, some cleanup

---

web/src/activity_ui.js
web/src/hotkey.js
web/src/stream_list.js
web/src/user_search.js
web/tests/stream_search.test.js

search: Esc always closes filter boxes

---

web/src/popover_menus.js

discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/cannot.20open.20left.20sidebar.20menu.20on.20top.20of.20compose.20box

Fix cannot open left sidebar menu if on top of compose box.

---

api_docs/incoming-webhooks-overview.md
templates/zerver/integrations/include/create-stream.md
templates/zerver/integrations/include/event-filtering-instruction.md
templates/zerver/integrations/include/generate-integration-url.md
templates/zerver/integrations/include/webhook-url.md
zerver/webhooks/github/doc.md

Adds a modified version of the content in `create-bot-construct-url.md` to the API docs Integrations section so that we have that information documented before transitioning the Integrations docs to describe the new web-app interface for generating incoming webhook bot URLs (see #26201).
[Relevant CZO conversation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/bot.20URL.20construction.20docs/near/1652322).
<details>
<summary>New API page on incoming webhook URLs</summary>
</details>
---
<details> …

api-docs: Document incoming webhook URL specification and modal to generate these URLs in web-app.

---

zerver/lib/email_notifications.py
zerver/models.py
zerver/tests/test_message_notification_emails.py

Earlier, email message notifications included prior messages sent to the same topic for context. This is more confusing than helpful for messages that the user is likely to have received notifications for all the prior messages in the conversation already (or read them in the Zulip UI).
Now, we include prior context only when the user is mentioned via personal, group, stream or topic wildcard mention.
Fixes #27479.
<details>
</details>

email_notification: Include prior message context only when mentioned.

---

corporate/tests/test_stripe.py

In `test_downgrade_small_realms_behind_on_payments_as_needed`, a number of test realms are created. Previously, a random number generator was being used to create the realm name/string_id, which made it unlikely that there would be duplicate numbers generated in a test run but didn't guarantee it.
Updates the realm name/string_id generation in the test to use a counter, instead of something like a uuid. This way if the test fails on a particular realm check, it would be easier to debug the test for which realm case failed the test.
Also, the Customer returned by the test's create_realm function was never being used/checked in the test, so removed that extra return value.
Also, includes a second commit replacing `billable_user` variables with `billing_session`, which part of an earlier …

corporate: Fix downgrade small realms test realm generation.

---

zerver/lib/events.py
zerver/lib/types.py
zerver/lib/users.py
zerver/models.py
zerver/tests/test_auth_backends.py
zerver/tests/test_event_system.py
zerver/views/auth.py
zerver/views/users.py

- First commit is to rename `get_raw_user_data`.
- Last two commits are to use TypedDict when returning user data.
Fixes:  https://github.com/zulip/zulip/pull/27544#discussion_r1385832863
<details>
</details>

Refactor code used to get user data from API to use TypedDict for the data returned by different functions.

---

scripts/lib/check_rabbitmq_queue.py

This queue is used to things which definitionally may take longer than a request, so paging after 60s is rather aggressive.  This is especially true because this queue has a very long tail of very slow tasks -- p99 of task time in this queue is 8.5s, while p99.9 is 197s.
Raise the paging threshold to 15 minutes.  While there are semi-user-facing tasks which use this queue (primarily marking messages as read), those being delayed for minutes is already a real possibility if they are stuck behind a large realm export -- and this is not a situation which should necessarily page, since it is not solvable by the administrator.
<details>
Individual …

queue: Increase paging thresholds for deferred_work queue.

---

web/src/dropdown_widget.js
web/src/inbox_ui.js
web/styles/inbox.css
web/styles/zulip.css
web/templates/dropdown_list.hbs
web/templates/dropdown_list_container.hbs
web/templates/inbox_view/inbox_view.hbs

Fixes https://github.com/zulip/zulip/issues/27522
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/followed.20topics.20filter.20in.20Inbox

INBOX: Add a dropdown to filter inbox topics.

---

help/mute-a-stream.md
help/stream-notifications.md

Just a couple of small changes.
https://zulip.com/help/stream-notifications
https://zulip.com/help/mute-a-stream

help: Stream muting and notifications tweaks

---

web/src/activity.ts
web/src/global.d.ts
web/src/presence.ts
web/tests/activity.test.js

Migrates `activity.js` module to TypeScript.
<details>
</details>

ts: Convert `activity.js` module to TypeScript.

---

web/src/invite.ts

The message shown on successful invitation included "User(s)" previously.
This PR updates it to include "User" or "Users" according to the number of users invited.
Fixes:  https://chat.zulip.org/#narrow/stream/58-translation/topic/More.20gender-inclusive.20German.20translation/near/1678636
<details>
</details>

invite: Use ICU plural syntax for invite success message.

---

web/src/left_sidebar_navigation_area.js

This simplifies the click-handler for expanding and collapsing the Views area by naming the two targets--the icon, and the heading--meant to handle expansion or collapse.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/non-functional.20Views.20heading/near/1680873)
<details>
</details>

left_sidebar: Explicitly handle clicks on collapsible Views targets.

---

corporate/lib/stripe.py
corporate/views/upgrade.py

CZO Discussion:
> I think we could move 90% of upgrade to a new shared `BillingSession.do_upgrade` method, accepting all the parameters from upgrade (perhaps via a new dataclass) and returning a data to pass to `json_success` if it succeeds. I think we'd have just the outer try/except block that does logging left inside `corporate/views/upgrade.py`
<details>
</details>

stripe: Add 'do_upgrade' method to the 'BillingSession' class.

---

web/shared/src/typeahead.ts
web/tests/typeahead.test.js

Currently we prioritize (even partial) realm emojis above all, including over perfect matches if the emoji is **not** a realm emoji.
The commit changes this behavior to prioritize perfect matches above all, regardless of emoji category.
close https://github.com/zulip/zulip/issues/27545
before:
after:
I've kept the same code logic as we're close to v8.0 cutoff but the whole `sort_emojis`  seems very greedy, we filter many times over the emoji list. A cleaner version would be to define an order function or at least a key function then order by key, allowing to traverse the list only once.
<details>
Individual …

sort_emojis: Prioritize perfect matches above all

---

web/styles/compose.css

This fixes two issues:
1. It corrects the center alignment of `>` between the stream/DM and topic/recipient boxes.
2. It corrects a goofy little layout shift that could be triggered by typeahead and recipient pill activity.
| --- | --- |
| ![topic-marker-alignment-before](https://github.com/zulip/zulip/assets/170719/e79371f5-1ba2-4f9f-9cfa-bbafce6824de) | ![topic-marker-alignment-after](https://github.com/zulip/zulip/assets/170719/3d932f31-8ee7-48a6-9b33-69cecf85674a) |
<details> …

compose_box: Better align and maintain alignment of topic marker.

---

web/src/linkifiers.ts
web/src/markdown.js
web/tests/linkifiers.test.js
web/tests/markdown.test.js
web/tests/markdown_parse.test.js
web/third/marked/lib/marked.js
zerver/lib/markdown/__init__.py
zerver/tests/test_markdown.py

[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/pasting.20HTML.20into.20compose/near/1681231).
<details>
</details>

Improve re2 whitespace boundaries, and match JS implementation to server-side implementation

---

web/src/compose_validate.js
web/tests/compose_validate.test.js

We refactor the code checking if wildcard mentions are allowed by renaming the pre-existing function `wildcard_mention_allowed` to `wildcard_mention_allowed_in_large_stream`, adding a new function `is_recipient_large_stream` and finally redefining `wildcard_mention_allowed` to combine these two functions.
Fixes: #27248.
<details>
</details>

typeahead: Include wildcard mentions in typeahead for small streams.

---

web/styles/recent_view.css

This modernizes a previous `inline-block` display for icons, and replaces it with flexbox.
Because the space between filter icons and the name of a stream were achieved care of whitespace, 3px of right margin is added here to the icons to maintain that. Future adjustments to that space can be handled more precisely, if needed.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/Recent.20conversations.20muting.20alignment/near/1680047)
| --- | --- |
| ![recent-icon-alignment-before](https://github.com/zulip/zulip/assets/170719/c0c7b8d1-2b36-4a1d-9187-c84d18e2a3d5) | ![recent-icon-alignment-after](https://github.com/zulip/zulip/assets/170719/d0a5f942-23e3-4fd8-8e5a-329b20482a4c) |
<details> …

recent_view: Correct icon alignment within rows.

---

web/styles/compose.css

This fixes a regression where a resized textarea would remain that size when moving into fullscreen mode.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/preview.20mode/near/1682672)
| --- | --- |
| ![Screen Shot 2023-11-15 at 15 12 01](https://github.com/zulip/zulip/assets/170719/ae1f97f5-d732-4499-94da-30c6382e1b97) | ![Screen Shot 2023-11-15 at 15 11 43](https://github.com/zulip/zulip/assets/170719/b4356f9e-4410-42b3-af5c-1bcabbb1846f) |
<details> …

compose_box: Set auto height on textarea in full screen.

---

corporate/lib/stripe.py
corporate/views/upgrade.py
zerver/actions/users.py
zerver/management/commands/change_user_role.py
zerver/tests/test_events.py

Extracted from #27575 to merge as a preparatory PR.

management: Allow changing is_billing_admin using change_user_role.

---

help/configure-home-view.md

Fixes #27655.
- https://zulip.com/help/configure-home-view
<details>
</details>

help: Document changing home view from left sidebar.

---

web/styles/left_sidebar.css

This corrects the layout and alignment of "more conversations" and the DIRECT MESSAGES header when zooming into the more conversations view.
The purple gridlines on the DIRECT MESSAGES header are showing to better gauge alignment. It also includes the All DMs view, to demonstrate that no highlighted area is disturbed by this fix.
| --- | --- |
| ![dm-zoomed-in-before](https://github.com/zulip/zulip/assets/170719/ccf53962-ad62-4c94-a15e-a780beed75ef) | ![dm-zoomed-in-after](https://github.com/zulip/zulip/assets/170719/80350141-3370-430e-a593-20e4707b9370) |
<details> …

left_sidebar: Preserve DM layout when zoomed into more conversations.

---

corporate/lib/stripe.py
corporate/tests/test_stripe.py
corporate/views/billing_page.py

CZO Discussion:
> The goal would be to get at least the block starting with plan = get_current_plan_by_customer(customer) that ends with a context become instead something like:
```
billing_session = RealmBillingSession(user)
main_context = billing_session.get_billing_page_context()
```
> Looking at that big context block, the things that expressly depends on user or realm are:
> * `seat_count = get_latest_seat_count(user.realm)` => equivalent to `self.current_count_for_billed_licenses` on a BillingSession.
> * `renewal_amount` => Calls `make_end_of_cycle_updates_if_needed`. We should just remove that call to make_end_of_cycle_updates_if_needed; 
<details> …

stripe: Add `get_billing_page_context` method to 'BillingSession'.

---

help/follow-a-topic.md

help: Define "participate" for automatically following topics.

---

api_docs/include/rest-endpoints.md

rest-endpoints: Add new /api/get-stream-email-address endpoint.

---

zerver/openapi/zulip.yaml

This allows it to inherit the required `description` field.
<details>
</details>

openapi: Use SuccessDescription in new get-stream-email-address.

---

puppet/zulip_ops/files/statuspage-pusher
puppet/zulip_ops/manifests/profile/prometheus_server.pp
puppet/zulip_ops/manifests/statuspage.pp
puppet/zulip_ops/templates/supervisor/conf.d/statuspage-pusher.conf.template.erb

zulip_ops: Configure stats to be pushed to status.zulip.com.

---

help/mention-a-user-or-group.md

Bug recently introduced in 8264b8cde08563a1fd1ca20a37f38614fa3c098e. (#27738)

help: Fix copy-paste bug in wildcard mention documentation.

---

web/styles/zulip.css

This PR fixes the overflow of long names in tooltips and empty feed title.
Fixes: #27282 
**Before**
**After**
<details>
</details>

style: Fix overflow of text.

---

help/desktop-notifications.md
help/follow-a-topic.md

Current: https://zulip.com/help/desktop-notifications#unread-count-badge
Updated:
Also mention it on /help/follow-a-topic.
Current: https://zulip.com/help/follow-a-topic#configure-notifications-for-followed-topics
Updated:

help: Improve unread count badge documentation.

---

zerver/lib/remote_server.py
zerver/tests/test_push_notifications.py
zilencer/auth.py
zilencer/views.py
zproject/default_settings.py
zproject/dev_settings.py

Preparatory commits extracted from https://github.com/zulip/zulip/pull/27575.

Push bouncer typed endpoint migration

---

web/src/narrow.js

Fixes #27622
If target message ID is valid but the stream name is invalid, we fix the stream name in the URL and narrow the target message.
In the URL specified in the issue: `https://chat.zulip.org/#narrow/stream/9issues/topic/.22All.22.20button.20in.20Recent.20Conversations/near/1675386`
`9issues` here is incorrect but since `stream_data.slug_to_name` considers to be a correct `pre-2018` slug name, we still process it.
In case both stream name and target ID are invalid, we already show a no search results page which seems more appropriate than taking user to the default view.

narrow: Fix `near:ID` narrows with invalid stream name in hash.

---

web/src/padded_widget.ts

Followup to #27807, fixing a bug it will cause without this change.

padded widget: Use padding_selector instead of padding_sel.

---

analytics/lib/counts.py
analytics/management/commands/update_analytics_counts.py
zerver/lib/remote_server.py
zerver/tests/test_push_notifications.py
zproject/computed_settings.py

Spread analytics data POSTs across ten minutes

---

web/styles/popovers.css

The user avatar flowed out of the popover and this PR fixes it by reducing the avatar
width by 2px (i.e. 1px for borders on each side) such that it fits inside its container.
Before -
See at the bottom right corner
After -
<details>
</details>

popovers: Reduce avatar width such that it fits inside its container.

---

web/src/inbox_ui.js
web/src/recent_view_ui.js

views: Set focus back to views after closing compose box.

---

web/src/gear_menu_util.ts
web/templates/gear_menu_popover.hbs

Fixes this issue reported in https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20Padding.20in.20Org.20Info.20section.20of.20the.20gear.20menu/near/1686528.

gear_menu: Fix display of version for forks of betas.

---

web/src/user_card_popover.js

Now, deactivated users will receive silent mentions. I've also changed the .hbs popover to show it.
Fixes: 
https://github.com/zulip/zulip/issues/26858
<details>
- [.] [Self-reviewed](https://zulip.readthedocs.io/en/latest/contributing/code-reviewing.html#how-to-review-code) the changes for clarity and maintainability
</details>

popovers: Insert silent mentions for deactivated users.

---

zilencer/migrations/0037_alter_remoteinstallationcount_unique_together_and_more.py

This removes a window where more violations could enter, and also a period where indexes which may be useful are lacking.
<details>
</details>

migrations: Keep the existing constraints until the new ones are made.

---

corporate/lib/stripe.py
corporate/views/upgrade.py
web/src/billing/page_params.ts
web/src/billing/upgrade.ts

This PR updates the `get_initial_upgrade_context` method to use `get_price_per_license` for determining `annual_price and `monthly_price` based on tier and discount instead of hardcoding.
Also, removed the `percent_off` page_params as `get_price_per_license` already performs the price calculation taking discount into consideration.
<details>
</details>

stripe: Use 'get_price_per_license' in 'get_initial_upgrade_context'.

---

zerver/webhooks/github/fixtures/issues__assigned.json
zerver/webhooks/github/tests.py
zerver/webhooks/github/view.py

See [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/127-integrations/topic/odd.20behaviour.20github.20integration/near/1687129).
Updates the message body content for assigned issues and pull requests to be formatted as:
"user_A assigned user_B to [issue/PR #XXX title here]()."
Previously, if the issue or PR title ended in a value included in `string.punctuation`, then the closing parenthesis for the link would be removed, which broke the link formatting.
Also fixes a bug where all instances of "unassigned" would be replaced in the message body with text that included the assignee's information. Now only the first instance of "unassigned" is replaced, which will be the action/verb in the message body and not the issue title content.
---
<details> …

integrations: Reformat GitHub assigned issue/PR message body.

---

help/change-a-users-name.md
help/change-a-users-role.md
help/deactivate-or-reactivate-a-user.md
help/include/sidebar_index.md
help/manage-a-user.md

Adds a dedicated page to document getting to the user management UI from the user's profile and from Settings / Users.
Fixes #27748.
<details>
</details>

help: Document "Manage a user".

---

web/templates/message_view_header.hbs

In this PR, we update the formatting of the tooltip over the stream name to match other two line tooltips in the app. We also remove the stream privacy icon from the tooltip, as it is already displayed in the message view header.
Fixes: Formatting of the tooltip + remove stream privacy icon.
CZO: [Link](https://chat.zulip.org/#narrow/stream/101-design/topic/stream.20subscribers.20in.20top.20bar/near/1684775)
<details> …

message_view_header: Update tooltip over stream name in top bar. 

---

help/add-a-bot-or-integration.md
help/bots-and-integrations.md
help/generate-integration-url.md
help/include/sidebar_index.md
templates/zerver/integrations/include/generate-integration-url.md

Adds a help center article to document the new modal for generating an integration URL, and links /integrations docs to this article.
Fixes #27744.
- https://zulip.com/integrations/doc/airbrake
<details>
</details>

help: Document modal to generate bot URL.

---

help/generate-integration-url.md

help: Add intro to "Generate URL for an integration" page.

---

zerver/actions/create_realm.py
zerver/lib/home.py
zerver/lib/name_restrictions.py
zerver/lib/remote_server.py
zerver/middleware.py
zerver/tests/test_realm.py
zerver/tests/test_signup.py
zerver/views/upload.py
zilencer/views.py
zproject/default_settings.py
zproject/dev_settings.py

I believe these should all pass CI without further iteration.

Preparatory commits extracted from #27575

---

tools/test-js-with-node
web/src/dropdown_widget.js
web/src/inbox_ui.js
web/src/recent_view_ui.js
web/src/views_util.js
web/styles/inbox.css
web/styles/recent_view.css
web/styles/zulip.css
web/templates/dropdown_list.hbs
web/templates/recent_view_filters.hbs
web/tests/recent_view.test.js

Add dropdown widget to recent topics.

---

web/src/left_sidebar_navigation_area.js

left_sidebar: Preserve views collapsed / expanded state.

---

corporate/tests/test_remote_billing.py
zerver/lib/test_classes.py
zerver/tests/test_push_notifications.py

Adds a file and two basic tests for the end-to-end flow from user perspective.

End-to-end test of the RemoteRealm authentication flow

---

zerver/signals.py
zerver/tests/test_new_users.py

Addresses issue #27727.
Fixes: https://github.com/zulip/zulip/issues/27727
Before Changes:
After Changes:
<details>
- [ ✓ ] [Self-reviewed](https://zulip.readthedocs.io/en/latest/contributing/code-reviewing.html#how-to-review-code) the changes for clarity and maintainability
- [ ✓ ] Explains differences from previous plans (e.g., issue description).
- [ ✓ ] Highlights technical choices and bugs encountered.
- [ ✓ ] Calls out remaining decisions and concerns.
- [ ✓ ] Automated tests verify logic where appropriate.
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-disciplin …

email: Add a space after the time and AM/PM in the login email

---

help/guest-users.md
help/include/sidebar_index.md

Follow-ups:
- @drrosa Could you please put up a PR linking to this page from anywhere that's appropriate?
- Once the limited guests UI has been merged, we will add a section to document it on this page.

help: Add dedicated page about guest users.

---

help/guest-users.md

- Addresses https://github.com/zulip/zulip/pull/27917#issuecomment-1828670935
- Notes a couple more non-configurable permissions.

help: Add more permissions info to Guest users help page.

---

zerver/lib/users.py
zerver/tests/test_users.py
zerver/views/muted_users.py

Previously, we weren't able to mute the system bots. This was because, for muting the users, we mute only those profiles which are in realm, excluding the cross realm profiles.
This is fixed by replacing the ```access_user_by_id``` method in the muted_users file with a new method ```access_user_by_id_including_cross_realm``` to include cross_realm as well.
Fixes: #27823
<details>
</details>

bots: Fix muting of cross realm bots.

---

web/templates/invite_user_modal.hbs

This commit updates label for new user's role dropdown to use "Users" instead
of "User(s)" because that caused some problems in translating the text.
We should ideally be using the ICU plural syntax for such cases, but since it is
used as label, we cannot use the plural syntax there. So we instaed just change
it to always have "Users" plural like we do at some other places in that modal.
<details>
</details>

invite: Fix label for new user's role dropdown.

---

docs/testing/testing-with-django.md

estimation for the number of backend tests has been updated to a close-to-actual value from a far-from-close-to-actual value.

docs: Update testing-with-django.md

---

help/include/sidebar_index.md
help/start-a-call.md

Documents the new audio call option (video call with video muted by default) to the compose box.
Fixes #26895.
- https://zulip.com/help/start-a-call
<details>
</details>

help: Document voice calls option.

---

corporate/lib/stripe.py
corporate/tests/test_stripe.py

Followsup to #27915
https://github.com/zulip/zulip/pull/27915#discussion_r1406768176 and https://github.com/zulip/zulip/pull/27915#discussion_r1406770747 are addressed. Replied to feedback in https://github.com/zulip/zulip/pull/27915#discussion_r1406774376

Followups to Downgrade free trial realms PR.

---

templates/zerver/emails/confirm_registration.html
templates/zerver/emails/confirm_registration.txt
zerver/tests/test_signup.py
zerver/views/registration.py

Adds details about the requested organization URL and type to the registration confirmation email that's sent when creating a new Zulip organization.
Fixes #25899.
<details>
<summary>Update HTML email</summary>
</details>
<details>
<summary>Update text version email</summary>
</details>
---
<details>
</details>

emails: Add organization details to confirm registration for new org.

---

web/styles/left_sidebar.css

Despite the existing comment in the CSS, the previous DM row was 22.5px tall. Adjusting the padding makes for 22px tall box, which greatly improves the centering of the unread count within its bounding box.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/DM.20unread.20counter.20too.20low/near/1690500)
| --- | --- |
| <img width="295" alt="dm-rows-before" src="https://github.com/zulip/zulip/assets/170719/4ab96849-012a-4606-b7e1-14bdb690a243"> | <img width="295" alt="dm-rows-after" src="https://github.com/zulip/zulip/assets/170719/a49a7bfe-cae7-4fd5-96b5-7bbec42b5be8"> |
<details> …

left_sidebar: Establish better-centered DM row height.

---

web/src/popover_menus_data.js
web/templates/gear_menu_popover.hbs

This PR fixes the extra space and additional border that was being added to the gear menu popover when the user did not have permission to invite users.
CZO: [link](https://chat.zulip.org/#narrow/stream/9-issues/topic/extra.20line.20in.20gear.20menu/near/1688450)
| ![image](https://github.com/zulip/zulip/assets/82862779/d78ff50e-4817-4e4d-8fc8-c7948e4e98e5) | ![image](https://github.com/zulip/zulip/assets/82862779/a4cbf76c-abdb-41e7-a971-809c683ae094) | 
<details> …

gear_menu_popover: Fix extra space when no invite permission.

---

zerver/actions/create_realm.py

create_realm: Fix copy/paste error in assertion message.

---

zerver/actions/user_settings.py
zerver/tests/test_email_change.py
zerver/views/user_settings.py

Tighten down email changes

---

zerver/management/commands/register_server.py

register_server: Redact the key when printing it.

---

web/src/presence.ts
web/templates/settings/organization_permissions_admin.hbs
web/tests/presence.test.js
zerver/actions/users.py
zerver/lib/create_user.py
zerver/lib/users.py
zerver/models.py
zerver/tests/test_users.py

- First commit is just a simple refactor in settings page.
- Second commit is to not log for unknown users in presence data.
- Third commit is to add `realm_host` field in `ClientDescriptor`.
- Fourth commit is to update `get_fake_email_domain` to take realm host as arg.
<details>
</details>

Preparatory commits from #27944.

---

.github/workflows/production-suite.yml

We build this image on bookworm, for diversity.
<details>
</details>

ci: Add a test for upgrading from 7.0.

---

web/templates/topic_sidebar_actions.hbs

Fixes:  There is an extra line in the left sidebar topic menu for logged-out users.
CZO Discussion: [Link](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20extra.20line.20in.20logged.20out.20topic.20menu/near/1691642)
- Before
- After
<details>
</details>

topic_sidebar_actions: Remove extra line in spectators view.

---

web/src/dropdown_widget.js
web/src/recent_view_ui.js
web/styles/recent_view.css
web/templates/recent_view_row.hbs
web/templates/recent_view_table.hbs
web/tests/recent_view.test.js

discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20unread.20column.20in.20Recent.20conversation.20.28logged.20out.20view.29

Recent conversation minor bug fixes.

---

zerver/lib/markdown/tabbed_sections.py

Small prep commit for convenience.

help: Add tab for Zulip 8.0+ features.

---

version.py

This should have been updated in 56ec1c2.
<details>
</details>

version: Fix incorrect API_FEATURE_LEVEL.

---

help/zulip-cloud-billing.md

Current page not deployed yet. (https://chat.zulip.org/help/zulip-cloud-billing)

help: Document license management and downgrades.

---

corporate/lib/stripe.py
corporate/tests/test_stripe.py

Moves `invoice_plan` to the `BillingSession` abstract class. Updates error message for a customer on a paid plan without a stripe customer ID to be more general.
Also, updates `do_change_plan_to_new_tier` to use an enum for the value returned when checking for a valid change between two plan tier types. This makes it more explicit that the implementation for a valid upgrade in plan tier will be different from a valid downgrade in plan tier.
---
<details> …

corporate: Move invoice_plan to BillingSession.

---

web/src/upload.js

Previously, dragging an image and dropping it in on itself led to the image being re-uploaded, which is probably not the intent of a user. This PR prevents this reuploading of the same image by explicitly checking if the image is being dragged onto itself, and then rejecting this action.
CZO discussion: [Link](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20accidentally.20dragging.20images)
<details> …

upload: Prevent drag-and-drop of an image onto itself.

---

zerver/actions/users.py

users: Fetch and lock the user row before updating its role.

---

templates/corporate/for/business.html
templates/corporate/legacy_pricing_model.html
templates/corporate/plans.html
templates/corporate/pricing_model.html
web/src/portico/landing-page.js
web/styles/portico/hello.css
web/webpack.assets.json
zerver/tests/test_docs.py

This is PR for placing [the redesigned plans page](https://terpimost.github.io/zulip-plans/#cloud). 
Here are screenshots implementing the fixes noted below as of 2023-12-01:
| Zulip Cloud | Self-hosted |
| --- | --- |
| ![zulip-cloud-fixes](https://github.com/zulip/zulip/assets/170719/5c66d863-95f0-4b0c-9176-6cac8cec4d43) | ![self-hosted-fixes](https://github.com/zulip/zulip/assets/170719/eb73ee74-9ea6-4ca2-bc56-05fd3bc79fe9) |
Here is a screenshot of its responsive state as of 2023-11-30:
Some things remain to be finished and polished, including:
Some things to handle probably as follow-up PRs
<details> …

portico: Add redesigned Plans page.

---

analytics/views/remote_activity.py

Updates query to count the distinct pairs of `user_id` and `user_uuid` on the `RemotePushDeviceToken` table.
---
<details>
</details>

analytics: Update query for remote_push_devices in remote activity.

---

corporate/lib/stripe.py
corporate/models.py
corporate/tests/test_remote_billing.py
corporate/tests/test_stripe.py
corporate/urls.py
corporate/views/billing_page.py
corporate/views/upgrade.py
templates/corporate/billing.html
templates/corporate/upgrade.html
web/src/billing/billing.ts
web/src/billing/upgrade.ts
web/styles/portico/billing.css
zilencer/management/commands/add_server_to_legacy_plan.py
zilencer/management/commands/populate_billing_realms.py

Show tier information correctly on billing and upgrade page.

---

web/templates/compose_control_buttons.hbs

We exchange the positions of the preview and upload buttons to make the preview button the first one, as the preview button is different from the other buttons in that it does not manipulate the contents of the ompose box.
Fixes: [CZO message](https://chat.zulip.org/#narrow/stream/101-design/topic/UI.20redesign.3A.20compose.20icons/near/1694187)
<details>
</details>

compose: Make the Preview button the first, and Upload files the second.

---

web/src/popover_menus.js

So far, we were only considering elements at the the reference element's bounding box top-left corner, to check if the reference element was covered by other elements. This led to a bug where the popover wouldn't show up even if a very small part of the reference element was covered.
Now we consider elements that are at both the top-left and bottom-right of the reference element's bounding box, as those covering the reference element.
Fixes: [CZO message](https://chat.zulip.org/#narrow/stream/9-issues/topic/clicking.20half.20obscured.20message.20actions.20menu.20button/near/1695023)
Now popover is visible even if the button is partially covered by the sticky header
<details> …

popover: Improve computation of elements at reference elements.

---

web/src/hotspots.js
zerver/lib/hotspots.py

Fixes: #27878.
- Before
- After
- Screencast
<details>
</details>

hotspots: Fix misplaced onboarding hotspots.

---

corporate/lib/stripe.py
corporate/lib/stripe_event_handler.py
corporate/models.py
corporate/tests/test_remote_billing.py
corporate/urls.py
corporate/views/billing_page.py
corporate/views/portico.py
corporate/views/remote_billing_page.py
corporate/views/sponsorship.py
templates/corporate/plans.html
templates/corporate/pricing_model.html
templates/corporate/sponsorship.html
web/src/billing/sponsorship.ts
web/src/portico/landing-page.js
web/styles/portico/pricing_plans.css
zerver/tests/test_docs.py
zilencer/management/commands/populate_billing_realms.py

Run `./manage.py register_server` if not done already.
Run `./manage.py populate_billing_realms` to see plans for different remote servers  and realms.
```shell
----------------------------------------
unique_id: legacy-server
server_uuid: 2c1e6cda-329a-4995-8803-ddfed7af382c
api_key: 2c1e6cda-329a-4995-8803-ddfed7af382c
----------------------------------------
unique_id: legacy-server-upgrade-scheduled
server_uuid: e5b7c4b4-98d6-4626-9c2f-16ee5f458d68
api_key: e5b7c4b4-98d6-4626-9c2f-16ee5f458d68
----------------------------------------
unique_id: business-server
server_uuid: afa903ac-89a8-4790-a2ec-70c4a4561a3b
api_key: afa903ac-89a8-4790-a2ec-70c4a4561a3b
----------------------------------------
unique_id: business-server-free-trial
server_uuid: 0a2dbce8-4e7d-4242-baf3-f4142d2947a5 …
```

Show plans button correctly for different realm types.

---

puppet/zulip/files/nginx/zulip-include-common/tornado_cors_headers
puppet/zulip/files/nginx/zulip-include-frontend/app
zerver/tornado/event_queue.py
zerver/tornado/handlers.py

Limit Tornado request methods, close memory leak

---

zerver/tests/test_push_notifications.py
zilencer/views.py

I expect we would ignore extra events anyway, but this just makes it
easier to reason about how the system works.

zilencer: Only accept SYNCED_BILLING_EVENTS.

---

help/change-the-color-of-a-stream.md
help/include/how-to-create-a-user-group.md
help/message-a-stream-by-email.md
help/mute-a-stream.md
help/pin-a-stream.md
help/unsubscribe-from-a-stream.md
zerver/lib/markdown/help_relative_links.py
zerver/tests/test_docs.py

- Documents new gear menu icons.
- https://chat.zulip.org/help/review-your-organization-settings
- https://chat.zulip.org/help/review-your-settings
- https://chat.zulip.org/help/analytics
-  https://chat.zulip.org/help/browse-and-subscribe-to-streams
-  https://zulip.com/help/browse-and-subscribe-to-streams
-  https://chat.zulip.org/help/unsubscribe-from-a-stream
-  https://zulip.com/help/unsubscribe-from-a-stream
-  https://chat.zulip.org/help/user-groups
-  https://zulip.com/help/user-groups
<details>
Completed …

help: Update gear menu icons.

---

tools/run-dev
zerver/management/commands/runtornado.py
zerver/tornado/application.py

- https://github.com/tornadoweb/tornado/pull/3302
- https://chat.zulip.org/#narrow/stream/49-development-help/topic/run-dev.20requiring.20Ctrl.2BC.20twice.20to.20exit/near/1698891

tornado: Fix autoreload for Tornado 6.4 changes

---

static/images/unknown-user-avatar-medium.png
zerver/actions/message_edit.py
zerver/actions/message_send.py
zerver/lib/email_mirror.py
zerver/lib/markdown/__init__.py
zerver/lib/mention.py
zerver/lib/message.py
zerver/lib/users.py
zerver/tests/test_events.py
zerver/tests/test_markdown.py
zerver/tests/test_message_dict.py
zerver/tests/test_message_edit.py
zerver/tests/test_message_fetch.py
zerver/tests/test_message_send.py
zerver/tests/test_notification_data.py
zerver/tests/test_users.py
zerver/tornado/event_queue.py
zerver/views/message_edit.py
zerver/views/message_fetch.py

- First two commits are preparatory refactors.
- Next commit is to not send sender's original details in push notifications.
- Next commit is to not send sender's original details in message objects.
- Next commit is to allow restricted user access for guests only on plus plans.
- Next commit is to add client capability.
- Last two commits are to not send unknown users data to webapp and some UI changes.
<details>
</details>

Remaining work for restricted user access feature for guests.

---

web/src/hashchange.js
web/src/user_groups.ts
web/templates/settings/organization_permissions_admin.hbs
web/tests/user_groups.test.js
zerver/tests/test_realm.py
zerver/views/realm.py

- First commit is to fix the bug in user creation reported in #28108.
- Second commit is to enable "#groups" UI in production.
- Third commit is to update label for "can_access_all_users_group" setting.
- Fourth commit is to allow changing "can_access_all_users_group" setting in production.
Fixes:  #28108.
<details>
</details>

Follow-ups for "#groups" UI and user access setting.

---

help/mobile-notifications.md

Getting the PR below merged and out to users is a blocker for deploying this change:
- https://github.com/zulip/zulip-mobile/pull/5799
Current page: https://zulip.com/help/mobile-notifications#testing-mobile-notifications
Updated:

help: Document new UI for testing mobile push notifications.

---

web/src/message_edit.js
web/styles/zulip.css

- First commit is to fix the color of spinner in light theme.
- Second commit is to fix the alignment of spinner.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20save.20message.20edit.20spinner.20color
<details>
</details>

Fix loading spinner shown in "Save" button of message edit form.

---

help/contact-support.md
templates/corporate/development-community.md

Current: https://zulip.com/development-community/#streams-for-everyone
<details>
<summary> Updated</summary>
</details>
Current:
<details>
<summary> Updated</summary>
</details>

Improve CZO stream descriptions and support instructions

---

zerver/tornado/handlers.py

Fix memory leak in Tornado

---

zerver/lib/import_realm.py
zerver/models.py
zerver/tests/test_import_export.py
zerver/tests/test_slack_importer.py

This PR creates a `RealmAuditlog` entry with a new event_type `RealmAuditLog.REALM_IMPORTED` after the realm is reactivated.
It contains user count data (using `realm_user_count_by_role`) stored in `extra_data`.
This helps to have an accurate user count data for the billing system if someone tries to signup just after doing an import.
<details>
</details>

import_realm: Create audit log with user count data.

---

help/create-user-groups.md
help/include/create-a-stream-instructions.md
help/include/how-to-create-a-user-group.md
help/include/sidebar_index.md
help/include/user-groups-intro.md
help/manage-user-groups.md
help/setting-up-zulip-for-a-class.md
help/user-groups.md

This makes some tweaks on top of #28096.

Update user groups documentation

---

corporate/tests/test_remote_billing.py
corporate/views/remote_billing_page.py
templates/corporate/legacy_server_login.html
web/src/billing/remote_billing_auth.ts
web/styles/portico/billing.css

Show better error messages and validate zulip_org_id in JS before sending it to the server and give an appropriate error message.

legacy_server_login: Do better error handling.

---

corporate/lib/stripe.py
zerver/actions/realm_settings.py
zerver/lib/push_notifications.py
zerver/tests/test_events.py
zerver/tests/test_push_notifications.py
zilencer/views.py

https://github.com/zulip/zulip/issues/27483#issuecomment-1841696222

zilencer: Return can_push info at the push/notify endpoint.

---

requirements/dev.in
requirements/dev.txt
tools/run-dev
zerver/tornado/handlers.py

This allows request cancellation to be propagated to the server.

run-dev: Rewrite development proxy with aiohttp

---

zerver/actions/realm_settings.py

This fixes a bug introduced in
6f93ab72c03a1afeb0c93f252b5b6f979706c0d0 where deactivating a realm would fail with an exception that sessions cannot be cleared inside database transactions.

realm_settings: Clear sessions outside transaction.

---

web/templates/personal_menu.hbs

https://chat.zulip.org/#narrow/stream/9-issues/topic/missing.20time.20in.20gear.20menu/near/1701038

personal_menu: Handle undefined user_time

---

analytics/views/remote_activity.py

analytics: Show latest number in "Analytics users", not max.

---

help/contact-support.md

help: Fix “community norms” link

---

corporate/lib/stripe.py
zilencer/views.py

stripe: Implement `sync_license_ledger_if_needed` for `RemoteServerBillingSession`.

---

templates/corporate/billing.html

| --- | --- |
| ![Screen Shot 2023-12-12 at 17 21 54](https://github.com/zulip/zulip/assets/170719/20bbee86-91e1-47bd-a756-fa489394bf11) | ![Screen Shot 2023-12-12 at 17 22 20](https://github.com/zulip/zulip/assets/170719/8fbc5115-d566-45ed-8398-fa19e9f35a47) |

portico: Move billing contact to above payment method.

---

corporate/lib/stripe.py
corporate/views/billing_page.py
corporate/views/upgrade.py
templates/corporate/server_not_uploading_data.html

Adds a template with an error message to be used when the billing or upgrade context for a remote server or remote realm raises a `MissingDataError`.
**Notes**:
- Tests can be added when `current_count_for_billed_licenses` is implemented for the remote billing sessions.
- Can be manually tested by updating one of those functions to raise the specified error.
- Template strings are currently not marked for translation.
---
<details> …

corporate: Show error page if mobile push data has not been uploaded.

---

analytics/views/remote_activity.py

remote_activity: Hide deactivated remote servers.

---

web/src/user_card_popover.js
web/src/user_profile.js

We incorrectly passed bot owner ID to get_bot_owner_user instead of the bot object.
<details>
</details>

popover: Fix user popover and profile for bot with inaccessible users.

---

analytics/tests/test_support_views.py
analytics/views/support.py
corporate/lib/support.py
templates/analytics/remote_realm_details.html
templates/analytics/remote_server_support.html
templates/analytics/sponsorship_forms_support.html

Adds the most recent sponsorship request data if the customer associated with the remote realm or server currently has sponsorship_pending = True.
Note that these changes are only currently implemented for remote support views. Non-remote realm support views have not been updated for these changes.
<details>
<summary>Sponsorship pending with no request data</summary>
*This could currently happen if a support admin toggled the sponsorship pending as true.*
</details>
<details>
<summary>Sponsorship pending with request data</summary>
</details>
---
<details> …

support: Add sponsorship request information remote server view.

---

zerver/lib/send_email.py
zerver/management/commands/send_custom_email.py
zerver/tests/test_email_notifications.py

Improve `./manage.py send_custom_emails --remote-servers`

---

zilencer/auth.py

zilencer: Log why the server got a 401.

---

templates/analytics/remote_realm_details.html
templates/analytics/remote_server_support.html

The plan type for the remote realm is useful to compare to any current plan attached to the same remote realm.
<details>
<summary>Updated support view for remote realms</summary>
</details>
---
<details>
</details>

support: Add the remote realm's plan type to the support view.

---

corporate/views/remote_billing_page.py
templates/corporate/remote_realm_login_error_for_server_on_active_plan.html
templates/corporate/remote_server_login_error_for_any_realm_on_active_plan.html

Deny login for remote server/realm. 

---

zerver/management/commands/change_user_role.py

change_user_role: List role choices in --help output

---

corporate/lib/stripe.py

Fixes couple of bugs:
1.
The call to `get_billable_licenses_for_customer` during the `sync_license_ledger_if_needed` step should use the audit_log's `event_time` while calculating `current_count_for_billed_licenses`.
Earlier, it used `timezone_now()`, resulting in the latest user count recorded corresponding to each audit log.
2.
Earlier on creating a user, a row was added in ledger with the same licenses count. The issue was, realmauditlog event_time was somehow greater than timezone_now in `current_count_for_billed_licenses`. resulting in the query discarding the latest audit log.
```
RemoteRealmAuditLog.objects.filter(
remote_realm=remote_realm,
event_type__in=RemoteRealmAuditLog.SYNCED_BILLING_EVENTS,
event_time__lte=event_time,
)
.exclude(extra_data={}).last()
```
This commit fixes …

stripe: Fix `get_billable_licenses_for_customer` not using `event_time`.

---

templates/corporate/billing.html

billing: Don't show current license for legacy plan customers.

---

zerver/lib/push_notifications.py
zerver/tests/test_push_notifications.py

I think this is the right logic but I need someone else to fix the tests and review it for me.

push_notifications: Improve logging when not contacting bouncer.

---

zerver/lib/send_email.py

612f2c73d663 started passing add_context to
`send_custom_server_email`, but did not make it make use of it.
Also add the `hostname` as a built-in value, since that is most likely the most useful property.
Fixes: 
<details>
</details>

send_email: Support add_context for remote servers.

---

templates/corporate/remote_billing_finalize_login_confirmation.html

I manually tested the regular login form, but not the deactivation one.

billing: Don't ask about subscriptions when deactivating registration.

---

zerver/lib/send_email.py

send_email: Send emails to remote servers from BILLING_SUPPORT_EMAIL.

---

version.py

version: Update to point to 8.0 blog post.

---

corporate/views/remote_billing_page.py

remote_billing_page: Allow deactivation logins with realm plans.

---

corporate/views/portico.py
templates/corporate/pricing_model.html
web/styles/portico/pricing_plans.css

Kick in min-width at the required width.
This will ensure that scrollbars are only visible if the window is at this width.

pricing_plans: Fix scrollbars always visible.

---

corporate/tests/test_stripe.py

* First commit -- follow-up: https://github.com/zulip/zulip/pull/28196#issuecomment-1858211066
> check what /billing/ says about the next renewal date and amount is better than checking the data structure for it.
* Second commit:  Add remote server non-sponsorship E2E test.
<details>
</details>

test_stripe: Add remote server non-sponsorship E2E test.

---

corporate/models.py

**Notes**:
- Removes the contact email from the remote activity table. This can be accessed via the support view link.
- Shortens the plan status text strings, which are currently primarily used here.
<details>
<summary>Updated plan status string on support view</summary>
</details>
<details>
<summary>Updated remote activity page</summary>
</details>
---
<details>
</details>

support: Shorten plan status strings for remote activity.

---

web/src/user_group_edit.js

We now do not remove the user group row immediately from "Your groups" panel when user is removed from the group, if the user can join that group again by themselves. This makes the behavior similar to what we have for streams.
<details>
</details>

user_groups: Do not remove the user group row if user can join again.

---

.eslintrc.json
web/debug-require-webpack-plugin.ts
web/e2e-tests/compose.test.ts
web/e2e-tests/lib/common.ts
web/e2e-tests/realm-creation.test.ts
web/e2e-tests/realm-playground.test.ts
web/e2e-tests/user-status.test.ts
web/src/attachments_ui.ts
web/src/avatar.ts
web/src/billing/billing.ts
web/src/blueslip.ts
web/src/feedback_widget.ts
web/src/input_pill.ts
web/src/realm_icon.ts
web/src/realm_logo.ts
web/src/settings_emoji.ts
web/src/settings_exports.ts
web/src/stream_data.ts

https://typescript-eslint.io/linting/configs/#strict-type-checked

eslint: Enable `@typescript-eslint/strict-type-checked` config

---

tools/test-js-with-node
web/src/fold_dict.ts
web/src/unread.js
web/src/unread.ts
web/tests/unread.test.js

This will help with https://github.com/zulip/zulip/pull/26803 and having typescript support for search pills

convert unread.js to typescript

---

web/templates/settings/notification_settings_checkboxes.hbs
web/templates/settings/stream_specific_notification_row.hbs

- First commit is to not show the tooltip when push notifications are enabled.
- Second commit is to show the tooltip for checkbox in stream notification row.
<details>
</details>

Fix tooltips shown for push notifications not enabled on server.

---

docs/production/deployment.md
docs/production/postgresql.md
puppet/zulip/manifests/profile/postgresql.pp
scripts/lib/install
scripts/setup/upgrade-postgresql

install: Support PostgreSQL 16.

---

corporate/tests/test_stripe.py

`RemoteZulipServer`: Receive a deactivate server confirmation link => login => deactivate server =>  verify that login fails.
<details>
</details>

test_stripe: Add E2E test for deactivate registration with bouncer.

---

.eslintrc.json
web/src/activity.ts
web/src/billing/helpers.ts
web/src/blueslip.ts
web/src/browser_history.ts
web/src/channel.ts
web/src/compose_call.ts
web/src/compose_fade_helper.ts
web/src/compose_state.ts
web/src/hash_util.ts
web/src/invite.ts
web/src/message_store.ts
web/src/overlays.ts
web/src/people.ts
web/src/portico/desktop-login.ts
web/src/portico/portico_modals.ts
web/src/presence.ts
web/src/settings_emoji.ts
web/src/stream_data.ts
web/src/user_topics.ts
web/src/util.ts
web/tests/peer_data.test.js
web/tests/presence.test.js

https://typescript-eslint.io/linting/configs/#stylistic-type-checked

eslint: Enable `@typescript-eslint/stylistic-type-checked` config

---

web/src/filter.js
web/src/filter.ts
web/src/message_view_header.js
web/src/page_params.ts
web/tests/compose_validate.test.js
web/tests/filter.test.js

Merge #28189 (the first four commits) first. The last three commits of this PR are the ones relevant to filter.js
This will help with https://github.com/zulip/zulip/pull/26803 and having typescript support for search pills.

convert filter.js to typescript

---

tools/test-js-with-node
web/src/subscriber_api.ts

subscriber_api: Convert module to TypeScript.
<details>
</details>

subscriber_api: Convert module to TypeScript

---

web/src/starred_messages.ts

starred_messages: Migrate module to typescript.

---

tools/test-js-with-node
web/src/navbar_help_menu.ts

Migrate javascript code to typescript
<details>
</details>

navbar_help_menu: Migrate module to typescript.

---

help/custom-certificates.md

https://chat.zulip.org/#narrow/stream/31-production-help/topic/.E2.9C.94.20zulip.20client.20for.20Ubuntu.20certificate/near/1709820

docs: Correct certutil invocation for importing self-signed certificate

---

web/src/page_params.ts
web/src/people.ts

[Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/page_params.2Eis_bot/near/1710556).

people: Don’t reference nonexistent page_params.is_bot

---

docs/subsystems/billing.md

[CZO Discussion](https://chat.zulip.org/#narrow/stream/19-documentation/topic/billing.20docs.20improvement/near/1679800)
**Before**
**After**
<details>
</details>

docs: Improve billing (development) docs.

---

web/styles/dark_theme.css

Before -
After -
<details>
</details>

settings: Fix discard button in groups UI in dark theme.

---

analytics/tests/test_support_views.py
corporate/lib/support.py
templates/analytics/next_plan_details.html
templates/analytics/remote_realm_details.html
templates/analytics/remote_server_support.html

Currently, this will only be the case for legacy self-managed plans that have scheduled a switch to either the Basic or Business plan.
**Notes**:
- The next plan information is after the dropdown fields / forms since those actions apply to the current plan and not the upcoming next plan.
- This will be good to have in place for adding a discount for folks with an active, current, paid plan. Note that currently adding a discount will update both the current plan and the upcoming plan. This is not an issue for legacy plans, but would be in other situations.
<details>
<summary>Example of a customer with an active plan with a scheduled switch to another plan tier</summary>
</details>
---
<details> …

support: Display next plan data on remote support view.

---

corporate/lib/stripe.py

Currently, there's a formatting issue with the previous discount in these success message strings.
<details>
<summary>Current strings</summary>
</details>
<details>
<summary>Updated strings</summary>
</details>
---
<details>
</details>

support: Reformat percentages in attach discount success message.

---

web/src/message_flags.ts
web/src/message_store.ts

CI will fail because of something I have a question about

message flags: Convert module to typescript.

---

help/generate-integration-url.md
templates/zerver/integrations/include/generate-integration-url.md

As the help center article now has detailed instructions to generate an incoming webhook URL, the integration documentation only needs to link to that information.
Also makes a few small updates to the main description of the **Generate URL for an integration** help center article.
---
<details>
<summary>Updated Airbrake integration doc - no events filtering</summary>
[Current documentation](https://zulip.com/integrations/doc/airbrake)
</details>
<details>
<summary>Updated PagerDuty integration doc - has events filtering</summary>
[Current documentation](https://zulip.com/integrations/doc/pagerduty)
</details>
<details>
<summary>Generate URL for an integration help center</summary>
[Current documentation](https://zulip.com/help/generate-integration-url) …

integrations: Simplify instruction for generating incoming webhook URL.

---

web/src/compose_pm_pill.ts
web/src/custom_profile_fields_ui.js
web/src/input_pill.ts
web/src/user_pill.ts
web/tests/user_pill.test.js

We previously allowed adding pills for inaccessible user by typing the email manually. This commit updates it to handle inaccessible users like we handle invalid emails.
Before -
After -
<details>
</details>

user_pill: Add support to not allow adding inaccessible users manually.

---

analytics/views/activity_common.py
analytics/views/remote_activity.py
templates/analytics/remote_activity_key.html

In the remote activity view:
- Format no data (`None`) for **Mobile users** and **Mobile pushes forwarded** as 0.
- Use the `last_audit_log_update` field on the remote server for the latest update time.
- Removes note about Zulip version in the key at the top of the page.
- Adds a sum in the total row for **Mobile pushes forwarded**.
<details>
<summary>Updated remote activity view</summary>
</details>
---
<details> …

remote-activity: Format mobile push data and use audit log data for update time

---

help/self-hosted-billing.md

Current: https://zulip.com/help/self-hosted-billing#paid-plan-discounts
<details>
<summary>Screenshot</summary>
<details>

help: Document self-hosted plan discounts in more detail.

---

analytics/tests/test_support_views.py
templates/analytics/sponsorship_forms_support.html
templates/zerver/emails/sponsorship_request.html

I don't know how to preview these. Also not sure whether the test changes I made were correct.

billing: Improve display of sponsorship requests.

---

templates/corporate/comparison_table_cloud.html
templates/corporate/comparison_table_self_hosted.html
templates/corporate/plans.html
web/styles/portico/comparison_table.css

This should be accurate, with some further info to be added as follow-ups.

billing: Add Cloud comparison table.

---

tools/test-js-with-node
web/src/fetch_status.ts
web/src/message_list.js
web/src/message_lists.ts
web/src/message_util.ts
web/tests/recent_senders.test.js

message_util: Convert module to typescript.

---

tools/fetch-contributor-data

fetch-contributor-data: Add zulip-flutter repo.

---

.github/workflows/production-suite.yml

ci: Test upgrades from Zulip Server 8.0.

---

analytics/tests/test_support_views.py
analytics/views/support.py
corporate/lib/support.py
templates/analytics/remote_realm_details.html
templates/analytics/remote_server_support.html

**Updates**:
- Updates strings from `MissingDataError` to clarify if analytics data or audit log data was missing.
- Adds a link to the server's remote installation analytics page. This is the same link on the remote activity page.
- Adds data on mobile users and mobile pushes forwarded. For the server, these should be the same counts as on the remote activity page.
**Notes**:
- I wonder if we want to consolidate some of the database queries for the support view. Or if there's a more efficient way to go about it than I am currently. But perhaps that can be a refactor after we've got all the data that we want to show?
<details>
<summary>Updated remote server / realm information in support view</summary>
</details>
---
<details> …

remote-support: Add mobile counts and server analytics link.

---

docs/production/mobile-push-notifications.md

Add a more direct link to the code for the push notification bouncer.
Prompted by [this](https://chat.zulip.org/#narrow/stream/31-production-help/topic/So.20does.20Zulip.20wants.20to.20loose.20also.20their.20current.20users.3F/near/1706776).

Add a more direct link to the code for the push notification bouncer.

---

corporate/lib/stripe.py
corporate/tests/test_stripe.py

For self hosted basic plan, we need to allow customers to subscribe without purchasing 10 licenses and also we need to allow customer take fully use the available discount so that if the add more users in the future, the full discount was already applied.
To fix above, we set minimum user count to the least number of licenses we require for the charge to be positive after applying the complete discount.
| monthly | annual |
| --- | --- |
| <img width="843" alt="Screenshot 2024-01-06 at 10 57 33 AM" src="https://github.com/zulip/zulip/assets/25124304/87e55f5b-4c92-4a39-920c-7e54c658cdae"> | <img width="843" alt="Screenshot 2024-01-06 at 10 57 46 AM" src="https://github.com/zulip/zulip/assets/25124304/a7af5368-70bd-4936-896d-3500a08d35ba"> |
|   <img width="843" alt="Screenshot 2024-01-06 …

stripe: Set min license count based on flat discount.

---

corporate/lib/stripe.py
templates/corporate/pricing_model.html
web/src/billing/upgrade.ts
web/styles/portico/pricing_plans.css

Only enable free trial for basic plan.

---

templates/zerver/development/dev_login.html
web/styles/portico/portico.css

Restructures the links at **portico** **devlogin** pages. (`/devlogin`)
Centers the **devtool buttons** at the bottom of the page.
[CZO Thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/UI.20inconsistency.20on.20system.20bot.20realm.20devlogin.20page)
| --------- | -------- |
|![Screenshot_20240106_155556](https://github.com/zulip/zulip/assets/11803841/363fb406-e4e3-4cd8-9b2b-5e9db1dda9a9) | ![Screenshot_20240109_072247](https://github.com/zulip/zulip/assets/11803841/0962b160-fc73-4a7a-9bf4-6c89074aded3) |
<details> …

Restructure devlogin page link

---

help/mobile-notifications.md

Current: https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications
Updated:

help: Document plan sign-up in notification troubleshooting section.

---

zerver/lib/dev_ldap_directory.py

modified concatenation of strings to f-strings to improve readability and unify the code
<details>
- [ x Commit message(s) explain reasoning and motivation for changes.
</details>

сhanged concatenation of strings to f-strings to improve readability

---

help/self-hosted-billing.md
help/zulip-cloud-billing.md
templates/corporate/plans.html
templates/corporate/pricing_model.html

- Clarify sponsorship policies.
- Explain how paid self-hosted plans fund the Zulip project.
Current: https://zulip.com/plans/#self-hosted
<details>
<summary>
Self-hosted /plans
</summary>
</details>
Current: https://zulip.com/plans/#cloud
<details>
<summary>
Cloud /plans
</summary>
</details>
Current: https://zulip.com/help/zulip-cloud-billing#apply-for-sponsorship
<details>
<summary>
Updated Zulip Cloud sponsorship section
</summary>
</details>
Current: https://zulip.com/help/self-hosted-billing#free-community-plan
<details>
<summary>
Self-hosted billing
</summary>
</details>

billing: Improve /plans and billing help pages.

---

tools/test-js-with-node
web/src/user_group_popover.ts

This is needed for #24580.
<details>
</details>

user_group_popover: Convert module to typescript.

---

templates/404.html
templates/4xx.html
zerver/decorator.py
zerver/middleware.py

Fixes: #25626. 
Used the Zulip error template (`templates/404.html`) to create a page for CSRF validation error. As per the issue an error message has been added, suggesting users check if they are using Safari's private browsing mode or some other privacy-blocking extension and, if so, they may need to disable it.
Before:
After:
<details>
</details>

CSRF error page #25626

---

zerver/lib/message.py
zerver/tests/test_message_send.py

We now allow system bots to mention a group if `can_mention_group` setting
is set to "role:everyone" group and not when it is set to some other group.
<details>
</details>

message: Allow system bots to mention group if everyone else can.

---

web/src/stream_list_sort.js
web/src/stream_list_sort.ts

Built off of #28395, which should be merged first

stream_list_sort: Convert module to typescript.

---

zerver/openapi/zulip.yaml

[CZO Discussion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/register.3A.20.60realm_push_notifications_enabled_end_timestamp.60/near/1717465)
This PR updates the doc to explicitly mention that `realm_push_notifications_enabled_end_timestamp` is a UNIX timestamp.
---
</img>
</details> 
</img>
</details> 
---
<details> …

api_docs: Update doc for `realm_push_notifications_enabled_end_timestamp`.

---

web/src/message_list.js
web/styles/zulip.css
web/templates/message_controls.hbs

As as a sort of parallel to #28538, this PR cleans up some unreachable or unused styles and structures related to status/`/me` messages that are not reachable, or that no longer have any purpose owing to the grid-based layout in the message row.
_As this is a code-quality PR, there should be no visual changes._
| --- | --- |
| ![sender-status-before](https://github.com/zulip/zulip/assets/170719/90ede3f2-8c8a-4f43-98cd-5706010206b2) | ![sender-status-after](https://github.com/zulip/zulip/assets/170719/b2abf124-866e-4696-af6c-ede8923f87c1) |
| ![sender-status-edit-before](https://github.com/zulip/zulip/assets/170719/c8bfae3f-4e97-46ee-b9ab-88494e905ddf) | ![sender-status-edit-after](https://github.com/zulip/zulip/assets/170719/c6d1509f- …

message_row: Sender-status cleanup.

---

web/templates/settings/notification_settings.hbs

This PR fixes the bug in which "Automatically follow topics where I'm mentioned" label doesn't have click functionality.
**Before**
**After**
<details>
</details>

settings: Fix setting label click functionality.

---

api_docs/http-headers.md
api_docs/incoming-webhooks-overview.md
docs/overview/changelog.md
docs/production/install.md
docs/production/security-model.md
docs/subsystems/markdown.md
templates/corporate/features.html
templates/corporate/for/business.html
templates/corporate/for/education.html
templates/corporate/for/events.html
templates/corporate/for/open-source.html
templates/corporate/for/research.html
templates/corporate/why-zulip.md
templates/zerver/app/index.html
templates/zerver/emails/missed_message.html
templates/zerver/emails/missed_message.txt
templates/zerver/landing_nav.html
web/templates/settings/display_settings.hbs
zerver/openapi/zulip.yaml
zerver/tests/test_message_notification_emails.py

Fix 301 redirects seen in production.

---

web/src/user_status.ts

user_status: Fix parsing of partial user_status events

---

help/include/self-hosted-billing-multiple-organizations.md

Typo fix and minor clarification.

help: Make minor tweaks to warning about multiple organizations billing.

---

templates/corporate/communities.html
templates/zerver/integrations/index.html
templates/zerver/portico-header-dropdown.html
web/src/billing/helpers.ts
web/src/portico/communities.ts
web/src/portico/header.ts
web/src/portico/integrations.js
web/styles/portico/integrations.css
web/styles/portico/portico.css

discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/bootstrap

helpers: Remove dead bootstrap tabs code.

---

corporate/lib/stripe.py
zilencer/management/commands/populate_billing_realms.py

Run `./manage.py populate_billing_realms`. Avoid running the server while doing so to avoid any weird behaviour.

Allow access to billing page without talking to stripe.

---

web/src/message_view_header.js
web/src/search.js
web/styles/search.css
web/third/bootstrap-typeahead/typeahead.js

prep commits for search pills

---

web/src/stream_edit.js
web/src/stream_edit_toggler.ts
web/src/stream_settings_ui.js
web/src/stream_ui_updates.js

- First commit is to refactor the code to avoid trying to set hash multiple times.
- Second commit is to empty the right panel based on the url hash.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/Alt.2Bleftarrow.20steals.20focus.3F.20.28streams.20settings.29
<details>
</details>

stream-settings: Refactor code for updating right panel.

---

web/src/unread_ops.js

Fixes https://github.com/zulip/zulip/issues/27372.
This commit refactors the original mark_all_as_read in unread_ops to bulk_mark_mesages_as_read to include marking stream/topic as read.
The unread_ops API reamins the same to mark stream/topic as read but the underlying implementation now uses a different endpoint. 
A new function mark_all_as_read has been added so that the unread_ops API remains the same.
I did not create a new function for this task since a lot of the code would have been shared with mark_all_as_read
GIF shows results with initial and followup batch sizes to 1
<details> …

unread_ops: Use /messages/flags/narrow to mark stream/topic as read.

---

tools/test-backend
zerver/actions/presence.py

Fixes: #25498 
<details>
</details>

tests: full coverage for zerver/actions/presence.py

---

web/src/all_messages_data.ts
web/src/filter.ts
web/src/message_list.js
web/src/narrow_state.ts
web/src/search.js
web/src/typing_events.js
web/src/upload.js
web/tests/compose_closed_ui.test.js
web/tests/filter.test.js
web/tests/left_sidebar_navigation_area.test.js
web/tests/message_fetch.test.js
web/tests/message_list.test.js
web/tests/message_list_data.test.js
web/tests/message_list_view.test.js
web/tests/narrow_state.test.js
web/tests/popover_menus_data.test.js
web/tests/upload.test.js

These should all be good to merge.

Preparatory commits extracted from #28483

---

tools/backport-pull-request

See https://chat.zulip.org/#narrow/stream/438-release-management/topic/backporting.20tooling/near/1713799 for discussion.

tools: Add a tool for backporting PRs.

---

zerver/tests/test_home.py
zerver/views/home.py

Redirect home for some hostnames.

---

templates/corporate/for/business.html
templates/corporate/plans.html
templates/corporate/self-hosting.html
web/styles/portico/hello.css
web/styles/portico/plans_pages.css
web/styles/portico/pricing_plans.css
web/webpack.assets.json

This PR:
1. Isolates global /plans styles to their own file.
2. Scopes `pricing_plans.css` to only those landing pages that need it.
3. Implements background and gradient fixes originally in #28491, whose changes were reverted in 40f99d0990c758b423f144f9dd651e6be5127135
`/why-zulip/` (background is white, as expected):
`/for/business/` (background is white, plans tabs rendered as expected):
`/plans/` (background properly extends below footer):
<details>
Completed …

portico: Scope styles, implement gradient fixes.

---

help/logging-in.md

Current: https://zulip.com/help/logging-in
Updated:

help: Tweak instructions for finding your Zulip account.

---

zerver/lib/message.py

The previous query suffered from pessimal corner cases when the user had received a large number of direct messages but sent very few, comparatively.  This mean that the first half of the UNION would retrieve a very large number of UserMessage rows, requiring fetching a large number of Message rows, merely to throw them away upon determining that the recipient was the current user.
Instead of merging two queries of "last 1k received" + "last 1k sent", we instead make better use of the UserMessage rows to find "last 10k sent or received."  This may change the list of recipients, as large disparities in sent/received messages may result in pushing the most-recently-sent users off of the list.  These are likely uncommon edge cases, however -- and the disparity is the whole reason for the …

message: Rewrite personals query to be more performant and accurate.

---

tools/backport-pull-request
web/src/desktop_integration.js
zerver/decorator.py
zerver/lib/test_helpers.py
zerver/tests/test_auth_backends.py
zerver/tests/test_signup.py
zerver/views/auth.py
zerver/views/registration.py
zproject/backends.py
zproject/default_settings.py

* https://github.com/zulip/zulip/pull/28577
* https://github.com/zulip/zulip/pull/28411

Backport a few more changes to 8.x

---

web/src/compose_validate.js

This fixes the bug reported in https://chat.zulip.org/#narrow/stream/137-feedback/topic/Always.20actual.20ping.20bot's.20in.20DM's/near/1722645.

compose: Don't convert bot mentions to silent mentions. 

---

help/self-hosted-billing.md
help/zulip-cloud-billing.md
templates/corporate/plans.html

Current: https://zulip.com/plans/
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/plans/#self-hosted
<details>
<summary>
Updated
</summary>
</details>
Current:
- https://zulip.com/help/self-hosted-billing#paid-plan-discounts
- https://zulip.com/help/self-hosted-billing#free-community-plan
<details>
<summary>
Updated
</summary>
---
</details>
Current: https://zulip.com/help/zulip-cloud-billing#free-and-discounted-zulip-cloud-standard
<details>
<summary>
Updated
</summary>
</details>

billing: Qualify policies for free and discounted plans.

---

analytics/views/remote_activity.py

Per notes in https://github.com/zulip/zulip/pull/28634#issuecomment-1900914170 for the chart layout:
- Combines the IDs for the remote realm and remote server in the first column.
- Moves the Realm name to the second column.
- For the host/hostname column, displays the remote realm host if it is a remote realm row. Otherwise, the remote server hostname is displayed.
**Questions**:
- Is the **Server email contact** still a useful column at this point?
- Should the **Realm name** be after the **Realm host or server hostname** column?
@alya - It'd be good to get your thoughts on these changes and the questions above.
---
<details>
<summary>Updated remote activity chart</summary>
</details>
---
<details>
(variable …

remote-activity: Update column data/structure for remote realms.

---

web/src/compose_ui.js
web/src/compose_validate.js
web/styles/user_status.css
web/templates/status_emoji_selector.hbs
web/tests/compose_ui.test.js
zerver/data_import/slack.py
zerver/tests/test_slack_importer.py

* https://github.com/zulip/zulip/pull/28291
* https://github.com/zulip/zulip/pull/28554
* https://github.com/zulip/zulip/pull/28637
* https://github.com/zulip/zulip/pull/28609

Backport more changes to 8.x

---

web/src/stream_edit_subscribers.js

There is no need to log if the stream edit UI is not opened when an event for updating subscribers list is received and we should just return because this is not a bug. We do the same in other places where we just return early without logging because we do not need to make any updates.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/stream_edit_subscribers.20console.20logging
<details>
</details>

stream_edit_subscribers: Remove unnecessary logging.

---

web/src/admin.js
web/src/settings.js
web/src/settings_config.ts
web/src/settings_preferences.js
web/styles/settings.css
web/templates/settings/display_settings.hbs

This helps fixes part of issue #26874.
In this pull request
Changed Files:
web/src/admin.js
web/src/settings.js
web/src/settings_config.ts
web/src/settings_preferences.js
web/styles/settings.css
web/templates/settings/display_settings.hbs
<details>
</details>

Rename "Display settings" -> "Preferences".

---

templates/corporate/pricing_model.html

Because we can now extend the end date for legacy self-hosted plans, instead of hard-coding the generic end date in the plans template, show the specific end date for the current legacy plan as they should always have an end date set.
<details>
<summary>Updated plans view for self-hosted legacy server in dev environment after extending the current plan end date for a year</summary>
</details>
---
<details> …

plans-template: Show end date of legacy plan for push notifications.

---

docs/production/authentication-methods.md

A draft doc for  https://github.com/zulip/zulip/pull/28411
As mentioned there, it feels pretty hard to get these instructions right, since going into full relevant detail would make this very long and overwhelming, while staying shallow risks making this not useful for users, since implementation-level details are pretty relevant here. The fact that getting such a custom auth wrapper wrong can be horrible for security doesn't help :neutral_face:

docs: Add documentation for the new custom auth wrapper setting.

---

web/src/info_overlay.js

This commit fixes the behaviour of message formatting overlay in help menu not opening due to assertion error in rendered markdown after changes from #28418.
Fixes: bug from #28418 
<details>
</details>

help_menu: Fix help_menu message formatting overlay not opening.

---

help/self-hosted-billing.md

Current: https://zulip.com/help/self-hosted-billing#upgrades-for-legacy-customers
Updated:
Related PR: https://github.com/zulip/zulip-mobile/pull/5814

help: Add announcement info to "Upgrades for legacy customers" section.

---

zilencer/management/commands/populate_db.py

The presence of the name "François" in the random first name list led to email addresses of the form `françois1234@zulip.com` which are invalid.
Strip invalid ASCII from the email addresses generated in populate_db, and validate them before tossing them verbatim into the database.
Fixes: 
<details>
</details>

populate_db: Only make valid email addresses.

---

help/emoji-and-emoticons.md
help/include/emoji-and-emoticons-intro.md

Documents how to insert emoji in topic names to avoid potential confusion with Markdown formatting for emoji.
See [CZO thread](https://chat.zulip.org/#narrow/stream/137-feedback/topic/icon.20in.20topic.20.3Aoctopus.3A/near/1703228) for details.
<details>
</details>

help: Document how to use an emoji in a topic name.

---

zerver/lib/import_realm.py

This also requires shuffling the message import to before the scheduled messages.
Fixes: #28690.
<details>
</details>

import: Rewrite "delivered_message" column of scheduled messages.

---

web/src/hashchange.js
web/src/user_group_edit.js
web/templates/gear_menu_popover.hbs

- First commit is to make "Cancel" button work in group creation form.
- Second commit is to open groups UI with "#groups/your" hash when opening the groups UI from gear menu.
- Third commit is to fix browser back button behavior when opening the groups UI by manually entering "#groups" hash.
- Fourth commit is to empty the right panel based on url hash.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/new.20user.20group.20cancel.20button.20bugs.20out.20in.20group.20settings
<details> …

Fix bugs in new groups UI.

---

puppet/zulip_ops/files/nagios4/conf.d/services.cfg

Using locks is not itself a bad sign; there is no need to alert on it, as there is no value which can be chosen as being "too many."
<details>
</details>

nagios: Remove locks alert.

---

web/src/settings_bots.js
web/styles/dark_theme.css
web/styles/settings.css
web/templates/settings/account_settings.hbs
web/templates/settings/bot_settings.hbs
web/tests/settings_bots.test.js

This PR replaces the boostrap tabs with our own tabs implementation in components.ts.
This is part of the bootstrap removal project.
<details>
</details>

settings: Do not use bootstrap tabs in bots panel.

---

puppet/zulip_ops/manifests/prometheus/akamai.pp
puppet/zulip_ops/templates/vector.toml.template.erb

puppet: Add vector pipelines for other Akamai SQS queues.

---

help/mobile-notifications.md
help/self-hosted-billing.md
zerver/lib/markdown/tabbed_sections.py

Current: https://zulip.com/help/self-hosted-billing#upgrades-for-legacy-customers
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications
<details>
<summary>
Updated
</summary>
</details>
Follow-ups:
- #28707

Tweak user docs for self-hosted billing and mobile push notifications

---

help/desktop-app-install-guide.md
tools/linter_lib/custom_check.py

Adds documentation for installing zulip through Flathub in https://zulip.com/help/desktop-app-install-guide.
Fixes: #28508
<details>
</details>

Help: Add documentation for installation through Flathub.

---

web/src/emoji.ts
web/src/reactions.js
web/tests/input_pill.test.js
web/tests/pm_list_data.test.js
web/tests/reactions.test.js

prep commits for converting reactions module to typescript

---

web/src/settings_account.js
web/styles/zulip.css
web/templates/dialog_change_password.hbs
web/third/bootstrap/css/bootstrap.app.css

- First commit is to remove unnecessary code.
- Second commit is to not use "fade" class for password quality bar.
- Third commit is to remove the bootstrap CSS fror "fade" class.
<details>
</details>

Remove bootstrap "fade" class.

---

web/src/typeahead_helper.ts
web/src/types.ts
web/src/user_groups.ts
web/tests/typeahead_helper.test.js

typeahead_helper: Convert module to typescript.

---

corporate/urls.py
templates/corporate/case-studies/atolio-case-study.md
templates/corporate/case-studies/end-point-case-study.md
templates/corporate/case-studies/gut-contact-case-study.html
templates/corporate/case-studies/gut-contact-case-study.md
templates/corporate/case-studies/idrift-case-study.md
templates/corporate/for/business.html
templates/corporate/for/use-cases.md
templates/zerver/landing_nav.html

Sorry, the non-relative link in the top nav will make this fail tests.
<details>
<summary>
GUT contact case study
</summary>
</details>
<details>
<summary>
/for/business
</summary>
</details>
<details>
<summary>
Use cases
</summary>
</details>

portico: Add GUT contact case study.

---

docs/outreach/overview.md

contributor docs: Link to GSoC 2023 blog post.

---

corporate/lib/activity.py
corporate/views/remote_activity.py

Adds a column with the percentage rate that the remote server or realm is paying on the displayed plan.
**Notes**:
- We display 0% for community plans that are 100% sponsored.
- For legacy plans or plans with a scheduled downgrade, we display a placeholder, "---".
- Otherwise, the value is calculated from the CustomerPlan discount field.
- De-duplicated for some shared logic/code for getting remote realm and remote server plan data.
<details> …

remote-activity: Add column for rate paid on displayed plan.

---

docs/outreach/gsoc.md

/cc @chrisbobbe
<details>
</details>

docs: Update mobile project description for GSoC 2024.

---

corporate/views/remote_activity.py
templates/corporate/activity/installation_activity_table.html

Moves links in installation and remote server activity charts to be the first column.
<details>
<summary>Updated installation activity chart</summary>
</details>
<details>
<summary>Updated remote servers activity chart</summary>
</details>
---
<details>
</details>

activity: Move links columns to be first in chart.

---

api_docs/integrations-overview.md
help/add-a-bot-or-integration.md
help/bots-overview.md
help/deactivate-or-reactivate-a-bot.md
help/deactivate-or-reactivate-a-user.md
help/edit-a-bot.md
help/generate-integration-url.md
help/include/set-up-integrations.md
help/include/sidebar_index.md
help/integrations-overview.md
help/request-an-integration.md
help/restrict-bot-creation.md
help/restrict-direct-messages.md
help/self-hosted-billing.md
help/set-up-integrations.md
help/view-all-bots-in-your-organization.md
help/view-your-bots.md
zerver/lib/url_redirects.py

- Renames [Bots and integrations](https://zulip.com/help/bots-and-integrations) to "Bots overview" everywhere (sidebar, page title, page URL).
- Adds a copy of [/api/integrations-overview](https://zulip.com/api/integrations-overview) (symbolic link) as the second page in the Bots & integrations section, titled "Integrations overview".
- Cross-link as appropriate, both in related articles and in the content of the pages.
Fixes #28758.
<details>
</details>

help: Improve integrations documentation.

---

web/src/compose.js
web/src/drafts.js
web/src/echo.js
web/src/info_overlay.js
web/src/markdown.js
web/src/markdown.ts
web/src/markdown_config.ts
web/src/message_edit.js
web/tests/compose.test.js
web/tests/drafts.test.js
web/tests/echo.test.js
web/tests/markdown.test.js
web/tests/markdown_parse.test.js
web/third/marked/lib/marked.d.ts

stub marked and migrate markdown module.

---

tools/push-to-pull-request

- https://github.com/zulip/zulip/pull/28784#issuecomment-1922046293

push-to-pull-request: Accept intermixed options and arguments again

---

help/contact-support.md
help/self-hosted-billing.md
templates/corporate/billing/billing.html

<details>
<summary>
Screenshots
</summary>
</details>

billing: Rename Self-hosted/Self-managed plan to Free on billing and help pages.

---

puppet/zulip/manifests/app_frontend_base.pp

These two changes should help better choose how to use memory.

Tweak number of processes for low-memory systems

---

puppet/zulip_ops/files/install-ssh-authorized-keys
puppet/zulip_ops/files/install-ssh-keys
puppet/zulip_ops/manifests/profile/base.pp
puppet/zulip_ops/manifests/profile/chat_zulip_org.pp
puppet/zulip_ops/manifests/profile/grafana.pp
puppet/zulip_ops/manifests/profile/munin_server.pp
puppet/zulip_ops/manifests/profile/nagios.pp
puppet/zulip_ops/manifests/profile/postgresql.pp
puppet/zulip_ops/manifests/profile/prod_app_frontend.pp
puppet/zulip_ops/manifests/profile/prometheus_server.pp
puppet/zulip_ops/manifests/profile/smokescreen.pp
puppet/zulip_ops/manifests/profile/staging_app_frontend.pp
puppet/zulip_ops/manifests/profile/teleport.pp
puppet/zulip_ops/manifests/profile/zmirror.pp
puppet/zulip_ops/manifests/profile/zmirror_personals.pp
puppet/zulip_ops/manifests/profile/zulipbot_zulip_org.pp
puppet/zulip_ops/manifests/ssh_authorized_keys.pp
tools/setup/bootstrap-aws-installer

Limit key distribution

---

puppet/zulip/manifests/app_frontend_base.pp
puppet/zulip/manifests/profile/memcached.pp
puppet/zulip/manifests/profile/redis.pp
puppet/zulip/manifests/sysctl.pp
puppet/zulip/manifests/systemd_daemon_reload.pp
puppet/zulip/templates/sysctl.d/40-uwsgi.conf.erb
puppet/zulip_ops/files/postgresql/40-postgresql.conf
puppet/zulip_ops/manifests/profile/postgresql.pp
puppet/zulip_ops/manifests/profile/prod_app_frontend.pp
puppet/zulip_ops/manifests/profile/redis.pp
puppet/zulip_ops/manifests/teleport/part.pp
puppet/zulip_ops/templates/sysctl.d/40-conntrack.conf.erb

Update kernel settings on redis hosts.

---

web/src/narrow.js
web/src/topic_generator.ts
web/src/unread_ops.js

Extracted from #28636.
I think we can safely merge this to not think about them.

Prep commits to merging narrow activate and deactivate calls.

---

web/src/click_handlers.js
web/src/stream_popover.js
web/styles/app_components.css
web/styles/components.css
web/styles/message_row.css
web/styles/modal.css
web/styles/settings.css
web/styles/zulip.css
web/third/bootstrap/css/bootstrap-btn.css
web/third/bootstrap/css/bootstrap.app.css

discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/bootstrap.20dropdown-toggle

Bootstrap cleanup

---

web/src/message_fetch.js
web/src/reload.js
web/src/server_events.js
web/src/util.ts
web/tests/message_fetch.test.js

Based on an investigation of a case where the web app managed to hit server-side rate limits.
The individual commits detail the changes.

Fix rate limiting issues with the web application

---

corporate/lib/stripe.py

This will require customers to include an address when setting up, or updating, the credit card information for their account. The billing address for the card will also be saved as the billing address for the stripe customer.
The stripe customer's billing address appears on the invoices that are generated by stripe.
**Notes**:
- Updating the stripe test fixtures for these changes seems like something that would be fine to do when we update the stripe API version as the fields that are updated/added are not ones that we verify/need in what we're testing. Otherwise, doing so now will update hundreds of the existing test fixtures for these changes. 
- In manual testing in the dev environment, updating a card's address will mean that the current, updated address on the customer's account is …

stripe: Add billing address collection to checkout session.

---

puppet/zulip_ops/manifests/app_frontend.pp
puppet/zulip_ops/manifests/profile/redis.pp

This was left off of 1fe5e7c7daf9.
<details>
</details>

puppet: Create redistunnel group.

---

.github/workflows/zulip-ci.yml
requirements/common.in
requirements/dev.txt
requirements/prod.txt
version.py
zerver/lib/markdown/api_arguments_table_generator.py
zerver/lib/markdown/api_return_values_table_generator.py
zerver/lib/test_classes.py
zerver/middleware.py
zerver/openapi/curl_param_value_generators.py
zerver/openapi/markdown_extension.py
zerver/openapi/openapi.py
zerver/openapi/zulip.yaml
zerver/tests/test_openapi.py
zproject/test_extra_settings.py

[Discussion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/OpenAPI.20requestBody/near/1622284).

openapi: Validate real requests and responses, not fictional mocks

---

docs/outreach/gsoc.md

Extend some of the early framing and remove/update previous projects. I intend to add more changes to add new ones too.

docs: Update main GSoC page.

---

zerver/actions/message_send.py

Removes the stale `email_gateway` parameter from `do_send_messages` function.
This should have been removed in 6c473ed75f64e88d1462808d9c880a8016fb43e4, when the call to `build_message_send_dict` was removed from `do_send_messages`.
<details>
</details>

do_send_messages: Remove the stale 'email_gateway' parameter.

---

puppet/zulip_ops/manifests/app_frontend.pp
puppet/zulip_ops/manifests/user_dotfiles.pp

Manage known_hosts

---

web/src/narrow_state.ts
web/src/peer_data.ts
web/src/people.ts
web/src/server_events_dispatch.js
web/src/user_events.js
web/tests/narrow_state.test.js
web/tests/peer_data.test.js

These cover the changes needed to these other data modules to support the new buddy list work in #26717.
@evykassirer FYI.

Preparatory commits extracted from #26717

---

zerver/actions/create_user.py
zerver/tests/test_events.py
zerver/tests/test_invite.py
zerver/tests/test_new_users.py

Previously, new user sign up notification message was - 
> @some user just signed up for Zulip. (total: N).
Since there are other ways to see the number of users , updated the code to - 
> @some user joined this organization.
Fixes: #28834.
Previously - 
Presently - 
<details>
</details>

messages: Update new user signup notification.

---

puppet/kandra/files/chrony-20.04.conf
puppet/kandra/files/chrony-22.04.conf
puppet/kandra/manifests/profile/base.pp

kandra: Update default chrony configuration for 22.04.

---

puppet/kandra/manifests/profile/nagios.pp

This prevents failures when new hosts are initially added to the configuration.
<details>
</details>

kandra: Pull in known_hosts to the nagios user.

---

web/src/admin.js
web/src/settings_components.js

- First commit is to make setting disabled for orgs without "Plus" plans.
- Second commit is to allow orgs without "Plus" plan to change the guest indicator setting.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/incorrect.20Plus.20plan.20required.20banner
<details>
</details>

Fix "Who can access all users" setting UI.

---

help/desktop-app-install-guide.md
help/include/app-will-update-tip.md

Apply current help center patterns (e.g., tips).
Current: https://zulip.com/help/desktop-app-install-guide
<details>
<summary>
Mac
</summary>
</details>
<details>
<summary>
Windows
</summary>
</details>
<details>
<summary>
Linux
</summary>
</details>

help: Clean up desktop installation guide.

---

help/custom-profile-fields.md

Also reorder as in 60225591dcc947c61b1d13202942d86886a42839.
Current: https://zulip.com/help/custom-profile-fields#profile-field-types
Updated:

help: Improve descriptions of custom profile field types.

---

tools/test-js-with-node
web/src/compose_recipient.js
web/src/compose_ui.js
web/src/compose_ui.ts
web/tests/compose_ui.test.js

#28725 had pushing by maintainers disabled.

 compose_ui: Convert module to typescript.

---

web/src/click_handlers.js
web/src/stream_popover.js

This PR fix the issue of stream popover not closing when clicked on `unsubscribe`.
CZO discussion: [here](https://chat.zulip.org/#narrow/stream/9-issues/topic/Stream.20popover.20does.20not.20close.2E/near/1733590)
Before:
After:
<details>
</details>

stream_popover: Hide popover when clicked on `unsubscribe`.

---

api_docs/incoming-webhooks-overview.md
api_docs/incoming-webhooks-walkthrough.md

- Updates [incoming webhooks walkthrough](https://chat.zulip.org/api/incoming-webhooks-walkthrough) following changes introduced in #26365. 
- Updates [incoming webhooks overview](https://chat.zulip.org/api/incoming-webhooks-overview) to be consistent with the `zerver/webhooks/` codebase, and improve readability.
<details>
</details>

integrations: Update incoming webhooks overview and walkthrough.

---

web/src/message_notifications.js

This logic was part of the original desktop notifications implementation in 4cb0c6225e22c257318f63fc491fb6b5c202f2e7.
There's no apparent standard for the number of characters allowed to be shown in a desktop notification, so truncating at 150 characters arbitrarily seems wrong.
Further, we've decided it's no longer a priority to truncate at word boundaries, we can rely on the browser to take responsibility for truncation.
Fixes #25260.
Fixes: 
<details>
Completed …

notifications: Remove custom truncation logic.

---

web/src/message_notifications.js

Prep commits related to #21032.

Prep commits to internationalization of desktop notification.

---

docs/contributing/counting-contributions.md
docs/contributing/index.md

Current: https://zulip.readthedocs.io/en/latest/contributing/contributor-statistics.html
Updated:

contributor docs: Tweak wording in "Counting contributions" intro.

---

help/change-a-users-role.md
help/include/change-a-users-role.md
help/roles-and-permissions.md

Current: https://zulip.com/help/roles-and-permissions
Updated:

help: Improve Roles and permissions page.

---

corporate/lib/stripe.py
corporate/tests/test_stripe.py
corporate/views/support.py
templates/corporate/support/next_plan_details.html
templates/corporate/support/remote_realm_details.html
templates/corporate/support/remote_server_support.html
web/styles/portico/activity.css

This will help us modify the configured plan if we need to.

support: Add button to delete configured fixed next plan.

---

web/src/drafts.js
web/src/drafts_overlay_ui.js

drafts: Move some functions from draft_overlay_ui.

---

web/src/stream_settings_components.js
web/styles/subscriptions.css
web/templates/stream_settings/selected_stream_title.hbs

Fixes:  #25171 Made the stream name clickable and added a tool-tip (on hover with delay) showing the keyboard shortcut for the view stream [shift][v].
<details>
</details>

stream_title: Make stream name in stream settings panel a link.

---

web/src/stream_popover.js
web/src/tippyjs.ts
web/styles/dark_theme.css

This PR disables stream-select dropdown in ```move_topic_modal``` for users who are not permitted to move messages.
Fixes: #28345
<details>
</details>

message_move: Disable stream select dropdown for unprivileged users.

---

api_docs/changelog.md
puppet/zulip/templates/supervisor/zulip.conf.template.erb
scripts/lib/email-mirror-postfix
scripts/lib/upgrade-zulip-stage-2
scripts/lib/zulip_tools.py
scripts/reload-clients
scripts/restart-server
version.py
web/src/server_events_dispatch.js
web/tests/dispatch.test.js
web/tests/lib/events.js
zerver/decorator.py
zerver/lib/event_schema.py
zerver/lib/events.py
zerver/management/commands/runtornado.py
zerver/openapi/zulip.yaml
zerver/tests/test_decorators.py
zerver/tests/test_email_mirror.py
zerver/tests/test_event_queue.py
zerver/tests/test_event_system.py
zerver/tests/test_events.py
zerver/tornado/application.py
zerver/tornado/django_api.py
zerver/tornado/event_queue.py
zerver/tornado/views.py
zerver/views/email_mirror.py
zproject/urls.py

Push separate events for reloading web clients

---

web/src/compose_recipient.js
web/src/compose_validate.js
web/src/people.ts
zerver/actions/message_send.py
zerver/tests/test_message_send.py

Fixes: #28412 
| --- | --- |
| ![Screenshot from 2024-01-07 11-41-42](https://github.com/zulip/zulip/assets/90370535/99ef6806-1845-42b2-a83e-98557648f363) | ![Screenshot from 2024-01-07 11-40-23](https://github.com/zulip/zulip/assets/90370535/5eed3eb5-3612-4646-a42b-35a4b67811e4) |
| ![Screenshot from 2024-01-07 11-41-30](https://github.com/zulip/zulip/assets/90370535/9830599b-18d2-4083-a32a-c0366798240f) | ![Screenshot from 2024-01-07 11-40-36](https://github.com/zulip/zulip/assets/90370535/056d967a-f914-4906-9ac1-7254e8345788) |
<details> …

Enable a direct message to bots and to yourself when DMs are disabled

---

templates/corporate/team.html
tools/fetch-contributor-data
web/src/portico/team.ts

Changed the bucketing system in the team page to be able to render multiple repositories under 1 tab.
We were rendering the team section with respect to repository name and 1 repository was assigned to 1 tab.
Changed the design to render the team section with respect to tab name to render multiple repositories under 1 tab
Fixes:  #28504 
<details>
</details>

portico-team: Rework repository on team page

---

web/src/hash_parser.ts
web/src/hashchange.js
web/src/personal_menu_popover.js
web/src/user_card_popover.js
web/src/user_profile.js
web/styles/dark_theme.css
web/styles/modal.css
web/styles/popovers.css
web/templates/personal_menu.hbs
web/templates/profile_access_error_modal.hbs
web/templates/user_profile_modal.hbs

This adds a "Copy link to profile" button in the user profile modal. Users can easily copy the profile link by clicking on this option, which triggers a "Copied!" tooltip for confirmation. This also updates the user profile modal behavior to depend on a dynamically generated URL for opening. Upon closing the modal, the URL reverts to the one that was active before the modal was opened.
Fixes #28445
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/Copy.20link.20to.20profile)
**Light Mode**
**Dark Mode**
<details> …

user_card_popover: Add "copy link to profile" feature in user card.

---

puppet/zulip/manifests/app_frontend_base.pp
web/src/admin.js
web/src/compose_actions.js
web/src/message_fetch.js
web/src/message_list.js
web/src/narrow.js
web/src/reload.js
web/src/server_events.js
web/src/settings_components.js
web/src/util.ts
web/tests/message_fetch.test.js
web/tests/narrow_activate.test.js

* #28852 I pushed directly while preparing this.
* #28755
* https://github.com/zulip/zulip/pull/28767
* https://github.com/zulip/zulip/pull/28817
* https://github.com/zulip/zulip/pull/28620
* https://github.com/zulip/zulip/pull/28809
* https://github.com/zulip/zulip/pull/28873

Backport several PRs to the 8.x branch

---

docs/subsystems/markdown.md

This PR fix a small typo in developer documentation [Checkout here](https://zulip.readthedocs.io/en/latest/subsystems/markdown.html) instead of `markdown.js`  `markdown.ts` should be shown.
**before:**
**After:**
<details>
</details>

fix a typo in markdown implementation documentation.

---

corporate/lib/stripe.py

Earlier, during invoicing we used to send a mail to sales@zulip.com when the `last_audit_log_update` was at least one day ago.
There was an assertion that `last_audit_log_update` can't be None which is incorrect as such customers exist.
This PR extends the behaviour to send an invoice overdue email even if the data was never uploaded.
<details>
</details>

corporate: Send invoice overdue mail also when data never uploaded.

---

corporate/lib/stripe.py
zerver/tests/test_push_notifications.py

Fixed failing tests & added a test to cover the case where remote realm has an expired plan & remote server has an active plan. -- #28960
<details>
</details>

corporate: Fix plan precedence issues with expired plans.

---

web/third/bootstrap/css/bootstrap.app.css

Happily, every last CSS property in these styles is already described for the places `<pre>` appears in the Zulip UI:
1. In rendered message markdown
2. In the compose preview
3. In the information overlay (Message formatting)
Fixes: 
**Devtools inspections of the three `<pre>` occurrences**
In rendered messages:
In message previews:
In the Message formatting overlay:
<details>
</details>

bootstrap: Remove pre styles.

---

web/tests/hashchange.test.js
web/tests/lib/namespace.js
web/tests/recent_view.test.js
web/tests/rendered_markdown.test.js
web/tests/typeahead_helper.test.js
web/tests/upload.test.js

tests: Fix direct mutation of ES modules again, again

---

corporate/lib/stripe.py

In `invoice_plan()`, the primary way to not create an invoice for a plan is to not have any new ledger entry.
This PR adds a `self.on_paid_plan()` check which is an extra layer of defense to avoid creating any invoices for customers not on paid plan. It saves a DB query too.
<details>
</details>

stripe: Add a check to create invoices only for paid plans.

---

tools/test-js-with-node
web/src/message_lists.ts
web/src/message_live_update.ts

message_live_updates: Convert module to TypeScript.

---

web/src/message_actions_popover.js
web/styles/modal.css
web/styles/settings.css

| --- | --- |
| <img width="683" alt="Screenshot 2024-02-20 at 9 54 41 PM" src="https://github.com/zulip/zulip/assets/25124304/196e663b-7613-44be-905a-2e1ee442609a"> | <img width="683" alt="Screenshot 2024-02-20 at 9 54 19 PM" src="https://github.com/zulip/zulip/assets/25124304/847a9949-d20f-4d8e-8410-a02e754f7078"> |
| <img width="683" alt="Screenshot 2024-02-20 at 9 54 53 PM" src="https://github.com/zulip/zulip/assets/25124304/19c92a8d-6edb-49c9-b19b-07f49bfe798b"> | <img width="683" alt="Screenshot 2024-02-20 at 9 54 00 PM" src="https://github.com/zulip/zulip/assets/25124304/f415febf-a73d-482b-a171-70d3205fb4d0"> |

Minor issue fixes with move messages dropdown.

---

templates/corporate/billing/legacy_server_login.html
templates/corporate/billing/remote_billing_confirm_email_form.html
templates/corporate/billing/remote_billing_email_confirmation_sent.html
templates/corporate/billing/remote_billing_finalize_login_confirmation.html
templates/corporate/billing/remote_billing_server_deactivate.html
templates/corporate/billing/remote_billing_server_deactivated_success.html
templates/corporate/billing/upgrade.html
web/styles/portico/billing.css
web/webpack.assets.json

Fix spacing issues on fixed plan upgrade page.

---

corporate/tests/test_support_views.py
templates/corporate/support/current_plan_details.html
templates/corporate/support/next_plan_details.html
templates/corporate/support/realm_details.html
templates/corporate/support/remote_realm_details.html
templates/corporate/support/remote_server_support.html
templates/corporate/support/sponsorship_forms_support.html
templates/corporate/support/support.html
web/styles/portico/activity.css

Adjusts the remote support view to have two columns with the remote server information and forms on the left and the remote realm information and forms on the right.
Updates the background colors and adds borders to more easily distinguish between the different areas of the view and different forms.
<details>
<summary>Zulip Cloud support - search for Iago</summary>
</details>
<details>
<summary>Remote support view - server has remote realms</summary>
</details>
<details>
<summary>Remote support view - server has no remote realms</summary>
</details>
---
<details> …

support: Update views to highlight important information.

---

zerver/tornado/event_queue.py

tornado: Fix GC of old queues.

---

docs/production/deployment.md
docs/production/install.md
docs/production/troubleshooting.md

Current: https://zulip.readthedocs.io/en/latest/production/install.html
<details>
<summary>
Updated
</summary>
</details>
<details>
<summary>
Section moved to Server configuration
</summary>
</details>
<details>
<summary>
Section moved to Troubleshooting and monitoring
</summary>
</details>
**Questions / notes:**
- I put the troubleshooting section at the bottom of the page, but there may be a better placement for it.
- I left the content on what to do after installation as-is, but I'm planning to follow up with a separate pass on that.

docs: Improve Zulip server installation doc.

---

templates/corporate/support/realm_details.html
templates/corporate/support/remote_realm_details.html
templates/corporate/support/remote_server_support.html
web/styles/portico/activity.css

**Notes**:
- Updates the class name used for the sponsorship form container in the remote support views to be more specific.
- Adds a shared "support-form" class for the different forms in the realm_details template.
- Use the same CSS rule for current and next plan information sections to have a small bottom margin.
<details>
<summary>Zulip Cloud support view</summary>
</details>
<details>
<summary>Remote support view</summary>
</details>
---
<details> …

remote-support: Use more specific class name for sponsorship forms.

---

corporate/lib/decorator.py

Followup on https://github.com/zulip/zulip/pull/28963#issuecomment-1950499660

billing: Return login URL for AJAX request session timeout for servers.

---

web/styles/left_sidebar.css

This removes an extra pixel of padding that was likely left in place to match the icon position in the pre-gridded DM rows, but that actually carried forward a design that didn't offer perfect centering.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/left.20sidebar.20DMs.20spacing.20with.20bots/near/1735952)
| --- | --- |
| ![Screenshot 2024-02-20 at 3 41 59 PM](https://github.com/zulip/zulip/assets/170719/68e7999a-0a1d-4156-92e6-46764c123925) | ![Screenshot 2024-02-20 at 3 38 45 PM](https://github.com/zulip/zulip/assets/170719/e2d7f03e-7efd-4ecd-b96d-af7f12d2d40e) |
<details> …

left_sidebar: Remove unnecessary padding on bot icon.

---

corporate/tests/test_remote_billing.py
corporate/tests/test_stripe.py
corporate/views/remote_billing_page.py
zilencer/views.py

remote_billing: Remove code migrating Legacy plan from server to realms.

---

corporate/lib/support.py
corporate/tests/test_support_views.py
corporate/views/support.py
templates/corporate/support/remote_server_support.html

**Notes**:
- **Search improvements**:
- Can search for a remote realm host
- Can search for a remote server or remote realm UUID
- Leading or trailing whitespace is removed from the search query string
- **Query improvements**:
- Removed prefetch of remote realm set for remote servers as we were hitting the database twice because we need to exclude the system bot remote realm from the data
- Only get the customer object once (instead of getting it again for sponsorship data)
- Only get plan licenses at next renewal once (instead of getting it twice for next plan data)
- Only get the user counts once (instead of getting it in the plan data a second time)
---
<details> …

remote-support: Improve search and reduce duplicate queries.

---

web/styles/left_sidebar.css

The padding on the bot icon is no longer necessary for vertical alignment, and by removing the 6px of padding it represents, bot DM rows will have the same 22px height as other DM rows.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/left.20sidebar.20DMs.20spacing.20with.20bots/near/1742108)
| --- | --- |
| ![bot-icon-before-28px](https://github.com/zulip/zulip/assets/170719/d4456799-ec8b-43fb-b0f7-4815bb05f51b) | ![bot-icon-after-22px](https://github.com/zulip/zulip/assets/170719/97dab7e4-f4ce-4776-ae16-1f6abc46c57c) |
<details> …

left_sidebar: Remove padding from bot icon.

---

.github/workflows/codeql-analysis.yml
.github/workflows/production-suite.yml
.github/workflows/update-oneclick-apps.yml
.github/workflows/zulip-ci.yml

[Discussion](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/github.20actions.20upgrades/near/1742336).

ci: Upgrade external GitHub actions

---

web/src/user_search.ts

merge #28897 first, this PR is just the last commit

user_search: Convert module to typescript

---

corporate/urls.py
templates/corporate/case-studies/atolio-case-study.md
templates/corporate/case-studies/end-point-case-study.md
templates/corporate/case-studies/gut-contact-case-study.md
templates/corporate/case-studies/idrift-case-study.md
templates/corporate/case-studies/semsee-case-study.html
templates/corporate/case-studies/semsee-case-study.md
templates/corporate/for/business.html
templates/corporate/for/use-cases.md
templates/zerver/landing_nav.html

Let me know if you'd like more screenshots.

Add Semsee case study

---

web/src/hash_util.ts
web/src/hashchange.js
web/src/message_view_header.js
web/src/stream_settings_ui.js
web/src/user_group_edit.js
web/src/user_group_popover.ts
web/src/user_groups.ts
web/templates/user_group_settings/user_group_settings.hbs
web/tests/hashchange.test.js
web/tests/user_groups.test.js

- First commit is to not pass unnecessary parameter to a function.
- Second commit is a preparatory commit to refactor the code.
- Third commit is to include right side tab in url hash.
- Fourth commit is to fix the url opened by clicking on stream name in message view header.
Fixes:  #28678
<details>
</details>

Include right side tab in url hash for group settings edit UI.

---

web/src/typing.ts
web/src/typing_events.ts

* Commit 1: Fix "Missing stream_id" server error.
* Commit 2: Fix assertion error when narrowed to a non existing stream.
<details>
</details>

typing: Fix errors related to typing notifications.

---

tools/test-js-with-node
web/src/dropdown_widget.ts
web/src/integration_url_modal.js
web/src/list_widget.ts
web/src/settings_org.js
web/src/stream_edit.js
web/src/stream_settings_components.js
web/src/user_group_components.js
web/src/user_profile.js
web/src/views_util.js
web/tests/recent_view.test.js

dicussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/TypeScript.20migration

dropdown_widget: Migrate to typescript.

---

docs/production/system-configuration.md
puppet/kandra/files/memcached_exporter
puppet/kandra/manifests/app_frontend_monitoring.pp
puppet/kandra/manifests/prometheus/memcached.pp
puppet/kandra/templates/supervisor/conf.d/memcached_exporter.conf.template.erb
puppet/zulip/manifests/profile/memcached.pp
puppet/zulip/templates/memcached.conf.template.erb
requirements/dev.txt
requirements/prod.in
requirements/prod.txt
version.py

kandra: Add a memcached exporter using bmemcached.

---

tools/test-js-with-node
web/src/list_cursor.ts
web/src/pm_list.ts
web/src/stream_list.js
web/src/stream_list.ts
web/src/unread.ts
web/tests/stream_list.test.js
web/tests/stream_search.test.js

merge  https://github.com/zulip/zulip/pull/29033 first

stream_list: Convert module to typescript.

---

web/e2e-tests/stream_create.test.ts
web/src/stream_create.js
web/src/user_group_create.js

- Use proper punctuation.
- Make errors friendlier.

stream/group settings: Improve error strings.

---

zerver/management/commands/export_search.py

export_search: Support exporting DMs or huddles.

---

tools/test-js-with-node
web/src/onboarding_steps.ts
web/src/state_data.ts

onboarding_steps: Convert module to TypeScript.

---

scripts/log-search

Updates to log-search

---

CONTRIBUTING.md

docs: Update contributing guide for zulip-flutter, vs. zulip-mobile.
---
docs: Fix a server/web-specific segment in contributing guide.
These are fine instructions, but are specific to the server and
web app, while the surrounding section is otherwise valid for the
project as a whole.  Mark them as such, and add a sibling item
for the Flutter app.  (Consisting of good advice for becoming
familiar with really any software project, plus a link to the
app's README for specific setup instructions.)
---
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.htm …

Fix and update contributing guide as to zulip-flutter

---

puppet/kandra/files/memcached_exporter

Fix memcached metric descriptions, add two settings metrics

---

zerver/forms.py
zerver/lib/email_validation.py
zilencer/views.py

Only one of them properly checked for improperly-formed email addresses, thanks to #22723.
<details>
</details>

email_validation: Merge two implementations of a disposable-email check.

---

help/moderating-open-organizations.md

Context: [CZO discussion about changing default permissions](https://chat.zulip.org/#narrow/stream/101-design/topic/onboarding.3A.20message.20moving.20and.20deletion.20permissions/near/1745921)
Current page: https://zulip.com/help/moderating-open-organizations
Updated:

help: List more permissions on "Moderating open organizations" guide.

---

web/styles/portico/activity.css

Sets the max-width for table data cells in the activity and installation charts.
If the content exceeds the limit, then the overflow is set to hidden and the text-overflow is set to ellipsis, so there is a visual indication that the text is not completely visible.
**Notes**:
- The other activity chart that will likely be impacted is the realm activity chart, which has a column for user emails.
<details>
<summary>Remote activity - with find on page for email that's hidden due to overflow</summary>
</details>
<details>
<summary>Remote activity chart - zoomed in to columns that will be most likely impacted by setting max-width</summary>
</details>
---
<details> …

activity: Limit width of columns in activity charts.

---

scripts/log-search

Add date and time limits to log-search

---

web/src/channel.ts
web/src/spectators.ts
web/tests/channel.test.js

Fixes errors on /devtools/integrations/ and /emails/.

channel: Use base_page_params

---

corporate/lib/stripe.py
corporate/tests/test_activity_views.py
corporate/tests/test_stripe.py
templates/corporate/billing/billing.html

<details><summary>Billing Page - Before</summary>
</img>
</details> 
<details><summary>Billing Page - After</summary>
</details> 
<details>
</details>

corporate: Fix next payment info on billing page for fixed-price plans.

---

zerver/migrations/0320_realm_move_messages_between_streams_policy.py
zerver/migrations/0355_realm_delete_own_message_policy.py
zerver/models/realms.py

- First commit is to update default for "Who can move messages between streams" setting.
- Second commit is to update default for "Who can delete their own message" setting.
Fixes:  https://chat.zulip.org/#narrow/stream/101-design/topic/onboarding.3A.20message.20moving.20and.20deletion.20permissions
<details>
</details>

Update defaults for delete message setting and setting for moving message between streams.

---

web/src/compose_ui.ts
web/tests/compose_ui.test.js
web/third/bootstrap-typeahead/typeahead.js

https://github.com/fregante/text-field-edit/releases/tag/v4.0.0

web: Convert uses of deprecated text-field-edit function aliases

---

web/templates/settings_overlay.hbs

Fixes: #29132
<details>
</details>

settings: Update the icon of preferences in personal settings.

---

web/src/copy_and_paste.js
web/tests/copy_and_paste.test.js

Since the html copied from VS Code is not structured as code but as styled divs for each line, any code copied from it would be pasted unformatted with blank lines between each line of code.
This has now been fixed, by detecting VS Code style code blocks by the CSS property `white-space: pre` and pasting the text within as is, as code.
Fixes: [CZO issue thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/extra.20line.20breaks.20when.20pasting/near/1690703)
Code copied from VS Code:
Pastes in Zulip as:
<details> …

copy_and_paste: Fix formatting of code pasted from VS Code.

---

templates/corporate/hello.html
templates/corporate/try-zulip.html

The first commit is my version of #27068 (sorry for dropping the ball on this, @andersk !).
The second commit can be merged separately if we'd like to iterate on it.

Updates to /hello

---

web/src/copy_and_paste.js
web/tests/copy_and_paste.test.js

This reverts commit 4a1423b34a90ea6d9a983b36e3b2384c0ff0ec33 (part of #29123).
- https://github.com/zulip/zulip/pull/29123#pullrequestreview-1910146894
Cc @N-Shar-ma

Revert "copy_and_paste: Fix formatting of code pasted from VS Code."

---

templates/corporate/team.html
tools/fetch-contributor-data
web/src/portico/team.ts
web/styles/portico/portico.css

Based on an audit of all repositories in the zulip organization.
See [the chat.zulip.org thread](https://chat.zulip.org/#narrow/stream/2-general/topic/stats.20on.20.2Fteam.20page/near/1738732) for screenshots and the like.

team: Add more repositories and rename tabs.

---

docs/production/export-and-import.md

- More consistent export/import vs backup bullets at the top.
- Remove misleading documentation regarding the `zulip_org_id` reuse problems. This documentation was written for Zulip 2.1.0 in c6fe6cf0a47cd61c0005aa099b9f7fa16d96f603 and largely made obsolete in d800ac33a0322b0d3ef327bcebf318a27448bbee (Zulip 5.0).
- Light editing for readability/crispness.
Fixes #28925.

docs: Better document backup/export tool tradeoffs.

---

web/src/user_status_ui.ts

- https://github.com/zulip/zulip/pull/28996#pullrequestreview-1912489742

user_status_ui: Fix input_field() type

---

templates/corporate/billing/sponsorship.html

sponsorship: Add basic plan option for self hosted orgs.

---

web/templates/unread_banner/mark_as_read_only_in_conversation_view.hbs

help: Link mark as read in conversation banner to help page.

---

tools/test-js-with-node
web/src/zcommand.ts

zcommand: Convert module to TypeScript.

---

docs/subsystems/hotspots.md
tools/test-js-with-node
web/src/hotspots.ts
web/src/onboarding_steps.ts
web/src/state_data.ts

hotspots: Convert module to TypeScript

---

help/add-or-remove-users-from-a-stream.md
help/include/sidebar_index.md
help/include/stream-menu-subscribers-tab-tip.md
help/manage-user-stream-subscriptions.md
help/view-stream-subscribers.md
zerver/lib/markdown/tabbed_sections.py

This is an updated version of #29119. I only made changes to the first commit.
Fixes https://github.com/zulip/zulip/issues/28887.
New page:

help: View stream subscribers

---

web/src/stream_edit.js
web/src/stream_settings_ui.js
web/templates/modal_banner/stream_creation_confirmation_banner.hbs
web/templates/stream_settings/stream_settings.hbs

This PR adds banner which is shown on successful stream creation
which contains a link to stream narrow.
This banner makes it more clear that stream was created successfully
and also makes it easy to navigate to the new stream.
Fixes #29171.
<details>
</details>

stream_settings: Show banner on successful stream creation.

---

web/styles/portico/markdown.css

Add a word-wrap rule so that longer code elements, such as example URLs or long return value names in the API documentation, do not overflow out of the view in narrowed browsers or mobile views.
**Notes**:
- `<code>` tags that are in `<pre>` tags have the same word-break rule applied confirming that these changes to not impact those elements in the help center and API documentation.
---
<details>
<summary>Register response main description changes note - mobile view via browser devtools</summary>
| --- | --- |
| ![Screenshot from 2024-03-05 17-25-32](https://github.com/zulip/zulip/assets/63245456/955b8e21-03bc-46c2-b28a-59a7e4088dd2) | ![Screenshot from 2024-03-05 17-25-07](https://github.com/zulip/zulip/assets/63245456/4d08bb69-a81f- …

markdown-css: Wrap longer code elements in documentation.

---

web/src/emoji_picker.js
web/src/hotkey.js
web/src/reactions.ts
web/tests/reactions.test.js

Followup to comments on #28375

reactions: Followups to typescript migration

---

docs/production/mobile-push-notifications.md

Current: https://zulip.readthedocs.io/en/stable/production/mobile-push-notifications.html#how-to-sign-up
Updated:

docs: Add plan sign-up to mobile notifications sign-up instructions.

---

tools/test-js-with-node
web/src/left_sidebar_navigation_area.ts

left_sidebar_navigation_area: Convert module to TypeScript.

---

corporate/lib/stripe.py
corporate/models.py

* Fix the check for -- "whether the plan being processed is paid or not".
* Fix assertion error while attempting to charge customers on fixed-price plans for additional licenses.
<details>
</details>

corporate: Bug fixes related to plan invoicing.

---

web/src/people.ts

CZO conversation: https://chat.zulip.org/#narrow/stream/6-frontend/topic/remove_diacritics.20performance/near/1689797

people: Cache results of remove_diacritics.

---

web/src/state_data.ts

state_data: Fix alphabetical sorting.

---

tools/test-js-with-node
web/src/condense.ts
web/src/message_store.ts

condense: Convert module to Typescript.

---

web/templates/bookend.hbs

Also change "deactivated"->"archived" for consistency.

bookends: Add periods to stream status bookends.

---

web/src/user_profile.js

Left/right keys arrows in User Profile now navigates between tabs when the modal is first opened.
This issue was pointed out by @amanagr [here](https://github.com/zulip/zulip/issues/27781#issuecomment-1887251580)
Fixes: #28615
<details>
</details>

User Profile: Navigate tabs by arrow keys when user profile opens.

---

templates/corporate/for/education.html
web/styles/portico/landing_page.css

These changes add an extra bullet, which is not actually showing up on the page. @amanagr , if it's not too hard, could you please tweak the CSS to make it work?

portico: Align plans on /for/education with /plans.

---

tools/test-js-with-node
web/src/resize_handler.ts

This PR migrates `resize_handler.js` to `resize_handler.ts`.
<details>
</details>

resize_handler: Convert module to Typescript

---

zerver/views/report.py

Refactor `report_csp_violations` view to use `typed_endpoint` decorator instead of `has_request_variables`. This change improves code consistency and enhances codebase comprehension.
Fixes: 
<details>
</details>

csp_violations: Migrate has_request_variables to typed_endpoint.

---

docs/tutorials/screenshot-and-gif-software.md

Remove the redundant closing bracket in the Gifski link.
Before the change
After the change
<details>
</details>

docs: Fix typo in screenshot and gif software tutorial.

---

corporate/views/realm_activity.py

realm_activity: Correct the "messages sent" column.

---

web/src/stream_settings_ui.js
web/src/stream_ui_updates.js

- First commit is to fix the live update on subscribing or unsusbcribing.
- Second commit is to remove unnecessary code.
- Last commit is to fix live update on changing privacy.
<details>
</details>

Fix live update of stream email UI.

---

web/src/message_fetch.js
web/src/message_scroll.js
web/src/narrow_state.ts
web/tests/message_fetch.test.js

Prep commits to don't cache message list for all messages view.

---

help/moderating-open-organizations.md

Follow-up to https://github.com/zulip/zulip/issues/15688#issuecomment-1989614462
Note:
- I have not thought too deeply about how to order the bullets within their section.
Current page: https://zulip.com/help/moderating-open-organizations
Updated (top part):

help: Organize and extend guide for moderating open organizations.

---

help/configure-organization-language.md

[CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/topic.20name.20translation/near/1747238)
Current: https://zulip.com/help/configure-organization-language
Updated:

help: Clarify how automated notices are translated.

---

help/quote-and-reply.md

help: Document new option to quote part of a message.

---

templates/corporate/for/education.html

portico: Add quote from UTFPR to /for/education.

---

api_docs/changelog.md
zerver/openapi/zulip.yaml

**Notes on updates to feature level 224 documentation**: 
- Adds missing update personal message flag endpoints to the feature level changelog entry.
- Updates the order and formatting of these new and deprecated flags in the available flags table on the [/api/update-message-flags](https://zulip.com/api/update-message-flags#available-flags) endpoint.
- Adds a link to the [topic wildcard mentions](https://zulip.com/help/mention-a-user-or-group#mention-all-topic-participants) section of the help center documentation in that same table.
- Makes small clean ups to the **Changes** notes for this feature level, as well as the changelog entry itself.
[CZO conversation for 8.0 API changelog updates](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/8.2E0.20API.20changelog.20audit/n …

api-docs: Update feature level 224 changelog and changes notes.

---

help/change-a-users-name.md
help/change-your-name.md
help/demo-organizations.md
templates/corporate/billing/remote_billing_finalize_login_confirmation.html
templates/zerver/new_user_email_address_visibility.html
templates/zerver/register.html
web/styles/portico/portico_signin.css
web/styles/settings.css
web/templates/demo_organization_add_email_modal.hbs
web/templates/settings/admin_human_form.hbs
web/templates/settings/profile_settings.hbs

- First two commits update the name field label and placeholder on account creation page.
- Next commit is to update the field label in app and includes the documentation changes.
- Next commit is to update the field label in billing flow on the login confirmation page.
- Last commit is to add description below the name field.
Fixes: #29226
Account creation form -
Demo organization email modal -
Profile settings and user edit form -
<details> …

Change name field label and description

---

corporate/lib/stripe.py

Earlier, when a customer with scheduled fixed-price plan visited the billing page, the `get_next_billing_cycle` function raised an assertion error as no renewal ledger entry exists.
No renewal ledger entry exists for a scheduled fixed-price plan.
We don't need the ledger entry to determine the next billing cycle in this case, so we move the code block which determines the `last_renewal` time within the else conditional i.e. where it is needed.
<details>
Completed …

corporate: Fix 'get_next_billing_cycle' for scheduled fixed-price plan.

---

web/tests/composebox_typeahead.test.js
web/tests/pill_typeahead.test.js
web/tests/search.test.js

tests: Avoid override_rewire for bootstrap_typeahead

---

web/tests/compose_actions.test.js
web/tests/composebox_typeahead.test.js
web/tests/dispatch_subs.test.js
web/tests/drafts.test.js
web/tests/hotkey.test.js
web/tests/stream_events.test.js

tests: Replace unneeded override_rewire uses by whole-module mocks

---

requirements/dev.txt
requirements/pip.in
requirements/pip.txt
requirements/prod.txt
version.py

- https://github.com/pypa/setuptools/commit/76ef30913dce00de4bca773f2dda9dd25ff66ad8
- https://github.com/zulip/pip/compare/6642149c44297200f44dfe215b1cb7954d47ed77...39e8b5ecfcd8d19872f103d680713bc8e9de9d00

requirements: Fix Python 3.12 issue in pip._vendor.pkg_resources

---

docs/conf.py
docs/development/setup-recommended.md
docs/development/setup/install-docker.md
docs/development/setup/vagrant-halt.md
docs/development/setup/vagrant-rebuild.md
docs/development/setup/vagrant-resume.md
docs/development/setup/vagrant-ssh.md
docs/development/setup/vagrant-up.md
docs/development/setup/vagrant-update.md
requirements/dev.txt
requirements/docs.in
requirements/docs.txt
requirements/pip.in
requirements/pip.txt
requirements/prod.txt

Merging this early should help reduce churn/merge conflicts for #28892.
I made a few changes:
- Bumped `PROVISION_VERSION`
- Fixed an accidental duplication of 3 lines of Windows steps.

Preparatory documentation refactoring commits extracted from #28892

---

help/include/self-hosted-billing-multiple-organizations.md

There may be other approaches to communicating this, but this is the best one I was able to come up with.
current: https://zulip.com/help/self-hosted-billing
Updated (occurs in 5 places on the page):

help: Clarify that the whole organization must be on the same plan.

---

web/src/ui_init.js
web/styles/app_components.css
web/styles/app_variables.css
web/styles/dark_theme.css
web/styles/left_sidebar.css
web/styles/zulip.css

Main things to test are spectator and logged in user at various widths.

Prep commits to hiding sidebars.

---

templates/corporate/development-community.md

Adds the Flutter mobile project to the section on chat.zulip.org linkifiers in the development community page. Moves the React Native mobile project to the bottom of the list as that project/repository is in maintenance mode.
---
<details>
</details>

dev-community: Document chat.zulip.org linkifier for flutter project.

---

tools/test-js-with-node
web/src/dropdown_widget.ts
web/src/integration_url_modal.ts
web/src/state_data.ts

integration_url_modal: Convert module to TypeScript.

---

docs/production/export-and-import.md
docs/production/system-configuration.md
puppet/zulip/files/postgresql/env-wal-g
puppet/zulip/manifests/postgresql_backups.pp
puppet/zulip/manifests/postgresql_base.pp

Add options for on-host wal_g backups

---

docs/production/export-and-import.md
docs/production/system-configuration.md
puppet/zulip/files/postgresql/env-wal-g
puppet/zulip/manifests/postgresql_backups.pp
puppet/zulip/manifests/postgresql_base.pp

Add options for on-host wal_g backups [8.x]

---

scripts/setup/create-database
web/src/compose_recipient.js

- https://github.com/zulip/zulip/pull/29242
- https://github.com/zulip/zulip/pull/29194

Backport a couple changes to the 8.x branch

---

docs/subsystems/widgets.md
web/src/poll_widget.ts
web/src/widgetize.ts
web/src/zcommand.ts

widgetize: Convert module to typescript

widgetize: Convert module to typescript

---

web/src/billing/billing.ts
web/src/billing/remote_billing_auth.ts
web/src/billing/sponsorship.ts
web/src/billing/upgrade.ts
web/src/invite.ts
web/src/portico/signup.ts
web/src/realm_logo.ts
web/src/settings_emoji.ts
web/src/stream_list.ts
web/src/user_search.ts
web/tests/activity.test.js
web/tests/user_search.test.js

[Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/TypeScript.20migration/near/1750154).

web: Fix selectors to correspond with annotated types

---

zerver/management/commands/send_custom_email.py

send_custom_email: is_realm_admin is a property, not a real column.

---

tools/test-documentation

Pull request [18124](https://github.com/zulip/zulip/pull/18124) contains the python code to fix issue #17929, but It failed the
merge tests. I merged the code from from [18124](https://github.com/zulip/zulip/pull/18124), ran merge tests and fixed
errors.
I have done the following tests.
Executed the original test plan as
described in [18124](https://github.com/zulip/zulip/pull/18124) and verified both outputs were similar from the python script and the original bash script.
Ran the script outside venv and verified the python script exited with the right error message.
Verified the merge tests all passed on my local branch.
Fix issue #17929
Fixes: #17929 
<details>
- [x ] …

tools: Fix test-documentation merge check errors.

---

web/styles/compose.css
web/styles/dark_theme.css
web/styles/right_sidebar.css
web/styles/scheduled_messages.css
web/styles/typing_notifications.css
web/styles/zulip.css

This is all but the last commit from #29342, which look good to me.

Sidebar css cleanups extracted from #29342

---

web/src/integration_url_modal.ts

Fixes: [Runtime safety](https://github.com/zulip/zulip/pull/29340#discussion_r1530905699)
<details>
</details>

integration_url_modal: Fix input selector for runtime safety.

---

docs/tutorials/new-feature-tutorial.md

[relevant CZO discussion](https://chat.zulip.org/#narrow/stream/3-backend/topic/flush.20vs.20restart.20memcached)

docs: Change "restart" to "flush" command in test-your-migration-changes section.

---

docs/git/overview.md
docs/git/pull-requests.md
docs/subsystems/accessibility.md
docs/translating/internationalization.md

Fixes #29332 
Change edX's GitHub links to point to their new organisation `openedx` and change `readthedocs.io` links to `docs.openedx.org`.
While the previous link in [`docs/translating/internationalization.md`](https://github.com/zulip/zulip/blob/main/docs/translating/internationalization.md#internationalization-for-developers) redirected to the new domain (`docs.opendedx.org`), I have explicitly updated this to the new domain as well. The other links were broken with no redirects.
<details>
- <del>[ ] Explains differences from previous plans (e.g., issue description).</del>
- <del>[ ] Highlights technical choices and bugs …

docs: Update broken edX reference links

---

docs/subsystems/events-system.md

[CZO](https://chat.zulip.org/#narrow/stream/19-documentation/topic/Typo.20in.20events.20system.20docs.3A.20wrong.20function)
Fixes: 
**<ins>Before:</ins>**
> ![image](https://github.com/zulip/zulip/assets/133781250/23a62e51-d9bd-4fc2-8525-acc636da1b53)
**<ins>After:</ins>**
> ![image](https://github.com/zulip/zulip/assets/133781250/333cdd7f-b1b4-4e36-bfd2-1a09fb0acf36)
<details>
</details>

docs: Fix incorrect function typo in events system.

---

templates/corporate/billing/upgrade.html

upgrade: Minor text edits.

---

web/src/bootstrap_typeahead.js
web/src/composebox_typeahead.js

prep commits for converting typeahead to typescript

---

docs/subsystems/markdown.md
tools/test-js-with-node
web/src/gear_menu.js
web/src/info_overlay.ts

info_overlay: Convert module to TypeScript.

---

zerver/worker/queue_processors.py
zproject/default_settings.py
zproject/sentry.py

Enable Sentry tracing and profiling.

---

puppet/kandra/manifests/apache.pp

It does not exist in 22.04, and its last use was removed in 61666a9262f5.
<details>
</details>

kandra: Remove unnecessary libapache2-mod-wsgi.

---

puppet/kandra/manifests/profile/grafana.pp
puppet/kandra/templates/grafana.ini.template.erb

kandra: Template and insert email credentials.

---

tools/semgrep-py.yml
zerver/actions/message_edit.py
zerver/actions/reactions.py
zerver/lib/message.py
zerver/lib/push_notifications.py
zerver/lib/test_classes.py
zerver/migrations/0273_migrate_old_bot_messages.py
zerver/models/messages.py
zerver/tests/test_message_move_stream.py
zerver/tests/test_message_move_topic.py
zerver/views/message_edit.py
zerver/views/reactions.py
zerver/views/read_receipts.py
zerver/views/submessage.py

https://chat.zulip.org/#narrow/stream/3-backend/topic/select_related.28.29.20with.20no.20args/near/1713375
@sahil839: Looks like one of these remaining calls was still a big performance problem.  Always a good idea to complete these migrations fully!
<details>
</details>

Improve message access queries
