zulip/zulip

- zerver/decorator.py
- zerver/lib/webhooks/common.py
- zerver/middleware.py
- zerver/tests/test_decorators.py
- zerver/tests/test_webhooks_common.py
- zerver/webhooks/bitbucket2/view.py
- zerver/webhooks/bitbucket3/view.py
- zerver/webhooks/freshping/view.py
- zerver/webhooks/github/view.py
- zerver/webhooks/groove/view.py
- zerver/webhooks/harbor/view.py
- zerver/webhooks/linear/view.py
- zerver/webhooks/reviewboard/view.py
- zerver/webhooks/sentry/view.py
- zerver/webhooks/statuspage/tests.py
- zerver/webhooks/statuspage/view.py
- zerver/webhooks/transifex/tests.py
- zerver/webhooks/transifex/view.py
It is not clear why 84723654c884 added these lines, are they are not related to status codes.
Using an explicit `capture_exception` causes the exception in Sentry to not have a `logger` field, which is quite useful for filtering.
<details>
</details>
> webhooks: Logger and exception cleanups.

- zerver/tests/test_auth_backends.py
- zerver/tests/test_presence.py
- zerver/tests/test_rate_limiter.py
- zerver/tests/test_realm_domains.py
This may save us from bugs like the ones fixed in
78683c1b9c3bfae70cce196382aa0ed5c28c8eb4 in the future.
> tests: Fix missing setUp calls in ZulipTestCase subclasses.

- help/configure-default-new-user-settings.md
- help/follow-a-topic.md
- help/include/configure-topic-notifications.md
- help/include/manage-configured-topics.md
- help/include/sidebar_index.md
- help/mute-a-topic.md
- help/stream-notifications.md
Current: https://zulip.com/help/mute-a-topic
<details>
<summary>
Combining instructions for muted and unmuted streams:
</summary>
</details>
<details>
<summary>
Just using the unmuted stream instructions for mobile:
</summary>
</details>
- No mobile UI yet. Can use the same instructions as /help/mute-a-topic once there is one.
- We'll add the setting for automatically following topics once it's merged in `main`.
- Sections ordered in terms of how useful I think they are.
<details>
<summary>
Screenshot
</summary>
</details>
> help: Update /help/mute-a-topic and document following topics.

- help/change-a-users-name.md
- help/change-a-users-role.md
Drop mostly redundant instuctions tab.
Current:
- https://zulip.com/help/change-a-users-name
- https://zulip.com/help/change-a-users-role
Updated:
> help: Simplify instructions for changing a user's name or role.

- web/src/message_edit.js
- web/tests/message_edit.test.js
- zerver/tests/test_message_edit.py
- zerver/views/message_edit.py
Fixes: [this](https://github.com/zulip/zulip/issues/25971)
This pr adds bot owners to delete messages of their bots' messages.
Tooling tips: https://zulip.readthedocs.io/en/latest/tutorials/screenshot-and-gif-software.html
-->
<details>
</details>
> Add capability of  delete messages for bot owners

- docs/development/remote.md
- tools/run-dev
- zproject/dev_settings.py
**Problem:** Making JSON requests from app running in a remote development environment with an SSL-certified domain currently results in a 403 (CSRF) error.
**What changes:**
Set in the Django dev settings:
```
CSRF_TRUSTED_ORIGINS = [EXTERNAL_URI_SCHEME + EXTERNAL_HOST]
```
Since Django 4.0 it seems that if running the server behind a reverse-proxy such as Nginx, then we require the `CSRF_TRUSTED_ORIGINS` setting containing the exact value for scheme + hostname.
[Reference in the Django docs about `CSRF_TRUSTED_ORIGINS` setting](https://docs.djangoproject.com/en/4.1/ref/settings/#csrf-trusted-origins)
**Screenshot of error as it appears in the network inspector:**
> run-dev: Add flag to allow JSON requests through HTTPS proxy.

- api_docs/changelog.md
- tools/lib/capitalization.py
- version.py
- zerver/lib/exceptions.py
- zerver/lib/push_notifications.py
- zerver/lib/remote_server.py
- zerver/openapi/zulip.yaml
- zerver/tests/test_openapi.py
- zerver/tests/test_push_notifications.py
- zerver/views/push_notifications.py
- zilencer/urls.py
- zilencer/views.py
- zproject/urls.py
Still missing more complete tests, and I imagine we will want to add some error handling with informative error responses to make the endpoint useful?
Will fix #23997 when complete.
Adds two endpoints:
1. Remote server endpoint `users/me/test_notify`, to which the mobile app will be able to make a request.
2. This will cause the remote server to request the bouncer to send the notification to the device at `/api/v1/remotes/push/test_notify`.
A server like the bouncer itself skips step 2 of course and send the notification directly.
> push_notifs: Add endpoint for sending a test notification.

- web/src/realm_user_settings_defaults.ts
- web/src/settings_config.ts
- web/templates/settings/organization_user_settings_defaults.hbs
This PR adds the following two settings to 'SETTINGS / DEFAULT USER SETTINGS':
* Let recipients see when a user is typing direct messages
* Let recipients see when a user is typing stream messages
<details>
</details>
> settings: Add default typing indicator user settings.

- web/src/message_fetch.js
- web/src/recent_view_ui.js
- web/src/timerender.ts
- web/src/ui_init.js
- web/styles/recent_view.css
- web/styles/zulip.css
- web/templates/recent_view_table.hbs
- web/tests/message_fetch.test.js
- web/tests/timerender.test.js
Fixes: #18461, building off of #19151
design discussion on CZO [here](https://chat.zulip.org/#narrow/stream/101-design/topic/recent.20topics.20load.20more.20messages)
Open questions:
* [design] Do we want to show a special message when there are no messages left to fetch, or is it clear enough to remove the banner?
* [eng] What's the best way to center the loading spinner while allowing the button to be flexible width for i18n?
> recent conversations: Add button to fetch more messages.

- docs/subsystems/analytics.md
This doc was using a lot of references of to class names etc. without putting them in `<code>`, making it harder to read.
> docs: Use `code` syntax in analytics subsystem doc for readability.

- web/src/compose_setup.js
> compose_setup: Hide compose formatting popover clicking an option.

- web/src/global.d.ts
Commit 747b62d0508737254fa31899c044b32e7269dc0d (#27124) removed the code.
> global: Remove type stub for Bootstrap modal

- web/src/click_handlers.js
- web/templates/left_sidebar.hbs
Fixes: 
**Issue:** #25647 
- The issue was `toggle_private_messages_section_icon` was not keyboard focusable. So making it keyboard accessible also correctly handled the enter key press scenario through the hotkey.js to treat it the same way as a click, correctly togging the current state of the PM list.
- Also, it was suggested that we smartly use [Element closest](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest) for show_all_private_messages to early return for both mouse click and keyboard click scenarios.
https://github.com/zulip/zulip/assets/26189424/6df0b7ab-f945-46ca-b98b-286929903d67
<details> …
> "All direct messages" should work with keyboard

- zerver/tests/test_user_groups.py
Python evaluates function parameter defaults at definition time, not call time. This function wouldn’t work with other realms anyway.
> test_user_groups: Fix database access outside test function

- web/src/inbox_ui.js
If the last returned value of `insert_stream` was false, `has_topics_post_filter` was false and hence this empty text was visible.
We only need one of the inserted streams to visible to hide the empty text.
Reproducer:
* Mark all messages as read.
* mark one message in denmark as unread.
* mute #support (any stream that would come later to denmak alphabetically)
* sent a message support from a different user while inbox is open.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Inbox.20no.20messages.20incorrect.20in.20pinned.20tab
> inbox: Fix empty text visible with visible unread rows.

- web/src/user_topics_ui.js
Rerendering of "all messages" is slow, and by definition, not visible to the user, so make sure the browser gets an opportunity to rerender the content that is visible before starting that expensive computation.
Addresses https://chat.zulip.org/#narrow/stream/9-issues/topic/lag.20in.20closing.20topic.20menu.20after.20choosing.20following/near/1662023
> user topics: Delay rerendering all messages.

- help/configure-default-new-user-settings.md
- help/configure-organization-language.md
[CZO thread](https://chat.zulip.org/#narrow/stream/31-production-help/topic/default.20language.20for.20new.20users/near/1649589)
This PR replaces #27080.
- https://chat.zulip.org/help/configure-default-new-user-settings
> help: Add documentation on configuring default language for new users

- analytics/views/support.py
This function was used in the html template in an early version of PR #27033 but then ended up unused and didn't get cleaned up.
> remote_support: Remote redundant remote_installation_stats_link context.

- help/typing-notifications.md
Fixes #27163.
Current: https://zulip.com/help/typing-notifications
Updated:
> help: Document newly implemented stream typing notifications.

- help/delete-a-message.md
- help/restrict-message-editing-and-deletion.md
- help/view-your-bots.md
This is a follow-up PR to document the new feature added in #26008.
Fixes: #27189.
- https://zulip.com/help/delete-a-message
- https://zulip.com/help/view-your-bots
<details>
</details>
> help: Document bot owners can delete messages sent by their bots.

- help/start-a-call.md
- web/src/compose_call_ui.js
- web/templates/compose_control_buttons.hbs
- web/templates/settings/organization_settings_admin.hbs
- web/tests/compose_video.test.js
This changes:
* The compose-box call button tooltip to read "Add voice call"
* The settings menu to reference "Call provider"
* The help docs to reference the new "Call provider" label in the settings menu
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/audio-only.20calls/near/1663648)
Compose-box call button tooltip:
Settings menu label:
Start a call provider documentation:
<details> …
> Change "audio" references to "voice"

- web/src/stream_edit.js
Fixes a regression exposed by eb6ac7bd98089bf08556b66fa7255e64e2cda2c4 (#27053).
[Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/Error.20while.20muting.20stream/near/1665169).
> stream_edit: Fix set_stream_property usage

- web/src/compose.js
- web/src/compose_banner.ts
- web/src/compose_notifications.js
- web/src/compose_setup.js
- web/src/echo.js
- web/src/transmit.js
- web/templates/compose_banner/automatic_new_visibility_policy_banner.hbs
- web/tests/compose.test.js
Fixes the first two checkbox of #26900 
[screen-capture (1).webm](https://github.com/zulip/zulip/assets/56781761/3b9cb3a0-6378-4262-964c-094ba18d40ff)
<details>
</details>
> compose_banner: Show banner when automatically follow or unmute a topic. 

- web/styles/portico/hello.css
Original:
| --- | --- |
| <img width="673" alt="Screenshot 2023-10-20 at 8 07 57 AM" src="https://github.com/zulip/zulip/assets/25124304/4562d32a-1ebd-4809-a186-9624c296fede"> | <img width="673" alt="Screenshot 2023-10-20 at 8 08 23 AM" src="https://github.com/zulip/zulip/assets/25124304/0256863d-8e4a-40a0-9bd1-2e3934ffa06e"> |
> Minor fixes to hello page.

- zerver/openapi/openapi.py
- zerver/tests/test_events.py
It’s unused since commit a881918a05503574d144fd90669e3a60d8d07684 (#24979).
> openapi: Remove unused display_brief_error parameter

- web/src/recent_view_ui.js
- web/src/resize.js
- web/src/views_util.js
This seems to have left out in the renaming of recent view from
recent table -> recent conversations -> recent view.
`recent_view_filters_height` being `0` resulted in table having
more height than it should have, so when focus was set on a
hidden row, it somehow scrolled the whole table.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Row.20of.20buttons.20disappear.20in.20.22Recent.20conversations.22
> resize: Use correct id for recent view filter buttons.   @amanagr

- web/src/page_params.ts
- web/src/people.ts
- web/src/typeahead_helper.js
- web/templates/typeahead_list_item.hbs
- web/tests/composebox_typeahead.test.js
- web/tests/people.test.js
- web/tests/typeahead_helper.test.js
This PR adds the pronouns custom profile field to the typeaheads in the composebox along with the necessary node tests.
Details of the implementation:
- Added logic to display pronouns in ( ) after status emoji but before the user's email (if present) when the user has a non-empty pronoun-type custom profile field.
- If multiple pronoun fields exist in the organization, the implementation selects the one earlier in the list of custom profile fields.
- No pronouns are displayed if the selected pronoun field is empty.
Fixes: #26924
[CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/feature.20request.3A.20.60.40name.60.20shows.20pronouns/near/1591147)
- Normal
- When the pronouns field is empty
- When multiple pronouns exist and the order …
> compose: Show pronouns in compose typeaheads.

- zerver/lib/email_notifications.py
- zerver/tests/test_message_notification_emails.py
- zproject/default_settings.py
This change removes the setting SEND_MISSED_MESSAGE_EMAILS_AS_USER
to improve the notification email that users receive when they get
a mention in a stream with the setting set to True.
Originally, this was how the notification emails worked and that
has been changed in commit number:
https://github.com/zulip/zulip/commit/797a7ef97bda8cfcc87cb25f9e870fe7558e7739
The footer and from address of emails that are sent when this
setting is set to True are confusing especially when more people
are involved in a stream and since we have changed the way we send
emails, it should be removed. It’s also not widely used.
Fixes:https://github.com/zulip/zulip/issues/26609
<details> …
> email: Drop support for SEND_MISSED_MESSAGE_EMAILS_AS_USER.

- web/src/invite.ts
- web/src/tippyjs.js
- web/styles/dark_theme.css
- web/styles/zulip.css
- web/templates/copy_invite_link.hbs
Added a "Copied!" confirmation tooltip for "Copy link" button in the "Invite users" modal.
Fixes: Issue #26872
Remaining: The tooltip is now in top position, might want to move the tooltip to bottom because the before "Copy link" tooltip is in the bottom position.
Screenshot:
> Added "Copied!" confirmation for user invite link

- web/src/hashchange.js
- web/src/modals.ts
Modals like those for Read receipts, Schedule message, Message edit history, User profile, etc would not close when the hash changed.
Now we close any active modal whenever the hash changes; we add a new function in `modals.ts` to do this, and call it from `hashchange.js`.
Fixes: [Issue described here on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Read.20receipts.20popover.20persists.20on.20going.20back.20in.20history)
<details> …
> popovers: Fix bug where modals persisted on hashchange.

- help/include/change-password-via-email-confirmation.md
- templates/zerver/emails/find_team.html
- templates/zerver/emails/find_team.txt
This suggests resetting the user's password, rather than contacting support, if a user has trouble logging in after finding their account. (Proposed by @timabbott )
- Should this be implemented with a variable for the help center URL? I wasn't sure where to put it if so.
> emails: Suggest resetting password if having trouble logging in.

- help/keyboard-shortcuts.md
- tools/test-js-with-node
- web/src/activity_ui.js
- web/src/compose_actions.js
- web/src/gear_menu.js
- web/src/hotkey.js
- web/src/message_actions_popover.js
- web/src/navbar_help_menu.js
- web/src/navbar_menus.js
- web/src/personal_menu_popover.js
- web/src/popover_menus.js
- web/src/popover_menus_data.js
- web/src/search.js
- web/src/stream_list.js
- web/src/ui_init.js
- web/src/user_card_popover.js
- web/styles/popovers.css
- web/styles/search.css
- web/styles/zulip.css
- web/templates/gear_menu_popover.hbs
- web/templates/keyboard_shortcuts.hbs
- web/templates/navbar.hbs
- web/templates/navbar_help_menu.hbs
- web/templates/personal_menu.hbs
- web/templates/tooltip_templates.hbs
- web/tests/compose_actions.test.js
- web/tests/stream_search.test.js
While gear menu is open, press right arrow to go to personal menu and left arrow to open gear menu again.
discussioN: https://chat.zulip.org/#narrow/stream/101-design/topic/keyboard.20nav.20for.20personal.20menu
> hotkey: Make g + left / right arrow work to open navbar dropdowns.

- help/manage-user-stream-subscriptions.md
- zerver/lib/markdown/tabbed_sections.py
Fixes #26902
- Documents the procedure to subscribe / unsubscribe a user via their profile and general stream settings.
- Both methods are separated into tabs in the documentation.
- Earlier only one of the method was documented for subscribing and unsubscribing.
Link to the current [documentation](https://zulip.com/help/manage-user-stream-subscriptions)
---
<details>
<summary>Previous Look</summary>
</details>
<details>
<summary>After updating the docs</summary>
</details>
---
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commi …
> help: Improve user stream management docs

- help/follow-a-topic.md
- help/include/automatically-follow-topics.md
- help/include/automatically-unmute-topics-in-muted-streams.md
- help/include/configure-notifications-for-followed-topics.md
- help/include/configure-topic-notifications-desktop-web.md
- help/include/configure-topic-notifications.md
- help/include/manage-configured-topics-desktop-web.md
- help/include/manage-configured-topics.md
- help/include/sidebar_index.md
- help/mute-a-topic.md
- help/topic-notifications.md
- web/templates/settings/notification_settings.hbs
- web/templates/settings/user_topics_settings.hbs
- Updates `follow-a-topic.md` adding Markdown include blocks for reusability in `mute-a-topic.md`.
- Adds a "Topic notifications" page, just under "Stream notifications" in the left sidebar, using Markdown include blocks for reusability in `follow-a-topic.md` and `mute-a-topic.md`.
- Adds a tip block to clarify that disabling followed topic global settings will not stop notifications if you already have stream level settings enabled.
- Updates the `?` link on "Topic notifications" and "Topic settings" to go to the new /help/topic-notifications page.
- Adds links to /help/follow-a-topic and /help/mute-a-topic.
Fixes: #27297.
- http://chat.zulip.org/help/follow-a-topic
- http://chat.zulip.org/help/mute-a-topic …
> help: Document settings to automatically unmute and follow topics.

- zerver/actions/create_user.py
- zerver/tests/test_invite.py
- zerver/tests/test_users.py
Fixes #27243
Fixes:  Use silent mentions in personal notification that invite was accepted.
Added new query because my change requests for user_profile.full_name 
sql: SELECT "zerver_userprofile"."id", "zerver_userprofile"."full_name" FROM "zerver_userprofile" WHERE ("zerver_userprofile"."is_active" AND "zerver_userprofile"."realm_id" = 2 AND UPPER("zerver_userprofile"."full_name"::text) = UPPER('Fred Flintstone'))
| --- | --- |
| ![Screenshot from 2023-10-17 23-51-36](https://github.com/zulip/zulip/assets/90370535/ab735651-dd68-4cb2-9dae-0423b47905fa)| ![Screenshot from 2023-10-17 14-19-35](https://github.com/zulip/zulip/assets/90370535/89aa45d3-e0b6-4f23-a33f-5b2a575e565f)
<details> …
> create_user: Use silent mentions in personal notification.

- web/templates/settings/add_new_bot_form.hbs
The tooltip is removed from the '?' and it is linked to the help path.
Fixes: #27047
<details>
</details>
> typo: change bot-type link to help center docs.

- web/styles/left_sidebar.css
- web/templates/left_sidebar.hbs
This PR establishes a grid-based layout for the expanded views navigation, in addition to referencing the new icons introduced in #27190, with the condensed views.
It ensures correct and uniform horizontal and vertical alignment of the vdots icons up and down the left sidebar.
As an [addendum](https://chat.zulip.org/#narrow/stream/101-design/topic/Make.20views.20section.20collapsible.20feedback/near/1668229), icons for the condensed views are bumped up in size to 15px.
Once this PR is merged, there will remain only three areas of the left-sidebar for gridded row rewrites:
* Direct Messages header
* Direct messages rows
* Streams header
In the screenshots below, you'll see slight misalignment of those areas (e.g., the direct messages row text is further to the right than the names of …
> left sidebar: Set new icons and grid-based layout on expanded views rows

- web/styles/popovers.css
before:
after:
I think Vlad wanted to use different top / bottom paddings according to the this font used in the figma which we don't use in Zulip.
> help-menu: Center align keyboard shortcut hint.

- web/src/left_sidebar_navigation_area.js
- web/src/left_sidebar_navigation_area_popovers.js
- web/src/popover_menus.js
- web/src/server_events_dispatch.js
- web/src/ui_init.js
- web/styles/left_sidebar.css
- web/templates/left_sidebar.hbs
- web/templates/popovers/left_sidebar_all_messages_popover.hbs
- web/templates/popovers/left_sidebar_inbox_popover.hbs
- web/templates/popovers/left_sidebar_recent_view_popover.hbs
- web/tests/dispatch.test.js
- web/tests/lib/events.js
> Make home view configurable from left sidebar

- web/src/recent_view_ui.js
Since we now have empty text message as a table row, `$topic_rows.length === 0` no longer works to test if the table is empty.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.22Compose.20message.22.20in.20empty.20inbox
> recent_view_ui: Return if the list is empty.

- zerver/openapi/zulip.yaml
[CZO Discussion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/.2326900.20compose.20banner.20on.20automatic.20follow.2Funmute/near/1666571)
Changes include:
* Explicitly mention that the new visibility policy is still sent as `user_topic` event.
* Adds a link as a way to understand the meaning of the enum values '2' and '3'.
<details><summary>Docs</summary>
</img>
</details> 
<details>
</details>
> api_docs: Update the docs for the `POST /messages` response.

- zerver/openapi/openapi.py
- zerver/openapi/zulip.yaml
Adds a deprecated changes note to the three bulk mark as read endpoints in the API documentation and removes the out of date link/reference to the bulk mark messages as read endpoints in the main description for the [update personal message flags](https://zulip.com/api/update-message-flags) endpoint.
See [CZO discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/deprecate.20and.20remove.20legacy.20unread.20endpoints.2C.20.2323598/near/1641286).
Part of work on [#23598](https://github.com/zulip/zulip/issues/23598).
<details>
<summary>Mark messages in topic as read endpoint main description</summary>
[Current documentation](https://zulip.com/api/mark-topic-as-read)
</details>
<details>
<summary>Mark messages in stream as read endpoint …
> api-docs: Document bulk mark as read endpoints as deprecated.

- web/e2e-tests/admin.test.ts
- web/e2e-tests/copy-and-paste.test.ts
- web/e2e-tests/lib/common.ts
- web/e2e-tests/realm-creation.test.ts
- web/e2e-tests/realm-playground.test.ts
- web/e2e-tests/settings.test.ts
- web/e2e-tests/user-status.test.ts
- web/shared/src/typing_status.ts
- web/src/billing/billing.ts
- web/src/billing/helpers.ts
- web/src/billing/upgrade.ts
- web/src/input_pill.ts
- web/src/list_widget.ts
- web/src/messages_overlay_ui.ts
- web/src/modals.ts
- web/src/portico/portico_modals.ts
- web/src/portico/signup.ts
- web/src/realm_playground.ts
- web/src/stats/stats.ts
- web/tests/billing.test.js
- web/tests/input_pill.test.js
- web/tests/list_widget.test.js
There are 7 remaning unchecked casts, of which 3 are in `debug-require-webpack-plugin.ts` and can probably be removed with some investigation of the webpack API:
https://github.com/zulip/zulip/blob/db05d7ef0c8dad631687f32623930a17c0830e47/web/debug-require-webpack-plugin.ts#L23-L53
and 4 are in `list_widget.ts` and are hiding an observable functionality bug (sorting muted users by date in settings doesn’t work) that needs further work:
https://github.com/zulip/zulip/blob/db05d7ef0c8dad631687f32623930a17c0830e47/web/src/list_widget.ts#L128-L155
So it looks like linting against unchecked casts would be reasonable.
> Remove almost all unchecked casts in TypeScript

- templates/zerver/emails/onboarding_team_to_zulip.html
- templates/zerver/emails/onboarding_team_to_zulip.subject.txt
- templates/zerver/emails/onboarding_team_to_zulip.txt
- zerver/lib/email_notifications.py
- zerver/models.py
- zerver/tests/test_email_log.py
- zerver/tests/test_email_notifications.py
- zerver/tests/test_example.py
- zerver/views/development/email_log.py
Updated version of #26713, which adds a new onboarding email `onboarding_team_to_zulip` for the user who created the new Zulip organization. This PR squashes the commits and updates the text version for the updated HTML version text.
Currently, the URLs in the text version of this new email are in angle brackets ("<") except for the unsubscribe link at the bottom of the email; see [CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/URLs.20in.20plain.20text.20versions.20of.20emails/near/1664341) about how we may want to standardize how we format links in the text versions of emails in general.
Email subject line, which is not in the screenshots, is **Choosing the chat app for your team**.
<details>
<summary>HTML version in dev …
> onboarding-emails: Add new onboarding email for organization creator.

- help/inbox.md
- help/include/all-messages.md
- help/include/go-to-all-messages.md
- help/include/go-to-draft-messages.md
- help/include/go-to-inbox.md
- help/include/go-to-recent-conversations.md
- help/include/go-to-scheduled-messages.md
- help/include/inbox-instructions.md
- help/include/recent-conversations.md
- help/include/view-mentions.md
- help/include/view-starred-messages.md
- help/marking-messages-as-read.md
- help/schedule-a-message.md
- help/view-and-edit-your-message-drafts.md
- help/view-your-mentions.md
This PR replaces special links with include / instructions blocks so that users can learn how to access views in the left sidebar from the documentation.
Fixes #27326.
Fixes part of #27359.
**Notes:**
For **Inbox**, **Recent Conversations**, and **All messages** views, I added the keyboard shortcut as part of the instruction so that it doesn't look too cluttered since these sections already have other `tips`. Similarly, I think a single-line instruction for **Drafts** and **Scheduled Messages** would work best.
- http://chat.zulip.org/help/inbox
- http://chat.zulip.org/help/recent-conversations
- http://chat.zulip.org/help/all-messages
- http://chat.zulip.org/help/view-your-mentions
- http://chat.zulip.org/help/star-a-message
- …
> help: Update Views docs for logged-in users and document collapsed views.

- web/src/unread_ui.js
- web/styles/dark_theme.css
- web/styles/zulip.css
This implements an unread dot and redesigned icon colors, including for hover and visible focus interactions, for the left-sidebar/streams toggle.
It also corrects some layout issues with the revealed sidebars under certain conditions. Note that those fixes are to a certain degree stop-gap. Forthcoming layout work in the right sidebar will result in a pixel-perfect vertical alignment shared with both the VIEWS and USERS headings.
Finally, there's a commit that just removes a bit of unnecessary cruft related to the users toggle--colors and interactions there are already handled using CSS variables.
Fixes: #27357
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/unread.20counts.20in.20top.20bar/near/1663455); also [regarding dark mode …
> navbar: Redesign left-sidebar toggle and unread indicator.

- web/src/input_pill.ts
This PR aims at resolving the issues of irregularities in the Stream Membership input field, along with fixing the **Select all and backspacing issue**
Fixes: [#19544](https://github.com/zulip/zulip/issues/19544) Stream membership input: Selecting all text and backspacing does nothing.
**BEFORE FIX**:
- ```ctrl+a``` backspace  doesn't work but if selection made from any point except starting point, and ```backspace pressed```, it works fine.
- After one or more pills are added, and then the ```ctrl+a``` backspace is done for remaining text, it removes the Last Pill rather than the text.
- If the input being entered has a TYPEAHEAD, then it ```ctrl+a``` backspace works as expected:
**REASON FOR BEHAVIOR**: 
- This irregularity in the Stream Membership Input occurs only when Backspace is …
> stream-membership-input: Fix selecting all text and backspacing.

- analytics/tests/test_activity_views.py
- analytics/views/installation_activity.py
- templates/analytics/activity.html
- templates/analytics/realm_summary_table.html
Removed "Durations" tab from the main installation activity page.
**Notes**:
- Since there's now only one tab on the installation activity page, updated the template (`/activity.html`), which is also used for the realm and user activity pages, to only create tabs for pages that aren't the "home" view. Also, changed the page title string to be "Installation Activity" instead of "Activity".
- Removed the DAT/DAU (hr) and DAT (hr) columns from the realm summary chart.
- Added a comment to the `user_activity_intervals` function that did the database query to get the data for the "Durations" tab and the above columns to explain why the function isn't currently in use. Alternatively, we could just delete the function with these changes.
<details>
<summary>Updated installation activity page in …
> analytics: Remove "Durations" tab and hourly columns.

- web/src/input_pill.ts
- web/tests/input_pill.test.js
We should remove this overly defensive code and remove the `undefined` type from the return type of this function to avoid handling unexpected `undefined` values in the downstream code.
[CZO Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/input_pill.20typescript).
<details>
</details>
> input_pill: Remove over defensive if checks for `create` function.

- web/templates/recent_view_row.hbs
`recent_view_focusable` class should be set on element whose children can receive focus as per
`$topic_row.find(".recent_view_focusable").eq(col).children().trigger("focus")`
> recent_view: Fix user unable to focus change_visibility_policy icon.

- analytics/views/installation_activity.py
- corporate/lib/analytics.py
- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
Moves two functions in `corporate/lib/stripe.py` that are used for the main analytics installation activity page to a separate file: `corporate/lib/analytics.py`.
Also, updates these functions for the possibility of realm being `None` for a `Customer` object.
**Notes**:
- These two functions are only used for the installation activity page data.
- A follow-up (or additional change to add to this PR) could be to combine these two functions so that only one database query is made. I'm pretty sure the `CustomerPlan` query could return the discount information as well as the projected annual revenue.
- There is a `corporate/lib/support.py` file that only has one function currently, and I thought about moving these two functions there. But keeping the support and analytics logic (in the …
> corporate: Move functions for realm installation data to new file.

- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
Updates query in `downgrade_small_realms_behind_on_payments_as_needed` to exclude `Customer` objects with `realm=None`.
<details>
</details>
> corporate: Exclude non-realm `Customer` objects in downgrade small realms.

- web/e2e-tests/compose.test.ts
- web/src/click_handlers.js
- web/src/pm_list.js
- web/src/pm_list_dom.ts
- web/src/stream_list.js
- web/src/tippyjs.js
- web/styles/dark_theme.css
- web/styles/left_sidebar.css
- web/templates/left_sidebar.hbs
- web/templates/more_pms.hbs
- web/templates/pm_list_item.hbs
- web/tests/pm_list.test.js
- web/tests/vdom.test.js
This PR renames classes and IDs and a couple of related functions to use "direct message" references, rather than "private messages." There are no visual or behavioral changes here; these adjustments are only make the innermost DM rows read better, while some temporary styles maintain the current layout--though those will be removed in the row work these commits prepare for.
As these changes are focused on the innermost DM rows, there are a couple of places where this PR leaves an awkward blend of direct- and private-message references. Those blended classes will be cleaned up in subsequent work on gridding the DM heading area.
File names are another consideration; those changed here still all reference _pm_, but there is a [CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/ …
> left_sidebar: DM rows structural prep.

- web/styles/portico/hello.css
before:
after:
discussion:
https://chat.zulip.org/#narrow/stream/137-feedback/topic/landing.20page
> hello: Make logos more visible in light theme.

- web/styles/zulip.css
This PR addresses the case where the use of alpha channels in HSL color values shows its limits. Specifically, [it corrects the faint "halo" visible](https://github.com/zulip/zulip/pull/27390#issuecomment-1781444484) due to a color mismatch on the border around the unread dot.
The use of an alpha channel is necessary for the background elements for the top navbar elements, because they sit over the top of the navbar's bottom border (actually an inset shaddow).
However, it's impossible to use the alpha-channel based color on elements like the unread dot, where the border actually sits on top of the element itself--meaning that the effect would be a larger dot with an imperceptibly darker ring around it.
What this commit does is use a technique suggested by Anders Kaseorg for using CSS's …
> navbar: Correct for alpha background on unread dot's border.

- web/src/user_status.ts
There’s no such thing as a numeric object key in JavaScript.
Cc @Lalit3716 (#26776)
> user_status: Remove useless number coercion for object keys

- corporate/lib/stripe.py
- corporate/lib/stripe_event_handler.py
- corporate/models.py
- corporate/tests/test_stripe.py
- corporate/views/upgrade.py
Refactors `ensure_realm_does_not_have_active_plan` to instead directly check the customer: `ensure_customer_does_not_have_active_plan`,
**Notes**:
- Prep commit that updates the `__str__` method on the Customer model to account for Customer objects with `realm=None`.
- `ensure_realm_does_not_have_active_plan` was first getting the Customer for the Realm, so these changes are just removing that circular step since in all the places the function was used there was already (or would be) a customer object.
- The new function uses the updated Customer string for the billing_logger warning if there is error raised.
<details> …
> corporate: Refactor ensure_realm_does_not_have_active_plan.

- help/change-a-users-name.md
- help/change-a-users-role.md
- help/deactivate-or-reactivate-a-user.md
- help/include/manage-user-tab-tip.md
- Adds instructions tab for reactivating a user via the user profile.
- Simplifies instructions for deactivating a user.
**Notes**
- There seems to be a bug when clicking on **Reactivate this user** in the three dot menu of a deactivated user's card; the user card just goes away and then nothing happens.
Fixes #26906.
- http://chat.zulip.org/help/deactivate-or-reactivate-a-user
<details>
</details>
> help: Document reactivating a user via user profile.

- api_docs/changelog.md
- version.py
- zerver/actions/create_user.py
- zerver/actions/streams.py
- zerver/lib/stream_subscription.py
- zerver/lib/streams.py
- zerver/lib/test_classes.py
- zerver/openapi/zulip.yaml
- zerver/tests/test_events.py
- zerver/tests/test_invite.py
- zerver/tests/test_subs.py
Previous behavior-
- Guest did not receive stream creation events for new web-public streams.
- Guest did not receive `peer_add` and `peer_remove` events for web-public and subscribed public streams.
This PR fixes the behavior to be -
- Guests now receive stream creation events for new web-public streams.
- Guest now receive `peer_add` and `peer_remove` events for web-public and subscribed public streams.
<details>
</details>
> streams: Fix sending stream-related events to guests.

- tools/lib/capitalization.py
- web/src/composebox_typeahead.js
- web/tests/composebox_typeahead.test.js
Fixes: #27399.
<details>
</details>
> compose: Add a placeholder "is …" for the `/me` slash command.

- zerver/openapi/zulip.yaml
Updates the description of the `update_message_flags op: add` event in the get events documentation; see [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/unreads.3A.20messages.20from.20muted.20users.3F/near/1660912).
@gnprice and @chrisbobbe mentioning you here for a review these changes. I did make a few small edits and added some more links to the text drafted in the conversation in CZO (linked above).
<details>
<summary>Updated update_message_flags op: add description</summary>
[Current documentation](https://zulip.com/api/get-events#update_message_flags-add)
</details>
---
<details> …
> api-docs: Update description for update_message_flags add event.

- web/src/input_pill.ts
This commit fixes the behavior of trying to remove the selected text when selection is made from start in stream membership input and compose box dm using backspace button.
Previously the selected text was not removed if no typeahead was shown for the text and it instead removed the last pill.
Now we remove the selected text and not any input pills on pressing the backspace button irrespective whether tyepeahead is shown or not.
This commit updated the code to remove pill only when there is no other text or when the pointer is at start of input but its selection
length is 0, in the input and let it follow the default behavior in
cases when there is any text (other than user pills) in the input to fix the bug.
Fixes: [#27403](https://github.com/zulip/zulip/issues/27403) Irregular behaviour …
> input_pill: Fix backspace behavior on selecting text from start.

- web/src/recent_view_ui.js
If the user has no messages, `message_list_data` can be empty, so, in that case, we just use the current oldest_message_timestamp.
The bug can also be reproduced if the last 400 messages were
in a muted topic for the user and we process recent_view_message_list_data
before all messages data.
We still process the remaining logic `set_oldest_message_date` to update has_found_newest/oldest.
> recent_view: Fix error when user has no messages.

- web/src/integration_url_modal.js
Instead of using the stream name for the incoming webhook URL that is generated in the web-app, we used the stream ID instead.
Also, limits the streams listed in the dropdown widget to streams that the bot owner has permission to post in.
**Notes**:
- The [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), which is being used to append the stream ID and topic to the URL, encodes spaces as `+` in the search query. In the screenshots, one can see that other reserved characters are being encoded.
<details>
<summary>Example with Iago - can post in #announce stream</summary>
</details>
<details>
<summary>Examples with Aaron - can't post in #announce stream</summary>
</details>
<details> …
> integrations: Use stream ID for incoming webhook URL generated in modal.

- zerver/openapi/zulip.yaml
Tweaks to the doc as suggested by @gnprice in the post-merge comments at the end of https://github.com/zulip/zulip/pull/26697
> send_test_push_notification_api: Fixes to the API endpoint doc.

- help/include/reading-conversations.md
- help/keyboard-shortcuts.md
- web/src/hotkey.js
- web/src/narrow.js
- web/src/topic_generator.js
- web/templates/keyboard_shortcuts.hbs
- web/tests/hotkey.test.js
- web/tests/topic_generator.test.js
This PR adds a `Shift + N` keyboard shortcut, which is used to narrow to the next unread followed topic.
Fixes part of #27323.
---
<details><summary> ? Menu</summary>
</img>
</details> 
<details><summary>/help/keyboard-shortcuts#the-basics</summary>
</img>
</details> 
---
<details>
</details>
> hotkey: Add 'narrow to next unread followed topic' hotkey.

- zerver/webhooks/gitlab/view.py
> gitlab: Description can be none.

- web/styles/left_sidebar.css
- web/templates/left_sidebar.hbs
- web/templates/pm_list_item.hbs
This PR applies CSS Grid to the DM rows. This brings DMs in line with the navigation, streams, and topic rows, and for the first time, introduces a uniform alignment of icons, labels, and unreads up and down the left sidebar.
Additionally, as a bit of a piggy-back, this PR includes a commit that displays the navigation tooltips fully to the side of the expanded nav items--bringing that in line with the tooltips on DM rows, which this PR also corrects.
| Before | After | 
| --- | --- |
| <img width="295" alt="lsb-dm-rows-before" src="https://github.com/zulip/zulip/assets/170719/d7bd53fd-a4d0-4ce4-ad43-f6b724c88e0c"> | <img width="295" alt="lsb-dm-rows-after-more-convo-fix" src="https://github.com/zulip/zulip/assets/170719/0f01f305-3fac-4702-89df-4115a124 …
> left_sidebar: Set grid on DM rows.

- help/insert-a-link.md
- zerver/lib/markdown/tabbed_sections.py
- Adds a "Via paste" tab to document the new functionality.
Fixes #26892.
- http://chat.zulip.org/help/insert-a-link
<details>
</details>
> help: Document option to paste URL to create a named link.

- help/change-your-language.md
Documents how to figure out whether the Zulip font supports a language and what to do about unsupported languages, providing links to official font / browser documentation rather than step-by-step instructions in case the instructions change.
Fixes #26986.
Replaces #27322.
- http://zulip.com/help/change-your-language
<details>
</details>
> help: Document font configuration for unsupported languages.

- help/direct-messages.md
- help/include/how-to-start-a-new-topic.md
- help/include/send-group-dm.md
- help/open-the-compose-box.md
- Documents the new contextually-aware button since the instructions now differ depending on whether you're currently in a direct message view or not.
- Simplifies the new topic instructions by combining the first two tabs into a single web/desktop tab, with an optional step 2 to change the destination stream.
Fixes #27159.
- http://zulip.com/help/starting-a-new-topic
- http://zulip.com//help/starting-a-new-direct-message
- http://zulip.com/help/direct-messages
- http://zulip.com/help/open-the-compose-box
> help: Document "Start new conversation" button.

- web/src/stream_edit.js
- web/styles/subscriptions.css
- web/templates/settings/notification_settings.hbs
- web/templates/stream_settings/stream_settings.hbs
- web/templates/stream_settings/stream_settings_checkbox.hbs
This PR includes the following changes:
- Allow the user to interact with notification settings for muted streams.
- Add "In muted streams, stream notification settings apply only to unmuted topics." line of text in stream settings and decreases the space between "Notification Settings" heading and text.
- Append "In muted streams, stream notification settings apply only to unmuted topics." line of text in notification settings.
Fixes: #27272 …
> stream_edit: Enable notification settings for muted streams.

- web/src/stream_edit.js
- web/templates/stream_settings/stream_settings_checkbox.hbs
> [!WARNING]  
> In this PR, the "Mute stream" option has been moved to "Notification settings." When the mute stream option is enabled, the notification settings become disabled, including the Mute stream's own checkbox. This leads to a self-restricting state where unmuting the stream is no longer possible. Therefore, #27272 should be considered as a blocker for this PR.
This PR adds the following changes:
- Move "Mute stream" to the top of the "Notification settings" section
- Add a help `?` link to /help/mute-a-stream beside the "Mute stream" label.
- Drop the "Muted streams don't show up in "All messages" or generate notifications unless you are mentioned." text for muted streams.
Fixes: #27274
|Not Muted| Muted | …
> stream_settings: Improve "Mute stream" option UI in stream settings

- web/src/hotkey.js
When the focus is inside a dropdown, we do not consider any key strokes to be hotkeys.  This prevents the user from accidentally triggering an action while trying to type into the dropdown search / filter.
This aims to fix the bug where on pressing a character key that is also a hotkey, the hotkey action would be triggered, even if the focus was inside the stream picker dropdown.
Fixes: #27492 
(The solution implemented here is different to the one proposed in the linked issue)
<details>
Completed …
> compose: Disallow hotkeys when dropdowns (like stream pickers) are open.

- web/src/message_viewport.js
- web/src/personal_menu_popover.js
- web/src/popover_menus.js
- web/src/recent_view_ui.js
- web/src/resize_handler.js
There are few things to notice:
* It doesn't work perfectly for resize as the `reference` can hide during the reisze which triggers the popover to hide, but I don't think that's a real issue since for mobile overlay popovers, it works to not hide the popovers with `show-when-reference-hidden` class.
* If the reference goes under fixed / sticky element, but not outside the window, the popover would still be visible but the reference not. It is super expensive to do that check so, instead we just check compose, navbar or sticky message header not obscuring the reference which is where it makes a real difference.
> Don't hide popovers on scrolling / resize.

- .gitignore
- zproject/dev_settings.py
This lets us simplify the instructions for testing push notifications with a development client on iOS.
(They'll still be kind of annoying — see [current version](https://github.com/zulip/zulip-mobile/blob/9133ae3e5084969646db3985367d5a5e403b4498/docs/howto/push-notifications.md#ios), which comes after a different simplification I made today — but a couple of the later steps will go away.)
<details>
</details>
> push_notifs: In dev, automatically use dev APNs cert if provided

- zerver/models.py
- zilencer/management/commands/populate_billing_realms.py
Add various types of realms in different plan types and billing cycles. Useful for testing.
> populate_realm_db: Add script to add various types of realms.

- web/src/emoji_picker.js
Similar to emoji_picker.process_keypress, process_enter_while_filtering should have a stopPropagation.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/popover.20event.20propagation.20bug
> emoji_picker: Stop propagating enter keypress to message.

- web/styles/left_sidebar.css
- web/styles/zulip.css
This fixes a difficult-to-spot problem with the background color on unreads in the condensed view hover state. An alpha in dark mode was allowing the icon highlight to show through.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/condensed.20view.20dark.20mode.20unreads/near/1674956)
| --- | --- |
| ![detail-condensed-unread-hover-before](https://github.com/zulip/zulip/assets/170719/2797a33a-91ce-4cc5-b482-b2c6de681435) | ![detail-condensed-unread-hover-after](https://github.com/zulip/zulip/assets/170719/6cc592a6-600f-4219-b72b-293e3bd484b3) |
| ![condensed-unread-hover-before](https://github.com/zulip/zulip/assets/170719/990ab56d-a801-47b6-afa0-5bca76bb0420) | …
> left_sidebar: Display dark-mode condensed unreads without alpha.

- web/src/compose_tooltips.js
Fixes #27383
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/Micromodal.20returning.20focus.20to.20trigger.20.2327383
> compose_tooltips: Don't show tooltip on focus.

- web/src/left_sidebar_navigation_area.js
- web/src/sidebar_ui.js
- web/styles/left_sidebar.css
- web/templates/left_sidebar.hbs
- web/templates/popovers/left_sidebar_all_messages_popover.hbs
- web/templates/popovers/left_sidebar_inbox_popover.hbs
- web/templates/popovers/left_sidebar_recent_view_popover.hbs
- web/tests/left_sidebar_navigation_area.test.js
This PR places the selected home view both atop the expanded navigation list, and to the start of the flexbox (far left) of the condensed navigation list.
Additionally, it ensures that the unread count and "Mark all as read" vdots menu follows the selected home view.
[CZO Discussion](https://chat.zulip.org/#narrow/stream/137-feedback/topic/reordering.20views/near/1674084)
TODOs:
<details>
</details>
> left_sidebar: Place home view based on user preference.

- web/src/resize_handler.js
- web/src/scroll_bar.ts
ResizeObserver isn't supported for Safari iOS versions we support.
We support iOS Safari ≥ 12.2 but ResizeObserver support requires iOS Safari >=13.4. So if they're on iOS Safari >= 12.2 and < 13.4, it crashes.
> scroll_bar: Hook to window resize event instead of ResizeObserver.

- web/src/copy_and_paste.js
This commits ensures that we pass in the correct context (compose box or a message being edited) when pasting content.
Fixes: [Issue described in this CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/pasting.20bug.20for.20message.20editing)
<details>
</details>
> compose: Fix bug where pasted content would only go to the compose box.

- help/share-and-upload-files.md
- zerver/lib/markdown/tabbed_sections.py
- Replaces the "Via Markdown" tab with "Via drag-and-drop", and modifies the instructions to explain that you can drag and drop anywhere in the app, whether or not the compose box is open.
- Adds "Via paste" tab for the copy-pasting instructions.
Fixes #26894.
- https://zulip.com/help/share-and-upload-files
> help: Document ability to drag-and-drop anywhere to upload a file.

- web/styles/zulip.css
This fixes a bug introduced in #27520, which left hovered light-mode unreads without a background color in the condensed views row.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/unread.20count.20.28light.20theme.29.20on.20hover.20not.20visible/near/1675367)
| Light mode (fixed) | Dark mode (unchanged) |
| --- | --- |
| ![fixed-unreads-light](https://github.com/zulip/zulip/assets/170719/274e1bf1-dd40-4935-92f1-d296b589db28) | ![unreads-dark](https://github.com/zulip/zulip/assets/170719/aefc9535-1e3e-4151-9367-105caac86fc3) |
> left_sidebar: Align no-alpha variable for light mode unreads.

- web/src/copy_and_paste.js
- web/tests/copy_and_paste.test.js
If the selection copied, is entirely within a single element, like text within a heading (like `h1`) we discard this outermost element and only convert the inner HTML to markdown.
However, we retain `pre` so a code block within it stays as is and does not change into inline code, losing all its linebreaks.
Fixes: [Issue described in here on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Github.20issue.20number.20copy.20paste.20bug)
<details> …
> compose: Remove formatting enclosing entire selection when pasting.

- puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf
The colon is invalid syntax. Verified the updated policy using an online CSP checker.
> puppet: Fix buggy media-src Content-Security-Policy.

- corporate/lib/stripe.py
- corporate/views/session.py
- corporate/views/upgrade.py
Refactors `setup_upgrade_checkout_session_and_payment_intent` to be part of the `BillingSystem` abstract class.
**Notes**:
- Prep commit to replace `compute_plan_parameters` with `get_price_per_license` since that's the only information that `setup_upgrade_checkout_session_and_payment_intent` was using.
- Second commit moves the logic for creating `stripe.checkout.Session` and `Session` object to the `BillingSession` abstract class. This happens in three code paths: the initial upgrade for the 'charge automatically' path, if the initial card added to the account fails to charge, changing an existing card on account to a new card.
- Third commit moves the logic for creating `stripe.PaymentIntent` and `PaymentIntent` object to the `BillingSession` abstract class, which only happens in the …
> corporate: Move `setup_upgrade_checkout_session_and_payment_intent` to BillingSession class.

- zerver/actions/typing.py
- zerver/lib/test_classes.py
- zerver/tests/test_typing.py
The event for stream typing notifications is no longer sent to the long_term_idle subscribers of the stream.
This helps to reduce the tornado's work of parsing super-long JSON-encoded lists of user IDs in large streams. Now the lists are shorter.
<details>
</details>
> typing_notifications: Don't notify long_term_idle subscribers.

- web/src/emoji_picker.js
- web/src/popover_menus.js
- web/templates/popovers/emoji/emoji_popover.hbs
Fixes #11448
https://github.com/zulip/zulip/assets/25124304/8dc0d45a-90a4-42ed-a078-bace2c429073
Since focus on input elements on mobile opens keyboard which changes window height, emoji popover can hide or scroll out of view. To fix it, we don't focus on search input unless user wants to when emoji popover is open.
Tested on Chrome Android and Firefox Android.
> emoji_picker: Don't autofocus search input on mobile.

- web/src/compose_ui.js
- web/src/copy_and_paste.js
- web/tests/copy_and_paste.test.js
compose: Allow pasting plainly, when Shift is held down, for Firefox.
We introduce a state variable `shift_pressed` for the purpose of detecting whether the Shift key is pressed when pasting content. Only if it is not, do we proceed with the default formatted paste behavior.
In Chrome, plain paste works out of the box for `Ctrl+Shift+V`, but in Firefox, we need to handle it ourselves.
compose: Paste content into the compose box without adding any space.
We replace the call to `insert_syntax_and_focus` with a direct call to `insert_and_scroll_into_view` when pasting content into the compose box, which fixes the bug where leading and trailing spaces were added to any pasted content.
compose: Always retain `ol` tag when pasting content enclosed by it.
Fixes: [Issues discussed in this CZO …
> Paste improvements

- zerver/webhooks/slack/doc.md
- zerver/webhooks/slack_incoming/doc.md
This PR is based on #27599.
I rewrote the intro content for the Slack-compatible integration doc; my commit can be squashed if desired.
I did not make any changes to:
- Instructions
- The Slack integration doc
<details>
<summary>Slack integration doc (copied from #27599)</summary>
[Current documentation](https://zulip.com/integrations/doc/slack)
</details>
<details>
<summary>Slack-compatible integration doc</summary>
[Current documentation](https://zulip.com/integrations/doc/slack_incoming)
</details>
> Update both Slack integration articles (revised)

- help/start-a-call.md
- templates/zerver/integrations/jitsi.md
- web/templates/settings/organization_settings_admin.hbs
- Updates "Start a call", fixing misplaced include block for opening the compose box.
- Documents the "Jitsi server URL" setting, and links to it in a (?) from the relevant admin UI.
- Tweaks /integrations documentation, and clarifies that the "Jitsi server URL" setting is not just a server-side setting.
- Updates /integrations instructions to a series of steps to be followed directly, without having to go to the help center.
Fixes #26907.
- https://chat.zulip.org/help/start-a-call#change-your-organizations-video-call-provider
- https://zulip.com/integrations/doc/jitsi
- https://chat.zulip.org/#organization/organization-settings
<details>
Individual …
> help: Document "Jitsi server URL" setting.

- web/src/about_zulip.ts
- web/templates/about_zulip.hbs
Previously when a user tries to click on the clipboard to copy the merge base version info, the copied tooltip would appear in the wrong location where the Zulip version is instead. This is caused by both clipboard icon using the same Clipboard instance where the success event would only display the tooltip at the Zulip version. These changes fixes this and allows the clipboards to be independent of each other.
<details> …
> alerts: Fix improper copied tooltip location in About Zulip Modal.

- web/src/compose_ui.js
- web/tests/compose_ui.test.js
The commit resolves an issue in compose_ui with incorrect string formatting in the Intl.ListFormat implementation. The previous code was using .join(", "), which resulted in inconsistencies. This fix replaces the .join method with Intl.ListFormat for more accurate and localized list formatting.
**English**:
**Espanol:**
<details>
</details>
>  compose_ui: Use Intl.ListFormat rather than .join(", "). #27353 

- web/src/popover_menus.js
- web/templates/popovers/actions_popover.hbs
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Cannot.20copy.20link.20to.20message.20with.20keyboard
> actions_popover: Fix copy link not working on `enter` keypress.

- web/src/settings_notifications.js
- web/templates/settings/notification_settings_checkboxes.hbs
- web/templates/settings/stream_specific_notification_row.hbs
This PR enables the user to control notification settings of muted streams through the "Notification" section of Personal settings.
Fixes #27272.
**ScreenShots and screen captures:**
[settings.webm](https://github.com/zulip/zulip/assets/128511266/6013350a-deb8-434c-836d-41b0275ece13)
<details>
</details>
> settings_notifications: Allow users to modify notification settings of muted streams from "Personal settings"

- api_docs/changelog.md
- docs/production/mobile-push-notifications.md
- version.py
- zerver/lib/push_notifications.py
- zerver/tests/test_migrations.py
- zerver/tests/test_push_notifications.py
- zerver/views/push_notifications.py
- zilencer/migrations/0032_remotepushdevicetoken_backfill_ios_app_id.py
- zilencer/views.py
- zproject/default_settings.py
- zproject/test_extra_settings.py
The existing notifications code assumes that all iOS clients getting notifications through APNs have the same app ID. In particular all such notifications going through the bouncer are assumed to be for the same app ID, `org.zulip.Zulip`, which corresponds to the main Zulip mobile app.
For the new Flutter-based app, we have a separate app ID `com.zulip.flutter` we'll be using through the Flutter app's beta period, so that it can be installed alongside the existing app. In order to get notifications there, then (zulip/zulip-flutter#321), we'll need the same servers to be able to send notifications to both `org.zulip.Zulip` and `com.zulip.flutter`.
Some of the pieces needed for handling this are already present in the code — notably, an `ios_app_id` field on the `PushDeviceToken` model. In …
> Make push notifications work for multiple iOS app IDs

- web/src/popover_menus.js
The popover didn't open since sticky_header is part of message feed and we were hiding popovers if `elements_at_reference_position` had `sticky_header`. Now, we just don't do that check if the reference is part of sticky_header.
Super sorry for not checking popovers in sticky_header !
> popovers: Fix topic visibility popover in sticky header not working.

- analytics/tests/test_support_views.py
- analytics/views/support.py
- corporate/tests/test_remote_counts.py
- templates/analytics/remote_server_support.html
- zilencer/lib/remote_counts.py
This calculates the largest amount of messages sent within a month for the last 3 months. The query is targeted for the specific use-case in this function - for finding the count for a specific server. For calculating this in bulk for a large number of remote server an adapted, bulk query will be needed - rather than running this one in a loop, which would likely be very inefficient.
I took the bulk query designed by @alya in the discussion thread and tweaked it to suit this function which just queries for a single server, so it can be significantly simpler.
Here's a screenshot of the /support page with 3 different server, one of them missing the last 3 days of data:
> counts: Add function compute_max_monthly_messages for remote servers.

- web/src/message_edit.js
Bug reported here:
https://chat.zulip.org/#narrow/stream/464-kandra-js-errors/topic/Error.3A.20The.20partial.20.40partial-block.20could.20not.20be.20found/near/1673466
The issue was happening because `channel.xhr_error_message` can return the empty string sometimes, and `render_compose_banner` shows the banner text if it exists and otherwise tries to render a `@partial-block`. Unfortunately the empty string acts as falsy in the template, leading to the partial block error.
> message edit: Use a default error message for failed edits.

- zerver/lib/markdown/__init__.py
- zerver/lib/mention.py
- zerver/tests/test_markdown.py
Previously, when a deactivated user was mentioned, he wasn't rendered as a Pill. This is because the dataset for validating mentions only included active users, which is fixed by removing that filter.
To allow only silent mentions of them, an extra is_active property added to FullNameInfo class, which is populated from the query, which tells if user is deactivated. This is used to convert any mentions of them to silent mentions in the backend markdown.
Fixes: #26857 User pills for mentions of deactivated users
<details> …
> user_mention: Fix mentions of deactivated users.

- web/src/copy_and_paste.js
- web/tests/copy_and_paste.test.js
We add anchors to the list of enclosing elements we don't strip away.
Fixes: [Issue discussed here](https://chat.zulip.org/#narrow/stream/9-issues/topic/Github.20issue.20number.20copy.20paste.20bug/near/1677091)
<details>
</details>
> compose: Always retain link formatting when pasting just a link.

- web/styles/popovers.css
- web/styles/zulip.css
- web/templates/personal_menu.hbs
| --- | --- |
| <img width="369" alt="Screenshot 2023-11-01 at 11 44 38 AM" src="https://github.com/zulip/zulip/assets/25124304/fffd2cfa-96dd-451a-a14a-73e1a6335f35"> | <img width="369" alt="Screenshot 2023-11-01 at 11 42 58 AM" src="https://github.com/zulip/zulip/assets/25124304/32853adb-a442-4aa9-9bb0-4e32ce8606a6"> |
| <img width="369" alt="Screenshot 2023-11-01 at 11 44 30 AM" src="https://github.com/zulip/zulip/assets/25124304/cd0ecac2-9591-47d2-aeec-ea809d1ee15e"> | <img width="369" alt="Screenshot 2023-11-01 at 11 43 36 AM" src="https://github.com/zulip/zulip/assets/25124304/a35d2b13-cc1a-4990-b004-0909249d2de0">
> Personal menu status color changes

- scripts/lib/upgrade-zulip-stage-2
- zerver/lib/cache_helpers.py
Filling caches needs to happen close to when the server is restarted, as the gap opens us up to race conditions with user modifications.  If there are migrations, however, it must happen within the critical period after the migrations are applied.
Move the call to fill the caches to within the `shutdown_server` function, so that we push it as close to the server shutdown as possible.
<details>
</details>
> upgrade-zulip: Defer cache-filling to just outside the critical period

- web/src/left_sidebar_navigation_area_popovers.js
This adds click-handlers to the "Mark all messages as read" popover items for Recent conversations and All messages, which did not get them as part of #27501.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/mark.20all.20messages.20as.20read/near/1677814)
<details>
</details>
> left_sidebar: Register mark-all-as-read handlers on home views.

- web/src/lightbox.js
Presently in a session when an image or video title is updated, the same change is not reflected in the lightbox view of them, until a new session is made.
This is because the metadata of the media is stored in Map for the session with the ```preview_src``` as keys, and hence, when title is changed the ```preview_src``` being same, the title change is not reflected inside lightbox view.
This is fixed by modifing the ```asset_map``` (cache map) keys from ```preview_src``` to an array of ```preview_src```, and the media title. Hence, when title is modified now, the keys won't map to the existing value, and hence new metadata would be shown.
Fixes: #21311
<details> …
> lightbox_view: Fix media title update on change in title.

- help/format-your-message-using-markdown.md
- help/keyboard-shortcuts.md
- help/search-for-messages.md
- zerver/lib/markdown/help_relative_links.py
- Updates help center docs to reflect the new dedicated help menu.
- Adds `keyboard_tip` to document the `?` keyboard shortcut.
Fixes #27384.
- https://chat.zulip.org/help/keyboard-shortcuts#keyboard-shortcuts-reference
- https://chat.zulip.org/help/format-your-message-using-markdown#message-formatting-reference
- https://chat.zulip.org/help/search-for-messages#search-filters-reference
<details>
</details>
> help: Document new help menu.

- help/recent-conversations.md
This PR is an edited version of #27608.
Adds a new section with a short intro and instructions that explain how to load more conversations.
Fixes #27253.
Current page:
New section:
> help: Document "Load more" recent conversations.

- web/e2e-tests/message-basics.test.ts
- web/src/hotspots.js
- web/src/left_sidebar_navigation_area.js
- web/src/stream_list.js
- web/src/tippyjs.js
- web/styles/dark_theme.css
- web/styles/left_sidebar.css
- web/styles/right_sidebar.css
- web/styles/zulip.css
- web/templates/left_sidebar.hbs
- web/templates/right_sidebar.hbs
This PR provides a gridded rewrite to the header rows in the left sidebar.
Among the changes in this PR are the establishment of a uniform 24px height for all heading rows (minus any filter boxes); that value is derived from the 24px height in place on the Views heading row, and fits with a broader plan to create even-valued heights where vertical centering is essential. Those heights also account for the very slight vertical layout shifts in the screenshots below.
Fixes parts of: #27559 (this presents the current icon and unread layouts as-is; those newer layouts will probably be coupled together with #27380)
| --- | --- |
| <img width="380" alt="left-sidebar-headers-before" …
> left_sidebar: Header row CSS Grid rewrites.

- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
- corporate/views/upgrade.py
Moves the `setup_upgrade_checkout_session_and_payment_intent` function to the 'BillingSession' abstract class.
This refactoring will help in minimising duplicate code while supporting both realm and remote_server customers.
<details>
</details>
> stripe: Move `setup_upgrade_checkout_session_and...` to BillingSession.

- web/src/scheduled_messages.js
- web/tests/scheduled_messages.test.js
This PR addresses the issue where scheduling a message for a time less than 5 minutes in the future resulted in the confirmation banner not displaying the scheduled time, which should have actually been 5 minutes in the future, as enforced at the UI level by the MINIMUM_SCHEDULED_MESSAGE_DELAY_SECONDS variable.
We remove the `is_send_later_timestamp_missing_or_expired` method along with it's tests since `selected_send_later_timestamp` is already set to the minimum of 5 minutes in the future through the `minDate` option of the flatpickr.
Edit: Also note that  `is_send_later_timestamp_missing_or_expired` was only being used to display the formatted date and isn't linked with any logic of scheduled timestamp handling.
Fixes: #26784.
Rebased from #26789. …
> compose_banner: Display time for messages with < 5 mins scheduled time.

- web/src/tippyjs.js
- web/templates/left_sidebar.hbs
This PR improves the presentation and consistency of tooltips on the left sidebar's headers. Specifically, it:
1. Adds an expand/collapse tooltip to the Views header to make that header consistent with the tooltip on the DMs header
2. It introduces `<span>` elements to keep the tooltip centered on the heading text, rather than the heading's area in the grid (which can be much wider than the text itself); this fixes a regression introduced in #27638
3. It adds an `EXTRA_LONG_HOVER_DELAY` to the expand/collapse tooltips on the Views and DMs headers so as not to distract users familiar with the UI
4. For Views and DMs rows, it adds the expand/collapse tooltip to the arrows as well; while there isn't a contiguous area with the arrow and the heading text following the grid-row rewrites, the …
> left_sidebar: Present consistent header tooltips.

- corporate/lib/stripe.py
- corporate/lib/stripe_event_handler.py
- corporate/tests/test_stripe.py
- corporate/views/upgrade.py
Updates `process_initial_upgrade` so that it doesn't directly rely on a customer having a realm or have hard-coded values related to Zulip Cloud (e.g. `CustomerPlan.STANDARD` for the plan tier or `"Zulip Cloud Standard"` for the plan name).
Probably will need a few rounds of updates/review. Making notes about my specific questions/thoughts in the code changes directly.
---
<details>
</details>
> corporate: Make `process_initial_upgrade` not reliant on customer with realm.

- web/src/compose_validate.js
- web/src/composebox_typeahead.js
- web/tests/composebox_typeahead.test.js
It is common for users in other chat tools to start off a direct message
with @ mentioning the addressee. However, this results in potentially
unexpected behavior in Zulip, where the message is highlighted and shows
up in @ mentions in addition to DMs. We want to prevent this behaviour by
automatically changing the @ mentions to silent @ mentions for the user.
Fixes: #17998.
<details>
</details>
> compose: Automatically change @ mentions to silent mentions in 1:1 DMs.

- web/src/feedback_widget.ts
- web/src/narrow.js
- web/templates/feedback_container.hbs
When navigating to the next unread followed topic using the Shift+N hotkey, we notify the user using `feedback_widget` when there are no more unread messages in followed topics.
Fixes: #27604
[no-more-unread.webm](https://github.com/zulip/zulip/assets/56781761/f88ab472-07f4-4987-8118-f4ca9e895462)
<details>
</details>
> hotkey: Give feedback when no unreads left in followed topics.

- web/src/compose_ui.js
- web/src/composebox_typeahead.js
- web/src/copy_and_paste.js
- web/tests/composebox_typeahead.test.js
- web/tests/copy_and_paste.test.js
compose: Completely remove style elements when pasting HTML as markdown.
Turndown would strip `<style>` tags, but retain the content enclosed. This resulted in unwanted content being pasted, like the comment nodes inside the `<style>` tag when pasting cell/s copied from Google Sheets.
compose: Always retain `ul` tag when pasting content enclosed by it.
This functionally makes no difference, but we add it along with `ol` for consistency.
commit: Disable automatic numbering / bulleting when inside code block.
compose: Do not paste formatted markdown when inside a code block.
We usually default to pasting formatted markdown (unless the Shift key is used to paste plainly instead), but when we're inside a code block, we always want to paste plainly.
compose: Add a function checking whether the …
> When inside a code block, paste plainly and don't automatically add bullets / numbers

- web/src/search_suggestion.js
- web/tests/search_suggestion.test.js
Previously, the "All messages" typeahead would be shown whenever the search bar had an empty input. This change removes that typeahead completely in favor of using other filters such as -is:muted.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/search.20bar.20UX/near/1662286)
Fixes #27358
<details>
- [x ] [Self-reviewed](https://zulip.readthedocs.io/en/latest/contributing/code-reviewing.html#how-to-review-code) the changes for clarity and maintainability …
> search: Remove "All messages" typeahead

- help/follow-a-topic.md
- help/inbox.md
- help/include/followed-topic-workflows.md
- help/include/view-starred-messages.md
- help/reading-strategies.md
Fixes part of #27510, but I'd like to keep it open for now.
1. Updates Inbox view documentation for #27552.
Because the dropdown is unlabeled, I think it's worth listing out the options.
<details>
<summary>
Screenshot
</summary>
Current: https://chat.zulip.org/help/inbox#include-muted-conversations
</details>
2. Adds instructions for going though your followed topics.
<details>
<summary>
Screenshot
</summary>
Current page (this section is new): https://chat.zulip.org/help/follow-a-topic
</details>
3. Documents some workflows with followed topics on https://chat.zulip.org/help/follow-a-topic and https://chat.zulip.org/help/reading-strategies.
<details>
<summary>
Screenshots
</summary>
</details>
> Improve documentation for followed topics

- web/styles/inbox.css
- web/templates/inbox_view/inbox_view.hbs
Due to filters dropdown's variable width, the search icon was incorrectly positioned, we fix it by positioning it relative to the filter dropdown.
| --- | --- |
| <img width="361" alt="Screenshot 2023-11-11 at 7 18 19 AM" src="https://github.com/zulip/zulip/assets/25124304/c08fd568-4c0a-4785-9a7a-45d6e567f3c2"> | <img width="361" alt="Screenshot 2023-11-11 at 7 18 01 AM" src="https://github.com/zulip/zulip/assets/25124304/24229e26-a50f-4b4e-ad59-e8b476b2dd05"> |
> inbox: Fix search icon position on narrow widths.

- web/src/filter.js
- web/src/message_feed_top_notices.js
- web/src/message_list.js
- web/src/message_list_data.js
- web/src/message_list_view.js
- web/src/narrow_state.js
- web/src/search.js
- web/tests/filter.test.js
- web/tests/message_list_data.test.js
- web/tests/search.test.js
For more clarity, the 3 related functions `is_search` in `filter.js`, `message_list.js` and `message_list_data.js` are all renamed to `is_keyword_search`.
Fixes: [issue brought up here](https://github.com/zulip/zulip/pull/27509#discussion_r1389955254)
<details>
</details>
> refactor: Rename `is_search` to `is_keyword_search` for clarity.

- corporate/lib/stripe.py
- corporate/lib/stripe_event_handler.py
- corporate/tests/test_stripe.py
- corporate/views/upgrade.py
Moves the `process_initial_upgrade` function to the `BillingSession` abstract class.
This refactoring will help in minimizing duplicate code while supporting both realm and remote_server customers.
<details>
</details>
> stripe: Move `process_initial_upgrade` to BillingSession.

- web/styles/left_sidebar.css
This corrects a regression in the DM section header introduced by #27638, which caused the highlighted header to extend beyond the other DM rows (thanks @amanagr for catching). 
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/Make.20views.20section.20collapsible.20feedback/near/1680162)
| --- | --- |
| <img width="400" alt="dm-header-row-before" src="https://github.com/zulip/zulip/assets/170719/bb2a3092-3439-4093-94c8-e6a486ac690e"> | <img width="400" alt="dm-header-row-after" src="https://github.com/zulip/zulip/assets/170719/24165d2b-6ad3-4d3c-bcf3-bbd80289047a"> |
<details> …
> left_sidebar: Set shared right margin on DM section.

- web/src/rendered_markdown.js
- web/src/rows.js
- web/styles/rendered_markdown.css
- web/tests/rendered_markdown.test.js
Adds support to highlight the `@topic` wildcard mention text for the users who are both:
* subscribed to the stream
* a topic participant
Topic participants: Users who either sent or reacted to the messages in the topic.
Fixes part of #22829.
---
<details><summary>Topic participant</summary>
</details> 
<details><summary>Not a topic participant</summary>
</img>
</details> 
---
<details>
</details>
> topic_mentions: Highlight the @topic mention for topic participants.

- web/src/composebox_typeahead.js
- web/tests/composebox_typeahead.test.js
- web/tests/typeahead_helper.test.js
Add a `@topic mention` typeahead that appears only in stream messages and not in private messages.
Fixes part of #22829
---
<details><summary>Typeahead menu</summary>
</img>
</details> 
---
<details>
</details>
> topic_mentions: Add @topic mention typeahead.

- puppet/zulip/manifests/common.pp
- puppet/zulip_ops/manifests/prometheus/akamai.pp
- puppet/zulip_ops/manifests/vector.pp
- puppet/zulip_ops/templates/supervisor/conf.d/prometheus_akamai_exporter.conf.template.erb
- puppet/zulip_ops/templates/vector.toml.template.erb
Akamai writes access logs to S3; we use an SQS events queue, combined with Vector, to transform those into Prometheus statistics.
<details>
</details>
> zulip_ops: Add configuration for Vector Akamai stats.

- zerver/lib/cache_helpers.py
- zerver/models.py
This cache was only used in one place, which is infrequently called (only when sending messages, or searching explicitly for a list of users) and the overhead of maintaining the cache is not worth trying to avoid the well-indexed lookup of the huddle.
<details>
</details>
> cache: Drop the huddle cache.

- zerver/actions/streams.py
- First commit is to unset `is_realm_public` field when unarchiving streams.
- Second commit is to unset `is_web_public` field when deactivating streams.
Fixes:  #27634
<details>
</details>
> Unset `is_web_public` field on attachments when deactivating stream.

- web/src/compose_ui.js
- web/src/tippyjs.js
- web/styles/compose.css
- web/styles/zulip.css
- web/templates/compose.hbs
This PR introduces a few fixes to the new Send area UI. In particular:
* It introduces a new `send-control-button` class [to avoid confusion](https://github.com/zulip/zulip/pull/27535#discussion_r1391677223) with `message-control-buttons` references outside the compose area
* It uses that class to unify the tooltip behavior on the Send and vdots buttons
* It ensures that all of the hovered area around vdots is clickable, for opening the send options menu
* It fixes the position of the loading spinner, which appears in place of the Send button icon
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/new.20Send.20button.20styles/near/1681175)
Fixed load spinner:
Fixed clickable areas:
<details> …
> compose box: Improve structures, clickable areas, and load spinner.

- web/src/typeahead_helper.js
- web/tests/composebox_typeahead.test.js
https://github.com/zulip/zulip/pull/26371#issuecomment-1808537189
> why @topic doesn't appear at the top of the typeahead for just typing @? I think we probably want it to appear there next to @-all.
---
<details><summary>Using @</summary>
</img>
</details> 
<details><summary>Using @t</summary>
</img>
</details> 
---
<details>
</details>
> typeahead: Fix '@topic' not present when stream wildcard suggested.

- web/src/click_handlers.js
- web/src/compose_tooltips.js
- web/src/popover_menus.js
- web/src/tippyjs.js
- web/styles/compose.css
- web/styles/dark_theme.css
In addition to suppressing the tooltips when the send popover is open, this PR has a prep commit that cleans up a bunch of unreachable stuff from the now-defunct `enter_sends` interface that used to live beneath the Send button.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/Send.20tooltip.20with.20popover.20open/near/1681410)
With tooltips suppressed:
<details>
</details>
> compose box: Suppress tooltips when vdot send popover is open.

- web/src/hotkey.js
- web/src/scheduled_messages_popover.js
- web/templates/popovers/send_later_popover.hbs
While opening the send later popover via the keyboard, we want to focus the first text option, which is "Schedule message" at present. When the popover is opened via mouse click, we want to keep the original behavior of not focusing on any option.
Note: This is similar to the behavior of the message actions popover, and hence this commit follows a similar pattern to add the focus.
Fixes: #27701 
<details> …
> popovers: Focus first option in send later popover when opened with keyboard.

- web/src/scheduled_messages_ui.js
reload: Fix bug where stream input is unexpectedly cleared on reload.
Earlier, we preserved the stream name across reloads, and to restore the compose state, passed that to `compose_actions.start`, which since c3fe96a, considers the stream id, and not its name.
This caused a bug where on server initiated reload, the stream input would not retain its value and be unexpectedly cleared.
This is fixed by preserving the stream id across reloads, instead of its name, and passing that to `compose_actions.start` instead.
compose: Pass in `stream_id` to compose when editing scheduled message.
Earlier, we only passed in the stream name which isn't considered in `compose_actions.start` when populating the recipient.
There was no visible bug since we first narrow to the correct stream and then call …
> Bunch of bug fixes where stream id had to be passed into `compose_actions.start` instead of stream name.

- web/styles/left_sidebar.css
This goes up a selector level with the fix from #27679, which only partially fixed the issue of rows in the DM area extending too far right when the All DMs narrow was active.
> left_sidebar: Keep all DM container rows to same right margin.

- corporate/lib/stripe.py
- corporate/tests/stripe_fixtures/free_trial_upgrade_by_card--Customer.retrieve.4.json
- corporate/tests/test_stripe.py
- corporate/views/billing_page.py
- web/src/billing/helpers.ts
There is a discrepancy between price per license shown on billing and upgrade page for annual billing frequency due to difference in methods used to calculate the amount.
To fix it, we use the same method on both the pages.
| --- | --- |
| <img width="1134" alt="Screenshot 2023-11-14 at 7 17 23 AM" src="https://github.com/zulip/zulip/assets/25124304/bd7692f2-7c3a-4b09-8d2f-9edafb8434ad"> | <img width="1136" alt="Screenshot 2023-11-14 at 7 53 41 AM" src="https://github.com/zulip/zulip/assets/25124304/3a41e3aa-ba9f-4ad8-a626-456c9ba705bc"> |
> bililng: Fix incorrect price per license on billing page.

- web/styles/compose.css
This PR corrects a layout shift where the preview area appeared closer to the recipient row than the normal text area. It also fixes a regression with previewing long messages in full screen. That was achieved by removing a no-longer-necessary `height` declaration, which is now more properly the province of grid to manage.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/preview.20mode/near/1681809)
| --- | --- |
| ![message-preview-before](https://github.com/zulip/zulip/assets/170719/888975f1-028a-45ec-a7a5-9279b023b34c) | ![message-preview-after](https://github.com/zulip/zulip/assets/170719/e66ba7b9-2443-4e22-a28e-efd8449e0f88) |
<details> …
> compose box: Message-preview fixes.

- analytics/views/support.py
- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
- corporate/views/billing_page.py
CZO Discussion:
> * `make_end_of_cycle_updates_if_needed` => Needs to be a `BillingSession` method, probably. This might require a few phases of refactoring, because this is called from or main daily billing cron job as well.
> * I think what this means is we need to change `RealmBillingSession` to accept `user=None` (our convention for automated system jobs), adding `assert self.user is not None` in the places that access `self.user.foo` in the `RealmBillingSession`; none of those will be called from the cron code path. `RealmBillingSession` should probably assert that `realm is not None or user is not None` in this commit.
> * And then we can make all the callers of make_end_of_cycle_updates_if_needed make a RealmBillingSession(None, realm)
<details> …
> stripe: Move `make_end_of_cycle_updates_if_needed` to BillingSession.

- help/typing-notifications.md
- zerver/actions/typing.py
- zerver/tests/test_typing.py
- zproject/default_settings.py
#27706 
Changes:
* Test added
* removed the equality sign in `if total_subscriptions > settings.MAX_STREAM_SIZE_FOR_TYPING_NOTIFICATIONS:` as the doc says "Typing notifications are not shown in streams with more than 100 subscribers."
<details>
</details>
> typing: Limit typing notifications in large streams.

- web/src/left_sidebar_navigation_area.js
- web/src/unread.js
- web/styles/left_sidebar.css
- web/styles/zulip.css
- web/templates/left_sidebar.hbs
- web/tests/left_sidebar_navigation_area.test.js
In addition to adding a Streams unread count, this shifts the icons on the DM and Streams header rows to the left of the unread count, as called for in the left-sidebar redesign.
Fixes: #27559, #27380
Unreads with everything expanded:
Unreads with condensed views (yay!):
Unreads with condensed views, home view:
<details>
</details>
> left_sidebar: Add unread count to Streams header.

- web/styles/dark_theme.css
- web/styles/message_row.css
- web/styles/modal.css
- web/styles/zulip.css
- web/templates/message_edit_form.hbs
This PR places the message-edit buttons on their own line along with the editing timer, leaving the format buttons to their own line above.
Note that there's nothing fancy about how the lines of buttons are created: they're each just flex containers, each behaving as a block with regard to the other.
There are also some Frankensteined button styles in effect here; they draw on colors and styles from the modal buttons (e.g., on the Delete message modal), as well as the color and dimensions of the new send button to try and suggest a parallel between sending a message and editing and saving it later.
CZO discussion: None public yet; will update this.
| Source View, Before | Source View, After |
| --- | --- |
| …
> message_edit: Tune message-edit buttons and layout.

- web/src/message_list_tooltips.js
- web/src/tippyjs.js
- web/styles/dark_theme.css
- web/styles/reactions.css
- web/styles/zulip.css
This PR does two primary things:
1. It implements new reaction-container colors and rounded-pill styles defined by @terpimost.
2. It expresses all reaction-container colors and reaction button colors as CSS variables, in the process streamlining the number CSS selectors required.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/Reactions.20background.20color/near/1631057)
**Screenshots as of 2023-10-13**
| --- | --- |
| ![light-before-2023-10-13](https://github.com/zulip/zulip/assets/170719/e3b55813-3c3f-4f7e-aa0e-f67d3ff492ec) | ![light-after-2023-10-13](https://github.com/zulip/zulip/assets/170719/d07c91ed-1ca7-444d-a702-b3168e4eff2c) |
| ![dark-before-2023-10-13](https://github.com/zulip/zulip/assets/170719/b66aec82-b1ad-4d66-9e97-c9a43c9d5190) | …
> reactions: Rectify reaction-container colors.

- docs/overview/release-lifecycle.md
Current doc: https://zulip.readthedocs.io/en/latest/overview/release-lifecycle.html#server-roadmap
Updated:
I also changed a few examples from Zulip 4.x to Zulip 7.x, just to make the doc not feel super old.
> docs: Update server roadmap documentation.

- web/src/compose_ui.js
Tested on Safari 13.1 on macOS 10.15.
> compose_ui: Fall back to comma join when `Intl.ListFormat` is missing

- web/src/hashchange.js
- web/src/left_sidebar_navigation_area.js
- web/src/message_scroll.js
- web/src/message_scroll_state.ts
- web/src/narrow.js
- web/tests/left_sidebar_navigation_area.test.js
This fixes [a code path](https://github.com/zulip/zulip/pull/27643#discussion_r1389691913) for highlighting the All messages navigation item on a reload, which left all users--whether All messages was their home view or not--without a proper highlight when reloading from `/#all_messages`.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/Make.20views.20section.20collapsible.20feedback/near/1678805)
| Before (All messages loses highlight after reload) | After |
| --- | --- |
| ![reload-all-messages-before](https://github.com/zulip/zulip/assets/170719/45f0aba8-1ef4-4e7f-a4a7-684a71e88911) | ![reload-all-messages-after](https://github.com/zulip/zulip/assets/170719/378ebc61-edd0-4463-90a4-ac3940ea54ea) |
<details> …
> left_sidebar: Preserve highlight on All messages after reload.

- docs/translating/spanish.md
The word "Filtrar" is ambiguous in this context since it can be interpreted as "filter out" which is the opposite of what we want here. "Buscar solo" is a better phrase that we can use unambiguously and consistently for all instances of "Narrow to".
<details>
</details>
> docs: Update Spanish translation for "Narrow to".

- .gitignore
- docs/production/mobile-push-notifications.md
- requirements/common.in
- requirements/dev.txt
- requirements/prod.txt
- version.py
- zerver/lib/push_notifications.py
- zerver/tests/test_push_notifications.py
- zproject/default_settings.py
- zproject/dev_settings.py
- zproject/test_extra_settings.py
This is a followup to #27590, after it was split as discussed at https://github.com/zulip/zulip/pull/27590#issuecomment-1800407932 and [in `#api design`](https://chat.zulip.org/#narrow/stream/378-api-design/topic/iOS.20app.20IDs.20in.20registering.20push.20device.20tokens/near/1677679).
In this PR, we arrange for our APNs connection to use [token-based authentication](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns) if a key is provided for that, as well as the existing [certificate-based authentication](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_certificate-based_connection_to_apns) if a cert is provided instead. …
> Make push notifications work for multiple iOS app IDs, part 2/2

- analytics/migrations/0017_regenerate_partial_indexes.py
Due to a bug[^1] in Django 4.2, fixed in 4.2.6, queries using `__isnull` added an unnecessary cast.  This cast was _also_ used in `WHERE` clauses for partial indexes.  This means that partial indexes created before Zulip was using Django 4.2 (i.e. before Zulip Server 7.0 or 2c20028aa451) will not be used when the server is using Django 4.2.0 through 4.2.5 -- and, conversely, that indexes created while Zulip had those versions of Django (i.e. Zulip Server 7.0 through 7.4 or 7807bff52635) will not be used later.
We re-create the indexes, to ensure that users that installed Zulip after Zulip Server 7.0 / 2c20028aa451 and before Zulip Server 7.5 / 7807bff52635 have indexes which can be used by current Django.  This is useless work for some installations, but most analytics tables are not …
> analytics: Regenerate partial indexes due to Django bug.

- help/custom-profile-fields.md
Current: https://zulip.com/help/custom-profile-fields#profile-field-types
Updated: 
I decided that the precise detail of what happens if an org has *two* pronoun fields does not need to be documented, since it's a rather odd circumstance.
> help: Document that pronouns are now shown in @-mention typeahead.

- zerver/lib/drafts.py
Bumped into these outdated comments when looking through some @typed_endpoint example code.
> These were written before the draft endpoints were converted to use @typed_endpoint and pydantic-based DraftData(BaseModel) for param validation. Update them to avoid the confusion of talking about dicts and dict_validator functions when those are no longer a thing.
@PIG208 Can you check if my phrasing for these makes sense?
> drafts: Update some stale docstrings regarding draft data validation.

- docs/testing/manual-testing.md
- docs/translating/translating.md
- help/keyboard-shortcuts.md
- help/unsubscribe-from-a-stream.md
- web/src/add_stream_options_popover.js
- web/src/gear_menu.js
- web/src/stream_settings_ui.js
- web/templates/gear_menu_popover.hbs
- web/templates/keyboard_shortcuts.hbs
- zerver/lib/markdown/help_relative_links.py
- zerver/tests/test_docs.py
- Renames gear menu label, and updates code comments.
- Renames "Streams settings" label in the keyboard shortcuts reference to "Stream settings" for consistency.
- Updates help center docs to reflect renamed gear menu label.
- Updates contributor docs to reflect renamed gear menu label.
Fixes #27754.
- **Gear menu**
- https://zulip.com/help/unsubscribe-from-a-stream
- https://chat.zulip.org/#keyboard-shortcuts
- https://zulip.com/help/keyboard-shortcuts
<details> …
> Rename "Manage streams" -> "Stream settings".

- web/src/copy_and_paste.js
- web/tests/copy_and_paste.test.js
Due to the way turndown pads every block element with 2 new lines, and makes `br` double space by default, we would get 3 blank lines pasted when there's just 1 line break between 2 paragraphs.
Now we set `br` to an empty string, and since turndown collapses sequences of multiple new lines to `\n\n` (1 blank line), so any 2 block elements will now always have 1 blank line between them, irrespective of if and how many line breaks there are between them in the copied HTML.
Fixes: [issue brought up in this CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/extra.20line.20breaks.20when.20pasting/near/1682915)
<details>
Individual …
> compose: Fix bug where extra line breaks were pasted between blocks.

- web/src/compose_recipient.js
- web/src/compose_tooltips.js
- web/src/compose_validate.js
- web/src/upload.js
- web/tests/compose_validate.test.js
- web/tests/upload.test.js
Earlier, the send button's state was determined independently by the message length and the upload status. As the message length check was run on each character input, it often overrode the upload status check.
Now using the observer pattern we update the send button anytime message length or upload status changes, considering **both** of them together.
(The Save button when editing a message still works like before -- only dependent on upload status.)
Fixes: #21135.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-disciplin …
> compose: Disable send button when upload/s are in progress.

- help/font-size.md
- help/include/sidebar_index.md
I documented the keyboard as the primary method, as it's generally the most handy, and consistent across browsers.
Thanks @alexmv for the suggestion on a thread a couple of months ago. :)
> help: Document how to change font size with zoom.

- api_docs/changelog.md
- zerver/openapi/zulip.yaml
While the server implementation has accepted this value for a few months as part of building the feature, following topics was not a fully supported feature of the Zulip server before 3f2ab44f9485da603dc192b1b6a03102d13997d4, just before feature level 219.
So that's probably the correct level to document as the first feature level at which we recommend that clients supporting the followed topics feature process the value.
> api_docs: Add missing followed topic visibility policy.

- docs/overview/changelog.md
- docs/production/authentication-methods.md
- zerver/tests/test_auth_backends.py
- zproject/backends.py
Changing how realms not listed in the `AUTH_LDAP_ADVANCED_REALM_ACCESS_CONTROL` setting are handled, as suggested in https://github.com/zulip/zulip/pull/24284#discussion_r1098030159
> ldap: Realms not listed in access control setting should not be affected by it.

- web/src/filter.js
- web/src/message_view_header.js
- web/styles/dark_theme.css
- web/styles/zulip.css
- web/templates/message_view_header.hbs
- web/templates/navbar_icon_and_title.hbs
- web/tests/filter.test.js
This PR carries forward work begun in #27409 for dropping the subscription count from the top navbar.
In addition to that work, this PR:
* Modernizes the layout for all icon-title combinations in the top navbar
* Gets ALL titles on the same invisible line (the Inbox one previously drooped a bit lower than the others)
* Precisely aligns the stream name with its description on a shared baseline
* Places the same icons as are in use in the left sidebar, as many of those align better than their FA counterparts
* Makes the whole title area more robust (partially by structuring the title as a first-rate DOM element, where it had previously been a text node), and removes and otherwise cleans up a bunch of brittle CSS that was formerly used for adjusting to a narrower header height. That's now …
> top_navbar:  Remove subscriber count; improve icons and alignment.

- web/src/message_view_header.js
- web/templates/message_view_header.hbs
At present, it's not obvious that clicking on the stream name in the top navbar will take the user to stream settings. To make it more apparent, we add a tooltip to the stream name, explicitly indicating its functionality.
We also add a second line to the tooltip thar displays the number of subscribers to the stream and remove the tooltip from the number of subscribers indicator on the top navbar. These changes are in preparation for removing the number of subscribers indicator from the top navbar.
Fixes #27360.
Previous work: #27466
[CZO thread](https://chat.zulip.org/#narrow/stream/101-design/topic/stream.20subscribers.20in.20top.20bar/near/1666842)
- Stream Name tooltip
- Tooltip removed from number of subscribers indicator
- Stream Name tooltip …
> message_view_header: Add tooltip to stream name in top navbar.

- web/styles/zulip.css
- web/templates/recipient_row.hbs
This PR corrects a misaligned link icon, which was most obvious in Chrome but also presented itself in Firefox. See screenshots below.
Additionally, this drops the size on the visiblity policy icons (mute, default, follow) so that they are 15px like the others on the row.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/icon.20alignment.20in.20topic.20header.20bar/near/1683623)
| Chrome, before | Chrome, after |
| --- | --- |
| ![chrome-before](https://github.com/zulip/zulip/assets/170719/b87bcc6e-e7e6-458a-8d36-86a6a480fb99) | ![chrome-after](https://github.com/zulip/zulip/assets/170719/c19f0587-8396-4011-8175-bc8ffa4ba4ad) |
| Firefox, before | Firefox, after |
| --- | --- |
| …
> message feed: Correct recipient-bar icon alignment.

- web/src/watchdog.ts
- web/tests/watchdog.test.js
Earlier, in the `check_for_unsuspend` function, we didn't handle the exception, if any, during callback execution, resulting in `watchdog_time` not always being updated.
This PR handles the exception using the try/catch block.
Fixes: #27723
<details>
</details>
> watchdog: Handle exception in `callback`.

- package.json
- pnpm-lock.yaml
- version.py
- web/src/message_edit_history.js
- web/src/people.ts
- web/src/settings_data.ts
- web/src/timerender.ts
- web/tests/people.test.js
- web/tests/timerender.test.js
`date-fns-tz` does not handle daylight saving time correctly, and can be replaced with modern browser APIs.
> people: Remove final use of date-fns-tz

- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
- corporate/views/upgrade.py
This PR moves a major portion of the `initial_upgrade` view to a new shared `BillingSession.do_initial_upgrade` method.
<details>
</details>
> stripe: Add 'do_initial_upgrade' method to the 'BillingSession' class.

- help/allow-image-link-previews.md
- web/src/admin.js
- zerver/lib/markdown/__init__.py
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/setting.20for.20whether.20previews.20are.20displayed
This setting now also works to decide whether to show previews of uploaded or linked videos.
First message with preview enabled second with preview disabled.
> realm_inline_image_preview: Use it to toggle video previews too.

- zerver/lib/email_notifications.py
- zerver/tests/test_message_notification_emails.py
Fixes the email notification part of #25289.
> When I receive a message with latex math, the notification (in all of email, android, and desktop) includes the math three times in a row (once as unicode, once as latex, again as unicode). This seems to happen every time.
Earlier, for the emails having latex math like `$$d^* = +\infty$$`, the bad rendering led to the math being included multiple times in the email body.
This was due to displaying KaTeX HTML without the CSS.
This PR fixes the incorrect behavior by replacing the KaTeX with the raw LaTex source.
---
| ![image](https://github.com/zulip/zulip/assets/56781761/dbfedadb-44f7-456e-9ddb-57ff1af72ae1) | …
> email_notification: Fix bad rendering of math formulas.

- web/src/buddy_list.js
- web/src/list_cursor.ts
- web/src/stream_list.js
- web/tests/buddy_list.test.js
- web/tests/list_cursor.test.js
- web/tests/user_search.test.js
Extracted from https://github.com/zulip/zulip/pull/26717.
> buddy list: Rename sel variables to selector to avoid abbreviations.

- web/src/message_edit_history.js
- web/src/timerender.ts
https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat_datetimeformat_options_parameter_options_datestyle_parameter
> timerender: Avoid dateStyle option missing in Safari < 14.1

- web/src/left_sidebar_navigation_area.js
- web/styles/left_sidebar.css
- web/styles/zulip.css
- web/templates/left_sidebar.hbs
- web/tests/left_sidebar_navigation_area.test.js
Judging by the surrounding CSS, including `position: sticky`, this PR makes the streams header sticky, increasing its utility especially in a collapsed views state.
The streams sticky-header should be a fairly low-risk change, as it's only a single line of CSS, and makes no structural changes to the left sidebar.
Additionally, this presents the 'Back to streams' area as a gridded row, complete with an unread count that will be shown while the ordinary streams header is hidden when zoomed in to a topic. By matching the two row heights and their typographic treatments, the two appear to swap places when zooming in and out.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/Make.20views.20section.20collapsible.20feedback/near/1685495) …
> left_sidebar: Make streams header sticky.

- web/e2e-tests/mention.test.ts
- web/src/compose_actions.js
- web/src/compose_setup.js
- web/src/compose_validate.js
- web/src/message_edit.js
- web/src/util.ts
- web/src/zulip_test.js
- web/templates/compose_banner/stream_wildcard_warning.hbs
- web/templates/compose_banner/wildcard_warning.hbs
- web/tests/compose_validate.test.js
- web/tests/example1.test.js
- web/tests/util.test.js
Earlier, a 'large @-mention notification' warning that pops up for stream wildcard mentions was shown for topic wildcard mentions too, which is incorrect.
This PR fixes the incorrect behavior. We no longer show the banner for @-topic mentions.
We don't need a banner for @-topic mentions, as those are much less likely to be used without thinking about it and would rarely be spammy for a lot of people.
Fixes #27767.
---
[no-warning.webm](https://github.com/zulip/zulip/assets/56781761/1835281b-244d-4025-9db3-25317d74f0e6)
<details> …
> topic_mentions: Fix the incorrect large @-mention notification warning.

- web/src/click_handlers.js
- web/src/compose_reply.js
- web/src/compose_state.ts
- web/src/message_actions_popover.js
- web/tests/compose_actions.test.js
- web/tests/compose_ui.test.js
Until now, when a user quoted and replied to a message, even while editing another, the quote would be inserted into the compose box. There was no way to quote into the edit box.
Detecting the edit box to add content too was tricky, since on opening the message actions popover, that message would be selected, while the edit box would lose focus.
Now we don't shift focus on opening the message actions popover, and add the quote content to the edit box when its message is selected.
Fixes: #20380.
compose: Do not select message row on opening message actions popover.
Now since all actions available in the message actions popover operate
on that message itself, we don't need to select the message row when
opening the popover.
compose: Pass in the message_id when quoting from the message's …
> compose: When editing the selected message, quote into the edit box.

- zerver/migrations/0490_renumber_options_desktop_icon_count_display.py
Renumbering 4 -> 3, and then 3 -> 2 leads to everyone having their preferences set to 2.  Swap the order, so that we renumber 3 -> 2, then 4 -> 3.
<details>
</details>
> migrations: Fix revert migration to not lose all preferences.

- web/src/message_edit.js
- web/src/stream_popover.js
- web/templates/move_topic_to_stream.hbs
In the previous menu for moving messages, the default option was "Move this and all following messages." However, this default choice was not always aligned with user intentions, particularly when moving the first or last message in a topic. In such cases, the desired behavior often corresponds to "Move all messages in this topic" for the first message and "Move only this message" for the last message.
To address this, we have updated the default options as follows:
1. **When moving the first message in a topic:** The default option is now "Move all messages in this topic." This change better represents the user's intention when moving the initial message in a topic.
2. **When moving the last message in a topic:** The default option has been adjusted to "Move only this message." This …
> message-editing: Make default "Move messages" form context-dependent.

- web/src/hotkey.js
- web/tests/hotkey.test.js
We don't show emoji icon on message on width range even if the logged in user is not the sender, which causes popover to not be displayed since the reference is not visible.
To avoid such case in future, we just check if the emoji icon is visible and if not fallback to the ellipsis icon for reference.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20emoji.20reaction.20shortcut.20broken.20in.20narrow-ish.20windows
> hotkey: Fix emoji popover not triggered in a narrow width range.

- web/src/invite.ts
- web/src/page_params.ts
- web/templates/invite_user_modal.hbs
- web/templates/modal_banner/invite_tips_banner.hbs
- web/templates/modal_banner/modal_banner.hbs
We include setup tips to the user invite modal for the following
cases:
(At the top of the invite modal)
- If the org description is missing.
- If the org profile picture is missing.
- If the custom profile fields have not been added.
We also use the new banner ui to display these tips. In doing so, we extract the banner component from `compose_banner.hbs` to `popover_banner.hbs`, removing any compose specific code from the banner component.
Fixes: #24262
Previous Work: #24273 
> [!NOTE]  
> - This PR includes the newer compose banner system as suggested in https://github.com/zulip/zulip/pull/24273#issuecomment-1716341552.
> - This PR includes setup tips pointing to default new user settings but does not actually check for any changes from the original default new user settings since we …
> invite: Add setup tips to user invite modal.

- zerver/tests/test_realm.py
- zerver/views/realm.py
We previously did not allow setting `signup_notifications_stream` and `notifications_stream`
settings to private streams that admin is not subscribed to, even when admins have access
to metadata of all the streams in the realm and can see them in the dropdown options as well.
This commit fixes it to allow admins to set these settings to private streams that the admin is not subscribed to.
Fixes: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20private.20stream.20for.20announcements
<details> …
> realm: Allow setting notification settings to unsubscribed private streams.

- web/src/recent_view_ui.js
- web/templates/recent_view_filters.hbs
- web/tests/recent_view.test.js
Earlier All filter button is included in recent conversations which is used to shown all conversations and clears remaining filters whose functionality is confusing
This PR Removes "All" filter and corresponding js along with modified tests to enables control filters individually
Fixes #27588
**Before:**
**After:**
<details>
</details>
> filters : removal of All filter from recent conversations

- web/src/compose_banner.ts
- web/src/invite.ts
This PR contains the following changes,
1. Change banner type from `warning` to `info`.
2. Rename "setup_tips_warning" classname to "setup_tips_banner". (part of the same commit as `1`)
3. Remove redundant param "banner_html" which was introduced in eecb611789aa61ee84c6ffc8d2f5bafb333da4c7
CZO: [link](https://chat.zulip.org/#narrow/stream/101-design/topic/setup.20tips.20in.20user.20invite.20modal/near/1687490)
<details> …
> invite: Change setup tips banner from warning to info and remove redundant code.

- web/src/emoji_picker.js
- web/styles/user_status.css
- web/templates/set_status_overlay.hbs
As reported on [#27270](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html), the emoji picker in the set status modal was not opening when pressing enter. This commit adds a keypress event listener to the emoji picker in the set status modal, and opens the
emoji picker when the enter key is pressed.
Fixes part of #27270.
Relevant discussion: https://github.com/zulip/zulip/issues/27270#issuecomment-1791107342
<details> …
> user_status: Fix press enter to open status emoji picker.

- help/include/compose-and-send-message.md
- help/include/replying-to-messages.md
- help/mastering-the-compose-box.md
- help/schedule-a-message.md
Updates relevant articles to reflect the changes to the send button and compose box menu.
Fixes #27848.
- https://zulip.com/help/mastering-the-compose-box#toggle-between-ctrl-enter-and-enter-to-send-a-message
- https://zulip.com/help/schedule-a-message
- https://zulip.com/help/getting-started-with-zulip#responding-to-an-existing-thread
<details>
</details>
> help: Document compose box UI changes.

- analytics/tests/test_support_views.py
- analytics/views/support.py
- corporate/lib/stripe.py
- corporate/lib/support.py
- corporate/tests/test_stripe.py
- corporate/views/billing_page.py
- zerver/actions/realm_settings.py
This PR moves a major portion of the 'update_plan` view to a new shared `BillingSession.do_update_plan` method.
This refactoring will help in minimizing duplicate code while supporting both realm and remote_server customers.
<details>
</details>
> stripe: Add `do_update_plan` method to the 'BillingSession' class.

- web/src/dropdown_widget.js
- web/src/settings_org.js
- web/styles/app_components.css
- web/templates/dropdown_current_value_not_in_options.hbs
If the current value is not in the calculated options, `text_if_current_value_not_in_options` can be provided to the widget to show custom text in that case.
Used by stream / user announcement settings if user doesn't have access to information about the currently selected stream.
| Owner with stream access |
| --- |
| <img width="456" alt="Screenshot 2023-11-22 at 3 22 34 PM" src="https://github.com/zulip/zulip/assets/25124304/c1c8bf83-eb48-4127-a165-a5202395b9b8"> |
| Admin not subscribed to the stream but has stream data |
| --- |
| <img width="456" alt="Screenshot 2023-11-22 at 3 21 53 PM" src="https://github.com/zulip/zulip/assets/25124304/88e0fa64-16f2-4b41-a44b-06d43d7b3a4b"> |
| Normal user with not subscribed to the stream |
| --- |
| <img width="456" alt="Screenshot 2023-11-22 …
> dropdown_widget: Allow showing custom text if value is not in options.

- web/styles/compose.css
- web/styles/dark_theme.css
- web/styles/popovers.css
- web/styles/zulip.css
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20arrow.20on.20popovers.20in.20dark.20theme
> css: Set tippy-arrow color same as background in light theme.

- help/allow-image-link-previews.md
- help/include/sidebar_index.md
- help/manage-your-uploaded-files.md
- help/search-for-messages.md
- help/share-and-upload-files.md
- help/view-and-browse-images.md
- help/view-images-and-videos.md
- zerver/lib/url_redirects.py
- Updates [View and browse images](https://zulip.com/help/view-and-browse-images), adding desktop/web app instructions and tweaking the intro paragraph.
- Renames page to **View images and videos**.
- Clarifies viewer support for browsing both images and videos, and tweaks documentation on other pages.
- Adds a new section to describing the video player features.
- Splits out browsing other images and videos in the view into its own section.
- Adds mobile app instructions.
Fixes #27801.
- https://zulip.com/help/view-and-browse-images
- https://zulip.com/help/search-for-messages#search-for-attachments-or-links
- https://zulip.com/help/share-and-upload-files
> help: Document "image viewer" mobile feature.

- web/src/settings_components.js
- web/src/settings_org.js
- web/src/types.ts
- web/src/user_groups.ts
- web/styles/settings.css
- web/templates/settings/organization_permissions_admin.hbs
- web/tests/user_groups.test.js
- zerver/models.py
- zerver/tests/test_realm.py
- zerver/views/realm.py
- First commit is to rearrange settings in "Organization permissions" section.
- Second commit is to add support to update the `can_access_all_users_group` setting.
<details>
</details>
> Add support to update `can_access_all_users_group` setting in dev environment.

- api_docs/changelog.md
- version.py
- web/src/compose.js
- web/src/compose_banner.ts
- web/src/compose_validate.js
- web/src/echo.js
- web/src/markdown.js
- web/src/message_edit.js
- web/src/transmit.js
- web/templates/compose_banner/wildcard_mention_not_allowed_error.hbs
- web/templates/settings/organization_permissions_admin.hbs
- web/tests/compose_validate.test.js
- web/tests/transmit.test.js
- zerver/actions/message_edit.py
- zerver/actions/message_send.py
- zerver/lib/exceptions.py
- zerver/lib/markdown/__init__.py
- zerver/lib/message.py
- zerver/openapi/zulip.yaml
- zerver/tests/test_message_edit.py
- zerver/tests/test_message_send.py
**First commit:** 
Prep commit to address this comment https://github.com/zulip/zulip/pull/27813#issuecomment-1821332747
<details><summary>@-stream</summary>
</details> 
<details><summary>@-everyone</summary>
</details> 
<details><summary>@-all</summary>
</details> 
**Second commit:**
Now, the topic wildcard mention follows the following rules:
* If the topic has less than 15 participants , anyone can use @ topic mentions.
* For more than 15, the org setting 'wildcard_mention_policy' determines who can use @ topic mentions.
Fixes part of #27700.
---
**Message Edit:**
<details><summary>Stream wildcard mention</summary>
</img>
</details>
<details><summary>Topic wildcard mention</summary>
</img>
</details> 
**Message Send:**
<details><summary>Stream …
> topic_mentions: Fix restriction rule for @-topic mentions. 

- help/restrict-wildcard-mentions.md
Also drop extraneous details.
- We don't normally document defaults, to avoid having to update documentation if they are changed or become context-dependent.
- I don't think it's important to document warning banners.
I was also careful to not say that it depends on how many people will actually be notified (which the previous version did), since my understanding is that it's based on just the number of subscribers/participants, now how those users' personal notification settings are configured.
> help: Document updated setting to restrict wildcard mentions.

- web/src/message_list_view.js
- web/src/rendered_markdown.js
- web/styles/rendered_markdown.css
- web/tests/rendered_markdown.test.js
Fixed the following behavior in unsubscribed streams:
* Stream wildcard mention pill should be green instead of purple.
* Message background should never be highlighted.
* Mention text should never be bold.
Fixes #27654.
---
**Before**
| Subscribed | Unsubscribed |
| ![image](https://github.com/zulip/zulip/assets/56781761/d76dac2a-def6-4edb-861b-c2ebd76b816a) | ![Screenshot from 2023-11-17 18-01-19](https://github.com/zulip/zulip/assets/56781761/df97aafd-782d-4f6c-a11e-d6535eb37db2) | 
**After**
| Subscribed | Unsubscribed |
| ![image](https://github.com/zulip/zulip/assets/56781761/e626ff7d-b751-4136-ac19-cdf661d51f1a) | ![image](https://github.com/zulip/zulip/assets/56781761/e4a64f00-d46a-4fad-9b61-a8eac35fd123) …
> mention: Fix mention highlighting in unsubscribed streams.

- corporate/lib/remote_billing_util.py
- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
- corporate/urls.py
- corporate/views/billing_page.py
- corporate/views/remote_billing_page.py
- corporate/views/upgrade.py
- templates/corporate/upgrade.html
- tools/test-backend
- zerver/views/auth.py
Completes the first and second task of `#16`.
changed dev_settings:
```
DEVELOPMENT_DISABLE_PUSH_BOUNCER_DOMAIN_CHECK = True
PUSH_NOTIFICATION_BOUNCER_URL = "http://aman.zulipdev.org:9991"
```
and ran `./manage.py register_server` for it to work as recommened in #27575
The actual upgrade flow doesn't work here.
> Allow upgrade access to remote realms.

- zerver/tests/test_auth_backends.py
- zproject/backends.py
Related to https://github.com/zulip/zulip/pull/27874
This logic has been #nocoverage since its implementation, but since this is an authentication codepath, it seems important for it to have a test.
> tests: Add test for nocoverage userAccountControl case in ldap auth.

- corporate/lib/decorator.py
- corporate/views/remote_billing_page.py
- corporate/views/upgrade.py
- zerver/decorator.py
Discussion: https://github.com/zulip/zulip/pull/27868#discussion_r1403598674
Added just the `authenticated_remote_realm_management_endpoint` wrapper, we can add `authenticated_remote_server_management_endpoint` while making progress on billing pages otherwise it will just be unused right now.
> decorator: Add wrapper to directly pass remote_realm to view_func.

- web/src/recent_view_ui.js
- web/tests/recent_view.test.js
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Recent.20conversations.20unread.20filter
I accidentally removed the filter_unread parameter passed to the template.
> recent_view: Show checkbox icon for unread filter.

- corporate/lib/stripe.py
- corporate/views/billing_page.py
- corporate/views/event_status.py
This PR refactors `event_status` view and adds `BillingSession.get_event_status` method.
This refactoring will help in minimizing duplicate code while supporting both realm and remote_server customers.
<details>
</details>
> stripe: Refactor `event_status` and `sponsorship_request` views.

- web/src/click_handlers.js
- web/src/emoji_picker.js
- web/src/user_card_popover.js
This PR fixes the focus on messages when clicking message feed buttons that open popovers. The focus no longer changes when following buttons are clicked on the message-box:
- "Add emoji"
- "Move message"
- "User avatar or name"
Fixes: #27820
<details>
</details>
> message_feed_ui: Fix focus when clicking on message feed buttons.

- web/src/narrow.js
Earlier navigating to the next unread topic or DM with N / P and reaching last unread topic or dm, nothing happened when shortcut was pressed again.
This commit changes the behaviour when shortcut reaches the last topic or dm and pressed again. Now it notifies the user that there are no more unread messages.
Fixes zulip#27862.
<details>
</details>
> keyboard_shortcut: Add feedback for N/P shortcut after no more message.

- web/src/lightbox.js
Previously, when we load for the first time, the ```panzoom``` control is binded by default to the image class.
This causes various problems like when a non image class is opened first in lightbox, and some ```panzoom``` function
is performed on it. Even though no ```panzoom``` object is binded to them, it would rather perform the function with the object binded to image class, causing it to throw errors when no image has been opened yet in the lightbox.
This is fixed by checking if the image class has an ```img``` tag in it before performing any functions of the the ```panzoom``` object using the ```isActive()``` method
[CZO Thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/Lightbox.20youtube.20previews.20breaking.20the.20media_list.20navigation)
<details> …
> lightbox: Fix broken media list nav when youtube videos are opened first.

- corporate/tests/test_stripe.py
- templates/corporate/upgrade.html
- zerver/tests/test_signup.py
This PR simplifies the /upgrade page when there's a free trial. The intent is not to change anything about the upgrade page otherwise.
Known to-do's:
> upgrade: Simplify free trial upgrade page.

- analytics/views/activity_common.py
- analytics/views/installation_activity.py
- analytics/views/remote_activity.py
- templates/analytics/realm_summary_table.html
- tools/test-backend
Updates the remote installations analytics page to have a columns for:
- The Zulip version stored on the server (will be `None` if no value is stored).
- The link to the remote server's analytics page (pie chart icon).
- The link to the remote server's support page (gear icon).
Also updates the general installation activity page to show the realm's support page link as a gear icon, instead of the realm's name.
<details>
<summary>Updated installation activity page for gear icon</summary>
</details>
<details>
<summary>Updated remote installations page - hovering on analytics icon</summary>
</details>
<details>
<summary>Updated remote installations page - hovering on support icon</summary>
</details>
---
<details> …
> analytics: Add Zulip version and support page links to remote installations page.

- web/e2e-tests/mention.test.ts
- web/src/compose_validate.js
- web/src/composebox_typeahead.js
- web/src/recent_senders.js
- web/src/zulip_test.js
- web/tests/compose_validate.test.js
- web/tests/composebox_typeahead.test.js
- web/tests/recent_senders.test.js
Earlier, when a topic had less than 15 participants, the @-topic typeahead was not visible. It should be visible
irrespective of the 'realm_wildcard_mention_policy' setting when the participant count is not greater than 15.
The participant count for a topic can't always be calculated accurately in the client as some of the messages might still be loading.
We show @-topic in the typeahead whenever it might be possible to use it.
We will give an error later if you aren't allowed to use it.
Fixes: #27852 
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline …
> typeahead: Show @-topic typeahead whenever it might be possible to use.

- zerver/lib/markdown/__init__.py
- zerver/tests/test_markdown.py
549dd8a4c4a4 changed the regex that we build to contain whitespace for readability, and strip that back out before returning it. Unfortunately, this also serves to strip out whitespace in the source linkifier, causing it to not match expected strings.
Revert 549dd8a4c4a4.
Fixes: #27854.
<details>
</details>
> markdown: Stop attempting to expand/collapse re2 regex.

- analytics/tests/test_counts.py
- analytics/tests/test_support_views.py
- corporate/tests/test_stripe.py
- tools/semgrep-py.yml
- zerver/lib/test_classes.py
- zerver/tests/test_auth_backends.py
- zerver/tests/test_digest.py
- zerver/tests/test_email_change.py
- zerver/tests/test_example.py
- zerver/tests/test_gitter_importer.py
- zerver/tests/test_home.py
- zerver/tests/test_invite.py
- zerver/tests/test_muted_users.py
- zerver/tests/test_new_users.py
- zerver/tests/test_presence.py
- zerver/tests/test_retention.py
- zerver/tests/test_sessions.py
- zerver/tests/test_user_groups.py
> Consistently use time_machine, and lint against mocking timezone_now

- web/src/compose_actions.js
- web/src/compose_banner.ts
- web/src/compose_reply.js
- web/src/compose_setup.js
- web/src/compose_validate.js
- web/src/narrow.js
- web/tests/compose_actions.test.js
- web/tests/narrow.test.js
When a user is composing a message while in a search view, we now warn them that the full conversation is not visible and urge them to go to the conversation they are composing to, so they can see the complete conversation. On narrowing to that conversation, the banner is removed.
Fixes: #25893.
<details>
</details>
> compose: Add banner to go to conversation when composing in search view.

- web/src/css_variables.js
- web/styles/search.css
- web/styles/zulip.css
- web/templates/navbar.hbs
Fixes #27366.
<details>
<summary>full wide and tall</summary>
</details>
<details>
<summary>medium wide and tall</summary>
</details>
<details>
<summary>narrow and tall</summary>
</details>
<details>
<summary>full wide and short</summary>
</details>
<details>
<summary>medium wide and short</summary>
</details>
<details>
<summary>narrow and short</summary>
</details>
I can come back later to add screenshots for search bar, but essentially I had it take the full width for narrow screens but not for short screens, which is one piece of the narrow search bar logic that I kept for narrow instead of moving to the short styles.
> navbar: Show shorter navbar for short screens not narrow screens.

- tools/setup/emoji/build_emoji
- tools/setup/emoji/emoji_setup_utils.py
- tools/setup/emoji/generate_emoji_names_table
- version.py
- web/tests/emoji_picker.test.js
The Twitter emoji team was laid off in 2022, so new emoji aren't supported (see https://github.com/twitter/twemoji/issues/570#issuecomment-1303422143). 
The "twitter" sprite sheet we’re using does have images in those locations, but they’re fallback images that `emoji-datasource` fills in from the Apple sprite sheet, which has unclear licensing implications, so we don't want to use that.
To be able to support newer emoji, we will explicitly fallback to Google Modern for any emoji not covered by Twemoji.
CZO conversation:
https://chat.zulip.org/#narrow/stream/107-kandra/topic/emoji.20changes.20in.208.2E0/near/1689918
<details>
<summary>typeahead (in compose and emoji picker)</summary>
</details>
<details>
<summary>with google modern selected:</summary>
</details>
<details>
<summary>with …
> emoji: Fallback to Google Modern for unsupported new Twitter emoji.

- web/src/time_zone_util.ts
- web/tests/time_zone_util.test.js
Safari doesn’t support it yet.
> time_zone_util: Avoid relying on `timeZoneName: "longOffset"`

- help/change-a-users-role.md
- help/guest-users.md
- help/roles-and-permissions.md
- help/stream-permissions.md
- help/zulip-cloud-billing.md
This is a follow-up PR (see #27917) to document the new  setting that configures the `(guest)` indicator, and add links to the guest users page from relevant docs.
- https://chat.zulip.org/help/guest-users
<details>
</details>
> help: Document "(guest)" indicator setting.

- templates/zerver/app/index.html
- web/src/about_zulip.ts
- web/src/upload.js
- web/styles/zulip.css
- web/tests/upload.test.js
With respect to the documentation added in #27536 we should extend the drag-and-drop upload area to the blank spaces on either end of the app just after the sidebars.
Fixes: #27550.
- Beyond Left Sidebar
- Beyond Right Sidebar
- Normal App area upload
(Edit 1)
- Sidebars + Navbar
<details>
</details>
> uploads: Extend drag and drop upload area to blank areas after sidebars.

- analytics/views/remote_activity.py
- templates/analytics/ad_hoc_query.html
- templates/analytics/remote_activity_key.html
**1st commit**:
- Adds a column to the remote servers activity page for a 7-day count of forwarded mobile push notifications from
`RemoteInstallationCount` for each server, which will be `None` if there is no data for the remote server with that ID.
- This expands the current query for the new data since we're already getting data on all remote servers here.
- Manually tested by adding a remote server and countstat via `populate_analytics_db.py` and rebuilding the dev database (`tools/rebuild-dev-database`) with those changes and comparing the query data to the database via `./manage.py dbshell`.
<details>
<summary>populate_analytics_db for testing</summary>
replace FixtureData and insert_fixture_data function with below:
```python
import uuid
from zilencer.models import …
```
> analytics: Add mobile pushes forwarded column to remote activity page.

- templates/analytics/activity.html
- templates/analytics/activity_details_template.html
- templates/analytics/ad_hoc_query.html
- templates/analytics/realm_summary_table.html
- web/styles/portico/activity.css
**Notes**:
- Removes use of bootstrap "container" class from analytics activity pages. Note it is still used in the support view pages.
- Adds "activity-page" class to give a slight margin to the page content on activity pages in general. This pushes the "Home" link and other content away from the edge of the browser.
- Renames "analytics_table" class to "analytics-table" and "activity_head" class to "activity-head". This makes it easier to grep for these CSS classes.
- Stops setting `width` on the installation and activity tables and instead gives a small 10px right/left margin to the tables. As a result, the tables are no longer centered on the page, but since width is no longer being set by the bootstrap "container" class, this should help with overflow issues.
- Sets the max-width on …
> analytics: Adjust width and margin CSS for activity pages.

- web/src/sidebar_ui.js
- web/src/stream_list.js
- web/styles/app_components.css
- web/styles/left_sidebar.css
- web/styles/zulip.css
- web/templates/left_sidebar.hbs
In addition to displaying a hoverable unread dot on STREAMS based on the user preference to do so, this PR introduces a subtle dark-mode color for masked unread dots. Previously, the shade used in light mode was also used in dark mode, where it appeared considerably more intense.
Fixes: #27762
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/unread.20dot.20color.20on.20Streams/near/1691388) (dot color)
| --- | --- |
| <img width="295" alt="masked-unread-light-before" src="https://github.com/zulip/zulip/assets/170719/6822ac27-6e7f-401f-aded-54b150614235"> | <img width="295" alt="masked-unread-light-after" src="https://github.com/zulip/zulip/assets/170719/e86659da-068f-4ddb-a7b2-cce1298f276d"> |
| <img …
> left_sidebar: Respect unread display settings on STREAMS header.

- corporate/tests/test_stripe.py
- corporate/views/support.py
- corporate/views/upgrade.py
- zerver/lib/digest.py
- zerver/lib/email_notifications.py
- zerver/lib/send_email.py
- zerver/tests/test_email_change.py
- zerver/tests/test_management_commands.py
- zerver/tests/test_message_notification_emails.py
- zerver/tests/test_realm.py
- zerver/tests/test_signup.py
- zproject/default_settings.py
- zproject/prod_settings_template.py
Currently, the **sender names** for outgoing emails sent by Zulip **are hardcoded**. It **should be configurable for self-hosted** systems.
The first commit performs minor upgrade in  'from_name' text for **non user-facing emails**:
* `Zulip Support`
* `Zulip Sponsorship` 
The second **commit makes the 'Zulip' part a variable** in the following email sender names: 
* `Zulip Account Security`
* `Zulip Digest`
* `Zulip Notifications`
by introducing a settings variable `SERVICE_NAME` with the default value as f"{EXTERNAL_HOST} Zulip".
**Note**: Default value can be `{realm_name}` or `{realm_host}` or `EXTERNAL_HOST`. (It is yet to be decided as discussed in the [issue description](https://github.com/zulip/zulip/issues/23857).)
**Update**: Default value = f"{EXTERNAL_HOST} Zulip"
Fixes: …
> send_email: Improve configurability for Zulip outgoing email sender name.

- corporate/lib/remote_billing_util.py
- corporate/urls.py
- corporate/views/remote_billing_page.py
- templates/corporate/legacy_server_login.html
- web/src/billing/legacy_server_login.ts
- web/styles/portico/billing.css
- web/webpack.assets.json
Missing tests, but they should be  easy once we agree this is roughly the way this is supposed to work.
Adds a flow for legacy servers that don't have `RemoteRealm` registrations.  At the end redirects to the dummy page that shows basic info, just like in #27575
The form's mechanism is mostly inspired by our login for at `/login/` 
Here's a screencast showing how it works, including an error. This is very crude and basic and we may want to open a follow-up issue for styling this properly?
[Screencast from 2023-11-29 21-35-15.webm](https://github.com/zulip/zulip/assets/45007152/1f8b837f-c3de-4caa-ba75-b096047f8f54)
> [WIP] remote_billing: Add flow for legacy servers.

- analytics/management/commands/update_analytics_counts.py
- docs/overview/changelog.md
- docs/production/mobile-push-notifications.md
- zerver/lib/remote_server.py
- zerver/tests/test_push_notifications.py
These metadata are essentially all publicily available anyway, and
making uploading them unconditional will simplify some things.
The documentation is not quite accurate in that it claims the server
will upload some metadata that is not actually uploaded yet (but will
by soon). This seems harmless.
@mateuszmandera can you fix the tests? Feel free to add other adjacent stuff to this PR.
> push bouncer: Submit basic metadata unconditionally.

- api_docs/changelog.md
- zerver/lib/events.py
- zerver/lib/push_notifications.py
- zerver/openapi/zulip.yaml
- zerver/tests/test_auth_backends.py
- zerver/tests/test_message_edit_notifications.py
- zerver/tests/test_message_flags.py
- zerver/tests/test_push_notifications.py
- zerver/views/auth.py
Prototype of the API detailed in https://chat.zulip.org/#narrow/stream/378-api-design/topic/register.3A.20Be.20more.20informative.20about.20push-bouncer.20setup/near/1686802.
> WIP: Push notifications enabled migration to have current information about bouncer registration state

- tools/setup/emoji/build_emoji
CZO conversation:
https://chat.zulip.org/#narrow/stream/107-kandra/topic/emoji.20changes.20in.208.2E0/near/1690617
google blob:
google modern:
twitter:
> emoji: Use individual emoji images instead of a sprite sheet.

- puppet/zulip/manifests/profile/rabbitmq.pp
The Ubuntu and Debian package installation scripts for `rabbitmq-server` install `/etc/rabbitmq` (and its contents) owned by the `rabbitmq` user -- not `root` as Puppet does.  This means that Puppet and `rabbitmq-server` unnecessarily fight over the ownership.
Create the `rabbitmq` user and group, to the same specifications that the Debian package install scripts do, so that we can properly declare the ownership of `/etc/rabbitmq`.
<details> …
> puppet: Change /etc/rabbitmq to be owned by rabbitmq.

- web/styles/modal.css
- web/styles/zulip.css
This was due to color variables not being accessible as `zulip.css` is not a file we import on billing page.
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/cancel.20button.20styling.20in.20billing.20flow
@karlstolley FYI
> css: Fix modal exit button colors not working on billing pages.

- web/src/message_view_header.js
- web/templates/message_view_header.hbs
This PR encompasses the following changes:
1. Hide the subscriber count on the message view header tooltip for spectators, since this information is not available to such users.
2. Rename the variables `message_view_header` and `message_view_header_data` with `context`. We also rename the function `make_message_view_header` with `get_message_view_header_context`.
Fixes: We used to show "_This stream has no subscribers_" to the guest user, when it reality the subscriber count was unavailable.
CZO discussion: [Link](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20weird.20stream.20tooltip.20for.20logged.20out.20users/near/1691644)
- Tooltip for a spectator
- Tooltip for a logged-in user
<details> …
> message_view_header: Update tooltip when user is not logged in.

- corporate/lib/decorator.py
- corporate/lib/remote_billing_util.py
- corporate/tests/test_remote_billing.py
- corporate/views/remote_billing_page.py
This does two important things:
1. Fix return type of get_identity_dict_from_session to correctly be Optional[Union[RemoteBillingIdentityDict, LegacyServerIdentityDict]]. RemoteBillingIdentityDict is the type in the 8.0+ auth flow, LegacyServerIdentityDict is the type in old servers flow, where only the server uuid info is available.
2. The uuid key used in request.session["remote_billing_identities"] should be explicitly namespaced depending on which flow and type we're dealing with - to avoid confusion in case of collisions between a realm and server that have the same UUID. Such a situation should not occur naturally and I haven't come up with any actual exploitation ideas that could utilize this by manipulating your server/realm uuids, but it's much easier to just not think about such …
> remote_billing: Sort out remote_billing_identities typing and add session expiry mechanism.

- web/images/icons/zulip-icons.font.js
We’re currently generating the icon font in five formats: Embedded OpenType, WOFF, WOFF2, TrueType, and SVG. But they’re [misordered](https://github.com/jeerbl/webfonts-loader/pull/219) by webfonts-loader such that modern browsers always select the WOFF version. WOFF2 is [supported](https://caniuse.com/woff2) by all modern browsers, so just use that exclusively.
(The [EOT](https://caniuse.com/eot) and [SVG font](https://caniuse.com/svg-fonts) formats are obsolete and no longer supported.)
> zulip-icons: Use WOFF2 format for icon font

- puppet/zulip_ops/files/nagios_plugins/zulip_zephyr_mirror/check_user_zephyr_mirror_liveness
Limiting only by client_name and query leads to a very poorly-indexed lookup on `query` which throws out nearly all of its rows:
```
Nested Loop  (cost=50885.64..60522.96 rows=821 width=8)
->  Index Scan using zerver_client_name_key on zerver_client  (cost=0.28..2.49 rows=1 width=4)
Index Cond: ((name)::text = 'zephyr_mirror'::text)
->  Bitmap Heap Scan on zerver_useractivity  (cost=50885.37..60429.95 rows=9052 width=12)
Recheck Cond: ((client_id = zerver_client.id) AND ((query)::text = ANY ('{get_events,/api/v1/events}'::text[])))
->  BitmapAnd  (cost=50885.37..50885.37 rows=9052 width=0)
->  Bitmap Index Scan on zerver_useractivity_2bfe9d72  (cost=0.00..16631.82 rows=..large.. width=0)
Index Cond: (client_id = zerver_client.id)
->  Bitmap Index Scan on zerver_useractivity_1b1cc7f0 …
```
> nagios: Use a better index on UserActivity for zephyr alerting.

- api_docs/changelog.md
- version.py
- zerver/openapi/zulip.yaml
- zerver/tests/test_auth_backends.py
- zerver/views/auth.py
This PR reverts the API changes in 56ec1c2.
<details>
</details>
> notifications: Revert API changes for push_notifications_enabled.

- web/src/left_sidebar_navigation_area.js
This corrects a small oversight from #27501, where the tabindex on a previous home view wasn't removed from the correct element. This also reorders the class and tabindex removal to match the comment above.
<details>
</details>
> left_sidebar: Remove tabindex from correct home-view element.

- zerver/actions/create_realm.py
- zerver/lib/import_realm.py
- zerver/lib/remote_server.py
- zerver/tests/test_import_export.py
- zerver/tests/test_realm.py
- zerver/worker/queue_processors.py
Queues up an order to `deferred_work` to call `send_realms_only_to_push_bouncer()` in:
1. `do_create_realm`
2. `do_import_realm`
> realms: Call send_realms_only_to_push_bouncer at realm creation/import.

- web/src/message_edit.js
Hiding the spinner confusingly flashes the Save button before the edit view closes. This just prevents that from happening, so that the sign of success is the rendered, edited message.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20.22Save.22.20button.20states/near/1692911)
Spinner remains until the message-edit form closes:
<details>
</details>
> message_edit: Don't hide spinner on save success.

- corporate/lib/decorator.py
- corporate/lib/remote_billing_util.py
- corporate/tests/test_remote_billing.py
- corporate/views/remote_billing_page.py
- templates/corporate/legacy_server_login.html
- zerver/lib/exceptions.py
- zerver/views/push_notifications.py
Edit: the PR message below is outdated, it's from the original approach to this for just the RemoteRealm flow. See the message on `remote_billing: Add redirect flow for users with expired session` and `remote_billing: Add redirects to login for unauthed user in legacy flow` for descriptions of their mechanism
------
Implements a nice redirect flow to give a good UX for users attempting to access a remote billing page without a valid session e.g. `/realm/some-uuid/sponsorship` unauthed - perhaps through their browser history or just their session expired while they were doing things in this billing system.
The logic has two pieces:
1. `get_remote_realm_from_session`, if the user doesn't have a valid identity_dict will raise `MissingAuthenticationError`.
2. The decorator …
> remote_billing: Implement a redirection flow for unauthed users.

- help/follow-a-topic.md
Notes:
- This PR documents that recent conversations has a "followed" filter now.
- Also adds a few links.
- We don't list specific filters on the recent conversations page, since we plan to revamp them. So don't have to update anything there.
- I kept the section recommending using Inbox for catching up on followed topics as-is.
Current: https://zulip.com/help/follow-a-topic
Updated:
> help: Update documentation on followed topics in recent conversations.

- .gitignore
- docs/subsystems/settings.md
- zproject/computed_settings.py
- zproject/configured_settings.py
- zproject/dev_settings.py
- zproject/test_extra_settings.py
- zproject/test_settings.py
Extracted from #28017; see https://github.com/zulip/zulip/pull/28017/commits/3f40f4598ca84e52d4355959204ada188bbfa075#r1413157005 for context.
> Add support for overriding development environment settings

- web/src/user_profile.js
Previously, when the user modal is opened, and a stream is selected from the streams tab, and then, when a new tab is selected and you navigate back to this streams tab and try to pick a new stream, it wouldn't allow you to do so.
This is because, previously once a stream is picked, and you go out of the tab and come back, then the
previous object of the subscribe widget was invalidated and a new object was created. However, the options still corresponded to the old object. Hence, the error.
This is fixed by checking out if a stream widget object exists, before creating a new one. Before the user profile modal is rendered, the object is initialized to undefined to avoid using of old object in new modal.
Fixes: #27422
Fixes: 
<details> …
> stream_settings: Fix stream settings dropdown of user profile.

- web/src/compose_actions.js
- web/src/compose_tooltips.js
- web/src/tippyjs.ts
compose: Show tooltip instantly for a `.disabled-on-hover` button.
We have some delay for tooltips for all compose buttons, but we would like to show the tooltip instantly for buttons that are disabled on hover, to emphasize that the button is disabled, and why.
compose: Fix bug where poll button was disabled on opening compose box.
On opening the compose box right after closing it with some text in it, the poll button would wrongly be disabled.
This is now fixed by ensuring to reset the button state on opening the compose box.
<details> …
> compose: Fix issues with the new poll button.

- analytics/tests/test_activity_views.py
- analytics/views/remote_activity.py
- zilencer/models.py
This PR adds two columns named 'Guest users' and 'Non guest users' to represent count of such users.
We query 'RemoteRealmAuditLog' to get the data.
**Steps for manual testing**
* Uncomment the bottom two lines of zproject/dev_settings.py to use localhost as a push notifications bouncer.
* start server: `./tools/run-dev`
* Run manage.py register_server and register your server (as the local server) with itself (as the bouncer).
* Restart server
* In `update_remote_realm_data_for_server` add `ignore_conflicts=True` 
```
try:
RemoteRealm.objects.bulk_create(new_remote_realms, ignore_conflicts=True)
```
Reason: This is an existing bug in main. So, I'd fix that separately.
* In `update_analytics_counts.py` change (60*10) to (5) -- reduced delay to 5 second
* Run management command `manage.py …
> remote_activity: Add 'guest users' and 'non guest users' count column.

- analytics/tests/test_support_views.py
- analytics/views/installation_activity.py
- analytics/views/support.py
- corporate/lib/stripe.py
- templates/analytics/remote_realm_details.html
- templates/analytics/remote_server_support.html
- web/styles/portico/activity.css
Expands the support view for remote servers for:
- Displaying the current `CustomerPlan` information for the remote server.
- Updating the billing modality for the current `CustomerPlan`.
- Modifying the current `CustomerPlan` for various downgrade actions.
- Adds information about the remote server's plan type.
- Adds information about any remote realms attached to the remote server.
**Notes**:
- Updated query for remote servers in the final commit (adds remote realm information) may not be the most efficient way to add this information. Calling a `RemoteRealm` query on the loop over the remote servers also didn't seem like a good option.
- Not sure if it would be better to hide the update billing modality for legacy plans, see 3rd commit.
- CSS changes just add some small margins to …
> support: Expand remote servers support view.

- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
- zerver/actions/create_user.py
- zerver/actions/users.py
* First commit: Moves the `update_license_ledger_for_manual_plan` function to the `BillingSession` abstract class.
* Second commit: Moves `update_license_ledger_if_needed` and `update_license_ledger_for_automanaged_plan` to `BillingSession`.
<details>
</details>
> stripe: Refactoring related to current license count.

- zilencer/management/commands/populate_db.py
As of c9b060232005e34d31e87a35c6a96582f1f88af8 and 8b55d60f9e0365e47dadd4d82b7946e9c8f53149 we create a default registration for the dev env "RemoteZulipServer" (and also RemoteRealms for the dev realms) in populate_db. However these models weren't listed in clear_database, meaning the state wasn't properly cleaned up at the start of the command.
Most important, this would manifest in getting:
```
django.db.utils.IntegrityError: duplicate key value violates unique
constraint "zilencer_remotezulipserver_uuid_key"
DETAIL:  Key (uuid)=(......) already exists
```
if you re-run populate_db.
> populate_db: Clean up existing RemoteRealm, RemoteZulipServer objects.

- analytics/tests/test_support_views.py
- corporate/lib/support.py
- templates/analytics/current_plan_details.html
- templates/analytics/realm_details.html
- templates/analytics/remote_server_support.html
- web/styles/portico/activity.css
Updates the support and remote support views to use a shared template for the current plan details section.
**Notes**:
- Per https://github.com/zulip/zulip/pull/28047#discussion_r1415936156, uses a boolean value to check for the one plan tier that we expect to not have any licenses information.
- Handles, in the 2nd commit, when the remote support view doesn't have current data for the number of licenses used.
<details>
<summary>Support view for realm after changes - smaller header for the current plan section</summary>
</details>
<details>
<summary>Legacy tier remote support view - without and with missing current licenses data</summary>
</details>
<details>
<summary>Business tier remote support view - without and with missing current licenses …
> support: Use shared template for current plan details in support views.

- corporate/lib/stripe.py
- corporate/lib/support.py
- corporate/views/support.py
- templates/zerver/emails/sponsorship_request.html
- templates/zerver/emails/sponsorship_request.subject.txt
- templates/zerver/emails/sponsorship_request.txt
- zerver/actions/create_realm.py
Makes some updates to the sponsorship request email sent to support.
**Notes**:
- The first commit removes the `string_id` from the context, which is used in the email header, and replaces it with the `BillingSession.billing_entity_display_name`. This is no change for organizations requesting sponsorship on Zulip Cloud.
- The second commit implements `support_url` for all the `BillingSession` child classes. Note the query for the support view for a remote realm is based on the attached remote server.
- The third commit updates the email templates for the new information in the form for sponsorship requests.
<details>
<summary>Sponsorship request for regular organization - both text and HTML versions</summary>
</details>
<details>
<summary>Sponsorship …
> corporate: Update sponsorship request emails sent to support.

- zerver/lib/narrow.py
- zerver/tests/test_message_fetch.py
These confused `ok_to_include_history` and caused exceptions looking for the "flags" column.
<details>
</details>
> narrow: Prevent contradicting DM and stream narrows.

- zerver/lib/push_notifications.py
- zerver/lib/remote_server.py
- zerver/tests/test_push_notifications.py
The comments explain the context, but we shouldn't mark our access to push notifications as disabled incorrectly here.
We have some existing nocoverage markers in this code that probably should be fixed in a separate PR that also moves this code to be reusable.
> push_notifications: Fix handling of 500s from bouncer.

- api_docs/changelog.md
- version.py
- zerver/lib/push_notifications.py
- zerver/openapi/zulip.yaml
- zerver/tests/test_push_notifications.py
Adds `user.realm.string_id` as the realm name to the base payload for notifications. Uses this realm name in the body of the alert in the `apns_data`.
Changes the event string from "test-by-device-token" to "test".
See [relevant conversation on CZO](https://chat.zulip.org/#narrow/stream/378-api-design/topic/.2323997.20Endpoint.20for.20test.20notification/near/1696957).
---
<details>
</details>
> push-notifications: Update payload for realm name and event string.

- web/src/scheduled_messages_feed_ui.js
- web/src/scheduled_messages_ui.js
We now pass empty string as stream name instead of undefined when passing the narrow
operands to make sure we show an invalid narrow instead of error. We do same thing for drafts.
We also need to add a check to make sure narrow_state.stream_sub is defined before accessing
stream_id field in the code to filter scheduled messages for a narrow.
Before
After
<details>
</details>
> scheduled_message: Fix editing msg scheduled to inaccessible stream.

- zerver/context_processors.py
- zproject/computed_settings.py
Context is only available for functions inside corporate app.
> context_processors: Add common context to be used in corporate pages.

- web/src/message_list_tooltips.js
This PR decouples the reaction button Tippy logic from other reaction pills, and introduces a longer delay. Additionally, it suppresses the reaction-button tooltip when the emoji picker is open.
CZO discussion
| --- | --- |
| ![reaction-button-tooltip-before](https://github.com/zulip/zulip/assets/170719/c9f78adb-3cf6-4f05-8eab-c9936e392023) | ![reaction-button-tooltip-after](https://github.com/zulip/zulip/assets/170719/581f6b88-7e08-437f-b56e-81ee3d967df4) |
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit …
> message_list: Add delay, tooltip suppression to reaction button.

- docs/production/mobile-push-notifications.md
The "nothing else" line is accurate at a high level but more ambigious
than I'd like for sensitive documentation -- we're not trying to make
an extreme claim that we've disabled all forms of short-term logging.
> docs: Tweak mobile push notifications privacy text.

- zerver/management/commands/register_server.py
Includes a proposed way of having an extra prompt + the --submit-realms-data arg for skipping the prompt (analogical to --agree_to_terms_of_service), to have a reasonable user experience with this command.
Example from terminal:
```
./manage.py register_server
The following data will be submitted to the push notification service:
contact_email: desdemona+admin@zulip.com
hostname: zulipdev.com:9991
zulip_org_id: xxx
zulip_org_key: xxxxxxxxxx
To register, you must agree to the Zulipchat Terms of Service: https://zulip.com/policies/terms
Do you agree to the Terms of Service? [Y/n] 
You've successfully registered for the Mobile Push Notification Service!
Now initial realms data needs to be submitted.
Proceed? [Y/n] 
Successfully submitted realms data.
To finish setup for sending push …
```
> register_server: Update the prompt.

- zproject/dev_settings.py
- zproject/test_extra_settings.py
We already override PUSH_NOTIFICATION_BOUNCER_URL in test_extra_settings.py, so making this change should have as its only impact making it a bit easier to test the push notifications bouncer manually in a development environment.
I submitted a related PR to the mobile app documentation for testing the push notifications software against a production server motivated by this.
> settings: Simplify testing push bouncer.

- help/guest-users.md
- help/include/cloud-plus-only.md
- help/include/upgrade-to-plus-if-needed.md
- help/scim.md
Verification that I describe this correctly, an any other feedback, are appreciated!
Blockers:
- Renaming the setting, and getting this feature enabled in production.
- For the last commit, deploying the new /plans page is a blocker for deploying this.
> help: Document new limited guests feature.

- corporate/tests/test_remote_billing.py
- corporate/views/remote_billing_page.py
- help/self-hosted-billing.md
- templates/zerver/emails/remote_billing_legacy_server_confirm_login.html
- templates/zerver/emails/remote_billing_legacy_server_confirm_login.subject.txt
- templates/zerver/emails/remote_billing_legacy_server_confirm_login.txt
- templates/zerver/emails/remote_realm_billing_confirm_login.html
- templates/zerver/emails/remote_realm_billing_confirm_login.subject.txt
- templates/zerver/emails/remote_realm_billing_confirm_login.txt
Also adds a basic help page to link to (not linked from the left sidebar yet).
Someone should take an engineering cleanup pass on this:
- There are probably emails/urls that should be put in variables somewhere.
- I'm not sure I got all the translation tags quite right.
> emails: Adjust wording in server log in link email.

- analytics/views/support.py
- corporate/lib/support.py
- templates/analytics/current_plan_forms_support.html
- templates/analytics/remote_realm_details.html
- templates/analytics/remote_server_support.html
- templates/analytics/sponsorship_forms_support.html
- web/styles/portico/activity.css
Updates the remote server support view so that any remote realms attached to a remote server have the same forms/actions for support admin (e.g. sponsorship requests, discounts, modifying current plan actions).
<details>
<summary>business remote realm example</summary>
</details>
<details>
<summary>Sponsorship requested & sponsored remote realms</summary>
*Are we planning that 100% sponsored remote realms/servers will also have a current plan? Or is this just an error with how we're generating that in populate_billing_realms?*
<details> …
> support: Add forms for attached remote realms.

- web/styles/popovers.css
- web/styles/zulip.css
This PR adds the following changes:
- **Fix padding of items in org info section.**
Add padding to org info items to avoid collision on text with the menu boundary
- **Let menu items control the width of dropdown menus.**
We set the width of the navbar dropdowns to be equal to the longest menu item, via the min-content intrinsic sizing.
- **Add text wrapping to long org names.**
Some organizations may have long names that could blow up the gear menu width, in those cases we want to prevent it by wrapping the org name.
- **Fix font size of org plan.**
As per the intended design, the font size of the org plan should be equal to the font size of other similar links such as org version.
- **Align org info menu items to the left.**
This maintains consistency across the whole gear menu.
CZO: …
> gear_menu_popover: Various fixes and improvements related to dropdown menu width and org info.

- requirements/dev.in
- requirements/dev.txt
It’s still used indirectly via Scrapy, but we haven’t used it directly since commit 09e17fbe17fecb3b83ef80a0e04248e7387f328f (#2002).
Skipping a `PROVISION_VERSION` bump because this has no real effect.
> requirements: Remove direct requirement on Twisted

- web/src/popover_menus_data.js
- web/styles/left_sidebar.css
- web/styles/popovers.css
- web/styles/zulip.css
- web/templates/stream_sidebar_actions.hbs
- web/templates/topic_sidebar_actions.hbs
**Changes:**
- Set popover width based the longest menu item. (`min-content` sizing)
- Allow topic name to wrap across multiple lines.
- Left align the topic name.
- Remove the '>' icon.
- Change `<p>` tag to `<div>` and replace `<b>` tag with `font-weight` property.
- Set popover width based the longest menu item. (`min-content` sizing)
- Allow stream name to wrap across multiple lines.
- Left align the stream name.
- Change `<p>` tag to `<div>` and replace `<b>` tag with `font-weight` property.
- Restructured popover-related CSS and sensible renaming, to avoid CSS overlapping.
Fixes: #27562.
CZO Discussions: [#design](https://chat.zulip.org/#narrow/stream/101-design/topic/topic.20menu.20with.20long.20topic/near/1671161) and [#frontend](https://chat.zulip.org/#narrow/stream/6-frontend/top …
> popovers: Add dynamic width, structural changes and other small improvements to stream and topic action popovers.

- analytics/management/commands/update_analytics_counts.py
- corporate/tests/test_remote_billing.py
- zerver/actions/create_realm.py
- zerver/actions/create_user.py
- zerver/actions/realm_settings.py
- zerver/actions/users.py
- zerver/lib/import_realm.py
- zerver/lib/push_notifications.py
- zerver/lib/remote_server.py
- zerver/lib/sessions.py
- zerver/management/commands/register_server.py
- zerver/models.py
- zerver/tests/test_import_export.py
- zerver/tests/test_push_notifications.py
- zerver/tests/test_realm.py
- zerver/views/push_notifications.py
- zerver/worker/queue_processors.py
Actions that change the number of user counts adds a deferred_work queue processor job immediately update the billing service about your change.
This helps to avoid having users see stale state for how many users they have when trying to pay.
<details>
</details>
> remote_server: Immediately send analytics on user count change.

- zerver/lib/push_notifications.py
- zerver/tests/test_push_notifications.py
- zilencer/views.py
This lets the self-hosted server clean them up too.
Addresses a part of #27483 (https://github.com/zulip/zulip/issues/27483#issuecomment-1791089638 specifically), but needs a couple of extra things mentioned there to close the issue.
> zilencer: Have push/notify endpoint return deleted registrations.

- zerver/tornado/handlers.py
4af00f61a8c4b779365a5e7b8746716b7f32e837 claimed that `on_finish` and `on_connection_close` were mutually exclusive.  In cases where a `DELETE` is called on the queue while a longpoll is in progress, this can cause _both_ to happen:
- The `DELETE` pushes a `cleanup_queue` event, which triggers `finish_handler` to begin pushing out an empty event response to the longpoll connection.
- In the midst of that, in an `await`, the longpoll connection drops, and `on_connection_close` clears the handler.
- The `await` resumes, calls `finish`, and attempts to clear the handler.
The easiest solution is to make `clear_handler_by_id` tolerant to multiple attempts to clear it.  Since these processes run in parallel, it means that parts may have a `handler_id` but `get_handler_by_id` may error in …
> tornado: Support clearing a handler more than once.

- web/src/topic_generator.js
- web/tests/topic_generator.test.js
[CZO issue report](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20Shift.2BN.20in.20muted.20stream/near/1690781)
* The Shift+N shortcut is not working to go to a followed topic in a muted stream
*  Go to followed or unmuted topics using N if they are in muted streams
<details>
</details>
> hotkey: Fix `N` and `Shift + N` behaviour for muted streams.

- help/guest-users.md
Fixes #28131.
Current: https://zulip.com/help/guest-users#configure-whether-guests-can-see-all-other-users
Updated:
> help: Document limited guest user API access to presence updates.

- help/follow-a-topic.md
- help/include/automatically-follow-topics.md
Current:
- https://zulip.com/help/follow-a-topic#automatically-follow-topics
- https://zulip.com/help/topic-notifications#automatically-follow-topics
Updated:
> help: Document setting to automatically follow topics when mentioned.

- analytics/views/support.py
- templates/analytics/remote_realm_details.html
**Notes**:
- Corrects two references in `remote_realm_details.html` to be remote_realm (instead of remote_server).
- Excludes the system bot realm from the remote realms listed in the support view for a remote server.
<details>
</details>
> support: Fix remote realm details.

- zerver/lib/queue.py
If the exception was because the channel closed, attempting to NAK the events will just raise another error, and is pointless, as the server already marked the pending events as NAK'd.
<details>
</details>
> queue: Only NAK the events if the channel is still open.

- zerver/tornado/event_queue.py
- zerver/tornado/handlers.py
As premonitioned in c741c527d7cc56d7a4999257b7332ce2441bf63b, it is indeed possible for `get_handler_by_id` to error out by cause the handler has been unset elsewhere.
Protect the callsites of `get_handler_by_id` to be able to gracefully handle when the handler has already done away.
<details>
</details>
> tornado: Handle the handler having been cleared by connection close.

- templates/corporate/pricing_model.html
| Cloud, logged in | Self-hosted, logged in (no change)|
| --- | --- |
| ![Screen Shot 2023-12-12 at 10 12 12](https://github.com/zulip/zulip/assets/170719/4419dd86-54bc-4c9a-9f5a-0834fcc1b271) | ![Screen Shot 2023-12-12 at 10 06 57](https://github.com/zulip/zulip/assets/170719/80cb24ec-69ee-4276-a105-b347ffc3bf39) |
<details>
</details>
> portico: Disable self-hosted tab for logged-in cloud users.

- corporate/lib/stripe.py
- corporate/tests/test_remote_billing.py
- corporate/urls.py
- corporate/views/billing_page.py
- corporate/views/remote_billing_page.py
- templates/corporate/remote_billing_server_deactivate.html
- templates/corporate/remote_billing_server_deactivated_success.html
- web/src/billing/deactivate_server.ts
- web/webpack.assets.json
This is a general link for logging into the billing system on behalf of a server, but it's tied to the .contact_email and takes the user straight to the /deactivate/ page via the next_page mechanism.
The `generate_confirmation_link_for_server_deactivation` can be used to generate and send these in emails to self hosters.
Screencast of using the link:
[Screencast from 2023-12-12 19-08-16.webm](https://github.com/zulip/zulip/assets/45007152/16bd5aa9-8219-4251-ba7e-40f2dffd172d)
> remote_billing: Add endpoint and a helper to make deactivation links.

- zerver/management/commands/register_server.py
This currently _works_, but only because we are very forgiving about how we parse requests.
<details>
</details>
> register_server: POST requests take data, not params.

- corporate/tests/test_remote_billing.py
- corporate/views/remote_billing_page.py
- templates/corporate/remote_billing_confirm_email_form.html
- templates/corporate/remote_billing_email_confirmation_sent.html
These updates are only for RemoteRealms; legacy self-managed logins should be unaffected.
| Remote realm login | Remote realm confirm |
| --- | --- |
| <img width="1181" alt="Screenshot 2023-12-12 at 1 38 37 PM" src="https://github.com/zulip/zulip/assets/170719/7373c69f-dfa9-414f-8ad4-148388d63cda"> | <img width="1181" alt="Screenshot 2023-12-12 at 1 39 27 PM" src="https://github.com/zulip/zulip/assets/170719/63469730-2698-4dab-b6ef-e2509ca4e174"> |
<details> …
> portico: Update strings for RemoteRealm login flow.

- web/src/compose_actions.js
- web/src/views_util.js
Currently, given that the compose box is already open, it stays open when the user navigates to the inbox/recent view, even when there are no modifications to the message or recipients.
This PR adds conditions to close the compose box when navigating to the inbox/recent view, except when we can reasonably infer that it was the intended action.
Fixes: [Issue reported at CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/compose.20box.20tooltips.20lag.20.2327158/near/1697754)
[before-compose-actions-fix.webm](https://github.com/zulip/zulip/assets/82862779/dddcc09a-6894-43e6-a0cd-bcf1d9fd7a4c)
[after-compose-actions-fix.webm](https://github.com/zulip/zulip/assets/82862779/3b6881de-1c22-417c-932e-eaf50cd14fee) 
<details> …
> compose_actions: Hide compose box when navigating to inbox/recent view.

- zerver/lib/remote_server.py
- zerver/tests/test_push_notifications.py
This PR adds code to make sure that the push
notification does not crash on receiving data for
a non-existent realm.
<details>
</details>
> remote_server: Handle data of non existent realms.

- analytics/tests/test_activity_views.py
- analytics/views/remote_activity.py
- corporate/lib/analytics.py
- corporate/lib/stripe.py
- templates/analytics/remote_activity_key.html
Adds two columns to the chart for remote servers on the remote activity support page:
- Whether the server (or attached realms) has a customer plan with an "Active" status.
- The annual revenue for that customer plan.
**Notes**:
- The 4 additional queries in the activity test for the remote active page are:
- the new query to get the customer plans
- 2 queries on the LicenseLedger table via the first two lines of `make_end_of_cycle_updates_if_needed`
- an additional query on `get_remote_server_guest_and_non_guest_count` as I added a realm without an active plan for test coverage.
<details>
<summary>Remote activity - updated</summary>
</details>
---
<details> …
> support: Add plan information to remote activity page.

- corporate/lib/analytics.py
Quick follow-up to #28171. Updates query of CustomerPlan objects to filter for `customer__realm__isnull=True`.
<details>
</details>
> support: Filter remote realm data query for customer realm None.

- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
- corporate/views/remote_billing_page.py
Adds `BILLING_SUPPORT_EMAIL` to `stripe.py` so that it can be consistently used in billing code.
<details>
</details>
> corporate: Add billing support email constant.

- zerver/tests/test_invite.py
- zerver/tests/test_signup.py
- zerver/views/registration.py
While the query parameter is properly excaped when inlined into the
template (and thus is not an XSS), it can still produce content which
misleads the user via carefully-crafted query parameter.
Validate that the parameter looks like an email address.
Thanks to jinjo2 for reporting this, via HackerOne.
<details>
</details>
> registration: Prevent injecting arbitrary strings via query param.

- web/templates/settings/organization_settings_admin.hbs
- zerver/lib/validator.py
- zerver/tests/test_realm.py
- zerver/views/realm.py
- First commit is to raise error at API level for long url.
- Second commit is to set max length in input UI.
<details>
</details>
> Handle long url for `jitsi_server_url` setting.

- zerver/tests/test_push_notifications.py
- zilencer/views.py
A deactivated server shouldn't be updated like that - we want to return an error.
> zilencer: Fix server/register failing to check if server is deactivated.

- web/src/stream_edit_toggler.ts
Followup to #27637.
This fixes a bug in #26717 (not merged yet) where the hash would flash to #personal before #subscribers. Sometimes `setup_toggler` is called after the hash change, and it needs to know which tab to show.
Ideally in the future we'd clean up this code so that the hash changing function isn't called multiple times.
> stream edit toggler: Update `select_tab` when changing hash."

- zerver/lib/send_email.py
For remote servers, we cannot advertise `List-Unsubscribe=One-Click`, which is specified in RFC 8058[^1] to mean that the `List-Unsubscribe` URL supports a POST request with no arguments to unsubscribe.  Because we show an interstitial and confirmation page, as this is not just a mailing list which is disabled if you click the link, it does not support the mail system performing the unsubscribe for the user.
Remove the inaccurate header for remote servers.
[^1]: https://datatracker.ietf.org/doc/html/rfc8058
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-disci …
> send_email: Remove `List-Unsubscribe-Post` from remote-server emails.

- corporate/lib/stripe.py
- templates/zerver/emails/sponsorship_request.html
* Show if requested org is hosted on Zulip Cloud.
* Change how user numbers are displayed.
> sponsorship_request: Minor changes.

- zilencer/views.py
We could be incorrectly logging the can_push value associated with the system bot realm when only a single human realm existed on a server.
> zilencer: Fix can_push logging bug with system bot realms.

- web/src/portico/landing-page.js
This clarifies and corrects the tab-visibility and scrolling logic on the `/plans` page.
<details>
</details>
> portico: Correct tab/scroll logic for self-hosted fragments.

- web/styles/portico/pricing_plans.css
This takes some of the eyeballing, guesswork, and media-queries out of the sizing of the plans panes, and ensures that systems set to always display scrollbars only take them when they are required.
Responsiveness:
<details>
</details>
> plans: Precisely determine min- and max-widths.

- zerver/tests/test_push_notifications.py
- zilencer/views.py
Old RemotePushDeviceTokens were created without this attribute. But when processing a notification, if we have remote_realm, we can take the opportunity to to set this for all the registrations for this user.
> zilencer: Set .remote_realm for existing RemotePushDeviceToken.

- web/src/unread.ts
A followup to converting `unread` to typescript. If we don't re-fetch the message ids, we don't have to confirm they're not undefined.
> unread: Iterate over both topic_name and messages.

- .eslintrc.json
- web/src/components.ts
- web/src/compose_fade_users.ts
- web/src/compose_pm_pill.ts
- web/src/electron_bridge.d.ts
- web/src/global.d.ts
- web/src/list_cursor.ts
- web/src/list_widget.ts
- web/src/localstorage.ts
- web/src/markdown_config.ts
- web/src/messages_overlay_ui.ts
- web/src/poll_widget.ts
- web/src/upload_widget.ts
- web/src/url-template.d.ts
- web/src/vdom.ts
- web/tests/list_widget.test.js
For historical reasons, TypeScript ignores variance errors for method shorthand type declarations even in strict mode. Prefer the correctly checked style.
https://typescript-eslint.io/rules/method-signature-style
> eslint: Enable @typescript-eslint/method-signature-style

- web/e2e-tests/navigation.test.ts
- web/src/page_params.ts
- web/src/setup.ts
- web/src/zulip_test.js
This isn’t sent by the server; it’s a client-side global variable.
> page_params: Move page_load_time to zulip_test

- templates/zerver/accounts_home.html
- templates/zerver/login.html
- zerver/context_processors.py
This was used by a work-in-progress social login implementation in zulip-desktop that was reverted for security reasons and never released.
- https://github.com/zulip/zulip/pull/13782
- https://github.com/zulip/zulip-desktop/pull/863
We replaced it by a secure implementation with a maintainable API.
- https://github.com/zulip/zulip-desktop/pull/943
Tested in production on andersk.zulipdev.org.
> login: Remove external_authentication_methods from page_params

- corporate/tests/test_remote_billing.py
> test_remote_billing: Use unordered comparison for deactivation test

- web/src/page_params.ts
- web/src/stream_create_subscribers_data.ts
- web/src/user_group_create_members_data.ts
- web/src/user_groups.ts
`page_params.narrow` may be undefined, `page_params.server_sentry_dsn` may be `null` but not undefined, and `page_params.user_id` may be `0` (for spectators) but not undefined.
Cc @alexmv (#24382), @evykassirer (#28323).
> page_params: Fix types of narrow, server_sentry_dsn, user_id

- docs/tutorials/new-feature-tutorial.md
- web/src/hashchange.js
- web/src/message_fetch.js
- web/src/reload_setup.js
- web/src/server_events.js
- web/tests/message_edit.test.js
`events_queue_expired`, `initial_pointer`, `initial_offset`, `initial_narrow_pointer`, `initial_narrow_offset` are client-side global variables and are never sent by the server. `sent_by_me` has never existed. `mandatory_topics` was renamed.
> Remove fictional variables from `page_params`

- web/src/settings_profile_fields.js
- web/src/stream_create.js
- web/src/typing.js
- web/src/typing_events.js
- web/tests/settings_profile_fields.test.js
For spectators, most of `page_params` has not been initialized yet at module load time.
> Fix early reads of page_params

- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
- corporate/views/billing_page.py
- Make `self.write_to_audit_log` support a `background_update: bool=False` parameter that can be passed when code that might have an acting user happens to trigger a background update.
- Make `make_end_of_cycle_updates_if_needed` pass that parameter for its direct audit log writes.
- Audit code that `make_end_of_cycle_updates_if_needed` calls and make sure those write audit logs this way too.
- Pass the user in the `billing_page` code that had to avoid it as a workaround:
```
billing_session = RealmBillingSession(user=None, realm=user.realm)
```
> billing: Improve make_end_of_cycle_... interactions with audit logs.

- analytics/tests/test_support_views.py
- corporate/lib/support.py
- templates/analytics/remote_realm_details.html
- templates/analytics/remote_server_support.html
- zilencer/management/commands/populate_billing_realms.py
- zilencer/management/commands/populate_db.py
Updates to remote server support view:
- Removes the last updated field and replaces it with the date the remote server was created based on the audit log data.
- Adds a remote server UUID field to the remote server information.
- Changes the emoji that highlights when a remote realm or server has an active discount.
- Moves the 'has remote realms' field to be after the Zulip version information, and adds an extra break there to visually highlight that field as well as the following 'max monthly messages' field.
<details>
<summary>Example legacy server with upgrade scheduled and discount set</summary>
</details>
<details>
<summary>Example server with multiple realms</summary>
</details>
<details>
<summary>Example legacy sponsored server</summary> …
> support: Update remote server support view for UUID and date created.

- web/templates/settings/user_topics_settings.hbs
Fixes: https://chat.zulip.org/#narrow/stream/9-issues/topic/topic.20following.20not.20mentioned.20in.20settings.20text/near/1710888
I copied the pattern for how to make a link from `notification_settings.hbs`.
> settings: Update description text in Settings > Topics panel.

- web/src/compose_reply.js
- web/src/filter.ts
- web/src/hash_util.ts
- web/src/hashchange.js
- web/src/message_events.js
- web/src/message_feed_top_notices.js
- web/src/message_fetch.js
- web/src/narrow.js
- web/src/narrow_banner.js
- web/src/narrow_history.ts
- web/src/narrow_state.ts
- web/src/search.js
- web/src/search_suggestion.js
- web/src/typing_events.js
- web/src/unread_ops.js
- web/tests/filter.test.js
- web/tests/hash_util.test.js
- web/tests/hashchange.test.js
- web/tests/narrow.test.js
- web/tests/narrow_state.test.js
- web/tests/search.test.js
- web/tests/search_suggestion.test.js
Operand is a confusing name because this
data structure has an attribute *called*
operand. This commit renames references to
this structure to "term", short for "search
term".
This PR is a followup from this comment https://github.com/zulip/zulip/pull/28229#discussion_r1427278515 and a conversation with Anders.
This seems like a brittle change, so I'm putting it in its own PR. It seems easy to forget a rename and have it not caught by tests or the linter. Curious if there are ways that would be good for testing this.
> filter: Use terms instead of operands.

- templates/analytics/remote_realm_details.html
- zilencer/management/commands/populate_billing_realms.py
If a remote realm on a remote server is locally deactivated, we show a header with an emoji to alert support admin. Also updates `populate_billing_realms` to not locally deactivate test remote realms when generating them.
<details>
<summary>Example of remote server support with locally deactivated remote realm</summary>
</details>
---
<details>
</details>
> support: Display if remote realm is locally deactivated.

- docs/production/authentication-methods.md
That specific piece of the instructions makes it sound like /auth/ is surely supposed to be there in the URL. But newer versions of Keycloak don't have it - so mention that explicitly, not to create a wrong expectation.
https://chat.zulip.org/#narrow/stream/9-issues/topic/SAML.20documentation
> docs: Add tiny note about Keycloak URL format in SAML doc.

- zerver/openapi/zulip.yaml
- zerver/tests/test_user_topics.py
- zerver/views/user_topics.py
For endpoints:
* [`/users/me/subscriptions/muted_topics` ](https://zulip.com/api/mute-topic)
* [`/user_topics`](https://zulip.com/api/update-user-topic)
`topic` length was not validated before DB operations which resulted in an exception.
This commit adds a validation for the topic name length <= 'max_topic_length' characters.
Fixes #27796.
<details><summary>Docs</summary>
</img>
</details> 
<details>
</details>
> user_topics: Validate 'topic' parameter length <= max_topic_length. 

- web/styles/portico/footer.css
This corrects an undesired 5px open space beneath the portico footer, while improving the vertical alignment of legal footer elements on wider screens by putting flexbox in full control of vertical alignment. (Prior use of margin on individual flex items in the legal area were intended to keep the `border-bottom` borders adjacent the link text, but that was a poor pushback against flexbox's default stretch behavior.)
| --- | --- |
| ![portico-footer-narrow-before](https://github.com/zulip/zulip/assets/170719/c969a40c-3278-4872-980b-afe3b372c5a5) | ![portico-footer-narrow-after](https://github.com/zulip/zulip/assets/170719/eeaf72c6-4357-4fd3-8d6e-895b62226b1a) |
| ![portico-footer-wide-before](https://github.com/zulip/zulip/assets/1707 …
> portico: Correct spacing at footer bottom.

- docs/development/setup-recommended.md
This PR adds a warning targeted to macOS users who may experience provisioning failures.
[CZO discussion](https://chat.zulip.org/#narrow/stream/21-provision-help/topic/provision.20error.20ERR_PNPM_LINKING_FAILED/near/1697894)
Fixes: #28370
> docs: Add warning about failed provisioning on macOS.

- zerver/lib/send_email.py
- zerver/management/commands/send_custom_email.py
The set of `enable_marketing_emails=True` are those that have opted into getting marketing newsletter emails -- but we previously limited further to only those users active in the last month.
Broaden that to "opted in, and either recently active or an owner or an admin," with the goal of providing information to folks who may have tried out Zulip in the past.
---
If we `.distinct("delivery_email")` then we must also `.order_by("delivery_email")`; adc987dc43f6 added the `.order_by`
call, which broke the newsletter codepath, since it did not contain the `delivery_email` in the ordering fields.
Add a flag to distinct on emails in `send_custom_email`.
---
> send_custom_email: Various newsletter cleanups

- web/styles/rendered_markdown.css
- web/styles/zulip.css
Closes #28407 
Currently it looks like this
Before it was like this
<details>
</details>
> alert-word: Background color of alert word fixed closes #28407 

- docs/production/mobile-push-notifications.md
- zerver/management/commands/register_server.py
Doing so immediately regenerates the UUID and key, since we do not allow reactivating deactivated servers.
<details><summary>Command-line example</summary>
```
zulip@alexmv-prod:~/deployments/current$ ./manage.py register_server
This command registers your server for the Mobile Push Notifications Service.
Doing so will share basic metadata with the service's maintainers:
* This server's configured hostname: alexmv-prod.zulipdev.org
* This server's configured contact email address: alexmv@zulip.com
* Metadata about each organization hosted by the server; see:
<https://zulip.readthedocs.io/en/latest/production/mobile-push-notifications.html#uploading-basic-metadata>
Use of this service is governed by the Zulip Terms of Service:
<https://zulip.com/policies/terms>
Do you want to agree to the …
```
> management: Provide a way to deactivate the push registration.

- zerver/lib/markdown/__init__.py
- zerver/tests/fixtures/markdown_test_cases.json
`<time:1234567890123>` causes a "signed integer is greater than maximum" exception from dateutil.parser; datetime also cannot handle it ("year 41091 is out of range") but that is a ValueError which is already caught.
Catch the OverflowError thrown by dateutil.
<details>
</details>
> markdown: Prevent OverflowError with large time integers.

- corporate/tests/test_remote_billing.py
- corporate/tests/test_stripe.py
- corporate/views/remote_billing_page.py
- zilencer/views.py
https://chat.zulip.org/#narrow/stream/273-kandra-billing/topic/realm_locally_deleted/near/1713870
Earlier, the `handle_customer_migration_from_server_to_realms` function was called during the send analytics step.
It resulted in an error for customers having multiple Zulip servers, one for testing and the others for not-testing, sharing a push bouncer registration.
The migration step when run in a test instance caused customers to have their legacy plan migrated to a test realm, resulting in them losing their legacy plan.
This PR moves the migration step to run during plan management login step. This reduces the chances of losing legacy
plan as we expect them to only verify that 8.0 upgrade works and not bother trying to login to plan management from their test instance.
<details> …
> migrate_customers: Migrate customer from server to realms during login.

- zerver/tests/test_home.py
- zerver/views/push_notifications.py
https://chat.zulip.org/#narrow/stream/49-development-help/topic/Help.20with.20CI.20tests.20Error.20Code
`os.path.getmtime` needs to be mock.patched or otherwise the success of
the test depends on the filesystem state and breaks if version.py hasn't
been modified in a while.
> tests: Fix how test_is_outdated_server works.

- corporate/lib/stripe.py
- zerver/tests/test_push_notifications.py
We return expected_end_timestamp as "None" for the plans to be downgraded if number of users is not more than MAX_USERS_WITHOUT_PLAN.
<details>
</details>
> push_notification: Check users count for plans to be downgraded.

- api_docs/include/rest-endpoints.md
- zerver/openapi/test_curl_examples.py
- zerver/openapi/zulip.yaml
As discussed in [#api documentation](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/test.20notification.20endpoint/near/1690326) on CZO, creates the ability to exclude testing the generated curl examples for specific documented endpoints. Currently, this is limited to the endpoint for testing push notifications on mobile devices.
Also, updates some of the descriptive text for said test notifications endpoint; see screenshot below. And, adds that endpoint to the sidebar list of documented endpoints, in the specialty endpoints section.
@chrisbobbe - Could you look over the API documentation text changes? Also, I wonder if you have thoughts on the final sentence in the `token` parameter description. There's something about the final "this client" that sounds off to me, but …
> test-api: Exclude generated curl examples for specific documented endpoints.

- web/src/drafts.js
- web/src/drafts_overlay_ui.js
- web/src/scheduled_messages_ui.js
As part of the process of moving from stream names to ids, we now only pass the stream id in compose args to `compose_actions.start()`.
For when we still need the stream name, and have access to the compose args, we compute it from the id exactly where needed, to localise the instances of stream names.
Fixes issue mentioned: [here
](https://github.com/zulip/zulip/pull/27695#discussion_r1393484614)
<details>
</details>
> refactor: Pass only stream id, not name, to `compose_actions.start()`.

- help/include/import-how-users-will-log-in.md
- zerver/management/commands/send_password_reset_email.py
Emailing the password reset email to users who have already logged in is not as useful.
<details>
</details>
> send_password_reset_email: Add a flag to only email users who need it.

- web/templates/settings/admin_profile_field_list.hbs
This PR fixes the issue #27816. 
Explanation:
In the "Organization settings" under the tab "Custom profile fields" the edit and delete buttons have a hover-text displaying "edit" respectivley "delete". Before, it looked like the GIF "old version" below but this PR has updated the design to use the new tippy design, shown in GIF "New version dark mode" and "New version lilght theme" where LONG_HOVER_DELAY is used.
Fixes: #27816 
**Old version - before this PR**
**New version dark theme**
**New version lilght theme**
<details>
Individual commits are ready for review (see [commit discipline (https://zulip.readthedocs.io/en/latest/contributing/commit-disciplin …
> Organization settings: Fix tippy design and hover delay for edit/delete in custom profile fields.

- templates/zerver/policies_minimal/privacy.md
- templates/zerver/policies_minimal/terms.md
- zerver/tests/test_docs.py
- zerver/views/documentation.py
> documentation: Support having no sidebar for policies docs.

- web/styles/dark_theme.css
Fixes: #26480 
These are screenshots and screen captures after i have made the changes:-
https://github.com/zulip/zulip/assets/119888263/833d835e-9fcd-438c-9057-d1523c41ce9c
<details>
</details>
I had adjusted the background hsl color value which was causing the problem
it would be greate if someone reviews the PR and please tell me weather any changes needed!!
Thank You : )
> settings: Fix color leak during linkifier row drag in settings

- puppet/zulip/templates/logrotate/zulip.template.erb
149bea83090951db5daac5d9c49396cae87fc561 added a separate config file for smokescreen (which is necessary because it can be installed separately) but failed ot notice that `zulip.template.erb` already had a config line for it.  This leads to failures starting the logrotate service:
```
logrotate[4158688]: error: zulip:1 duplicate log entry for /var/log/zulip/smokescreen.log
logrotate[4158688]: error: found error in file zulip, skipping
```
Remove the duplicate line.
> logrotate: smokescreen has its own config file.

- templates/corporate/plans.html
- web/styles/portico/hello.css
- web/styles/portico/pricing_plans.css
This applies the same structures and now more-generalized CSS from `/hello` to the `/plans` page, ensuring the correct gradient display while also masking any color shifts from top and bottom overscrolling.
| Light mode, before | Light mode, after |
| --- | --- |
| ![plans-gradient-light-before](https://github.com/zulip/zulip/assets/170719/ddb33a67-3f60-4860-8352-dcf1d4cb2192) | ![plans-gradient-light-after](https://github.com/zulip/zulip/assets/170719/850dd2ba-b568-48cb-8207-5f69c2ec1cb0) |
| Dark mode, before | Dark mode, after |
| --- | --- |
| ![plans-gradient-dark-before](https://github.com/zulip/zulip/assets/170719/4a8c7464-4493-42aa-8c21-0335c29e717e) | ![plans-gradient-dark-after](https://github.com/zulip/zulip/assets/170719/f3c38d8a-d7d7-4317-9 …
> portico: Extend proper background gradients to /plans.

- web/styles/portico/comparison_table.css
This PR establishes the correct, expected link styles on the comparison tables. It does so by removing `!important` declarations that were unnecessary and interfered with expected link, :hover, and :active styles.
It also uses a previously declared but unused CSS variable for specifying the text color for active-state links.
_These provide context of link styles across the whole page; there were no expected changes in any of the non-comparison-table areas, but this serves to confirm._
| --- | --- |
| ![comparison-links-before](https://github.com/zulip/zulip/assets/170719/a595bfd6-d0fd-44e0-ba64-cf5fbe4ea773) | ![comparison-links-after](https://github.com/zulip/zulip/assets/170719/d3b165ab-4963-4b2b-a3ab-6bec88be169f) |
_Comparison of …
> plans: Bring comparison link-styles in line with the mocked design.

- web/src/composebox_typeahead.js
- web/tests/composebox_typeahead.test.js
Updated typeahead text for slash commands 
Fixes: #27391
Before:
After: 
<details>
</details>
> Fixes- #27391 : Updated typeaheads

- web/src/compose_validate.js
- web/tests/compose_validate.test.js
Earlier, a new banner would be showed for each mention of the same private stream in the compose box. This commit fixes that by checking if the private stream warning banners already shown include the private stream just mentioned, and if so, not showing a new banner.
This implementation is in line with the one for warnings for mentions of users not subscribed to the current stream.
Fixes: #26914.
<details> …
> compose: Fix duplicate warning banners for the same private stream.

- puppet/zulip_ops/manifests/ksplice_uptrack.pp
This reverts a759d26a327cd4337d68eaa1d45d6a69edc9161c; apparently the package has switched back.
<details>
</details>
> puppet: Adjust uptrack permissions and ownership to match package's.

- zerver/models/messages.py
By default, `SELECT FOR UPDATE` will also lock any rows which are `JOIN`ed into the selected rows; in the case of UserMessage rows, this can mean arbitrary Message rows.
Since the messages themselves are not being changed, it is not necessary to lock them -- and doing so may lead to deadlocks, in the case that the UserMessage row is locked for update before the Message, and some other request has already taken a read lock on the Message and is blocked on the UserMessage write lock.
Change `select_for_update_query` to explicitly only lock UserMessage.
<details> …
> messages: Only lock UserMessage rows, not other joined tables.

- web/styles/portico/pricing_plans.css
At @terpimost's suggestion, this PR drops the font-weight on the unlimited push placeholder for legacy self-hosted billing views.
| --- | --- |
| <img width="650" alt="push-notifications-placeholder-before" src="https://github.com/zulip/zulip/assets/170719/66b22f5d-fee2-4d49-99c0-66a1974fdf0d"> | <img width="650" alt="push-notifications-placeholder-after" src="https://github.com/zulip/zulip/assets/170719/a4ebf5d4-d436-4b54-a3ef-db038b984a6d"> |
> plans: Reduce font-weight on push placeholder button.

- web/styles/portico/comparison_table.css
At @terpimost's suggestion, this PR reduces the font-size of text comparison elements, such as _Billed hourly_, for a better presentation of the comparison tables for both Cloud and Self-hosted plans. As the screenshots illustrate and the code confirms, this has no effect on the size or positioning of icons.
A small prep commit consolidates `position: relative` on the same selectors that benefit from a uniform `font-size` adjustment.
| Cloud comparison, before | Cloud comparison, after |
| --- | --- |
| <img width="835" alt="cloud-comparison-before" src="https://github.com/zulip/zulip/assets/170719/3fb32ca4-eb87-408e-b03d-539b0e74c803"> | <img width="835" alt="cloud-comparison-after" src="https://github.com/zulip/zulip/assets/170719/3e412579-eccb-4b44-8 …
> plans: Reduce font-size of text comparison elements.

- puppet/zulip_ops/manifests/profile/nagios.pp
fcf096c52ed6 removed the callsite which would have notified this contact.  It's also not clear where
`/usr/local/share/zulip/integrations/nagios/zulip_nagios.cfg` was meant to be provisioned from.
<details>
</details>
> nagios: Remove provisioning of zulip contact alias.

- templates/zerver/portico-header.html
- web/styles/portico/portico.css
Fixes #27477
Dropped the Find accounts link for shorter screem in the header of help-center/api-center/policy-page as discussed in the [here](https://chat.zulip.org/#narrow/stream/101-design/topic/Documentation.20website.20in.20mobile.20browser)
**For wider screen:**
**For smaller screen:**
</details>
> portico-header: Dropped find accounts link for smaller windows.

- templates/corporate/plans.html
- templates/corporate/pricing_model.html
This PR adds links from the Cloud and Self-hosted plans to URL fragments on their respective sponsorship and discounts areas.
| Cloud linked copy | Self-hosted linked copy |
| --- | --- |
| ![cloud-copy](https://github.com/zulip/zulip/assets/170719/085049c0-b030-4269-9118-ea5a7d7df307) | ![self-hosted-copy](https://github.com/zulip/zulip/assets/170719/74a592ec-8dda-4f0c-9d4b-f589d905082f) |
> plans: Link to cloud, self-hosted sponsorship areas.

- corporate/lib/stripe.py
- templates/analytics/realm_details.html
- templates/analytics/remote_realm_details.html
- templates/analytics/remote_server_support.html
- templates/analytics/sponsorship_forms_support.html
Updates the HTML input field to have a min of 0, max of 99.99 and allow increments of 0.01.
Also, use format_discount_percentage for displaying the customer default discount in the support form.
All screenshots are from the /activity page, but would be the same for the discount form on the activity/remote page.
<details>
<summary>Success setting a discount with two decimal places</summary>
</details>
<details>
<summary>HTML validation not allowing three decimals to be set</summary>
</details>
<details>
<summary>HTML validation not allowing negative value to be set</summary>
</details>
<details>
<summary>HTML validation not allowing values above 99.99</summary>
</details>
---
<details> …
> support: Update validation for adding or updating a discount.

- docs/production/mobile-push-notifications.md
- help/include/legacy-log-in.md
We redirect from `/serverlogin` to `/serverlogin/`, so save a 301.
<details>
</details>
> docs: Fix selfhoster URL to be the canonical one.

- web/styles/message_row.css
- web/styles/zulip.css
This PR does three things:
1) It moves various `message_edit` selectors and styles from `zulip.css` into `message_row.css`
2) It removes some dead CSS related to message-edit structures that no appear to exist in the codebase.
3) It strengthens the layout of the message edit buttons with flexbox, especially the load spinner on the Save button. The kinds of fiddly tweaks in #28134 should no longer be necessary, as flexbox is responsible for all alignment matters, instead of positioning and brittle pixel-offset tweaks.
_As this is a code-quality PR, there should be no visual changes._
| --- | --- |
| <img width="470" alt="save-spinner-before" src="https://github.com/zulip/zulip/assets/170719/806881a2-61dd-4d00-8c10-cdbd4d0fd135"> | …
> message_edit: Lay out edit buttons with flexbox

- zerver/management/commands/process_queue.py
- zerver/worker/queue_processors.py
queue_processors: Defer initial email connection creation.
We previously created the connection to the outgoing email server when the EmailSendingWorker was first created.  Since creating the connection can fail (e.g. because of firewalls or typos in the hostname), this can cause the `QueueProcessingWorker` creation to raise an exception.  In multi-threaded mode, exceptions in the worker threads which are _not_ during the handling of a specific event percolate out to `log_and_exit_if_exception` and trigger the termination of the entire process -- stopping all worker threads from making forward progress.
Contain the blast radius of misconfigured email servers by deferring the opening of the connection until it is first needed.  This will not cause any overall performance change, since it …
> Ensure email server failures do not stop all workers from making progress

- corporate/tests/test_remote_billing.py
- corporate/views/remote_billing_page.py
The bug was that a user could do the first part of the flow twice, receiving two confirmation links, before finishing signup. Then they could use the first link, followed by the second, which would case an IntegrityError due to trying to create the RemoteRealmBillingUser for the second time.
When the second link gets clicked, we should just transparently redirect the user further into the flow so that they can proceed.
> remote_billing: Handle two confirmation links for same user correctly.

- corporate/tests/test_remote_billing.py
- corporate/views/remote_billing_page.py
- zilencer/views.py
This was a bug from 4715a058b0ace97e92f360ac1cbf169648e3441d where this was just incorrectly called. get_realms_info_for_push_bouncer() is a function meant to be called on a self-hosted server - and this handle_... call happens on the bouncer. Therefore this returns all zulipchat realms in production.
With the way, handle_... is being called right now, there's no reason for it to have an argument for passing a list of realms. It should just fetch the relevant RemoteRealm entries  by itself, given the server arg.
> remote_billing: Fix handle_customer_migration_from_server_to_realms.

- web/src/compose_ui.js
- web/tests/compose_ui.test.js
compose: Revamp and improve test suite for compose formatting buttons.
Earlier, the tests for compose formatting were verbose, hard to read as well as extend, and overly granular, without even having the ability to test the final text selection or the cursor position.
Now, new test helpers, `init_textarea_state` and `get_textarea_state`, have been added, enabling the tests to be more concise and readable, while also being more powerful. A representative string alone now describes the textarea state (the text and the selection / cursor), making each test case as easy as defining the initial state as a string and comparing the expected state post formatting with another string.
These new tests helped surface a couple bugs which have been fixed in preceding commits.
compose: Fix bug where …
> compose: Revamp and improve test suite for compose formatting buttons.

- web/src/copy_and_paste.js
- web/tests/copy_and_paste.test.js
When pasting any code without any newlines, from a code block, it will now be pasted as inline code, instead of a code block.
Fixes: [Issue brought up here on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20Pasting.20single-line.20code.20should.20use.20inline.20code)
<details>
</details>
> turndown: Convert single line code blocks to inline code markdown.

- zerver/decorator.py
- zerver/lib/test_helpers.py
- zerver/tests/test_auth_backends.py
- zerver/tests/test_signup.py
- zerver/views/auth.py
- zerver/views/registration.py
- zproject/backends.py
- zproject/default_settings.py
Adds a decorator to `authenticate` functions to allow setting up arbitrary code to wrap them in. Here's a simplistic example that I can add in `/etc/zulip/settings.py` for restricting IP login for a user to a specific IP (when logging in via EmailAuthBackend specifically, for demonstration's sake):
```
def custom_auth_wrapper(
auth_func, *args, **kwargs
):
from zerver.lib.exceptions import JsonableError
backend = args[0]
backend_name = backend.name
request = args[1]
ip_address = request.META["REMOTE_ADDR"]
backend.logger.info("%s backend. ip is %s", backend_name, ip_address)
user_profile = auth_func(*args, **kwargs)
if user_profile is not None and user_profile.delivery_email == "protecteduser@example.com:
if backend_name == "email" and ip_address != "185.195.233.144":
raise …
```
> auth: Add a configurable wrapper around authenticate calls.

- web/styles/zulip.css
Fixes: #27825 
This PR fixes the issue of mention typeaheads spilling out of the box by limiting the max-width in accordance with the screen size.
Initially - 
Finally - 
<details>
</details>
> typeaheads: Fix mention typeaheads spill width.

- web/e2e-tests/settings.test.ts
Finished renaming display_settings_section to preferences_section
This helps fixes part of issue https://github.com/zulip/zulip/issues/26874.
In this pull request
Renamed display_settings_section to preferences_section in the web/e2e-tests/setting.test.ts file.
Changed Files:
web/e2e-tests/setting.test.ts
<details>
</details>
> e2e-tests: Rename display_settings_section to preferences_section.

- web/e2e-tests/drafts.test.ts
There were two typeahead displayed while we were testing create_private_message_draft. One was topic typeahead from previous create_stream_message_draft test and the other was cordelia DM typeahead. So, when clicking on the typeahead, we clicked the topic typeahead when we really wanted to select the cordelia typeahead. This resulted in drafts test failing.
> drafts: Fix flaky drafts tests.

- zerver/tests/test_signup.py
- zerver/views/development/email_log.py
- zerver/views/registration.py
Fixes:  Fixes part of  #3128 
https://github.com/zulip/zulip/assets/78016781/c6146640-2a24-4440-8dd1-900d9391da3b
<details>
</details>
> find_account: Remove emails as URL parameters.

- web/styles/portico/billing.css
Fixes #28428
<details>
</details>
> billing: Change background color of reactivate subscription.

- web/templates/settings/admin_user_list.hbs
Added handlebars if-else conditions to display
'User is deactivated' tooltip for deactivated users and 'Bot is deactivated' tooltip for deactivated bots.
Fixes:#28593.
<h3>Bots table and Deactivated users table before changes:</h3>
<h3>Bots table and Deactivated users table After changes:</h3>
> hbs:  Use correct tooltips for deactivated bots.

- web/src/message_notifications.js
Follows the general pattern of always using a stream marker.
> notifications: Add # to stream name in desktop notifications.

- corporate/tests/test_stripe.py
- templates/zerver/emails/sponsorship_request.subject.txt
This makes the subject nicer for replying to these emails.
> emails: Remove organization type from sponsorship request emails.

- corporate/tests/test_stripe.py
- help/self-hosted-billing.md
- templates/corporate/plans.html
It was not clear that the button could be used for discounts.
Plans page:
> billing: Rename button to apply for sponsorship or discount.

- corporate/tests/test_remote_billing.py
- corporate/views/remote_billing_page.py
- templates/corporate/remote_server_rate_limit_exceeded.html
- zproject/default_settings.py
- zproject/test_extra_settings.py
These should be rate-limited by both IP using our regular sends_email_by_ip bucket as well as by server, using a new bucket dedicated to this.
> remote_billing: Add rate-limiting for confirmation email sending.

- web/styles/settings.css
- web/templates/settings/display_settings.hbs
Finished renaming display-settings-form to preferences-settings-form
This helps fixes part of issue https://github.com/zulip/zulip/issues/26874.
In this pull request
Renamed display-settings-form to preferences-settings-form.
Changed Files:
web/styles/settings.css
web/templates/settings/display_settings.hbs
<details>
</details>
> settings: Rename display-settings-form to preferences-settings-form.

- web/src/desktop_integration.js
Closes the gear menu in the desktop app when clicking "Plan management"
[Screencast from 2024-01-18 22-27-33.webm](https://github.com/zulip/zulip/assets/45007152/3582f350-848f-40ac-944e-0f1f89ccd85a)
Though I also noticed that at least for me, in the desktop application the behavior of not closing the gear menu happens when I click on "Integrations", "API documentation" and such, not sure why.
> desktop_app: Close popover when clicking on "Plan management".

- templates/zerver/find_account.html
- tools/lib/capitalization.py
- zerver/views/registration.py
Fixes:  Fixes part of  #3128 
<details>
</details>
> find_account: Add button to send another email.

- web/src/narrow.js
- web/tests/narrow_activate.test.js
This will prevent any message we want to select after narrowing from being offscreen entirely or partially.
Steps to reproduce the bug:
* `./manage.py populate_db -n 3000 --max-topics=2`
* Narrow to a stream and scroll high up.
* Align two recipient bars together with nothing between them.
* Click on the first recipient bar after keeping the selected message on the second recipient bar.
* You will see that the selected message is not in view.
Previous PR #27632
before:
https://github.com/zulip/zulip/assets/25124304/f657a97e-a6bd-4875-93af-c2becb484767
after:
https://github.com/zulip/zulip/assets/25124304/bca2a36b-a46f-4c9c-9d77-ff1fa9409894
> narrow: Fix message row partially visible on narrow.

- web/styles/user_status.css
- web/templates/status_emoji_selector.hbs
fix alignment of select-emoji in set-status-modal
and replace old fa-smile icon with custom zulip-smile-icon
| Before | Now |
| --- | --- |
| ![Screenshot from 2023-12-19 18-58-26](https://github.com/zulip/zulip/assets/90370535/514a934e-69cd-4b04-aca6-68f1415fcf58)| ![Screenshot from 2024-01-19 22-13-47](https://github.com/zulip/zulip/assets/90370535/f9eefa7d-8943-488a-98ab-ef2d6a1f5e14)|
| --- | --- |
| ![2](https://github.com/zulip/zulip/assets/90370535/096a10a8-bcf9-4637-ace6-859cc2c5ac4f) | ![Screenshot from 2024-01-19 23-08-54](https://github.com/zulip/zulip/assets/90370535/3d6ce735-70b4-4b13-b221-223780c2a064)|
| ![1](https://github.com/zulip/zulip/assets/90370535/38257055-6518-4704-9ce6-0f8c49478728) | …
> Fix alignment of select-emoji of set-status-modal

- analytics/tests/test_activity_views.py
- analytics/views/remote_activity.py
- corporate/lib/analytics.py
- templates/analytics/remote_activity_key.html
- zilencer/models.py
Updates the remote activity page for:
- Removes the "analytics users" column (commit 1)
- Adds a column for remote realms (ID, name, organization type) and a row is displayed in the chart for each remote realm on a remote server.
- If the server doesn't have remote realms, then it still has a row displayed with any active plan, revenue and user information.
- Updates the remote activity key for these changes and to more clearly explain some of the existing chart data.
**Notes**:
- We were previously querying the database for each remote server to get the user counts. And adding the remote realms to the chart added two additional queries (one to get the remote realm object and then one to get the user counts)
- Added functions to do a server and realm query for the audit logs to tally the …
> remote-activity: Add rows to general chart for remote realms.

- web/src/settings.js
- web/src/settings_config.ts
Finished renaming display_settings_labels to preferences_settings_labels
This helps fixes part of issue #26874.
In this pull request
Renamed display_settings_labels to preferences_settings_labels.
Changed Files:
web/src/settings.js
web/src/settings_config.ts
<details>
</details>
> settings: Rename display_settings_labels to preferences_settings_labels.

- tools/test-js-with-node
- web/src/scheduled_messages.js
- web/src/scheduled_messages.ts
- web/src/scheduled_messages_feed_ui.js
- web/src/scheduled_messages_overlay_ui.js
- web/src/scheduled_messages_ui.js
The first commit converts `scheduled_messages_data` from an `object` to a `Map`. The second commit converts `scheduled_message` to TypeScript.
[message.webm](https://github.com/zulip/zulip/assets/123243429/f77f90e8-381c-4f07-97a0-68819f7d7b28)
> scheduled_messages: Convert module to TypeScript.

- web/templates/personal_menu.hbs
Use `tabindex` instead of `href` to set focus on `a` tag.
Ideally, we should use `button` for these elements but since we want to keep the pattern for these dropdowns same where some `a` elements do have a valid `href`.
> personal_menu: Fix clicking on `Set status` not working.

- help/custom-profile-fields.md
- web/e2e-tests/custom-profile.test.ts
- zerver/migrations/0417_alter_customprofilefield_field_type.py
- zerver/models/custom_profile_fields.py
This changes the name of four custom profile field types and reorders them in alphabetical order. It also updates the documentation to reflect the new names.
Fixes: #28511 
Previous menu:
Updated menu:
<details>
</details>
> settings: Rename and reorder custom profile fields

- analytics/tests/test_support_views.py
- corporate/lib/support.py
- templates/analytics/current_plan_details.html
Instead of showing the next invoice date for the plan, show the date for the next billing cycle start (e.g. the next plan renewal charge date), except for plans currently on a free trial.
For plans on a free trial, the next plan renewal date will be when the free trial ends, which is stored as the next invoice date on the plan.
These changes will apply to both Cloud and remote support views.
<details>
<summary>Basic remote realm</summary>
</details>
<details>
<summary>Free trial remote realm</summary>
**Note that the free trial end date is set to 2 months in populate_billing_realms for the dev environment.**
</details>
---
<details> …
> support: Show date for start of next billing cycle for current plan.

- zerver/actions/user_activity.py
- zerver/tests/test_import_export.py
- zerver/tests/test_queue_worker.py
- zerver/worker/queue_processors.py
This leads to significant speedups.  In a test, with 100 random unique event classes, the old code processed a batch of 100 rows (on average 66-ish unique in the batch) in 0.45 seconds.  Doing this in a single query processes the same batch in 0.0076 seconds.
<details>
</details>
> queue_processors: Process user_activity in one query.

- zerver/data_import/slack.py
- zerver/tests/test_slack_importer.py
1e5c49ad825d added support for shared channels -- but some users may only currently exist in DMs or MPIMs, and not in channel membership.
Walk the list of MPIM subscriptions and messages, as well as DM users, and add any such users to the set of mirror dummy users.
<details>
</details>
> import: Support shared users in huddles/DMs.

- corporate/views/remote_billing_page.py
This was an oversight in the original implementation.
> remote_billing: Pass language argument to send_email calls.

- zerver/tests/test_queue_worker.py
These values have to round-trip through the database, and microsecond precision is not guaranteed to do so.
Fixes: 
<details>
</details>
> test_queue_worker: Use integer epoch values.

- web/styles/portico/activity.css
This will be applied to both the overall installation activity chart as well as the associated remote, client, realm and user views.
```console
$ git grep summary-table
templates/analytics/realm_summary_table.html:<table class="table summary-table sortable table-striped table-bordered">
web/styles/portico/activity.css:.summary-table,
$ git grep analytics-table
templates/analytics/ad_hoc_query.html:<table class="table sortable table-striped table-bordered analytics-table">
web/styles/portico/activity.css:.analytics-table {
$ git grep ad_hoc_query
analytics/views/activity_common.py:        "analytics/ad_hoc_query.html",
$ git grep make_table analytics/
analytics/views/activity_common.py:def make_table(
analytics/views/installation_activity.py:    make_table, …
```
> activity-css: Make activity charts header row sticky.

- zerver/openapi/zulip.yaml
Following discussion:
https://chat.zulip.org/#narrow/stream/378-api-design/topic/.60realm_authentication_methods.60/near/1723399
-----
Would it be good to add the same text to `authentication_methods` in the [`realm/update_dict` event doc](https://zulip.com/api/get-events#realm-update_dict)? I guess we probably assume that people will read both the event doc and the corresponding field in the `/register` doc; I always check both. So maybe not necessary.
> api-docs: Clarify realm_authentication_methods in /register response

- help/keyboard-shortcuts.md
- web/src/common.ts
- web/src/compose.js
- web/src/compose_setup.js
- web/src/hotkey.js
- web/templates/keyboard_shortcuts.hbs
- web/tests/common.test.js
- web/tests/hotkey.test.js
On Mac, it's Option+P.
Fixes: #18471.
refactor: Extract new function `show_preview_area` for the compose box.
The code responsible for switching from edit mode to preview mode from `compose_setup.js` is now extracted into a new function in `compose.js`, to facilitate reuse.
This is a prep commit for introducing a hotkey to toggle between edit and preview mode for the compose box.
Revision of #26841 
<details> …
> hotkey: Introduce hotkey Alt+P to toggle preview for compose box.

- puppet/zulip_ops/manifests/profile/grafana.pp
Grafana 10.2.1 and up package their tarball with a `grafana-v10.2.1` and not `grafana-10.2.1` as previously.
<details>
</details>
> puppet: Fix grafana tarball path.

- web/styles/compose.css
- web/styles/zulip.css
This PR   fixes the issue “Unsteady height of  message compose  bars occurring while  scrolling down Through  the  stream names  having    language  other than English  like  Korean or Chinese in recent messages  view”.
Fixes:#27837.
I have   updated the PR  implementing  css property <b> line-height : var(--line-height-compose-buttons) </b> to the compose message box buttons  with value set as  <b>20px</b> in zulip.css to <b>compose_message</b> ,   <b>start_new_conversation</b>,  <b>new_direct_message</b>,    and modified the <b>line-height </b>  property of  <b>new_direct_message_mobile_button</b> to make  their  heights  steady  while  the  text within them is changed  to non-latin  characters. Thus  setting the  exact pixel-based  line-height solves the issue.
<h3>Before Changes:</h3> …
> css: Making the height of compose bars steady.

- analytics/tests/test_activity_views.py
- corporate/lib/analytics.py
- corporate/lib/stripe.py
- corporate/lib/support.py
**Notes**:
- Adds a test for the remote activity view with a more robust data set for customer plans and audit log data.
- Updates the query for customer plans to prefetch the related license ledger entry to calculate the estimated annual recurring revenue.
- Updates the query for the remote realm audit logs to select the related remote_realm to have the remote realm ID for the dict key.
- The query count in the new test goes from 27 to 11 with the updated queries.
<details>
<summary>console log 11 queries</summary>
```console
ITEMS:
#1
sql: SELECT "zerver_realm"."id", "zerver_realm"."name", "zerver_realm"."description", "zerver_realm"."string_id", "zerver_realm"."uuid", "zerver_realm"."uuid_owner_secret", "zerver_realm"."push_notifications_enabled", …
```
> remote-activity: Reduce number of database queries for view.

- puppet/zulip_ops/files/statuspage-pusher
- puppet/zulip_ops/manifests/statuspage.pp
This was changed midway through the implementation, from reading it from `zulip-secrets.conf`, and a couple locations still reference the secrets path.
<details>
</details>
> puppet: statuspage-pusher uses zulip.conf for page_id.

- web/src/emoji_picker.js
- web/styles/dark_theme.css
- web/styles/reactions.css
- web/templates/popovers/emoji/emoji_popover.hbs
- web/templates/popovers/emoji/emoji_popover_emoji.hbs
Due to a logical bug in the `process_enter_while_filtering` function, the `toggle_reaction` was being called when pressing enter while filtering the emojis in the status emoji picker.
This PR fixes the above bug, while also adding some cleanups to the `emoji_picker.js` by combining multiple click handlers and aggregating all the logic related to an emoji being selected into a common function.
Fixes: #28464
**Steps to reproduce**: Go to "Set  Modal > Open emoji picker > Enter random words to filter > Press Enter
[before-status-emoji-picker.webm](https://github.com/zulip/zulip/assets/82862779/bb35aae7-0ab7-4daf-9ab5-8f4e4a760d57)
[after-status-emoji-picker.webm](https://github.com/zulip/zulip/assets/82862779/d83652c0-760b-4511-8759-28b691a9b46a) …
> emoji_picker: Fix status emoji picker inconsistencies.

- web/styles/settings.css
- web/templates/settings/data_exports_admin.hbs
This  PR  removes the extraneous background color applied only to  <b>"start export of  public data " </b>Button.
In this PR  I have removed the <b> div</b>  containing the <b>  grey-box </b>   which was responsible for the extraneous background around the button. As a part this  I have also removed  the <b> add-new-export-box </b>  class from settings.css
Fixes: #28625.
<br>
<br>
<h3>Screen Shots  Before Changes:</h3>
<h3>Screen Shots After Changes:</h3>
> templates: Remove the extraneous background color.

- analytics/views/activity_common.py
- analytics/views/installation_activity.py
- analytics/views/realm_activity.py
- analytics/views/remote_activity.py
- corporate/lib/analytics.py
- templates/analytics/ad_hoc_query.html
- templates/analytics/realm_summary_table.html
- web/styles/portico/activity.css
Updates the total row for the installation and remote activity charts to be in the table footer. Makes the footer class sticky to the bottom of the view so that it is always visible even if the chart has many rows.
Also, updates the installation activity column for revenue (ARR) to be formatted as a dollar string, since this formatting was being applied in the updated total row.
**Notes**:
- Tried to add an extra row to the header, but this meant the columns were no longer sortable with the current module that's being used.
@karlstolley and @alya - Would be good to get your feedback on these changes. Thanks!
<details>
<summary>Activity view - for revenue string formatting</summary>
</details>
<details>
<summary>Remote activity - with chart key …
> activity: Add totals row as sticky footer to activity charts.

- tools/lib/capitalization.py
- zerver/tests/test_push_notifications.py
- zilencer/views.py
> Improve validation at the `register/server` endpoint

- web/styles/zulip.css
- web/templates/invite_user_modal.hbs
- web/third/bootstrap/css/bootstrap-btn.css
- First commit is to re-add bootstrap CSS for `btn-link` elements in invite modal.
- Second commit removes bootstrap CSS rules for `btn-link` elements.
<details>
</details>
> Remove bootstrap css for `btn-link` elements.

- help/email-notifications.md
Fixes: https://chat.zulip.org/#narrow/stream/9-issues/topic/setting.20to.20manage.20newsletter/near/1726656
Current: https://zulip.com/help/email-notifications#low-traffic-newsletter
Updated:
> help: Clarify that newsletter only goes to Zulip Cloud users.

- web/src/stream_edit.js
- web/templates/stream_settings/stream_settings.hbs
This commit introduces a "reset to default notifications" button to the personal panel in stream settings. On clicking, it unmutes the stream and reset all notifications configurations to default.
Fixes zulip#27624.
[Screencast from 20-01-24 03:48:52 AM IST.webm](https://github.com/zulip/zulip/assets/33497322/148f085a-d045-4e55-a911-183bcd211db6)
**Reset notification button preview:**
<details>
</details>
> stream_settings: Add stream "reset to default notifications" button.

- help/mobile-notifications.md
Documents the new setting to control warning banners about mobile push notifications.
Fixes #28707.
- https://chat.zulip.org/help/mobile-notifications#warning-banners
<details>
</details>
> help: Document how to configure warnings about mobile notifications.

- templates/analytics/current_plan_forms_support.html
- templates/analytics/realm_details.html
- templates/analytics/remote_server_support.html
- templates/analytics/sponsorship_forms_support.html
- templates/analytics/support.html
- web/styles/portico/activity.css
Moves CSS styles for support view buttons to `web/styles/portico.activity.css`.
As the "sea-green" styles from the web-app were not being applied to the approve sponsorship buttons, moved the applicable CSS rules to that button class, "approve-sponsorship-button".
<details>
<summary>Iago user support view</summary>
| --- | --- |
| ![Screenshot from 2024-01-29 12-02-45](https://github.com/zulip/zulip/assets/63245456/4cd25cd2-86f3-4eeb-b927-b1f673f4bff5) | ![Screenshot from 2024-01-29 11-59-59](https://github.com/zulip/zulip/assets/63245456/d0df87fb-98a9-4090-991d-797a4314b6b6)
</details>
<details>
<summary>remote server support view</summary>
| --- | --- |
|![Screenshot from 2024-01-29 …
> bootstrap: Remove "bootstrap.btn" classes from support view buttons.

- web/src/popover_menus_data.js
- web/src/topic_popover.js
- web/src/unread_ops.js
- web/templates/topic_sidebar_actions.hbs
This commit adds a new option to the three-dot topic menu in the left sidebar to mark all the messages of topic as unread, provided the topic's messages are already read before choosing this option.
The  `bulk_mark_messages_as_read` method is slightly modified so that it can now mark bulk messages as read or unread.
Fixes #25085
<details>
</details>
> left_sidebar: Add mark all messages unread to three dot topic menu.

- web/shared/src/typeahead.ts
- web/src/typeahead_helper.ts
- web/tests/composebox_typeahead.test.js
- web/tests/typeahead.test.js
- web/tests/typeahead_helper.test.js
So far, when ordering typeahead suggestions, any query matches that did not occur at the start of the target string were considered equally. So for example, for the query "ok", "squared_ok" and "smoking" were allotted equal priority, which does not make sense.
Now, matches from a word boundary (space, hyphen, dash or slash) are given priority, so that in the above example, "squared_ok" is regarded as a better match than "smoking".
Fixes: #24127.
Before:
After:
<details> …
> typeahead: Prefer word boundary matches to arbitrary substring matches.

- corporate/lib/stripe.py
- templates/corporate/support/current_plan_forms_support.html
**Commit 1**: https://github.com/zulip/zulip/pull/28596#discussion_r1470062164
**Commit 2**:
If a plan is already on `basic` or `business` plan and wants to switch to a fixed-price `basic` / `business` plan, then it is necessary that the current plan should have an end date configured.
Earlier, we could update the `end_date` only if the current plan already had an `end_date` set.
This commit makes it possible to always show the option to set or update `end_date`.
---
<details><summary>Plan already has end_date</summary>
</img>
</details> 
<details><summary>No end_date</summary>
</img>
</details> 
---
<details> …
> support: Always show the option to update end_date on /support page.

- zerver/webhooks/alertmanager/tests.py
- zerver/webhooks/alertmanager/view.py
Renaming "graph" to "source" in Alertmanager's integration messages
Fixes: None
We use Alertmanager as an aggregation place for example for failing CI pipelines, and `graph` does not always reflect the source of the alert. It's called `source` originally and I think it should stay this way. 
> Renaming graph to source

- web/src/hash_parser.ts
- web/src/hashchange.js
- web/src/message_notifications.js
- web/src/ui_util.ts
- web/tests/hash_util.test.js
- web/tests/notifications.test.js
- web/tests/ui_util.test.js
Since notifications have limited space for the contents of a message, a quote from a previous message, or elsewhere, can take up most of the notification, leaving little room for the actual message, and reducing the usefulness of the notification.
To fix this, we collapse blockquotes and "user said" paragraphs to make space for the actual message.
Fixes: [CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/desktop.20notifications.20and.20block.20quotes)
<details> …
> notifications: Collapse blockquotes and "user said" paragraphs.

- templates/corporate/comparison_table_self_hosted.html
- templates/corporate/pricing_model.html
- web/styles/portico/comparison_table.css
- web/styles/portico/pricing_plans.css
This PR includes numerous fixes and improvements to the /plans page, including:
* Cleaning up structures and unused CSS
* Opening up the available width for plans panes for better line-wrapping
* Implementing finer details (font-sizing, hovers, minor dark-mode adjustments) from @terpimost's original design
* Adding a tooltip-style discount balloon on self-hosted plans
* Ensuring concord in the plans presentations between `/plans` and `/for/business`
This work began as a small set of prep commits for the scrolling controls, but got large enough to warrant its own preparatory PR.
| Large screens, before (`/plans`) | Large screens, after (`/plans`) |
| --- | --- |
| ![plans-cloud-before](https://github.com/zulip/zulip/assets/170719/dd908b21-e9fe-409c-9354- …
> portico: Fix up display of /plans pages.

- corporate/lib/stripe.py
- corporate/lib/support.py
- corporate/tests/test_stripe.py
- corporate/tests/test_support_views.py
- corporate/views/portico.py
- zilencer/management/commands/populate_billing_realms.py
Commit 1: Adds a `legacy remote-realm` to make it easy to test such realms.
Commit 2: Fix next plan info missing on support page for customers with no current plan.
For `free-tier-remote-realm` (no current plan), when fixed-price plan is configured:
<details><summary>Earlier Next plan info was missing</summary>
</img>
</details> 
Commit 3: Restrict free-trial when fixed-price plan is configured.
<details>
</details>
> populate_billing_realms: Add a legacy remote realm.

- web/templates/settings/display_settings.hbs
6cd165386aac0aac9fb4ab500a1358ea2280663a incorrectly converted this field with different names in the two places it is used.
@Aditya8840 FYI -- you need to take responsibility for testing your refactoring changes.
> settings: Fix buggy conversion of emoji-display-settings-status.

- web/src/compose_actions.js
- web/src/message_list.js
- web/src/narrow.js
- web/tests/narrow_activate.test.js
Fix an issue reported in https://chat.zulip.org/#narrow/stream/9-issues/topic/DM.20conversation.20opens.20in.20wrong.20place/near/1728883 that caused the user's scroll position to be jumped up unpleasantly when visiting direct message conversations due to an unfortunate interaction with the animated auto scroll.
> Fix direct message narrow scroll position bugs

- pyproject.toml
- zerver/data_import/import_util.py
- zerver/data_import/slack.py
- zerver/lib/export.py
- zerver/lib/import_realm.py
- zerver/lib/markdown/api_arguments_table_generator.py
- zerver/lib/outgoing_webhook.py
- zerver/migrations/0177_user_message_add_and_index_is_private_flag.py
- zerver/tests/test_message_edit.py
- zerver/tornado/event_queue.py
- zerver/webhooks/slack_incoming/view.py
This PR upgrades Zulip's Ruff configuration in preparation for Ruff's v0.2.0 release. (The changes are compatible with Ruff v0.1.14, which Zulip uses today.)
Specifically, we're now warning when linter-only options are specified under `[tool.ruff]` instead of `[tool.ruff.lint]`. We've also stabilized some changes to `RUF019` (and other rules) that led to some new violations, so I just went ahead and applied the fixers. `ruff check` now passes without error on Zulip with Ruff v0.2.0.
> Upgrade configuration for Ruff v0.2.0

- web/third/bootstrap/css/bootstrap.app.css
The same definition is already present app_components.css, so we don't need it here.
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/bootstrap
> bootstrap: Remove duplicate `invoice` class.

- zerver/actions/realm_settings.py
- zerver/tests/test_auth_backends.py
- zerver/views/realm.py
The endpoint was lacking validation that the authentication_methods dict submitted by the user made sense. So e.g. it allowed submitting a nonsense key like NoSuchBackend or modifying the realm's configured authentication methods for a backend that's not enabled on the server, which should not be allowed.
Both were ultimately harmless, because:
1. Submitting NoSuchBackend would luckily just trigger a KeyError inside the transaction.atomic() block in do_set_realm_authentication_methods so it would actually roll back the database changes it was trying to make. So this couldn't actually create some weird RealmAuthenticationMethod entries.
2. Silently enabling or disabling e.g. GitHub for a realm when GitHub isn't enabled on the server doesn't really change anything. And this action is only …
> realm_settings: Improve authentication_methods param validation.

- web/src/narrow.js
- web/src/search.js
- web/src/views_util.js
- web/tests/search.test.js
This function doesn't need to be called since `render_title_area` already takes care of it which is always called when changing narrow.
First commit from #28636
Discussion: https://github.com/zulip/zulip/pull/28636#discussion_r1463715960
So, `render_title_area` already calls `set_search_bar_text("");` via `close_search_bar_and_open_narrow_description`. So, the main call that we are removing here is `$("#search_query").trigger("blur");`. I don't see a reason why we should call it. Everthing seems to work fine without out. Also, `#search_query` is already blurred after user searches. Maybe this is not what the old behaviour was and we needed to blur it after user searched something.
> narrow: Remove duplicate clear search form.

- web/src/message_list_view.js
- web/src/message_scroll.js
- web/src/message_viewport.ts
- web/src/navigate.js
- web/src/ui_init.js
- web/src/unread_ops.js
- web/tests/example7.test.js
The previous logic for both scrolling down and using pagedown would incorrectly mark an entire conversation as read when reaching the bottom of a render window, even if there were more messages loaded or to fetch from the server.
Fix this error in the calculation by asking the correct data structures if we're actually at the bottom.
To avoid the navigate.js keyboard shortcut code paths circumventing this new logic, or needing to duplicate it, they now call process_visible, rather than its helper.
> unread: Stop treating bottom of render windows as the global bottom.

- web/src/compose_actions.js
This was introduced in #28767 with the intention to skip scrolling the selected message.
So, the actual bug that the PR fixed would have been just fixed by opening the compose box early.
> compose_actions: Fix incorrect condition.

- web/src/echo.js
- web/src/message_list_view.js
- web/src/message_lists.ts
- web/src/reactions.js
- web/templates/message_body.hbs
- web/tests/reactions.test.js
Reproducer:
* React to a message in a narrow.
* Go to All messages view.
* The message no longer has the reaction.
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/All.20message.20emoji.20reactions.20broken
> Fix reactions not being displayed on changing narrow for the same message.

- web/src/timerender.ts
Currently, when the "Add global time" of the compose box is pressed, it would result in an exception. This is because, it is using `get_timestamp_for_flatpickr`, without passing any parameter. 
This is avoided by doing an early return of current time to hour in case no string is passed to the get_timestamp_for_flatpickr method.
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Add.20global.20time.20of.20compose.20box.20broken)
<details> …
> timerender: Fix get_timestamp_for_flatpickr when no parameter passed

- web/src/message_list_view.js
- web/src/navigate.js
- web/src/unread_ops.js
- web/tests/example7.test.js
This is a follow-up addressing bugs in #28772, intended to fix the bugs reported in https://chat.zulip.org/#narrow/stream/9-issues/topic/recent.20conversations.20unread.20topic.20persists/near/1732064.
See the individual commits for details.
> Fix races when marking unread at end-of-feed.

- analytics/views/stats.py
We don't have an index on `(server_id, id)`, and in any case, we have a stronger guarantee that `remote_id` is time-sorted, from the construction of the analytics tables, than that the `id`s given these entries when uploaded are time-sorted.
> stats: Fix bad query plan for remote counts.

- corporate/lib/activity.py
- corporate/lib/support.py
- corporate/views/installation_activity.py
- corporate/views/realm_activity.py
- corporate/views/remote_activity.py
- corporate/views/support.py
- corporate/views/user_activity.py
- templates/corporate/support/remote_realm_details.html
- templates/corporate/support/remote_server_support.html
Adds the following information to the remote support view:
- For the remote server:
- Shows the last audit log update date/time, which is also displayed in the remote activity chart.
- Shows the date/time that the mobile pushes forwarded count was updated for the server.
- If there are remote realms, shows the count of mobile users that have not yet been associated with a remote realm. This helps to account for the potential discrepancy between the total mobile user count for the server and the sum of the mobile user counts for the remote realms associated with the server.
- For the remote realm:
- Shows the date/time that the mobile pushes forwarded count was updated for the realm.
**Notes**:
- The formatting for optional date/times in the activity views was setting the timezone to be …
> remote-support: Expand push notification data.

- templates/corporate/comparison_table_cloud.html
- templates/corporate/comparison_table_self_hosted.html
- templates/zerver/documentation_main.html
- web/templates/settings/add_new_bot_form.hbs
- zerver/openapi/zulip.yaml
This is a follow-up PR (#28775).
- Fixes "contact us" link in the footer of documentation pages.
- Updates links to "Bots overview" help center page.
> help: Improve integrations documentation (follow-up).

- tools/test-js-with-node
- web/shared/src/typing_status.js.flow
- web/shared/src/typing_status.ts
- web/src/page_params.ts
- web/src/typing.js
- web/src/typing.ts
- web/tests/typing_status.test.js
-> First commit adds `server_typing_started_wait_period_milliseconds`, `server_typing_stopped_wait_period_milliseconds` property to `page_params.ts`.
-> Second commit extends `Recipient` type and corresponding changes in `typing_status.js.flow` ,`typing_status.test.js` (to satisfy the tests).
-> Third commit converts module - `typing.js` to `TypeScript`.
discussion:[CZO](https://chat.zulip.org/#narrow/stream/6-frontend/topic/typing-js)
https://github.com/zulip/zulip/assets/123243429/882f42e9-738e-4264-b2e4-a411588244f9
https://github.com/zulip/zulip/assets/123243429/06fe547d-9ab9-4964-bb24-558403a5ae00
> typing: Convert module to TypeScript.

- zerver/lib/exceptions.py
- zerver/lib/push_notifications.py
- zerver/lib/remote_server.py
- zerver/tests/test_push_notifications.py
- zilencer/views.py
This was an uncaught JsonableError before, getting logged and email with a full traceback.
The first commit adds the bouncer-side of this fix - making this as a distinct json error with its own code.
The second takes advantage of that, by detecting that json error code, catching the exception in the appropriate place that sends a push notiification, and doing useful stuff with it
> Gracefully handle "Your plan doesn't allow sending push notifications." exception

- scripts/restart-server
- scripts/stop-server
Rather than tell the user to re-run the command as `zulip` instead of `root`, do the privilege-dropping ourselves.
<details>
</details>
> start-server/restart-server: Drop privileges if necessary.

- zerver/actions/create_user.py
This logic was apparently missed when we implemented private streams with shared history; the correct check is to look at whether the user can access message history in the stream, which used to be equivalent to whether it's a private stream.
> create_user: Fix initial unreads ignoring private streams.

- docs/contributing/contributor-statistics.md
- docs/contributing/index.md
Screenshot:
See [this CZO thread for more details](https://chat.zulip.org/#narrow/stream/2-general/topic/stats.20on.20.2Fteam.20page/near/1306415).
> team page: Display contributor count per repo.

- corporate/lib/stripe.py
Earlier, we were not setting `free_trial` = False for legacy customers in `do_upgrade`.
This lead to a bug where customers were upgraded even before the payment was complete (Actual payment happened within an hour). `process_initial_upgrade` was always getting called instead of `setup_upgrade_payment_intent_and_charge`.
This PR fixes the incorrect behaviour.
<details>
</details>
> corporate: Fix 'free_trial=True` for legacy customers during upgrade.

- web/shared/src/typing_status.ts
- web/src/message_list_view.js
- web/src/typing.ts
- web/templates/edited_notice.hbs
- web/templates/message_body.hbs
- web/tests/message_list_view.test.js
- zerver/actions/message_edit.py
This PR contains 3 preparatory as suggested in the review of the PR - #28585
- First commit (`fd887ca`): Refactors the editing notices as suggested in [review 1](https://github.com/zulip/zulip/pull/28585#discussion_r1480419695), [review 2](https://github.com/zulip/zulip/pull/28585#discussion_r1456298156) and [CZO]([CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/issue.20in.20message_list_view.20rendering.20logic)).
- Second commit (`fbbec5f`): Extracts the checks for message editing into a method, as suggested in the [review](https://github.com/zulip/zulip/pull/28585#discussion_r1480421982).
- Third commit (`b31ce04`): adds an extra `notification_event_type: "typing"` as suggested in the [review](https://github.com/zulip/zulip/pull/28585#discussion_r1484877271). 
**Screenshots …
> Preparatory commits for #28585

- corporate/lib/stripe.py
- corporate/models.py
- corporate/tests/test_support_views.py
- corporate/views/support.py
- templates/corporate/billing/billing.html
> billing: Remove extra space above renewal amount.

- web/styles/subscriptions.css
added padding-right to subscriber_list_remove class
Fixes: #26835
<details>
</details>
> Fix overlapping Unsubscribe button with side scroll. 

- web/src/stream_edit.js
- web/templates/stream_settings/confirm_stream_privacy_change_modal.hbs
This PR adds confirmation dialog widget for changing the privacy of a "Private, protected history" stream.
Fixes: #27916
<details>
</details>
> stream_settings: Add confirmation modal for changing privacy.

- web/templates/settings/bot_list_admin.hbs
- web/templates/settings/data_exports_admin.hbs
- web/templates/settings/deactivated_users_admin.hbs
- web/templates/settings/default_streams_list_admin.hbs
- web/templates/settings/emoji_settings_admin.hbs
- web/templates/settings/invites_list_admin.hbs
- web/templates/settings/linkifier_settings_admin.hbs
Fixes: #27250 
This PR fixes the first two items of the issue:
1. Changing the string "No X found" to "There are no X" in settings tables.
2. Using "emoji" rather than "emojis", like elsewhere on this page / in our documentation.
3. Replaces "No linkifers set." to "No linkifiers configured." (to match the Playgrounds placeholder text)
Before Changes
After Changes
Before Changes
After Changes
Before Changes
After Changes
Before Changes
After Changes
Before Changes
After Changes
Before Changes
After Changes
> settings: Improve placeholder text for empty settings tables

- web/src/stream_edit_subscribers.js
- web/src/user_group_edit.js
- web/src/user_group_edit_members.js
Previously, when wrong username is entered in the Stream Membership input to subscribe a user then "No User to Subscribe" error is thrown but the error is expected to fade away it remains until successful user is added and the same goes for succesfull messages too
This PR uses the `stream_subscription_req_result_elem` div which is responsible for showing both error and successful messages and makes the `innerHTML` to empty when user inputs into the input box which result in removal of message
Fixes : #27438
Fixes: 
**Before:**
**After**
**screen captures**
**Before:**
https://github.com/zulip/zulip/assets/88829894/0ccf3962-9936-4f35-8fbb-77245419eb9d
**After:**
https://github.com/zulip/zulip/assets/88829894/66e64ca4-c6ff-4bac-90ab-1bfd78 …
> input : Error message disappears when user inputs

- templates/zerver/documentation_main.html
- templates/zerver/portico-header.html
- web/src/portico/help.js
- web/styles/portico/portico.css
This PR fixes issue #28564 
I have added "Skip to main content" button which links the main content. Keyboard and screen readers can now skip to the main content without traveling long.
On Clicking Tab:
On Clicking Enter:
Please review my code. This is my first contribution to Zulip :)
> skip_navigation: Add a skip navigation link to the /help and /api sites

- corporate/lib/activity.py
- corporate/tests/test_activity_views.py
- corporate/views/installation_activity.py
- corporate/views/remote_activity.py
Expands the main query for remote servers to get the audit log event datetime for when the server was created/registered.
The remote realm object has a field for when the remote realm was created on the remote server.
**Notes**:
- I'm not sure if getting the audit log for the remote server creation date will make that big query much slower. But if it does, then we could consider an index for it.
- Creates a tiny helper function for formatting the datetime value in the chart. And updates the installation activity chart to use this function since there is an intention to potentially refactor that chart to be generated in a similar manner to the other activity charts in the future.
<details>
<summary>Updated remote activity chart</summary>
</details> …
> remote-activity: Add column for remote server or realm creation date.

- web/styles/zulip.css
- web/third/bootstrap/css/bootstrap.app.css
This PR removes the `html` & `body` selectors and styles from `bootstrap.app.css`, redeclaring only zeroed `margin` and `padding` values on `body` explicitly in `zulip.css`.
Removing the `text-size-adjust` properties does not affect Zulip web in horizontal orientation on an iPhone:
| --- | --- |
| ![html-bootstrap-before](https://github.com/zulip/zulip/assets/170719/e190b642-1610-43c4-b0ff-3d5ed98ddb3f) | ![html-bootstrap-after](https://github.com/zulip/zulip/assets/170719/15d8510d-a75e-4a20-be4d-fafdcd1699a6) |
Before and after of the interface looks identical:
| --- | --- |
| ![bootstrap-root-removal-before](https://github.com/zulip/zulip/assets/170719/2e40a9db-8a16-482e-bb12-675adaa250e1) | …
> bootstrap: Remove html, body components.

- web/src/click_handlers.js
- web/src/confirm_dialog.ts
- web/src/message_edit.js
- web/templates/confirm_dialog/confirm_merge_topics_with_rename.hbs
Fixes #27369.
[CZO conversation](https://chat.zulip.org/#narrow/stream/101-design/topic/unwanted.20merging.20of.20topics.20.2327369/near/1669292)
When editing a topic name via the topic header bar, it's easy to accidentally move messages into an existing topic, which is difficult to undo. This commit adds a confirmation modal for when this is about to happen.
newer screenshot:
older screen capture:
> topic edit: Warn when renaming a topic to an existing topic name.

- templates/zerver/landing_nav.html
- web/src/portico/header.ts
- web/styles/portico/navbar.css
Everything other than the last 2 commits is in #28753, so this PR is just focused on the last 2 commits.
Changes in Product menu:
- Drops home page link (it seems common not to have it; the Zulip logo takes you there anyway)
- Drops GitHub link (we still have it in Resources)
- Adds help center link (duplicated from Resources)
- Renames Features -> Feature matrix (will make more sense when we switch to the new features page)
- Renames Apps -> Desktop and mobile apps (for clarity, esp. since Slack uses "Apps" for plugins)
- Rearranges the columns, adds labels
- Moves use cases into this menu
Changes to Solutions -> Case studies menu:
- Dedicated menu just for case studies
- Arranged by category
If we like these changes, we'll need to do an engineering pass to make them work at different …
> portico: Reorganize top navigation area.

- web/src/settings_invites.ts
- web/templates/confirm_dialog/confirm_resend_invite.hbs
Fixes: #28829 
I have made the following changes to implement the required functionality:
1. Added question  mark to confirmation dialog heading in zulip/web/templates/confirm_dialog/confirm_resend_invite.hbs
2. Appended required text in confirmation dialog text in zulip/web/src/settings_invites.ts
**Before changes:**
**After changes:**
<details>
</details>
> Improve 'Resend invitation' confirmation modal

- corporate/lib/stripe.py
- corporate/tests/test_support_views.py
Earlier, on extending `end_date` for legacy plans, `next_invoice_date` was not extended which resulted in `invoice_plan()` run for such legacy plans before the `end_date`.
The intended behaviour is that the legacy plan should be invoiced only once on the `end_date` to downgrade or switch to a new tier.
<details>
</details>
> corporate: Fix `next_invoice_date` not updated on `end_date` extension.

- web/src/page_params.ts
As of commit fd2ad130f91805fd64e894b9058ec043726c4ac1 (#28930) this is popped in `ui_init.initialize_everything` now.
> page_params: Remove max_message_id from type

- corporate/lib/stripe.py
In cases where a support admin approves a sponsorship for a remote server without any billing users having been created, note that no emails were sent in the success message on the support page.
We already do this for remote realms and should be an infrequent case as ideally most remote servers will submit official sponsorship requests.
---
<details>
</details>
> remote-support: Note if emails were sent for remote server sponsorship.

- corporate/lib/support.py
- corporate/views/remote_activity.py
- templates/corporate/support/remote_realm_details.html
- templates/corporate/support/remote_server_support.html
**Notes**:
- The first commit fixes an error, which was introduced in commit 230294cfb31ba4b1e9fb1427147b3683c84376e6, that broke the support links in the remote activity view.
- The second commit fixes the remote support view to display the start of the day time interval for the most recent update to the mobile pushes forwarded CountStat for either the remote server or remote realm.
<details>
<summary>Remote support view - with either None or date for last push notification forwarded</summary>
</details>
<details>
<summary>Remote activity view - hovering over support links</summary>
</details>
---
<details> …
> Remote activity fix support links and last push notification date

- web/src/message_view_header.js
- web/templates/message_view_header.hbs
Fixes: #28851
| Before(Any User) | After(Admin or Owner) | After(Other User)
|![Screenshot from 2024-02-07 22-53-05](https://github.com/zulip/zulip/assets/90370535/aab9d398-8452-484f-ada1-cf7130aad498)| ![Screenshot from 2024-02-15 10-25-22](https://github.com/zulip/zulip/assets/90370535/2548a52b-303f-444b-b8cb-887fbc9d8287)| ![Screenshot from 2024-02-07 22-10-23](https://github.com/zulip/zulip/assets/90370535/6ec53a04-a605-4826-bd61-eb3c6ef76627)|
|![Screenshot from 2024-02-07 22-52-41](https://github.com/zulip/zulip/assets/90370535/c5667863-622c-4ed4-b6a4-bb1f53761e4d)| ![Screenshot from 2024-02-15 10-25-01](https://github.com/zulip/zulip/assets/90370535/117a98f2-2d64-49d1-85dd-3778f91d2948)| ![Screenshot from 2024-02-07 …
> Change header of streams without description.

- tools/lint
Commit 3a27b12a7dc9580e565946d3252720cbdce08934 (#24731) migrated yarn.lock to pnpm-lock.yaml.
> lint: Remove .lock extension from frontend group

- web/src/base_page_params.ts
- zerver/lib/home.py
- zerver/tests/test_home.py
Fix a ZodError when spectators load the app, introduced by commit a4938d3760d5d9c67fb3c4f72274d8f775321931 (#28971).
> page_params: Set and expect state_data = null for spectators

- web/webpack.assets.json
Commit a4938d3760d5d9c67fb3c4f72274d8f775321931 (#28971) fixed the order-sensitivity of these modules, so it suffices to just import them where they are used.
> webpack: Remove extraneous inclusions of page_params

- web/third/bootstrap/css/bootstrap.app.css
There is no greppable evidence of the `<q>` (quote) element in use in the Zulip UI, nor that any of the Python-Markdown syntax generates them either.
> bootstrap: Remove q styles.

- web/src/bundles/app.ts
- web/src/desktop_integration.js
- web/src/server_events.js
- web/src/settings.js
Some of these may have once been necessary to enforce an ordering on cyclic imports, but we’ve fixed all of those now.
> bundles: Remove unnecessary imports of effect-free modules

- zilencer/views.py
Just like deactivated realms should be excluded, so should locally deleted realms.
In particular, failure to exclude locally deleted realms breaks handle_customer_migration_from_server_to_realms.
> zilencer: Exclude realm_locally_deleted in get_human_user_realm_uuids.

- web/src/compose.js
- web/src/echo.js
- web/tests/compose.test.js
- web/tests/echo.test.js
Now whenever we initiate sending a message, we save / update its draft, which is deleted on a successful send. Earlier, we did this only for locally echoed messages. Hence a non locally echoed message's draft would remain, if created in the timeframe between initiating send and receiving the same message from the server, which can be significant for slow connections.
Fixes: [CZO issue thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/able.20to.20send.20message.20and.20save.20draft.20together/near/1733960)
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/com …
> compose: Fix bug where sometimes message draft remained post sending it.

- web/styles/app_components.css
- web/styles/compose.css
- web/styles/inbox.css
- web/styles/popovers.css
The distance between the stream name and the down arrow in the compose box dropdown corrected.
Fixes:  #28797 
Before:
After:
<details>
</details>
> Added space to between stream name and down arrow

- corporate/tests/test_remote_billing.py
- corporate/views/remote_billing_page.py
- zilencer/views.py
Here's the most likely scenario to cause a state that this aims to fix:
1. A server was on the legacy plan
2. Admin opened realm-level "Plan management", causing the legacy plan to get migrated to the realm.
3. Legacy plan expired, the admin fills out a sponsorship form from the server-level view and gets approved for Community plan.
4. Now opening realm-level plan management will attempt to migrate the Community plan to the realm, triggering `IntegrityError`. This PR fixes that scenario.
Detailed overview copied from the commit message:
The logic in the case where there's only one realm and the function
tries to migrate the server's plan to it, had two main unhandled edge
cases that would throw exceptions:
1.
```
remote_realm = RemoteRealm.objects.get(
uuid=realm_uuids[0], …
```
> Fix `handle_customer_migration_from_server_to_realms` when the RemoteRealm has a Customer object

- web/src/click_handlers.js
- web/src/tippyjs.ts
- web/styles/popovers.css
- web/templates/popovers/user_card/user_card_popover.hbs
- web/templates/status_emoji.hbs
This issue requires us to add a dedicated tooltip whenever the user hovers over the status-emoji in the left and right sidebar.Currently we don't show the name of status-emoji in sidebars and only show the active-status tooltip.
This PR adds a dedicated tooltip in left and right sidebar whenever user hovers over the status-emoji.
Provisionally, the changes done are - 
1) Whenever the status-emoji is hovered in right sidebar , the buddy list tooltips instance will be hidden and vice-versa for status-emoji-tooltip.
2) Same goes for left sidebar / dm section . 
Fixes: #26772
<details> …
> tooltips: Add a dedicated tooltip for status-emojis.

- puppet/zulip/templates/nginx/trusted-proto.template.erb
- templates/corporate/comparison_table_integrated.html
Following up on #28969, this PR updates outdated links to new [Reverse proxies](https://zulip.readthedocs.io/en/latest/production/reverse-proxies.html) documentation page.
> docs: Update links to new "Reverse proxies" page.

- zerver/lib/topic.py
- zerver/migrations/0497_resort_edit_history.py
5c96f942060e mistakenly appended, rather than prepended, the edit to the history.  This caused AssertionErrors when attempting to view the history of moved messages, which check that the `last_edit_time` matches the timestamp of the first edit in the list.
Fix the ordering, and update the `edit_history` for messages that were affected.  We limit to only messages edited since the commit was merged, since that helps bound the affected messages somewhat.
<details> …
> topic: Fix history order for topic moves.

- analytics/tests/test_counts.py
- corporate/lib/stripe.py
- zerver/tests/test_push_notifications.py
The previous logic incorrectly used the server-level number of users even when a (presumably smaller) realm-level count was available.
Fixes a bug introduced in 2e1ed4431adf8dfe1e8bcfeae63dfc327b425369.
@prakhar1144 review appreciated, and perhaps you can look at doing the follow-up suggested in the TODO comment in your next billing PR.
> corporate: Fix billing_session variable reuse confusion.

- help/keyboard-shortcuts.md
- templates/zerver/app/index.html
- web/src/hotkey.js
- web/src/read_receipts.ts
- web/styles/dark_theme.css
- web/styles/modal.css
- web/templates/keyboard_shortcuts.hbs
- web/templates/popovers/actions_popover.hbs
- web/templates/read_receipts.hbs
- web/templates/read_receipts_modal.hbs
- web/tests/hotkey.test.js
The read receipts option, receides under the triple-dot message actions menu. This made the process of viewing the read receipts take up multiple steps, even via a keyboard-driven workflow.
Via this PR, now while focused on a message in any message feed, and pressing `Shift` + `V`, efficiently brings up the read receipts for that message.
Fixes part of #24716.
| Screencast |
|--------|
| ![shift+v](https://github.com/zulip/zulip/assets/82862779/0dd730b2-4d14-4b51-bfd5-422a94d5a1e2) |
| Message actions menu | ![image](https://github.com/zulip/zulip/assets/82862779/07a7e477-0020-4a18-85a5-471e7d525611) | ![image](https://github.com/zulip/zulip/assets/82862779/e5d367c4-7531-4b0c-b6ae-83cc6f3cdc77) |
| …
> hotkey: Add `Shift` + `V` keyboard shortcut for the read receipts menu.

- .editorconfig
This was added in https://github.com/mvdan/sh/commit/7f96e7d84a265f4d1005b96493422cde800bf9d1.
> editorconfig: Use `[[shell]]` section for shfmt options

- web/styles/portico/comparison_table.css
This PR corrects a whole bunch of different edge cases, largely at smaller screen sizes, where sticky headers spilled over the top of the header row or fell out of nice alignment with the plans labels.
It also provides a fix for overscrolling on the features table's All view, which can be viewed in viewports as narrow as 374px (previously, it needed a viewport of at least 406px to not begin to scroll).
_Firefox does not capture blur effects, so disregard the lack of blur behind the menus here._
| Cloud view, before | Cloud view, after |
| --- | --- |
| ![cloud-view-before](https://github.com/zulip/zulip/assets/170719/f2fb4ccf-de76-49dc-aad1-fea336e2fc35) | ![cloud-view-after](https://github.com/zulip/zulip/assets/170719/4390580c-1f10-4b77-a0f1-3756ceb1a …
> portico: Features table fixes.

- help/code-blocks.md
- web/templates/settings/playground_settings_admin.hbs
`git grep replit | grep -v locale/` produces no results after these changes.
---
Settings panel:
---
Current help center section: https://zulip.com/help/code-blocks#code-playgrounds
Updated:
I also edited the second step to match the current settings UI.
> playgrounds: Replace replit playground example with Rust playground.

- web/src/settings_invites.ts
- web/templates/settings/invites_list_admin.hbs
Sorting of invitations by the "Expires at" column was broken. This PR corrects the sorting logic to ensure invitations are sorted correctly based on their expiry dates.
Fixes: #29005.
----
<details>
</details>
> Fix sorting of invitations by the "Expires at" column

- corporate/lib/support.py
- corporate/tests/test_support_views.py
- templates/corporate/support/current_plan_details.html
- templates/corporate/support/next_plan_details.html
- templates/corporate/support/next_plan_forms_support.html
- templates/corporate/support/push_status_details.html
- templates/corporate/support/remote_realm_details.html
- templates/corporate/support/remote_server_support.html
- templates/corporate/support/sponsorship_forms_support.html
- web/styles/portico/activity.css
Adds the information returned by `get_push_status_for_remote_request` for remote billing users to the remote support page. 
**Notes**:
- Getting the current push status data will result in some duplicate database queries (getting customer, plan, current billed users, next billing cycle) when generating the remote support view.
- There's a prep commit to add a class for the section headers in the support views. These were all previously using the bootstrap rules for `<h4>` tags. This makes the spacing a bit more compact and consistent.
<details>
<summary>Example with realm deactivated notices</summary>
</details>
<details>
<summary>Example of server with realms</summary>
</details>
<details>
<summary>Example server on community plan</summary>
</details> …
> remote-support: Add push notification status information.

- api_docs/api-keys.md
- api_docs/configuring-python-bindings.md
- help/add-a-bot-or-integration.md
- templates/zerver/integrations/google-calendar.md
- web/templates/settings/account_settings.hbs
- web/templates/settings/api_key_modal.hbs
- zerver/lib/markdown/tabbed_sections.py
- Adds instructions for downloading a zuliprc file for a bot or for yourself.
- Updates the button label to "Download zuliprc", since that's the filename it downloads.
- Renames button to "Manage your API key", and updates docs accordingly.
Fixes #28881.
- https://chat.zulip.org/api/configuring-python-bindings
- https://chat.zulip.org/#settings/account-and-privacy
<details>
</details>
> api-docs: Add instructions to download `zuliprc` files.

- templates/corporate/pricing_model.html
- templates/corporate/self-hosting.html
- web/styles/portico/landing_page.css
This got accidentally dropped from #28754.
It needs some CSS work to look reasonable. I wasn't able to find an existing style that would look OK here. @amanagr would you be up for proposing something here?
<details>
<summary>
Screenshots
</summary>
</details>
> portico: Add quote to /self-hosting.

- corporate/tests/test_support_views.py
- corporate/views/support.py
- templates/corporate/support/remote_realm_details.html
- templates/corporate/support/remote_server_support.html
- tools/linter_lib/custom_check.py
- zilencer/models.py
**Notes**:
- Adds a list of active billing users for the remote server and remote realms. Uses a variation of how we get the admin and owner emails on the Zulip Cloud support view.
- Adds search results for emails that match either a remote server or remote realm billing user.
<details>
<summary>Email with no matches to billing users or remote server contact emails</summary>
</details>
<details>
<summary>Email with remote realm billing user match</summary>
</details>
<details>
<summary>Email with match to both contact and billing user email - one response</summary>
</details>
---
<details>
Individual …
> remote-support: Add billing user emails and ability to search by those emails

- web/src/inbox_ui.js
- web/src/unread.ts
Missed refactor from the earlier typescript conversion
> unread: Refactor get_counts for two return types.

- web/src/compose_setup.js
- web/src/message_edit.js
- web/src/upload.js
- web/tests/compose.test.js
Every time a user edits a message, we call the `setup_upload` method which creates a new Uppy instance and adds some event listeners to enable the upload process. These event listeners were not being removed during the cleanup process of message editing, which led to multiple event listeners being attached to the edit message form. Due to this, multiple duplicate files would get attached via these multiple event listeners if a user opened the edit message form for the same message multiple times.
This PR adds the `deactivate_upload` method to perform all the necessary cleanups while closing the edit message form. Via this method, we remove the event listeners attached and close the Uppy instance which cancels all uploads, resets progress and removes all files.
Fixes: [CZO …
> uploads: Fix duplicate drag-and-drop uploads during message editing.

- help/all-messages.md
- help/configure-multi-language-search.md
- help/include/recent-conversations.md
- help/keyboard-shortcuts.md
- help/mastering-the-compose-box.md
- help/reading-strategies.md
- web/src/compose_notifications.ts
- web/templates/keyboard_shortcuts.hbs
Notes:
- I didn't include screenshots of all the help pages; let me know if you need them.
- Did not update api docs or contributor docs.
- The order of sections in the ? menu now matches the help center page.
---
<details>
<summary>
Banner
</summary>
</details>
<details>
<summary>
? menu
</summary>
</details>
Keyboard shortcuts help page: https://zulip.com/help/search-for-messages#search-filt
<details>
<summary>
Updated keyboard shortcuts help page
</summary>
</details>
> Excise "narrow" from app and help center

- api_docs/api-keys.md
- api_docs/deploying-bots.md
- api_docs/incoming-webhooks-overview.md
- api_docs/incoming-webhooks-walkthrough.md
- api_docs/installation-instructions.md
- api_docs/non-webhook-integrations.md
- api_docs/outgoing-webhooks.md
- api_docs/running-bots.md
- api_docs/writing-bots.md
- Updates API doc to follow current help center documentation patterns.
- Updates API docs that have numbered instructions to use the `{start_tabs}` formatting we use in the help center.
- Cross-links related articles.
Fixes #28876.
-  https://zulip.com/api/api-keys
<details>
</details>
> api-docs: Update "API keys", use `start_tabs` formatting, and cross-link related articles.

- help/latex.md
- web/templates/popovers/compose_control_buttons/compose_control_buttons_in_popover.hbs
Current help page: https://zulip.com/help/latex
> tooltips: Rename LaTeX button to "Math (LaTeX)".

- zerver/models/realm_audit_logs.py
- zerver/tests/test_push_notifications.py
- zilencer/views.py
> Set `realm_locally_deleted=True` when a realm re-appears during realm sync

- web/e2e-tests/admin.test.ts
https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/main.20failing/near/1743361
This might be similar to the failure reported in #28864.
<details>
</details>
> puppeteer: Disable flaky administrative UI test.

- web/src/message_list_tooltips.js
- web/templates/message_avatar.hbs
- web/templates/message_body.hbs
- web/templates/tooltip_templates.hbs
This PR aids in differentiating between a normal user and a bot account, furthur eliminating any confusion between them (a step forward, considering how good LLM bots have become in impersonating a real user).
Fixes #25958.
> [!NOTE]
> This is a completion PR for #27934.
| ![view_bot_card_before](https://github.com/zulip/zulip/assets/82862779/702053bc-87d1-4c23-94ce-fd2f6ef35efd) | ![view_bot_card_after](https://github.com/zulip/zulip/assets/82862779/b8419391-b105-4a11-a616-08aa88ddbd8e) |
"View user card" remains unchanged for normal users.
<details>
Individual …
> message_list_tooltips: Add "View bot card" tooltips for bots.

- zerver/webhooks/slack/doc.md
- zerver/webhooks/slack/tests.py
- zerver/webhooks/slack/view.py
Due to the `channel_map_to_topics` URL parameter in the Slack webhook, it was not migrated to use the `check_send_webhook_message`. Here we update the integration to use that function for sending the Slack integration webhook messages.
**Notes**:
- By using `check_send_webhook_message`, any topic parameter in the webhook URL will be prioritized over mapping Slack channels to topics, e.g. when `channel_map_to_topics` is true. This is because the default behaviour for incoming webhooks is to send a default topic as a parameter to `check_send_webhook_message` in case there is no topic specified in the URL.
- In contrast, we can override the stream passed in the URL when `channel_map_to_topics` is false by passing the Slack channel name to `check_send_webhook_message`. The default behaviour …
> integrations: Update Slack webhook to use check_send_webhook_message.

- docs/overview/architecture-overview.md
removed "using" wrong or unnecessary
> docs: Fixed a typo

- analytics/lib/counts.py
- zerver/lib/remote_server.py
- zerver/tests/test_push_notifications.py
`LoggingCountStat`s with a daily duration and that are directly stored on the `RealmCount` table (not via aggregation in `process_count_stat`), can be in a state, after the hourly cron job to update analytics counts, where the logged value will be live-updated later, because the end time for the stat is still in the future.
As these logging counts are designed to be used on the self-hosted installation for either debugging or rate limiting, sending these partial/incomplete counts to the bouncer has low value.
---
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit …
> push-bouncer: Exclude LoggingCountStats with partial data.

- puppet/zulip/templates/supervisor/zulip.conf.template.erb
- tools/run-dev
- zerver/management/commands/runtornado.py
This makes no immediate reloads the default for runtornado, matching the production configuration, and changes the development incantation to be the one to specify the departure from the norm, with --immediate-reloads.
<details>
</details>
> runtornado: Swap deferred reload events to the default.

- zerver/lib/events.py
- zerver/tests/test_events.py
These signal that the Tornado process restarted, which in itself is not notable for apply_events.
Fixes: 
<details>
</details>
> events: Do nothing in apply_event for restart events.

- templates/corporate/features.html
- templates/corporate/for/business.html
- templates/corporate/for/education.html
- templates/corporate/for/events.html
- templates/corporate/for/open-source.html
- templates/corporate/for/research.html
- templates/corporate/values.html
- templates/corporate/values.md
- templates/corporate/why-zulip.md
- zerver/tests/test_docs.py
<details>
<summary>
Selected screenshots
</summary>
</details>
> portico: Consistently describe Zulip as organized team chat.

- help/create-a-poll.md
Adds missing icon for the poll button.
Fixes #29051.
- https://zulip.com/help/create-a-poll#create-a-poll
<details>
</details>
> help: Add poll icon to "Create a poll".

- web/src/buddy_list.ts
More context for this change here:
https://github.com/zulip/zulip/pull/29022#discussion_r1499949934
> buddy_list: Assert we always find something with find_li.

- web/styles/app_variables.css
- web/styles/reactions.css
This PR increases the prominence of one's own emoji reactions by:
1. Setting a pixel-and-a-half border around own reactions
2. Reducing the alpha on the inner drop shadow of other reactions
3. Increasing the contrast on own reactions borders (and decreasing them, in dark mode, on other reactions)
Space around the emoji is maintained as in the current design in the own reactions. Other reactions benefit from an additional half pixel of padding, top and bottom, which is necessary to keep the pills (and the hover reaction button) the same height as each other--regardless of whether there's an own reaction among them or not. Padding is reduced in line with the increased border on own reactions.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/8.2E0.20reactions.20changes. …
> reactions: Increase prominence of own reactions.

- help/email-notifications.md
- help/include/view-mentions.md
- help/link-to-a-message-or-conversation.md
- help/marking-messages-as-read.md
- help/mastering-the-compose-box.md
Previously, links went to /help/recent-conversations.
After these changes, this returns no results: `git grep "conversation](/help/recent" help/ `.
> help: Link to /help/reading-conversations to define "conversation".

- web/src/base_page_params.ts
This was broken in commit a4938d3760d5d9c67fb3c4f72274d8f775321931 (#28971).
> base_page_params: Restore google_analytics_id

- help/marking-messages-as-read.md
The definition of "conversation" is copy-pasted (not included) to avoid an undesirable line break.
Current: https://zulip.com/help/marking-messages-as-read
Updated:
> help: Explain options for automatically marking as read in detail.

- help/configure-notification-bot.md
As noted in https://github.com/zulip/zulip/pull/29049#issuecomment-1962741151, this PR adds basic documentation for the new organization setting for posting Zulip news.
See #28604.
<details>
</details>
> help: Document "Zulip update announcements" setting.

- templates/corporate/apps.html
- web/src/portico/landing-page.js
- web/styles/portico/landing_page.css
Builds on #28773.
The following needs engineering help:
- Rebase on `main`, since #28773 has been merged.
- Change "download APK" back to "manually download APK".
- Link "desktop notifications" to /help/desktop-notifications
- Link "mobile notifications" to /help/mobile-notifications
- Customize the wording for the help installation instructions help links by platform, replacing "Need help? See installation guide." in this PR.
- Mac: For help or to install via Homebrew, see our [installation guide](https://zulip.com/help/desktop-app-install-guide).
- Windows: For help or to install offline, see our [installation guide](https://zulip.com/help/desktop-app-install-guide).
- Linux: For help or to install via a package manager, see our [installation …
> Proposed revision for /apps

- docs/production/deployment.md
- docs/production/reverse-proxies.md
Introduced in 2b9506840684ceb9e27ba5b509561be509d7059d.
> docs: Fix broken Markdown links from recent reorganization.

- corporate/views/support.py
As a follow-up to commit d66b7ad853 (#29120), where we send internal emails when an active paid plan is on a locally deleted remote realm, we need search queries in the remote support view to return results for these deactivated remote realms, instead of excluding them. Particularly since the support URL generated for these emails uses the remote realm UUID as of #29125.
---
<details>
</details>
> remote-support: Show remote realm matches if deactivated.

- corporate/tests/test_support_views.py
- corporate/views/support.py
- templates/corporate/support/remote_realm_details.html
- templates/corporate/support/remote_server_support.html
- templates/corporate/support/sponsorship_details.html
- templates/corporate/support/sponsorship_forms_support.html
- templates/corporate/support/sponsorship_request_details.html
- web/styles/portico/activity.css
The remote support view now returns results for deactivated remote servers with those results sorted to the end and formatted to visually stand out.
**Notes**:
- Forms to change sponsorship and discount fields on the customer for the remote server or realm are not shown, but the data stored on the customer object is shown, including any sponsorship request information (if the customer had a sponsorship request pending when it was deactivated).
- Forms to schedule a plan are also not shown for deactivated servers and their associated remote realms.
- Forms and information for any current plan or scheduled plan, for either the deactivated remote server or its associated remote realms, are shown so that support staff can update those plans if necessary.
- Pulls out the information about the …
> remote-support: Show deactivated servers in search results.

- web/src/narrow_banner.ts
- web/tests/narrow.test.js
This pr changes placeholder text for dm with yourself from `Why not start a conversation with yourself` to `Use this space for personal notes and test messages.`
Fixes: #29078
<details>
</details>
> Onboarding: Improve placeholder message for dm with yourself

- .github/workflows/production-suite.yml
- .github/workflows/zulip-ci.yml
- docs/development/setup-advanced.md
- docs/development/setup-recommended.md
- docs/production/requirements.md
- requirements/common.in
- requirements/dev.in
- requirements/dev.txt
- requirements/pip.in
- requirements/pip.txt
- requirements/prod.txt
- scripts/lib/build-pgroonga
- scripts/lib/install
- scripts/setup/apt-repos/zulip/custom.sh
- scripts/setup/apt-repos/zulip/noble.list
- tools/ci/build-docker-images
- tools/lib/provision.py
- version.py
- zerver/lib/email_notifications.py
- zerver/lib/validator.py
- zerver/signals.py
- zerver/tests/test_new_users.py
The Ubuntu 24.04 feature freeze and Debian import freeze aren’t until [February 29](https://discourse.ubuntu.com/t/noble-numbat-release-schedule/35649), but Python 3.12 as default went in today, so it’s worth trying out.
> install: Support Ubuntu 24.04

- web/src/message_edit_history.ts
- web/src/message_viewport.ts
- web/src/rendered_markdown.ts
- web/src/rows.ts
- web/src/user_group_popover.ts
This lets us simplify their types and remove dead error-handling code.
> rows: Make errors fatal in id, local_echo_id

- tools/setup/dev-vagrant-docker/Dockerfile
https://github.com/gdraheim/docker-systemctl-replacement/compare/v1.5.7106...v1.5.8066
> dev-vagrant-docker: Upgrade docker-systemctl-replacement to 1.5.8066

- web/templates/inbox_view/inbox_row.hbs
[CZO Thread](https://chat.zulip.org/#narrow/stream/101-design/topic/remove.20default.20notifications.20icon.20in.20Inbox/near/1749510)
Vlad Korobov has suggested removing the default notifications icon in the Inbox view; it would still be possible to change topic visibility there via the three-dot menu.
<details><summary>Inbox - No icon for default</summary>
</img>
</details> 
<details>
---
</details>
> inbox: Remove 'default' visibility policy indicator.

- zerver/actions/message_send.py
- zerver/actions/user_settings.py
- zerver/lib/cache.py
- zerver/lib/cache_helpers.py
- zerver/tests/test_soft_deactivation.py
This saves a hit to the database to fetch the Realm of a UserProfile that we are trying to flush.
<details>
</details>
> caches: Only take the realm_id, not the Realm, as a cache key function.

- web/src/hashchange.js
- web/src/stream_settings_ui.js
- web/src/user_group_edit.js
- web/src/user_profile.js
- web/templates/user_group_list_item.hbs
This is a possible fix for #25214
Still waiting for clarification on whether we want similar controls as in "Streams" tab or not. But i'll hazard a guess that we don't, atleast for this issue. 
<details>
<summary>git grep output</summary>
```bash
$ git grep .group_list_item_link
web/src/user_profile.js:    $("body").on("click", "#user-profile-modal .group_list_item_link", () => {
web/templates/user_group_list_item.hbs:            <a class = "group_list_item_link" href="{{group_edit_url}}">{{name}}</a>
```
</details>
<details>
<summary>Before: all users</summary>
</details>
<details>
<summary>After: normal users</summary>
https://github.com/zulip/zulip/assets/133781250/4f8ce6e0-ffe5-4852-8714-b21562513ab5
</details>
<details>
<summary>After: guest …
> user_profile: Add links to group settings.

- web/src/compose_ui.ts
- web/tests/compose_ui.test.js
compose: Fix bug where inserted content would not be scrolled into view.
On chromium browsers, the scroll position is not restored when the text in a textarea is replaced. So instead of directly replacing the text, we call the `insert_and_scroll_into_view` function with `replace_all` set to true.
compose: Add parameter `replace_all` to `insert_and_scroll_into_view`.
We refactor the `insert_and_scroll_into_view` function to accept a new parameter, `replace_all`, defaulting to false, that when set to `true`, will replace all existing content of the textarea with the new content, instead of inserting the new content at the current cursor position.
This is a prep commit for the next commit, which will set this new flag.
Fixes: [CZO issue …
> compose: Fix bug where inserted content would not be scrolled into view.

- web/src/message_store.ts
- web/src/reactions.js
- web/src/reactions.ts
- web/tests/reactions.test.js
Split this into several commits since there was a lot going on. 
[reactions: Calculate vote_text before creating clean reaction.](https://github.com/zulip/zulip/pull/28375/commits/614ea588d530de0b2ffe81501576f19eaf6e1165) commit feels a bit messy but wasn't sure if there was a nicer way to do that. Would love feedback there
> reactions: Convert module to typescript

- web/src/message_list_tooltips.js
- web/src/ui_init.js
Events that are called after a delay can find message_lists.current to be undefined if user has moved to non-message list view.
> message_list: Fix delayed events finding current msg list undefined.

- web/src/copy_and_paste.js
- web/tests/copy_and_paste.test.js
Since the html copied from VS Code is not structured as code but as styled divs for each line, any code copied from it would be pasted unformatted with blank lines between each line of code.
This has now been fixed, by detecting VS Code style code blocks by the CSS property `white-space: pre` and pasting the text within as is, as code.
> copy_and_paste: Fix formatting of code pasted from VS Code.

- corporate/tests/test_remote_billing.py
- templates/corporate/billing/remote_realm_login_error_for_server_on_active_plan.html
- templates/zerver/config_error/container.html
- templates/zerver/config_error/remote_billing_bouncer_not_configured.html
- web/styles/portico/portico.css
- zerver/lib/home.py
- zerver/lib/test_helpers.py
- zerver/tests/test_home.py
- zerver/views/errors.py
- zerver/views/push_notifications.py
- zproject/urls.py
Just shows a config error page if the bouncer is not enabled. Uses a new endpoint for this so that it can work nicely for both browser and desktop app clients.
It's necessary, because the desktop app expects to get a json response with either an error or billing_access_url to redirect to. Showing a nice config error page can't be done via the json error mechanism, so instead we just serve a redirect to the new error page, which the app will open in the browser in a new window or tab.
> remote_billing: Make "plan management" always available.

- web/styles/portico/comparison_table.css
This PR removes the tab for All plans at mobile scales below 460px, the point at which the All plans features-comparison table cannot comfortably fit within a narrow viewport.
Note that this does not attempt to catch edge cases like where All tabs might be selected and then the viewport shifts smaller (e.g., on an orientation shift from landscape to portrait.
| 460px wide, Before | 460px wide, After |
| --- | --- |
| ![460-wide-before](https://github.com/zulip/zulip/assets/170719/153cb8fe-adbe-439d-a7d6-f3ae9d420659) | ![460-wide-after](https://github.com/zulip/zulip/assets/170719/f9b20c29-a4ce-4a4e-b5b3-fdae6dd11d3f) |
| 470px wide, Before | 470px wide, After (no change) |
| --- | --- |
| ![470-wide-before](https://github.com/zulip/zulip/assets/170719/ …
> portico: Remove All plans tab at mobile scale.

- web/src/compose_recipient.js
We were updating the compose banners on every `keyup` event on the topic input. Since, `keyup` also gets triggered for the modifier and non-printing keys such as "Enter", this lead to banner for topic required being closed via the `check_posting_policy_for_compose_box` when pressing "Enter" to send a message with no topic.
This bug was probably introduced in 5c993f0, which moved additional logic into `update_on_recipient_change`.
To solve this issue, we use the `input` event instead of the `keyup` event to update the compose banners only when the value inside the input element changes.
This also as a side effect solves two other issues:
1. Prevents the the compose banner from being closed when we only press modifier keys - such as Shift/Caps.
2. Fixes the flashing "Direct messages are …
> compose: Fix topics required banner closing on enter to send.

- web/styles/app_variables.css
- web/styles/dark_theme.css
- web/styles/reactions.css
This PR improves the CSS around the emoji picker:
1. It removes a few stale selectors leftover from before the picker's implementation in Tippy
2. It reorders a selector to make it easier to cross-reference the CSS with HTML order in templates
3. It creates variables for emoji picker background, border, and box-shadow colors
4. It eliminates all separate emoji-picker references from `dark_theme.css`
It also introduces a previously missing dark-theme color for the `:focus` state on a reacted emoji.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/emoji.20picker.20dark.20theme/near/1745800)
_Showing focus on reacted emoji_
| --- | --- |
| ![light-mode-reacted-emoji-focused-before](https://github.com/zulip/zulip/asse …
> emoji_picker: Improve CSS and correct light bleedthrough in dark theme.

- web/src/tippyjs.ts
- web/src/user_settings.ts
- web/templates/org_logo_tooltip.hbs
The organization logo in the upper left navigates to the user's home view. We add a tooltip to make this easier to discover.
We show `Esc` as the keyboard shortcut here, unless the user has disabled it, in which case we show the alt shortcut `Ctrl` + `[`.
Fixes: #29185.
<details><summary>When ` Escape key navigates to home view` is disabled</summary>
<p>
</p>
</details> 
<details><summary>When ` Escape key navigates to home view` is enabled</summary>
<p>
</p>
</details> 
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-disci …
> navbar: Add navigate to home view tooltip to the organization logo.

- web/src/condense.js
- web/src/message_actions_popover.js
This creates a much cleaner API and types for these functions. Since the callers already had the message objects, this avoids extra work both in the most callers and in these functions.
We also loop through all_rendered_message_lists rather than hardcoding logic for message_lists.home.
> condense: Pass message objects to collapse functions.

- tools/test-js-with-node
- web/src/compose_fade.js
- web/src/compose_fade.ts
- web/src/message_viewport.ts
- web/src/rows.ts
[Commit-3](https://github.com/zulip/zulip/commit/95fd0fe87a31562d6006183477b0401f8c6e046d): Previously we  declared the 'focused_recipient' object
with an initial field of 'msg_type' and progressively added
fields by mutating the object(depending on the 'msg_type' ie. 'stream'
or 'private'). This was not TypeScript friendly and the compiler threw.
Now, we first fetch those fields into variables and then create the 'focused_recipient'
object depending on the value of 'msg_type' field.
> compose_fade: Convert module to TypeScript.

- corporate/tests/test_support_views.py
- corporate/views/support.py
- templates/corporate/support/remote_server_support.html
- web/styles/portico/activity.css
In the remote support view:
- Adds a deactivate button for remote servers that are active.
- Adds a reactivate button for remote servers that are deactivated.
**Notes**:
- Uses the utility functions in `stripe.py` for deactivating and reactivating the remote server.
- When deactivating, if a `ServerDeactivateWithExistingPlanError` is raised, then an error message is shown in the support view and the remote server is not deactivated.
- Note that remote servers (and associated remote realms) with a `CustomerPlanOffer` configured can be deactivated, but the support admin can still delete that configured plan when the remote server is deactivated.
- Positioned the buttons at the bottom of the remote server section and included the hostname on the button text. The button does have a max-width …
> remote-support: Add ability to deactivate and reactivate remote servers.

- requirements/common.in
- requirements/dev.txt
- requirements/pip.in
- requirements/pip.txt
- requirements/prod.txt
- https://github.com/zulip/zulip/pull/29234#discussion_r1516958975
For permanence, I copied these tags into the forks:
- https://github.com/zulip/pip/releases/tag/zulip-29074
- https://github.com/zulip/zoneinfo/releases/tag/zulip-24573
> requirements: Move pip and zoneinfo forks to zulip organization

- requirements/common.in
- requirements/dev.txt
- requirements/pip.in
- requirements/pip.txt
- requirements/prod.txt
> [8.x] requirements: Move pip and zoneinfo forks to zulip organization

- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
- corporate/tests/test_support_views.py
* PR to use `next_invoice_date` as the event_time in invoice_plan.
<details>
</details>
> corporate: Use `next_invoice_date` as the event_time in invoice_plan.

- scripts/setup/create-database
A user who somehow got an empty `zulip` database, but without a `zerver_messages` table in it, would get stuck in the installer at:
```
++ su postgres -c 'cd / && psql -v ON_ERROR_STOP=1 -Atc '\''SELECT COUNT(*) FROM zulip.zerver_message;'\'' zulip'
ERROR:  relation "zulip.zerver_message" does not exist
LINE 1: SELECT COUNT(*) FROM zulip.zerver_message;
^
+ records=
```
Treat a failure to select from `zerver_messages` as having 0 messages, and continue with the `DROP DATABASE IF EXISTS` / `CREATE DATABASE` that `create-db.sql` usually does.
Fixes: #29110.
> create-database: Treat "zulip" db without "zerver_messages" as empty.

- scripts/lib/upgrade-zulip-from-git
While this could be done previously by calling `upgrade-zulip-from-git --remote-url /srv/zulip.git`, the explicit argument makes this more straightforward, and avoids churning the `refs/remotes/origin/` namespace.
<details>
</details>
> upgrade-zulip-from-git: Provide a flag to use a local branch.

- web/src/typeahead_helper.ts
- web/tests/typeahead_helper.test.js
Earlier, streams were prioritised like this: pinned streams > subscribed streams > other streams, with message volume serving as the tie breaker.
Now we prioritise them like: stream being composed to > pinned unmuted streams > unpinned unmuted streams > pinned muted streams > unpinned muted streams > unsubscribed streams, with the same tie breaker.
Fixes: #20618.
<details>
</details>
> typeahead: Update activity score computation algorithm for streams.

- web/src/stream_create_subscribers.js
- web/src/stream_edit_subscribers.js
- web/src/user_group_create_members.js
- web/src/user_group_edit_members.js
- web/styles/dark_theme.css
- web/styles/input_pill.css
- web/templates/stream_settings/new_stream_user.hbs
- web/templates/stream_settings/stream_member_list_entry.hbs
- web/templates/user_display_only_pill.hbs
In the **create stream** UI and in stream , user/bot names have been transformed from plain links to pills. Additionally, names are now displayed as pills in Members tables for both new and existing groups in /#groups.
Handling of long names has been addressed to ensure reasonable presentation, especially on narrow screens. Long names are now appropriately abbreviated with "..." when necessary.
To display  avatar of user ```src``` key is added in respective files.
Fixes:  [#25724](https://github.com/zulip/zulip/issues/25724)
| **Dark Input Pill** | **Light Input Pill** |
| ------------------- | -------------------- |
| ![Dark Pill](https://github.com/zulip/zulip/assets/73663475/30e69bd9-a57c-4dce-af06-a263da56eab0) | ![Light Pill](https://github.com/zulip/zulip/assets/73663475/ef032b84-074 …
> stream_settings: Convert name to pills.

- web/src/rendered_markdown.ts
- web/styles/rendered_markdown.css
- web/templates/code_buttons_container.hbs
- web/templates/copy_code_button.hbs
- web/tests/rendered_markdown.test.js
This PR corrects the overlap problem described in #29165. Additionally, to shore up the code in this area, the PR:
1. Makes a containing template with logic for displaying the REPL button only when a code playground is available
2. Cleans up the JavaScript for readability
3. Sets a `position: relative` context on `.codehilite` blocks, to more accurately position the button-container overlay, and make the overlay's position agnostic toward whether or note the code block is inside a spoiler (issue #20712, whose fix introduced the overlap regression here)
4. Positions the REPL and Copy buttons to a similar righthand edge as can be seen on the similar Copy icon in message-source view
5. Prepares a flexbox-based layout for the REPL and Copy buttons, providing better target areas and reliable …
> rendered_markdown: Correct and modernize presentation of REPL and Copy buttons.

- web/src/compose_state.ts
- web/src/compose_validate.js
This function was introduced in
99d1c5a1f3e5e3f1ec71161f562e8eab1d718df7 and always has the opposite value from what its name suggests. It worked OK because the caller also expected it to have an incorrect value.
It's cleaner in this context to just use the `stream_id` helper, so just delete the bad code and use that.
Fix the docstring comment having been incorrectly pushed down while we're addressing this.
@evykassirer FYI.
> compose_state: Remove incorrect recipient_has_topics helper.

- help/configure-notification-bot.md
- help/include/sidebar_index.md
- Rename article "Configutre Notification Bot" -> "Configure automated notices".
- Reorganize article around types of notices.
- Other cleanup and clarifications.
Notes:
- Leaving actually moving the page for a follow-up.
- Filed #29272 while working on this.
Current: https://zulip.com/help/configure-notification-bot
<details>
<summary>
Updated
</summary>
</details>
> help: Rewrite article about automated notices.

- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
This was implemented instead as part of the `BillingSession` class with the `do_change_plan_type` method.
[CODE link](https://github.com/zulip/zulip/blob/d98580ab14452c838a58f389402bf9eca2e39582/corporate/lib/stripe.py#L4371-L4398)
```python
class RemoteServerBillingSession(BillingSession):
...
@override
@transaction.atomic
def do_change_plan_type(
self, *, tier: Optional[int], is_sponsored: bool = False, background_update: bool = False
) -> None:
if is_sponsored:
plan_type = RemoteZulipServer.PLAN_TYPE_COMMUNITY
self.add_customer_to_community_plan()
elif tier == CustomerPlan.TIER_SELF_HOSTED_BASIC:
plan_type = RemoteZulipServer.PLAN_TYPE_BASIC
elif tier == CustomerPlan.TIER_SELF_HOSTED_BUSINESS:
plan_type = RemoteZulipServer.PLAN_TYPE_BUSINESS
elif tier == …
```
> stripe: Remove unused do_change_remote_server_plan_type.

- web/src/tippyjs.ts
- web/templates/right_sidebar.hbs
- web/templates/tooltip_templates.hbs
The buddy list redesign introduced a new, more detailed tooltip, and neglected to remove the previous one.
> right-sidebar: Remove duplicate search people tooltip.

- web/src/compose_reply.js
- web/src/message_actions_popover.js
- web/tests/compose_actions.test.js
- web/tests/compose_ui.test.js
Whenever the user has text selected within a single message, and uses the hotkey to quote and reply, this selection will be quoted. In case of no selection or selection not within a single message, the entirety of the currently focused message will be quoted like before.
Similarly, when the user selects text within a single message, opens that message's actions menu, and clicks the "Quote and reply" option, the selected text will be quoted. In case of no selection or selection containing any other message/s, the entirety of the message whose menu was opened will be quoted like before.
When partially quoting a message, it is the markdown version of the selection that is quoted, hence preserving any formatting. Any other elements of the message, outside of the content, selected presumably …
> message_view: Allow quoting selected message text, via hotkey and menu.

- zerver/middleware.py
Refactor `parse_client` view to use `typed_endpoint` decorator instead of `has_request_variables`. This change improves code consistency and enhances codebase comprehension.
Fixes: 
<details>
</details>
> parse_client: Migrate has_request_variables to typed_endpoint.

- web/e2e-tests/drafts.test.ts
- web/e2e-tests/lib/common.ts
- web/e2e-tests/mention.test.ts
- web/src/bootstrap_typeahead.js
- web/src/composebox_typeahead.js
- web/tests/composebox_typeahead.test.js
In this PR, I have added functionalities in web/third/bootsrap-typeahead/typeahead.js which will improve topic typeahead beahviour as shown in video below.
Fixes: #29006 
Before changes:
[Before_making_typeahead_changes.webm](https://github.com/zulip/zulip/assets/113179991/c257abe4-833e-4a1a-80b0-eb3b4e1350ba)
After changes:
[After_making_typeahead_changes.webm](https://github.com/zulip/zulip/assets/113179991/e686daab-dbdf-4a3d-9d95-e5a794161de2)
<details>
Completed …
> Change topic typeahead behaviortypeahead: change topic typeahead behavior

- help/code-blocks.md
Fixes #29067. Replaces #29166.
The playgrounds were tested successfully by @laurynmm .
> help: Add example playground URL templates.

- zerver/views/development/email_log.py
Refactor `email_page` view to use `typed_endpoint` decorator instead of `has_request_variables`.
Fixes: 
<details>
</details>
> email_page: Migrate has_request_variables to typed_endpoint.

- web/src/bootstrap_typeahead.js
- web/src/compose_actions.js
- web/src/compose_recipient.js
- web/src/compose_tooltips.js
- web/src/drafts.ts
- web/src/scheduled_messages_popover.js
- web/styles/compose.css
- web/templates/compose.hbs
- web/templates/drafts_tooltip.hbs
- web/templates/popovers/send_later_popover.hbs
- web/templates/tooltip_templates.hbs
- web/tests/compose.test.js
- web/tests/compose_actions.test.js
- web/tests/drafts.test.js
Now we show the number of drafts that are addressed to the current recipient selected in the compose box, if any, in the Drafts button within parentheses (whether it is next to the Send button, or in the Send options popover).
Fixes: #28696.
At viewport widths where the word for drafts does not fit and trails off, the counter is still shown:
<details>
</details>
> compose: Show counter inside Drafts button for the current recipient.

- web/styles/inbox.css
- web/templates/inbox_view/inbox_row.hbs
This bug occurred when we added `INHERIT` visibility policy for topics but forgot to handle that case here.
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/inbox-view.20focus
> inbox: Add icon for default topic visibility policy.

- docs/subsystems/performance.md
Some people (including me) get confused reading this part, so this is a more simple way of delivering the same meaning. 
[revised message](https://chat.zulip.org/#narrow/stream/19-documentation/topic/Request.20Volume/near/1755646) from CZO
<details>
<summary>Rendered updated text : </summary>
</details>
see [updated doc](https://zulip--29260.org.readthedocs.build/en/29260/subsystems/performance.html#major-zulip-endpoints)
see [original doc](https://zulip.readthedocs.io/en/latest/subsystems/performance.html)
> docs: Revised performance.md for more clarity.

- web/src/settings_components.js
- web/tests/settings_org.test.js
Whenever a setting that needs confirmation to save is tweaked, and the save button is not visible, we scroll it into view, to ensure the user does not mistake it for an automatically saved change and misses saving their change.
Fixes: #29290.
Before toggling off the checkbox under the pointer:
After clicking:
<details>
</details>
> settings: Scroll save button into view when a change made needs saving.

- corporate/lib/stripe.py
- corporate/models.py
- corporate/tests/test_stripe.py
- corporate/views/portico.py
If the remote realm registered after the legacy plan on server ENDED, we never migrate the plan to the remote realm. So, we need to check the server of remote realm whenever we are check remote realm for legacy plan.
> upgrade: Fix allowed free trails for ended legacy plans on server.

- web/src/bootstrap_typeahead.js
- web/src/composebox_typeahead.js
- web/src/custom_profile_fields_ui.js
- web/src/pill_typeahead.js
- web/src/search.js
- web/src/settings_playgrounds.js
- web/tests/composebox_typeahead.test.js
- web/tests/pill_typeahead.test.js
- web/tests/search.test.js
Part of an effort towards converting the typeahead to typescript.
> typeahead: Convert from a jQuery plugin to a normal exported function.

- tools/test-js-with-node
- web/src/add_stream_options_popover.ts
- Migrated the `add_stream_options_popover.js` to TypeScript. 
- File extension is modified in test-js-with-node.
<details>
</details>
> types: Migrated add_stream_options_popover to TypeScript.

- web/src/stream_settings_ui.js
- web/src/user_group_edit.js
- web/tests/stream_settings_ui.test.js
Earlier in stream settings, clicking an unsubscribed stream in "all streams" and then clicking subscribed tab, the right side panel title and url hash would remain same as that of the unsubscribed stream.
This PR fixes the behaviour and resets the panel title and url hash to default.
This PR also fixes - 
- On searching any stream name, the right side panel also resets. The PR also fixes this behaviour of searching for stream names. The right side panel after this PR currently reloads only when the user selects an unsubscribed stream in "all streams" and then navigates to "subscribed" tab.
- In group settings, clicking a non participating group from "all groups" and then clicking "your group" would reset the right panel but the panel title would remain same as that of the non …
> stream-settings: Fix stream settings panel title not updating.

- web/src/compose_setup.js
- web/src/message_edit.js
In case of empty topics, only the compose box
topic is changed to remove the tick-prefix from it.
The function `with_first_message_id` may return
undefined when no message is found, instead of
throwing an error.
Fixes #29182
Fixes: 
Instead of an error, unresolving an empty topic and then sending a message in it now results in:
<details>
</details>
> Compose Box: Unresolve empty topics.

- web/src/hotkey.js
- web/src/inbox_ui.js
Earlier Shift + M shortcut is working only in messages to mute/unmute topic in messages part
This PR enables shortcut Shift + M work in recent conversations and the inbox view.It achieves this by utilizing the existing function toggle_topic_visibility_policy in user_topics_ui.The focused row message of the recent_view_ui is passed to mute/unmute the selected topic in the recent_view_ui, and the same process is applied to the inbox_ui but the logic of muting/unmuting the topic is kept in inbox_ui which uses function toggle_topic_visibility_policy in user_topics_ui.
The function toggle_topic_visibility_policy is called in both cases based on specific conditions to prevent the shortcut from affecting other parts of the page, thus avoiding errors.
Fixes: #27741  …
> shortcut : made Shift + M work in Recent conversations and Inbox

- web/src/message_scroll.js
Previously, if the user hovered over the "scroll to bottom" button as it was disappearing and did not move the mouse, the tippy would remain visible even though the button was hidden.
Presently, the tippy is explicitly destroyed when the transition animation finishes.
This issue was also attempted in #28680, but the approach there involved the use of a timer to destroy the tippy, which could have led to inconsistent behavior. My approach differs in that I used the `transitionend` event to detect when the button is completely hidden.
Fixes #28656
**Old behaviour**
[Screencast from 09.03.2024 17:22:41.webm](https://github.com/zulip/zulip/assets/104032457/089b501a-3573-4ab5-85d3-58df26c507ba)
**New bevahoiur**
[Screencast from 09.03.2024 …
> tooltip: Hide scroll button tooltip on transition

- web/src/alert_words.ts
- web/tests/alert_words.test.js
- web/tests/dispatch.test.js
If the overlapping alert words are configured , only the overlapped part of it seems to be highlighted.
The expected behaviour should be that anything which is a part of alert word should be highlighted.
This approach modifies the approach of processing alert words by sorting the words based on their size. 
It initially checks for the larger words and hence resolve the incorrect highlighting.
Fixes: #28415
Completion PR for - #28431
Previously - 
Presently - 
<details>
- [] Calls out remaining decisions and concerns. …
> alert_words: Fix incorrect highlighting of alert words.

- tools/release
9bd340957ff8 changed the headers; while we no longer store the changelog text in the Github release object, we should still output the changelog to STDOUT correctly.
<details>
</details>
> release: Fix changelog output.

- help/keyboard-shortcuts.md
- help/mute-a-topic.md
Current: https://zulip.com/help/mute-a-topic
Updated:
Note: I would have put the keyboard tip inside the Desktop/Web instruction block, but we're currently reusing that block for followed topics, and I'm not sure it's worth it to split out the two use cases.
---
Current: https://zulip.com/help/keyboard-shortcuts#for-a-selected-message-outlined-in-blue
Updated:
Note: It's a bit weird for this to be in the "For selected message" section, but probably OK? I removed random bits of description of what a muted topic is, since I think it's better to direct folks to the page that explains them in detail.
> help: Improve documentation for Shift+M keyboard shortcut.

- docs/translating/hindi.md
I fixed some typos in the Hindi translation guide. I think more issues/typos remain, but I'm not sure what's the correct translation, so I haven't fixed them yet.
> docs: Fix typos in the Hindi translation guide.

- web/src/message_list.js
Previously, when a stream is deleted and the deleted stream is looked up in the search bar, then an error is thrown.
This is because, when the StreamSubscription object of the deleted stream is fetched we try to access its properties -- invite_only and is_web_public, despite it being undefined.
This is fixed by accessing the properties only when the object is not undefined.
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/error.20when.20deleting.20a.20stream.20and.20searching.20for.20it)
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html …
> message_view: Fix error thrown on deleting stream and searching for it.

- corporate/lib/stripe.py
- corporate/tests/test_stripe.py
- templates/zerver/emails/internal_billing_notice.html
- templates/zerver/emails/internal_billing_notice.subject.txt
- templates/zerver/emails/internal_billing_notice.txt
- zerver/tests/test_push_notifications.py
**Updates**:
- Adds a line to the top of the `internal_billing_notice` email with the billing entity's display name.
- Makes sure all existing `internal_billng_notice` email subjects also include the billing entity's display name.
- Makes small updates to the notice text for some cases.
---
<details>
</details>
> remote-support: Include billing entity name in internal billing notice.

- web/src/buddy_list.ts
Discussion on [CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/User.20list.20behaviour/near/1761900)
Essentially, when `hide_headers` is true (when we're not showing a separate users list for the current narrow) we're actually still showing the "other users" section, just without its header. But the code that ensured that collapsed sections stay collapsed between narrows ended up hiding the list of users in the `hide_headers` view, which caused this bug. This adds some logic to make sure the list is always shown in these situations.
> buddy_list: Ensure users are visible when hide_headers is true.

- zerver/lib/test_helpers.py
- zproject/dev_urls.py
This makes it easier to browse to the docs in development mode, and more closely matches ReadTheDocs production.
<details>
</details>
> dev_urls: Make requests to /docs redirect to the index.

- docs/production/postgresql.md
- puppet/kandra/manifests/prometheus/postgresql.pp
- puppet/zulip/manifests/postgresql_client.pp
We require a `pg_dump` whose version matches the version of the server we are configured against (see 3a8b4b020509).  Installing the latest `postgresql-client` does not guarantee that we have such a binary present.
<details>
</details>
> puppet: Install the same version of postgres-client as the server.

- zerver/lib/test_classes.py
This gives more helpful error tracebacks from failing tests.
[Discussion](https://chat.zulip.org/#narrow/stream/49-development-help/topic/issue.20.2316206.20-.20Test.20failures.20.2B.20understanding.20.2B.20BC.20break.3F/near/1763630).
> test_classes: Skip OpenAPI validation on exceptions

- analytics/tests/test_counts.py
- zerver/actions/message_send.py
- zerver/actions/realm_settings.py
- zerver/actions/users.py
- zerver/data_import/import_util.py
- zerver/data_import/mattermost.py
- zerver/data_import/rocketchat.py
- zerver/data_import/slack.py
- zerver/lib/display_recipient.py
- zerver/lib/email_mirror.py
- zerver/lib/email_notifications.py
- zerver/lib/export.py
- zerver/lib/import_realm.py
- zerver/lib/message.py
- zerver/lib/message_cache.py
- zerver/lib/narrow.py
- zerver/lib/push_notifications.py
- zerver/lib/recipient_users.py
- zerver/lib/retention.py
- zerver/lib/test_helpers.py
- zerver/lib/users.py
- zerver/migrations/0182_set_initial_value_is_private_flag.py
- zerver/models/recipients.py
- zerver/tests/test_email_mirror.py
- zerver/tests/test_import_export.py
- zerver/tests/test_mattermost_importer.py
- zerver/tests/test_rocketchat_importer.py
- zerver/tests/test_users.py
- zerver/tests/test_zulip_update_announcements.py
- zilencer/management/commands/populate_db.py
Naming Convention Update: Changed Recipient's HUDDLE attribute to DIRECT_MESSAGE_GROUP
With VS Code's Search bar, I searched for all occurrences of "Recipient.HUDDLE" and manually changed it to "Recipient.DIRECT_MESSAGE_GROUP". Recipient_HUDDLE was left alone.
Fixes part of [#28640](https://github.com/zulip/zulip/pull/28640).
> Naming Convention Update: Changed Recipient's HUDDLE attribute to DIRECT_MESSAGE_GROUP.

- zerver/management/commands/register_server.py
Using --rotate-key without write access to the secrets file is currently quite painful, since you end up rotating your registration's secret with no local record of it; so effectively you lose your registration and need help from support. We should just prevent this failure mode.
> register_server: Check write access to secrets file when rotate_key.

- zerver/lib/push_notifications.py
- zerver/tests/test_push_notifications.py
Current solution: replace the long string for organisations that have notification body/content disabled (settings.PUSH_NOTIFICATION_REDACT_CONTENT set to true) with "New message".
Resolves #29152 
This solution replaces the previous redacted push notification body string ("\*This organization has disabled including message content in mobile push notifications\*") with "New message". This is done in favour of setting up a notification string encoding convention and frontend push notification parsing logic to italicise the new text. The redundant asterisks have also been removed based on the solution discussion CZO thread linked in the next comment.
<details> …
> notifications: Update string for redacted body notifications

- web/shared/src/typeahead.ts
- web/src/composebox_typeahead.js
- web/src/recent_view_ui.js
- web/tests/recent_view.test.js
- web/tests/typeahead.test.js
Fixes: Uptil now, the `query_matches_string` function always respected the order of words in the query string when matching a source string. This meant that for query "two one", the source string "one two three" would not be matched.
To make this more flexible, a default parameter `order_matters` has been added to the function. When it's passed in as false, the function returns true if each word in the query string matches the prefix of any distinct word in the source string, else it returns false.
The algorithm for computing this is quadratic in terms of the source word count so can be a little expensive but it is only currently used for searching topics in Recent Conversations, where the strings' length is limited by the max stream / topic name length allowed, so this should be …
> typeahead: Add option for word order not mattering for query matching.

- docs/development/overview.md
- docs/development/setup-advanced.md
- docs/development/setup-recommended.md
- docs/development/setup/vagrant-up.md
- docs/development/setup/vscode-vagrant.md
- docs/git/cloning.md
- tools/documentation.vnufilter
This updates the developer documentation page describing the recommended setup for development environments.  The goal is to make it easier to read by splitting out OS-specific instructions into separate tabs.
Tabbed documentation is already used in the Zulip Help Center, so this is a standard documentation UI element already being utilized.  However, it is not (to my knowledge) used anywhere in developer documentation yet.
Some of the design decisions I made while making this change:
- I utilized the `sphinx-design` package to provide the tabbing interface.
- Sphinx Design tabs can be made to "synchronize", meaning if I click "macOS" on one tab every tab on the page will switch to "macOS".  I enabled this feature, as I suspect most people will only select one OS and use that same OS …
> docs: Initial proof of concept of using tabs for each OS.

- docs/production/mobile-push-notifications.md
- help/mobile-notifications.md
Documentation follow-up to d9c5eb1280ddaf0f010e52e4584a4fe3822af995.
New help section in https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications:
> docs and help: Update text of no-content mobile notifications.

- web/src/message_list_tooltips.ts
frontend-lint was failing due to code style issue in `message_list_tooltips`.
This was introduced in fd3c7728fc807e96bc04d2886a8c2ffe9c61898b.
<details>
</details>
> message_list_tooltips: Fix code style issue.

- scripts/setup/apt-repos/zulip/custom.sh
This lets us avoid CI failures related to that repository's signing key having expired. See https://github.com/apache/arrow/issues/40744.
> scripts: Use Apache Arrow from Groonga repository.

- .github/workflows/production-suite.yml
This reverts commit 51773d55ed1b71bb1e679997e283109513d213ed.
Supposedly https://github.com/apache/arrow/issues/40744 is fixed.
> Revert "ci: Disable 8.0 upgrade suite to unbreak CI."

- web/src/user_events.js
- web/styles/dark_theme.css
- web/styles/settings.css
This is a follow-up for #28924 to fix css issues related to border around required custom-profile-fields.
This styling issue occurred after ```.field``` was renamed to ```.settings-profile-user-field``` to make it globally unique but it was left unchanged in some positions. See [here](https://github.com/zulip/zulip/pull/28924#discussion_r1532798749) for discussion.
|![Screenshot 2024-03-25 144143](https://github.com/zulip/zulip/assets/119798962/24fe7cc7-2f7f-4dd2-bba8-7f846d7aaf6a)|![Screenshot 2024-03-25 121331](https://github.com/zulip/zulip/assets/119798962/31996288-e7cf-4f3f-8b20-69a2a4d1c280)|
|![Screenshot 2024-03-25 144502](https://github.com/zulip/zulip/assets/119798962/9eb1cf00-aa1d-4a5a-aa09-dd1933ae4d75) …
> css: Fix css styling in "profile-settings-form".

- web/styles/app_variables.css
- web/styles/compose.css
- web/templates/compose.hbs
The icon is now bigger, slimmer in stroke width and has less horizontal spacing around it.
Fixes: part of #28792.
Before:
After:
Demo Design:
Before:
After:
Demo Design:
<details>
</details>
> compose: Redesign the  arrow between stream and topic.

- web/src/bootstrap_typeahead.js
- web/src/compose_ui.ts
- web/src/composebox_typeahead.js
- web/styles/zulip.css
- web/tests/compose_ui.test.js
- web/tests/composebox_typeahead.test.js
To increase the discoverability of the possibility of specifying the language for a code block, we trigger the language typeahead when code syntax is added using the code formatting button. A blank option is shown preselected in the typeahead, so that pressing enter will not mistakenly add a language to the code block.
We only trigger the typeahead on empty opening fences when added by the button, by setting a state variable to true when adding the syntax using the button, checking for this state when sourcing languages for the code typeahead, and then resetting the state variable to false.
Fixes: #29150.
typeahead: Don't hide typeahead on blur if focus is back in the input.
Now we don't hide the typeahead if the focus is back in the input within 150 ms. This is common when using the …
> compose: Trigger language typeahead on using code formatting button.

- puppet/kandra/manifests/prometheus/rabbitmq.pp
These default to off, because in situations with thousands of queues, consumers, and producers, they cause unreasonable overhead.  Our use case has few enough queues that we do want to be able to inspect them individually.
Enable per-object Prometheus metrics, per [1].
[1]: https://github.com/rabbitmq/rabbitmq-server/tree/78851828ecd1dddab2c890aaedfed7d6559dcd6e/deps/rabbitmq_prometheus#configuration
<details>
</details>
> kandra: Enable per-object metrics from rabbitmq.

- templates/zerver/landing_nav.html
> landing_navbar: Add `Semsee` case study link in mobile navbar.

- docs/translating/hindi.md
Recommend the use of formal second-person pronoun (आप) in the Hindi translation guide.
> docs: fix pronoun use in hindi translation guide.

- zerver/actions/create_user.py
- zerver/actions/message_flags.py
- zerver/actions/reactions.py
- zerver/lib/soft_deactivation.py
- zerver/lib/user_message.py
- zerver/tests/test_message_flags.py
Helps with #22396, by making it faster and not causing user-visible 500's during login.
<details>
</details>
> Make more use of `bulk_insert_all_ums`, removing race conditions

- web/src/activity_ui.ts
- web/src/sidebar_ui.ts
- web/src/tippyjs.ts
- web/styles/right_sidebar.css
- web/styles/zulip.css
- web/templates/navbar.hbs
- web/templates/tooltip_templates.hbs
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/Hide.20right.20sidebar
> Allow user to hide right sidebar on any width.

- puppet/kandra/templates/supervisor/conf.d/autossh_tunnels.conf.erb
927660a7b62f removed the munin deploys; this stops tunneling port 4949 back to the nagios host.
<details>
</details>
> kandra: Drop the munin port forward.

- web/src/message_scroll.js
This PR fixes the bug where the scroll button tooltip does not hide even after the button is dissapeared. This is because the fading animation confuses the `data-referrence-hidden` property of tippy.
This issue has been resolved in #29253. But presently the jquery wraps the native event object in it's own event object as a wrapper. Hence we would need to bypass the jquery wrapper to access a specific property.
This PR uses the `originalEvent` key to bypass the jquery wrapper and directly access the `propertyName` property from the jquery event object.
Fixes: #28656
<details> …
> tooltips: Hide scroll button tooltip under transition.

- zerver/tests/test_i18n.py
Updates the check email translation test for updated email text in confirm_new_email.html and onboarding_zulip_topics.html for current translated strings in German.
---
<details>
</details>
> i18n-test: Update translated strings in test_email_translation.

- puppet/zulip/files/cron.d/send_zulip_update_announcements
- puppet/zulip/manifests/app_frontend_once.pp
- zerver/lib/zulip_update_announcements.py
- zerver/tests/test_zulip_update_announcements.py
Commit 1: Group DM text update.
Commit 2: A daily cron job is configured to run the `send_zulip_update_announcements` management command.
<details>
</details>
> puppet: Add a daily cron-job to send zulip update announcements.

- web/src/sidebar_ui.ts
- web/styles/right_sidebar.css
- web/styles/zulip.css
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/Hide.20right.20sidebar
> right_sidebar: Hide underline from user-list toggle button in navbar.

- corporate/lib/stripe_event_handler.py
This decorator, among other things, transforms the "event" argument passed when calling the decorated functions into actually passing event.content_object.
So e.g. despite having a (before the decorator is applied) signature:
```
def handle_invoice_paid_event(stripe_invoice: stripe.Invoice, invoice: Invoice) -> None:
```
these are called passing an `Event` in the second arg when calling `handle_invoice_paid_event`:
```
handle_invoice_paid_event(stripe_invoice, event)
```
I found that kind of confusing because the `@error_handler` decorator didn't sound like something that would intervene in the arguments like that. So it feels helpful to rename it something with a less modest name, that makes it sound like it does more than just pure error-handling.
@amanagr @prakhar1144 Can either of you …
> stripe: Rename @error_handler decorator.

- web/src/pm_list.ts
- web/src/views_util.js
This PR fixes the behaviour of DM row highlight lingering on view changed.
PR fixes two sub issues
- When user navigates away from selected DM row to recents or inbox, the dm remains highlighted because `update_private_message` builds the dm list again from `pm_list_data` with `is_active` set as true for the last DM which should actually be set to false. `get_active_user_ids_string()` is returning last selected DM row since `message_lists.current` wasn't updating to return `undefined`. We fix it by updating `current` before updating the DM list again.
- When the user navigates away to other left sidebar narrows, the DM highlight lingers as the `handle_narrow_activated` isn't calling `update_private_message`. We fix it by updating the dm list again on unnarrowed.
Fixes: zulip#27698. …
> Fix DM row highlight linger in left siderbar.

- scripts/setup/apt-repos/zulip/zulip.pref
This package is replaced by libmagic1t64 1:5.45-3 for the Ubuntu 64-bit time_t transition, but hasn’t been deleted from the archive yet.
[Discussion](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/CI.20and.20production.20suite.20failure.20Ubuntu.2024.2E04/near/1768953).
> apt-repos: Disallow libmagic1 1:5.45-2 (Ubuntu 24.04)

- help/include/sidebar_index.md
- help/search-for-messages.md
- help/user-list.md
Current: https://zulip.com/help/search-for-messages
<details>
<summary>
Updated
</summary>
</details>
<details>
<summary>
User list (new page)
</summary>
</details>
Sidebar:
> Document user list + message search fixup

- zerver/decorator.py
- zerver/tests/test_decorators.py
Commit 807a4428f62f1cbb76d369b5581a0bcd71d62afc (#29485) deleted the corresponding tests in `TestAuthenticatedJsonPostViewDecorator`.
> test_decorators: Replace some deleted tests

- tools/test-js-with-node
- web/src/email_pill.ts
- web/src/input_pill.ts
- web/src/invite.ts
- web/styles/input_pill.css
- web/templates/invite_user_modal.hbs
- web/tests/input_pill.test.js
Replaces the "emails" text area in **invite new users modal** with an **input_pill** component.
Implemented email based pills utilizing the /web/src/input_pill.ts component. 
Features:
- Supports pasting comma separated emails
- Allow valid, non-duplicate emails
- Displays errored emails
Fixes: #29391
<details>
1. Invite new users modal initial state:
2. Input_pill component with pasted emails:
3. Success message on inviting:
4. On server side error:
</details>
<details> …
> invite_user_modal: Replaced email text_area with input_pill

- puppet/kandra/manifests/prometheus/rabbitmq.pp
puppet hard-fails if it can't find the binary to run in `$PATH`, so we need to make the `unless` short-circuit to false if puppet itself is not installed yet (as during initial installation).
<details>
</details>
> kandra: rabbitmqctl may not exist when applying the initial catalog.

- templates/zerver/login.html
- templates/zerver/register.html
- templates/zerver/reset_confirm.html
- web/src/common.ts
- web/templates/dialog_change_password.hbs
- web/tests/common.test.js
New keyboard accessibility for toggling between show and hide password for `/login` page, user can toggle by pressing `Enter` key while `<i>` is in focus 
**Details**
****templates/zerver/login.html**** :
added `tabindex="0"` which makes the element a part of the navigation flow, following the natural order in which element appear in the HTML code
****web/src/common.ts**** :
Added listener for `keyup` event.
**Manual Testing**
Tested manually on Chrome, Chromium and FireFox. …
> portico: Add keyboard accessibility for show/hide password icon.

- scripts/lib/setup-apt-repo
- scripts/setup/apt-repos/zulip/zulip.pref
[Discussion](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/libmagic1.20not.20available.20error.20on.20Ubuntu24/near/1771274).
> apt-repos: Temporarily work around Ubuntu 24.04 non-installable gnupg

- web/styles/compose.css
compose: Increase gap between Draft button's text and the counter.
compose: Adjust alignment and size of Drafts button at smaller widths.
The padding on the sides of the Drafts button is reduced from 5 to 3px
at smaller width, so that it's not right up against the textareas when
hovered.
The text is also aligned to the Send button's edge, like at larger
widths.
Fixes: [Issue report on CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/UI.20redesign.3A.20drafts.20button.20and.20counter.20in.20compose.20box/near/1769156)
Light:
Dark:
<details> …
> compose: Redesign Drafts button, especially at smaller widths.

- help/generate-integration-url.md
- templates/zerver/integrations/include/event-filtering-instruction.md
- templates/zerver/integrations/include/generate-integration-url.md
- web/src/integration_url_modal.ts
- web/styles/modal.css
- web/templates/settings/generate_integration_url_modal.hbs
- web/templates/settings/integration_events.hbs
Fixes: #27628
Following up on #25976, this PR introduces the ability to filter events when generating the URL for an incoming webhook integration. The new feature includes a checkbox UI for selecting events. The UI is designed with a one-column better readability and responsiveness, replacing the three-column  or two-column layout that was causing readability issues.
| **Dark Events** | **Light Events** |
| ------------------- | -------------------- |
| ![Dark events](https://github.com/zulip/zulip/assets/73663475/acc3e8be-3c81-4db6-a782-a5b27a5000ef) | ![Light events](https://github.com/zulip/zulip/assets/73663475/6a1b8a6c-91fa-4aed-b56b-47346ad99481) |
| **Before** | **After** |
| ------------------- | -------------------- |
| ![Dark …
> Implement Event Filtering for Webhook Integration URL Generation 

- corporate/views/installation_activity.py
- templates/corporate/activity/installation_activity_table.html
- templates/zerver/register.html
- web/e2e-tests/realm-creation.test.ts
- web/src/bundles/portico.ts
- web/src/portico/signup.ts
- web/styles/portico/billing.css
- web/styles/portico/portico.css
- web/styles/portico/portico_signin.css
- web/webpack.assets.json
- zerver/actions/create_realm.py
- zerver/forms.py
- zerver/lib/test_classes.py
- zerver/models/realm_audit_logs.py
- zerver/views/development/registration.py
- zerver/views/registration.py
@timabbott what do you think about the approach here?
> Collect how they know about Zulip data in new org registration.

- web/src/settings_users.js
- web/templates/popovers/user_card/user_card_popover_manage_menu.hbs
- web/templates/settings/admin_user_list.hbs
Organization settings: add links to manage deactivated users.
Display manage this user in the three-dot menu on the user card regardless of user is_active. Similarly, display edit user icon in deactivated users list. Do not hide edit button when user is deactivated.
Fixes: #29486 
UI Changes:
<details>
</details>
> Add links to manage deactivated users

- corporate/tests/test_stripe.py
- scripts/lib/zulip_tools.py
- tools/setup/build_timezone_values
- zerver/lib/email_notifications.py
- zerver/lib/export.py
- zerver/lib/push_notifications.py
- zerver/lib/timezone.py
- zerver/lib/validator.py
- zerver/signals.py
- zerver/tests/test_new_users.py
- zerver/tests/test_timezone.py
- zerver/tornado/event_queue.py
- zerver/worker/queue_processors.py
Bumping `target-version = "py38"` to `"py310"` in `pyproject.yaml` will cause Ruff to enable new rules, fixes, and formatting. This is a subset that doesn’t include mass changes. Since we have not yet bumped `target-version`, they’re not yet lint-enforced.
> Small bits of Python 3.8 → 3.10 modernization

- web/src/user_card_popover.js
Closing overlay before switching narrow takes sets the previous hash of the new narrow incorrectly, which results in browser back taking user the previous narrow instead of opening the overlay again.
Fixed by switching narrow before closing the overlay.
> settings_overlay: Fix browser back not working as expected.

- api_docs/incoming-webhooks-overview.md
- templates/zerver/integrations/include/congrats.md
- templates/zerver/integrations/include/event-filtering-additional-feature.md
- templates/zerver/integrations/include/generate-integration-url.md
- templates/zerver/integrations/include/generate-webhook-url-basic.md
- templates/zerver/integrations/include/git-branches-additional-feature.md
- templates/zerver/integrations/include/webhooks-url-specification.md
- web/styles/portico/integrations.css
- web/styles/portico/markdown.css
- zerver/webhooks/airbrake/doc.md
- zerver/webhooks/azuredevops/doc.md
- zerver/webhooks/gitlab/doc.md
Proposal based on #29348. My changes are in a separate commit.
Relevant [CZO conversation](https://chat.zulip.org/#narrow/stream/19-documentation/topic/updating.20event.20filtering.20in.20integration.20docs.2C.20.2328294/near/1759249).
These changes use the GitLab, Airbrake and Azure Devops integrations as examples.
<details>
<summary>Updated GitLab integration doc</summary>
[Current documentation](https://zulip.com/integrations/doc/gitlab)
</details>
<details>
<summary>Updated Airbrake integration</summary>
[Current documentation](https://zulip.com/integrations/doc/airbrake)
</details>
<details>
<summary>Updated Azure Devops integration</summary>
[Current documentation](https://zulip.com/integrations/doc/azuredevops)
</details>
<details>
<summary>API …
> integrations: Restructure documentation pages.

- templates/zerver/emails/find_team.html
- templates/zerver/emails/find_team.subject.txt
- templates/zerver/emails/find_team.txt
- templates/zerver/find_account.html
- zerver/tests/test_i18n.py
- zerver/tests/test_signup.py
- zerver/views/registration.py
Previously, the emails which weren't connected to a Zulip account were ignored but now they recieve an email stating their email isn't connected to a Zulip account
Fixes part of #3128
Recording:
https://github.com/zulip/zulip/assets/78016781/259d6eb4-d300-47c8-821d-cbbe6befe03b
Zulip-Cloud:
Self-hosted:
> find_account: Send emails to non zulip accounts

- puppet/zulip/manifests/postgresql_backups.pp
Puppet 6.x and above moved the `cron` resource type out of core Puppet, into a "cron_core" module[^1]; thus Debian 12 and Ubuntu 24.04, with the newer Puppet, fail to compile if backups are configured:
```
Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'cron' (file: /home/zulip/deployments/current/puppet/zulip/manifests/postgresql_backups.pp, line: 32, column: 3) on node zulip.example
```
However, we only use the `cron` package to assert that we no longer use it, for installs which are coming up from Zulip 4.x where it _was_ used.
Since Zulip 4.x does not support Ubuntu 24.04 or Debian 12, having Puppet >= 6.x means that the cron must have been previously removed in a previous upgrade, and we can skip the block.
In `main`, this block is …
> puppet: Only use the cron resource on Puppet 5.x.

- puppet/zulip/manifests/app_frontend_base.pp
- puppet/zulip/manifests/postgresql_backups.pp
- puppet/zulip/manifests/postgresql_base.pp
- puppet/zulip/manifests/profile/rabbitmq.pp
- puppet/zulip/manifests/supervisor.pp
It is not possible to have upgraded from 4.x to this version without having run puppet at least once, since there are no shared OS versions in between them.  Remove these `absent`/`purged` blocks which we know to have already been run.
----
Compare #29572 in `8.x`.
<details>
</details>
> puppet: Remove all purged/absent blocks known to have run already.

- zerver/lib/zulip_update_announcements.py
- zerver/tests/test_zulip_update_announcements.py
* Update cron job to run daily instead of hourly.
* Wait for 24 hours after sending group DM to admins to publish Zulip updates in stream.
<details>
</details>
> zulip_news: Wait for one day after sending group DM if stream is set.

- templates/corporate/self-hosting.html
Current: https://zulip.com/self-hosting/
<details>
<summary>
Updated
</summary>
</details>
> portico: Clarify wording and policies on /self-hosting.

- zerver/migrations/0501_delete_dangling_usermessages.py
The `zerver/0501_delete_dangling_usermessages` was backported to the `8.x` branch (and the 8.3 release) in 3db1733310dd.  However, because `main` contained migrations which `8.x` did not, it was backported with a different `dependencies`:
```
dependencies = [
("zerver", "0496_alter_scheduledmessage_read_by_sender"),
]
```
...as opposed to in `main`:
```
dependencies = [
("zerver", "0500_realm_zulip_update_announcements_stream"),
]
```
This causes upgrades from 8.3 to `main` to fail:
```
django.db.migrations.exceptions.InconsistentMigrationHistory:
Migration zerver.0501_delete_dangling_usermessages is applied before
its dependency zerver.0500_realm_zulip_update_announcements_stream on
database 'default'.
```
Adjust the dependencies in `main` to match those in `8.x` where many deploys will …
> migrations: Match dependencies from 8.x branch.

- templates/zerver/emails/find_team.txt
- zerver/tests/test_signup.py
Follow-up to #28598. The HTML version of this email was updated in commit 5410df2a7bc745.
Now both the HTML and text emails when no Zulip Cloud accounts are found read:
> You have requested a list of Zulip accounts for this email address.
> Unfortunately, no Zulip Cloud accounts were found.
---
<details>
</details>
> emails: Update text version of find team email to match HTML version.

- zerver/openapi/python_examples.py
- zerver/openapi/zulip.yaml
This PR makes small revisions in "/invites" API documentation.
Fixes: 
<details>
</details>
> api_docs: Fix "/invites" enpoint documentation.

- scripts/setup/apt-repos/zulip/zulip.pref
> apt-repos: Disallow libmagic1 1:5.45-2 (Ubuntu 24.04) again

- web/src/invite.ts
- web/templates/right_sidebar.hbs
- web/templates/settings/invites_list_admin.hbs
This PR updates the user invitation terminology by :
- Renaming "Invite more users" -> "Invite users to organization" in the right sidebar.
- Renaming "Invite users to Zulip" -> "Invite users to organization" in the modal title.
Fixes #29582
**right sidebar:**
**user invitation modal:**
<details>
</details>
> right_sidebar: Rename invite modal label.

- web/src/people.ts
- web/tests/people.test.js
In `composebox_typeahead`, it is completely possible to call `people.get_mention_syntax` for a wildcard mention, which will not have a `user_id`.
Updates `get_mention_syntax` to not raise a blueslip error if the mention syntax is for a wildcard mention.
Adds "topic" to the array of possible wildcard mention strings.
Tightens the types for the parameters for `get_mention_syntax`, by setting `user_id` to be number or undefined, and by setting `silent` to default to false (which is expected in a number of modules where this function is called).
```console
$ git grep get_mention_syntax web/src
web/src/compose_reply.js:    const mention = people.get_mention_syntax(message.sender_full_name, message.sender_id);
web/src/compose_validate.ts:    const silent_mention_text = …
```
> people: Update get_mention_syntax to better account for wildcards.

- tools/check-frontend-i18n
Fixes: [CZO](https://chat.zulip.org/#narrow/stream/6-frontend/topic/ci.3A.20broken.20link.20in.20tools.2Fcheck-frontend-i18n)
<details>
</details>
> tools: Fix broken link in check-frontend-i18n

- puppet/zulip/templates/supervisor/zulip-once.conf.template.erb
- puppet/zulip/templates/supervisor/zulip.conf.template.erb
The process of running Django's built-in database and config checks can be very heavy-weight, potentially taking multiple seconds:
```
$ hyperfine './manage.py print_initial_password iago@zulip.com'  './manage.py print_initial_password iago@zulip.com --skip-checks'
Benchmark 1: ./manage.py print_initial_password iago@zulip.com
Time (mean ± σ):      4.943 s ±  0.722 s    [User: 4.434 s, System: 0.311 s]
Range (min … max):    4.415 s …  6.835 s    10 runs
Benchmark 2: ./manage.py print_initial_password iago@zulip.com --skip-checks
Time (mean ± σ):      1.786 s ±  0.113 s    [User: 1.598 s, System: 0.162 s]
Range (min … max):    1.576 s …  1.999 s    10 runs
Summary
'./manage.py print_initial_password iago@zulip.com --skip-checks' ran
2.77 ± 0.44 times faster than './manage.py …
```
> django: Skip running config and database checks on process start.

- web/src/message_list_tooltips.ts
- web/src/message_lists.ts
- web/src/server_events_dispatch.js
- web/styles/app_variables.css
- web/styles/dark_theme.css
- web/styles/message_row.css
- web/styles/print.css
- web/styles/zulip.css
- web/templates/message_body.hbs
- web/tests/dispatch.test.js
- web/tests/lib/zjquery.js
- web/tests/popover_menus_data.test.js
In addition to cleaning up some structural and CSS matters around message timestamps, this PR calculates a shared width for all timestamp columns, based on the largest possible timestamp for a given language/locale and time format (12 and 24).
This ensures that the timestamp column is always the same size between messages, leading to more consistent appearance of the star icon and hover controls.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/Star.20icon.20alignment/near/1660398)
Fixes: #26970
| --- | --- |
| ![timestamps-before](https://github.com/zulip/zulip/assets/170719/be0627b5-33c8-4cc1-9fda-4bd3a2a75041) | ![timestamps-after](https://github.com/zulip/zulip/assets/170719/aa7a8362-9f75-4a30-bd77-286fdf81e …
> message_body: Calculate width of timestamp column.

- web/src/util.ts
- web/tests/util.test.js
92fa9ee78c78 switched this regex to match the server-side regex, but Safari < 16.4 does not support look-behind in regexes.
Switch to matching on start-of-string or a positive character class.
<details>
</details>
> util: Do not use look-behind in wildcard mention checks.

- api_docs/changelog.md
- api_docs/message-formatting.md
- api_docs/sidebar_index.md
- version.py
- web/src/composebox_typeahead.js
- web/src/markdown.ts
- web/src/people.ts
- web/src/util.ts
- web/tests/composebox_typeahead.test.js
- web/tests/markdown.test.js
- web/tests/people.test.js
- web/tests/typeahead_helper.test.js
- web/tests/util.test.js
- zerver/lib/mention.py
- zerver/tests/test_message_notification_emails.py
- zerver/tests/test_soft_deactivation.py
Adds "channel" as one of the stream wildcard mention strings on the backend and implements it on the web app frontend.
Still to do as part of (or follow-ups to) these changes:
- Remove "stream" from typeahead, but still support it in the web app if someone manually types it in the compose box.
- Update the help center docs (replace "stream" with "channel" in the stream wildcard mentions).
- Figure out API changelog update - currently the wildcard strings are not documented in the API docs directly.
---
Part of the work towards #28468 (Rename "stream" to "channel").
Relevant CZO discussions:
- [#api design - stream/channel rename: stream wildcard mention](https://chat.zulip.org/#narrow/stream/378-api-design/topic/stream.2Fchannel.20rename.3A.20.40stream.20wildcard.20mention/near/1752174)
- …
> wildcard-mentions: Add "channel" as a stream wildcard option.

- zproject/computed_settings.py
`SHA1PasswordHasher` will be [removed in Django 5.1](https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-5-1). `MD5PasswordHasher` will [remain](https://github.com/django/django/pull/15871#issuecomment-1193110581) for exactly this purpose of [speeding up tests](https://docs.djangoproject.com/en/5.0/topics/testing/overview/#password-hashing).
Use `MD5PasswordHasher` by default, but leave `SHA1PasswordHasher` in the list for compatibility with test databases that have already been generated.  Once some other change forces test databases to be rebuilt, we can remove `SHA1PasswordHasher`.
(For my future reference, my current `db_files_hash_for_test` is `4e8367bf77e8466c407fffc9c5fb325463b8e441`.)
> tests: Downgrade deprecated SHA1PasswordHasher to MD5PasswordHasher

- web/src/click_handlers.js
- web/src/compose_popovers.js
- web/src/dropdown_widget.ts
- web/src/gear_menu.js
- web/src/left_sidebar_navigation_area_popovers.js
- web/src/message_actions_popover.js
- web/src/message_list_tooltips.ts
- web/src/personal_menu_popover.js
- web/src/popover_menus.ts
- web/src/scheduled_messages_popover.js
- web/src/topic_popover.js
- web/src/user_topic_popover.js
When user is trying to open a modal after clicking on a button in a popover, we call `popovers.hide_all()` before opening the modal which hides the popover but since the event handler call isn't finished running yet, we call `instance.hide()` again resulting in tippy throwing errors that this could be a memory leak.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/minor.20bug.20in.20deleting.20messages
> popover_menus: Fix event handler trying to hide a hidden popover.

- api_docs/construct-narrow.md
- zerver/openapi/zulip.yaml
``is:unread`` is an important feature which offers an alternative to searching in narrows, and I have included it in documentation on [personal message flags](https://zulip.com/api/update-message-flags-for-narrow) and [narrow construction](https://zulip.com/api/construct-narrow) related to narrows.
Here are pictures of what they would look like now:
fixes #28328.
> docs: Update documentation on narrows to include ``is:unread``

- web/src/typeahead_helper.ts
- web/tests/typeahead_helper.test.js
typeahead: Redesign the function `compare_people_for_relevance`.
We make the following changes:
- Remove the dm partnership check before calling the comparator passed by the caller, and instead have the more thorough `compare_by_pms` be the final tie breaker. This deprioritization of dms fixes the bug where dm partners would be prioritized even if they had not participated in a stream conversation over recent senders who are not dm partners.
- Make the passed comparator optional, since the tie breaker is same as the comparator that was passed so far for dms, and only pass it in case of a stream conversation.
tests: Add missing setup to typeahead_helper tests passing as a fluke.
typeahead: Add check for all time dm partners to `compare_by_pms`.
For the rare case where there is no recent …
> typeahead: Redesign the function compare_people_for_relevance.

- web/src/settings_profile_fields.js
- web/third/marked/lib/marked.js
`String.prototype.replace` and `String.prototype.replaceAll` interpret certain sequences such as `$$` within a string provided as the replacement argument. Avoid this interpretation by providing a function.
> web: Fix usage of .replace with variable replacement

- web/src/click_handlers.js
- web/src/inbox_ui.js
- web/src/recent_view_ui.js
Fixes #17935
This allows users to ctrl + click a link to open it in new tab without changing the state in the current tab.
> click_handlers: Don't handle clicks with meta / ctrl keypress.

- web/styles/compose.css
- web/styles/input_pill.css
We set `min-width: 0` on all nested flex containers for pills, not just the pills label, which allows the label content to collapse as much as needed with ellipsis when overflowing.
Fixes: #27205.
Before:
After:
<details>
</details>
> css: Make pills' content collapse according to width available.

- web/src/hash_util.ts
Replaces the `Term` type in `hash_util.ts` with the `NarrowTerm` type that is defined in `state_data.ts`.
---
<details>
</details>
> hash-util: Use NarrowTerm type from state_data.

- web/src/settings_components.ts
- web/tests/settings_org.test.js
In an unsaved state, when focus is in a textarea or an input of type text, we don't yet scroll the save button into view to not interrupt the user's typing. When the input / textarea loses focus, we scroll then if needed, triggered via the `change` event.
Fixes: [issue reported on CZO here](https://chat.zulip.org/#narrow/stream/9-issues/topic/.22Save.20changes.22.20in.20settings.20often.20missed.20when.20out.20of.20view/near/1768180)
<details> …
> settings: Do not scroll to save button when typing in textarea / input.

- web/src/admin.js
- web/src/people.ts
- web/src/settings_users.js
- web/styles/settings.css
- web/templates/settings/deactivated_users_admin.hbs
- web/templates/settings/user_list_admin.hbs
- web/tests/people.test.js
Fixes #18617.
The role filter is added to both active and deactivated user list. The original plan was to introduce a multi select checkbox dropdown for the roles, but since that component is not ready yet, we will use the dropdown component for the first iteration.
To accomodate multiple filters, we have used an approach similar to the one in recent_view_ui.js where we use dropdown callback function and on("input") event on text search to set the filter value in memory. The predicate functions uses these filters. See this [CZO chat](https://chat.zulip.org/#narrow/stream/6-frontend/topic/Allow.20multiple.20filters.20in.20ListWidget) for more details.
There was an existing inactive PR linked to this issue, that PR was not used since it was introducing business logic in ListWidget directly …
> settings_users: Add role based filter to the active and deactivated user list page.

- scripts/setup/apt-repos/zulip/zulip.pref
This reverts commit 13e28fc3aceccfd43595ed246291ce30a10d8a8a.
> Revert "apt-repos: Disallow libmagic1 1:5.45-2 (Ubuntu 24.04) again."

- puppet/kandra/templates/supervisor/conf.d/autossh_tunnels.conf.erb
By default, autossh writes to syslog; setting AUTOSSH_DEBUG is the only way to produce output to STDERR.  Timestamp that and log that to the logfile, making the logs perhaps useful.
<details>
</details>
> kandra: Log and timestamp autossh output.

- help/change-a-users-role.md
- help/find-administrators.md
- help/include/sidebar_index.md
- help/include/view-users-by-role.md
- help/roles-and-permissions.md
- help/user-list.md
Follow-up to https://github.com/zulip/zulip/pull/29597.
<details>
<summary>
Roles and permissions
</summary>
Current: https://zulip.com/help/roles-and-permissions
</details>
<details>
<summary>
New page: Find administrators
</summary>
</details>
Notes:
- I didn't document the Deactivated users filter. It seems fine to me to leave that undocumented, and let users discover it when viewing that panel.
> Document new roles filer for Users table

- api_docs/changelog.md
- version.py
- zerver/models/messages.py
- zerver/openapi/zulip.yaml
- zerver/tests/test_message_send.py
- zerver/tests/test_scheduled_messages.py
- zerver/tests/test_typing.py
- zerver/views/message_send.py
- zerver/views/scheduled_messages.py
- zerver/views/typing.py
For endpoints with a type parameter to indicate whether a message is a direct or stream message, adds support for passing "channel" as a value for stream messages.
Part of stream to channel rename project, see [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/438-release-management/topic/rename.20.22stream.22.20to.20.22channel.22.20project.2C.20.2328468/near/1758864).
<details>
<summary>API update</summary>
</details>
<details>
<summary>Typing endpoint</summary>
[Current documentation](https://zulip.com/api/set-typing-status#parameter-type)
</details>
<details>
<summary>Send message endpoint</summary>
[Current documentation](https://zulip.com/api/send-message#parameter-type)
</details>
<details>
<summary>Schedule message …
> message-type: Add support for "channel" as value for type parameter.

- zerver/management/commands/unarchive_stream.py
> unarchive_stream: Prevent unarchiving a stream in the wrong realm.

- web/src/attachments_ui.ts
- web/src/channel.ts
- web/src/dialog_widget.ts
- web/src/settings_exports.ts
- web/src/settings_linkifiers.js
- web/src/settings_playgrounds.ts
- web/src/settings_ui.ts
- web/src/settings_users.js
- web/src/user_profile.js
[CZO discussion thread ](https://chat.zulip.org/#narrow/stream/6-frontend/topic/setting_ui.20do_settings_change)
Reason for 2nd Commit:
Since the type of request_method(`AjaxRequestHandler`) has
been extended in the previous commit.Consequently the 'data'
field of '`request_method`' has to be typed such that it
satisfies this change.
Because `request_method`'s type can also be `'typeof patch`' which
does not accept undefined '`data`' field, I haved '`omit`'-ted
'`undefined`' from 'data's type in function signature to satisfy
TypeScript.
Now ,in support of the changes I have made to two different function
sign(namely `setting_ui.do_settings_change` & `dialog_widget.submit_api_request`)
I am stating some points about `data` field inside these respective
function signs. …
> channel: Use TypeScript unions for AjaxRequestHandler.

- tools/test-js-with-node
- web/src/information_density.ts
- web/src/server_events_dispatch.js
- web/src/ui_init.js
- web/styles/app_variables.css
- web/tests/dispatch.test.js
- web/tests/lib/events.js
This PR provides the JavaScript and CSS variables to set the `font-size` and `line-height` based on values stored in the database. That happens in development only, both when the UI is initialized, and when either value is adjusted from preferences.
Note that this PR does not yet utilize the CSS variables set and adjusted here.
<details>
</details>
> info_density: Set font size, line height vars in dev.

- zerver/webhooks/github/view.py
>GSoC`2024 participant.
Modified the 'get_zulip_event_name' function to
differentiate between 'opened' and 'updated' actions for pull requests within the 'pull_request' event type. Created separate event types for 'opened_pull_request' and 'updated_pull_request'. Updated the 'EVENT_FUNCTION_MAPPER' dictionary to include handlers for these new event types. Adjusted the'get_opened_or_update_pull_request_body' function to handle both 'opened' and 'updated' actions appropriately.
Fixes #29594.
<details> …
> integration: Split 'opened_or_update_pull_request' event type into multiple event type.

- web/src/compose_recipient.ts
Previously, when stream settings were updated, without opening the compose box, assertion error were thrown.
This error was a result of a regression in compose_recipient, due to an extra assert statement added during its typescript migration in 25ff0d441858aa5c8f0bf51b47ad2a872141c262.
This is fixed by removing the statement.
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/updating.20stream.20settings.2E/near/1776498)
<details>
</details>
> stream_settings: Fix error on stream setting update when compose closed.

- zerver/actions/create_user.py
- zerver/lib/scim.py
- zerver/tests/test_scim.py
- zproject/settings_types.py
When an organization (without open ability for anyone to join) invites a guest user, the invitation prompts allows them to choose whether the guest should be added to default streams or not. This is useful, because since we don't have per-role default streams configs, they may want default streams to be for full Members.
SCIM provisioning doesn't have this control, since a newly provisioned user gets created via a direct do_create_user call, thus adding them to the organization's default streams, with no workaround possible aside of just getting rid of default streams in the organization.
To make provisioning guests in such an organization usable, we add a simple config option to create them with no streams. It's configured by adding
```
"create_guests_without_streams": True
```
to the …
> scim: Add config option to disable initial streams for guests.

- web/src/dialog_widget.ts
- web/src/invite.ts
- web/templates/dialog_widget.hbs
We now always show the scrollbar in invite modal body if it is scrollable. This avoids confusion and makes it clear that some options are out of view.
Fixes: #29393.
| ![image](https://github.com/zulip/zulip/assets/133781250/6f074c1d-6fca-4fe4-be0f-5bf42283187e) | ![image](https://github.com/zulip/zulip/assets/133781250/944c023d-04a0-46e7-a466-6d8ffacb499c) | 
<details> …
> invite_user_modal: Always show scrollbar.

- web/src/settings_users.js
Fixes #29687.
We could have used Array.reverse() before running Array.map() in the previous code, but that would loop through the array twice. That's why switched to a for loop here.
<details>
<summary>Role filter dropdown</summary>
</details>
<details>
<summary> Role filter dropdown on users list page along with active filters and their results</summary>
</details>
<details>
<summary>Role filter dropdown on deactivated users list page along with active filters and their results </summary>
</details>
**Self-review checklist:**
<details> …
> settings_users: Reverse order of roles in role filters.

- docs/overview/changelog.md
- puppet/zulip/files/hooks/post-deploy.d/send_zulip_update_announcements.hook
- puppet/zulip/manifests/app_frontend_once.pp
- puppet/zulip/manifests/hooks/send_zulip_update_announcements.pp
- zerver/lib/zulip_update_announcements.py
- zerver/management/commands/send_zulip_update_announcements.py
- zerver/tests/test_zulip_update_announcements.py
[CZO Discussion:](https://chat.zulip.org/#narrow/stream/101-design/topic/New.20feature.20notification.20system.20.2328604/near/1771998)
> What I'm imagining for self-hosted servers, in that in a post-9.0 release, they'll already have the DMs, and for the 9.0 release, we can just offer a documented option in the management command for how to skip the delay, and put that in the "upgrade notes" section of the changelog.
For 9.0 upgrade:
* post upgrade tooling will send the group DM.
* Upgrade notes suggests to run `./manage.py send_zulip_update_announcements --skip-delay` to send updates immediately. (Stream should be configured)
<details><summary>Upgrade notes</summary>
</img>
</details> 
For post 9.0 upgrades:
* post upgrade tooling will send the update messages.
<details> …
> hooks: Add a send_zulip_update_announcements post deploy hook.

- web/src/compose_actions.ts
- web/tests/compose_actions.test.js
When a long message is restored from a draft (or scheduled messages), its end, and the cursor placed there, used to be out of view, giving the impression that the message was not focused, when it actually was.
This is fixed by always scrolling the cursor into view.
Fixes: [CZO issue thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/position.20when.20restoring.20draft/near/1756940)
<details>
</details>
> compose: Scroll cursor at message's end into view when restoring draft.

- web/src/message_list_view.js
- web/src/message_viewport.ts
Now whenever the bottom of the feed is visible, we always scroll to the message/s just sent by the current user, updating the selected message if necessary.
Scroll behaviour for messages sent by other users remains unchanged.
Fixes: #23298.
Before sending:
New message scrolled into view on sending:
<details>
</details>
> message_view: For message sent by current user, always scroll into view.

- web/src/invite.ts
- web/src/tippyjs.ts
- web/styles/app_components.css
- web/styles/modal.css
- web/templates/invite_user_modal.hbs
This PR replaces the radio buttons in invite user modal with tab component.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/user.20research.3A.20invite.20modal/near/1762354)
Fixes #29392
<details>
When the user is not allowed to generate invite links
When the user is not allowed to send email invitations
On very narrow widths:
</details>
<details>
</details>
> popovers: Convert invite modal to tabbed format.

- zerver/tests/test_create_video_call.py
- zerver/views/video_calls.py
When a Zoom organization is configured to always require authentication in meetings, not generating a meeting password implies the use of the waiting room feature, which is annoying for example when sending a DM to a colleague with a Zoom link.
This changes how we call the Zoom API to have Zoom generate a meeting password, using the settings in the user's Zoom account. The password will be included in the meeting link, users won't have to type it in manually. Example of the newly generated URLs:
```
https://DOMAIN.zoom.us/j/MEETING_NUMBER?pwd=ENCODED_PASSWORD
```
Fixes: https://chat.zulip.org/#narrow/stream/137-feedback/topic/default.20password.20for.20zoom
<details> …
> Add a default password to Zoom meetings

- zerver/lib/push_notifications.py
- zilencer/views.py
The IntegrityError shows up in the database logs, which looks unnecessarily concerning.  Use `ON CONFLICT IGNORE` to mark this as expected, especially since the return value is never used.
<details>
</details>
> push_notifications: Use ignore_conflicts, over catching IntegrityError.

- puppet/zulip/files/postgresql/pg_backup_and_purge
Without `FIND_FULL`, `wal_g delete before ...` will fail, rather than delete a base backup which is needed by the delta backups after it. By passing `FIND_FULL`[^1], we tell it explicitly that we're OK preserving files before the specified one, as long as they are necessary for the delta chain.
[^1]: https://github.com/wal-g/wal-g/blob/master/docs/README.md#delete
<details>
</details>
> pg_backup_and_purge: Properly preserve needed base backups.

- zerver/actions/reactions.py
- zerver/lib/message.py
- zerver/lib/push_notifications.py
- zerver/views/message_edit.py
f92d43c6908e added uses of `@overload` to probide multiple type signatures for `access_message`, based on the `get_user_message` parameter.  Unfortunately, mypy does not check the function body against overload signatures, so it allows type errors to go undetected.
Replace the overloads with two functions, for one of which also returns the usermessage.  The third form, of only returning if the usermessage exists, is not in a high-enough performance endpoint that a third form is worth maintaining; it uses the usermessage form.
Fixes: https://github.com/zulip/zulip/pull/29409#discussion_r1536029108
<details> …
> messages: Remove use of @overload in access_message.
