zulip/zulip

web/src/message_helper.js, web/src/message_list_view.js, web/tests/dispatch.test.js, web/tests/message_events.test.js
Prerequisite to [PR #29109 ](https://github.com/zulip/zulip/pull/29109)
Clean reactions and set `message_reactions` in `process_new_message`. Earlier, `message_reactions` was being set
after the predicate for the narrow was built,
as a result functions that require the reactions while building the predicate.
Also attempted to clean up and simplify  `type Message`, but ran into tsc lint errors.
Please give feedback on how relevant changes that can be made to simplify the `type Message` with or without affecting the other functions that use `Message`
=> Clean message reactions during initial processing.

web/src/invite.ts
"When a user invites someone to join Zulip and then clicks on the invite button,a success
message is displayed in a popover. However, the current placement of the success message
at the top of the popover may not be easily visible to the user, making it unclear whether
the invitation has been sent successfully.
To make the confirmation banner visible, changed the code to  scroll the invitation modal
to the top when a user sends invites or generates an invite link."
The problem was related to the way the scrolling was implemented. We were scrolling to the invite dialog element what did not work as the dialog was already in view. Changed the code to scroll to the Sucess message (both link and mail invite).
Fixes: #28906 …
=> Fix invite scrolling

api_docs/changelog.md, api_docs/construct-narrow.md, web/src/compose_tooltips.ts, web/src/filter.ts, web/src/hash_parser.ts, web/src/hash_util.ts, web/src/message_fetch.js, web/src/message_list_view.js, web/src/message_view_header.ts, web/src/narrow.js, web/src/narrow_banner.ts, web/src/narrow_state.ts, web/src/narrow_title.ts, web/src/people.ts, web/src/search_suggestion.ts, web/src/stream_list.ts, web/src/util.ts, web/tests/filter.test.js, web/tests/hashchange.test.js, web/tests/narrow_state.test.js, zerver/lib/narrow.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_fetch.py
Adds backend support for `channel` and `channels` as search/narrow operators and updates the web-app to start using these operators in the `Filter` class, without making user-facing changes to search suggestion strings and URLs.
In the backend changes:
- There's a prep commit to make the test changes easier to read.
- Implements each operator in a separate commit.
- Since the backend/server code isn't user-facing, I went ahead and updated `zerver/lib/narrow.py` and `zerver/tests/test_message_fetch.py` for the stream to channel rename.
In the frontend changes:
- There's a prep commit to make the test changes easier to read.
- Implements each operator in a separate commit.
- The search suggestions still use the "stream" and "stream" strings and neither of the new operators will offer …
=> narrow-filters: Add support for "channel" and "channels" operators.

templates/corporate/hello.html
Notes:
- I tried different widths, and didn't feel the need to use `&nbsp;` anywhere.
- We should make the link to /why-zulip show up with the same formatting as links in the Enterprise section, as a blocker to deploying this. @amanagr it would be great to get a follow-up PR for that.
- Other formatting improvements can happen as part of a broader redesign for this page.
=> portico: Update text on home page.

web/src/click_handlers.js, web/src/inbox_ui.js, web/src/recent_view_ui.js, web/src/stream_list.ts, web/src/topic_list.ts
See #17935.
This is because shift-clicking a link on most browsers should open the link in a new window, not navigate inside the current tab. Right now Zulip early-exits in various click handlers when ctrl is pressed to support "ctrl-click opens new tab". This simply adds shift to the same code.
I checked every element whose handler I was modifying to check that they did have link semantics and shift-clicking them made sense.
Looking at the `initialize` function in `topic_list.ts`:
https://github.com/zulip/zulip/blob/e7a19aca757820fe53f896ab15ad4128bf94838a/web/src/topic_list.ts#L333-L344
I'm not sure the early-exit is enough. I suspect `.sidebar-topic-check` and `.topic-markers-and-controls` should be turned into `<a>` links inside the template code. I might open an issue or a follow-up …
=> Add early-exit to click handlers when shift is pressed

web/src/composebox_typeahead.js, web/src/submessage.ts, web/src/todo_widget.js, web/src/widgetize.ts, web/styles/widgets.css, web/templates/widgets/todo_widget.hbs, web/templates/widgets/todo_widget_tasks.hbs, zerver/lib/validator.py, zerver/lib/widget.py, zerver/tests/test_widgets.py, zerver/views/submessage.py
Near identical to #22551, except this excludes 1 buggy commit for reordering tasks. Everything else works the same as in #22551.
Earlier the tasks in a list were sorted alphabetically and on marking one complete, it was pushed under any incomplete tasks. This behaviour can be unexpected and confusing, so now each task is appended to the bottom of the list on being added, and no shifting takes place on marking it completed.
Users can now name task lists by providing the task list title in the `/todo` command on the same line. Example: `/todo School Work`. If no title is provided by the user, "Task list" (which is also the placeholder) is used as default. The author of a task list can later edit / update the task list title in the todo widget, just like the question in the poll widget.
Up …
=> todo_widget: Improve its functionality and customizability (revision)

api_docs/construct-narrow.md, version.py
In commit 32d5b4fe3ea, the channel and channels operators were documented in the API docs. This bumps the API version to match those changes.
Also, cleans up one **Changes** note from the same commit noted above in the documentation for constructing narrows.
Follow-up to #29663.
---
<details>
</details>
=> api-docs: Bump API version for addition of channel/channels operators.

zerver/lib/upload/__init__.py
Because loading boto3 is so slow, this saves a significant amount of time (0.3s or so) in process startup on servers which are not using the S3 file storage backend.
<details>
</details>
=> upload: Only load S3 backend (and thus boto3) if necessary.

api_docs/changelog.md, version.py, zerver/actions/custom_profile_fields.py, zerver/tests/test_custom_profile_data.py, zerver/tests/test_events.py, zerver/views/custom_profile_fields.py
Fixes: #23022 
This PR makes the following 4 fields optional i.e. you could not pass them if they are unchanged for the patch request.
1. Name
2. Hint
3. field_data
4. required
I have not made any changes on the frontend code which handles the API requests to not pass these fields if they are unchanged. IMO they should be tackled in a separate issue once this gets merged, so its not too many changes to review at one.
NOTE: As for the documentation, I have not added anything since I could find a relevant entry in `rest-endpoints.md`. Since this is an existing endpoint, is that intentional? If not intentional, do we track it in another issue or fix it in this one? IMO another issue will be better for ease of review. 
No UI changes
<details> …
=> custom_profile_fields: Make name, required, hint, field_data optional during update

tools/linter_lib/custom_check.py, zerver/lib/events.py, zerver/lib/narrow.py, zerver/lib/narrow_helpers.py, zerver/lib/narrow_predicate.py, zerver/lib/topic.py, zerver/lib/topic_sqlalchemy.py, zerver/lib/user_topics.py, zerver/tests/test_message_fetch.py, zerver/tornado/event_queue.py, zerver/views/message_fetch.py
Loading sqlalchemy can take a significant amount of time, so splitting these into these own file can be a significant startup-time savings.
<details>
</details>
=> topic: Move sqlalchemy methods into their own file.

corporate/lib/stripe_event_handler.py
Earlier, we were not verifying that the invoice which got paid is for the fixed-price plan.
That could result in a bug where another support invoice with collection_method = "send_invoice" got paid while a fixed-price plam is already configured. The fixed-price plan would be falsely activated.
This PR is to verifiy the invoice before activating the fixed-price plan.
<details>
</details>
=> invoice_paid_event: Verify invoice before activating fixed-price plan.

zerver/lib/narrow.py, zerver/lib/recipient_users.py, zerver/tests/test_message_fetch.py
9a682fb20a40 started performing message fetching in a read-only transaction.  However, our use of `get_or_create_huddle` can violate the read-only promise, and result in a user-facing 500.
In the cases where we're attempting to narrow to a huddle that does not exist, this is equivalent to a false condition; catch those, without making the huddle row, and insert a false.
<details>
</details>
=> narrow: Do not create huddles when fetching messages.

requirements/common.in, requirements/dev.txt, requirements/prod.txt, zerver/lib/markdown/__init__.py, zerver/tests/test_link_embed.py
soupsieve is a heavy-weight dependency, and Tornado pulls it in by way of markdown rendering; since we are only using it for a very simple process, perform that manually.
Per CSS spec[^1]:
> In quoted <string> url()s, only newlines and the character used to
> quote the string need to be escaped.
[^1]: https://drafts.csswg.org/css-values/#urls
<details>
</details>
=> markdown: Switch to directly URL-escaping CSS URLs.

help/typing-notifications.md
Follow-up to #29642 / PR #29719. @roanster007 FYI
Current: https://zulip.com/help/typing-notifications
<details>
<summary>
Updated
</summary>
</details>
=> help: Document option to disable seeing typing notifications.

zerver/migrations/0509_fix_emoji_metadata.py
bcd179be0e93 fixed this for recent imports, but did not address imports from before it was merged.
<details>
</details>
=> migrations: Add a migration to fix emoji metadata in S3.

zerver/actions/invites.py, zerver/actions/message_send.py, zerver/lib/bulk_create.py, zerver/lib/digest.py, zerver/lib/message.py, zerver/lib/message_cache.py, zerver/lib/stream_subscription.py, zerver/lib/test_classes.py, zerver/management/commands/sync_ldap_user_data.py
`QuerySet` doesn’t implement `__contains__`, so it can’t be a subtype of `Container` or `Collection` (https://code.djangoproject.com/ticket/35154). This incorrect subtyping annotation was removed in https://github.com/typeddjango/django-stubs/pull/1925, so we need to stop relying on it before upgrading to django-stubs 5.
- Preparation for #29721.
=> python: Avoid relying on `Collection` supertype of `QuerySet`

web/styles/rendered_markdown.css
This PR extends to KaTeX-only messages the CSS in place to properly align timestamps and EDITED/MOVED markers on image-only messages.
| Before | After (`:has()`) | After (inline-grid fallback) |
| ![katex-before](https://github.com/zulip/zulip/assets/170719/2af016eb-de42-407c-9c65-b20af610f33e) | ![katex-after](https://github.com/zulip/zulip/assets/170719/e8d1b2a4-67b3-4df3-bc87-508061f9280b) | ![katex-fallback](https://github.com/zulip/zulip/assets/170719/c7e3ffd7-7c8b-4d6d-b6b6-f4e0c7a42cb6) |
=> katex: Properly align timestamps with KaTeX-only messages.

web/e2e-tests/stream_create.test.ts, web/src/stream_create.js, web/src/stream_settings_ui.js, web/templates/stream_settings/first_stream_created_modal.hbs, zerver/lib/hotspots.py, zerver/tests/test_hotspots.py
Fixes #29375
When a user creates a stream for the first time, they are taken to the newly created stream. Additionally, if this is the first time the user is creating a stream, an explanatory modal is shown.
- `hotspots.py` is used to determine if this is the first time the user has created a stream.
- `stream_create.test.ts` is modified to account for the redirection and the first-time modal.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/.2329412.20Go.20to.20newly.20created.20stream)
<details>
<summary> Screenshots </summary>
After creating the stream, the following appears
</details>
<details> …
=> Go to newly created stream

zerver/lib/db.py, zerver/lib/db_connections.py, zerver/middleware.py, zerver/worker/base.py, zerver/worker/missedmessage_emails.py, zproject/default_settings.py, zproject/settings.py
Import cycles aren’t ordinarily a problem for mypy, but cycles involving the Django settings module are a problem for django-stubs, and becoming more of a problem for django-stubs 5.
- Preparation for #29721.
=> Break `zproject.settings` import cycles at type-checking time

puppet/kandra/files/postgresql/setup_data.sh, puppet/kandra/manifests/profile/postgresql.pp, puppet/zulip/manifests/profile/postgresql.pp, tools/setup/bootstrap-aws-installer
If there is a replication primary configured, and no current database, then we check all of the required secrets are in place, then pull down the latest backup and trigger a PostgreSQL restart, which will pick up downloading the remaining WAL logs to catch up, then start streaming from the configured primary.
<details>
</details>
=> Automate the second stage of bootstrapping Kandra database replicas.

web/src/pm_list_data.ts, web/src/topic_list_data.ts, web/tests/pm_list_data.test.js, web/tests/topic_list_data.test.js
This PR adds a PM thread/Topic entry in the left sidebar when narrowed down to an empty conversation.
It also disappears if the user navigates away without starting the conversation.
For PM list, it checks if the narrowed user string(s) is already available in `pm_conversations.recent` or else adds on top of it.
Since it just adds it for rendering purpose, it doesn't mess with the `pm_conversations.recent` history and will get removed on unnarrowed.
In topic list too, `get_list_info` checks if the narrowed topic is available in the `stream_topic_history.get_recent_topic_names`, and renders the topic entry if needed.
Fixes: zulip#22769
[Screencast from 04-03-24 05:12:19 PM IST.webm](https://github.com/zulip/zulip/assets/33497322/c81872bd-06fe-45cc-8478-6 …
=> Show empty conversation in left sidebar when viewed.

web/src/stream_create.js, web/templates/announce_stream_docs.hbs
In commit 449febf036, the tooltip that provided information about the announcement stream was replace with inline text on the stream creation form.
Removes the now unused template and code in stream_create for this tooltip.
See #24816, #23327 and https://chat.zulip.org/#narrow/stream/9-issues/topic/private.20announcement.20streams/near/1465348 for more context on the changes that removed this tooltip.
This removes two translated strings from the web app code, and is a prep commit for the stream to channel rename.
---
<details> …
=> stream-settings: Remove unused tooltip for announcement stream.

zerver/actions/message_flags.py, zerver/lib/markdown/__init__.py, zerver/lib/test_classes.py, zerver/lib/test_helpers.py, zerver/lib/timeout.py, zerver/tests/test_markdown.py, zerver/tests/test_message_flags.py, zerver/tests/test_message_topics.py, zerver/tests/test_timeout.py, zerver/views/message_flags.py, zerver/views/streams.py
The `zerver.lib.timeout` strategy using asynchronous exceptions has a number of safety caveats (read the docstring!!) and should only be used in very specific circumstances.
=> timeout: Remove inappropriate uses and rename to unsafe_timeout

zilencer/management/commands/populate_db.py
Since we're just creating an initial database state, there's no reason we need to submit increment analytics updates to the bouncer service; such updates will happen during queue worker startup, if needed.
=> populate_db: Don't enqueue push notifications service updates.

web/src/message_list_view.js
We forgot to restore the date on sticky header if the header is no longer sticky.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/incorrect.20message.20timestamp
Reproducer:
* Have two messages with same sender on different dates next to each other in a stream narrow.
* Scroll so that sticky header is on the 2nd message.
* Scroll down fast so that to avoid us capturing the sticky header over the first message.
* Scroll up slowly so to see the group header of the messages have the date of the second message.
Super easy to reproduce here - https://chat.zulip.org/#narrow/stream/1-announce/topic/server.20releases/near/1592347
=> message_list_view: Restore date on previous sticky header.

puppet/kandra/files/needrestart/zulip.conf
These are often how one is connected to the node, and restarting them would drop the connection one us actively using.
=> kandra: Add teleport services to "needsrestart" skip list.

zerver/actions/user_groups.py, zerver/lib/user_groups.py, zerver/tests/test_audit_log.py, zerver/tests/test_slack_importer.py
Earlier a extra audit log entry of type `USER_GROUP_GROUP_BASED_SETTING_CHANGED` was
made when a new user group is created. This commit updates the code to not create that audit log entry.
There is no need to create these entry as we would still have the required data from the "OLD_VALUE" field in the audit log entry created when changing the setting and this also makes it consistent with the entries created for other operations like stream creation.
Taken from #26355, since this was pending from a long time.
Fixes:  https://chat.zulip.org/#narrow/stream/101-design/topic/New.20permissions.20model/near/1612949
<details> …
=> audit_log: Update audit log entries created while creating a group.

zerver/lib/narrow.py, zerver/tests/test_message_flags.py, zerver/views/message_flags.py
Migrate `message_flags.py` to `typed_endpoint` as part of the project to migrate the server’s Python codebase from the legacy `@has_request_variables` decorator to the new `@typed_endpoint`
=> message-flags: Migrate message flag endpoints to typed_endpoint.

web/src/settings_invites.ts, web/templates/settings/invites_list_admin.hbs
>GSoC'2024 Participant
Previously, the sorting was broken due to
incorrect referencing of the property.
The code has been updated to use the "referrer_name" property instead of "ref".
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/.60Invited.20by.60.20field.20sorting.20is.20broke/near/1784697)
<details>
</details>
=> setting_ui: Fix sorting by "Invited by" column.

web/src/message_list_tooltips.ts, web/templates/message_body.hbs, web/templates/message_controls.hbs, web/templates/tooltip_templates.hbs
Modified tooltips for both the Cancel button and the in-progress sending spinner to provide clearer guidance to users. Now, if the message fails to send successfully, the tooltip includes an additional line explicitly stating: `If the message is not sent successfully, it will be saved as a draft.` 
Additionally, it's worth noting that in my development environment, I noticed that the loading spinner was not displayed, which may be related to the changes introduced in [this commit](https://github.com/zulip/zulip/commit/7463f561f1a38b2afd6da9e84163ee1dda6dd283). Despite this, I proceeded with adding tooltips for both the Cancel button and the spinner, as demonstrated in the attached screenshot.
Fixes part of #29100.
<details> …
=> Modify tooltips to clarify draft saving.

api_docs/include/rest-endpoints.md, zerver/openapi/zulip.yaml
Makes a few small tweaks on the newly documented invites endpoints for current API documentation conventions that were missed in the review process.
- Adds indefinite article to title for creating a reusable invitation link.
- Updates the error response for the delete an email invitation endpoint.
- Updates the ID field description for the invitation object to clarify when in the get invitations endpoint there might be more than one invitation with the same ID integer, which is true for the success example on the page.
<details>
<summary>Updated title for creating a reusable invitation link</summary>
[Current documentation](https://zulip.com/api/create-invite-link)
</details>
<details>
<summary>Updated error response for delete email invitation …
=> api-docs: Tweak newly documented invites endpoints documentation.

zerver/lib/typed_endpoint.py, zerver/tests/test_push_notifications.py, zerver/views/push_notifications.py, zerver/views/reactions.py, zerver/views/read_receipts.py, zilencer/views.py
Migrates `reactions.py`, `push_notifications.py`, `read_receipts.py` to use `typed endpoint` instead of `has_request_variables`.
=> Migrate to typed endpoint

corporate/lib/stripe.py, web/src/message_list_view.js
We use `error_description` in upgrade.ts to determine if the error was related to customer's card. Doesn't seem like there is any harm in doing so since we are explicitly handling "stripe.CardError" and raising these errors with "card error" description.
=> stripe: Remove invalid comment.

web/styles/message_row.css, web/styles/rendered_markdown.css, web/styles/widgets.css, web/templates/widgets/poll_widget.hbs
This PR adjusts the inter-element spacing for all rendered-Markdown elements. The purpose of these adjustments is to make it easier to create a reasonable set of variables for declaring space between Markdown elements as part of the user-adjustable information density project, #12611.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/rendered.20Markdown.20CSS.20adjustments/near/1783569)
The PR shifts all spacing to `margin-bottom`, rather than a combination of top and bottom margin, except for specific sibling combinators (e.g., `p + p`), where `margin-top` is necessary to increase the desired spacing when one element follows a specific other.
Additionally, space above the rendered-Markdown area that was previously set by margins bleeding out from Markdown elements …
=> markdown: Refactor Markdown element spacing.

web/styles/zulip.css, web/templates/copy_invite_link.hbs
Fixed overflow of invite link in the invite users modal for mobile view.
Fixes zulip#29524.
=> modal: Fix invite link overflow in mobile view

web/styles/app_variables.css, web/styles/message_row.css
This PR achieves two primary goals:
1) It cleans up all of the legacy Sass-style variables in `message_row.css`
2) It aligns the `line-height` values on the sender line, including the sender name and timestamp, with the height value set on the hover icons.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/fixes.20to.20the.20sender.20line/near/1785636)
The second change in particular means no more reliance on a magical `margin-top: 3px` value set against the old 20.5px sender-line line-height established by `line-height: normal`. The MDN docs indicate that `normal` equates to a line-height of approximately `1.2`, though that value was closer to `1.464` in situ on the message box previously (14px font-size × 1.464 = ~20.5).
This change also now means that single-line …
=> message_row: Clean up Sass variables, correct line-heights.

web/styles/message_row.css
This PR offers some cleanup on the `message_row.css` file by putting all textarea-related styles behind the `.message_content_edit` class.
It removes any browser-default top margin from the textarea. Additionally, the PR makes minor adjustments to the padding and line-height of the `.message_content_edit` class to bring it in line both with the main compose box as well as the message-area edit preview.
Note that there are still discrepancies between the height of the textarea and preview area, as well as differences in bottom-margin with where the formatting buttons sit. Those will presumably be addressed and cleaned up as part of #28702.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/shifts.20on.20message-edit.20preview/near/1781484) …
=> message_edit: Correct unpleasant content shifts between edit and preview.

web/e2e-tests/message-basics.test.ts, web/src/drafts_overlay_ui.js, web/src/filter.ts, web/src/hash_util.ts, web/src/hotkey.js, web/src/message_edit.js, web/src/message_events.js, web/src/message_flags.ts, web/src/narrow.js, web/src/scheduled_messages_ui.js, web/src/search_suggestion.ts, web/src/ui_init.js, web/src/unread_ops.js, web/templates/search_description.hbs, web/templates/search_operators.hbs, web/tests/filter.test.js, web/tests/message_flags.test.js, web/tests/narrow.test.js, web/tests/narrow_state.test.js, web/tests/search_suggestion.test.js
Updates implementation of the new "channel" and "channels" search operators in the web app to be the defaults.
- "stream" and "streams" still display suggestions, for folks who have those in their muscle memory.
- Changes `Filter.unparse` to use `Filter.canonicalize_operator` when setting the operator value in the string.
- This impacts the search suggestion behavior for the `from` operator, as the canonicalized version of that is `sender`.
- But it doesn't change what suggestions are shown to the user (see screenshots below).
- It changes what string is shown in the search bar if a user selects one of the shown suggestions.
- Updates filters and narrows set in the web app to use "channel" and "channels", instead of "stream" and "streams".
- Updates info overlay for search operators, but …
=> search-suggestions: Update for "channel" and "channels" to be defaults.

web/src/composebox_typeahead.js, web/src/people.ts, web/tests/people.test.js
Updates the logic for adding a wildcard mention syntax in a message to use the "channel" wildcard instead of the "stream" wildcard.
Adds some TODO notes for eventually removing the "stream" wildcard from the typeahead suggestions in the web app.
Part of stream to channel rename project.
**Notes**:
- Translated string in typeahead is updated in #29765
- Help center documentation will be updated separately from these changes.
<details>
<summary>typeahead suggestions when composing a message</summary>
</details>
---
<details> …
=> all-wildcards: Update for "channel" wildcard as preferred to "stream".

web/src/compose_closed_ui.js, web/src/compose_tooltips.ts, web/templates/compose.hbs, web/templates/tooltip_templates.hbs
Change compose_reply_button tooltip logic to show the correct tooltip. Earlier in organizations where DMs were disabled, a stale tooltip was being displayed.
Similar to [#28523](https://github.com/zulip/zulip/pull/28523), When the user hovers over the `compose_reply_button` sometimes had stale tooltip content rendered on it. In this PR, we change the logic used to render this tooltip, to now render the tooltip content on the fly via `instance.setContent()` which should eliminate any such bug.
Earlier if the user hovered over the `compose_reply_button` when it was disabled and switched to a stream in which it was enabled before waiting for the tooltip delay, the next time the user hovers over the `compose_reply_button` the stale disabled tooltip is displayed instead of the enabled one. …
=> compose_tooltips: Improve tooltip logic for compose_reply_button.

zerver/lib/email_notifications.py, zerver/lib/notification_data.py, zerver/lib/push_notifications.py, zerver/lib/soft_deactivation.py, zerver/tests/test_message_notification_emails.py, zerver/tests/test_push_notifications.py, zproject/default_settings.py
This PR makes possible to soft reactivate if the user group mentions has less than 12 members.
Fixes part of #27586 
We will do topic wildcard mention part of the issue in a separate PR.
<details>
</details>
=> soft_reactivate: Reactivate if group mention has < 12 members.

web/src/click_handlers.js, web/styles/zulip.css
This PR makes the reaction button visible when clicking on a message box in a mobile view, enhancing the user experience.
Fixes #29529 
**Note:**  This PR is built upon the work done in the [Closed PR#29533](https://github.com/zulip/zulip/pull/29533), which provided a valuable contribution in making this current PR.
[reaction.webm](https://github.com/zulip/zulip/assets/128511266/1e2c2954-b450-4529-91d2-798ca3832438)
<details> …
=> Enable reaction button to be visible upon clicking a message box in mobile devices.

web/src/settings_org.js
Previously, the stream permissions warning banner failed to hide after changes to the stream's privacy settings were saved or discarded. This fix addresses the issue, ensuring the banner behaves as expected by disappearing when changes to make the stream private are either saved or discarded.
Fixes: #29625
Fixes: 
https://github.com/zulip/zulip/assets/72064462/f8e785fa-ef06-41ab-9296-59897ddf0574
<details> …
=> settings: Fix stream permissions warning banner persistence issue.

web/styles/app_variables.css, web/styles/message_row.css, web/styles/zulip.css
This PR chiefly fixes a regression introduced in #29819 that caused broken and unnecessarily complicated dueling line-height values between sender rows on ordinary messages vs. me-messages.
Additionally, this PR adds the 5px of space below a me-message, so that long me-messages that wrap onto multiple lines will have the same apparent space beneath them as ordinary paragraph messages.
Finally, because the work was sitting there for the doing, this moves all of the sender-related selectors out of `zulip.css` and puts them into `message_row.css`, where they belong.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/fixes.20to.20the.20sender.20line/near/1785636)
| --- | --- |
| …
=> message_row: Fix me messages, consolidate sender-line selectors.

web/styles/reactions.css, web/styles/zulip.css
This PR introduces some aggressive cleanup and rethought approaches to spacing in preparing emoji reactions to play nicely with user-selectable font-size and line-height.
The changes here do not affect the appearance of the reactions emoji. Instead, the changes in how space within and around them is declared should head off little shifts in alignment as work progresses on adjusting the font-size and line-height in the message area. 
As discussed on CZO, this does increase the space below reactions from 4px to 5px, in keeping with a recurring 5px spacing-value found elsewhere in the message area.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/space.20beneath.20reactions/near/1786348)
| --- | --- |
| …
=> reactions: Message-reaction refactors.

web/src/server_events_dispatch.js, web/src/ui_init.js, web/styles/app_variables.css, web/styles/message_row.css, web/tests/dispatch.test.js
Here we go. This PR applies database-stored information density values to the message-content area when "Dense mode" is unselected in user preferences. This is what's necessary to begin building out the information density project, and getting more Zulip developers in on experimenting with values as that project progresses.
Small but compounding sub-pixel rounding causes shifts to certain elements. But overall, things look as they should in the subtle shift from 1.214 to 1.22 for a `line-height` value.
| Before (legacy values) | After (legacy-equivalent db values)
| --- | --- |
| ![legacy-info-density](https://github.com/zulip/zulip/assets/170719/65acbd48-0dd2-4f6b-b029-aac35d5b460b) | ![legacy-info-density-db-values](https://github.com/zulip/zulip/asse …
=> info_density: Apply database values outside of dense mode (dev only).

help/change-organization-url.md, templates/corporate/comparison_table_integrated.html, templates/corporate/pricing_model.html
Notes/questions:
- Is there any additional information that folks should provide when contacting support about changing the subdomain or full URL, or any additional steps they should take? @alexmv @mateuszmandera for your thoughts. In any case, this could potentially be expanded upon as a follow-up; these changes don't remove any information.
- I didn't audit the help article intro, or the contents of the self-hosted section.
- I played with including the license minimum in the Plus plan overview box at the top of /plans, but it didn't look good. I think it's OK to relegate the info to the help page + tooltip.
Current help page: https://zulip.com/help/change-organization-url
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/plans/#cloud
<details>
<summary> …
=> help and portico: Document custom domain request process on Cloud.

web/src/narrow.js
In `narrow.activate`, the `adjusted_terms_if_moved` helper uses the raw terms from the URL for checking if a message was moved. If a non-canoncial operator was in the URL for a narrow (e.g. "subject" instead of "topic" and now "stream" instead of "channel"), then the view wasn't updated correctly.
Update `adjusted_terms_if_moved` to use the canonical version of the operator in the URL when adjusting the message history.
---
<details>
</details>
=> narrow: Adjust for moved message with canonical terms.

web/src/list_widget.ts
`callback_after_render` was not being called when `render` did an early return which caused "load more" to not be updated.
This is noticeable now since we are doing fewer calls to `process_messages` which also updates the `load more` banner.
=> list_widget: Fix recent view "load more" fails to render.

web/src/information_density.ts, web/styles/app_variables.css, web/styles/message_row.css, web/styles/rendered_markdown.css, web/styles/widgets.css
This PR introduces variables for the 5px and 10px inter-element spacing variables found in the Markdown area. It preserves the legacy values inside `.more-dense-mode`, and calculates the database-stored values outside of that.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/rendered.20Markdown.20CSS.20adjustments/near/1788573)
| Before | After, legacy vars (no change) | After, db vars |
| ![single-line-markdown-main](https://github.com/zulip/zulip/assets/170719/e7bd778e-4ecf-4f47-b1e7-d34765c2abb0) | ![single-line-markdown-legacy-vars](https://github.com/zulip/zulip/assets/170719/6dc8c66e-876a-4e03-884e-a05afa0eb36a) | ![single-line-markdown-legacy-db-vars](https://github.com/zulip/zulip/assets/170719/5f081ded …
=> info_density: Express Markdown and message-box spacing as CSS variables.

web/templates/topic_sidebar_actions.hbs
In spectator mode, the separators encapsulating the topic visibility switcher wasn't being hidden since the `hidden-for-spectators` class was being applied only to the `popover-menu-inner-list-item` element.
This removes the additional separators by shifting the `hidden-for-spectators` class to the `popover-menu-outer-list-item` element instead, which is responsible for showing the separators.
Fixes: https://github.com/zulip/zulip/pull/29785#issuecomment-2079809519 / [CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/UI.20redesign.3A.20stream.2Ftopic.20actions.20menu.20popover.20.2329785/near/1789000)
| --- | --- |
| ![image](https://github.com/zulip/zulip/assets/82862779/f31bed5a-99ca-4753-973e-3992f61b3cde) | …
=> topic_popover: Remove additional separators in spectator mode.

web/styles/app_variables.css, web/styles/compose.css, web/styles/dark_theme.css, web/styles/message_row.css, web/styles/modal.css, web/styles/zulip.css
css: Make all modal buttons half opaque when disabled, instead of grey.
Earlier, the primary modal button always turned grey on being disabled, while other modal buttons remained as is in light mode, and grey in dark mode. Now the styling is made consistent across all modal buttons, by giving them all 50% opacity when disabled.
css: Make message send / save buttons half opaque when disabled.
So far, the Send buttons area would turn grey when the message could not be sent. The Save button when editing a message would also turn grey when the message could not be edited anymore. Now we simply make the buttons half opaque instead of turning them grey in a disabled state.
css: Redesign exit / close buttons.
We change the background colors for the close / cancel / exit buttons in modals and …
=> css: Redesign message source textarea and close / cancel buttons.

templates/corporate/hello.html, templates/corporate/support/demo_request.html, templates/corporate/support/support_request.html
Link to new demo request form instead of communities directory.
Before: https://zulip.com/
After:
=> portico: Change CTA buttons in the top section of /hello.

zerver/lib/exceptions.py, zerver/lib/streams.py, zerver/openapi/zulip.yaml, zerver/tests/test_user_topics.py
Creates an `IncompatibleParametersError` to be used in cases where there are two (or more) optional parameters for an endpoint that are incompatible with each other, e.g. there's a parameter for a user name and a user ID but only one should be sent in the request to identify the user.
Documents the error on the `/api/rest-error-handling` article.
Updates the `PATCH users/me/subscriptions/muted_topics` endpoint to use this error when both the stream and stream_id parameters are passed (note this endpoint is currently deprecated).
**Notes**:
- This eliminates the need for a specific translated string for these errors in different endpoints where the parameters that are incompatible have specific names.
- See [relevant CZO #api design](https://chat.zulip.org/#narrow/stream/378-api-design/topi …
=> exceptions: Add IncompatibleParametersError as a JsonableError.

corporate/lib/stripe.py, corporate/tests/test_stripe.py, corporate/tests/test_support_views.py, corporate/views/support.py, templates/corporate/support/realm_details.html, templates/corporate/support/sponsorship_discount_forms.html, templates/corporate/support/sponsorship_forms_support.html
This PR just adds required plan tier field to clould support page and make the field required for setting discount.
Disabled until a required plan tier is set.
=> Prep commits to removing discount percentage.

pyproject.toml, tools/run-dev, tools/semgrep-py.yml, zerver/data_import/import_util.py, zerver/lib/message.py, zerver/lib/partial.py, zerver/lib/test_runner.py, zerver/management/commands/check_redis.py, zerver/tests/test_events.py, zerver/tests/test_invite.py, zerver/tornado/django_api.py, zerver/views/video_calls.py, zerver/webhooks/bitbucket2/view.py, zerver/webhooks/bitbucket3/view.py, zerver/webhooks/clubhouse/view.py, zerver/webhooks/github/view.py, zerver/webhooks/gitlab/view.py, zerver/webhooks/groove/view.py, zerver/webhooks/intercom/view.py, zerver/worker/base.py
The returns plugin hasn’t been updated for mypy ≥ 1.6 (dry-python/returns#1711). This annotation is more limited in that it only supports a fixed number of positional arguments and no keyword arguments, but is good enough for our purposes.
=> partial: Replace returns plugin with an annotation

web/src/narrow.js, web/src/reload_setup.js
Adds a new trigger string to use for `narrow.activate` opts when it is called due detecting a message move for the targeted message ID: "retarget message location".
Updates `narrow.save_narrow` and `narrow.hashchange` to accept the `opts.trigger` as a parameter so that, even if the narrow was started via a hash change in the web app, the URL and browser history is updated for the current location of the targeted message.
---
<details>
</details>
=> narrow: Update hash for moved message even if hash change in progress.

docs/production/video-calls.md
Talking to a customer made me realize that this page should start by giving an interview and documenting the Jitsi integration, before jumping into Zoom and BigBlueButton instructions.
Before: https://zulip.readthedocs.io/en/latest/production/video-calls.html
After:
=> docs: Add introduction to video call providers doc.

web/src/hash_parser.ts, web/src/stream_settings_ui.js, web/tests/hash_util.test.js
The root cause of the bug is that the `switch_rows(event)` function in `stream_settings_ui.js` does not consider whether the user is currently editing the `add_subscriber_pill` input in the right panel of the stream settings menu for the key up/down event to trigger the stream row switching process.
Adjusted the `switch_rows(event)` behavior by adding a condition to prevent switching stream row when the user in the subscriber tab on stream settings menu (`hash_parser.is_on_stream_subscribers()`) and is focused on the `add_subscribers_pill` input
Fixes zulip#29690
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Up.2Fdown.20in.20stream.20add.20users/near/1772561)
[Screencast from 25-04-24 …
=> stream_settings: Fix stream row switching behavior when adding subscribers.

help/collaborative-to-do-lists.md, zerver/lib/widget.py
This fixes the annoying behaviour where a task title with a url in it, for example, "Fix issue https://github/com/zulip/zulip/issues/1234" would be wrongly split into a description at the `:` in the url.
Fixes: [CZO issue thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/extra.20space.20in.20todo.20list.20URL/near/1790012)
<details>
</details>
=> todo: Require space after colon to separate task title from description.

api_docs/changelog.md, version.py, zerver/actions/message_delete.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_delete.py, zerver/tests/test_retention.py
This commit updates the "first_message_id" of the stream on the deletion of the first message that was sent to it.
This results in 1 extra query when any stream message is deleted and 3 extra queries when the first message sent to any stream is deleted.
Fixes #28877.
<details>
</details>
=> message_delete: Update "first_message_id" on message deletion.

web/src/compose_banner.ts, web/src/compose_validate.ts, web/src/ui_init.js, web/styles/app_variables.css, web/styles/compose.css, web/templates/compose.hbs, web/templates/compose_limit_indicator.hbs, web/tests/compose_validate.test.js
compose: Remove the `message_too_long` banner.
Since the banner only repeated what the disabled Send button's and the limit indicator's tooltips already said, it was redundant and has been removed.
compose: Redesign limit indicator to show remaining characters count.
Additionally, the text colors have been updated for both light and dark themes, it starts showing when 900 or less characters are left, as 999 was too soon, and has a tooltip to show the maximum characters limit.
Fixes: #28706.
**Light theme:**
Close to limit:
Over limit:
**Dark theme:**
Close to limit:
Over limit:
<details> …
=> compose: Redesign limit indicator to show remaining characters count.

web/src/sidebar_ui.ts
When user search is active, right sidebar was acting as an overlay since "expanded" class was incorrectly added to it whenever user started a search.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Right.20sidebar.20bugs
=> sidebar_ui: Fix right sidebar acting as an overlay even on wide width.

web/src/compose.js, web/src/compose_notifications.ts, web/src/compose_setup.js, web/templates/compose_banner/compose_banner.hbs, web/templates/compose_banner/success_message_scheduled_banner.hbs, web/templates/modal_banner/modal_banner.hbs, web/tests/compose.test.js
* First commit : A small prep commit to remove a stale class.
* Second commit:
[CZO Discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/jumping.20to.20sent.20message.20conversation.20.28experiment.29.20.2329186/near/1789655)
> we should have a standard pattern for these onboarding banners, and replace the x with a "Got it" button like in [#design > explaining message fading](https://chat.zulip.org/#narrow/stream/101-design/topic/explaining.20message.20fading) .
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit- …
=> compose_banner: Replace the close button with "Got it" button. 

web/src/unread.ts
I haven’t investigated the consequences of this but it’s clearly a bug.
Cc @amanagr (#23127)
=> unread: Fix addition to unread_mention_topics sets

web/styles/message_row.css
This PR makes a significant set of changes to the structure of CSS in `message_row.css`. It flattens a number of selectors, and reduces the `.message_row` selector only to selectors that represent additional classes.
A follow-up PR to this will further flatten the selectors inside of `.include-sender` and `.messagebox-content`, but that's too much churn to add into this already quite massive refactor.
| --- | --- |
| ![viewing-light-before](https://github.com/zulip/zulip/assets/170719/2293e828-e86b-46b9-ae50-9e64c00a7325) | ![viewing-light-after](https://github.com/zulip/zulip/assets/170719/94a7f1c5-db76-47fe-80ed-74dd620c266d) |
| ![viewing-dark-before](https://github.com/zulip/zulip/assets/170719/2d4e4fe2-af8f-4e23-a4dc-9e6b92a42aa4 …
=> message_row: Extract selectors from .message_row

web/styles/app_variables.css, web/styles/popovers.css
This removes the common min-width being used across all popovers and instead sets the min-width according to a popover's requirements.
This allows for greater control over the popovers since we have a variety of use cases for them — which a single common min-width cannot accommodate.
Fixes: [CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/UI.20redesign.3A.20stream.2Ftopic.20actions.20menu.20popover.20.2329785/near/1787888)
<details>
<summary>Navbar popovers</summary>
</details>
<details>
<summary>Message Actions popover</summary>
</details>
<details>
<summary>Stream and Topic popovers</summary>
</details>
<details> …
=> popovers: Move from global popover min-width to per-popover basis.

help/dark-theme.md, help/include/personal-menu.md
As a follow-up to commit ad013a9, this updates the /help/dark-theme docs to describe the newer way to switch themes via the theme switcher, located in the Personal Menu.
This replaces the documentation on switching themes via "Personal Settings".
Fixes: #29550.
| ![image](https://github.com/zulip/zulip/assets/82862779/e9ff204e-9d8a-4219-83cf-41bf72e47265) | ![image](https://github.com/zulip/zulip/assets/82862779/aabf2b0d-5fb1-4906-b586-731738ae82ab) | 
<details> …
=> help: Update documentation on switching themes.

docs/documentation/helpcenter.md
Current: https://zulip.readthedocs.io/en/latest/documentation/helpcenter.html#user-interface
Updated:
=> contributor docs: Extend help center writing style documentation.

web/styles/dark_theme.css
Removes hover effect on compose typeahead which causes it to change text color in dark mode.
Fixes: #29842.
| ---- | --- | 
| ![image](https://github.com/zulip/zulip/assets/91622060/3506ca5e-81ee-4f9a-9ed6-9c2a46e15e25) | ![image](https://github.com/zulip/zulip/assets/91622060/bc476d95-4a46-4529-9cbe-f0e2217b65ce) |
| Light Mode | Dark Mode |
| ------ | ----- |
| ![image](https://github.com/zulip/zulip/assets/91622060/2d35de56-cc9d-40ee-8f2f-3a00826aeb7d) | ![image](https://github.com/zulip/zulip/assets/91622060/bc476d95-4a46-4529-9cbe-f0e2217b65ce) |
<details> …
=> Compose(typeahead): Remove text color change on hover.

web/src/echo.js
Previously, when a message is edited, it is locally echoed with its
pre-edit content.
This is because previously, when we tried to render the edited
message of the edit box during local echo, in order to update
the content, flags, and is_me_message properties of the message
object with that of those returned is markdown.render(), we used
the spread operator and created a new message object, and updated
the existing message object with this new one.
This was misconverted, since edit_locally() method already has a
fully-rendered message object to start with, and is just doing a
rerendering, it should be mutating what message it received, rather
than constructing a new local variable.
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/view.20message.20source.20appearing.20during.20edi …
=> message_edit: Fix local echo of message edit.

web/shared/src/poll_data.ts, web/src/blueslip.ts, web/src/buddy_list.ts, web/src/compose_call.ts, web/src/condense.ts, web/src/dialog_widget.ts, web/src/flatpickr.ts, web/src/hotspots.ts, web/src/integration_url_modal.ts, web/src/invite.ts, web/src/lightbox.ts, web/src/list_widget.ts, web/src/localstorage.ts, web/src/message_edit_history.ts, web/src/message_util.ts, web/src/message_viewport.ts, web/src/narrow_state.ts, web/src/portico/signup.ts, web/src/recent_senders.ts, web/src/search.ts, web/src/search_suggestion.ts, web/src/settings_emoji.ts, web/src/settings_invites.ts, web/src/spoilers.ts, web/src/stream_list.ts, web/src/tippyjs.ts, web/src/user_group_popover.ts
From a [discussion on #frontend](https://chat.zulip.org/#narrow/stream/6-frontend/topic/typescript.20migration/near/1792147):
> For the linter to catch this, we need to enable the `@typescript-eslint/no-unsafe-argument`, `@typescript-eslint/no-unsafe-assignment`, `@typescript-eslint/no-unsafe-call`, `@typescript-eslint/no-unsafe-member-access`, `@typescript-eslint/no-unsafe-return` rules that we currently [disable](https://github.com/zulip/zulip/blob/da675cb6412867eab7e14dace9cb25d00d14bdd9/.eslintrc.json#L190-L194). We should enable them, but it will take some work to fix the 355 existing violations.
This PR removes 89 of those violations.
=> Fix various implicit uses of the `any` type

help/self-hosted-billing.md
Notes:
- I also removed the server version banners from the new customers section, since new customers are expected to be on 8.0+ in any case.
Current: https://zulip.com/help/self-hosted-billing#upgrades-for-legacy-customers
<details>
<summary>
Updated
</summary>
</details>
=> help: Remove description of transition from self-hosted billing page.

web/src/stream_list_sort.ts, web/tests/stream_list_sort.test.js
Fixes: [CZO issue thread](https://chat.zulip.org/#narrow/stream/138-user-questions/topic/stream.20search.20broken.20on.20zulip.20cloud.3F)
<details>
</details>
=> left_sidebar: Add colon `:` to the list of stream word separators.

web/styles/left_sidebar.css, web/templates/more_pms.hbs
This PR applies the DM-area CSS grid to the 'more conversations' row, and fixes a corner-case unread-count display in the process.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/misaligned.20more.20conversations.20unread.20count.20on.20DMs/near/1792575)
| Before | After | After, showing grid |
| ![more-convos-before](https://github.com/zulip/zulip/assets/170719/8618b347-4082-4bba-bcf1-47b52654501e) | ![more-convos-after](https://github.com/zulip/zulip/assets/170719/721550a5-1804-417a-8d6b-f6911b2601ac) | ![more-convos-after-showing-grid](https://github.com/zulip/zulip/assets/170719/c452cb1e-c549-4b3b-bd95-09cf53559d18) |
=> left_sidebar: Apply grid to 'more conversations' DM row.

help/include/plan-upgrade-steps.md, help/self-hosted-billing.md, help/zulip-cloud-billing.md
Now that we don't need to document upgrades for legacy customers (which had an additional scheduled upgrade option), we can consolidate instructions.
We weren't linking to any of the removed anchor links.
Current: https://zulip.com/help/self-hosted-billing
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/zulip-cloud-billing
<details>
<summary>
Updated
</summary>
</details>
=> help: Update plan upgrade instructions

web/styles/message_header.css, web/styles/zulip.css
[At Tim's suggestion](https://github.com/zulip/zulip/pull/29915#issuecomment-2091516907), this moves a few more message-header selectors into the `message_header.css` file.
<details>
</details>
=> message_header: Bring over control hover selectors.

web/styles/message_row.css, web/templates/single_message.hbs
This restores a degree of context to the includes-sender class.
I opted for `messagebox-includes-sender` to make `includes` sound descriptive, rather than as a command ("Thou shalt include sender, O messagebox.")
| --- | --- |
| ![sender-class-before](https://github.com/zulip/zulip/assets/170719/cdcb2747-10f2-4afe-805d-d54dedf606bb) | ![sender-class-after](https://github.com/zulip/zulip/assets/170719/095b6139-5ce4-4663-85bc-f0300b0fa6ef) |
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discip …
=> message_row: Establish clarifying messagebox-includes-sender class.

web/src/hash_util.ts, web/src/hashchange.js, web/src/hotkey.js, web/src/message_list.js, web/src/message_list_view.js, web/src/message_lists.ts, web/src/narrow.js, web/src/narrow_history.ts, web/src/unread.ts, web/src/unread_ops.js, web/src/views_util.ts, web/tests/compose_closed_ui.test.js, web/tests/message_list.test.js, web/tests/narrow_activate.test.js
This effectively makes the narrow pointer and offset restoration behaviour for combined feed view same as other narrows which is to only restore narrow state when using browser back button.
See https://github.com/zulip/zulip/pull/29740#discussion_r1579784395
=> Misc bug fixes related to restoring narrow state.

tools/test-js-with-node, web/e2e-tests/compose.test.ts, web/e2e-tests/lib/common.ts, web/e2e-tests/mention.test.ts, web/e2e-tests/message-basics.test.ts, web/e2e-tests/navigation.test.ts, web/e2e-tests/stream_create.test.ts, web/e2e-tests/user-deactivation.test.ts, web/src/global.d.ts, web/src/global.ts, web/src/message_lists.ts, web/src/message_store.ts, web/src/zulip_test.ts
We haven’t yet converted two of its dependencies `reload` and `stream_create_subscribers`. However, the Puppeteer tests that use `zulip_test` are already TypeScript, and having a type for `zulip_test` fixes 67 implicit uses of `any` within them. So I’m skipping the line here using evil `// @ts-expect-error` comments.
=> zulip_test: Convert module to TypeScript

docs/contributing/commit-discipline.md, docs/contributing/index.md, docs/contributing/review-process.md, docs/contributing/reviewable-prs.md
This PR's main goal is to turn the "Reviewable pull requests" article into a step-by-step guide for how to put together a great PR. There is some new overview content here, and various sections are moved around de-duplicated.
To do:
- I haven't had a chance to take a look at the contributor guide, and see if any links or text there needs to be updated.
=> contributor docs: Update documentation on submitting PRs.

web/src/echo.js
These checks are not required since the local echo might be for a different message list than current. Also, we don't add new messages outside of fetch request for the current message list if the latest message has not been found anyway.
=> echo: Remove checks on current message list.

zerver/migrations/0517_resort_edit_history.py, zerver/migrations/0518_merge.py
Migration 0517 migration was already run as 0497 on `main`, but was accidentally omitted on 8.x until this point.
Merge the 0517 migration into the migration history.  It is included as a no-op in `main` because it has already run as 0497.
<details>
</details>
=> migrations: Merge 0517 as a no-op.

web/src/narrow_state.ts
Combined feed always narrowed to the first unread id regardless of if it was muted or not since we were not actually using the msg_id that we found after all the hard work of doing all the checks for it.
=> narrow_state: Fix combined feed narrowing near msg id of muted message.

web/styles/left_sidebar.css
This is a minor fix that was accidentally left off of #29941.
=> left_sidebar: Correct vertical alignment on 'more conversations.'

tools/backport-pull-request
The commit hashes that appear in the `pull/12345/head` ref are the ones _before_ any final rebase occurs, and as such may not match to any commit hashes which exist in `main`.
Use the GitHub GraphQL API to pull the last "merge commit" on the PR, which is post-rebase, and use that as the target commit when cherry-picking.  Then walk backwards from that commit, including every sequential commit which is still associated with the PR; we do this because during the merge, commits may be added or removed, so the PR is not reliable in the commit count.
=> backport: Fix the commit-ids that are used.

CONTRIBUTING.md
Follow-up to restructuring PR guide pages.
Before:
After:
=> contributor docs: Update links to PR guides.

zerver/openapi/zulip.yaml
=> documentation: Described display_in_profile_summary field as optional.

web/src/bootstrap_typeahead.ts, web/src/composebox_typeahead.js, web/src/stream_popover.js
`data("typeahead").unlisten()` of move topic to stream popover crashed since we removed `data('typeahead')` in #29973.
=> stream_popover: Fix broken move topic to stream popover.

web/src/narrow.js, web/src/submessage.ts, web/src/widgetize.ts, web/tests/widgetize.test.js
Earlier we did not activate widgets if their rendered HTML was cached, and also when narrowing to the combined feed view. This caused bugs with widgets not being activated, and so not responding to any interactions.
Now we unconditionally render and activate widgets in the current view, irrespective of the cached HTML or the view being narrowed to.
Fixes: [CZO issue thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/Voting.20on.20Polls.20in.20the.20webapp)
<details> …
=> widgets: Always render and activate widgets in the current view.

help/preview-your-message-before-sending.md, web/templates/compose_control_buttons.hbs, web/templates/popovers/compose_control_buttons/compose_control_buttons_in_popover_2.hbs, web/templates/tooltip_templates.hbs
compose: Add keyboard shortcuts to compose control buttons' tooltips.
For more discoverability, the keyboard shortcuts for preview, and bold, italic and link formatting are now displayed in the tooltips of those compose buttons.
help: Document keyboard shortcut for previewing message being composed.
Fixes: [CZO issue report](https://chat.zulip.org/#narrow/stream/101-design/topic/key.20combination.20for.20hotkey.20to.20toggle.20compose.20preview/near/1793636)
<details> …
=> Document preview hotkey, and show all hotkeys in compose button tooltips.

web/src/compose_recipient.ts, web/src/compose_ui.ts, web/styles/left_sidebar.css, web/templates/left_sidebar.hbs
After restoring a draft with no recipient, compose was broken as this assertion fails.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Assertion.20failed.20when.20restoring.20draft.20with.20no.20stream
=> compose_recipients: Fix broken compose state after restore draft.

web/e2e-tests/drafts.test.ts, web/e2e-tests/lib/common.ts, web/e2e-tests/realm-playground.test.ts, web/src/bootstrap_typeahead.ts, web/src/compose_ui.ts, web/src/composebox_typeahead.js, web/src/custom_profile_fields_ui.js, web/src/pill_typeahead.ts, web/src/settings_playgrounds.ts, web/styles/popovers.css, web/styles/zulip.css, web/tests/composebox_typeahead.test.js, web/tests/pill_typeahead.test.js, web/third/bootstrap-typeahead/typeahead.css
No visual changes, just used tippy to position elements.
Next steps here would to use start using the new styles while renaming the clases for typeahead and dropdown-menu to ensure we are not using any bootstrap styles.
=> Use tippy to position typeaheads

zerver/lib/export.py, zerver/management/commands/export.py
This PR creates `REALM_EXPORTED` audit log to help during import to distinguish readily between imports from another Zulip server vs imports from another product.
Prep PR for #29762
<details>
</details>
=> export: Create REALM_EXPORTED audit log for exports via shell.

web/src/poll_widget.ts, web/src/submessage.ts, web/src/todo_widget.js, web/src/widgetize.ts, web/tests/poll_widget.test.js, web/tests/widgetize.test.js
In 61b3c698affb9aebf29300d36f42a1d8440151a6 we stopped restoring widgets from the cache, so the only purpose of the cache remaining was to access the event handler patched onto the widget jquery.
Now instead of the entire jquery object, we cache just the event handler since that's the only thing we need from the cache, and do not patch it onto the widget jquery object.
[CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/Voting.20on.20Polls.20in.20the.20webapp/near/1795125)
<details> …
=> widgets: Cache event handler instead of entire jquery for each widget.

api_docs/changelog.md, version.py, zerver/actions/user_groups.py, zerver/lib/event_schema.py, zerver/lib/user_groups.py, zerver/openapi/zulip.yaml, zerver/tests/test_audit_log.py, zerver/tests/test_event_system.py, zerver/tests/test_events.py, zerver/tests/test_home.py, zerver/tests/test_user_groups.py, zerver/views/user_groups.py
This contains all the commits responsible for the main can_mention_group setting API change in #29937.
(The `_previous` detail is still under discussion and will merge with another feature level).
=> can_mention_group commits extracted from #29937

requirements/common.in, requirements/dev.txt, requirements/prod.txt
Building these libraries from source requires too much memory, and causes OOMs on a host with 4GB of RAM when still running Zulip.
Building from source was enabled in `main` to work around xmlsec/python-xmlsec#320, which does not occur with the xmlsec version in the 8.x branch, as xmlsec/python-xmlsec#314 (incompatibilities with Ubuntu 20.04) causes us to pin xmlsec<1.3.14.
As such, we switch back to using prebuilt wheels.  The version mismatch from xmlsec/python-xmlsec#320, if real, is not new, so this exposes us to no more risk than before.
=> requirements: Drop the --no-binary for lxml and xmlsec.

web/styles/rendered_markdown.css
The `margin-bottom` was removed for the last element in the preview in e55f5a1b5903994a65844e8c711989f5ed32e51c to remove vertical shifts when toggling preview mode, but it is not needed for image / video previews, so now `margin-bottom` is not set to 0 for the last inline preview.
Fixes: [CZO issue report](https://chat.zulip.org/#narrow/stream/9-issues/topic/misaligned.20image.20previews.20when.20at.20end.20of.20message.20preview/near/1796347)
Before:
After:
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html)) …
=> compose: Fix bug in preview where image at the end would be misaligned.

web/src/recent_view_ui.js, web/src/ui_init.js
Since there are no rows to set focus in recent view before initial fetch, we were falling back to set focus on input filter after rendering recent view.
Waiting for initial fetch to complete helps us set focus on the table easily while recent view is also open for user to play with if the load takes longer.
=> recent_view: Fix filter input focused on load.

api_docs/changelog.md, api_docs/include/rest-endpoints.md, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_openapi.py
This PR adds API documentation for following endpoints:
- /users/me/apns_device_token
- /users/me/android_gcm_reg_id
<details>
</details>
<details>
</details>
=> openapi: Document apns_device_token and android_gcm_reg_id endpoints.

web/e2e-tests/stars.test.ts
With combined feed no longer cached, this test became flaky as it took longer for combined feed to load.
Verified that other tests waiting on `.message-list` don't need this change.
discussion: https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/flaky.20star.20message
=> stars: Fix flaky test due to message list not yet rendered.

scripts/setup/apt-repos/zulip/zulip.pref
It depends libarrow1600, which is missing from the PGroonga repository on Debian 12.
[Discussion](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/libgroonga.20installation/near/1797208).
=> apt-repos: Deprioritize libgroonga0 14.0.3-1

zerver/lib/onboarding.py, zerver/tests/test_signup.py
#30056
* First commit: Adds a prep commit to avoid `remove_single_newlines` repetition.
* Second commit: #30056 
* Third commit: https://github.com/zulip/zulip/pull/30056#issuecomment-2105341642
<details>
</details>
=> onboarding: Modify content on onboarding messages.

templates/zerver/deactivated.html, templates/zerver/invalid_realm.html, zerver/middleware.py, zerver/tests/test_auth_backends.py, zerver/tests/test_decorators.py, zerver/tests/test_docs.py, zerver/tests/test_signup.py, zerver/views/home.py
This ended up being more tangly than I expected, so I'm putting up this WIP PR, which will require some work to complete.
<details>
<summary>
PR screenshot
</summary>
</details>
**To do:**
<details>
<summary>
PR screenshot
</summary>
</details>
**To do:**
=> Improve pages when there is no organization or it has been deactivated

web/styles/app_components.css, web/styles/compose.css, web/styles/zulip.css
Due to these transitions the theme switch from dark <-> light was not pleasant as the background color and color changed at different intervals.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/theme.20transition
=> css: Fix theme switch changing color of elements at different intervals.

zerver/actions/create_user.py, zerver/lib/onboarding.py
First commit: Third commit from #30063 somehow got dropped.
Second commit: https://github.com/zulip/zulip/pull/29421#issuecomment-2103382711
> I'm not convinced that the topics are being translated properly; they're computed outside the with override_language block. Do we want to just call send_initial_realm_messages inside a with override_language block in the caller, rather than indenting everything? Seems timely but not a blocker since none of these new strings are actually translated yet.
<details> …
=> onboarding: Fixes bugs from #29421.

web/src/filter.ts, web/src/message_view_header.ts, web/styles/message_view_header.css, web/templates/navbar_icon_and_title.hbs, web/tests/filter.test.js
Adds description in views styled like stream descriptions along with adding a help center link to the appropriate page at the end of each description.
[CZO thread](https://chat.zulip.org/#narrow/stream/101-design/topic/Describe.20views.20in.20top.20navbar.20.2329769/near/1782549)
Fixes: #29769
<details>
</details>
=> Navbar: Describe views in top navbar.

zerver/lib/import_realm.py, zerver/tests/test_import_export.py
When importing a Stream, UserProfiles don't yet exist. so trying to import stream.creator fails with something like:
```
psycopg2.errors.ForeignKeyViolation: insert or update on table
"zerver_stream" violates foreign key constraint
"zerver_stream_creator_id_65aeba7e_fk_zerver_userprofile_id"
DETAIL:  Key (creator_id)=(5) is not present in table "zerver_userprofile".
```
=> import: Fix import of Stream.creator field.

web/styles/dark_theme.css
Fixes #30083.
We have used the dark theme color for the left sidebar row hover: `--color-background-active-narrow-filter`. We are not using that variable directly since we don't want a change in that color affecting the color in recent conversations.
We've also used a single color on hover compared to 2 different colors for unread and read row before. Light mode also uses a single color on hover.
Relevant CZO convo: [link](https://chat.zulip.org/#narrow/stream/101-design/topic/Hover.20color.20in.20Recent.20conversations.20dark.20mode.2E/near/1797727)
<details>
<summary>Hover GIF</summary>
</details>
<details> …
=> recent_topics: Change background color in dark mode on hover on a row.

api_docs/changelog.md, api_docs/group-setting-values.md, api_docs/roles-and-permissions.md, api_docs/sidebar_index.md, version.py, web/src/settings_org.js, zerver/lib/exceptions.py, zerver/openapi/zulip.yaml, zerver/tests/test_user_groups.py, zerver/views/user_groups.py
=> Add API support to set `can_mention_group` setting to anonymous user group.

web/src/click_handlers.js, web/src/compose_setup.js, web/src/message_actions_popover.js, web/src/message_edit.js, web/src/message_list.js, web/src/message_list_view.js, web/src/resize.ts, web/src/ui_init.js, web/src/upload.js, web/templates/compose_control_buttons.hbs, web/tests/compose.test.js, web/tests/compose_video.test.js, web/tests/upload.test.js
This was due to event handlers being lost when restoring a message edit state. To avoid it, we recreate the form and attach event handlers to it which also correctly update the current state of the edit form buttons based on settings.
Just edit a message -> go to a different narrow -> click browser back button -> focus on the edit form and try to press escape (it doesn't work)
discussion: https://github.com/zulip/zulip/pull/29383#discussion_r1546776263
=> Fix `escape` key not working to close compose edit state.

web/src/unread_ops.ts
Converting stream_id to string invalidates the
value as our narrow parser expects integer as valid stream_id and stream name if it is string.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Marking.20topic.20as.20read.20doesn't.20work
=> unread_ops: Fix unable to mark messages as read in Inbox view.

web/src/copy_and_paste.ts
Fixed 2 bugs in the detection of the last message row copied. This fixes the issue where when the mouse was released on the message header after copying multiple messages, the pasted text was not formatted correctly.
Follow up to #30091.
<details>
</details>
=> copy_and_paste: Fix bugs surfaced by typescript migration.

web/src/invite.ts, web/styles/app_components.css, web/templates/invite_user_modal.hbs
- First commit fixes the bug of invite modal not opening for users who cannot subscribe others.
- Second commit is to fix the UI.
<details>
</details>
=> invite: Fix invite modal bug for users who can't subscribe others.

zerver/lib/onboarding.py, zerver/lib/zulip_update_announcements.py, zerver/tests/test_signup.py, zerver/tests/test_zulip_update_announcements.py
To help users focus on the onboarding experience, we no longer send the introductory "Zulip updates" message as a part of onboarding.
Now, we send the introductory message just before the first update message.
Fixes: #30053.
We diverted a bit from what the issue suggests after discussion -- [CZO Discussion
](https://chat.zulip.org/#narrow/stream/101-design/topic/New.20feature.20notification.20system.20.2328604/near/1799805)
<details> …
=> onboarding: Don't send zulip update message during new realm creation.

zerver/lib/bulk_create.py, zerver/tests/test_subs.py, zilencer/management/commands/populate_db.py
Fixes: [#29425 (comment)](https://github.com/zulip/zulip/pull/29425/files#r1573478548)
<details>
</details>
=> streams: Set creator for some initial streams in populate_db.

api_docs/changelog.md, version.py, zerver/openapi/zulip.yaml
The original changes for this feature level are in commits a6be1d101 and 7b42c802b.
Some notes on updates:
- Bumps the API feature level in version.py
- Uses channel in descriptive text instead of stream in these changes so that I don't have merge conflicts with my general changes in the API documentation for that rename.
<details>
<summary>Updated API changelog entry</summary>
</details>
<details>
<summary>Updated parameter descriptions for email invite endpoint</summary>
</details>
<details>
<summary>Updated parameter descriptions for reusable link endpoint</summary>
</details>
---
<details>
Individual …
=> api-docs: Update feature level 261 documentation.

web/e2e-tests/custom-profile.test.ts, web/e2e-tests/realm-linkifier.test.ts, web/e2e-tests/settings.test.ts, web/e2e-tests/user-deactivation.test.ts, web/src/confirm_dialog.ts, web/src/dialog_widget.ts, web/src/modals.ts, web/src/settings_linkifiers.ts, web/src/unread_ops.ts, web/src/user_deactivation_ui.ts, web/templates/dialog_widget.hbs
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/close_active.28.29.20called.20without.20checking.20any_active.28.29
=> dialog_widget: Check if modal is open before closing.

api_docs/changelog.md, api_docs/include/rest-endpoints.md, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_openapi.py
This PR adds API documentation for "/invites/multiuse{invite_id}" endpoint.
<details>
</details>
=> api_documentation: Document "/invites/multiuse/{invite_id}" endpoint.

web/src/settings_sections.js, web/src/settings_streams.js, web/styles/settings.css, web/templates/invite_user_modal.hbs, web/templates/settings/default_streams_list_admin.hbs, web/templates/settings_overlay.hbs
Updates instances of `default-streams-list` to instead be `default-channels-list` as the data-section for the organization settings overlay is part of the URL hash.
Did a general sweep for everything returned by `git grep default-streams-list`.
---
<details>
</details>
=> org-settings: Update tab for default channel settings.

docs/translating/chinese.md, docs/translating/finnish.md, docs/translating/hindi.md, docs/translating/polish.md, docs/translating/urdu.md
docs: Updated "Private messages" -> "Direct messages" #26939 
Fixes: https://github.com/zulip/zulip/issues/26939
The documentation from "Private messages/PMs" to "Direct messages/DMs" was done by a local search in the file, and for different languages, i used google translator and then got it verified by the peoples from the same region. 
And after verifying again going through ChatGPT just to make a cross check if that's correct.
</details>
=> docs: Updated "Private messages" -> "Direct messages" #26939

.github/workflows/production-suite.yml
This reverts commit 2ec288a9837eb1395d870d4ca05f9ed7eaf2f12d. Upstream PostgreSQL fixed this in
https://salsa.debian.org/postgresql/postgresql-common/-/commit/7df2322ef5d37417afd7dcc3a7ed77a6a5a14820
<details>
</details>
=> Revert "ci: Temporarily upgrade postgresql-client-common before upgrading."

docs/subsystems/schema-migrations.md, docs/tutorials/new-feature-tutorial.md
It turns out `./manage.py migrate` auto flushes memcached resulting in clearing the cache, so no need to tell the developer to manually type the command to flush .
[relevant CZO topic](https://chat.zulip.org/#narrow/stream/3-backend/topic/flush.20vs.20restart.20memcached) 
<summary>Rendered updated text : </summary>
see [updated doc](https://zulip--29427.org.readthedocs.build/en/29427/tutorials/new-feature-tutorial.html)
see [original doc](https://zulip.readthedocs.io/en/latest/tutorials/new-feature-tutorial.html)
=> docs: Remove flush memcached command as it's auto-done by migration.

templates/zerver/deactivated.html, templates/zerver/invalid_realm.html
`is_self_hosting_management_page` is used to check if user is on `selfhosting.ORG_URL` domain which is not what we want for these pages.
discussion: https://chat.zulip.org/#narrow/stream/3-backend/topic/How.20to.20test.20the.20corporate_enabled.20flag.3F
=> zerver: Use correct flags to check if this is a self hosted server.

web/src/hashchange.js
Reproducer:
* Start with empty hash and combined feed as home view.
* Go to any narrow.
* Keep pressing escape key.
You will keep switching between narrow view and home view while you should just stop at home view. This was due to `set_hash_to_home_view` not considering empty hash as a valid home view hash.
Introduced in f07ed8b6b309dc56cad7ed58bbf62e6883115443
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Esc.20key.20loop.20with.20combined.20feed
=> hashchange: Fix infinite home view <-> narrow loop on escape keypress.

web/src/message_util.ts, web/src/server_events.js, web/tests/server_events.test.js
Hiding the loading indicator was based on us adding some messages into the view which was no always the case.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/message.20loading.20spinner.20keeps.20spinning
Reproducer: populate database with no messages
Do we even need this indicator?
=> server_events: Fix infinite loading indicator on page load.

zerver/lib/markdown/__init__.py, zerver/tests/fixtures/markdown_test_cases.json
In file zerver/lib/Markdown/__init__.py we try to atler timestamp using the astimezone function. However, if an incorrect timezone (such as +32h) was provided, this function would produce an error and the message would not be sent. 
The try/except fixes the python error and allows the message to be sent, saying `Incorrect Date Format: [time]`, much like trying to send a message with `<time:abc>`. This approach was chosen to make the website more coherent.
Also created two tests which verify that the request is successful, when the timezone is valid and invalid. 
Fixes zulip#19658
- Before:
- After:
<details> …
=> fix: Added a try/except case when trying to execute the astimezone function.

zerver/lib/user_groups.py, zerver/views/user_groups.py
- First commit is to move some functions to `zerver.lib.user_groups`.
- Second commit is to rename `are_both_setting_values_equal`.
<details>
</details>
=> Follow ups for the group settings API changes in #29937.

web/src/composebox_typeahead.ts, web/src/message_edit.js
Followup to https://github.com/zulip/zulip/pull/30086#discussion_r1600536580
=> composebox_typeahead: Clean up initalize method to take JQuery object.

web/src/hash_parser.ts, web/src/hashchange.js, web/src/input_pill.ts, web/src/user_card_popover.js, web/src/user_group_pill.ts, web/src/user_group_popover.ts, web/styles/input_pill.css, web/templates/input_pill.hbs, web/tests/hash_util.test.js, web/tests/user_group_pill.test.js
This PR aims to continue where #28820 has left off. The changes introduced in my PR are primarily fixes addressing the comments left by reviewer in the original PR.
Details of the original PR by Ecxtacy: 
- Added css fix for hovering effect on the X icon in user pills.
- Added an optimization refactor to `removePill` function of `input_pill.ts` module as discussed in the [CZO](https://chat.zulip.org/#narrow/stream/6-frontend/topic/Input.20pill.20code.20optimization).
- Fixed user pill related components to enable popover effect for user and user group pills in channel and group settings.
New changes in this PR is detailed in the PR comments I've highlighted in the code.  
Fixes: #28687
<details>
<summary>
Popovers on user and group pills in channel and …
=> popover: Fix user pop over not showing when clicked in channels /group settings

corporate/tests/test_stripe.py, corporate/tests/test_support_views.py, corporate/views/support.py, tools/test-api, zerver/actions/create_realm.py, zerver/actions/realm_settings.py, zerver/management/commands/deactivate_realm.py, zerver/management/commands/export.py, zerver/tests/test_audit_log.py, zerver/tests/test_auth_backends.py, zerver/tests/test_decorators.py, zerver/tests/test_email_change.py, zerver/tests/test_email_mirror.py, zerver/tests/test_events.py, zerver/tests/test_push_notifications.py, zerver/tests/test_realm.py, zerver/tests/test_signup.py, zerver/views/realm.py
It's going to be helpful in the future to record the reason for realm deactivation.
- For information tracking
- For making a distinction between cases where we can allow realm owners to reactivate their realm via a self-serve flow (e.g. "owner_request") vs where we can't (ToS abuse).
=> do_deactivate_realm: Add deactivation_reason kwarg.

zerver/actions/message_send.py, zerver/actions/streams.py, zerver/actions/uploads.py, zerver/actions/user_topics.py, zerver/lib/streams.py, zerver/lib/test_classes.py, zerver/lib/user_topics.py, zerver/tests/test_event_queue.py, zerver/tests/test_event_system.py, zerver/tests/test_events.py, zerver/tests/test_link_embed.py, zerver/tests/test_message_move_topic.py, zerver/tests/test_message_send.py, zerver/tests/test_service_bot_system.py, zerver/tests/test_subs.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/jump.20to.20topic.20view.20before.20message.20is.20there/near/1793763)
<details>
</details>
=> message_send: Update `do_send_messages` codepath to send event on commit.

web/src/recent_view_ui.ts
If the initial fetch pre #29740 fetches all muted messages we don't have any messages in all message list and hence query for oldest message is undefined.
This results in us trying to render oldest_message_timestamp with its value as infinity.
So, to fix it, we just wait for our other initial fetch of recent view to return us the messages we need.
=> recent_view: Fix error on initial fetch being all muted messages.

web/tests/input_pill.test.js
Added a test for newly added `input` event handler for `input_pill.ts` module.
<details>
</details>
=> input_pill: Add test for `input` event handler.

api_docs/construct-narrow.md, api_docs/create-scheduled-message.md, api_docs/create-stream.md, api_docs/include/rest-endpoints.md, api_docs/incoming-webhooks-overview.md, api_docs/incoming-webhooks-walkthrough.md, api_docs/integrations-overview.md, api_docs/message-formatting.md, api_docs/outgoing-webhooks.md, api_docs/real-time-events.md, api_docs/roles-and-permissions.md, api_docs/running-bots.md, api_docs/send-message.md, api_docs/writing-bots.md, zerver/openapi/zulip.yaml, zerver/tests/test_docs.py, zerver/tests/test_openapi.py
Updates the API documentation to use "channel" in descriptive text, instead of "stream". This is in keeping with how we use "organization" instead of "realm" in descriptive text in our user-facing documentation.
See relevant CZO conversations:
- https://chat.zulip.org/#narrow/stream/438-release-management/topic/rename.20.22stream.22.20to.20.22channel.22.20project.2C.20.2328468/near/1799766
- https://chat.zulip.org/#narrow/stream/378-api-design/topic/renaming.20to.20.22channel.22.20across.20API/near/1796710
Before changes:
```console
$ git grep -i stream zerver/ | wc -l
14467
$ git grep -i stream zerver/openapi/ | wc -l
1328
$ git grep -i stream zerver/openapi/zulip.yaml | wc -l
1130
$ git grep -i stream api_docs/ | wc -l
255
```
After changes:
```console
$ git grep -i stream zerver/ | wc …
```
=> api-docs: Update descriptive text for stream to channel rename.

zerver/openapi/javascript_examples.js, zerver/openapi/python_examples.py
Updates the Python and Javascript usage examples in the API documentation for the stream to channel rename.
**Notes**:
- Focuses on updating descriptive text as function, endpoint and parameter/field names would be separate API changes if/when we decide to make them.
- Updates some example strings used for channel names and some variable names.
- For some Python usage examples, shows getting the value for a request field/parameter to improve clarity of example.
**Example screenshots:**
<details>
<summary>Get channel/stream ID endpoint</summary>
[Current documentation](https://zulip.com/api/get-stream-id#usage-examples)
</details>
<details>
<summary>Update channel/stream enpoint</summary>
[Current documentation](https://zulip.com/api/update-stream#usage-examples)
</details>
<details> …
=> api-docs: Update usage examples for stream to channel rename.

web/src/stream_edit_subscribers.js
Add user name in feedback message so that it is more clear which user is unsubscribe.
https://github.com/zulip/zulip/assets/73663475/df816098-2397-460b-b861-89276b939865
Fixes #19165.
<details>
</details>
=> stream_settings: Update feedback message to include user name.

zerver/lib/narrow.py, zerver/tests/test_message_fetch.py
Fix issue with `is:resolved streams:public` only fetching rows from `zerver_usermessage`.
=> is-resolved: Ok to include history.

zerver/lib/message.py, zerver/tests/test_message_edit.py, zerver/tests/test_message_send.py
- First commit is to fix code to check whether `UserGroup` object is linked to a `NamedUserGroup` object.
- Second commit is a small optimization to check if can_mention_group is everyone group.
<details>
</details>
=> message: Fix code checking group mention permission to handle anonymous user groups.

web/src/narrow.js, web/src/recent_view_ui.ts, web/src/ui_init.js, web/src/unread.ts, web/tests/hashchange.test.js
We already had the data at initial request, so we just add some plumbing to make it available.
Followup to https://github.com/zulip/zulip/pull/30008#discussion_r1597265650
=> recent_view: Complete TODO to use first unmuted unread message id.

docs/development/setup-recommended.md
Since the docker macOS setup doesn't work without this, it makes sense for it to be just part of the setup instead of a thing they fix after running into failure.
Didn't remove the failure note since that seems useful for someone looking for that error.
=> setup-recommended: Make user choose `osxfs` earlier to avoid failure.

web/styles/compose.css
Reproducer:
1. Make your window narrow, to get the `...` formatting buttons menu.
2. Open the menu.
3. Make your window wide again.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/formatting.20buttons.20menu.20remains.20open
=> compose: Fix formatting popover persists on wide screens.

web/styles/compose.css
This PR improves the layout of the send controls by using layout techniques, and not padding on the often-invisible `#compose-limit-indicator`, to keep the send controls in step with the compose box's text area at all sizes (normal, enlarged, maximized).
Additionally, this PR better centers the vdots when they appear above the send controls.
There is one change--setting a height of 26px on the send-later vdots--which should be revisited once #29953 or some similar PR gets close to being a candidate for merging. But as that work promises to take awhile, this PR corrects the immediate problem in the compose area with a workable interim solution.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/Misalignment.20in.20compose.20send.20controls.20area.20at.20narrow.20widths/ne …
=> compose: Correct layout of send controls in narrow viewports.

corporate/lib/activity.py, corporate/lib/stripe.py, corporate/lib/support.py, corporate/tests/test_activity_views.py
In the activity and support views, we want to see the annual revenue for fixed price plans. While on billing pages, we do not display this information as these plans are renegotiated annually.
Adds `get_annual_recurring_revenue_for_support_data` function to `BillingSession` class, so that we can get the fixed price plan data for these views without changing the logic for what is displayed on the billing pages.
<details>
<summary>Remote support view</summary>
| --- | --- |
|![Screenshot from 2024-05-22 17-03-17](https://github.com/zulip/zulip/assets/63245456/a24df839-7d46-44bb-a260-f996a4dfd4e8) | ![Screenshot from 2024-05-22 17-03-38](https://github.com/zulip/zulip/assets/63245456/b2992986-84ca-4a4b-b846-b82e22142e7e)
</details> …
=> support: Show annual revenue for active fixed price plans.

web/src/submessage.ts
We now check if the row exists in the current view, and only then do we process the submessages in it, instead of letting `Error: Failed to do_process_submessages` happen.
Fixes: [CZO issue report](https://chat.zulip.org/#narrow/stream/9-issues/topic/Error.3A.20Failed.20to.20do_process_submessages/near/1805249)
<details>
</details>
=> widgets: Fix bug where `process_submessages()` was run for empty rows.

web/src/topic_list.ts, web/src/topic_popover.js, web/styles/left_sidebar.css, web/templates/more_topics.hbs, web/templates/topic_list_item.hbs
This PR gets the `.searching-for-more-topics` indicator participating in the same grid used on other topic rows. A prep commit just flattens a selector in the area.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/topics.20loading.20indicator/near/1792633)
| --- | --- |
| ![more-topics-before](https://github.com/zulip/zulip/assets/170719/75275441-e710-4fa9-8434-44c9c15682ab) | ![more-topics-after](https://github.com/zulip/zulip/assets/170719/61ed9570-291a-445d-bc31-391b96b213c2) |
<details> …
=> left_sidebar: Align more-topics indicator on topic grid.

api_docs/changelog.md, api_docs/include/rest-endpoints.md, version.py, zerver/lib/events.py, zerver/lib/user_status.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_user_status.py, zerver/views/presence.py, zproject/urls.py
This PR adds "users/{user_id}/status" endpoint to the API documentation which fetches the status of a specified user.
It completes the work started in #19498.
<details>
<summary>**Screenshots and screen captures:**</summary>
</details>
<details>
</details>
=> api: Add "users/{user_id}/status" endpoint to fetch a single user's status.

web/src/filter.ts, web/tests/filter.test.js
Some we didn't have a check for if topic is muted here which resulted in combined feed trying to navigate user to muted unread message if it was the first unread in the narrow.
Reproducer:
* Mark a message as unread which is not the last message.
* mute the topic
* Navigating to combined feed takes you a random message. (which is actually the message nearest to that unread message if the topic was not muted).
=> filter: Fix combined feed navigating to muted unread message.

web/src/message_list.js, web/src/message_list_data.ts, web/src/message_lists.ts, web/src/narrow.js, web/src/unread.ts
Opened for further discussion after https://github.com/zulip/zulip/pull/30008#discussion_r1597279862
https://github.com/zulip/zulip/pull/30008#discussion_r1597279862 still needs to be fixed.
https://chat.zulip.org/#narrow/stream/6-frontend/topic/fetching.20message.20history
Reproducer:
* Have some unreads in the Combined feed view.
* Scroll up and select a message that was not part of initial fetch.
* Reload.
* Go a another narrow.
* Come back to combined feed to find your at a random message. This message is actually last message of the current fetch of combined feed view which was returned via `first_unread_message_id`.
=> narrow: Fix combined feed selecting random messages on narrow.

web/src/recent_view_ui.ts
The bug is hard to reproduce, but I was able to reproduce with #30134 and used the same strategy to fix it here.
=> recent_view: Fix no topic found at center of recent view.

zproject/sentry.py
If the value at runtime is actually an int, not a float, we should not try to treat it as a dict.
=> sentry: More gracefully handle a value of 0.

web/src/composebox_typeahead.ts
Fixes this error, which occured when editing DM messages and bringing up the mention typeahead with "@"
https://zulip.sentry.io/issues/5389123227/events/46ab6c6ca68344ac89af7444fa0f8c39/?project=4504556882821120
=> composebox_typeahead: Allow for undefined topic in PersonSuggestionOpts.

web/src/message_list.js, web/src/message_list_data.ts, web/tests/message_list.test.js
It’s unused since commit 748e5b6da6e1e55799add8db76eaa5e512927d3a.
=> message_list: Remove nth_most_recent_id

web/src/message_list.js, web/src/message_list_data.ts
It’s unused since commit c876e12b86e9e2cb22240d0d38921010da7a1765 (#23579).
=> message_list: Remove ids_greater_or_equal_than

zerver/tests/test_push_notifications.py, zilencer/views.py
This switches to dnspython, since it offers the higher-level
`resolve_name` method to look up both A and AAAA records, and set
timeouts.
<details>
</details>
=> zilencer: Disambiguate no MX records from the domain not existing.

puppet/zulip/templates/postfix/main.cf.erb
The default is 10MB[^1]; increasing this to 25MB aligns it with the email mirror's internal limit.
[^1]: https://www.postfix.org/postconf.5.html#message_size_limit
<details>
</details>
=> postfix: Increase the max message size to 25MB.

zerver/lib/import_realm.py
This was added long ago in
38dd9e49de99040969563e4ba47a04de3c001af1
Double-checked that this is right and added a brief mention of what exactly the dependency here is.
=> import: Check off old, redundant TODO about huddle import.

web/src/bootstrap_typeahead.ts
Since `onHidden` is only called once tippy is fully hidden, tippy can fail to call `onHidden` if `onShow` is called before tippy is fully hidden. This hurts us as we want to call `destroy` to remove this tippy instance from DOM.
To avoid this, we `destroy` the tippy instance outside of tippy callbacks which is more reliable since our event handlers call `hide` without fail.
=> bootstrap_typeahead: Fix AssertionError due to `onHidden` not called.

web/src/settings_components.ts, web/src/settings_org.js, web/templates/popovers/send_later_popover.hbs, web/templates/settings/admin_auth_methods_list.hbs, web/templates/settings/auth_methods_settings_admin.hbs, web/templates/settings/settings_checkbox.hbs, web/templates/user_topic_ui_row.hbs
- First commit is to refactor authentication settings code.
- Second commit is to cleanup unnecessary use of `prop-element` class.
<details>
</details>
=> settings: Refactor code to handle authentication methods.

api_docs/changelog.md, zerver/openapi/zulip.yaml
The original feature level updates were made in commit de90d0acdf.
Relevant [CZO discussion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/Consistency.20when.20referring.20to.20events.20in.20API.20docs/near/1806105).
**Notes**:
- Added a link in the API changelog entry to the **Delete a topic** endpoint since there's a **Changes** note there.
- Updated the link in the event description to go to the response for **Get streams** since that's where the detailed information about channel properties is.
- Added a **Changes** note to the event description since it's linked to in the API changelog entry.
<details>
<summary>API changelog entry</summary>
[Current documentation](https://zulip.com/api/changelog)
</details>
<details> …
=> api-docs: Update feature level 256 changelog and changes notes.

puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf
Clients making requests to Zulip with a `Authorization: Basic ...` for an upload in S3 pass along all of their request headers to the S3 backend -- causing errors of the form:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>InvalidArgument</Code>
<Message>Only one auth mechanism allowed; only the X-Amz-Algorithm
query parameter, Signature query string parameter or the
Authorization header should be specified</Message>
<ArgumentName>Authorization</ArgumentName>
<ArgumentValue>Basic ...</ArgumentValue>
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>
```
Strip off all request headers which AWS reports that S3 may read[^1].
Fixes: #30180.
[^1]: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html
Fixes:  …
=> nginx: Strip off request headers which might affect S3's behaviour.

web/styles/rendered_markdown.css
This PR corrects for some over-zealous CSS introduced in #29715:
1) It no longer assumes a paragraph for the spoiler header, which assumption lead to a misplaced spoiler arrow previously.
2) It no longer touches possible margin-left or -right values, such as may be used to style list items.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/spoilers.3A.20collapse.20icon.20misplaced.20when.20header.20is.20a.20list.20item/near/1806485)
| --- | --- |
| ![spoiler-headers-before](https://github.com/zulip/zulip/assets/170719/7e17b33a-3987-40e0-8034-15504649e2a7) | ![spoiler-headers-after](https://github.com/zulip/zulip/assets/170719/aa28b015-d72b-4e87-aea2-939b1250cc2d) |
<details> …
=> spoilers: Style headers in Markdown-neutral way.

puppet/kandra/files/needrestart/zulip.conf
Ksplice keeps the kernel updated without restarts.
=> puppet: Silence "needrestart" nags about kernel upgrades.

web/src/custom_profile_fields_ui.js, web/src/dialog_widget.ts, web/src/user_events.js, web/src/user_profile.js, web/styles/modal.css, web/templates/settings/custom_user_profile_field.hbs, web/templates/user_profile_modal.hbs, web/tests/example4.test.js, web/tests/user_events.test.js
This PR completes the original work done by #27266.
Fixes: #26692
The user-profile modal now shows a confirmation feedback when the user edits a profile field and clicks on the save changes button. This way, the user knows that the changes have been made successfully and can close the modal manually. Previously, the modal would close automatically without any feedback, which could be confusing for the user.
The user-profile modal now shows a confirmation feedback when the user edits a profile field and clicks on the save changes button. This way, the user knows that the changes have been made successfully and can close the modal manually. Previously, the modal would close automatically without any feedback, which could be confusing for the user.
The changes in user/bot profile are also …
=> Update user-profile modal to show confirmation feedback #26692

puppet/kandra/manifests/app_frontend_monitoring.pp
This is a regression introduced in
f246b82f67b62cd95e2c0eb02dd283ac569918d9.
Fixes: 
<details>
</details>
=> kandra: Run rabbitmq cron jobs as root.

web/src/bootstrap_typeahead.ts, web/src/search.ts
We don't use tippy to position the typeahead if a `parentElement` is specified. `non_tippy_parent_element` helps us covey that.
=> bootstrap_typeahead: Rename parentElement for clarity.

templates/zerver/development/dev_tools.html, web/html/5xx.html, web/webpack.config.ts
This can be viewed at http://localhost:9991/webpack/5xx.html on the development server.
=> 5xx: Fix development server preview of 500 error page

web/src/settings_streams.js, web/src/stream_data.ts, web/tests/stream_data.test.js
The 'Select channel' dropdown in 'Add default channels' modal is
the LAST dropdown element on the modal and it does not contain
`data-stream-id` attribute.
.attr('data-stream-id') would return undefined for this element
and as a result the returned `Set` would have its last element a
`NaN` --- passing a `NaN` inside 'data' field of 'channel.post' threw
an error.
We tweaked the selector string to selectively map over the elements with
'data-stream-id' attribute.
Also we removed '.toString()' converting stream-id to a string (stream-id is a
'number' type).
Fixes: 
Before:
https://github.com/zulip/zulip/assets/123243429/8ebb4f4b-58dd-4da5-967f-8139f7787a4e
After:
https://github.com/zulip/zulip/assets/123243429/80435418-7c5e-4f61-8333-44c8ed463bf1 …
=> settings_streams: Fix error thrown when adding default channels.

zerver/lib/message.py, zerver/tests/test_zulip_update_announcements.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/438-release-management/topic/zulip_updates.20items.20of.20note/near/1804031)
I have tested it manually with the case in https://github.com/zulip/zulip/commit/330439a83b7c9d01bfc608a7e82b427f53bae164 and few other cases (with hyphen, digit etc)
<details>
</details>
=> remove_single_newlines: Fix regex to parse list syntax correctly.

web/src/add_stream_options_popover.ts, web/src/admin.js, web/src/bootstrap_typeahead.ts, web/src/buddy_list.ts, web/src/click_handlers.js, web/src/common.ts, web/src/compose_popovers.js, web/src/compose_recipient.ts, web/src/compose_send_menu_popover.js, web/src/compose_tooltips.ts, web/src/copied_tooltip.ts, web/src/drafts.ts, web/src/integration_url_modal.ts, web/src/message_list_tooltips.ts, web/src/personal_menu_popover.js, web/src/playground_links_popover.ts, web/src/popover_menus.ts, web/src/portico/help.js, web/src/portico/tippyjs.ts, web/src/settings_components.ts, web/src/stats/stats.ts, web/src/tippyjs.ts, web/src/user_card_popover.js, web/src/user_group_popover.ts
Names like `delegate`, `Instance`, `Placement`, `Props`, and `ReferenceElement` are much too generic to make sense as named imports.
The downside is that we now need to write `tippy.default(…)` instead of `tippy(…)` (because ES module namespace objects cannot be callable), but that cost is worthwhile.
=> tippy: Use namespace import for tippy.js

web/src/copy_and_paste.ts
If the selection stays inside a message header and there are messages before the message header, our logic thinks `end_id` is message before the header while `start_id` and `end_id` should be that same.
It is best to just let browser handle the copy paste in this case.
Reproducer - select a topic in message header in a stream narrow. There should be a message before the message header.
sentry issue - https://zulip.sentry.io/issues/4007566572/events/d91be0e230b34ecbb01009ba27cb1510/?project=4504556882821120&referrer=next-event
=> copy_and_paste: Fix our logic being confused about selected messages.

web/styles/app_variables.css, web/styles/left_sidebar.css, web/styles/zulip.css
This PR accomplishes two primary goals:
1. It eliminates the use of small bits of padding and fiddly line-height adjustments to make left sidebar rows sized wholly based on their line-height, which will play extremely well with adjustable information density in ways that 1- or 2-pixel offsets would make a massive headache.
2. It consolidates the previous rather random-looking collection of row heights in the left sidebar into just two: 24px and 22px (which are here expressed in their `em` equivalents, thus preparing the left sidebar for adjustable information density).
A secondary goal of this PR is to make sure that there is 1:1 parity between the vertical areas of a row that show a highlight, and vertical areas that are clickable. There are no longer "dead zones" that show the hover …
=> left_sidebar: Normalize row sizes based on line-height.

web/src/popover_menus_data.js, web/styles/popovers.css, web/templates/popovers/left_sidebar/left_sidebar_stream_actions_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_topic_actions_popover.hbs, web/templates/popovers/message_actions_popover.hbs, web/templates/popovers/navbar/navbar_gear_menu_popover.hbs, web/templates/popovers/navbar/navbar_help_menu_popover.hbs, web/templates/popovers/navbar/navbar_personal_menu_popover.hbs
This refactors popover list structure to use a flattened `ul > li` structure along with aria-related additions, enabling screen reader accessibility and announcing menu length and position (`# of n`).
Added ARIA roles:
- `role="menu"` to the parent `<ul>` element, indicating it is a widget offering a list of choices.
- `role="menuitem"`, `role="menuitemcheckbox"`, or`role="menuitemradio"` to child elements based on their function.
- `role="group"` to the theme switcher and topic visibility switcher, identifying them as containers for related menu items.
- `role="none"` to `<li>` elements, removing the implied `listitem` role that conflicts with the parent menu structure.
[CZO Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/nested.20HTML.20lists/near/1799749) …
=> popovers: Flatten nested lists for better accessibility.

web/styles/app_variables.css, web/styles/popovers.css
Tested left, top and bottom placement of emoji popover to check if arrow color is correctly displayed in both dark and light theme.
| --- | --- |
| <img width="456" alt="Screenshot 2024-05-31 at 1 02 59 PM" src="https://github.com/zulip/zulip/assets/25124304/34693d45-becd-4e21-a29f-777cbd75f91f"> | <img width="456" alt="Screenshot 2024-05-31 at 1 02 26 PM" src="https://github.com/zulip/zulip/assets/25124304/e0142de9-a546-4443-aa1b-f12ac4aadbd0"> |
=> emoji_popover: Fix white arrow color in dark theme.

web/src/ui_init.js
Since scroll event is always fired at root level, we don't have control over capturing the event and containing it to the popover if scroll happened inside the popover.
This can lead to unintentional moving of selected message since we try to move the selected message to rendered top / bottom if we receive a scroll event when top / bottom ends are rendered.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/scrolling.20emoji.20picker.2C.20changes.20focused.20message
I tested by narrowing to a topic with 2 messages and opening emoji popover. We correctly don't move the selected message.
When the end of the message list is rendered and last message is not selected; if you open emoji popover and scroll, we don't move the selected message now, I don't see this as a regression …
=> popovers: Fix selected message being changed on scroll inside popover.

web/src/settings_components.ts, web/src/settings_org.js, web/src/settings_preferences.js, web/src/settings_profile_fields.ts, web/src/stream_edit.js, web/src/stream_ui_updates.js, web/src/user_group_components.ts, web/src/user_group_edit.js
Refactor get_property_value and check_property_changed to improve type checking and code readability.
<details>
</details>
=> settings_components: Split functions to improve type checking.

zerver/lib/import_realm.py, zerver/tests/test_import_export.py
Fixes #26369.
After importing, edit history of imported messages is now displayed correctly:
Previously this would either be empty/throw a blueslip error due  to the `"user_id"` being the old value, so not present in the new, imported realm. Or if just `user_id` was fixed, mentions would be broken and show `@Unknown user`.
=> Fix import of message edit history

web/src/list_widget.ts, web/src/message_fetch.js, web/src/message_list_data.ts, web/src/recent_view_ui.ts
We completely rerender recent view when we receive a new message, which is not ideal since it is flashes recent view frequently during the initial fetch.
Since later parts of initial fetch which trigger the flash, only load old messages, they cannot change the latest message of rendered rows in recent view. That means we can just inplace rerender the rendered rows which got updated and don't have to worry about order of rows being changed.
I had a 5k messages populated db which did flash first row with focused underline even after this change due to `inplace_rerender` but after I sent a message in a new topic, I didn't notice any flashing on reload since the first row didn't update in the subsequent fetches.
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/recent.20view.2 …
=> recent_view: Reduce constant flashing of recent view on initial load.

web/src/onboarding_steps.ts, web/src/server_events_dispatch.js, web/src/state_data.ts, web/src/ui_init.js, web/tests/dispatch.test.js
[CZO Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/.60onboarding_steps.60.20-.20.60state_data.60.20field/near/1810939)
<details>
</details>
=> ui_init: Don't store onboarding_steps state_data as current_user_param.

zerver/openapi/python_examples.py
Adds `assert` statements to check if the request succeeded before
validating against the openapi schema.
Improves the robustness of tests in `python_examples.py`.
Fixes: 
<details>
</details>
=> Improve tests in `python_examples.py`.

web/styles/left_sidebar.css
This PR condenses the height of the navigation rows, and expands the height of topic rows.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/consolidating.20heights.20of.20left-sidebar.20rows/near/1811602)
| --- | --- |
| ![left-sidebar-row-adjustments-before](https://github.com/zulip/zulip/assets/170719/00e97e90-58d2-41cd-96f9-737ff4e9edd7) | ![left-sidebar-row-adjustments-after](https://github.com/zulip/zulip/assets/170719/2c066e8f-68b2-416e-9617-79d5293f87b5) |
<details> …
=> left_sidebar: Adjust navbar, topic row-heights.

tools/test-js-with-node, web/src/navbar_alerts.js, web/src/navbar_alerts.ts, web/src/state_data.ts
=> navbar_alerts: Convert module to TypeScript.

web/src/echo.js, web/src/message_events.js, web/tests/compose.test.js, web/tests/echo.test.js, web/tests/server_events.test.js
Commit 50f5cf9ad818b2dfc8dc34f47d7d286a96250c37 (#30227) changed `message_helper.process_new_message` (called by
`message_events.insert_new_messages`) to return a newly created message object rather than mutating the object it was passed. So `echo.insert_local_message` needs to use this new object, fixing a regression where we’d fail to replace a locally echoed message when the server-rendered message came in.
[Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/bug.20.20in.20rendering.20code.20blocks/near/1811900).
=> echo: Use newly created MessageWithBooleans in insert_local_message

templates/corporate/billing/billing.html, templates/corporate/billing/upgrade.html, web/styles/portico/billing.css
**Updates**:
- Removes unused billing CSS rules for template IDs that have been removed as part of redesign of billing pages.
- For fixed price plans, always show the same text about license management. *Note that this does not address the current issues in the implementation of fixed price plan offers combined with the user selecting pay by invoice.*
- Updates both billing and upgrade pages to link to the appropriate help center links based on if it is self-hosted billing or Zulip Cloud billing.
Manually tested links to help center in dev environment when reviewing to make sure there were no visual changes in billing/upgrade pages due to the CSS changes, except for the fixed plan offer case.
**Notes on links**:
- Made sure that these all open a new tab/window, as this seemed nicer than …
=> billing: Update help center links about license management.

web/e2e-tests/lib/common.ts, web/e2e-tests/subscribe_toggle.test.ts, web/src/hash_util.ts, web/src/stream_edit.js, web/src/stream_settings_ui.js, web/src/stream_ui_updates.js, web/src/tippyjs.ts, web/templates/popovers/left_sidebar/left_sidebar_stream_setting_popover.hbs, web/templates/stream_settings/stream_settings_overlay.hbs, web/templates/subscribe_to_more_streams.hbs, web/tests/stream_settings_ui.test.js
---
Fixes: #21869
Continuing the works of: #26049
----
https://github.com/zulip/zulip/assets/73663475/9d79038c-c1a3-444f-8b4e-b9e27f0c1aa2
---
| tooltip| 
|------|
| ![image](https://github.com/zulip/zulip/assets/73663475/9b1eac5f-8e68-4537-aa27-566099ef73d0) |
| Empty view|
|------|
| ![image](https://github.com/zulip/zulip/assets/73663475/06a8b59e-b6e4-46bd-ae3f-dc7f236cd02b) |
---
<details>
</details>
=> Add `Not subscribe` tab in channels settings.

web/src/settings_profile_fields.ts
Fixes how the confirmation modal title is generated for translation for deleting an option or multiple options from a customer profile field that's a list of options.
Confirmed that running `makemessages` updates the strings in `translastion.json` for:
- Removing the untranslatable "{modal_heading_text}" key
- Adding new key with actual strings to translate "{N, plural, one {Delete this option?} other {Delete these options?}}":
| --- | --- |
| ![Screenshot from 2024-06-04 17-50-31](https://github.com/zulip/zulip/assets/63245456/580a8584-d090-4e20-bc85-7442788676e4) | ![Screenshot from 2024-06-04 18-21-02](https://github.com/zulip/zulip/assets/63245456/ce11fdf8-3edc-4e1a-b078-96a31f116cd0)
| --- | --- |
| ![Screenshot from 2024-06-04 …
=> i18n: Fix translated strings for delete profile field option.

web/src/popover_menus.ts, web/src/topic_popover.js, web/src/user_topic_popover.js, web/src/user_topics.ts, web/src/user_topics_ui.ts, web/src/util.ts, web/styles/app_components.css, web/styles/popovers.css, web/templates/popovers/change_visibility_policy_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_topic_actions_popover.hbs, web/tests/util.test.js
This PR adds the new sliding tab animation to the topic visibility switchers (one situated in the message header topic visibility popover, and the other one situated in the sidebar topic actions), along with some functionality changes, such as:
- Hiding the popover, only when the mute topic request gets completed successfully.
- Adding visual feedback via the same sliding animation, on request failure.
Fixes: [CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/UI.20redesign.3A.20theme.20switcher.20.2322803/near/1766900)
<details>
<summary>Light Mode</summary>
| ![image](https://github.com/zulip/zulip/assets/82862779/254813a0-bdc4-423e-97fc-09565314a6ef) | …
=> user_topic_popover: Use new sliding tab for topic visibility switcher.

zerver/lib/push_notifications.py
4430ab9cbee8 changed this, assuming that all servers would send `realm_url` -- however, only servers running that commit do.  Update to accept either `realm_url` or `realm_uri` payload properties.
---
Regression in #29959.
=> push_notifications: Support test notifications from old servers.

web/styles/portico/portico.css, web/third/bootstrap/css/bootstrap.portico.css
Next I think we can remove the `container` class with a little of changes to remove its exisiting uses.
=> css: Remove unused `row-fluid` class.

docs/production/email.md
Django has some somewhat archaic variable names for configuring SMTP that are misleading for users not familiar with Django.  Be more explicit about the correct configuration for both implicit and explicit TLS.
----
Replaces #28271, which I don't have rights to re-push to.
=> docs: Improve STARTTLS / SSL documentation for Django email settings.

web/src/compose_recipient.ts, web/styles/app_variables.css, web/styles/compose.css, web/templates/compose.hbs
The chevron arrow icon before the topic / dm user field now also acts as a go to conversation button. Whenever the functionality is available, the plain icon changes to look and behave like a button. The old go to conversation button on the right of the field is removed.
Fixes: #28697.
(Alternative to #28915)
**When the go to conversation functionality isn't available:**
Light:
Dark:
**When it is available:**
Light:
Dark:
<details>
</details>
=> compose: Make conversation arrow double as a go-to-conversation button.

web/e2e-tests/compose.test.ts, web/e2e-tests/copy-and-paste.test.ts, web/e2e-tests/drafts.test.ts, web/e2e-tests/edit.test.ts, web/e2e-tests/message-basics.test.ts, web/e2e-tests/stars.test.ts, web/src/compose_banner.ts, web/src/compose_notifications.ts, web/src/message_events.js, web/src/narrow.js
CZO deployment to test out UX.
Fixes #29186.
[screen-capture (2).webm](https://github.com/zulip/zulip/assets/56781761/24eda3d2-17fa-4220-839d-7ef46437bb7a)
<details>
</details>
=> compose: Jump to conversation where message was sent.

web/src/compose_banner.ts, web/src/compose_notifications.ts, web/src/compose_setup.js, web/templates/compose_banner/jump_to_sent_message_conversation_banner.hbs, zerver/lib/onboarding_steps.py, zerver/tests/test_onboarding_steps.py
The first commit is from #29211 pulled here for testing the flow.
Show a one-time banner when jump to sent message conversation takes place for the first time.
Fixes: #29575 
<details>
</details>
=> compose: Show a first-time banner for jump to sent message conversation.

locale/fa/LC_MESSAGES/django.po, zerver/lib/streams.py
This catches things like trailing spaces in internationalized default-stream names.
---
The Persian translation was also fixed in Transifex.
=> streams: Move enforcement of stripped-stream-names lower

web/src/i18n.ts, web/src/settings_preferences.ts
This can happen when the user’s configured language is less than 5% translated.  Fixes an assertion failure introduced by commit 6a429603ad8dc1bcdda591d0a12c77dc7f7f97ee (#30261).
=> i18n: Allow `get_language_name` to return `undefined` again

web/styles/widgets.css, web/templates/widgets/poll_widget.hbs, web/templates/widgets/todo_widget.hbs, web/templates/widgets/todo_widget_tasks.hbs
This PR modernizes the layout and presentation of the poll and todo widgets. While this area is in need of a design pass at some point in the future, for now, this corrects a number of sore points on widgets, maximizes the space available for inputs and buttons, and also gets the spacing of these widgets in line with the overall spacing strategy in the rendered markdown area. It also radically improves buttons for internationalization.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/button.2Epoll-option.20width/near/1804563) (button widths)
Note that a follow-up pass will be required on widgets as part of information density (especially the 30.5px height on the header-edit form). That would add too much churn to this already quite large PR. …
=> widgets: Refactor and improve existing Markdown widgets.

zilencer/views.py
This should ideally get a test, but I think writing it is hard because we need the _client_ of the upload to have different `LOGGING_COUNT_STAT_PROPERTIES_NOT_SENT_TO_BOUNCER` from the _server_.
<details>
</details>
=> zilencer: Do not error on old stats which we no longer have.

web/styles/portico/portico.css
Likely an effect of recent error pages refactoring. Tested /help and /api page on desktop and mobile width.
=> portico: Remove extra margin on help page.

web/src/bootstrap_typeahead.ts
This default delay comes off as the typeahead being laggy to the user.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/typeahead.20slow.20to.20appear
=> typeahead: Remove delay when opening / closing typeahead.

web/src/compose_validate.ts, web/src/composebox_typeahead.ts, web/src/people.ts, web/src/pill_typeahead.ts, web/src/typeahead_helper.ts, web/src/user_pill.ts, web/tests/compose_validate.test.js, web/tests/composebox_typeahead.test.js, web/tests/pill_typeahead.test.js, web/tests/typeahead_helper.test.js, web/tests/user_pill.test.js
Commit 33484e7ac38d95e2b4f1879b03fae6a66158bc93 (#29200) added a cache for `remove_diacritics`, but this caching was rendered ineffective by commit 45e9c046d8ef308d94c28ca889f921be6f50c396 (#29650) because it relied on mutating a direct reference to the `User` object. Fix the cache by rearranging the types to preserve that direct reference.
[Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/laggy.20compose.20input/near/1817871).
=> typeahead: Nest User inside UserPillData, UserOrMention

zerver/lib/typed_endpoint_validators.py, zerver/tests/test_bots.py, zerver/tests/test_typed_endpoint_validators.py, zerver/views/user_topics.py, zerver/views/users.py
Migrated `users` and `user_topics` to typed endpoint.
I have not used Pydantic's `URL` type for `payload_url` because `URL` doesn't flag incomplete URLs like `http://127.0..:6000`.
I have also created `check_int_param_in` which is similar to `check_int_in` but `check_int_param_in` raises a `ValueError` not `ValidationError`.
Similarly `check_param_url`, which is similar to `check_url`.
=> Users typed endpoint

web/styles/app_variables.css, web/styles/right_sidebar.css, web/styles/user_circles.css, web/styles/zulip.css
This PR rewrites the user rows using CSS grid, improving alignment and making it so that long status messages, when shown, properly receive an ellipsis.
Only the user rows are touched by this PR; the "In this channel," "Others," and other rows require work (e.g., explicitly setting a font-size on `h5`, which currently just takes the browser default!) that would add too much churn to this PR.
Because these changes are much more like the left-sidebar row rewrites into grid from Fall 2023, and therefore prone to side-effects and possible conditions I might have overlooked, I've marked this for CZO review.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/indentation.20of.20user.20rows.3F/near/1811354)
| --- | --- | …
=> right_sidebar: Rewrite users rows with CSS grid.

templates/zerver/app/index.html, web/src/list_widget.ts, web/src/recent_view_ui.ts, web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/recent_view.css, web/styles/zulip.css, web/templates/recent_view_table.hbs, web/templates/settings/profile_field_settings_admin.hbs, web/tests/list_widget.test.js, web/tests/recent_view.test.js
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/recent.20conversations.20loses.20filter.20checkboxes
Things I tested:
* No topics
* only 1 topic
* Filters work as expected.
* Compose reply works
* Page up / down works
* focus changes correctly when navigating rows at the edge of visible area.
* load more works correctly.
* Recent view -> messages narrow -> recent view correctly preserves row focus
* Loading to `Combined feed` -> recent view correctly sets focus to first row.
* Initial loading indicator when no messages are fetched is displayed correctly.
=> Use `html` as scroll container for recent view.

web/src/compose.js, web/src/compose_actions.ts, web/src/compose_recipient.ts, web/src/compose_setup.js, web/src/compose_state.ts
Fixes #30104.
I set this up so that:
* It only applies to auto-restored drafts, not drafts restored from the drafts menu (or e.g. quote replies)
* Any input change in the composebox makes it so that the draft doesn't auto-close anymore, even if the user makes a change then undoes that change
* The input-monitoring has minimal performance implications, using a `one` event.
=> compose: Auto-close unchanged auto-opened drafts on narrow change.

web/styles/message_row.css, web/styles/zulip.css
It's time. This has no effect at legacy settings (`.more_dense_mode`), but this moves the `font-size` declaration to the `body` selector, paving the way for much easier testing and tweaking as the info-density project gets ready to make its debut.
Along those lines, I've created a new [`area: information density`](https://github.com/zulip/zulip/labels/area%3A%20information%20density) label to accompany this PR, as I suspect there will be more PRs like this one (not to mention issues) that will be about information density in general, and not necessarily tied to one part of the UI or another.
| Before | After (no changes) |
| --- | --- |
| ![body-font-size-before](https://github.com/zulip/zulip/assets/170719/c697e7c7-e73c-496d-a9dc-64c07af9be13) | …
=> info_density: Set calculated font-size on body.

web/styles/message_view_header.css
This PR does a bit of cleanup and then proceeds to express navbar font and icon sizes in ems. There are still pixel values in the area, specifically the `line-height` value tied to the 40px `--header-height` variable. But even within that value, there is a respectable amount of room for font-size and line-height values to grow in that area beyond 16/140.
As a comment in `message_view_header.css` explains, removing `.navbar_title` from the templates will make it easier to consistently work in this area (how long have we dealt with icon alignment issues that differ in narrows but not in other views?), but that's just a bit beyond the scope of the information density project at this point.
| --- | --- |
| …
=> navbar: Express font and icon sizes in ems.

web/templates/presence_row.hbs
This fixes the presentation of emoji in the compact view, where the flexbox for properly aligning emoji was not set. That meant compact view status emoji were more distant and droopy than their show-status counterparts.
The discrepancy was introduced in be4d4085f2f691506f187a3138422293265c3706, but became much more noticeable after the grid rewrites in #30291.
| Compact, before | Compact, after |
| --- | --- |
| ![right-sidebar-compact-before](https://github.com/zulip/zulip/assets/170719/0963f9e1-4787-4a7d-a863-84826110edb2) | ![right-sidebar-compact-after](https://github.com/zulip/zulip/assets/170719/bb147308-836f-4e47-8a75-4f5307662d1a) |
| Show status, before | Show status, after (no change) |
| --- | --- |
| …
=> right_sidebar: Uniformly group user name and status emoji.

help/mastering-the-compose-box.md
Follow up to: #30027
This also fixes a small typo and removes the unnecessary distinction between channel and direct messages.
Before:
Now:
<details>
</details>
=> docs: Update section on Go to conversation button with new icon, etc.

web/src/activity.ts, web/src/activity_ui.ts, web/src/buddy_data.ts, web/src/presence.ts, web/src/server_events_dispatch.js, web/src/ui_init.js, web/tests/activity.test.js, web/tests/buddy_data.test.js, web/tests/dispatch.test.js, web/tests/example4.test.js, web/tests/presence.test.js, zerver/lib/presence.py, zerver/tests/test_presence.py
Implements a prototype for the API discussed in https://chat.zulip.org/#narrow/stream/378-api-design/topic/presence.20rewrite/near/1586819
Commit 1 Adds the necessary `last_update_id` column and `PresenceSequence` model, commit message elaborates on the migration plan
Commit 2 The backend+frontend parts of the system using the above data structure.
This is WIP, so no tests and only tested in the webapp.
What this has:
- Adds the `last_update_id` param and plumbing in the API through the backend and frontend
- Implements what is intended to be an efficient locking mechanism inside `do_update_user_presence`, updating `PresenceSequence` and the related `UserPresence` update in a single SQL query, at the very end of the transaction, ensuring the hot lock only gets held as briefly as possible. …
=> Presence `last_update_id` API 

help/search-for-messages.md, web/src/filter.ts, web/src/left_sidebar_navigation_area.ts, web/src/message_feed_top_notices.ts, web/src/message_parser.ts, web/src/narrow_banner.ts, web/src/search_suggestion.ts, web/styles/left_sidebar.css, web/templates/left_sidebar.hbs, web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs, web/templates/search_operators.hbs, web/templates/tooltip_templates.hbs, web/tests/filter.test.js, web/tests/message_view.test.js, web/tests/search_suggestion.test.js
- Created a new search operator `has:reaction`
- Added search suggestions for the new operator
- Created a new view in the left sidebar for `has:reaction sender:me`
- Updated `web/src/filter.ts` and `web/src/message_parser.ts` to deal with cached messages
- Fixed `message_reactions` undefined by cleaning reactions earlier in the flow.
- Used `zulip-icon-smile` instead of https://feathericons.com/?query=thumbs-up to maintain uniformity with other reaction buttons.
Fixes: [Issue 27328](https://github.com/zulip/zulip/issues/27328)
<details> …
=> Create Reactions View

web/src/compose_notifications.ts, web/src/filter.ts, web/src/scheduled_messages_feed_ui.ts, web/tests/filter.test.js
Fixes two bugs:
When we are in `/near/` topic or dm view then,
1. scheduled message indicator is missing in the conversation.
2. On sending a message in the same topic, the 'jump to sent message' banner is incorrectly shown. Fixes #30341
<details>
</details>
=> compose_banner: Don't show banner if message sent in a near view. 

corporate/lib/stripe.py
Updates type annotation for stripe collection method:
```python
Literal["charge_automatically", "send_invoice"]
```
<details>
</details>
=> stripe: Use comma for collection method Literal values.

web/src/user_topic_popover.js, web/styles/popovers.css, web/templates/popovers/change_visibility_policy_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_topic_actions_popover.hbs, web/templates/popovers/navbar/navbar_personal_menu_popover.hbs
As part of the popover menu redesign, this updates the topic visibility popover to use the new "popover-menu" popover theme and improves accessibility by using appropriate ARIA attributes.
Fixes part of #28699.
| ![image](https://github.com/zulip/zulip/assets/82862779/d951aa1e-070c-46a4-8fd9-76a14f5e9246) | ![image](https://github.com/zulip/zulip/assets/82862779/ea661f05-bff1-4c89-bddd-253fe3bd5b37) |
| ![image](https://github.com/zulip/zulip/assets/82862779/0e726348-051b-4e5f-88d2-09e2eec7c03d) | ![image](https://github.com/zulip/zulip/assets/82862779/538c4c45-5297-49b1-8b1d-235d7119450c) | 
<details> …
=> redesign: Topic visibility policy popover

web/styles/app_variables.css, web/styles/compose.css
This PR corrects for a number of issues that impact the compose box under user-selectable information density:
1. It sizes the collapsed compose buttons relatively for uniform sizing.
2. It converts to em units a critical height/min-height value in the recipient row.
3. It expresses compose-banner dimensions and layout relative to the base font-size in use.
Additionally, there is a small fix to prevent grid blowouts on the recipient box that was causing problems on screens narrower than ~400px.
Fixes all known info-density compose issues that aren't pill-related from #30359.
| Small recipient box, before | Small recipient box, after |
| --- | --- |
| ![small-recipient-box-before](https://github.com/zulip/zulip/assets/170719/545bfc6c-2151-41d6-bddc-a31b3 …
=> compose: Prepare compose box for adjustable info density.

web/src/resize.ts
If the elements are hidden, their margin is still included in calculating the height of buddy list which we don't want.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/right.20sidebar.20bottom.20padding
| --- | --- |
| ![image](https://github.com/zulip/zulip/assets/25124304/9da92863-0b1b-4f3f-b36c-d3ec6da25319)  | ![image](https://github.com/zulip/zulip/assets/25124304/4c9a390c-bb01-4345-87e8-f768760963a6) |
=> resize: Remove height of hidden elements from buddy list height.

web/styles/portico/activity.css, web/styles/portico/portico.css, web/third/bootstrap/css/bootstrap.portico.css
* `.container` class is only used in `/activity/support` and
`/activity/remote/support` pages. It is also used in emails but
it has its own CSS.
* Since the CSS applied is localized and looks good, we just
move the CSS relevant to us to `activity.css` which is used
by both of these pages.
* Searched `"container"`, `<space>container<space>`, `"container<space>` and
`<space>container"` to look for the uses of this class.
=> Move .container CSS from bootstrap to activity.css.

web/styles/portico/portico.css, zerver/lib/markdown/api_return_values_table_generator.py
This first commit adds a table of links for easy navigation of events in API documentation.
The second commit converts the event names in API documentation to lowercase.
<details>
</details>
=> api_docs: Add table of links for easy navigation in events api docs.

web/styles/app_variables.css, web/styles/input_pill.css
Fixed the missing background color which made the input field look disabled.
Before: 
After:
The difference is not quite clear from the screenshots, but becomes clear when seen in a browser.
[CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/invite.20email.20field)
=> invite_user_modal: Fix background color of input field.

web/styles/input_pill.css
Removes the fixed height of the input field in compose DM recipient box. This commit makes the behaviour of recipient compose box equivalent to input pills used else where.
Fixes: #27688.
Before:
After:
<details>
</details>
=> compose_pills: Fix long text overflow in DM recipient box.

web/src/information_density.ts, web/styles/app_variables.css, web/styles/rendered_markdown.css
This PR calculates values necessary to properly fit and vertically align inline-block elements within any given line height and font size combination. Those values are then applied as an example to inline emoji, though the techniques and values here are strong candidates to be extended to other blocks appearing within the message area (e.g., todo widget checkboxes, `<time>` elements). 
Additionally, previous fiddly `top` and `margin` values applied to emoji have been removed here, so that similarly fiddly adjustments are made unnecessary as users adjust information density values. A commit added on 11 June 2024 now also restores the oversize-emoji look that Zulip is known for, but critically without disturbing the surrounding lines of text (updated screenshots below).
[CZO …
=> info_density: Calculate values for vertical alignment and apply to emoji.

web/src/sidebar_ui.ts, web/src/stream_list.ts, web/src/tippyjs.ts, web/src/ui_init.js, web/src/unread_ui.ts, web/styles/right_sidebar.css, web/styles/search.css, web/styles/zulip.css, web/templates/navbar.hbs, web/templates/tooltip_templates.hbs
Unread indicator is not visible on the toggle button in 1st screenshot since it seems like that is more distracting that helpful when left sidebar is visible.
=> Add button to toggle left sidebar.

web/src/buddy_list.ts
This check doesn't work with the `me` user, because that user is always at the top of the all users list, and therefore `new_pos_in_all_users` will always be 0 and never `render_count`. It's possible this was already broken before the split buddy list change.
We can remove this check because `insert_new_html` is only called when we definitely want to insert html. It's only called from `insert_or_move`, and for moves we always remove the user we're moving/replacing before the insert.
Fixes both these issues:
* [name disappears in right sidebar](https://chat.zulip.org/#narrow/stream/9-issues/topic/name.20disappears.20in.20the.20right.20sidebar/near/1817995)
* [buddy list DM with yourself](https://chat.zulip.org/#narrow/stream/9-issues/topic/buddy.20list.20DM.20with.20yourself/near/1821121)
=> buddy list: Remove buggy check preventing updates to me.

web/src/user_profile.js
Sentry reporting discovered that if the user was viewing the channels tab for a bot when the bot's owner was changed (or various other live-updates), we'd throw an exception trying to access the original_values object for the manage-user/bot tab.
This code is fragile and messy, but probably a framework change is the most expedient path to fixing it.
=> user_profile: Fix live-update exception when viewing channels tab.

web/styles/portico/portico.css
Since left sidebar was in fixed position, mac's rubber-band scroll effect was not working on it while it was working for others making the bounce look weird.
Fixed by letting it bounce with the rest of the elements on the page.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/grey.20stripe.20in.20the.20help.20center
Tested /help and /api pages.
=> help: Fix left sidebar not bouncing on mac.

web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/rendered_markdown.css
<details>
<summary>
Currently, there's a block of css rule that sets a group of elements to have a dark border color in `dark_theme.css` :
</summary>
</details>
This PR adds a new rule that overrides that specific css rule. This new rule specifically targets tables inside message/ chat and set a brighter color border for them.
Fixes zulip#29856
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/table's.20border.20color.20is.20still.20black.20in.20darkmode)
> _last updated: **2 May 2024**_
The new dark mode table is under these new effect(s): `opacity: 0.2`
| ![image](https://github.com/zulip/zulip/assets/108744694/b8debaba-c3fa-4392-8371-f0170fe79738) | …
=> dark_theme_css: Fix border color for tables in message/chat.

api_docs/changelog.md, zerver/openapi/zulip.yaml
Updates:
- In the API changelog, removes colons in the feature level lines for consistency. The majority of these lines end without a colon.
- For changes notes in the API docs, we want to have only the most recent change entry to start with `**Changes**:`. Older entries should follow as separate paragraphs.
- Changes notes that I've done more editing on than removing extra **Changes** on are shown in screenshots below.
<details>
<summary>realm_user op: remove event</summary>
[Current documentation](https://zulip.com/api/get-events#realm_user-remove)
</details>
<details>
<summary>user_list_incomplete in client_capabilities parameter</summary>
[Current documentation](https://zulip.com/api/register-queue#parameter-client_capabilities)
</details> …
=> api-docs: Clean up of changes and changelog formatting.

web/src/message_view_header.ts
Since spectators cannot mute channels or topics, the combined feed description for spectators is tweaked to exclude that part.
Fixes #30321
<details>
</details>
=> navbar: Tweak Combined feed description for spectators.

zerver/openapi/zulip.yaml
Updates the various descriptions for `can_mention_group` user group setting in the API docs to be a bit clearer and more concise.
Also, adds more links to the [group-setting values](https://zulip.com/api/group-setting-values) article and to the help center article on [mentioning a user or user group](https://zulip.com/help/mention-a-user-or-group).
@sahil839 - Pinging you for a review to make sure that the text for these is still accurate.
@Vector73 - Pinging you for a review as you've been looking at this descriptions as well. Note this doesn't fix the issue with the endpoint parameters not rendering the `GroupSettingValue` schema properly.
---
<details>
<summary>Get user groups return value</summary>
[Current …
=> api-docs: Clean up descriptions of can_mention_group user group setting.

help/include/sidebar_index.md, help/left-sidebar.md
This is intended to be a mergeable starting point for this page. As follow-ups, we'll want to add documentation for:
<details>
<summary>
Screenshot
</summary>
</details>
[CZO discussion
](https://chat.zulip.org/#narrow/stream/101-design/topic/left.20sidebar.20toggle.20icon/near/1823029)
=> help: Add page documenting the left sidebar.

web/src/stream_edit.js
If a user popover is open in stream settings, and user presses `down/up` arrow to view settings for a different stream, the user popover stay open.
Why we need to explicitly hide it?
We have click handlers to hide the popover and `data-reference-hidden` to hide the popover if the reference goes offscreen via scrolling.
In this case, those events don't fire, there is no reason for tippy to check if reference is visible and thus show / hide the popover.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Persistent.20user.20card.20popover.20in.20stream.20modal
Reproducer:
https://chat.zulip.org/user_uploads/2/6c/xnurQEaaNvd45VD6yO6UGcGM/Screencast-from-13-06-24-121001-AM-IST.webm
=> stream_edit: Fix user popover permanently displayed in stream settings.

tools/test-js-with-puppeteer
On puppeteer test failure, screenshots are generated which are helpful in debugging.
Earlier, the instruction to see those screenshot in github actions was not the easy way. It linked to a github doc which suggests to make API calls using artifact ID (which can be confusing to find) to download the artifact and extract it to see the screenshots.
Before:
> See https://docs.github.com/en/rest/reference/actions#artifacts for information
on how to view the generated screenshots, which are uploaded as Artifacts.
Screenshots are extremely helpful for understanding puppeteer test failures.
The easier way is to download the artifact directly using the download URL present in the "Store puppeteer artifacts" step of the job.
<details> …
=> puppeteer_tests: Update the instruction to view generated screenshots.

web/styles/app_variables.css
This restores a value that was erroneously changed in #30388.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/group.20members.20section.20is.20broken/near/1825650)
<details>
</details>
=> user_groups: Restore correct max-height value.

web/src/resize.ts
Earlier, autosize wasn't updated for the compose box after resetting its `max-height`, so in cases where the older `max-height` was more than the height, and the current max-height was less than the height, the compose box would not be scrollable.
We now always update the autosize after resetting the max-height.
Fixes: [CZO issue thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/scrolling.20not.20working.20in.20compose.20box)
<details> …
=> compose: Fix bug where compose box was sometimes not scrollable.

web/styles/compose.css, web/templates/compose.hbs
The messagebox-wrapper div is removed, and it's only style `flex: 1` is applied to the messagebox div. The `height: 100%` and `margin-top: 5px` styles on the messagebox div were earlier causing it to move 5px down, outside the messagebox-wrapper div, when the compose box was expanded.
Fixes: [CZO issue report thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/subtle.20layout.20shift.20when.20expanding.20compose.20box/near/1825379)
<details> …
=> compose: Fix bug causing layout shift on expanding compose box.

web/styles/portico/portico.css, zerver/lib/markdown/api_return_values_table_generator.py
Following up on updates in #30413, updates the CSS and `render_events` code for clarity.
**Notes**:
- Uses templates for parts of the events documentation where we're added HTML for CSS classes/styling as well as links.
- Creates two helper functions (`generate_event_strings` and `generate_events_table`) to clarify the logic / process of generating the documentation for each event and the events table.
- Uses nesting in CSS rules so that they are more specific and updates some of the class names to be clearer.
---
<details>
<summary>Events table and first few events</summary>
</details>
<details>
<summary>user_settings op: update event</summary>
[Current documentation](https://zulip.com/api/get-events#user_settings-update)
</details>
---
<details> …
=> api-docs: Extract functions/templates for generating events documentation.

web/styles/app_variables.css, web/styles/informational_overlays.css
The first regression detailed #30428 was because a table selector in `dark_theme.css` was deprecated. Specifically in this [commit](https://github.com/zulip/zulip/commit/dae4c28b5bf65de0945e76743ebaa47d2fcb1103). So, these tables basically don't have the correct formatting for their border-color.
This fix largely follows the approach used in the previous CSS refactor for other tables in #29859. Which is to add new CSS variables into `app_variables.css` specifically targeting these three tables in `keyboard_shortcuts.hbs`, `markdown_help.hbs`, and `search_operators.hbs`. Instead of targeting each table individually, the selector targets a wrapper div one level higher, using the `.informational-overlays .overlay-body` class. I think this is a nice level of abstraction because …
=> informational_overlays: Fix CSS for tables in info_overlay.

web/styles/app_variables.css, web/styles/informational_overlays.css
This assumes the width of the informational overlay at the largest viewports to be the canonical reference. Future adjustments can be made gracefully care of a CSS variable.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/help.20modal.20.22snap.20back.22/near/1821161)
| --- | --- |
| ![informational-overlay-before](https://github.com/zulip/zulip/assets/170719/bdd294c5-5913-4f70-9060-c1d9a1445922) | ![informational-overlay-after](https://github.com/zulip/zulip/assets/170719/684647a0-3a50-4132-8aa7-8e565784570f) |
<details> …
=> informational_overlay: Constrain to variablized width.

web/styles/message_view_header.css, web/templates/message_view_header.hbs, web/templates/navbar_icon_and_title.hbs
In addition to simplifying the code in this area, this has the effect of correcting vertical alignment of icons on views. There is also now the same amount of space between the view title and description as exists between channel titles and descriptions.
Note that the description portion has been moved from `navbar_icon_and_title.hbs` and into `message_view_header.hbs`. That is so that the `narrow_description` shares the same flexbox relationship between channels and views--though clearly there is room for additional cleanup and simplification here.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/icons.20sagging.20on.20.60main.60/near/1825971)
| View headers, before | View headers, after |
| --- | --- |
| …
=> navbar: Consolidate view, channel structures and styles.

tools/setup/postgresql-init-dev-db
These are necessary if the path contains spaces.
=> postgresql-init-dev-db: Add missing quotes.

zerver/lib/events.py, zerver/models/realms.py, zerver/models/users.py, zerver/tests/test_event_system.py, zerver/tests/test_events.py, zerver/tests/test_home.py, zerver/tests/test_subs.py
This PR updates code to prefetch realm group settings like "can_create_public_channel_group" only when computing settings for "/register" response in `fetch_initial_state_data` by refetching the realm object with `select_related` instead of fetching those settings in UserProfile query.
This change is done because we do not need to prefetch these settings for every UserProfile object and for most of the cases where these settings are actually accessed, we can afford extra query like when checking permission to create streams. But we cannot afford one query extra for each setting when computing these settings for "/register" response, so we re-fetch the realm object with select_related leading to only one extra query.
The query count changes in tests are -
- Query count increases by two …
=> realm: Prefetch group settings only for "/register" response.

help/emoji-and-emoticons.md, help/include/legacy-log-in.md, help/linking-to-zulip-website.md, tools/linter_lib/custom_check.py
mdxjs does not allow autolinks.
See https://github.com/mdx-js/mdx/issues/1049.
We also added a linter check for the same.
Preparatory commit for #30451.
Fixes: 
<details>
</details>
=> help: Do not allow autolinks for help center docs.

web/tests/hash_util.test.js, zerver/lib/push_notifications.py, zerver/lib/url_decoding.py, zerver/tests/fixtures/message_link_test_cases.json, zerver/tests/test_url_decoding.py
https://github.com/zulip/zulip/pull/30404#discussion_r1640557709
> I feel like it would be better for this to be an algorithm that uses urllib for parsing the full link into search operand/operator pairs, and then doing checks on those operators being exactly one of the specific formats for a said link.
> We don't currently do this in the server, but it might make sense to have a new function in a new file zerver/lib/url_decoding.py for this logic, with its own little test suite...
**operand/operator pairs**
I didn't actually use a data structure in  the PR to store operator-operand pair because I think we won't be benefiting much in that way because we still need to store the position at which the operator occurs instead of just verifying that certain operator and operator should …
=> url_decoding: Add 'is_same_server_message_link' function.

tools/test-js-with-node, web/src/message_fetch.js, web/src/message_view.js, web/src/navigate.js
Fixes #14971
Instead of taking user to top / end of fetched history, we take
user to the first / last message of the narrow.
We simply check our cached history if we have the data for the
jump, if not, we ask server for the data.
Tested by simply pressing `fn + left / right arrow` on mac in
combined feed and topic narrows. Also, reduced message_fetch
constant values to be all single digital to check if the -
data not in cache -> fetch data -> select message logic works well.
=> Take user to top / end of feed on home / end keypress.

web/e2e-tests/stream_create.test.ts, web/src/settings_config.ts, web/src/stream_create.js, web/src/stream_edit.js, web/src/stream_settings_components.js, web/src/user_group_components.ts, web/src/user_group_create.js, web/src/user_group_edit.js, web/styles/settings.css, web/styles/subscriptions.css, web/templates/stream_settings/selected_stream_title.hbs, web/templates/stream_settings/stream_creation_form.hbs, web/templates/stream_settings/stream_privacy_icon.hbs, web/templates/stream_settings/stream_settings.hbs, web/templates/stream_settings/stream_types.hbs, web/templates/user_group_settings/user_group_creation_form.hbs
| panel 1 | panel 2 |
| -------- | -------- |
| ![image](https://github.com/zulip/zulip/assets/73663475/cb6b0513-3951-4c7d-8ae2-62d28f1b0cf0) | ![image](https://github.com/zulip/zulip/assets/73663475/1abbadf1-1bf1-426a-8c54-7e6461a033ef)|
-----
| panel 1 | panel 2 |
| -------- | -------- |
| ![image](https://github.com/zulip/zulip/assets/73663475/a41b64ab-6c8d-4d6b-b8ee-64bfe595a557) | ![image](https://github.com/zulip/zulip/assets/73663475/d092addf-6a6e-4765-a915-34800f422641) |
- ###  Advance configuration:
| img | img |
| -------- | -------- |
| ![image](https://github.com/zulip/zulip/assets/73663475/8fc8a08d-3c40-471d-a559-7bb196a3a7c3) | ![image](https://github.com/zulip/zulip/assets/73663475/edf94696-9fc4-4e40-ba86-aaa5f3447907) |
-----
- The issue description doesn't include a …
=> stream_settings: Restructure stream creation panel.

web/src/search_suggestion.ts, web/tests/common.test.js, web/tests/search_suggestion.test.js
Fixes: https://github.com/zulip/zulip/issues/30320
Currently, there are 2 lists of filterers
* one for non-spectators ([here](https://github.com/zulip/zulip/pull/30330/files#diff-426bbd5e4a5470f26a21e1b64d96f3d668b91dc2602cb51c77786126162374f2R842))
* one for spectators ([here](https://github.com/zulip/zulip/pull/30330/files#diff-426bbd5e4a5470f26a21e1b64d96f3d668b91dc2602cb51c77786126162374f2R858))
When you type `is:` in the search bar as a spectator, it currently suggests "Direct messages" (Issue 30320) because [get_operator_suggestions](https://github.com/zulip/zulip/pull/30330/files#diff-426bbd5e4a5470f26a21e1b64d96f3d668b91dc2602cb51c77786126162374f2L857) is adding the suggestion.
This PR
* Removes the `is:dm` suggestion from `get_operator_suggestions` 
* And since …
=> search-suggestions: Remove is:dm suggestion from get_operator_suggestions

api_docs/changelog.md, api_docs/construct-narrow.md, help/search-for-messages.md, version.py, web/src/filter.ts, web/src/narrow_banner.ts, web/src/search_suggestion.ts, web/templates/search_description.hbs, web/templates/search_operators.hbs, web/tests/filter.test.js, web/tests/message_view.test.js, web/tests/search_suggestion.test.js, zerver/lib/narrow.py, zerver/lib/narrow_predicate.py, zerver/lib/topic_sqlalchemy.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_fetch.py
Create the is:followed search operator.
Fetch all messages that are from followed topics
using exists.
Update API documentation and changelog.
Co-authored-by: Nimish <medatwalnimish@gmail.com>
Fixes #27309.
Added `Followed` enum `3` to `visibility_policy` of `user_topics` endpoint in `zulip.yaml` .
Screenshots.
Top of view
Search suggestions
Help menu.
Api Change log
construct-narrow documentation
<details>
</details>
=> search: Add is:followed filter.

web/src/add_stream_options_popover.ts, web/src/left_sidebar_navigation_area_popovers.js, web/src/popover_menus.ts, web/src/stream_popover.js, web/src/topic_popover.js, web/styles/left_sidebar.css, web/styles/popovers.css, web/styles/zulip.css, web/templates/popovers/left_sidebar/left_sidebar_all_messages_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_drafts_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_inbox_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_recent_view_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_starred_messages_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_stream_setting_popover.hbs
As part of the popover menu redesign, this PR redesigns all the remaining left sidebar popovers using the new "popover-menu" tippy theme and improves accessibility by using appropriate ARIA attributes.
Fixes part of https://github.com/zulip/zulip/issues/28699.
| Inbox | ![Screenshot 2024-06-13 at 6 05 45 PM](https://github.com/zulip/zulip/assets/82862779/7e650a7f-6027-472a-b9a6-ebd759968965) | ![Screenshot 2024-06-13 at 4 49 16 PM](https://github.com/zulip/zulip/assets/82862779/5aa61daf-72e0-4fa7-9375-f7c865cdc12e) |
| Combined Feed | ![Screenshot 2024-06-13 at 5 59 29 PM](https://github.com/zulip/zulip/assets/82862779/7e0e1578-b415-4bf6-9db6-774bc97b4656) | ![Screenshot 2024-06-13 at 4 49 …
=> redesign: Left sidebar popovers.

web/src/realm_icon.ts, web/src/realm_logo.ts, web/src/tippyjs.ts, web/src/ui_init.js, web/styles/app_variables.css, web/styles/zulip.css, web/templates/navbar.hbs
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/left.20sidebar.20toggle.20icon
| --- | --- |
| <img width="811" alt="Screenshot 2024-06-18 at 12 09 21 AM" src="https://github.com/zulip/zulip/assets/25124304/6d54468d-de7c-47ee-8059-cc1c50f5fa4d"> | <img width="811" alt="Screenshot 2024-06-18 at 12 08 44 AM" src="https://github.com/zulip/zulip/assets/25124304/acec85c8-34a5-4730-bbce-0bb758496fb6"> |
Search open.
Tested:
* Light / dark theme
* Full width layout 
* Search box
* left sidebar expanded / non-expanded states.
* with or without a realm logo icon set.
* Updating the realm logo icon.
* Small height window.
=> Expand middle column to occupy the unused space when left sidebar is hidden.

web/src/settings_components.ts, web/templates/settings/profile_field_choice.hbs, zerver/tests/test_custom_profile_data.py
This PR does not make any behavioural changes, but since we want to discuss what the exact behaviour should be for #29880, this is a seperate PR consisting of cleanups. 
There is one behaviour change on this PR where we use `tippy` for the select field delete button
<details>
</details>
=> Cleanup tests for custom profile fields + small refactors

web/styles/app_components.css, web/styles/app_variables.css, web/styles/informational_overlays.css, web/styles/settings.css
The regression was because tables that used `.table-striped` CSS (`/app_components.css` starts at line 720) depended on the deprecated `dark_theme.css` rule at #29859 for its border-color value in dark theme. These tables are used primarily at the personal and organizational settings menu at /#settings. See full git grep:
`git grep ".table-striped"`:
<details>
</details>
The fix that I've included in this PR is to switch the border-color value for `.table-striped` for a new variable in `app_variable.css`. This approach is fairly in line with how it is done at #29859, where CSS variables are used more specifically for particular elements.
Let me know whether this is at the right level of granularity that we want. For example, `.table-striped` is used in a wide range of menus, if we want …
=> app_components: Fix CSS for tables in settings menu.

web/src/server_events_dispatch.js, web/tests/dispatch.test.js
Owing to logic added in #30050, which accounts for the legacy line- height value, toggling dense mode requires recalculating the typography vars--otherwise, a non-legacy line-height value will not be picked up until a refresh.
<details>
</details>
=> server_dispatch: Calculate typography vars on dense_mode.

web/styles/left_sidebar.css
This removes a now-unnecessary style block that restores space to the righthand side of DM partners, so that collisions with unreads as shown in the Before screenshot below are no longer possible.
Fixes part of #30359 
Note the 1:1 DM to Prospero.
| --- | --- |
| ![main-morning-of-2024-06-18](https://github.com/zulip/zulip/assets/170719/129dd2bc-ef3f-4ecb-90a3-0673a5c39437) | ![dm-partners-after](https://github.com/zulip/zulip/assets/170719/9d6652d2-045d-4eac-bf16-e0e6c05fd444) |
<details> …
=> left_sidebar: Restore righthand padding to DM partners.

web/src/left_sidebar_navigation_area.ts, web/src/sidebar_ui.ts, web/styles/left_sidebar.css, web/templates/left_sidebar.hbs
This PR adds the Views label in the left side bar for the spectators without it being collapsible.
Fixes #30324 
<details>
</details>
=> left sidebar: Add Views label for spectators.

web/src/user_group_components.ts, web/src/user_group_create.js, web/styles/subscriptions.css
this PR address the comment on #29433:
- Update user group panel titles _posted by @sujalshah-bit in https://github.com/zulip/zulip/issues/29433#issuecomment-2174264462_
|  Panel A|  Panel B|
|---|---|
| ![image](https://github.com/zulip/zulip/assets/73663475/7d4df38d-18d9-4e9e-9fb1-dd8ca50d09b5)  | ![image](https://github.com/zulip/zulip/assets/73663475/8cac0d9e-d1e8-4c3a-9b44-b4be1b665aa9)  | 
- Reduce Vertical margin between `default-streams` and `announce-streams` _posted by @sujalshah-bit in https://github.com/zulip/zulip/issues/29433#issuecomment-2174256476_
|  Before  |  After |
|---|---|
| ![image](https://github.com/zulip/zulip/assets/73663475/5816c597-35fb-487a-9f9a-509e3ba097c2)  |  ![image](https://github.com/zulip/zulip/assets/73663475/a1db8cb1-e38b-4a15-a247-681e526ee467) | …
=> Follow up restructure stream creation panel PR

templates/zerver/app/index.html, web/src/unread_ui.ts, web/styles/print.css, web/styles/typing_notifications.css
Previously, the typing notifications used to appear between the message list and the mark as read banner in a thread. This would cause the banner to shift down whenever someone starts typing, and shift back up if everyone stops typing.
This frequent bouncing of the banner could be distracting, and hence, is fixed by moving the typing notifications to below the mark as read banner.
[CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/Typing.20notifications.20cause.20bouncing.20banner/near/1778791)
<details> …
=> typing: Move the typing notifications to below the mark as read banner.

web/src/compose_actions.ts, web/src/tippyjs.ts, web/styles/app_variables.css, web/styles/compose.css, web/templates/compose.hbs
We now right align recipient input (even at very narrow widths) and banners to the textbox, and move the close button to the absolute top right corner of the compose box, updating the icon to be slimmer, bigger and purplish, and adding a background highlight on hover.
This involved refactoring the send control area width into a responsive css variable, and simplifying the html structure of the compose box.
Fixes: #28792.
Before:
After:
<details> …
=> compose: Rework alignment of upper elements, and redesign close button.

web/src/tippyjs.ts
As reported in a bug report, the tooltip on the DM collapse/expand toggle was reappearing after switching in and out of the browser window.
This PR destroys the current instance of the tooltip when it is hidden. This clean up ensures that the tooltip does not appear again unless the triggered explicitly by the user.
Fixes: [Issue reported on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Expand.2FCollapse.20direct.20messages.20tooltip.20popping.20constantly/near/1768745)
Screencast as uploaded by the user:
Steps to reproduce:
1) Open the "All messages" section.
2) Click on the expand/collapse dm button.
3) Then hover over the button to show the tooltip.
4) Then hover anywhere on the screen and then change window.
5) Return back to CZO window
(This bug was reported on a Macbook …
=> pm_section: Fix ghost tooltip on collapse/expand DM toggle.

web/templates/popovers/change_visibility_policy_popover.hbs
A bug was observed on Safari where the visibility policy switcher popover was shrinking beyond the width of the policy switcher, hiding a portion of the switcher component.
This was due to the presence of the `width: min-content` on the popover for supporting dynamic popover menu sizing based on the content of the menu items, in tandem with some issue in Safari since it worked fine on other browsers.
This commit adds the `.popover-menu-label` class to the visibility policy switcher's label to enforce `max-content` width on the label element, which in turn fixes the popover shrinking issue on Safari.
Fixes: [Issue reported on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/visibility.20popover.20cut.20off.20on.20Safari.20.28macOS.20and.20iOS.29/near/1828494) …
=> visibility_policy_popover: Fix popover shrinking bug on Safari.

api_docs/changelog.md, api_docs/rest-error-handling.md, zerver/openapi/zulip.yaml
**Notes on changes**:
- Updates the main description of the API error handling article so that the `code` key in the error reponse is more accurate.
- Adds a bullet point to the API changelog for feature level 76 about the `code` key being consistently in all error responses.
- This is based on commit 8b9011dff8, which completed the migration to JsonableError, at which point the API feature level was already set to 75, and not yet set to 76.
- Alternatively, we could just use the major release (Zulip 5.0) for when clients can expect all error responses to contain a `code` key.
- Also, revises the other error related feature level 76 entries in the API changelog.
- Updates the descriptions of the shared error responses documented on the error handling page to include information about any …
=> api-docs: Clarify error response keys and handling documentation.

web/src/inbox_ui.ts, web/src/message_list_view.js
The `get_all_rows` part in the above screenshot is removed after this change.
On 6x CPU slowdown:
| --- | --- |
| <img width="382" alt="Screenshot 2024-06-20 at 1 55 14 AM" src="https://github.com/zulip/zulip/assets/25124304/1fc93147-a1fe-443e-8eb1-9cf077ae9e29"> | <img width="382" alt="Screenshot 2024-06-20 at 1 54 59 AM" src="https://github.com/zulip/zulip/assets/25124304/7945d022-121a-4d68-a0a6-328e1ca670d8"> |
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/scrolling.20lag
=> inbox_ui: Don't process scroll events if Inbox is not visible.

web/src/pm_list.ts, web/styles/dark_theme.css, web/styles/left_sidebar.css
Fixes: #30467
[CZO Thread](https://chat.zulip.org/#narrow/stream/101-design/topic/DM.20-.20active.20narrow.20filter.20background.20color.20dark.20mode/near/1829356)
This PR also take two refactor commits from #30332 and puts it as the first two commits so it's a bit easier to review and merge.
There's also one more commit that removes unused CSS applying `background-color` for dark theme: [fc90036](https://github.com/zulip/zulip/pull/30468/commits/fc90036d3e9a04bb54fe5ddc52dec07040883c9f). This would require some regression testing.
It would be good to get this PR merged before #30332 .
<details>
<summary>Home page screenshot before the PR</summary>
</details>
<details>
<summary>Home page screenshot after the PR</summary>
</details> …
=> Make the active narrow background color for DM section consistent

zerver/lib/types.py, zerver/tests/test_custom_profile_data.py, zerver/views/custom_profile_fields.py
Convert `custom_profile_fields.py` to use
`typed_endpoint`.
Use `TypedDict` from `typing_extensions` instead of `typing`,
to support Pydantic's type checking.
Fixes: 
<details>
</details>
=> custom_profile: Convert to typed_endpoint.

web/src/filter.ts, web/src/search_suggestion.ts, web/templates/search_description.hbs, web/templates/search_list_item.hbs, web/templates/user_pill.hbs, web/tests/search.test.js, web/tests/search_suggestion.test.js
Fixes #23365. Still need to work on some puppeteer tests.
The first commit is pulled from https://github.com/zulip/zulip/pull/26803
=>  Show user pills in search typeahead dropdown even after user is selected

web/src/list_widget.ts
This bug can be reproduced by scrolling anywhere where list widget is used except recent view.
`$scroll_container` was used before
371cd0da6cc4da913d05c0936a6e32458daa652b
to listen to scroll events which was incorrectly replaced by `opts.$simplebar_container` in the above commit. To fix this, we use the same function `scroll_util.get_scroll_element` to get the correct scroll element.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Scrolling.20user.20list
=> list_widget: Fix more elements not rendered on scrolling to bottom.

web/styles/app_components.css
The margin properties in question were getting overridden by other css, so they were not important. The width was not making a difference in case of channel filter, since its parent was a flexbox. For the topic list, the width was getting overriden by
`#stream_filters .input-append.topic_search_section input`.
This one was made during #30332, but pulling this out into another PR to make it easier to review
Fixes: 
| --- | --- |
| <img width="505" alt="current channel filter" src="https://github.com/zulip/zulip/assets/13910561/88da3e35-babd-4280-9131-9538e88b3d47"> |  <img width="505" alt="new channel filter" src="https://github.com/zulip/zulip/assets/13910561/1478fea2-6bd7-41d3-837f-c25f9022bb08">
| --- | --- |
| …
=> css: Remove unused css for channel & topic list filter.

web/styles/app_variables.css, web/styles/compose.css
For the compose control buttons, the compose close button, and the send later vdots button, we show the focus ring only on `focus-visible` and not on `focus`.
Fixes part of: #27117.
css: Redefine `--color-outline-focus` for dark theme.
The css variable `--color-outline-focus`, which affects focus rings throughout the app, now has a different value defined for the dark theme but this should have no visible effect, and help clean up the code.
This is a prep commit for the next, which shows focus rings only on `focus-visible` and not on `focus` for composer buttons.
<details> …
=> compose: Show focus ring on buttons only when using keyboard navigation.

web/e2e-tests/message-basics.test.ts, web/e2e-tests/navigation.test.ts, web/src/click_handlers.js, web/src/pm_list.ts, web/src/pm_list_data.ts, web/src/resize.ts, web/src/stream_list.ts, web/src/tippyjs.ts, web/styles/left_sidebar.css, web/templates/left_sidebar.hbs, web/templates/tooltip_templates.hbs, web/tests/pm_list.test.js
This is a partial rename for `private` to `direct` mainly for the left sidebar. This only does renames for code encountered while working on #30332 and does not attempt the complete rename.
I've also hyphenated the relevant attributes during the rename.
There are two commits here that are not renaming commits:
1. c1ef62d74cf957401f3a8a3044a089a2d8651a29: Removes unused `toggle_private_messages_section` class. A `git grep` would show you two occurrences for this name in `pm_list.ts` and `click_handlers.js`, but in that case `toggle_private_messages_section` is a function inside `pm_list` which is unrelated to the the html class.
2. bca302f12cd03bc45fc528c4441d7526a7d82a06: Remove unused `more_private_messages_sidebar_title` css. There were some css rules for …
=> Rename `Private` to `Direct` for left sidebar (Partial)

zerver/lib/narrow.py, zerver/tests/test_message_fetch.py, zerver/views/message_fetch.py, zerver/views/message_flags.py, zilencer/management/commands/profile_request.py
Migrated `message_fetch` to `typed_endpoint`.
Removed the old `narrow_parameter` as we have shifted to the new `NarrowParameter` Pydantic Object.
This new object provides better error messages for data validation, hence changed the error messages in `test_message_fetch`. 
`num_before` and `num_after` are required parameters, added them to all the calls of `get_messages_backend`.
Earlier we were using the type `OptionalNarrowListT` for all functions
that required "narrow" as a parameter.
This commit changes all the functions accepting a "narrow"
to use a list of the new `NarrowParameter`
instead of `OptionalNarrowListT` which is a list of dicts.
=> message_fetch: Convert to typed_endpoint.

web/templates/markdown_timestamp.hbs, web/tests/rendered_markdown.test.js
The space wasn’t visible because it was narrower than the padding on `.rendered_markdown time`, but it showed up in copy-and-paste.
=> markdown_timestamp: Remove incorrect space

web/styles/app_variables.css, web/styles/zulip.css
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/left.20sidebar.20toggle.20icon
| --- | --- |
| ![image](https://github.com/zulip/zulip/assets/25124304/9a39c6d8-a609-40e7-8865-79b72d1b119a) | <img alt="image" src="https://github.com/zulip/zulip/assets/25124304/4451f1c4-8e99-420f-9868-0a5d1fd711ad"> |
| --- | --- |
| ![image](https://github.com/zulip/zulip/assets/25124304/3fe4f4f5-702a-491e-8818-08549050f56b) | ![image](https://github.com/zulip/zulip/assets/25124304/21a0eb24-27aa-4c29-a4fb-d8cb9f5242ac) |
| --- | --- |
| ![image](https://github.com/zulip/zulip/assets/25124304/672c193e-fe3f-4543-bd6d-30fca35fc18a) | ![image](https://github.com/zulip/zulip/assets/25124304/c006355b-e369-46a2-aaad-129c265312d0) |
=> navbar: Remove empty space to the left and right.

web/src/people.ts, web/src/realm_user_settings_defaults.ts, web/src/scheduled_messages.ts, web/src/settings_linkifiers.ts, web/src/starred_messages.ts, web/src/state_data.ts, web/src/ui_init.js, web/src/user_settings.ts
Until now there has been no validation for the parts of `state_data` split off by `pop_fields` in `ui_init.initialize_everything`. Start adding that validation gradually, to improve our confidence in the correctness of our annotations, and so we don’t have to do it all at once when we convert `ui_init.js` to TypeScript.
We use Zod’s `.transform` to replace `pop_fields` as the mechanism for splitting `state_data`. This leaves `state_data.state_data_schema` as the single source of truth for which fields are sent where.
=> Start validating the rest of `state_data` using Zod

zerver/openapi/python_examples.py
This PR is a follow-up of #30115. It adds assert statements to validate the error response for the "400" error code. The current validation using `validate_against_openapi_schema` doesn't correctly validate "400" responses.
Fixes: 
<details>
</details>
=> python_examples: Validate error responses.

web/src/compose_closed_ui.ts
Earlier when dms were disabled, the `new conversation` button tooltip wasn't being updated, therefore a stale tooltip was being shown.
Earlier the `data-conversation-type` attribute of the `new conversation` button was being set to `direct` only if dms were enabled. As a result a stale tooltip was being shown when dms were disabled.
This commit updates the attribute to `direct` reagardless of dms being enabled or not.
> Note
> 
> A user can always DM themselves or a bot, even when direct messages are disabled in an org — the reason why we don't disable the "Start new conversation" button. (#28412)
> 
Fixes #29916.
<details>
[336899046-5808aa3a-d1ea-4f41-b03f-3c5468cc144b.webm](https://github.com/zulip/zulip/assets/29176437/08c38a30-85af-4659-b1d2-41e6481a3b14)
</details>
=> new conversation: Show correct tooltip when dms are disabled.

web/src/attachments_ui.ts, web/src/message_edit_history.ts, web/src/settings_linkifiers.ts, web/src/stream_edit_subscribers.ts, web/src/stream_topic_history_util.ts, web/src/zcommand.ts
Prefer using `raw_data` and `data` instead of `data` and `clean_data`.
As advised by Andres in [#29243(comment)](https://github.com/zulip/zulip/pull/29243#discussion_r1603719919) and [#28432(comment)](https://github.com/zulip/zulip/pull/28432#discussion_r1442236806)
[Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/typescript.20migration/near/1554084)
=> stream_edit_subscribers: Use `raw_data` & `data` more.

web/src/stream_edit_subscribers.ts
`.safeParse` does not return a “schema”.
=> `stream_edit_subscribers`: Fix incorrect error result test, rename misleading variable

web/styles/app_variables.css, web/styles/input_pill.css
This PR aims to make pills participate in user-adjustable information density by tying their dimensions to the `font-size` in use.
Additionally, the PR begins by implementing better, more uniform spacing around pills in the recipient box in the compose area. Pills themselves become "dumb" about their spacing, and instead pill containers can use a combination of their own padding and the `gap` property to better control how pills are laid out--especially when they span onto multiple rows.
(A follow-up PR will improve the pill containers elsewhere in the UI.)
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/pill.20containers.20and.20pill.20spacing/near/1831577)
**Screenshots and screen captures:** (updated 21 June 2024)
| Before, Legacy | After, Legacy |
| --- | --- | …
=> info_density: Refactor pills to follow font-size.

web/src/alert_words.ts, web/src/bot_data.ts, web/src/bot_types.ts, web/src/emoji.ts, web/src/local_message.ts, web/src/muted_users.ts, web/src/onboarding_steps.ts, web/src/pm_conversations.ts, web/src/presence.ts, web/src/settings_config.ts, web/src/state_data.ts, web/src/stream_data.ts, web/src/stream_types.ts, web/src/sub_store.ts, web/src/ui_init.js, web/src/unread.ts, web/src/user_groups.ts, web/src/user_status.ts, web/src/user_status_types.ts, web/src/user_topics.ts
- Followup to #30519.
This validates everything from `state_data` except the part for `server_events.js` and the parts of `current_user` and `realm` not yet used from TypeScript.
=> Validate more of state_data using Zod

web/src/css_variables.js, web/styles/app_variables.css, web/styles/compose.css, web/styles/dark_theme.css, web/styles/message_row.css, web/templates/compose.hbs, web/templates/message_edit_form.hbs
The row of buttons is placed using CSS grid template areas so that visually it is now inside the bottom edge of the textbox. The color of the buttons row and individual buttons is changed to match the color of the textbox. All textbox border / box shadow properties are now applied to its parent instead which is extended under the buttons' row, so that its border snuggly fits around the buttons row too.
Notable side effects:
- In dark mode the textbox in focused state now has a light border which does not match the recipient input's current border which doesn't change when focused. Likely, the recipient input should be updated to match the textbox's border color.
- The dividers in the formatting buttons row are not vertically centered now. This should be figured out soon.
Known concern:
- …
=> compose: Move row of formatting buttons into the textbox.

web/src/inbox_util.ts, web/src/stream_color.ts
Changing theme didn't change the color of the stream icons.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/stream.20colors.20ignore.20light.2Fdark.20mode.20toggle
=> stream_color: Fix stream icon color not changing on theme change.

tools/test-js-with-node, web/src/compose_popovers.js, web/src/giphy.js, web/src/giphy_state.ts, web/src/message_edit.js, web/src/state_data.ts, web/src/ui_init.js
This removes `giphy` from the critical path of the TypeScript migration.
=> giphy: Split `is_giphy_enabled` to a separate module

tools/test-js-with-node, web/src/invite.ts, web/src/invite_stream_picker_pill.ts, web/src/pill_typeahead.ts, web/src/stream_data.ts, web/src/stream_pill.ts, web/styles/input_pill.css, web/styles/zulip.css, web/templates/invite_user_modal.hbs, web/tests/pill_typeahead.test.js, web/tests/stream_data.test.js, web/tests/stream_pill.test.js
Fixes #26871.
The Invite Users Modal previously featured a list of checkboxes for selecting streams when inviting users. This has been replaced with an input field featuring typeahead and stream pills for streamlined stream selection.
<details>
</details>
=> Replace Checkboxes List with Stream Pills in Invite Users Modal #26871

web/src/ui_init.js
Before commit fd253539e036c4960fee5719681b4f3a80a1423c (#30519), each part of `state_data` was removed by `pop_fields`, to ensure that it was only used by its associated module and not manipulated directly. Restore this guarantee by removing `page_params.state_data` itself.
=> ui_init: Restore guard against direct use of `page_params.state_data`

web/src/filter.ts, web/src/message_view.js, web/tests/filter.test.js
If in the same narrow, we just want to select a new id which is already rendered, we don't need to call `narrow.activate`, we can just select the new id.
=> hashchange: Select the new near id if it is already rendered.

web/styles/compose.css
This corrects an issue on Safari for iPad and iPhone, where the UA stylesheet added 1em of inline padding to the start and end of buttons. This zeroes out the padding so that the `width` attribute has the final say on the size of the expand/collapse compose buttons.
As the screenshots below show, this change appears to have no affect on the rendering of the buttons on other browsers.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/misplaced.20expand.20compose.20button.20in.20Safari.2FiPad/near/1824281)
| Mobile Safari, before | Mobile Safari, after |
| --- | --- |
| ![composebox-buttons-safari-iphone-before](https://github.com/zulip/zulip/assets/170719/cb169598-b055-4dc7-ac1d-a6e2fd57e5cd) | …
=> compose: Zero out UA padding on composebox buttons.

zerver/lib/events.py, zerver/tests/test_event_system.py, zerver/tests/test_home.py
Currently, for computing fields like can_create_public_streams and can_create_private_steams fields, is_user_in_group is called to check whether the user is part of the group which has the permission. This means that there will be one DB query for each field.
To optimize this, we now first fetch all the groups that the user is member of, including the anonymous groups which are used for settings, such that we can then just check whether the user is part of the group which has the permission meaning we would need only one query to compute all the fields.
This would be helpful when settings for other similar fields will also be migrated to groups framework.
<details> …
=> events: Optimize computing can_create_streams and related fields.

web/src/information_density.ts, web/src/message_lists.ts, web/src/server_events_dispatch.js, web/tests/dispatch.test.js
This PR fixes a regression I detected stemming from #30472, where an incorrect/missing base `em` unit caused timestamp columns to always be sized to a browser-default 16px em, even at smaller font sizes (that made this bug impossible to spot at 16/140).
Because a number of server events call for recalculating the width of the column, and because the column width is dependent on the base font-size in play, this PR moves the `calculate_timestamp_widths()` function definition into the information density file, and also calls the function in the info-density initialization function as well as on dense-mode and font-size/line-height server events. Prior to this PR, in other words, the timestamp column would not be recalculated from changes to dense mode, the font size, or the line height.
[CZO …
=> info_density: Relocate and improve timestamp-column calculations.

web/src/add_subscribers_pill.ts, web/src/stream_create_subscribers.ts, web/src/stream_edit_subscribers.ts, web/src/typeahead_helper.ts, web/src/user_group_create_members.ts
The generic argument of `InputPillContainer` should not be `InputPillItem<…>`, as `InputPillContainer` already uses `InputPillItem` where applicable.
=> typeahead_helper: Straighten `CombinedPill` types

web/styles/reactions.css
While the count/usernames with reaction emoji currently resize along with font-size, this PR enables reaction emoji to scale, too. As can be seen in the screenshots below, there is a regrettable mismatch between the size of inline emoji and reaction emoji as the font-size increases.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/testing.20info.20density.20on.20CZO/near/1836805)
| 16/140, before | 16/140, after |
| --- | --- |
| ![16-140-reaction-emoji-before](https://github.com/zulip/zulip/assets/170719/75093fe2-9b68-4ca8-8d9d-a2ad6ec641cf) | ![16-140-reaction-emoji-after](https://github.com/zulip/zulip/assets/170719/c912212e-96da-4a36-be9b-085486eb81ca) |
| Legacy, before | Legacy, after (no change) |
| --- | --- |
| …
=> info_density: Scale reaction emoji with font-size.

web/src/composebox_typeahead.ts, web/src/topic_link_util.ts, web/tests/topic_link_util.test.js
The `#**stream>topic**` syntax generates broken links for topics containing two backticks or starting/ending with *, because of architectural flaws in the backend markdown processor. So we avoid generating the syntax for such topics and instead generate the normal link syntax in markdown.
Fixes #19873
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/broken.20topic.20link)
<details>
<summary>Screenshots and Screen Captures</summary>
</details>
<details> …
=> composebox_typeahead: Avoid generating broken links.

corporate/views/installation_activity.py, corporate/views/support.py, zerver/views/documentation.py
Convert `documentation`, `installation_activity` and `support` to `typed_endpoint`.
=> Corporate typed endpoint migration

web/src/message_notifications.js
Fixes #21032
There are no visual changes but the strings are tagged for translation now.
Testing:
Test notification:
Stream message
DM
Huddle:
Multiple notifications:
=> Fix translation for desktop notifications.

web/src/narrow_banner.ts, web/styles/zulip.css, web/tests/message_view.test.js
Expands the descriptive text for both the starred messages and mentions views when they are empty.
**Notes**:
- Because this text is much longer than what's normally in these empty narrow banners, the max-width for the empty narrow feed is now set to 600px. See [relevant CZO design discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/Provide.20more.20info.20in.20empty.20views.20.2329378/near/1791960).
- I edited the text for the starred view from what's specified in the issue (see fixes note below). Specifically, I changed the instruction for how to star a message to better match what we say in the help center.
- Instead of creating a new `hbs` template for these empty narrows, I put the longer text in some constants at the top of `web/src/narrow_banner.ts` so it was easier …
=> narrow: Expand descriptive text when starred and mentioned views are empty.

web/src/click_handlers.js, web/src/inbox_ui.ts, web/src/message_list.js, web/src/recent_view_ui.ts, web/src/tippyjs.ts, web/src/user_topic_popover.js, web/styles/message_header.css, web/templates/inbox_view/inbox_row.hbs, web/templates/left_sidebar.hbs, web/templates/recent_view_row.hbs, web/tests/recent_view.test.js
The elements which received focus didn't have tooltips attached to them, thus when blur was triggered on `a`, the tooltip didn't hide as it was not listening on it for the blur event.
We move the toolip to `a` elements so that when focus and blur are triggered tippy is able to capture them.
Reproducer: Click to expand the views tab and press tab multiple times, tooltips will show but won't hide.
=> left_sidebar: Fix tooltips not hidden on blur.

zerver/lib/markdown/api_arguments_table_generator.py, zerver/lib/markdown/api_return_values_table_generator.py, zerver/openapi/zulip.yaml, zerver/views/user_groups.py
This PR fixes the missing content from API documentation. There are some places in the documentation where the content present in `zulip.yaml` does not appear on the page. I have posted screenshots of some of the places where I found this bug. There might be other places too.
| ![Screenshot 2024-06-10 121138](https://github.com/zulip/zulip/assets/119798962/7382059f-7708-4238-b063-f86d57c784e2) | ![Screenshot 2024-06-10 121043](https://github.com/zulip/zulip/assets/119798962/1d7b518b-adce-4656-b9a4-26514f9e0a27) |
| ![Screenshot 2024-06-10 120754](https://github.com/zulip/zulip/assets/119798962/c7c102bd-be05-4890-88eb-b079ac9da08b) | ![Screenshot 2024-06-10 …
=> api_docs: Fix missing content from API documentation.

help/desktop-notifications.md
Notes:
- The test notification doesn't say "Test notification", but I think we should update it, matching mobile (https://github.com/zulip/zulip-mobile/pull/5799). If we think this documentation would be confusing for the current state, we could tweak it to more closely match the notification we currently send.
Current: https://zulip.com/help/desktop-notifications
Updated:
=> help: Improve documentation on troubleshooting desktop notifications.

help/desktop-notifications.md, web/src/settings_notifications.js, web/templates/settings/notification_settings.hbs
Notes:
- I'm not sure if the notification needs to say that it's from Zulip -- we do have the URL just above.
=> Clarify test notifications UI

web/src/message_fetch.js
Found while migrating message_fetch to Typescript in #30509.
Tested by setting message fetch constants to single digit with some unreads and checking if we are hitting both `fetched_substantial_history` and `found_first_unread`.
=> message_fetch: Stop infinite fetch for first unread message id.

web/src/composebox_typeahead.ts, web/tests/composebox_typeahead.test.js
Fixes: [CZO issue report](https://chat.zulip.org/#narrow/stream/9-issues/topic/weird.20characters.20when.20copy-pasting.3F/near/1837866)
<details>
</details>
=> typeahead: Add non breaking space (\u00a0) to list of word separators.

web/styles/app_variables.css, web/styles/left_sidebar.css, web/styles/popovers.css, web/styles/recent_view.css, web/styles/right_sidebar.css, web/styles/zulip.css
This PR allows status circles to scale, while maintaining adjustments (e.g., in the Recent conversations area) present in the current design.
Note that user circles on the typeahead menu do not yet scale at 16/140, but will once typeahead text scales with the rest of the UI.
Fixes part of #30476 
| Before | After (no change at legacy sizes) |
| --- | --- |
| ![user-circles-legacy-before](https://github.com/zulip/zulip/assets/170719/f1219a4f-ded1-4dc3-b172-5e5f18eed2ca) | ![user-circles-legacy-after](https://github.com/zulip/zulip/assets/170719/2acd7acd-8e22-4419-bf1a-43d77281f906) |
| ![user-circles-16-140-before](https://github.com/zulip/zulip/assets/170719/58f3aecb-f65c-4e99-9498-891420dc5b26) | …
=> user_circles: Allow status circles to scale.

web/styles/zulip.css
This does not affect status emoji in popovers, which should be handled alongside scaling popover text (that has been noted in #30476).
Fixes part of #30476
| Before | After (no change at legacy sizes) |
| --- | --- |
| ![status-emoji-legacy-before](https://github.com/zulip/zulip/assets/170719/a320116c-6a4b-4660-86d3-28b3e8dccfb5) | ![status-emoji-legacy-after](https://github.com/zulip/zulip/assets/170719/c7e9f576-8ce4-45ac-bbe9-4a831b862457) |
| ![status-emoji-16-140-before](https://github.com/zulip/zulip/assets/170719/adf51426-9089-43c2-b970-8db800cb2e57) | ![status-emoji-16-140-after](https://github.com/zulip/zulip/assets/170719/98603c73-e4c4-48c0-b01d-0ee89f957512) |
<details> …
=> status_emoji: Allow status emoji to scale with text.

zerver/openapi/zulip.yaml
Also adds a link to the BigBlueButton integration documentation in the endpoint's main description.
_**Note**: Our API documentation rendering expects a documented example for endpoint parameters, so currently rendering this API endpoint doc raises an error._
<details>
<summary>Updated BigBlueButton create meeting API endpoint documentation</summary>
</details>
---
<details>
</details>
=> api-docs: Add example for BigBlueButton meeting_name parameter.

web/src/pm_list_data.ts, web/src/topic_list_data.ts, web/tests/pm_list_data.test.js
When narrowing to an existing topic name with different casing, left sidebar renders duplicate topic rows for the existing topic name and one with the different casing. Since topic names are case insensitive, it should narrow to the existing row only.
Also when narrowing to a DM with their own user pill in recipient, a duplicate DM row gets rendered.
Fixes: regression introduced in #29175 
Before:
<details> …
=> Duplicate conversation rows in left sidebar.

web/styles/settings.css, web/styles/widgets.css, web/styles/zulip.css
This removes the remaining 14px font-size and related styles in the code base, except for instances in `popovers.css`, `tooltips.css`, and `right_sidebar.css`--all of which are being tracked for removal separately in #30476.
<details>
</details>
=> info_density: Remove unnecessary 14px-related styles after audit.

web/src/bootstrap_typeahead.ts, web/third/bootstrap-typeahead/typeahead.css
This fixes an issue where the typeahead container was being rendered without anything in it:
The issue is that the search typeahead container isn't hidden on page load. We hide it when the search bar gets closed, but if the page is loaded with the search bar expanded then it's still visible even though there's nothing rendered in the typeahead container.
=> typeahead: Hide by default and show container on show() to avoid half-rendered state.

web/styles/drafts.css, web/styles/inbox.css, web/styles/left_sidebar.css, web/styles/message_header.css, web/styles/popovers.css, web/styles/rendered_markdown.css, web/styles/zulip.css, web/templates/compose_banner/automatic_new_visibility_policy_banner.hbs, web/templates/confirm_dialog/confirm_delete_topic.hbs, web/templates/confirm_dialog/confirm_merge_topics_with_rename.hbs, web/templates/draft.hbs, web/templates/message_moved_widget_body.hbs, web/templates/move_topic_to_stream.hbs, web/templates/recent_view_row.hbs, web/templates/recipient_row.hbs, web/templates/scheduled_message.hbs, web/templates/stream_topic_widget.hbs, web/templates/topic_list_item.hbs, web/templates/typeahead_list_item.hbs, web/templates/user_topic_ui_row.hbs, web/tests/composebox_typeahead.test.js
Set `white-space` to `pre` or `pre-wrap` to fix compressing of display topic names everywhere in the web UI that we display topics.
To replace white-space default/normal value, used `pre-wrap` and to replace nowrap value used `pre`.
Using span where ever necessary because of `pre`. It considers new line characters from templates to add space so a better practice is to set `pre-wrap` inside a span.
Referred to the [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#syntax).
Fixes part of: #30478 
| ![Screenshot from 2024-06-21 13-12-23](https://github.com/zulip/zulip/assets/78212328/37480045-7d26-4302-a124-b0f331e02abf) | ![Screenshot from 2024-06-21 …
=> topic_name: Fix compressing of display topic names

web/src/settings_org.js, web/src/settings_realm_user_settings_defaults.js, web/src/stream_ui_updates.js, web/styles/settings.css, web/styles/subscriptions.css
- First commit is to fade the label for disabled checkbox settings.
- Second commit is to fade the label for disabled checkbox stream settings.
- Third commit is for refactoring CSS.
Fixes: https://chat.zulip.org/#narrow/stream/101-design/topic/disabled.20checkbox.20label.20in.20settings
| ![image](https://github.com/zulip/zulip/assets/35494118/441e70f9-fe6b-4662-a401-05fc2993884e) | ![image](https://github.com/zulip/zulip/assets/35494118/9c929de7-31e6-4207-8360-0ec7e64f89b4)  |
| ![image](https://github.com/zulip/zulip/assets/35494118/2bee7d38-718d-4c68-b588-580299b5f430) | ![image](https://github.com/zulip/zulip/assets/35494118/a65086b8-f0f7-4c0d-843d-75bcde7f1842)  |
<details> …
=> settings: Fade label for disabled checkbox settings.

web/src/bootstrap_typeahead.ts, web/styles/app_variables.css, web/styles/compose.css, web/styles/dark_theme.css, web/styles/inbox.css, web/styles/zulip.css, web/templates/typeahead_list_item.hbs, web/tests/composebox_typeahead.test.js, web/third/bootstrap-typeahead/typeahead.css
This attempts to change background color and text color of typeaheads to be same as dropdown widgets we have in the app.
`active` typeahead color was taken from https://terpimost.github.io/compose-decomposed/
Related issue - #25116
This PR is to help us get the colors we want for the typeaheads, then we can do some of the much needed cleanup work in this space.
Here is a list of all typeaheads:
* Compose box textarea with various triggers - `@`,`#`, `/`, ....
* Compose box topic / DM
* Message edit box
* Search (No change)
* Playground settings > Language - http://localhost:9991/#organization/playground-settings
* Profile > Mentor - http://localhost:9991/#settings/profile
* Stream settings > Add subscribers - http://localhost:9991/#channels/21/Denmark/subscribers
=> typeahead: Make them look like dropdown widget.

corporate/tests/test_stripe.py, corporate/tests/test_support_views.py, corporate/views/support.py, templates/zerver/emails/realm_deactivated.html, templates/zerver/emails/realm_deactivated.subject.txt, templates/zerver/emails/realm_deactivated.txt, tools/test-api, zerver/actions/create_realm.py, zerver/actions/realm_settings.py, zerver/management/commands/deactivate_realm.py, zerver/management/commands/export.py, zerver/tests/test_audit_log.py, zerver/tests/test_auth_backends.py, zerver/tests/test_decorators.py, zerver/tests/test_email_change.py, zerver/tests/test_email_mirror.py, zerver/tests/test_events.py, zerver/tests/test_push_notifications.py, zerver/tests/test_realm.py, zerver/tests/test_signup.py, zerver/views/realm.py, zproject/jinja2/__init__.py
Creates a new `realm_deactivated` email that can be sent as part of the realm deactivation process.
Fixes #24685.
**Notes**:
- Adds a new boolean flag, `email_owners`, to `do_deactivate_realm`. This flag is set to `False` when `do_deactivate_realm` is used for realm exports or changing a realm's subdomain, so that the active organization owners are not emailed in those cases.
- This flag is optional for the `deactivate_realm` management command, but as there is no active user passed in that case, then the email is sent without a reference to who deactivated the realm.
- It is passed as `True` for the support analytics view, but the email that is generated does not include information about the support user who completed the request for organization deactivation.
- When an active …
=> realm-deactivation: Send email to owners when deactivating organization.

web/templates/inline_decorated_stream_name.hbs, web/templates/typeahead_list_item.hbs, web/tests/composebox_typeahead.test.js
We are using `white-space: pre` which doesn't condense whitespaces, so we need to remove any unintentional whitespaces here.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/channel.20typeaheads.20indented
| --- | --- |
| ![image](https://github.com/zulip/zulip/assets/25124304/08cd617b-4b82-4e47-b300-dfdacf84e117) | <img width="562" alt="Screenshot 2024-06-27 at 3 50 06 PM" src="https://github.com/zulip/zulip/assets/25124304/94f38056-c766-45df-9328-078fcc105160"> |
| ![image](https://github.com/zulip/zulip/assets/25124304/fb707328-b6bc-407c-8783-0a496188f07a) | <img width="562" alt="Screenshot 2024-06-27 at 3 51 04 PM" src="https://github.com/zulip/zulip/assets/25124304/759a5747-4f75-4d26-8615-1a0c87d974fb"> |
=> typeahead: Remove all sources of white space inside `strong` element.

web/src/message_events.js, web/src/message_store.ts, web/src/stream_topic_history.ts, web/src/stream_topic_history_util.ts, web/src/ui_init.js, web/tests/message_store.test.js, web/tests/stream_topic_history.test.js
Fixes #27500
This simplifies the code by removing the concept of historical topics and just asking server for the correct order when we are not sure what is the right order of the topics.
=> Fix incorrect topics order when moving messages.

web/styles/app_components.css, web/styles/inbox.css, web/styles/left_sidebar.css
This PR sets font-sizing and related dimensions on the unread counts to scale across the UI, including in sidebars and the Recent and Inbox views.
There is a change to how focus rings are sized in the inbox view; as the screenshots below show, there is no visible effect to that change (previous use of padding was perfectly sized to the row, but `align-self: stretch` now has the same effect, without blowing out the size of the rows with unreads that scale up.
There is also a commit to ensure that user-circles scale in the inbox, which should have been a part of #30591, but makes sense enough to include here, given parallel inbox fixes with this PR.
Fixes parts of #30476
| Legacy, before | Legacy, after (no change) |
| --- | --- |
| …
=> unread_counts: Scale unread counts with UI.

web/src/pill_typeahead.ts, web/src/typeahead_helper.ts, web/tests/pill_typeahead.test.js, web/tests/typeahead_helper.test.js
This does following things:
Fixes: #30577
<details>
</details>
=> Improve channels typeahead on invite modal #30577

web/src/compose_setup.js
Renarrow to the unresolved topic for better UX.
This PR is a followup to PR #29225. It addresses the TODO comment on that PR:
```
// TODO: Probably this should also renarrow to the
// new topic, if we were currently viewing the old
// topic, just as if a message edit had occurred.
```
When a user tries to send a message to an empty resolved topic, the `Unresolve topic` button marks the topic as unresolved instead of giving an error. (done in #29225).
In this PR, it also renarrows to the now unresolved topic.
<details>
</details>
<details> …
=> compose: Unresolve empty topics followup

zerver/openapi/zulip.yaml
Now that the `presences` objects are being rendered in the API documentation, updates those to be formatted more clearly and accurately. Also, revises most of the descriptive text for the `PATCH /users/me/presence` endpoint.
There may be some missing API feature level **Changes** notes that should be added as well regarding when the modern format was more stable/active, but as this was already a major revision to get the current documentation more accurate and robust, I thought that could be a follow-up.
Other areas I've noted that need some attention regarding user presence:
- The contributor documentation on the presences data/system.
- The presence event in `GET /events`.
- The API changelog - in particular bottom section on [changes that aren't …
=> api-docs: Update `presences` object documentation.

zerver/actions/create_user.py, zerver/tests/test_onboarding_steps.py, zerver/tests/test_signup.py, zerver/tests/test_users.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/Don't.20show.20the.20.22Now.20following.22.20banner.20to.20new.20users.20.2330615/near/1840176)
Earlier, a one-time `visibility_policy_banner` was displayed to existing as well as new users to inform them about the new **"follow/unmute topics"** feature.
It makes sense to educate only the existing Zulip users about the new feature using this banner. New users don't need to know about following topics right away.
This PR makes changes to NOT show the banner to new users.
Fixes: #30615
<details> …
=> onboarding_step: Don't show 'visibility_policy_banner' to new users.

web/src/compose_popovers.js, web/styles/compose.css, web/templates/popovers/mobile_message_buttons_popover.hbs
As part of the popover menu redesign, this redesigns the mobile message buttons popover using the new "popover-menu" tippy theme and improves accessibility by using appropriate ARIA attributes.
This PR also updates the logic for the mobile message buttons popover to mimic the "Start new conversation" button's logic — show new topic option only when in a stream narrow, else show the new channel message option. And removes the `is_in_private_narrow` check from the logic, as we show the new direct message option regardless of it.
Fixes part of #28699.
[CZO Discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/compose.3A.20Redesign.20mobile.20message.20buttons.20popover.20.2330603/near/1839459) …
=> compose: Redesign mobile message buttons popover.

web/e2e-tests/message-basics.test.ts, web/styles/app_components.css, web/styles/app_variables.css, web/styles/left_sidebar.css, web/templates/filter_topics.hbs, web/templates/left_sidebar.hbs
This PR provides some polish to the left sidebar's participation in scalable information density.
1. It scales the resolved checkmark along with the rest of the UI, and does so in a way that preserves the space alloted topic names in the topic rows
2. It scales the font size on "show all topics," "more conversations" rows 
3. It rewrites the topic filter into a gridded row, achieving for the first time perfect alignment with the filtered topic rows below
4. It removes the `.input-append` class from stream and topic filter boxes, so that their text is sized identically as other parts of the UI, [as called for](https://chat.zulip.org/#narrow/stream/101-design/topic/font.20size.20on.20.3Cinput.3E.20elements/near/1824511) by @terpimost's redesign
Fixes parts of #30476  …
=> left_sidebar: Better present navigational, topic and topic-filter rows.

web/styles/app_variables.css, web/styles/compose.css
Revert "css: Redefine `--color-outline-focus` for dark theme."
This reverts commit 5c1069872dff741ad8884b0bf6f9e438e90ff78c.
compose: Use same focus ring color for compose buttons in each theme.
A new css variable is created with the same blue color in light theme as `color-outline-focus`, and gray color in dark theme, and is used for the focus-visible state of the compose control buttons, the compose close button, and the send later vdots button.
(The revert fixes regressions mentioned in the linked CZO thread, and creates the need for a separate css variable for the color of focus rings of compose buttons.)
Fixes: [CZO issue](https://chat.zulip.org/#narrow/stream/9-issues/topic/recent.20conversations.20underline.20color/near/1833310)
(regressions …
=> css: Revert "css: Redefine `--color-outline-focus` for dark theme."

web/src/add_subscribers_pill.ts, web/src/stream_create_subscribers.ts, web/src/stream_create_subscribers_data.ts, web/src/stream_ui_updates.js, web/styles/subscriptions.css, web/templates/stream_settings/add_subscribers_form.hbs, web/templates/stream_settings/new_stream_user.hbs, web/templates/stream_settings/new_stream_users.hbs, web/templates/user_display_only_pill.hbs, web/tests/stream_create_subscribers_data.test.js
One additional detail to the specs described in #29825 is that we will not have a pill for the current user. Discussion can be found here: https://chat.zulip.org/#narrow/stream/6-frontend/topic/Disabled.2Fun-editable.20input.20pill/near/1838691
I've not added extra puppetteer tests, since adding users was not part of the existing tests.
While there are 2 commits in this PR and each of them will past the tests independently, the first commit has functional bugs, as it's an intermediate step. I've kept two commits here so it's a bit easier to review, we can squash it at the end.
Fixes: #29825.
<details>
<summary>Screen capture</summary>
Resultant subscriber list:
</details>
<details> …
=> Change interaction UI for adding users when creating streams

web/src/message_events.js, web/src/stream_topic_history.ts, web/tests/stream_topic_history.test.js
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/topic.20list.20order
Testing:
* Set message_fetch constants to 1.
* Click on show all in a stream and go to a topic
* Open the same stream in other tab and checking if live update works correctly in both the tabs when moving / deleting messages.
=> Fix topics with 0 message count not updated correctly.

help/import-from-mattermost.md
The created export-archive needs to extracted before converting
Added clarification for that in the documentation
Fixes: 
Fixes the error following Mattermost import:
```
zulip@3849e11c9576:~/deployments/current$ ./manage.py convert_mattermost_data /tmp/export.tar.gz --output /tmp/converted_mattermost_data
Converting data ...
File "./manage.py", line 151, in <module>
execute_from_command_line(sys.argv)
File "./manage.py", line 116, in execute_from_command_line
utility.execute()
File "/srv/zulip-venv-cache/bbd84a06bc651effedfe39cab337a1bf300cee02/zulip-py3-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File …
```
=> Fix docs for importing Mattermost data

zerver/lib/zcommand.py, zerver/models/users.py, zerver/tests/test_settings.py, zerver/tests/test_users.py, zerver/tests/test_zcommand.py
As a follow up for f49a11c810632cce6a94e679b2fb847dd2291c42, this PR standardizes the naming of the day and night themes to light and dark, respectively in the backend. This makes the backend consistent with the naming used in the frontend and UI.
This also solves a regression introduced in f49a11c810632cce6a94e679b2fb847dd2291c42, where the frontend was sending `/light` and `/dark` commands to the backend, but the backend was expecting `/day` and `/night` commands.
Fixes: [Issue reported on CZO
](https://chat.zulip.org/#narrow/stream/9-issues/topic/slash.20commands.20for.20theme.20switch.20are.20not.20working/near/1840977)
<details> …
=> zcommand: Rename night->dark and day->light in the color scheme backend.

web/src/filter.ts, web/src/message_view.js, web/tests/filter.test.js
Tested by sending a message in a topic with a link to the message above it. Then, renaming the topic and clicking on the link the to see if it works.
=> Fix near links to message in the same narrow not working due to topic rename.

web/src/drafts.ts, web/templates/draft.hbs, web/tests/drafts.test.js
variation of https://github.com/zulip/zulip/pull/28653/commits/53891c556ab06c5b34eeae3737f5007fa6836294
=> drafts: Show saved time in UTC format in a tooltip

web/third/bootstrap-typeahead/typeahead.css
This css accidentally got removed in #29882. This bug fix was originally part of #30514.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Weird.20search.20state.20after.20clicking.20.60near.60.20view
=> typeahead: Fix search typeahead open on `near` narrows.

web/styles/left_sidebar.css
This PR refactors the left sidebar navigation rows in a way that does not disturb high-res presentation of the labels and icons, but makes a big improvement to low-res display of navigation rows in Chrome.
The solution here effectively decouples the row height from the line-height, which was off in Chrome due to likely subpixel rounding errors in its font rendering engine. Instead, CSS Grid auto-generates rows as needed to the same `height` as would otherwise be specified on the `line-height`.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20icons.20sagging.20on.20.60main.60/near/1825390)
| Chrome, low-res before | Chrome, low-res after |
| --- | --- |
| ![chrome-before](https://github.com/zulip/zulip/assets/170719/75 …
=> left_sidebar: Refactor nav rows for low-resolution screens.

web/styles/app_variables.css, web/styles/subscriptions.css
On some specific screen height, the `.subscriber-list` table will have its bottom border cut off by the `.subscriber_list_container` wrapper div around it.
This PR attempts to fix that issue by formatting the bottom border of the `.subscriber_list_container` wrapper div to act like the tables bottom border. 
[Screencast from 07-02-2024 02:16:25 PM.webm](https://github.com/zulip/zulip/assets/108744694/3c4f30e6-0304-43f8-a9cb-ef1c483dec2c)
`git grep "subscriber_list_container"`:
<details>
<summary>
Screenshots & video:
</summary>
| Description | Before | After |
| Create Channel | ![image](https://github.com/zulip/zulip/assets/108744694/8a5bba52-5fd3-4553-9709-6b5efb29508f) | ![image](https://github.com/zulip/zulip/assets/108744694/3b4970ed-78d0-48cb-8cf1-13fe272b03e2) | …
=> subscription css: Fix cut off bottom border for subscriber list.

web/styles/app_variables.css, web/styles/message_row.css, web/styles/reactions.css, web/styles/zulip.css
This PR extends the use of Markdown-derived interelement spacing to provide a more consistently sizable message box. Previous inconsistent space beneath reactions and Show more/Show less toggles now also take values derived from interelement spacing.
In making for consistent spacing, however, this PR introduces some subtle design changes that become more pronounced at 16/140, especially regarding the apparent alignment of the username and the top of the avatar. However, note in the screenshots that the avatar and the hover icons share a similar vertical distance from the top of the message box. That is a consequence of trying to vertically center-align the hover icons with the username and timestamp, while also keeping a consistent distance between the focus ring and hover icons between …
=> message_box: Space message box elements evenly, based on single-line reference.

puppet/kandra/templates/nagios4/cgi.cfg.template.erb, scripts/setup/initialize-database, zerver/webhooks/gitlab/doc.md
Noticed the "you you" typo in the documentation for the [GitLab integration](https://zulip.com/integrations/doc/gitlab), and then did `git-grep "you you"` to fix any other instances of this same typo in docs.
---
<details>
</details>
=> documentation: Fix "you you" typos in docs/comments/logs.

web/src/narrow_title.ts
Earlier the narrow title for `sender:me` was being displayed.
Instead, display the narrow title for `has:reaction sender:me`.
Before:
After:
=> reactions view: Add narrow title.

web/styles/zulip.css
We're reverting removing `outline: none` from commit fe11f3be7c21c649e21702b9afbbb63fb70879d6. While we set tabIndex to -1 in that commit, which makes sure that it does not get focus when navigating via a keyboard. But it does not prevent us from programmatically focusing on the element. In this case, we don't want to see the outline. 
Fixes https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20weird.20left.20sidebar.20outline/near/1834137
| --- | --- |
|  <img width="1351" alt="Screenshot 2024-07-03 at 1 58 31 AM" src="https://github.com/zulip/zulip/assets/13910561/f9983fd8-ff73-4146-99fc-aa4284149f74"> |  <img width="1351" alt="Screenshot 2024-07-03 at 1 58 12 AM" …
=> scroll: Set outline as none for `.simplebar-content-wrapper`.

web/styles/app_components.css
This PR introduces a negative top-margin adjustment on the icon lock, UI wide. Mathematical centering is just that: this adjustment goes for visual/perceptual centering instead. And it does so with an `em` value that works at legacy and 16/140.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20drooping.20left.20sidebar.20lock.20icons/near/1842926)
Fixes part of #30476
| Left sidebar detail, before | Left sidebar detail, after |
| --- | --- |
| ![lock-icons-before](https://github.com/zulip/zulip/assets/170719/e9b241b7-d213-4804-9851-1a25cbad520f) | ![lock-icons-after](https://github.com/zulip/zulip/assets/170719/430cca04-de7f-41b6-9fd3-580ddb4729df) |
| Recent conversations, before | Recent conversations, after |
| --- …
=> privacy_icon: Raise lock icon throughout UI for better visual centering.

web/src/pm_conversations.ts, web/tests/pm_conversations.test.js
Adds `has_conversation` function in `pm_conversation.RecentDirectMessages` for checking previous messages in the DM conversations.
<details>
</details>
=> Preparatory commit for #28470.

web/src/recent_view_ui.ts
Looks like the error was only there when the topic had a single message which was deleted. 
Tested by having focus on the topic with a single unread message in recent view and deleting that message in another window. Couldn't reproduce the bug for topic with multiple unread messages.
=> Recent view fix error when deleting the only message in a topic.

web/templates/recipient_row.hbs, zerver/management/commands/makemessages.py
Might fix the CI errors due to extra space between `You and` and the user full name.
discussion: https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/main.20failing/near/1844222
No visual changes.
=> recipient_row: Remove extra whitespace around recipient full name.

web/src/compose_tooltips.ts, web/src/tippyjs.ts, web/styles/tooltips.css, web/styles/zulip.css
This PR sets Tippies to scale with the UI, including initializing Tippies with em values for `maxWidth`. Additionally, a small commit here ensures that bold font-weights don't make their way into a Tippy when it's attached to a parent (as is the case in the Notifications UI.
Fixes part of #30476
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/maxWidth.20on.20Tippy.20tooltips/near/1845656)
| 16/140 Tippies, before | 16/140 Tippies, after |
| --- | --- |
| ![tippies-before](https://github.com/zulip/zulip/assets/170719/abc9848a-dc28-4536-acfb-24ecf2b33260) | ![tippies-after](https://github.com/zulip/zulip/assets/170719/c7075420-74fb-4bc1-a7ed-b0ac99d84ee7) |
| Legacy Tippies, before | Legacy Tippies, after (no apparent change) |
| …
=> tippy: Enable Tippies to scale with UI.

web/html/5xx.html
We only want to apply this class on the actual content of the page.
| --- | --- |
| <img width="1139" alt="Screenshot 2024-07-04 at 1 20 51 AM" src="https://github.com/zulip/zulip/assets/25124304/b037eaa0-3313-4919-be62-8bd910ca44c7"> | <img width="1139" alt="Screenshot 2024-07-04 at 1 18 52 AM" src="https://github.com/zulip/zulip/assets/25124304/b8c6479a-c8fa-47f4-91dd-73504ad7f2a0"> |
=> 5xx: Remove duplicate `error_page` class applied on page.

web/styles/recent_view.css
This provides a fixed, uniform but scalable column for filter icons in the Recent conversations view. Icons are now also more reliably centered related to their adjacent text content. 
Fixes part of #30476 
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/testing.20info.20density.20on.20CZO/near/1844325)
| --- | --- |
| ![recent-view-icons-legacy-before](https://github.com/zulip/zulip/assets/170719/f0f6a5cf-e9e1-429e-ade2-cdaaceea4d2d) | ![recent-view-icons-legacy-after](https://github.com/zulip/zulip/assets/170719/7104890f-ebc5-494c-b6a3-3e8588cc8ada) |
| ![recent-view-icons-before](https://github.com/zulip/zulip/assets/170719/496786da-e5c7-4cb6-8b2a-0c768428b468) | …
=> recent_view: Set a shared column for filter icons.

web/styles/left_sidebar.css
This fixes a regression introduced in #30692; the use of `grid-auto-rows` set a non-zero auto-generated row height, which was applied even when the expanded nav list had no displayable children.
A clever use of `height` on the active filter ensures that that view remains undisturbed by this more targeted use of `grid-auto-rows`.
[
CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20left.20sidebar.20space.20between.20collapsed.20views.20and.20DMs/near/1845632)
| Condensed nav, before | Condensed nav, after |
| --- | --- |
| ![condensed-nav-before](https://github.com/zulip/zulip/assets/170719/516e6f7b-4031-4238-9c94-b1b30ff22183) | ![condensed-nav-after](https://github.com/zulip/zulip/assets/170719/fa51ea76-cae3-453e-ba53-2 …
=> left_sidebar: More carefully generate auto rows for expanded nav.

help/direct-messages.md, help/left-sidebar.md, zerver/lib/markdown/help_relative_links.py
**Notes on updates**:
- Removed the bulleted list of these actions in the main description.
- The information about configuring unread markers is just in the related articles section now. I didn't see a good way to include it with the left sidebar actions that can all be done/undone during your work session since it's a general setting that a user decides on.
- Added a section titled "Adjust the left sidebar for your focus" under which all the actions have their own sections. This seemed like a nice general section to be able to link to from blog posts or landing pages.
- Added some tips that seemed useful as I was manually testing the new instructions.
Fixes #30411.
---
[Current documentation](https://zulip.com/help/left-sidebar)
<details> …
=> help: Document left sidebar actions.

web/styles/settings.css, web/templates/settings/uploaded_files_list.hbs
| --- | --- |
| <img width="710" alt="Screenshot 2024-07-01 at 11 04 34 PM" src="https://github.com/zulip/zulip/assets/25124304/0aa5c823-fbd8-4a61-a27e-0e78978110e0"> | <img width="710" alt="Screenshot 2024-07-01 at 11 03 43 PM" src="https://github.com/zulip/zulip/assets/25124304/ee4e1644-aafe-4575-9e71-07ed2dbf9277"> |
Most changes are from this commit - https://github.com/zulip/zulip/pull/28653/commits/ae05c92ae714ae65bc23daea4f36c37447675e8e
=> settings: Use box buttons for download and delete.

web/src/playground_links_popover.ts, web/templates/popovers/playground_links_popover.hbs
As part of the popover menu redesign, this PR redesigns the playground links popover using the new "popover-menu" tippy theme and improves accessibility by using appropriate ARIA attributes.
Additionally, this PR also contains the following fixes:
- Fixes a bug where the playground links popover doesn't reopen after it's closed.
- Removes the `href` attribute from the external code button when multiple code playground links are present for a language – prevents the bug where the external code button would always link to the previously set code playground link
Fixes part of #28699.
<details><summary>Light Mode</summary>
<p>
| <img width="897" alt="image" src="https://github.com/zulip/zulip/assets/82862779/9a294e77-7c1b-4bbe-a579-5fa4da9c1830"> | <img …
=> playground_popover: Redesign popover using the new "popover-menu" theme.

help/resize-the-compose-box.md, web/src/resize.ts
Also,
compose: Fix the calculation of the compose box's max height.
This is a follow up to #30396, to remove consideration of the text box's margin after it's removal in #29953.
Fixes: [CZO message](https://chat.zulip.org/#narrow/stream/438-release-management/topic/zulip_updates.20items.20of.20note/near/1844022)
<details>
</details>
=> docs: Update docs for 3 way compose box resizing.

web/styles/settings.css
This helps us in avoiding the scrollbar inside the box if the information density setting
is set to 16/140 by allowing the box to set its height as per the content.
There is no need for max-height since the height of the box was anyways less than
the max-height value set before at normal font size and screen widths.
For narrow screens, the max-height property was set to unset, so removing the max-height
property does not have any effect on how the bots are shown on narrow screens.
Fixes #30669.
**For 14px**
**For 16px**
<details> …
=> settings: Remove max-height for bots box container.

package.json, patches/tippy.js@6.3.7.patch, pnpm-lock.yaml
In Firefox, event targets can be pseudo elements like text nodes which don't have .closest method. This results in error when delegate tries to handle trigger for a text node target.
Since https://github.com/atomiks/tippyjs/pull/1166 has no response from the developer, we decided to apply this patch ourselves.
=> tippy: Add patch to avoid text Node as target in Firefox.

web/styles/message_row.css
This corrects a subtle regression introduced by #30579, which set `padding-top: 0` on `.message_content`, leading to larger emoji being cut off at the top of the message box in narrower line-heights, such as at legacy values.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/info.20density.3A.20inline.20emoji.20presentation/near/1847196)
| Legacy, before | Legacy, after |
| --- | --- |
| ![top-line-emoji-legacy-before](https://github.com/zulip/zulip/assets/170719/b3cb8660-7394-4cb2-bc92-99b12a46daa6) | ![top-line-emoji-legacy-after](https://github.com/zulip/zulip/assets/170719/60bd0e9f-3911-4a8c-b609-e310a266a932) |
| 16/140, before | 16/140, after (no change) |
| --- | --- |
| …
=> message_box: Ensure emoji display correctly on messages with senders.

corporate/views/billing_page.py
Migrate the following 3 functions 
- `update_plan()`
- `update_plan_for_remote_realm()`
- `update_plan_for_remote_server()`
from `@has_request_variables` endpoint decorator to `@typed_endpoint`.
=> billing: Migrate to @typed_endpoint.

web/styles/app_variables.css, web/styles/informational_overlays.css, web/templates/markdown_help.hbs, web/templates/search_operators.hbs
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/.F0.9F.8E.AF.20info.20density.3A.20help.20modal
| --- | --- |
| <img width="866" alt="Screenshot 2024-07-03 at 7 47 42 AM" src="https://github.com/zulip/zulip/assets/25124304/c7c01648-a279-4ce2-a099-d2472e5406fa"> | <img width="780" alt="Screenshot 2024-07-03 at 7 44 52 AM" src="https://github.com/zulip/zulip/assets/25124304/3145c1b9-5fe9-4d3a-8431-c295b59eaac8"> |
| --- | --- |
| <img width="592" alt="Screenshot 2024-07-02 at 10 15 43 PM" src="https://github.com/zulip/zulip/assets/25124304/f40c0db4-1e69-45f5-a941-7d68b60f681a"> | <img width="602" alt="Screenshot 2024-07-02 at 10 15 50 PM" src="https://github.com/zulip/zulip/assets/25124304/638844ad-6621-480d-a31d-0b350ea278ed"> | …
=> Increase max width of information overlay.

web/styles/app_variables.css, web/styles/right_sidebar.css
This PR computes legacy values using different but context-appropriate methods for the left and right sidebar, so that links at the bottom of each sidebar scales up and preserves the legacy space from the bottom of the viewport.
Fixes parts of #30476.
| Legacy, before | Legacy, after (no change) |
| --- | --- |
| ![sidebars-legacy-before](https://github.com/zulip/zulip/assets/170719/b9d7badd-d8d5-40a0-a3f7-ad133cde3149) | ![sidebars-legacy-after-no-change](https://github.com/zulip/zulip/assets/170719/3ff7c405-16fd-4188-9277-720d3ee912c2) |
| 16/140, before | 16/140, after |
| --- | --- |
| ![sidebars-16-140-before](https://github.com/zulip/zulip/assets/170719/e72dc87f-3cee-4848-a68d-c8875ef9bc07) | …
=> sidebars: Correct placement of browse more streams, invite more users links.

web/styles/compose.css
Due to a wrong CSS selector, the expected red outline flashing effect was not being applied to the compose box when the user tried to send a message that was longer than the maximum allowed length, which is fixed by this commit.
<details>
</details>
=> compose: Fix flashing effect on trying to send message that's too long.

web/src/message_list.js, web/src/message_list_view.js, web/src/server_events_dispatch.js, web/src/stream_events.js, web/src/stream_settings_ui.js
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20Missing.20subscribed.20bookends
Tested that subscribing to Denmark for Iago displays the subscribed bookend and updating the stream privacy works corretcly to only update the bookend if it displayed and not show one if it is not required.
Tested channel archieved booked is displayed when deleting a stream.
Tested toggle subscribed button works in the trailing bookend.
=> Fix subscribed bookend not displayed for newly subscribed stream.

help/include/clear-status.md, help/include/self-user-card.md, help/include/set-status.md, help/status-and-availability.md, static/images/help/mobile-x-icon.svg
Fixes #29415.
- Added a "Via Personal Settings" tab.
- Added relative link in self-user-card.md.
- Added "Clear a Status", where the user is told to press the X button.
Here's what the new documentation would be as opposed to the [old documentation](https://zulip.com/help/status-and-availability#statuses):
=> Documentation Update: Add instructions to Status and Availability.

web/styles/app_variables.css, web/styles/compose.css
compose: Make compose close cross button smaller and add active state.
The background color's opacity is reduced for the button's active state.
compose: Rework paddings for the compose content for more symmetry.
The space above and to the left of the recipient area is now matched to the space below it, and this is also the space above and on the sides of a collapsed compose row.
Fixes: [CZO message](https://chat.zulip.org/#narrow/stream/101-design/topic/compose.20close.20icon.20update/near/1834022)
Compose box open:
Compose box collapsed:
<details> …
=> compose: Make compose close icon small and reduce space above recipient area.

web/src/typeahead_helper.ts, web/styles/compose.css, web/styles/zulip.css, web/templates/typeahead_list_item.hbs, web/tests/composebox_typeahead.test.js, web/tests/typeahead_helper.test.js
This PR uses markdown rendered version of the description instead of plain description text in stream typeahead. This renders emojis in the description.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20emoji.20in.20channel.20description.20in.20typeahead/near/1839913)
<p>
</p>
</details> 
<p>
</p>
</details> 
<details> …
=> compose_typeahead: Show emojis in stream description typeahead.

web/styles/app_variables.css, web/styles/zulip.css
This PR reduces the total width of the hover-control area from a legacy 78px (which I believe existed prior to the grid-rewrites) to an icon + padding-sized 66px (22px width per icon).
There is more than can be done to tune this area and how it behaves with 16/140, but first it's better to decide how narrower icon targets and a narrower hover-control area feel.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/message.20width/near/1836122)
| Before (26px width per icon) | After (22px per icon) |
| --- | --- |
| ![hover-controls-before](https://github.com/zulip/zulip/assets/170719/29984933-57e9-46b5-9b84-b6c0b927da14) | ![hover-controls-after](https://github.com/zulip/zulip/assets/170719/2fb5f543-fa60-4b96-9290-76ebbe2ce58d) | …
=> message_controls: Reduce control button width to match padded icon.

web/src/typeahead_helper.ts
Earlier in search typeaheads, empty query suggestions would highlight all the available suggestions for person name and channel name.
This PR changes the behaviour so that empty query doesn't give highlighted suggestions.
Fixes: [czo](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20bold.20in.20search.20typeahead)
**Screenshots and screen captures:**\
<details>
</details>
=> Remove highlight for suggestions with empty query.

zerver/views/development/dev_login.py, zerver/views/development/integrations.py, zerver/views/submessage.py, zerver/views/thumbnail.py, zerver/views/tutorial.py, zerver/views/zephyr.py, zerver/webhooks/pivotal/view.py
Migrate "submessage.py", "thumbnail.py", "tutorial.py", "zephyr.py" and
"dev_login.py" and "integrations.py" to `typed_endpoint`.
=> Integrations-typed-endpoint

zerver/webhooks/grafana/doc.md
Reformatted Grafana doc into 3 part sections. One for creating the Zulip bot and webhook URL. One for setting up Grafana version 8.3 and above and the last one for setting up Grafana version 8.2 and below.
Part of #29592.
<details>
<summary>
[Grafana](https://zulip.com/integrations/doc/grafana)
</summary>
</details>
<details>
</details>
=> integration-docs: Update Grafana for new doc format.

tools/test-js-with-node, web/shared/src/typeahead.ts, web/src/emoji_picker.js, web/src/emoji_picker.ts, web/tests/composebox_typeahead.test.js, web/tests/typeahead.test.js
First commit:
Fixes: [#30439 ](https://github.com/zulip/zulip/issues/30439) 
Second commit: Migrates `emoji_picker` to TypeScript.
<details>
</details>
=> emoji_picker: Convert module to TypeScript.

zerver/actions/message_edit.py, zerver/tests/test_message_move_stream.py, zerver/tests/test_message_move_topic.py
This PR fixes the bug where the "topic unresolved" notification is wrongly triggered when moving a message between a resolved and unresolved topic.
To resolve this issue, this solution ensures that resolved/unresolved notifications are not sent if a message has been moved to a new topic. This is achieved by comparing the names of the old and new topics without considering the "resolved prefix". It also updates the code so that only the moved notification is triggered when moving a message between a resolved and unresolved topic in different streams or when moving a topic itself.
The PR also accounts for the scenario where `new_topic_name` has been truncated, indicating that it was resolved and the name had to change to accommodate the "resolved prefix".
This solution assumes that a stream …
=> resolve_topic: Fix incorrect trigger of notification when moving message.

web/src/bootstrap_typeahead.ts, web/src/input_pill.ts
On the pressing the 'X' button on a pill, the input was moving without repositioning the typeahead. Fixed it by:
Calling popper instance update method to refresh the position of the typeahead menu.
Before:
After:
<details>
</details>
=> typeahead: Fix typeahead position not updating on pill remove.

web/src/message_edit.js
[CZO link for this issue](https://chat.zulip.org/#narrow/stream/9-issues/topic/Duplicate.20confirmation.20modals.20merging.20topics).
Earlier `focus_submit_on_open` was set to `false` so even when the
`confirm_dialog` is open the `topic_edit_save` button is still in focus.
Therefore pressing enter causes the `topic_edit_save` button to be
pressed causing multiple `confirm_dialog` modals to be created.
This commit sets `focus_submit_on_open` to `true` so that the
`confirm_dialog` is in focus when it is opened and pressing enter
will cause the `confirm_dialog` to be closed.
=> topic: Focus on confirm dialog when merging topics.

help/desktop-notifications.md
Adding a clarification in response to https://github.com/zulip/zulip-desktop/issues/1376. Should this PR be marked as fixing it?
Current: https://zulip.com/help/desktop-notifications#testing-desktop-notifications
Updated:
=> help: Add a note about unread count badge when testing notifications.

web/src/click_handlers.js, web/src/pm_list.ts, web/src/resize.ts, web/styles/left_sidebar.css, web/templates/left_sidebar.hbs, web/tests/pm_list.test.js
While the TODO comment we deleted in left_sidebar.css says we need to rewrite both show more and show less button to grids; show more was already a grid. There have been some very slight changes in the actual size of the back to channels row; those changes make the row more consistent with the rest of the left sidebar rows in terms of sizing.
We've introduced a new class called `.hide-more-direct-messages-text` that applies the same properties as the `span` selector used to. We are using a class because of better performance when selecting, see https://chat.zulip.org/#narrow/stream/6-frontend/topic/CSS.20selector.20performance/near/1845719 for more info on the why, The `font-size` was moved inside the above class, so that when setting the line-height of the anchor component, the `em` …
=> left_sidebar: Rewrite `back to channels` to use css grid.

web/styles/zulip.css
Using flexbox to left-align icon with the text on the first line in compose dropdowns.
Fixes part of #30469.
Before:
After:
<details>
</details>
=> compose: Align multi-line text in compose box dropdown.

corporate/views/upgrade.py, zerver/lib/typed_endpoint_validators.py
migrate the following endpoints from `@has_request_variables` to `@typed_endpoint` :
- `upgrade()`
- `remote_realm_upgrade()`
- `upgrade_page()`
- `remote_server_upgrade()`
=> corporate-upgrade: Migrate to @typed_endpoint.

help/channel-feed.md, help/combined-feed.md, help/include/configure-channel-links.md, help/include/sidebar_index.md, help/keyboard-shortcuts.md, help/left-sidebar.md, web/templates/keyboard_shortcuts.hbs
**1st commit:**
<details>
<summary>
Channel -> channel feed in keyboard shortcuts docs
</summary>
</details>
**2nd commit:**
<details>
<summary>
New channel feed page
</summary>
</details>
**3rd commit:**
Current: https://zulip.com/help/left-sidebar
<details>
<summary>
Left sidebar page
</summary>
---
</details>
=> help: Document channel feed and new channel link setting.

web/src/info_overlay.ts, web/styles/widgets.css
Since we more space now in info overlay after recent width increase and 40 / 60 split between columns, we have the space to show the poll header at its normal font size of `18px` without making it wrap to the next line at even medium width.
14px
| --- | --- |
| <img width="674" alt="Screenshot 2024-07-09 at 11 24 26 AM" src="https://github.com/zulip/zulip/assets/25124304/2c75c6f7-eba5-4ee5-a36f-0b9df1aa9e55"> | <img width="749" alt="Screenshot 2024-07-09 at 11 20 04 AM" src="https://github.com/zulip/zulip/assets/25124304/5744834b-dd61-4c8c-bd68-afb748e6ae81"> |
16px
| --- | --- |
| <img width="775" alt="Screenshot 2024-07-09 at 11 20 30 AM" src="https://github.com/zulip/zulip/assets/25124304/db7ed414-29bc-4e2e-a78d-e712d2da46b3"> | <img width="846" …
=> info_overlay: Render poll widget header without font size reduction.

web/src/tippyjs.ts, web/templates/settings/admin_emoji_list.hbs, web/templates/settings/admin_linkifier_list.hbs, web/templates/settings/admin_profile_field_list.hbs, web/templates/settings/alert_word_settings_item.hbs, web/templates/settings/bot_settings.hbs, web/templates/settings/default_stream_choice.hbs, web/templates/settings/organization_profile_admin.hbs, web/templates/settings/profile_settings.hbs, web/templates/settings/uploaded_files_list.hbs, web/templates/stream_settings/stream_settings.hbs
This is a completion PR for #27913.
Currently Zulip uses default hover-box at some places which is inconsistent with the present tooltip format i.e tippy which Zulip uses now.
This PR replaces all the default-hover box type tooltips with tippy tooltips to maintain consistency and provide better experience.
It also removes some of the additional tooltips which display the same content as their parent and were unnecessary.
Fixes: #27817 
Co-Authored-By: peterssonlinn
<details> …
=> tooltips: Replace default hover-box to tippy.

web/src/stream_ui_updates.js, web/styles/app_components.css, web/styles/dark_theme.css, web/styles/modal.css, web/styles/settings.css, web/styles/subscriptions.css, web/templates/stream_settings/stream_types.hbs
**First commit**, fixes crreator pill dark theme issue reported in [#29425(comment)](https://github.com/zulip/zulip/pull/29425#discussion_r1573483703)
| ![image](https://github.com/zulip/zulip/assets/133781250/1e64533c-0981-43ec-b89f-511575c408b9) | ![image](https://github.com/zulip/zulip/assets/133781250/43f5e7a1-dbf9-4177-8055-d52b119deac2) | 
**Second and third commit**, fixes `Advanced configurations` issue reported in [CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Stream.20settings.20advanced.20configurations.20always.20enabled/near/1831470)
| ![image](https://github.com/zulip/zulip/assets/133781250/3f783382-0824-4110-afa3-79a53589e096) …
=> Fix visual bugs in stream settings.

web/styles/settings.css, web/templates/settings_overlay.hbs
Instead of showing ellipsis if the content of the tab switcher is more than the width, we now allow it to take more width to show full text.
Increased 5px with of left sidebar:
Mobile sizes:
=> settings: Allow tab switcher text to expand to show full text.

web/styles/app_variables.css, web/styles/compose.css
compose: Remove dividers and reduce button width at narrow mobile sizes.
At widths under 400px, buttons in the popover were running off the edge, which is fixed by removing the dividers between them.
For the new info density, buttons in the original row, even despite removing the dividers, were still not fitting, so their width has been slightly reduced.
compose: Adjust media queries for the buttons row as per info density.
compose_box: Scale send buttons with info density.
Because the formatting buttons are integrated with the message box, the send button and its accompanying vdots now share the same button dimensions.
compose_box: Scale formatting buttons with info density.
Fixes: [one of the 2 issues mentioned in this CZO message](https://chat.zulip.org/#narrow/stream/101-design/topic/t …
=> compose: Scale compose formatting buttons and send area elements with info density.

web/templates/introduce_zulip_view_modal.hbs
- Make more succinct; don't over-describe UI the user can't see yet.
- Remove links (there are help links in view descriptions now).
- Explain where topics come from.
|Before | After |
| --- | --- |
|![Screenshot 2024-07-09 at 14 25 09@2x](https://github.com/zulip/zulip/assets/2090066/354d00f2-4c9e-4842-8727-215e630952b5) | ![Screenshot 2024-07-09 at 14 55 47@2x](https://github.com/zulip/zulip/assets/2090066/b0aecdd8-ac2d-4c18-9477-d71a9994c5bc) |
| ![Screenshot 2024-07-09 at 14 33 53@2x](https://github.com/zulip/zulip/assets/2090066/075e58e0-e00c-42fa-940d-9e8d8170fbc3) | ![Screenshot 2024-07-09 at 14 58 12@2x](https://github.com/zulip/zulip/assets/2090066/e3bd8598-1068-46a2-9cc3-9ba1c6dd651e) |
| --- | --- |
Notes:
- I think it's actually a good feature that the content is basically the …
=> onboarding: Update introductions to Inbox and Recent conversations.

web/styles/search.css
=> search: Vertically center search pills in search bar.

web/src/activity_ui.ts, web/templates/inbox_view/inbox_row.hbs, web/templates/popovers/user_card/user_card_popover.hbs, web/templates/recent_view_row.hbs, web/templates/user_profile_modal.hbs, web/tests/activity.test.js
Currently, the user circles indicating presence are not synced across the frontend. In this PR, we sync them across:
- Inbox row
- Recent view row
- User card popover
- User profile modal
Fixes #30536
**Screen capture**
*After few moments of inactivity, when the presence status of ZOE is updated to blank circle, all the circles turn blank*
*Likewise, upon logging ZOE in again, all circles turn green*
https://github.com/zulip/zulip/assets/88523649/91264c7d-151f-4e6d-8c50-2e8d2197990e
<details>
Completed …
=> user_status: Live update user status icon in recent conversations.

web/src/tippyjs.ts, web/src/user_group_popover.ts, web/styles/app_variables.css, web/styles/popovers.css, web/templates/popovers/user_group_info_popover.hbs
As part of the popover menu redesign, this PR redesigns the user group info popover using the new "popover-menu" tippy theme and improves accessibility by using appropriate ARIA attributes.
Fixes part of #28699.
| Header | Header | Header |
| Light Mode | <img width="480" alt="image" src="https://github.com/zulip/zulip/assets/82862779/37d87228-81ab-4323-a78f-34b8fa920ee5"> | <img width="480" alt="image" src="https://github.com/zulip/zulip/assets/82862779/4c556906-2337-4b56-af4f-451f59eae7c7"> |
| Dark Mode | <img width="480" alt="image" src="https://github.com/zulip/zulip/assets/82862779/0ec1c505-53eb-41b6-a169-00945aff1d70"> | <img width="480" alt="image" src="https://github.com/zulip/zulip/assets/82862779/940e9a49-eed8-426 …
=> user_group_popover: Redesign popover using the new "popover-menu" theme.

web/styles/popovers.css, web/styles/search.css, web/styles/typeahead.css, web/styles/zulip.css
Fixes #30780
| --- | --- |
| <img width="368" alt="Screenshot 2024-07-10 at 5 32 15 PM" src="https://github.com/zulip/zulip/assets/25124304/133d897e-c5ae-419a-ac3b-dd4707d5b2d9"> | <img width="394" alt="Screenshot 2024-07-10 at 5 31 00 PM" src="https://github.com/zulip/zulip/assets/25124304/22f4d47e-0e95-4a9b-a72e-bf1a3c052b24"> |
| <img width="371" alt="Screenshot 2024-07-10 at 5 32 10 PM" src="https://github.com/zulip/zulip/assets/25124304/20c2f327-e9a1-46a2-a6ad-6492e7feb5ee"> | <img width="384" alt="Screenshot 2024-07-10 at 5 31 09 PM" src="https://github.com/zulip/zulip/assets/25124304/eaa69da4-d7b6-44cd-88b6-14cc51f900ff"> |
| <img width="368" alt="Screenshot 2024-07-10 at 5 32 03 PM" src="https://github.com/zulip/zulip/assets/25124304/a7c4e02f-7624-4bf5-8e5b-a2df3 …
=> Scale typeaheads and dropdowns with font size.

web/styles/app_components.css
This fixes the issue where the lock icon, most noticeably in the compose recipient stream dropdown, was placed too high.
Fixes: [CZO issue report](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20channel.20privacy.20icons.20in.20typeahead/near/1882568)
<details>
</details>
=> css: Exclude lock icons in dropdowns from being unnecessarily pulled up.

web/styles/input_pill.css, web/styles/search.css
**in the search bar**
before:
after:
------
**in the typeahead**
before:
after:
=> search pills: Fix some UI bugs with long pills.

web/templates/move_topic_to_stream.hbs
Changed the `Select a channel below or change topic name.` instruction in `move topics/move messages` modal. 
1) On the `Move topic` modal, dropped the line
2) On the `Move messages` modal, replaced the line with `Move messages to:`
Fixes #30055
-- Instructions on `Move messages/topics` modal after and before changes --
*before changes*
*after changes *
<details>
</details>
=> popovers: Simplify instructions for moving topics/messages

corporate/views/remote_billing_page.py, zerver/lib/attachments.py, zerver/lib/export.py, zerver/lib/message.py, zerver/lib/onboarding.py, zerver/lib/soft_deactivation.py, zerver/lib/streams.py
When using the sub-expression purely for filtering, and not for accessing the value in the resultset, .alias() is potentially faster since it does not pull the value in as well.
<details>
</details>
=> django: Switch to .alias() instead .annotate() where possible.

web/src/stream_popover.js, web/templates/popovers/left_sidebar/left_sidebar_stream_actions_popover.hbs
Changes in this PR:
- Grouped related actions in the channel actions popover for better usability.
- Added a menu option to copy the channel feed link to the clipboard.
- Enabled the stream popover for spectators, showing only the "Copy link to channel" option.
- Added a conditional link to the "Personal" tab in channel settings if the user lacks permission to change channel permissions.
Fixes: #30529
| Channel settings | <img width="278" alt="Screenshot 2024-06-29 at 12 31 50 AM" src="https://github.com/zulip/zulip/assets/82862779/713fbba7-fab9-42a4-85e9-2396b8a15f86"> | <img width="278" alt="Screenshot 2024-06-28 at 11 34 01 PM" src="https://github.com/zulip/zulip/assets/82862779/014d9d8a-7998-483 …
=> stream_popover: Organize and improve the left sidebar channel menu.

web/src/portico/help.js
We were trying scroll the highlighted element but it also scrolls the parent elements leading to scrolling of the help doc.
We don't need to scroll here at all actually since focused element is scrolled to be visible by default. Tested in chrome, firefox and safari on mac by going to http://aman.zulipdev.org:9991/help/support-zulip-project
fixes: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20landing.20low.20on.20help.20pages
dones't fix: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20anchor.20link.20partially.20hidden.20in.20help.20center (which I still cannot reproduce)
=> help: Fix help center loading scrolled down.

zerver/lib/email_mirror.py, zerver/tests/test_email_mirror.py
Besides "RE:" and "FWD:", "AW:" (from German *Antwort* for *answer*) is another common prefix in email subjects. Let email mirror automatically remove it as well.
<details>
</details>
=> email_mirror: Also strip "AW:" from subject

web/src/settings_users.js, web/styles/settings.css, web/templates/settings/admin_user_list.hbs
Fixes: #29894
> One small bug that I noticed - when I reactivate a user in "Deactivated users" list, the row of the reactivated user becomes faded, but when I click on any of the column heading to change the sorting, the row is not faded. I think it should still be faded like it is when sorting changes after deactivating a user in "Users" list.
This is fixed by the second commit.
#29986 was mostly correct in its underlying implementation, it was missing the fix for a case noted during testing, for which I've added the second commit. 
In terms of changes to the original PR, the variable name has been changed from `display_last_active_in_table` to `display_last_active_column` since `in_table` part was redundant in that context. 
<details>
<summary>Active …
=> settings: Don't show last active in deactivated users table. 

web/src/bootstrap_typeahead.ts, web/src/composebox_typeahead.ts, web/src/custom_profile_fields_ui.ts, web/src/pill_typeahead.ts, web/src/search_suggestion.ts, web/src/settings_playgrounds.ts, web/src/typeahead_helper.ts, web/styles/compose.css, web/styles/search.css, web/styles/typeahead.css, web/tests/composebox_typeahead.test.js, web/tests/pill_typeahead.test.js, web/tests/search_suggestion.test.js
To increase the number of options available for the user to pick from, we increase the limit of options shown to 50 for all typeaheads, and make the menu scrollable. The max height is set to original height of the composebox typeahead menu, which fit 8 options.
A thorough audit of the effect of this change on the performance of the typeaheads will probably be needed, followed by reduction of the maximum number of options shown if and where necessary.
Fixes: #20620.
Composebox:
Search:
Move message modal:
Code playground settings:
Adding channel's members to user group:
<details> …
=> typeahead: Make menu scrollable with upto 50 items.

help/invite-new-users.md, web/src/invite.ts
Updates strings in the user invite modal to use "invitation" as the noun/adjective in strings, instead of "invite".
See [relevant CZO design discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/invite.20user.20modal.3A.20.22invite.22.20strings/near/1852874).
*Note that these are all internationalized strings and will need translation updates.*
<details>
<summary>Invite user modal - email invitations</summary>
</details>
<details>
<summary>Invite user modal - invitation link</summary>
*Before submitting*
*After submitting*
</details>
<details>
<summary>Help center - create reusable invitation link instructions</summary>
[Current documentation](https://chat.zulip.org/help/invite-new-users#create-a-reusable-invitation-link)
</details>
--- …
=> invite-users: Use "invitation" instead of "invite" for strings.

web/src/ui_init.js
`information_density.initialize` uses `timerender.stringify_time`, and thus requires `timerender.initialize` to have been called first.
Cc @karlstolley (7291f0a9192c3bc114f0e5a73c27a83e033a4c22, #29569).
=> ui_init: Initialize `timerender` before `information_density`

web/src/user_groups.ts, zerver/lib/exceptions.py, zerver/lib/user_groups.py, zerver/tests/test_realm.py, zerver/tests/test_user_groups.py, zproject/default_settings.py, zproject/dev_settings.py, zproject/test_extra_settings.py
- First commit is for the backend changes to allow only system groups.
- Second commit is to not show user defined groups in webapp UI.
<details>
</details>
=> Allow only system groups to be used as setting in production.

web/src/click_handlers.js, web/styles/left_sidebar.css
First commit fixes https://github.com/zulip/zulip/pull/30707#discussion_r1669110661.
Second commit fixes https://github.com/zulip/zulip/pull/30332#discussion_r1669198527. 
For the second commit, I considered changing the HTML structure have a selector that will encapsulate all elements of the section header except the filter. But in that case also, we need the DM filter to narrow on click around the edge of the DM list filter in the empty space, which might not happen after changing the HTML structure. I'm not committed to the current approach in the PR, so suggestions are welcome!
| -- | -- |
| <img width="285" alt="Screenshot 2024-07-10 at 2 49 48 PM" src="https://github.com/zulip/zulip/assets/13910561/96925503-ed63-467a …
=> Direct messages code cleanup followups

web/src/settings_panel_menu.js
We changed the scope of the selector to just the switcher. This means that the hotkeys will only run when the user focuses on that element. This follows the same pattern as the `Personal` and `Organization` tab switchers which limit the hotkey area to their tab list and not the content. If we want to use hotekeys inside the content, just filtering out INPUT elements in keydown_util might be better. 
Fixes https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20Org.20settings.20user.20search.20does.20not.20work.20with.20vim.20hotkeys.2E/near/1882313
<details> …
=> settings: Do not execute hotkey inside any users tab filter input.

web/src/buddy_list.ts
Earlier in right sidebar user count, it would show less user count when a bot was present as a recipient in the conversation. Since the sidebar shows active human users only, user count should not consider bots in the conversation.
This PR fixes the behaviour by adding all the subtracted bots from user count.
Fixes: [czo](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20incorrect.20user.20counts.20in.20right.20sidebar.20in.20bot.20DMs)
<details> …
=> Fix incorrect user count in sidebar with bot as recipient.

web/styles/search.css
before:
after:
CZO: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20search.20pills.20alignment
=> search pills: Align typeahead text with pills.

web/styles/search.css
before:
after:
CZO: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20x.20icon.20in.20search.20box
=> search: Enlargen x button in search bar.

web/src/search.ts
`on_search_contents_changed` resets the search bar on input change in the "freshly opened" state. We shouldn't be calling this when removing pills, since removing pills should always remove the freshly opened state, not reset the search bar.
This bug was reported on CZO:
https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20message.20search.20'x'.2Fdelete/near/1883828
Note: After deleting a pill, the next pill will be highlighted. This is a feature of input pill and happens for all input pills, so I didn't bother changing it here even though I think it would be better to put focus in the text area.
=> search pills: Fix bug closing multiple pills on fresh open.

web/src/copy_and_paste.ts, web/src/hash_util.ts, web/tests/copy_and_paste.test.js
- Pasting a link to the same zulip server transforms it to the `#**stream>topic**` syntax.
- The link may or may not contain topic, but must contain a stream (else it is unaffected).
-  `Ctrl+Z` replaces the transformed link with the original pasted url.
- The feature works even when only the stream id is present in the pasted url, and not the name.
- Invalid urls are not transformed (a url with valid syntax but invalid stream id is considered invalid too).
Fixes #29136
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/.2329136.20Paste.20stream.20and.20topic.20links.20with.20nice.20formatting)
<details>
Sample input:
Compose box:
After being sent:
</details>
<details> …
=> compose: Implement formatting of channels and topics on paste

web/src/add_subscribers_pill.ts, web/src/stream_create_subscribers.ts, web/src/user_group_pill.ts, web/src/user_group_popover.ts, web/src/user_groups.ts, web/templates/popovers/user_group_info_popover.hbs, web/tests/user_group_pill.test.js, web/tests/user_groups.test.js
Fixes: #30690 . This PR implements the second remaining part of #30690.
Changes in addition to the original issue description:
1. For the user group popover, the `group settings` link is not shown for system groups after this PR since they are immutable.
2. For user group popover, it only showed the direct members of the group before this PR. Now, we should all members of a group including subgroup members. This will change the behaviour everywhere where the user group popover is being used, but since that might the desired behaviour, that shouldn't be an issue hopefully.
3. User group pill did not count subgroup members as part of its count before, now it does. This will affect all user group pills, but since that might be the desired behaviour, that shouldn't be an issue hopefully.
For …
=> stream_create: Add "all users: N" pill to input on clicking `Add all users`

help/link-to-a-message-or-conversation.md
Current: https://zulip.com/help/link-to-a-message-or-conversation
Updated:
=> help: Update documentation on linking to topics and channels.

help/moderating-open-organizations.md, zerver/lib/zulip_update_announcements.py
[CZO discussion](https://chat.zulip.org/#narrow/stream/438-release-management/topic/zulip_updates.20items.20of.20note/near/1884247)
Message (links work):
--
Help center commit:
Before: https://zulip.com/help/moderating-open-organizations#minimize-spam
After:
=> Zulip Updates + help center tweak

web/styles/typeahead.css
=> Fix typeahead spacing and alignment issue.

zerver/models/custom_profile_fields.py, zerver/tests/test_custom_profile_data.py, zerver/tests/test_users.py
bulk fetch query of `UserProfile` against which user_ids are validated, instead of looping over `user_ids` and fetching each `UserPfrofile` resulting in `O(n)` queries.
raises `ValidationError` showing all the invalid ids in one line instead of one exception per the first encountered invalid id.
=> custom_profile_fields: improve check_valid_user_ids() efficiency.

api_docs/changelog.md, api_docs/construct-narrow.md, version.py, web/src/filter.ts, web/src/hash_parser.ts, web/src/message_fetch.js, web/src/message_view.js, web/src/narrow_state.ts, web/tests/filter.test.js, web/tests/narrow_activate.test.js, web/tests/narrow_unread.test.js, zerver/lib/narrow.py, zerver/tests/test_message_fetch.py, zerver/views/message_fetch.py
**Commit 1**: adds a new narrow operator -- "with" which expects a string operand of message_id, and returns all the messages in the same channel and topic of the operand, with the first unread message of the topic as anchor.
cherry-picked commits into #30644:
**Commit 2**: Converts #-mention of topics to permalinks.
**Commit 3**: Converts left sidebar topic links and `Copy link to topic` to permalinks.
Fixes: #21505 
<details>
</details>
=> topics: Convert topic links to permalinks.

web/styles/search.css
This reverts #30804. We need a followup PR to address the issue that PR was trying to solve without breaking icon alignment.
https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20buggy.20.60x.60.20button.20in.202-line.20search.20box/near/1886781
=> search pills: Align icons on top row.

analytics/lib/counts.py, analytics/tests/test_counts.py, corporate/lib/stripe.py, tools/droplets/create.py, zerver/actions/bots.py, zerver/actions/streams.py, zerver/lib/compatibility.py, zerver/lib/export.py, zerver/lib/generate_test_data.py, zerver/lib/import_realm.py, zerver/lib/markdown/__init__.py, zerver/lib/markdown/api_arguments_table_generator.py, zerver/migrations/0486_clear_old_data_for_unused_usermessage_flags.py, zerver/migrations/0501_mark_introduce_zulip_view_modals_as_read.py, zerver/migrations/0513_copy_groups_data_to_named_user_group.py, zerver/openapi/markdown_extension.py, zerver/tests/test_management_commands.py, zerver/tests/test_message_delete.py, zerver/tests/test_message_edit.py, zerver/tests/test_message_move_stream.py, zerver/tests/test_message_move_topic.py, zerver/tests/test_message_send.py, zerver/tests/test_push_notifications.py, zerver/worker/missedmessage_mobile_notifications.py
https://docs.astral.sh/ruff/rules/non-augmented-assignment/
=> ruff: Fix PLR6104 Use `+=` to perform an augmented assignment directly

zerver/data_import/slack.py, zerver/lib/cache.py, zerver/lib/markdown/__init__.py, zerver/lib/templates.py, zerver/tests/test_auth_backends.py
https://docs.astral.sh/ruff/rules/repeated-global/
=> ruff: Fix FURB154 Use of repeated consecutive `global`, `nonlocal`

zerver/lib/notes.py, zerver/lib/outgoing_webhook.py, zerver/lib/queue.py
https://docs.astral.sh/ruff/rules/meta-class-abc-meta/
=> ruff: Fix FURB180 Use of `metaclass=abc.ABCMeta`

corporate/views/remote_activity.py, zerver/tests/test_custom_profile_data.py
https://docs.astral.sh/ruff/rules/unnecessary-enumerate/
=> ruff: Fix FURB148 `enumerate` index or value is unused

web/src/popover_menus_data.js, web/templates/popovers/navbar/navbar_personal_menu_popover.hbs
=> personal_menu: Don't show user local time.

web/src/input_pill.ts, web/tests/input_pill.test.js
We decided this is more likely to be where the user wants the focus to be after exiting a pill with the x button.
CZO:
https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20message.20search.20'x'.2Fdelete/near/1886757
=> input pills: Focus input after removing a pill with x button.

web/src/compose_recipient.ts, web/src/compose_validate.ts, web/src/settings_org.js, web/src/user_groups.ts
Adds `is_empty_group` function in `user_groups.ts` to check for nobody group and removes hardcoded checks of `"role:nobody"`.
Follow-up for #28470.
Fixes: 
<details>
</details>
=> user_groups: Add `is_empty_group` function to check for nobody group.

web/src/filter.ts, web/src/message_events.js, web/tests/filter.test.js
We used to just drop moved messages from the list of messages to update if we didn't have them cached. So, if the user is in the narrow where messages were moved to, user will not see the moved message if they were not cached locally.
To fix this, we re-render the narrow after fetching messages from the server.
We don't want to use `fast_track_current_msg_list_to_anchor` here since that function assumes that current rendered state of the message list is correct which is not the case here.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20moved.20messages.20not.20with.20client.20locally
=> message_events: Fix moved messages not rendered if they are not cached.

web/styles/compose.css, web/templates/compose.hbs, web/templates/lightbox_overlay.hbs
Preparatory PR for #30895.
I've checked most instances of `.small` class and removed `.small` class in 2 instances were it was being overriden. I've checked the buttons with text for getting their properties overriden, but the buttons with icons, since I noticed a pattern of them using the `.small` properties. The goal of this PR is not to remove `.small` for ALL possible cases, but just the ones that I noticed. 
This PR makes no visual changes, the screenshots are just for comparison b/w the before and after state.
<details>
<summary> Commit 1 (compose box): </summary>
Devtools screenshot showing the overriden properties:
| Compose box - full screen - 14px - before | Compose box - full screen - 14px -  after | Compose box - full screen - 16px before | …
=> Remove instances of unnecessary `.small` classes

web/src/message_fetch.js
This helps keep the app working and avoids functionalities like insert messages from breaking when we don't the message id cached which ideally we should have.
=> recent_view: Catch errors in trying to get message from id.

web/src/compose_recipient.ts, web/src/dropdown_widget.ts, web/src/integration_url_modal.ts, web/src/settings_org.js, web/src/settings_streams.ts, web/src/settings_users.js, web/src/stream_edit.js, web/src/stream_popover.js, web/src/stream_settings_components.js, web/src/user_group_components.ts, web/src/user_profile.js, web/src/views_util.ts
We generalize the approach used for compose box to apply it for all the dropdowns.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/dropdown.20widget.20not.20fully.20visible.2E
Tested all the dropdowns at various heights.
=> dropdown: Fix dropdown partially hidden at small heights.

web/styles/subscriptions.css
Fixes #30675
This PR doesn't completely fix the issue but does a reasonably good job at it. I think we need to add icons here and use ellipsis for text overflow to completely fix the issue.
| --- | --- |
| <img width="849" alt="Screenshot 2024-07-15 at 11 42 38 AM" src="https://github.com/user-attachments/assets/e219b972-601f-4f65-b563-aa73238f4c16"> | <img width="902" alt="Screenshot 2024-07-15 at 11 43 35 AM" src="https://github.com/user-attachments/assets/39aa4aba-00ab-4185-a2e2-ce23d1021068"> |
Some other screen sizes:
=> subscriptions: Keep individual tabs in the same row.

web/tests/i18n.test.js
Before this, settings_tab.hbs was being used to test the `{{#tr}}` syntax for tagging strings for translation. That was introduced in 82b5d9304b1b968f8be6f2d1e605360537eb3786, when the template in question was small enough to mock.
There are smaller templates than `user_notification_settings` but since none of them are used as a partial in another template, we can't use them for this test. This is because we can't test partial block handling part of the tr tag in templates.js with those templates. Since `user_notification_settings` has only 1 partial, it will atleast make it easier for us to know which arguments to pass to the template; in comparison to `settings_template` where it was hard to determine which arguments were supposed to be passed to the template.
I've also renamed the test …
=> i18n: Use user_notification_settings for tr_tag tests.

web/src/input_pill.ts, web/src/message_view.js, web/src/search.ts
Alya said on CZO:
> It used to be the case that selecting something from the typeahead immediately performed a search. Now, you have to press Enter again for the search to happen. Is this change intentional?
I said:
> Yes it is, because selecting from the typeahead is the main way to create a pill, and if you want a multi-pill search it can be annoying for the search bar to close and initiate a search after each pill you create.
>
> The first enter is for pill validation/creation, the second enter is for searching. When I was working on search pills I thought this might not feel great but couldn't think of a different way to go about it. Definitely open to ideas!
Alya said:
> it should leave the search open and your cursor in it, but navigate your view based on the current set of inputs.
=> search: Update narrow when search bar contents change. 

web/styles/settings.css
Fixes #30674.
The previous method was using `min-width` as a proxy for padding which led to unusually high padding for very short strings and no padding for long strings. It also had an issue where changing the font-size changed the alignment with the search filter. 
Another issue that you might notice is that the all these filters have a fixed height, which leads to a decrease in padding when changing the font size, the whitespace would become oh-so-slightly smaller on increasing the font size. This probably should be fixed but it is out of scope of this PR since it would apply to all the filters in settings panel. [CZO link](https://chat.zulip.org/#narrow/stream/9-issues/topic/Filters.20with.20fixed.20height.20in.20settings.20panels/near/1886187).
| Long button - 14px - before    | Long …
=> settings: Fix Add channel button relying on min-width for padding.

web/templates/bookend.hbs
Description:
This PR removes the word "channel" from the stream status to streamline the messaging and improve clarity. The changes ensure that the status messages are concise and focused.
Fixes: #30803
|----|-----|
|<img width="617" alt="Screenshot 2024-07-10 at 12 37 36 PM" src="https://github.com/zulip/zulip/assets/113302312/2365c544-85ec-431f-920a-6d933dcb4503">| You unsubscribed from #fsad|
The screenshot is not provided for the after because using the localhost (via vagrant ssh) is not giving any log in the new channel. This might be an issue that only I'm facing as I have done some changes in the past for other issues. If this is an issue and I'm able to fix this then I will upload the picture for the after.
<details> …
=> edit_stream_status: Removed the word channel from the stream_status

docs/production/system-configuration.md, puppet/zulip/manifests/app_frontend_base.pp, puppet/zulip/templates/supervisor/zulip.conf.template.erb, zproject/computed_settings.py, zproject/test_extra_settings.py
The memory costs are low (~60MB), and likely worth the stability.
=> katex: Default the server on.

zerver/management/commands/register_server.py
This is needed for the command to work in docker-zulip, where the zulip user may not have write permissions to the parent directory of the secrets file. By default, crudini creates a temporary file, which makes the command fail under those conditions.
With --inplace, the secret file gets written to directly without creation of temporary files.
=> register_server: Call crudini with --inplace when rotating secret key.

web/styles/app_components.css, web/styles/left_sidebar.css, web/styles/modal.css, web/styles/popovers.css
As part of the efforts to allow the UI to scale with the font-size, this PR makes changes in the popover-related css to allow for font-scaling in the popovers.
The base work for this was done by @karlstolley in #30745.
Fixes: Part of #30476.
| ![add-channel-before](https://github.com/user-attachments/assets/9d1b5d55-d10f-49cb-b10b-04fbb33b3df9) | ![add-channel-after](https://github.com/user-attachments/assets/29946551-1cb4-4c1f-a797-7ba8957923fa) |
| ![group-info-before](https://github.com/user-attachments/assets/9ed71926-2a7f-46cd-a626-318fa4c6cc04) | ![group-info-after](https://github.com/user-attachments/assets/e3f927e3-012f-4279-b960-8ef4fb9586be) |
| …
=> popovers: Allow popover menus to scale with font-size.

web/src/filter.ts, web/src/narrow_state.ts, web/tests/filter.test.js, web/tests/narrow_unread.test.js
Previously, when "adjusted_terms_if_moved" was called for non stream messages, it used to return "null" for adjusted terms. This is true for some extent since the non stream messages can not be moved.
However, in case of narrow containing "with" operator, this would be buggy since there, we want the narrow terms to be adjusted according to the "with" operand to point to the current narrow, rather than returning null.
This commit updates the method to return null only if  the "raw_terms" dont contain "with" operator. Else, adjust the "raw_terms" according to the message.
`commit 1`: Fixes checkbox 6 of https://github.com/zulip/zulip/pull/30114#issuecomment-2226642678
`commit 2`: Fixes checkbox 7 of https://github.com/zulip/zulip/pull/30114#issuecomment-2226642678
<details> …
=> topic permalinks follow up commits

corporate/views/upgrade.py, zerver/lib/typed_endpoint_validators.py, zerver/tests/test_realm.py, zerver/tests/test_typed_endpoint_validators.py, zerver/tests/test_user_topics.py, zerver/tests/test_users.py, zerver/views/realm.py, zerver/views/realm_domains.py, zerver/views/realm_emoji.py, zerver/views/realm_linkifiers.py, zerver/views/realm_logo.py, zerver/views/realm_playgrounds.py, zerver/views/user_topics.py, zerver/views/users.py
The first commit creates a function that returns an `AfterValidator`. This makes it possible to avoid using the lambda wrapper everywhere, making the code cleaner.
Migrate `realm.py`, `realm_domains.py`, `realm_emoji.py`,
`realm_linkifiers.py`, `realm_logo.py`, `realm_playgrounds.py`
to typed_endpoint.
=> Realm-typed-endpoint

help/follow-a-topic.md, help/resolve-a-topic.md, help/search-for-messages.md
Notes:
- Repeated text could be extracted to /include. Not sure it's worth it at this stage?
Current: https://zulip.com/help/follow-a-topic
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/resolve-a-topic
<details>
<summary>
Updated
</summary>
</details>
[CZO discussion ](https://chat.zulip.org/#narrow/stream/19-documentation/topic/.60has.3A.60.20search.20filter.20help.20section/near/1890436)(or just me talking to myself?)
Current: https://zulip.com/help/search-for-messages#search-for-attachments-or-links
<details>
<summary>
Moved `has:reaction` 
</summary>
</details>
=> help: Add search to documentation to pages on followed topics and resolved topics

web/styles/popovers.css
As noted in PR #30849, the stream lock icon was not positioned correctly in the stream actions popover and this was being exaggerated at 16/140.
This commit overrides the margin-top set on the stream lock icon at the top-level in `app_components.css`, since we don't need to pull up this icon for the stream actions popover header.
Fixes: [Issue mentioned in #30849 comments](https://github.com/zulip/zulip/pull/30849#issuecomment-2229023244)
| ![Screenshot 2024-07-16 at 2 54 29 PM](https://github.com/user-attachments/assets/a74ad3b9-8700-475d-b1e7-147fd1dbc680) | ![Screenshot 2024-07-16 at 2 52 52 PM](https://github.com/user-attachments/assets/27b07fa4-2f34-4f85-978f-697987e2fdc3) | 
<details> …
=> stream_popover: Fix stream lock icon position in stream actions popover.

zerver/lib/export.py, zerver/lib/import_realm.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20No.20data.20exported.20for.20table.20zerver_onboardingusermessage/near/1885788)
https://github.com/zulip/zulip/pull/30142#issuecomment-2220901079
> @prakhar1144: Our export tool is mildly unhappy with the new table:
> 2024-07-10 15:54:20.993 WARN [] ??? NO DATA EXPORTED FOR TABLE zerver_onboardingusermessage!!!
PR to add support to export and import `OnboardingUserMessage` table properly.
<details> …
=> Add support to export and import `OnboardingUserMessage` table.

web/src/filter.ts, web/src/search_suggestion.ts, web/templates/search_description.hbs, web/tests/filter.test.js, web/tests/search_suggestion.test.js
Earlier in search suggestion, has: operator returned two different suggestion string which were `messages with one or more links` and `messages that contain links`.
This PR changes this to a consistent suggestion string.
Fixes: zulip#30908
<details>
</details>
=> Change search suggestion string for has: operator.

zerver/tests/test_auth_backends.py, zerver/tests/test_signup.py, zproject/computed_settings.py
`SHA1PasswordHasher` will be removed in Django 5.1. `MD5PasswordHasher` will remain for the purpose of speeding up tests.
- Followup to commit ac5161f4397eb6d984cdc27f56fba52f6a220af2 (#29620).
=> tests: Remove deprecated SHA1PasswordHasher

web/styles/compose.css, web/styles/message_row.css
This PR removes a one-off color declaration from the message-edit box to ensure that `--color-text-default` appears when editing a message.
Additionally, this corrects for an even subtler bug: it fixes the browser-default `#000`-equivalent on the compose textarea in light mode by specifying that the textarea there also takes `--color-text-default` (that was already handled correctly in dark mode, thanks to a `color: inherit` declaration in dark theme that picked up `--color-text-default).
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20text.20greyed.20out.20when.20editing.20message/near/1883076)
| Compose/edit mode, before | Compose/edit mode, after (no change in dark theme) |
| --- | --- |
| …
=> compose: Ensure color concord across compose and edit boxes.

corporate/lib/stripe.py, corporate/views/support.py
The previous default of `"http"` is deprecated and will change to `"https"` in Django 6.0.
https://docs.djangoproject.com/en/5.0/releases/5.0/#id2
https://docs.djangoproject.com/en/5.0/ref/forms/fields/#django.forms.URLField.assume_scheme
=> corporate: Set assume_scheme="https" for django.forms.URLField

zerver/management/commands/runtornado.py
Tornado ≥ 5 uses `AsyncIOLoop` and `AsyncIOMainLoop` automatically when appropriate. Fixes “DeprecationWarning: make_current is deprecated; start the event loop first” with warnings enabled.
=> runtornado: Remove explicit AsyncIOMainLoop installation

puppet/kandra/files/memcached_exporter, scripts/setup/flush-memcached, zilencer/management/commands/populate_db.py
Fixes warnings like `ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 33332), raddr=('127.0.0.1', 11211)>` with warnings enabled.
=> Explicitly close memcached connections

zerver/lib/narrow.py, zerver/lib/topic_sqlalchemy.py
Fixes `sqlalchemy.exc.RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0.` with warnings enabled.
https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#change-5284
=> narrow: Migrate legacy SQLAlchemy select syntax

zerver/webhooks/wekan/doc.md, zerver/webhooks/wordpress/doc.md, zerver/webhooks/wordpress/fixtures/user_register.txt, zerver/webhooks/wordpress/fixtures/wp_login.txt, zerver/webhooks/wordpress/tests.py, zerver/webhooks/wordpress/view.py
Apply integration-docs' new format for Wekan and Wordpress.
Fixes part of https://github.com/zulip/zulip/issues/29592.
<details>
<summary>Wekan</summary>
[Doc link](https://zulip.com/integrations/doc/wekan)
</details>
<details>
<summary>Wordpress</summary>
[Doc link](https://zulip.com/integrations/doc/wordpress)
</details>
<details>
</details>
=> integration-docs: Update for new format (Wekan, Wordpress).

help/read-receipts.md
Before: https://zulip.com/help/read-receipts
After:
=> help: Add keyboard tip for toggling read receipts.

web/src/filter.ts, web/tests/filter.test.js
This commit updates `ilter.is_conversation_view` to be true for `with` operator. This is important because essentially, the `with` operator lands you in the same view as the channel-topic narrow or the `dm` narrow i.e., the last unread message of the narrow.
Hence, the `with` narrow should be handled in a similar way while determining whether to allow automatically marking messages as read, or displaying the unread banner, etc.
Fixes: #30863 and checkbox 1 of https://github.com/zulip/zulip/pull/30114#issuecomment-2226642678
<details> …
=> narrow_operators: Add `with` operator to `filter.is_conversation_view`.

web/src/message_view.js, web/src/search.ts, web/tests/search.test.js
The first commit is a bug I noticed while working on this.
The second and third commits are two parts of the solution to [this reported issue](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20search.20suggestion.20narrow.20from.20recent.20and.20inbox/near/1890604)
=> search pills: Ensure correct narrow/header when search content changes.

web/src/search.ts
Some time ago, I added a condition to not reset the search bar if the user had already started typing, so that we wouldn't erase what they'd started typing. But we encountered a situation where the search bar can be opened with text in it: clicking "searching all public channels" from a search view. We want to reset the searchbox to add the `channels: public` pill.
I tried to replicate original issue I encountered where the search box resetting was clearing user input and couldn't replicate it. So for now I'm just removing that if statement.
CZO thread: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20search.20pills.20don't.20update.20on.20hash.20change
=> search: Always reset the search bar when opening it.

web/styles/compose.css, web/styles/search.css, web/styles/typeahead.css, web/styles/zulip.css
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20global.20typeahead.20styling.20in.20compose.2Ecss
There might still be some more bugs to fix here like the extra margin on the left in the wrapped user pill.
=> Fix search suggestions not wrapping to next line.

web/styles/modal.css
Fixes #30920.
This change affects all dialog boxes, so the impact is pretty widespread. I've added 1 screenshot of the dialog box for reference. But some regression testing would still be required by whoever tests this.
| 14px - before                           | 14px -  after                          | 
| -- | -- |
|                <img width="522" alt="add_emoji_14px_old" src="https://github.com/user-attachments/assets/a443924d-12fc-4625-9437-6a3c9799f2fd">                  |               <img width="520" alt="dialog_14px_emoji" src="https://github.com/user-attachments/assets/22ec60b6-9c23-4465-8f83-495cb0e180b7">                  |
| 16px - before                           | 16px -  after                          | 
| -- | -- |
|      <img …
=> Scale modal buttons when switching between 14px and 16px mode.

web/styles/app_components.css
Fixes zulip#30895. 
The root font-size for the app has always been 16px, and it remains the same when switching between 14px and 16px mode. This leads to `.small` buttons looking relatively smaller to their surroundings in 16px mode. So, if we use a unit that changes when switching between modes, we will have to multiple that value by (16/14) so that we don't change the existing behaviour for the 14px mode and make things smaller. This commit only affects `.small` buttons, the same named class is used in other places but does not use rem unit there and therefore does not require any changes. 
The original plan was to use em instead of rem and multiply it by (16/14 * 0.8), but since em depends on the parent element, there was a case in the poll button widget where 1em was equal to 16px in …
=> css: Scale font-size for .small buttons.

web/src/filter.ts, web/src/message_view.js, web/tests/filter.test.js
Previously, while using "with" operator, even when the narrow was not updated by the operator, hash change requests were made.
This commit introduces a new variable - "narrow_requires_hash_change" which determines whether the narrow was updated and thus requires a hash change or not.
`commit 1`:
Fixes: #30862 and checkbox 4 of https://github.com/zulip/zulip/pull/30114#issuecomment-2226642678
`commit 2:`
This is from https://github.com/zulip/zulip/pull/30678#discussion_r1663279010. It is important because without this you won't be able to open search bar after using permalink.
`commit 3`:
Fixes incorrect rendering of message view header title when `with` adjusts the narrow.
<details>
Communicate …
=> topic permalinks follow ups

web/styles/settings.css, web/styles/zulip.css, web/templates/dialog_change_password.hbs, web/templates/settings/api_key_modal.hbs
Fixes https://chat.zulip.org/#narrow/stream/9-issues/topic/Eye.20icon.20misaligned.20in.20Manage.20your.20API.20key/near/1890711.
Also fixes an additional issue of the `Forgot It` text not aligning properly. I've added 10px of left margin while I was at it so that text looks nicer.
The order of commits in this PR is not the nicest, but since I was not 100% sure of the approach taken in the third commit to introduce an extra div, I kept the order of commits this way so that it is easier to modify my approach if there's a better one without doing too much playing around with git history. While reading the first two commits, please note that the `margin-bottom: 10px` for each element in their respective commits is going to be removed.
| 14px - before | …
=> Fix misaligning eye icon

tools/test-js-with-node, web/src/compose_notifications.ts, web/src/echo.js, web/src/message_events.js, web/src/message_events_util.js, web/src/server_events.js, web/tests/echo.test.js
[CZO Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF400.20error.20on.20sending.20message.20while.20narrowed.20to.20search.20view/near/1851146)
* Commit 1: Fix message sent when narrowed to search view was not getting added to that view. 
* Commit 2: Fixes a 400 error during local echo while sender is narrowed to search view.
* Commit 3: Alya suggested -- https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF400.20error.20on.20sending.20message.20while.20narrowed.20to.20search.20view/near/1851376
<details><summary>Message sent when narrowed to search view (Sent message doesn't match narrow)</summary>
</img>
</details> 
<details><summary>Message sent when narrowed to search view (Sent message matches …
=> echo: Fix error during local echo while narrowed to search view.

web/styles/left_sidebar.css, web/styles/right_sidebar.css
This PR uses a resolution-based media query to adjust the top margin on user-presence circles on low-resolution screens.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20.E2.9D.93.20sagging.20presence.20icons.20in.20the.20left.20sidebar/near/1851356)
Because things like multiline DM groups are in the future (as well as non-CSS presence icons), it doesn't make sense to engage in a more drastic reworking of this area in quite the same way as a similar PR, #30692, did for the comparatively simpler, one-line elements in the navigation area.
| Low-res, before | Low-res, after |
| --- | --- |
| ![low-res-circles-legacy-before](https://github.com/user-attachments/assets/aa080d68-f1d7-4d57-aca7-831c12bbc027) | …
=> user_circles: Adjust circles top margin on low-res screens.

web/styles/app_variables.css, web/styles/search.css
This PR makes the new, info-density-aware navbar play nicely with short viewports at both 16/140 and legacy sizes.
Also, it fixes a really subtle but nasty bug with user-pill alignment on short viewports containing a user pill when focused. Tall viewports were unaffected by the bug and the fix.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20navbar.20search.20text.20not.20middle.20aligned.20on.20small.20heights/near/1892365)
| Closed search, before | Closed search, after |
| --- | --- |
| ![closed-search-before](https://github.com/user-attachments/assets/ee4cc8bd-a145-4d66-8890-d87a66fcc99e) | ![closed-search-after](https://github.com/user-attachments/assets/ae33ab59-6daa-498f-94d5-e9479e732fd6) |
| …
=> navbar_search: Make search bar conform to short viewports.

.github/workflows/codeql-analysis.yml
https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
=> ci: Upgrade github/codeql-action

web/src/compose_tooltips.ts, web/src/message_edit.js, web/src/message_list.js
[CZO bug report](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20Tippy.20tooltips.20leaking.20when.20editing.20messages/near/1886541)
Bug:
A tooltip appears on hovering over a control button in the message edit form. Now when the form was closed either using Esc key (cancel) or Enter / Ctrl + Enter (save), the tooltip didn't disappear. This resulted in a random tooltip visible
in the message list view.
Fix:
Since `tippyjs` doesn't hide tooltip even after the element is hidden we need to explicitly hide the tooltip in those cases.
See https://github.com/atomiks/tippyjs/issues/938
This PR fixes the above mentioned bug by explicitly hiding the tooltip instance.
**Before**
[screen-capture …
=> message_edit: Fix compose tooltip not hidden on closing message edit form.

web/src/server_events_dispatch.js, web/src/settings_org.js, web/src/settings_preferences.ts, web/src/settings_realm_user_settings_defaults.js, web/src/settings_ui.ts, web/tests/dispatch.test.js, zerver/actions/realm_settings.py, zerver/actions/user_settings.py, zerver/tests/test_realm.py, zerver/tests/test_settings.py, zerver/views/realm.py, zerver/views/user_settings.py
- First commit is to flush cache after commiting to DB so that the cache data is not stale.
- Second commit is to change code to require clients to pass `dense_mode` field when needed instead of changing it in the server implicitly.
- Third commit is to pass `dense_mode` field when needed from webapp.
- Fourth commit is to fix flashing of text inputs.
- Fifth commit improves behavior for setting inputs in default user settings panel.
<details> …
=> Improvements in information density settings.

web/src/bootstrap_typeahead.ts
This keeps the first item focused when user uses keyboard. User can still move the focused item using mouse and click to select it. Highlighting an item via mouse and then pressing enter would select the highlighted item.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20unexpected.20selection.20from.20search.20typeahead
=> typeahead: Ignore mouse position once user uses keyboard.

web/src/search_suggestion.ts
Previously, if you typed "channel: rome" you'd see a result for both channel "rome" and a second one for "Rome". This commit deduplicates that by comparing for duplicates without case sensitivity.
Note that if you fully type "channel: rome" you'll see the result with a lowercase R instead of uppercase. It would be a bit involved to change this, so I'm leaving that as something to address in the future.
=> search: Avoid duplicate search results from case sensitivity.

web/styles/rendered_markdown.css
When rendering a spoiler block that includes a datetime format, the dropdown button was pushed out of view on smaller devices. This happened because the time tag was overflowing past the spoiler blocks width.
This commit intends to fix this problem by adding a `white-space` attribute to the rendered time tags which will stop it from overflowing.
Fixes: #30641.
After fix screenshot
<details>
</details>
=> ui: Fix overflowing time tag in spoiler block.

web/styles/search.css
The pill-container background color has been displaying erroneously on the search input in dark mode. This PR explicitly calls up the search background color; while those match in light mode, they do not in dark mode.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20search.20typeahead.20color/near/1893907)
| Before | After (no change in light mode) |
| --- | --- |
| ![search-background-dark-before](https://github.com/user-attachments/assets/cc1e247f-72b9-458e-8e48-1a38e196ff7e) | ![search-background-dark-after](https://github.com/user-attachments/assets/ebffe374-3226-47f0-855e-9dc5d39a2522) |
| ![search-background-light-before](https://github.com/user-attachments/assets/965cfceb-62cc-4a91-be44-f4a0e35ad089) | …
=> navbar_search: Explicitly specify search input background color.

web/styles/message_view_header.css
This PR introduces a minor refactor of how the help widget is displayed and aligned; it causes no changes to Firefox, but works around a paint bug present in Chrome where the icon remains visible when there is an ellipsis on the description.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20space.20between.20channel.20description.20and.20search/near/1893064)
| Chrome, before | Chrome, after |
| --- | --- |
| ![chrome-help-widget-before](https://github.com/user-attachments/assets/d22f1f08-9259-48ce-8d07-cf95ecae7820) | ![chrome-help-widget-after](https://github.com/user-attachments/assets/1825bcab-2373-4737-a8d8-6651e3f6da86) |
| --- | --- |
| …
=> navbar_description: Refactor help-widget icon display.

web/src/left_sidebar_navigation_area_popovers.ts
The bug was introduced in 22a58c739c7d1c30845dc40ebb646ccebd35f089
https://github.com/user-attachments/assets/4acba720-e65b-44cb-8bac-6d029bb158e2
https://github.com/user-attachments/assets/1b069d10-f50d-464a-b45e-9d60d44dd9af
<details>
- x ] Each commit is a coherent idea.
</details>
=> Fix property name starred_message_counts.

zerver/lib/exceptions.py, zerver/tests/test_realm.py, zerver/tests/test_settings.py, zerver/views/user_settings.py
This would help us in avoiding adding translation everytime we use this error for a new pair of parameters.
<details>
</details>
=> exceptions: Add new error class to be used for invalid parameter values.

web/src/stream_ui_updates.js
This bug was introduced in 08f35e08a4cdf5.
<details>
</details>
=> stream_ui_updates: Pass missing parameter.

web/styles/app_variables.css, web/styles/left_sidebar.css, web/styles/zulip.css
This PR attempts to make the left sidebar more responsive to font size and available screen size, whose `max-width` is now calculated to scale with the font size as well:
* The left sidebar takes up 33.3333% of the screen
* The left sidebar will be no wider, however, than 20.5em minus the 12px of righthand margin on the left sidebar
* When the left sidebar is hidden at narrower viewports, it opens at its max-width size
* The max width of the UI (the left sidebar, the message column, and the right sidebar) is now calculated and appropriately scales with the font size
| 16/140, before | 16/140, after |
| --- | --- |
| ![16px-before](https://github.com/user-attachments/assets/10baa1b4-9044-4a5c-95a7-4ccbe6eee0c2) | …
=> left_sidebar: Present a wider left sidebar and scaling UI layout.

help/custom-profile-fields.md
- Describe user cards in intro.
- Remove outdated list of info in user profiles (not needed here).
- Document required profile fields.
Current: https://zulip.com/help/custom-profile-fields
=> help: Improve custom profile fields article.

web/src/info_overlay.ts, web/src/search_suggestion.ts, web/src/ui_init.js, web/templates/message_feed_errors.hbs, web/templates/search_operators.hbs
We use different text for guest users, specifying that they can only search in channels they can view.
The issue description suggests the same for spectators, but we already use different text for them.
The issue also specifies changing the "searching all public channels" link to use channels rather than streams in the URL.
But that is better done separately.
Fixes: #30902 
<details>
- As guest:
- Otherwise:
- As guest:
- Otherwise:
</details>
<details> …
=> search: Improve text about searching public channels.

zerver/lib/typed_endpoint_validators.py, zerver/lib/validator.py, zerver/tests/test_invite.py, zerver/tests/test_typed_endpoint_validators.py, zerver/views/email_mirror.py, zerver/views/invite.py, zerver/views/registration.py
Convert a few files from /zerver to typed_endpoint.
Removed unnecessary validators from `validators.py`.
=> Zerver-typed-endpoint-migrate

zerver/lib/import_realm.py
The emoji dir is present in the data from our export tool. This was added in 468afe4840fbac0ca93643d1c8fc11c31a687528.
This comment hasn't been updated since
c4b886d8aee2503a03cfbffd30676ee0d4aba933, so probably we just forgot to refresh it when custom emoji export was added.
=> import_realm: Update incorrect comment about emoji dir in exported data.

docs/production/system-configuration.md, puppet/zulip/manifests/app_frontend_base.pp, puppet/zulip/templates/supervisor/zulip.conf.template.erb, scripts/lib/check_rabbitmq_queue.py, scripts/nagios/check-rabbitmq-consumers
There's no need for sharding, but this allows one to spend a bit of extra memory to reduce image-processing latency when bursts of images are uploaded at once.
=> thumbnail: Add support for multiple queue workers.

web/src/message_view.js, web/tests/narrow_activate.test.js
After navigating to a `near` narrow, user is likely to press back to go back to previous selected message. To support this, we have to select `then_select_id` without rerender, if we can.
Tested by using breakpoints with `near` links to check if the correct code is being executed.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/slow.20following.20links.20within.20conversation/near/1852358
=> message_view: Select message without rerender if possible.

web/styles/search.css
Fixed by including the margin and padding in the
`width: 100%` calculation.
| --- | --- |
| <img width="756" alt="Screenshot 2024-07-22 at 9 48 37 AM" src="https://github.com/user-attachments/assets/e0f9e08a-a076-4610-ab19-3247b1d52fc7"> | <img width="756" alt="Screenshot 2024-07-22 at 9 46 47 AM" src="https://github.com/user-attachments/assets/aa228b02-3d6d-4eca-abd9-35d8a25d2856"> |
=> search: Fix outline of clear search button.

web/src/message_view.js
If user is no longer in the current message list, then the messages fetched for it are relevant to the current narrow and can be safely ignored.
=> message_view: Ignore fetched messages if user changed view.

zerver/lib/events.py, zerver/models/realms.py, zerver/tests/test_event_system.py, zerver/tests/test_home.py
https://github.com/zulip/zulip/pull/28720#discussion_r1486601441
In `fetch_initial_state_data` we were doing one database query per announcement stream.
This PR updates the logic to prefetch those streams using `select_related` hence avoiding the extra db queries.
Fixes: #28909.
Note: We can't use the first option suggested in #28909 because we need to check if `stream.deactivated`
> Just avoiding fetching the object if all we need for the API is the ID, i.e. .stream_id rather than .stream.id somewhere.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-disciplin …
=> fetch_initial_state: Avoid doing one db query per announcement stream.

help/allow-image-link-previews.md, help/include/sidebar_index.md, help/manage-your-uploaded-files.md, help/share-and-upload-files.md, help/view-images-and-videos.md
- Make page title more general.
- Document new option for animated image previews.
- Split instructions for showing different preview types.
- Update intro.
Current: https://zulip.com/help/allow-image-link-previews
<details>
<summary>
Updated
</summary>
</details>
Follow-ups:
- Change page URL to match the new title.
- Make the animate setting apply to GIPHY images. If this will be delayed a while, we can add a note to the documentation instead.
=> help: Improve previews documentation.

api_docs/changelog.md, api_docs/message-formatting.md, version.py, zerver/lib/markdown/__init__.py, zerver/lib/thumbnail.py, zerver/tests/test_markdown_thumbnail.py, zerver/worker/thumbnail.py
This allows clients to potentially lay out the thumbnails more intelligently, or to provide a better "progressive-load" experience when enlarging the thumbnail.
<details>
</details>
=> thumbnail: Add a data-original-dimensions attribute

web/src/inbox_ui.ts, web/src/modals.ts, web/src/recent_view_ui.ts, web/src/user_deactivation_ui.ts, web/src/views_util.ts
Earlier the focus was not being set to the modal when it was opened.
This was because `is_in_focus` checks if  `modals.any_active` which
checks `$(".micromodal").hasClass("modal--open")`.
But when `is_in_focus` is called
`$(".micromodal").hasClass("modal--opening")`.
This commit fixes the issue by creating a function
`is_active_or_animating` which checks if the modal has the class
`modal--open` or `modal--opening`.
[CZO Link](https://chat.zulip.org/#narrow/stream/6-frontend/topic/.F0.9F.8E.AF.20focus.20on.20dialog.20widget).
Also set `focus_submit_on_open` to true in the deactivate users modal.
=> Inbox and recent view multiple modal issue.

web/src/settings_components.ts
It's unlikely that the saved button didn't appear. So, we were too late in calling the waitForSelector method, so having a delay would help in that case.
discussion: https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/main.20failing/near/1892339
This is an attempt to fix this CI failure:
```
TimeoutError: Waiting for selector `#org-notifications .save-button[data-status="saved"]` failed: Waiting failed: 30000ms exceeded
at new WaitTask (/__w/zulip/zulip/node_modules/.pnpm/puppeteer-core@22.12.0/node_modules/puppeteer-core/src/common/WaitTask.ts:82:28)
at IsolatedWorld.waitForFunction (/__w/zulip/zulip/node_modules/.pnpm/puppeteer-core@22.12.0/node_modules/puppeteer-core/src/api/Realm.ts:74:22)
at Function.waitFor (/__w/zulip/zulip/node_modules/.pnpm/puppeteer-core@22.12.0/node …
```
=> settings_components: Keep saved button displayed a little longer.

tools/lib/capitalization.py, zerver/lib/email_mirror.py, zerver/tests/test_email_mirror.py
If the email subject is something like `Fwd:`, it gets stripped to an empty string, activating the "(no topic)" override. This however leads to faillure if the organization enables the setting forcing every message to have a topic. Such emails should still go through, so we should just change the topic value used.
=> email_mirror: Change default topic name if subject ends up empty.

web/src/stream_list.ts
The previous logic did not properly account for the fact that in muted channels, unmuted/followed topics are sorted above normal topics.
Rather than trying to reproduce that logic, we just call the function for computing the topics in the left sidebar, and pull off the top topic.
=> stream_list: Fix clicks on muted channels.

web/styles/message_row.css
This PR modestly improves i18n on edited/moved notices (both in Compact mode and at 16/140) while alternative solutions, including icons, are discussed on CZO.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20.22Edited.22.20marker.20internationalization/near/1899489)
| --- | --- |
| ![edited-before](https://github.com/user-attachments/assets/632dff81-5538-49e8-bd00-17954e898e07) | ![edited-after](https://github.com/user-attachments/assets/bd6e4bb0-60f7-400f-af13-b07ce5060094) |
| ![edited-compact-before](https://github.com/user-attachments/assets/d64d1317-3980-4c57-94e6-c635f17549f2) | ![edited-compact-after](https://github.com/user-attachments/assets/613d1d04-4e7b-4dbd-b942-2fbc363597da) | …
=> message_row: Add ellipsis to edited notices below avatar.

help/configure-home-view.md, help/configure-unread-message-counters.md, help/enable-full-width-display.md, help/include/configure-channel-links.md, help/manage-inactive-channels.md, help/marking-messages-as-read.md, help/mastering-the-compose-box.md, help/star-a-message.md, help/status-and-availability.md, help/typing-notifications.md
This is a followup commit to #30824.
Fixes https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20help.20not.20updated.20for.20new.20preferences.20sections/near/1899330.
git grep in the help directory will still show up results for `Advanced` but those are mostly used in either plain english language instructions or refer to some other part of the app. At the point of writing this commit, there were 6 results for `Advanced`, 4 of which were plain english, 1 refers to the Advanced settings in chrome for desktop notifications, and another one refers to `Advanced configurations` for channel settings.
I've added one screenshot just for reference, but don't think we need screenshots for all changes.
<details> …
=> docs: Replace `Advanced` with relevant section for user Preferences.

web/templates/invite_user_modal.hbs
This PR removes the "organization" qualifier in front of administrator and owner roles in the invite modal.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/role.20names.20in.20invite.20modal/near/1900317)
<details>
</details>
=> invite_modal: Simplify Administrator, Owner role labels.

web/src/tippyjs.ts, web/src/user_card_popover.js, web/templates/popovers/user_card/user_card_popover.hbs, web/templates/popovers/user_card/user_card_popover_custom_fields.hbs
When the user card is opened via the keyboard shortcut `U`, the initial focus should be on the first popover menu option, rather than the copy buttons or the custom profile field links which can be distracting due to the presence of tooltips on them.
This also adds the `LONG_HOVER_DELAY` delay to the user card tooltips to further reduce the distraction from the tooltips.
Fixes part of #31027.
| ![user_card_fix_focus_and_tooltip-before](https://github.com/user-attachments/assets/d7eac826-41c3-43c1-b3f7-8ef16c01d750) | ![user_card_fix_focus_and_tooltip-after](https://github.com/user-attachments/assets/e8b4060e-3e8b-4533-b839-627379dd2cb3) | 
<details> …
=> user_card_popover: Focus on menu options first when opened with keyboard.

web/styles/app_variables.css, web/styles/search.css
This PR fixes some subtle but unmistakably annoying shifts in the height of the search bar. It does this by 1) correcting the variable referencing the height of the pill-container search box, and 2) overriding padding inherited from the pill container class, which becomes unnecessary when the search box has a correct height set. Adjustments are present for the height on short screens, too.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20inconsistent.20search.20box.20height/near/1900406)
| --- | --- |
| ![search-box-before](https://github.com/user-attachments/assets/a418304f-51ce-4d1c-aa1f-f61f2ad579f6) | ![search-box-after](https://github.com/user-attachments/assets/588a810d-5a48-4a69-bdbf-252e5f23 …
=> search_box: Correct search box height.

web/styles/app_variables.css, web/styles/popovers.css
This PR updates the Zulip color palette by using the oklch color space in color-mix() functions and replacing var() color arguments with static hsl() values for better compatibility and browser support. Additionally, it improves the contrast of text items in the user card popover, enhancing readability and accessibility of user-related information.
Fixes: Part of #31027.
| ![Screenshot 2024-07-24 at 3 03 53 AM](https://github.com/user-attachments/assets/4a814f7a-1371-48f3-be1e-23632d3b42e4) | ![Screenshot 2024-07-24 at 3 03 05 AM](https://github.com/user-attachments/assets/b67eb7c6-285d-4af4-bb9e-f1c1b4f1ae39) |
| ![Screenshot 2024-07-24 at 3 03 48 AM](https://github.com/user-attachments/assets/e074c525-e83a-48e6-9 …
=> user_card_popover: Use `oklch` color space in `color-mix`, use static color values for PostCSS compilation and improve text items contrast.

web/src/user_card_popover.js
As a follow-up to the previous commit f124ef931, which deals with the keyboard focus when opened via the keyboard shortcut `U`, this commit ensures that when the user card is opened via the mouse, and the first navigational key is pressed, the focus is on the first menu option instead of the other tabbable elements which can be distracting.
Fixes: https://github.com/zulip/zulip/pull/31047#issuecomment-2245742391 and [CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20keyboard.20focus.20when.20opening.20user.20card/near/1900196)
<details> …
=> user_card_popover: Focus on menu options first when key is pressed on a user card opened via mouse.

web/src/popover_menus.ts
When the user card is displayed via right sidebar, the reference can be lost due to it being updated or hidden on window resize.
To fix it, we show user card as an overlay when we cannot find the reference.
Another solution would have been to relocate the reference and update it for the popover but that is not naturally supported by tippy once the popover has been displayed.
=> popover_menus: Fix user card moves to top left of screen.

web/src/thumbnail.ts
While this has no real effect in the message feed itself, it makes the transition in the lightbox a lot nicer.
=> thumbnail: Prefer 840x560 thumbnails for web app.

zerver/tests/test_markdown.py
These were omitted from b42863be4b2ccf7ca697e2bdea4fc5fdf2b5c26d.
Fixes: 
<details>
</details>
=> tests: Remove THUMBNAIL_IMAGES overrides, since the setting was dropped.

web/src/bundles/common.ts
I'm not aware of us using any of these; we don't generate the class names involved, and we're not using `uppy.use` on any of their UI components.
I confirmed that the only use of an Uppy UI component was the progress bar, which was stopped using in
b01ac3623fa2a6e98a917b0664568ff8b4e8aaba.
=> upload: Stop importing unused Uppy styles.

web/src/message_events.js
When moving message while compose box has content, stream was not updated to the new stream if it was changed.
Tested by moving message with stream changed and with / without topic changed.
https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20redirect.20on.20move.20only.20half-updates.20compose.20box
=> message_events: Fix compose stream not updated when moving messages.

web/styles/app_components.css, web/styles/dark_theme.css, web/styles/recent_view.css, web/templates/login_to_view_image_button.hbs, web/templates/recent_view_row.hbs
- First two commits removes the use of `*` selector and uses class names instead of them.
- Last two commits removes the unnecessary CSS.
Fixes:  Part of https://chat.zulip.org/#narrow/stream/6-frontend/topic/CSS.20selector.20performance
<details>
</details>
=> css: Remove `*` selectors being used for CSS.

help/keyboard-shortcuts.md
Before: https://zulip.com/help/keyboard-shortcuts#the-basics
After:
=> help: Document new way to remove pasted formatting.

web/src/inbox_ui.ts, web/src/message_list_view.js, web/src/tippyjs.ts, web/styles/zulip.css, web/templates/change_visibility_policy_button_tooltip.hbs, web/templates/inbox_view/inbox_row.hbs, web/templates/recent_view_row.hbs, web/templates/recipient_row.hbs, web/templates/topic_list_item.hbs
Earlier tooltips for topic menu button had inconsistent context with that of other tooltips. In topic menu tooltip, action was described in first line which different from that of other tooltips.
This PR changes the tooltip context and rearranges them to match the format of action on first line and more context on second line.
Fixes: [czo](https://chat.zulip.org/#narrow/stream/101-design/topic/follow.20topic.20menu.20tooltips)
<details> …
=> Change inconsistent tooltip for topic menu option.

web/src/message_util.ts, web/src/recent_view_ui.ts
Tested by deleting a DM and navigating to recent view. No error is thrown and dm row is correctly placed.
Fixes [this](https://chat.zulip.org/#narrow/stream/464-kandra-js-errors/topic/Error.3A.20Assertion.20failed/near/1898878) sentry exception.
=> recent_view_ui: Fix dm rows not updated for deleted messages.

help/allow-image-link-previews.md
Current: https://chat.zulip.org/help/allow-image-link-previews
Updated:
=> help: Add caveat about previews of old image uploads always animating.

zerver/lib/thumbnail.py, zerver/tests/test_thumbnail.py, zerver/views/development/camo.py, zerver/views/thumbnail.py
Providing a signed Camo URL for arbitrary URLs opened the server up to being an open redirector.  Return a client redirect if the URL is not a user upload, and the backend image if it is.  Since we do not have ImageAttachment rows for uploads at a time we wrote `/thumbnail?` URLs, return the full-size content.
=> thumbnail: Do not Camo old thumbor URLs; serve images directly.

tools/setup/emoji/custom_emoji_names.py, tools/setup/emoji/emoji_names.py
The more neutral folded_hands is the official name and should make folks more confortable with using this for thank_you, which is certainly a more common use in work contexts than pray.
=> emoji: Fix canonical name for folded_hands emoji.

web/src/message_events.js, web/src/message_view.js
Here we want to rerender the current narrow after receiving an event which moves messages. We have mechanisms to keep using the cached list if we are narrowing to the same narrow which we want to avoid in this case.
=> message_view: Fix current narrow doesn't rerender when asked to.

tools/release
[Discussion](https://chat.zulip.org/#narrow/stream/438-release-management/topic/release.20checklist/near/1902682).
=> release: Parse version.py using the language it was written in

zerver/lib/zulip_update_announcements.py
This uses invalid syntax for a cloud vs. self-hosted conditional.
[CZO discussion](https://chat.zulip.org/#narrow/stream/438-release-management/topic/zulip_updates.20items.20of.20note/near/1901817)
=> updates: Add update message (level=8).

templates/corporate/history.md
Current: https:/zulip.com/history/#major-server-releases-and-product-announcements
Updated:
=> portico: Add Zulip Server 9.0 relese to /history.

puppet/kandra/files/nagios4/conf.d/services.cfg
It is often flaky for reasons we cannot affect, and this is no longer an important part of the Zulip Cloud service.
Fixes: 
<details>
</details>
=> nagios: Make zephyr mirroring not page.

web/templates/message_reactions.hbs
Using the existing tooltip template for the other "add emoji reaction" element in message_controls results in the keyboard shortcut being shown and avoids doing work to translate the string for every single message containing emoji reactions.
=> message_reactions: Use the reactions tooltip template.

web/src/click_handlers.js
Scroll to bottom button is visible for a few ms when switching narrow to Inbox / Recent view while scrolling in message feed. While we can end the transition faster to completely avoid the issue for now but this seems like a more permanent and simpler fix than to fiddle with CSS.
=> scroll-to-bottom: Fix misclicks to scroll to bottom button.

web/styles/rendered_markdown.css
This removes a malformed selector that referenced an incorrect color, even when correctly formed:
The color in question is already better declared as `--color-text-self-direct-mention` further down in the rendered markdown CSS file.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/CSS.20selector.20performance/near/1904125)
=> rendered_markdown: Remove incorrect selector with unused color.

web/styles/subscriptions.css
These selectors drill all the way down to `inline_decorated_stream_name.hbs`, which no longer contains any Font Awesome references.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/CSS.20selector.20performance/near/1904125)
=> streams_settings: Removed unused FontAwesome references.

web/src/bootstrap_typeahead.ts
When the caret in textarea is around the right end of the screen, typeahead can overflow the window. To fix it, we use tippy's mechanism to keep the tooltip inside the visible boundary.
https://github.com/user-attachments/assets/1d8bcea9-278a-40d9-8358-4689f0c36e82
=> typeahead: Fix typeahead overflowing out of window.

web/src/stream_list.ts
This check been present since
466beef6fedbd800933fecb59f1b492865035b84, but it seems unnecessary in that the main logic handles there being 0 channels just fine, that's a rare case (so not a useful optimization), and importantly, not calling stream_list_sort.sort_groups for that transition resulted in `stream_list_sort` having stale data structures, resulting in exceptions if one tried to open the CHANNELS filter widget in the newly-no-channels state.
=> stream_list: Fix handling of unsubscribing from last channel.

web/templates/edit_content_button.hbs
This adds a missing `message-controls-icon` class to the edit buttons, which caused the misalignment of edit and related icons. This was overlooked in #31157.
| --- | --- |
| ![Screen Shot 2024-07-30 at 14 57 39](https://github.com/user-attachments/assets/e6a19b73-5ee1-4803-b08f-fdea8d16e888) | ![Screen Shot 2024-07-30 at 14 57 15](https://github.com/user-attachments/assets/858d3f97-7ce8-4144-b198-c63c230255dc) |
<details> …
=> message_controls: Add missing class to edit buttons.

web/src/compose.js, web/src/message_edit.js, web/styles/app_variables.css, web/styles/compose.css, web/styles/message_row.css, web/styles/rendered_markdown.css, web/tests/compose.test.js
This PR does three things:
1) It eliminates expensive, anonymous `:first-child` and `:last-child` selectors from the rendered Markdown CSS.
2) It reads the `height` value of both the compose and message-edit textareas to set a `height` value on the preview area, eliminating a small but annoying jog in the size of the compose box and preview areas. The jog became larger and more annoying with the fixes from 1) in place, which is why these two aspects appear inside the same PR.
3) It removes show/hide logic from the compose textarea, which is needless because the textarea will automatically be obscured by the preview area in preview mode. That keeps the textarea an active part of the DOM, ensuring that the compose box's resize buttons and logic work as expected even in preview mode.
[CZO …
=> message_previews: Simplify presentation of message previews.

zerver/lib/users.py, zerver/tests/test_users.py
Fixes #31188, removing a lot of useless high-entropy data from the /register response.
=> users: Reduce date_joined precision to minutes

web/src/compose_call_ui.ts, web/src/info_overlay.ts, web/src/lightbox.ts, web/src/navbar_alerts.ts, web/src/portico/landing-page.ts, web/src/settings_profile_fields.ts
There is no need to add a separate function signature to a function variable; just add types directly to the function itself.
Cc @afeefuddin, who introduced all of these.
=> web: Condense unnecessarily verbose function signatures

docs/overview/release-lifecycle.md
I made a new view for us to link to from this documentation, designed for users, rather than for contributors: https://github.com/orgs/zulip/projects/9/views/13
Current doc: https://zulip.readthedocs.io/en/latest/overview/release-lifecycle.html#server-roadmap
Updated:
=> docs: Tweak server roadmap documentation.

zerver/lib/events.py, zerver/lib/home.py, zerver/lib/typed_endpoint_validators.py, zerver/lib/validator.py, zerver/tests/test_event_queue.py, zerver/tests/test_openapi.py, zerver/tests/test_settings.py, zerver/tornado/views.py, zerver/views/events_register.py, zerver/views/user_settings.py, zerver/views/video_calls.py, zilencer/views.py
Migrate `tornado/views.py`, `user_settings.py`,
`events_register.py` and `zilencer/views.py` to typed_endpoint.
Remove unused validators and unused openapi tests.
=> endpoints: Migrate to typed_endpoint.

web/tests/example1.test.js, web/tests/example2.test.js, web/tests/example3.test.js, web/tests/example7.test.js, web/tests/lib/test_stream.js
The PR introduces a new function make_stream to make test streams in node tests with accurate types instead of dummy objects.
I've currently modified `example${i}.test.js` files only.
I've used dummy data in `make_stream` function.
<details>
</details>
=> test_stream: Setup make_stream function to create streams in node tests.

zerver/actions/alert_words.py, zerver/actions/scheduled_messages.py, zerver/actions/user_status.py, zerver/lib/alert_words.py, zerver/tests/test_events.py, zerver/tests/test_user_status.py
Migrates 4 action functions to use `send_event_on_commit`.
<details>
</details>
=> Migrate action functions to send event on commit.

web/styles/app_components.css
Added right padding to the actions heading in the table.
Fixes #29633.
<table>
<tr>
<th></th><th>Before</th><th>After 2em</th><th>After 1em</th><th>After 1em with data</th>
</tr>
<tr>
<td>Users</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Bots</td>
<td>
</td><td>
</td><td>
</td><td>
</td>
</tr>
<tr>
<td>Default Channels</td>
<td>
</td><td>
</td><td>
</td><td>
</td>
</tr>
<tr>
<td>
Custom Emoji
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<tr>
</table>
=> ListWidget: Fix sliding of actions column in tables.

web/src/lightbox.ts
Setting any value for a boolean attribute (like "controls") enables it.
=> lightbox: Disable controls on video previews in lightbox.

puppet/zulip/templates/nginx.conf.template.erb
The default compression level is 1; increasing this to 3 takes a small amount more CPU time (single-digit ms on multi-MB transfers), but results in a small but noticeable (4-7%) percentage better compression in JSON content.
Assuming a 25 megabit connection (the current average data rate for cell phones in the U.S.), a 2MB file which is shrunk an additional 4% saves approximately 25 milliseconds of transfer time; thus the additional few milliseconds of CPU-time is well worth the cost.  For faster connections (e.g. 100 megabit), the tradeoff is more or less a wash.
=> nginx: Adjust default gzip level.

zerver/tests/test_openapi.py, zerver/views/user_groups.py
migrate the following endpoints from `@has_request_variables` to `@typed_endpoint`:
- `get_user_group()`
- `delete_user_group()`
- `update_user_group_backend()`
- `update_subgroups_of_user_group()`
- `get_is_user_group_member()`
- `get_user_group_members()`
- `get_subgroups_of_user_group()`
=> user_groups: Migrate to @typed_endpoint.

web/styles/app_variables.css, web/styles/compose.css, web/styles/dark_theme.css
This keeps colors uniform between edit and preview modes, and also ensures no bleedthrough of the editor when in preview mode. In using `color-mix`, it maintains the colors as-is, but removes an alpha channel in preview mode that is at the heart of a serious dark-mode regression introduced in #31177.
ID selectors have been used for those colors to both keep the text color declaration in the same place, and to avoid a dark-theme specificity problem where the generic textarea took precedence over the colors specified on the compose box's own textarea.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/message.20preview.20overlapping.20with.20original.20message/near/1908596)
| Preview mode, before | Preview mode, after (no change in …
=> compose: Specify non-alpha message-area colors.

zerver/actions/message_send.py, zerver/lib/markdown/__init__.py, zerver/lib/thumbnail.py, zerver/tests/test_markdown_thumbnail.py, zerver/worker/thumbnail.py
Messages are rendered outside of a transaction, for performance reasons, and then sent inside of one.  This opens thumbnailing up to a race where the thumbnails have not yet been written when the message is rendered, but the message has not been sent when thumbnailing completes, causing `rewrite_thumbnailed_images` to be a no-op and the message being left with a spinner which never resolves.
Explicitly lock and use he ImageAttachment data inside the message-sending transaction, to rewrite the message content with the latest information about the existing thumbnails.
Despite the thumbnailing worker taking a lock on Message rows to update them, this does not lead to deadlocks -- the INSERT of the Message rows happens in a transaction, ensuring that either the message rending blocks the …
=> thumbnail: Resolve a race condition when rendering messages.

docs/subsystems/input-pills.md, web/src/add_subscribers_pill.ts, web/src/compose_pm_pill.ts, web/src/email_pill.ts, web/src/input_pill.ts, web/src/invite.ts, web/src/invite_stream_picker_pill.ts, web/src/search.ts, web/src/search_pill.ts, web/src/search_suggestion.ts, web/src/stream_pill.ts, web/src/typeahead_helper.ts, web/src/user_group_pill.ts, web/src/user_pill.ts, web/templates/search_user_pill.hbs, web/tests/compose_pm_pill.test.js, web/tests/composebox_typeahead.test.js, web/tests/input_pill.test.js, web/tests/pill_typeahead.test.js, web/tests/search.test.js, web/tests/search_suggestion.test.js, web/tests/stream_pill.test.js, web/tests/user_group_pill.test.js, web/tests/user_pill.test.js
This PR should have no visual changes to users, it's purely a refactor.
This change had two main motivators:
(1) We were putting a bunch of custom logic in `input_pill`, especially for display. This PR moves that to the relevant modules.
(2) `display_value` was being used for both the pill identifying "value" and for parsing the value a pill represented. This led to some hacks in the search pill code where we adjusted `display_value` just before displaying it. This PR removes `display_value` altogether and replaces it with relevant identifying information for each pill. Display values are calculated when we need them based on that identifying information. Maybe we want to tweak this to only generate `display_value` once, but I think the current state of the PR is fine since we don't …
=> input pill: Refactor to move custom attributes into relevant modules

web/src/inbox_ui.ts
Have one inbox row and focus on it. Mark the message as read in another tab. Press `r` in the first tab will return an error as the row_focus didn't change but there is no present. So, we fix it by updating the row_focus if it can get out of bounds when updating inbox view.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/error.20in.20dev
=> inbox_ui: Fix row_focus not synced with inbox rows.

zerver/tests/test_auth_backends.py, zerver/views/realm.py
https://chat.zulip.org/#narrow/stream/31-production-help/topic/can't.20enable.20SAML.20login/near/1912753
This bug was introduced in da9e4e6e54ddbd06e2c16db17eb7cb0678b5a786.
`validate_plan_for_authentication_methods` is already called inside
`validate_authentication_methods_dict_from_api`, conditionally on
`settings.BILLING_ENABLED`. This additional, redundant call runs
regardless of `BILLING_ENABLED`, and thus prevents a self-hosted server
from enabling certain backends in the organization settings UI.
The impact of this is limited - in order to encounter this bug, a
self-hosted server would have to first disable the backend in the UI, as
self-hosted realms are created with all backend flags enabled. A backend
doesn't show up in the org settings UI until it is first enabled in …
=> auth: Fix re-enabling of SAML/AzureAD in organization settings UI. 

web/src/lightbox.ts
Not sure why this `open_image` call was required. Likely we forgot to remove it in [this](https://github.com/zulip/zulip/pull/21227/files#diff-dc0c835aa47c6028f2a63c07f0f93129eb39d035c02089a636dacf07b50f15d7R511) migration
=> lightbox: Remove unnecessary open_image call.

web/styles/typeahead.css
Fixes https://chat.zulip.org/#narrow/stream/101-design/topic/font.20weight.20in.20typeaheads/near/1911442.
I've included a few screenshots to demonstrate the change, let me know if you need more screenshots.
| Before - compose box | After - compose box |
| -- | -- |
| <img width="471" alt="typeahead_font_weight_compose_before" src="https://github.com/user-attachments/assets/04dc7d67-fe3e-4542-8382-17b39501f2eb">   | <img width="471" alt="typeahead_font_weight_compose_after" src="https://github.com/user-attachments/assets/8a08876f-fd2e-4938-90c5-20ef20f17e1e"> |
| Before - user group | After - user group |
| <img width="592" alt="typeahead_font_weight_user_group_before" src="https://github.com/user-attachments/assets/7eaf8741-b900-47d5-9cff-8b8cb2fb456d" …
=> typeahead: typeahead-strong-section should have a font weight of 500.

web/styles/popovers.css, web/templates/popovers/user_group_info_popover.hbs
Previously no message was being shown in the group popover, when group had no members, this commit intends to fix this by displaying an approriate message when group is empty. 
Fixes #30830.
Fixes: 
DARK
LIGHT
<details>
</details>
=> user_group_popovers: Add display message when group is empty.

web/src/compose_actions.ts, web/src/compose_ui.ts, web/tests/compose_actions.test.js
We are using `.val` to set compose box content which is very fast vs `setFieldText` which is very slow due to it doing a lot of forced repaints. The major downside of using `val` here is that user will not able to perform `undo` operation on this which doesn't seem something user would want to do here.
Note that this effects compose content restored from drafts, scheduled messages and on reload.
Tested by created a draft of 30k characters and trying to restore it through various ways possible.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20too-large.20drafts.20cause.20new.20replies.20to.20wedge
=> compose: Fix restoring big drafts freezes the app.

web/styles/app_variables.css, web/styles/right_sidebar.css, web/templates/right_sidebar.hbs
**This PR builds on commits that should be merged first in #31277**
Parallel to #31277, this refactors the right sidebar to make better use of CSS Grid to match @terpimost's right sidebar redesign, https://terpimost.github.io/zulip-sidebar/
Fixes #27574.
| Before (showing #31277) | After |
| --- | --- |
| ![right-sidebar-before](https://github.com/user-attachments/assets/59e2bf90-186b-41e9-be5a-331df3543cc2) | ![right-sidebar-after](https://github.com/user-attachments/assets/f1fb61c4-331a-43a2-a98d-6b987af0ab0e) |
In bringing the right sidebar into better concord with the left sidebar, this PR includes the following improvements:
* The USERS heading is now perfectly vertically aligned with the VIEWS heading in the left sidebar
* The user filter box matches the style and font-size of the …
=> right_sidebar: Adjust padding, gridded row values.

web/src/message_live_update.ts, web/src/people.ts, web/tests/composebox_typeahead.test.js, web/tests/people.test.js, web/tests/search.test.js, web/tests/search_suggestion.test.js, web/tests/user_pill.test.js
This parameter is unused for Zulip avatars, and results in a smaller (pixel-wise) Gravatar than we use for Zulip "small" avatars.  Omitting the `s=50` parameter results in a 80x80 image, which is closer to the 100x100 image that Zulip thumbnails avatars to.  Ironically, using the default (larger) Gravatar dimensions also results in _smaller_ responses (in bytes) from Gravatar.
<details>
</details>
=> avatar: Stop adding &s=50 to Gravatar and Zulip avatar requests.

web/src/bootstrap_typeahead.ts, web/styles/app_variables.css, web/styles/typeahead.css
Fixes: https://chat.zulip.org/#narrow/stream/101-design/topic/UI.20redesign.3A.20new.20topic.20indicator.20in.20typeaheads/near/1908770
The first commit is a refactor.
Second commit fixes the issue at hand, these are the screenshots after the second commit (does not include changes from the third commit):
For the third commit, there was a css rule to apply a right margin of 14px to a direct descendant of `.typeahead-option-label-container` that was a `<strong>` element. I suspect at one point, another layer of element was added b/w the container and the `<strong>` element and the style ended up getting ignored. I've not spent time digging through when this change might have happened since this is a small visual change and it would be more efficient to …
=> UI redesign: new topic indicator in typeaheads

web/src/hotkey.js
What was happening:
* Focus being in the search input text box made Up/Down be handled by the browser and move the cursor. This is default browser behavior, and not useful to us (you can use home/end for the same goal, but also one just doesn't put much text in that input given the pills system).
* We probably don't want to push keyboard focus out of the search box after completing a search, since that would make it annoying to type a new search term or whatnot.
The fix is to just make the existing Up/Down keyboard handler apply even if the search input is focused.
More context here:
https://chat.zulip.org/#narrow/stream/9-issues/topic/Can't.20navigate.20search.20results.20using.20the.20keyboard.20.2331291/near/1913535
=> search: Navigate results with up/down when input is focused.

templates/corporate/hello.html, web/src/portico/hello.ts, web/styles/app_components.css, web/styles/dark_theme.css, web/styles/portico/hello.css, web/styles/portico/markdown.css, web/styles/portico/portico.css, web/styles/rendered_markdown.css, web/styles/settings.css, web/styles/subscriptions.css, zerver/lib/markdown/tabbed_sections.py, zerver/tests/test_templates.py
Two instances of the div selector haven't been removed, which is at https://github.com/zulip/zulip/blob/69194489177bc3b43ff7002bd4de92ceda628f77/web/styles/portico/portico.css#L277 and https://github.com/zulip/zulip/blob/69194489177bc3b43ff7002bd4de92ceda628f77/templates/zerver/emails/email.css#L322. At both of these places, using the div selector feels like the right thing to do since it is applying generic rules to divs. For the second case of email, it's more clear cut, since it applies to all divs, for `.help .markdown`, it might be up for debate. 
There is one commit which changes a bit of behaviour, which has been approved in https://chat.zulip.org/#narrow/stream/6-frontend/topic/Subscription.20list.20slight.20look.20change/near/1906254
Fixes part of : …
=> CSS selector performance: Use classnames instead of div.

zerver/migrations/0564_purge_nagios_messages.py
We didn't correctly check for the possibility that these users don't exist.
Fixes: 
<details>
</details>
=> migrations: Fix Nagios bot cleanup crash.

web/src/user_topics_ui.ts, web/tests/user_topics_ui.test.js
[CZO Discussion
](https://chat.zulip.org/#narrow/stream/9-issues/topic/Mute.20keyboard.20shortcut.20most.20unresponsive.20in.209.2Ex.20.2331275/near/1917971)
Fixes the buggy behavior of `Shift + M` hotkey.
<details>
</details>
=> user_topics_ui: Fix `toggle_topic_visibility_policy` behavior.

help/start-a-call.md
**Updates**:
- Adds note about feature being available only to organization owners and administrators.
- Fixes the icon in the note about BigBlueButton to be the zulip icon that's currently used in the compose box.
[Current documentation](https://zulip.com/help/start-a-call#change-your-call-provider)
---
<details>
</details>
=> help: Fix details in "Change your call provider" section.

docs/production/management-commands.md, help/configure-authentication-methods.md, zerver/management/commands/change_auth_backends.py
A utility command to enable or disable certain authentication backends for a realm from the command line. Can be helpful e.g. if the administrator accidentally disables some auth methods in the UI leaving themselves with none remaining that they could actually use to log back into the organization.
Example usage:
```
(zulip-py3-venv) vagrant@c32c137f59a0:/srv/zulip$ ./manage.py change_auth_backends -r zulip --show
Current authentication backends for the realm:
Enabled backends:
Dev
Email
GitHub
GitLab
Google
Apple
SAML
OpenID Connect
(zulip-py3-venv) vagrant@c32c137f59a0:/srv/zulip$ ./manage.py change_auth_backends -r zulip --disable GitHub
Disabling GitHub backend for realm Zulip Dev
Updated authentication backends for the realm:
Enabled backends:
Dev
Email
GitLab
Google
Apple
SAML …
```
=> management: Add change_auth_backends command.

help/import-from-rocketchat.md, zerver/data_import/rocketchat.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/Migration.20from.20Rocket.2EChat.20issues.3A.20messages.20and.20uploads/near/1906256)
List of bugs discussed in #20108 
* Bug: https://github.com/zulip/zulip/issues/20108#issuecomment-960665584
Resolved: https://github.com/zulip/zulip/commit/1cc2764d4560a7678ecc8f089c9aaab7d2a9c16c
* Bug: https://github.com/zulip/zulip/issues/20108#issuecomment-961455420
Resolved: https://github.com/zulip/zulip/commit/51421f378b92ef6e3378ca982f00be3ce20cd7a2
* Bug: https://github.com/zulip/zulip/issues/20108#issuecomment-962091717
Resolved: https://github.com/zulip/zulip/commit/c308799133229e3e00dde46f4e014a84bd2da617
* Bug: https://github.com/zulip/zulip/issues/20108#issuecomment-962235336
Resolved: Second Commit
* Bug: …
=> data_import_rocketchat: Fix import rocketchat bugs.

web/src/search_pill.ts
In an earlier refactor, `removePill` was being called with the exit button element instead of the pill. This change fixes that bug by using similar code to what we previously did (and still do in input_pill for cases without on_pill_exit).
=> search: Fix bug preventing closing regular search pills.

corporate/lib/support.py, corporate/views/support.py, templates/corporate/support/realm_details.html, templates/corporate/support/remote_realm_details.html, templates/corporate/support/remote_server_support.html, templates/corporate/support/sponsorship_details.html
**Updates**:
- Fixes the remote support view to show discount header after the removal of `default_discount` on the `Customer` model.
- Updates the Zulip Cloud support view to show discount and 100% sponsored headers.
---
<details>
<summary>Remote support view for realm with discount</summary>
| --- | --- |
| ![Screenshot from 2024-08-14 18-59-58](https://github.com/user-attachments/assets/9066d707-38cf-4a35-93ca-67df9c589214) | ![Screenshot from 2024-08-14 18-58-36](https://github.com/user-attachments/assets/ba5eb92a-a16c-47d7-8747-2f3ee7f460b9)
</details>
<details>
<summary>Zulip Cloud support view for realm with discount</summary>
| --- | --- |
| ![Screenshot from 2024-08-14 …
=> support: Show sponsorship and discount headers.

web/src/message_view.js
This needs to be done to update narrow title for different `near` message targets or no `near` topic narrows.
Tested full behaviour described here - https://chat.zulip.org/#narrow/stream/9-issues/topic/Navigation.20within.20a.20topic.20fails.20to.20update.20near.3A.20search.20pills/near/1902599
=> message_view: Update narrow title after change in narrow filter.

web/src/drafts_overlay_ui.js, web/src/markdown.ts, web/src/user_card_popover.js, web/src/user_group_popover.ts, web/styles/rendered_markdown.css, web/tests/markdown.test.js, zerver/lib/markdown/__init__.py, zerver/tests/test_markdown.py
Fixes #31102.
TO CHECK: The default placement for the user group popover is right and it opens in the right everywhere except compose box preview. It's somehow running out of space and opening on top as its fallback placement. Not sure if we wanna look into this more or not.
For compose box preview, a `pointer` cursor will show up for `@all` and `@topic` when the default cursor for that area is `not-allowed` (cursor with a ban icon on it). This was to ensure consistency with all types of mention. LMK if this needs to change.
| User card - compose preview - self | User card - compose preview - other user | User Group - compose preview | 
| -- | -- | -- |
| <img width="399" alt="user_mention_self_compose_box" …
=> User card and user group card popover should work in all rendered messages

web/src/filter.ts, web/tests/filter.test.js
We decide what operators are valid when parsing a term by calling `operator_to_prefix`, but `operator_to_prefix` calls `canonicalize_operator`, so we need to call `canonicalize_operator` on the operand we return from `parse`, or else we might end up with an invalid operator in a parsed term.
Fixes this bug:
https://chat.zulip.org/#narrow/stream/9-issues/topic/valid.20search.20terms.20in.20uppercase.20followed.20by.20.3A.20throwing.20error
=> filter: Canonicalize operator before creating parsed term.

web/src/message_list.js, web/src/message_view.js, web/src/stream_data.ts, web/src/stream_list_sort.ts, web/src/topic_generator.ts, web/tests/message_list.test.js, web/tests/stream_data.test.js, web/tests/stream_list.test.js, web/tests/topic_generator.test.js
This PR should have no user-facing changes. These are the simpler commits from #31299
=> prep commits: use stream id instead of stream name

web/src/message_list_view.js, web/tests/message_list_view.test.js
The message feed can take long enough to render that users are locked out of clicking things for a second or so. This has become especially an issue since we updated the search bar logic to refresh the message feed as search terms are added to the search bar.
More details on CZO here:
https://chat.zulip.org/#narrow/stream/101-design/topic/search.20narrow.20live.20update
=> message_list: Reduce _RENDER_WINDOW_SIZE to 250.

web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/search.css
This PR resets some default iOS button styles, and in doing so ensures better consistency in search-box icon colors. Dark mode styles are also removed in favor of CSS variables.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/blue.2C.20misaligned.20search.20close.20X.20on.20iPad/near/1922058)
| iPad, before | iPad, after |
| --- | --- |
| ![ipad-search-before](https://github.com/user-attachments/assets/240e104d-d826-47eb-9e77-200473e73acc) | ![ipad-search-after](https://github.com/user-attachments/assets/f7d39118-ef8a-464b-9371-f692e1ebb244) |
| Desktop (Firefox), before | Desktop (Firefox), after (no change) |
| --- | --- |
| ![search-icons-firefox-before](https://github.com/user-attachments/assets/7d307e45-ace1-438d-a0ca-b2bad1ce …
=> search: Reset default iOS button styles.

web/e2e-tests/compose.test.ts, web/e2e-tests/copy-and-paste.test.ts, web/e2e-tests/drafts.test.ts, web/e2e-tests/edit.test.ts, web/e2e-tests/mention.test.ts, web/e2e-tests/message-basics.test.ts
Just verifying that a `message-list` is rendered is not enough to ensure that we are in the correct narrow. We need to check if we are narrowed to the correct message list id.
This prevents CI from failing unexpectedly.
=> puppeteer: Use a robust method to verify if we switched narrow.

docs/documentation/api.md, docs/tutorials/new-feature-tutorial.md, docs/tutorials/writing-views.md
Update the tutorial documentation on creating views and REST apis to reflect the `typed_endpoint` decorator instead of the previous `has_request-variables` decorator.
<details>
</details>
=> Typed-endpoint-docs

corporate/lib/stripe.py, corporate/tests/test_stripe.py, corporate/tests/test_support_views.py, corporate/views/support.py, templates/corporate/support/next_plan_forms_support.html, templates/corporate/support/remote_realm_details.html, templates/corporate/support/remote_server_support.html
Expands section for scheduling plans in the remote support view to have a form to create a "temporary courtesy" plan (aka our legacy plan) for remote servers and realms.
**Notes**:
- Form is not shown if there is a current plan for the remote billing entity, and would raise a `SupportRequestError` in that case as well.
- There must be an end date submitted for the courtesy/legacy plan to be configured.
- The user-facing language for these plans is still "Free (legacy plan)". The terminology "temporary courtesy plan" is all internal to the support view/admin.
- Not implemented for non-remote support view because there is no legacy plan support in place for non-remote billing entities currently.
---
<details>
<summary>Schedule plan forms in remote …
=> remote-support: Add ability to configure temporary courtesy plan.

web/src/user_group_edit.js, web/styles/app_components.css, web/styles/subscriptions.css, web/templates/dropdown_widget_with_label.hbs
Previously, even when a user doesn't have permission to edit a user group, the dropdown for the group permission settings was not disabled, and is possible for a user to change the values.
This commit adds a property `is_disabled` to the `dropdown_widget`, which can be used to disable the dropdown in cases of no permission  to update the widget, and the same is reflected in the user group permission settings.
[CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/group.20permissions.20dropdown.20not.20disabled/near/1886217)
<details> …
=> user_group_settings: Disable dropdown if no permission to update it.

zerver/lib/user_groups.py, zerver/tests/test_event_system.py, zerver/tests/test_home.py, zerver/tests/test_user_groups.py
This PR refactors code in `user_groups_in_realm_serialized` such that we do not prefetch `can_mention_group__direct_members` and `can_mention_group__direct_subgroups` using `prefetch_related` and instead fetch members and subgroups for all groups in separate queries and then use that data to find the members and subgroups of the group used for that setting.
This change helps us in avoiding two prefetch queries for each setting when we add more group settings.
<details> …
=> user_groups: Refactor code to compute user group objects.

corporate/lib/stripe.py, corporate/tests/test_support_views.py, corporate/views/support.py, templates/corporate/activity/installation_activity_table.html, templates/corporate/support/current_plan_forms_support.html, templates/corporate/support/next_plan_forms_support.html, templates/corporate/support/realm_details.html, templates/corporate/support/remote_realm_details.html, templates/corporate/support/remote_server_support.html, templates/corporate/support/sponsorship_details.html, templates/corporate/support/sponsorship_discount_forms.html, templates/corporate/support/sponsorship_forms_support.html, web/styles/portico/activity.css
Use the same sponsorship form template for both remote and Zulip Cloud support views.
**Notes**:
- Removes "Org type" abbreviation from support/activity views, and instead uses "Organization type".
- Adds a "🛠️ Realm management" header/section to Zulip Cloud view for support actions that are specific to non-remote realms (e.g., changing an organization's type).
- Moves notification about notifying organization owners when sponsorship is approved on Zulip Cloud to success message in view, which mirrors how this information is shown in the remote support view for billing users.
- If a Zulip Cloud realm is 100% sponsored for the Standard plan, then the discount and sponsorship forms are no longer shown in the support view, which mirrors the behavior of the remote support views for the …
=> support: Consolidate sponsorship discount forms.

api_docs/construct-narrow.md
On the server-side, the implementation of the "near" operator is a noop. Clients should instead use the "anchor" parameter to express the "near" operator in a search box or URL fragment.
<details>
<summary>Updated "Message IDs" section in Construct a narrow doc</summary>
[Current documentation](https://zulip.com/api/construct-narrow#narrows-that-use-ids)
</details>
---
<details>
</details>
=> api-docs: Clarify the behavior of the near operator.

zerver/actions/scheduled_messages.py, zerver/lib/recipient_parsing.py, zerver/lib/request.py, zerver/tests/test_recipient_parsing.py, zerver/tests/test_scheduled_messages.py, zerver/views/scheduled_messages.py
Migrate `scheduled_message.py` to typed_endpoint.
Perform Json parsing in the endpoint itself instead of
in `recipient_parsing.py`.
=> scheduled_messages: Migrate to typed_endpoint.

tools/semgrep-py.yml, zerver/decorator.py, zerver/tests/test_decorators.py
migrated `decorators.py` to `typed_endpoint`.
`authenticate_internal_api` is only called once in `internal_api_view` and is not a standalone endpoint, so it does not need the `@typed_endpoint` decorator.
=> decorators: Migrate to typed_endpoint.

docs/overview/changelog.md, docs/production/authentication-methods.md, docs/production/email.md, docs/production/postgresql.md, docs/production/requirements.md, zerver/lib/scim.py, zerver/models/users.py, zerver/tests/test_auth_backends.py, zerver/tests/test_scim.py, zerver/views/auth.py, zproject/backends.py, zproject/computed_settings.py, zproject/default_settings.py, zproject/prod_settings_template.py
Replace the SOCIAL_AUTH_SYNC_CUSTOM_ATTRS_DICT with
SOCIAL_AUTH_SYNC_ATTRS_DICT, designed to support also regular user attrs
like role or full name (in the future).
Custom attributes can stay configured as they were and will get merged
into SOCIAL_AUTH_SYNC_ATTRS_DICT in computed_settings, or can be
specified in SOCIAL_AUTH_SYNC_ATTRS_DICT directly with "custom__"
prefix.
The role sync is plumbed through to user creation, so users can
immediately be created with their intended role as provided by the IdP
when they're creating their account, even when doing this flow without
an invitiation
Notes:
- The interface for configuring this may need some dicussion/revision of course. With my proposal here, the idea is to replace the `SOCIAL_AUTH_SYNC_CUSTOM_ATTRS_DICT` dict in settings with more …
=> Support syncing user role during SAML login

zerver/lib/validator.py, zerver/tests/test_openapi.py, zerver/views/message_send.py
Convert `message_send.py` use `typed endpoint`.
Disable `message_send` endpoint `to` parameter in the `openapi`
`validate_json_schema` check, because it is a special case where the
content type of the parameter is application/json but the
parameter may or may not be JSON encoded since previously we also
accepted a raw string and some ad-hoc bot might still depend on sending
a raw string.
=> message_send: Convert to typed endpoint.

web/styles/zulip.css, web/templates/navbar.hbs
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.22sign.20up.22.20.2F.20.22login.22.20truncated
This allows log in button in navbar for spectators to have more space to be displayed in different languages without being truncated. Login page already has 2 buttons for user to sign up from.
=> navbar: Remove signup button.

web/src/info_overlay.ts, web/src/rendered_markdown.ts, web/styles/rendered_markdown.css, web/templates/markdown_timestamp.hbs, web/templates/mention_content_wrapper.hbs, web/tests/rendered_markdown.test.js
This PR fixes long-standing problems with `inline-block` and `inline-flex` causing trailing punctuation especially to drop to the line below mentions and global times. 
Not only are the design and near-pixel-perfect approximate dimensions of mentions and global times preserved here, but in the case of global times, they now do not disturb the line-height otherwise set in the message area. Global times retain their `inline-flex` layout, which is now specified on the inner element, while the outer global time element displays properly inline.
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/wrangling.20inline.20elements/near/1922053), [CZO issue](https://chat.zulip.org/#narrow/stream/9-issues/topic/global.20time.20wrapping/near/1907899) …
=> markdown: Render mentions, global times as inline elements.

web/src/bootstrap_typeahead.ts
This bug was introduced in d9f25d01a15521bdafec77689a171420810d1688 
It's possible that `find(".active")` returns `undefined` here.
=> bootstrap_typeahead: Fix bug on select with no active item.

zproject/backends.py
As detailed in the comment in the code:
The upstream implementation uses the outdated /oauth2/authorize API (instead of the v2.0 API), which doesn't allow us to authenticate users with just a personal Microsoft account. v2.0 API is required. This requires us to override the default URLs to use it as well as adjust the requested scopes, to match this new API.
The backend in its previous state was only able to authenticate users that were tied to an organizational directory, even if the application settings in Azure were set up to also allow personal accounts. Users trying to use a personal account would face an error from Microsoft:
AADSTS500200: User account 'xxxx@example.com' is a personal Microsoft account. Personal Microsoft accounts are not supported for this application unless …
=> auth: Update AzureADAuthBackend to use the newer Microsoft API.

zerver/data_import/import_util.py, zerver/lib/export.py, zerver/lib/import_realm.py, zerver/tests/test_import_export.py
Haven't investigated automated tests yet. Tested locally in dev. Here's some example output listing emoji files for the realms, showing that the imported realm (id `4`) has all the files for each emoji like we'd expect, matching the files that the original realm (id `2`) had - meaning the stills were generated and `.png` thumbnails were re-generated:
```
./var/uploads/avatars/4/emoji/images/817e19fb.gif.original
./var/uploads/avatars/4/emoji/images/cc36a770.png.original
./var/uploads/avatars/4/emoji/images/still/817e19fb.png
./var/uploads/avatars/4/emoji/images/817e19fb.gif
./var/uploads/avatars/4/emoji/images/e9144a9a.png.original
./var/uploads/avatars/4/emoji/images/e9144a9a.png
./var/uploads/avatars/4/emoji/images/cc36a770.png
./var/uploads/avatars/2/emoji/images/817e19fb.gif.original …
```
=> import: Export and import .original emoji files correctly.

help/delete-a-message.md, help/restrict-message-editing-and-deletion.md
Current: https://zulip.com/help/delete-a-message
Updated:
Current: https://zulip.com/help/restrict-message-editing-and-deletion
Updated:
=> help: Fix up message deletion permissions documentation.

web/src/info_overlay.ts
This corrects [malformed closing tags](https://github.com/zulip/zulip/pull/31416#discussion_r1725949135) in the information overlay, which were merged along with #31416. As such, I'm marking this PR also with the backport-candidate label.
=> global_times: Correct malformed closing tags in overlay.

web/src/server_events_dispatch.js, web/src/stream_edit_subscribers.ts, web/src/user_group_edit.js, web/src/user_group_edit_members.ts, web/templates/stream_settings/stream_members.hbs, web/templates/stream_settings/stream_members_table.hbs, web/templates/user_group_settings/user_group_members.hbs, web/templates/user_group_settings/user_group_members_table.hbs, web/templates/user_group_settings/user_group_settings.hbs, web/tests/dispatch.test.js
- First commit is to fix live updating stream subscribers list.
- Second commit is to fix live update of groups UI.
<details>
</details>
=> Fix live updating groups UI on changing group managing permissions.

web/templates/typeahead_list_item.hbs
=> typeahead: Change icon for wildcard mentions.

help/include/view-starred-messages.md, help/keyboard-shortcuts.md, web/src/deprecated_feature_notice.ts, web/src/hotkey.js, web/templates/keyboard_shortcuts.hbs, web/templates/left_sidebar.hbs, web/templates/tooltip_templates.hbs, web/tests/deprecated_feature_notice.test.js
This PR adds '*' as a keyboard shortcut to navigate to the starred messages view and the shortcut is documented in various required locations accordingly. 
Fixes: [#31397](https://github.com/zulip/zulip/issues/31397).
Fixes: 
| Screencast |
|--------|
|![keyboard shortcut](https://github.com/user-attachments/assets/e644d8a8-3958-4a1a-a89b-dd2c684bee0a)| 
| Desc | After PR |
| Tooltip in the left sidebar | ![image](https://github.com/user-attachments/assets/334afbf2-6935-4c58-946a-8e8f35f1f6a3) |
| `?` menu | ![image](https://github.com/user-attachments/assets/a2ee4ad6-5c18-41c6-b069-d827bc8ac1aa) | 
| Help center->Keyboard shortcuts | ![image](https://github.com/user-attachments/assets/58508616-e052-470e-bd62-2722a976d280) | 
| Help …
=> hotkey: Add keyboard shortcut to navigate to starred messages view.

corporate/tests/test_support_views.py, corporate/views/support.py, templates/corporate/support/realm_details.html, zerver/actions/realm_settings.py, zerver/tests/test_realm.py
Adds ability in Zulip Cloud support view to update the maximum number of email invitations that a realm can send per day.
**Notes**:
- Uses "0" as the value to reset the maximum number of invites to the default for the current plan type.
- Adds some validation for changing the realm's max invites via the support view so that it is not set below the default max for the realm's plan type, and so that if it's currently set to the default max it's not reset to that same value.
- The audit log event type used is `REALM_PROPERTY_CHANGED`.
- Adds some question mark icons with hover tooltips to note how to change back to the default for the current plan type, and that changing the plan type will reset the max invitations to be the default for the new plan type.
Generally, these realm management …
=> support: Add ability to update max daily invitations for realm.

docs/testing/mypy.md, zerver/actions/message_send.py, zerver/actions/streams.py, zerver/lib/cache.py, zerver/lib/cache_helpers.py, zerver/lib/display_recipient.py, zerver/lib/message.py, zerver/lib/query_helpers.py, zerver/lib/stream_subscription.py, zerver/lib/test_classes.py, zerver/lib/user_groups.py, zerver/models/recipients.py
This was made unnecessary in django-stubs 5.0.1 and mypy 1.10.
=> mypy: Remove use of ValuesQuerySet and QuerySetAny

corporate/views/support.py, zerver/actions/realm_settings.py, zerver/models/realms.py
There are a few places where we want to set the `max_invites` for a realm to the default for a realm's `plan_type`, so this creates a helper function that can be used consistently to get that default value.
**Notes**:
- Follow-up from [review comment](https://github.com/zulip/zulip/pull/31430#discussion_r1729591686).
- Uses `Realm.ALL_PLAN_TYPES` dict for check/assertions that a `plan_type` value is one of the valid plan types. This dict was added for populating realms with different plan types for billing testing (see commit 9ebb3f06b3ad87e91e1f66bb5a94fe377c4196b9).
---
<details> …
=> realm-settings: Get max invites for realm plan type helper.

analytics/views/stats.py, zerver/decorator.py
Migrate analytics to `typed_endpoint`.
Split `get_chart_data` into two functions `get_chart_data` (the endpoint) and `do_get_chart_data` (the function that is called by other endpoints) because `typed_endpoint` was attempting to validate ` server: Optional["RemoteZulipServer"] = None,` but when `"RemoteZulipServer"` is not imported an error was occurring as observed in #30652 .
=> analytics: Migrate to @typed_endpoint.

corporate/lib/stripe.py, corporate/lib/support.py, corporate/tests/test_support_views.py, corporate/views/support.py, templates/corporate/support/basic_realm_data.html, templates/corporate/support/realm_details.html, templates/corporate/support/remote_realm_details.html
Adds a shared realm data section to both remote and Zulip Cloud support views with this information:
- Organization type
- Plan type
- Non-guest user count
- Guest user count
**Notes**:
- The remote realm section of the support view already had this information, so we're mostly adding it to the Zulip Cloud realm support view.
- Adds two simple database query tests to the support views for a single realm or single remote realm, so that we have a baseline for these views and can assess performance as we expand/change the features on these views.
- Confirms that these updates add two more queries to the Zulip Cloud support view for a realm.
- The user counts for the Zulip Cloud view uses the same queries as is used for getting the realm's seat count.
- Adds a shared context dict to the …
=> support: Add shared general realm data section to views.

scripts/lib/create-production-venv, scripts/lib/install
This prevents, among other things, `libvips` from pulling in the `firefox` package by way of the `nip2` package.
Fixes: #31411.
<details>
</details>
=> create-production-venv: Do not pull in "recommended" packages.

web/styles/app_variables.css, web/styles/left_sidebar.css, web/styles/zulip.css
This PR opens the next phase of the redesigned left sidebar as articulated in @terpimost's design at https://terpimost.github.io/zulip-sidebar/
Fixes #27565
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/proposed.20left-sidebar.20spacing.20and.20alignment/near/1918358)
It removes the awkwardly named `--left-sidebar-collapse-widget-gutter` value and replaces it with `--left-sidebar-padding-left`. Negative-margin values that pulled expand/collapse toggles and otherwise worked around the larger-than-necessary "widget gutter" have also been adjusted.
Note that the width of the left sidebar has been preserved here (2px from the old value have been added to the width of the sidebar itself). Eagle-eyed reviewers may notice a very slight shift in some of the screenshots …
=> left_sidebar: Adjust lefthand padding, gridded row values.

web/src/left_sidebar_navigation_area.ts, web/src/starred_messages_ui.ts, web/styles/app_variables.css, web/styles/left_sidebar.css, web/templates/left_sidebar.hbs, web/tests/left_sidebar_navigation_area.test.js, web/tests/starred_messages.test.js
Fixes #30898.
This PR improves how the starred message count is hidden and follows the following pattern:
- Shows a dot where the counter would be.
- The message counter is revealed by hovering over the starred message row.
- The message counter is revealed when the user is in the starred message view.
<details><summary>GIF</summary>
<p>
</p>
</details> 
<details><summary>Pic</summary>
<p>
</p>
</details> 
<details>
- [] Highlights technical choices and bugs encountered.
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html …
=> left sidebar: Improve how starred message count is hidden.

web/e2e-tests/compose.test.ts, web/e2e-tests/drafts.test.ts, web/src/drafts.ts, web/src/filter.ts, web/src/message_list_view.js, web/src/message_store.ts, web/src/message_view.js, web/src/people.ts, web/tests/filter.test.js, web/tests/people.test.js, web/tests/people_errors.test.js
This PR fixes the behaviour of inconsistent recipient name order for group direct message.
This PR fixes multiple sub issues:
- The message header for each narrowed group direct message.
- Recipient row having incorrect order.
- Recipient order in drafts for group direct message draft.
- Left sidebar recipient order.
- Recipient changing on `message_header` and `compose_to_target` narrow.
- Placeholder text on compose box.
- Order of pills in private message recipient in compose box.
All of the sub issues either uses `util.strcmp` or `sort_emails` function (which is also using `util.strcmp`) to sort the recipients to make it consistent.
Fixes: zulip#27375
[Screencast from 22-05-24 03:35:40 AM IST.webm](https://github.com/zulip/zulip/assets/33497322/3ca6 …
=> Fix order of group direct message recipients.

web/src/settings_emoji.ts, web/templates/settings/admin_emoji_list.hbs
previously, author names are displayed in plain text, now they are converted to pills.
Fixes #30990.
| Dark | Light |
|----------|----------|
| ![image](https://github.com/user-attachments/assets/126bf266-7d35-4d88-96a4-bd9fe2589d31) | ![image](https://github.com/user-attachments/assets/77dd1741-d2bc-48e4-bea5-89a4063073e1) |
<details>
</details>
=> settings: Convert name to pills in custom emoji section.

web/src/emoji_picker.ts, web/src/giphy.js, web/src/popover_menus.ts, web/src/user_card_popover.js, web/src/user_group_popover.ts, web/styles/app_components.css, web/styles/app_variables.css, web/styles/popovers.css, web/templates/popovers/user_card/user_card_popover.hbs, web/templates/user_profile_modal.hbs
This PR enhances the user_card_popover experience for bot users:
1. The bot owner card now appears as an overlay, centered on the screen, similar to mobile display behavior. This also hides the bot user card when the bot owner card is active.
2. The bot user role is now displayed in the bot user card, below the bot full name.
3. The bot owner field has been repositioned alongside user fields, making room for the new user pill display.
This also adds the detailed bot role in the bot's user profile modal in the format: `Bot ({role})`.
Fixes: Part of #31027.
| ![Screenshot 2024-07-25 at 6 02 14 PM](https://github.com/user-attachments/assets/e5243b21-1ce0-4a12-b5e3-dee07299d935) | ![Screenshot 2024-07-30 at 3 44 …
=> user_card_popover: Improvements for bot and bot owner user cards.

web/src/narrow_banner.ts, web/src/people.ts, web/tests/message_view.test.js, web/tests/people.test.js
Previously empty-view banner for DM / group DM with any recipients contained "Why not start the conversation".
For deactivated users/bots, we are now not displaying it as it is quite confusing (since it's not possible to dm them).
| ![Before](https://github.com/user-attachments/assets/9d0aaf39-3d08-4a12-aee4-7b2adc546276) | ![After](https://github.com/user-attachments/assets/22c917c0-71bd-4160-8f9a-76e9e3fbad49) |
| ![image](https://github.com/user-attachments/assets/33ec13ff-d5d2-4321-b3fe-51d0b721d135) | ![image](https://github.com/user-attachments/assets/5f67aa1b-dc2a-4d2e-8102-9ece333560be) |
To reproduce: In search box type "Direct messages", with the deactivated user/users.
<details> …
=> narrow_banner: Fix message view banner for dm with deactivated user.

web/src/server_events_dispatch.js, web/src/settings_config.ts, web/templates/settings/display_settings_general.hbs, web/templates/settings/display_settings_information.hbs
Finished renaming `user_display_settings` to `user_preferences`.
Fixes part of zulip#26874.
this pull request:
Renames user_display_settings to user_preferences.
Changed Files:
`web/src/server_events_dispatch.js`
`web/src/settings_config.ts`
`web/templates/settings/display_settings_general.hbs`
`web/templates/settings/display_settings_information.hbs`
<details>
</details>
=> settings: Rename user_display_settings to user_preferences.

zerver/actions/uploads.py, zerver/tests/test_delete_unclaimed_attachments.py
Since each loop may add more than one file to the `storage_paths` list, this may result in more than 1000 files being sent to delete_message_attachments.  Since the S3 backend only supports 1000 elements being deleted at once, we must partition the list into chunks which are no more than 1000 elements long.
<details>
</details>
=> do_delete_old_unclaimed_attachments: Cap deletions at batch size.

web/src/stream_settings_ui.js, web/styles/app_components.css, web/templates/stream_settings/stream_settings_overlay.hbs
fixes #18332.
| Dark | Light |
|----------|----------|
| ![image](https://github.com/user-attachments/assets/1cf9a28f-1f84-4dd8-8b7a-3520927efd89) | ![image](https://github.com/user-attachments/assets/bf101471-82f4-45d7-ab0b-8cf64ed22b26) |
- At the time the issue was opened, the **Not Subscribed** tab was not available. However, it is now present, so the text will be displayed in **Not Subscribed** tab too.
| when no channel match filter query | when there is no channel |
|----------|----------|
| ![image](https://github.com/user-attachments/assets/0564c76c-fd79-4ca4-b99c-478f5896e971) | ![image](https://github.com/user-attachments/assets/0c1be636-5d31-4767-b8b9-308e6502c846) |
<details>
Communicate …
=> stream_settings: Show disabled create stream button and text.

corporate/models.py, corporate/views/plan_activity.py
Updates the string method for `LicenseLedger` objects to include the license counts, date and type of entry.
**Notes**:
- Main known use case is printing the ledger entry for a customer plan via the `invoiced_through` field.
- Translated the `is_renewal` bool as a string to be "renewal" or "update".
- Updated the header area of the plan activity view in second commit:
- Adds the `invoiced_through` entry.
- Revises the `next_invoice` date to have the same name as the support view: "Start of next billing cycle".
<details>
<summary>python shell example</summary>
```
In [1]: plan = CustomerPlan.objects.get(id=8)
In [2]: ledger_entries = LicenseLedger.objects.filter(plan=plan).order_by("-event_time")
In [3]: for entry in ledger_entries:
...:     print(entry)
...: 
License update, 3 purchased, …
```
=> corporate: Update license ledger string method.

scripts/lib/setup_path.py
`setup_path()` previously only checked that some `zulip-py3-venv` was the `sys.prefix`, not that it was the one associated with this deployment.  When `uwsgi` is started, it is started from `bin/uwsgi` within a `zulip-py3-venv` virtualenv, and as such sets `sys.executable` to that, resulting in uwsgi workers picking up the library path of that virtualenv.  On first start, `sys.path` thus already matches the expected virtualenv, and the `setup_path` in `zproject.wsgi` does nothing.
If a rolling restart was later done into a deployment with a different virtualenv, the `zproject.wsgi` call to `setup_path()` did not change `sys.path` to the new virtualenv, since it was already running within _a_ virtualenv.  This led to dependency version mismatches, and potentially even more disastrous …
=> setup_path: Ensure that the right venv is activated.

web/src/message_list.js, web/styles/message_row.css, web/templates/message_body.hbs, web/templates/message_edit_form.hbs, web/templates/single_message.hbs
This moves the placeholder elements for the message edit form, to `message_edit_form.hbs`, so they are conditionally rendered only when a message is being edited, rather than being present for every message in the list.
Fixes #31134.
**Screenshots and screen captures: (Testing screencast)**
<details>
</details>
=> message_list: Conditionally render message edit form container element.

api_docs/changelog.md, version.py, web/src/message_events.js, web/src/message_store.ts, web/src/server_message.ts, web/src/types.ts, zerver/actions/message_edit.py, zerver/lib/event_schema.py, zerver/lib/message_cache.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_edit.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/edit.20history/near/1928233)
PR to remove the `prev_rendered_content_version` field from:
* the 'edit_history' object within message objects in the API response of `GET /messages`, `GET /messages/{message_id}` and `POST /zulip-outgoing-webhook`.
* the 'update_message' event type
as it is not used by any client.
Note: The field is still stored in the 'edit_history' column of the 'Message' table as it will be helpful when making major changes to the markup rendering process.
<details> …
=> edit_history: Remove 'prev_rendered_content_version' field.

web/src/condense.ts, web/src/message_edit.ts, web/styles/zulip.css, web/templates/message_body.hbs, web/templates/message_length_toggle.hbs
This moves the content inside `message_length_controller` to a new handlerbars template `message_length_toggle.hbs`, and dynamically renders the content based on the message length.
Since the majority of the messages aren't collapsed/condensed, this change should improve the initial rendering of the message list.
Fixes #31133.
**Setup**: Created two channels with 50 messages each, one of the channel contained only short messages, while the other contained only long messages that would render the `SHOW MORE`/`SHOW LESS` toggle buttons.
**Method used**: Used `performance.now()` to measure the time taken by `condense.condense_and_collapse()` in the initial message rendering.
**Note:** There may be better options to measure the performance of this, like using profiling with filters, but I'm …
=> condense: Dynamically render content for message length toggle.

scripts/setup/apt-repos/zulip/custom.sh, scripts/setup/apt-repos/zulip/noble.list, tools/lib/provision.py
These did not exist when we first added Ubuntu 24.04 support; now they do. Fixes #31261.
(Don’t auto-merge this, since that doesn’t check production tests.)
=> apt-repos: Use PGroonga binaries on Ubuntu 24.04

web/src/bootstrap_typeahead.ts, web/src/portico/signup.ts, web/src/search.ts
`keyCode` is deprecated and those values are not readable.
Tested by using all the special keys - backspace, enter, tab, arrows to see if they are working as expected. 
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/Migration.20to.20use.20.60key.60.20instead.20of.20.60keyCode.60
=> typeahead: Migrate to use `key` instead of `keyCode`.

web/styles/dark_theme.css, web/styles/settings.css, web/templates/settings_overlay.hbs
Fixes: One point of https://chat.zulip.org/#narrow/stream/6-frontend/topic/CSS.20selector.20performance/near/1920156
| --- | --- |
| <img width="1038" alt="before_light_org" src="https://github.com/user-attachments/assets/b03b40e2-55e2-4b8f-b745-3991ecf38f35"> | <img width="1038" alt="after_light_org" src="https://github.com/user-attachments/assets/1d7c6db1-be32-439b-8e05-c0491acd3e80"> |
| <img width="1038" alt="before_light_personal" src="https://github.com/user-attachments/assets/08fcaf4f-5223-4e80-850f-ce256dd6e8ea"> |<img width="1038" alt="after_light_personal" src="https://github.com/user-attachments/assets/04cc370d-6578-40cc-9097-85bdded4da1c"> |
| <img width="1038" alt="before_dark_org" …
=> settings: css selector performance .sidebar

web/src/settings_invites.ts
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/filter.20text.20is.20applied.20in.20every.20tab.2E/near/1923769)
**Before:**
**After:**
<details>
</details>
=> settings_users: Fix for filter search text issue in settings users.

web/src/topic_list.ts, web/styles/left_sidebar.css
Grouping should not be rendered in the event a channel is empty. This PR explicitly adds a class declaring that case, so that there is no need of fancy `:has()` portions to the CSS selectors.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/stream.20with.20no.20topics.20topic.20wrapper.20line/near/1934129)
| Before | After (no change for channels with topics |
| --- | --- |
| ![empty-channel-before](https://github.com/user-attachments/assets/f9215b1b-e167-47ee-8bcd-f7a96a852bda) | ![empty-channel-after](https://github.com/user-attachments/assets/7344b513-c230-46df-8b2c-531b8f1379b5) |
| ![channel-with-topics-before](https://github.com/user-attachments/assets/051a4757-df3e-4230-b05b-c4faaca442bf) | …
=> left_sidebar: Render brackets only on non-empty channels.

puppet/zulip/manifests/profile/app_frontend.pp
Using 7 makes this fail when run under the Sentry cron wrapper.
Fixes: 
<details>
</details>
=> puppet: Make restart-server cron use standard day-of-week.

web/styles/settings.css, web/styles/subscriptions.css, web/templates/dialog_change_password.hbs, web/templates/settings/account_settings.hbs, web/templates/settings/organization_profile_admin.hbs, web/templates/settings/profile_settings.hbs, web/templates/settings_overlay.hbs, web/templates/stream_settings/stream_creation_form.hbs, web/templates/user_group_settings/user_group_creation_form.hbs, web/templates/user_profile_modal.hbs
This PR removes all `.new-style` references from `settings.css`. It does not yet clear the `new-style` class from the HTML, which must wait until the remaining `.new-style` values are cleaned up elsewhere in the codebase, including especially `components.css` and `app_components.css`.
An extensive set of matching before-and-after screenshots appear below; but it would be good to have testing and visual scans by multiple sets of eyeballs that none of the removals here negatively impact especially the settings modals or channel and groups modals.
_Before and After are identical throughout._
| --- | --- |
| ![group-settings-before](https://github.com/user-attachments/assets/8da7a3d3-7a3a-4476-9101-92b2ca487159) | …
=> settings: Clear all .new-style references.

zerver/lib/request.py, zerver/tests/test_openapi.py, zerver/views/auth.py
migrate the following endpoints from `@has_request_variables` to `@typed_endpoint` :
- `remote_user_sso()`
- `get_email_and_realm_from_jwt_authentication_request()`
- `remote_user_jwt()`
- `oauth_redirect_to_root()`
- `login_page()`
- `jwt_fetch_api_key()`
- `api_fetch_api_key()`
- `json_fetch_api_key()`
=> auth: Migrate to @typed_endpoint.

zerver/actions/alert_words.py, zerver/actions/scheduled_messages.py, zerver/actions/user_status.py
https://github.com/zulip/zulip/pull/31169#issuecomment-2262076392
> Though as discussed on chat.zulip.org today, I wonder if some of these should be using durable=True instead, we can handle that in a follow-up sweep.
<details>
</details>
=> actions: Use 'durable=True' in outermost transaction.atomic block.

web/styles/app_components.css, web/styles/left_sidebar.css, web/styles/message_view_header.css, web/styles/settings.css, web/styles/zulip.css, web/templates/compose.hbs, web/templates/dropdown_list.hbs, web/templates/message_feed_errors.hbs, web/templates/navbar_icon_and_title.hbs, web/templates/settings/admin_profile_field_list.hbs, web/templates/settings/notification_settings.hbs, web/templates/settings/profile_field_choice.hbs, web/templates/settings/profile_settings.hbs, web/templates/subscribe_to_more_streams.hbs
` i ` occurences from portico haven't been touched. See https://github.com/zulip/zulip/pull/31204#discussion_r1716314707
In a lot of these commits, `i` has been replaced by `.zulip-icon` wherever applicable. These are cases where all <i> tags inside an element have `.zulip-icon` tag. 
The other common occuring class is `.fa`, but in those cases I've introduced a new class name, since I thought we're in the processing of transitioning from `fa` to `zulip-icon` and somehow it didn't feel right to introduce `.fa` rules now. 
1c8eaf722a5e0dbbe2784eab054827267e3b5cde is a bit different from other commits in the sense that it has some refactoring also going on. 
I haven't added screenshots, see https://github.com/zulip/zulip/pull/31204#issuecomment-2265944347 …
=> css: Use classname for ` i ` rules. 

web/src/bootstrap_typeahead.ts
The `flip` popper function is not working properly here since we migrated to use Simplebar (Can be verified by removing `data-simplebar`).
To fix it, we need to force trigger the function as soon as tippy is attached to DOM.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/topic.20typeahead.20opening.20downwards
=> typeahead: Fix compose topic typeahead partially hidden.

web/src/util.ts, web/tests/util.test.js
discussed here: https://chat.zulip.org/#narrow/stream/9-issues/topic/Search.3A.20Cannot.20find.20active.20element/near/1928574
I decided to change this to fail quieter, because when introducing uses of `util.the` across the codebase it was hard to know for sure if I made any mistakes, and this will let us catch mistakes without unnecessarily breaking the website.
=> util: Use blueslip error for util.the instead of an assert.

web/templates/move_topic_to_stream.hbs
We initialize the topic typeahead in the modal with the element `$("#move_topic_form .move_messages_edit_topic")`, which previously was capturing two elements, the second one being a hidden input element.
This wasn't causing issues, but once we added `util.the` in the typeahead code we were getting errors for having multiple elements where we expected one.
The fix is removing `move_messages_edit_topic` from the hidden element's classnames, since that class is only used for input and styling things.
=> move_topic: Remove extraneous classname on hidden input, fixes bug.

help/keyboard-shortcuts.md, web/styles/informational_overlays.css, web/templates/keyboard_shortcuts.hbs
This info was already in the Basics section, but was missing from the Navigation section.
Current:  https://zulip.com/help/keyboard-shortcuts#navigation and help modal
<details>
<summary>
Updated
</summary>
</details>
The current sizing (12px) looks really bad at 16px font size:
It's also not necessary, as the modal is currently wide enough such that there's no line wrapping. It's not translated, so we can worry about line wrapping in other languages when we fix that (which may be after we redesign this modal).
<details>
<summary>
Before (16px)
</summary>
</details>
<details>
<summary>
After (16px, 14px)
</summary>
</details>
=> help: Fix minor bugs in keyboard shortcuts help.

zerver/lib/thumbnail.py, zerver/tests/test_markdown_thumbnail.py
BeautifulSoup with `formatter="html5"` unnecessarily escapes many characters with HTML5-specific entities that cannot be correctly parsed by lxml during generation of email notifications.
[Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/HTML.20entities.20in.20email.20notifications/near/1936525).
Cc @alexmv (#30477)
=> thumbnail: Fix corrupted email notifications due to HTML5 entities

web/src/billing/sponsorship.ts, web/src/invite.ts, web/src/portico/signup.ts
[`:selected`](https://api.jquery.com/selected-selector/) is one of several [jQuery-specific selector extensions](https://github.com/wikimedia/eslint-plugin-no-jquery/blob/HEAD/docs/rules/no-sizzle.md) that force jQuery away from the native `document.querySelector` fast path onto the Sizzle slow path, and also present an extra obstacle to migrating away from jQuery. Replace `:selected` by simply using [`.val()`](https://api.jquery.com/val/)/[`.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/value) or [`.selectedOptions`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedOptions) on the `<select>` control.
Similarly, replace [`:input`](https://api.jquery.com/input-selector/) with [`HTMLFormElement.elements`](https://developer.mozilla.org/en …
=> biling: Avoid slow jQuery `:selected` selector extension
