tools/semgrep-py.yml
- https://github.com/zulip/zulip/pull/29409#pullrequestreview-1955495637
=> semgrep: Broaden select_related() and prefetch_related() rules

tools/test-js-with-node, web/src/message_list_tooltips.js, web/src/message_list_tooltips.ts
=> message_list_tooltips: Convert module to TypeScript.

zerver/lib/import_realm.py
The bots do not exist in the user table to look up their active status, and attempting to import them into the analytics table will result in duplicate rows.
<details>
</details>
=> import: Skip "active" check, and analytics, for crossrealm bots.

puppet/zulip/manifests/apache_sso.pp, puppet/zulip/manifests/app_frontend_base.pp, puppet/zulip/manifests/apt_repository.pp, puppet/zulip/manifests/common.pp, puppet/zulip/manifests/external_dep.pp, puppet/zulip/manifests/hooks/sentry.pp, puppet/zulip/manifests/nginx.pp, puppet/zulip/manifests/postgresql_base.pp, puppet/zulip/manifests/postgresql_common.pp, puppet/zulip/manifests/process_fts_updates.pp, puppet/zulip/manifests/profile/app_frontend.pp, puppet/zulip/manifests/profile/base.pp, puppet/zulip/manifests/profile/memcached.pp, puppet/zulip/manifests/profile/rabbitmq.pp, puppet/zulip/manifests/profile/redis.pp, puppet/zulip/manifests/sasl_modules.pp, puppet/zulip/manifests/sha256_file_to.pp, puppet/zulip/manifests/sha256_tarball_to.pp, puppet/zulip/manifests/static_asset_compiler.pp, puppet/zulip/manifests/tornado_sharding.pp, puppet/zulip/manifests/yum_repository.pp
This is linted by more recent puppet-lint.
<details>
</details>
=> puppet: Switch from top-level fact variables to facts dict.

web/templates/buddy_list/view_all_subscribers.hbs, web/templates/buddy_list/view_all_users.hbs, web/templates/draft_table_body.hbs, web/templates/login_to_view_image_button.hbs, web/templates/settings/add_new_bot_form.hbs, web/templates/settings/admin_emoji_list.hbs, web/templates/settings/edit_bot_form.hbs
This PR adds internationalization to the following files:
- `view_all_subscribers.hbs`
- `view_all_users.hbs`
- `web/templates/draft_table_body.hbs` is missing a tag on "Other drafts"
- `web/templates/login_to_view_image_button.hbs`
- `web/templates/settings/add_new_bot_form.hbs` and `web/templates/settings/edit_bot_form.hbs`: "Avatar" is missing a translation tag.
- `web/templates/settings/admin_emoji_list.hbs`, "Unknown author" is missing a translation tag.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html)) …
=> templates: Add internationalization.

web/src/personal_menu_popover.js, web/src/popover_menus.ts, web/src/popover_menus_data.js, web/styles/app_components.css, web/styles/app_variables.css, web/styles/popovers.css, web/templates/personal_menu.hbs, web/templates/tooltip_templates.hbs
This PR introduces a theme switcher feature within the personal
menu popover. The implementation begins with the development of a
tab picker, which has the following features:
* Utilization of radio buttons to emulate the tab picker.
Radio input buttons provides the native way in HTML to select one
value out of a set.
* Support for both horizontal (default) and vertical orientations.
Vertical orientation can be achieved by appending the
`.tab-picker-vertical` class.
* Respects the `prefers-reduced-motion` option set by the user.
Disables the sliding tab animation to improve accessibility.
Additionally, the theme switcher component incorporates error handling
mechanisms. In the event of a server/network error, the tab slider
reverts to the previous theme option after a delay of 500ms. This …
=> personal_menu: Add theme switcher to personal menu popover.

web/styles/right_sidebar.css, web/templates/presence_row.hbs
CZO thread: https://chat.zulip.org/#narrow/stream/9-issues/topic/Right.20sidebar.20bugs/near/1764506
=> fix a couple buddy list bugs

web/src/navbar_alerts.js
This is a follow-up PR for #28924 to fix the weird closing behavior of the navbar alert, which shows the presence of empty required profile fields.
It fixes the following bugs:
- The "profile-missing-required" alert doesn't close on clicking the close button.
- The alert doesn't get closed when all the required profile fields are filled.
<details>
</details>
=> navbar_alert: Fix weird closing of profile-missing-required alert.

web/styles/subscriptions.css
Fix overlapping UI layout for stream subscribers search on screens smaller than 320px. 
The filter subscribers search field now moves to a row below the Subscribers title on small screens instead of overlapping with the table below. 
Fixes #29368 
https://github.com/zulip/zulip/assets/72880238/c5df8668-e8e7-4699-a5ac-5fb104e48bf2
Before | After
--- | ---
<details>
</details>
=> subscriptions: Fix broken UI for subscriber search.

puppet/zulip/manifests/postgresql_client.pp
It pulls in the server.
<details>
</details>
=> puppet: Do not include postgresql_common for all PostgreSQL clients.

web/src/settings_components.ts
This commit fixes an assert statement in get_input_element_value to also include the textarea elements, which is used for realm description. After updating, the assert statement now checks the input_elem to be having one of the following types - HTMLInputElement, HTMLSelectElement and HTMLTextAreaElement, as these cover all the possible input elements with input_type set to "string".
Follow-up to #29264.
<details>
</details>
=> settings_components: Fix assert in get_input_element_value.

web/src/inbox_ui.js
[Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/commas.20in.20Inbox.20and.20Recent.20conversations/near/1768375).
=> inbox_ui: Sort names, not HTML

zerver/lib/message.py, zerver/lib/onboarding.py, zerver/lib/zulip_update_announcements.py, zerver/tests/test_zulip_update_announcements.py
PR to address https://github.com/zulip/zulip/pull/28720#issuecomment-2010342989
<details>
</details>
=> message: Add function to remove single newline in triple quoted string.

web/styles/inbox.css, web/styles/recent_view.css, web/templates/status_emoji.hbs, web/templates/user_with_status_icon.hbs
[Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/commas.20in.20Inbox.20and.20Recent.20conversations/near/1728046).
=> status_emoji: Remove extra space with Handlebars whitespace control

web/src/settings_components.ts, web/src/settings_org.js
This commit refactors code to handle authentication methods so that we need not update the type returned for
"realm_authentication_methods" by get_property_value to be something different than what is the type for realm object.
This change essentially means that we do not use the value returned by get_property_value for authentication methods and directly call realm_authentication_methods_to_boolean_dict.
Follow up to #29264 
<details>
</details>
=> settings: Refactor code to handle authentication methods.

docs/production/postgresql.md, puppet/zulip/manifests/postgresql_client.pp, puppet/zulip_ops/manifests/prometheus/postgresql.pp, tools/semgrep-py.yml, zerver/migrations/0273_migrate_old_bot_messages.py, zerver/models/messages.py, zerver/worker/queue_processors.py
Backports of:
- #29379
- #29473
- 3cbce0c5c7d08bc91a60a0f11ec727d13f28d236 from #29396, to fix the memory leak
- 6ace34c374ed18482375ae6bf56ea23ee298ce40 and 7d0c12aa3acc90e5ab33439cf88efdb086d0c14b from #29409.
- #29417
<details>
</details>
=> Various 8.x backports

tools/test-js-with-node, web/src/submessage.js, web/src/submessage.ts, web/src/widgetize.ts, web/src/zform.js, web/tests/submessage.test.js, web/tests/widgetize.test.js
=> submessage: Convert module to TypeScript.

help/keyboard-shortcuts.md, web/src/common.ts, web/src/copy_and_paste.js, web/templates/keyboard_shortcuts.hbs, web/tests/common.test.js, web/tests/copy_and_paste.test.js
copy_and_paste: Add documentation for keyboard shortcuts for pasting.
turndown: Enable turndown in production.
Fixes: #29209
Windows:
Mac:
<details>
</details>
=> Enable turndown in production and add documentation for keyboard shortcuts for pasting

puppet/kandra/files/postgresql/setup_disks.sh, puppet/kandra/manifests/profile/postgresql.pp, puppet/kandra/manifests/prometheus/postgresql.pp
=> kandra: Improve postgres disk setup

web/src/tippyjs.ts, web/templates/settings/custom_user_profile_field.hbs
Previously, "This profile field is required." tooltip was visible on all custom profile fields, including those that were not required. This commit fixes that by showing the tooltip only when the first label of the wrapper has "required-field" class.
Fixes: [CZO link](https://chat.zulip.org/#narrow/stream/9-issues/topic/.22required.22.20tooltip.20shows.20on.20all.20custom.20profile.20fields)
<details>
</details>
=> tooltips: Fix incorrect "required" tooltip on custom profile fields.

corporate/tests/test_remote_billing.py, zilencer/views.py
As explained in the comment, when we're moving the server plan to the remote realm's Customer object, the realm Customer may not have stripe_customer_id set and therefore that value needs to get moved from the server Customer.
=> remote_billing: Move stripe_customer_id from server to realm if needed.

tools/test-js-with-node, web/src/settings_user_topics.ts, web/src/user_topics.ts, web/tests/message_list_data.test.js, web/tests/notifications.test.js, web/tests/settings_user_topics.test.js, web/tests/unread.test.js, web/tests/user_topics.test.js
CI failures are coming from production install, so I think it's unrelated to these changes?
=> settings_user_topics: Convert module to typescript.

web/src/emojisets.ts
Fixes #25964
We can fail to load emojiset if browser is unable to connect to internet or fetch failed midway due to a network error. We simply wait for browser to come back online and retry.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/blank.20reaction.20emoji/near/1587634
=> emojisets: Retry fetch for emojiset in case of network failure.

api_docs/changelog.md, api_docs/include/rest-endpoints.md, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_openapi.py
This PR adds the pending "/invites" endpoint to the API documentation.
<details>
</details>
=> api_documentation: Add "/invites" endpoint to the api documentation.

docs/production/upgrade.md
- https://github.com/zulip/zulip/pull/29458#discussion_r1546785745
=> docs: Update current PostgreSQL version

confirmation/models.py, corporate/views/remote_billing_page.py, zerver/tests/test_typed_endpoint.py
See commit c2c96eb0cf3b9d9ba0452eb74ab71248f461b1cf (#26405).
=> python: Add missing TypeAlias annotations

tools/test-js-with-node, web/src/settings_components.ts, web/src/user_group_components.ts
=> user_group_components: Convert module to TypeScript.

tools/documentation_crawler/documentation_crawler/spiders/common/spiders.py
[Discussion](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/main.20failing/near/1742264).
=> documentation_crawler: Consider status.zulip.com external

help/moderating-open-organizations.md, help/restrict-name-and-email-changes.md
Current: https://zulip.com/help/restrict-name-and-email-changes
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/moderating-open-organizations#restrict-permissions-for-making-changes
<details>
<summary>
Updated
</summary>
</details>
=> help: Document option to require unique names.

tools/test-js-with-node, web/src/stream_color_events.ts
=> stream_color_events: Convert module to TypeScript.

zerver/lib/message.py, zerver/lib/zulip_update_announcements.py, zerver/tests/test_zulip_update_announcements.py
- Pasting formatted content.
- Quote-and-reply selection.
- Hide user list.
Mockup:
=> zulip_updates: Announce three features.

web/templates/settings/organization_permissions_admin.hbs
This commit adds the /help link to the User Identity section heading of the Organization Permissions, linking to /help/restrict-name-and- email-changes.
[CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/full.20name.20field/near/1773432)
<details>
</details>
=> organization-permissions: Add help page link for User Identity section.

tools/test-js-with-node, web/src/compose_actions.js, web/src/compose_recipient.js, web/src/compose_recipient.ts, web/src/compose_ui.ts, web/src/dropdown_widget.ts
=> compose_recipient: Convert module to TypeScript.

web/src/inbox_ui.js
Fixed vim keymap navigation when inbox's view filter is selected
Fixes #29509.
https://github.com/zulip/zulip/assets/124865398/7592adc4-910b-416e-a8f9-e424c11f0719
<details>
</details>
=> keyboard ui: Fix vimkeymap navigation from inbox view filter

docs/development/setup/vscode-vagrant.md
Fixed the error in documentation.
There was an Error in the documentation so I had fixed it
Fixes: 
The documentation says "Virtual Studio Code" instead of Visual Studio Code
<details>
</details>
=> Documentation Fix

zerver/views/auth.py, zproject/backends.py
It’s [removed in Django 5.0](https://docs.djangoproject.com/en/5.0/releases/5.0/#features-removed-in-5-0).
=> auth: Avoid deprecated django.contrib.auth.views.logout_then_login

web/src/compose_actions.js
More context here:
https://chat.zulip.org/#narrow/stream/6-frontend/topic/autosize.20callback/near/1772484
=> compose_actions: Fix unused callback function.

puppet/kandra/manifests/aws_tools.pp, puppet/kandra/manifests/ksplice_uptrack.pp, puppet/kandra/manifests/profile/base.pp, puppet/kandra/manifests/profile/nagios.pp, puppet/kandra/manifests/profile/zmirror.pp, puppet/kandra/manifests/profile/zmirror_personals.pp, puppet/kandra/manifests/teleport/base.pp, puppet/kandra/manifests/teleport/db.pp, puppet/kandra/manifests/vector.pp, puppet/zulip/manifests/external_dep.pp, puppet/zulip/manifests/postfix_localmail.pp
These were somehow missed in 57f8b48ff989.
<details>
</details>
=> puppet: Switch from top-level fact variables to facts dict, again.

tools/renumber-migrations
Security fix cf8b9ad needed migration `zerver/0501_delete_dangling_usermessages` on the 8.x branch (3db1733). This resulted in two migrations numbered 0501, due to which this tool always got stuck on 0501.
Fixes: [CZO](https://chat.zulip.org/#narrow/stream/18-tools/topic/renumber-migrations.20gets.20stuck.20at.200501)
<details>
</details>
=> renumber-migrations: Skip migration 0501.

tools/test-js-with-node, web/src/compose_tooltips.ts
=> compose_tooltips: Convert module to TypeScript.

web/styles/message_edit_history.css
This is an follow up to #28818, The cursor styling has been changed to default since nothing happens when you click something.
Fixes: 
| Bafore | After |
|----------|--------|
| ![Screenshot from 2024-04-04 13-14-23](https://github.com/zulip/zulip/assets/100200105/8454d7d8-9061-44ad-87fd-063b6f76bbaa) | ![Screenshot from 2024-04-04 13-14-46](https://github.com/zulip/zulip/assets/100200105/5923e8b5-7e9e-4af0-8419-0b362b0b778f) |
<details> …
=> message_edit_history: Set cursor to default on hover.

api_docs/changelog.md, api_docs/include/rest-endpoints.md, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_openapi.py
This PR adds "/invites/multiuse" endpoint to the API documentation.
<details>
</details>
<details>
</details>
=> api_documentation: Document "/invites/multiuse" endpoint.

web/src/message_edit_history.ts, web/styles/message_edit_history.css, web/templates/message_history_overlay.hbs
Adds a loading spinner to the message history overlay, improving the user experience by providing visual feedback while the message edit history is loading.
| Light | Dark |
| [Light Theme Preview](https://github.com/zulip/zulip/assets/100200105/4b7afbf2-4674-431c-90ce-c6c28c62ffa2)| [Dark Theme Preview](https://github.com/zulip/zulip/assets/100200105/0bfdbffa-a039-4d79-a873-25e953e68a70) | 
Fixes: 
<details> …
=> message_edit_history: Add loading spinner.

help/invite-new-users.md
Before: https://zulip.com/help/invite-new-users#send-email-invitations
After:
=> help: Clarify warning about not applying authentication methods.

zerver/actions/user_settings.py, zerver/lib/users.py, zerver/tests/test_bots.py, zerver/views/users.py
**GSoC 2024 Participant**
Completing the remaining works of #24887
Creating a bot with a name that is already in use will raise an error. However, by deactivating the existing bot, creating a new bot with the same name, and then reactivating the original bot, it is possible to have multiple bots with the same name.
To fix this, we check if the bot name is already in use in the active bots list by using `check_bot_name_available()` function present inside `users.py`. If it is, an error will be raised, prompting either the name of the existing bot to be changed or the bot to be deactivated.
<details> …
=> bots: Avoid multiple active bots with the same name.

web/src/dropdown_widget.ts
Addresses this comment:
https://github.com/zulip/zulip/pull/29611/files#r1559751399
=> dropdown_widget: Fix DropdownWidgetOptions.

tools/setup/emoji/build_emoji
=> build_emoji: Make sure emoji names are supported.

web/src/user_topic_popover.js, web/styles/inbox.css, web/styles/recent_view.css
=> Hide default topic visibility indicator in recent view.

web/styles/portico/portico_signin.css
This ensures that in the registration page the text does not overlap icons in any language.
Changed pixel to percentage definition so that it adapts dynamically to all languages. After testing in all languages 16% is the minimum requirement so that all text is properly formatted. (Including Ukrainian, witch is an edge case)
Fixes: https://github.com/zulip/zulip/issues/20563
Befor (In Ukrainian):
After (In Ukrainian):
<details>
</details>
=> onboarding: Fix formatting of registration page buttons.

zerver/views/message_fetch.py
=> message_fetch: Take a REPEATABLE READ READ ONLY when fetching messages.

templates/corporate/for/research.html
=> portico: Add quote to /for/research.

api_docs/changelog.md, api_docs/construct-narrow.md, version.py, zerver/lib/narrow.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_fetch.py
Create has:reaction operator on the backend.
Use exists query in sql alchemy to check for messages that have reactions.
Prep commit for [#29109](https://github.com/zulip/zulip/pull/29109)
=> reaction view: Create backend operator.

web/styles/portico/integrations.css
Added a rule for unordered list elements inside
an ordered list element.
Fixes zulip#29669
- Cannot render unordered lists inside the {{tabs}} block in markdown:
More detail about the bug: [ISSUE#29669](https://github.com/zulip/zulip/issues/29669)
- Unordered lists now can be rendered properly:
<details>
</details>
=> integrations_docs: updated integrations css.

puppet/kandra/manifests/app_frontend.pp
This was removed in 263212decf68.
<details>
</details>
=> kandra: Remove zulip::static_asset_compiler include.

zerver/actions/invites.py
=> invites: Use query.count() not len(query).

web/templates/popovers/emoji/emoji_popover_emoji.hbs
This fixes the bug where on hovering / selecting an emoji picker search results emoji, invariably its canonical name would show / be used, which is not always the same as the matching alias. For example, searching for "swe" would show the "sweeping" emoji, but its canonical name is "broom" which can be a confusing search result for "swe".
Fixes: [Issue report on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Emoji.20typeahead.2Fautocomplete.20order.3F/near/1779039)
PS: The code did already intend for this happen, by sending the matching alias to the handlebars template, the bug was that the template did not use this variable, which has now been fixed here
Though "yam" is the canonical name of this emoji, it's now named the alias matching …
=> emoji_picker: Search result emojis now named as the matching alias.

templates/corporate/hello.html, web/styles/portico/hello.css
=> hello: Apply same link styles to all the screen descriptions.

templates/corporate/activity/installation_activity_table.html
=> activity: Rearrange columns.

docs/production/scim.md
Documents the little functionality added in
c9ca4e68e525c8e5d4e1019e45b7a3105b21e41e.
=> docs: Document new create_guests_without_streams SCIM option.

zerver/management/commands/runtornado.py
This is particularly important because they can be quite heavy-weight.
<details>
</details>
=> runtornado: Honor the --skip-checks flag.

zerver/lib/cache.py, zerver/lib/html_to_text.py, zerver/lib/request.py, zerver/middleware.py, zerver/views/documentation.py, zproject/computed_settings.py
This middleware was highly-specific to a set of URLs, and pulled in a beautifulsoup dependency for Tornado.  Move it closer to where it is used, minimizing action at a distance, as well as trimming out a dependency.
<details>
</details>
=> documentation: Move OpenGraph description updating out of middleware.

zerver/lib/typed_endpoint.py, zerver/lib/typed_endpoint_validators.py, zerver/tests/test_push_notifications.py, zilencer/views.py
migrated views:
- `zilencer.views.register_remote_server`
- `zilencer.views.register_remote_push_device`
- `zilencer.views.unregister_remote_push_device`
- `zilencer.views.unregister_all_remote_push_devices`
- `zilencer.views.remote_server_notify_push`
to make sure the previous checks for `remote_server_notify_push` matches to old one, The `RemoteServerNotificationPayload` is defined.
Fixes: 
<details>
</details>
=> zilencer: Migrate to `@typed_endpoint`.

templates/corporate/case-studies/gut-contact-case-study.md
[Reported on CZO](https://chat.zulip.org/#narrow/stream/2-general/topic/typo.20in.20case.20study/near/1782816)
=> portico: Fix typo.

requirements/common.in, requirements/dev.txt, requirements/mypy.in, requirements/prod.txt, version.py, zerver/lib/test_runner.py, zproject/computed_settings.py
- [Discussion](https://chat.zulip.org/#narrow/stream/3-backend/topic/Django.205.2E0.20Python.20compatibility/near/1706198)
- [Release notes](https://docs.djangoproject.com/en/5.0/releases/5.0/)
=> requirements: Upgrade Django to 5.0.5.dev

templates/corporate/for/research.html
Adding more detail in response to request. This specific language has been approved.
=> portico: Add more detail to title in quote.

zerver/openapi/zulip.yaml
In 5e30ab91b9b87bc912895c2f1f49c38b5424564a, we introduced `stream_id` parameter. `to` is no longer used when composing stream messages to specify the stream ID.
Earlier, `to` parameter accepted a single element list containing the ID of the stream.
Since we can't specify multiple stream IDs anymore, the example JSON error response documented is stale.
This PR updates that.
</img>
</details> 
</img>
</details> 
<details>
Completed …
=> api_docs: Fix the example JSON error response for 'POST /typing'.

web/src/message_fetch.js, web/src/message_list_data.ts, web/src/server_events.js, web/src/ui_init.js, web/tests/message_fetch.test.js, web/tests/server_events.test.js
Prep commits extracted from #29740.
=> Prep commits to enable custom caching of view.

web/src/settings_invites.ts, web/styles/dark_theme.css, web/styles/input_pill.css, web/templates/settings/admin_invites_list.hbs, web/templates/stream_settings/new_stream_user.hbs, web/templates/stream_settings/stream_member_list_entry.hbs
>GSoC'2024 Participant
_Comment posted by @alya in https://github.com/zulip/zulip/issues/29664#issuecomment-2057895713_
<details>
</details>
=> Convert links to user pill for invite section

api_docs/include/rest-endpoints.md, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_openapi.py, zerver/views/invite.py, zproject/urls.py
This PR adds the API documentation for "/invites/{prereg_id}" endpoint.
<details>
<summary>**Screenshots and screen captures:**</summary>
</details>
<details>
</details>
=> api_documentation: Document "/invites/{prereg_id}" endpoint.

api_docs/changelog.md, zerver/openapi/zulip.yaml
Changes to API feature level 254 documentation:
- Updates the changelog entry to use "ID" instead of "id".
- Revises text for "null" value to match other field descriptions in these stream/subscription objects.
<details>
<summary>API feature level updates</summary>
Our convention is to always use "ID" in API docs text, unless it's part of a name.
</details>
<details>
<summary>Updated creator_id description for objects</summary>
Note descriptions for notifications fields for the revisions made here.
</details>
---
<details> …
=> api-docs: Make small clean-ups to feature level 254 updates.

api_docs/changelog.md, zerver/openapi/zulip.yaml
Updates the API changelog entries and changes notes for feature levels 233 and 230, which both are related to the onboarding steps (hotspots and one-time notices) updates.
- Feature level 233 was originally documented in commit 83bd9955e3 and ac8af3d6de.
- Feature level 230 was originally documented in commit 8d633cc36.
---
<details>
<summary>API changelog updates</summary>
[Current documentation](https://zulip.com/api/changelog#changes-in-zulip-80)
</details>
<details>
<summary>Get events updates</summary>
[Current documentation](https://zulip.com/api/get-events#onboarding_steps)
</details>
<details>
<summary>Register queue updates</summary>
[Current documentation](https://zulip.com/api/register-queue) - search for "onboarding" on page
</details>
--- …
=> api-docs: Clean up feature level 233 and 230 documentation.

web/src/settings_profile_fields.js
Fixes #29814.
Fixes: 
<details>
<summary>Create custom profile field</summary>
</details>
<details>
<summary>Edit custom profile field</summary>
</details>
Self review checklist:
<details>
</details>
=> custom_profile_fields: Don't show display summary tooltip on `required`.

web/src/message_edit.js, web/src/stream_popover.js, web/templates/message_moved_widget_body.hbs
A confirmation toast is shown when a message is moved using the "Move only this message" option. The toast contains the link to the new location of the message.
Fixes #29702
<details>
<summary> Screenshots </summary>
</details>
<details>
</details>
Kislay U. Verma, GSOC'24 Applicant.
=> message_move: Show confirmation toast.

api_docs/deploying-bots.md, api_docs/outgoing-webhooks.md, help/delete-a-message.md, help/edit-a-message.md, help/include/invite-users.md, help/logging-in.md, help/logging-out.md, help/view-zulip-version.md, zerver/lib/markdown/help_settings_links.py
This PR updates the previously used Font Awesome icons for gear menu, invite users and pencil in the `/help` and `/api` docs to reflect the newer custom Zulip icons.
<details>
<summary><h3>Gear Icon</h3></summary>
- [help/invite-new-users](https://zulip.com/help/invite-new-users)
- [help/logging-in](https://zulip.com/help/logging-in)
- [help/logging-out](https://zulip.com/help/logging-out)
- [help/view-zulip-version](https://zulip.com/help/view-zulip-version)
- Other places referenced using `{relative/gear/..}`
- [help/analytics](https://zulip.com/help/analytics)
- [help/change-the-color-of-a-stream](https://zulip.com/help/change-the-color-of-a-stream)
- [help/message-a-stream-by-email](https://zulip.com/help/message-a-stream-by-email)
- …
=> docs: Update /help and /api docs to reflect the new icons.

web/templates/stream_settings/stream_settings.hbs
Fixes: [CZO #design](https://chat.zulip.org/#narrow/stream/101-design/topic/.22Stream.20details.22.20section.20design/near/1786390)
| ![image](https://github.com/zulip/zulip/assets/133781250/134995c0-44d9-4618-aa36-d51b8e277269) | ![image](https://github.com/zulip/zulip/assets/133781250/f27381e0-1ce7-4ed0-8bef-93ffba641d3a) |
| ![image](https://github.com/zulip/zulip/assets/133781250/7487d0e5-41e1-4e63-ac6a-82233f53154a) | ![image](https://github.com/zulip/zulip/assets/133781250/b949fb68-37bb-426d-92aa-aab14a2b90ae) | 
<details> …
=> stream_settings: Remove "Stream events" field.

puppet/zulip/files/postgresql/env-wal-g, puppet/zulip/files/postgresql/wal-g-exporter
=> wal-g: Support parameterizing the bucket which is fetched.

web/src/hash_util.ts, web/tests/hashchange.test.js
Updates hash_util.decode_operand to handle a URL with channel and the stream name and ID encoded in the URL.
For example "/#narrow/channel/12-test" where 12 is the ID of the stream named "test".
Part of stream to channel rename project.
---
| --- | --- |
| ![Screenshot from 2024-04-24 21-10-16](https://github.com/zulip/zulip/assets/63245456/d89124be-cb0b-4640-b8ca-64ceaacb52b7) | ![Screenshot from 2024-04-24 21-09-36](https://github.com/zulip/zulip/assets/63245456/27d31506-4dbb-4bec-88c7-6d92d6c91655)
| --- | --- |
| ![Screenshot from 2024-04-24 21-10-04](https://github.com/zulip/zulip/assets/63245456/528d6b83-1690-4e08-b606-aadd3d74a9ac) | ![Screenshot from 2024-04-24 …
=> hash-util: Decode URL with channel and encoded stream ID.

corporate/tests/test_stripe.py, corporate/urls.py, corporate/views/support.py, templates/corporate/support/demo_request.html, templates/corporate/support/support_request_thanks.html, templates/zerver/emails/demo_request.html, templates/zerver/emails/demo_request.subject.txt, templates/zerver/emails/demo_request.txt, web/styles/portico/portico_signin.css
This sends an email to us after user fills out and sends the form.
=> demo_request: Add form for user to request a demo.

web/src/stream_settings_ui.js, web/templates/stream_settings/first_stream_created_modal.hbs
- Not redirecting to the topic `stream events` which might not be present if the org language is not English. (It has been replaced with `channel events` in the English version anyway)
- Replaced `stream` with `channel` in the modal that appears when a stream is created for the first time.
<details>
<summary> Screenshots</summary>
</details>
<details>
</details>
=> Goto new stream but not topic `stream events`

tools/semgrep-py.yml
=> semgrep: Add linters for non-concurrent index changes.

requirements/dev.in, requirements/dev.txt, version.py
[Discussion](https://chat.zulip.org/#narrow/stream/3-backend/topic/Ubuntu.2024.2E04.20released/near/1789453).
=> requirements: Add pyasyncore, to fix pyinotify on Python 3.12

tools/semgrep-py.yml
Semgrep understands `import`s.
Cc @alexmv (#27945, #29884).
=> semgrep: Use fully qualified patterns

web/src/sidebar_ui.ts, web/src/user_search.ts, web/styles/zulip.css, web/tests/user_search.test.js
Followup from https://github.com/zulip/zulip/pull/29342#issuecomment-2021155711
=> sidebar_ui: Fix flickering of invite users button when showing sidebar.

web/src/presence.ts, zerver/actions/presence.py, zerver/lib/presence.py
Tiny, mostly self-explanatory tweaks
=> Minor tweaks in presence code

zproject/default_settings.py
=> settings: Fix a typo in a comment.

web/src/timerender.ts, web/styles/message_row.css, web/styles/zulip.css, web/tests/timerender.test.js
This PR begins the work of flattening out the message-row CSS, and better integrating straggling styles hanging out in `zulip.css`. That said, styles that provide vertically centered lines remain in `zulip.css`. Those will likely need to be decoupled and their values converted to `em` or other font-relative units to play gracefully with the coming information-density changes.
| Before | After (no visual changes) |
| --- | --- |
| ![date-sub-rows-before](https://github.com/zulip/zulip/assets/170719/9766fa14-643e-4c13-9d3b-37e8e20e18d5) | ![date-sub-rows-after](https://github.com/zulip/zulip/assets/170719/85af320c-f4e7-4a52-bde4-3feafd127ef1) |
<details>
Communicate …
=> message_row: Date-row cleanup.

web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/message_row.css
This PR simplifies and flattens the unread-marker selectors.
| --- | --- |
| ![unread-marker-light-before](https://github.com/zulip/zulip/assets/170719/12ef04ac-bbc1-4876-9f40-5192f03e4665) | ![unread-marker-light-after](https://github.com/zulip/zulip/assets/170719/6676f925-de57-4300-b9c2-3f58209e6fbe) |
| ![unread-marker-dark-before](https://github.com/zulip/zulip/assets/170719/d1b87c62-fb47-423c-9da9-caa032ad7660) | ![unread-marker-dark-after](https://github.com/zulip/zulip/assets/170719/746f96cb-94af-4d78-91b3-0c1567b58786) |
<details> …
=> message_row: Unread-marker cleanup.

zerver/lib/zulip_update_announcements.py
Waiting on feedback [on CZO](https://chat.zulip.org/#narrow/stream/438-release-management/topic/zulip_updates.20items.20of.20note/near/1789985). -> Good to go?
=> updates: Add update message (level=3).

web/templates/introduce_zulip_view_modal.hbs
Noted these two translated strings that need to be updated for the stream to channel rename while working on some help center updates. They are recent additions to the codebase and are not yet in the current web app translations.
The help center link will be updated in a separate change.
<details>
</details>
=> zulip-view-modal: Update translated strings for stream/channel rename.

web/src/input_pill.ts, web/tests/input_pill.test.js
We wrap `onTextInputHook` in a setTimeout to defer it to the next process tick so that it is ready to read the updated value of the text input field in the callback.
We need to do this because "keydown" events does not run after updating the input value but before and some of our hooks tries to read the updated value of input fields to do relevant actions for e.g our invite modal validating email regex.
Fixes: [CZO Topic](https://chat.zulip.org/#narrow/stream/6-frontend/topic/validation.20of.20invite.20emails.20lags.20one.20character.20behind)
Before:
https://github.com/zulip/zulip/assets/84276404/8dc6e933-d748-43bc-a41d-43de15e2164a
After:
https://github.com/zulip/zulip/assets/84276404/723234ea-2d10-400a-ba45-d1529c1d0424
<details> …
=> input_pill: Register `onTextInputHook` inside `input` event handler.

web/src/info_overlay.ts
Fixes: #29832  
here's the [issue](https://github.com/zulip/zulip/issues/29832) that it fixes, Just updated the "info-overlay.ts" to match the documentation in [here](https://zulip.com/help/collaborative-to-do-lists#examples), so we have a more coherent app, and better coordination between the documentation and the web app.
Before:
After:
Fixes: #29832 
<details>
</details>
=> keyboard-shortcuts: Update the to-do list example to match documentation.

docs/subsystems/billing.md
Run `./tools/build/docs` and go to http://localhost:9991/docs/subsystems/billing.html
=> billing: Document how to test different billing states.

web/src/invite.ts, web/src/settings_components.ts, web/src/types.ts
Fixes: #29909 
<details>
</details>
=> Combining HTMLSelectElement & {type: "select-one"} into HTMLSelectOneElement. 

web/src/buddy_data.ts, web/src/input_pill.ts, web/src/message_live_update.ts, web/src/message_store.ts, web/src/people.ts, web/src/settings_components.ts, web/src/settings_realm_domains.ts, web/src/settings_user_topics.ts, web/src/support/support.ts, web/tests/input_pill.test.js, web/tests/settings_realm_domains.test.js, web/tests/settings_user_topics.test.js, web/tests/support.test.js
=> Fix various implicit uses of the `any` type, part 2

web/src/message_list_view.js, web/src/message_scroll.js, web/src/message_viewport.ts
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/message.20list.20doesn't.20load.20newer.20messages.20when.20near.20end
=> Fix check for when to fetch more messages.

web/e2e-tests/realm-creation.test.ts, web/shared/src/poll_data.ts, web/src/billing/billing.ts, web/src/billing/helpers.ts, web/src/billing/sponsorship.ts, web/src/billing/upgrade.ts, web/src/channel.ts, web/src/inbox_ui.js, web/src/invite.ts, web/src/poll_modal.ts, web/src/popover_menus.ts, web/src/portico/signup.ts, web/src/reactions.ts, web/src/scroll_util.ts, web/src/settings_components.ts, web/src/settings_linkifiers.ts, web/src/stats/stats.ts, web/src/submessage.ts, web/src/ui_report.ts, web/src/unread.ts
Continuation of
- #29931
- #29946
This reduces the number of violations to 24.
=> Fix various implicit uses of the `any` type, part 3

zerver/worker/missedmessage_emails.py
```
2024-05-06 19:13:58.985 ERR  [] Exception in MissedMessage background worker; restarting the loop
2024-05-06 19:14:00.015 ERR  [] Exception in MissedMessage background worker; restarting the loop
2024-05-06 19:14:02.059 ERR  [] Exception in MissedMessage background worker; restarting the loop
2024-05-06 19:14:06.089 ERR  [] Exception in MissedMessage background worker; restarting the loop
2024-05-06 19:14:14.124 ERR  [] Exception in MissedMessage background worker; restarting the loop
2024-05-06 19:14:30.155 ERR  [] Exception in MissedMessage background worker; restarting the loop
2024-05-06 19:15:00.192 ERR  [] Exception in MissedMessage background worker; restarting the loop
```
<details> …
=> missedmessage_emails: Backoff the background worker retries.

web/src/bootstrap_typeahead.ts, web/src/composebox_typeahead.js, web/src/custom_profile_fields_ui.js, web/src/message_edit_history.ts, web/src/pill_typeahead.ts, web/src/portico/header.ts, web/src/search.ts, web/src/settings_playgrounds.ts, web/styles/portico/hello.css, web/tests/composebox_typeahead.test.js, web/tests/pill_typeahead.test.js, web/tests/search.test.js
Continuation of
- #29931
- #29946
- #29955
This reduces the number of violations to 7.
=> Fix various implicit uses of the `any` type, part 4

web/src/rendered_markdown.ts, web/tests/rendered_markdown.test.js
This pr fixes code getting copied even when `View in xxx playground` is clicked.
Fixes: #29844.
| ---- | ---- |
| ![Animation10](https://github.com/zulip/zulip/assets/91622060/7c35d9d4-24ef-493c-9ec9-848336eb0880) | ![Animation11](https://github.com/zulip/zulip/assets/91622060/59fc4266-4e77-4a40-a844-0f9326e3dd9e) | 
<details>
</details>
=> rendered_markdown: Fix code getting copied when visiting custom playground.

.eslintrc.json, web/src/compose_setup.js, web/src/compose_ui.ts, web/src/drafts.ts, web/src/emoji_picker.js
Finale of
- #29931
- #29946
- #29955
- #29973
=> Fix various implicit uses of the `any` type, part 5

web/src/user_profile.js, web/styles/dark_theme.css, web/styles/modal.css, web/styles/popovers.css, web/templates/user_profile_modal.hbs
**The PR is made as per the [discussion on #CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/Copy.20link.20to.20profile)**
This PR includes the following changes:
- Updates the font-awesome "edit" icon and "copy-link" icon found in the user profile modal with the corresponding zulip icons.
- Adds a help center page to document the "copy link to profile" feature.
**Light Mode**
**Dark Mode**
**Help-center Page**
<details> …
=> user_profile_modal: Updates "edit" icon and "copy link" icon of user profile modal.

templates/corporate/case-studies/asciidoctor-case-study.md, templates/corporate/case-studies/atolio-case-study.md, templates/corporate/case-studies/end-point-case-study.md, templates/corporate/case-studies/gut-contact-case-study.md, templates/corporate/case-studies/recurse-center-case-study.md, templates/corporate/case-studies/semsee-case-study.md, templates/corporate/case-studies/tum-case-study.md, templates/corporate/comparison_table_integrated.html, templates/corporate/development-community.html, templates/corporate/development-community.md, templates/corporate/for/business.html, templates/corporate/for/communities.md, templates/corporate/for/education.html, templates/corporate/for/events.html, templates/corporate/for/open-source.html, templates/corporate/for/research.html, templates/corporate/history.md, templates/corporate/policies/privacy.md, templates/corporate/policies/terms.md, templates/corporate/security.md, templates/corporate/try-zulip-part2.md, templates/corporate/why-zulip.md, templates/corporate/zephyr.html
This PR renames `stream`->`channel` across templates/corporate. Each case study's renaming is done as a separate commit to ease the review process and accelerate the request approval for changing the quote. Similar separation is maintained across multiple commits to allow sensible reverts/changes wherever required.
This PR does not contain the `stream`->`channel` renaming for the `https://chat.zulip.org/#narrow/stream/` links, as those require more attention since mobile doesn't support that URL format yet.
<details> …
=> Rename stream->channel across templates/corporate.

web/styles/reactions.css, web/styles/zulip.css
=> 8.x backport of 28920

puppet/zulip/templates/supervisor/zulip-once.conf.template.erb, puppet/zulip/templates/supervisor/zulip.conf.template.erb, tools/backport-pull-request, tools/release, web/src/pm_list.js, web/src/settings_invites.ts, web/src/views_util.js, web/styles/inbox.css, web/templates/inbox_view/inbox_row.hbs, web/templates/settings/invites_list_admin.hbs, zerver/lib/import_realm.py, zerver/lib/push_notifications.py, zerver/lib/rate_limiter.py, zerver/lib/redis_utils.py, zerver/lib/remote_server.py, zerver/lib/test_classes.py, zerver/management/commands/register_server.py, zerver/tests/test_push_notifications.py, zerver/webhooks/alertmanager/tests.py, zerver/webhooks/alertmanager/view.py
Backports PRs which apply cleanly:
- #29972
- #27259
~- #28998~ (removed by tabbott)
- #29178
- #29299 (added by tabbott)
- #29326
- #29359
- #29405
- #29424
- #29456
- #29608
- #29801
<details>
</details>
=> 8.x backports

web/src/copy_and_paste.js, web/src/rendered_markdown.js, web/src/ui_util.ts, web/tests/notifications.test.js, web/tests/rendered_markdown.test.js
=> 8.x backport of 29601

zerver/actions/message_flags.py, zerver/lib/markdown/__init__.py, zerver/lib/test_classes.py, zerver/lib/test_helpers.py, zerver/lib/timeout.py, zerver/tests/test_markdown.py, zerver/tests/test_message_flags.py, zerver/tests/test_message_topics.py, zerver/tests/test_timeout.py, zerver/views/message_flags.py, zerver/views/streams.py
=> 8.x backport of 29782

docs/production/postgresql.md
This just missed being tacked onto #30000
=> docs: Update for wal-g not being required for replication.

docs/production/deployment.md, docs/production/export-and-import.md, docs/production/postgresql.md, docs/production/requirements.md, docs/production/system-configuration.md
=> 8.x backport postgres docs

puppet/kandra/manifests/prod_app_frontend_once.pp, puppet/kandra/manifests/profile/staging_app_frontend.pp, puppet/zulip/manifests/cron.pp
This went undetected because the clause is only used on kandra hosts.
Fixes: 
<details>
</details>
=> kandra: Fix puppet errors.

templates/corporate/for/open-source.html, templates/corporate/for/research.html
This change has been approved by Kevin.
Current: https://zulip.com/for/research/
Updated:
=> portico: Tweak quote.

web/src/message_fetch.js
We do a rough check on date of the latest message to check if it is near the near the day till which we want to fetch.
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/fetching.20message.20history/near/1793200
=> message_fetch: Fetch till 180 days of history or we reach backfill cap.

templates/corporate/comparison_table_integrated.html
The plan overview already has the correct info.
=> portico: Update features table to reflect current storage policy.

web/src/compose_recipient.js, web/src/compose_validate.js, web/src/people.ts, zerver/actions/message_send.py, zerver/tests/test_message_send.py
=> 8.x backport of 28477

web/src/unread_ops.js
Use the `/json/messages/flags` instead of `/json/messages/flags/narrow` when we have fully fetched the current view.
Update messages on the basis of id instead of updating the entire narrow.
If `message_lists.current.data.fetch_status.has_found_newest()`, then filter all the message ids on the basis of the anchor and only update those messages.
Fixes #28945.
<details>
</details>
=> mark unread: Use more efficient endpoint.

zerver/migrations/0516_fix_confirmation_preregistrationusers.py
We update the existing migration, because any deployment which had invitations with non-default streams in this state cannot have proceeded past this migration yet.
=> migrations: Update 0516 to handle invites with non-default streams.

help/linking-to-zulip-website.md
Current: https://github.com/alya/zulip/pull/new/linking
Updated:
=> help: Update suggested text for linking to Zulip.

tools/lib/capitalization.py, web/e2e-tests/message-basics.test.ts, zerver/actions/create_realm.py, zerver/actions/create_user.py, zerver/lib/onboarding.py, zerver/models/realms.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_audit_log.py, zerver/tests/test_digest.py, zerver/tests/test_event_system.py, zerver/tests/test_events.py, zerver/tests/test_home.py, zerver/tests/test_import_export.py, zerver/tests/test_invite.py, zerver/tests/test_message_fetch.py, zerver/tests/test_new_users.py, zerver/tests/test_realm.py, zerver/tests/test_signup.py, zerver/tests/test_subs.py, zerver/tests/test_users.py, zilencer/management/commands/populate_db.py
* Commit 1,2,3 : Improvements I found while working on this PR
* Commit 3: Remove "core team" stream
* Commit 4: Mark stream name. description & topic names for translation.
* Commit 5: Fixes #29297
<details><summary>general</summary>
</img>
</details> 
<details><summary>Zulip</summary>
</img>
</details> 
<details><summary>sandbox</summary>
</img>
</details> 
---
<details>
</details>
=> onboarding: Replace stream messages in new organizations.

web/src/unread_ops.js
When the request to mark a thread as unread fails, we should use the
value of include_anchor that was sent in the request, not false.
Modified handle_mark_unread_from_here_error to take an object instead of
parameters.
As mentioned in [#29521 (comment)](https://github.com/zulip/zulip/pull/29521#discussion_r1594430934) .
=> mark unread: Use correct value of include_anchor in case of errors.

web/src/buddy_list.ts
=> buddy_list: Fix empty_list_widget_for_list.hbs usage

tools/test-js-with-node, web/src/compose_closed_ui.js, web/src/compose_closed_ui.ts, web/src/message_helper.js, web/src/message_list_view.js, web/src/message_lists.ts, web/src/message_store.ts, web/src/people.ts, web/tests/message_store.test.js
I took a stab at finishing up #29708, but there's a sticky issue to fix. I'd like to clean up some of this code if it isn't too hard, and am curious if anyone has more context on what a good fix would look like.
=> compose_closed_ui: Migrate module to TypeScript.

templates/corporate/for/research.html
Current: https://zulip.com/for/research/
I confirmed with `grep` that there are no other pages to update. Making an update was approved by Stelios.
=> portico: Update title/job for quote author.

web/src/stream_pill.ts, web/src/user_group_pill.ts, web/src/user_pill.ts
- Mostly introduced by #29823, cc @afeefuddin
=> stream_pill, user_group_pill, user_pill: Avoid unnecessary array allocations

tools/test-js-with-node, web/src/message_lists.ts, web/src/unread_ops.js, web/src/unread_ops.ts
Fixes
- https://github.com/zulip/zulip/pull/23605#pullrequestreview-2055969079
- https://github.com/zulip/zulip/pull/28560#pullrequestreview-2056072495
- https://github.com/zulip/zulip/pull/29521#pullrequestreview-2055957393
=> unread_ops: Fix `do_mark_unread_by_narrow` arguments, convert module to TypeScript

tools/test-js-with-node, web/src/message_lists.ts, web/src/user_topics.ts, web/src/user_topics_ui.js, web/src/user_topics_ui.ts
Fixes
- https://github.com/zulip/zulip/pull/27254#pullrequestreview-2056268030
=> user_topics_ui: Fix backwards setTimeout arguments, convert module to TypeScript

help/include/send-dm.md
Current: https://zulip.com/help/starting-a-new-direct-message and other pages
<details>
<summary>
Updated
</summary>
</details>
=> help: Document that groups can be DM addressees.

zerver/tests/test_message_move_topic.py, zerver/tests/test_realm.py
- First commit is to improve the tests for `video_chat_provider` and `jitsi_server_url` settings.
- Second commit is to remove `set_up_db` calls.
- Third commit is to not have multiple `assert_has_visibility_policy` functions. [Discussion](https://github.com/zulip/zulip/pull/25508#discussion_r1191590930)
Fixes:  https://github.com/zulip/zulip/pull/14639#issuecomment-621529750
<details>
</details>
=> tests: Refactor tests in `test_realm` in `test_message_move_topic`.

web/styles/popovers.css
In this commit, I fixed the 'word-break: break-all' for profile fields in popovers.css to 'overflow-wrap: break-word which allows long words to break and wrap onto the next line if they exceed the width. Also, this works on all browsers (Safari included). While testing my implementation, I noticed that the word for Email was not in Russian like it was before, so I implemented it back to Russian instead of English in translation.json.
Fixes: #22865
Before: 
After: 
<details> …
=> popovers: Refine word wrapping in user profile.

web/src/stream_edit.js, web/tests/stream_settings_ui.test.js
- Added event of scroll to stream_edit.js file for when scrolling through container Fixes #17451
Fixes: https://github.com/zulip/zulip/issues/17451 
<details>
</details>
=> settings: fixed colorpicker so it closes when scrolling stream settings

web/src/buddy_data.ts, web/src/people.ts, web/src/recent_view_ui.ts, web/tests/people.test.js, web/tests/recent_view.test.js
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/DMs.20match.20all.20search.20filters.20in.20Recent.20conversations
=> Fix search for dms not working in recent view.

web/src/message_list_view.js
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Message.20edit.20box.20loses.20focus
=> Fix edit box losing focus on editing immediately a sent message.

web/src/typeahead_helper.ts
Followup for
https://github.com/zulip/zulip/pull/29650/files#r1569209419
=> typeahead_helper: Clean up current_stream check.

zerver/lib/import_realm.py
Fixes: https://github.com/zulip/zulip/issues/29350
Before importing messages : 
1.  Read attachments file earlier (without importing attachments themselves) which contains each attachment mapped to its related `messages ids` and `scheduled_messages ids`.
2. Map each `message_id` to it related attachments.
3. As a result in `fix_upload_links()` each message can access directly its attachments without searching for them in all existing attachments.
The Time complexity is reduced From:  
**`O(No.messages_with_attachments x No.all_attachments)`** 
To
**`O(No.messages_with_attachments x No.attachments/message)`**
which is a great improvment, also because a single message typically has a few attachments.
=> Improve fix_upload_links performance

tools/test-js-with-node, web/src/settings_components.ts, web/src/settings_org.js, web/src/settings_profile_fields.js, web/src/settings_profile_fields.ts, web/src/settings_streams.js, web/src/state_data.ts, web/src/stream_edit.js, web/src/types.ts, web/src/user_group_edit.js, web/tests/settings_profile_fields.test.js
=> settings_profile_field: Convert Module to TypeScript.

web/src/settings_components.ts
Fixes: [Comment](https://github.com/zulip/zulip/pull/30018#discussion_r1607108893)
<details>
</details>
=> settings_components: Rename subsection to $subsection_elem.

help/self-hosted-billing.md, help/zulip-cloud-billing.md, templates/corporate/for/education.html
Current: https://zulip.com/for/education/#feature-pricing
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/zulip-cloud-billing#free-and-discounted-zulip-cloud-standard
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/self-hosted-billing#education-pricing
<details>
<summary>
Updated
</summary>
</details>
=> portico and help: Improve documentation on education pricing.

web/src/compose_popovers.js
Introduced by 2014c25cb4d2cbe3684b5beb2c66e18588729bdd (#29610).
=> compose_popovers: Fix message_type typo

zerver/lib/zulip_update_announcements.py
[CZO discussion](https://chat.zulip.org/#narrow/stream/438-release-management/topic/zulip_updates.20items.20of.20note/near/1798501) ongoing.
=> [WIP] updates: Add update about stream->channel rename and faster loading.

web/src/settings_profile_fields.ts
Introduced in #30018 
<details>
</details>
=> settings_profile_field: Fix class selector.

zerver/actions/create_realm.py, zerver/actions/uploads.py, zerver/lib/upload/__init__.py, zerver/lib/user_topics.py, zerver/tests/test_import_export.py
* First two commits: See commit messages.
* Third commit: For the same logic mentioned in https://github.com/zulip/zulip/pull/30101#discussion_r1606282187
<details>
</details>
=> bug_fixes: Tiny improvements and bug fixes.

web/src/settings_components.ts, web/src/settings_notifications.js, web/src/settings_org.js, web/templates/settings/language_selection_widget.hbs, web/templates/settings/organization_permissions_admin.hbs
- First commit is to fix user email notification batching setting.
- Second commit is to fix updating the realm default language setting.
- Thrid commit is to fix updating the realm joining restrictions setting.
<details>
</details>
=> Fix bugs in settings due to recent typescript migrations.

corporate/lib/support.py, corporate/tests/test_support_views.py, templates/corporate/support/current_plan_details.html
Adds a link to the stripe customer dashboard if the `Customer` object for an active plan has a `stripe_customer_id`. If there is no stripe ID to link to, then the icon is shown without a link, which is the case for remote server/realm sponsorships and legacy plans.
<details>
<summary>Example of a plan without a stripe ID</summary>
</details>
<details>
<summary>Example of a plan with a stripe ID</summary>
</details>
---
<details> …
=> support: Add link to stripe customer dashboard.

zerver/actions/create_user.py
This PR fixes comment about subscribing to default streams in `set_up_streams_for_new_human_user`
to explain the logic after changes in 69ba580a5435.
Fixes:  https://github.com/zulip/zulip/pull/25739#discussion_r1608549463
<details>
</details>
=> create_user: Fix comment in set_up_streams_for_new_human_user.

web/src/narrow.js
This commit extracts the method to create and update message lists in the narrow. This is particularly useful in cases when we need to update the narrow and view with our own message lists.
This is a preparatory commit to #30114, since it involves creating a new message list from the messages fetched, which may be of a different narrow from that of the initial filter, and updating the view and narrow with it.
Prep commit to [review comment](https://github.com/zulip/zulip/pull/30114#discussion_r1607386873).
<details> …
=> refactor: Extract method to create and update message lists in narrow.

web/src/invite.ts
The default streams checkbox only exists in DOM if there are default channels in the realm, so we should make sure that we check whether there are default streams in the realm before accessing the checkbox element in set_streams_to_join_visibility.
<details>
</details>
=> invite: Fix rendering invite modal for realms without default channels.

zerver/lib/markdown/__init__.py
requests transforms the base urllib3 exceptions into requests.RequestExceptions -- but only within code that it is running.  When parsing the streaming body in fetch_open_graph_image, the read itself (inside lxml) may trigger urllib3 to raise its own timeout error -- which escapes the current catch of requests.RequestExceptions.
Catch both requests and urllib3 exceptions.
Fixes: 
<details>
</details>
=> markdown: Catch urllib3 exceptions which are raised during streaming.

tools/test-js-with-node, web/src/muted_users.ts, web/src/muted_users_ui.ts
=> muted_users_ui: Convert module to TypeScript.

web/src/invite.ts, web/styles/zulip.css
- First commit is to fix the invite button state when opening the modal.
- Second commit is to remove unnecessary calls of `toggle_invite_submit_button`.
- Third commit is to remove some unused code in JS and CSS.
- Fourth commit is to fix a comment.
<details>
</details>
=> invite: Fix bugs and remove unused code.

web/src/browser_history.ts, web/src/hashchange.js, web/src/narrow.js, web/src/narrow_history.ts, web/src/stream_list.ts, web/tests/narrow_activate.test.js
 When navigating "back" or "forward", the left sidebar state should be restored.
Earlier, "more topics" expanded was not considered a distinct state.
This PR makes it possible to correctly place you in the "more topics" view or not, depending on where you were.
Fixes: #29548.
<details>
</details>
=> narrow: Add 'more topics' state to browser history.

templates/corporate/for/communities.html
Current page: https://zulip.com/for/communities/
<details>
<summary>
Screenshots (top and bottom of page, wide and narrow)
</summary>
</details>
=> portico: Link to sponsorship policies from /for/communities page.

help/gdpr-compliance.md
Current: https://zulip.com/help/gdpr-compliance#how-zulip-supports-gdpr-compliance
<details>
<summary>
Updated
</summary>
</details>
=> help: Link to Data Processing Addendum (DPA) from GDPR help page.

templates/corporate/billing/upgrade.html
| --- | --- |
| <img width="785" alt="Screenshot 2024-05-30 at 5 54 49 PM" src="https://github.com/zulip/zulip/assets/25124304/df956ab7-3397-4917-b930-97bb11496fd4"> | <img width="785" alt="Screenshot 2024-05-30 at 5 54 38 PM" src="https://github.com/zulip/zulip/assets/25124304/22ea5cc1-de26-41ca-b8a2-b7db6bf4fdc4"> |
=> upgrade: Inform customer that fixed price plan will not auto-renew.

zerver/lib/zulip_update_announcements.py, zerver/tests/test_zulip_update_announcements.py
Fixes the error catched by sentry:
```
AssertionError: null
File "zerver/lib/zulip_update_announcements.py", line 230, in send_zulip_update_announcements
send_zulip_update_announcements_to_realm(realm, skip_delay)
File "zerver/lib/zulip_update_announcements.py", line 269, in send_zulip_update_announcements_to_realm
if not is_group_direct_message_sent_to_admins_within_days(realm, days=7):
File "zerver/lib/zulip_update_announcements.py", line 170, in is_group_direct_message_sent_to_admins_within_days
assert level_none_to_zero_auditlog is not None
```
<details> …
=> zulip_updates: Fix assertion error while sending update messages.

web/src/narrow.js, zerver/openapi/zulip.yaml
Commit 1: Extracts some methods of `narrow.js` into a separate method as a preaparatory refactor of #30114.
Commit 2: Preparatory change as suggested in [review comment.](https://github.com/zulip/zulip/pull/30114#discussion_r1617685978) 
<details>
</details>
=> Preparatory commits to #30114

tools/droplets/README.md, tools/droplets/create.py
=> Droplet updates

puppet/kandra/templates/supervisor/conf.d/prometheus_process_exporter.conf.template.erb, puppet/zulip/manifests/common.pp
=> Infra upgrades

tools/test-js-with-node, web/src/dialog_widget.ts, web/src/settings_streams.ts
=> settings_streams: Convert module to TypeScript.

scripts/setup/configure-rabbitmq, zerver/lib/queue.py, zproject/default_settings.py, zproject/prod_settings_template.py
Fixes #30255.
<details>
</details>
=> Support vhosts in rabbitmq

zerver/lib/narrow.py, zerver/models/messages.py, zerver/tests/test_message_fetch.py
Previously, when the operand of id operator was more than 2147483647, it was raising server error. This is because the maximum permissible PostgreSQL integers value is 2147483647.
This is fixed by raising a BadNarrowOperatorError in case the id operand is larger than 2147483647.
https://chat.zulip.org/#narrow/stream/378-api-design/topic/topic.20permalinks/near/1810055
<details>
</details>
=> narrow: Fix server error of operand of "id" operator at large values.

tools/test-js-with-node, web/src/compose_call_ui.ts, web/src/state_data.ts, web/src/ui_report.ts, web/tests/compose_video.test.js
=> compose_call_ui: Convert module to TypeScript.

api_docs/group-setting-values.md, zerver/lib/user_groups.py, zerver/tests/test_user_groups.py, zerver/views/user_groups.py, zproject/default_settings.py, zproject/dev_settings.py, zproject/test_extra_settings.py
This PR adds a server level setting which controls whether the setting can
be set to anonymous user groups. We only allow it in the tests for now because
the UI can only handle named user groups.
Discussion - https://chat.zulip.org/#narrow/stream/378-api-design/topic/managing.20resolve.20topic.20permissions.20independently/near/1809310
<details>
</details>
=> user_groups: Add server level setting disallow anonymous groups for settings

tools/lib/capitalization.py, tools/screenshots/message-screenshot.js, tools/screenshots/thread-screenshot.js, web/src/demo_organizations_ui.js, web/src/integration_url_modal.ts, web/src/popover_menus_data.js, web/src/settings_bots.js, web/src/state_data.ts, web/src/topic_popover.js, web/src/ui_init.js, web/src/user_deactivation_ui.ts, web/tests/settings_bots.test.js, zerver/lib/markdown/__init__.py, zerver/lib/push_notifications.py, zerver/views/auth.py, zerver/views/development/dev_login.py
In #23380, @timabbott talked about replacing deprecated URI abbreviation with URL in order to follow web standards.
This PR focuses on replacing URI abbreviations related to the realm. It rebases the original work done in #25141 by resolving merge conflicts to make it mergeable.
- #29976 - Replaced occurrences of `uri` with `url` in models files.
- #30022 - Added an alias `realm_url` and deprecated `realm_uri` in the API.
- #30029 - Replaced `realm_uri` with `realm_url` in templates.
This PR replaces the remaining occurrences of `realm_uri` with `realm_url`.
<details> …
=> realm: Replace occurrences of URI with URL.

analytics/lib/counts.py, analytics/migrations/0018_remove_usercount_active_users_audit.py, analytics/migrations/0019_remove_unused_counts.py, analytics/tests/test_counts.py, docs/subsystems/analytics.md, zerver/actions/create_user.py, zerver/actions/users.py, zerver/migrations/0528_realmauditlog_zerver_realmauditlog_user_activations_idx.py, zerver/models/realm_audit_logs.py, zerver/tests/test_push_notifications.py, zerver/tests/test_signup.py, zerver/tests/test_users.py, zilencer/migrations/0061_clean_count_tables.py, zilencer/views.py
=> Stop storing unused analytics data

web/src/message_helper.ts, web/src/message_store.ts, web/tests/echo.test.js, web/tests/message_store.test.js
=> messages: Rename convert_raw_message_to_message_with_booleans.

tools/i18n/unescape-contents, tools/i18n/update-for-legacy-translations
Quick fix for issue with unescaping json data contents and then normalizing for NFC; see [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/438-release-management/topic/translations/near/1814003).
**Updates**:
- Adds a print statement to `tools/i18n/update-for-legacy-translations` to help with debugging if an error is raised for a particular locale/file.
- Updates `tools/i18n/unescape-contents` to write a newline at the end of the file when unescaping the json data contents.
Manually tested these updates with `tools/i18n/sync-translations` in local dev environment. The error reported on CZO was resolved and the tool was able to successfully complete updating the translation files.
---
<details> …
=> i18n: Add newline to json translation files when updating data contents.

package.json, pnpm-lock.yaml, tools/test-js-with-node, version.py, web/src/base_page_params.ts, web/src/settings_config.ts, web/src/settings_preferences.js, web/src/settings_preferences.ts, web/src/settings_ui.ts
=> settings_preferences: Convert module to TypeScript.

help/include/left-sidebar-conversations.md, tools/lib/capitalization.py, web/src/topic_list_data.ts, web/templates/more_topics.hbs, web/tests/topic_list_data.test.js, zerver/models/streams.py, zerver/openapi/zulip.yaml, zilencer/management/commands/populate_db.py
This PR replaces the occurrences of "more topics" to "show all topics" in the UI, comments and documentation.
Fixes #30014
<details>
</details>
<details>
</details>
=> left_sidebar: Rename "more topics" to "show all topics"

scripts/nagios/check-rabbitmq-consumers
=> check-rabbitmq-consumers: Add missing f on format string.

web/templates/popovers/message_actions_popover.hbs
In the spectator view, we are only left with the last few options belonging to the same group, and the separator is not needed.
| ![image](https://github.com/zulip/zulip/assets/82862779/50d43df9-9af9-48e8-9d9e-44aa4cc7d49d) | ![image](https://github.com/zulip/zulip/assets/82862779/db536fbc-1dec-4670-bd22-fdd1455eaadc) | 
<details>
</details>
=> message_actions_popover: Hide extra separator in spectator view.

tools/test-js-with-node, web/src/message_lists.ts, web/src/navigate.ts
=> navigate: Convert module to TypeScript.

web/src/copy_and_paste.ts
copy_and_paste: Let uppy handle pasted single images.
This fixes the bug where an image copied from sites like Twitter / X did not paste as expected.
copy_and_paste: Extract function `is_single_element` for reuse.
This is a prep commit for the next which will introduce a function that also calls `is_single_element`.
Fixes: [CZO issue report](https://chat.zulip.org/#narrow/stream/101-design/topic/pasting.20HTML.20into.20compose/near/1807726)
Note, when multiple images are pasted (not uploaded / drag and dropped) with or without any text, they don't go through uppy and the external links is retained for each.
<details> …
=> copy_and_paste: Let uppy handle pasted single images.

web/src/overlays.ts
We blur the last focused element when an overlay opens, and refocus it when the overlay is closed, to prevent side effects.
What motivated this change was that opening a lightbox overlay from preview content while editing a message caused the escape key to close the message edit form instead of closing the overlay. The overlay would close on pressing the escape key
for the second time.
[CZO report](https://chat.zulip.org/#narrow/stream/6-frontend/topic/incorrect.20escape.20behaviour)
<details>
Completed …
=> overlay: Blur focused element while overlay is open.

web/src/list_widget.ts, web/tests/lib/index.js, web/tests/list_widget.test.js
- https://github.com/zulip/zulip/pull/30134#discussion_r1631471821
=> list_widget: Reduce TypeScript wreckage

api_docs/changelog.md, api_docs/include/rest-endpoints.md, zerver/openapi/openapi.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_openapi.py
This PR adds API documentation for `/users/me/presence` endpoint.
<details>
<summary>Screenshots and screen captures:</summary>
</details>
<details>
</details>
=> api_docs: Document "/users/me/presence" endpoint.

.eslintrc.js, package.json, pnpm-lock.yaml, templates/zerver/app/index.html, version.py, web/src/billing/helpers.ts, web/src/billing/sponsorship.ts, web/src/browser_history.ts, web/src/hashchange.js, web/src/message_view.js, web/src/people.ts, web/src/portico/dev-login.ts, web/src/portico/landing-page.js, web/src/reload_setup.js, web/src/sentry.ts, web/src/settings_toggle.js
This would have caught the problem fixed in 6d30e3e01cf763c095983eb91dbc74781c29c7a9 (#29155).
=> eslint: Enable no-restricted-globals with confusing-browser-globals

help/include/sidebar_index.md, help/introduction-to-topics.md
=> help: Make introduction to topics easier to navigate.

web/e2e-tests/message-basics.test.ts
[CZO test failure](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/main.20failing/near/1818968)
<details>
</details>
=> message_basic_tests: Fix flaky behavior on sending multiple messages.

help/channel-permissions.md
Small fix for the spacing of this chart in the markdown file, which is from the stream to channel rename documentation changes in commit 5342d4ecfbf.
---
<details>
</details>
=> help: Fix private channel permissions chart spacing.

api_docs/include/rest-endpoints.md, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_openapi.py, zerver/views/invite.py, zproject/urls.py
This PR adds API documentation for "/invites/{invite_id}/resend" endpoint.
<details>
<summary>**Screenshots and screen captures:**</summary>
</details>
<details>
</details>
=> api_docs: Document "/invites/{invite_id}/resend" endpoint.

help/resolve-a-topic.md
Before: https://zulip.com/help/resolve-a-topic#mark-a-topic-as-unresolved
After:
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/closing.2Fsolving.20a.20topic.20.28.2311154.29/near/1821361)
=> help: Document grace period for unresolving topics.

web/src/settings_components.ts, web/src/settings_org.js, web/src/stream_edit.js, web/src/user_group_components.ts, web/tests/settings_org.test.js
- First commit is to use a single function to set dropdown widget variables.
- Second commit is to extract a function for setting up the dropdown widgets.
<details>
</details>
=> Refactor code to handle dropdown widgets in organization settings.

web/styles/portico/portico.css, zerver/lib/markdown/api_return_values_table_generator.py
This PR is a follow-up of #30105 that improves the events table and fixes the inconsistent event titles.
<details>
<summary>**Screenshots and screen captures:**</summary>
</details>
<details>
</details>
=> api_docs: Improve events table and fix font style of events title.

help/change-organization-url.md, help/include/automatic-billing.md, help/include/import-how-users-will-log-in.md, help/include/legacy-log-in.md, help/include/manage-billing-intro.md, help/include/manual-add-license-instructions.md, help/include/manual-billing-intro.md, help/include/pay-by-invoice-steps.md, help/include/payment-options.md, help/include/plan-upgrade-steps.md, help/include/self-hosted-billing-log-in-step.md, help/include/self-hosted-billing-multiple-organizations.md, help/include/self-hosted-log-in.md, help/include/send-us-info.md, help/self-hosted-billing.md, help/zulip-cloud-billing.md, templates/corporate/billing/billing.html, templates/corporate/billing/upgrade.html, zerver/lib/markdown/tabbed_sections.py
Updates both self-hosted and Zulip Cloud billing articles in the help center for recent updates and features.
**Prep commits**:
- Updates all instances of "e-mail" in help center to instead be "email", which is much more widely used in the help center docs.
- Updates "automatic billing" and "manual billing" to instead by "automatic license management" and "manual license management" as this is how we refer to the on the billing/upgrade pages.
**Current updates**:
- [Self-hosted billing article](https://zulip.com/help/self-hosted-billing):
- Creates an initial instruction set for logging in to the billing management pages, which is then referenced in all other instructions on the page. This is so that we can use separate tabs for the two types of payment: by card and by invoice.
- Creates …
=> help: Update billing articles for updated features.

zerver/openapi/zulip.yaml
Updates these descriptions to better fit current API documentation conventions.
**Notes**:
- The `services` array (for bots) is currently not completely rendered in the documentation, but #30375 is working on fixing that so getting that text into a better state seems useful.
**Screenshots from [register response](https://zulip.com/api/register-queue):**
| --- | --- |
| ![Screenshot from 2024-06-14 12-07-08](https://github.com/zulip/zulip/assets/63245456/3344d31f-3e4f-43bd-a594-14a86819f014) | ![Screenshot from 2024-06-14 12-06-53](https://github.com/zulip/zulip/assets/63245456/d73655fe-06df-4087-a065-895c472a07a9)
| --- | --- |
| ![Screenshot from 2024-06-14 12-15-01](https://github.com/zulip/zulip/assets/63245456/53720663-2cad-4520-84b0-dde0a132bd01) …
=> api-docs: Revise the "services" array and "config" object for bots.

web/styles/recent_view.css
This PR makes needed adjustments for the Recent conversation view to work with user-adjustable information density. It also includes some cleanup and alignment tweaks.
Fixes part of #30359.
| Legacy, before | Legacy, after |
| --- | --- |
| ![recent-view-legacy-before](https://github.com/zulip/zulip/assets/170719/22f733c9-de41-4240-8e34-3f17f4822887) | ![recent-view-legacy-after](https://github.com/zulip/zulip/assets/170719/4064db05-1355-4e86-89c1-72338ec4540c) |
| 16/140, before | 16/140, after |
| --- | --- |
| ![recent-view-16-140-before](https://github.com/zulip/zulip/assets/170719/df670e3b-c951-4855-800b-1393747a0aef) | ![recent-view-16-140-after](https://github.com/zulip/zulip/assets/170719/4d89b7a7-918c-4859-93e7-313b7a3fa521) |
<details> …
=> recent_view: Adjust alignment and sizing for info density.

web/styles/settings.css
This PR overrides a hard-coded width of 200px on the organization profile preview button, and properly describes a flex (not inline-flex) layout for it.
Fixes part of #30359
| --- | --- |
| ![org-profile-preview-before](https://github.com/zulip/zulip/assets/170719/047ee20c-bbf6-49d6-a6f1-ddf6e282d256) | ![org-profile-preview-after](https://github.com/zulip/zulip/assets/170719/db06beec-735d-44d4-939c-1fa1859a92d1) |
| ![org-profile-preview-16:140-before](https://github.com/zulip/zulip/assets/170719/7fec5315-b7ea-4948-825d-2ea740900654) | ![org-profile-preview-16:140-after](https://github.com/zulip/zulip/assets/170719/06e37063-4804-4982-aaba-9c9e1b8cfb8d) |
<details> …
=> org_settings: Improve organization preview button layout.

web/src/settings_components.ts, web/src/settings_data.ts, web/styles/dark_theme.css, web/styles/settings.css, web/tests/buddy_data.test.js, web/tests/composebox_typeahead.test.js, web/tests/dispatch.test.js, web/tests/hashchange.test.js, web/tests/message_store.test.js, web/tests/message_view.test.js, web/tests/pm_list_data.test.js, web/tests/poll_widget.test.js, web/tests/presence.test.js, web/tests/recent_view.test.js, web/tests/rendered_markdown.test.js, web/tests/settings_data.test.js, web/tests/stream_data.test.js
- First commit is to fix the styling bug.
- Second commit is a small refactor in CSS.
- Third commit is to refactor the dropdown widget code as discussed in https://github.com/zulip/zulip/pull/30386#discussion_r1635357757
<details>
</details>
=> Fix styling bug in public channel creation setting in dark theme.

web/tests/markdown.test.js, zerver/lib/push_notifications.py, zerver/tests/fixtures/markdown_test_cases.json
To make better use of the limited characters in mobile push notifications for messages quoting another message, we compress the blockquotes and "user said" paragraphs to make space for the actual message.
Fixes #28951.
<details>
</details>
=> push_notifications: Compress blockquotes when replying to a message.

web/src/sidebar_ui.ts, web/styles/right_sidebar.css, web/templates/right_sidebar.hbs
This PR removes the realm rendered description from the right sidebar for spectators.
Fixes: #30322 
<details>
</details>
=> right_sidebar: Remove realm description for spectators.

zerver/actions/presence.py, zerver/tests/test_presence.py
This was discussed in the review of #29999:
https://github.com/zulip/zulip/pull/29999#discussion_r1620818568
The previous way of handling wasn't entirely correct, as unnecessary events were omitted, with a bad guarantee of even being in the correct order.
This is an improvement as now the function detects that it ended up doing nothing and can skip sending an event.
The race condition is hard to make up in an automated test, so the test this commit adds is pretty weak, but possibly the best we can reasonably do here. Aside of that, the actual race was simulated in manual testing to verify the expected behavior.
=> presence: Improve INSERT conflict handling in do_update_user_presence.

web/src/resize_handler.ts
The URL bar in iOS shrinks / expands on scrolling causing change in height. This triggers our resize handler and forces user to jump to the selected message. This jump triggers before our keep pointer in view logic kicks in which means user scrolls back to the previous selected message instead of scrolling forward.
To fix this, we only do this jump when width changes on mobile devices.
Note that modern devices support resizeable windows of all forms but for most use cases where app is full expanded, this seems like the right fix.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/scrolling.20in.20Firefox.20mobile
=> resize_handler: Fix scroll jumps on iOS.

zerver/lib/user_topics.py
See #26461
I followed a slightly different approach from what @alexmv [suggested](https://github.com/zulip/zulip/pull/26461#issuecomment-1708563718) because that would cost us an extra database query & this function is used in our send message codepath.
> We can re-select the rows that we attempted to insert, and see if the values match what we tried to insert -- if they don't, then throw the event away. I believe the transaction is guaranteed to be able to see the conflicting rows if they now exist.
<details> …
=> user_topics: Handle IntegrityError during bulk insertion.

web/src/custom_profile_fields_ui.ts
See https://chat.zulip.org/#narrow/stream/9-issues/topic/user.20management.20-.20error.20in.20new.20realm.20on.20dev/near/1826159
Updates `initialize_custom_date_type_fields` to first check to see if there are any custom profile date type fields. If not, then there's nothing to initialize and return early. If there are, then initialize the event listeners for all custom profile date type fields.
Manually tested updating settings/profile fields in dev environment with:
- Realm with no date fields
- Realm with one date field
- Realm with more than one date field
---
<details> …
=> profile-fields: Check for date fields before initializing flatpickr.

web/styles/inbox.css
This preserves a minimum 15px font-size on the inbox view, but allows scaling to larger font sizes as well.
Fixes part of #30359
| --- | --- |
|![main-morning-of-2024-06-18](https://github.com/zulip/zulip/assets/170719/8752abf2-046f-4c9e-aa38-fd15cd5d8ea1) | ![inbox-after](https://github.com/zulip/zulip/assets/170719/f4113800-0609-4926-9706-fdaa593cf044) |
<details>
</details>
=> inbox: Enable flexible font-sizing on inbox.

web/styles/message_row.css
Message timestamps are here expressed in em units, using 14px/1em as the legacy reference.
Fixes part of #30359 
Note that even with the recalculated widths, the larger 16/140-relative timestamps do not really cramp the message area all that much.
| --- | --- |
| ![timestamps-before](https://github.com/zulip/zulip/assets/170719/7a18d426-75d7-4a31-849f-182ba0302e74) | ![timestamps-after](https://github.com/zulip/zulip/assets/170719/abc5fc27-5028-40f5-b51e-189f1ab54b08) |
| ![timestamps-i18n-before](https://github.com/zulip/zulip/assets/170719/c711d011-3427-4a72-84c4-934d7af22ce5) | ![timestamps-i18n-after](https://github.com/zulip/zulip/assets/170719/cad44ac6-5716-45bf-b9cc-290eb589b2ce) |
<details> …
=> message_time: Express font-size in em units.

web/styles/search.css
Additional work can (and eventually will) better shore up the twisted inheritance chains for font-sizing on input elements such as the search input box, but the fix in this PR gets the highly visible search box in line with the rest of the always-visible UI.
Fixes part of #30359
| Before | After | After, expanded |
| ![main-morning-of-2024-06-18](https://github.com/zulip/zulip/assets/170719/903e8a05-a3ba-4a25-baa8-31ba2bf4e392) | ![search-collapsed-after](https://github.com/zulip/zulip/assets/170719/b84ad318-4b4c-4cdf-9488-034bd4c8794e) | ![search-expanded](https://github.com/zulip/zulip/assets/170719/59ac79c7-5ebd-4e02-abd8-ac0d9e5c1578) |
<details> …
=> search: Set base font-size on search input.

web/src/dropdown_widget.ts
If `disable_for_spectators` is true, the widget text is greyed out but the tippy instance is still delegated, causing it to appear on click/enter.
This PR fixes that by not delegating tippy if the `disable_for_spectators` is true.
This bug was surfaced when it was found that the
topic type filter in Recent conversations has disabled
styling for spectators, but a spectator could still click on it to open the dropdown.
Fixes #30461 
<details> …
=> dropdown_widget: Fix bug in `disable_for_spectators`.

web/src/settings_config.ts, web/styles/zulip.css, web/templates/invite_user_modal.hbs
These are the first two prep commits from #26109 updated for changes in the code base:
- The first commit cleans up some CSS rules and fixes the small issue in the screenshot below.
- The second commit updates some settings config values to be snake case vs camel case.
**Notes**:
- There's still a slight height difference between the time input and the dropdown for time units, which is not addressed in these changes.
| --- | --- |
| ![Screenshot from 2024-06-20 18-39-55](https://github.com/zulip/zulip/assets/63245456/fd9ed4a4-09e2-4c43-8e5c-ac94417237f7) | ![Screenshot from 2024-06-20 18-39-29](https://github.com/zulip/zulip/assets/63245456/f13107dd-7026-4756-8e4c-6e37b607b766)
---
<details> …
=> invite-user-modal: Update CSS for select dropdowns and expires_in_values keys for snakecase.

web/src/presence.ts
As per the new presence API, we don't get presence info for users if they went offline after `last_update_id`. This results in webapp not updating presence info for them.
To fix it, we loop over all the active / idle status users and update presence status for them as per the latest server time.
Testing:
* Log in Desdemona
* Log in as Iago in a separate session
* Both users should be online
* Logout Iago
* After some time presence for Iago is updated for Desdemona.
=> presence: Fix presence status not updated for offline users.

help/emoji-reactions.md, zerver/lib/zulip_update_announcements.py
Help center page: https://zulip.com/help/emoji-reactions
Modeled off https://zulip.com/help/view-your-mentions and https://zulip.com/help/view-and-edit-your-message-drafts#restore-a-draft
[CZO discussion of updates](https://chat.zulip.org/#narrow/stream/438-release-management/topic/zulip_updates.20items.20of.20note/near/1832544)
=> Level 5 Zulip Update, with corresponding help center update

tools/test-js-with-node, web/src/stream_edit_subscribers.ts, web/src/subscriber_api.ts
=> stream_edit_subscribers: Convert module to TypeScript.

help/include/international-wire-transfers.md, help/include/pay-by-invoice-warning.md, help/self-hosted-billing.md, help/zulip-cloud-billing.md
Adds information to the help self-hosted and Zulip Cloud billing articles about international wire transfers and fees.
<details>
<summary>Section about international transfers</summary>
*Separate section so that we can also easily link to this via the billing pages and or support/sales emails.*
</details>
<details>
<summary>Self-hosted pay by invoice instructions</summary>
</details>
<details>
<summary>Zulip Cloud pay by invoice instructions</summary>
</details>
---
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline …
=> help-billing: Add information about international bank transfers.

web/styles/rendered_markdown.css
This PR improves the display of horizontal rules by a) having them participate with other information-density values and b) aligning them better, though not perfectly, when they open a message.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/icons.20misaligned.20when.20message.20content.20is.20-----/near/1832775)
| --- | --- |
| ![hr-before](https://github.com/zulip/zulip/assets/170719/ab6760ce-b3b7-4c70-9246-862feb980969) | ![hr-after](https://github.com/zulip/zulip/assets/170719/1a8234d8-0c25-48eb-92db-1cb5ae276992) |
<details> …
=> markdown: Improve treatment of horizontal rules.

web/styles/app_variables.css, web/styles/input_pill.css, web/styles/settings.css, web/styles/zulip.css
This PR corrects regressions in pill spacing introduced in #30495 while also improving and unifying the display of pills in pill containers across the UI. Those improvements include better-centered pills in the subscribers table, as @alya [requested](https://chat.zulip.org/#narrow/stream/101-design/topic/pill.20containers.20and.20pill.20spacing/near/1832214).
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/pill.20containers.20and.20pill.20spacing/near/1831577) (design)
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/subscriber.20pills.20touching/near/1834869) (spacing regression)
_Channel Subscribers_
| Before | After | After, 16/140
| …
=> input_pills: Simplify and make uniform pill-container display.

web/styles/app_components.css, web/third/bootstrap/css/bootstrap.app.css
Next we can remove `close` class too after a bit of cleanup in another PR. Also,  it's prime time to work on #26990 and then we can soon delete the file.
=> Remove some bootstrap css.

web/src/hotkey.js
Fixes https://chat.zulip.org/#narrow/stream/9-issues/topic/Pressing.20escape.20in.20topic.20filter.20closes.20compose.20box/near/1833316.
Topic list escape key action should take preference over open composebox.
Fixes: 
<details>
</details>
=> hotkey: Don't close compose box on topic list input ESC.

zerver/lib/onboarding.py
Preparatory work for #30486 and #30278
This PR updates the message contents in that file to use triple quotes and `remove_single_newlines`
<details>
</details>
=> onboarding: Update message contents to use triple quotes.

tools/setup/install-aws-server
=> kandra: Default to installing "production", not "main".

web/src/settings_components.ts
This PRrefactors code such that we do not add separate if condition block for each
realm group based settings using the new API format to send the request accordingly.
We now use a single if-block to update the request data for realm group permission
settings using new API format.
<details>
</details>
=> settings: Refactor code to update realm group based settings.

web/styles/rendered_markdown.css
This removes duplicate font-size and line-height declarations that matched the legacy values.
Fixes part of #30476 
| Before | After (no change at legacy sizes) |
| --- | --- |
| ![mention-pills-legacy-before](https://github.com/zulip/zulip/assets/170719/6c6bfec0-5610-4cb2-a24f-2fc2b8350e51) | ![mention-pills-legacy-after-no-change](https://github.com/zulip/zulip/assets/170719/f25aa437-4b04-42a9-bfaf-f05c0eaffbc4) |
| ![mention-pills-16-140-before](https://github.com/zulip/zulip/assets/170719/d5929bfc-b0d3-4fb4-ad10-3ca591ec2e48) | ![mention-pills-16-140-after](https://github.com/zulip/zulip/assets/170719/7ab3a0be-9d95-4be3-853e-79b61a01f12d) |
<details> …
=> mention_pills: Allow pills to scale with other message text.

web/styles/app_components.css, web/styles/compose.css, web/third/bootstrap/css/bootstrap.app.css, web/third/bootstrap/css/bootstrap.portico.css
| --- | --- |
| <img width="562" alt="Screenshot 2024-06-26 at 9 37 57 PM" src="https://github.com/zulip/zulip/assets/25124304/07d62429-85d8-4045-ae75-14e7c0323cdc"> | <img width="562" alt="Screenshot 2024-06-26 at 9 38 02 PM" src="https://github.com/zulip/zulip/assets/25124304/40c62464-be83-4e1b-bc9b-a13a38985081"> |
=> Cleanup text-* classes from bootstrap.app

tools/test-js-with-node, web/src/left_sidebar_navigation_area_popovers.ts, web/src/popover_menus.ts
=> left_sidebar_navigation_area_popover: Convert module to TypeScript.

web/styles/settings.css
This PR updates the CSS to makes the label for disabled checkbox less faded such that it
is faded enough to figure out that the setting is disabled but the text is also visible clearly.
Follow up to #30594.
| Light mode | Dark mode |
| ![light-50](https://github.com/zulip/zulip/assets/35494118/435a0429-fb4d-4ec9-953b-90886b16b6f8) |  ![dark-50](https://github.com/zulip/zulip/assets/35494118/eb935746-ac53-4d32-bdb4-14c452bd1f01) |
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.ht …
=> settings: Make the label for disabled checkboxes less faded.

templates/corporate/history.md
=> portico: Add HostingAdvice.com review to history page.

web/templates/settings/notification_settings.hbs
In this commit, a help center link to follow-a-topic and mute-a-topic has been added in `SETTINGS / NOTIFICATIONS > Topic notifications` so that users can understand thier options.
Fixes #30562.
Fixes: 
UI changes
<details>
</details>
=> settings: Add links to topic notification settings.

web/styles/app_variables.css, web/styles/left_sidebar.css
This PR prepares for info-density work in the left sidebar by converting Sass-style variables to native CSS ones.
| --- | --- |
| ![left-sidebar-vars-before](https://github.com/zulip/zulip/assets/170719/f6d18b52-4509-4656-9344-4151eb191589) | ![left-sidebar-vars-after](https://github.com/zulip/zulip/assets/170719/c83b89cf-ce95-4ab9-8aac-f10807581249) |
<details>
</details>
=> left_sidebar: Convert Sass-style vars to CSS vars.

web/src/people.ts, web/src/tutorial.js, web/src/ui_init.js
[CZO Discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/onboarding.20banners/near/1838857)
Earlier, new users were narrowed to the interleaved DMs view on the first visit.
This PR updates the behavior to narrow new users in DMs with Welcome Bot.
Reason for the change:
It makes more sense overall as an interleaved DMs view is a power user view and it would also prevent the message fading banner #29076 from showing up if the user DMs Welcome Bot right away.
**Tested manually.**
[screen-capture.webm](https://github.com/zulip/zulip/assets/56781761/d0cfe1c8-576e-4d6e-bbd1-5760e845a540)
<details> …
=> onboarding: Narrow new users in DMs with Welcome Bot.

web/src/emoji_picker.js, web/src/giphy.js, web/styles/dark_theme.css, web/styles/popovers.css, web/styles/reactions.css, web/styles/zulip.css, web/templates/dropdown_list_container.hbs, web/templates/giphy_picker.hbs, web/templates/popovers/emoji/emoji_popover.hbs
=> Style emoji and giphy search same as dropdown widget.

web/styles/dark_theme.css
In dark theme, the selector for the outline was the wrong element, so a double, misplaced outline would show up.
Fixes: [CZO issue](https://chat.zulip.org/#narrow/stream/9-issues/topic/funky.20red.20error.20outline.20on.20compose.20box/near/1841380)
<details>
</details>
=> compose: Fix the red outline in invalid state in dark theme.

pyproject.toml, scripts/log-search, tools/lib/provision_inner.py, tools/run-mypy, tools/test-js-with-puppeteer, tools/total-contributions, zerver/lib/compatibility.py, zerver/lib/markdown/include.py, zerver/lib/user_agent.py, zerver/management/commands/create_default_stream_groups.py, zerver/management/commands/deactivate_user.py, zerver/management/commands/delete_old_unclaimed_attachments.py, zerver/management/commands/register_server.py, zerver/migrations/0041_create_attachments_for_old_messages.py, zerver/migrations/0371_invalid_characters_in_topics.py, zerver/migrations/0375_invalid_characters_in_stream_names.py, zerver/migrations/0383_revoke_invitations_from_deactivated_users.py, zerver/migrations/0423_fix_email_gateway_attachment_owner.py, zerver/migrations/0501_delete_dangling_usermessages.py, zerver/openapi/markdown_extension.py, zerver/tornado/sharding.py
https://docs.astral.sh/ruff/rules/#refurb-furb
=> ruff: Enable FURB rules

tools/test-js-with-node, web/src/compose_popovers.ts, web/src/rows.ts
=> compose_popovers: Convert module to TypeScript.

zerver/webhooks/codeship/doc.md, zerver/webhooks/crashlytics/doc.md, zerver/webhooks/delighted/doc.md, zerver/webhooks/dropbox/doc.md, zerver/webhooks/errbit/doc.md
As part of https://github.com/zulip/zulip/issues/29592, updates the following integration documentation pages:
1. [Codeship](https://zulip.com/integrations/doc/codeship)
2. [Crashlytics](https://zulip.com/integrations/doc/crashlytics)
3. [Delighted](https://zulip.com/integrations/doc/delighted)
4. [Dropbox](https://zulip.com/integrations/doc/dropbox)
5. [Errbit](https://zulip.com/integrations/doc/errbit)
As the changes were mostly to the docs format and not content, these are grouped together in a PR that updates 5 doc pages.
---
<details>
<summary>Updated Codeship doc</summary>
</details>
<details>
<summary>Updated Crashlytics doc</summary>
</details>
<details>
<summary>Updated Delighted doc</summary>
</details>
<details>
<summary>Updated Dropbox …
=> integration-docs: Update for new format (Codeship, Crashlytics, Delighted, Dropbox, Errbit).

zerver/webhooks/freshdesk/doc.md
Revises doc to have three instructions sections. One for creating the Zulip bot and webhook URL. One for adding notifications for new Freshdesk tickets. And one for getting notifications for existing Freshdesk tickets.
Part of #29592.
*Because this integration documentation differs from the general format, these changes are up in a separate PR.*
<details>
<summary>Updated Freshdesk doc</summary>
[Current documentation](https://zulip.com/integrations/doc/freshdesk)
</details>
---
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/comm …
=> integration-docs: Update Freshdesk for new doc format.

zerver/tests/test_openapi.py
Adds a test to check if links of API docs pages are present in the sidebar and have the same label as the endpoints' summary.
<details>
</details>
=> api_docs: Add test to check links of pages in the sidebar.

web/src/emoji_picker.js
Previously the `maybe_change_focus_emoji` was being triggered on `mouseenter` event instead of `mousemove` event. This resulted in the wrong emoji being picked when user tried to choose emoji through the keyboard. This commit intends to fix this issue by changing the event trigger.
Fixes #30559.
Fixes: 
manual testing passed
https://github.com/zulip/zulip/assets/53932029/155e749f-2090-433d-b3a8-21064ede33ce
<details> …
=> emoji: Change event trigger for emoji_picker.js.

zerver/webhooks/ansibletower/doc.md, zerver/webhooks/appfollow/doc.md, zerver/webhooks/appveyor/doc.md, zerver/webhooks/basecamp/doc.md, zerver/webhooks/beeminder/doc.md
As part of #29592, updates the following integration documentation pages:
1. [Ansible Tower](https://zulip.com/integrations/doc/ansibletower)
2. [Appfollow](https://zulip.com/integrations/doc/appfollow)
3. [Appveyor](https://zulip.com/integrations/doc/appveyor)
4. [Basecamp](https://zulip.com/integrations/doc/basecamp)
5. [Beeminder](https://zulip.com/integrations/doc/beeminder)
As the changes were mostly to the docs format and not content, these are grouped together in a PR that updates 5 doc pages.
---
<details>
<summary>Updated Ansible Tower doc</summary>
</details>
<details>
<summary>Updated Appfollow doc</summary>
</details>
<details>
<summary>Updated Appveyor doc</summary>
</details>
<details>
<summary>Updated Basecamp doc</summary>
</details> …
=> integration-docs: Update for new format (Ansible, Appfollow, Appveyor, Basecamp, Beeminder).

web/src/stream_create.js, web/styles/subscriptions.css, web/templates/stream_settings/new_stream_users.hbs, web/templates/stream_settings/stream_creation_form.hbs
Fixes part of #30690.
<details>
</details>
=> stream_create: Move `Add all users` beside `Choose subscribers`.

zerver/lib/upload/__init__.py, zerver/lib/upload/local.py
Due to recent refactoring in 9fb03cb2c7aa3a, a user could not upload avatar
if the server uses local upload backend and there was already an avatar file
for that user.
This commit fixes it to just check if there exists a file only when importing and
not when the user is actually trying to change the avatar.
Fixes: #30676
<details>
</details>
=> users: Fix uploading user avatars.

web/src/custom_profile_fields_ui.ts
Fixes #29921.
Before this, we used to initialize only 1 typeahead resulting in the bug of only the first field updating even when trying to change values in the others.
#29977 was mostly correct, added @ngadou as a co-author
<details>
</details>
=> custom_profile_fields: Initialize typeahead for every pronoun field.

help/deactivate-or-reactivate-a-user.md, web/src/settings_panel_menu.js, zerver/lib/markdown/help_settings_links.py
The second commit contains an optional change to rename `Users` to `Active users` in the `Active` tab for the heading and the filter text. We can discard that change if it's desired.
Fixes: https://chat.zulip.org/#narrow/stream/9-issues/topic/deactivated.20users.20tab/near/1843114
<details>
</details>
=> Settings: Rename `Users` and `Deactivated users` tab.

zerver/webhooks/flock/doc.md, zerver/webhooks/freshping/doc.md, zerver/webhooks/freshstatus/doc.md, zerver/webhooks/front/doc.md
As part of https://github.com/zulip/zulip/issues/29592, updates the following integration documentation pages:
1. [Flock](https://zulip.com/integrations/doc/flock)
2. [Freshping](https://zulip.com/integrations/doc/freshping)
3. [Freshstatus](https://zulip.com/integrations/doc/freshstatus)
4. [Front](https://zulip.com/integrations/doc/front)
As the changes were mostly to the docs format and not content, these are grouped together in a PR that updates 5 doc pages.
*The Front instructions were updated based on [this documentation](https://help.front.com/en/articles/2212) on their site.*
---
<details>
<summary>Updated Flock doc</summary>
</details>
<details>
<summary>Updated Freshping doc</summary>
</details>
<details>
<summary>Updated Freshstatus …
=> integration-docs: Update for new format (Flock, Freshping, Freshstatus, Front).

web/src/filter.ts, web/tests/filter.test.js
prep commit for #26803 from https://github.com/zulip/zulip/pull/26803#discussion_r1655702186
=> filter: Add validation function for search pill terms.

help/star-a-message.md
**Notes**:
- Puts documentation of new feature after "view starred messages" and before "Toggle starred messages counter".
- Notes that the option may not be present in the topic actions menu if there are no starred messages in the selected topic.
- Updates tabs to be Desktop/Web.
- Didn't add a description of the feature because it felt self-explanatory. Note there are no descriptions for "Star a message" or "View starred messages" either.
Fixes #29512.
---
[Current documentation](https://zulip.com/help/star-a-message)
<details>
<summary>Zoomed in to new "unstar all messages" section</summary>
</details>
<details>
<summary>Full article screenshot</summary>
</details>
---
<details> …
=> help: Document "Unstar all messages in topic" feature.

web/src/composebox_typeahead.ts
Before calling `on_enter_send`, we checked if the
#compose-send-button is disabled, but never actually set it to disabled, 
rather we updated its container (.message-send-controls) with that state.
This commit fixes that by correctly checking the button's
container for the class .disabled-message-send-controls
which is set to indicate that the user cannot send messages
at the moment.
Fixes #30620
<details> …
=> composebox_typeahead: Fix checking whether messages can be sent.

web/src/user_profile.js
We should disable the submit button of bot-edit-form after changes have been saved successfully. 
This Pull Request fixes a minor typo.
Fixes: [CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Manage.20bots.20save.20changes.20button)
**Before**:
https://github.com/zulip/zulip/assets/126336384/55876102-288f-49a4-9a75-e148208dc1ef
**After**:
https://github.com/zulip/zulip/assets/126336384/d1e7837e-35f1-43ae-acf3-e786fb9154c0
<details> …
=> user_profile: Pass correct element to toggle_submit_button.

zerver/webhooks/bitbucket2/doc.md, zerver/webhooks/bitbucket3/doc.md, zerver/webhooks/canarytoken/doc.md, zerver/webhooks/circleci/doc.md, zerver/webhooks/clubhouse/doc.md
As part of https://github.com/zulip/zulip/issues/29592, updates the following integration documentation pages:
1. [Bitbucket Cloud SAAS](https://zulip.com/integrations/doc/bitbucket2)
2. [Bitbucket Server](https://zulip.com/integrations/doc/bitbucket3)
3. [Canarytoken](https://zulip.com/integrations/doc/canarytoken)
4. [Clubhouse](https://zulip.com/integrations/doc/clubhouse)
5. [CircleCI](https://zulip.com/integrations/doc/circleci)
As the changes were mostly to the docs format and not content, these are grouped together in a PR that updates 5 doc pages.
---
<details>
<summary>Updated Bitbucket SAAS doc</summary>
</details>
<details>
<summary>Updated Bitbucket Server doc</summary>
</details>
<details>
<summary>Updated Canarytoken doc</summary> …
=> integration-docs: Update for new format (Bitbucket SAAS and Server, Canarytoken, Clubhouse, CircleCI).

zerver/webhooks/alertmanager/doc.md
Updates the documentation page for Prometheus Alertmanager integration for the new format of integration doc pages as part of #29592.
**Notes**:
- Also, revises text of `name` and `desc` URL parameters to be clearer and note the default values that are used for the integration ([CODE LINK](https://github.com/zulip/zulip/blob/073b116c55b6d4762122ae73824d854daa3661e3/zerver/webhooks/alertmanager/view.py#L22-L23)).
<details>
<summary>Updated documentation page</summary>
[Current documentation](https://zulip.com/integrations/doc/alertmanager)
</details>
---
<details> …
=> integration-docs: Update Prometheus Alertmanager for new doc format.

help/star-a-message.md
Quick follow-up to #30710 and #29512, so that we also have the "Unstar all messages" feature documented.
<details>
</details>
=> help: Document "Unstar all messages" feature.

web/src/stream_edit_subscribers.ts, web/src/user_group_edit_members.ts
- https://github.com/zulip/zulip/pull/30496#discussion_r1664655728
=> user_group_edit_members: Initialise `users` data as empty array.

tools/test-js-with-node, web/src/user_group_components.ts, web/src/user_group_create.js, web/src/user_group_create.ts
=> user_group_create: Convert module to TypeScript.

web/templates/recipient_row.hbs
This commit removes the whitespaces between "You and" and the user full names, thus fixing the puppeteer flake.
<details>
</details>
=> recipient_row: Remove extra whitespace around recipient full name.

zerver/lib/onboarding.py, zerver/tests/test_signup.py, zerver/tests/test_users.py
PR to update the Welcome Bot's initial direct message content.
* Update content
* Show the "I've kicked off some conversations..." only if tracked onboarding messages exists.
Fixes: #30051 
<details><summary>Realms with old onboarding messages</summary>
</img>
</details> 
<details><summary>Realms with new onboarding messages</summary>
</img>
</details> 
Note: We're further improving the interaction with welcome bot in #30049 
<details> …
=> Update initial dm

docs/documentation/integrations.md, zerver/webhooks/azuredevops/doc.md, zerver/webhooks/basecamp/doc.md, zerver/webhooks/bitbucket2/doc.md, zerver/webhooks/bitbucket3/doc.md, zerver/webhooks/circleci/doc.md, zerver/webhooks/clubhouse/doc.md, zerver/webhooks/freshping/doc.md, zerver/webhooks/freshstatus/doc.md, zerver/webhooks/front/doc.md, zerver/webhooks/gitlab/doc.md, zerver/webhooks/grafana/doc.md
Using an if block when `{!event-filtering-additional-feature.md!}` is used implied that we plan to have this in all webhook doc `.md` files.
But, it actually makes sense to only use this macro when the webhook integration actually supports event filtering, e.g. `all_event_types` is defined in the view code.
<details>
<summary>git grep 'all_event_types='</summary>
```console
zerver/webhooks/azuredevops/view.py:@webhook_view("AzureDevOps", all_event_types=ALL_EVENT_TYPES)
zerver/webhooks/basecamp/view.py:@webhook_view("Basecamp", all_event_types=ALL_EVENT_TYPES)
zerver/webhooks/bitbucket2/view.py:@webhook_view("Bitbucket2", all_event_types=ALL_EVENT_TYPES)
zerver/webhooks/bitbucket3/view.py:@webhook_view("Bitbucket3", all_event_types=ALL_EVENT_TYPES) …
```
=> integration-docs: Clarify use of event-filtering-additional-feature.

help/include/invite-users.md, help/invite-new-users.md, zerver/lib/markdown/help_settings_links.py
Follow-up to #28819.
**Notes**:
- The first commit fixes the **Manage pending invitations** documentation for invitations being part of the **Users** tab in the **Organization settings** overlay.
- The second commit fixes the instructions that had been incorrectly changed in commit 1045e322fda3d. These instructions are from the gear menu and not from the **Organization settings** overlay.
- The third commit updates the email invitation documentation for the new feature of getting a direct message notification when an email invitation is accepted.
**Questions**:
- When looking at the instructions for generation a reusable invitation link, that we use "invite" and not "invitation" for a number of strings in the model. I wasn't sure if that was something we wanted to update or not.
--- …
=> help: Update invite new user documentation.

help/direct-messages.md
Current: https://zulip.com/help/direct-messages
I also referred to https://zulip.com/help/user-list when writing this.
<details>
<summary>
Updated
</summary>
</details>
<details>
<summary>
Updated in context
</summary>
</details>
=> help: Document new DMs filter.

zerver/webhooks/github/doc.md, zerver/webhooks/github/githubsponsors.md, zerver/webhooks/updown/doc.md, zerver/webhooks/uptimerobot/doc.md
The changes are implementing the new integration-docs format and does not modify content.
There are 4 commit each updating one doc.md file.
Fixes part of https://github.com/zulip/zulip/issues/29592.
<details>
<summary>Github</summary>
[Doc link](https://zulip.com/integrations/doc/github)
</details>
<details>
<summary>Github Sponsors</summary>
[Doc link](https://zulip.com/integrations/doc/githubsponsors)
</details>
<details>
<summary>UptimeRobot</summary>
[Doc link](https://zulip.com/integrations/doc/uptimerobot)
</details>
<details>
<summary>Updown</summary>
[Doc link](https://zulip.com/integrations/doc/updown)
</details>
<details>
Communicate …
=> integration-docs: Update for new format (Github, Github Sponsors, UptimeRobot, Updown).

zerver/webhooks/hellosign/doc.md, zerver/webhooks/helloworld/doc.md, zerver/webhooks/heroku/doc.md, zerver/webhooks/ifttt/doc.md, zerver/webhooks/insping/doc.md
The changes are implementing the new integration-docs format and does not modify content.
There are 5 commit each updating one `doc.md` file.
<details>
<summary>HelloSign</summary>
[HelloSign](https://zulip.com/integrations/doc/hellosign)
</details>
<details>
<summary>Hello World</summary>
[Hello World](https://zulip.com/integrations/doc/helloworld)
</details>
<details>
<summary>Heroku</summary>
[Heroku](https://zulip.com/integrations/doc/heroku)
</details>
<details>
<summary>Insping</summary>
[Insping](https://zulip.com/integrations/doc/insping)
</details>
<details>
<summary>IFTTT</summary>
[IFTTT](https://zulip.com/integrations/doc/ifttt)
Requires updated logo and addition of example message.
</details> …
=> integration-docs: Update for new format (HelloSign, Hello World, Heroku, Insping, IFTTT).

zerver/webhooks/gitea/doc.md, zerver/webhooks/gogs/doc.md, zerver/webhooks/gosquared/doc.md, zerver/webhooks/groove/doc.md
As the changes were mostly to the docs format and not content, these are grouped together in a PR that updates 4 doc pages.
As part of https://github.com/zulip/zulip/issues/29592, update the following integration documentation pages:
<details>
<summary>
[Groove](https://zulip.com/integrations/doc/groove)
</summary>
</details>
<details>
<summary>
[GoSquared](https://zulip.com/integrations/doc/gosquared)
</summary>
</details>
<details>
<summary>
[Gogs](https://zulip.com/integrations/doc/gogs)
</summary>
</details>
<details>
<summary>
[Gitea](https://zulip.com/integrations/doc/gitea)
</summary>
</details>
<details> …
=>  integration-docs: Update for new format (Groove, Gosquared, Gogs, Gitea). 

help/restrict-direct-messages.md
Blockers (the settings this PR documents):
- #24467
Current: https://zulip.com/help/restrict-direct-messages
<details>
<summary>
Updated
</summary>
</details>
=> help: Document new direct message permissions settings.

web/src/settings_invites.ts
The multiuse invites data from server does not include `notify_referrer_on_join` fields since
we do not allow configure that for multiuse invites. This PR fixes the zod schema accordingly.
<details>
</details>
=> invites: Fix zod schema for multiuse invites.

zerver/lib/onboarding.py, zerver/models/messages.py, zerver/tests/test_tutorial.py
Fixes failing tests on #30278 -- Opened a separate PR because I can't push my changes on that PR.
https://github.com/zulip/zulip/pull/30278#issuecomment-2216757961
> I added a commit to update Welcome Bot's responses to commands, which had gotten stale.
> @prakhar1144 if you are up for fixing any tests I might have broken, that would be helpful. :)
Fixes: #30049 
<details>
</details>
=> onboarding: Change Welcome Bot message interactions.

help/left-sidebar.md
Quick follow-up from #30713 ([feedback](https://github.com/zulip/zulip/pull/30713#issuecomment-2208571121)):
> Could you please put up a quick PR to rename "Show all direct message conversations" -> "Show more direct message conversations"?
---
<details>
</details>
=> help: Revise header for more direct messages in left sidebar article.

zerver/webhooks/intercom/doc.md, zerver/webhooks/jira/doc.md, zerver/webhooks/librato/doc.md, zerver/webhooks/lidarr/doc.md, zerver/webhooks/linear/doc.md
As part of https://github.com/zulip/zulip/issues/29592, updates the following integration documentation pages:
1. [Intercom](https://zulip.com/integrations/doc/intercom)
2. [Jira](https://zulip.com/integrations/doc/jira)
3. [Librato](https://zulip.com/integrations/doc/librato) - *[Librato](https://www.librato.com/) seems to be completely [AppOptics](https://support.solarwinds.com/appoptics) now, but seems to have the same [webhook structure](https://documentation.solarwinds.com/en/success_center/appoptics/content/kb/alert/notification_services/webhook.htm).*
4. [Lidarr](https://zulip.com/integrations/doc/lidarr)
5. [Linear](https://zulip.com/integrations/doc/linear)
---
<details>
<summary>Intercom</summary>
</details>
<details>
<summary>Jira</summary> …
=> integration-docs: Update for new format (Intercom, Jira, Librato, Lidarr, Linear)

api_docs/incoming-webhooks-walkthrough.md, api_docs/writing-bots.md, docs/contributing/how-we-communicate.md, docs/development/setup-recommended.md, docs/development/using.md, docs/documentation/api.md, docs/documentation/overview.md, docs/git/zulip-tools.md, docs/overview/release-lifecycle.md, docs/production/authentication-methods.md, docs/production/export-and-import.md, docs/production/management-commands.md, docs/subsystems/events-system.md, docs/subsystems/hashchange-system.md, docs/subsystems/markdown.md, docs/subsystems/notifications.md, docs/subsystems/pointer.md, docs/subsystems/presence.md, docs/subsystems/queuing.md, docs/subsystems/realms.md, docs/subsystems/schema-migrations.md, docs/subsystems/settings.md, docs/testing/typescript.md, docs/translating/internationalization.md, docs/tutorials/writing-views.md, help/include/when-to-start-a-new-topic.md, help/setting-up-zulip-for-a-class.md, help/using-zulip-for-a-class.md, templates/zerver/development/dev_tools.html, tools/droplets/README.md
Follow-up passes from #30732:
- `git grep '[a-zA-Z] e\.g\.,'`: When "e.g.," is preceded by a word without any punctuation.
- `git grep e\.g\.,:'`: When "e.g.," is followed by a colon.
---
<details>
</details>
=> documentation: Follow-ups to exempli gratia ("e.g.,") changes.

web/src/settings_org.js, web/src/stream_edit.js, web/src/stream_settings_components.js, web/src/user_group_components.ts, web/styles/settings.css, web/styles/subscriptions.css
- First commit is to allow buttons to get wider.
- Second commit is to allow menu to get wider to not wrap the options.
Fixes:  #30673
<details>
</details>
=> Allow dropdown widget buttons and its dropdown menu to get wider.

web/styles/settings.css, web/styles/subscriptions.css
- First commit is to fix the tabs in bots panel.
- Second commit is to fix the tabs in stream and group settings.
Fixes: #30672
<details>
</details>
=> settings: Allow tabs to be wider.

docs/contributing/design-discussions.md, templates/corporate/development-community.md
This adjusts the various links to #mobile and #mobile-team so that they point to the right one of #mobile, #mobile-team, and the new #mobile-dev-help.
<details>
</details>
=> Fix and update mobile channel links

web/src/stream_popover.js
Previously, when enter was pressed in the move messages modal, it used to trigger page reload because the enter event of the modal was not handled.
This commit fixes it by adding the `form_id` field while launching the `dialog_widget`.
Fixes #29655
<details>
</details>
=> popovers: Fix page reload on enter in move message modal.

docs/overview/changelog.md
I also did a sweep for references to "streams" in the 9.0 release notes.
=> docs: Update changelog with recently merged changes.

web/src/stream_settings_ui.js
There was a bug when updating stream privacy with message list not narrowed to a stream as 'narrow_state.stream_sub().stream_id', added in 933195f7a55, tried to access stream_id field even when `narrow_state.stream_sub()` returned undefined.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/Error.20when.20changing.20channel.20permission.20.28privacy.29
<details>
</details>
=> stream-settings: Fix stream privacy update event handling.

web/src/stream_events.js, web/src/stream_settings_ui.js, web/tests/stream_events.test.js
[CZO Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.22you.20subscribed.22.20notice.20in.20new.20channel/near/1800359)
See commit message for explanation.
</img>
</details> 
**After: No bookend when stream created.**
<details>
</details>
=> channels: Don't show "You subscribed to" bookend on channel creation.

version.py
Update version.py for the textarea-caret package.
Follow up PR for [comment](https://github.com/zulip/zulip/pull/30141#discussion_r1674838979) by @andersk.
<details>
</details>
=> Follow up PR for updating PROVISION_VERSION in version.py.

web/styles/app_components.css, web/styles/settings.css, web/templates/settings/admin_profile_field_list.hbs, web/templates/settings/admin_user_list.hbs, web/templates/settings/auth_methods_settings_admin.hbs, web/templates/settings/linkifier_settings_admin.hbs, web/templates/settings/playground_settings_admin.hbs, web/templates/settings/profile_field_settings_admin.hbs, web/templates/user_topic_ui_row.hbs
- First commit is to remove unused class.
- Second commit is to fix custom profile field settings UI in narrow screens.
- Third commit is to not set width for any of the table columns except `Actions` column.
- Fourth commit is to adjust wrapping of text for certain columns.
- Fifth commit is to adjust wrapping of text in table headers.
- Sixth commit is to handle min widths of columns.
- Seventh commit is to remove `user_role` from bot owner column.
- Eigth commit is to remove sorting arrows.
Topics table
Users table with russian language selected
Users table for narrow screens
<details> …
=> Fix tables for 16px font size.

web/src/bootstrap_typeahead.ts, web/src/dropdown_widget.ts
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20Typeaheads.20and.20stream.20dropdown.20not.20working.20on.20mobile
=> Fix dropdown and typeahead on displayed on mobile.

zerver/webhooks/greenhouse/doc.md, zerver/webhooks/harbor/doc.md, zerver/webhooks/jotform/doc.md, zerver/webhooks/json/doc.md
As the changes were mostly to the docs format and not content, these are grouped together in a PR that updates 4 doc pages.
As part of https://github.com/zulip/zulip/issues/29592, update the following integration documentation pages:
<details>
<summary>
[Harbor](https://zulip.com/integrations/doc/harbor)
</summary>
</details>
<details>
<summary>
[Greenhouse](https://zulip.com/integrations/doc/greenhouse)
</summary>
</details>
<details>
<summary>
[JSON](https://zulip.com/integrations/doc/json)
</summary>
</details>
<details>
<summary>
[Jotform](https://zulip.com/integrations/doc/jotform)
</summary>
</details>
<details> …
=> integration-docs: Update for new format (Harbor, Greenhouse, JSON, Jotform) 

web/src/search.ts, web/styles/search.css
reported here: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20buggy.20.60x.60.20button.20in.202-line.20search.20box/near/1886779
=> search: Fix bug where exit button jumps when clicked.

help/invite-new-users.md
Follow-up from #30767:
> It might be a good idea to mention generating an invitation link and sending the email yourself as a workaround here; it might save some stress and support tickets for people where that workaround is totally sufficient for their needs.
---
<details>
</details>
=> help: Suggest invitation link for Cloud email invite rate limit.

web/src/user_group_edit.js
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20incorrect.20tooltip.20message/near/1886301)
Fixes: 
Before:
After:
<details>
</details>
=> group_settings: Change tooltip on add members input box.

web/styles/tooltips.css
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20tooltip.20font.20size.20too.20big/near/1882678)
Fixes: 
| ![Screenshot 2024-07-12 165323](https://github.com/user-attachments/assets/7e4c968b-ec5e-4fcd-b281-fb61bc8df5ed) | ![Screenshot 2024-07-12 164513](https://github.com/user-attachments/assets/801309d6-5187-4ab0-ac32-3d11bee3c552) |
| ![Screenshot 2024-07-12 165330](https://github.com/user-attachments/assets/cf737bac-58de-4a84-aec0-e20c1a12c12a) | ![Screenshot 2024-07-12 164521](https://github.com/user-attachments/assets/1ef15ad5-e80a-4929-97cc-53dd72484e6b) | 
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20tooltip.20font.20size.20too.20big …
=> tooltips: Make size of tooltips consistent.

corporate/views/support.py, zerver/data_import/mattermost.py, zerver/data_import/rocketchat.py, zerver/lib/bulk_create.py, zerver/lib/display_recipient.py, zerver/lib/server_initialization.py, zerver/lib/test_fixtures.py, zerver/tests/test_import_export.py, zerver/views/message_send.py
https://docs.astral.sh/ruff/rules/for-loop-set-mutations/
=> ruff: Fix FURB142 Use of set.add() in a for loop

corporate/views/support.py
https://docs.astral.sh/ruff/rules/check-and-remove-from-set/
=> ruff: Fix FURB132 Use `discard` instead of check and `remove`

api_docs/changelog.md, version.py, web/src/upload.ts, web/tests/upload.test.js, zerver/actions/create_realm.py, zerver/lib/scim_filter.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_delete_unclaimed_attachments.py, zerver/tests/test_events.py, zerver/tests/test_scheduled_messages.py, zerver/tests/test_subs.py, zerver/tests/test_thumbnail.py, zerver/tests/test_upload.py, zerver/tests/test_upload_local.py, zerver/tests/test_upload_s3.py, zerver/views/auth.py, zerver/views/upload.py
In #23380, @timabbott asked to replace deprecated URI abbreviation with URL to follow web standards.
In #29959, the URI occurrences related to realm were replaced by URL.
This PR replaces other occurrences - local variables, comments, and the "/user_uploads" endpoint.
<details>
</details>
=> Replace occurrences of URI with URL.

web/src/portico/help.js, web/src/portico/help.ts
=> help: Convert module to TypeScript.

web/templates/settings/edit_embedded_bot_service.hbs
We should check if the service variable is defined or not to avoid throwing errors.
Since the implementation of embedded bots is not complete, the service is likely to be undefined.
Fixes: [issue](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.93.82.20Error.20when.20opening.20.22Edit.20bot.22.20menu.20to.20edit.20Embedded.20bot)
Before 
After
https://github.com/user-attachments/assets/6041c3e9-7309-4fdb-a58e-77c7dc9c4ba2
<details> …
=> edit_embedded_bot: Check if service is defined.

help/include/create-a-channel-instructions.md, help/include/how-to-create-a-user-group.md
**Notes**:
- Expanded "info" to "information".
- Notes about where the "Create" button was seemed redundant since the user will have clicked the "Continue to add ..." buttons that are in the same place and have very clear/particular text.
Fixes #30861.
<details>
<summary>Create channels instructions</summary>
[Current documentation](https://zulip.com/help/create-channels)
</details>
<details>
<summary>Create user groups instructions</summary>
[Current documentation](https://zulip.com/help/create-user-groups)
</details>
---
<details> …
=> help: Create channels and user groups instructions for UI updates.

web/styles/settings.css, web/templates/settings/linkifier_settings_admin.hbs
- First commit is to remove unnecessary div.
- Second commit is to refactor the CSS selector for file name.
- Third commit is to refactor CSS for users and bots table.
Follow-ups of #30832.
<details>
</details>
=> settings: Refactor CSS selectors for tables to be more specific.

web/src/search_pill.ts
I missed one call.
Followup to https://github.com/zulip/zulip/pull/30889#issuecomment-2229106232
=> search pills: Always pass quiet=true to clear().

web/templates/stream_settings/stream_creation_form.hbs
This PR address tim's both feedbacks on https://github.com/zulip/zulip/pull/29433#issuecomment-2174606839
<details>
</details>
=> Followup stream creation panel

tools/linter_lib/custom_check.py, tools/test-js-with-node, web/src/server_message.ts
The pull-request creates a `server_message.ts` module which will home our `zod` schema for the messages received from server. We can then import the schema to parse the data in needed modules at the API boundaries.
This will also help us write better tests.
=> Preparatory commit for #30509 and #30702

web/src/hash_util.ts
This PR extends the work in #29302 to support the new "channel" operator,
which is synonymous to the "stream" operator, in transforming stream-topic urls
to the pretty syntax.
<details>
</details>
=> compose: Support `channel` in transforming stream-topic links.

web/styles/zulip.css
CZO discussion
| Channel typeaheads, before | Channel typeaheads, after |
| --- | --- |
| ![typeahead-icons-before](https://github.com/user-attachments/assets/75086bfb-55d6-4265-bac2-ffe032d401a9) | ![typeahead-icons-after](https://github.com/user-attachments/assets/ce7b7f9a-a2f5-42d4-aacc-86684e582850) |
| User typeaheads, before | User typeaheads, after (no change) |
| --- | --- |
| ![typeahead-users-before](https://github.com/user-attachments/assets/5a756361-1a58-4f41-9837-5a652470ce58) | ![typeahead-users-after-no-change](https://github.com/user-attachments/assets/75030bdf-184b-46e6-8080-a89af31293bb) |
<details> …
=> typeaheads: Space channel icons with flexbox.

web/templates/settings/admin_linkifier_list.hbs
All the buttons in settings have become rounded but these were still square with no border-radius. Added the `rounded` class for them to have the standard border-radius.
Before:
After:
<details>
</details>
=> settings_linkifiers: Make edit and delete buttons rounded.

zerver/webhooks/taiga/doc.md, zerver/webhooks/thinkst/doc.md, zerver/webhooks/transifex/doc.md, zerver/webhooks/travis/doc.md
<details>
<summary>Taiga</summary>
[Doc link](https://zulip.com/integrations/doc/taiga)
</details>
<details>
<summary>Thinkst</summary>
[Doc link](https://zulip.com/integrations/doc/thinkst)
</details>
<details>
<summary>Transifex</summary>
[Doc link](https://zulip.com/integrations/doc/transifex)
</details>
<details>
<summary>Travis CI</summary>
[Doc link](https://zulip.com/integrations/doc/travis)
</details>
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing …
=> integration-docs: Update for new format (Taiga, Thinkst, Transifex, Travis CI).

web/styles/left_sidebar.css
This replaces a previous hard-coded pixel value for calculating the `top` value on the sticky zoomed in narrow filter with its em-based counterpart. Additionally, an unreachable style that did a similar calculation is removed. 
Other vertical uses of `calc()` have also been audited for the left sidebar, but no changes were necessary.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20.22Back.20to.20channels.22.20partially.20hidden/near/1890375)
| --- | --- |
| ![topic-scrolling-before](https://github.com/user-attachments/assets/e84d1486-bbf6-459b-9dda-f68c0772dcea) | ![topic-scrolling-after](https://github.com/user-attachments/assets/7d66a895-ea0b-4e92-ba0c-7c7a1552af8a) |
<details> …
=> left_sidebar: Correct improper zoomed-in topic scroll.

zerver/migrations/0553_copy_emoji_images.py
=> Fix emoji re-thumbnailing for imports

web/src/information_density.ts, web/src/server_events_dispatch.js, web/src/settings_components.ts, web/src/settings_config.ts, web/src/settings_preferences.ts, web/templates/settings/display_settings_general.hbs, web/tests/dispatch.test.js, zerver/actions/realm_settings.py, zerver/actions/user_settings.py, zerver/tests/test_realm.py, zerver/tests/test_settings.py, zerver/views/realm.py, zerver/views/user_settings.py
- First commit is to rename "Dense mode" setting to "Compact mode" and use that to update the font size and line-height.
- Second commit is to handle when updating the settings through API.
- Third commit is to handle invalid combinations.
- Fourth commit is to handle showing the settings in production.
<details>
</details>
=> Use "compact mode" checkbox setting to toggle between 14/122 and 16/140 modes.

web/src/settings_users.js, web/src/stream_data.ts, web/styles/input_pill.css, web/styles/right_sidebar.css, web/styles/settings.css, web/templates/settings/active_user_list_admin.hbs, web/templates/settings/admin_invites_list.hbs, web/templates/settings/admin_user_list.hbs, web/templates/settings/bot_list_admin.hbs, web/templates/settings/deactivated_users_admin.hbs, web/templates/stream_settings/new_stream_user.hbs, web/templates/stream_settings/new_stream_users.hbs, web/templates/stream_settings/stream_member_list_entry.hbs, web/templates/stream_settings/stream_members.hbs, web/templates/stream_settings/stream_settings.hbs, web/templates/user_display_only_pill.hbs, web/templates/user_group_settings/new_user_group_users.hbs, web/templates/user_group_settings/user_group_members.hbs, web/tests/stream_data.test.js
Converting links to pill in the Organization settings.
Fixes: #24229
<details>
</details>
=> Organization Pill

zerver/webhooks/zabbix/doc.md
Fixes part of https://github.com/zulip/zulip/issues/29592.
<details>
<summary>Zabbix</summary>
[Doc link](https://zulip.com/integrations/doc/zabbix)
</details>
<details>
</details>
=> integration-docs: Update Zabbix for new doc format.

zerver/webhooks/slack_incoming/doc.md, zerver/webhooks/sonarqube/doc.md, zerver/webhooks/sonarr/doc.md, zerver/webhooks/splunk/doc.md, zerver/webhooks/statuspage/doc.md, zerver/webhooks/stripe/doc.md
<details>
<summary>Stripe</summary>
[Doc link](https://zulip.com/integrations/doc/stripe)
</details>
<details>
<summary>Statuspage</summary>
[Doc link](https://zulip.com/integrations/doc/statuspage)
</details>
<details>
<summary>Splunk</summary>
[Doc link](https://zulip.com/integrations/doc/splunk)
</details>
<details>
<summary>Sonarr</summary>
[Doc link](https://zulip.com/integrations/doc/sonarr)
</details>
<details>
<summary>Sonarqube</summary>
[Doc link](https://zulip.com/integrations/doc/sonarqube)
</details>
<details>
<summary>Slack incoming</summary>
[Doc link](https://zulip.com/integrations/doc/slack_incoming)
</details>
<details> …
=> integration-docs: Update for new format (Slack incoming, Sonarqube, Sonarr, Splunk, Statuspage, Stripe).

zerver/migrations/0553_copy_emoji_images.py
90701978d9bfd886e33c15107e6ee3139dec16ee was an incomplete fix.
Fixes: 
<details>
</details>
=> migrations: Further fix emoji re-thumbnailing.

zerver/webhooks/teamcity/doc.md, zerver/webhooks/trello/doc.md
Apply integration-docs' new format for TeamCity and Trello.
Fixes part of https://github.com/zulip/zulip/issues/29592.
<details>
<summary>TeamCity</summary>
[Doc link](https://zulip.com/integrations/doc/teamcity)
</details>
<details>
<summary>Trello</summary>
[Doc link](https://zulip.com/integrations/doc/trello)
</details>
<details>
</details>
=> integration-docs: Update for new format (Teamcity, Trello).

web/templates/modal_banner/stream_creation_confirmation_banner.hbs
When an administrators create channels that they are themselves not initial subscribers, a channel creation confirmation banner is displayed in the settings panel.
This PR updates the term "stream" to "channel" in the banner.
[CZO report
](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20.22stream.22.20in.20confirmation.20banner/near/1891728)
</img>
</details> 
</img>
</details> 
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline …
=> stream_settings: Rename stream to channel in stream created banner.

web/src/blueslip.ts, web/src/blueslip_stacktrace.ts
[Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/blueslip.20error.20due.20to.20originalevent.2Eerror.20being.20null/near/1892096).
=> blueslip_stacktrace: Handle thrown null or undefined

api_docs/changelog.md, version.py, zerver/actions/message_delete.py, zerver/actions/message_edit.py, zerver/openapi/zulip.yaml, zerver/tests/test_delete_unclaimed_attachments.py, zerver/tests/test_events.py, zerver/tests/test_link_embed.py, zerver/tests/test_message_delete.py, zerver/tests/test_message_move_topic.py, zerver/tests/test_push_notifications.py, zerver/tests/test_retention.py, zerver/views/message_edit.py, zerver/views/streams.py
This PR completes the work done in #30440 by documenting the change. Currently, `delete_message` event is not sent to the user who deletes the message in a channel they are not subscribed to. This PR fixes that by always sending the event to the user who deletes the message.
Fixes #29826.
<details>
</details>
=> events: Send `delete_message` event to user who deleted the message.

web/src/input_pill.ts, web/src/search.ts
CZO: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20backspace.20doesn.27t.20clear.20all.20selected.20search.20pills
=> input pill: Differentiate how pills are removed in the callback.

api_docs/changelog.md, api_docs/construct-narrow.md, zerver/openapi/zulip.yaml
**Notes**:
- Prep commit adds a section header for the changes notes in the construct a narrow documentation about adding support / deprecating narrow filters. And fixes links in the API changelog and endpoint documentation accordingly.
- Revises the API feature level 271 changelog and narrow documentation.
Fixes #30864.
---
<details>
<summary>Updated API feature level 271</summary>
</details>
<details>
<summary>Example of updated narrow parameter description</summary>
</details>
<details>
<summary>Updated changes section in narrow documentation</summary>
</details>
<details>
<summary>Updated message IDs section in narrow documentation</summary>
</details>
---
<details> …
=> api-docs: Revise feature level 271 documentation.

web/src/user_profile.js, zerver/views/users.py
- First commit is to show current deactivated owner in options.
- Second commit is a small optimization and also a short term fix to allow changing other bot fields if the bot owner is not changed.
Fixes: https://chat.zulip.org/#narrow/stream/9-issues/topic/editing.20a.20bot.20with.20deactivated.20owner
<details>
</details>
=> settings: Fix editing a bot with deactivated owner.

tools/semgrep-py.yml, zerver/migrations/0553_copy_emoji_images.py
=> migrations: Derive emoji content-type from the bytes.

web/src/bootstrap_typeahead.ts, web/src/invite_stream_picker_pill.ts, web/src/pill_typeahead.ts, web/styles/input_pill.css
This PR fixes bug that were caused in #28686.
This PR makes sure that typeahead menu don't pop up every time we delete a pill.
Fixes: #30542
[screen-capture.webm](https://github.com/zulip/zulip/assets/98596642/0f244947-e95c-48ab-9c43-5840cebb598a)
<details>
</details>
=> Improve invitation modal stream pills backspace interaction #30542

web/src/search.ts
This came out of this conversation on CZO:
https://chat.zulip.org/#narrow/stream/101-design/topic/.F0.9F.8E.AF.20behavior.20when.20search.20is.20cleared/near/1891878
=> search pills: Don't re-narrow when deleting pills.

web/src/input_pill.ts
https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20quotes.20representation.20in.20pills/near/1890117
=> search pills: Decode display value.

web/styles/message_view_header.css
This PR adds the same padding to the right of the description as appears to the left in order to keep descriptions or ellipses from colliding with the search box.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20space.20between.20channel.20description.20and.20search/near/1890042)
| --- | --- |
| ![description-before](https://github.com/user-attachments/assets/fb718aec-e4eb-41f7-9c44-50be0886858b) | ![description-after](https://github.com/user-attachments/assets/a8125124-5636-4ad0-8639-a419b9042fd5) |
<details> …
=> navbar: Keep descriptions and closed search box from colliding.

zproject/computed_settings.py, zproject/default_settings.py, zproject/dev_settings.py
[Discussion](https://chat.zulip.org/#narrow/stream/3-backend/topic/katex.20server/near/1893398).
=> settings: Disable KaTeX server in development

docs/overview/changelog.md
=> docs: Fix some entries about user inivitations in changelog.

web/src/integration_url_modal.ts, web/src/settings_account.js, web/src/settings_emoji.ts, web/src/settings_linkifiers.ts
Fixed the "multiple modals opening on pressing enter" for some of the modals with more obvious solutions.
[CZO thread](https://chat.zulip.org/#narrow/stream/6-frontend/topic/.F0.9F.8E.AF.20focus.20on.20dialog.20widget).
=> Multiple-modals-issue

zerver/webhooks/splunk/doc.md, zerver/webhooks/stripe/doc.md, zerver/webhooks/trello/doc.md
Fixes:
- Splunk doc: Rephrase the tip.
- Stripe doc: Clarify the tip by adding a suggestion.
- Trello doc: Format keyboard shortcuts.
[Splunk typo fix](https://github.com/zulip/zulip/pull/30798/files/994af5565793da732d2171779f380a23688e17be#r1681742386)
[CZO Topic: Stripe hint fix](https://chat.zulip.org/#narrow/stream/19-documentation/topic/Stripe.20doc/near/1893109)
[Trello keyboard shortcuts fix](https://github.com/zulip/zulip/pull/30799#issuecomment-2234251800)
| Before | After|
|---|---|
| ![image](https://github.com/user-attachments/assets/0207380f-2aad-466a-b07b-783ab75fbb67) | ![image](https://github.com/user-attachments/assets/691884fa-b8b0-481d-80bc-11d4b89bbf2e) |
| ![image](https://github.com/user-attachments/assets/67e02306-78e4-43ea-805f-6d8dbac4bba0) | …
=> Fix typos in integration docs

web/styles/input_pill.css
We now set max-width on the pill value for stream creator pill to make sure that the pill does not get too long for long names and the full name can anyways be seen by clicking on the pill.
Fixes: https://github.com/zulip/zulip/pull/30371#issuecomment-2231358392
<details>
</details>
=> stream-settings: Set max-width for stream creator pill.

help/configure-default-new-user-settings.md, help/dark-theme.md, help/font-size.md, help/include/set-up-your-account.md, help/link-to-a-message-or-conversation.md, zerver/lib/zulip_update_announcements.py
[Updates discussion on CZO](https://chat.zulip.org/#narrow/stream/438-release-management/topic/zulip_updates.20items.20of.20note/near/1891407)
Screenshot (I tested the links):
https://zulip.com/help/font-size
https://zulip.com/help/set-up-your-account
https://zulip.com/help/link-to-a-message-or-conversation
=> Help updates + Zulip update message

zerver/actions/uploads.py, zerver/lib/markdown/__init__.py, zerver/lib/test_classes.py, zerver/lib/thumbnail.py, zerver/lib/upload/__init__.py, zerver/management/commands/delete_old_unclaimed_attachments.py, zerver/tests/test_markdown.py, zerver/tests/test_thumbnail.py, zerver/views/upload.py, zerver/worker/thumbnail.py, zproject/test_extra_settings.py
These test refactors all seem good and I think we can merge them to shrink #30477.
=> Preparatory test refactoring commits extracted from #30477

web/styles/search.css
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20search.20typeahead.20multi-line.20styling/near/1896190)
| --- | --- |
| ![Screenshot 2024-07-19 at 11 46 53 AM](https://github.com/user-attachments/assets/488127ac-7371-476d-a2a9-8ea9a1990ec7) | ![Screenshot 2024-07-19 at 11 45 33 AM](https://github.com/user-attachments/assets/6a289295-25d7-48d6-8b9e-9f73dcaf03d7) |
<details> …
=> search_pills: Improve user-pill container and search-list spacing.

web/src/settings_org.js
| ![Screenshot 2024-07-19 141332](https://github.com/user-attachments/assets/70b9dcde-f53f-41ba-96e4-84b523025ef1) | ![Screenshot 2024-07-19 174407](https://github.com/user-attachments/assets/11af8bbc-b36f-40b3-a8b0-4eb40daaa4b9) | 
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/dropdown.20list.20item.20highlight.20on.20hover/near/1896085)
<details>
</details>
=> dropdown: Fix partial highlight of list-item on hover.

web/e2e-tests/message-basics.test.ts, web/src/search.ts, web/src/search_suggestion.ts, web/styles/search.css
Fixes https://github.com/zulip/zulip/issues/30911
=> search: Empty input on open, and show current narrow search suggestions.

web/src/inbox_ui.ts, web/src/recent_view_ui.ts, web/src/views_util.ts
Reproducer:
Open search box and type something. Then use the arrow keys. The focus is changed to inbox view rows which shouldn't happen.
=> Fix inbox view steals focus when navigating in search box.

zerver/lib/typed_endpoint.py, zerver/lib/typed_endpoint_validators.py, zerver/tests/test_subs.py, zerver/views/streams.py
Convert streams to typed endpoint.
Used pydantic's BaseClass to provide better type validation.
=> streams: Convert to typed_enpoint.

zerver/webhooks/opsgenie/doc.md, zerver/webhooks/pivotal/doc.md, zerver/webhooks/radarr/doc.md, zerver/webhooks/raygun/doc.md, zerver/webhooks/reviewboard/doc.md, zerver/webhooks/rhodecode/doc.md, zerver/webhooks/rundeck/doc.md
<details>
<summary>Radarr</summary>
[Doc link](https://zulip.com/integrations/doc/radarr)
</details>
<details>
<summary>Raygun</summary>
[Doc link](https://zulip.com/integrations/doc/raygun)
</details>
<details>
<summary>Review Board</summary>
[Doc link](https://zulip.com/integrations/doc/reviewboard)
</details>
<details>
<summary>RhodeCode</summary>
[Doc link](https://zulip.com/integrations/doc/rhodecode)
</details>
<details>
<summary>Rundeck</summary>
[Doc link](https://zulip.com/integrations/doc/rundeck)
</details>
<details>
<summary>Pivotal</summary>
[Doc link](https://zulip.com/integrations/doc/pivotal)
</details>
<details>
<summary>Opsgenie</summary>
[Doc …
=> integration-docs: Update for new format (Radarr, Raygun, Review Board, RhodeCode, Rundeck, Pivotal, Opsgenie)

web/src/user_events.js
When a user changed an email, we updated the compose and narrow state before updating that person's email in `people_dict`. This raised a warning in `get_direct_message_permission_hints` when using `emails_strings_to_user_ids_string` since that person's email wasn't updated in `people_dict` by then.
We just changed the order of update so that the email is updated in `people_dict` before we update compose and narrow state.
<details> …
=> user_events: Update email in people_dict before updating compose state.

web/src/stream_popover.js
There was a bug when stream_id field was being passed as NaN when user tried to edit topic of a message if the user did not had permission to edit the channel.
This PR fixes it to not pass stream_id field in such cases because channel cannot be changed.
Fixes: #30992
<details>
</details>
=> stream_popover: Fix message topic edit without permission to edit channel.

zerver/tests/test_import_export.py
https://github.com/zulip/zulip/pull/30922#issuecomment-2231367963
> We generally do try to add test coverage when adding to the export tool; maybe you can do a quick follow-up that adds to the base data for the data import/export
<details>
</details>
=> test_import_export: Add test coverage for OnboardingUserMessage.

web/styles/recent_view.css
This PR increases right padding for the th elements in recent views table to make sure that the sorting arrow is visible correctly for various screen width and font sizes. This change is similar to what we did for tables in settings UI.
Fixes: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20sort.20by.20unread.20button.20highlighting
<details>
</details>
=> recent-view: Fix sorting arrows in recent views table heading.

web/styles/app_components.css
This PR compensates for selector reordering introduced in 8457d12e59ca2b78f34a0dd3cae688ad999fb4ad. [As noted on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.F0.9F.8E.AF.20.22about.20Zulip.22.20popup.20in.20the.20corner/near/1886384), the long-range fix is to better isolate show/hide behavior to specific classes, but this effectively restores `display: flex` winning out when both the `show` and `flex` classes appear on the same component.
One of the more important fixes this introduces is to ensure properly centered popup overlays such as About Zulip.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.F0.9F.8E.AF.20.22about.20Zulip.22.20popup.20in.20the.20corner/near/1882629)
| About Zulip, …
=> app_components: Display as flex in presence of show and flex classes.

web/styles/compose.css
This PR adjusts breakpoints by 20px, to account for the wider sidebar introduced in #31002.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.F0.9F.8E.AF.20compose.20icons.20spill.20out/near/1898977)
<details>
</details>
=> compose: Adjust popover-button breakpoints for wider left sidebar.

help/contact-support.md
Current: https://zulip.com/help/contact-support#product-feedback
Updated:
=> help: Document feedback@zulip.com contact email.

web/styles/app_components.css, web/styles/app_variables.css, web/styles/recent_view.css
- First commit is a refactor to use variable for padding value.
- Second commit is to increase the padding
| --------- | --------- |
| ![recent-view-before](https://github.com/user-attachments/assets/ef8d9e9f-a951-4c32-8e56-2974f7b8c63a) |![recent-view-after](https://github.com/user-attachments/assets/fab78f24-b877-4209-9817-971eaaf1d303) |
| ![topics-before](https://github.com/user-attachments/assets/72815c9d-1a16-4abe-a629-945162999cfd) |![topics-after](https://github.com/user-attachments/assets/f0cade05-b0bd-4338-97bd-00e9f4396526) |
<details> …
=> tables: Increase right padding for sortable column headers.

web/src/inbox_ui.ts, web/src/recent_view_ui.ts
[CZO Discussion
](https://chat.zulip.org/#narrow/stream/101-design/topic/inbox.20.2F.20recent.20conversations.20intro.20modal/near/1900242)
> we should probably make the confirmation button for these modals say "Got it" rather than "Continue", to reinforce the vocabulary we're using ("Got it" = dismiss one-time content forever).
<details><summary>Inbox view modal</summary>
</img>
</details> 
<details><summary>Recent view modal</summary>
</img>
</details> 
<details> …
=> onboarding_steps: Update button text of inbox and recent view modals to "Got it".

help/configure-automated-notices.md
Current: https://zulip.com/help/configure-automated-notices#zulip-update-announcements
Updated:
=> help: Add a note about frequency of Zulip updates.

templates/corporate/team.html, web/src/portico/team.ts
This is a useful supplement to the number for 100+ commits.
=> team: Count contributors with 20+ commits too.

help/include/manage-this-user-via-user-profile.md, help/include/manage-user-tab-tip.md, help/preview-your-message-before-sending.md
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/help.20center.20icon.20update/near/1900456)
=> help: Update edit icon.

web/src/user_card_popover.js, web/src/user_profile.js
Previously, clicking on "view user profile" in the user card popover would open up the profile as an overlay, changing the hash, and closing other already opened overlays when opened.
This commit would modify it to behave as a modal rather when an overlay is already open in the background, thus preventing the hash change, and allowing the background overlays to exist when it is opened.
Fixes #30481
<details>
</details>
=> popovers: Skip updating url hash when clicked on "View user profile".

web/src/lightbox.ts, web/styles/lightbox.css
This improves the user experience by showing *something* as we fetch the full-resolution image in the background.
<details>
</details>
=> thumbnail: Use the pre-fetched thumbnail as a temporary stand-in.

web/src/thumbnail.ts, zerver/lib/thumbnail.py
=> Remove unused thumbnail sizes

web/src/settings_account.js, web/src/settings_users.js, web/src/user_deactivation_ui.ts
We previously did not allow users to deactivate themselves from users list to avoid users deactivating themselves accidentally. But we now show a confirmation modal before deactivating a user, so it is fine to allow it.
Fixes: https://chat.zulip.org/#narrow/stream/9-issues/topic/deactivating.20yourself.20disabled.20in.20users.20panel
<details>
</details>
=> settings: Allow admins/owners to deactivate themselves from users list.

web/src/user_card_popover.js, web/styles/popovers.css, web/templates/popovers/user_card/user_card_popover.hbs
This PR improves the user_card_popover for bot users by:
- Removing the presence circle indicator for bots.
- Adding bot-specific terminology for mute/unmute options.
- Changing “Bot owner” to “Owner”.
- Fixing overflow issues with long bot owner names.
- Correcting the avatar replacement bug for bot user cards by scoping the selector properly.
Fixes: Part of #31027.
<details>
</details>
=> user_card_popover: Improvements and bug fixes for bot user card popover.

web/src/copy_and_paste.ts
This PR makes pasting formatted text a two-step process:
- Insert unformatted text
- Insert formatting
This way, undo (Ctrl+Z) will restore the original pre-formatting syntax.
This is the same as the approach taken with
auto-formatting in #29302.
`Tested in Chrome and Firefox.`
Fixes #31061
<details>
</details>
=> copy_and_paste: Paste text first unformatted and then formatted.

web/src/settings_profile_fields.ts, web/src/settings_streams.ts
Fixes the multiple modal issue for default streams as well as custom profile fields.
=> Multiple-modals-default-stream

web/src/lightbox.ts
By using canonical URLs in constructing media lists and comparing the payload.source with canonical display source URLs, this correctly highlights media selected from a message, and restores the proper function of thumbnail highlighting and advancing in the lightbox.
[CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/lightbox.20does.20not.20start.20selected.20on.20Firefox/near/1900878)
<details> …
=> lightbox: Update `canonical_url_of_media` to use URL pathname.

web/src/hotkey.js
Fixes
https://chat.zulip.org/#narrow/stream/101-design/topic/key.20combination.20for.20hotkey.20to.20toggle.20compose.20preview/near/1902135. The logic to put focus back to textarea is not part of the `clear_preview_area` function because you wouldn't expect a function clearing the preview area to somehow put focus into the edit area.
<details>
</details>
=> hotkey: Put focus back into edit text area after Alt + P.

docs/overview/changelog.md
=> docs: Update changelog with changes and upgrade notes.

.github/workflows/production-suite.yml, tools/ci/Docker-prod-8.0.diff, tools/ci/Dockerfile.prod
=> Update Docker images and CI

puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf, scripts/setup/apt-repos/zulip/custom.sh, zerver/management/commands/register_server.py
- https://github.com/zulip/zulip/pull/29443 (Most important, as it fixes upgrading Debian systems).
- https://github.com/zulip/zulip/pull/30904
- https://github.com/zulip/zulip/pull/30235
- https://github.com/zulip/zulip/pull/30247
=> Backport several PRs to 8.5

scripts/lib/run_hooks.py, scripts/lib/upgrade-zulip-stage-3
=> upgrade-zulip: Factor out a script to run hooks.

templates/zerver/integrations/index.html, templates/zerver/landing_nav.html, templates/zerver/portico-header.html, web/styles/app_components.css, web/styles/dark_theme.css, web/styles/left_sidebar.css, web/styles/portico/integrations.css, web/styles/portico/navbar.css, web/styles/portico/portico_signin.css, web/styles/settings.css, web/styles/subscriptions.css, web/styles/zulip.css, web/templates/change_visibility_policy_button_tooltip.hbs, web/templates/settings/display_settings_emoji.hbs, web/templates/settings/display_settings_information.hbs, web/templates/stream_settings/stream_settings_overlay.hbs, web/templates/streams_subheader.hbs, web/templates/user_group_settings/user_group_settings_overlay.hbs
See https://chat.zulip.org/#narrow/stream/6-frontend/topic/CSS.20selector.20performance/near/1845719 for more context
=> Improve CSS selector performance by removing some spans

web/styles/rendered_markdown.css
This removes the `.rendered_markdown .message_embed > *` selector which was expensive, and instead moves the styles to the specific elements that need them.
See https://chat.zulip.org/#narrow/stream/6-frontend/topic/CSS.20selector.20performance/near/1901261 for context.
| ![Screenshot 2024-07-30 at 2 36 20 AM](https://github.com/user-attachments/assets/ad0c44d7-eaff-480e-b63a-5ea0a2f4f567) | ![Screenshot 2024-07-30 at 2 35 43 AM](https://github.com/user-attachments/assets/f61cfbd8-22ae-418c-81ca-a06e1c42436d) | 
<details> …
=> rendered_markdown: Remove universal selector for embedded content.

web/src/portico/integrations_dev_panel.js, web/src/portico/integrations_dev_panel.ts
=> integrations_dev_panel: Convert module to TypeScript.

analytics/lib/counts.py
analytics_usercount_property_realm_id_end_time_591dbec1_idx, added back in b7df84d5a8d9, makes this lookup actually indexed. 195defb0310a rewrote this query in a way which stopped using the index.
Fixes: 
<details>
</details>
=> analytics: Better indexed join to analytics_usercount, using realm_id.

docs/overview/architecture-overview.md, puppet/zulip/manifests/app_frontend_base.pp, puppet/zulip/manifests/nagios_plugins.pp, puppet/zulip/manifests/postgresql_base.pp, puppet/zulip/manifests/profile/base.pp
=> docs: Fix up some paths and references in architecture-overview.md.

web/styles/popovers.css
This fixes the alignment of the copy-URL icon on custom URL profile fields.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/misaligned.20.22copy.22.20icon.20in.20user.20profile/near/1882684)
| --- | --- |
| ![Screen Shot 2024-07-30 at 16 46 03](https://github.com/user-attachments/assets/9c375b3d-1c21-490d-a998-211f8b9b9169) | ![Screen Shot 2024-07-30 at 16 45 08](https://github.com/user-attachments/assets/ffd15c6f-388b-48f9-bf4c-b86ad69b3bdd) |
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributin …
=> user_profile: Properly center icon for copying URLs.

zilencer/views.py
Because Django does not support returning the inserted row-ids with a `bulk_create(..., ignore_conflicts=True)`, we previously counted the total rows before and after insertion.  This is rather inefficient, and can lead to database contention when many servers are reporting statistics at once.
Switch to reaching into the private `_insert` method, which does support what we need.  While relying a private method is poor form, it is mildly preferable to attempting to re-implement all of the complexities of it.
Fixes: 
<details> …
=> zilencer: Avoid repeated COUNT(*) queries.

web/src/base_page_params.ts, web/src/portico/landing-page.ts, web/src/portico/team.ts
=> landing_page: Convert module to TypeScript.

zerver/webhooks/semaphore/doc.md, zerver/webhooks/sentry/doc.md
<details>
<summary>Sentry</summary>
[Doc link](https://zulip.com/integrations/doc/sentry)
</details>
<details>
<summary>Semaphore</summary>
[Doc link](https://zulip.com/integrations/doc/semaphore)
</details>
<details>
</details>
=> integration-docs: Update to the new format (Sentry and Semaphore).

web/styles/rendered_markdown.css
This PR improves the layout, and by extension the clock-icon alignment, on time spans. Originally noted as part of #31183
| --- | --- |
| ![clock-compact-before](https://github.com/user-attachments/assets/25e8c85c-8fae-42e0-8b54-e917f0e88d1d) | ![clock-compact-after](https://github.com/user-attachments/assets/2866173f-e001-4d3d-8441-ca242371b8b7) |
| ![clock-16-before](https://github.com/user-attachments/assets/fb270fe2-3855-4634-b1fd-8bb3c9f50e2c) | ![clock-16-after](https://github.com/user-attachments/assets/8a34c9e6-9741-436a-8fbe-89e15166ff22) |
<details> …
=> rendered_markdown: Lay out time spans with inline-flex.

tools/linter_lib/custom_check.py, tools/test-js-with-node, web/src/message_events_util.js, web/src/message_events_util.ts
=> message_events_util: Convert module to TypeScript.

analytics/tests/test_counts.py, tools/rebuild-test-database, zerver/actions/users.py, zerver/data_import/mattermost.py, zerver/data_import/rocketchat.py, zerver/lib/display_recipient.py, zerver/lib/export.py, zerver/lib/narrow.py, zerver/lib/users.py, zerver/models/messages.py, zerver/models/recipients.py, zerver/models/scheduled_jobs.py, zerver/tests/test_mattermost_importer.py, zerver/tests/test_rocketchat_importer.py, zilencer/management/commands/populate_db.py
This commit completes rename of "huddle" to "direct_message_group" in all the non API files.
Part of #28640
Also includes:
- `huddle_recipient_id_to_user_ids` to `user_ids_in_direct_message_groups`
- `include_deactivated_users_for_huddles` to `include_deactivated_users_for_dm_groups`
(since using `direct_message_groups would be long for them)
remaining as per the [CZO thread](https://chat.zulip.org/#narrow/stream/2-general/topic/Renaming.20Huddle.20to.20DirectMessageGroup/near/1848720)
<details> …
=> refactor: Complete rename of `huddle` to `direct_message_group` in non api files.

zerver/models/clients.py
The last desktop client to use that was 0.5.8, released 2017-04-12. There are no clients with such old versions still observed in the wild.
Fixes: 
<details>
</details>
=> clients: Drop "desktop app" substring check.

docs/overview/changelog.md
=> docs: Note required OS upgrade in upgrade notes.

web/src/info_overlay.ts, web/styles/rendered_markdown.css, web/templates/markdown_timestamp.hbs, web/tests/rendered_markdown.test.js
This updates the icon in use on Zulip timestamps as well as in the message formatting tab of the information overlay.
Fixes: #28830
| --- | --- |
| ![clock-icon-before](https://github.com/user-attachments/assets/cb943b56-afc9-4c3e-8ce6-5ee54c047bb3) | ![clock-icon-after](https://github.com/user-attachments/assets/296cf9fe-37ef-401a-9fd3-4264e826ed20) |
| ![overlay-clock-icon-before](https://github.com/user-attachments/assets/6446c7cf-3452-4538-b0f9-ee0d2356508a) | ![overlay-clock-icon-after](https://github.com/user-attachments/assets/5e60c6b8-82d3-4d5a-9bd0-a08e41613cde) |
<details> …
=> rendered_markdown: Update markdown timestamps to use Zulip icon.

.eslintrc.js, help-beta/.gitignore, help-beta/README.md, help-beta/astro.config.mjs, help-beta/package.json, help-beta/src/content/config.ts, help-beta/src/env.d.ts, help-beta/tsconfig.json, help/channel-permissions.md, pnpm-lock.yaml, pnpm-workspace.yaml, scripts/lib/node_cache.py, templates/zerver/development/dev_tools.html, tools/build-help-center, tools/convert-help-center-docs-to-mdx, tools/run-dev, tsconfig.json, version.py
Fixes: #30451 (refer this to see what is not supported right now)
Have a look at the README to see how the commands work. This PR has 1 preparatory commit. `./tools/convert-help-center-docs-to-mdx` is used to convert the existing help center files, the includes files are not part of the conversion yet, they should be converted in stage 2 in its own issue. We'll use `run-dev` with different flags to run this project. Production environment specific config will be done at the end of the project.
<details>
<summary>Example page</summary>
</details>
<details> …
=> Help center stage 1

web/src/settings.js, web/src/settings_panel_menu.js, web/src/user_card_popover.js, web/templates/popovers/user_card/user_card_popover.hbs, web/templates/settings/account_settings.hbs, web/templates/settings/profile_settings.hbs
- First commit is to show the right section correctly when increasing screen width.
- Second commit is to always show the left section only when opening overlays in narrow screens.
Fixes:  https://chat.zulip.org/#narrow/stream/9-issues/topic/settings.20overlay.20on.20small.20screen.20sizes
<details>
</details>
=> Fix settings overlay for narrow screens.

web/src/lightbox.ts
=> lightbox: Correct media types to include HTMLImageElement

help/channel-permissions.md
Fixes #31286.
While our current implementation of help center renders the table without those three dashes, our new help-beta using starlight needs those 3 dashes there.
Fixes: 
Current help center table works as before:
Help-beta table also works now:
<details>
</details>
=> help: Add missing `---` three dash for tables.

web/templates/popovers/user_card/user_card_popover.hbs
Fixes https://chat.zulip.org/#narrow/stream/101-design/topic/user.20card.20for.20deactivated.20users/near/1913800
Active user:
Deactivated user:
Active bot:
Deactivated bot:
<details>
</details>
=> user_card_popover: Show `Manage the user` row for deactivated users.

help-beta/package.json, pnpm-lock.yaml, version.py
Also ran pnpm dedupe after the upgrade.
<details>
</details>
=> dependencies: Upgrade @astrojs/starlight to 0.25.4.

tools/test-js-with-node, web/src/dropdown_widget.ts, web/src/people.ts, web/src/settings_profile_fields.ts, web/src/state_data.ts, web/src/types.ts, web/src/user_card_popover.js, web/src/user_profile.js, web/src/user_profile.ts
1st commit in an improvement done to ease the Type and operand handling.
2nd commit is a bug visible in production where it shows `/undefined` in the link but redirect to `/general`
<details>
</details>
=> user_profile: Convert module to TypeScript.

api_docs/changelog.md, api_docs/include/rest-endpoints.md, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_openapi.py
Adds API documentation for `/export/realm` endpoints.
<p>
</p>
</details> 
<details>
</details>
=> api_docs: Document "/export/realm" endpoints.

zerver/webhooks/jira/doc.md, zerver/webhooks/jira/tests.py, zerver/webhooks/jira/view.py
This PR fixes:
- Comment-related events not containing issue links.
- Outdated instructions to set up the Jira integration.
Fixes part of: [CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Jira.20.28Cloud.29.20integration.20problems)
- Current commented event notification.
- Updated "comment" event notification.
- "New" Jira Site administration page. 
- Updated Jira doc.
<details>
</details>
=> integrations: Update notifications for commented events in Jira integration.

puppet/zulip/files/nagios_plugins/zulip_app_frontend/check_send_receive_time, zerver/lib/server_initialization.py, zerver/migrations/0563_zulipinternal_can_delete.py, zerver/migrations/0564_purge_nagios_messages.py
This prevents building up a large number of messages in the database.
<details>
</details>
=> nagios: Clean up after ourselves.

zerver/migrations/0564_purge_nagios_messages.py
=> migrations: Fix missing Literal() calls in 0564.

web/src/add_subscribers_pill.ts, web/src/invite_stream_picker_pill.ts, web/src/stream_pill.ts, web/tests/stream_pill.test.js
This is a pure refactor with no intended functional changes.
=> stream_pill: Use stream id instead of stream name.

tools/test-js-with-node, web/src/echo.js, web/src/echo.ts, web/src/message_lists.ts, web/src/message_store.ts, web/src/people.ts, web/src/server_events.js, web/src/server_message.ts, web/tests/compose.test.js, web/tests/echo.test.js, web/tests/people.test.js, web/tests/server_events.test.js
=> echo: Convert module to TypeScript.

corporate/lib/stripe.py, corporate/tests/test_support_views.py
=> support: Reject attempts to approve sponsorship for deactivated orgs.

help-beta/astro.config.mjs
Fixes #31250.
<details>
</details>
=> help-beta: Remove prev/next buttons at the bottom. 

web/src/filter.ts
Since we will be checking if a filter is equal to the filter of different message list data objects, it makes to have this operation be optimized.
=> Optimize filter comparison.

zerver/openapi/openapi.py, zerver/openapi/zulip.yaml, zerver/tests/test_openapi.py
Fixes part of #30458.
[CZO discussion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/Support.20schema.20examples.20in.20our.20API.20docs.20generator.2C.C2.A0.2330458/near/1910596)
Fixes: 
<p>
</p>
</details> 
<details>
</details>
=> api-docs: Handle multiple examples in `responses`.

zerver/lib/narrow.py, zerver/tests/test_message_fetch.py
=> narrow: Do not error when given an empty DM recipient list.

web/styles/dark_theme.css
This replaces a :disabled selector with individual ones for each element type; I verified in CSS selector profiling that this change removes lines that were previously about 10% of profiled CSS selector processing time for rendering the combined feed.
The reason being that the rendered elements have very few disable-able elements, but the browser was spending a lot of time trying to match **every** element for whether it might have been disabled, which was slow.
This probably reflects a browser bug.
Fixes: 
<details> …
=> css: Explode dark theme disabled rule.

docs/git/setup.md
PR updates the stale links in [Set up Git docs](https://zulip.readthedocs.io/en/latest/git/setup.html):
[Updated docs link](https://zulip--31360.org.readthedocs.build/en/31360/git/setup.html#install-and-configure-git-join-github)
<details>
</details>
=> docs: Update the stale links in "Set up Git" docs.

zerver/openapi/zulip.yaml
Updates the description of the `topics` array that is returned by `/api/v1/users/me/{stream_id}/topics` to clarify that it is sorted by recency, i.e., the topic with the latest/most recent message is ordered first.
See [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/Does.20get-stream-topics.20returns.20a.20sorted.20list.20of.20topics.3F/near/1916151).
---
**Screenshot of updated response description for "Get topics in a channel"**:
[Current documentation](https://zulip.com/api/get-stream-topics#response)
---
<details> …
=> api-docs: Update topics array description in get-stream-topics response.

scripts/setup/apt-repos/teleport/jammy.list
=> kandra: Bump Teleport version to 16.

docs/production/system-configuration.md, puppet/zulip/files/postgresql/env-wal-g
=> wal-g: Support setting the compression method.

web/src/user_card_popover.js
Fixes #31345.
We were using `e.target` as the popover element for the person picker which meant that the popover would either open just beside the user's image or the user's name text, both of which would cover the close icon. The popover element is now the entire pill by using `e.currentTarget`.
Custom profile field person picker:
Channel settings person picker:
Channel settings user group picker:
<details> …
=> user_card_popover: Pass correct popover element for person picker.

templates/zerver/app/index.html, web/src/postprocess_content.ts, web/templates/message_avatar.hbs, web/tests/postprocess_content.test.js, zerver/views/home.py
=> Lazy loading of images and videos, preconnect

zerver/lib/users.py, zerver/tests/test_subs.py, zerver/views/streams.py
Fixes #21820.
[principal_to_user_profile](https://github.com/zulip/zulip/blob/main/zerver/views/streams.py#L84) acts as a bottleneck when converting `principals` to `UserProfile`,  during stream creation, as it executes `O(n)`  queries where `n` is the number of stream subscribers, this is very slow when subscribing large number of users to a channel (stream).
Bulk conversion of `principals` to `UserProfile`s through `bulk_principals_to_user_profiles()` which executes `O(1)` query instead of `O(n)` with the same filters and checks previously used by `principal_to_user_profile()`.
`bulk_principals_to_user_profiles()` is also now used in `remove_subscriptions_backend()` endpoint, to bulk unsubscribe many users more efficiently.
Tested the time taken to create a stream with `10k` …
=> create stream:  Faster stream creation

zerver/actions/message_flags.py, zerver/actions/muted_users.py, zerver/actions/streams.py, zerver/tests/test_message_flags.py, zerver/tests/test_push_notifications.py
Further work for the `send_event` -> `send_event_on_commit` transition.
<details>
</details>
=> Migrate action functions to send event on commit.

web/src/user_profile.ts
Fixes: [Issue from CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/custom_profile_fields.20not.20getting.20updated.20by.20server_events)
https://github.com/user-attachments/assets/b43af159-a323-47b9-8012-8d926a8d00f7
<details>
</details>
=> user_profile: Set original_values in show_user_profile.

help/view-someones-profile.md
Adds instructions regarding how to copy the user profile URL.
Fixes #31093.
<details>
</details>
=> help: Document `Share someone's profile`.

help/keyboard-shortcuts.md, web/templates/keyboard_shortcuts.hbs
=> help: Tweak keyboard navigation docs for combined and DM feeds.

web/src/message_edit.js
This fixes a bug introduced by 9cf9cec.
=> message_edit: Fix type of message id for aborting video.

web/styles/app_variables.css
This removes the alpha channel from table borders in dark mode, eliminating points of "starlight" where borders intersect.
Other fixes like this have involved `color-mix()`, but that is a poor choice in this case because background colors in messages differ from place to place anyway. And calculating a proper color-mix for each variant is clearly way too much overhead for such a minor design feature (note that there already is no alpha channel in light mode, either).
One additional improvement with a non-alpha color here is that borders remain constant even over the darker background of table header rows.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/dark.20mode.20tables.20need.20an.20alphaless.20border.20color/near/1906401)
| …
=> rendered_markdown: Approximate non-alpha dark mode table border color.

web/src/dropdown_widget.ts
When the dropdown widget is repeatedly opened and closed and then an item is clicked, it triggers multiple clicks and `item_click_callback` is called multiple times. This commit fixes that bug.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/dropdown.20widget.20multiple.20triggers/near/1918218)
<details>
</details>
=> dropdown_widget: Fix multiple triggers on item click.

puppet/kandra/manifests/profile/postgresql.pp, puppet/zulip/manifests/profile/postgresql.pp
=> Fix PostgreSQL ordering in kandra

help/status-and-availability.md
=> help: Add a tip to turn off read receipts with invisible mode.

tools/test-js-with-node, web/src/list_widget.ts, web/src/settings_bots.ts, web/src/state_data.ts
=> settings_bots: Convert module to TypeScript.

web/src/user_group_edit.js, web/styles/subscriptions.css
- First commit is to fix the tooltips on disabled setting elements.
- Second commit is to increase the gap between setting elements.
<details>
</details>
=> user_groups: Fix group settings UI.

templates/zerver/footer.html
This commit updates the footer social media links to use target="_blank" and rel="noopener noreferrer". 
By setting target="_blank", external links will open in a new tab. The rel="noopener noreferrer" attribute prevents the new page from accessing the original page's window object and avoiding the leakage of referral information.
Fixes: #31268
[360059941-83545cd7-0dd6-429e-9c38-52e55c1e1170 (1).webm](https://github.com/user-attachments/assets/9ce2d417-2e1e-43e2-9ec5-a7d430a7ec6a)
<details> …
=> footer: Add noopener noreferrer and target=_blank to social links.

help-beta/package.json, pnpm-lock.yaml, version.py
This is needed for #31329 so that sidebar doesn't scroll to top everytime we click on a page down the order
<details>
</details>
=> dependencies: Upgrade @astrojs/starlight to 0.26.1.

templates/zerver/development/dev_tools.html
Fixes
https://chat.zulip.org/#narrow/stream/19-documentation/topic/help-beta.20dev.20tools.20instructions/near/1929409
<details>
</details>
=> dev_tools: Improve instructions for running help-beta.

web/src/user_profile.ts
It is better to have stream dropdown option value, which is the ID of the stream, to be of "number" type.
Also, fixes the assertion error which occurred due to dropdown option having "string" type.
<details>
</details>
=> user_profile: Update stream dropdown option value to be of "number" type.

tools/test-js-with-node, web/src/poll_widget.ts, web/src/submessage.ts, web/src/todo_widget.ts, web/src/widgetize.ts
=> todo_widget: Convert module to TypeScript.

tools/test-js-with-node, web/src/base_page_params.ts, web/src/message_lists.ts, web/src/popover_menus_data.ts, web/src/settings_config.ts, web/src/state_data.ts, web/src/user_topics.ts
=> popover_menus_data: Convert module to TypeScript.

tools/test-js-with-node, web/src/message_fetch.js, web/src/message_fetch.ts, web/src/message_list_data.ts, web/src/message_lists.ts, web/src/message_scroll.js, web/src/message_store.ts, web/src/submessage.ts, web/src/types.ts, zerver/lib/narrow.py
=> message_fetch: Convert module to TypeScript.

docs/subsystems/widgets.md, web/src/compose_fade.ts, web/src/message_list_view.js, web/src/util.ts, web/tests/message_list_view.test.js
This is a collection of various changes required for cleanly converting `message_list_view`. A draft for the full conversion (unfinished) can be found at https://github.com/evykassirer/zulip/pull/10/
=> prep commits for converting message_list_view to typescript

tools/semgrep-py.yml, zerver/actions/message_send.py, zerver/lib/thumbnail.py, zerver/migrations/0576_backfill_imageattachment.py, zerver/migrations/0577_merge_20240829_0153.py, zerver/tests/test_events.py, zerver/tests/test_markdown_thumbnail.py
=> thumbnail: Backfill ImageAttachment rows.

docs/production/system-configuration.md, pyproject.toml, scripts/restart-server, zproject/wsgi.py
=> Wait for rolling restarts during restart-server

web/src/postprocess_content.ts
The filename contains URI-escaped characters, which do not need to be escaped for safety -- they only make the filename in the tooltip less readable.
Fixes: 
<details>
</details>
=> postprocess_content: Un-URI-escape filename in title.

web/src/settings_users.js
Fixes
https://chat.zulip.org/#narrow/stream/9-issues/topic/filters.20are.20not.20working.20properly/near/1923794. This commit also changes the datatype used for the dropdown to number which is more suitable for our case.
Could have made changing the datatype a different commit but didn't think it would be worth a seperate commit for such a small and in our case, a suitable change.
Role:
Search text:
<details> …
=> settings_users: Show previously selected value in role code dropdown.

web/styles/message_row.css
Because avatars and their columns began scaling up in #30579, it is safe to scale the edited/moved messages as part of adjustable information density.
I'm unsure whether this is a candidate for backporting, so I have not included that label.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/message-edit.20notices/near/1933411)
| --- | --- |
| ![message-markers-before](https://github.com/user-attachments/assets/5e039691-5119-431e-9334-7688d3bff1b4) | ![message-markers-after](https://github.com/user-attachments/assets/7c1159cc-704c-4322-9030-bb6d9f289274) |
<details> …
=> message_row: Allow moved/edit markers to scale.

help-beta/astro.config.mjs, help-beta/src/styles/main.css
Dependent on #31424 for a dependency upgrade.
Fixes: https://github.com/zulip/zulip/issues/31251.
Just a sample screenshot, it would be better to just check the sidebar by running the astro dev server:
<details>
</details>
=> help-center-stage-2: Group pages on the left sidebar

help/include/how-to-invite-users-to-join.md, help/include/sidebar_index.md, help/moving-to-zulip.md, zerver/lib/markdown/tabbed_sections.py
To-do's:
- Do some de-duplication / clean up of content on some related pages (Import from X, Setting up your organization pages).
- Deprecate https://zulip.com/help/getting-your-organization-started-with-zulip in favor of this page.
- Consider linking here from landing pages.
- Add a page on choosing a plan.
<details>
<summary>
New page (main tabs only -- pull down the PR for the rest)
</summary>
</details>
<details>
<summary>
Sidebar
</summary>
</details>
=> help: Moving to Zulip

web/src/message_edit.ts
This commit resolves an issue where the formatting buttons in the message edit UI remained disabled after exiting the preview mode and reopening the edit interface. The problem was caused by the preview area not being properly cleared when the edit session ended, leading to an incorrect UI state on subsequent edits.
To fix this, the clear_preview_area function is now called within the end_message_row_edit method. This change ensures that when the edit UI is reopened, all buttons are reset to their correct state, fully functional and ready for use.
Fixes #31503.
**UI Changes:**
https://github.com/user-attachments/assets/e6765233-bc6b-4ac1-91f8-112e6a3a2f3b
<details> …
=> compose: Fix disabled buttons after exiting preview mode in edit UI.

web/src/dropdown_widget.ts
Prep commit for #31359.
The new saved replies feature requires removing saved replies by clicking on
trash icon on dropdown item. So dropdown widget should allow more than
one click without closing it to delete multiple saved replies.
<details>
</details>
=> Preparatory commit for saved replies feature.

web/src/rendered_markdown.ts, web/styles/rendered_markdown.css, web/tests/rendered_markdown.test.js
Fixes: a part of https://chat.zulip.org/#narrow/stream/6-frontend/topic/CSS.20selector.20performance/near/1920156
See https://chat.zulip.org/#narrow/stream/6-frontend/topic/CSS.20selector.20performance.3A.20spoiler-button/near/1934194 on why rendered_markdown.ts was modified. 
| --- | --- |
|  ![Screenshot 2024-09-03 at 10 05 45 PM](https://github.com/user-attachments/assets/241947f8-3652-45f5-a90c-17e12ff2972d)| ![Screenshot 2024-09-03 at 10 05 21 PM](https://github.com/user-attachments/assets/db3c6dce-6568-46bc-8fca-9955704f2c4c)
<details> …
=> css: Use a class for spoiler header text. 

web/src/click_handlers.js, web/styles/dark_theme.css, web/styles/settings.css, web/templates/settings_overlay.hbs
Fixes https://chat.zulip.org/#narrow/stream/101-design/topic/org.20settings.20-.20show.20more.20-.20icon.20alignment/near/1935512
| Before | After | 
| --- | --- |
| <img width="334" alt="Screenshot 2024-09-03 at 3 57 57 PM" src="https://github.com/user-attachments/assets/73ee7752-e3e1-4391-b777-855774c78d74">| <img width="334" alt="Screenshot 2024-09-03 at 3 57 43 PM" src="https://github.com/user-attachments/assets/4e22a361-82ce-44a1-b7a8-0a18eef4bded">
<details> …
=> settings: Make show more tab look similar to other tabs.

zerver/lib/users.py, zerver/tests/test_settings.py
Partially fixes: #20128.
Fixes: 
<details>
</details>
=> users: Allow zero-width-joiners in user names.

web/src/filter.ts, web/tests/filter.test.js
Previously, on narrowing to a direct message using the `with` operator, we used to end up at the last message rather than the last unread message.
This was because while correcting the narrow using the `with` operand, we used to consider all the users of `display_recipient`. This would also include the `current_user`. This is not right because the unread messages for direct messages are bucketed with a `user_ids_string`, that does not include the user id of the current user. Hence, when looked up for the last unread id by the `with` operator, it used to return undefined.
This is fixed by removing the current user's user id from the user ids string if current user is not the only display recipient to the direct message.
Extracted from #31239, as per …
=> narrow: Fix last unread when narrowed to a `dm` message using `with`.

docs/subsystems/index.md, docs/subsystems/thumbnailing.md
=> docs: Add description of thumbnailing system.

docs/subsystems/accessibility.md
In the [Current Doc](https://zulip.readthedocs.io/en/latest/subsystems/accessibility.html#github-issues), the link to "currently open accessibility issues" is not correct.
[Updated Doc](https://zulip--31538.org.readthedocs.build/en/31538/subsystems/accessibility.html#github-issues)
<details>
</details>
=> docs: Fix the "currently open accessibility issues" link.

web/src/stream_settings_ui.js
This PR adds code to add a check if overlay is opened before executing the code
for removing stream from UI on receiving the stream deletion event.
This makes sure that the we do not call code which expects certain UI elements to
be present in the DOM and thus avoid errors in cases where the stream settings UI
is not opened and the related elements are not in DOM.
<details>
</details>
=> stream-settings: Check if overlay is opened when removing stream.

version.py, web/src/upload.ts, web/tests/upload.test.js, zerver/actions/uploads.py, zerver/lib/attachments.py, zerver/lib/email_mirror.py, zerver/lib/test_classes.py, zerver/lib/transfer.py, zerver/lib/upload/__init__.py, zerver/lib/upload/base.py, zerver/lib/upload/local.py, zerver/lib/upload/s3.py, zerver/openapi/curl_param_value_generators.py, zerver/openapi/zulip.yaml, zerver/tests/test_email_mirror.py, zerver/tests/test_events.py, zerver/tests/test_import_export.py, zerver/tests/test_markdown_thumbnail.py, zerver/tests/test_realm.py, zerver/tests/test_subs.py, zerver/tests/test_upload.py, zerver/tests/test_upload_local.py, zerver/tests/test_upload_s3.py, zerver/views/upload.py, zerver/worker/thumbnail.py
Fixes: #29491.
<details>
</details>
=> Use original file name when downloading uploaded attachments

api_docs/changelog.md, api_docs/message-formatting.md, version.py, zerver/lib/markdown/__init__.py, zerver/lib/thumbnail.py, zerver/openapi/zulip.yaml, zerver/tests/test_markdown_thumbnail.py
This lets us reserve the right amount of space in the message feed immediately.
<details>
</details>
=> thumbnail: Put the original dimensions on spinner images.

zerver/tests/test_realm.py
Fixes test that checks for error when invalid value is given for a property in realm. Currently, only properties with type `int` are checked, leaving properties having optional `int` (`(int, type(None))`) type. This commit fixes that.
Fixes: 
<details>
</details>
=> test_realm: Fix `test_invalid_integer_attribute_values`.

web/styles/recent_view.css, web/styles/subscriptions.css
Fixes #21297.
This PR hides the `x` button when the following filter fields are empty:
- "Filter streams" in stream settings.
- "Filter topics" in Recent topics.
| Area | Before | After |
| Recent conversation | ![image](https://github.com/user-attachments/assets/a9548673-f9b9-4ea3-a071-14aef84fec8c) | ![image](https://github.com/user-attachments/assets/16a827f6-0886-427c-a723-6bab096dc524) |
| Stream settings | ![image](https://github.com/user-attachments/assets/2af16d31-caac-4bf0-89e7-35c29a3a3265) | ![image](https://github.com/user-attachments/assets/3cbc3588-0034-445e-801a-e098bd618fdd) | 
<details><summary>Working of Filter streams:</summary>
<p>
</p>
</details> 
<details><summary>Working of Filter topics:</summary> …
=> search: Hide close button in empty filter streams and filter topics.

zerver/actions/realm_settings.py
minor fix
Fixes: 
<details>
</details>
=> chore: update realm_settings.py

tools/test-js-with-node, web/src/echo.ts, web/src/message_events.js, web/src/message_list.js, web/src/message_list_data.ts, web/src/message_list_data_cache.ts, web/src/message_lists.ts, web/src/message_util.ts, web/src/message_view.js, web/tests/echo.test.js, web/tests/example5.test.js, web/tests/narrow_activate.test.js, web/tests/narrow_local.test.js
=> Cache message list data objects.

docs/git/using.md, docs/translating/german.md, docs/tutorials/new-feature-tutorial.md, web/src/fetch_status.ts, web/styles/app_variables.css, zerver/management/commands/send_custom_email.py, zerver/models/messages.py, zerver/tests/test_signup.py, zerver/views/streams.py
fix some comments
<details>
</details>
=> chore: fix some comments

tools/test-js-with-node, web/src/popover_menus.ts, web/src/stream_card_popover.ts, web/src/stream_pill.ts, web/src/ui_init.js, web/styles/app_variables.css, web/styles/popovers.css, web/templates/input_pill.hbs, web/templates/popovers/left_sidebar/left_sidebar_stream_actions_popover.hbs, web/templates/popovers/stream_card_popover.hbs, web/tests/stream_pill.test.js
Fixes #30567.
This PR adds a stream-info-popover when a channel pill is clicked (e.g., in the UI for adding subscribers to a channel).
<details><summary>GIF</summary>
<p>
</p>
</details> 
<details><summary>Pic</summary>
<p>
</p>
</details> 
<details>
</details>
=> popovers: Add stream-info-popover when channel pill is clicked.

web/src/compose_reply.ts, web/src/hash_util.ts, web/src/narrow_state.ts, web/src/stream_data.ts, web/tests/narrow_state.test.js, web/tests/stream_data.test.js
These 3 commits seem finished, and will let us shrink the original PR.
=> Preparatory commits extracted from #31299

web/src/message_events.js
Broken in #31540
Thanks @evykassirer for the ping.
=> message_events: Fix CI failure.

analytics/tests/test_counts.py, tools/rebuild-test-database, zerver/actions/users.py, zerver/data_import/mattermost.py, zerver/data_import/rocketchat.py, zerver/lib/display_recipient.py, zerver/lib/export.py, zerver/lib/narrow.py, zerver/lib/users.py, zerver/models/messages.py, zerver/models/recipients.py, zerver/models/scheduled_jobs.py, zerver/tests/fixtures/mattermost_fixtures/direct_channel/export.json, zerver/tests/test_mattermost_importer.py, zerver/tests/test_rocketchat_importer.py, zilencer/management/commands/populate_db.py, zproject/backends.py
- #27214 
- #31396 
- #30766 (needed for #31396 to not merge conflict)
=> Backport a few more PRs to 9.x

docs/subsystems/widgets.md, tools/test-js-with-node, web/src/compose_fade.ts, web/src/message_list_view.js, web/src/message_list_view.ts, web/src/message_lists.ts, web/src/message_store.ts, web/src/message_viewport.ts
[message_list_view: Create group and message container all at once.](https://github.com/zulip/zulip/commit/93ffd2935814d73799e3569ce989b6cf3e25be0a) is probably the most complicated commit to understand, hopefully the rest are fairly straightforward.
=> message_list_view: Convert module to typescript

web/src/message_list.js, web/src/message_list_view.ts, web/tests/message_list_view.test.js
followup to [#31576](https://github.com/zulip/zulip/pull/31576)
=> message list view typescript followups

web/src/search.ts
By request:
https://chat.zulip.org/#narrow/stream/9-issues/topic/search.3A.20press.20tab.20to.20select.20item.20in.20autocomplete/near/1936714
=> search: Switch to pressing tab able to select typeahead item.

web/src/stream_card_popover.ts, web/src/stream_data.ts, web/src/stream_popover.js, web/src/stream_settings_data.ts
As mentioned by Tim Abott in [this comment](https://github.com/zulip/zulip/pull/31385#discussion_r1752893312):
> Probably this should be refactored to a `stream_data.can_edit_description(sub);` generally we're moving away from direct is_admin
I have added `can_edit_description` function in `stream_data.ts` to check if the user has permission to edit the description of the stream.
<details>
</details>
=> stream_data: Add can_edit_description function.

help/zulip-cloud-billing.md
If there are no spare licenses available, and there are 5*N guest users in the Zulip Cloud organization, then adding a guest user adds an additional license for the current billing period.
<details>
</details>
=> billing: Clarify guest licenses documentation on Zulip Cloud.

templates/corporate/hello.html
=> portico: /hello tweaks

web/src/server_events_dispatch.js, web/src/settings_components.ts, web/src/state_data.ts, web/src/user_groups.ts, web/tests/dispatch.test.js, web/tests/user_groups.test.js
These seem safe and good to merge, and should help shrink the main PR.
=> Preparatory commits extracted from #31527

corporate/views/installation_activity.py
=> installation_activity: Show extra data for `Other` referrer.

web/src/message_list_view.ts
More context in this thread on CZO:
https://chat.zulip.org/#narrow/stream/9-issues/topic/Blueslip.20error.20on.20editing.20a.20message/near/1943476
=> message edit: Fix bug preventing messages from being edited.

web/src/settings_data.ts, web/tests/popover_menus_data.test.js, web/tests/settings_data.test.js, web/tests/stream_data.test.js, zerver/lib/message.py, zerver/lib/streams.py, zerver/lib/user_groups.py, zerver/lib/users.py, zerver/models/users.py, zerver/tests/test_message_delete.py
We do not want to allow guests to delete messages sent by others even when guest
are part of the group which is set to `can_delete_any_message_group` setting.
<details>
</details>
=> message: Do not allow guests to delete messages sent by others.

web/src/localstorage.ts
Commit bca41fd29f0036162730c2029d89f3f103d66323 (#23028, cc @evykassirer) introduced this for `reload.is_stale_refresh_token`, which had always returned `true` because it was operating on the raw JSON string rather than the parsed data.
=> localstorage: Fix removeDataRegexWithCondition to check parsed data

docs/subsystems/hashchange-system.md, tools/test-js-with-node, web/e2e-tests/navigation.test.ts, web/src/activity.ts, web/src/localstorage.ts, web/src/reload.js, web/src/reload.ts, web/src/reload_state.ts, web/src/zulip_test.ts, web/tests/reload.test.js
=> reload: Convert module to TypeScript

web/src/localstorage.ts
This was introduced by commit 8b22b94ab1613f523be01572787a13e3d49c50fd with no actual cleanup mechanism, and has never been used.
=> localstorage: Remove unused expiry feature

web/src/message_view_header.ts
=> message_view_header: Rename current_stream to more accurate current_sub.

web/styles/search.css
Followup to https://github.com/zulip/zulip/pull/31647#discussion_r1767352535
No visual changes
=> search: Hide outline unless focus-visible.

web/tests/stream_data.test.js
followup to this discussion: https://github.com/zulip/zulip/pull/31299#discussion_r1767792427
=> stream_data: Add test cases for getting stream id from slug.

help/share-and-upload-files.md, zerver/openapi/zulip.yaml
=> docs: Adjust for 100MB MAX_FILE_UPLOAD_SIZE.

zerver/openapi/zulip.yaml
=> openapi: Update upload-file example response to add filename.

api_docs/changelog.md, api_docs/include/rest-endpoints.md, version.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_realm_export.py, zerver/views/realm_export.py, zproject/urls.py
This commit adds a new endpoint `export/realm/consents` to fetch the consents of users for their private data exports.
Fixes part of #31201.
<details><summary>changelog</summary>
</img>
</details> 
<details><summary>API Docs 0</summary>
</img>
</details> 
<details><summary>API Docs 1</summary>
</img>
</details> 
<details>
</details>
=> realm_export: Add a new endpoint to fetch private data export consents.

web/templates/settings/integration_events.hbs
This adds a critical missing `.rendered-checkbox` class to the integration events modal, restoring checkboxes in that area.
| --- | --- |
| ![integration-events-checkboxes-before](https://github.com/user-attachments/assets/dd7988a6-b47a-4663-8764-4e996e26eb7a) | ![integration-events-checkboxes-after](https://github.com/user-attachments/assets/70f5ea68-c3ff-4463-8a8b-196096dff03b) |
<details> …
=> integration_events: Restore checkbox in events modal.

web/src/filter.ts, web/tests/filter.test.js
=> filter: Add function to check if we can show the next unread button.

api_docs/changelog.md, zerver/openapi/zulip.yaml
=> tus: Document new API level for TUS endpoints.

help/include/how-to-invite-users-to-join.md, help/moving-to-zulip.md
Fixes: [CZO feedback](https://chat.zulip.org/#narrow/stream/19-documentation/topic/moving.20to.20Zulip.20guide/near/1936569)
=> help: Tweaks to moving to Zulip guide.

tools/test-js-with-node, web/src/message_list_hover.js, web/src/message_list_hover.ts
=> message_list_hover: Convert module to TypeScript.

web/src/user_profile.ts
Previously, we were selecting the wrong input element, which caused an unexpected undefined type error. This change corrects the selector to properly select the input element.
<details>
</details>
=> user_setting: Correct selector for channel input filter.

zerver/actions/realm_export.py, zerver/lib/export.py, zerver/views/realm_export.py, zerver/worker/deferred_work.py
First 6 commits of https://github.com/zulip/zulip/pull/21725 were merged in #31624
This PR includes the next 3 commits (7th, 8th & 9th):
* Removed the 8th commit of #21725 because the metadata returned is not being used in that PR.
<details>
</details>
=> export: Notify all realm admins on realm export.

help/share-and-upload-files.md, templates/corporate/comparison_table_integrated.html, tools/lib/capitalization.py
Notes:
- We should add a link to production docs for how to configure this on a self-hosted server.
Current: https://zulip.com/help/share-and-upload-files
<details>
<summary>
Updated
</summary>
...
</details>
<details>
<summary>
Features table tooltips
</summary>
</details>
=> help: Describe file upload limits.

web/styles/app_variables.css, web/styles/typeahead.css
This PR improves the styling of links in typeahead suggestions, such as in channel descriptions. The links now match the text color and have a 1px half-transparent underline with 0.6 opacity to enhance visual consistency.
**Fixes:** #31005.
**UI Changes:**
| Before (light) | After (light) |
| -------------- | ------------- |
| ![Before screenshot](https://github.com/user-attachments/assets/e22172c7-8e41-47c8-b335-f6cfaac5289f) | ![After screenshot](https://github.com/user-attachments/assets/dd5bd2dc-7a0c-4fba-a91c-5301083f8d1a) |
| Before (dark)  | After (dark)  |
| -------------- | ------------- |
| ![Before screenshot](https://github.com/user-attachments/assets/06487790-2ec5-49da-9a42-0c3baa471004) | ![After screenshot](https://github.com/user-attachments/assets/0686b836 …
=> typeahead: Improve link styling in typeahead suggestions.

web/src/group_setting_pill.ts, web/src/input_pill.ts, web/src/pill_typeahead.ts, web/src/settings_components.ts, web/src/user_group_create.ts, web/src/user_group_edit.js, web/src/user_group_pill.ts, web/src/user_pill.ts, web/tests/pill_typeahead.test.js
- First two commits are preparatory refactors.
- Last commit is to not show guests in the typeahead and also not converting the email into pill for them.
<details>
</details>
=> settings: Do not allow to use guests as members of anonymous groups in new settings UI.

zerver/lib/export.py, zerver/lib/upload/s3.py
[Discussion](https://chat.zulip.org/#narrow/stream/3-backend/topic/Python.20process.20startup.20time/near/1948011).
=> upload: Lazily import boto3

web/src/message_list.ts, web/src/message_view.ts, web/tests/compose_closed_ui.test.js, web/tests/message_list.test.js, web/tests/message_list_view.test.js, web/tests/popover_menus_data.test.js
=> message_view typescript followups

zerver/lib/integrations.py, zerver/lib/test_helpers.py, zerver/tests/test_urls.py
[Discussion](https://chat.zulip.org/#narrow/stream/3-backend/topic/Python.20process.20startup.20time/near/1948244).
=> integrations: Lazily load webhook integrations

puppet/kandra/files/nginx/sites-available/zulip, puppet/kandra/files/nginx/sites-available/zulip-staging
This parallels 02d3fb76660e.
Fixes: 
<details>
</details>
=> kandra: Add localhost access to internal APIs on port 80.

help/custom-profile-fields.md, web/templates/settings/add_new_custom_profile_field_form.hbs, web/templates/settings/edit_custom_profile_field_form.hbs
[CZO thread](https://chat.zulip.org/#narrow/stream/101-design/topic/editable.20profile.20fields/near/1947962)
| ![image](https://github.com/user-attachments/assets/08438ef6-002e-419a-8865-70cbb04a70f8) | ![image](https://github.com/user-attachments/assets/79fe2525-2037-4d09-a3b2-f151b5ca7cc9) |
| ![image](https://github.com/user-attachments/assets/56616194-23fd-45c0-9c1b-277ddec924b6) | ![image](https://github.com/user-attachments/assets/5b35df73-7831-4613-a471-bcb766365d2c) |
| ![image](https://github.com/user-attachments/assets/4e748dee-7518-430a-8dd3-e61fce607859) | ![image](https://github.com/user-attachments/assets/d6a63eb1-b4ac-497b-972d-6f250007d719) | 
<details> …
=> custom_profile_fields: Update label for non-editable field toggle.

puppet/zulip/templates/nginx/zulip-enterprise.template.erb
=> nginx: Fix missing word in comment.

puppet/kandra/manifests/profile/prometheus_server.pp, puppet/kandra/manifests/prometheus/akamai.pp, puppet/kandra/manifests/ses_logs.pp, puppet/kandra/manifests/vector.pp, puppet/kandra/templates/supervisor/conf.d/prometheus_akamai_exporter.conf.template.erb, puppet/kandra/templates/supervisor/conf.d/vector.conf.template.erb, puppet/kandra/templates/vector_akamai.toml.template.erb, puppet/kandra/templates/vector_ses.toml.template.erb
=> kandra: Use vector to plumb SES logs into S3.

templates/zerver/register.html, web/src/portico/tippyjs.ts
This is needed to make sure that user can see the realm name in case it does not fits into the UI and is shown with ellipsis.
Fixes #31676.
<details>
</details>
=> signup: Show realm name in a tooltip on signup page.

zerver/lib/test_helpers.py, zerver/lib/upload/__init__.py, zerver/lib/upload/s3.py, zerver/tests/test_tusd.py, zerver/tests/test_upload_s3.py, zerver/views/tusd.py, zerver/views/upload.py
=> Handle Unicode filenames in TUS uploads

zerver/actions/users.py, zerver/data_import/slack.py, zerver/forms.py, zerver/lib/upload/__init__.py, zerver/lib/upload/base.py, zerver/lib/upload/local.py, zerver/lib/upload/s3.py, zerver/management/commands/convert_slack_data.py, zerver/management/commands/send_password_reset_email.py, zerver/tests/test_slack_importer.py, zerver/tests/test_upload_local.py, zerver/tests/test_upload_s3.py, zerver/views/user_settings.py
This should help avoid future merge conflicts.
=> Preparatory Slack/upload commits extracted from #31686

corporate/lib/stripe.py
The removal of the `stripe_customer_id` when creating a legacy plan actually disconnects any existing information in Stripe about a customer, who may have previously had a paid plan, so we don't want that removal to happen. Instead we get or create the customer associated with the billing session entity.
Also, updates some of the code comments in the function for legacy plan migrations to be clearer.
---
<details>
</details>
=> billing: Keep stripe_customer_id when migrating to legacy plan.

web/styles/alerts.css, web/styles/app_variables.css, web/styles/dark_theme.css
This PR refactor all the theme colors used in `alerts.css` and `dark_theme.css`.
Note:
- Screenshots in before column are taken from main branch.
- # CSS changes for `.alert-content`:
| ![image](https://github.com/user-attachments/assets/dc55a838-32f3-4173-85f6-114d9768f1bd)  | ![image](https://github.com/user-attachments/assets/4b5cf6c5-8568-4c58-8e97-c5e603527749)  |
| ![{7414F1A0-DDE2-42B4-9B7C-D7D8EA50BBAC}](https://github.com/user-attachments/assets/1a471377-f0c8-43df-b9fc-769f7955cdea)  | ![{FB241117-8C3A-4E7F-BF22-4C107404F585}](https://github.com/user-attachments/assets/3df25914-6f8d-424c-93f0-9dcb37f3df47)  |
<details> …
=> Refactor theme colors for `alerts`.

puppet/kandra/manifests/app_frontend_monitoring.pp, puppet/zulip/manifests/app_frontend_base.pp, puppet/zulip/templates/supervisor/zulip.conf.template.erb
This allows its /metrics endpoint to be monitored.
Fixes: 
<details>
</details>
=> puppet: Allow tusd to be exposed on non-localhost.

web/src/scheduled_messages_ui.js
When narrowing to a scheduled channel message from the scheduled message overlay, we need to set the channel ID to be a string, like we do in the drafts overlay UI.
See [CZO issue report](https://chat.zulip.org/#narrow/stream/9-issues/topic/Editing.20scheduled.20message.20deletes.20message/near/1950625).
---
<details>
</details>
=> scheduled-messages-ui: Set channel ID in narrow term to a string.

help/marking-messages-as-read.md
Current: https://zulip.com/help/marking-messages-as-read#mark-all-messages-as-read
Updated:
=> help: Update instructions to mark messages as read.

web/src/message_view_header.ts
To try to figure out why this is happening:
https://chat.zulip.org/#narrow/stream/464-kandra-js-errors/topic/Error.3A.20Failed.20to.20process.20an.20event
=> message_view_header: Add blueslip logging for undefined sub.

zerver/lib/user_groups.py, zerver/tests/test_user_groups.py, zerver/transaction_tests/test_user_groups.py, zerver/views/user_groups.py
- First commit is a refactor commit so that we can use different settings for checking permissions for different things like updating group, adding members, etc.
- Second commit is to add restriction for allowing only group members for managing group.
<details>
</details>
=> Refactor code to check permissions for updating code.

zerver/lib/user_groups.py, zerver/views/user_groups.py
This PR adds `access_user_group_to_read_membership` function so that we can avoid calling
`get_user_group_by_id_in_realm` with "for_read=True" from views functions, which is better for
security since that function does not do any access checks.
Fixes:  https://github.com/zulip/zulip/pull/31749#issuecomment-2384578617
<details>
</details>
=> user_groups: Add `access_user_group_to_read_membership`.

web/styles/app_components.css, web/styles/app_variables.css, web/styles/dark_theme.css
This PR refactor all the theme colors used in `app_components.css` and `dark_theme.css`.
Note:
- Not all uses of `.table-striped`, `.clear_search_button`, and `.dropdown-widget-button` have been captured in screenshots due to the large number of elements with these classes.
- For `.dropdown-widget-button`, dark theme screenshots are not included since no deletions were made for this class in `dark_theme.css`. Only specific instances of `.dropdown-widget-button` were overridden in the dark theme, not all instances of the class.
- Screenshots in before column are taken from main branch.
- # CSS changes for `.demo-organization-warning`:
| `.demo-organization-warning`  | `.demo-organization-warning`  | …
=> Refactor theme colors for `app_components`.

web/styles/app_components.css, web/styles/app_variables.css, web/styles/dark_theme.css
This PR fixes the issue where the dark-theme CSS was not being applied to `kbd` elements in `#message-formatting` and `#keyboard-shortcuts`.
CZO: https://chat.zulip.org/#narrow/stream/9-issues/topic/.60kbd.60.20element.20in.20dark.20theme.2E/near/1937499
Before:
After:
<details>
</details>
=> Fix dark theme styling for `kbd`.

help/introduction-to-channels.md, zerver/lib/markdown/help_relative_links.py
Updates the relative help link for "Browse and subscribe to channels" in help center "Introduction to channels" article.
Fixes #31605.
<details>
<summary>Introduction to channels - without relative link to "Not subscribed" tab of channels overlay</summary>
</details>
<details>
<summary>Introduction to channels - with relative link to "Not subscribed" tab of channels overlay</summary>
</details>
---
<details> …
=> help-relative: Add option for "Not subscribed" tab of channels overlay.

web/src/compose_recipient.ts
When adding or removing recipients for a direct message, the placeholder text may cause a change in the size of the compose box, so this adds a call to `compose_ui.autosize_textarea` when setting that placeholder attribute.
See [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/error.20when.20DMing.20a.20large.20group/near/1945514).
| --- | --- |
| ![Screenshot from 2024-10-01 16-52-01](https://github.com/user-attachments/assets/302eb095-1e8a-41e6-9dd3-9577dd00fb71) | ![Screenshot from 2024-10-01 16-53-28](https://github.com/user-attachments/assets/ba0f017c-a0ab-41cb-b285-00964d232717) 
---
<details>
Communicate …
=> compose-recipients: Resize compose box text area for placeholder.

tools/test-js-with-node, web/src/dropdown_widget.ts, web/src/saved_snippets.ts, web/src/saved_snippets_ui.ts, web/src/server_events_dispatch.js, web/src/state_data.ts, web/src/tippyjs.ts, web/src/ui_init.js, web/styles/compose.css, web/styles/dark_theme.css, web/styles/zulip.css, web/templates/add_saved_snippet_modal.hbs, web/templates/confirm_dialog/confirm_delete_saved_snippet.hbs, web/templates/dropdown_list.hbs, web/templates/popovers/send_later_popover.hbs, web/templates/tooltip_templates.hbs, web/tests/dispatch.test.js, web/tests/lib/events.js, web/tests/saved_snippets.test.js
Adds a new feature for adding saved replies.
Fixes: #31227
<p>
</p>
</details> 
<details>
</details>
=> saved_replies: Add new feature for saved replies.

zerver/tests/test_tusd.py, zerver/views/tusd.py
These files are necessary for the protocol to verify that the file upload was completed successfully.  Rather than delete them, we update their StorageClass if it is non-STANDARD.
=> tusd: Do not delete the .info files.

web/styles/subscriptions.css
The typeahead should not open on clicking the pill container when the container is disabled when the user is not allowed to change the setting.
It can be reproduced only when the container is empty.
Previous behavior
<details>
</details>
=> user_groups: Do not allow click events on disabled pill container.

web/src/echo.ts, web/src/echo_state.ts, web/src/message_events.js, web/src/message_helper.ts, web/src/stream_topic_history.ts, web/tests/echo.test.js, web/tests/stream_topic_history.test.js
Commit 1: Patch the local messages before updating stream_sidebar. (`Preparatory commit`)
Commit 2: Add message to `stream_topic_history` only if it is acked, according to the proposal in https://github.com/zulip/zulip/pull/31167#discussion_r1699112981
[CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/stream.20topic.20history.20storing.20float.20values.20of.20message.20id/near/1905465)
<details>
</details>
=> stream_topic_history: Update history to only store acked message ids.

templates/corporate/development-community.md
Adds some links to web-public channels on the [development community page](https://zulip.com/development-community/#channels-for-code-contributors).
[Current documentation](https://zulip.com/development-community/#channels-for-code-contributors)
[Current documentation](https://zulip.com/development-community/#channels-for-anyone-spending-time-in-the-community)
---
<details>
</details>
=> docs: Add missing links to web-public channels in development community page.

help/manage-user-groups.md, help/setting-up-zulip-for-a-class.md
Right now, we are referring to the roles instead of groups since we have not enabled that UI for these settings.
<details>
</details>
=> help: Refer to group settings for create/manage group at org level.

web/src/blueslip.ts, web/src/channel.ts, web/src/message_view.ts, web/src/sent_messages.ts, web/src/sentry.ts, web/src/transmit.js, web/tests/transmit.test.js
https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/
[Discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/Sentry.2EgetHub.20Deprecated.20after.20rebase/near/1748853).
=> sentry: Address Sentry JavaScript 7.x deprecations

zerver/lib/message.py, zerver/tests/test_event_system.py
=> message: Do not differentiate topics by case when aggregating.

CONTRIBUTING.md
The existing text says to post a GitHub comment "saying that you'd like to work on" the issue.  A lot of new contributors, understandably, take that literally -- they just say they'd like to work on the issue, with no further information.
In particular they don't give any evidence that they've taken the steps we prescribe in the preceding section, of figuring out what code is involved and how they'll approach the problem before they claim it. When I reply asking for that information, very often they haven't done those steps... while sometimes they have, and just hadn't put together from context that that would be a good thing to communicate.
So spell that out explicitly.  Hopefully this will elicit smoother communication from the contributors who have done that work; and for those who …
=> contributor docs: Clarify how to claim a mobile issue

web/src/hashchange.js
Fixes #31701
This fixes a bug where when the user clicks on a near link, the pointer doesn't shift to the `near` linked message. This can be a confusing experience for the user.
=> hashchanged: Retarget near link if clicked on it again.

zerver/actions/message_delete.py, zerver/actions/reactions.py, zerver/actions/submessage.py, zerver/lib/message.py, zerver/tests/test_message_delete.py, zerver/tests/test_retention.py, zerver/views/submessage.py
https://github.com/zulip/zulip/pull/29380#issuecomment-2010731437
<details>
</details>
=> send_event: Fix recipients while sending events.

help/include/view-starred-messages.md, help/star-a-message.md, web/templates/left_sidebar.hbs
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/icon.20for.20starred.20messages.20view/near/1956608)
| --- | --- |
| ![expanded-before](https://github.com/user-attachments/assets/5cc67ca6-e271-4e22-ac80-5bd73fe06b7e) | ![expanded-after](https://github.com/user-attachments/assets/d929af95-ab3d-4821-82f8-cf8c2b5a1bab) |
| ![collapsed-before](https://github.com/user-attachments/assets/a3de51a7-256f-4bbd-bad7-9de7ff456130) | ![collapsed-after](https://github.com/user-attachments/assets/ba80768e-13d4-4ce1-8aba-bd8de12cb9ba) |
<details> …
=> left_sidebar: Use unfilled star icon in sidebar navigation.

puppet/kandra/files/nagios4/commands.cfg, puppet/kandra/files/nagios4/conf.d/services.cfg, puppet/kandra/templates/nagios4/contacts.cfg.template.erb
=> nagios: Switch staging hosts to not page, but send a zulip.

zerver/lib/import_realm.py
This PR fixes a couple bugs reported when importing a Cloud export onto a self-hosted system.
=> Bug fixes for cloud=>self hosted data export.

help/keyboard-shortcuts.md
Clarifies the help center keyboard shortcut documentation for **Send message** and **Insert new line** in the section about the compose box.
**Updates**:
- First, document the keyboard shortcut for **Send message** and **Insert new line** that can be used at all times
- Then, describe the keyboard shortcuts for those actions that are based on the user's ["Enter to send" configuration](https://zulip.com/help/mastering-the-compose-box#toggle-between-ctrl-enter-and-enter-to-send-a-message)
---
[Current documentation](https://zulip.com/help/keyboard-shortcuts#in-the-compose-box)
*non-Mac users*:
*Mac users*:
---
<details> …
=> help: Clarify "Enter to send" keyboard shortcuts.

web/tests/compose_validate.test.js, web/tests/composebox_typeahead.test.js, web/tests/dispatch.test.js, web/tests/people.test.js, web/tests/settings_bots.test.js, web/tests/settings_data.test.js, web/tests/settings_org.test.js, web/tests/typeahead_helper.test.js, web/tests/user_groups.test.js
=> tests: Use override more for realm

tools/test-js-with-node, web/tests/dispatch.test.js, web/tests/lib/index.js, web/tests/lib/zpage_params.js
=> tests: Unmock realm_user_settings_defaults

tools/test-js-with-node, web/src/activity.ts, web/src/attachments_ui.ts, web/src/desktop_integration.js, web/src/desktop_notifications.ts, web/src/electron_bridge.ts, web/src/filter.ts, web/src/lightbox.ts, web/src/narrow_title.ts, web/src/portico/desktop-login.ts, web/src/server_events_dispatch.js, web/styles/lightbox.css, web/styles/settings.css, web/templates/settings/uploaded_files_list.hbs, web/tests/activity.test.js, web/tests/dispatch.test.js, web/tests/filter.test.js, web/tests/notifications.test.js, zerver/lib/import_realm.py, zerver/lib/thumbnail.py, zerver/lib/webhooks/git.py, zerver/management/commands/backup.py, zerver/webhooks/gitlab/fixtures/release_hook__create.json, zerver/webhooks/gitlab/fixtures/release_hook__delete.json, zerver/webhooks/gitlab/fixtures/release_hook__update.json, zerver/webhooks/gitlab/tests.py, zerver/webhooks/gitlab/view.py, zerver/webhooks/slack_incoming/view.py, zerver/worker/thumbnail.py
- #31780 
- #31444 
- #31809
- #31814
- #31849
- #31875 
- #31877 
- #31879 
- #31627
- #31123 
- #31556
=> Backport several changes to Zulip 9.x

web/src/filter.ts, web/tests/filter.test.js
With the starred message icon change for the left sidebar in #31916, this restores parity with the navbar header's icon.
| --- | --- |
| ![starred-header-before](https://github.com/user-attachments/assets/33da6410-efb3-4d6b-ae2e-1e3859d44b4b) | ![starred-header-after](https://github.com/user-attachments/assets/cea92ade-fae0-48ee-89a6-314ad94d885c) |
<details>
</details>
=> starred_messages: Match header to left-sidebar icon.

api_docs/changelog.md, version.py, web/src/user_events.js, web/src/user_group_edit.js, web/src/user_group_edit_members.ts, zerver/actions/create_user.py, zerver/actions/users.py, zerver/lib/events.py, zerver/lib/mention.py, zerver/lib/user_groups.py, zerver/lib/users.py, zerver/openapi/zulip.yaml, zerver/tests/test_events.py, zerver/tests/test_markdown.py, zerver/tests/test_notification_data.py, zerver/tests/test_user_groups.py, zerver/tests/test_users.py, zerver/views/user_groups.py
- First commit is to not include deactivated users in the members list.
- Second commit is to not include deactivated users in the mention data.
- Third commit is to not allow adding or removing deactivated users from groups.
- Fourth commit is to remove unnecessary check.
<details>
</details>
=> Handle group membership for deactivated users.

zerver/actions/create_user.py, zerver/actions/users.py
The user groups, fetched to send events when deactivating or reactivating a user, are ordered by ID so that we can avoid flaky behavior in tests when verifying event details in test_do_deactivate_user and test_do_reactivate_user tests in test_events.py.
Fixes:  https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/main.20failing/near/1959618
<details>
</details>
=> users: Fetch user groups ordered by ID to send events.

web/src/settings_components.ts, web/src/user_group_edit.js
- First commit is to fix showing and hiding save discard buttons.
- Second commit is to refactor the live update code.
<details>
</details>
=> Fix group settings UI.

web/src/settings_components.ts, web/src/settings_data.ts, web/src/settings_notifications.ts, web/src/state_data.ts, web/src/user_groups.ts
Removed "type"/"Type" from schema and type names used for group settings because we want to use "type"/"Type" only for "type of a type" cases.
So, this commit renames-
- anonymous_group_type => anonymous_group_schema
- group_setting_type_schema => group_setting_value_schema
- GroupSettingType => GroupSettingValue
We also had duplicate definitions for GroupSettingType, in state_data.ts and in settings_components.ts. So, removed it from settings_components.ts.
https://github.com/zulip/zulip/pull/31623#discussion_r1795968511
<details> …
=> settings: Clean schemas and types used for group settings.

web/src/message_events.js
When combined feed is cached, moving messages can cause some messages to be missing.
This can be reproduced by moving messages from a muted stream to non muted stream.
Fixed by updating all rendered message lists for the messages that were moved.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.8E.AF.20.E2.9D.93combined.20feed.20missing.20messages
=> message_events: Fix messages missing in combined feed.

api_docs/changelog.md, version.py, web/src/server_events_dispatch.js, web/tests/dispatch.test.js, web/tests/lib/events.js, zerver/actions/realm_settings.py, zerver/lib/event_schema.py, zerver/lib/events.py, zerver/models/realms.py, zerver/openapi/zulip.yaml, zerver/tests/test_events.py, zerver/views/tusd.py, zerver/views/upload.py
[API Design discussion](https://chat.zulip.org/#narrow/stream/378-api-design/topic/max.20file.20size.20upload.20limit/near/1954374)
<details>
</details>
=> realm: Add max file size upload restriction. 

web/src/popover_menus.ts, web/src/sidebar_ui.ts, web/styles/right_sidebar.css, web/templates/popovers/buddy_list_popover.hbs
Addresses two issues raised in #31816 before it was merged.
=> buddy_list: Menu followups to #31816

web/src/settings_config.ts, web/src/settings_exports.ts, web/templates/settings/admin_export_list.hbs, web/templates/settings/data_exports_admin.hbs, web/templates/start_export_modal.hbs
* First commit: #31708
* Second commit:
* Adds modal to select `export_type` + text updates as described in #31201
* Third commit:
* Adds "Type" column to the panel.
<details>
</details>
=> settings_export: Add modal to select export_type before starting export.

web/src/user_group_edit.js
This PR fixes the mistakes made during rebase in 96abf2501a4 and 9bbd6a73167.
<details>
</details>
=> user_group_edit: Fix update_group function.

help/restrict-account-creation.md
=> help: Note that email domain restrictions apply to email changes.

help/configure-who-can-invite-to-channels.md, help/create-a-channel.md, help/create-user-groups.md, help/public-access-option.md, help/restrict-account-creation.md, tools/i18n/update-for-legacy-translations, web/templates/settings/organization_permissions_admin.hbs, web/templates/stream_settings/stream_types.hbs, web/templates/user_group_settings/group_permissions.hbs
See https://chat.zulip.org/#narrow/channel/101-design/topic/name.20permissions.20settings.20consistently/near/1959774
The last commit doesn't exactly fit the bill of the settings discussed on CZO but I think it would still be good to remove that question mark, we can leave that commit off, if we don't want to remove the question mark. 
Organisation settings:
Channel settings:
Group settings:
<details>
</details>
=> Consistently name permission settings.

tools/test-js-with-node, web/src/scheduled_messages_ui.ts
https://github.com/user-attachments/assets/402b790e-38c6-4c6d-8b01-5d2576496ef1
=> scheduled_messages_ui: Convert module to TypeScript.

web/src/message_fetch.ts
**Notes**:
- Updates `handle_operators_supporting_id_based_api` to:
- Use the canonical operator when updating the narrow parameter to use object IDs.
- Just parse, update and stringify the narrow parameter vs the object with all of the parameters to fetch messages.
- Instead of parsing and stringifying the narrow parameter various times, we now build the initial narrow data once, deep copy it, and then update it to use IDs for the operators that support that in the API.
- Also, cleans up some of the code comments to better reflect the current state of narrow and filter data in the web app.
**Questions/Follow-up**:
- We still send the request to the server for unknown channels with the operand set to an empty string, which will always return a `BAD_NARROW` response from the server. See …
=> message-fetch: Refactor building narrow data for load_messages.

web/src/narrow_history.ts
Checking `browser_history.state.changing_hash` was not correct since we were calling `select_id` on message list, which saves the narrow state, before we set `browser_history.state.changing_hash` to `false`. That means, it was not reliable to save the narrow state.
Also, it is possible that `save_narrow_state` is called after URL hash is changed but before we render the new message list. That could result in us saving the narrow state of the previous message list on the new URL. That could lead to a weird bug where message list doesn't change after clicking on a near link but user just gets scrolled in the current message list as per the wrongly saved narrow state.
We fix it by only saving the narrow state when the URL matches the filter set in the current message list.
Tested that using …
=> narrow_history: Correctly check for when we can save the narrow state.

api_docs/changelog.md, docs/overview/changelog.md, help/export-your-organization.md, help/include/not-human-export-format.md, web/templates/settings/account_settings.hbs, zerver/openapi/zulip.yaml
#31989
> @prakhar1144 Could you please fix up this PR with whatever changes are appropriate for the anchor tags I replaced?
<details>
</details>
=> help: Update exports documentation.

web/styles/recent_view.css
This ensures additional space to the left of DM icons, so that the icons do not collide with the "Direct messages" label.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/icons.20too.20close.20in.20recent.20conversations/near/1959608)
| --- | --- |
| ![recent-tight-before](https://github.com/user-attachments/assets/9eb32dd2-185b-4a00-bb77-99f88a7bab3b) | ![recent-tight-after](https://github.com/user-attachments/assets/78abfbb6-8859-46fd-858e-50dc6be11952) |
| ![recent-comfortable-before](https://github.com/user-attachments/assets/e2de6971-9503-47aa-a12c-015211729502) | ![recent-comfortable-after](https://github.com/user-attachments/assets/440c408c-8029-46f8-ad9d-0ad74e67eb36) |
<details> …
=> recent_conversations: Prevent DM label, icon collision.

web/templates/guest_visible_users_message.hbs
**Commit Message:**
invite: Use help_link_widget in guest visible users message.
**Commit Description:**
In the guest visible users message, replace the manual help link implementation with Zulip’s `help_link_widget` template to reduce code duplication and improve maintainability.
Follow-up to commit 3b1877e.
**Fixes:**
No specific issue link, but this change addresses feedback provided in PR review [here](https://github.com/zulip/zulip/pull/31936#discussion_r1802119389) for commit 3b1877e.
| Email Invitation | Invitation Link | Non-Default Channel |
| ---------------- | --------------- | --------------- | 
| ![Email Invitation](https://github.com/user-attachments/assets/676cc2b2-e867-4130-b690-e857e94a1170) | ![Invitation …
=> invite: Use help_link_widget in guest visible users message.

help/change-your-email-address.md
This was pointing to the wrong page.
=> help: Fix incorrect link in help/change-your-email-address.

web/src/settings_components.ts, web/src/settings_org.ts, web/src/state_data.ts, web/src/user_group_components.ts, web/src/user_group_create.ts, web/src/user_group_edit.js, web/src/user_groups.ts, web/styles/subscriptions.css, web/templates/user_group_settings/browse_user_groups_list_item.hbs, web/templates/user_group_settings/group_permissions.hbs
Fixes: #32007 + converts can_mention_group to use pills. 
Also changes the cursor to not allowed on checkmark icon on the group left sidebar when the user cannot leave this group. 
General:
Cannot join this group:
Cannot leave this group:
<details>
</details>
=> Group settings UI tweaks + use pill UI for can_mention_group

zerver/views/invite.py
This PR is a preparatory step for [#31698](https://github.com/zulip/zulip/pull/31698), which introduces functions for accessing email invites and multi-use invites with proper permission checks.
- Added `access_invite_by_id` to retrieve preregistration users by `invite_id`.
- Added `access_multiuse_invite_by_id` to retrieve multiuse invites by `invite_id`.
- Refactored repeated invite access logic into the above helper functions.
<details>
</details>
=> Invite: Add functions to access email and reusable invites by id.

web/styles/subscriptions.css
The CSS for setting min-width was added in 63a7c9061ba to set the width of pill containers used for group settings, but that also applied to pill containers of subscribers in stream creation form.
This PR updates the CSS to be applied only for settings in groups UI.
Fixes:  https://chat.zulip.org/#narrow/channel/9-issues/topic/extra-wide.20pills.20in.20subscribers.20preview
<details>
</details>
=> stream_creation: Fix subscriber pills being too long.

web/src/todo_widget.ts
From [CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20todo_list.20tasks.20are.20ignored.20.2331611/near/1952988) and follow-up to #31634:
Reusing `new_task_inbound_data_schema` in the todo widget code to parse two completely different types of things is confusing. So, adding a comment in the code noting that potential refactor here.
---
<details>
</details>
=> todo-widget: Add TODO for inbound/outbound data schema refactor.

api_docs/changelog.md, version.py, zerver/lib/user_groups.py, zerver/openapi/zulip.yaml, zerver/tests/test_user_groups.py, zerver/views/user_groups.py
- First two commits are refactors.
- Third commit is to update the permissions to add subgroups to be based on `can_add_members_group`.
- Fourth commit is to add support to update subgroups using the same endpoint used for updating members.
- Fifth commit is to add support for adding subgroups while creating subgroups.
<details>
</details>
=> Update API for adding and removing subgroups.

templates/corporate/for/business.html, templates/corporate/hello.html, templates/corporate/self-hosting.html, templates/zerver/footer.html
<details>
<summary>
Screenshots
</summary>
</details>
=> portico: Make "Get a demo" button easier to find. (+ typo fix!)

templates/zerver/realm_creation_form.html, web/e2e-tests/realm-creation.test.ts
=> realm_creation: Let user choose their org type.

web/src/settings_users.js
* Commit 1: A small fix to the `zulip.yaml` changes made in #32055 
* Commit 2: A small improvement. Explained in the commit message.
<details>
</details>
=> api_docs: Fix `realm_export_consent` event type docs.

web/styles/subscriptions.css
Fixes: https://github.com/zulip/zulip/pull/32014#pullrequestreview-2372178148
<details>
</details>
=> Hide close icons if user cannot manage group.

help/create-user-groups.md, help/include/how-to-create-a-user-group.md, help/include/user-groups-intro.md, help/manage-user-groups.md, help/user-groups.md
Update for recently added functionality.
- Lots of changes on https://zulip.com/help/manage-user-groups.
- The new intro also appears on https://zulip.com/help/user-groups.
- Updated https://zulip.com/help/create-user-groups
<details>
<summary>
Create user groups screenshot
</summary>
</details>
I think we'll need additional documentation about the overall groups model, but this can be done as a follow-up.
=> help: Improve groups documentation.

templates/corporate/why-zulip.html, web/styles/portico/landing_page.css, web/styles/portico/navbar.css
=> portico: Add buttons to Why Zulip hero bar.

web/src/user_group_create_members.ts, web/src/user_group_create_members_data.ts, web/templates/user_group_settings/add_members_form.hbs, web/templates/user_group_settings/new_user_group_users.hbs
This makes the behaviour of this screen similar to the create channel screen where the user does not need to click `Add` button to add users to members preview. This follows most of the logic from that flow for soft removal, syncing between members preview list and the input pills, etc. The current user will have a pill in this case unlike channel creation since a user can create a group without them in it.
Most changes are similar to and built on top of #30610.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.htm …
=> user_groups: Add users to members preview list without add button.

tools/test-js-with-node, web/src/add_group_members_pill.ts, web/src/add_subscribers_pill.ts, web/src/server_events_dispatch.js, web/src/user_group_components.ts, web/src/user_group_create.ts, web/src/user_group_create_members.ts, web/src/user_group_create_members_data.ts, web/src/user_group_edit.js, web/src/user_group_edit_members.ts, web/src/user_group_popover.ts, web/src/user_groups.ts, web/styles/input_pill.css, web/styles/subscriptions.css, web/templates/user_group_display_only_pill.hbs, web/templates/user_group_settings/add_members_form.hbs, web/templates/user_group_settings/new_user_group_subgroup.hbs, web/templates/user_group_settings/user_group_members_table.hbs, web/templates/user_group_settings/user_group_membership_request_result.hbs, web/templates/user_group_settings/user_group_subgroup_entry.hbs, web/tests/dispatch.test.js, web/tests/user_groups.test.js, zerver/tests/test_user_groups.py
- First two commits are for refactoring.
- Third commit is to fix the behavior of pressing enter inside the pill input.
- Fourth commit is to update code for checking whether the user being added to a group is already a member to consider only direct members.
- Fifth commit is to add UI for updating subgroups of existing groups.
- Sixth commit is to add UI for adding subgroups while creating groups.
<details> …
=> Add UI for updating subgroups of a group.

web/src/add_stream_options_popover.ts, web/styles/left_sidebar.css
This PR makes it so that the hover styles and controls are maintained on the Channels heading row while the Channels popover is visible.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/show.20.22.2B.22.20when.20viewing.20menu.20.28left.20sidebar.29/near/1964104)
| --- | --- |
| ![channels-popover-before](https://github.com/user-attachments/assets/edb958d2-6b3f-4950-a053-cf50511d9b9a) | ![channels-popover-after](https://github.com/user-attachments/assets/4b817028-c0ba-4c32-a663-721b13e30381) |
<details> …
=> left_sidebar: Maintain Channels hover state while showing popover.

templates/zerver/realm_redirect.html
Fixes #32042
| --- | --- |
|  ![Screenshot 2024-10-20 at 2 57 22 PM](https://github.com/user-attachments/assets/730321a5-5f5f-4a31-b14b-17abcde0b5e7) | ![Screenshot 2024-10-20 at 2 57 13 PM](https://github.com/user-attachments/assets/f549315c-a52e-4718-978b-ff3c90673019) |
=> realm_redirect: Change bottom text.

web/src/stream_list.ts
This commit configures the click event so that when the user is in a narrow topic of a channel, clicking the same channel will take the user to the channel feed. 
Fixes: #32032 
https://github.com/user-attachments/assets/07ba7ad8-24fa-4caa-9259-d94bf150a612
https://github.com/user-attachments/assets/4ae5242c-e217-4b79-a888-3099d95db3cc
<details>
</details>
=> channel_feed: Configure the click event for channel name click.

web/src/stream_settings_ui.js
When creating the channel using left sidebar menu, the overlay did not focus anywhere. Now to improve it added automatic focus to channel name text field.
Fixes: #32034 
|Before|After|
|----|----|
|<img width="1440" alt="Screenshot 2024-10-20 at 8 31 42 PM" src="https://github.com/user-attachments/assets/888d7815-0ef9-4f77-b9ae-2ca089dc3b2e">|<img width="1440" alt="Screenshot 2024-10-20 at 8 30 52 PM" src="https://github.com/user-attachments/assets/bb5994dd-7b93-46db-a534-a838ed647ffc">|
<details> …
=> channel_name_autofocus: Place the cursor automatically to channel field

tools/test-js-with-node, web/src/user_topic_popover.js, web/src/user_topic_popover.ts
This PR migrates user_topic_popover.js to user_topic_popover.ts.
<details>
</details>
=> user_topic_popover: Convert module to TypeScript.

corporate/views/remote_activity.py
Updates the main query and logic for building the remote activity table to use remote server mobile user/push data for server rows and remote realm mobile user/push data for realm rows.
Screenshots below are from testing in dev environment with 2 registered mobile users on the same remote server:
- 1 without a remote realm
- 1 on the Analytics realm
- 0 on the Zulip Dev realm
<details>
<summary>Remote activity table</summary>
</details>
<details>
<summary>Support view for remote server and realms</summary>
| Server | Dev | Analytics |
| ![Screenshot from 2024-10-24 21-17-12](https://github.com/user-attachments/assets/6f62a1d2-0760-4816-a001-e8d76fa5ac2c) | ![Screenshot from 2024-10-24 …
=> remote-activity: Show remote realm mobile user and push data.

api_docs/changelog.md, version.py, web/src/settings_components.ts, zerver/lib/event_schema.py, zerver/lib/events.py, zerver/models/realms.py, zerver/openapi/zulip.yaml, zerver/tests/test_events.py, zerver/tests/test_invite.py, zerver/tests/test_realm.py, zerver/views/realm.py
Not sure if we need extra tests since we have existing tests that test anonymous groups in `test_realm.py`. 
<details>
</details>
=> Accept anonymous groups for all realm level group settings

web/templates/popovers/user_group_info_popover.hbs
Follow-up for #32100.
<details>
</details>
=> user_group_popover: Remove period after members count.

.github/workflows/production-suite.yml, zerver/lib/storage.py
Tested using `tools/build-release-tarball` and inspecting the resulting tarballs.
=> Fix storage logic for system bot avatars

web/src/stream_list.ts, web/templates/stream_sidebar_row.hbs, web/tests/stream_list.test.js
PR hides the new topic button in left sidebar when user doesn't have permission to post a message in the corresponding stream.
Fixes: zulip#31800.
<details>
</details>
=> Hide new topic button when user doesn't have permission to post a message.

help/manage-user-groups.md
=> help: Add tip mentioning who can join the group.

web/src/add_group_members_pill.ts, web/src/add_subscribers_pill.ts, web/src/user_group_edit_members.ts, web/src/user_groups.ts
- First two commits are preparatory refactors
- Third commit is to not create pills for invalid subgroups.
- Fourth commit is to not show deactivated groups in typeahead and not create pills for them as well.
<details>
</details>
=> Improve UI for adding subgroups.

zerver/data_import/slack_message_conversion.py, zerver/tests/fixtures/slack_message_conversion.json, zerver/tests/test_slack_message_conversion.py
Currently, Slack messages containing hyperlinks (e.g.,<http://foo.com|Foo!>) are converted like normal links. This PR reformats Slack hyperlinks into Zulip-friendly markdown (e.g., [Foo!](http://foo.com)).
This fix is needed so that we can refactor Slack text reformatting functions out of `slack_incoming_webhook` and into `slack_message_conversion` in: 
- #32164.
Part of #31311.
<details>
</details>
=> slack_data_import: Improve hyperlink conversion.

docs/contributing/continuing-unfinished-work.md
[CZO discussion](https://chat.zulip.org/#narrow/channel/2-general/topic/guide.20on.20continuing.20unfinished.20work/near/1966669)
=> docs: Add edits, new section on crediting contributions.

CONTRIBUTING.md
Current: https://zulip.readthedocs.io/en/latest/contributing/contributing.html
<details>
<summary>
Updated
</summary>
</details>
=> contributor docs: Clarify how to find abandoned issues.

web/src/user_group_edit.js, web/styles/subscriptions.css, web/templates/popovers/user_group_info_popover.hbs, web/templates/user_group_settings/user_group_settings.hbs
- First commit is to link to help center from group permissions.
- Second commit is to fix the members text in popover for case where there are only empty subgroups as members of the group.
- Third commit is to fix the disabled state style for group settings.
<details>
</details>
=> Improvements in group settings and group popover.

web/styles/left_sidebar.css
[CZO discussion](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/channel.20filter.20width/near/1972848)
| --- | --- |
| ![filter-topics-row-before](https://github.com/user-attachments/assets/513f11fb-cf18-460e-a812-17f9efbc28f1) | ![filter-topics-row-after](https://github.com/user-attachments/assets/7f3949f6-e122-4ff5-8984-64ebb2fdba7b) |
<details>
</details>
=> left_sidebar: Open up grid for topic filter box.

help/keyboard-shortcuts.md, help/search-for-messages.md, help/user-list.md, web/e2e-tests/message-basics.test.ts, web/src/activity_ui.ts, web/src/buddy_data.ts, web/src/buddy_list.ts, web/src/hotkey.js, web/src/resize.ts, web/src/tippyjs.ts, web/src/user_search.ts, web/styles/right_sidebar.css, web/templates/buddy_list/title_tooltip.hbs, web/templates/keyboard_shortcuts.hbs, web/templates/right_sidebar.hbs, web/tests/activity.test.js, web/tests/user_search.test.js
Fixes #31974.
Ready for review. There might be more things I can pull into prep commits, but I didn't want to leave things in a half-built state so the last commit is a bit big.
=> buddy_list: Redesign top of right sidebar.

templates/zerver/find_account.html, web/styles/portico/portico_signin.css
**Updates**:
- Removes CSS rules with h3 elements that were removed from these templates in commit https://github.com/zulip/zulip/commit/58d00af6c34215a6bdad81ebf8c9169391396ef3.
- Updates CSS rule for "Find your accounts" form tip to use a class instead of the `<i>` element.
---
**Screenshots - No visual changes**:
| --- | --- |
| ![Screenshot from 2024-11-01 14-14-56](https://github.com/user-attachments/assets/d25d1e1e-dc55-4b00-8b33-eaaee275edeb) | ![Screenshot from 2024-11-01 14-17-25](https://github.com/user-attachments/assets/fec8722c-5781-4a92-91c6-6da7c4bd7faf) |
---
<details> …
=> portico: Clean up CSS rules for "Find account" and "Reset password" pages.

tools/test-js-with-node, web/src/demo_organizations_ui.ts
=> demo_organizations_ui: Convert module to TypeScript.

corporate/lib/stripe.py, zerver/actions/invites.py, zerver/actions/user_groups.py, zerver/lib/digest.py, zerver/lib/retention.py, zerver/lib/send_email.py, zerver/management/commands/sync_ldap_user_data.py, zerver/tests/test_push_notifications.py, zerver/views/message_edit.py, zerver/views/reactions.py, zerver/views/user_groups.py, zilencer/views.py
PR addresses https://github.com/zulip/zulip/pull/32135#issuecomment-2445015860
```zsh
$ git grep @transaction.atomic$
confirmation/migrations/0009_confirmation_expiry_date_backfill.py:    @transaction.atomic
zerver/migrations/0377_message_edit_history_format.py:@transaction.atomic
zerver/migrations/0459_remove_invalid_characters_from_user_group_name.py:    @transaction.atomic
zerver/migrations/0460_backfill_realmauditlog_extradata_to_json_field.py:@transaction.atomic
zerver/migrations/0574_backfill_directmessagegroup_group_size.py:@transaction.atomic
zilencer/migrations/0027_backfill_remote_realmauditlog_extradata_to_json_field.py:@transaction.atomic
```
<details> …
=> transaction: Add savepoint=False or durable=True to transaction.atomic decorators.

web/src/invite.ts
Replaces custom-invite-expiration-time with custom-expiration-time-input and custom-expiration-time-unit in the on-change event.
Follow-up for this PR comment: https://github.com/zulip/zulip/pull/32046#discussion_r1826048872
<details>
</details>
=> refactor: Update on-change event to use custom-expiration-time-input.

web/styles/widgets.css
This PR aligns the color of the "edit" pencil button in polls and to-do lists with the color of the message action buttons, ensuring consistency across the interface. The changes cover both the light and dark themes and include:
- **Unhovered State:**  The pencil button color now matches the unhovered state of the message action buttons.
- **Hovered State:**  The color transition on hover for the pencil button matches that of the message action buttons.
<table>
<tr>
<th> Before </th>
<th> After </th>
</tr>
<tr>
<th colspan="2" > Poll </th>
</tr>
<tr>
<td>  <img src="https://github.com/user-attachments/assets/106835fe-e7e1-417b-b137-e49ce1635520" >
</td>
<td>    <img src="https://github.com/user-attachments/assets/672cdb31-acfb-4b4c-83c6-54309336522e" >
</td>
</tr>
<tr>
<td>   <img …
=> update_ui: Standardize pencil icon color for todo and poll.

web/src/copy_and_paste.ts, web/src/hash_util.ts, web/src/topic_link_util.ts, web/tests/copy_and_paste.test.js, web/tests/topic_link_util.test.js, zerver/lib/markdown/__init__.py, zerver/tests/test_markdown.py
To provide a better formatting to /near/ links, we extend the stream-topic mention syntax to include the message id, added after the topic name, separated by `@`. The message id is replaced by 💬 in the rendered message.
Eg, `#**announce>pizza@12345**`
Fixes #31920
[CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/handy.20notation.20for.20near.20links/near/1934657)
<details>
</details>
=> markdown: Format /near/ links nicely.

web/templates/invite_user_modal.hbs
**Updates**:
- Removes the "for" attribute on the **Custom time** label so that clicking on that label does not move the focus to the **Invitation expires after** select element above the custom time inputs.
- Moves a number of the "name" attributes from the nested option elements to the select elements; see  [MDN select element doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attributes) and [MDN option element doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attributes).
- Removes the currently unused "custom_time_choice" class.
- Reorders the attributes in the custom time input and select element so that they are a bit more readable.
---
<details> …
=> invite-user-modal: Clean up of template HTML attributes.

web/src/settings_account.ts
There are two inputs for the add email modal in demo organizations, one to add the email address of the owner and one to update their full name. We want the email input to be selected when the modal is opened.
[Relevant CZO issues conversation](https://chat.zulip.org/#narrow/channel/9-issues/topic/Error.20on.20add.20email.20popover.2E/near/1974174)
| --- | --- |
| ![Screenshot from 2024-11-05 12-18-51](https://github.com/user-attachments/assets/707386a0-af1a-4158-867c-1f0d18ba6542) | ![Screenshot from 2024-11-05 12-18-29](https://github.com/user-attachments/assets/de949864-8bbc-4bb3-a00c-b3d40fb3364a) |
---
<details> …
=> demo-orgs: Specify email input when rendering add email modal.

web/src/user_card_popover.js
Previously, the event handler was targeting the `event.target` element instead of the `event.currentTarget` element. Due to event bubbling, this lead to incorrect element being used to extract the `data-user-id`, resulting in an error whenever a user mention was clicked in the unsaved message in the message box or the drafts view.
| ![unsaved_mentions-before](https://github.com/user-attachments/assets/3e6f9328-ee5f-4273-ba4f-25bf5d87c643) | ![unsaved_mentions-after](https://github.com/user-attachments/assets/2285292e-6b5c-4b10-86d0-d4e15938df59) |
<details>
Individual …
=> user_card_popover: Fix unknown user_id in unsaved message user mentions.

CONTRIBUTING.md
Corrected a minor typo in the "Contributing guide" to improve readability. Changed "do" to "to" on line 287 in CONTRIBUTING.md. 
<details>
</details>
=> Fixed minor typo in contributing guide

help/include/links-examples.md, help/include/links-intro.md, help/link-to-a-message-or-conversation.md
Todo: Update screenshot (pinged @laurynmm )
Current: https://zulip.com/help/format-your-message-using-markdown#links
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/link-to-a-message-or-conversation#get-a-link-to-a-specific-message
<details>
<summary>
Updated
</summary>
</details>
=> help: Document pretty message links.

help/archive-a-channel.md
Initial bullets closely match in-app confirmation modal.
=> help: Document how archived channels work now.

docs/production/upgrade.md
https://chat.zulip.org/#narrow/channel/31-production-help/topic/.E2.9C.94.20Ubuntu.2024.2E04.20server.20upgrade/near/1941859
Tested the upgrade manually, though ran into a hiccup because I initially did `apt remove` instead of `apt purge`, leaving files around and running into the same issue this was supposed to avoid :facepalm:  But effectively the steps end up and should be fine as described, though I didn't redo the full process end to end.
Due to Ubuntu 22.04->24.04 doing an incompatible minor version jump in rabbitmq-server, we need to work around the issue by removing the rabbitmq-server package before upgrading to 24.04.
https://bugs.launchpad.net/ubuntu/+source/rabbitmq-server/+bug/2074309
=> docs: Fix upgrade instructions for Ubuntu 22.04->24.04.

zerver/lib/email_mirror.py, zerver/tests/test_email_mirror.py
Otherwise this leads to an uncaught exception when the check happens later in `check_message`.
=> email_mirror: Check that email gateway bot can send to the channel.

confirmation/models.py, pyproject.toml, zerver/lib/events.py, zerver/lib/types.py, zerver/tests/test_typed_endpoint.py, zerver/views/events_register.py
https://docs.astral.sh/ruff/rules/function-call-in-default-argument/
- Followup to #32316.
=> ruff: Enable B008 function-call-in-default-argument

web/e2e-tests/navigation.test.ts, web/src/stream_list.ts, web/templates/go_to_channel_feed_tooltip.hbs, web/templates/stream_sidebar_row.hbs, web/templates/topic_list_item.hbs
discussed on CZO here: https://chat.zulip.org/#narrow/channel/137-feedback/topic/Clicking.20on.20channel.20while.20focused.20should.20unfocus.20the.20topic/near/1975953
=> stream_list: Add tooltip in left sidebar when clicking opens feed.

web/src/rendered_markdown.ts, web/styles/rendered_markdown.css, web/templates/mention_content_wrapper.hbs
Fixes partially https://github.com/zulip/zulip/issues/26831
[CZO thread](https://chat.zulip.org/#narrow/stream/101-design/topic/more.20user.20indicators/near/1643075)
<details>
<summary>Mention Pill</summary>
<hr></hr>
</details>
<details>
</details>
=> mention_pill: Show bot icon in bot mention pill.

web/src/settings_users.ts
This bug was introduced in 174a4589281 as `this` parameter passed to role_selected_handler was DropdownWidget instance and not the Jquery element for the selected role option.
<details>
</details>
=> settings: Fix filtering users based on role.

web/src/stream_edit.ts
Fixes bug reported here: https://github.com/zulip/zulip/pull/32227#issuecomment-2469769073
CZO thread: https://chat.zulip.org/#narrow/channel/6-frontend/topic/possible.20settings.20regression/near/1979962
=> stream_edit: Fix bug where personal settings weren't being saved.

web/src/settings_components.ts
The setting value for message move limit seconds was not being converted to seconds before checking if the value was allowed or not and that resulted in requests being made for values greater than the allowed values.
<details>
</details>
=> settings: Fix checking max values for message move limit settings.

web/templates/settings/preferences_information.hbs
- Discovered by writing #32366.
=> settings: Fix display of status emoji in “User list style”

web/styles/right_sidebar.css
=> right_sidebar: Add missing right margin to header.

tools/test-js-with-node, web/src/admin.js, web/src/click_handlers.js, web/src/hashchange.js, web/src/settings.js, web/src/settings_panel_menu.ts, web/src/settings_toggle.js, web/src/ui_init.js, web/src/user_card_popover.js
Based off of #32379, merge that first
=> settings_panel_menu: Convert module to typescript.

web/src/settings_components.ts, web/src/user_group_create.ts, web/src/user_group_edit.js, web/templates/user_group_settings/group_permissions.hbs, web/templates/user_group_settings/user_group_creation_form.hbs, web/templates/user_group_settings/user_group_settings.hbs, zerver/actions/streams.py, zerver/actions/users.py, zerver/lib/streams.py, zerver/tests/test_subs.py, zerver/views/streams.py
- First commit is to fix the code being called unnecessary in a loop when it would be fine to just call it once.
- Second commit is a small optmiziation for computing variables only if necessary.
- Third commit is to extract a new function to avoid code duplicaton.
- Fourth and Fifth commits are to optimize computing setting values in stream objects.
- Sixth commit is to use common template for user group permission settings.
- Last commit is to set up setting widgets using a loop.
Fixes:  Includes some follow-ups for #32361.
<details> …
=> Refactor group settings code.

web/templates/compose_banner/compose_banner.hbs, web/templates/modal_banner/modal_banner.hbs
- [Discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/notification.20banners.20-.20undefined.20variables/near/1983028).
- Followup to #32366.
=> templates: Fix @partial-block invocations for explicitPartialContext

docs/production/deployment.md, docs/production/install.md, docs/production/upgrade.md, puppet/zulip/manifests/app_frontend_base.pp, web/src/echo.js, web/tests/echo.test.js, zerver/data_import/mattermost.py, zerver/data_import/slack.py, zerver/lib/email_notifications.py, zerver/lib/retention.py, zerver/lib/thumbnail.py, zerver/lib/upload/local.py, zerver/lib/upload/s3.py, zerver/management/commands/convert_slack_data.py, zerver/tests/test_email_notifications.py, zerver/tests/test_message_notification_emails.py, zerver/tests/test_signup.py, zerver/tests/test_slack_importer.py, zerver/views/registration.py, zerver/webhooks/slack_incoming/tests.py, zerver/webhooks/slack_incoming/view.py
- #32359
- #32174 
- #32170
- #32048
- https://github.com/zulip/zulip/pull/31687
- https://github.com/zulip/zulip/pull/31671
- https://github.com/zulip/zulip/pull/31670
- https://github.com/zulip/zulip/pull/32276
- https://github.com/zulip/zulip/pull/32303
- Slack import commits from #31752
- #32303
- https://github.com/zulip/zulip/pull/32274
- #32387
=> Backport several changes to the 9.x branch

web/src/settings_users.ts
This PR improves the role filter dropdown in **Organization settings > Users** by displaying accurate user counts for each role separately in both active and deactivated sections. Now, role-specific counts are calculated and displayed per user status (active or deactivated), ensuring clarity for administrators managing user roles.
1. **Role-Specific User Counts**:
- Added `count_users_by_role` to compute role-based user counts, formatted as `"Role Name (count)"` (e.g., "Owners (3)"), for both active and deactivated user lists.
2. **Accurate "All Roles" Total**:
- Updated the "All roles" option in each dropdown to show the total count specific to either active or deactivated users, providing a clear summary.
3. **Dropdown Integration by User Section**:
- Enhanced …
=> Enhanced User Role Filter Dropdown with Role-Specific and Total User Counts.

web/src/buddy_list.ts, web/styles/app_variables.css, web/styles/right_sidebar.css, web/styles/zulip.css, web/templates/buddy_list/section_header.hbs
From conversation [here](https://chat.zulip.org/#narrow/channel/101-design/topic/right.20sidebar.20move.20arrow.20to.20left/near/1982115)
without avatars
with avatars
=> buddy_list: Move arrow toggle to the left of the header text.

web/styles/right_sidebar.css
This PR removes empty/offline circles presented with avatars in the right sidebar.
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/display.20status.20and.20profile.20picture.20in.20right.20sidebar.20.2332128/near/1984854)
Fixes: 
| --- | --- |
| ![empty-circle-light-before](https://github.com/user-attachments/assets/670f52fe-6005-421f-8483-009c96a81197) | ![empty-circle-light-after](https://github.com/user-attachments/assets/ea4a67d8-ced8-4ed1-82ab-4bd406de3ef0) |
| ![empty-circle-dark-before](https://github.com/user-attachments/assets/1d8ec74d-243c-4d03-934d-63ecee2ddddc) | ![empty-circle-dark-after](https://github.com/user-attachments/assets/8e4a41b1-a7ea-4608-a265-e831b0f6acdd) |
<details> …
=> right_sidebar: Suppress empty circle over user avatars.

web/src/invite.ts
This PR resets the channels list to be empty (with the default channels checkbox unchecked) when the user selects "Guests" from the role dropdown while inviting users. It includes the following changes:
- When inviting users for guest roles, an empty channel list is displayed instead of the default channel list, and the default channels checkbox is unchecked.
- When inviting users for non-guest roles, the default channels checkbox remains selected (maintaining the old behavior).
- When switching between guest and non-guest roles, the previous state of included channels (if any specified explicitly by the user) for the guest role is restored while inviting a user as a guest.
Fixes: #31988.
**Before Changes**
<details>
<summary>1. Inviting Users as …
=> invitations: Default to empty channel list when inviting guest users.

templates/zerver/development/integrations_dev_panel.html, web/src/bundles/app.ts, web/src/bundles/common.ts, web/styles/portico/integrations_dev_panel.css
This PR removes the final vestiges of `bootstrap-btn.css` from portico, allowing us to move `bootstrap-btn.css` from `common.ts` bundle to just `app.ts` bundle.
Fixes: https://github.com/zulip/zulip/pull/32357#discussion_r1842732416
| ![Screenshot 2024-11-21 at 6 04 03 PM](https://github.com/user-attachments/assets/1882e3f2-71fa-4a59-9553-c6915e9377d1) | ![Screenshot 2024-11-21 at 6 03 10 PM](https://github.com/user-attachments/assets/3ecff87d-9906-4e02-9e6c-ea3a01b068d6) | 
<details> …
=> portico: Remove `bootstrap-btn.css` dependency from portico.

web/templates/poll_modal_option.hbs, web/templates/recent_view_table.hbs, web/templates/settings/bot_avatar_row.hbs, web/third/bootstrap/css/bootstrap.portico.css
This PR removes the `button-secondary`, `button-group` and `bootstrap-btn-group` classes which don't have any corresponding styles attached to them or are no longer in use in the codebase.
Fixes: https://github.com/zulip/zulip/pull/32357#discussion_r1842734544, https://github.com/zulip/zulip/pull/32357#discussion_r1842736088, https://github.com/zulip/zulip/pull/32357#discussion_r1842736921
**Screenshots and screen captures: N/A**
<details>
</details>
=> bootstrap: Remove unused bootstrap button classes.

corporate/lib/stripe.py, corporate/tests/test_stripe.py
For cases where a customer is created in Stripe first for the manual invoice, we want to connect that customer information to our Customer object in the database. That way the customer can access the billing page once the invoice is paid.
<details>
<summary>Support view after invoice has been paid</summary>
*Note credit card icon is not a link in the first image indicating that there is no stripe_customer_id on the Customer object.*
| --- | --- |
| ![Screenshot from 2024-11-20 18-24-22](https://github.com/user-attachments/assets/0d030d1c-612f-4e06-bf0d-e7b827e86f9c) | ![Screenshot from 2024-11-21 17-12-21](https://github.com/user-attachments/assets/1de5bf29-210e-41de-b608-681785b51098) |
</details>
<details>
<summary>Customer billing …
=> billing: Link customer stripe ID for manual fixed-price plan invoices.

tools/lib/capitalization.py, web/src/stream_data.ts, web/templates/settings/group_setting_value_pill_input.hbs, web/templates/stream_settings/stream_types.hbs, web/tests/stream_data.test.cjs, zerver/lib/streams.py, zerver/openapi/zulip.yaml, zerver/tests/test_subs.py
- First commit is to allow admins to unsubscribe others.
- Second commit is to mention the admin privilege with label.
- Third commit is to optimize DB queries for computing group setting values.
Fixes:  https://chat.zulip.org/#narrow/channel/101-design/topic/permissions.20for.20admin.20to.20unsubscribe.20others
<details>
</details>
=> Allow admins to unsubscribe others irrespective of setting.

web/styles/app_variables.css, web/styles/left_sidebar.css, web/styles/right_sidebar.css, web/templates/right_sidebar.hbs, web/templates/subscribe_to_more_streams.hbs
=>  Redesign links at the bottom of left and right sidebars

web/styles/right_sidebar.css
=> buddy_list: Center toggle arrow.

zerver/tests/test_event_system.py
This PR extends the test for the `/api/v1/register` endpoint for spectators by adding an assertion to check the number of database queries.
Fixes: #32409
<details>
</details>
=> tests: Add assertion for database queries count.

web/src/stream_data.ts, web/tests/stream_data.test.cjs
Dropdown widget in compose box and in message move modal should not show archived streams
in dropdown as we do not allow sending messages or moving messages to archived streams.
We need a more focused audit of code for fixing other things where archived streams are shown.
Fixes:  https://chat.zulip.org/#narrow/channel/9-issues/topic/Deleted.20channels.20still.20show.20up.20when.20composing.20message
<details>
</details>
=> streams: Do not show archived streams in dropdown.

zerver/lib/streams.py, zerver/tests/test_subs.py
Since "Nobody" and other user-defined empty groups has no members or subgroups, we need a UserGroup query.
Since we are doing UserGroup query, updated the code to check whether the setting is set to anonymous group or not just after doing UserGroup query and not in membership queries.
Also, added tests to check query count when setting is set to anonymous group.
<details>
</details>
=> streams: Fix handling empty groups when computing setting values.

web/styles/left_sidebar.css, web/styles/right_sidebar.css
As discussed here: https://chat.zulip.org/#narrow/channel/101-design/topic/sidebar.20click.20transitions/near/1986041
=> sidebars: Remove transition when link buttons are clicked on.

zerver/lib/zulip_update_announcements.py
The linter is hanging for me. :(
=> updates: Add update message (level=10).

help/create-user-groups.md, help/include/user-groups-intro.md, help/manage-user-groups.md, help/user-groups.md
Fixes https://chat.zulip.org/#narrow/channel/438-release-management/topic/zulip_updates.20items.20of.20note/near/1988307
=> help: Remove extraneous banner about requiring a paid plan.

web/styles/subscriptions.css
Text shown for empty left and right panels in stream and group settings UI was too faded in light theme, so we make the text a little darker.
Fixes #32212.
<details>
</details>
=> settings: Make the empty panel text darker in light theme.

help/create-user-groups.md, help/include/user-subgroups-intro.md, help/invite-new-users.md, help/manage-user-groups.md, help/user-groups.md
Current: https://zulip.com/help/user-groups
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/create-user-groups
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/manage-user-groups#add-groups-and-users-to-a-group
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/invite-new-users
<details>
<summary>
Updated
</summary>
</details>
=> help: Improve subgroups documentation.

docs/development/setup-recommended.md, docs/development/setup/wsl-rebuild.md
This PR fixes the WSL rebuild documentation present [here](https://zulip.readthedocs.io/en/latest/development/setup-recommended.html#rebuilding-the-development-environment)
Fixes #32402
There is no mention of vagrant installation and setup before this point for the wsl documentation
[CZO](https://chat.zulip.org/#narrow/channel/43-automated-testing/topic/global.2Enavigator.20TypeError.20while.20running.20test-js-with-node/near/1976371) conversation with @timabbott for the same
I have changed the documentation so as to unregister i.e. uninsall wsl distribution and then follow the initial setup steps to rebuild the environment.
A note is appended in the first step to ensure that developers install a fresh instance of WSL and do not reuse an existing one.
Also mentioned the relevant scripts …
=> docs: Fix WSL rebuild steps tab, explicit note to install a fresh instance.

locale/fr/LC_MESSAGES/django.po, web/src/portico/integrations.js
Motivation: https://github.com/zulip/zulip/pull/32424#issuecomment-2492504251 
<details>
</details>
=> Trim trailing whitespace in integration categories.

web/src/buddy_list.ts
followup to https://github.com/zulip/zulip/pull/32501#discussion_r1861330067
=> buddy_list: Always update section hiddenness on populate.

web/src/portico/integrations.js, web/src/portico/integrations.ts, web/webpack.assets.json
=> integrations: Convert module to TypeScript

zerver/lib/events.py, zerver/tests/test_event_system.py, zerver/tests/test_home.py
We already have fetched all the groups that the user is member of, so we can just check if
`can_invite_users_group` is included in that list of groups like we do for similar fields like
`can_create_public_streams`, etc.
Fixes:  #32408
<details>
</details>
=> register: Optmize computing can_invite_others_to_realm.

web/src/buddy_list.ts
Followup to https://github.com/zulip/zulip/pull/32470#issuecomment-2504958549
=> buddy_list: Show unsubscribed participants in participants list.

web/src/filter.ts, web/src/message_events.js, web/src/message_events_util.ts, web/src/message_fetch.ts, web/src/message_list.ts, web/src/message_list_data.ts, web/tests/filter.test.cjs, zerver/lib/narrow.py
=> Mergeable prep commits.

zerver/lib/integrations.py
Fixes: https://github.com/zulip/zulip/pull/32539#issuecomment-2512263888
[CZO topic](https://chat.zulip.org/#narrow/channel/101-design/topic/Renaming.20the.20SVN.20integration/near/1991424)
<details>
</details>
=> Use Subversion name for svn, remove former name "Hudson" from Jenkins.

web/styles/popovers.css
Fixes channel name overflow in dropdown widget after selecting a long channel name.
**Before:**
**After:**
<details>
</details>
=> Fix overflow in channel dropdown widget in user profile.

web/templates/invite_user_modal.hbs
Placeholders for channels and groups pill inputs are updated to
"Add channels" and "Add user group" to maintain consistency.
Fixes:  https://github.com/zulip/zulip/pull/30299#issuecomment-2501771920
<details>
</details>
=> invite: Fix placeholder for pill inputs.

corporate/lib/stripe.py
Updates `next_invoice_date` since, as of commit caba57fe1e0d, we no longer consider the plan's billing schedule (annual or monthly) when invoicing for additional licenses.
---
<details>
</details>
=> stripe: Update next_invoice_date for current logic of monthly invoices.
