web/styles/portico/comparison_table.css
This PR ensures that once comparison-table tabs are clicked, adding an ID of `showing-tab-xxx`, that those tabs override the classes added for the sake of cloud vs. self-hosted vs. all-plan feature comparisons.
We can't simply remove the problem classes (`.showing-cloud`, `.showing-self-hosted`) when users browse the features table via the comparison tabs, because those classes are necessary for showing the correct plans comparisons and sponsorship and questions boxes.
This has been tested at both /plans/ and /features/
Choosing All Plans with Cloud default:
| --- | --- |
| ![plans-page-before](https://github.com/user-attachments/assets/34300f10-99bf-4cef-acdf-cf66c84aba6a) | …
=> portico: Ensure comparison tabs take precedence over plans.

api_docs/changelog.md, tools/test-js-with-node, version.py, web/src/attachments.ts, web/src/attachments_ui.ts, web/src/message_edit.ts, web/templates/confirm_dialog/confirm_delete_detached_attachments.hbs, zerver/actions/message_edit.py, zerver/actions/scheduled_messages.py, zerver/actions/uploads.py, zerver/lib/test_classes.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_edit.py, zerver/views/message_edit.py
When a user edits a message, attachments can be removed or changed. When the user hits 'save', if any attachments are removed, a modal will pop up asking the user to delete them.
**Notes:**
Currently when you try to upload multiple files, the app will throw random errors and is independent of these changes as discussed in [CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/blueslip.20error.20due.20to.20originalevent.2Eerror.20being.20null)
Fixes: #25525.
<details> …
=> uploads: Ask users to delete uploaded files when removed from edited message.

web/src/compose_send_menu_popover.js, web/src/server_events_dispatch.js, web/src/settings.js, web/src/settings_config.ts, web/styles/components.css, web/styles/dark_theme.css, web/styles/settings.css, web/templates/settings/organization_user_settings_defaults.hbs, web/templates/settings/preferences_general.hbs
Addresses user research feedback by duplicating the "Enter Sends Message" setting in the Settings > Preferences menu, specifically within the General section, ensuring users can easily locate and configure this option.
This PR attempts to complete the original work done by #29111 completion candidate PR.
CZO: https://chat.zulip.org/#narrow/stream/6-frontend/topic/checkbox.20styling.2E
Fixes: https://github.com/zulip/zulip/issues/29083.
SETTINGS/DEFAULT USER SETTINGS:
SETTINGS/PREFERENCES:
<details> …
=> settings: Improve visibility of "Enter Sends Message" setting #29083.

zerver/models/users.py, zerver/tests/test_bots.py
Imported Slack bots currently do not have owners (#23145).  Soften the deactivation codepath to allow them to be successfully deactivated despite this.
<details>
</details>
=> users: Soften assumptions that all bots have owners.

tools/semgrep-py.yml, zerver/actions/message_send.py, zerver/lib/thumbnail.py, zerver/migrations/0576_backfill_imageattachment.py, zerver/tests/test_events.py, zerver/tests/test_markdown_thumbnail.py
Backport of #31468.
<details>
</details>
=> 9.x: Backfill ImageAttachments

puppet/kandra/files/nginx/sites-available/zulip-staging
It is not configured in the ALB's rules, nor does the ALB ever forward to port 80.
Fixes: 
<details>
</details>
=> kandra: We do not serve staging from staging.zulip.com:80.

web/src/server_events_dispatch.js, web/src/settings_account.js, web/tests/dispatch.test.js
This PR fixes the live-update bug in [the "Privacy" subsection of  user-settings.](https://chat.zulip.org/#settings/account-and-privacy)
These three were not live-updated:
* Let recipients see when I'm typing direct messages
* Let recipients see when I'm typing messages in channels
* Let others see when I've read messages 
Also, includes small code restructuring to better organise the code.
<details>
</details>
=> settings: Fix live-update bug for privacy settings. 

templates/zerver/emails/custom_email_base.pre.html, templates/zerver/emails/custom_email_base.pre.manage_preferences_block.txt, zerver/lib/send_email.py, zerver/tests/test_email_notifications.py
* First commit - remote_server_email: Add 'unsubscribe link' in the mail footer.
<details><summary>See Footer (Before)</summary>
</img>
</details> 
<details><summary>See Footer (After)</summary>
</details> 
* Second commit - custom_email: Add manage_preferences block content to the plaintext version.
<details><summary>Text only version (Before)</summary>
</details> 
<details><summary>Text only version (After)</summary>
</details> 
<details> …
=> custom_emails: Add unsubscribe link in the footer & include mange_preferences block content in the plaintext version.

web/src/messages_overlay_ui.ts
Since `success_message_scheduled_banner` and scheduled message overlay both use `data-scheduled-message-id`, `get_element_by_id` needs to be more specific which selector it wants.
Reproducer:
* Clear all scheduled messages.
* Schedule a message.
* Open scheduled message overlay with the compose success banner for scheduled message displayed.
Fixes https://zulip.sentry.io/issues/5807613209/
=> messages_overlay: Fix multiple IDs selected accidentally.

zerver/actions/message_send.py, zerver/migrations/0377_message_edit_history_format.py, zerver/tests/test_service_bot_system.py, zilencer/management/commands/populate_db.py
With the addition of `Message.type` column with a completely different meaning, we prefer `recipient_type` for variable names in python code when they're actually about the recipient. Here I clean up the occurences that are easy.
What remains and is not easy:
1. `analytics` context. We have the `messages_sent:message_type` CountStat with lots of references to it. We could rename this, but it'll involve a db migration for the `*Count` objects. Do we want to do that?
2. Most of the occurences of `message_type` is in API and events context. This is obviously much harder to clean up. I assume we'll probably leave it as it is for now?
=> Rename some message_type var names to recipient_type in python code

web/src/buddy_data.ts, web/src/buddy_list.ts, web/src/peer_data.ts, web/tests/buddy_data.test.js
Filter out active people from the buddy list in the right sidebar.
Screenshots:
| ![Screenshot from 2024-08-09 23-59-23](https://github.com/user-attachments/assets/adc91d35-55ab-409f-adc0-9692140242c7) | ![Screenshot from 2024-08-10 00-06-08](https://github.com/user-attachments/assets/ad4f20bd-3cf8-4846-a24e-be2f0b58b748) |
CZO: [link](https://chat.zulip.org/#narrow/stream/9-issues/topic/Showing.20deactivated.20users.20in.20buddy.20list)
<details> …
=> buddy_list: Remove deactivated users from right sidebar.

web/styles/message_row.css
This only impacts collapsed Show More buttons in a message with a sender.
Fixes #31221
| --- | --- |
| ![collapsed-show-more-before](https://github.com/user-attachments/assets/866ff73a-471f-446a-be0a-3444ec8c599e) | ![collapsed-show-more-after](https://github.com/user-attachments/assets/a1c17d1f-1819-4cc4-9ef8-74ee94d94bdb) |
<details>
</details>
=> message_row: Reduce space above collapsed Show More button.

docs/translating/translating.md
New guide for consistency to make sure Translators always use the same translation for the same word across Zulip.
=> translation: Add new tip.

api_docs/changelog.md, version.py, web/src/stream_edit_subscribers.ts, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_subs.py, zerver/views/streams.py
As part of our todo in the code, we want to use the unique user IDs instead of emails when processing the results of subscribing users to a channel. These changes apply those changes and streamlines the use of IDs.
<details><summary>Help Center</summary>
<p>
Before:
After:
</p>
</details> 
<details>
</details>
=> channel_subscribe: Use IDs instead of emails when processing results.

web/src/filter.ts, web/src/narrow_state.ts, web/tests/filter.test.js
Previously, in presence of `dm` operators, the `with` operator behaviour in the web client was not consistent with that of the API. For instance, when `with` points to a stream message, while the narrow containing `dm`, rather than correcting narrow to point to the anchor message, it used to remove the `with`.
Similarly, when `with` pointed to a direct message, then it used to narrow to the correct narrow, but `with` used to be removed from the filter.
This commit removes these inconsistencies of `with` in case of `dm` operators, and makes it consistent to those mentioned in the api documentation.
[CZO thread](https://chat.zulip.org/#narrow/stream/378-api-design/topic/topic.20permalinks/near/1907306)
<details> …
=> narrow: Make `with` operator behaviour consistent with API behaviour.

zerver/tests/test_retention.py, zerver/tornado/event_queue.py
As noted in the comment in that block, this is no longer useful.
=> retention: Remove outdated compat block for delete_message events.

web/src/compose_fade.ts, web/src/message_list_view.js, web/src/message_lists.ts, web/src/timerender.ts, web/src/util.ts, web/tests/message_list_view.test.js, web/tests/timerender.test.js
This is a collection of various changes required for cleanly converting message_list_view. Part 1 (merged) was #31448. A draft for the full conversion (unfinished) can be found at https://github.com/evykassirer/zulip/pull/10
=> prep commits (part 2) for converting message_list_view to typescript

web/src/message_events.js, web/src/server_events_dispatch.js, web/tests/dispatch.test.js, web/tests/message_events.test.js
Fixes #31208
Fixes #14510
discussion: https://chat.zulip.org/#narrow/stream/6-frontend/topic/live.20update.20for.20views.20based.20on.20message.20property
Tested by adding / removing the message property for the following views:
```js
const supported_term_types = [
"has-image",
"has-link",
"has-reaction",
"has-attachment",
"is-starred",
"is-unread",
"is-mentioned",
"is-alerted",
// TODO: Implement support for these terms.
// "is-followed",
];
```
Left to implement `is-followed` as a followup since it is not straighforword to implement correctly.
=> message_events: Fix live update for views based on message property.

web/src/typeahead_helper.ts, web/styles/typeahead.css, web/templates/typeahead_list_item.hbs
discussion: https://chat.zulip.org/#narrow/stream/101-design/topic/unsubscribed.20channel.20warning
| --- | --- |
| ![Screenshot 2024-09-11 at 12 50 13 PM](https://github.com/user-attachments/assets/9295d195-5f82-481e-9b22-6bd0459ac97a) | ![Screenshot 2024-09-11 at 12 50 26 PM](https://github.com/user-attachments/assets/3dff1c53-8b4b-4707-8896-e974a74ec274) |
=> typeahead: Remove unsubscribe icon.

scripts/lib/install
5308fbdeacee split out `zulip::postgresql_client`, and 80ef38757aae made it no longer depend on `zulip::postgresql_common`, but directly on `zulipconf('postgresql', 'version', undef)`.  However, the installer depended on recognizing `zulip::postgresql_common` in the list of pulled-in classes to know that we needed to keep the `postgresql.version` setting in `/etc/zulip.conf`.
Update the installer to also recognize `zulip::postgresql_client` as a class which tells us to keep `postgresql.version` in our settings.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-d …
=> install: We need postgresql.version with zulip::postgresql_client too.

web/src/portico/integrations.js
We do want to be notified about 40x errors for potential broken links to integration documentation pages.
---
<details>
</details>
=> integration-docs: Limit client-side error reporting to 40x errors.

zerver/lib/webhooks/git.py, zerver/webhooks/gitlab/fixtures/release_hook__create.json, zerver/webhooks/gitlab/fixtures/release_hook__delete.json, zerver/webhooks/gitlab/fixtures/release_hook__update.json, zerver/webhooks/gitlab/tests.py, zerver/webhooks/gitlab/view.py
This is an improvement to the Gitlab webhook integration to support the `release hook`. It works in the same way as other events processed in the gitlab integration and builds a message with the `release name`, `url` and `description` like this:
Without topic:
Specified topic:
It supports all 3 event actions: create, update and delete.
Fixes:
Adds one of the few hooks not yet supported by the gitlab integration.
=> Gitlab webhook: support release hooks

zerver/tests/test_user_groups.py
Follow-up to #30296.
As `user_groups_in_realm_serialized` converts the `NamedUserGroup.date_created` datetime field into a timestamp, we need to do the same conversion/comparison in the test for this function. And we also need to account for it being `None`.
---
<details>
</details>
=> user-groups: Add helper for date_created comparison test.

web/src/echo.ts, web/styles/message_row.css, web/templates/message_body.hbs, web/templates/message_controls.hbs, web/templates/message_controls_failed_msg.hbs
This PR addresses two key issues related to handling failed message controls and the `locally_echoed` flag during message resends:
1. **Dynamic Rendering of Failed Message Controls**:
Previously, message controls for failed messages were rendered for all messages regardless of their status and only hidden for successfully sent messages. This behavior led to unnecessary rendering. The update introduces dynamic rendering of message controls, ensuring that the controls are only displayed when a message is confirmed to have failed. This is achieved through conditional logic in the Handlebars template.
2. **Fix for `locally_echoed` Flag on Successful Message Resend**:
The `on_success` function within `echo.resend_message` was incorrectly setting the `locally_echoed` flag to `true` after a …
=> echo: Update message controls dynamically for failed messages and fix `locally_echoed` flag.

docs/subsystems/dependencies.md
According to the production requirements page, Debian (not just Ubuntu) is a supported OS, so the dependencies page should also reflect that.
Fixes: Inconsistent documentation between https://zulip.readthedocs.io/en/latest/subsystems/dependencies.html and https://zulip.readthedocs.io/en/latest/production/requirements.html
<details>
</details>
=> docs: Mention Debian as a supported distro

docs/subsystems/typing-indicators.md
This PR fixes https://github.com/zulip/zulip/issues/30665
Earlier: There were outdated pieces of information in the typing_indicators.md in docs. Specifically:
The document stated that typing indicators were only implemented for direct message conversations in the web app.
The roadmap section mentioned adding support for channel conversations as a future feature.
Current: This PR updates the typing_indicators.md file to reflect the current state of typing indicators in Zulip. The changes include:
Updated the introduction to state that typing indicators are implemented for both direct message and channel conversations in the web app.
Modified the server section to mention handling of channel typing notifications.
Added get_channel_typists to the list of API functions in the typing_data.ts …
=> Updated subsystems documentation for typing indicators

web/src/message_view.js
This was missed in the migration that happend in #31326.
Fixes error when pressing `Home` button in message list.
=> message_view: Fix load_local_messages called without superset_data.

zerver/lib/thumbnail.py
Failure to have a stable ordering can lead to deadlocks.
Fixes: 
<details>
</details>
=> thumbnail: Set a stable ordering on ImageAttachment rows for locking.

corporate/tests/test_activity_views.py, corporate/urls.py, corporate/views/audit_logs.py, templates/corporate/support/remote_server_support.html, tools/test-backend
Adds an activity view for a remote server's audit logs.
**Notes**:
- Links to the audit log view via the remote support view in the section with the remote server user counts.
- Activity charts can be sorted by the headers, so one can sort by the "Event time" header to see a chronological view of the audit logs.
- Because this view shows both remote server and remote realm audit logs, the "Audit log ID" column can have duplicates.
- If the "Remote realm host" or "Role count: human" fields are blank, then they aren't applicable (e.g. the audit log is for the remote server or the event type isn't a synced billing events). When that data isn't present (e.g. audit logs created for bulk user creation or pre-8.0 remote servers without remote realm objects), then a string with "N/A" is shown to …
=> activity: Add view for a remote server's audit logs.

web/src/lightbox.ts, web/styles/lightbox.css
This PR makes two fixes to the Lightbox source:
1. It corrects the centering of the lightbox media list, which was lost from `.new-style` rewrites in #31497 (I have a planned follow-up to improve centering and layout in that area, and change the stretched out angle bracket characters to actual Zulip chevron icons.)
2. It addresses an edge case, reported in Sentry, where `media` may be undefined inside `canonical_url_of_media()`. This originates inside of click events (or keyboard-activated click events) on the media list, and protective logic here removes the problem thumbnail and exits the click event when it is clear that the original media is no longer available in the message list.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.E2.9C.94.20.F0.9F.8E.AF.20lightbox …
=> lightbox: Improve Typescript types and handle undefined media.

docs/subsystems/accessibility.md
In Documentation (https://zulip.readthedocs.io/en/latest/subsystems/accessibility.html#github-issues) , the label is written as "@zulipbot add “area: accessibility” " whereas it should be written correctly as "@zulipbot add “accessibility” ".
Fixes:  In "docs/subsystems/accessibility.md"  added the correct label.
Previously :-
After:-
=> Corrected the label name from area:accessibility to accessibility

web/src/todo_widget.ts
This commit corrects the `type` parameter in
`new_task_inbound_data_schema`, which was previously optional but not added as such.
[CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.93.82.20todo_list.20tasks.20are.20ignored.20.2331611/near/1942435)
<details>
Communicated decisions, questions, and potential concerns.
- [] Explained differences from previous plans (e.g., issue description).
- [] Highlighted technical choices and bugs encountered.
Individual commits are ready for review.
- [] Responsiveness and internationalization.
- [] Strings and tooltips.
- [] End-to-end functionality of …
=> todo_widget: Add `type`` as Optional in `new_task_inbound_data_schema`.

web/styles/left_sidebar.css
This corrects a subtle regression introduced back in #31492.
| --- | --- |
| ![filter-brackets-before](https://github.com/user-attachments/assets/3510e5e3-ffc2-4cd2-a95a-f7620c6d9d60) | ![filter-brackets-after](https://github.com/user-attachments/assets/054b5fa1-1630-4868-8073-fc3fcac53430) |
=> left_sidebar: Ensure brackets are not shown while zoomed in.

web/styles/pygments.css
`@extend` can only be used in an element selector, not directly within `@media`.
(Introduced by #30511, but the incorrect syntax came from [my suggestion](https://chat.zulip.org/#narrow/stream/431-redesign-project/topic/code.20span.20colors.3A.20dark.20theme/near/1832576).)
=> styles: Fix invalid CSS generated due to @extend misusage

help/manage-user-groups.md
Follow-up to #31614.
Notes:
- We don't currently have any links to the Delete a user group anchor.
- I removed the warning about it not being undoable, as that's already the content of the confirmation modal.
- Other changes are just to better follow current help center patterns.
Current: https://zulip.com/help/manage-user-groups#delete-a-user-group
<details>
<summary>
Updated
</summary>
</details>
=> help: Replace instructions to delete a group with deactivation.

tools/test-js-with-node, web/src/composebox_typeahead.ts, web/src/group_setting_pill.ts, web/src/input_pill.ts, web/src/pill_typeahead.ts, web/src/settings_components.ts, web/src/settings_config.ts, web/src/settings_data.ts, web/src/settings_org.js, web/src/settings_preferences.ts, web/src/state_data.ts, web/src/typeahead_helper.ts, web/src/user_group_components.ts, web/src/user_group_create.ts, web/src/user_group_edit.js, web/src/user_group_pill.ts, web/src/user_group_popover.ts, web/src/user_groups.ts, web/src/user_pill.ts, web/styles/subscriptions.css, web/templates/user_group_settings/group_permissions.hbs, web/tests/composebox_typeahead.test.js, web/tests/pill_typeahead.test.js, web/tests/typeahead_helper.test.js, web/tests/user_groups.test.js
- First three commits are prep commits with one of them adding a new function to check permission when a setting is set to anonymous group and the other two being code refactors.
- Fourth commit is to add a new module to handle pills for group setting.
- Fifth commit is to not show `role:` for system groups.
- Sixth commit is to add code for typeahead shown for group settings.
- Last commit is to use the pills UI for `can_manage_group` setting.
Part of #28808.
<details> …
=> Use new pills UI for `can_manage_group` setting.

web/styles/tooltips.css
Earlier, mostly in non-English languages, the tooltip labels would force the tooltip hotkey hints to wrap. This PR adds the `white-space: nowrap` property to ensure that the hotkey hint texts are forced to be in a single line.
Fixes: [CZO Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/i18n.3A.20popover.20has.20poor.20keyboard.20shortcut.20formatting/near/1900109)
| ![Screenshot 2024-09-19 at 11 02 55 PM](https://github.com/user-attachments/assets/c44f3bf7-fa66-422f-a68c-7bf0db5976cb) | ![Screenshot 2024-09-19 at 11 02 32 PM](https://github.com/user-attachments/assets/f611cdf9-2fcc-40fa-bf3a-b5efef56efaa) |
<details> …
=> tooltips: Fix hotkey hints wrapping when next to longer tooltip labels.

web/styles/components.css, web/templates/popovers/user_card/user_card_popover.hbs, web/templates/popovers/user_group_info_popover.hbs
This PR increases the contrast for "This user has been deactivated" text in user popover and "This group has been deactivated" text in group popover in both light and dark mode by making the opacity 1 as this is important information and should be clearly visible.
The text color and opacity matches with the role text shown in user popover.
|Before|After|
|------|------|
|![opacity-0 5](https://github.com/user-attachments/assets/973cd700-f4a4-40b6-b55d-ef3dc4568dc9)|![opacity-1](https://github.com/user-attachments/assets/0da1aa9d-01a5-4f06-b47a-59998035db2c)|
|![Screenshot from 2024-09-19 15-15-00](https://github.com/user-attachments/assets/1e73c9ec-b466-4d09-82e1-f6c5777e1b25)|![Screenshot from 2024-09-19 …
=> popovers: Increase contrast of deactivated information text.

web/styles/search.css
before:
after:
reported on CZO here:
https://chat.zulip.org/#narrow/stream/9-issues/topic/clear.20navbar.20search.2C.20keyboard.20navigation/near/1937903
=> search: Fix cutoff focus outline.

web/src/message_list.js
Note that even though we no longer trigger message selection events from within the rerender calls with their different `opts`, it doesn't effect the scroll position and selected id since the events are triggered synchronously and the final message selection event call has the opts of the initial caller.
=> message_list: Avoid recursive calls to message_selected event.

zerver/tests/test_signup.py, zerver/views/registration.py
Aside of what's generally explained in the code comment, this is motivated by the specific situation of import of Slack Connect channels. These channels contain users who are "external collaborators" and limited to a single channel in Slack. We don't have more sophisticated handling of their import, which would map this concept 1-to-1 in Zulip - but we create them as inactive dummy users, meaning they have to go through signup before their account is usable.
The issue is that their imported UserProfile.role is set to Member and when they register, the UserProfile gets reactivated with that role unchanged. However, if e.g. the user is signing up after they received an invitation from the admin, they should get the role that was configured on the invite. In particular important if the user …
=> signup: Mirror dummy user should be registered with role from invite.

web/styles/app_variables.css, web/styles/compose.css, web/styles/dark_theme.css, web/templates/compose.hbs
In the 2024 redesigned button configurations, the compose buttons become outliers. This retains their previous style inherited from .button, allowing that base component class to move forward in #31595, for which this PR serves as prep.
This PR also corrects a regression from the removal of `.new-style` that introduced an undesired `min-width` on the clear-topic button in the compose box.
CZO discussion
_Expanded compose box:_
| --- | --- |
| ![light-expanded-before](https://github.com/user-attachments/assets/edcc119a-d135-429b-9902-22a14ced5ee5) | ![light-expanded-after](https://github.com/user-attachments/assets/65a9c25a-4ffa-4a23-9078-488f5a6ada53) |
|  ![dark-expanded-before](https://github.com/user-attachments/assets/4b8edbf5-7d5 …
=> compose: Decouple compose buttons from button classes.

web/src/buddy_list.ts
This PR changes -
"Others" will on default be collapsed. If it is expanded it will be preserved when switching view.
Fixes #31628
https://github.com/user-attachments/assets/82557cd8-8820-458f-8409-a90a6d89bb7e
<details>
- [x ] Explains differences from previous plans (e.g., issue description).
- [x ] Automated tests verify logic where appropriate.
</details>
=> right-sidebar: Others collapsed by default

zerver/lib/retention.py
If do_delete_messages (and friends) are called for a massive number of messages, the giant list of message ids is passed to Postgres even though chunk_size makes all but the first chunk_size of message ids useless.
Verified with manual do_delete_messages call, with the `django.db` logger enabled, to verify the list gets chunked as it should before being sent in the query.
=> retention: Limit number of ids passed to db in delete messages query.

web/src/composebox_typeahead.ts, web/src/message_edit.ts
This allows any event handlers that are attached to textarea like typeahead to handle the keypress and stop propagation if they successfully handle it.
This fixes a bug where message edit form gets saved on enter keypress instead of selecting the active item in the message edit typeahead.
Introduced in 0696e234bd4ae937ffb9d3c1ace004b48f5414fd.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/broken.20typeahead.20while.20editing
=> message_edit: Attach keydown to $form instead of textarea.

web/src/stream_data.ts
The removed alternative is a subtype of `NeverSubscribedStream` and thus already included.
=> stream_data: Simplify ApiGenericStreamSubscription type

web/src/unread_ops.ts
This bug was introduced in #31299, which replaced the channel name with a string id. It's still valid to send the channel id to the server, but it shouldn't be a string, it should be a number. (See https://zulip.com/api/construct-narrow#channel-and-user-ids)
In the future, we hope to update `NarrowTerm` to allow for integer operands for channel terms.
=> unread_ops: Convert stream ids to integers before sending request to server.

web/tests/lib/index.js
This lets us collect all failures rather than the first failure in each process.
=> test-js-with-node: Keep running after some tests fail

web/src/composebox_typeahead.ts, web/src/people.ts, web/src/typeahead_helper.ts, web/styles/typeahead.css, web/templates/typeahead_list_item.hbs, web/tests/composebox_typeahead.test.js
This PR styles info in typeaheads in a consistent way.
- Pronouns in @-mention typeaheads now don't have parentheses around them and uses css same as that of user emails.
- Slash commands now have extra field info to render supplementary text as secondary without parens.
- Wildcard mention have separate secondary_text field to render wildcard string without parens.
Fixes: zulip#31245.
<details>
</details>
=> Style supplementary info in typeaheads consistently.

web/src/tippyjs.ts, web/templates/tooltip_templates.hbs
Show  specific tooltips for button  `subscribe to/unsubscribe` in channel settings.
Fixes: [#31500](https://github.com/zulip/zulip/issues/31500)
- Added multiple HTML tooltip templates for different button states  subscribed, unsubscribed.
- Updated JavaScript to select and render the appropriate tooltip based on  the current  button's state.
| --- | --- |
| ![subscribe(before)](https://github.com/user-attachments/assets/84e73b5a-c72c-49a4-bb85-edae3f2a2223)| ![subscribe](https://github.com/user-attachments/assets/dabc0de6-bed4-41c2-a5e1-412f6d29e8c0)|
|![unsubscribe(before)](https://github.com/user-attachments/assets/54485914-65ec-4c47-86be-cb42a82bd9bc)| ![unsubscribe](https://github.com/user-attachments/assets/3018e320-a373-4578-b5 …
=>  tooltips: Change tooltip for subscribe/unsubscribe button 

web/src/compose_pm_pill.ts, web/src/composebox_typeahead.ts, web/tests/compose_pm_pill.test.js
This PR changes -
- When composing a DM, if there are already addressees present, we restrict own user suggestion in the typeahead, and not pillify name if you type it out. It should not be possible to add own user to the list of recipients in this case.
- If there are no addressees present, it should be possible to add own user as it is now (so that you can DM yourself). However, if user then adds any other addressees, we clear the current `user_pill` widget.
Fixes: zulip#31629
[Screencast from 18-09-24 04:12:21 AM IST.webm](https://github.com/user-attachments/assets/4b95c520-7aae-4ad0-8355-7e448abffda2)
<details> …
=> Prevent adding yourself as a DM recipient when other recipients are present.

templates/zerver/accounts_accept_terms.html, zerver/forms.py, zerver/views/home.py
Tested by modifying this diff below by checking if the `enable_marketing_emails` value in the db  changed for the logged in user.
```diff
diff --git a/zerver/views/home.py b/zerver/views/home.py
index ffafb969f0..89288d7120 100644
--- a/zerver/views/home.py
+++ b/zerver/views/home.py
@@ -88,7 +88,7 @@ def accounts_accept_terms(request: HttpRequest) -> HttpResponse:
"first_time_terms_of_service_message_template": None,
-        "first_time_login": first_time_login,
+        "first_time_login": True,
"default_email_address_visibility": default_email_address_visibility,
"email_address_visibility_options_dict": UserProfile.EMAIL_ADDRESS_VISIBILITY_ID_TO_NAME_MAP,
"email_address_visibility_admins_only": UserProfile.EMAIL_ADDRESS_VISIBILITY_ADMINS,
@@ -97,7 +97,7 @@ def …
```
=> accounts_accept_terms: Check if imported user wants marketing emails.

web/src/message_edit.ts
There is no `.message_edit_content` in `focus` when user does `tab + enter` to save the message. We use the existing text content edit object get identify the row being edited which is more robust and efficient.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/.E2.9C.94.20broken.20typeahead.20while.20editing
=> message_edit: Fix `tab + enter` broken for saving.

web/src/buddy_data.ts
This is a followup to #31645. I tweaked the filter in `maybe_shrink_list`, but that function works with user ids originally fetched in `get_filtered_user_id_list`, which was only fetching ids of users that had been recently active.
=> buddy_list: Fetch *all* subscribers for small channels in big orgs.

web/src/message_edit.ts
`Enter` keypress on `save/cancel` was not working for users without `should_enter_send` user setting due to it being prevented from triggering default behaviour.
Fixed by only handling enter keypress if pressed inside `message_edit_content` textarea.`
Tested by disabled the `Enter` sends message user setting. Also, tested that tab / enter to typeahead completing works.
This was similarly bugged after 0696e234bd4ae937ffb9d3c1ace004b48f5414fd since we removed
`if ($(e.target).hasClass("message_edit_content")) {`.
=> message_edit: Fix `save/cancel` on message edit form not working.

web/src/user_group_edit.js
Previously, the error was shown besides the group name after the modal was closed, but it did not look good for long error messages like the one we get when the group being deactivated is being used for a setting.
Updated the code to use dialog_widget.submit_api_request since it takes care of showing the error inside the modal and also added code to show loading spinner as the modal is not closed immediately to show the error.
[Discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/Support.20user.20group.20deactivation/near/1946852)
<details> …
=> user_groups: Show deactivation error in modal itself.

web/styles/settings.css, web/templates/settings_overlay.hbs
As a follow-up to cca891689cb5d1168f59f385bdc45cf672c3aeb3, this updates the old bot icon in the Settings UI with the new one antenna bot icon.
[CZO Discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/org.20settings.20-.20show.20more.20-.20icon.20alignment/near/1946176)
| ![Screenshot 2024-09-24 at 1 06 02 AM](https://github.com/user-attachments/assets/272d4e08-d011-4218-abc7-f8251242c14d) | ![Screenshot 2024-09-24 at 1 05 06 AM](https://github.com/user-attachments/assets/0a61aa00-d2a1-47f6-b4a5-d506afae3097) | 
<details> …
=> icons: Update bot icon in Settings UI.

web/src/compose_actions.ts, web/src/compose_setup.js, web/src/pm_list.ts, web/src/stream_list.ts, web/src/topic_list.ts, web/styles/compose.css, web/styles/left_sidebar.css
As stated by Tim Abbott [here](https://chat.zulip.org/#narrow/stream/6-frontend/topic/refactor.20how.20close.20buttons.20are.20handled.20in.20filter.20fields.2E/near/1944067):
>  I think a PR to refactor those 3 would be great.
This PR focuses on refactoring the logic of how close button are handled in Filter topics field in the left sidebar, Filter direct messages field under direct messages and Stream message topic.
| Area | Before | After (no change) |
| FIlter topics | ![image](https://github.com/user-attachments/assets/e8960f5a-7d69-4e1c-b121-eaa52153abe7) | ![image](https://github.com/user-attachments/assets/35ab5725-26ed-4e4f-9c63-38ce8fa5d68e) |
| Filter direct messages | ![image](https://github.com/user-attachments/assets/b0e90949-652a-44cf-8915-460664 …
=> Refactor how close buttons are handled in filter topics, filter direct messages and stream message topics.

web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/message_edit_history.css
This PR refactor all the theme colors used in `message_edit_history_content.css` and `dark_theme.css`.
Fixes: 
<details>
</details>
=> Refactor theme colors for `message_edit_history_content`.

web/src/message_list_view.ts, web/src/timerender.ts
Earlier messages would not display year if it were from current year. This would lead to confusion when the date in a date divider is in a different year from the date in the message header bar above it.
This PR adds
- Show the year in date dividers if it's different from the year of the previous date displayed.
- Show the year in message header bars if it's different from the year of the previous date displayed.
Fixes: zulip#26673.
[Screencast from 08-09-24 03:03:01 AM IST.webm](https://github.com/user-attachments/assets/5cbd3d2d-287c-444e-8fbe-29f6240ccb78)
[Screencast from 08-09-24 03:04:05 AM IST.webm](https://github.com/user-attachments/assets/2a1da74c-462f-4b8c-b949-21a51e48c9cc)
<details> …
=> Display current year in header on year change.

web/src/message_list_tooltips.ts, web/src/message_list_view.ts, web/templates/edited_notice.hbs, web/templates/message_edit_notice_tooltip.hbs
Earlier, we used to compute last_edit_timestr as data-tippy-content when rendering the whole message feed.
This commit changes the behaviour by computing the `last_edit_timestr` when a user hovers over the message_edit_notice.
Fixes: zulip#27240.
<details>
</details>
=> Defer computing last_edit_timestr until tooltip renders.

corporate/lib/activity.py, corporate/views/installation_activity.py, templates/corporate/activity/installation_activity_table.html
Adds an optional boolean parameter for the installation activity view to make the chart more export friendly.
**Notes**:
- There's a prep commit that refactors the installation view to loop over the realm data returned from the query only once. Previously, it was looping over the data multiple times.
- Adding the realm admin emails to the query for the installation activity chart means that the initial data needs to be processed/looped through once to collect the admin emails into one string and to deduplicate realm data.
- The export version of the installation activity chart:
- Removes the initial links column.
- Removes the blank column before the human message counts.
- Adds a final column with the realm owner and admin user emails.
- The realm name in the installation and …
=> Activity: Add export version of installation activity chart.

zerver/webhooks/travis/doc.md, zerver/webhooks/travis/tests.py, zerver/webhooks/travis/view.py
Description: 
Removed the ignore_pull_request form the CI integration. As this functionality is now fully covered by zulip's standard event filtering framework.
Fixes: #30934
<details>
</details>
=> travis_webhook: Removed the ignore_pull_requests from the CI integration

help/include/left-sidebar-conversations.md, help/left-sidebar.md, web/shared/icons/heading-triangle-right.svg, web/src/left_sidebar_navigation_area.ts, web/src/pm_list.ts, web/src/stream_list.ts, web/src/tippyjs.ts, web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/left_sidebar.css, web/styles/right_sidebar.css, web/templates/left_sidebar.hbs, web/templates/more_topics.hbs, web/templates/streams_subheader.hbs
This PR implements new heading typography and expand/collapse icons from @terpimost's [sidebar redesign](https://terpimost.github.io/zulip-sidebar/), as well as new colors on the headings and subheadings.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/proposed.20left-sidebar.20spacing.20and.20alignment/near/1922052)
There are a few things not yet implemented from Vlad's design, all of which are effects-based:
* Hover styles and triangle-rotation effects are not yet implemented on the buddy list subheaders; those will require reworking how buddy lists are added and removed from the DOM, even on clicking expand/collapse
* Drop shadows on the buddy list subheader are not yet implemented; that represents a bit too much churn in an already quite large PR
**Screenshots …
=> sidebars: Place new heading typography, icons, and partial colors.

zerver/lib/export.py, zerver/management/commands/export.py, zerver/management/commands/export_usermessage_batch.py, zerver/models/realms.py, zerver/tests/test_import_export.py, zerver/tests/test_management_commands.py, zerver/tests/test_realm_export.py, zerver/tests/test_user_topics.py, zerver/worker/deferred_work.py
For exporting full with consent:
* Earlier, a message advertising users to react with thumbs up was sent and later used to determine the users who consented.
* Now, we no longer need to send such a message. This commit updates the logic to use `allow_private_data_export` user-setting to determine users who consented.
Fixes part of #31201 
<details>
</details>
=> export_realm: Remove the 'react on consent message' approach.

web/src/message_fetch.ts
This was a bug caused by https://github.com/zulip/zulip/pull/31299/files#r1773871463
CZO thread for error: https://chat.zulip.org/#narrow/stream/464-kandra-js-errors/topic/ZodError.3A.20.5B
I double checked that the logged in behavior still works:
And now the logged out behavior doesn't throw an error, just shows this:
=> message_fetch: Don't allow undefined narrow term operands.

web/src/filter.ts
to reproduce the bug that this fixes:
1. open search bar
2. type `channel: name-that-doesnt-exist topic:foo` and then start typing anything else
=> filter: Fix bug where invalid stream name could throw an error.

web/src/message_events.js
=> message_events: Fix move_message_stream_id type confusion.

zerver/lib/email_notifications.py, zerver/tests/test_message_notification_emails.py
Apparently, Outlook ignores height/width CSS rules, but does support
the attribute on the image element itself, so specify that instead.
I don't think there are likely to be image tag implementations that
don't support the attribute, given that's the only thing that works in
Outlook.
=> email_notifications: Fix emoji being giant in Outlook.

help/keyboard-shortcuts.md, web/templates/keyboard_shortcuts.hbs
Add "Go to inbox" and "Go to recent conversations" entries to the Navigation section of both the in-app shortcuts overlay and the more detailed help center reference.
Fixes: Some "Go to <view>" shortcuts not appearing in the list of navigation shortcuts. See also [this thread in #documentation](https://chat.zulip.org/#narrow/stream/19-documentation/topic/.22Go.20to.20inbox.22.20shortcut/near/1946981).
<details> …
=> docs: Add "Go to inbox" and "Go to recent conversations" navigation shortcuts

web/src/bot_data.ts, web/src/bot_types.ts
My claim here is that `services` is either a full object satisfying `services_schema` or undefined; there was no reason for this `deepPartial` to be deep in the first place.
https://github.com/zulip/zulip/blob/b0ca32c95525f8056985a9ccf9c901be28e8256e/zerver/lib/event_schema.py#L699-L714
https://github.com/zulip/zulip/blob/b0ca32c95525f8056985a9ccf9c901be28e8256e/zerver/actions/users.py#L559-L570
https://github.com/zulip/zulip/blob/b0ca32c95525f8056985a9ccf9c901be28e8256e/zerver/actions/users.py#L582-L589
=> bot_data: Avoid deprecated ZodObject.deepPartial()

corporate/lib/stripe.py, corporate/tests/test_stripe.py, corporate/views/billing_page.py, templates/corporate/billing/billing.html, web/src/billing/billing.ts, web/styles/portico/billing.css
Fixes #28633
Added a button to switch license management type on billing page.
Tested that the plan switch works correctly.
Tested that when switching from manual to automatic license management, customer is only billed for billable users for the next billing cycle.
=> stripe: Allow customer to switch license management type.

templates/corporate/billing/billing.html, templates/corporate/billing/sponsorship.html, templates/corporate/billing/upgrade.html
Logged in users can use the relative links to access the help document. Didn't convert the `zulip.com` links on error pages since the user might not be able to login to see the page.
=> billing: Use relative links for help references.

web/templates/introduce_zulip_view_modal.hbs
Noticed a small grammatical error in the introduction modal when I registered for a new Zulip instance.
<details>
</details>
=> introduce_zulip_view_modal: Fix small syntax problem

web/src/lightbox.ts, web/styles/lightbox.css
This PR corrects for some lingering errors with the lightbox.
1. It ensures proper functioning of the `v` hotkey; on `main` and in production, use of the hotkey will always throw an error when there is more than a single image in a topic. This is likely the source of many Sentry errors.
2. It improves the logic for detecting the selected image by avoiding the use of the canonical URL, which may not be unique in a given topic if users copy and paste an image reference from a previous message. Detecting the selected image is now handled by a short-lived class added to an image clicked on in the message area.
3. It removes any open video players when navigating thumbnails, preventing audio from continuing to play ([CZO issue](https://chat.zulip.org/#narrow/stream/9-issues/topic/lightbox.20vid …
=> lightbox: Better handle duplicate images, hotkey behavior.

corporate/views/installation_activity.py, templates/zerver/register.html, web/src/portico/signup.ts, web/styles/portico/portico_signin.css, zerver/forms.py, zerver/models/realm_audit_logs.py, zerver/views/registration.py
(ignore the empty `advertisement:` fields they were created by mistake and are not actually possible to create by a user filling the form)
=> Modification to how user found zulip input.

web/src/stream_settings_components.js
This was not correctly migrated in 65893292b5d07deab8c118168ce87ab840e0cc5e.
@Joelute FYI -- looks like your `git grep already_subscribed` wasn't done properly.
=> stream_settings: Fix already-subscribed error handling.

web/src/reload.ts
The stream id can be undefined when the compose box is open to start a stream message, but no stream has been selected from the dropdown yet.
Fixes this error introduced in 97ffccb45f85b05c9158ed119c71b6a404afb298
https://chat.zulip.org/#narrow/stream/464-kandra-js-errors/topic/Error.3A.20Failed.20to.20preserve.20state/near/1948680
I tested this manually locally, reproduced the error, and confirmed that undefined and defined stream ids both work now.
=> reload: Handle stream messages without specified stream.

web/src/lightbox.ts
This PR includes fixes suggested by @timabbott on #31775, which was merged before these could be included.
<details>
</details>
=> lightbox: Fixes that didn't make it into #31775.

zerver/migrations/0001_squashed_0569.py, zerver/migrations/0295_case_insensitive_email_indexes.py, zerver/models/users.py
It's nicer to have these indexes properly registered, rather than hidden in RunSQL operations. Now that Django has had support for unique functional indexes for a while, let's clean this up.
=> migrations: Register (UPPER(email), realm) indexes in UserProfile.Meta.

web/src/drafts_overlay_ui.js, web/src/message_edit_history.ts, web/src/scheduled_messages_overlay_ui.js, web/templates/draft.hbs, web/templates/message_edit_history.hbs, web/templates/scheduled_message.hbs, web/templates/scheduled_messages_overlay.hbs
This fixes a bug where when selecting an element using their `class`, items from differnet overlay are selected due to them being not removed from DOM even though they are hidden.
This happens when user tries to open scheduled messages overlay after opening drafts overlay. Drafts overlays is not removed from DOM when hidden. When scheduled messages overlay is open, more than expected number of rows are selected due to usng a generic selector like `overlay-messages-list`.
Sentry - https://zulip.sentry.io/issues/5810649774/?project=4504556882821120
=> Use overlay specific names for `keyboard_handling_context`.

puppet/zulip/manifests/common.pp
This version causes `sentry-cli monitors run` to not fail if Sentry is down (getsentry/sentry-cli#2169).
=> puppet: Upgrade sentry-cli.

help/zulip-cloud-billing.md, zerver/lib/markdown/help_relative_links.py, zerver/lib/templates.py, zerver/tests/test_docs.py
In order to only generate relative links for Zulip Cloud billing specific gear menu options in relevant help center articles, we pass down `settings.CORPORATE_ENABLED` to be set as a global variable for `zerver/lib/markdown/help_relative_links.py` so that self-hosted servers' help center documentation will not have these links.
**Notes**:
- Another option would be to never link the billing gear menu instructions in the help center, which is what is done on the self-hosted billing help center article.
@shubham-padia - Flagging your review on these changes in case they'd negatively impact work towards #31253.
---
<details>
<summary>Gear menu billing not linked when corporate is not enabled</summary>
</details>
<details>
<summary>Gear menu billing linked …
=> help-links: Limit billing related relative gear menu links.

web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/left_sidebar.css, web/styles/right_sidebar.css, web/templates/left_sidebar.hbs
This PR implements the colors for active filters and hovered elements in both sidebars. There have been some minor adjustments to the geometry of row grids to properly accommodate the new hover styles, especially for vdots, but also collapsed navigation items and other rows where the introduction of the outline hover style introduced some collision issues. There is certainly room for tweaking some of that yet. 
Additionally, this corrects some lingering dark-mode regressions with hover colors on links in the sidebars.
There are still some special effects (e.g., slight scaling downward on click/`:active`) that will be implemented in a follow-up PR. It would also be nice to introduce the new unread background colors, but those will likely happen alongside a PR that introduces the …
=> sidebars: Introduce new highlight and hover styles.

web/src/attachments_ui.ts, web/styles/settings.css, web/templates/settings/uploaded_files_list.hbs
The HTML `id` attribute is supposed to be globally unique; it’s not an appropriate place to store a user-controlled string, or to identify part of a component that’s rendered more than once.
=> uploaded_files_list: Fix id pollution.

web/src/buddy_data.ts, web/src/buddy_list.ts, web/src/list_util.ts, web/src/message_list.ts, web/src/sidebar_ui.ts, web/templates/buddy_list/section_header.hbs, web/templates/right_sidebar.hbs, web/tests/buddy_data.test.js, web/tests/message_list.test.js
Fixes #31129
Note: This is ready for product review, but CI won't pass because I haven't updated unit tests yet.
<details>
<summary>Users in all three sections:</summary>
</details>
<details>
<summary>No "others in this channel"</summary>
</details>
<details>
<summary>No "others"</summary>
</details>
<details>
<summary>Collapsed sections</summary>
</details>
<details>
<summary>Just a bot, so no participants section:</summary>
</details>
<details>
<summary>Interleaved view, so no participants section:</summary>
</details>
<details>
<summary>Recent conversations, so no participants section</summary>
</details>
<details>
<summary>DM conversation, so no participants section</summary>
</details>
=> buddy list: Create new participants section.

web/src/input_pill.ts, web/tests/input_pill.test.js
Select the pill on the first backspace and delete the whole pill on the second backspace. If the pill is already highlighted from left-pressing, then backspace would delete it right away.
We're making this change because it can be quite annoying to re-type out a pill that's accidentally deleted, and users might think pills are editable and accidentally delete the whole thing with a backspace stroke.
=> input_pill: Highlight/focus pill before removing it.

web/styles/message_row.css, web/templates/message_edit_form.hbs
Fixes #31750.
The control buttons of the edit box were flickering b/w default cursor and pointer cursor after c1d155d923f95b264397344651ef79e59f68e549. The addition of `position: relative` to `.edit-content-container` was causing that.
No flicker in final state:
Copy message comparison for regression:
| --- | --- |
| ![Screenshot 2024-09-27 at 9 12 55 AM](https://github.com/user-attachments/assets/c632d8b7-3f4d-4497-9521-34ed1ad2a47d) | ![Screenshot 2024-09-27 at 9 11 44 AM](https://github.com/user-attachments/assets/2145115f-2f2c-4709-a3ca-fb7958623a26)| 
<details> …
=> message_edit: Use display: flex instead of relative positioning.

web/src/reload.ts
This isn't a bug fix, but it does clean up the code. `reload_setup` only uses the `stream_id` if it can parse it as an integer and otherwise falls back to `undefined`, so it makes more sense to not include undefined stream ids.
=> [followup] reload: Only add stream_id if it's defined.

api_docs/changelog.md, version.py, web/src/hashchange.js, web/src/user_group_edit.js, web/templates/user_group_settings/cannot_deactivate_group_banner.hbs, zerver/lib/exceptions.py, zerver/lib/user_groups.py, zerver/openapi/zulip.yaml, zerver/tests/test_user_groups.py
- First commit adds backend code to include the details of supergroups and of the groups and streams for which the group is being used as setting.
- Second commit adds the frontend code to show the details.
Fixes:   https://chat.zulip.org/#narrow/stream/101-design/topic/Support.20user.20group.20deactivation/near/1949585
<details>
</details>
=> user_groups: Show details in group deactivation error.

zerver/management/commands/backup.py
In docker-zulip installs, /etc/zulip/zulip.conf, /etc/zulip/zulip-secrets.conf, and /home/zulip/uploads are all symlinks into the `/data` directory which is mounted as a Docker Volume.  By default, `tar` does not dereference symlinks, leading to backups that are missing these critical pieces.
Add `-h` to the `tar` invocation, to follow symlinks, so backups in Docker have all of their pieces.  Since none of the contents of the backup intentionally use symlinks, this is safe.
Fixes: https://github.com/zulip/docker-zulip/issues/423
<details> …
=> fix broken symlinks to `uploads` and `settings/zulip-secrets.conf` in final `.tar.gz` file

CONTRIBUTING.md
=> contributor docs: Clarify how to ask for an issue to be assigned.

web/src/saved_snippets_ui.ts, web/templates/add_saved_snippet_modal.hbs
This PR prepopulates the 'content' block of the saved snippet with the compose box content.
Fixes #31827.
<details><summary>GIF</summary>
<p>
</p>
</details> 
<details>
</details>
=> saved_snippet: Prepopulate new saved snippet content.

web/src/buddy_data.ts, web/src/buddy_list.ts, web/tests/activity.test.js, web/tests/buddy_data.test.js
This was causing a bug where the participants weren't necessarily all getting rendered, specifically when there were many subscribers to a channel, because we render users in batches as buddy list scrolls, and those users would only show up after some scrolling.
This fix makes sure we always load the participants first.
Reported here: https://chat.zulip.org/#narrow/stream/101-design/topic/Show.20conversation.20participants.20in.20the.20right.20sidebar.20.2331129/near/1952659
I tested by making an organization with 1000 users and returning early in `maybe_shrink_list` so that there were many users that got in the buddy list populate queue. Before this change, participants only showed up after scrolling, and after this change they always appear in the list.
=> buddy_data: Add participants to the top of sorted user list.

corporate/lib/support.py, zerver/actions/invites.py, zerver/lib/cache_helpers.py, zerver/models/realms.py
Because the main indexes on end_time either don't include realm_id or do include subgroup, passing an explicit subgroup=None for single-realm queries to read CountStats that don't use the subgroups feature greatly improves the query plans.
=> analytics: Pass subgroup=None to improve indexing.

web/styles/compose.css
Previously, no custom styling was being applied to the enter send choice options, which led to uneven styling from the other popover options, as well as the outline ring being cut-off from the edges of the popover. This PPR fixes these issues by adding custom styling for the outline ring when the enter send choice options are focused.
[CZO Discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/selection.20box.20cut.20off.20in.20send.20menu/near/1950294)
| ![Screenshot 2024-10-02 at 2 55 20 PM](https://github.com/user-attachments/assets/5967e614-b23e-44b2-a1b0-31fc8f4b62c0) | ![Screenshot 2024-10-02 at 2 54 48 PM](https://github.com/user-attachments/assets/76866bd3-ed13-49ce-bb0f-1efcf543c26e) | …
=> send_later_popover: Improve on-focus styling of enter send choices.

web/src/filter.ts, web/tests/filter.test.js
This commit refactors the `ensure_channel_topic_terms` of `filter.ts`. Previously, this method used to add channel and topic terms, with operands as placeholders in case the `with` narrow doesn't have channel-topic terms.
This commit updates it to rather correct the narrow with the right terms in case the channel-topic terms are missing in the `with` narrow, but leave it as it is in case the channel-topic terms are present, so that it can later be corrected if the channel-topic terms are not pointing to the right conversation.
Fixes https://github.com/zulip/zulip/pull/31239#discussion_r1752930765
<details> …
=> filter: Refactor code path which adjusts the narrow containing `with`.

web/src/message_view_header.ts
The narrow_state module has a function that returns what this needs.
This does remove a log statement, but I don't think it was useful; we don't need to or have a useful way to colorize a channel that doesn't exist.
=> message_view_header: Remove unnecessary complexity.

web/src/filter.ts, web/tests/filter.test.js
Previously `[{operator: "topic", operand: "one\xa0two"}]` would be unparsed to `"topic:one\xa0two"` which parses as `[{operator: "topic", operand: "one"}, {operator: "search", operand: "two"}]`, leading to exceptions in the search pill system.
=> filter: Fix unparse to round-trip Unicode whitespace operands.

web/src/billing/sponsorship.ts
The sponsorship form is not visible once user submits the form, hence we don't to call these functions.
https://zulip.sentry.io/issues/5904364828/events/?project=4504556882821120
=> sponsorship: Fix `#organization-type` not found.

zerver/webhooks/slack_incoming/view.py
Hi,
When using alertmanager with zulip's slack_incoming hook zulip does not receive the "resolved" messages, only the "firing" message.
This is because alertmanager expects an `{"ok: true, ...}` in json responses [see alertmanager code](https://github.com/prometheus/alertmanager/blob/e1492602209b86e0ca6d7671c7353b62a31b897b/notify/slack/slack.go#L258). Seems [specified here](https://api.slack.com/web#responses) at slack.
The current behavior of alertmanager is like this:
1. an alert triggers, alertmanager sends a "firing" message to slack_incoming, alertmanager thinks it has failed (because no "ok: true" in the json response)
2. an alert stops, alertmanager does not notify slack_incoming because the alert trigger failed.
Best,
Pierre
=> slack_incoming: add ok=true to json in case of success

.eslintrc.js, help-beta/package.json, package.json, patches/puppeteer-core.patch, pnpm-lock.yaml, version.py, web/src/buddy_list.ts, web/src/color_data.ts, web/src/common.ts, web/src/components.ts, web/src/copy_and_paste.ts, web/src/i18n.ts, web/src/input_pill.ts, web/src/message_list_tooltips.ts, web/src/message_view.ts, web/src/recent_view_ui.ts, web/src/search_suggestion.ts, web/src/sentry.ts, web/src/stream_list_sort.ts, web/src/topic_generator.ts, web/src/ui_util.ts
Prep commits already merged:
- #31742
- #31753
- #31755
- #31756
- #31767
Includes this patch for a Puppeteer 22.12.1 regression:
- puppeteer/puppeteer#13153
=> Upgrade JavaScript dependencies

zerver/worker/thumbnail.py
This prevents a deadlock between the thumbnailing worker and message sending, as follows:
1. A user uploads an image, making Attachment and ImageAttachment    rows, as well as enqueuing a job in the thumbnailing queue.
2. Message sending starts a transaction, creates the Message row, and calls `do_claim_attachments`, which edits the Attachment row of the upload (implicitly locking it).
3. The thumbnailing worker starts a transaction, locks the ImageAttachment row for its image, thumbnails it, and then attempts to `select_for_update()` the message objects (joined to the Attachments table) to find the ones which link to the attachment in question. This query blocks, since "a locking clause without a table list affects all tables used in the statement"[^1] and the message-send request …
=> thumbnail: Only lock the message row, not the Attachment row.

web/src/reactions.ts, web/styles/reactions.css, web/templates/message_body.hbs, web/templates/message_reactions.hbs, web/tests/reactions.test.js
Before, the message reactions section along with the add reaction button was being rendered for every message even when there were no reactions present - this led to additional DOM cost.
This PR adds the message reactions section only when there is at least a single reaction on the message, and follows up with a cleanup of the message reactions section when there are no reactions.
Fixes #31137.
<details> …
=> reactions: Optimize DOM cost of message reactions via dynamic rendering.

web/styles/compose.css
Fixes #31214.
<details>
</details>
=> compose: Change cursor to default instead of not-allowed.

web/e2e-tests/copy-and-paste.test.ts
This change might also fix the flaky nature of this test but needs to be tested by running online on CI.
=> copy-and-paste: Remove not required click on all messages narrow.

web/e2e-tests/compose.test.ts, web/e2e-tests/drafts.test.ts, web/e2e-tests/edit.test.ts, web/e2e-tests/lib/common.ts, web/e2e-tests/message-basics.test.ts, web/e2e-tests/stars.test.ts
This flake was happening since `wait_for_fully_processed_message` only checks if the `star` icon is displayed on the message but doesn't check for current narrow or waits for the narrow to change.
Since narrow is changed to the message narrow after sending a message. If we don't wait for narrow to change, this narrow change can make the `get_current_msg_list_id` call return true for the wrong narrow change. Which causes message list id of the wrong message list to be returned and hence we cannot locate this message list id.
To fix it, we check if sending this message will cause a narrow change and if true, we wait for the narrow to change before checking if the message is visible.
=> puppeteer: Fix flaky wait for narrow change after sending a message.

web/src/message_view.ts, web/tests/narrow_activate.test.js
On a fresh render of a narrow if the view doesn't scroll, `update_sticky_recipient_headers` is not called. So, we need call it after we have scrolled to the message we want to select.
Populated that database with `./manage.py populate_db --oldest-message-days=10 -n 1000 --max-topics=` and used `ctrl .` hotkey to reproduce the bug.
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/Jump.20to.20conversation.20keyboard.20shortcut.20bugs
=> message_view: Update date on sticky header after rendering narrow.

web/styles/widgets.css
This corrects a regression on poll and to-do widget edit buttons in dark mode.
The colors themselves will likely change once #31595 progresses.
[CZO issue](https://chat.zulip.org/#narrow/stream/9-issues/topic/Title.20edit.20checkmark.20buttons'.20background.20color.2E/near/1955900)
| --- | --- |
| ![widget-edit-buttons-dark-before](https://github.com/user-attachments/assets/751d9ff7-75d1-4932-8f5b-3e9e962d5a5f) | ![widget-edit-buttons-dark-after](https://github.com/user-attachments/assets/802284f6-ee9c-4561-b7bf-47a4b99fd158) |
| ![widget-edit-buttons-light-before](https://github.com/user-attachments/assets/7472ea14-5c6f-41d9-9709-6b996623ed4c) | ![widget-edit-buttons-light-after](https://github.com/user-attachments/assets/ac31e621-e2 …
=> widgets: Assign zulip-button colors to edit buttons.

docs/production/reverse-proxies.md, puppet/zulip/files/nginx/uwsgi_params, puppet/zulip/templates/uwsgi.ini.template.erb
The nginx-to-uwsig-timeout defaults to 60s, which is exactly the same
as the current "harakiri" timeout configured in uwsgi (which limits
the length a request can run before the worker is terminated).  This
causes a race, where if nginx hits its 60s before uwsgi, then we
return a 504; otherwise, we get a 502.
Make the nginx-to-uwsgi timeout explicit, and shorten the "harakiri"
timeout to be explicitly less than that.  Document the 60s timeout,
which all outer reverse proxies must be set to _longer than_ in order
to have proper "onion" timeouts.
Fixes: 
<details> …
=> nginx: Make uwsgi timeout shorter than nginx-to-uwsgi timeout.

web/e2e-tests/compose.test.ts, web/e2e-tests/edit.test.ts
This caused another CI flake in https://github.com/zulip/zulip/actions/runs/11217538032/job/31179325677#step:16:281
Also, added a comment to the only other place where we pass false explicitly explaining why.
=> puppeteer: Fix incorrectly passed `false` value to check narrow change.

api_docs/group-setting-values.md, zerver/openapi/zulip.yaml
Ths hardcoded documentation of which values are possible was destined to end up inaccurate and out-of-date; and meanwhile, we do have a part of the API that already has these data in machine-readable format.
The main new content is this:
=> groups: Rework documentation of permitted values.

scripts/lib/zulip_tools.py, scripts/restart-server
=> restart-server: Add a --only-django for rolling Django restarts.

web/src/inbox_ui.ts, web/src/stream_data.ts, web/src/stream_list.ts, web/src/sub_store.ts
This simplifies the `StreamSubscription` type, and parallels how we always initialize every other property that isn’t in `NeverSubscribedStream` (`audible_notifications`, `desktop_notifications`, `email_notifications`, `push_notifications`, `wildcard_mentions_notify`, `color`, `is_muted`). `email_address` was already optional.
=> stream_data: Always initialize pin_to_top

web/src/bootstrap_typeahead.ts, web/styles/dark_theme.css
reported here https://chat.zulip.org/#narrow/stream/9-issues/topic/unexpected.20search.20typeahead.20highlighting.20.28dark.20theme.29/near/1951962
=> typeahead: Prevent blue styling from mouse hover on typeahead item in dark mode.

web/src/buddy_list.ts, web/styles/right_sidebar.css, web/templates/buddy_list/section_header.hbs, web/tests/lib/buddy_list.js
<details>
<summary>screen capture</summary>
</details>
To better match Vlad's designs: https://terpimost.github.io/zulip-sidebar/
=> buddy_list: Rotate the header triangle when collapsing a section.

api_docs/changelog.md, version.py, zerver/lib/create_user.py, zerver/lib/users.py, zerver/models/users.py, zerver/openapi/zulip.yaml, zerver/tests/test_users.py
Implements the change to `GET /users/{email}` discussed around https://chat.zulip.org/#narrow/stream/378-api-design/topic/Update.20user.2C.20queried.20by.20real.20email.20-.20new.20endpoint/near/1937254 
The old behavior was for this endpoint to just naively lookup the target by the `.email` attribute. This translated to very quirky behavior requiring API users to be aware of implementation details of the email visibility setting:
- If the target had at all restricted email visibility, they couldn't be looked up by their real email, even if the requester **was** allowed to access that user's email. That restriction was logically unnecessary.
- Instead, the user **had** to be looked up via the dummy email `user{id}@{realm.host}`, which was the value of their `.email` attribute. 
- If the …
=> `GET /users/{email}`: Allow lookup by real email whenever the target allows the requester access to the real email

web/src/upload.ts
This feature isn't likely to be useful for our use case and generates some risk; see the comment for details.
=> upload: Disable the tus-js-client fingerprinting feature.

web/templates/popovers/left_sidebar/left_sidebar_all_messages_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_drafts_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_inbox_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_recent_view_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_starred_messages_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_stream_setting_popover.hbs
This PR is a follow-up of 43eebbf9c6b6ef8f3da517bed2b2841143e27b1e, and it sets `data-simplebar-tab-index="-1"` on the remaining popovers.
This prevents the simplebar container from taking focus while trying to navigate the popovers via the keyboard, thus fixing the bug where the user had to click the down key twice before reaching the first focus-able popover menu option.
Fixes: [CZO DIscussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/extra.20.22down.22.20required.20to.20select.20top.20option/near/1957947)
| ![before](https://github.com/user-attachments/assets/fe2a4c03-c475-417d-863d-7b170f54c460) | ![after](https://github.com/user-attachments/assets/ef3425e4-4e98-4cf8-81fa-f9814c719123) | 
<details> …
=> popovers: Fix initial focus on popover simplebar container.

web/src/message_edit.ts, web/templates/confirm_dialog/intro_resolve_topic.hbs, zerver/lib/onboarding_steps.py, zerver/tests/test_onboarding_steps.py
We show a modal explaining the "resolve topics" feature when the user marks a topic resolved for the first time.
We don't show anything the first time a topic is marked unresolved.
Fixes #31242
<details>
</details>
=> topic: Add first-time explanation for "Resolve topic".

zerver/openapi/zulip.yaml
For the six realm settings mentioned in the main description of the [/api/update-message](https://zulip.com/api/update-message) endpoint, link back to that page in the [/api/register-queue](https://zulip.com/api/register-queue) and [/api/get-events](https://zulip.com/api/get-events#realm-update_dict) endpoints. This way we can maintain a centralized point of documentation for how these settings work for message content edits and moving messages.
The descriptions in the events and register pages focuses on the specifics for each realm setting, e.g., when a value is added or changed for a particular realm setting.
See [relevant CZO discussion](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/realm_edit_topic_policy.20misleading/near/1956711).
**Notes**:
- Per [this CZO …
=> api-docs: Centralize history of realm message edit/move settings.

help/collaborative-to-do-lists.md, help/configure-send-message-keys.md, help/create-a-poll.md, help/include/compose-and-send-message.md, help/include/replying-to-messages.md, help/include/set-up-your-account.md, help/include/sidebar_index.md, help/keyboard-shortcuts.md, help/mastering-the-compose-box.md, zerver/lib/markdown/tabbed_sections.py, zerver/lib/url_redirects.py, zerver/openapi/zulip.yaml
Document setting the keys that will send a message or create a new line when composting a message via the compose box and via the personal settings overlay.
Updates links and redirect from former help center article about this feature. Fixes `collaborative-to-do-lists.md` for some formatting conventions we have for help center md files.
Fixes #31620.
---
<details>
<summary>Configure send messsage keys - for Mac users</summary>
</details>
<details>
<summary>Configure send messsage keys - for non-Mac users</summary>
</details>
<details>
<summary>Preferences section of help center left sidebar</summary>
</details>
---
<details> …
=> help: Create "Configure send message keys" article.

web/src/resize.ts, web/src/sidebar_ui.ts, web/src/tippyjs.ts, web/src/user_search.ts, web/styles/right_sidebar.css, web/templates/popovers/buddy_list_popover.hbs, web/templates/right_sidebar.hbs, web/tests/activity.test.js, web/tests/user_search.test.js
Fixes #31653
**part (1)**
> Add a three-dot menu to the right of the search button, with the "Invite users to organization" link as the only menu item to start with. We should use the same icon as we have in the gear menu. If a user doesn't have permission to send invites, the three-dot menu button should not be shown.
guest has no three-dot menu:
**part (2)**
> Make the "Invite users to organization" link be scrollable, rather than pinning it to the bottom of the sidebar.
=> buddy_list: Change how "Invite users to organization" link is shown.

web/src/message_edit.ts
We replace the comma in the buttons to an em dash. This is a follow up to #31312.
<details>
</details>
=> resolve_topic: Change dialog button text.

web/templates/inbox_view/inbox_list.hbs
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/direct.20messages.20in.20inbox/near/1960308)
| --- | --- |
| ![Screen Shot 2024-10-11 at 13 55 07](https://github.com/user-attachments/assets/aa463f19-4ca5-4c50-9d1d-eb359137229e) | ![Screen Shot 2024-10-11 at 13 54 56](https://github.com/user-attachments/assets/4e1ac656-a7dd-4a4d-813f-e9aa7a6a819c) |
<details>
</details>
=> inbox: Use plural for Direct messages header.

web/src/settings_components.ts, web/src/state_data.ts
This was replaced with realm_can_create_private_channel_group in e19524b and wasn't fully removed.
Note it's still present in the backend code because it's used by the mobile app.
Pulled from #31940
=> settings: Remove unused realm_create_private_stream_policy.

web/src/buddy_list.ts, web/tests/lib/buddy_list.js
`$(".buddy-list-subsection-header").children()` has length more often than I had thought. Using the narrow filter is more direct way of managing this state.
Fixes bug reported here: https://chat.zulip.org/#narrow/stream/137-feedback/topic/hiding.20inactive.20users.20in.20right.20sidebar/near/1958300
=> buddy_list: Fix bug where headers weren't being updated often enough.

api_docs/changelog.md, api_docs/include/rest-endpoints.md, version.py, web/src/settings_exports.ts, web/tests/lib/events.js, zerver/lib/event_schema.py, zerver/lib/export.py, zerver/openapi/zulip.yaml, zerver/views/realm_export.py
API changes to make it possible to use `POST /export/realm` for "full data export with member consent". Earlier, only public data export was supported.
<details>
</details>
=> realm_export: Add support to create "full data export" via `/export/realm`.

web/src/settings_profile_fields.ts, web/templates/settings/profile_field_settings_admin.hbs, web/tests/settings_profile_fields.test.js
[CZO discussion](https://chat.zulip.org/#narrow/stream/6-frontend/topic/Placeholder.20for.20profile.20fields.20org.20setting.20table.20.2327250/near/1822106) regarding whether to use ListWidget.
Fixes: #27250.
| ![image](https://github.com/zulip/zulip/assets/133781250/879e297b-bea6-4a8d-a8d4-a8cd84ba89ba) | ![image](https://github.com/zulip/zulip/assets/133781250/6bbbe015-a788-42e0-a62c-66a118b7e4ca) |
| ![image](https://github.com/zulip/zulip/assets/133781250/bfe3a0ca-1311-49ad-a373-f5186ec6add6) | ![image](https://github.com/zulip/zulip/assets/133781250/8d85710d-7b71-4552-bbc1-50bd1763f4bf) | 
<details>
Communicate …
=> Update custom profile fields admin table empty placeholder.

zerver/views/health.py
Fixes a spurious error that’s logged and ignored during the Puppeteer tests, introduced by commit eef65d7e304847793079c8e724f0416b464de95e (#31438, cc @alexmv).
e.g. from https://github.com/zulip/zulip/actions/runs/11301057896/job/31434895030:
```pytb
2024-10-12 00:36:59.775 ERR  [django.request] Internal Server Error: /health
File "/__w/zulip/zulip/zerver/views/health.py", line 26, in check_rabbitmq
conn = get_queue_client().connection
File "/__w/zulip/zulip/zerver/lib/queue.py", line 427, in get_queue_client
raise RuntimeError("Cannot get a queue client without USING_RABBITMQ")
RuntimeError: Cannot get a queue client without USING_RABBITMQ
During handling of the above exception, another exception occurred:
File …
```
=> health: Disable RabbitMQ check if not USING_RABBITMQ

docs/subsystems/thumbnailing.md
The first change fixes the incorrect claim that stills of animated emojis are unused.
Second change just fixes the missing words in the sentence.
=> docs: Minor tweaks to thumbnailing.md.

help/keyboard-shortcuts.md, tools/linter_lib/custom_check.py, web/src/common.ts, web/templates/keyboard_shortcuts.hbs, web/tests/common.test.js
Previously, these were only shown for Mac OS users and replaced the "Home", "End", "PgUp" and "PgDn" shortcuts. But as this really depends on the keyboard the user is using (there are Mac keyboards with the above keys), we instead show both options in our web app and help center documentation on keyboard shortcuts.
The tooltip for the "Scroll to bottom" button will now always show "End" for all users. Previously, it showed a "Fn" key option for Mac users.
See [relevant CZO dicussion](https://chat.zulip.org/#narrow/stream/137-feedback/topic/last.20message.20shortcut/near/1953002).
Fixes #31815.
---
<details>
<summary>Scroll to bottom button tooltip</summary>
</details>
<details>
<summary>Keyboard shortcuts help in web app for non-Mac users</summary> …
=> docs: Update keyboard shortcuts to always show "Fn" key option.

web/src/buddy_list.ts
Followup to #31960. I forgot to consider the case of a narrow with an undefined filter. To make sure we fully run render_section_headers on narrows like Recent Conversations the first time they load, this commit initializes `current_filter` to the string "unset".
Reported on CZO here: https://chat.zulip.org/#narrow/channel/9-issues/topic/None.20in.20users.20list
=> buddy_list: Differentiate updating and changing to an undefined filter.

web/src/message_events.js
If a muted message for the currently rendered message list is moved
to a non muted topic, it was not rendered if it is part of
`_all_items` and not `_items` due to it being previously muted.
We fix it by removing all the moved messages from the list and
added them back which allows us filter the messages for muting again.
This overall reduces the amount of rerender calls too since we
are now guaranteed to only call it once now.
Fixes https://github.com/zulip/zulip/issues/31977
=> Fix muted messages in a stream not rendered if moved to be unmuted when narrowed to the message stream.

zerver/actions/custom_profile_fields.py, zerver/views/custom_profile_fields.py, zerver/views/users.py
Fixes https://github.com/zulip/zulip/issues/31935
This can't be durable as it's invoked within `sync_ldap_user_data`, which is already in transaction.atomic.
Reverts 8b3d5a945594c80201753e79935f9410101700c5
@prakhar1144 Can you check if this is fine? Btw, is there a thread where i can read up on the background for why `savepoint=False` can't be used here? Since the original commit says:
> We can't set savepoint=False before hand to the outermost action function because it leads to rollback of transaction in tests when an error is raised in action function.
=> custom_profile_fields: Make transaction no longer durable.

web/src/typing.ts
Before sending typing notifications to the server, make sure that the user has set at least one valid user pill in the compose box recipient bar.
**Console in dev environment before changes**:
```
2024-10-15 14:38:28.458 INFO [zr] status=400, data=b'{"result":"error","msg":"Missing \'to\' argument","code":"BAD_REQUEST"}\n', uid=9@zulip
```
**Follow-up question**:
- Do we also want to check for `topic === ""` in realms where topics are mandatory before sending these events to the server as well?
---
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.htm …
=> typing: Check for valid user IDs when setting typing recipient.

web/src/narrow_banner.ts, web/tests/message_view.test.js
Reported on CZO: https://chat.zulip.org/#narrow/channel/6-frontend/topic/unknown.20channel.20ID.20-.20empty.20feed.20banner/near/1956805
Tested manually that the following views show the new "doesn't exist" message:
* link to invalid channel
* near link for inaccessible channel
* channel>topic link for invalid channel
Also tested:
* logged out, near link for inaccessible channel (says you need to log in)
* logged out, near link for invalid channel (says you need to log in)
* logged in, valid channel, unknown topic (offers the user to "start the conversation")
=> empty narrow updates for invalid channel ids

web/shared/icons/masked-unread.svg, web/src/click_handlers.js, web/src/stream_popover.js, web/src/topic_list.ts, web/styles/app_components.css, web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/left_sidebar.css, web/styles/message_header.css, web/styles/zulip.css, web/templates/left_sidebar.hbs, web/templates/more_topics.hbs, web/templates/popovers/left_sidebar/left_sidebar_stream_actions_popover.hbs, web/templates/stream_sidebar_row.hbs, web/templates/topic_list_item.hbs, web/third/bootstrap/css/bootstrap.app.css
This PR does the following:
1. It implements @terpimost's design for showing icons in DM and Channel heading rows only upon hover (controls remain visible for touchscreen devices).
2. It updates the icons and colors for the heading-row controls.
3. It moves the New topic icon and functionality to stream rows from their previous location in the channel popover. The New topic icon is always shown on the active channel, and available as a hover control on all other channel rows.
4. It adjusts the `--color-vdots-hint` values to be more subtle, and therefore less distracting, on touchscreens.
5. It refactors opacity and hover opacity for muted channels and muted topics, including restoring missing opacity value on muted topics that was lost in a recent regression.
6. It presents unread markers …
=> Left sidebar: Add hover controls to heading and stream rows.

api_docs/changelog.md, api_docs/group-setting-values.md, version.py, web/src/user_group_create.ts, web/src/user_group_edit.js, zerver/lib/user_groups.py, zerver/models/realms.py, zerver/tests/test_realm.py, zerver/tests/test_user_groups.py
The main change is redefining ALLOW_GROUP_VALUED_SETTINGS to not control code, but instead to instead control the configuration for whether settings that have not been converted to use our modern UI patterns should require system groups.
Fundamentally, it's the same for the realm/stream group-valued settings, which don't have the new UI patterns yet.
We remove the visual hiding of the "can manage group" setting, which was hidden only due to transitions being incomplete.
=> groups: Enable group-settings value on groups in production.

web/src/condense.ts
discussion: https://chat.zulip.org/#narrow/stream/9-issues/topic/issue.20with.20message.20links.20when.20message.20not.20loaded.3F
Since both the message reported in https://leanprover.zulipchat.com/#narrow/stream/236604-Zulip-meta/topic/Links.20to.20messages.20don't.20work.3F can be collapsed:
* https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/thoughts.20on.20elliptic.20curves/near/384147037
* https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/lean.2Envim/near/473385145
The reported issue is likely related to collapsing message. This is a bug I found when playing with the message collapsing which is likely the cause.
Easy reproducer is to send a very long message so that you can
see the collapse / expand banner followed by enough messages that
you can …
=> Fix message pointer out of view sometimes when vising a cached view.

zerver/data_import/import_util.py, zerver/data_import/mattermost.py, zerver/data_import/rocketchat.py, zerver/data_import/slack.py, zerver/data_import/user_handler.py, zerver/tests/test_mattermost_importer.py, zerver/tests/test_rocketchat_importer.py, zerver/tests/test_slack_importer.py
This PR makes the third-party data converters check for invalid user emails. If it finds any, it’ll raise an Exception and show an error message with all the bad emails listed out.
<details>
<summary>Error log when there are invalid user emails</summary>
```
Converting data ...
2024-10-10 05:48:17.320 INFO [] ######### IMPORTING USERS STARTED #########
2024-10-10 05:48:17.349 INFO [] USLACKBOT: slackbot -> imported-slackbot-bot@invalid.c
2024-10-10 05:48:17.351 INFO [] U06NU4E26M9: pieterceka123 -> pieterceka123@gmail.com
2024-10-10 05:48:17.363 INFO [] U07NFSVQCAD: pabbly_connect -> pabblyconnect-bot@invalid.c
File "/srv/zulip/./manage.py", line 150, in <module>
execute_from_command_line(sys.argv)
File "/srv/zulip/./manage.py", line 115, in …
```
=> data_import: Check for invalid user emails when converting data.

web/src/attachments_ui.ts, web/styles/settings.css, web/templates/settings/attachments_settings.hbs, web/templates/settings/upload_space_stats.hbs
This PR addresses the requested changes to enhance the UI of the "Uploaded Files" settings panel. The following improvements have been implemented:
1. **Renaming the table**: 
- The table header has been renamed from "Uploaded files" to "Your uploads" to clarify that the listed files are specific to the user, not everyone’s uploads.
- Other strings in the panel continue to use "Uploaded files" as needed.
2. **Quota notice text update**:
- The text of the storage quota notice has been updated to:
> "Your organization is using x% of your 5 GB file storage quota. Upgrade for more space."
3. **Clickable banner for upgrade**:
- Instead of having "Upgrade" as a link, the entire quota notice is now a clickable banner with a rocket icon, similar to the style used elsewhere in the …
=> ui: Improve Uploaded files settings panel

web/src/invite.ts, web/src/peer_data.ts, web/src/settings_data.ts, web/templates/guest_visible_users_message.hbs, web/templates/invite_user_modal.hbs, web/tests/peer_data.test.js, web/tests/settings_data.test.js
This PR adds a new note in the Invite modal informing users of how many users guests will be able to see in their channels. The message updates live as channel subscriptions or user roles change.
The note is displayed when the guest role is selected, and the setting prevents guests from viewing all users. The dynamic message shown is:
**"Guests will be able to see {N} users in their channels when they join."**
The value of `{N}` is determined using client-side cached subscription data, so it updates in real-time without needing any server-side interaction. This feature applies to both link and email invitations and includes a help link to guide users in configuring guest visibility settings.
| Email Invitation | Invitation Link | Non-Default Channel |
| ---------------- | --------------- …
=> invite: Add guest visibility note with live-updating user count.

zerver/lib/user_groups.py, zerver/tests/test_user_groups.py, zerver/views/user_groups.py
- First commit is to fix the code for checking group joining permission.
- Second commit is to refactor the code for checking permissions to update group.
<details>
</details>
=> user_groups: Refactor code to check group permissions.

web/src/typing.ts, web/tests/typing_status.test.js
Before sending typing notifications to the server, if the realm requires topics for channel messages, make sure that the topic string is not an empty string in the compose box.
Follow-up to #31999.
---
<details>
</details>
=> typing: Check empty topic string if realm has mandatory topics.

tools/lib/capitalization.py, web/src/invite.ts, web/src/settings_components.ts, web/src/settings_config.ts, web/src/util.ts, web/templates/invite_user_modal.hbs, web/tests/util.test.js
These updates are based on the 3rd/4th commits in #26109 as well as review feedback from that PR.
**Notes**:
- Extracts reusable elements from the custom time logic in the invite user modal as prep for setting a realm data deletion custom date on realm deactivation (see issue #24677).
- Adds some basic validation/disabling the submit button when invalid custom dates are input into the modal form.
- Updates the custom time units that are displayed in the dropdown to be internationalized.
---
<details>
<summary>Negative number as custom time input</summary>
| --- | --- |
| ![Screenshot from 2024-06-20 21-09-54](https://github.com/zulip/zulip/assets/63245456/81eadd2e-e028-4a20-b4ce-3b2782016f49) | ![Screenshot from 2024-06-20 …
=> invite-user: Add validation on custom time input and extract custom time logic for reuse.

web/styles/portico/navbar.css
This brings navbar subsheads into alignment with each other, and cleans up an unnecessary confusing selector.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/Hello.20page.20mobile.20navigation.20opacity/near/1963282)
| Before | After (no change on desktop) |
| --- | --- |
| ![mobile-menu-before](https://github.com/user-attachments/assets/86bad7fd-acdf-4d45-b98c-7ae56a0c1893) | ![mobile-menu-after](https://github.com/user-attachments/assets/3a64645a-a5c4-4353-b0fe-9779c5d53a2f) |
| ![wide-menu-before](https://github.com/user-attachments/assets/1c9966a2-683f-438a-b059-12233d6d786c) | ![wide-menu-after-no-change](https://github.com/user-attachments/assets/baeb182b-fbee-4042-94ff-004400d0f4ee) |
=> portico: Align mobile subhead colors with desktop.

zerver/data_import/rocketchat.py, zerver/tests/test_rocketchat_importer.py
The Rocket.Chat data importer made the mistake of loading the entire data set of messages/uploads into memory before trying to validate anything, which made for an annoying edit/refresh cycle for metadata problems.
=> Optimize import order for Rocketchat data import tool

help/channel-feed.md, help/mute-a-channel.md
First commit: This should ideally point to Not subscribed channels, not All channels. Waiting on #31605, so marking this PR as WIP.
Current: https://zulip.com/help/channel-feed
<details>
<summary>
Updated
</summary>
</details>
Second commit is responsive to [this CZO thread](https://chat.zulip.org/#narrow/stream/9-issues/topic/Empty.20combined.20feed/near/1926136).
Current: https://zulip.com/help/mute-a-channel
<details>
<summary>
Updated
</summary>
</details>
Perhaps we don't need to note anything on https://zulip.com/help/mute-a-topic? I didn't feel like it was necessarily worth getting into there.
=> [WIP] help: Recommend unsubscribing from muted channels.

web/src/stream_create.ts, web/src/stream_settings_ui.js
- First commit is to not show any banner on channel creation form.
- Second commit is to not show the channel creation banner when user is subscribed to the channel.
Fixes:  https://chat.zulip.org/#narrow/channel/9-issues/topic/confirmation.20banner.20flashes.20when.20creating.20channel
User creating the stream is subscribed
User creating the stream is not subscribed 
<details>
</details>
=> Fix flashing banners while creating channels.

api_docs/changelog.md, version.py, zerver/actions/create_user.py, zerver/actions/user_settings.py, zerver/lib/event_schema.py, zerver/lib/events.py, zerver/openapi/zulip.yaml, zerver/tests/test_events.py
Fixes part of #31201.
Extracted from #31947.
=> realm_export: Add realm_export_consent feature to API.

web/src/message_events.js
This fixes a bug where we try to rerender the anchor message even if we don't have it locally cached which results in error.
Introduced in #31942
Fixes https://zulip.sentry.io/issues/5991504658/events/recommended/?project=4504556882821120&referrer=recommended-event
=> message_events: Don't update msg if we don't have it cached locally.

web/src/ui_init.js
Saving narrow state before we have scrolled to the message results in view scroll position being different from where the message is displayed.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/back.2Fforward.20button.20scroll.20position.20broken
=> narrow_history: Save narrow state after we have scrolled to the msg.

web/src/activity.ts, web/src/message_events.js, web/src/message_scroll.js, web/src/ui_init.js, web/tests/activity.test.js, web/tests/example5.test.js, web/tests/hotkey.test.js
This works to stop messages from being marked as read if a new message arrives and we don't scroll. Unfortunately, we scroll most of the time when trying the bring the new message into view which marks the message as read.  So, we need to carefully pipe that information to scroll event to avoid this bug in that case too to close --  #32024.
=> Fix new messages marked read on active window.

web/src/server_events_dispatch.js, web/src/settings_exports.ts, web/src/user_events.js, web/styles/settings.css, web/templates/settings/admin_export_consent_list.hbs, web/templates/settings/data_exports_admin.hbs, web/tests/dispatch.test.js, web/tests/lib/events.js
Issue: https://github.com/zulip/zulip/issues/31201
* First commit: Adds 'Export permissions' table.
* Second commit: Fixes live update issue in the `start export` modal.
<details>
</details>
=> realm_export: Add 'Export permissions' table.

web/src/typeahead_helper.ts, web/styles/typeahead.css, web/templates/typeahead_list_item.hbs
Fixes partially [#26831 ](https://github.com/zulip/zulip/issues/26831)
Bot icon shown in the typeahead recipient list which pops up in the compose box while typing.
On typeahead hover, bot icon takes the color of the font for better contrast.
[CZO thread](https://chat.zulip.org/#narrow/stream/101-design/topic/more.20user.20indicators/near/1643075)
<details>
<summary>Compose recipient picker</summary>
<hr></hr>
</details>
<details> …
=> compose: Show bot icon after bot name in recipient picker.

CONTRIBUTING.md, docs/contributing/commit-discipline.md
<details>
<summary>
screenshots
</summary>
</details>
=> contributor docs: Add a page on taking over prior work.

web/src/settings_invites.ts
This PR refactors the confirmation modals for resending and revoking invitations.
It includes the following changes:
- Use `dialog_widget` instead of `confirm_dialog` to launch confirmation modals for resending and revoking invitations. 
- Change the error text as stated in #31395.
- Associate each modal with a specific ID.
- `resend_invite_modal`: for the resend invitation confirmation modal.
- `revoke_invite_modal`: for the revoke invitation confirmation modal.
- Display errors encountered during resending or revoking invitations within the confirmation modal, keeping the modal open.
- <details>
<summary>Stop the process of revoking or resending invitations if an error occurs.</summary>
For example, earlier, in the case of revoking an invitation, the invitation was revoked disregarding …
=> popovers: Refactor resend and revoke invitation confirmation modals.

web/src/admin.js, web/src/settings.js, web/src/settings_config.ts, web/src/settings_notifications.ts, web/src/stream_edit.js, web/src/tippyjs.ts, web/templates/settings/notification_settings.hbs
This PR addresses the issue where the "Allow message content in message notification emails" setting in user settings was not accurately reflecting the organization-level configuration. When the setting is disabled at the organization level, the corresponding checkbox should appear both disabled and greyed out in the user settings, preventing users from enabling it. Previously, users could still check the box, although the emails did not contain message content.
1. **Disable and Grey Out Setting:**
- If the "message content in message notification emails" is disabled at the organization level, the user setting now appears both disabled and greyed out, accurately reflecting the organization policy.
- Added a tooltip when hovering over the disabled checkbox: "Including message content in …
=> settings: Improve handling of "message content in email notifications" setting.

web/src/stream_edit.js
"update_default_stream_and_stream_privacy_state" function should be called only
when changing or discarding settings in "Stream permissions" subsections and not
when changing settings in "Advanced configurations" subsection, since the behavior
of stream privacy and default stream options does not depend on settings in
"Advanced configurations".
This also fixes the bug of trying to access "checked" property on undefined value of
$default_stream.find("input"), since there is no such input in "Advanced configurations"
section.
<details> …
=> stream_edit: Fix code being called for wrong subsection.

tools/test-js-with-node, web/src/scheduled_messages_overlay_ui.js, web/src/scheduled_messages_overlay_ui.ts
I manually tested the module by scheduling some messages (both type "stream" and "private"), testing keyboard events like `delete` to remove the scheduled msg, `enter`  to edit the msg. Also tested if the messages are sorted in correct order based on their scheduled time.
=> scheduled_messages_overlay_ui: Convert module to TypeScript.

web/src/message_scroll.js
Fixes #31833
Quoting from the issue:
Some of the reasoning behind that proposal was:
We want the first unread message to be what gets highlighted by the blue box, since that's what you should read first. It's bad to eat one unread message when entering a message feed via N or otherwise.
A consistent algorithm would be that messages get marked as read when you move the blue box past them ... except that there'd be no way to mark the last message that way.
Because the bottom being visible marks things as read, it should be fine to make this change now, even though there wouldn't currently be a way to use the location of the blue box to mark the last message in the current view as read.
=> message_scroll: Mark message as read after blue box moves past it.

web/src/message_list_view.ts, web/templates/recipient_row.hbs
Fixes #31958
[CZO Discussion ](https://chat.zulip.org/#narrow/stream/101-design/topic/Date.20indicators.20in.20search.20results)
<details>
<summary>See Before</summary>
</details>
<details>
<summary>See After</summary>
</details>
=> message_header: Add date on every recipient bar in search results.

web/src/search.ts
Fixes bug reported here:
https://chat.zulip.org/#narrow/channel/9-issues/topic/Broken.20links.20to.20previous.20messages.3F/near/196462
=> search: Only move cursor to end of selection if cursor is there already.

web/src/stream_popover.js
Previously, when selecting a new channel in the "move topic" modal using the keyboard, focus failed to advance to the topic input automatically. Users had to press the tab key an extra time to move focus to the topic input, which was not the intended behavior.
This PR modifies the `move_topic_on_update` function in `web/src/stream_popover.js` to explicitly set focus on the topic input field after a channel is selected.
Fixes: [CZO DIscussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/move.20topic.20modal.20keyboard.20focus/near/1954801)
<details> …
=> modals: Fix focus advancement in move topic modal.

web/src/topic_link_util.ts, web/tests/topic_link_util.test.js
`&` in topic names like `&copy;` can result in broken stream topic links. So we generate fallback markdown links for them too. 
This is a follow up to #30071.
<details>
</details>
=> topic_link_util: Add `&` as a character which can produce broken links.

web/src/message_scroll.js
Since `scroll_finished` is already called post render and we don't have to wait for anything rendering before calling `unread_ops.process_visible`, we can just directly call it.
=> message_scroll: Remove unnecessary `setTimeout` call.

web/src/add_subscribers_pill.ts, web/src/pill_typeahead.ts, web/src/user_group_edit_members.ts, web/src/user_groups.ts, web/tests/pill_typeahead.test.js, web/tests/user_groups.test.js
We do not show groups that will break the DAG constraint on being added to a group as subgroups in the typeahead shown in the members edit UI.
Fixes #32087.
<details>
</details>
=> user_groups: Do not show invalid subgroups in typeahead.

web/src/message_events.js, web/src/server_events_dispatch.js, web/src/user_topics_ui.ts, web/tests/dispatch.test.js
This adds live update support for `is-followed` narrow. We need to render the narrow again instead of just adding the relevant messages from the updated topic since it not easy to determine which message we need to add based on the selected message of the user and which messages to ask from the server.
=> message_events: Refresh `is-followed` narrow on topic visibility update.

web/src/attachments_ui.ts, web/src/dialog_widget.ts, web/src/onboarding_steps.ts
These are some minor independent fixes I observed in the last few days.
<details>
</details>
=> onboarding_steps: Fix blueslip error message. 

zerver/forms.py, zerver/tests/test_signup.py
Email is not case-sensitive. And password is obviously case-sensitive, so no point mentioning that.
Instead of:
Let's have:
=> auth: Fix invalid credentials message in login form.

zerver/lib/export.py, zerver/lib/import_realm.py, zerver/lib/test_classes.py, zerver/lib/thumbnail.py, zerver/lib/upload/__init__.py, zerver/tests/test_import_export.py, zerver/tests/test_markdown_thumbnail.py
**No tests yet**, but tested manually with both zulip=>zulip and Slack imports, so the main code is ready for normal review.
We didn't have thumbnailing for images coming from data import and this commit adds the functionality.
There are a few fundamental issues that the implementation needs to solve.
1. The images come from an untrusted source and therefore we don't want to just pass them through to thumbnailing without checking. For that reason, we cannot just import ImageAttachment rows from the export data, even for zulip=>zulip imports. The right way to process images is to pass them to maybe_thumbail(), which runs libvips_check_image() on them to verify we're okay with thumbnailing, creates ImageAttachment rows for them and sends them to the thumbnailing queue worker. This approach …
=> thumbnail: Make thumbnailing work with data import.

web/src/copy_and_paste.ts, web/tests/copy_and_paste.test.js
If we paste a stream-topic URL that can be pretty formatted (as per #29302),
we only formatted the link if the `#**stream>topic**` syntax would produce a 
valid link (as per #30071).
This PR changes this behaviour to generate a normal fallback markdown url syntax 
in case the `#**stream>topic**` syntax would produce a broken link.
Fixes #31904
<details>
[Screencast from 2024-10-09 00-53-12.webm](https://github.com/user-attachments/assets/fa71b72b-8cc3-4cce-91a1-cbb1d67344c2)
The topic name here produces an invalid `#**stream>topic**` link.
- We first use the typeahead to generate the fallback syntax, as done in #30071 
- Then we paste the link to the topic, which again generates the fallback syntax, **as was needed**
- We then paste using …
=> copy_and_paste: Paste fallback md link if syntax link will be broken.

web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/input_pill.css, web/styles/settings.css
This PR refactor all the theme colors used in `input_pill.css` and `dark_theme.css`.
Note:
- The first commit fixes the issue described in this [comment](https://github.com/zulip/zulip/pull/31544/files#r1783231857) of PR #31544.
- Screenshots in before column are taken from main branch.
| `#compose-direct-recipient .pill-container`  | `#compose-direct-recipient .pill-container`  |
| ![{7AE026D0-D01C-4CB0-992D-81732761D917}](https://github.com/user-attachments/assets/c985e38a-ff8f-4ff3-8caf-31d90aaed5e2)  | ![image](https://github.com/user-attachments/assets/3cf29064-e12c-4202-9e75-a0ca2ec41c85) |
| ![{B36D08A9-101C-40B3-8E00-B249A36D6566}](https://github.com/user-attachments/assets/9adfbd01-17c1-4e55 …
=> Refactor theme colors for `input_pill`.

web/styles/right_sidebar.css, web/templates/right_sidebar.hbs
This fixes a nasty little regression that torqued the centering of presence circles and hover buttons. In doing so, it actually cleans up one of the last remaining bits of left/right sidebar interdependence by removing the `.filters` class, whose prominent row-height was overriding what should've been applied to `.buddy-list-section`.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/shifted.20presence.20circles.20in.20right.20sidebar/near/1962405) (presence circles), [CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/buddy.20list.20.2E.2E.2E.20height/near/1965411) (vdots)
| --- | --- |
| ![right-sidebar-rows-before](https://github.com/user-attachments/assets/017299f5-c8ad-41f3-87cb-167db2f23e78) | …
=> right_sidebar: Correct line-height by decoupling .filters class.

web/styles/zulip.css
While working on #32122, I noticed that wrapped empty-title lines collide with each other. This is basically a Bootstrap override, but also something that likely got overlooked on the information-density project from Spring 2024.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/lines.20collide.20on.20empty.20feed.20titles/near/1968970)
| --- | --- |
| ![no-dms-with-before](https://github.com/user-attachments/assets/cd746cd3-424b-4ccd-8d3e-b7e20d522c44) | ![no-dms-with-after](https://github.com/user-attachments/assets/744dfe4c-f636-4d8d-9ae5-9fc52a251ec4) |
| ![empty-mentions-before](https://github.com/user-attachments/assets/8219cd6e-95ff-482e-ba79-f103ee640fce) | …
=> empty_titles: Set line-height to match font size.

zerver/lib/webhooks/git.py, zerver/webhooks/gitea/tests.py, zerver/webhooks/gitea/view.py, zerver/webhooks/github/tests.py, zerver/webhooks/github/view.py, zerver/webhooks/gogs/tests.py, zerver/webhooks/gogs/view.py
Fixes: https://chat.zulip.org/#narrow/channel/127-integrations/topic/GitHub.3A.20Wrong.20user.20identified.20as.20unassigned/near/1965136
On un-assigning everyone (when multiple people are assigned) with a single click, a message is generated for every single member un-assigned separately.
<details>
</details>
=> webhooks: Fix the message sent on unassignment of Github pull requests.

help-beta/src/styles/main.css, help/configure-emoticon-translations.md, help/emoji-and-emoticons.md, help/emoji-reactions.md, help/keyboard-shortcuts.md, help/search-for-messages.md, tools/convert-help-center-docs-to-mdx
Partially fixes #31255. We'll need to copy images to src/ at the time of cutover. See
https://chat.zulip.org/#narrow/stream/6-frontend/topic/Handling.20images.20in.20help.20center.20starlight.20migration.2E/near/1915130 for more details.
We've also copied over css relevant to markdown images, while making some small changes to it so that it works better with existing starlight styling.
Note: It would be good to replace the emojis being used in the emoticon translation table directly with the emoji, but there are some weird alignment issues that happen with it. I'll fix that in #31821 instead. 
Image with border, all images will have this:
Help center icon class using the image tag:
.emoji-small example:
There is no .emoji-big example to display, so the …
=> help-beta: Add support for images.

zerver/forms.py, zerver/tests/test_decorators.py, zerver/tests/test_signup.py
Follow-up on #32104 - we decided this is the better string to use.
=> auth: Tweak invalid credentials error message.

zerver/lib/storage.py
Previously, the hashing logic for static avatar files hashed the default and medium files separately, which didn’t match how user-uploaded avatars work—where you just add the "-medium.png" suffix to get the medium version. Since we don’t have clear documentation for avatars yet, this caused some issues for the mobile apps.
This PR makes sure the default and its medium variation share the same hash. So, the medium variants can be accessed by just adding the "-medium" suffix to the system bots default avatar file. 
User-uploaded avatar:
`https://chat.zulip.org/user_avatars/2/f641fe6b0cdca129f1ad583f6388672bf8ab64d8-medium.png`
`https://chat.zulip.org/user_avatars/2/f641fe6b0cdca129f1ad583f6388672bf8ab64d8.png`
vs
Static system bots avatar (after rework): …
=> storage: Rework static avatar files hashing logic.

web/src/pm_list.ts, web/styles/left_sidebar.css, web/templates/left_sidebar.hbs
DM heading-row controls are shown whenever the mouse hovers over any of the DMs area.
Additionally, the order of the DM heading-row controls are reversed in an experimental commit, putting the New DM control to the right, beside the unread count (if any).
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/.22New.20topic.22.20in.20stream.20menu/near/1965458)
=> left_sidebar: Show Direct Messages controls on DM area hover.

web/styles/app_components.css, web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/image_upload_widget.css, web/styles/settings.css, web/styles/subscriptions.css, web/styles/zulip.css
This PR removes the blue background and borders from dark theme modals and toasts, and also updates the light mode backgrounds and borders according to @terpimost's new design.
It also improves the Organization logo area by aligning elements to the left, and using the exact background colors from the navbar (the backgrounds beneath logos have been opened up, too). Various layout improvements are part of that commit as well.
Note that this PR is meant as a prerequisite for testing redesigned buttons in #31595.
[CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/removal.20of.20sea-green.20buttons/near/1944206)
| Dark mode, before | Dark mode, after |
| --- | --- |
| ![personal-profile-dark-before](https://github.com/user-attachments/as …
=> modals: Set new light, dark theme background and borders.

help/include/how-to-start-a-new-topic.md, help/include/send-dm.md, help/include/when-to-start-a-new-topic.md, help/introduction-to-topics.md
Document new ways to do it from the left sidebar.
The conditional instruction for new DMs was out of date.
I also removed some extra info that didn't seem relevant:
- You won't have a topic to clear if you started a conversation with the ways recommended here.
- I don't think the fading info belongs here (and we have a first-time banner for it now).
- I don't think it's worth mentioning auto-complete when talking about new conversations.
Current: https://zulip.com/help/starting-a-new-direct-message
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/introduction-to-topics#when-to-start-a-new-topic
<details>
<summary>
Updated
</summary>
</details>
=> help: Improve documentation about starting a new conversation.

web/templates/confirm_dialog/confirm_deactivate_stream.hbs
=> channel settings: Remove extraneous channel name from modal.

web/styles/app_components.css
This PR corrects some unsightly flashes of white on `:active` button states in dark mode, and also shores up the text-decoration and color inheritance for `a.button` cases.
| --- | --- |
| ![deactivate-btn-active-before](https://github.com/user-attachments/assets/f90ec782-af24-4443-9701-70901f3a36ae) | ![deactivate-btn-active-after](https://github.com/user-attachments/assets/b1ea5914-8017-4906-8d09-86d61427e906) |
<details> …
=> dark theme: Make critical button fixes.

zerver/lib/export.py, zerver/lib/import_realm.py, zerver/lib/test_classes.py, zerver/lib/thumbnail.py, zerver/lib/upload/__init__.py, zerver/tests/test_import_export.py, zerver/tests/test_markdown_thumbnail.py
Backport of #32039
Tested a zulip=>zulip import and a Slack import to check that this still works after backporting.
=> [Backport] thumbnail: Make thumbnailing work with data import.

zerver/lib/test_helpers.py
This is a somewhat hacky and fragile fix. Due to the order in which imports seem to happen, the original ordering breaks RealmImportExportTest: if one of the `use_s3_backend` tests runs before test_import_realm, the latter will fail while processing thumbnailing, as S3UploadBackend ends up leaking and
zerver.worker.thumbnail.upload_backend is still set to S3.
By making that mock.patch the first one that gets entered, and thus the last one to get cleaned up, we fix the leak and upload_backend is set back to LocalUploadBackend as it should.
This fixes the failure that I get via `test-backend RealmImportExportTest`, and sometimes in `test-backend` running all the tests; I'm guessing that's when one of the `s3` tests ends up run in the same process with `test_import_realm`.
```spoiler
p$ …
```
=> tests: Fix order of mock.patch in use_s3_backend.

web/src/buddy_list.ts, web/templates/buddy_list/section_header.hbs, web/templates/right_sidebar.hbs, web/tests/activity.test.js
This PR has several commits, mostly refactoring some code that could be cleaner that I noticed as I was editing this.
There are three changes:
* Adding a placeholder for the participants section, since that was overlooked last time (we actually do have a situation when we want to show a placeholder, just only when searching).
* Fixing a bug where the participant count became incorrect during search.
* (the main change) Uncollapsing all sections during search so all matching users are visible. When there is no search text in the search bar, the sections collapse state return to whatever the user last had them set to.
=> buddy_list: Show all sections (uncollapse) when searching.

api_docs/changelog.md, version.py, zerver/openapi/zulip.yaml, zerver/views/user_groups.py
Previously, the `group_id` was not included in the success response of the user group creation API. This omission made it challenging for clients to reference the newly created user group.
This commit enhances the API by returning a success response that includes the unique ID of the user group with the key `group_id`. This improvement simplifies the process for clients to easily reference the newly created user group.
Fixes: #29686
<details> …
=> user_groups: Include group_id in success response on group creation.

zerver/data_import/mattermost.py, zerver/lib/email_notifications.py, zerver/tests/test_email_notifications.py
html2text mangles Unicode by default, with a `--unicode-snob` option to disable it. If I have to get called a “snob” for wanting to correctly support non-English languages, then uh, I’ll take one for the team.
https://github.com/Alir3z4/html2text/blob/2024.2.26/html2text/config.py#L111-L150
=> email_notifications: Prevent html2text from mangling Unicode

web/src/echo.ts, web/tests/echo.test.js
We simply forgot to `add_to_narrow` locally echoed messages if the current narrow changed before we received confirmation from server.
Tested by populating database with 10k messages and sending a message in different topic after applying this diff:
```diff
diff --git a/web/src/message_fetch.ts b/web/src/message_fetch.ts
index 738ce45ade..eed6ba39f1 100644
--- a/web/src/message_fetch.ts
+++ b/web/src/message_fetch.ts
@@ -63,34 +63,34 @@ export const consts = {
//
// It's rare to have hundreds of unreads after the cursor, asking
// for a larger number of messages after the cursor is cheap.
-    narrow_before: 60,
-    narrow_after: 150,
+    narrow_before: 10,
+    narrow_after: 10,
// Number of messages that a message list restored from cached
// message list data should have to maintain …
```
=> echo: Fix send messages not visible when auto narrowed to recipient.

web/styles/app_variables.css, web/styles/compose.css, web/styles/dark_theme.css, web/styles/input_pill.css
This PR corrects some subtle but maddening (once you see them) differences between input elements in the compose box (the channel/DM widget, the topic box, and the compose area).
Specific changes to note:
* Borders are now exactly the same for all three elements. Both light and dark mode had subtle differences, although light mode was more obvious, with the elements on the recipient row all bordered by a neutral gray, despite the compose area's more blue-gray.
* The topic box now shares the same 4px border radius as other elements.
* The topic box in light mode uses the same color focus outline as the compose area, which is much more obvious and prominent. The dark-mode topic box previously had no outline change, but now also takes the same outline as the compose area.
* Although the …
=> compose: Bring input elements into concord.

zerver/webhooks/slack_incoming/tests.py, zerver/webhooks/slack_incoming/view.py
**Summary:**
This PR ensures that errors in the Slack incoming webhook handler return JSON responses with Slack's expected format: `{ok: false, error: "error string"}`. 
Previously, errors were returned using Zulip's default format (`{"result": "error", "msg": ""}`), which did not match Slack’s expected response structure. This update aligns error handling with Slack’s API requirements, improving compatibility for integrations.
**Fixes:**  
Fixes: [#31878](https://github.com/zulip/zulip/issues/31878)
---
No visual changes.
<details> …
=> slack_incoming: add ok=false to json in case of error.

zerver/actions/create_user.py, zerver/lib/onboarding.py, zerver/tests/test_signup.py
During account creation when a user selected to import settings from an existing account, the "Mark visibility_policy_banner as read" step was raising integrity error.
It is because `copy_onboarding_steps` is already executed earlier in the `do_create_user` codeflow. If the source profile had already marked `visibility_policy_banner` as read, we were facing integrity error.
This PR fixes the bug.
<details>
</details>
=> create_user: Fix integrity error when importing settings.

web/src/buddy_data.ts
This was filtering out users that were marked as
inactive for more than a year, but we want to show all participants, including inactive ones.
More discussion on this here:
https://chat.zulip.org/#narrow/channel/9-issues/topic/In.20this.20conversation.20and.20invisible.20mode/near/197309
I didn't know how to test this locally because all users are recently added and not inactive.
=> buddy_data: Don't filter out inactive participants.

web/src/util.ts, web/tests/util.test.js
Follow-up for this PR comment: https://github.com/zulip/zulip/pull/30510#discussion_r1803859377.
The helper function `get_custom_time_in_minutes` still returns the time value from the input, so that the app doesn't break when the error is thrown. Currently, this is only used in the invite users modal, but will likely be used in other modals where a user can set a custom time with different time units (minutes, days, etc.).
---
<details>
</details>
=> util: Make get_custom_time_in_minutes throw error for unknown unit.

help/configure-home-view.md, help/keyboard-shortcuts.md, web/src/common.ts, web/templates/keyboard_shortcuts.hbs
For all users, we want to display "Ctrl" for the "Ctrl" "[" keyboard shortcuts that match the "Esc" Vim keybinding behavior.
We use the "data-mac-key" attribute to override the default mapping of "Ctrl" to "Cmd" for Mac users in the documentation of these keyboard shortcuts. This data attribute was already in place for another exception to our default remapping of documented keyboard shortcuts for Mac users.
Fixes #20107.
---
`git grep '\[</kbd>'` after changes:
```
help/configure-home-view.md:<kbd data-mac-key="Ctrl">Ctrl</kbd> + <kbd>[</kbd> shortcut.
help/configure-home-view.md:   (<kbd data-mac-key="Ctrl">Ctrl</kbd> + <kbd>[</kbd> or <kbd>Esc</kbd>
help/configure-home-view.md:<kbd data-mac-key="Ctrl">Ctrl</kbd> + <kbd>[</kbd> shortcut.
help/keyboard-shortcuts.md:  <kbd …
```
=> keyboard-shortcuts: Display "Ctrl" for Vim "Esc" keybinding behavior.

web/src/invite.ts, web/src/settings_components.ts, web/styles/dark_theme.css, web/styles/zulip.css, web/templates/invite_user_modal.hbs
Prep commit for #31957.
This refactor moves the functions set_custom_expires_on_text, set_expires_on_text, and set_custom_time_inputs_visibility from invite.ts to settings_ui.ts.
It also adds general class names to elements to improve extensibility.
This change was made so that these functions can be reused in several places in the future.
[CZO thread](https://chat.zulip.org/#narrow/channel/6-frontend/topic/realm.3A.20Schedule.20realm.20deletion.20time.20while.20deactivating.20realm/near/1963971)
| ![image](https://github.com/user-attachments/assets/72057c29-3375-4b14-91a0-4bf74db3f3dc) | ![image](https://github.com/user-attachments/assets/5e8326ed-e9d8-4cfc-8ab5-673eba9075a8) |
| …
=> Prep commit for adding scheduled realm data deletion time.

templates/zerver/find_account.html, templates/zerver/invalid_realm.html
This PR customizes the `/find/accounts` page and the "No Organization Found" page for self-hosted Zulip servers. Previously, these pages were tailored for Zulip Cloud organizations, but this update ensures that self-hosted servers display more appropriate messages.
1. **Customize `/find/accounts` page for self-hosted servers**:
- The message displayed is now: 
- For Zulip Cloud: "for all the Zulip Cloud organizations in which you have active accounts."
- For self-hosted servers: "for all the Zulip organizations on this server."
- This change makes the text more relevant to users on self-hosted instances.
2. **Update the "No Organization Found" page**:
- For Zulip Cloud:
- Message updated to: "Please try a different URL, get a list of your Zulip Cloud accounts, or contact..."
- For …
=> Customize /find/accounts and "No Organization Found" Pages for Self-Hosted Servers.

web/src/dialog_widget.ts, web/src/loading.ts, web/src/user_profile.ts, web/templates/dialog_widget.hbs, web/templates/user_profile_modal.hbs
This PR refactors the duplicated spinner logic from the `dialog_widget` and `user_profile` modules by extracting the functionality for loading indicators in a button into reusable components, defined in `loading.ts`.
- Extracted loading spinner logic from the following functions:
- `dialog_widget.show_dialog_spinner`
- `user_profile.show_button_spinner`
- `dialog_widget.hide_dialog_spinner`
- `user_profile.hide_button_spinner`
- Introduced two new reusable components:
- `show_spinner` for displaying the spinner
- `hide_spinner` for hiding the spinner
This refactoring reduces redundancy and centralizes the logic for showing and hiding spinners, improving code reusability, maintainability, and making future updates easier.
Fixes: https://github.com/zulip/zulip/issues/26691
=> settings: Deduplicate show and hide spinner functions.

web/styles/left_sidebar.css
This fixes a layout-breaking regression I introduced in #32188, but also better hardens this bit of grid definition to prevent similar issues in the future.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/topic.20filter.20layout/near/1974040)
| --- | --- |
| ![clear-button-before](https://github.com/user-attachments/assets/ca0cf1cc-ee94-4421-bc20-dd334ccbbe77) | ![clear-button-after](https://github.com/user-attachments/assets/1ef84773-9309-41e5-afc6-abc986c3b53b) |
<details> …
=> left_sidebar: Solidify grid placement of filter-clearing button.

help/manage-user-groups.md, web/templates/settings/organization_permissions_admin.hbs
The previous wording was ambiguous as to whether this permission means the ability to administer all groups in the organization.
=> groups: Clarify meaning of global admin setting.

web/styles/right_sidebar.css
More context here:
https://chat.zulip.org/#narrow/channel/101-design/topic/userlist.20avatar.20slow.20load/near/1974268
=> buddy_list: Move user link a bit left to line up with empty message.

web/src/stream_popover.js
Previously, when there were no messages in the topic being moved, the banner in the move topic modal only showed a "Failed" error banner which did not convey the actual error to the user. Also, a server call was being made even when there were no messages in the topic being moved.
This PR explicitly handles the non-existent topic, prevents a call to the server when the message_id is undefined, and displays a more informative error banner to the user.
Fixes: [CZO Discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/Error.20moving.20topic.20with.20no.20messages/near/1966728)
<details>
Individual …
=> stream_popover: Handle no messages condition for a topic being moved.

web/styles/app_components.css, web/styles/app_variables.css, web/styles/compose.css, web/styles/inbox.css, web/styles/left_sidebar.css, web/styles/recent_view.css
This PR introduces the new unread-counter colors from @terpimost (https://terpimost.github.io/zulip-sidebar/), as well as the colors for DM partner icons, with the exception of user circles (which maintain their gray in Vlad's design, albeit as dots and with a different set of colors than currently in use).
Likely points of [CZO discussion](https://chat.zulip.org/#narrow/stream/101-design/topic/remaining.20sidebar.20grays.20.28unreads.2C.20DM.20partner.20icons.29/near/1959505) here:
1. The three levels of unread-counter prominence, including the 'quiet' ones for Drafts, Starred messages, and Scheduled messages, which here have their border removed, in keeping completely with Vlad's work. As an experiment, summary counters (Channels, Direct Messages) are also shown in the 'quiet' style.
2. …
=> left_sidebar: Update remaining gray left sidebar elements.

help/user-list.md, zerver/lib/zulip_update_announcements.py
The first commit updates the right sidebar help center page.
Current: https://zulip.com/help/user-list
<details>
<summary>
Updated
</summary>
</details>
----
The Zulip update needs to be tested!
=> zulip updates: Add update about sidebars and file size limit.

corporate/lib/stripe.py, corporate/lib/support.py, corporate/views/support.py, zerver/actions/create_realm.py, zerver/lib/streams.py
When new realms are created on Zulip Cloud, a notification message is sent to the admin realm. This moves the logic for generating and sending that message to the BillingSession framework in `corporate.lib.stripe.py`.
This is a preparatory change to adding more notification messages for other realm and remote server/realm changes.
**Notes**:
- Adds a channel name parameter for sending these messages since future messages may be sent to channels other than the one used for new organization signups.
- Adds a fallback of sending a direct message to admins in the admin realm when a channel with the specified name does not exist.
- Removes the `get_signups_stream` helper function as a result of the above changes.
- Removes the `get_realm_support_url` in `corporate.lib.support.py` in favor of …
=> notifications: Move new organization notifications to BillingSession framework.

zerver/tests/test_upload.py, zerver/views/users.py, zproject/urls.py
This refactor separates the `avatars/<email_or_id>` endpoint into two
distinct endpoints for emails and user IDs, aligning with existing API
path conventions (e.g the `users/` endpoint).
<details>
</details>
=> avatars: Split email-based and user ID-based avatar endpoints.

web/styles/left_sidebar.css, web/styles/popovers.css, web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs
This PR introduces a few improvements to alignment in the left sidebar and its condensed nav popover:
1. The `line-height: 1` fix is better scoped to low-resolution screens. Careful eyes will note that the 'g' in 'Starred messages' had the very bottom of its descender cut off. That line-height adjustment is also eliminated on rows with quiet unreads, as their baseline alignment introduced here makes an adjustment unnecessary.
2. Quiet unreads are now aligned on the same baseline as their labels.
3. Quiet unread alignment has been corrected similarly in the condensed nav popover, leading to better alignment on the Drafts and Scheduled messages popover items overall.
4. There are a few improvements to the popovers CSS for info density.
[CZO …
=> left_sidebar: Unread, nav area alignment fixes.

corporate/lib/stripe.py, zerver/actions/create_realm.py, zerver/actions/create_user.py, zerver/actions/realm_settings.py, zerver/actions/streams.py, zerver/actions/users.py, zerver/lib/retention.py, zerver/lib/soft_deactivation.py, zerver/lib/upload/__init__.py, zerver/management/commands/deliver_scheduled_emails.py, zerver/models/recipients.py, zerver/tests/test_subs.py, zerver/transaction_tests/test_user_groups.py, zerver/views/streams.py, zerver/views/tusd.py, zerver/views/user_groups.py, zerver/views/user_settings.py, zerver/worker/missedmessage_emails.py, zilencer/views.py
This PR is follow-up of #32205
Let me know if you'd like to squash the last 5 commits. I kept them separate as the commit messages explicitly explain the reasons which led to savepoint creation, so it'd be easier to review & revisit later.
<details>
</details>
=> transaction: Add savepoint=False or durable=True to transaction.atomic decorators.

tools/webpack, web/webpack.config.ts
Zopfli is very slow and the development server does not use its output anyway.
=> webpack: Disable CompressionPlugin for Puppeteer tests

web/src/left_sidebar_navigation_area.ts, web/src/sidebar_ui.ts, web/styles/left_sidebar.css, web/templates/left_sidebar.hbs
Fixes #31823
[Previous Closed PR](https://github.com/zulip/zulip/pull/31873)
Relevant [CZO](https://chat.zulip.org/#narrow/stream/6-frontend/topic/left_sidebar.3A.20Fix.20keyboard.20accessibility)
When home view changes, CSS just puts the selected home view at the top of the navigation list (expanded) or to the left (collapsed), but the rendered `<li>` elements stay in the same order in DOM.
With that said, Regardless of current home view, keyboard navigation follows the order in which the `<li>` elements appear in DOM which is always the following : 
1. Inbox
2. Recent Conversatios
3. Combined feed
- Reorder `<li>` navigation list elements in DOM, based on current home view  to match the order in which they should appear. The `<li>` elements are now ordered correctly on initial state …
=> left_sidebar: Fix keyboard accessibility out of order.

web/styles/app_components.css, web/styles/app_variables.css, web/styles/compose.css, web/styles/left_sidebar.css, web/templates/left_sidebar.hbs, web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs, web/templates/popovers/send_later_popover.hbs
In addition to upping the font weight in light and dark modes, this PR begins introducing new classes for different counter attention-levels, but only the quiet class is introduced on those elements that currently show a quiet count (Starred, Drafts, and Scheduled messages).
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/Starred.20messages.20counter.20in.20dark.20mode.20not.20very.20visible/near/1977477)
| --- | --- |
| ![quiet-count-light-before](https://github.com/user-attachments/assets/dffc3f50-ce54-4853-8dba-e037474fcde4) | ![quiet-count-light-after](https://github.com/user-attachments/assets/dc732a0d-58cf-4825-bde7-ae2aa8f1838b) |
| ![quiet-count-dark-before](https://github.com/user-attachments/assets/7 …
=> unread_count: Increase prominence of quiet unreads.

zerver/data_import/mattermost.py, zerver/data_import/rocketchat.py
This PR removes the logic that skips messages longer than 10K characters during the import process. With the changes introduced in #32090, those messages can now be imported with truncation, making the previous check unnecessary.
<details>
</details>
=> import: Remove skipping of too-long messages during import.

web/e2e-tests/stream_create.test.ts
In 245357c86800e5a2ceb418d1d56d2c6cd80ba791 we added a redirect after stream creation, to go to the stream feed. The puppeteer tests weren't updated, so sometimes it was able to run as before and pass before the redirect took place and sometimes it didn't. This commit updates the test to work with the new redirect.
=> stream_create: Fix puppeteer test flake from modal reopening.

zerver/data_import/slack.py, zerver/lib/thumbnail.py, zerver/lib/upload/local.py, zerver/lib/upload/s3.py
For resizing the `icon.png` files for realm icon we use `resize_avatar`:
https://github.com/zulip/zulip/blob/cb6c60ef7ab2aadb665dc5051e5e8c2e9f70323c/zerver/lib/upload/s3.py#L355-L376
But the Slack import codepath was calling `resize_logo`, which is therefore wrong. So we fix this, while also renaming other uses of `resize_avatar` in icon contexts to `resize_realm_icon`, because this is hard to mentally keep track of otherwise and causes this kind of bugs.
Despite this, in my basic testing Slack import still ended up with a correctly displaying realm icon on the login page - I think by coincidence, so we still want to fix this.
=> slack: Call the correct resize_* function when importing realm icon.

web/src/buddy_list.ts, web/styles/app_variables.css, web/styles/right_sidebar.css, web/templates/presence_row.hbs
followup to #32128 
discussion on CZO here: https://chat.zulip.org/#narrow/channel/101-design/topic/userlist.20avatar.20slow.20load.20.2332128/near/1972343
=> buddy_list: Add background color placeholder to loading avatar.

zerver/data_import/mattermost.py, zerver/data_import/rocketchat.py, zerver/data_import/slack.py, zerver/lib/export.py, zerver/lib/import_realm.py, zerver/tests/fixtures/import_fixtures/applied_migrations_fixtures/with_complete_migrations.json, zerver/tests/fixtures/import_fixtures/applied_migrations_fixtures/with_missing_apps.json, zerver/tests/fixtures/import_fixtures/applied_migrations_fixtures/with_unapplied_migrations.json, zerver/tests/fixtures/import_fixtures/check_migrations_errors/extra_migrations_error.txt, zerver/tests/fixtures/import_fixtures/check_migrations_errors/unapplied_migrations_error.txt, zerver/tests/fixtures/import_fixtures/migration_status.json, zerver/tests/test_import_export.py, zerver/tests/test_mattermost_importer.py, zerver/tests/test_rocketchat_importer.py, zerver/tests/test_slack_importer.py
This PR adds an assertion to check the compatibility between the migration status of the exported realm and the importing server.
<details>
<summary>
Info logs for mismatches in installed apps
</summary>
Each server might have a different set of apps installed (e.g., Zulip Cloud has zilencer/corporate, but self-hosted might not). We only checks for mismatches in apps installed on both servers and log warn on any detected mismatch in installed apps
```
...
2024-09-25 09:49:01.461 WARN [] Local server has 'sessions' app installed, but exported realm does not.
2024-09-25 09:49:01.461 WARN [] Exported realm has 'some_missing_app' app installed, but this server does not.
... 
```
</details>
<details>
<summary>
Error log for Zulip version mismatch
</summary>
```
Processing dump: …
```
=> export/import: Add assertion to check migration compitability when importing realm.

package.json, patches/svgicons2svgfont.patch, pnpm-lock.yaml, version.py
```
(node:13734) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
- nfroidure/svgicons2svgfont#173
=> svgicons2svgfont: Patch to fix Node 22 punycode DeprecationWarning

zerver/tests/fixtures/import_fixtures/check_migrations_errors/extra_migrations_error.txt, zerver/tests/fixtures/import_fixtures/check_migrations_errors/unapplied_migrations_error.txt, zerver/tests/test_import_export.py
Fix-up to #31681
Otherwise, these tests fail if ZULIP_VERSION is different locally from what's hard-coded. Use a placeholder instead and replace dynamically in a helper function.
=> test_import_export: Don't hard-code ZULIP_VERSION in fixtures.

zerver/actions/create_realm.py
If we don't revoke sessions, this can lead to issues when we import a realm (e.g. from Slack) into the original subdomain for the same organization. Because then, users who already had sessions before the move end up stuck:
- when they try to open Zulip on the original subdomain, which now has the imported instance, they get redirected to the moved subdomain due to their pre-existing session cookie.
- they can't even log out to get rid of the bugged cookie, because the account they're logged into in that session is now on the moved subdomain.
=> change_realm_subdomain: Revoke user sessions.

corporate/lib/activity.py, corporate/lib/stripe.py, zilencer/models.py
Python parameter defaults are only evaluated once at the function definition site, not at each call site. So these defaults were incorrectly evaluating to the server’s startup time rather than the current time.
- Followup to #25316
- Cc @prakhar1144 (#28070, #28242)
- Cc @laurynmm (#28634)
=> corporate: Fix misuse of timezone_now() as parameter default

web/webpack.assets.json
Event status page no longer uses any styles from this page.
Fixes #23629
=> webpack: Remove unused landing_page dependency on event status page.

web/styles/message_header.css
This was due to `box-shadow` used to hide the content was incorrectly overridden in `.sticky_header` from the `.message_header` just above.
The bug is highly reproducible since it happens due to minor pixel differences when rendering.
| --- | --- |
| ![Screenshot from 2024-11-09 20-50-53](https://github.com/user-attachments/assets/50a9d7fb-c644-4161-b77b-b4e854993a80) | ![Screenshot from 2024-11-09 20-50-38](https://github.com/user-attachments/assets/a11df56f-4dac-4a68-942f-e00166c2dd63) |
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/message.20peeks.20out.20when.20scrolling/near/1975833
=> message_header: Fix message content visible above sticky header.

web/babel.config.js
This was a workaround for a bug in babel-plugin-rewire-ts (#26381), which we’ve now removed (#32296).
=> babel: Remove transform-optional-chaining workaround

web/styles/settings.css
This PR cleans up the styles around user-list previews in the settings pane, and also makes better use of the available space for different previews, bringing it into better parity with the emoji-preview area.
As part of this clean-up, undesirable scrollbars and apparent scroll areas are removed.
[
CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/display.20status.20and.20profile.20picture.20in.20right.20sidebar.20.2332128/near/1975884)
| --- | --- |
| ![user-list-settings-light-before](https://github.com/user-attachments/assets/dd088f95-51d0-4131-afac-fd9c2f5a8cf4) | ![user-list-settings-light-after](https://github.com/user-attachments/assets/058b7761-e93c-4453-85d1-678e88e8e15c) |
| …
=> settings: Improve user-list style layout.

web/webpack.config.ts
`koa-body` was switched to `@koa/bodyparser` during development of #29198, so this was never used.
=> webpack: Remove unused hexoid alias

web/src/settings_account.ts, web/src/settings_sections.js, web/src/ui_init.js
This reverts commit 8eb0ca3a7cc605ea3834cbedb2771a7697b9fc7c (#32068).
We fixed the TypeScript configuration in #32327.
=> Revert "settings_account: Move async call into ui_init."

web/src/buddy_data.ts, web/templates/buddy_list_tooltip_content.hbs, web/tests/buddy_data.test.cjs
Removes "last active" time from the deactivated user tooltip and instead adds "This user has been deactivated." Also, in the deactivated bot tooltip, "This bot has been deactivated." has been added.
Fixes #32136.
| ![WhatsApp Image 2024-10-28 at 12 26 54_eef87a0d](https://github.com/user-attachments/assets/e210e949-8d81-477c-9a9e-798badf31a31) | ![image](https://github.com/user-attachments/assets/08b7c49f-be71-4e18-b8ca-4164a4e6a37c) |
| ![image](https://github.com/user-attachments/assets/63c5edc7-7f53-4116-b1c3-248be4ad2a86) | ![image](https://github.com/user-attachments/assets/82b7d2a4-9f80-4b83-ae8e-313923e8900c) | 
<details> …
=> tooltip: Remove "last active" time from deactivated user tooltip.

web/src/bundles/app.ts
Commit db24df488c0ed81c38ee1d914ae12ac223857c78 (#29286) made this a normal function rather than a jQuery plugin, so it doesn’t need to be imported for side effects.
=> bundles: Remove unnecessary bootstrap_typeahead import

tools/i18n/process-mobile-i18n, tools/i18n/unescape-contents, tools/i18n/update-for-legacy-translations, zerver/management/commands/compilemessages.py, zerver/management/commands/makemessages.py
`orjson`’s use of Unicode is more consistent with what we get from Transifex. (We could alternatively use `json`’s `ensure_ascii=False` flag.)
=> makemessages: Write with orjson

web/src/message_list.ts, web/src/message_list_view.ts, web/templates/bookend.hbs, web/tests/message_list.test.cjs
This PR removes the Subscribe and Unsubscribe buttons from the message feed and adds links to either view channel settings (if not subscribed) or manage channel settings (if subscribed) in the bottom divider.
Fixes: #32125 
<details>
<summary>UI Changes</summary>
| --- | --- |
| ![Before Image](https://github.com/user-attachments/assets/d2cdba99-9fd4-4def-93dc-366b3db8d9c0) | ![After Image](https://github.com/user-attachments/assets/3c62af51-115e-45ae-a3a8-26e051fad114) |
| ![Before Image](https://github.com/user-attachments/assets/b8855bfe-0b22-4c03-a2d0-34abacc44120) | ![After Image](https://github.com/user-attachments/assets/40f706cb-4adb-460d-a124-28a26b3e77e3) |
</details>
https://github.com/user-attachments/assets/208b55a4-9491-4388-9425-49a7c506232b
<details> …
=> message_feed: Add channel settings link and remove Subscribe/Unsubscribe buttons.

zerver/webhooks/linear/tests.py, zerver/webhooks/linear/view.py
**NOTE:** I couldn't get the environment running locally to run tests, so I'm hoping CI will help me.
The initial implementation for this feature used the issue UUID to create the topics, as some of the webhook events only provide this and it is the only way to group sub-issues with parents.
However, if we sacrifice this and allow sub-issues to be their own topic then we can avoid using the UUID as the topic name.
I think the quality of life improvement to topics here warrants this change, as UUID topic names can be come unruly very quickly. …
=> integrations(linear): make topics easier to understand

web/src/buddy_list.ts, web/styles/right_sidebar.css, web/templates/buddy_list/section_header.hbs
Fixes #32268
CZO thread: https://chat.zulip.org/#narrow/channel/101-design/topic/right.20sidebar.20headings.20.2332268/near/1980150
=> right sidebar: Redesign section headings.

puppet/zulip/manifests/app_frontend_base.pp
Zulip instances without a database included, like the Docker image, would not fail to use TLS properly, since `TLS_REQCERT` was not set in `/etc/ldap/ldap.conf`. While there's a few other ways we could fix this, just installing libldap-common on app frontend instances seems like a good solution, and has no impact on other Zulip systems, and it was already being installed through a "Recommends" tier apt dependency indirectly from the PostgreSQL server package.
Fixes zulip/docker-zulip#454.
=> puppet: Require libldap-common be installed.

web/src/blueslip_stacktrace.ts
`ResizeObserver loop completed with undelivered notifications` errors have originalEvent.error=null; in that case, it's worth including the `message` in what we display.
I think we probably want `message` in every case where this code path is relevant, so I just append it unconditionally.
=> blueslip: Include message for abnormal traces.

web/src/stream_card_popover.ts, web/src/stream_pill.ts, web/templates/popovers/stream_card_popover.hbs, web/tests/stream_pill.test.cjs
This Pull Request addresses an issue in the channel display UI by adjusting where the subscriber count is shown for channels. It removes the subscriber count from channel pills, and adds the count to channel cards. The subscriber count is styled to match the group member count in group cards and displays as "N subscribers" (or "1 subscriber" for singular cases). This change improves consistency in the UI and enhances readability.
**Fixes**: https://github.com/zulip/zulip/issues/32235.
| Area | Before | After |
| Stream Pill | ![pill-image-before](https://github.com/user-attachments/assets/8cabe3af-d858-42d1-a87d-2f89a4c09565) | ![pill-image-after](https://github.com/user-attachments/assets/624657a2-395f-47ff-88a0-9cb2e3d8c967) |
| …
=> streams: Move subscriber count from channel pills to channel cards.

web/src/buddy_list.ts
Non-functional change.
Followup to https://github.com/zulip/zulip/pull/32347#discussion_r1843068217
=> buddy_list: Move header_text calculation to where it's used.

web/src/compose_tooltips.ts, web/src/ui_init.js, web/templates/compose.hbs
This PR moves the inline tooltip off of the over-limit indicator and instead delegates it to `<body>`. The complex layout and positioning in the area of the tooltip (including where in the DOM the tooltip appears) was causing the tooltip to appear beneath rows in the right sidebar—an issue not shared with the similarly-delegated disabled compose tooltip, for example.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/Presence.20dot.20above.20the.20tooltip.2E/near/1983336)
| --- | --- |
| ![max-length-tooltip-before](https://github.com/user-attachments/assets/fc2f22c4-5b10-4340-a15f-95333047268e) | ![max-length-tooltip-after](https://github.com/user-attachments/assets/9f15d81b-9d9d-490b-83ee-0f0b35112828) |
<details> …
=> compose: Delegate max-length tooltip to body.

web/src/message_edit.ts, web/templates/confirm_dialog/confirm_edit_messages.hbs
On pressing left arrow key while in narrow stream to edit
the last message, if the user has unread messages sent in
topics other than the one where the user has sent its last
message (considering the topics for same stream) and the unread
messages were sent before the user message, the hotkey unexpectedly
marks the messages as read. Hence we disable the hotkey for
such a case.
Fixes #17737.
=> hotkey: Disable left arrow hotkey when view has unreads.

zerver/lib/import_realm.py, zerver/tests/fixtures/import_fixtures/check_migrations_errors/extra_migrations_error.txt, zerver/tests/fixtures/import_fixtures/check_migrations_errors/unapplied_migrations_error.txt, zerver/tests/test_import_export.py
This PR refines error handling in import/export process by using `CommandError` for version mismatch notifications. Previously, these errors were raised as general Exception types, which resulted in full tracebacks that were less user-friendly. This update aligns with Django’s best practices by providing a clear and concise error message with `CommandError`, enhancing readability and user experience.
Fixes: #32292 
**how would I test**
- first export by `./manage.py export --output exported_zulip -r zulip`
- extract_all of the generated `exported_zulip.tar.gz` into `./exported_zulip`
- delete the zulip realm `./manage.py delete_realm -r zulip`
- change the version in `./version.py` from `ZULIP_VERSION = "10.0-dev+git"` to `ZULIP_VERSION = "8.0-dev+git"`
when run ` ./manage.py import zulip …
=> Improve error handling for version mismatches in import/export with CommandError

web/e2e-tests/settings.test.ts
We wait for settings overlay to be fully visible before running rest of the tests. Without this, tests were flaky due to settings overlay not being present when running tests.
See https://github.com/zulip/zulip/actions/runs/11842922228/job/33002680462?pr=32331 for example.
=> settings: Fix flaky test.

web/templates/message_group.hbs, web/templates/stream_settings/browse_streams_list_item.hbs
By definition, `this` is already the current context.
=> templates: Remove redundant {{#with this}} blocks

templates/corporate/billing/upgrade.html
Currently, the user selected "pay by invoice" option requires manual license management, and a fixed-price plan offer requires automatic license management.
If we're offering a fixed-price plan and the user wants to pay by invoice, then the current system in place require us to create the invoice in Stripe first and then input it manually via the support page for the customer.
Here we remove the option to "pay by invoice" in the case where there is a fixed-price plan offer that's been configured for the organization.
If an invoice was configured in Stripe and added to the fixed-price plan offer, then a page with the invoice information will be shown to the user instead of the below screenshots.
---
**Zulip Basic with fixed-price offer - removes pay by invoice link**:
| …
=> billing: Remove invoice option for users with fixed-price plan offer.

web/src/stream_data.ts, web/tests/stream_data.test.cjs, zerver/lib/subscription_info.py, zerver/lib/types.py
- First commit is to fix the setting value in never subscribed dicts.
- Second commit is to fix the UI for admins when they are not allowed to unsubscribe others.
- Third commit is a refactor for optimization.
<details>
</details>
=> Fix can_remove_subscribers_group value in never subscribed subscriptions dict.

web/src/settings_config.ts, web/templates/settings/notification_settings.hbs, web/tests/settings_config.test.cjs
This Pull Request addresses an issue in the Notification triggers table located at the top of **Settings / Notifications**. It adds a help icon link next to **Followed topics**, directing users to `/help/follow-a-topic`. This enhancement provides quick access to relevant documentation, making it easier for users to learn how to follow topics directly from the settings page.
**Fixes**: https://github.com/zulip/zulip/issues/32033
| Before (light) | After (light) |
| --- | --- |
| ![image-before-light](https://github.com/user-attachments/assets/dfd52e61-5a37-4b35-a932-96e43393c9ae) | ![image-after-light](https://github.com/user-attachments/assets/fb183441-22f7-489b-b3a1-27c2bb57339a)
| Before (dark) | After (dark) |
| --- | --- |
| …
=> notifications: Add help link for "Followed topics" in triggers table.

web/src/list_widget.ts, web/src/recent_view_ui.ts, zerver/data_import/slack_message_conversion.py, zerver/migrations/0622_backfill_imageattachment_again.py, zerver/tests/fixtures/slack_message_conversion.json, zerver/tests/test_slack_message_conversion.py
Backports the following changes to 9.x:
- https://github.com/zulip/zulip/pull/32305
- ~~#31681~~
- ~~#32351~~
- ~~https://github.com/zulip/zulip/pull/32307~~
- https://github.com/zulip/zulip/pull/32162
- https://github.com/zulip/zulip/pull/32181
Edit: Dropped the migration status PRs; I'm not sure it is worth backporting their tests.
=> Backport several more changes to 9.x.

web/e2e-tests/settings.test.ts, web/src/custom_profile_fields_ui.ts, web/src/stream_create.ts, web/styles/modal.css, web/styles/settings.css, web/styles/subscriptions.css, web/templates/change_email_modal.hbs, web/templates/settings/account_settings.hbs, web/templates/settings/add_new_bot_form.hbs, web/templates/settings/api_key_modal.hbs, web/templates/settings/custom_user_profile_field.hbs, web/templates/settings/edit_custom_profile_field_form.hbs, web/templates/settings/language_selection_widget.hbs, web/templates/settings/notification_settings.hbs, web/templates/settings/organization_permissions_admin.hbs, web/templates/settings/organization_profile_admin.hbs, web/templates/settings/organization_settings_admin.hbs, web/templates/settings/organization_user_settings_defaults.hbs, web/templates/settings/preferences_general.hbs, web/templates/settings/preferences_information.hbs, web/templates/settings/preferences_navigation.hbs, web/templates/settings/profile_settings.hbs, web/templates/stream_settings/announce_stream_checkbox.hbs, web/templates/stream_settings/stream_creation_form.hbs, web/templates/stream_settings/stream_types.hbs
Currently, there are a lot of clickable labels in our settings menu, however upon clicking on the labels actually performs no actions. These cursors should at least perform an action when being clicked upon, otherwise they should remain to be default cursor.
Changes are of the following:
- Text that point to a button will automatically perform the button's action (e.g. opening menu). Uses pointer cursor.
- Text that point to a select/dropdown will focus on those select/dropdodwn. Uses pointer cursor.
- Text that point to a textfield will focus on those textfield. Uses pointer cursor.
- Text that clearly doesn't serve as a heading or label for a setting selector, will do nothing and receive a regular cursor rather than a pointer cursor.
- Labels uses the width of its text rather than the …
=> settings: Fix broken label interactions in settings.

web/styles/dark_theme.css, web/styles/recent_view.css, web/templates/recent_view_filters.hbs, web/third/bootstrap/css/bootstrap-btn.css
This PR removes the final vestiges of `bootstrap-btn-default` class from the codebase, by moving the relevant styles from the `bootstrap-btn` and `bootstrap-btn-default` classes to the `button-recent-filters` class.
Fixes: https://github.com/zulip/zulip/pull/32357#discussion_r1842726540
| ![Screenshot 2024-11-20 at 11 59 27 PM](https://github.com/user-attachments/assets/3e4694c6-ba93-4a72-a781-47a78ce5268e) | ![Screenshot 2024-11-21 at 12 01 17 AM](https://github.com/user-attachments/assets/a5673f2b-0666-4ff2-829b-2cbfea5c6675) | 
| ![Screenshot 2024-11-21 at 12 00 27 AM](https://github.com/user-attachments/assets/5b4c7db1-3d64-4e49-865d-bb91db41ca5f) | ![Screenshot 2024-11-21 at 12 01 …
=> recent_view: Remove bootstrap classes from recent view buttons.

web/e2e-tests/settings.test.ts
Since pressing `escape` key closes flatpickr and settings overlay at the same time, we need to wait for the settings to be not visible.
If we don't wait for the settings overlay to close, the next test could think the settings overlay is already open and continue with its tests which can easily become flaky.
=> settings: Wait for settings overlay to close.

tools/screenshots/generate-integration-docs-screenshot
After #32413
See [comment](https://github.com/zulip/zulip/pull/32413#:~:text=We%20could%20do%20this%20round%20as%20part%20of%20%2332414%20too%2C%20after%20the%20bot%20names%20are%20updated.)
<details>
</details>
=> Refine tools/generate-integration-docs-screenshot

templates/zerver/integrations/index.html, web/src/portico/integrations.js, zerver/lib/integrations.py
Apparently `.data("category")` would be come back as a single-element array for some French translations, rather than a string.
We fix this by using `.attr("data-category")` across this file, which is our preferred coding pattern anyway.
=> integrations: Fix jQuery .data mishandling translated category names.

corporate/lib/stripe.py, tools/linter_lib/custom_check.py, zerver/lib/retention.py, zerver/lib/test_classes.py, zerver/tests/test_subs.py, zerver/transaction_tests/test_user_groups.py, zerver/worker/embed_links.py
[CZO Discussion](https://chat.zulip.org/#narrow/channel/3-backend/topic/make.20add_subscription_backend.20atomic/near/1978928)
* First 2 commits are to handle the remaining `transaction.atomic` calls without `durable=True` or `savepoint=False`.
* We can drop the 3rd commit if it's not required. I felt the code should be explicit when using `savepoint=True`.
* The last commit adds a custom lint rule to avoid creating unintended savepoints. 
<details> …
=> custom_check: Add rule to avoid creating savepoints. 

web/styles/right_sidebar.css, web/templates/buddy_list/view_all_subscribers.hbs, web/templates/buddy_list/view_all_users.hbs
Built on top of #32332, merge that first.
As discussed here: https://chat.zulip.org/#narrow/channel/101-design/topic/.22View.20all.22.20links.20in.20right.20sidebar/near/1976275
=> buddy_list: Redesign view user links.

zerver/actions/create_user.py, zerver/tests/test_signup.py
[CZO Discussion](https://chat.zulip.org/#narrow/channel/138-user-questions/topic/Combined.20feed.20length/near/1985957)
We give the new users some messages in their feed.
Earlier, we were including upto 1000 messages which were sent within the last 12 weeks.
For realms with low-traffic it results in very few messages being included in the new user's feed.
This PR removes the 12 week limit. Now, we simply include upto 1000 recent messages.
<details> …
=> add_new_user_history: Remove the RECENT_MESSAGES_TIMEDELTA limit.

web/src/gear_menu.js, web/src/hotkey.js, web/src/navbar_help_menu.ts, web/src/navbar_menus.js, web/src/personal_menu_popover.ts, web/src/sidebar_ui.ts, web/src/views_util.ts, web/styles/zulip.css, web/templates/navbar.hbs
Earlier, keyboard navigation only worked for `gear_menu`, `help_menu` and `personal_menu` in the navbar.
This commit introduces the ability to navigate to userlist-toggle-button and login/sigunup button using keyboard from `gear_menu`
Fixes: zulip#29465.
userlist button:
[Screencast from 21-06-24 03:13:59 AM IST.webm](https://github.com/zulip/zulip/assets/33497322/3538e7ff-d9b0-4383-a09e-d494740d71c9)
Login and signup button:
[Screencast from 21-06-24 03:21:35 AM IST.webm](https://github.com/zulip/zulip/assets/33497322/9077279b-e2e8-42f5-b523-1488a41986bc)
<details> …
=> Add keyboard navigation for userlist-toggle-button.

web/styles/right_sidebar.css
This PR provides a small tweak to the Invite users to organization link, putting its text and icon in the same gridded areas as other rows in the right sidebar.
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/invite.20users.20link.20in.20right.20sidebar.20.20.2332332/near/1986017)
| Before | After, no subheads | After, with subheads | After, with avatars |
| --- | --- | --- | --- |
| ![before-no-subheads](https://github.com/user-attachments/assets/3e6997a4-91f1-4867-b154-db251ee99aab) | ![after-no-subheads](https://github.com/user-attachments/assets/89cb2705-a924-458f-bd17-2150a4787e7f) | ![after-with-subheads](https://github.com/user-attachments/assets/7db52435-d2c4-4176-8c3b-8ecc37e4b74d) | …
=> right_sidebar: Match invite-user grid to others.

help/include/user-groups-intro.md, templates/corporate/comparison_table_integrated.html, templates/corporate/pricing_model.html, web/src/settings_components.ts, web/src/settings_org.ts, web/src/user_group_edit.js, web/styles/subscriptions.css, web/templates/settings/organization_permissions_admin.hbs, web/templates/user_group_settings/user_group_settings_overlay.hbs, web/tests/settings_org.test.cjs, zerver/tests/test_realm.py, zerver/tests/test_user_groups.py, zerver/views/realm.py, zerver/views/user_groups.py
Users on limited plans can continue making changes to their existing groups. 
Group settings screen:
Org permissions screen:
Help center:
Standard plan feature list:
Feature table:
<details>
</details>
=> Restrict create group

zerver/migrations/0576_backfill_imageattachment.py, zerver/migrations/0622_backfill_imageattachment_again.py
These migrations can take a while, so it's worth having a progress indicator.
Fixes #32232.
=> migrations: Add progress indicator for imageattachment backfill.

web/templates/draft.hbs, web/templates/message_avatar.hbs, web/templates/message_edit_history.hbs, web/templates/scheduled_message.hbs, web/templates/single_message.hbs, web/templates/stream_settings/stream_members.hbs
Extracted from #32426, but seems like a clear readability improvement regardless.
=> templates: Avoid confusing Mustache-style conditionals

web/src/compose.js
This first call was added in this commit: 41afdc65265ef49c8c7b09e0c68faaf5d80197b1
At the time of this commit, the second call was already there. When removing this line in this commit, it seems like the earlier reported bug isn't present. So we can remove it, to avoid doing extra work when sending a message.
=> compose: Remove duplicate call to clear_preview_area.

web/src/message_list_view.ts, web/src/narrow_state.ts, web/src/stream_popover.js, web/tests/narrow_state.test.cjs
Fixes #32106
Default to "Move only this message" select option if messge is in search view,
because a search view by its construction doesn't guarantee to show all/later messages in the relevant topic.
So only if the message is in a search view we default to "Move only this message", otherwise the message placment in the topic (e.g first, last) is what determines the default option.
=> Move Message: Default to "Move only this message" in search view.

help/keyboard-shortcuts.md, web/src/message_edit.ts, web/templates/confirm_dialog/confirm_edit_messages.hbs
<details>
<summary>
Help modal (no changes) -- other places are changed to match
</summary>
</details>
<details>
<summary>
Confirmation modal
</summary>
</details>
<details>
<summary>
https://zulip.com/help/keyboard-shortcuts#message-actions
</summary>
</details>
=> help and modals: Describe "edit your last message" consistently.

templates/corporate/billing/billing.html, templates/corporate/billing/legacy_server_login.html, templates/corporate/billing/remote_billing_confirm_email_form.html, templates/corporate/billing/remote_billing_finalize_login_confirmation.html, templates/corporate/billing/remote_billing_server_deactivate.html, templates/corporate/billing/remote_billing_server_deactivated_success.html, templates/corporate/billing/sponsorship.html, templates/corporate/billing/upgrade.html, templates/corporate/support/support_request.html, templates/two_factor/_wizard_forms.html, templates/zerver/login.html, templates/zerver/register.html
The CSS rule for the "no-validation" class was removed in commit 388acbbfcba, but the class was not removed from the templates in those changes. Which then resulted in it being used in more templates as the billing, sponsorship and support templates grew in number and complexity.
---
<details>
</details>
=> templates: Remove "no-validation" class.

web/src/user_group_popover.ts, web/src/user_groups.ts
For a system group, we were showing it's name, e.g. `role:members` when we want to show it's display_name instead i.e `Members` in the user group popover.
Fixes https://chat.zulip.org/#narrow/channel/9-issues/topic/system.20group.20subgroup.20display.20in.20group.20popovers/near/1986632
<details>
</details>
=> user_group: Show display_name instead of name for direct subgroups.

zerver/management/commands/unarchive_channel.py
After #28478 we no longer change the name when deactivating a channel, so this is particularly needed - now there's always a "collision" on new_name.
=> unarchive_channel: Fix logic checking for name collision.

web/src/sidebar_ui.ts, web/styles/right_sidebar.css, web/templates/popovers/buddy_list_popover.hbs
As discussed here: https://chat.zulip.org/#narrow/channel/101-design/topic/buddy.20list.20style.20switcher/near/1984867
Manually tested:
* With and without the "invite users" option present (depends on user permissions)
* Toggling to each of the three options, including keeping it the same
=> buddy_list: Add style-change options to buddy list popover.

web/src/buddy_list.ts
As discussed on CZO here: https://chat.zulip.org/#narrow/channel/9-issues/topic/incorrect.20.22this.20channel.22.20section/near/1988804
=> buddy_list: Fix logic for showing the "channel" section and its "view all subscribers" link

web/templates/settings/admin_user_list.hbs
The deactivation icon was incorrectly showing for both active bots and active users in the admin settings panel. This fix ensures the icon only appears for deactivated entities.
<details>
</details>
=> settings_bots: Fix deactivation icon.

web/styles/app_variables.css
Reported here: https://chat.zulip.org/#narrow/channel/9-issues/topic/right.20sidebar.20headings.20problem/near/1989456
Before:
After:
=> buddy_list: Don't use transparent background for header hover.

web/src/buddy_data.ts
This was introduced in ebe15dcf2577249dd3c8b1f011cb194643167716 where I mistakenly had us include _all_ participants  _always_ even if there was filter text present. This commit fixes that.
=> buddy_list: Fix bug where participants weren't filtered on search.

pnpm-lock.yaml, version.py
It seems 4.1.4 is causing the client to ask the server to delete each upload immediately when it succeeds.
https://chat.zulip.org/#narrow/channel/9-issues/topic/broken.20image.20uploads/near/1989833
Cc @alexmv
=> dependencies: Downgrade @uppy/tus from 4.1.4 to 4.1.3

web/src/message_events.js
Previously, when a message was moved between two topics without sending an automated notice, the ordering of these topics in the left sidebar was not updated.
This is because the updated `max_message_id` of `stream_topic_history` was always computed before the moved message object's channel/topic were updated. This caused the `max_message_id` of `stream_topic_history` which determines the ordering of topics to always be the same.
This is fixed by making sure that the channel/topics of the objects of the messages which were supposed to be moved were updated before we compute this `max_message_id`.
Fixes https://chat.zulip.org/#narrow/channel/9-issues/topic/topic.20order.20after.20moving.20messages/near/1976960
<details> …
=> topics: Fix topic order after moving message without automated notice.

analytics/management/commands/populate_analytics_db.py, analytics/tests/test_counts.py, web/src/settings_components.ts, web/src/stream_create.ts, web/src/stream_data.ts, web/src/stream_edit.ts, web/src/stream_events.ts, web/src/stream_settings_ui.ts, web/src/stream_types.ts, web/templates/stream_settings/stream_settings.hbs, web/tests/stream_data.test.cjs, web/tests/stream_events.test.cjs, zerver/lib/bulk_create.py, zerver/lib/event_schema.py, zerver/lib/import_realm.py, zerver/lib/streams.py, zerver/lib/test_classes.py, zerver/lib/user_groups.py, zerver/tests/test_subs.py, zerver/views/streams.py
A lot of the dict generalisations for backend couldn't be done because of mypy issue no. 5382 (don't want to spam the issue with a link to this PR)
<details>
</details>
=> Stream settings prep

corporate/lib/support.py, templates/corporate/support/push_status_details.html
In our remote support view, we want any data for the end date of a server or realm's push notifications to be an optional `datetime` object vs a timestamp `int`.
---
<details>
</details>
=> support: Use datetime for push notification data in remote support.

web/styles/app_variables.css
This updates @evykassirer's temporary fix from #32514 by referencing the already-defined opaque hover color. There is no visual change here, but it does ensure that future adjustments to the value are reflected in the right sidebar--eliminating the need to fiddle with the temporary fix's one-off color value.
[CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/right.20sidebar.20headings.20problem/near/1989592)
| --- | --- |
| ![buddy-heading-hover-before](https://github.com/user-attachments/assets/9049124d-2b9e-4c02-a4f9-530f64af941f) | ![buddy-heading-hover-after](https://github.com/user-attachments/assets/865d7d24-d908-4cd1-9c7e-68e4348ca5d7) |
<details> …
=> buddy_list: Use opaque hover color for headings.

web/src/activity.ts, web/src/settings_users.ts
This PR addresses issue [#31039](#31039), where the app was not fetching presence data for users who had been idle for an extended period when the "Users" tab in the **Settings > Users** panel was opened. This caused outdated or missing availability data in the "Last active" column. With this update, the app now ensures that presence data is fetched for all users when the tab is opened, allowing for more accurate and up-to-date information to be displayed.
1. **New Data Structure:**
- Introduced a new structure, `user_setting_presence_info`, to store presence information specifically when the "Users" tab is opened in the settings panel. This structure helps track and display presence data for users, even if they have been idle for a long time.
2. **New API Call for Presence Data:**
- …
=> presence_data: Fetch presence data from the server

web/src/user_group_edit.js, web/src/user_groups.ts, web/styles/subscriptions.css, web/templates/confirm_dialog/confirm_join_group_direct_member.hbs, web/templates/user_group_settings/browse_user_groups_list_item.hbs, web/templates/user_group_settings/user_group_settings.hbs, web/tests/user_groups.test.cjs
The second commit just fixes the text always being `leave group` for the group membership button for a group where the user is associated via a subgroup, but it does not add the confirmation dialog when trying to join group, that is done later.
I could not tell if we wanted a loading spinner in the confirm dialog or not, it currently does not have it, lmk if we need it.
Fixes #32484. #32486.
Join group confirmation dialog:
Subgroup tooltip:
For #32486, screenshots would not explain a lot, it would just need manual testing. 
<details> …
=> user_group: Don't open edit panel on remove members.

web/src/markdown.ts, web/tests/markdown.test.cjs, web/third/marked/lib/marked.cjs
Follow up to #31965 
The frontend markdown processor didn't local
echo the syntax properly, resulting in a
rendering glitch when sending them.
<details>
</details>
=> markdown: Add support of new message-link syntax in local echo.

help/user-list.md
The second commit should be merged after the sidebar changes are integrated. No big rush to merge the first commit, if we want to do that at the same time.
Current page: https://zulip.com/help/user-list
=> help: Update user list doc.

web/src/user_group_edit.js, web/src/user_profile.ts, web/styles/popovers.css, web/templates/user_group_list_item.hbs, web/templates/user_profile_modal.hbs
In the User groups tab of the user profile, we add a "Remove" button to the row for each group.
Adding tooltip for disabled buttons is remaining
Fixes: zulip#32487.
<details>
</details>
=> Allow removing user from groups via user profile.

zerver/lib/response.py, zerver/lib/test_classes.py, zerver/middleware.py
Now a failure from `assert_json_success` and friends shows the full server-side traceback from the `JsonableError` that caused the failure, not just the test-side traceback for `AssertionError: 400 != 200 : {message}`.
```pytb
======================================================================
FAIL: test_api (zerver.tests.test_users.ActivateTest)
----------------------------------------------------------------------
File "/srv/zulip/zerver/tests/test_users.py", line 1830, in test_api
self.assert_json_success(result)
File "/srv/zulip/zerver/lib/test_classes.py", line 1233, in assert_json_success
self.assertEqual(result.status_code, 200, json["msg"])
File "/srv/zulip/zerver/lib/test_classes.py", line 296, in assertEqual
super().assertEqual(first, …
```
=> test_classes: Refine assert_json_success output with exception chaining

web/src/compose.js, web/src/compose_actions.ts, web/src/compose_setup.js, web/src/compose_validate.ts, web/src/composebox_typeahead.ts, web/src/message_edit.ts, web/src/message_list_tooltips.ts, web/styles/app_variables.css, web/styles/compose.css, web/templates/compose.hbs, web/templates/message_edit_form.hbs, web/tests/compose.test.cjs, web/tests/compose_actions.test.cjs, web/tests/compose_validate.test.cjs
Adds a message length limit indicator similar to the one in the compose box. The tooltip message for the disabled save button now appears dynamically based on whether the message exceeds the length limit or the editing time has expired.
Fixes #25271.
[CZO thread](https://chat.zulip.org/#narrow/channel/101-design/topic/UI.20redesign.3A.20message.20editing)
If the editing time expires along with the message's length exceeding the max length:
<details> …
=> message_edit: Add message length limit indicator in edit message UI.

zerver/actions/user_groups.py
This PR refactors code to use a loop over `GROUP_PERMISSION_SETTINGS`
for adding setting values to the group objects sent in group creation events.
<details>
</details>
=> user_groups: Refactor code creating group objects for creation events.

zerver/actions/message_edit.py, zerver/lib/email_notifications.py, zerver/lib/soft_deactivation.py, zerver/lib/test_classes.py, zerver/tests/test_link_embed.py, zerver/tests/test_message_notification_emails.py, zerver/tests/test_signup.py, zerver/views/realm_export.py
Fixes parts of #30489 
<details>
</details>
=>  Replace `queue_json_publish` with `queue_event_on_commit` as required.

web/src/settings_components.ts, web/src/settings_org.ts, web/src/stream_events.ts, web/tests/lib/example_settings.cjs, web/tests/stream_events.test.cjs, web/tests/user_groups.test.cjs, zerver/lib/exceptions.py, zerver/models/users.py, zerver/tests/test_events.py, zerver/tests/test_subs.py, zerver/views/streams.py
I've kept the switch case around where possible since it feels more readable than a long list of if conditions.
- First commit fixes the bug mentioned in https://github.com/zulip/zulip/pull/32429#issuecomment-2516045904.
- Second commit loops over stream permission group settings for some files.
- For third commit, I saw an opportunity to loop over user group group settings at one place and just added a commit for that. Those group of settings could have further similar optimisations but i haven't looked into it.
- 4th commit loops over stream permission group settings for stream_events.
- 5th commit loops over stream permission group settings for test_events.
- 6th commit shifts the realm admin check to `can_administer_channel`, not sure if the `stream.realm_id != user_profile.realm_id` …
=> stream: Only realm admins can change default channels.

web/src/settings_config.ts
We've fixed the various issues that made us leave this disabled by default.
=> settings_config: Allow using new user list style in production.

web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/settings.css, web/styles/subscriptions.css
This fixes a bug introduced in f40e1e9ad022d1ad73962cf2613621e9484c9bed We changed the settings overlay container background color in that commit, from hsl(0deg 0% 98%) to #ededed. #ededed is same as hsl(0deg 0% 93%). The latter is the exact same color for stream and group row active background. While we changed the settings overlay background color, we did not change the active row color for stream and group rows.
Fixes https://chat.zulip.org/#narrow/channel/9-issues/topic/Lack.20of.20highlighting.20of.20selected.20group.2E/near/1993630
Screenshots:
| Dark Mode | Light Mode |
| --- | --- |
| Org settings | Org settings |
| <img width="896" alt="Screenshot 2024-12-05 at 11 30 38 PM" src="https://github.com/user-attachments/assets/263ec9b5-eaca-4718-8cc7-7cdb14543139"> | <img width="896" …
=> css: Use --color-active-row-modal for settings overlay active rows.

api_docs/construct-narrow.md, zerver/lib/narrow.py, zerver/tests/test_message_fetch.py
Previously, when the message of the "with" operator can not be accessed by the user, it used to return messages in combined feed or stream feed.
This commit updates it to rather raise a BadNarrowOperator error if the message of "with" operand is not accessible to user, and the narrow terms present can not define a conversation. However, if the narrow terms can define a conversation, then the narrow falls back to that of without the "with" operator.
Fixes: [approach suggested in CZO](https://chat.zulip.org/#narrow/stream/378-api-design/topic/topic.20permalinks/near/1888408) and checkbox 2 of https://github.com/zulip/zulip/pull/30114#issuecomment-2226642678
This would be a really important detail because of how the web app currently handles the updating of narrow based on fetched messages …
=> narrow: Update `with` operator behaviour when message not accessible.

zerver/lib/message_cache.py, zerver/lib/outgoing_webhook.py, zerver/tests/test_message_dict.py, zerver/tests/test_message_fetch.py
An access control parameter should never be optional with a default of open.
- Context: #27944 (cc @sahil839).
=> message_cache: Require can_access_sender for finalize_payload

web/styles/app_variables.css, web/styles/left_sidebar.css, web/styles/right_sidebar.css, web/templates/buddy_list/view_all_subscribers.hbs, web/templates/buddy_list/view_all_users.hbs, web/templates/right_sidebar.hbs
As discussed [here](https://chat.zulip.org/#narrow/channel/101-design/topic/invite.20users.20link.20in.20right.20sidebar.20.20.2332332/near/1986802)
buddy list
hover
create a channel
hover
buddy list popover
=> sidebar links: Followup design updates

zerver/lib/users.py, zerver/models/users.py
Follow-up to [create stream: Faster stream creation](https://github.com/zulip/zulip/pull/31168)
Removes the unnecessary fields from bulk_access_users_by_email and
bulk_access_users_id, while also removing duplication of these lists
of fields.
1. `base_bulk_get_user_queryset`, used when fetching a user other than the acting user.
2. `base_get_user_queryset`, used when fetching the acting user, prefetching more fields.
There remains some inconsistency in the models.py functions that may
merit further investigation.
=> subscription: Remove unnecessary select_related fields and clean up.

docs/subsystems/queuing.md, zerver/actions/user_activity.py, zerver/decorator.py, zerver/lib/digest.py, zerver/lib/email_mirror.py, zerver/lib/queue.py, zerver/management/commands/enqueue_file.py, zerver/migrations/0209_user_profile_no_empty_password.py, zerver/migrations/0387_reupload_realmemoji_again.py, zerver/signals.py, zerver/tests/test_email_mirror.py, zerver/tests/test_event_queue.py, zerver/tests/test_link_embed.py, zerver/tests/test_message_delete.py, zerver/tests/test_message_edit_notifications.py, zerver/tests/test_queue.py, zerver/tests/test_queue_worker.py, zerver/tests/test_reactions.py, zerver/tests/test_realm_export.py, zerver/tests/test_submessage.py, zerver/tornado/django_api.py, zerver/tornado/event_queue.py, zerver/worker/deferred_work.py, zilencer/management/commands/queue_rate.py
PR to rename the `queue_json_publish` function to `queue_json_publish_rollback_unsafe`.
Fixes part of #30489.
[CZO Discussion
](https://chat.zulip.org/#narrow/channel/3-backend/topic/make.20add_subscription_backend.20atomic/near/1992756)
**Screenshots and screen captures: N/A**
<details>
</details>
=> queue: Rename queue_json_publish to queue_json_publish_rollback_unsafe.

zerver/actions/message_send.py
This PR fixes the code to add a check for whether the setting is set to an anonymous group
or not before checking if the setting is set to "Nobody" group by checking the group name.
<details>
</details>
=> message_send: Fix checking permission to send DMs.

help/include/add-users-to-a-group.md, help/include/depends-on-permissions.md, help/include/remove-from-a-group.md, help/include/sidebar_index.md, help/manage-user-channel-subscriptions.md, help/manage-user-group-membership.md, help/manage-user-groups.md, zerver/lib/markdown/tabbed_sections.py
Styling in the screenshots being messed up should be unrelated, and was reported separately.
Current: https://zulip.com/help/manage-user-channel-subscriptions#subscribe-a-user-to-a-channel
<details>
<summary>
Updated
</summary>
</details>
<details>
<summary>
New page
</summary>
</details>
<details>
<summary>
Left sidebar
</summary>
</details>
=> help: Add a page on managing a user's group membership.

web/src/compose_reply.ts, web/tests/compose_ui.test.cjs
This PR makes forwarded messages keep their original topic in the topic field, as proposed in [CZO](https://chat.zulip.org/#narrow/channel/101-design/topic/Explaining.20quote-and-reply/near/1993494)
Fixes: https://chat.zulip.org/#narrow/channel/101-design/topic/Explaining.20quote-and-reply/near/1993494 
<details>
</details>
=> message_forwarding: Make forward message keep original topic by default.

web/src/popover_menus_data.ts, web/src/topic_popover.ts, web/templates/popovers/left_sidebar/left_sidebar_topic_actions_popover.hbs
This PR changes the behavior of the topic actions popover (displayed from the left sidebar via the `...` menu) to no longer appear for empty topics (topics with no messages).
Instead, in place of the popover a message is displayed: "There are no messages in this topic.", along with the name of the topic (styled like the deactivated user line).
Fixes: #32098.
[CZO thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/Error.20moving.20topic.20with.20no.20messages/near/1966728)
**Before Changes**
<details>
<summary>GIF</summary>
</details>
<details>
<summary>Image</summary>
</details>
**After Changes**
<details>
<summary>GIF</summary>
</details>
<details>
<summary>Image</summary>
</details>
**Please note that the left sidebar actions popover for …
=> popovers: Hide left sidebar actions popover for empty topics.

zerver/data_import/slack_message_conversion.py
This is a prep PR for making the Slack text reformatters in `slack_message_conversion.py` to be compatible with `render_attachments` & `render_blocks` (#32164), it refactors the `slack_message_conversion.py` file. Changes include:
- Rearranging helper functions to appear before the main functions that use them.
- Create `convert_slack_workspace_mentions` helper function.
- Create `convert_slack_formatting` helper function.
<details>
</details>
=> slack-import: Reorder and extract additional helper functions in `slack_message_conversion`

docs/development/setup-recommended.md
This moves a confusing message about other Linuxes into its own tab, and clarifies a bit of ambiguous language in the message, too.
| --- | --- |
| ![other-linux-before](https://github.com/user-attachments/assets/a3b68e36-ee02-4aff-843a-117d1ba0bf45) | ![other-linux-after](https://github.com/user-attachments/assets/cdfefa1a-ce3e-4f1a-86b6-c47578efab02) |
=> dev_docs: Establish Other Linux tab.

web/styles/portico/portico.css
| --- | --- |
| ![image](https://github.com/user-attachments/assets/d067badf-31aa-4ac0-93e6-762dc6de5963) | ![Screenshot from 2024-11-26 09-52-53](https://github.com/user-attachments/assets/b594d7f2-e0c5-4dc4-a143-ed644d3beaa2) |
discussion: https://github.com/zulip/zulip/pull/31799#issuecomment-2499174669
=> portico: Remove text centering on thanks page.

web/src/tippyjs.ts
Hiding on popovers on hovering over emoji name is not required since this just a tooltip and not a popover.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/user.20mention.20typeahead.20closing.20unexpectedly
=> tippyjs: Fix user typeahead hidden when hovering over emoji name.

web/src/settings_profile_fields.ts, web/templates/settings/profile_field_choice.hbs
This pull request includes changes to the `settings_profile_fields.ts` and `profile_field_choice.hbs` files to improve the user interface for managing profile field choices. The most important changes include displaying move handles for all existing choice rows and conditionally hiding move handles for new empty choice rows.
Improvements to user interface for managing profile field choices:
* [`web/src/settings_profile_fields.ts`](diffhunk://#diff-cc690fe2bdfd038f1288155c79b26151351fb9472e7b5377fc7da8d872cfe771R301): Added code to display move handles for all existing choice rows when creating a new row.
* [`web/templates/settings/profile_field_choice.hbs`](diffhunk://#diff-0751f27f4e5530cf74ab170afee0ea136792fc5ff8ac4cfa932809f51bac4e15L2-R2): Modified the template to conditionally hide …
=> settings: Disable the move-handle for new-choice-row.

web/src/message_edit.ts
This was passing typechecking previously because of an incorrect assertion and `NaN` getting into `validate_stream_message_mentions`.
=> message_edit: Don't validate stream message mentions for DMs.

tools/test-js-with-node, web/src/compose.js, web/src/drafts.ts, web/src/message_events.js, web/src/message_events.ts, web/src/message_list.ts, web/src/message_store.ts, web/src/message_util.ts, web/src/message_view.ts, web/src/server_events.js, web/src/server_events_dispatch.js, web/src/unread.ts
There are a handful of things I made assumptions about that I need to check, one of which is related to a failing test, but opening this as a draft for now in case anyone wants to take a first pass review on it.
=> message_events: Convert module to typescript.

web/src/compose_send_menu_popover.js
Reported here: https://chat.zulip.org/#narrow/channel/9-issues/topic/Msg.20preview.20prevents.20saving.20draft.20.26.20start.20new.20action
=> compose: Clear preview area when starting a new draft.

web/styles/left_sidebar.css, web/templates/subscribe_to_more_streams.hbs
This PR improves the horizontal layout and vertical alignment of the Browse More Channels row. It fixes a subtle font-size bug that was making the icon too large, and blowing open the row's line-height to larger than the other prominent sidebar rows.
It also uses existing variables used on other left-sidebar rows for icon placement and gaps.
[
CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/invite.20users.20link.20in.20right.20sidebar.20.20.2332332/near/1995066)
_Grid shown in second set to illustrate the less immediately perceptible changes._
| --- | --- |
| ![browse-more-before](https://github.com/user-attachments/assets/e4574236-2196-4574-a45d-6eb64c1fa9a3) | …
=> left_sidebar: Adjust and improve alignment on Browse More Channels row.

web/src/group_setting_pill.ts, web/src/input_pill.ts, web/src/settings_components.ts, web/src/stream_create.ts, web/src/user_group_create.ts, web/styles/app_variables.css, web/styles/compose.css, web/styles/dark_theme.css, web/styles/input_pill.css, web/tests/input_pill.test.cjs
Fixes: #32113
One thing that was not mentioned in the original issue was how we want to handle not allowing the user to go the next step for invalid group setting values. Right now, for stream and group settings, if the name is invalid, we show an error text just below the field. Since our way of showing errors with the pill input box on enter is a red outline box and shaking animation, I've also used that to indicate an error without any additional text to accompany it. Let me know if we want to change that and if yes, where we want to show that text. 
There was no additional work needed for the `shake` animation, that was working already.
I've not used [:user-invalid pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid) here since it seems to be more suited for …
=> Group invalid inputs

web/src/presence.ts, web/tests/presence.test.cjs
When going offline, the "time since active" is based on when you were last active or idle. This means that if you have been idle for hours, and then go offline, the popover in the right sidebar will state that you were "Active x minutes ago". This is misleading since much more time actually has passed since you last were active. Changing the code to always return the `active_timestamp` when offline fixes this issue. Now the popover will display the amount of time that has passed since the user was actually last active. 
I have manually measured the time between being active and going offline to confirm that the solution is working. 
Linked discussion in CZO thread: [CZO thread](https://chat.zulip.org/#narrow/channel/101-design/topic/.2332271.20Misleading.20time.20description.20in.20right.2 …
=> popover: Fix misleading time description in right side-bar.

web/src/message_util.ts, web/src/stream_popover.ts, web/styles/popovers.css, web/styles/zulip.css, web/templates/move_topic_to_stream.hbs
This PR adds a message count display in the **Move topic** and **Move messages** modals, showing the number of messages that will be affected by the move action. The information is displayed below the stream/topic or selection specification, depending on the context of the modal.
**Tasks completed**
<table>
<thead>
<tr>
<th> After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th> After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<details>
<summary> Check for N = 1 and N > 1 </summary>
<table>
<thead>
<tr>
<th>For N = 1</th>
<th>For N > 1</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr> …
=> ui_update: Show the number of messages to be moved.

package.json, patches/textarea-caret@3.1.0.patch, pnpm-lock.yaml
Forced reflows are reduced after this change but I couldn't find any concrete difference in the time taken to compute this value on multiple samples with and without this patch even after 6x CPU slowdown.
Note that `getCaretCoordinates` is called in a loop by tippy to get the best `placement` for the typeahead which doesn't look like can be avoided.
| --- | --- |
| ![Screenshot from 2024-12-11 13-43-44](https://github.com/user-attachments/assets/7387ab79-6475-43d4-94ab-513b1f3c32a8) | ![Screenshot from 2024-12-11 13-37-06](https://github.com/user-attachments/assets/b22cb23f-40f6-4110-9013-465d674a98cc) |
=> textarea-caret: Reduce forced layout reflows.

web/src/conversation_participants.ts, web/src/message_list_data.ts, web/tests/compose_closed_ui.test.cjs, web/tests/conversation_participants.test.cjs, web/tests/message_list.test.cjs, web/tests/message_list_data.test.cjs, web/tests/message_list_view.test.cjs, web/tests/narrow_local.test.cjs, web/tests/stream_topic_history.test.cjs
This will help us accurately track participants in every narrow to be used buddy list and other components.
https://chat.zulip.org/#narrow/channel/9-issues/topic/build_user_sidebar.20called.203x.20when.20changing.20view/near/1981270
=> conversation_participants: Track participants data in with message data.

web/styles/zulip.css
20px before:
20px after:
12px before:
12px after:
=> show more/less: Use em for height of button.

web/styles/compose.css
20px before:
20px after:
12px before:
12px after:
=> compose: Size stream message arrow icon with em.

web/styles/settings.css
**20px before this PR**
----
**with this PR**
12px:
14px:
18px:
20px:
=> settings: Fix emoji and buddy list style selectors for bigger fonts.

corporate/lib/stripe.py, corporate/models.py, corporate/tests/test_stripe.py, templates/corporate/billing/billing.html, templates/corporate/billing/sponsorship.html
Updates the sponsorship and billing pages for current text for temporary complimentary access plans.
**Notes**:
- Fixes "discounted" not being shown when a request for a discounted Zulip Basic plan was submitted.
- Refactors some of the logic for the sponsorship page context:
- Early return if a sponsorship request is submitted/pending and the customer is on a paid plan.
- Removes free trial boolean from sponsorship as being on a free trial implies being on a paid plan, and therefore the early return noted above.
- Renames helper function for clarity on what it adds to the sponsorship page context.
- Revises old "legacy plan" language for current "complimentary access" language.
- Some of the changes here are also preps for implementing a version of the complimentary access plan for Zulip …
=> billing: Fix legacy plan strings in billing and sponsorship pages.

web/src/stream_popover.ts, web/styles/popovers.css, web/templates/move_topic_to_stream.hbs
This PR refactors the move messages and move topic modals to follow standard patterns from other modals (e.g. the invite user modal). It includes the following changes:
- Refactored the intro text for the move messages and move topic modals.
- New Labels are introduced in the move messages and move topic modals:
- New channel
- New topic
- Which messages should be moved? <- in the move messages modal
(no changes to checkboxes)
- Some CSS adjustments as mentioned in the [CZO thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/topic.20box.20too.20short.20in.20.22move.20messages.22/near/1962636).
Fixes: #32168.
[CZO thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/topic.20box.20too.20short.20in.20.22move.20messages.22/near/1962636) …
=> popovers: Restructure the Move messages and Move topic modals.

web/src/portico/signup.ts
This pull request builds on PR #29434 and addresses the comments and feedback raised in that review. Below is a summary of the primary differences and enhancements introduced in this PR:
1. **File Change Optimization**:
- In the previous PR, changes were included in `web/src/settings_account.js`, which were not essential to the intended functionality. 
2. **Minimum Length Validation Logic**:
- Previously, the minimum length error would display immediately as the user began typing in the password field, which could be intrusive for users.
- In this PR, I have introduced a new flag that tracks the initial `focusout` event on the password field. With this approach, the minimum length error is only shown after the user first blurs (focuses out of) the input field. After this initial focus …
=> Added debouncing to password input field to avoid lag.

docs/production/authentication-methods.md, help/configure-authentication-methods.md, help/saml-authentication.md, templates/corporate/security.md, zerver/lib/markdown/tabbed_sections.py
Microsoft has been renaming AzureAD to Entra ID. Though both names still seem to function, even if unofficially, so this mostly renames to `Entra ID (AzureAD)` to reference both for clarity.
=> docs: Finish renaming AzureAD to Entra ID.

web/styles/compose.css
The changes aren't super visible below 20px, but it seems good to scale it regardless.
---
18px before and after
=> compose: Use em for enter send setting font size.

api_docs/changelog.md, tools/check-schemas, version.py, web/tests/lib/events.cjs, zerver/actions/reactions.py, zerver/lib/event_schema.py, zerver/lib/message_cache.py, zerver/models/messages.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_dict.py, zerver/tests/test_reactions.py
Removes deprecated `user` object from reactions objects returned by the API as it is redundant because of the presence of `user_id` field in the API and is not used by any clients now.
<details>
</details>
=> api: Remove `user` object from reactions objects in the API.

web/styles/portico/footer.css
Change alignment of footer rows to flex-start a bit earlier. `1280px` is chosen since that's the standard `max-width` for the screens on the page and that is width around which the massive gap before the first item on the footer is diminished which allows us to left align the elements.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/48acdffe-3353-485f-a992-421479ee04be) | ![image](https://github.com/user-attachments/assets/4ff8ad03-39cb-47fe-a260-6ce6245786b8) |
=> footer: Fix footer items mis-aligned in Russian.

web/styles/app_variables.css
This PR includes color adjustments suggested by @terpimost.
[CZO discussion](https://chat.zulip.org/#narrow/stream/137-feedback/topic/design.20feedback/near/1950672)
| --- | --- |
| ![dark-mode-message-area-before](https://github.com/user-attachments/assets/146eda5a-48b9-4486-9fa1-cd8b12eee492) | ![dark-mode-message-area-after](https://github.com/user-attachments/assets/f3470600-2d72-44b6-b94c-2b9cf3254854) |
<details> …
=> dark_theme: Adjust message colors for higher contrast.

docs/production/authentication-methods.md, help/configure-authentication-methods.md, help/saml-authentication.md, templates/corporate/comparison_table_integrated.html, templates/corporate/pricing_model.html, zerver/openapi/zulip.yaml, zproject/prod_settings_template.py
This is a follow-up to #32693, which missed a bunch of places due to varying ways of typing Azure AD. (Azure AD, Azure Active Directory etc.)
In the diff there's an apparent inconsistency with renaming, in some places renaming to just "Microsoft Entra ID" and in others "Microsoft Entra ID (AzureAD)".
The idea is to add (AzureAD) in ordinary documentation, as it can help clarity since many people still think of this as AzureAD, while sticking with brevity and cleanliness of just using the official name in marketing focused material.
---------------
The most important place to consider renaming is the:
1. in Organization settings -> Authentication methods we still show `AzureAD`
2. If enabled, on the login page the 'Login with AzureAD' button. The logo it uses is also outdated I think:
So …
=> docs: Renaming AzureAD to Entra ID, part two.

web/src/compose_actions.ts, web/src/compose_closed_ui.ts, web/src/compose_tooltips.ts, web/src/stream_data.ts, web/templates/tooltip_templates.hbs, web/tests/compose_actions.test.cjs
This pull request includes several changes to improve the handling of stream permissions in the compose actions and UI components. The main changes ensure that users can only post messages in streams they have permission to, and provide appropriate feedback when they cannot.
* **Compose Actions**: Added checks to ensure users can only post messages in streams they have permission to. If not, the stream ID and topic are reset, and the stream selection dropdown is opened. (`web/src/compose_actions.ts`)
* **Compose Closed UI**: Introduced functions to determine if the reply button should be disabled based on stream permissions, and updated button states and labels accordingly. (`web/src/compose_closed_ui.ts`)
* **Compose Tooltips**: Added a new tooltip template for disabled stream reply …
=> Disable compose reply button if posting is not allowed in a stream.

web/src/condense.ts, web/src/message_viewport.ts
Fixes #31501
Collapse all unread messages that are over min(150 em, 2*viewport_height). Collapse all bot messages and human messages marked as read that are over max(35 em, 0.65*viewport_height).
=> condense: Modify height offset to collapse messages.

web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/recent_view.css
This PR refactor all the theme colors used in `recent_view.css` and `dark_theme.css`.
Note:
- Screenshots in before column are taken from main branch.
| `.recent_view_participant_overflow`  | `.recent_view_participant_overflow`  |
| ![{45E8352E-2A18-4A55-8359-356CBD77F87D}](https://github.com/user-attachments/assets/fc63cb58-d712-416d-bd5f-dbc6033ec49a)  | ![{E5CBC687-4FEA-4FE4-9690-040C64B94D5E}](https://github.com/user-attachments/assets/ffd4c3dc-3271-4216-adc4-933e5cb1f4b6)  |
| ![{50E96CFB-40DA-4461-916E-AB9F2D98D396}](https://github.com/user-attachments/assets/93680ffe-38d9-4ddc-a0d8-0511ef9d9aac)  | ![{B71B100A-7A1E-4BE7-8AA7-6BFD86272E3D}](https://github.com/user-attachments/assets/64d32868-9f …
=> Refactor theme colors for `recent_view`.

web/styles/recent_view.css
We don't set a background color for transparent avatars to avoid changing what the avatar is supposed to be.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/transparent.20background.20profile.20picture.20reappears
| --- | --- |
| ![image](https://github.com/user-attachments/assets/38b36798-2e90-4b9a-a51c-08e562ed1ee1) | ![Screenshot from 2024-12-13 14-10-20](https://github.com/user-attachments/assets/e6c314eb-37fa-4cc5-ab6a-a464bf86ed21) |
=> recent_view: Fix transparent avatar background color being changed.

corporate/lib/stripe.py
Now we allow visiting `/customer_portal` with not parameters passed if the user is a billing admin.
=> Fix error on visiting `/customer_portal` with no parameters.

web/src/recent_view_ui.ts, web/styles/app_components.css, web/styles/inbox.css, web/styles/recent_view.css, web/templates/recent_view_row.hbs, web/templates/user_with_status_icon.hbs, web/tests/recent_view.test.cjs
This PR runs usernames + status emoji as inline elements in the DM portions of Inbox and Recent views, employing CSS Grid to better allow ellipses to appear in the usernames in narrow views, much like is already done in the right sidebar. 
This has also been updated to suppress status emoji for group DMs in the Inbox and Recent conversations views, keeping those in line with a similar status-emoji-suppressed design that has long been part of the left sidebar's treatment of group DMs.
With those design improvements in hand, it also extends the use of `Intl.ListFormat` to DM groups in Recent conversations.
Fixes: #29778
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20status.20emoji.20line.20wrapping/near/1783055)
As the screenshots below illustrate, this …
=> usernames: Run usernames and status emoji as inline elements.

web/styles/app_variables.css, web/styles/compose.css, web/styles/dark_theme.css, web/templates/compose_control_buttons.hbs, web/templates/popovers/compose_control_buttons/compose_control_buttons_in_popover.hbs, web/templates/popovers/compose_control_buttons/compose_control_buttons_in_popover_2.hbs
This PR achieves two primary things, both in preparation for scrolling formatting buttons (#31215):
1. Buttons are now accurately sized to the height available in the grid (2em, or 28px at 14px/1em). Despite a `height` value on the icons, the larger line-height spilled out beneath the icon box's and grid area's bottom edges, creating problems for centering in relation to those icons, and a vertical overscroll (the overscroll behavior is not visible in this PR or in `main`).
2. Dividers between groups of formatting buttons are now drawn using CSS (previously, dividers were a difficult-to-center pipe character, `|`). That means both better control over the look of the dividers and, as is evident in the screenshots below, dividers that are properly centered for the first time (and that more …
=> compose: Correct and improve button dimensions.

corporate/urls.py, templates/corporate/case-studies/rush-stack-case-study.html, templates/corporate/case-studies/rush-stack-case-study.md, templates/corporate/for/communities.html, templates/corporate/for/open-source.html, templates/corporate/for/use-cases.md, templates/zerver/landing_nav.html, zerver/tests/test_docs.py
<details>
<summary>
Selected screenshots
</summary>
</details>
Notes:
- The /for/communities and /for/open-source hero areas don't look perfect on narrow screens, but I think using the two `&nbsp;` is better than not doing so.
=> portico: Add Rush Stack case study.

help/view-and-edit-your-message-drafts.md, web/src/drafts.ts, web/src/drafts_overlay_ui.ts, web/styles/drafts.css, web/templates/draft_table_body.hbs, web/tests/drafts.test.cjs
This commit eliminates the 30-day automatic removal feature for saved drafts, allowing users to retain drafts indefinitely until they choose to delete them manually. The following changes are included:
- **Code Adjustments**: Removed the `DRAFT_LIFETIME` constant and associated logic that calculated and deleted drafts older than 30 days. This prevents the auto-discard mechanism, ensuring drafts are retained without expiration.
- **Documentation Updates**:
- Updated the drafts modal to remove the line informing users that drafts older than 30 days are automatically removed.
- Modified `/help/view-and-edit-your-message-drafts` to remove mentions of the 30-day retention limit, ensuring documentation accurately reflects the indefinite storage of drafts.
- Checked other related documentation …
=> drafts: Remove feature for discarding drafts after 30 days.

web/webpack.dev-assets.json
This includes bootstrap.portico.css and happens to prevent webpack from kicking it out of the chunk with the rest of the portico CSS and misordering it.
=> dev-buttons: Use portico bundle

web/src/add_group_members_pill.ts, web/src/add_subscribers_pill.ts, web/src/stream_create.ts, web/src/stream_create_subscribers.ts, web/src/user_group_create.ts, web/src/user_group_create_members.ts
Show red outline on invalid subscribers/members input pill and disable create/add button wherever applicable. For the disabling button part, manual testing would be better, attached screenshots for the red outline:
Create channel add subscribers screen:
Edit channel add subscribers screen:
Create group members screen:
Edit group members screen:
<details>
</details>
=> Show red outline on invalid subscribers/members input pill

templates/zerver/realm_redirect.html, tools/lib/capitalization.py, web/styles/portico/portico_signin.css, zerver/tests/test_signup.py
I have made some UI changes as mentioned in [#32198](https://github.com/zulip/zulip/issues/32198):
1. Left aligned the label to make it consistent.
2. Changed the text: 'Enter your organization's Zulip URL' -> 'Organization URL'
3. Moved 'Don't know your organization URL? Find your organization.' to be just below the URL field.
4. Changed the placeholder 'your-organization-url' -> 'your-organization'
Fixes: [#32198](https://github.com/zulip/zulip/issues/32198) 
<details>
<summary>Earlier</summary>
</details>
<details> …
=> portico: Improve layout of the /go page

web/src/compose_banner.ts, web/src/compose_validate.ts
When a user doesn't have post permissions, hide warning banners as they are irrelevant.
**Banners affected:**
`warn_if_private_stream_is_linked`
`warn_if_mentioning_unsubscribed_user`
`warn_if_topic_resolved`
Fixes https://github.com/zulip/zulip/issues/25575.
**Previous PR:**
There is a previous PR #25653 opened for the same issue having `integration review` tag and now has `merge conflicts` due to `js` files being changed to `ts`. Also, the previous made changes to various section of codebase which I dont think are necessary. So, I just utilised some lines of his code and left the other untouched.
<details>
<summary>No post permissions, replying to a resolved topic.</summary>
</details>
<details>
<summary>Has post permissions, replying to a resolved …
=> compose: Hide warning banners when post permissions banner visible.

web/styles/subscriptions.css, web/templates/stream_settings/stream_privacy_icon.hbs
This also corrects some stray closing quotation marks that were improperly outside of an if-statement in the privacy-icon template.
[CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/channel.20privacy.20icon.20misaligned.20.28channel.20settings.29/near/2007667)
| --- | --- |
| ![public-before](https://github.com/user-attachments/assets/a39d239b-fe02-402e-8653-8d253949e899) | ![public-after](https://github.com/user-attachments/assets/d1d7d7d0-4093-404b-bbd8-472e4c08b8f2) |
| ![private-before](https://github.com/user-attachments/assets/aef2c378-c6e2-4346-8633-bbcbe7cf8d57) | ![private-after](https://github.com/user-attachments/assets/f32bee93-ae58-4684-9ebb-7b2883edf22c) |
| …
=> settings: Correct icon alignment in channel settings.

zerver/data_import/slack.py, zerver/tests/test_slack_importer.py, zerver/webhooks/slack/doc.md, zerver/webhooks/slack/tests.py, zerver/webhooks/slack/view.py
This PR:
- Fixes a typo in the Slack webhook doc.
- Make `check_token_access` accept a `required_scopes` parameter.
- Refactors the `check_token_access` in Slack webhook integration to be called only when handling Slack handshake (when first registering webhook endpoint) and have it send DM to the owner if there are any problems.
- Clean up duplicate functions now that we've refactored part of `slack_message_conversion.py`. (only `replace_links` left)
Fixes part of #30827
> Improve token checking to do fewer callbacks: https://github.com/zulip/zulip/pull/30465#discussion_r1880969823.
>  Remove Duplicative Code. To convert Slack text to Zulip markdown, a function in slack_message_conversion.py called convert_to_zulip_markdown is copied and adapted to be used in the Slack integration (under …
=> integrations: Clean up Slack integration.

web/src/tippyjs.ts, web/styles/app_variables.css, web/styles/popovers.css, web/templates/popovers/user_group_info_popover.hbs
Previously, due the uneven width between the icons and the user presence indicator, the icons and presence indicator were misaligned with each other.
This PR uses the grid and subgrid layout systems to fix this misalignment issue.
> [!NOTE]  
> Also contains a follow-up commit fixing the extra gap when the group description is absent.
Fixes: [CZO Discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/bots.20misaligned.20in.20group.20modal/near/1962348)
| ![Screenshot 2024-11-12 at 7 17 31 PM](https://github.com/user-attachments/assets/a88a6e5f-2d2d-41c4-9b2f-c871af588b5a) | ![Screenshot 2024-11-12 at 8 01 41 PM](https://github.com/user-attachments/assets/5ca335b5-6a33-4b04-832c-99fdde91bd4f) | …
=> user_group_popover: Fix misaligned icons in user group member list.

help/include/automatically-follow-topics.md, web/src/settings_config.ts, web/templates/settings/notification_settings.hbs
This PR improves the presentation of auto-follow topics section in Notification Settings.
Fixes: #32761 
From
To
Modify [documetation](https://zulip.com/help/follow-a-topic)
<details>
</details>
=> Improve presentation of auto-follow topics settings page

web/styles/modal.css, web/styles/popovers.css
This PR is a follow-up to #32760, and includes commits that were destined for that PR, but were left out owing to end-of-day sloppiness.
Specifically, this PR:
1. Introduces a grid-based heading layout in the Move/Rename modals that allows for multiline headings.
2. Introduces an italic, lowered-opacity styling on the indicator for how many messages are to be moved in the Move/Rename modals, and parallel lines on invitation and realm-deactivation modals.
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/move.20topic.20.2F.20message.20menu.20design/near/2009259)
| --- | --- |
| ![move-modal-before](https://github.com/user-attachments/assets/3f296e21-4fc1-4091-a9fb-151d1e5ff262) | …
=> modals: Help heading, timestamp follow-ups.

docs/subsystems/markdown.md, docs/subsystems/sending-messages.md
This PR updates the "Sending messages" and "Markdown implementation" documentation in the `sending-messages.md` and `markdown.md` files respectively to reflect the variable and function updates, ensuring consistency with changes in the codebase over time.
[CZO Thread](https://chat.zulip.org/#narrow/channel/19-documentation/topic/Sending.20Messages.20documentation)
[Sending messages documentation](https://zulip.readthedocs.io/en/latest/subsystems/sending-messages.html)
[Markdown implementation documentation](https://zulip.readthedocs.io/en/latest/subsystems/markdown.html)
The changes are as follows:
- Changes in `sending-messages.md`:
- Rename `local_message.next_local_id` to `local_message.get_next_id_float` - see commit [`2ddd3d0`](https://github.com/zulip/zulip/commit/2ddd3d046a203cffa41 …
=> docs: Update `sending-messages.md` and `markdown.md` for variable/function updates.

web/src/invite.ts, web/src/util.ts, web/tests/util.test.cjs
Updates the invite modal so that if the custom input is 0, the submit button is deactivated, since an email invitation or invite link that immediately expired would be unusable.
Also, updates the custom input to show 0 if a user navigates away from and back to the custom input option afer putting in an invalid value, e.g. "abc" or "-20". Previously, the custom input showed "NaN" in that case.
---
<details>
<summary>Before - custom input set to zero</summary>
</details>
<details>
<summary>Before - custom input invalid</summary>
</details>
<details>
<summary>After - for both of the above cases</summary>
</details>
---
<details> …
=> invite-modal: Fix invalid custom input to not show "NaN".

web/src/user_group_edit.ts
This commit fixes the currently broken feature of being able to change the group info using the edit icon that triggers the dialog_widget to let users edit their group description.
A new function `get_user_group_for_save` is introduced that picks out the save button from the DOM and the corresponding id for the group.
Fixes: #32767.
<details>
<summary>Videos containing Before and After</summary>
Before:
https://github.com/user-attachments/assets/5f26c5c7-1d7d-4193-a7f9-e53a5ac4e3dd
After:
https://github.com/user-attachments/assets/65d716e5-1981-4b2f-835c-9d02880104e8
</details>
<details> …
=> user_group: Fix broken edit description functionality.

web/src/server_events_dispatch.js, web/src/settings_exports.ts, web/templates/modal_banner/allow_private_data_export_banner.hbs, web/templates/start_export_modal.hbs, web/tests/dispatch.test.cjs, web/tests/lib/events.cjs
[CZO Discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/Add.20export.20consent.20privacy.20setting.20.2331201/near/2000411)
This PR introduces a banner on the "Start Export" modal to notify the admin that their personal setting to export private data is not toggled ON.
<details>
</details>
=> export: Add banner if admin's private data export setting is disabled.

web/src/markdown.ts, zerver/lib/markdown/__init__.py, zerver/tests/fixtures/markdown_test_cases.json
This also matches the except in the block above.
=> markdown: Catch OverflowErrors in global times.

zerver/actions/message_send.py, zerver/tests/test_message_send.py
We updated the stream property but forgot to inform the client.
Tested by marking a stream inactive in db shell and then checking if sending a message live updated it to become active.
=> message_send: Fix stream still inactive after sending message.

tools/setup/build_pygments_data
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/Code.20block.20for.20.F0.9F.94.A5.28Mojo.29.20doesn't.20work/near/2024596
| Before                                                                                                     | After                                                                                                      |
|------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------|
| ![Before Image](https://github.com/user-attachments/assets/5401aafc-2020-43ba-9a00-cd42387cfeac)          | ![After Image](https://github.com/user-attachments/assets/3f2a1fbd-0730-4030-9 …
=> code_block: Exclude 🔥 emoji alias for mojo.

web/styles/widgets.css
This pull request addresses the issue described in **#32829** where the focus outline for the tick (✅) button is partially cut off while editing the title of a poll or to-do list. The problem occurs when the user clicks on the ✏️ edit icon to modify the title, and the focus outline around the checkmark button is clipped on the right side, making it difficult to see the focus state.
Fixes: #32829
The issue was fixed by adding a `margin-right: 2px;` to the `.poll-question-bar` class. This small adjustment ensures that the focus outline around the checkmark button is fully visible and no longer clipped, enhancing the accessibility and visual clarity of the UI.
1. Create a poll or a to-do list using the `/poll` or `/todo` command, or via the UI buttons.
2. Click on the ✏️ icon near the title …
=> Fix: focus outline cutoff issue in poll title editing

web/src/compose.js, web/src/message_edit.ts, web/src/resize.ts
This was preventing images form showing up properly, since they're only a short line of text but tallin the preview.
CZO thread:
https://chat.zulip.org/#narrow/channel/9-issues/topic/compose.20preview.20image.20bugs
=> compose: Don't calculate preview height preemptively.

web/src/message_lists.ts, web/styles/message_header.css, web/styles/zulip.css
This PR completes the work in the PR: #27265 which was authored by @ecxtacy .
- **Recipient Bars Hover Behavior**: Action buttons are displayed on recipient bars when hovered over, except for the sticky recipient bar, which always displays the action buttons.
- **CSS Visibility Control**: The CSS rule `opacity: 0;` is toggled to `opacity: 1;` on hover. For sticky bars, `opacity: 1;` is applied by default to keep the action buttons visible.
- **Persistent Action Buttons with Active UI Elements**: To prevent the action buttons from disappearing when other UI elements (e.g., notification menu, topic editing UI) are active, the `:focus-within` CSS pseudo-class is used on `recipient_bar`, ensuring the buttons remain visible.
- **Conversation View Consistency**: In conversation views where a …
=> Show non-sticky recipient bar action buttons on hover. 

web/styles/right_sidebar.css, web/templates/buddy_list/section_header.hbs
Discussed here:
https://chat.zulip.org/#narrow/channel/101-design/topic/right.20sidebar.20heading.20dot/near/2013034
=> buddy_list: Use 0.75 opacity for the user counts.

web/src/compose.js, web/src/message_edit.ts
Changes in #32695 wrongly assumed the preview box can only expand from the composebox, but for some situations like links it can also have a preview block that is less high than the raw text.
Reported on CZO:
https://chat.zulip.org/#narrow/channel/9-issues/topic/Preview.20breaks.20when.20the.20compose.20box.20is.20expanded.20by.20itself.2E/near/2029447
=> compose: Set a min-height before showing preview area.

web/src/user_profile.ts
When editing a user or bot profile via the Manage User or Manage Bot overlay, an error was not hidden after receiving a successful response from the server. This PR ensures the error is hidden upon a successful response.
<details>
<summary>Steps to reproduce the bug in development environment.</summary>
1. Log in as Desdemona. Open the Manage user tab from the User Profile modal for a Normal user (e.g. here, Aaron).
2. Enter a name that is too short (like "a"), and click the Save changes button. An error shows up `Failed: Name too short!`.
3. Now, enter a valid name (like "aaron_updated"), and click the Save changes button.
4. The name in the title of the modal gets updated. The `Saved` confirmation message appears and gets removed after a delay but the error `Failed: Name too short!` is …
=> user_profile: Hide error when receiving a successful response.

zerver/actions/realm_settings.py, zerver/management/commands/archive_messages.py, zerver/tests/test_realm.py
Adds cron job logic to delete fully deactivated realms.
Follow-up of PR #31957.
Fixes #32763.
<details>
</details>
=> cron: Add cron job logic to delete fully deactivated realms.

web/src/message_fetch.ts, web/src/recent_view_ui.ts
When bulk marking messages as read, it can happen that the there are less number of rows visible than the current `row_focus`. This can lead to an error in the updated code here which results in the bulk mark as read operation from successfully updating the UI.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/Unable.20to.20mark.20all.20as.20read.20at.20Lean.20Prover
=> recent_view: Fix UI fails to update when marking messages read.

web/src/user_profile.ts
This PR adds a validation step that disables the Submit button in the Manage user tab and the Manage bot tab when the Name input field is empty.
Fixes: #22904.
<details>
<summary>Disabling the Submit button when the Name input field is empty.</summary>
</details>
<details>
<summary>Disabling the Submit button when the Name input field contains only spaces..</summary>
</details>
---
**Previous PRs associated with the same issue:**
- The PR [#23405](https://github.com/zulip/zulip/pull/23405) (inactive since Nov 2023) aims to solve this issue via backend changes but it was suggested to make changes in the frontend over [here](https://github.com/zulip/zulip/pull/23405#issuecomment-1300426434).
- The PR [#29640](https://github.com/zulip/zulip/pull/29640) …
=> settings: Validate the Name input field while editing a user or a bot.

web/src/compose.js, web/src/hotkey.js, web/tests/compose.test.cjs
This PR affects only test code (apart from a trivial search/replace).
=> compose tests: Clean up zjquery usage

web/src/message_lists.ts
In addition to the regular conversation view, we want to ensure the recipient bar remains consistently visible in the conversation view when using "near."
[Screencast from 2025-01-08 02-19-59.webm](https://github.com/user-attachments/assets/d0858bba-bd7d-40a0-9e3f-2b37807dfcc0)
[Screencast from 2025-01-08 02-21-41.webm](https://github.com/user-attachments/assets/652c687d-1ff7-4d58-bb40-4f62fa2bb8a3)
Fixes a bug introduced in #32233.
<details> …
=> messages_lists: Show recipient header in conversation view with "near".

api_docs/roles-and-permissions.md, docs/overview/changelog.md, docs/production/security-model.md, help/change-the-channel-description.md, help/change-the-privacy-of-a-channel.md, help/channel-posting-policy.md, help/configure-automated-notices.md, help/configure-who-can-administer-a-channel.md, help/configure-who-can-create-channels.md, help/configure-who-can-invite-to-channels.md, help/configure-who-can-unsubscribe-others.md, help/export-your-organization.md, help/manage-permissions.md, help/rename-a-channel.md, help/set-default-channels-for-new-users.md, web/templates/start_export_modal.hbs, zerver/openapi/zulip.yaml
Follow-up task from #32709:
> - Go through the channel management section and adjust Related articles links as needed.
> - Go through git grep "help/channel-permissions" outside of /help/ and /templates/corporate/ and see if anything needs to be adjusted. In particular, we may want to link anchor tags (e.g., /help/channel-permissions#private-channels) in some places.
**Notes**:
- Changed some descriptive text for links to `help/channel-permissions` as well as the noted tasks above.
---
*Updates that didn't change the content of the page, e.g. the link changed from `channel-permissions` to `channel-permissions#private-channels` are not shown below.*
<details>
<summary>Manage permissions</summary>
[CURRENT …
=> help: Update channel permissions links.

web/src/settings_account.ts, web/styles/settings.css, web/templates/settings/account_settings.hbs, web/templates/settings/profile_settings.hbs, web/tests/settings_org.test.cjs
This PR changes the behavior of the cursor with the "Name" and "Email" field labels in the Settings menu.
It includes the following changes:
- Introduces a class named `cursor-text` that sets the property `cursor: text;`.
- Uses a text cursor instead of a pointer cursor for the "Name" and "Email" field labels when the respective changes are disabled.
- Implements tests to verify the changes made.
This PR is a follow-up for [#32260(comment)](https://github.com/zulip/zulip/pull/32260#issuecomment-2521694570).
<details>
<summary>Name field</summary>
| Name changes enabled (Pointer Cursor) | Name changes disabled (Text Cursor) |
|---------------------------------------|-------------------------------------|
| ![Screenshot 2024-12-08 …
=> settings: Use text cursor for "Name" and "Email" field labels (if changes are disabled).

web/src/compose_ui.ts, web/tests/compose_ui.test.cjs
Previously, inserting a bulleted or numbered list via the compose box added an extra blank line before and after the list.
This commit removes the extra blank line inserted before the list.
Fixes #32607.
---
| **State**        | **Screenshot**                                                                                             |
|-------------------|----------------------------------------------------------------------------------------------------------|
| **Before**        | ![Before Recording](https://github.com/user-attachments/assets/dbbe124b-5034-4969-bed1-33cd1b1380ae)                         |
| **After**         | ![After Recording](https://github.com/user-attachments/assets/79f57f8c-89b9-42d1-b1f2-9cbea03f1e0f) …
=> compose: Remove extra blank line before lists.

tools/linter_lib/custom_check.py, zerver/tests/test_message_topics.py, zerver/views/streams.py
[Bug report on CZO](https://chat.zulip.org/#narrow/stream/9-issues/topic/Personal.20topics.20showing.20after.20being.20deleted/near/1931488)
Earlier, when a topic was deleted then UserTopic rows corresponding to that topic were not deleted resulting in a bug where the topic is listed in the '/#settings/topics' panel even after deletion.
<details>
</details>
=> delete_topic: Delete UserTopic rows when a topic is deleted. 

web/styles/app_components.css, web/styles/left_sidebar.css, web/styles/popovers.css, web/styles/recent_view.css, web/styles/right_sidebar.css, web/styles/subscriptions.css, web/styles/user_status.css, web/templates/filter_topics.hbs, web/templates/left_sidebar.hbs, web/templates/recent_view_table.hbs, web/templates/right_sidebar.hbs, web/templates/set_status_overlay.hbs, web/templates/stream_settings/stream_settings_overlay.hbs, web/templates/user_group_settings/user_group_settings_overlay.hbs, web/templates/user_profile_modal.hbs
This is a follow-up PR for #32594, It replaces all '**x**' -`fa-remove` icons with `zulip-icon-close` icons
across all search boxes in the app. 
Additionally, it resolves some hovering and displaying issues, ensuring consistency.
Fixes: #32598 
| Recent Conversations  | ![recent](https://github.com/user-attachments/assets/439911fa-1e88-49e2-95fd-e7c83b79e919)    |
| User Groups                         | ![Changes visible in alignment and hover](https://github.com/user-attachments/assets/639495b5-e275-49ee-9b69-3ac1a51e1c87)    |
| Direct Messages Left Sidebar  | ![dm](https://github.com/user-attachments/assets/846f4ee2-06bb-4 …
=> search_box: Use 'zulip-icon-close' instead of 'fa-remove' in all search boxes.

web/src/compose_validate.ts, web/styles/app_variables.css, web/styles/compose.css, web/styles/message_row.css, web/tests/compose_validate.test.cjs
This PR implements the feature of the compose box notifying users by changing colors when approaching or exceeding the message content limit.  
- Light theme
* background color when approaching the limit:
```css
--color-compose-message-content-background-approaching-limit: hsl(50deg 75% 92%);
```
* baclground color when exceeding the limit:
```css
--color-compose-message-content-background-over-limit: hsl(3deg 35% 90%);
```
*  border when approaching the limit:
```css
--color-message-content-container-border-approaching-limit: hsl(038deg 70% 50%);
```
* border when exceeding the limit:
```css
--color-message-content-container-border-over-limit: hsl(0deg 76% 65%);
```
- Dark theme  
* background color when approaching the limit:
```css …
```
=> Change compose box color when approaching/exceeding message length limit 

web/src/message_fetch.ts
Increase required messages significantly before stopping the backfill every time `Load more` is clicked.
=> recent_view: Fetch significant message history per `Load more` click.

api_docs/changelog.md, version.py, zerver/lib/email_mirror.py, zerver/lib/email_mirror_helpers.py, zerver/management/commands/send_to_email_mirror.py, zerver/openapi/zulip.yaml, zerver/tests/test_email_mirror.py, zerver/tests/test_queue_worker.py, zerver/tests/test_subs.py, zerver/views/streams.py
PR to add a `sender_id` parameter to the `GET /streams/{stream_id}/email_address` endpoint to specify the ID of a user or bot which should appear as the sender when messages are sent to a channel using the channel email address.
Earlier, Email gateway bot was always the sender.
[CZO API Design](https://chat.zulip.org/#narrow/channel/378-api-design/topic/channel.20email.20address/near/1991909)
**API Docs:**
**Manual testing using the `./manage.py send_to_email_mirror`**:
With `sender_id` as Hamlet, Email gateway bot (Default), and a Bot owned by Hamlet.
Fixes part of #31566 
<details> …
=> streams: Allow specifying sender for channel email generation.

templates/zerver/emails/realm_deactivated.html, templates/zerver/emails/realm_deactivated.txt, zerver/actions/realm_settings.py, zerver/tests/test_realm.py
Fixes #24686.
**Notes**:
- If there is a scheduled data deletion in the future, then the date is localized for the owner's language.
- In the case where no data deletion was scheduled when the realm was deactivated (e.g., via the support view or management command), then there is no change to the email content.
---
<details>
<summary>No data deletion done or scheduled when organization was deactivated</summary>
**No change from current email that's sent to organization owners.**
</details>
<details>
<summary>Data was immediately deleted when organization was deactivated</summary>
</details>
<details>
<summary>Data is scheduled to be deleted in the future when organization was deactivated</summary>
**3 owners - Russian, Italian and English set for their …
=> email: Update realm deactivation email for data deletion information.

zerver/lib/streams.py
We probably want to test in prod first before merging.
The NOT EXISTS structure might be better optimized by the Postgres query planner and might lead to slightly better performance than the id NOT IN (<subquery>) structure.
Generated SQL looks like this:
```
SELECT 
"zerver_stream"."id", 
"zerver_stream"."name", 
"zerver_stream"."realm_id", 
"zerver_stream"."date_created", 
"zerver_stream"."creator_id", 
"zerver_stream"."deactivated", 
"zerver_stream"."description", 
"zerver_stream"."rendered_description", 
"zerver_stream"."recipient_id", 
"zerver_stream"."invite_only", 
"zerver_stream"."history_public_to_subscribers", 
"zerver_stream"."is_web_public", 
"zerver_stream"."stream_post_policy", 
"zerver_stream"."is_in_zephyr_realm", 
"zerver_stream"."message_retention_days", …
```
=> streams: Tweak query in update_stream_active_status_for_realm.

docs/overview/changelog.md, help/delete-a-message.md, help/edit-a-message.md, help/email-notifications.md, help/include/cloud-only.md
Document more clearly when notifications are triggered.
Current: https://zulip.com/help/email-notifications
<details>
<summary>
Updated
</summary>
</details>
=> help: Refresh email notifications help page.

web/src/read_receipts.ts
Previously, the read-receipts dialog did not update if someone viewed the focused message while the dialog box was open. Users had to close and reopen it to see the updated receipts. Now, the dialog refreshes every minute to keep the read-receipts updated while open.
This issue solves the second part only as the first part was already solved by [#28799](https://github.com/zulip/zulip/pull/28799).
https://github.com/user-attachments/assets/22ae55d5-6f3f-4e26-b6dc-ada342b74cd2
Fixes: #24716.
<details> …
=> read-receipts: Auto-refresh read-receipts dialog every minute.

api_docs/changelog.md, docs/production/video-calls.md, help/start-a-call.md, version.py, web/src/compose_call.ts, web/src/compose_call_ui.ts, web/tests/compose_video.test.cjs, zerver/openapi/zulip.yaml, zerver/tests/test_create_video_call.py, zerver/views/video_calls.py
(This just fixes a couple conflicts that were unresolved in #27555)
We now allow users to create voice calls when their call provider is BigBlueButton. This is done by creating a call where cameras are disabled for all participants in the call -- a voice call, and making only the call creator the moderator, so no one else can switch a voice only call to a video call.
Also, we stop using the deprecated fields "attendeePW" and "moderatorPW" in the Big Blue Button API, and use "role" instead.
The side effects are that now we only support BigBlueButton 2.4 and above, and that only the call creator is a moderator and all other joinees are viewers for all BigBlueButton calls.
Fixes: #26550.
<details> …
=> integrations: Add support for BigBlueButton voice only calls.

web/styles/message_header.css
Followup up on  #32924 with a more involved change.
---
16px before and after
=> message_header: Use em instead of px for height and font-size.

web/styles/modal.css
This commit makes the modal title responsive for font-sizes 12px to 20px.
Fixes: 
| Old | New |
| --- | --- |
| 12px | 12px |
| ![old_modal_title_12px](https://github.com/user-attachments/assets/862b44be-9639-4a0a-88f4-658dfa334500) | ![new_modal_title_12px](https://github.com/user-attachments/assets/e703e881-723d-4129-b096-b20a2d1ff6ca) |
| 14px | 14px |
| ![old_modal_title_14px](https://github.com/user-attachments/assets/060c01ae-eb06-484a-8c7e-400d7b34eccb)  | ![new_modal_title_14px](https://github.com/user-attachments/assets/30596a61-8e0d-4929-960b-5d1bda9977e2)
| 16px | 16px |
| ![old_modal_title_16px](https://github.com/user-attachments/assets/7943e5eb-27b0-46fe-a3f5-67bdfcbb8af7)  | ![new_modal_title_16px](https://github.com/user-attachments/asse …
=> modal: Use em instead of rem for modal title.

web/src/composebox_typeahead.ts, web/tests/composebox_typeahead.test.cjs
Since Zulip channel and topic names cannot
contain newlines, we should not show channel
or topic suggestions if the `#**stream>topic`
syntax is spread across multiple lines.
So we tweak the regexes to not match topics having `\n`.
We do not need to change the regexes in `marked.js` or `markdown/__init.py__` since the message text is already split at newlines
before being matched against those regexes,
so a newline will never be present during matching, both in the frontend and the backend.
| ![image](https://github.com/user-attachments/assets/84bc3b69-deea-4e39-8053-94211902ad0a) | ![image](https://github.com/user-attachments/assets/cb72273e-91aa-4723-969d-e1e23d3eae5c) |
<details> …
=> composebox_typeahead: Avoid opening on multiline stream/topic names.

web/src/activity_ui.ts, web/src/buddy_data.ts, web/src/buddy_list.ts, web/src/message_list.ts, web/tests/buddy_data.test.cjs, web/tests/conversation_participants.test.cjs, web/tests/message_list.test.cjs
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/build_user_sidebar.20called.203x.20when.20changing.20view
Tested by simply sending new messages or removing existing messages. Also tested that other narrows look good.
=> Avoid rerender of user sidebar when adding or removing messages from message list.

help/gdpr-compliance.md, templates/corporate/policies/sidebar_index.md, templates/corporate/policies/subprocessors.md
Also add reference links.
Notes:
- I think we should make the /policies/subprocessors links non-relative once this has been deployed in production?
Current: https://zulip.com/help/gdpr-compliance
<details>
<summary>
Updated help center page
</summary>
</details>
<details>
<summary>
New policies page
</summary>
</details>
=> help and policies: Reorganize GDPR compliance documentation.

web/src/stream_create.ts, web/src/stream_settings_ui.ts, web/src/user_group_create.ts, web/src/user_group_edit.ts, web/src/user_groups.ts, web/templates/user_group_settings/change_user_group_info_modal.hbs, web/templates/user_group_settings/user_group_creation_form.hbs
- First commit is a preparatory refactor.
- Second commit is to live-update duplicate name error on receving stream rename events.
- Third commit is to allow renaming deactivated groups.
Fixes:  #32876
<details>
</details>
=> Allow renaming deactivated user groups.

web/src/bundles/app.ts, web/src/color_picker_popover.ts, web/src/hotkey.js, web/src/popover_menus.ts, web/styles/app_variables.css, web/styles/buttons.css, web/styles/color_picker.css, web/templates/popovers/color_picker_popover.hbs, web/templates/tooltip_templates.hbs, web/webpack.dev-assets.json
This PR is a follow-up for #32063, and makes the following changes:
- Updates custom color swatch icon to use rainbow gradient.
- Adds `buttons.css` file to `app.ts` bundle for production usage.
- Overrides the on-focus outline style in action-button and icon-button.
- Adds confirm button to the color picker popover.
Fixes:  [CZO Discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/colorpicker.20migration.20and.20redesign/near/2013004)
| Header | Header |
| <img width="271" alt="Screenshot 2025-01-09 at 1 48 18 AM" src="https://github.com/user-attachments/assets/7ed13a68-f59d-4b68-aee9-bf594e3d01c9" /> | <img width="271" alt="Screenshot 2025-01-09 at 1 14 57 AM" src="https://github.com/user-attachments/assets/fbce3e81-607f-4f22-bcf4-d11d96196278" /> |
| …
=> stream_color: Color picker popover improvements.

web/styles/left_sidebar.css
This commit removes the mistakenly added bottom border from topic search section.
before:
after:
<details>
</details>
=> left_sidebar: Remove bottom border from 'topic_search_section'.

web/src/popover_menus_data.ts
Allows the user to Quote a deleted message  as asked in [CZO Thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/message.20actions.20popover.20acts.20differently.20in.20dev.20environment/near/2029573)
As:
- It could not be correctly internationalized.
- We see a reason a user might want to do this.
<details>
</details>
=> popovers: Quoting for a  "(deleted)" tombstone messages will be allowed

api_docs/changelog.md, version.py, web/tests/lib/events.cjs, zerver/actions/reactions.py, zerver/lib/event_types.py, zerver/openapi/zulip.yaml, zerver/tests/test_reactions.py
The deprecated `user` object was removed from message objects and reaction events in #32701. This commit restores the `user` object in reaction events to maintain compatibility with mobile clients.
<details>
</details>
=> reaction: Add `user` object back in reaction events.

web/src/stream_edit.ts
Currently, clicking the subscriber count for a channel in the stream list menu works the same way as clicking the entire tab for that channel. If the currently open tab is "General," clicking on another channel’s tab also opens the "General" tab for that channel. This behavior applied to the subscriber count as well, as there was no specific click action associated with it.
This PR implements a dedicated click action for the subscriber count. Clicking it now opens the "Subscribers" tab of the selected channel, regardless of which tab is currently open.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
https://github.com/user-attachments/assets/d8570b04-3bbe-49ee-9378-89ee84ac4d01
</td>
<td>
https://github.com/user-attachments/assets/f44a55ba-12da-417a-bf3e-f3ab9784f8bb
</td> …
=> Open subscribers tab on clicking subscribers count.

web/src/recent_view_ui.ts, web/src/resize.ts, web/src/resize_handler.ts, web/src/views_util.ts, web/styles/app_variables.css, web/tests/recent_view.test.cjs
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/recent.20conversations.3A.20narrow.20window.20column.20misalignment
| just before right sidebar is hidden 4 avatars | with only 2 avatars |
| --- | --- |
| ![Screenshot from 2025-01-12 17-25-15](https://github.com/user-attachments/assets/6de8c6e6-b411-468c-b8bd-6c3813304b12) | ![Screenshot from 2025-01-12 17-25-23](https://github.com/user-attachments/assets/a76a5be9-b7fd-49f3-ba6f-3a0c65ab3c22)  |
| just before left sidebar is hidden 4 avatars | with only 2 avatars |
| --- | --- |
| ![Screenshot from 2025-01-12 17-25-59](https://github.com/user-attachments/assets/1fc4cb05-a2ba-48ed-8663-2b61e0ca2e28) | ![Screenshot from 2025-01-12 17-25-41](https://github.com/user-attachments/assets/04857679-33b8-41d0-9f2c-a84f157f841e) |
=> Prevent participants avatars from overflowing in recent view.

web/styles/portico/billing.css
Likely due to increase in font size payment method is wrapping to next line.
| --- | --- |
|![Screenshot from 2025-01-14 19-41-26](https://github.com/user-attachments/assets/a29d72c3-fcfa-4f02-ade1-1e291d343d2f) | ![Screenshot from 2025-01-14 19-41-12](https://github.com/user-attachments/assets/4ec3647e-0cc2-4ad3-a469-823171cd4f65) |
=> billing: Fix "Payment method" wrapping to next line.

web/src/hashchange.ts
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/Clicking.20link.20for.20same.20message.20the.202nd.20time.20doesn't.20work
In 666ce4519d09ac2f5bf53635cc9f422590b21c7b, we switched to use `this.href` instead of `e.currentTarget.getAttribute("href")`.
This bugged the behaviour since `this.href` includes the complete URL including hostname.
Switched to use `this.hash` to fix it.
=> hashchange: Fix `near` link not working if already narrowed to it.

web/src/compose_call_ui.ts, web/src/compose_closed_ui.ts, web/src/composebox_typeahead.ts, web/src/message_edit.ts, web/src/stream_popover.ts, web/src/typeahead_helper.ts, web/templates/confirm_dialog/confirm_merge_topics_with_rename.hbs, web/templates/inline_stream_or_topic_reference.hbs, web/templates/move_topic_to_stream.hbs, web/templates/typeahead_list_item.hbs, web/tests/compose_closed_ui.test.cjs, web/tests/compose_video.test.cjs
Fixes the followings checkboxes from #32996
Other Fixes:
- #**stream_name>topic_name** syntax to work properly for empty string topic.
---
<details><summary>Move messages modal</summary>
</details> 
<details><summary>Inline topic edit</summary>
</details> 
<details><summary>Confirm merge topics modal</summary>
</details> 
<details><summary>Reply button text</summary>
</details> 
<details><summary>Compose box textarea topic list typeahead</summary>
</details>
---
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.htm …
=> web: Add support for empty topic names.

web/templates/popovers/left_sidebar/left_sidebar_topic_actions_popover.hbs, web/templates/recipient_row.hbs, zerver/actions/message_edit.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_move_topic.py
FIxes the following checkbox from #32996 
---
<details><summary>Topic popover</summary>
</details> 
<details><summary>Message header</summary>
</details> 
<details><summary><code>/api/update-message</code></summary>
</details> 
---
<details>
</details>
=> message_edit: Disallow resolving empty string topic.

corporate/lib/stripe.py, corporate/tests/test_stripe.py, corporate/tests/test_support_views.py
If the customer has a current fixed-price plan and a support admin configures a fixed-price plan for the upcoming billing year, then a `CustomerPlan` object is created and not a `CustomerPlanOffer`.
Fixes the support action for deleting a configured fixed-price next plan. Currently trying to delete the scheduled next fixed-price plan returns an error.
Updates the success strings for these actions to be specify if the deleted object was a plan offer or a scheduled plan.
---
<details> …
=> billing: Fix deleting next fixed-price plan via support.

web/styles/popovers.css
This PR adjusts the focus outline for the "New channel" input in the Move message(s) and topic modal, preventing it from extending to the entire modal and limiting it to the input element only.
Fixes: [CZO thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/Focus.20outline.20in.20move.20messages.20modal/near/2042020).
<details>
<summary>Focus outline on the "New channel" input.</summary>
**Light mode:**
| Before changes | After changes |
|----------------|---------------|
| ![image](https://github.com/user-attachments/assets/8747474e-e9ab-4da4-8603-f93e40217073) | ![image](https://github.com/user-attachments/assets/6f18ac2d-1b1f-49c5-93ec-16c215a77c0c) |
**Dark mode:**
| Before changes | After changes |
|----------------|---------------|
| …
=> css: Adjust focus outline for New Channel input in Move messages modal.

api_docs/changelog.md, version.py, zerver/openapi/zulip.yaml, zerver/tests/test_user_groups.py, zerver/views/user_groups.py
This PR updates code to allow changing description and permission settings of deactivated
groups.
Fixes:  https://chat.zulip.org/#narrow/channel/101-design/topic/updating.20deactivated.20streams.20and.20groups/near/2037327
<details>
</details>
=> Allow changing description and settings for deactivated groups.

web/styles/inbox.css, web/styles/popovers.css, web/styles/user_status.css
This PR replaces instances of `hsl(200deg 100% 40%)` with CSS variable `--color-text-url` to standardise text link color. Unused style for `.bot-owner-name` is also removed.
fixes: #31520
<details>
<summary>UI Changes</summary>
| --- | --- |
| ![Before Image](https://github.com/user-attachments/assets/77382499-a5c5-4a08-bb02-9e2d6ce7f1d5) | ![After Image](https://github.com/user-attachments/assets/29d99202-6f60-43d5-be24-0252fbe396ac) |
| ![Before Image](https://github.com/user-attachments/assets/11de5023-310e-4957-9108-024f36508c3c) | ![After Image](https://github.com/user-attachments/assets/8b81bb2b-a1b7-446a-b3bd-c46b0427a0f5) |
| ![Before Image](https://github.com/user-attachments/assets/10c45011-83c8-42b6-b249-c86608a9aca8) | ![After …
=> css: Use `--color-text-url` variable as color for text links.

web/styles/left_sidebar.css, web/templates/filter_topics.hbs, web/templates/left_sidebar.hbs
This PR presents a proper gridded layout for filter-box inputs and close buttons, correcting some issues introduced by #32638. 
It also ensures that all three left-sidebar filters (DMs, channels, and topics) occupy the same vertical and horizontal space and offsets (note especially how the DM filter now matches the width of the channels and topics filters, and how all filters uniformly align to the left and right of other rows), and present an ellipsis on long filter input when the filter box is unfocused (previously, the DM filter was missing that).
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.E2.9C.94.20extra.20line.20in.20left.20sidebar/near/2035611)
_All screenshots show compact mode and 16px and 20px font-size. In addition to …
=> left_sidebar: Present uniform, gridded filter boxes.

web/src/compose_state.ts, web/src/hotkey.js
This PR permits the left arrow key to scroll the formatting buttons when keyboard focus is in the buttons area, making it so both the right and left arrows can control the scroll.
Additional work is being discussed [on CZO](https://chat.zulip.org/#narrow/channel/101-design/topic/arrow.20keys.20on.20scrolling.20formatting.20buttons/near/2043652), but will not be addressed until [after the 10.0 release](https://chat.zulip.org/#narrow/channel/101-design/topic/arrow.20keys.20on.20scrolling.20formatting.20buttons/near/2043779).
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/arrow.20keys.20on.20scrolling.20formatting.20buttons/near/2043652)
<details> …
=> compose: Allow left arrow to scroll buttons.

web/styles/compose.css, web/styles/inbox.css, web/styles/left_sidebar.css, web/styles/right_sidebar.css
This PR standardizes the use of `visibility: hidden` for `clear_search_buttons` in search boxes instead of `display: none`.
related [comment](https://github.com/zulip/zulip/pull/33047#issuecomment-2603110892)
<details>
</details>
=> searchbox_css: Replace `display: none` with `visibility: hidden`.

web/src/settings_components.ts, web/src/settings_org.ts, web/src/settings_preferences.ts, web/styles/settings.css, web/templates/settings/preferences_general.hbs
This PR includes the following changes:
- The theme select dropdown in the Preferences section of the Personal settings is replaced with the theme switcher, similar to the one in the personal menu popover.
- The theme select dropdown in the Default User Settings section of the Organization settings also follows the same set of changes.
Fixes: #32111.
[CZO Thread](https://chat.zulip.org/#narrow/channel/101-design/topic/dark.20theme.20setting/near/1964206)
<details>
<summary>Interaction of Theme switcher in Personal Settings - Preferences</summary>
</details>
<details>
<summary>Interaction of Theme switcher in Organization Settings - Default user settings</summary>
</details>
<details>
<summary>Reverting back to the previous theme in Personal Settings - …
=> settings: Replace the Theme select dropdown with the Theme switcher.

web/src/composebox_typeahead.ts, web/src/topic_link_util.ts, web/tests/topic_link_util.test.cjs
In the function `get_stream_topic_link_syntax`,
we used the typed syntax text to make out
the channel name and then use it to
generate the appropriate link syntax.
We change that to directly accepting the
channel name.
This is in preparation for #31420
Extracted from #31669.
=> topic_link_util: Accept channel name instead of syntax text.

web/src/compose_notifications.ts, web/templates/compose_banner/automatic_new_visibility_policy_banner.hbs, web/templates/compose_banner/message_sent_banner.hbs
Fixes the following checkbox of #32996:
<details><summary>Now following banner</summary>
</details> 
<details><summary>Unmuted banner</summary>
</details> 
<details><summary>Go to stream > topic</summary>
</details> 
<details><summary>Narrow to stream > topic</summary>
</details> 
---
<details>
</details>
=> compose_banner: Show `realm_empty_topic_display_name` for topic="".

web/src/hotkey.js
This fixes #33123, which was a regression due to
7e57477.
Test the color picker and the left/right keys for gear menu.
https://chat.zulip.org/#narrow/channel/9-issues/topic/keyboard.20navigation.20in.20gear.20menu
=> navbar bug fix: Restore sideways keyboard navigation.

zerver/lib/integrations.py
Layered the commits.
Ordered the refactoring commit (DOC_PATH) at the end, because I'm not sure about it, and I didn't want to block the rest of the commits by placing it at the beginning.
Affected integrations: Hubot integrations - Assembla, Bonusly, Chartbeat, Dark Sky, Instagram, Mailchimp, Google Translate, YouTube.
Here's how the catalog looks after adding the secondary line text "(Hubot script)"
<details> …
=> Update the HubotIntegrations

web/src/settings_ui.ts
This PR refactors the `do_settings_change()` function in the [`web/src/settings_ui.ts`](https://github.com/zulip/zulip/blob/main/web/src/settings_ui.ts#L34) file. It is used to inform users about the changes to the settings UI.
The function uses a `setTimeout` function (introduced in [`381e498`](https://github.com/zulip/zulip/commit/381e49834326bff609b5ff0b69ec27e6fc2e30c2#diff-b41fc8099af8ce546ed80f29155d770eed68bf1141db0b7ef91452d4a13119a1R55)) in its success callback where the value of `appear_after` is `500ms`. It was pointed out if the `setTimeout` function is useful here by `Tim Abbott` over [here](https://github.com/zulip/zulip/pull/32260#discussion_r1906092460).
`Tim Abbott` [said](https://chat.zulip.org/#narrow/channel/6-frontend/topic/setTimeout.20in.20do_settings_change/near/203 …
=> settings_ui: Refactor the `do_settings_change()` function.

templates/corporate/billing/billing.html, web/styles/portico/portico_signin.css
Updates the billing page HML and CSS to use header elements and classes for styling instead of label elements. Most of the label elements were not associated with any form or input elements, and were serving the role of a section header.
This also fixes an issue with displaying the next charge amount for fixed-price plans that are scheduled; see first screenshot.
*Sidenote: It looks like the CSS rules are still being applied/ordered oddly on these corporate billing pages as the font-family that's being applied (at least in the dev environment) is the one set by bootstrap and not portico.*
---
<details>
<summary>Scheduled upgrade to fixed-price plan</summary>
| --- | --- |
| ![Screenshot from 2025-01-14 …
=> billing: Update billing page label elements to header elements.

corporate/views/portico.py, templates/corporate/pricing_model.html
Updates the context variables used in the plans page template for the "legacy" plan change to "complimentary access".
**Notes**:
- Fixes the logic for when to show an "Upgrade scheduled" notice on the plans page template. Previously, that note was shown in the case that an annual fixed-price plan had a continuing plan scheduled for the upcoming year.
**Follow-ups**:
- Technically, an annual fixed-price plan could have a downgrade scheduled, e.g., the customer is on the Zulip Business plan currently and the upcoming year they negotiated a fixed-price plan for Zulip Basic. This is the only current case where a downgrade could be "scheduled". Regular plans would just be scheduled to end without a plan tier change. We should probably think about how we'd want this to appear on both the …
=> billing: Update plans page for "legacy" name change.

corporate/lib/stripe.py, corporate/tests/stripe_fixtures/change_plan_tier_from_standard_to_plus--Invoice.create.1.json, corporate/tests/stripe_fixtures/change_plan_tier_from_standard_to_plus--Invoice.finalize_invoice.1.json, corporate/tests/stripe_fixtures/change_plan_tier_from_standard_to_plus--Invoice.list.1.json, corporate/tests/stripe_fixtures/change_plan_tier_from_standard_to_plus--InvoiceItem.create.1.json, corporate/tests/test_stripe.py
When we are upgrading a customer to a different plan tier, we should check if switching plans would lead to different licenses due to different minimum license requirement between plans.
Tested by upgrade a realm from standard to plus to see if the licenses changed from 1 to 10.
=> stripe: Check for `min_licenses` when switching plan tier.

web/styles/widgets.css
Poll title was set to 18px which was leading to the title looking smaller than the options in 20px font size. Removing that explicit font-size declaration will make the h4 font-size fall back to 1.1em and thus that title will scale properly to font-size changes. At 16px, the font-size for the title was 18px initially, now it is 17.6px which should not be that big of a change.
NOTE: This PR also applies the same change to TODO lists as well since they share the same css, but I have not uploaded screenshots since it felt redundant to do so.
| --- | --- |
| 12px | 12px |
| <img width="745" alt="poll_12px_before" src="https://github.com/user-attachments/assets/ec16970b-40ba-4f00-8cba-6ce1d28b530a" /> | <img width="745" …
=> polls: Do not use pixel height for poll title.

zerver/actions/message_edit.py, zerver/tests/test_events.py, zerver/tests/test_message_fetch.py, zerver/tests/test_message_move_topic.py
"build_message_edit_request" is a better name for the function.
<details>
</details>
=> message_edit: Rename get_message_edit_request_object.

web/styles/popovers.css, web/styles/zulip.css
This PR fixes overflow issues in the move_topic_modal by removing the unneeded flex display and allowing the text in checklists to wrap on small screens. It also improves the width of the dropdown across different screen sizes.
<details>
<summary>Quick Overview</summary>
| --------- | ------ |
| When a channel name is big enough (~60 characters), there is overflow visible in "New topic" input. | Removing flex display helps avoiding this overflow without affecting the existing layout. |
| ![image](https://github.com/user-attachments/assets/1f42e803-4cc2-4440-9648-8cd7253d0795) | ![image](https://github.com/user-attachments/assets/85dd59d6-9cf7-4161-acf6-636a52123ae0)|
| The overflow is slightly noticeable even for shorter channel names. | This issue also gets fixed. |
| …
=> move_topic_modal: Fix overflow issues.

web/src/hotkey.js
[CZO thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/keyboard.20navigation.20in.20color.20picker)
At Channel settings overlay, vertical keyboard navigation on color picker was obstructed by `stream_settings_ui.switch_rows`.
This commit fixes the issue by using `color_picker_popover.handle_keyboard` prior to `stream_settings_ui.switch_rows`
<details>
</details>
=> color_picker: Enable vertical keyboard navigation at channel settings.

docs/production/reverse-proxies.md, docs/production/system-configuration.md, puppet/zulip/manifests/nginx.pp, puppet/zulip/templates/nginx/trusted-proto.template.erb
In some cases, it is not possible to configure the load-balancer to add an X-Forwarded-Proto header.  If Zulip is serving its traffic over HTTP, it will rightly error out, since it cannot guarantee that its response will be served over an encrypted connection.
Add a new `loadbalancer.rejects_http_requests` settings which serves as a way for the operator to swear that the load-balancer will *never* serve responses from Zulip over an unencrypted connection.  In most cases, this is because the load-balancer is configured to have port 80 always serve an HTTP 301 redirect to the same URL over HTTPS.
Properly configuring the proxy to send `X-Forwarded-Proto` is always a better solution than using this configuration parameter, so use of this should be viewed as a last resort.
=> nginx: Add an option which defaults loadbalancer requests to https.

web/src/compose_closed_ui.ts, web/templates/reply_recipient_label.hbs, web/tests/compose_closed_ui.test.cjs
Addresses https://github.com/zulip/zulip/pull/33020#discussion_r1915463713:
> I think ideally we'd arrange for this translation to match the other Message one just above to save translation effort, which probably means just reworking the recipient_label_text case to use the same string.
<details>
</details>
=> compose_closed_ui: Unify translation strings for reply button label.

web/src/filter.ts, web/src/inbox_ui.ts, web/src/recent_view_ui.ts, web/src/search_pill.ts, web/src/search_suggestion.ts, web/src/settings_user_topics.ts, web/templates/input_pill.hbs, web/templates/search_description.hbs, web/tests/filter.test.cjs, web/tests/recent_view.test.cjs, web/tests/search_suggestion.test.cjs
Completes filter and search part of #32996:
<details><summary>Recent conversations filter</summary>
</details> 
<details><summary>Inbox view filter</summary>
</details> 
<details><summary>SETTINGS/TOPICS</summary>
</details> 
<details><summary><code>channel:Scotland</code></summary>
</details> 
<details><summary><code>channel:Scotland topic:</code></summary>
</details>
<details><summary>Pill italics</summary>
</details> 
---
<details>
</details>
=> web: Add search/filter support for empty topic names.

web/src/message_list_view.ts
When `message_row`s can be stacked on top of each other if draft or scheduled messages overlay is open. To avoid selecting message from them, we filter them out.
=> message_list_view: Check if the sticky header is not from overlays.

web/styles/portico/markdown.css
Fixes: [CZO Link](https://chat.zulip.org/#narrow/channel/6-frontend/topic/Alignment.20of.20zulip-icon.20in.20integration.20docs/near/2054942)
The `zulip-icon` `vertical-alignment` discrepancy is caused by a rule that applies only to `.content` children.
While help docs and API docs have a `.content` element, integration docs do not.
So, I've moved that rule outside the `.content` selector, so that it applies to the integration docs and the Team page as well. Not sure if that's the best fix.
<details>
**`/team`**
| ![Pasted image 20250123004253](https://github.com/user-attachments/assets/ebe4cf3d-7402-4a2d-bd0e-f0d3dc5bb50c) | ![Pasted image 20250123004309](https://github.com/user-attachments/assets/1864ca4c-48da-4ece-956 …
=> Fix vertical alignment of icons in integration docs

web/styles/right_sidebar.css
The reason to use 0.875em instead of 1em in part was also that 1em felt a bit too large to show that empty list message. 
Haven't uploaded comparison screenshots, since it was not scaling at all before this. Let me know if you need them.
12px:
14px:
16px:
18px:
20px:
<details>
</details>
=> right_sidebar: Use em for empty list message font-size.

web/src/message_list.ts, web/styles/app_variables.css, web/styles/message_row.css
This PR does a few things:
1. It fixes a bug where going into topic-edit mode would cause a vertical shift in the sender line.
2. It reworks variables and grid definitions to allow the message action buttons to scale along with text, as well as ensuring uniform vertical alignment of the buttons with the timestamp, no matter what kind of message is displayed, with or without a sender line.
3. It improves the grid definitions on me-messages.
**Screenshots and screen captures** (The showing-grids captures have been updated since Tim's initial review):
| Topic outside edit mode | Topic while editing, before | Topic while editing, after |
| ![topic-pre-edit](https://github.com/user-attachments/assets/a35d7155-6de4-4431-8e59-11834d2c7d9f) | …
=> message_row: Refine grids and alignment for scalable action buttons.

web/src/reactions.ts, web/tests/reactions.test.cjs
While adding a new reaction, we create a new JQuery element called "message_reaction_container" and append it to the view to display the emoji.
Previously, when the reaction count became zero for an emoji, we used to just remove the emoji but not the JQuery element mentioned above, requiring a reload to remove it. This inconsistency introduced a bug in the UI. causing unwanted spaces between emojies as this element used to get accumulated.
This PR resolves the bug by introducing logic to remove reaction containers with no reactions. To achieve this, we assign a unique class to each container,
".emoji-container-emoji_code", where "emoji_code" is a variable unique to each emoji. This enables us to specifically identify and remove the containers.
**Before**
[Screencast from 2025-01-14 …
=> Remove emoji container when reaction count is 0.

web/src/tippyjs.ts, web/templates/left_sidebar.hbs, web/templates/popovers/left_sidebar/left_sidebar_condensed_views_popover.hbs, web/templates/tooltip_templates.hbs
This PR includes counts in tooltips for different navigation list in left sidebar.
Fixes: zulip#25901
<details>
</details>
=> Include tooltips count in left sidebar

templates/zerver/footer.html, templates/zerver/landing_nav.html, templates/zerver/portico-header.html, zerver/context_processors.py, zproject/default_settings.py
Fixes #32199
We only need a log in button since that will take users to "/accounts/go" if we are on a non-realm specific URL.
"/accounts/go" already has link to go to "Find accounts" page.
Home page:
| --- | --- |
| ![Screenshot from 2025-01-14 16-13-18](https://github.com/user-attachments/assets/ad884508-c090-410a-8c1a-d96489c6f4b7) | ![image](https://github.com/user-attachments/assets/db59e625-47fe-42c1-98e0-64a8bcd2cbd6) |
Other pages:
| --- | --- |
| ![image](https://github.com/user-attachments/assets/768a2115-0181-4597-8248-bec717876250) | ![image](https://github.com/user-attachments/assets/e636486f-696a-421b-a4ff-5412731b2ebd) |
I check help pages, login pages and landing page. I used `zulipdev.com:9991` and `localhost:9991` for testing. …
=> portico: Replace "Find accounts" link with "Log in".

web/styles/compose.css
As discussed on a call with @alya this week, this PR removes adjustments that made the help icon look diminutive in relation to the others in the formatting bar.
A flex adjustment previously on the help icon is now applied to all compose control buttons,
though no visible changes result from that (it's only the help button that needs it, owing to its place in the DOM relative to other formatting buttons). But because button sizes are controlled precisely in the area, ordinary flex grow/shrink behavior is undesirable.
| --- | --- |
| ![formatting-help-before](https://github.com/user-attachments/assets/4034ff4e-9c4a-418d-875a-94c873c6a383) | ![formatting-help-after](https://github.com/user-attachments/assets/ee86da1c-d69d-44dd-af02-0547 …
=> compose: Size help-button icon to match other formatting buttons.

zerver/data_import/slack.py, zerver/tests/test_slack_importer.py, zerver/webhooks/slack/view.py
1. Fetching from the `/users.list` endpoint is supposed to use pagination. Slack will return at most 1000 results in a single request. This means that our Slack import system hasn't worked properly for workspaces with more than 1000 users. Users after the first 1000 would be considered by our tool as mirror dummies and thus created with is_active=False,is_mirror_dummy=True. Ref https://api.slack.com/methods/users.list
2. Workspaces with a lot of users, and therefore requiring the use of paginated requests to fetch them all, might also get us to run into Slack's rate limits, since we'll be doing repeating requests to the endpoint. Therefore, the API fetch needs to also handle rate limiting errors correctly. Per, https://api.slack.com/apis/rate-limits#headers, we can just read the …
=> slack: Fetch workspace users from /users.list in the correct manner.

web/src/common.ts, web/styles/app_components.css
This commit updates the keyboard shortcuts UI by replacing the ⌘ symbol with a more visually appealing icon.
Fixes: #32926 
| **before**       | **after**                | 
|--------------------|--------------------------------|
| ![image](https://github.com/user-attachments/assets/3c31351d-265a-41ad-b4a2-a8d4d19c9756) | ![image](https://github.com/user-attachments/assets/65cf8e27-c705-4618-9947-d51710bece0d)    |
| ![image](https://github.com/user-attachments/assets/726c5179-c5ad-4fa0-be02-78053d433fc4)| ![image](https://github.com/user-attachments/assets/45998a94-b875-4cc6-a743-5cd8d5f58390) |
=> style: Center the ⌘ symbol by replacing with icon

scripts/lib/check-database-compatibility, zerver/lib/export.py, zerver/lib/import_realm.py, zerver/lib/migration_status.py, zerver/lib/test_fixtures.py, zerver/management/commands/get_migration_status.py, zerver/tests/fixtures/import_fixtures/applied_migrations_fixtures/with_complete_migrations.json, zerver/tests/fixtures/import_fixtures/applied_migrations_fixtures/with_missing_apps.json, zerver/tests/fixtures/import_fixtures/applied_migrations_fixtures/with_unapplied_migrations.json, zerver/tests/fixtures/import_fixtures/applied_migrations_fixtures/with_unsorted_migrations_list.json, zerver/tests/fixtures/import_fixtures/check_migrations_errors/extra_migrations_error.txt, zerver/tests/fixtures/import_fixtures/check_migrations_errors/unapplied_migrations_error.txt, zerver/tests/fixtures/import_fixtures/migration_status.json, zerver/tests/fixtures/import_fixtures/showmigrations_fixtures/with_stale_migrations.txt, zerver/tests/test_import_export.py, zerver/tests/test_migration_status.py
The current `get_migration_by_app` has a rather naive approach to compiling the migration status of a realm, which has led to issues like #32826. Specifically, those flaws are:
- It does not report the complete state of the migration status of the exporting servers, only the applied migration.
- It shows both the replaced and the squashing migrations. This would be a problem if we decide to delete old migrations we've replaced and import a slightly older realm with those still intact, `check_migration_status` would complain of incompatibility even though those migration files don't matter (they are replaced, after all). 
- It does not clean up ancient/stale applied migrations  (for reference, see how `check-database-compatibility` cleans those) 
This PR attempts to write a better …
=> export/import: Rework how we write `migration_status.json`

web/src/left_sidebar_navigation_area.ts, web/styles/left_sidebar.css, web/tests/left_sidebar_navigation_area.test.cjs
This PR implements the following changes as suggested by @amanagr [here](https://github.com/zulip/zulip/pull/29536#issuecomment-2058655243):
- Rename `active-filter` to `top-left-active-filter`.
- Remove handling of `active-sub-filter` as it is not relevant in this context.
- Use `$(".top-left-active-filter").removeClass("top-left-active-filter")` to remove the class and then add the class to the desired element.
Fixes: #26686.
<details> …
=> left_sidebar: Rewrite left sidebar navigation area library.

zerver/actions/message_send.py, zerver/lib/bot_lib.py, zerver/tests/test_message_flags.py, zerver/tests/test_message_send.py, zerver/tests/test_service_bot_system.py, zerver/worker/embedded_bots.py, zerver/worker/outgoing_webhooks.py
Previously service bots don't get UserMessage rows for new messages for optimization reasons. This commit adds `UserMessage` row for service bots to enforce the assertion that service bots behave similarly to generic bots.
Additionally, this commit also adds the ability to track whether or not service bots have processed an event (mention / direct message) message by flagging that message as read by the sending bot.
Fixes: #28869
[CZO discussion](https://chat.zulip.org/#narrow/channel/3-backend/topic/.2328869.20UserMessage.20for.20Outgoing.20webhook.20bot.20.26.20embedded.20bots)
- outgoing bot reacting to message in a group chat:
_before_
```bash
curl -sSX POST http://localhost:9991/api/v1/messages/101/reactions 
-u …
```
=> messages_send: Make service bots have UserMessage rows.

api_docs/changelog.md, version.py, web/src/message_view_header.ts, web/src/server_events_dispatch.js, web/src/stream_events.ts, web/src/stream_settings_ui.ts, web/tests/dispatch_subs.test.cjs, web/tests/lib/events.cjs, zerver/actions/streams.py, zerver/actions/users.py, zerver/lib/event_types.py, zerver/lib/streams.py, zerver/lib/types.py, zerver/openapi/zulip.yaml, zerver/tests/test_events.py, zerver/tests/test_subs.py
Fixes #32369
Migrate stream delete event to include only stream ids in the form of `"stream_ids": [1,...]` because clients only need the ids.
While also keep sending same ids in the form of `"streams": [{stream_id: 1},...]` for compatibility with all clients other than web.
=> stream_delete_event: Include only stream IDs in the event.

web/src/topic_link_util.ts, web/tests/topic_link_util.test.cjs
These characters cause the fallback markdown
links produced (https://github.com/zulip/zulip/pull/30071) to be broken.
Broken links are not produced when these are present
in `#**channel>topic**` syntax. It is only a problem
with the fallback markdown links.
| Before | After|
| <img width="671" alt="Screenshot 2025-01-25 at 17 43 17" src="https://github.com/user-attachments/assets/04ce7e5c-897b-4038-8933-bb83ea750d6f" />   | <img width="671" alt="Screenshot 2025-01-25 at 17 43 43" src="https://github.com/user-attachments/assets/0978c570-f3e0-470b-8b35-6e4b74563bbe" /> |
<details>
Individual …
=> topic_link_util: Add `[` and `]` as characters to escape.

web/src/settings_data.ts, web/src/stream_create.ts, web/src/stream_data.ts, web/src/stream_ui_updates.ts, web/tests/settings_data.test.cjs, zerver/lib/streams.py, zerver/models/users.py, zerver/openapi/zulip.yaml, zerver/tests/test_subs.py, zerver/views/streams.py
All the followups mentioned in #33000 have been addressed in this PR. The following lines were not added to any other settings because it does not apply to any other setting from what I checked:
```
Users who can administer the channel or have the similar
realm-level permission can add subscribers regardless of the value
of this setting.
```
It might change once https://github.com/zulip/zulip/pull/33000#discussion_r1927431606 is answered.
https://github.com/zulip/zulip/pull/33000#discussion_r1925950477 is being fixed in #33156.
<details> …
=> Can subscribe others followups

web/src/topic_list_data.ts, web/src/util.ts
Earlier, in `topic_list_data.ts` we were using `topic_display_name` variable to represent part of the topic name without resolved_prefix. This could led to confusion with `util.get_final_topic_display_name()` as both represent different things.
This commit updates the code to use 'topic_bare_name' for a better representation of its meaning.
<details>
</details>
=> topic_list_data: Update variable names to avoid confusion.

zerver/lib/topic.py
b747ea285f9a fixed the code's order, but not the accompanying comment.
Fixes: 
<details>
</details>
=> topic: Fix comment to be in the right order.

web/styles/popovers.css
In the profile card that pops up when clicking a user's name, the text of their name was not selectable text previously. This commit makes the text selectable.
[Screencast from 2025-01-27 22-07-00.webm](https://github.com/user-attachments/assets/d2ea36b5-85ac-4b67-ba18-89e8f310ef16)
[Screencast from 2025-01-27 22-06-16.webm](https://github.com/user-attachments/assets/34f7c56a-3b2c-4e23-946f-b632f1cb0170)
[CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/text.20in.20user.20card.20not.20selectable)
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discip …
=> popovers: Make "popover-menu-user-full-name" text selectable.

zerver/actions/message_edit.py, zerver/tests/test_message_move_topic.py
https://github.com/zulip/zulip/pull/32532#issuecomment-2613417916
> The first 2 commits need to be reworked for the empty topic work; @prakhar1144 maybe you can do a PR extracting and updating those, and then this PR can be integrated soon after with just the frontend commit?
* Second commit is not required.
* In the first commit, updated the logic to raise error when topic_name is empty string or "(no topic)" with `mandatory_topic=true`
* Cleaned up tests a bit and added comments.
---
---
<details> …
=> message_edit: Disallow empty topic when mandatory topic is true.

zerver/lib/email_notifications.py, zerver/lib/topic.py, zerver/tests/test_message_notification_emails.py
Fixes part of #32996.
Email only
<details>
</details>
=> missedmessage_emails: Show EMPTY_TOPIC_FALLBACK_NAME for topic="".

web/src/copy_and_paste.ts, web/tests/copy_and_paste.test.cjs
discussed [here](https://chat.zulip.org/#narrow/channel/9-issues/topic/pasting.20code/near/1987276):
> When I paste code, I appreciate that it sometimes adds backticks for me, but it's annoying when I've already written a backtick, and I end up in a situation like
>
> (before I paste)
>
> ```
> `
> ```
>
> (after I paste)
>
> ```
> ``some code`
> ```
>
> It would be nice if we checked for an existing backtick before adding them like that.
=> copy_and_paste: Don't add code syntax if backtick is already present.

web/src/group_permission_settings.ts, web/src/hash_util.ts, web/src/server_events_dispatch.js, web/src/settings_components.ts, web/src/settings_config.ts, web/src/stream_events.ts, web/src/user_group_edit.ts, web/src/user_groups.ts, web/styles/subscriptions.css, web/templates/settings/settings_checkbox.hbs, web/templates/settings/settings_numeric_input.hbs, web/templates/user_group_settings/group_permission_settings.hbs, web/templates/user_group_settings/user_group_settings.hbs, web/tests/dispatch.test.cjs, web/tests/lib/events.cjs, web/tests/stream_events.test.cjs
- First commit is a refactor commit to move type definition.
- Second commit is to improve node tests.
- Third commit is a refactor in live-update code.
- Fourth commit is to define labels in a common object.
- Fifth commit is again a refactor for moving function definitions.
- Sixth commit is a refactor to rename a variable.
- Last three commits are to add realm, stream and group settings in permissions panel.
Fixes part of #28806 
<details> …
=> Add permissions panel to group management UI.

zerver/webhooks/slack/doc.md, zerver/webhooks/slack_incoming/doc.md
I didn't test anything. The intent is there are no substantive changes in these instructions.
This PR replaces #32714.
Current: https://zulip.com/integrations/doc/slack
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/integrations/doc/slack_incoming
<details>
<summary>
Updated
</summary>
</details>
=> Update docs for Slack integrations

help/manage-user-groups.md
Current page: https://zulip.com/help/manage-user-groups
Note that I'm aiming to clearly label this heading vs. https://zulip.com/help/manage-user-groups#configure-group-permissions .
=> help: Document group permissions panel.

web/styles/left_sidebar.css
This replaces a hard-coded 17px font-size on the left sidebar vdots.
[CZO discussion](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/broader.20range.20of.20font.20sizes/near/2063089)
_All screenshots were captured at 122 line-height, at 20px, 16px, and 12px font-size._
| Navigation, before | Navigation, after |
| --- | --- |
| ![nav-vdots-20-before](https://github.com/user-attachments/assets/a13523df-2480-4c0b-8b54-e9167da195c1) | ![nav-vdots-20-after](https://github.com/user-attachments/assets/4e8f43e3-dcd4-40c9-8c39-650a57bf0b94) |
| ![nav-vdots-16-before](https://github.com/user-attachments/assets/1fc6eb12-1150-4c88-aad4-6491d4b3f1b7) | ![nav-vdots-16-after](https://github.com/user-attachments/assets/d6a23192-a805-47a5-b0b0-052b770 …
=> left_sidebar: Allow vdots icon to scale.

zerver/data_import/slack.py, zerver/tests/test_slack_importer.py, zerver/webhooks/slack/view.py
1. Fetching from the `/users.list` endpoint is supposed to use pagination. Slack will return at most 1000 results in a single request. This means that our Slack import system hasn't worked properly for workspaces with more than 1000 users. Users after the first 1000 would be considered by our tool as mirror dummies and thus created with is_active=False,is_mirror_dummy=True. Ref https://api.slack.com/methods/users.list
2. Workspaces with a lot of users, and therefore requiring the use of paginated requests to fetch them all, might also get us to run into Slack's rate limits, since we'll be doing repeating requests to the endpoint. Therefore, the API fetch needs to also handle rate limiting errors correctly. Per, https://api.slack.com/apis/rate-limits#headers, we can just read the …
=> Backport slack: Fetch workspace users from /users.list in the correct manner. 

zerver/lib/mention.py, zerver/lib/user_groups.py, zerver/tests/test_markdown.py
Fixes #32934
Fetching all members (direct & via sub-groups) of groups mentioned in a single message, using a constant number of  queries (only 2 queries) .
1. Create `get_root_id_annotated_recursive_subgroups_for_groups` which is the same as `get_recursive_subgroups_for_groups` except the former keeps track of and annotates  `root_id` for each group.
2. Attach `prefetch_related` to the  result of `get_root_id_annotated_recursive_subgroups_for_groups`, to get all the matching **active** members, **fetching only their ids**.
Using `CaptureQueriesContext`: 
`get_root_id_annotated_recursive_subgroups_for_groups` executes only **one query**, as opposed to iteratively calling `get_recursive_group_members`  which runs in `O(n)`.
I tested the following cases, mentioning them in a single message : …
=> mention: Optimize query when mentioning several groups.

web/styles/message_header.css
Pulled from #32928. It became necessary for this PR because `top: var(--navbar-fixed-height);` on the sticky header needs to use the app's font size, and having a different font size on that div was messing that up.
----
This is helpful for info density, because `em` values change depending on the font-size of the HTML element, and we want to be able to reference `em` sizes for the placement of the message header container when it's sticky.
**This commit should have no functional changes** because `message-header-contents` is the only child of `message_header` and doesn't itself use font size or line height.
This commit also changes the line height to unitless https://chat.zulip.org/#narrow/channel/6-frontend/topic/navbar.20sticky.20header.20with.20em/near/2054561
----
Screen videos of …
=> message_header: Specify font-size and line height on content div.

web/src/compose.js, web/src/hotkey.js
Previously, Cmd + Return did not send messages in preview mode when configured by the user.
This commit fixes the logic to allow sending messages in preview mode with Cmd + Return as per user configuration.
Fixes: #32960
<details>
</details>
=> compose: Fix Cmd + Return to send messages in preview mode on Mac.

web/src/compose_recipient.ts
This pr fixes the bug where the placeholder in message compose disappears after something is typed and the removed.
Just added a function which removes the br tag that gets added because of the `contenteditable` attribute in which the browser automatically adds a br tag when text is removed due to which the placeholder is not shown.
This bug still needs to be fixed for :
- Invite User Modal -> Channels they should join field
- Invite User Modal -> User groups they should join field
- Add Members to a Group Form -> Choose members field
Fixes: #32912
https://github.com/user-attachments/assets/d402d735-abee-4f6d-af8e-320551fed5fa
<details> …
=> compose: Fix placeholder disappearance bug.

web/styles/widgets.css
This PR resolves the transition problem for the "Add option" button and option field in polls to ensure proper synchronization when switching to the dark theme.
Fixes: #30628.
https://github.com/user-attachments/assets/4c4d8b3e-b229-44f1-894b-b09fd5adf076
https://github.com/user-attachments/assets/02d89d98-7d25-4e88-885f-97eb2ebcd191
<details>
</details>
=> polls: Fix transition issue for "Add" and "New" option in dark theme.

web/styles/app_variables.css, web/styles/dark_theme.css, web/styles/settings.css
This PR refactor all the theme colors used in `settings.css` and `dark_theme.css`.
[CZO](https://chat.zulip.org/#narrow/channel/6-frontend/topic/refactor.20theme.20colors.20in.20.60dark_theme.2Ecss.60/near/1944995).
| `#id_realm_enable_spectator_access_label a`  | `#id_realm_enable_spectator_access_label a`  |
| ![{C7385588-1BC2-49C1-BF70-BC497F9F0AF4}](https://github.com/user-attachments/assets/18d79cb9-ae09-4180-997b-245c273331c2) | ![{3BDE9218-44FF-47C0-A009-D8A62C81E708}](https://github.com/user-attachments/assets/c8777cb8-8eee-4b73-9108-2fb771c6334c) |
| ![{5B3C9F3C-B0AB-45A7-A9DF-11F3383AD7AF}](https://github.com/user-attachments/assets/1d1e1569-d7f9-40fb-9b44-96630d64a12c) | …
=> Refactor theme colors for `settings`.

web/styles/app_variables.css, web/styles/left_sidebar.css
This PR removes two unnecessary selectors, but also makes a) masked unread markers and b) the condensed navigation area scale appropriately.
[CZO discussion](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/broader.20range.20of.20font.20sizes/near/2064636)
| Before (20px, 12px) | After (20px, 12px) |
| --- | --- |
| ![sidebar-sweep-20-before](https://github.com/user-attachments/assets/2b262959-69de-4839-912c-f2685bb0555d) | ![sidebar-sweep-20-after](https://github.com/user-attachments/assets/12fd4a67-2436-4ea8-93f9-93318b8d3f51) |
| ![sidebar-sweep-12-before](https://github.com/user-attachments/assets/4a0fd427-cf7e-4ca0-9b62-e5c20875f014) | ![sidebar-sweep-12-after](https://github.com/user-attachments/assets/568aebb9-a8b2-483d-994c-c0e5 …
=> left_sidebar: Sweep for remaining px-based font-size values.

web/e2e-tests/navigation.test.ts, web/src/message_fetch.ts, web/src/reload.ts, web/src/server_events.js, web/src/util.ts, web/tests/util.test.cjs
In order to avoid races with the user's device connecting to a network after unsuspending, we ping the `/server_settings` endpoint for a success response before initiating the reload of the app.
Fixes #33118.
---
**Notes**:
- I haven't able to reproduce the reported error/screen from the issue / CZO conversation in the dev environment, but I was able to trigger initiating a reload of the web-app in the dev environment.
- Currently, there isn't any `"#connection-error"` show/hide for `ui_report` included in these updates. I wasn't sure if going with something like we have in [`get_events`](https://github.com/zulip/zulip/blob/264e49e7e8ede23be94089b5dd2237f577ad8518/web/src/server_events.js#L148-L156) polling where there is a specific class added to the error message or with something more …
=> reload: Check "/server_settings" before initiating a reload of the web-app.

web/src/tippyjs.ts
Earlier, unread_count in home view tooltip was set to total unread messages while we normally exclude muted messages from unread_count.
PR changes this by setting it to home_unread_messages count.
Fixes: [czo](https://chat.zulip.org/#narrow/channel/9-issues/topic/New.20left.20sidebar.20tooltips.20bug/near/2065009)
<details>
</details>
=> Left sidebar home view unread_count tooltip includes muted messages count.

web/styles/popovers.css
| Before  | After  |
|---------|--------|
| ![before](https://github.com/user-attachments/assets/421ecb21-2b8e-457c-84f0-9b05a58ec2a2) | ![after](https://github.com/user-attachments/assets/39556da1-4771-4891-894c-4c4ff4559c06) |
Fixes: https://chat.zulip.org/#narrow/channel/101-design/topic/UI.20for.20viewing.20deactivated.20groups.20.2332877/near/2062807
=> Fix deactivated icon overflow

zerver/lib/narrow.py, zerver/tests/test_message_fetch.py
[CZO discussion thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/-is.3Adm.20doesn't.20work.20with.20channels.3Apublic)
Solves the issue of ignoring the dm operators when they are present with channel operator in search even when one of them is negated.
Now the -is:dm filter when applied with channels:public filter gives the same result as channels:public filter. (same goes for -channels:public with is:dm)
For this I have added checks for negated terms which basically compares the address of the maybe_negative function with the not_ function so it has negligible effect on server speed.
Fixes: #33033 -is:dm now works with channels:public filter
As discussed in the thread …
=>  Considered negations of dm and channel narrows before pruning the search

web/src/bootstrap_typeahead.ts, web/src/composebox_typeahead.ts, web/src/typeahead_helper.ts, web/styles/typeahead.css, web/templates/typeahead_list_item.hbs, web/tests/composebox_typeahead.test.cjs, web/tests/typeahead_helper.test.cjs
Fixes #32184
This PR lets the user get a consecutive topic typeahead after selecting a particular stream via the typeahead menu. Previously they had to manually enter ">" after stream typeahead selection
Eg:
Previously #Den + "Tab" key would result in `#**Denmark**` and after this user would have to enter ">" to trigger the topic typeahead completion
This PR solves this unituitive behaviour by prompting a topic select after immediately selecting a particular stream via a typeahead menu.
- I changed a part of **tokenize_compose_str**, since it returned "**topic_jump**" as the current_token in `get_candidates()` whenever some stream was selected from the typeahead menu. I made it return the token instead, basically slicing it to return `#stream_name>sometext`
- Also had to alter the …
=> compose: make it easy to select topic after selecting stream in composebox_typeahead

help/link-to-a-message-or-conversation.md, help/mention-a-user-or-group.md, templates/corporate/case-studies/asciidoctor-case-study.md
Some tweaks were inspired by https://zulip.com/help/mention-a-user-or-group.
Current: https://zulip.com/help/link-to-a-message-or-conversation
Updated:
=> help: Update doc on linking to channels and topics within Zulip.

help/include/sidebar_index.md, help/keyboard-shortcuts.md, help/saved-snippets.md, web/templates/keyboard_shortcuts.hbs
First pass at documenting the new saved snippets feature for composing messages.
Fixes #33131.
Blocked on #31892.
---
**Notes**:
- Until #31892 is merged to main, the icon in the compose box used for this feature doesn't exist. So when that's merged, then this needs to be updated to use `class="zulip-icon zulip-icon-message-square-text"` instead of `class="zulip-icon zulip-icon-message-square"` which is used for the current draft.
- Also adds the keyboard shortcut documentation for the changes in the above pull request.
- We could possibly use a shared include file for the instruction to open the saved snippet dropdown and/or the keyboard shortcut tip. But as we probably won't use them anywhere else, it seemed fine to just repeat the text for the three instruction blocks.
--- …
=> help: Document the saved snippets compose box feature.

web/src/user_group_popover.ts, web/templates/popovers/user_group_info_popover.hbs
Fixes #31550.
This PR improves user group popover presentation. Instead of displaying all members, it just shows the first 30 members and includes a link to member management page or organization users page.
Note: I accidentally closed the PR [32917](https://github.com/zulip/zulip/pull/32917), so open this one instead.
For testing purpose, the gif shows change when cut-off is 10 members. The actual code was implemented with cut-off of 30 members. This value can be modified.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-di …
=> user_group_popover: Reduce member list size, add member page links.

web/styles/right_sidebar.css
These fixes replace `margin` with `padding`, and replicate the `--background-color` variable on the userlist header, so as to stave off an edge case where margin offsets might allow usernames from the user list to bleed through. (Note that the subsections were other possible culprits, but they are already offset by padding and have `--background-color` set on the `.buddy-list-subsection-header` selector.)
Though I was unable to replicate [the original issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AFusers.20peeking.20through.20above.20heading/near/1989366), including in the desktop app on an external monitor, this fix seems likely to correct the problem.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AFusers.20peeking.20through.20above.2 …
=> right_sidebar: Ensure opaque userlist header.

zerver/lib/avatar.py, zerver/tests/test_outgoing_webhook_interfaces.py, zerver/tests/test_upload.py, zerver/tests/test_users.py, zerver/views/users.py, zproject/default_settings.py
The functionality of gravatar can break anonymity if the user has had a gravatar account set up previously.
This option allows specifically cloud instances to have gravatar disabled selectively.
Fixes: no specific issue has been created yet
<details>
</details>
The option does have one main issue, it uses `realm.id` instead of the `realm.string_id`. I tried using `string_id` first, but this spawned a whole lot of regression fails due to increased …
=> gravatar: add option to overwrite global settings per realm

web/src/dialog_widget.ts, web/src/message_summary.ts, web/styles/zulip.css, web/templates/dialog_widget.hbs
Implemets part of #33230
* Make it wider.
* modal title just be the plain topic name
* add a "Mark topic as read" button if the topic has unreads.
* Add a footer warning.
Topic without unreads:
Topic with unreads:
=> AI summary modal UI tweaks

web/styles/banners.css
As I just noted in another PR that's using container queries, #32685, we should always be explicitly referencing the container name in `@container` queries. This adds `banner` to the three here (no others in the codebase yet exist, and we should keep it that way).
=> banners: Explicitly reference container name in queries.

zerver/lib/push_notifications.py, zerver/management/commands/register_server.py, zerver/tests/test_push_notifications.py
Remaining follow-up from https://github.com/zulip/zulip/pull/33233#discussion_r1936356290
This means that the URL is only hard-coded on the bouncer side. That's useful, because now we'll be able to change the URL and only need a bouncer deployment for users to get the new URL when they encounter HostnameAlreadyInUseBouncerError. As opposed to self-hosted servers being stuck with an outdated docs link hardcoded in their register_server.py.
=> register_server: Add docs_url to HostnameAlreadyInUseBouncerError.

web/src/sidebar_ui.ts, web/templates/left_sidebar.hbs, web/templates/popovers/color_picker_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_all_messages_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_inbox_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_recent_view_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_starred_messages_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_stream_actions_popover.hbs, web/templates/popovers/left_sidebar/left_sidebar_topic_actions_popover.hbs, web/templates/stream_sidebar_row.hbs
Fixes: #27625 
[CZO thread](https://chat.zulip.org/#narrow/stream/101-design/topic/narrow.20left.20sidebar.20closing/near/1678316)
Clicking on left_sidebar popovers on smaller screens, where the left_sidebar is hidden by default, caused the left_sidebar to close automatically. This required users to repeatedly reopen the sidebar if they wanted to perform multiple actions on the popover.
The first commit of this PR resolves this issue by adding the `no-auto-hide-left-sidebar-overlay` class to the left_sidebar popovers.
This class was previously used only on the "Change color" option but not on whole popover or the color picker popover itself.
<details>
<summary>Before</summary>
[issue_left_sidebar.webm](https://github.com/user-attachments/assets/a030ab87-91ab-4b6e-85c6-16b71f605751) …
=> left_sidebar: Avoid closing sidebar in narrow views when interacting with popovers.

web/src/list_widget.ts, web/src/settings_users.ts, web/styles/settings.css, web/templates/settings/active_user_list_admin.hbs, web/templates/settings/attachments_settings.hbs, web/templates/settings/bot_list_admin.hbs, web/templates/settings/data_exports_admin.hbs, web/templates/settings/deactivated_users_admin.hbs, web/templates/settings/default_streams_list_admin.hbs, web/templates/settings/emoji_settings_admin.hbs, web/templates/settings/filter_text_input.hbs, web/templates/settings/invites_list_admin.hbs, web/templates/settings/linkifier_settings_admin.hbs, web/templates/settings/muted_users_settings.hbs, web/templates/settings/playground_settings_admin.hbs, web/templates/settings/user_topics_settings.hbs, web/tests/list_widget.test.cjs
This PR adds an "x" button to the table filters in settings.
Fixes: #32599.
| Table | Before | After |
| Users | ![image](https://github.com/user-attachments/assets/60ef4c8b-0555-41c9-92d7-4e0eb41807f3) | ![image](https://github.com/user-attachments/assets/9016014c-4486-4330-84ac-de53a9ba7137) |
| Deactivated Users | ![image](https://github.com/user-attachments/assets/deec1e1c-4ecf-438d-9ead-cfb9a9336f93) | ![image](https://github.com/user-attachments/assets/0526109a-6aca-43e6-a048-204fc53bad99) |
| Invitations | ![image](https://github.com/user-attachments/assets/e7499fbd-ddf9-42a1-bccb-3ad968e2ae1d) | ![image](https://github.com/user-attachments/assets/db6f2f5d-7002-4de4-a411-50a10f7d7dc6) |
| Bots | …
=> Adds "x" button to the table filters in settings.

web/styles/modal.css
This fixes a bug with names with descenders at large font sizes.
Screenshots before and after at 12px, 14px, 16px, 20px. Note how King Hamlet was cut off on the bottom before this change.
| --- | --- |
| ![Screen Shot 2025-02-01 at 16 53 19](https://github.com/user-attachments/assets/1a30f2a6-a3e4-41a1-bdec-77f4354390e8) | ![Screen Shot 2025-02-01 at 16 59 55](https://github.com/user-attachments/assets/3a0c292e-07de-4c14-9cdd-c1e19864743c) |
| ![Screen Shot 2025-02-01 at 16 53 04](https://github.com/user-attachments/assets/f7500258-74d6-4ce7-8fa0-71ee20ec47ea) | ![Screen Shot 2025-02-01 at 16 57 46](https://github.com/user-attachments/assets/76c7c9d1-1e17-43cb-aac7-4684004f0d26) |
| ![Screen Shot 2025-02-01 at 16 52 …
=> user_profile: Use em to scale height of name heading with font size.

docs/outreach/mentoring.md
While reading the documentation, I noticed that the word 'you' had been omitted from a sentence. This causes the sentence to be unclear and grammatically incorrect. I have manually edited in the word to improve the documentation.
=> Corrected a missing word in this sentence for clarity.

web/src/compose.js, web/src/compose_send_menu_popover.js, web/src/scheduled_messages.ts, web/templates/compose_banner/success_message_scheduled_banner.hbs
This commit adds a note to the confirmation banner if the message is scheduled for the minimal 5 minutes ahead time,
regardless of whether the user tried to schedule it for sooner or not.
However this PR still doesn't solve the bug of that 1 minute delay that occurs in some cases as no reason for that lag has been identified yet.
Related [CZO Discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/Offset.20in.20scheduled.20messages).
If you don't want to read the entire thread, please read below mentioned messages as they are important to know about that 1 minute lag.
- [Message 1](https://chat.zulip.org/#narrow/channel/9-issues/topic/Offset.20in.20scheduled.20messages/near/2064263)
- [Message 2](https://chat.zulip.org/#narrow/channel/9-issues/topic/Offset.20in.20scheduled.20mess …
=> compose: Add notice to confirmation banner.

docs/contributing/counting-contributions.md
=> contributor docs: Document policy for non-code attributions.

web/src/message_viewport.ts
Reproducer:
* Mark all messages in a topic as unread.
* Go to recent view.
* Click on topic.
* Scroll
* Message selection is not updated.
To fix this, we don't disable updating message selection unless we are sure we are going to trigger a scroll event.
Tested using the avove reproducer.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/Message.20selection.20not.20updated.20on.20scroll
=> message_viewport: Fix msg selection not updated on scroll.

web/styles/compose.css
Fixes issue with radio button sitting too high at larger font sizes:
----
Here are screenshots after this fix. I turned on grid lines to show how the grid is set up, but just for the first option and the second option works the same but is visible without the grid lines.
12px:
14px:
16px:
20px:
=> compose: Use grid for enter sends choices to align radio buttons.

web/src/inbox_ui.ts
This is hard to debug but likely not a critical UX bug.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/compose.20button.20error.20in.20dev
=> inbox_ui: Avoid AssertionError when starting new compose message.

zerver/actions/streams.py, zerver/tests/test_subs.py
Previously, channel archival unread messages in archived channels could still be accessed from the inbox view.
This commit fixes this issue by auto-marking the channel archival event message as read.
Fixes: #33258.
| Before                                                                                      | After                                                                                       |
|---------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| ![before](https://github.com/user-attachments/assets/a0c94270-c6bc-4f36-91f3-8765aea91012) | ![after](https://github.com/user-attachments/assets/8d6a0a76-6b93-438d-ad …
=> channels: Auto-mark channel archival event messages as read.

zerver/actions/message_edit.py, zerver/tests/test_message_edit.py
This PR fixes a bug introduced in commit [37f2c5bc788](https://github.com/zulip/zulip/commit/37f2c5bc788d613e0b65f25341ea2704d9325097), where a message in DM is not updated to "(deleted)" when left empty after editing.
Fixes: #33305
<details>
</details>
=> message_edit: Fix "(deleted)" not showing for empty edited DMs.

web/src/group_permission_settings.ts, zerver/tests/test_subs.py
- First commit is to add test.  https://github.com/zulip/zulip/pull/33316#discussion_r1939986953 
- Second commit is to use set instead of list. https://github.com/zulip/zulip/pull/33316#discussion_r1939990964
<details>
</details>
=> Follow-ups for #33316.

web/src/server_events_dispatch.js, web/src/settings_components.ts, web/src/settings_config.ts, web/src/stream_events.ts, web/src/user_group_edit.ts, web/templates/user_group_settings/group_permission_settings.hbs, web/templates/user_group_settings/stream_group_permission_settings.hbs, web/templates/user_group_settings/user_group_permission_settings.hbs, web/tests/dispatch.test.cjs, web/tests/stream_events.test.cjs
- First two commits are refactors.
- Last commit is to live-update permissions panel when group gains permission.
<details>
</details>
=> Live update permissions panel when group gains permission.

web/src/copy_and_paste.ts, web/tests/copy_and_paste.test.cjs, zerver/tests/fixtures/katex_test_cases.json
We now do a more precise check to decide whether
to perform the span conversion for intermediate
text nodes.
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/HTML.20paragraphs.20misconverted.20by.20copy.20and.20paste.
Tested it manually on some other inline and math blocks.
=> copy_and_paste: Fix regression caused by quoting math.

web/styles/settings.css, web/templates/settings/custom_user_profile_field.hbs
Ideally this isn't set with relative positioning, but I decided not to refactor that for now and just help what we already have not be buggy.
---
16px before and after
=> settings: Fix placement of remove date button.

web/styles/inbox.css, web/templates/inbox_view/inbox_view.hbs
We likely added this logic to allow links to be opened in new tab on ctrl + click and not trigger text selection.
We retain this behaviour but allow selection of empty view text.
Verified text selection works on in empty view.
https://chat.zulip.org/#narrow/channel/9-issues/topic/Disallow.20select.20for.20empty.20view.20banner.20texts
=> inbox: Allow user to select empty view text.

zerver/openapi/zulip.yaml
* Commit 1: We missed to update docs for scheduled_message while working on feature level 334. 
* Commit 2: [CZO Discussion
](https://chat.zulip.org/#narrow/channel/412-api-documentation/topic/.28realm_.29mandatory_topics.20behavior/near/2052822)
Ideally, we should merge this after [/help/require-topics](https://chat.zulip.org/help/require-topics) gets updated -- which would be after we finalize the "general chat" name.
Schedule messages / update scheduled message related:
Message send / edit related:
<details> …
=> api_docs: Improve docs related to empty string topic.

web/src/emoji_picker.ts, web/src/popover_menus.ts
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/Reacting.20to.20very.20tall.20messages
=> emoji_picker: Show popover as overlay if reference is not visible.

web/styles/app_variables.css, web/styles/input_pill.css, web/styles/search.css, web/styles/zulip.css
<details>
<summary>screenshots: simple navbar</summary>
16px before and after
20px before after
</details>
<details>
<summary>screenshots: search with pills</summary>
16px before and after
</details>
<details>
<summary>screenshots: short navbar</summary>
16px before and after
</details>
=> navbar: Scale navbar with app font size, using em.

zerver/tests/test_thumbnail.py, zerver/tests/test_upload.py
Fixes warnings like `ResourceWarning: unclosed file <_io.FileIO name='/srv/zulip/var/4fc6d348-ccfe-43fa-8a2e-5b4ff5a15a66/test-backend/run_2304691/worker_7/test_uploads/files/2/d9/KYUsAKJ_g45NA7CojVbRW0C4/zulip.jpeg' mode='rb' closefd=True>` with warnings enabled.
- New instances since #30994
- Cc @alexmv
=> tests: Consume more streaming responses

web/styles/user_status.css
It looks fine without the height explicitly set, and the fixed height only works at 14px info density.
I tested that it doesn't overflow onto a second line or anything with long status messages.
Before and after at 12px, 14px, 16px, and 20px:
| ---- | ---- |
| ![Screen Shot 2025-02-05 at 12 33 52](https://github.com/user-attachments/assets/825280e5-1341-453a-be18-0c3f5d2f8e7f) | ![Screen Shot 2025-02-05 at 12 31 35](https://github.com/user-attachments/assets/5b8312dd-ab91-4e9f-b955-427a9ef081e2) |
| ![Screen Shot 2025-02-05 at 12 34 05](https://github.com/user-attachments/assets/1ba8386f-3502-4ae5-b5ca-65367b269631) | ![Screen Shot 2025-02-05 at 12 30 56](https://github.com/user-attachments/assets/d9ea80de-c4a8-4a09-8aef-ea68aa098661) |
| ![Screen Shot 2025-02-05 at 12 …
=> user_status: Remove fixed px height of status input.

web/src/hotkey.js, web/src/pm_list.ts, web/src/sidebar_ui.ts, web/src/stream_list.ts, web/src/topic_list.ts, web/tests/hotkey.test.cjs, web/tests/stream_search.test.cjs
Earlier, whenever pm_list or stream_list was zoomed in and channels filter was not visible, hitting `q` would trigger `stream_list.initiate_search` and `stream-row` would append highlight class in the background. Zooming out would then get in a state where stream filter is open without focus and `stream-row` is highlighted.
Steps to repro bug:
> 1. Expand the "Direct messages" section by hitting the "more conversations" link.
> 2. Click in the message feed to unfocus the "Filter direct messages" box.
> 3. Hit q. (Originally I'd done this in an attempt to focus the "Filter direct messages" box again. But in fact it has no visible effect.)
> 4. Hit the "back to channels" link to return to the full left sidebar.
Fixes: [czo](https://chat.zulip.org/#narrow/channel/9-issues/topic/left-sidebar.2 …
=> Remove auto highlight of stream row when filtering.

web/src/inbox_ui.ts, web/src/message_events.ts, web/src/pm_list_data.ts, web/src/recent_view_ui.ts, web/src/unread.ts, web/styles/left_sidebar.css, web/templates/inbox_view/inbox_list.hbs, web/templates/inbox_view/inbox_row.hbs, web/templates/inbox_view/inbox_stream_header_row.hbs, web/templates/pm_list_item.hbs, web/templates/recent_view_row.hbs, web/tests/pm_list_data.test.cjs, web/tests/recent_view.test.cjs
This PR introduces unread @-mention indicators for DMs in inbox, recent conversations and left sidebar.
Uses `unread.get_counts()` to maintain a `mention_dict` mapping `user_ids_strings` of DMs to a `boolean` if unread dm message contains any mentions.
Fixes: zulip#28849
<details>
</details>
=> Show unread @-mention indicator for DMs.

zerver/data_import/rocketchat.py
Apparently some exports have a weird `ObjectId("idstring")` typed value here, that stringify to the actual string.
=> rocketchat: Harden parsing of custom emoji exports.

web/src/user_profile.ts
I believe this regression was introduced by #33075, where some additional logic was added to not render the content of user profile tabs more times than necessary.
Fixes: The `user_groups_list_widget` is populated once the user profile modal is first opened, but not cleared when closed. This caused user group membership to not be rendered when opening the user profile modal again.
User groups disappear after opening and closing the dialog once:
https://github.com/user-attachments/assets/fcea912e-2d1d-46ba-abf3-3f172a4be3c9
User groups are shown consistently after closing and reopening the modal:
https://github.com/user-attachments/assets/eaf71b85-08e2-4840-96c7-3501062b99fa
<details> …
=> user_profile: invalidate user group state after closing the user modal.

web/src/stream_data.ts, web/tests/hash_util.test.cjs, web/tests/stream_data.test.cjs
Previously, if we had syntax in a URL slug that looked like a channel ID, but we couldn't find the channel.
This could break rendering of topic links that we want to process via rendered_markdown.ts. I believe that the web app's logic for processing narrows does not require its caller to check the channel ID is accessible.
The updated logic matches what we do in the mobile apps.
@evykassirer FYI, since you did the last pass on this code.
=> stream_data: Fix parsing of slugs for inaccessible channels.

docs/production/install.md, docs/production/mobile-push-notifications.md, scripts/lib/install
Either prompt the user which services to enable or get them passed via --services. Based on that, update the settings.py configuration.
The prompt string and service names are super crude right now, we'll want to reword them properly once we have the logic figured out.
By default, you're going to get prompted for your choices right after you start the install script.
e.g.
```
No --services option provided. Starting manual configuration.
Enable mobile_push? [y/n] (default: no): y
Enable submit_usage_statistics? [y/n] (default: no): jjj
Invalid input. Defaulting to 'no'.
...
```
If any service got enabled, runs `manage.py register_server` at the end. `register_server` prompts you to agree to ToS, so the user can still back out if they change their mind before any data gets sent to us.
=> install: Prompt for whether to enable push notifications service at the start.

web/styles/message_header.css
[CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20privacy.20icon.20spacing.20in.20message.20header/near/2057146)[ thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20privacy.20icon.20spacing.20in.20message.20header/near/2057146)
| -- | -- |
| ![Screen Shot 2025-02-05 at 21 43 21](https://github.com/user-attachments/assets/4aa5c95a-2d68-45e5-9ff3-077f051fa5fd) | ![Screen Shot 2025-02-05 at 21 43 44](https://github.com/user-attachments/assets/3694c7fc-f4af-44d3-8928-2d8f4d342f86) |
| ![Screen Shot 2025-02-05 at 21 43 01](https://github.com/user-attachments/assets/eec51518-d173-4bc7-a71f-92d3a7023f42) | ![Screen Shot 2025-02-05 at 21 42 …
=> message_header: Center privacy icons.

web/src/password_quality.ts, web/src/settings_account.ts, web/tests/password.test.cjs
This commit modify the settings_change_error function to show the error inside the modal, instead of the settings panel behind it.
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/Modal.20not.20closing.20when.20action.20fails.2E).
<details>
</details>
=> change_password_modal: Hide the dialog spinner when action fails.

web/styles/modal.css
| --- | ---- |
| ![Screen Shot 2025-02-05 at 12 51 34](https://github.com/user-attachments/assets/dd75ab44-f41b-45de-bebf-543b8a372673) | ![Screen Shot 2025-02-05 at 12 47 15](https://github.com/user-attachments/assets/49abdfd3-b1df-4bb9-b00b-6dae352a624a) |
| ![Screen Shot 2025-02-05 at 12 51 15](https://github.com/user-attachments/assets/ff473e37-9f5a-4763-b13f-7844a3400b58) | ![Screen Shot 2025-02-05 at 12 47 52](https://github.com/user-attachments/assets/90a30230-42d2-46d2-bfa9-d2911324be2e) |
| ![Screen Shot 2025-02-05 at 12 50 53](https://github.com/user-attachments/assets/b0505117-595d-48a8-a028-43984e6f22b5) | ![Screen Shot 2025-02-05 at 12 46 44](https://github.com/user-attachments/assets/2b748c4c-823d-4b36-8f34-2f62148 …
=> read reciepts: Use em for row height and modal width.

web/src/navbar_alerts.ts
This PR ensures that the timezone update banner is closed after the user either accepts or declines to update the timezone.
Fixes: [#33313](https://github.com/zulip/zulip/issues/33313).
[CZO thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/time.20zone.20banner.20advancement/near/2073700). 
- Accept to update timezone.
| Before | After | 
| ![accept before](https://github.com/user-attachments/assets/627cfffa-2764-473a-91e5-7f6afb60cbd2) | ![accept after](https://github.com/user-attachments/assets/fe5595e0-dcad-4c57-8243-26e0b8cad7e7) |
- Decline to update timezone.
| Before | After | 
| ![decline before](https://github.com/user-attachments/assets/cabb6646-0999-45dc-a3fe-c94b90e4ed2a) | ![decline …
=> banners: Close the timezone update banner after the user selects an option.

web/styles/left_sidebar.css, web/templates/left_sidebar.hbs
This commit updates the styling of "Log in to browse more channels" link in the left sidebar for logged out users to match "BROWSE N MORE CHANNELS" link. If the text exceeds the width of container, it'll be wrapped to the next line.
Fixes: #33108
The icon looks a bit of the vertical alignment, this problem is being addressed by [#32969](https://github.com/zulip/zulip/issues/32969)
|            |Light Theme|Dark Theme|
|----------|------------------|------------------|
|**B<br>E<br>F<br>O<br>R<br>E**|![image](https://github.com/user-attachments/assets/27d17b20-69dc-4da1-bda0-bb7de8195153)|![image](https://github.com/user-attachments/assets/2087fdf2-057a-4d71-83ed-57f41bf0b6ca)|
|**A<br>F<br>T<br>E<br>R**|![image](https://github.com/user-attachments/asset …
=> left sidebar (display): Restyle log-in link to match browse channels.

web/styles/zulip.css
There's a jump when the central panel becomes fixed width, which I showed Alya already and we both feel okay about it.
---
12px, 14px, 16px, 20px
(I realized near the end of recording these that exporting to a video might be better so you can pause. Let me know if you want me to rerecord them and to that)
| --- | --- |
|  ![Kapture 2025-02-06 at 13 56 30](https://github.com/user-attachments/assets/3bf81add-a05b-4b1c-b95f-33b69ca6dd71) | ![Kapture 2025-02-06 at 13 49 04](https://github.com/user-attachments/assets/ceb893bc-531d-461b-a4be-b11cc490d8d2) |
| ![Kapture 2025-02-06 at 13 53 49](https://github.com/user-attachments/assets/d0f67ff4-727a-4b3c-8e9a-27d2cefe75ee) | ![Kapture 2025-02-06 at 13 47 16](https://github.com/user-attachments/assets/536c433a-8421-4927-9a1b-579 …
=> empty feed: Increase line-height and use em for width.

web/styles/subscriptions.css
before and after at 12px, 14px, 16px, 20px:
| ---- | --- |
| ![Screen Shot 2025-02-05 at 21 23 24](https://github.com/user-attachments/assets/3fa81ff6-7ebf-4b6b-8501-0224a3a697e5) | ![Screen Shot 2025-02-05 at 21 22 43](https://github.com/user-attachments/assets/565e2f7f-0d54-4438-9719-ad2bd29bb6d3) |
| ![Screen Shot 2025-02-05 at 21 23 33](https://github.com/user-attachments/assets/47b7bcf8-9542-43e0-bad5-db00143d8323) | ![Screen Shot 2025-02-05 at 21 22 27](https://github.com/user-attachments/assets/76dd8335-5858-42b2-848e-96f383e409c3) |
| ![Screen Shot 2025-02-05 at 21 23 40](https://github.com/user-attachments/assets/5efaebc9-7099-4089-9a7c-62ee6472f454) | ![Screen Shot 2025-02-05 at 21 22 20](https://github.com/user-attachments/assets/60dd91a8-9e51-4f5f-ab76-230ca9 …
=> subscriptions: Use em to center permissions radio buttons.

web/src/narrow_state.ts, web/tests/narrow_state.test.cjs
This commit excludes terms containing the `with` operator from the search terms, since `with` operator is not a search operator.
This commit contains cherry-picked changes from https://github.com/zulip/zulip/pull/31152#discussion_r1945775063
<details>
</details>
=> search: Exclude `with` operator terms from search terms.

web/styles/message_header.css
Followup to https://github.com/zulip/zulip/pull/32933#discussion_r1910137015
Discussion here:
https://chat.zulip.org/#narrow/channel/6-frontend/topic/info.20density.20with.20em.20font.20size/near/2037799
Previously this value was 28px, and I accidentally converted it to 2em because I assumed 14px font size. But the font size is actually 15px and the em value should be reflected accordingly.
---
=> message_header: Fix em height calculation given larger font-size.

web/src/left_sidebar_tooltips.ts, web/src/topic_popover.ts, web/styles/recent_view.css, web/templates/recent_view_row.hbs
This helps us include topic summary feature in recent view.
[Screencast from 2025-02-07 19-53-15.webm](https://github.com/user-attachments/assets/3f53cd8d-231b-44fb-846d-392c8f1c0a74)
Things tested:
* Enter keypress/ click  to open popover works
* Topic visibility icon changes to vertical ellipsis on hover
* Focus is correctly propageted when using via keyboard to different popovers and modals.
* All the options in the topic popover work as expected
=> recent_view: Show topic menu instead of topic visibility popover.

web/styles/search.css
This was introduced in 325ab83edb78db5fc1609238141f261794b4c670 and should have only been applied to the expanded search bar.
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/narrow.20search.20bar.20hover.20behavior/near/2066736)
| --- | --- |
| <img width="595" alt="image" src="https://github.com/user-attachments/assets/4541f45b-61b3-4bbb-bc96-da190798de7c" />| ![Kapture 2025-02-07 at 13 42 39](https://github.com/user-attachments/assets/2d3ae4ad-6176-4be4-881a-6d5d90af2024)|
| no issue in dark mode before | ![Kapture 2025-02-07 at 13 41 14](https://github.com/user-attachments/assets/a595a398-90ea-45b2-9bc8-2dfd488a6123)|
=> search: Fix bug where narrow screen closed search had background color.

web/styles/rendered_markdown.css
It makes it easy to determine whether you are dragging
the scrollbar or selecting text from the editing area.
Fixes: #33253.
| Before  | After  |
|---------|--------|
| ![before](https://github.com/user-attachments/assets/dcd5cf15-772f-4a5a-8ae2-0f25fbea959a) | ![after](https://github.com/user-attachments/assets/c3cce0be-0705-4c69-ae53-e0614620fe23)
=> edit_message: Remove `cursor:text` from scrollbar thumb.

web/src/topic_list_data.ts
[CZO bug report](https://chat.zulip.org/#narrow/channel/9-issues/topic/general.20chat.20topic.20not.20shown.20in.20left.20sidebar.20when.20empty/near/2082985):
> Normally, when you go to an empty topic (with no messages yet), we show it in the left sidebar. This doesn't seem to work for test general chat yet.
<details>
</details>
=> topic_list: Show empty string topic when narrowed to empty topic.

web/src/dropdown_widget.ts
Using "Enter" key to click on "Create a new saved snippet" button does not work when the dropdown list is empty. This commit fixes that bug.
<details>
</details>
=> saved_snippets: Fix Enter click on "Create a new saved snippet" button.

web/src/bootstrap_typeahead.ts, web/src/composebox_typeahead.ts
Fixes : https://github.com/zulip/zulip/pull/32217#discussion_r1934905517.
=> composebox_typeahead: Reduce Escape induced select calls in typeahead.

web/styles/subscriptions.css
| before | after | 
| --- | --- |
| ![Screen Shot 2025-02-09 at 14 56 33](https://github.com/user-attachments/assets/de168e9e-d019-4027-8edd-730eae3c4f10) | ![Screen Shot 2025-02-09 at 14 56 03](https://github.com/user-attachments/assets/cb9cf5f3-fad5-4656-a17b-a63f6c58d98e) | 
| ![Screen Shot 2025-02-09 at 14 56 43](https://github.com/user-attachments/assets/2e367fc5-85b5-4be9-bb5a-fdd09aa01017) | ![Screen Shot 2025-02-09 at 14 56 03](https://github.com/user-attachments/assets/b7c9c260-a1dd-43fc-bef4-12af9d275523) | 
| ![Screen Shot 2025-02-09 at 14 56 51](https://github.com/user-attachments/assets/a58174fe-9511-42ae-bb07-76d2592ea735) | ![Screen Shot 2025-02-09 at 14 56 03](https://github.com/user-attachments/assets/9324bc3f-0b63-43c5-8013-31eb0 …
=> subscription settings: Use em for width and height of channel color.

web/styles/inbox.css
I left the hover styling for now, partially because it's easier to see the space it takes up, but I think it's likely we'll want to remove it.
| --- | --- |
| ![Screen Shot 2025-02-09 at 14 28 30](https://github.com/user-attachments/assets/760003b9-fadc-44b4-90d1-f68dcfd46d05) | ![Screen Shot 2025-02-09 at 14 22 46](https://github.com/user-attachments/assets/2932b3b4-57a9-4a76-a822-3ea1c6f6356e) |
| ![Screen Shot 2025-02-09 at 14 28 14](https://github.com/user-attachments/assets/1b7bee4e-7ebe-4738-9e41-cdbb8e1db1e3) | ![Screen Shot 2025-02-09 at 14 23 04](https://github.com/user-attachments/assets/6174c3f6-f26e-4441-8084-0275f4ae3be1) |
| ![Screen Shot 2025-02-09 at 14 28 …
=> inbox: Position search clear button with em.

web/styles/subscriptions.css
Fixes #29514 by having separate styling for narrower screens where the buttons don't all fit, and adjusting the height of the stream list based on which state (one row header or two row header) is being displayed.
<details>
<summary>breakpoint screenshots</summary>
12px:
14px
16px
20px (only has the two-row header)
</details>
<details>
<summary>screenshots of stream list scrolled to the bottom</summary>
12px
14px
16px
20px (only has the two-row header)
</details>
=> settings: Collapse header into two rows at narrower screens.

zerver/openapi/zulip.yaml
[CZO suggestion by Greg:](https://chat.zulip.org/#narrow/channel/412-api-documentation/topic/.28realm_.29mandatory_topics.20behavior/near/2079225)
> I'd say "the value of realm_empty_topic_display_name" (like in the paragraph above it) — otherwise it's a bit ambiguous whether the forbidden value is the string "realm_empty_topic_display_name" itself.
Ideally, we should have made this change in #33355 itself, but it was merged overnight :)
---
---
<details> …
=> api_docs: Improve docs related to mandatory topics.

web/styles/rendered_markdown.css
[CZO conversation](https://chat.zulip.org/#narrow/channel/9-issues/topic/large.20numbered.20lists/near/2086330)
| --- | --- |
| ![Screen Shot 2025-02-11 at 19 32 26](https://github.com/user-attachments/assets/949a4795-31bb-4825-9fb5-53992c3e19be) | ![Screen Shot 2025-02-11 at 19 30 43](https://github.com/user-attachments/assets/8c8ea4cb-3a04-4bd0-877d-10f6d325bdfe) |
| ![Screen Shot 2025-02-11 at 19 31 57](https://github.com/user-attachments/assets/695ea8ce-4e94-4f76-a601-9685a9f4c6ba) | ![Screen Shot 2025-02-11 at 19 30 57](https://github.com/user-attachments/assets/6af0be56-e784-4e33-ac55-1a6775a28430) |
| ![Screen Shot 2025-02-11 at 19 31 50](https://github.com/user-attachments/assets/34a79a78-02a7-4ca6-9a9f-77e98e571025) | …
=> markdown: Use em for left-margin of numbered lists.

web/src/postprocess_content.ts, web/styles/rendered_markdown.css, web/tests/postprocess_content.test.cjs
This PR uses some knuckle-draggy JavaScript to calculate the length of the largest counter in a list, and uses `ch`-based offsets to ensure the characters are visible.
This should handle counters up to `999999.`. If we wanted to get fancier, we could use a `.counter-length-max` class and set `list-style-position` to `inside` for counters of `1000000`+, but that seems like a highlighly improbably edge case.
Additionally, [`margin-inline-start`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start) is used to replace some previous class-based logic for handling i18n.
[CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/large.20numbered.20lists/near/2086330)
Fixes: #33424 
| --- | --- |
| …
=> rendered_markdown: Improve presentation of ordered-list counters.

web/styles/right_sidebar.css
| -- | -- |
| <img width="263" alt="image" src="https://github.com/user-attachments/assets/f17bc5e3-75d9-4c7a-9981-c22bf9279b60" /> | <img width="264" alt="image" src="https://github.com/user-attachments/assets/79e040e6-a3d3-4cd4-8e60-1ebffc63316c" /> |
| <img width="253" alt="image" src="https://github.com/user-attachments/assets/bf8bfd07-c049-481e-ae93-87d221dbaf31" /> | <img width="264" alt="image" src="https://github.com/user-attachments/assets/f78d001b-7943-4cf5-b61c-a2ed7d2689bd" /> |
| <img width="253" alt="image" src="https://github.com/user-attachments/assets/d9d6e445-5b97-4be0-9c89-71c797dfde01" /> | <img width="253" alt="image" src="https://github.com/user-attachments/assets/2f929666-8d88-45ec-8f71-3d1e6ee55693" /> | …
=> right_sidebar: Use em for triple dot menu size.

web/styles/app_components.css
I didn't put in much effort to find all the other relevant banners for this style:
```
.upgrade-tip,
.upgrade-or-sponsorship-tip,
.tip,
.invite-stream-notice
```
There are a lot of them, especially for `tip`, so if we want to be more careful then I can make this PR change just for the settings modal, and update other ones as we see them. But I just saw a `tip` in "Default user settings" that definitely benefits from this PR.
---
before and after at 12px, 14px, 16px, 20px:
| --- | ---- |
| ![Screen Shot 2025-02-11 at 20 16 12](https://github.com/user-attachments/assets/27ae61e5-c737-40c0-a87a-244287e43fb7) | ![Screen Shot 2025-02-11 at 20 14 38](https://github.com/user-attachments/assets/053fa034-6d8f-4c4c-91a4-d1f333f2cbc4) | 
| ![Screen Shot 2025-02-11 at 20 16 …
=> banners: Use em for font size.

templates/zerver/invalid_realm.html, templates/zerver/portico-header.html, zerver/tests/test_auth_backends.py, zerver/views/auth.py
| --- | --- |
| ![Screenshot from 2025-02-07 10-45-02](https://github.com/user-attachments/assets/e758d246-e85a-412e-9986-f7250bbf07c2) | ![image](https://github.com/user-attachments/assets/8cda51ef-696a-4571-898b-e55f8dbde275) |
On visiting the login page:
I added the last line for `selfhosting` subdomain in the above screenshot.
I think the first commit is enough to fix the issue. We could add similar check for password reset or other pages but now that we have removed the login button in the first commit, user is unlikely to get to other pages.
=> Fix 500 errors on user trying to access selfhosting login pages.

web/styles/message_row.css
This creates a more flexible action-button area in the message grid, and reduces some unnecessary complexity that was introduced previously by the fact that the edit icon, when present, isn't known until hover. That has been fixed here by just reserving the em-based equivalent width for the button, allowing other instances of the action button grid (especially in archived channels and narrow viewports) to not need a special grid definition.
(The previous CSS comment about height and the height property have not mattered since the gridded rewrite of the message box, but the selector came in handy here.)
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/spacing.20around.20message.20action.20buttons.20in.20archived.20channels/near/2068327) …
=> message_row: Refine grid for better-fitting action icons.

web/src/bot_data.ts, web/src/people.ts, web/src/settings_data.ts, web/src/stream_data.ts, web/src/stream_edit.ts, web/src/tippyjs.ts, web/src/user_profile.ts, web/styles/subscriptions.css, web/templates/stream_settings/copy_email_address_modal.hbs, web/templates/stream_settings/stream_settings.hbs, web/tests/bot_data.test.cjs, web/tests/people.test.cjs, web/tests/stream_data.test.cjs
* Disable "Generate email address" button with a tooltip when neither the current user nor any of the bots they control has the post message permission.
* Updated UI to configure "Sender"
Fixes #31566
---
* When the modal is opened, we show the email address for 'Email gateway' bot (default).
* The copy icon is now present alongside the address (see above image), it's a common UX so shouldn't be confusing ?
* When another sender is selected, we clear the address, disable the checkboxes, and focus on the "Generate email address" button to convey what should be done. See image below:
<details> …
=> Make sender configurable when generating channel email address

api_docs/changelog.md, api_docs/include/rest-endpoints.md, tools/check-schemas, version.py, web/shared/src/typing_status.ts, web/src/message_edit.ts, web/src/message_list_view.ts, web/src/server_events_dispatch.js, web/src/typing.ts, web/src/typing_data.ts, web/src/typing_events.ts, web/styles/message_row.css, web/templates/edited_notice.hbs, web/templates/editing_notifications.hbs, web/tests/dispatch.test.cjs, web/tests/lib/events.cjs, web/tests/typing_data.test.cjs, web/tests/typing_status.test.cjs, zerver/actions/typing.py, zerver/lib/event_schema.py, zerver/lib/event_types.py, zerver/lib/events.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_events.py, zerver/tests/test_typing.py, zerver/views/typing.py, zproject/urls.py
This PR adds typing indicators for message editing in stream as well as in dm, if the send typing notification for corresponding is enabled.
Referenced PR: #28585.
Fixes #25719.
API Design thread: https://chat.zulip.org/#narrow/stream/378-api-design/topic/typing.20notifications.20for.20editing.20messages/near/1720430
[CZO thread](https://chat.zulip.org/#narrow/channel/101-design/topic/typing.20notifications.20for.20editing.3F/near/2026990)
<details><summary>Intended behavior when the message list views of the sender and receiver user are same</summary>
<p>
https://github.com/user-attachments/assets/4bf301c8-693a-4f17-a810-f9f0eb86db71
https://github.com/user-attachments/assets/16665899-499d-42b4-b556-fe1f3f8a0f25
</p>
</details> …
=> message_edit: Show typing indicator for message editing.

web/styles/app_variables.css, web/styles/subscriptions.css, web/templates/stream_settings/stream_settings_overlay.hbs, web/templates/user_group_settings/user_group_settings_overlay.hbs
<details>
<summary>screenshots for stream setting UI</summary>
before and after at 12px, 14px, 16px, and 20px
| ---- | ---- |
| ![Screen Shot 2025-01-29 at 15 58 06](https://github.com/user-attachments/assets/68c2354a-261e-42ab-800d-baa79dc8424e) | ![Screen Shot 2025-01-29 at 15 56 42](https://github.com/user-attachments/assets/142d1c2f-f739-4fc0-802d-1ee34eb67910) |
| ![Screen Shot 2025-01-29 at 15 58 15](https://github.com/user-attachments/assets/98bd1377-2e6f-4019-b6cd-5bcb281a468d) | ![Screen Shot 2025-01-29 at 15 56 15](https://github.com/user-attachments/assets/c3db9c05-7cdf-4341-8602-985950ba94fc) |
| ![Screen Shot 2025-01-29 at 15 58 29](https://github.com/user-attachments/assets/de0d6428-8540-474f-a83f-65a52d2f6b0e) | ![Screen Shot 2025-01-29 at 15 56 …
=> settings: Scale plus button in stream and user group setting UI.

web/src/attachments_ui.ts, web/templates/settings/upgrade_tip_widget.hbs
This pull request addresses issue #20630 by:  
- Hiding upgrade-related links and storage stats for **guest users** to prevent unnecessary UI elements and potential 404 errors.  
- Removing the upgrade link code from `organization_profile_admin`, `organization_settings`, and `organization_permission_admin`, ensuring guests do not see upgrade options.  
- Removing the `% used` banner for uploaded files, which previously routed to `/upgrade/`, to prevent guests from encountering upgrade-related navigation.  
- Updating `admin.ts` to include `realm_plan_type` for better handling of organization settings, ensuring the UI correctly reflects user roles, including guests.  
- Verified that **guest users** no longer see upgrade-related links in the organization settings.  
- Checked that the …
=> settings: Hide upgrade links and storage stats for guests. 

web/shared/src/internal_url.ts, web/src/hash_util.ts, web/src/inbox_ui.ts, web/src/recent_view_ui.ts, web/src/stream_list.ts, web/src/stream_topic_history.ts, web/src/topic_list_data.ts, web/src/ui_init.js, web/tests/internal_url.test.cjs, web/tests/recent_view.test.cjs, web/tests/stream_topic_history.test.cjs, web/tests/topic_list_data.test.cjs
This commit updates the topic links obtained from clicking the topics in the left sidebar, recent view and inbox, and those obtained from "Copy link to topic" to use the new topic permalinks.
Fixes part of #21505
Cherry-picked from #30644
<details>
</details>
=> topics: Change topic links of left sidebar to use new permalinks.

web/src/stream_settings_ui.ts
Fixes
https://chat.zulip.org/#narrow/channel/9-issues/topic/.22Add.22.20button.20gives.20channel.20created.20modal
<details>
</details>
=> stream: Reset created stream early when not subscribed to it.

web/styles/inbox.css
I tried to keep 16px as the default proportions, since it seemed like Inbox View was built with 16px default (it at least looked better to me) -- let me know if I should change to 14px default.
I also wasn't sure how to align the icon and text in the headers. They ended up moving a bit left. I can put in more effort to have it not change at all at 16px but didn't end up getting to that tonight, so let me know if that's preferred or if I should aim for something different.
---
before and 12px, 14px, 16px, 20px
| --- | --- |
| ![Screen Shot 2025-02-11 at 22 39 41](https://github.com/user-attachments/assets/5a150eb1-7737-4e1e-bbdc-420ff8a10c8f) | ![Screen Shot 2025-02-13 at 00 06 09](https://github.com/user-attachments/assets/eba1f705-1cd1-4ab9-a708-0d09fa665587) |
| …
=> inbox: Use em for more spacing measurements.

web/styles/rendered_markdown.css
This is a regrettable adjustment, presented as a necessary follow-up to #33438, for how certain browsers (especially Safari on both iOS and macOS) present a larger, non-adjustable gap between the list marker and the list item's text.
Although this solves the immediate, unacceptable problem of counters ending up cut off, I plan to return to this problem after 10.0 to see if a more uniform list presentation is possible (e.g., by setting up a custom counter).
| Safari, before | Safari, after |
| --- | --- |
| ![safari-markers-before](https://github.com/user-attachments/assets/50c570f6-aa90-4659-ab4e-db54fd05868c) | ![safari-markers-after](https://github.com/user-attachments/assets/30dbd2a6-0abe-43d7-8362-57a89fa38567) |
| Firefox, before | Firefox, after …
=> rendered_markdown: Bump margin by half a character on ordered lists.

web/src/linkifiers.ts, web/src/settings_linkifiers.ts
[CZO discussion thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20linkifier.20validation.20in.20web.20app)
This PR adds frontend validation for custom linkifiers using `python_to_js_linkifier`. Previously, users could submit a linkifier that would be supported by the server but not by the web-app. This resulted in `BlueslipError: python_to_js_linkifier failure!`
**Changes**:
- Exported `python_to_js_linkifier` from `linkifiers.ts`.
- Added validation in `settings_linkifiers.ts` using a try-catch block.
- Displayed error message when validation fails, preventing invalid submissions.
Fixes #33238: Candidate linkifiers are now being validated locally before being sent to the server …
=> Frontend validation for custom linkifiers before being sent to the server

scripts/lib/install, zerver/management/commands/register_server.py, zerver/tests/test_home.py, zerver/views/home.py
With the exception of /registration-transfer, the /stable/ docs have the relevant sections - so that's the better choice to link to.
=> docs: Change /doc-permalinks/ redirects to point to /stable/ RTD.

api_docs/changelog.md, zerver/openapi/zulip.yaml
Updates API documentation for changes discussed here on CZO: https://chat.zulip.org/#narrow/channel/378-api-design/topic/Automatically.20detect.20user's.20timezone/near/2054874.
**Notes**:
- Refers to the `timezone` user setting as the "profile time zone" to help clarify that this user setting is used for displaying the user's local time to other users
- Adds links to the help center article about this user setting: https://zulip.com/help/change-your-timezone.
- More consistently notes the format of the string that's being returned is an IANA identifer of the time zone.
- For the feature level 329 changes:
- Clarifies that the alert is shown when the time displayed for the users's "profile time zone" setting differs from the current time displayed by the time zone configured on the user's …
=> api-docs: Updates documentation for user settings related to time zones.

web/styles/modal.css, web/styles/zulip.css
This will become more important with larger font sizes, which we're adding soon. The max-width will prevent the width from becoming too wide.
This affects several modals, but just showing the move message modal for an example of the changes (at 12px, 14px, 16px, 20px)
| ----- | -----|
| ![Screen Shot 2025-02-01 at 15 50 19](https://github.com/user-attachments/assets/f69448f3-72af-411d-87ac-8d2fdc22341d) | ![Screen Shot 2025-02-01 at 15 44 41](https://github.com/user-attachments/assets/d305a3b6-295b-4244-bd6a-b6400df6e185) |
| ![Screen Shot 2025-02-01 at 15 49 55](https://github.com/user-attachments/assets/fe82df37-1528-478a-b2ce-d07929e87ff6) | ![Screen Shot 2025-02-01 at 15 45 12](https://github.com/user-attachments/assets/efbdef99-d1e1-48e9-939b-2464653ebff2) |
| …
=> modal: Scale width with app font size.

web/styles/app_components.css, web/styles/app_variables.css, web/styles/modal.css, web/styles/settings.css, web/styles/subscriptions.css
This covers a lot of ground and applies to every modal in the app with inputs or dropdowns (which is many of them). It seems like too much to take screenshots of every modal screen at 4 font-sizes before and after, but I do think it would be good to do thorough manual testing. Maybe Alya you can let me know which screenshots would be helpful for you?
Modals I've looked at:
* Personal settings, all tabs
* "Add bot" modal
* "Add a new alert word" modal
* Org settings
* "Add a new emoji"
* Manage User
* Manage bot 
* Add a new custom profile field
* Add default channels
* Create a channel
* Move messages
* Polls
* User group settings
* Invite Users
Things I want to change:
Things of note:
(1) I made the jitsi indented dropdown less wide to line up on the right. Let me know if you'd prefer it …
=> modals: Standardize width and height of input and dropdowns.

templates/corporate/development-community.md
- More clear subsection structure and headings.
- Bold to highlight key points.
- Tighten wording of individual points.
- Link to more resources.
[CZO discussion
](https://chat.zulip.org/#narrow/channel/2-general/topic/automated.20response.20bot/with/2089922)
Current: https://zulip.com/development-community/
<details>
<summary>
Updated screenshots
</summary>
</details>
=> portico: Make community norms section easier to follow.

web/src/message_edit_history.ts, web/src/message_list_view.ts
Commit 1: When a message was moved from an empty string topic to another topic, the "Moved" notice beside sender name in the message body was missing.
Commit 2: Buggy message edit history rendered.
<details>
</details>
=> edited_notice: Fix missing "Moved" notice.

web/src/message_edit.ts, web/src/stream_popover.ts, web/styles/zulip.css, web/templates/move_topic_to_stream.hbs, web/templates/topic_edit_form.hbs
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/general.20chat.20.2F.20default.20topic/near/2090500)
> I guess the move topic modal's placeholder doesn't use italics; presumably we can copy the compose box implementation for it.
> When mandatory_topics = false, I think we should always show "test general chat" as the placeholder in the move topic modal.
Also, improved the "inline topic edit form".
<details> …
=> topic_edit: Show "general chat" placeholder when mandatory_topics=false.

web/styles/settings.css, web/templates/settings/active_user_list_admin.hbs, web/templates/settings/attachments_settings.hbs, web/templates/settings/bot_list_admin.hbs, web/templates/settings/data_exports_admin.hbs, web/templates/settings/deactivated_users_admin.hbs, web/templates/settings/default_streams_list_admin.hbs, web/templates/settings/emoji_settings_admin.hbs, web/templates/settings/invites_list_admin.hbs, web/templates/settings/linkifier_settings_admin.hbs, web/templates/settings/muted_users_settings.hbs, web/templates/settings/playground_settings_admin.hbs, web/templates/settings/user_topics_settings.hbs, web/templates/stream_settings/stream_members.hbs, web/templates/user_group_settings/user_group_members.hbs
Commit 1:
There are cases where the placeholder text overflows outside of the input box. In the settings panels, all these filter boxes are on the same row as a subheading on the left side. So the x in `Filter x` is usually the subheading title, making it redundant to mention the x part. We have not modified the aria-labels since it might still be helpful for assistive technologies to have the whole `Filter x` part.
[CZO thread](https://chat.zulip.org/#narrow/channel/101-design/topic/setting.20filter.20width)
Commit 2:
By removing an explicit height, we let the font-size, padding and line-height decide the height, which will vary based on font-size. We had to set line-height explicitly to 1.25em = 20px at 16px/1em since dropdown's height within the header was somehow 0.5px more than the …
=> Setting filters

web/src/compose_actions.ts, web/src/dropdown_widget.ts, web/src/saved_snippets_ui.ts, web/src/ui_init.js, web/tests/compose_actions.test.cjs
1. Moves initialization of `saved_snippets.ts` directly to ui_init.ts and defers saved snippets dropdown creation until the compose box is opened for better performance.
2. Fix dropdown state sync across browser tabs.
Fixes: #31831
<details>
</details>
=> saved_snippets: Move initialization directly to ui_init.ts

.codespellignore, requirements/common.in, requirements/dev.txt, requirements/prod.txt, version.py, zerver/tests/test_tornado.py, zerver/tornado/handlers.py
Required for Django 5.1. I’m not sure how much I trust this. Let’s give it some time to bake on chat.zulip.org.
=> requirements: Upgrade asgiref

web/styles/compose.css
before and after at 12px 14px 16px 20px --- screenshots with the hover style on to show the padding
| --- | --- |
| ![Screen Shot 2025-02-13 at 22 24 15](https://github.com/user-attachments/assets/582c7453-3aa3-4f13-92af-4f539e4d1f48) | ![Screen Shot 2025-02-13 at 22 28 49](https://github.com/user-attachments/assets/c7393a2f-eedf-4dca-9b30-17be9c6483f9) |
| ![Screen Shot 2025-02-13 at 22 24 25](https://github.com/user-attachments/assets/05cfa77f-2a3c-449c-9da6-134cbd8d73c4) | ![Screen Shot 2025-02-13 at 22 29 16](https://github.com/user-attachments/assets/acd7148b-bd93-4167-8b72-64a6288f2d93) |
| ![Screen Shot 2025-02-13 at 22 24 34](https://github.com/user-attachments/assets/10566c27-b43e-4439-990d-b785ae3bcb0b) | ![Screen Shot 2025-02-13 at 22 29 …
=> compose: Scale close button with font size.

web/src/compose_notifications.ts, web/src/inbox_ui.ts, web/src/message_edit.ts, web/src/narrow_banner.ts, web/src/narrow_error.ts, web/templates/compose_banner/compose_banner.hbs, web/templates/empty_feed_notice.hbs
Fixed the following bugs:
* Mark *test general chat* as read was buggy.
* Unmuting *test general chat* via unmute banner was broke.
* Buggy `stream_and_topic_exist_in_edit_history`
* Buggy empty feed notice when *test general chat* involved.
<details>
</details>
=> Empty string topic related bugs.

corporate/migrations/0001_squashed_0044_convert_ids_to_bigints.py, corporate/migrations/0018_customer_cloud_xor_self_hosted.py, corporate/migrations/0020_add_remote_realm_customers.py, corporate/models.py, requirements/common.in, requirements/dev.txt, requirements/prod.txt, version.py
- Requires #33299.
- [Django 5.1 release notes](https://docs.djangoproject.com/en/5.1/releases/5.1/).
- We already desupported Python 3.9 in #29458.
- We already desupported PostgreSQL 12 in #32207.
=> requirements: Upgrade Django from 5.0.10 to 5.1.6

zerver/lib/user_groups.py, zerver/tests/test_realm.py, zerver/tests/test_subs.py, zerver/tests/test_user_groups.py, zerver/views/realm.py, zerver/views/streams.py, zerver/views/user_groups.py
If empty anonymous group is passed for a setting value in an API request, the setting is set to "Nobody" group.
<details>
</details>
=> settings: Correctly handle passing empty anonymous group.

web/styles/compose.css
Before and after at 12px, 14px, 16px, 20px. The movement in the background is unrelated to this PR, I just forgot to do a full refresh before taking some of the screenshots. I can retake them if desired.
| --- | --- |
| ![Screen Shot 2025-02-18 at 11 45 07](https://github.com/user-attachments/assets/c3b90ea5-e6f7-454a-99ef-94cb10424752) | ![Screen Shot 2025-02-18 at 11 41 53](https://github.com/user-attachments/assets/1bbf0140-e435-4eb2-8cd5-e205083343b1) |
| ![Screen Shot 2025-02-18 at 11 43 44](https://github.com/user-attachments/assets/74b9381a-46b6-469d-9ef2-435e078acccf) | ![Screen Shot 2025-02-18 at 11 41 40](https://github.com/user-attachments/assets/a68e3ef3-944f-4ff0-a13d-9f3100d91007) |
| ![Screen Shot 2025-02-18 at 11 43 …
=> compose: Use em for sizing and position of stream typeahead icon.

web/src/stream_data.ts, web/tests/lib/example_settings.cjs, web/tests/peer_data.test.cjs, web/tests/stream_data.test.cjs
Before this, we were using `is_user_in_setting_group` which does not do the extra checks around a guest user's permissions (and in future, some other checks).
We introduced `initialize_and_override_current_user` in stream_data test to make it easier to set current_user.user_id.
<details>
</details>
=> stream_data: Use user_has_permission_for_group_setting.

web/styles/typeahead.css
This is a quicker fix for the sake of info density consistency. Later we'll hopefully convert these styles to grid.
There's still a slight visual issue with the icon and text moving a bit left when the text overflows. This was already an issue at 14px before this PR. I haven't figured this out yet and am not sure if it should be a blocker, since this is a low-visibility area and this PR is definitely an improvement.
Before and after at 12px, 14px, 16px, 20px:
| --- | --- |
| ![Screen Shot 2025-02-16 at 20 29 38](https://github.com/user-attachments/assets/b1dc6d8d-0eef-4be6-b65e-17d213cd6ffa) | ![Screen Shot 2025-02-16 at 20 30 27](https://github.com/user-attachments/assets/d9c951dd-4869-475f-ae13-718db7fba438) |
| ![Screen Shot 2025-02-16 at 20 29 …
=> typeahead: Use em for image placement.

zerver/migrations/0672_fix_attachment_realm.py
Old messages with attachments, sent by cross-realm bots, didn't have
the realm set correctly to the target realm, this migration fixes it
by looking at the messages linking to the attachment and setting the realm
based on the recipient.
This is the migration follow-up to
410281624098f56ff9a67c8c17aca205487d59bf
=> migrations: Add migration fixing realm of Attachments.

web/styles/typeahead.css, web/templates/typeahead_list_item.hbs
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20extraneous.20comma.20after.20pronouns/with/2088251.
|       ![image](https://github.com/user-attachments/assets/470b8487-02e7-4ff3-b8b1-1e426373b2a9)          |  ![image](https://github.com/user-attachments/assets/a08e27a7-a881-4125-aa3a-a5c23a924a1b)|
| ![image](https://github.com/user-attachments/assets/6341b084-dff4-4704-bfed-6d11445ed4e4) |![image](https://github.com/user-attachments/assets/86d21715-a360-430b-8c93-4c87cdb79041)
(stays the same, as expected)
| case1 | case2 | case3 |
|--------|-------|-------|
|![image](https://github.com/user-attachments/assets/d688e55d-cacb-471a-8cc9-5e4bf820c177) | …
=> composebox_typeahead: Update order of user typeahead elements.

web/src/typeahead_helper.ts, web/templates/typeahead_list_item.hbs
|![image](https://github.com/user-attachments/assets/80cdb72d-e91c-40b0-8f70-d1b73cd1e187)   | ![image](https://github.com/user-attachments/assets/c0f978aa-3880-4036-b9cd-1f303ee15ef0) |
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20extraneous.20comma.20after.20pronouns/with/2088251
=> composebox_typeahead: Remove extra comma in user mentions.

web/styles/compose.css
This was removed in 609106e2d0958903c57761620293782aa5ec1d23 but the CSS was still there, unused.
=> compose: Remove stale classname: compose_draft_button.

web/src/message_notifications.ts
This PR adds support to display `realm_empty_topic_display_name` value for empty string topic in the desktop notification.
<details>
</details>
=> desktop_notification: Add support for empty string topic.

web/styles/settings.css, web/templates/user_group_settings/new_user_group_subgroup.hbs, web/templates/user_group_settings/user_group_subgroup_entry.hbs
Commit 1:
- Removed the hard coded `colspan="2"` because of which the bug is encountering as it is always taking space of 2 columns even if the email column is hidden on small screens.
- Added a new table data `empty-email-col-for-user-group` and toggling its display property using media queries to fit on every screen.
Commit 2:
- While fixing the above bug, I found that on small screens, `settings-email-column` is set to `display: none`, while `hidden-subscriber-email` remains visible, breaking compatibility on small screens.  
- In this commit, I added the `display: none` property to `hidden-subscriber-email` when `settings-email-column` is set to `display: none`.
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.9B.A0.EF.B8.8F.20misaligned.20button.20in.20user.20 …
=> user_groups_setting: Fix the style related bugs in the user groups member settings.

web/src/postprocess_content.ts
This PR fixes a bug where animated images automatically play on Firefox because the image source didn't output the same URL across different browsers. Currently, the image source is normalized to ensure consistent URLs across different browsers.
Fixes: #33248
| --- | --- |
| [Before.webm](https://github.com/user-attachments/assets/a13fa845-8bfc-4b87-97f9-8039f8ebab78) | [After.webm](https://github.com/user-attachments/assets/b22a7069-2f60-4b4a-8c4b-5bfea4b3b3d7)| 
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/ …
=> postprocess: Fix animated images automatically playing on Firefox.

web/src/typeahead_helper.ts, web/styles/typeahead.css, web/templates/typeahead_list_item.hbs
Commit 1:
Use null check for user comma insertion.
As per https://github.com/zulip/zulip/pull/33536#discussion_r1960991985 which seems like a better fix than the
current implementation to include/exclude comma after pronouns.
Commit 2:
Adds a comment explaining the reason for setting left-margin to 0 for status-emoji typeahead item([CZO context](https://chat.zulip.org/#narrow/channel/6-frontend/topic/Removing.20extra.20space.20for.20status.20emoji.20in.20typeahead.2E/near/2095812))
=> typeahead: Use null check for user comma insertion and comment for removing margin for status emoji.

web/shared/src/typeahead.ts, web/src/settings_config.ts, web/src/typeahead_helper.ts, web/styles/typeahead.css, web/tests/composebox_typeahead.test.cjs, web/tests/typeahead_helper.test.cjs, web/tests/user_group_pill.test.cjs, web/tests/user_groups.test.cjs
- First commit is to use display name when sorting recipients in typeahead.
- Second commit is to update display name for `role:everyone` and `role:members` groups.
- Third commit is to show "role:members" group in typeahead considering both "Members" and "Everyone except guests" names.
Fixes:  https://chat.zulip.org/#narrow/channel/101-design/topic/suggesting.20.22Everyone.22.20for.20permissions.20that.20exclude.20guests.3F
<details> …
=> Update display names for `role:members` and `role:everyone` group.

analytics/management/commands/update_analytics_counts.py, zerver/lib/remote_server.py, zerver/management/commands/register_server.py, zerver/tests/test_push_notifications.py, zilencer/views.py
The motivation for the first commit is obvious, it's just adding useful logging.
Reason for the second commit (from the commit message):
--------
When these exceptions are thrown from the request-to-bouncer functions
inside of manage.py register_server/update_analytics_counts, they
shouldn't be silenced, merely calling maybe_mark_pushes_disabled in the
background.
This results in the occurrence of the error not being shown to the
user. Failure to upload analytics data when running these commands
should result in a loud, obvious error.
Failure of running register_server before this change:
```
./manage.py register_server
This command registers your server for the Mobile Push Notifications Service.
Doing so will share basic metadata with the service's maintainers:
* This server's configured …
```
=> zilencer: Log bouncer-side info when RemoteRealm creation fails.

web/styles/compose.css
at 12px, 14px, 16px, 20px
| --- | --- |
| ![Screen Shot 2025-02-18 at 15 03 49](https://github.com/user-attachments/assets/4e73eb3e-63b7-4941-9f3f-23e1d44e82c1) | ![Screen Shot 2025-02-18 at 15 02 48](https://github.com/user-attachments/assets/4173c10e-13af-44aa-bca5-3ce0175b828b) |
| ![Screen Shot 2025-02-18 at 15 03 58](https://github.com/user-attachments/assets/5ac3b0e4-93e3-4029-a704-be5da7f0d5b1) | ![Screen Shot 2025-02-18 at 15 02 32](https://github.com/user-attachments/assets/a3d68086-0a54-4c10-87b9-06f53e2ff207) |
| ![Screen Shot 2025-02-18 at 15 04 06](https://github.com/user-attachments/assets/3b424810-f559-4511-945f-552516883c12) | ![Screen Shot 2025-02-18 at 15 02 20](https://github.com/user-attachments/assets/cd34c554-50c7-46c7-87cf-aa356f1a3e77) |
| …
=> saved snippets: Use em for width, font-size, padding.

web/styles/message_row.css, web/templates/message_body.hbs
This PR is a follow-up to changes merged from #33447, which caused a readily reproducible regression where message content would reflow after leaving the locally echoed state.
Here the base message-body template includes the same `message_controls.hbs` partial when locally echoed. This appears to avoid any ill side-effects, as `echo.ts` has two functions--`show_message_failed()` and `show_failed_message_success()`--that handle message failure. When messages are sent successfully, the template re-renders with the correct (and visible on hover) buttons placed as expected.
The useful thing about this approach is that there is no need to keep a mock of the buttons in sync with those actually used. A complicated but effective CSS selector also prevents prematurely revealing the action buttons, …
=> message_row: Mock available icons to prevent post-echo reflow.

web/src/message_summary.ts
As we are rendering markdown in topic summaries, this adds the `.rendered_markdown` class to the summary modal to gain the benefits of the rendered-markdown CSS, including especially the thumbnailed treatment of images.
| --- | --- |
| ![llm-modal-before](https://github.com/user-attachments/assets/12a7cd77-a784-4585-afdd-016744d421fa) | ![llm-modal-after](https://github.com/user-attachments/assets/6d67fc50-e4fb-4fa0-b1c3-5c8536810769) |
<details> …
=> topic_summaries: Ensure modal takes rendered_markdown class.

web/src/stream_popover.ts, web/templates/move_topic_to_stream.hbs
Fixes:
https://chat.zulip.org/#narrow/channel/9-issues/topic/no.20topic.20length.20limit.20in.20move.20modal/with/2097474.
=> move_topic_to_stream: Limit topic name length in modal.

web/styles/compose.css
12px, 14px, 16px, 20px
| --- | --- |
| ![Screen Shot 2025-02-18 at 15 57 27](https://github.com/user-attachments/assets/9f9bcd22-9bc3-4c9c-8727-19a067fb3f1c) | ![Screen Shot 2025-02-18 at 15 56 51](https://github.com/user-attachments/assets/def4d56a-90a2-469a-930f-ca66eca19c49) |
| ![Screen Shot 2025-02-18 at 15 57 33](https://github.com/user-attachments/assets/7789984b-51ac-41ea-bcfa-291023d54b4c) | ![Screen Shot 2025-02-18 at 15 56 41](https://github.com/user-attachments/assets/8244b493-cb09-42ed-9ad5-43881a5400ba) |
| ![Screen Shot 2025-02-18 at 15 57 39](https://github.com/user-attachments/assets/4017f319-1e5d-4c3c-9615-0a7d99dc10df) | ![Screen Shot 2025-02-18 at 15 56 33](https://github.com/user-attachments/assets/cc1af486-2825-4fad-bf0d-d744c70b2613) |
| ![Screen …
=> compose: Use em for message-limit-indicator font size.

web/src/ui_init.js, web/styles/zulip.css
Despite the comment in `ui_init.js`, the `.default-sidebar-behaviour` class is never in fact removed, and appears only to add unnecessary complexity to certain selectors, which are here cleaned up.
This work is helpful prep for the container-query changes coming in #33249.
_There are no changes in any of the After shots:_
| Small, before | Small, after |
| --- | --- |
| ![500-before](https://github.com/user-attachments/assets/06078bfe-36e4-467c-9253-d386b9a1049d) | ![500-after](https://github.com/user-attachments/assets/905e804c-df15-490d-8cdd-a9dc1dbc1f66) |
| ![500-left-overlay-before](https://github.com/user-attachments/assets/7593636f-6faa-4601-95b4-b224270e9c75) | ![500-left-overlay-after](https://github.com/user-attachments/assets/3a487fd5-f5a0-4d …
=> sidebars: Refactor to remove .default-sidebar-behaviour.

docs/overview/changelog.md
#33338
* Added last two commits.
* Updated the third commit: Placeholder should live-update when `mandatory_topics` setting is changed.
* Minor fix in the fourth commit: `is_empty_stream_topic` -> `is_empty_string_topic`
* Pulled a commit from #33311 
* Simplified 3rd last commit. (Discussed with Karl in DM before making changes)
---
<details>
</details>
=> compose: Handle *general chat* in topic box.

web/src/settings_users.ts, web/styles/settings.css, web/templates/settings/settings_user_list_row.hbs
Remove "Loading..." text from settings page and replace it with a spinner.
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Loading.20indicator.20in.20the.20settings.2Fusers.20table.2E)
<details>
</details>
=> loading_spinner: Add loading spinner to settings page.

web/styles/subscriptions.css
I double checked things still look okay for the one-row header.
Screenshots for two-row header with right pane scrolled to the bottom, at 12px, 14px, 16px, 20px:
| --- | --- |
| ![Screen Shot 2025-02-18 at 18 00 28](https://github.com/user-attachments/assets/75488bd7-22a3-45f2-a4e8-2d4a8e0ae505) | ![Screen Shot 2025-02-18 at 18 00 41](https://github.com/user-attachments/assets/9e6bce23-7ff0-49fb-a30e-3c45fe84d259) |
| ![Screen Shot 2025-02-18 at 18 01 34](https://github.com/user-attachments/assets/6e867a1a-9997-4d8b-b288-9dd8d182cdbd) | ![Screen Shot 2025-02-18 at 18 01 43](https://github.com/user-attachments/assets/c3a9789e-0064-4566-b869-aa80e019f110) |
| ![Screen Shot 2025-02-18 at 18 02 36](https://github.com/user-attachments/assets/f47e5609-1809-4944-96e1-c16825d94e …
=> stream_settings: Fix height of right pane for two-row header.

web/src/topic_list_data.ts, web/tests/topic_list_data.test.cjs
This PR makes it possible to search for empty string topic in the left sidebar.
<details>
</details>
=> topic_list_data: Add support to filter empty string topic.

web/src/compose_setup.js
This commit solves the issue where the ResizeObserver loop completes with undelivered notifications. By using requestAnimationFrame, the resize event is deferred until after the paint cycle, preventing an infinite loop caused by consecutive resize triggers before repaint.
<details>
</details>
=> resize_observer: Prevent loop using requestAnimationFrame.

web/src/buddy_data.ts, web/src/buddy_list.ts, web/src/user_events.ts, web/styles/right_sidebar.css, web/templates/presence_row.hbs, web/tests/buddy_data.test.cjs, web/tests/user_events.test.cjs
In DMs that include a deactivated user, it shows the deactivated user with a special deactivated status icon (slashed circle) in the right sidebar. 
Currently, these users appear with no special indicator in the right sidebar.
In all other contexts, we shouldn't show deactivated users in the right sidebar.
Fixes part of #30797.
| Before  | After  |
|---------|--------|
| <img width="250" alt="Screenshot 2025-01-30 at 5 42 58 PM" src="https://github.com/user-attachments/assets/d4fecc95-2746-48b9-b8b0-6f38326a9c1b" />  | <img width="250" alt="Screenshot 2025-01-30 at 5 34 02 PM" src="https://github.com/user-attachments/assets/ec18580d-ac01-4466-9856-acae65ab0366" />  |
| <img width="249" alt="Screenshot 2025-01-30 at 5 42 48 PM" …
=> deactivated_user: Correctly display deactivated users in the right sidebar.

web/src/stream_list.ts
This PR show tooltips on channel names in the left sidebar if the channel name is too long.
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/missing.20tooltip.20on.20long.20channel.20names.20in.20left.20sidebar)
Before | After
|-------|---------|
| <img width="363" alt="Screenshot 2025-02-13 at 6 50 02 PM" src="https://github.com/user-attachments/assets/6c17fbd7-ae25-4ea4-a55f-da5efe840d06" /> | <img width="335" alt="Screenshot 2025-02-13 at 9 14 40 PM" src="https://github.com/user-attachments/assets/2100668f-235f-431a-b160-657d4522215f" /> |
<details> …
=> left_sidebar: Show tooltip only for truncated channel names.

web/src/message_notifications.ts, web/src/ui_util.ts, web/tests/ui_util.test.cjs
Through the changes in this PR, in desktop notifications, we no longer display an emoji's status code. Instead, we show the corresponding Unicode emoji to render it properly in desktop notifications. For custom emojis, we continue to display their name.
Fixes: #30598.
[CZO thread](https://chat.zulip.org/#narrow/stream/137-feedback/topic/Emoji.20in.20windows.20notification/near/1815298).
**Previous PR Reference:**
- This PR continues the work done in the PR [#30653](https://github.com/zulip/zulip/pull/30653) by @tnmkr.
- There also exists a PR [#31949](https://github.com/zulip/zulip/pull/31949) by @tony-nyagah.
- The developments made in this PR are:
- Better error handling for custom emoji and for the `String.fromCodePoint()` function.
- Added tests to verify the logic. …
=> notifications: Render emoji in desktop notifications.

zerver/management/commands/runtusd.py
Previously, tusd printed unnecessary logs on startup while running the tools/run-dev script. This commit resolves the issue by setting the verbose flag to false, which defaults to true if not specified.
The required PR adding this flag was introduced in https://github.com/tus/tusd/pull/1218.
Fixes #32301.
**This PR requires updating tusd version to https://github.com/tus/tusd/releases/tag/v2.6.0**
Related Discussions:
https://chat.zulip.org/#narrow/channel/3-backend/topic/Verbose.20tusd.20output/near/1983986
Fixes: 
<details> …
=> zerver: Remove unnecessary tusd logs during run-dev startup.

zerver/lib/onboarding.py
The left sidebar `+` is now the primary way to start a new conversation.
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/onboarding.20messages.3A.20starting.20a.20topic/with/2099476)
=> onboarding: Make new topic instructions point to left sidebar.

api_docs/changelog.md, version.py, zerver/actions/message_flags.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_flags.py, zerver/views/message_flags.py
Added `ignored_because_not_subscribed` field in the response of `/messages/flags/narrow` endpoint.
Fixes a part of #23470.
Extracted from #31535, which still needs some work on the frontend, so we can integrate the API change.
=> message_flags: Add skipped unsubscribed stream ids in the response.

web/src/message_list_tooltips.ts, web/templates/message_length_toggle.hbs
We fix tooltip being still visible once collapse / expand tooltip is visible and user changes narrow by destroying the tooltip when reference is hidden.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.22Show.20more.22.20tooltip.20doesn't.20disappear/with/2099867
=> message_length_toggle: Fix tooltip not hidden on narrow change.

tools/i18n/update-for-legacy-translations, web/src/compose_setup.js, web/src/compose_tooltips.ts, web/src/compose_validate.ts, web/styles/compose.css, web/tests/compose.test.cjs, web/tests/compose_validate.test.cjs, web/tests/lib/compose_helpers.cjs, web/tests/upload.test.cjs
Fixes: 
This commit adds some new error banners and
modifies the error message of the current private
recipient error message.
The banners are shown based on the priority defined
by @alya in https://github.com/zulip/zulip/issues/32115.
Fixes https://github.com/zulip/zulip/issues/32115.
Priority 1
Priority 2
Priority 3
Priority 3
Priority 4
Priority 4
Priority 5
<details>
</details>
=> compose: Better error feedback via banners.

web/src/filter.ts, web/src/search_suggestion.ts, web/templates/search_description.hbs, web/templates/search_operators.hbs, web/tests/filter.test.cjs, web/tests/search_suggestion.test.cjs
This PR adds support for searching unresolved topics.
It achieves this in the following ways:
- Rename "Topics marked as resolved" -> "Resolved topics".
- Adds 'Unresolved Topics' to the typeahead, which inserts `-is:resolved` into the search pill.  
- Updates conditions to display 'Unresolved Topics' instead of 'Exclude topic marked as resolved.'  
- Modifies conditions to correctly show the last searched option as 'Unresolved Topics.'
Fixes: #31725.
<details>
<summary> Unresolved and Resolved in the typeahead: </summary>
</details>
<details>
<summary> Unresolved in the history of last searched option: </summary>
</details>
<details>
<summary> Resolved Topics Heading: </summary>
</details>
<details>
<summary> Unresolved Topics in `?` menu: </summary> …
=> unresolved: Add support for searching for unresolved topics.

zerver/tests/test_bots.py, zerver/views/users.py
Currently, when trying to create a new bot with a used username, the error message is "Username already in use" which is misleading. This fixes the error message to be correct and consistent with the same error message for the same check in `create_user_backend`.
|![image](https://github.com/user-attachments/assets/e6b4cfb8-42d5-451e-993b-4022cc0ddddf)| ![image](https://github.com/user-attachments/assets/d8b20b1b-0589-4d3c-a36e-0f35c0e5addc) | 
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/Misleading.20error.20popup.20when.20creating.20bot.2E/with/2096190)
<details> …
=> bots: Fix email already in use error message.

web/src/hash_util.ts, zerver/lib/events.py, zerver/lib/home.py, zerver/lib/narrow_helpers.py, zerver/lib/narrow_predicate.py, zerver/lib/url_decoding.py, zerver/tests/fixtures/narrow_url_to_narrow_terms.json, zerver/tests/test_message_fetch.py, zerver/tests/test_url_decoding.py, zerver/views/home.py
Prep PR to fix: https://github.com/zulip/zulip/issues/31100. It adds `parse_narrow_url` which is the  Python copy of `hash_util.parse_narrow`. 
Additional context and details on the commit descriptions:
- ### narrow_term: Refactor a `NeverNegatedNarrowTerm`.
<details>
<summary>
git grep of `NarrowTerm` before  this PR
</summary>
```grep
zerver/lib/events.py:from zerver.lib.narrow_helpers import NarrowTerm, read_stop_words
zerver/lib/events.py:    narrow: Collection[NarrowTerm] = [],
zerver/lib/home.py:from zerver.lib.narrow_helpers import NarrowTerm
zerver/lib/home.py:    narrow: list[NarrowTerm],
zerver/lib/narrow_helpers.py:class NarrowTerm:
zerver/lib/narrow_helpers.py:def narrow_dataclasses_from_tuples(tups: Collection[Sequence[str]]) -> Collection[NarrowTerm]: …
```
=> url_decoding: Add `parse_narrow_url`.

docs/tutorials/new-feature-tutorial.md, help/animated-gifs-from-giphy.md, help/code-blocks.md, help/image-video-and-website-previews.md, help/message-retention-policy.md, help/read-receipts.md, help/require-topics.md, help/start-a-call.md, templates/zerver/integrations/jitsi.md, templates/zerver/integrations/zoom.md
Updates help center, integration and contributor docs where for the new subsections on the organization settings tab, which were changed in #33605.
Previously, these settings were all in the "Other settings" subsection for that organization settings tab.
---
*Did not include a screenshot of the changes to the new feature tutorial in the contributor docs.*
| Documentation | Screenshot |
| --- | --- |
| [Animated GIFs](https://zulip.com/help/animated-gifs-from-giphy) | ![Screenshot from 2025-02-24 20-49-20](https://github.com/user-attachments/assets/e15bf726-8d45-4564-8a36-694c60f6fed5) |
| [Code blocks](https://zulip.com/help/code-blocks#default-code-block-language) | ![Screenshot from 2025-02-24 …
=> docs: Update sections for organization settings tab changes.

help/message-a-channel-by-email.md
Documents setting the email sender in the generate channel email modal that was added in #32581 and #32382.
We could also add a step in the instructions for the **Who should be the sender of the Zulip messages for this email address?** question in the modal.
---
<details>
</details>
=> help: Document specifying sender in generate channel email modal.

web/src/composebox_typeahead.ts, web/styles/compose.css, web/styles/typeahead.css, web/tests/composebox_typeahead.test.cjs
Extracted from #33619
Fixes following:
* Topic completion for very long stream names.
* Topic input box in compose not visible for long stream names in short windows.
* Stream description alignment in stream typeahead.
* Wrap topic name to next line in inline topic edit typeahead.
| --- | --- |
| ![Screenshot 2025-02-24 123116](https://github.com/user-attachments/assets/05f89ff3-023a-4029-bdac-948a246c1e3f) | ![Screenshot 2025-02-24 123100](https://github.com/user-attachments/assets/3f75e295-24bc-4728-8683-5dedfadd426f) |
| ![Screenshot 2025-02-24 194037](https://github.com/user-attachments/assets/afddae96-89f3-4198-9618-6261999c5440) | ![Screenshot 2025-02-24 194001](https://github.com/user-attachments/assets/42d74540-f890-489e-a1da-b5b5ca406e4e) |
| …
=> Fixes related to typeahead.

web/styles/compose.css
12px, 14px, 16px, 20px
| --- | --- |
| ![Screen Shot 2025-02-18 at 16 02 48](https://github.com/user-attachments/assets/907df0d3-dd22-488f-a70b-f3edc52f1108) | ![Screen Shot 2025-02-20 at 12 41 48](https://github.com/user-attachments/assets/db6ed302-691a-4d44-8077-8daceaf136c7) |
| ![Screen Shot 2025-02-18 at 16 02 55](https://github.com/user-attachments/assets/f46abdb6-9a59-4418-9d0f-7dc0c5b1f4c8) | ![Screen Shot 2025-02-20 at 12 41 59](https://github.com/user-attachments/assets/13c4cedd-a236-41a8-b8ad-2adcfe34a489) |
| ![Screen Shot 2025-02-18 at 16 03 00](https://github.com/user-attachments/assets/a2beac42-bcb1-483c-bb3d-f413dda11fe9) | ![Screen Shot 2025-02-20 at 12 42 07](https://github.com/user-attachments/assets/565ae58e-d3b1-4979-ab4b-eb035363f482) |
| ![Screen …
=> compose: Scale send button with font size.

zerver/lib/events.py, zerver/models/realms.py
We were not actually using anything but the IDs here, so it was a bunch of wasted work to fetch these.
This essentially reverts f48e87cd3cb6846d99db5099cafe604390a9b667. At
the time, something like that was required, because we needed to check
if the channel was deactivated before exposing it to the API, but more
recent reworking of the system to change the setting if the channel is
deactivated, rather than masking it in fetch_initial_state_data, means
we can do this cleanup.
@prakhar1144 FYI.
=> get_realm_with_settings: Fix unnecessary joins with channel.

web/styles/popovers.css
This affects both the "Channels" and "User groups" tab in similar ways.
12px, 14px, 16px, 20px:
| --- | --- |
| ![Screen Shot 2025-02-25 at 12 50 51](https://github.com/user-attachments/assets/665554ba-ee32-4594-b314-c2a167bc7d5f) | ![Screen Shot 2025-02-25 at 12 47 53](https://github.com/user-attachments/assets/ba8ca248-8777-44af-94a4-152f0415d0ae) |
| ![Screen Shot 2025-02-25 at 12 50 36](https://github.com/user-attachments/assets/56e4896c-2388-4ca8-ae07-556a1cdeb70e) | ![Screen Shot 2025-02-25 at 12 48 18](https://github.com/user-attachments/assets/1ea4746c-2470-4529-a0f3-7afff129d0ed) |
| ![Screen Shot 2025-02-25 at 12 50 21](https://github.com/user-attachments/assets/81e053a8-8ba6-463b-bf52-27f66dc27422) | ![Screen Shot 2025-02-25 at 12 48 …
=> user_profile: Override default width of input, to avoid overflow.

api_docs/changelog.md, zerver/lib/streams.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_subs.py
This parameter is no longer restricted to realm administrators. Any user can get the streams they have metadata access to by setting this parameter to true.
I don't think there's need for a version change even though it's a different PR, since it's just a continuation of 
#33626. If another PR with a version change gets merged before this, we probably should have another version change (?)
Fixes: 
<details> …
=> get_streams: Return metadata access streams in `include_all`.

web/styles/user_status.css
at 12px, 14px, 16px, 20px
| --- | --- |
| ![Screen Shot 2025-02-20 at 18 42 53](https://github.com/user-attachments/assets/be97fe43-57fe-41e1-992f-23cb914e148c) | ![Screen Shot 2025-02-20 at 18 42 19](https://github.com/user-attachments/assets/e4cb28fe-bc1b-4efd-8e32-013700ef573b) |
| ![Screen Shot 2025-02-20 at 18 43 15](https://github.com/user-attachments/assets/bf592933-022c-4827-b2b0-e7cf30598941) | ![Screen Shot 2025-02-20 at 18 42 05](https://github.com/user-attachments/assets/28689776-133e-438c-9114-16eef4f9719e) |
| ![Screen Shot 2025-02-20 at 18 43 25](https://github.com/user-attachments/assets/f92a3934-54d3-4254-abea-c5aa5a0fa526) | ![Screen Shot 2025-02-20 at 18 41 48](https://github.com/user-attachments/assets/d6177e4f-7b77-419a-9952-628d4f4697ca) |
| …
=> user_status: Scale emoji with user's font-size.

web/styles/message_header.css
This commit fixes the alignment of the user emoji in the topic header. Previously, the icon in the user's name was slightly cut off at the top. This issue was resolved by setting the line height to 19px.
> Important Note:
This UI glitch was exclusive to Safari Browser. 
|Change in 12px (Before)|Change in 12px (After)|
|---|---|
|<img width="196" alt="Screenshot 2025-02-25 at 2 26 21 AM" src="https://github.com/user-attachments/assets/9f596c8a-8a74-4f1a-875e-085d831dcab3" />|<img width="196" alt="Screenshot 2025-02-25 at 2 09 42 AM" src="https://github.com/user-attachments/assets/22af786f-9563-44d8-8ae1-b5dec93a456a" />|
|Change in 14px(Before)|Change in 14px(After)|
|---|---|
|<img width="229" alt="Screenshot 2025-02-25 at 2 28 01 AM" …
=> banner: Aligned the username icon for topic header.

api_docs/changelog.md, version.py, zerver/actions/bots.py, zerver/actions/create_user.py, zerver/lib/streams.py, zerver/tests/test_bots.py, zerver/tests/test_events.py
See
https://chat.zulip.org/#narrow/channel/101-design/topic/manage.20bot.20access.20feature.20removal
<details>
</details>
=> bots: Do not remove bot from inaccessible streams on owner change.

web/src/presence.ts, web/tests/presence.test.cjs, zerver/actions/user_settings.py, zerver/tests/test_events.py, zerver/tests/test_presence.py, zerver/tests/test_user_status.py
This pull request introduces a change to the `status_from_raw` function in the `web/src/presence.ts` file to account for users who have turned on 'Go invisible' mode. 
* Modified the `status_from_raw` function to accept an additional `user_id` parameter.
* Added logic to handle the 'Go invisible' mode by comparing the user's `date_joined` with `last_active` and setting the `last_active` to `idle_timestamp` if the user is considered invisible.
* Added a new test case to verify the 'Go invisible' mode functionality.
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20last.20active.20time/near/2011826).
<details> …
=> presence_data: Fix last_active_time for users with invisible mode on.

help/deactivate-or-reactivate-a-user.md, help/status-and-availability.md, web/styles/portico/markdown.css
This brings the help center in line with the user-circle design implemented in #33052.
Current: https://chat.zulip.org/help/status-and-availability
| --- | --- |
| ![status-intro-before](https://github.com/user-attachments/assets/372f7f77-8a4f-4c7a-a0b6-7765093a0749) | ![status-intro-after](https://github.com/user-attachments/assets/6c018d3e-b680-47dd-aff9-459a50d4d009) |
| ![availability-before](https://github.com/user-attachments/assets/8ba24d42-8675-4cbe-bba3-4223f83a2eff) | ![availability-after](https://github.com/user-attachments/assets/87fa0b36-2709-4a55-bd38-bb58423d21cd) |
Current: https://chat.zulip.org/help/deactivate-or-reactivate-a-user
| --- | --- |
| …
=> help_center: Update presentation of user circles.

web/src/bootstrap_typeahead.ts, web/src/composebox_typeahead.ts
Previously, the typeahead's header html used to be updated only once -- after it is shown.
This caused stale state in compose box typeaheads -- when user starts with an `@`, the typeahead is shown for the first time, and the header html is rendered. Then when next character is `_` (silent mention), the header html is no longer updated since it is already updated once when `@` is used.
This is fixed by updating the typeahead everytime the user string is updated.
Fixes: [CZO Thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AFtypeahead.20doesn't.20update.20helper.20text.20when.20already.20shown/with/2105026)
https://github.com/user-attachments/assets/5f5e6099-31ba-4423-990b-a6e819f5604e
<details> …
=> typeahead: Re render header html for every update in user string.

web/postcss.config.js, web/src/buddy_list.ts, web/src/click_handlers.ts, web/src/css_variables.ts, web/src/information_density.ts, web/src/popover_menus.ts, web/src/realm_icon.ts, web/src/sidebar_ui.ts, web/src/ui_util.ts, web/styles/app_variables.css, web/styles/search.css, web/styles/zulip.css, web/templates/navbar.hbs
This PR introduces a container, `app-main`, for app-wide use in container queries. The benefit of this over media queries is that we can query for em-values on the container's size, meaning that adjustable font-size values will be taken into account.
**Updated, 2025-02-21:** The PR now includes a different mechanism for determining viewport state from within JavaScript. Rather than replicating media queries in JavaScript and then also trying to replicate container queries, there is a new stack of media and container queries that set the `content` attribute on `.app-main` for easier querying from JavaScript.
Additionally with the larger, more flexibly sized right sidebar, even above the `xl_min` query, manually hiding the right sidebar allows the middle column to occupy the entire …
=> app_layout: Introduce container queries, more flexible right sidebar.

api_docs/changelog.md, version.py, zerver/actions/message_edit.py, zerver/actions/reactions.py, zerver/lib/message.py, zerver/tests/test_message_delete.py, zerver/tests/test_reactions.py, zerver/views/message_edit.py, zerver/views/reactions.py, zerver/views/submessage.py, zerver/views/typing.py
Fixes #33567.
Supersedes #33457.
We have used the flag `is_modifying_message` since it's more generic than an archived channel specific flag and helps us understand better what is the condition where we do not want to allow archived channels. Message edit has an existing test for this.
Also see https://github.com/zulip/zulip/pull/33507#discussion_r1971062341
<details>
</details>
=> message: Allow accessing archived channel when not modifying message.

help/general-chat-topic.md, help/include/general-chat-intro.md, help/include/sidebar_index.md, help/require-topics.md
- The italics in the heading end up in the tab name. Would be better if they didn't, I think, but it's not terrible.
- I didn't change any of the intro to topics documentation. Possible follow-up.
- Not worried about making `/help/require-topics` perfect, since it'll likely get rewritten with #33549.
<details>
<summary>
New "_general chat_" help page
</summary>
---
---
</details>
<details>
<summary>
Updated version of required topics page
</summary>
https://zulip.com/help/require-topics
</details>
=> help: Document "general chat" topic.

help/link-to-a-message-or-conversation.md
Follow-up to #31669; @kuv2707 FYI.
Notes:
- I considered doing this as an addition to the instruction to enter the channel name, rather than as a tip. But I think that would be awkward, as it actually affects both that instruction and the next one.
- I think moving the info about manually typing out links down below where we introduce the syntax makes sense. It's not really a tip, in that we aren't really suggesting that people should ever do this.
- I untippified the message link tip for consistency with the prior sections.
=> help: Document nice syntax for linking in the current channel.

web/src/hotkey.js
Fixes #33574
This was due to the method used to get the emoji name was incorrect.
=> hotkey: Fix `=` to toggle reaction results in error.

zerver/actions/streams.py, zerver/lib/streams.py, zerver/tests/test_subs.py
We no longer archive private streams when they become vacant, since user can still have permissions to subscribe to it.
And streams can anyways be archived manually if needed.
Fixes:  #33689
<details>
</details>
=> streams: Do not archive vacant private streams.

zerver/webhooks/github/tests.py, zerver/webhooks/github/view.py
This PR updates the GitHub webhook integration to include the old issue number in the transfer message sent for the new repository, alongside the old repository's full name.
Fixes: [#integrations > github bot @ 💬](https://chat.zulip.org/#narrow/channel/127-integrations/topic/github.20bot/near/2099493)
Follow-up of #33525.
<details>
</details>
=> github: Include old issue number in transfer message for new repo.

web/styles/typeahead.css
| --- | -- |
| ![Screen Shot 2025-02-20 at 21 56 08](https://github.com/user-attachments/assets/49337ab8-2d64-4326-8011-25cabba8590f) | ![Screen Shot 2025-02-20 at 21 55 20](https://github.com/user-attachments/assets/256a1fc9-703d-4b4f-9199-9130857278f7) |
| ![Screen Shot 2025-02-20 at 21 56 24](https://github.com/user-attachments/assets/39fb4d4f-9982-4a92-9944-0a872b0e19a8) | ![Screen Shot 2025-02-20 at 21 55 00](https://github.com/user-attachments/assets/a36b0639-c26c-46fc-ac6e-5a381aa5750e) |
| ![Screen Shot 2025-02-20 at 21 56 40](https://github.com/user-attachments/assets/ae01e10f-a1fc-4bb2-9245-f7f1cdeaee84) | ![Screen Shot 2025-02-20 at 21 54 42](https://github.com/user-attachments/assets/322b29b1-729e-446b-9312-8ebbf34c88bd) |
| …
=> typeahead: Scale header text with font size.

zerver/actions/realm_settings.py, zerver/actions/streams.py, zerver/actions/user_groups.py, zerver/actions/users.py, zerver/lib/event_schema.py, zerver/lib/event_types.py, zerver/lib/events.py, zerver/lib/streams.py, zerver/lib/subscription_info.py, zerver/lib/types.py, zerver/lib/user_groups.py, zerver/models/realms.py, zerver/tests/test_event_system.py, zerver/tests/test_events.py, zerver/tests/test_home.py, zerver/tests/test_subs.py, zerver/tests/test_user_groups.py, zerver/views/streams.py, zerver/views/user_groups.py
- First commit is a refactor commit.
- Second commit is to update code to not fetch all setting fields using `select_related`.
Fixes:  #33656
<details>
</details>
=> register: Optimize computing realm group settings.

web/src/compose_notifications.ts
Earlier when a new user sent a message in empty string topic, it resulted in an error while displaying the automatic new visibility policy banner.
<details>
</details>
=> compose_banner: Fix automatic visibility policy banner rendering.

web/styles/compose.css
This rewrites the grid and adds some critical properties on the general-topic placeholder to make both overflow work as expected, and sure that the faux placeholder and ordinary topic text occupies the same baseline in the composebox.
CZO issues:
* [#issues > 🎯 compose box placeholder text misaligned @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20compose.20box.20placeholder.20text.20misaligned/near/2104852)
* [#issues > 🎯 topic placeholder spills out with long channel name @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20topic.20placeholder.20spills.20out.20with.20long.20channel.20name/near/2105576)
| --- | --- |
| ![before-faux-placeholder](https://github.com/user-attachments/assets …
=> compose: Correct alignment, ellipsis on general chat placeholder.

web/src/copy_messages.ts
The `clipboard.write` API requires new permissions and can throw `NotAllowedError` under certain circumstances in the browser (and always in the current version of Zulip Desktop).
- Closes #33681
- [Discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20copying.20message.20text.20not.20working.20in.20desktop.20app/near/2104750)
=> copy_messages: Remove `clipboard.write` usage

web/styles/modal.css
This commit changes the width of the dropdown and also the text above the email.
12px, 14px, 16px, 20px:
| --- | --- |
| ![Screen Shot 2025-02-18 at 18 12 34](https://github.com/user-attachments/assets/09358d06-302a-481e-9059-e1c803f22c7d) | ![Screen Shot 2025-02-18 at 18 08 05](https://github.com/user-attachments/assets/515260ea-e619-4806-b7d7-beba811f6d9c) |
| ![Screen Shot 2025-02-18 at 18 12 14](https://github.com/user-attachments/assets/ebee8e7d-a173-4495-94a6-69a693eba047) | ![Screen Shot 2025-02-18 at 18 08 24](https://github.com/user-attachments/assets/e79e2069-6d23-45a5-ae5f-ab06760a7465) |
| ![Screen Shot 2025-02-18 at 18 11 55](https://github.com/user-attachments/assets/e9636ba0-0c4b-449b-8351-a8f992008cff) | ![Screen Shot 2025-02-18 at 18 08 …
=> modal: Scale channel email widget and email header with font size.

web/styles/reactions.css
This fixes a bug introduced in b2c5eed70df375d4249e3f46d36a991e3aec5b24 and discussed here:
https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20triangle.20next.20to.20emoji.20button/near/2105156
=> reactions: Stop using height: fit-content for emoji picker.

zerver/lib/zulip_update_announcements.py
I triggered this in the dev environment and checked all the links.
CZO discussion: [#release management > zulip_updates items of note @ 💬](https://chat.zulip.org/#narrow/channel/438-release-management/topic/zulip_updates.20items.20of.20note/near/2106859)
=> updates: Add update message (level=13).

web/styles/alerts.css
This is a follow-up commit to d1de4457dc34c4297a3f0fcffc08425ca66b9a68, which had set the font-size for the alert popups to --base-font-size-px.
This removes that line of code, as it was pointed out by Tim Abbott that the web/styles/alerts.css file was also being shared with portico through the web/src/bundles/common.ts bundle, but the --base-font-size-px variable doesn't exist there.
Removing the font-size property from the alert box doesn't affect its styling since it still inherits the `--base-font-size-px` from the body in the Zulip Web App.
CZO Discussion: [#redesign project > broader range of font sizes @ 💬](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/broader.20range.20of.20font.20sizes/near/2107255)
<details> …
=> alerts: Remove --base-font-size-px and allow font-size to be inherited.

help/using-zulip-via-email.md
I think it's actually best to keep these instructions simple, and not call out the config options (which are described on the help page we link to).
=> help and integrations: Update doc on using Zulip via email.

api_docs/changelog.md, version.py, web/src/typing.ts, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_typing.py, zerver/views/typing.py, zproject/urls.py
Replaces `/message_edit_typing` with `/messages/{message_id}/typing`. The `message_id` parameter, previously passed in the request body, is now included in the URL path.
[CZO thread](https://chat.zulip.org/#narrow/channel/378-api-design/topic/typing.20notifications.20for.20editing.20messages/near/2105514)
Fixes: 
<details>
</details>
=> api: Add endpoint `/messages/{message_id}/typing`.

web/src/buddy_list.ts, web/tests/activity.test.cjs, web/tests/lib/buddy_list.cjs
Instead of showing the "None" empty message, just hide the whole section
instead. Notably this uses the total user counts and not the number of users
rendered, so it's possible we'll still show the sections when they're partially
loaded or if they have inactive users (in which case we'd show the "view more"
links).
The exception is the "THIS CHANNEL" section which we always want to show,
since it can be confusing to see other sections without this section
present. More conversation on that here:
https://chat.zulip.org/#narrow/channel/101-design/topic/right.20sidebar.20design.20tweaks/near/2099241
=> buddy_list: Don't show (most) sections with no users in them.
