corporate/lib/support.py
Updates `get_plan_data_for_support_view` to get the latest ledger entry directly instead of calling `make_end_of_cycle_updates_if_needed` so that viewing a support page doesn't trigger any changes to the current and scheduled plans.
**Manually tested cases** *(no visual changes to support view)*:
- Regular Zulip Cloud Standard with card.
- Remote realm Zulip Basic complimentary access plan.
- Remote realm Free Trial of Zulip Basic with invoice.
- Fixed price plan Zulip Cloud Standard with card.
**Follow-up notes/questions**:
- It might make sense to break the licenses information out into a list with "purchased", "in use" and "management"? And for fixed price plans we could not show "purchased" since that's not applicable for that situation.
- Alternatively for fixed-price plans, we could …
=> support: Get plan data without making end of billing cycle updates.

help/user-list.md
Adds documentation for how to configure the user list style to the help center.
---
---
<details>
</details>
=> help: Document how to configure the user list style.

templates/corporate/comparison_table_integrated.html, templates/corporate/for/business.html, templates/corporate/for/education.html, templates/corporate/for/open-source.html, templates/corporate/for/research.html
<details>
<summary>
Screenshots
</summary>
</details>
=> portico: Document new permissions capabilities.

templates/zerver/development/design_testing/buttons.html, templates/zerver/development/dev_tools.html, web/src/portico/design-testing.ts, web/styles/app_variables.css, web/styles/buttons.css, web/styles/portico/dev-buttons.css, web/webpack.dev-assets.json, zerver/tests/test_urls.py, zerver/views/development/design_testing.py, zproject/dev_urls.py
This PR adds the redesigned button styles to the codebase along with with a storybook-style page in `/devtools/buttons` to view and test the redesigned button component.
The redesigned button component, uses the `action-button` class to follow Zulip's no-abbreviation policy, and to avoid conflicts with the pre-existing `button` and bootstrap `btn` classes.
A button using the new redesigned styles, required two classes,
- First, the base `action-button` class which defines the structure and behavior of the button.
- Second, a modifier class like `action-button--primary-neutral` which defines the styles for the particular action button type.
<details>
Communicate …
=> buttons: Add redesigned button styles.

help/include/sidebar_index.md, templates/zerver/landing_nav.html
Notes:
- Not added to the bottom nav, but I think we don't necessarily need it there?
=> portico and help: Link to guide to choosing a team chat app.

web/src/server_events_dispatch.js, web/src/user_group_edit.js, web/src/user_groups.ts
First commit addresses https://github.com/zulip/zulip/pull/32477#discussion_r1866857031
Second addresses the bug mentioned in https://github.com/zulip/zulip/pull/32477#issuecomment-2513382863
=> Live update on subgroup add/remove 

web/src/message_fetch.ts, web/src/message_list.ts, web/src/message_viewport.ts
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/Empty.20combined.20feed
=> Improvements to rendering message list.

version.py
This change was missed in 367a0bdbfff (#32567).
<details>
</details>
=> version: Bump API_FEATURE_LEVEL.

zerver/decorator.py, zerver/tests/test_subs.py, zerver/views/streams.py
Although, right now, the function only checks if a user is realm admin, it will still be beneficial to use can_manage_default_streams for when we might have granular permissions for that. I've used a decorator for endpoints where this function was applicable, since that seemed nicer to use compared to inserting a function in each of the endpoints.
Addresses https://github.com/zulip/zulip/pull/32558#discussion_r1869986375
<details> …
=> streams: Use can_manage_default_streams to check permissions.

web/src/user_group_edit.js
Addresses https://github.com/zulip/zulip/pull/32547#discussion_r1870438888
=> user_group_edit: Move tab key check to update groups list function.

web/src/user_group_edit.js, web/src/user_groups.ts, web/src/util.ts, web/templates/user_group_settings/user_group_members.hbs, web/templates/user_group_settings/user_group_membership_status.hbs, web/tests/user_groups.test.cjs, web/tests/util.test.cjs
We now mention if user is member of the group in the "Members" tab, also including the details about whether the user is direct member or is member by being direct member of one of the subgroups.
Fixees #32485.
Fixes: 
<details>
</details>
=> group-settings: Show membership details in right panel.

zerver/lib/outgoing_webhook.py
- https://github.com/zulip/zulip/pull/32583#discussion_r1871985292
=> outgoing_webhook: Optimize can_access_sender computation

web/templates/empty_feed_notice.hbs, web/tests/message_view.test.cjs
[Discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/.22stream.22.20in.20empty.20search.20results/near/1994278).
=> empty_feed_notice: Update “stream” to “channel”

web/src/settings_users.ts
Follow-up work for #31895 as suggested [here](https://chat.zulip.org/#narrow/channel/2-general/topic/Automatic.20deactivation.20of.20users/near/1993907).
Related-CZO : [here](https://chat.zulip.org/#narrow/channel/2-general/topic/Automatic.20deactivation.20of.20users)
Fixes: 
<details>
</details>
=> presence_data: Add fallback logic for date_joined.

web/styles/right_sidebar.css, web/templates/buddy_list/section_header.hbs
Screenshot for first commit:
Second commit:
=> followups for sidebar changes

web/src/compose_actions.ts, web/src/compose_recipient.ts, web/src/compose_reply.ts, web/src/hotkey.js
Rename `open_compose_recipient_dropdown` to `toggle_compose_recipient_dropdown` as that is a more accurate description of what the function actually does.
Fixes:  https://chat.zulip.org/#narrow/channel/101-design/topic/Explaining.20quote-and-reply/near/1994680
<details>
</details>
=> Rename function 'open_compose_recipient_dropdown'

zerver/lib/users.py, zerver/tests/test_users.py
This commit is to use medium-size avatar images when previewing avatars during the copy account settings flow. Before this commit, the avatar images were blurry when using the avatar from an existing account while joining a new realm. Now, the avatar is clear.
Fixes: #32604
| --- | --- |
| <img width="374" alt="Screenshot 2024-12-07 at 2 54 14 PM" src="https://github.com/user-attachments/assets/9f1334af-8792-4893-9bb3-131fa4d8adcf"> | <img width="377" alt="Screenshot 2024-12-07 at 2 52 28 PM" src="https://github.com/user-attachments/assets/45377e0e-4c07-4b2a-9c85-e4617d59372f"> |
<details> …
=> portico: Load medium-sized avatar in preview.

web/src/browser_history.ts, web/src/filter.ts, web/src/message_list_data.ts, web/src/message_view.ts, web/src/server_events_dispatch.js, web/src/stream_events.ts, web/src/stream_muting.ts, web/src/user_topics.ts, web/src/user_topics_ui.ts, web/tests/filter.test.cjs, zerver/lib/narrow.py, zerver/lib/user_topics.py, zerver/tests/test_message_fetch.py
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/Empty.20combined.20feed
=> Fix live update for muted messages in combined feed.

help/self-hosted-billing.md
On the help center page for self-hosted billing, the "pay by invoice" instructions to upgrade directly to a paid plan were missing the step where the user selects the plan the would like to purchase.
*Note that the font in the screenshot from the dev environment help center is off due to a separate issue; see [this CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/help.20center.20sidebar.20shrunk/near/1993482).*
<details>
<summary>Upgrade directly to paid plan instructions for self-hosted billing</summary>
**[CURRENT DOCUMENTATION](https://zulip.com/help/self-hosted-billing#upgrade-directly-to-a-paid-plan) - select pay by invoice tab**
</details>
---
<details> …
=> help: Add pick plan step for self-hosted invoice billing upgrade.

web/src/user_profile.ts, web/styles/app_components.css, web/styles/popovers.css, web/styles/recent_view.css, web/styles/subscriptions.css, web/templates/user_profile_modal.hbs
- First commit is to use grid layout for search input in streams and groups UI.
- Second commit is to use grid layout for search input in recent conversations view.
- Third commit is to use grid layout in stream search input in user profile modal.
- Fourth commit is to remove some unnecessary CSS.
Fixes:  https://chat.zulip.org/#narrow/channel/9-issues/topic/Short.20filter.20box.20in.20groups.20popover
| | Screenshot |
| ------ | ------ |
| Streams UI | ![stream-search](https://github.com/user-attachments/assets/f0e05590-e63d-4d0e-911c-2b21759aa06e)|
| Groups UI | ![group-search](https://github.com/user-attachments/assets/3f2cd843-a1bb-4670-8dd9-22a3ad2a28e3)|
| Recent topics for narrow screen | …
=> Use grid layout for search inputs.

tools/test-js-with-node, web/src/hashchange.js, web/src/list_widget.ts, web/src/server_events_dispatch.js, web/src/settings_components.ts, web/src/settings_org.ts, web/src/ui_init.js, web/src/user_events.js, web/src/user_group_edit.js, web/src/user_group_edit.ts
I tested the pull request by creating, joining and leaving some user groups (by both manually entering name and clicking "Join group" and "Leave group" buttons), paying attention to the resultant changes in tabs and join/leave buttons.
=> user_group_edit: Convert module to TypeScript.

web/src/settings_users.ts
This commit removes an unused block of code involving `failed_listing_users`, which handles cases where there are no users to list.  
It addresses [this comment](https://github.com/zulip/zulip/pull/31895/files/e60c84fc9961762350a4af81a805394f5972fc1a#r1866805149), which states that such a scenario is impossible because there will always be at least one active user, i.e., yourself.
Fixes: 
<details>
</details>
=> settings_users: Remove the unused block of code.

zerver/openapi/zulip.yaml
=> openapi: Fix config_options.validator documentation for webhook bots

web/src/avatar.ts
=> avatar: Fix missing function call

tools/test-js-with-node, web/src/buddy_data.ts, web/src/click_handlers.js, web/src/click_handlers.ts, web/src/gear_menu.ts, web/src/recent_view_ui.ts, web/src/server_events.js, web/src/tippyjs.ts, web/src/ui_init.js, web/tests/activity.test.cjs
=> click_handlers: Convert module to TypeScript

web/templates/settings/add_emoji.hbs
=> add_emoji: Make "Preview:" translatable.

zerver/webhooks/circleci/doc.md
The file had already been deleted, leaving behind its entry in the doc.
Fixes: [CZO link](https://chat.zulip.org/#narrow/channel/127-integrations/topic/circleci/near/2001851)
<details>
</details>
=> Remove the second screenshot from CircleCI doc.

templates/zerver/integrations/asana.md, templates/zerver/integrations/big-blue-button.md, templates/zerver/integrations/capistrano.md, templates/zerver/integrations/codebase.md
Part of `templates/zerver/integrations` sweep for #29592.
<details>
<summary>Asana</summary>
[Doc Link](https://zulip.com/integrations/doc/asana)
</details>
<details>
<summary>BigBlueButton</summary>
[Doc Link](https://zulip.com/integrations/doc/big-blue-button)
</details>
<details>
<summary>Capistrano</summary>
[Doc Link](https://zulip.com/integrations/doc/capistrano)
</details>
<details>
<summary>Codebase</summary>
[Doc Link](https://zulip.com/integrations/doc/codebase)
</details>
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/ …
=> integration-docs: Update for new format (Asana, BigBlueButton, Capistrano, Codebase).

web/src/message_fetch.ts, web/src/stream_list.ts, web/src/topic_list.ts
Fixes #32601
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20auto-scroll.20left.20sidebar.3F
=> Scroll user to the selected topic.

web/styles/compose.css
At some point, the conversation arrow background became an egg. This ensures a scalable fix to keep the background circular.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/conversation.20arrow.20is.20an.20egg/near/2002965)
| --- | --- |
| ![conversation-arrow-before](https://github.com/user-attachments/assets/bb561453-1cb4-4f7c-87d3-832ec2e440c0) | ![conversation-arrow-after](https://github.com/user-attachments/assets/d692d9b6-3a3f-4a76-acdf-a825ba3f9e34) |
| ![conversation-arrow-compact-before](https://github.com/user-attachments/assets/8c40565a-1c30-4dae-bd3b-a316dadca9c3) | ![conversation-arrow-compact-after](https://github.com/user-attachments/assets/f30a4c62-9f30-4d53-9560-31876adaecbf) |
<details> …
=> compose: Maintain circular shape for converation arrow.

.github/funding.json
Format: https://floss.fund/funding-manifest/
- I left in all the comments to make review easier. They'll need to be deleted.
- We will need to follow the instructions at https://floss.fund/funding-manifest/#wellKnown to add a https://zulip.com/.well-known/funding-manifest-urls file (name is up to us).
- I haven't added plans for OpenCollective and Patreon. Maybe we should? Not sure.
=> [WIP] funding: Add a funding.json file.

web/src/portico/signup.ts
This pull request includes a minor change to the `web/src/portico/signup.ts` file. The change ensures that the `debounced_password_quality` function is properly canceled when the password length is less than or equal to 30 characters.
* [`web/src/portico/signup.ts`](diffhunk://#diff-dad6ee29ca8d4767b15705b199640a59d581a38af30937938eb00005206fc7dbR38): Added a call to `debounced_password_quality.cancel()` to ensure the function is canceled when the password length is less than or equal to 30 characters.
Fixes: 
<details> …
=> password: Add cancel debounce feature.

zerver/lib/zulip_update_announcements.py
Not tested in dev yet, since we're still [working on the wording](https://chat.zulip.org/#narrow/channel/438-release-management/topic/zulip_updates.20items.20of.20note/near/2001738).
=> updates: Add update message (level=11).

templates/zerver/app/index.html
Sets a title and description for open graph data that can be used for URL/link previews for Zulip organizations that have web-public channels. See [relevant CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/Link.20previews.20for.20Zulip.20URLs/near/1995067).
**Questions**:
- Should we mark either of these strings for translation? They are not currently marked for translation in these changes.
---
<details>
<summary>meta tags in dev environment - via devtools and view page source</summary>
</details>
<details>
<summary>Example of link preview in Zulip</summary>
</details>
---
<details> …
=> templates: Add open graph title and description for web-public view.

zerver/data_import/import_util.py, zerver/data_import/slack.py, zerver/tests/test_slack_importer.py
Currently, we're unable to convert messages from Slack's integration bots because this message subtype doesn't come from a Slack "user", that is they don't have a Slack user profile.
This is a preparatory change to support converting Slack's integration bot messages. This PR artificially creates Slack user data from the integration bot's "profile" so that we can create a corresponding Zulip user for them. 
<details> …
=> slack_data_import: Add support converting Slack integration bots.

templates/corporate/comparison_table_integrated.html, templates/corporate/for/education.html, templates/corporate/for/events.html, templates/corporate/policies/privacy.md, templates/corporate/security.md
=> portico: Improve channel permissions links.

api_docs/changelog.md, version.py, web/src/state_data.ts, web/src/stream_data.ts, web/tests/lib/events.cjs, web/tests/stream_data.test.cjs, zerver/actions/default_streams.py, zerver/lib/default_streams.py, zerver/lib/event_schema.py, zerver/lib/events.py, zerver/models/streams.py, zerver/openapi/zulip.yaml, zerver/tests/test_invite.py, zerver/tests/test_signup.py, zerver/tests/test_subs.py
- First commit is to include only stream IDs in default streams data.
- Second commit is to include only stream IDs in default stream group data.
- Third commit is to remove unused code.
[Discussion](https://chat.zulip.org/#narrow/channel/378-api-design/topic/stream.20traffic.20data.20in.20stream.20objects/near/1618783)
<details>
</details>
=> streams: Include only stream IDs for default streams data and default stream groups data.

web/src/buddy_data.ts, web/src/conversation_participants.ts, web/src/people.ts
This is for test deploying on czo to weed out any bugs - https://github.com/zulip/zulip/pull/32540#issuecomment-2539535843
=> Verify that conversation participants data is correct.

tools/test-js-with-node, web/src/group_permission_settings.ts, web/src/settings_components.ts, web/src/user_group_create.ts, web/src/user_group_edit.ts, web/src/user_groups.ts
- First commit adds code to fix live update of left panels when removing members.
- Secomd commit adds code to fix live update of checkmark for indirectly affected groups.
Fixes: https://chat.zulip.org/#narrow/channel/101-design/topic/displaying.20group.20membership.20via.20subgroups/near/1991876
<details>
</details>
=> Fix live update of groups UI when updating membership.

docs/development/setup-recommended.md
This PR makes minor updates to the WSL documentation with respect to activating the Zulip python environment.
Fixes: 
[CZO](https://chat.zulip.org/#narrow/channel/19-documentation/topic/Alias.20to.20activate.20zulip.20environment.2E)
<details>
</details>
=> Inline to code block to activate py env

web/src/echo.ts, web/src/message_events.ts, web/src/message_events_util.ts, web/src/message_fetch.ts, web/src/message_list.ts, web/src/message_list_data.ts, web/src/message_util.ts, web/src/message_view.ts, web/tests/compose_closed_ui.test.cjs, web/tests/example5.test.cjs, web/tests/message_list.test.cjs, web/tests/message_list_data.test.cjs, web/tests/message_list_view.test.cjs, web/tests/stream_topic_history.test.cjs
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20.E2.9D.93combined.20feed.20missing.20messages
Reproduced by sending a new message while latest message for combined feed was not fetched.
=> Fix combined feed missing messages.

web/styles/subscriptions.css
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/channel.20description.20word.20breaks/near/2008741)
| --- | --- |
| ![ordinary-words-before](https://github.com/user-attachments/assets/fb0c8680-217a-4e8f-8b26-ea36b24c6677) | ![ordinary-words-after](https://github.com/user-attachments/assets/583dc3bf-d1d8-4837-8562-e305b19386e2) |
| ![long-words-before](https://github.com/user-attachments/assets/527cb814-6185-4bb0-93dd-7e1ea93a4d9e) | ![long-words-after](https://github.com/user-attachments/assets/1e44c86d-e6b0-4b88-a19f-a6f193678da8) |
<details> …
=> channel_descriptions: Hyphenate long words in lieu of arbitrary breaks.

help/start-a-call.md
Fixes: https://chat.zulip.org/#narrow/channel/138-user-questions/topic/Members.20using.20video/near/1982285
Before: https://zulip.com/help/start-a-call
After:
=> help: Note that you may need a separate account for a call.

help/include/tips-for-creating-channels.md, help/rename-a-channel.md
Also add a tip about links in channel descriptions.
[CZO discussion](https://chat.zulip.org/#narrow/channel/138-user-questions/topic/.E2.9C.94.20emoji.20in.20channel.20name/near/1949736)
Current: https://zulip.com/help/rename-a-channel
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/create-channels#tips-for-creating-channels
<details>
<summary>
Updated
</summary>
</details>
=> help: Note that channel names can include Unicode emoji.

templates/zerver/development/design_testing/buttons.html, web/src/portico/design-testing.ts, web/styles/app_variables.css, web/styles/buttons.css, web/styles/portico/dev-buttons.css
This PR adds the icon-only button styles to the codebase along with appending this new button style to the storybook-style page in `/devtools/buttons` to view and test the icon-only button component.
The redesigned icon button component, uses the `icon-button` class to follow Zulip's no-abbreviation policy, and to avoid conflicts with the pre-existing `button` and bootstrap `btn` classes.
A button using this new style, should use the following classes,
- First, the base `icon-button` class which defines the structure and behavior of the button. (Required)
- Second, a `icon-button-square` class, to be used in conjecture with the `icon-button` class which provides the style for the squared button style of icon button. (Optional)
- Third, a modifier class like `icon-button-neutral` which …
=> buttons: Add icon-only button styles.

web/src/stream_popover.ts, web/styles/modal.css, web/templates/inline_stream_or_topic_reference.hbs
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/move.20topic.20.2F.20message.20menu.20design/near/2003917)
| --- | --- |
| ![move-topic-before](https://github.com/user-attachments/assets/a2be3438-cb99-47ed-84ae-5154a7dc09a9) | ![move-topic-after](https://github.com/user-attachments/assets/d7aa9a43-154b-4200-a8e0-256304234a19) |
| ![rename-messages-before](https://github.com/user-attachments/assets/76de89b1-0e9f-44d9-b682-b906c08747f3) | ![rename-messages-after](https://github.com/user-attachments/assets/cea69d67-ecb0-4642-a02c-a4b739573c11) |
| ![move-messages-before](https://github.com/user-attachments/assets/01c65157-2c37-461d-bffb-1c8d790818d2) | ![move-messages-after](https://github.com/user-attachments/as …
=> modals: Adjust copy, layout of move/rename modals.

docs/production/requirements.md, scripts/lib/install
=> requirements: Require some swap space if installed on < 5GB RAM.

web/src/add_group_members_pill.ts, web/src/user_group_create_members_data.ts, web/src/user_groups.ts
- First commit is to allow adding system groups as subgroups during group creation.
- Second commit is to remove an incorrect comment.
<details>
</details>
=> Allow adding system groups as subgroups during group creation.

CONTRIBUTING.md
Current: https://zulip.readthedocs.io/en/latest/contributing/contributing.html#working-on-an-issue
<details>
<summary>
Updated
</summary>
</details>
=> contributor docs: Improve guidelines on how to get help.

help/deactivate-your-organization.md
Document setting when the organization data will be permanently deleted when deactivating an organization.
Follow-up to #31957.
<details>
<summary>Deactivate your organization - without relative links</summary>
[CURRENT DOCUMENTATION](https://zulip.com/help/deactivate-your-organization)
</details>
<details>
<summary>Deactivate your organization - with relative links</summary>
[CURRENT CZO DOCUMENTATION](https://chat.zulip.org/help/deactivate-your-organization)
</details>
---
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-d …
=> help: Document setting a data deletion date during organization deactivation.

templates/zerver/integrations/email.md
Split from #32354
[CZO](https://chat.zulip.org/#narrow/channel/19-documentation/topic/Integrations.20that.20are.20also.20features/near/1996162)
[Doc link](https://zulip.com/integrations/doc/email)
<details>
</details>
=> Symlink email integration doc to help center doc

tools/lib/provision_inner.py
This PR conditionally adds the source command for virtualenv in the user's bash profile only when the system is virtualized.
1. https://superuser.com/questions/1749781/how-can-i-check-if-the-environment-is-wsl-from-a-shell-script
2. @andersk's [comment](https://github.com/zulip/zulip/pull/26965#issuecomment-1751479201) in a previously closed PR. 
As originally brought to attention [here](https://github.com/zulip/zulip/pull/32806#pullrequestreview-2519614854), would we want to source the bash profile in bashrc for WSL because of the non login shell behavior mentioned in this [comment](https://github.com/zulip/zulip/pull/32806#issuecomment-2558442168)?
The reason to not do this might be ensuring backward compatiability for users that use WSL environment for doing other stuff apart from …
=> provision: Source virtualenv for login shells conditionally.

docs/development/setup-recommended.md
https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890
These commands are taken from the [official documentation](https://developer.hashicorp.com/vagrant/install)
Thanks @psybers for adding that in the issue description.
Fixes #32837.
| **Before**                                                                                     | **After**                                                                                     |
|------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| <img src="https://github.com/user-attachments/assets/24f927ff-26ef-4705-979a-d1604d6bc148" width="200"/> | …
=> setup_docs: Update vagrant installation to support Ubuntu 24.04.

docs/contributing/design-discussions.md, templates/corporate/development-community.md
This documents on /development-community the [new #mobile-design channel](https://chat.zulip.org/#narrow/channel/530-mobile-design/topic/channel.20events/near/2024940). It also clarifies what the existing #design channel is and isn't for; and adds a bit more structure to the list of channels for code contributors, which has gotten long.
<p>
</p>
</details> 
<details>
</details>
=> docs: Introduce #mobile-design, clarify role of #design

web/src/tippyjs.ts, web/templates/tooltip_templates.hbs
Bug was introducted in 0383730391906ce73e648793cfc742ee3ce28887. So, we revert that and add a QoL commit.
=> Fix "This is your home view" not present in left sidebar.

web/src/message_fetch.ts, web/src/message_list.ts, web/src/message_list_data.ts, web/src/message_view.ts
discussion: https://github.com/zulip/zulip/pull/32751#discussion_r1890660446
=> message_list: Rename variable for caller clarity.

tools/check-schemas, zerver/lib/event_schema.py, zerver/lib/event_types.py, zerver/tests/test_events.py
- https://github.com/zulip/zulip/pull/32865#discussion_r1900452685
- https://github.com/zulip/zulip/pull/32868#discussion_r1901223786
=> check-schemas: Remove unnecessary special case for saved_snippets

help/change-your-timezone.md
Updates the help center article for changing your time zone to document the banner for updating the local time zone to match the computer's time zone.
Follow-up task from #30425.
[CURRENT DOCUMENTATION](https://zulip.com/help/change-your-timezone)
---
<details>
</details>
=> help: Update time zone article for update local time zone banner.

api_docs/integrations-overview.md
=> api_docs: Fix link to Slack incoming webhook doc.

zerver/lib/import_realm.py, zerver/tests/fixtures/import_fixtures/applied_migrations_fixtures/with_unsorted_migrations_list.json, zerver/tests/test_import_export.py
This PR sorts the list of migrations to ensure the same
sets of migrations don't somehow order differently. This
has been reported to happen when importing Zulip Cloud to
self-host (zulip-cloud-current).
The order of migrations listed in `migration_status.json`
don't actually matter, migrations specify which other
migrations they depend on.
https://docs.djangoproject.com/en/5.1/topics/migrations/
Fixes #32826.
[CZO](https://chat.zulip.org/#narrow/channel/3-backend/topic/.2332826.20Fix.20check_migrations_status)
<details> …
=> import: Sort realms migrations status before checking.

zerver/lib/event_schema.py
=> event_schema: Use correct mypy type for EventModel.

zerver/tests/test_subs.py
Replaced list with set to ensure order-independent comparison of IDs during assertions.
Fix the failing test.
Using set instead of list to fix the test failing due to order of ids.
[CZO](https://chat.zulip.org/#narrow/channel/43-automated-testing/topic/main.20failing/near/2025577).
<details>
</details>
=> Fix failing `test_unarchive_stream` test.

scripts/lib/upgrade-zulip-stage-3
=> upgrade-zulip: Pass --only-django through to restart-server.

web/templates/message_edit_history.hbs
=> edit history: Rename Stream -> Channel.

web/styles/popovers.css
With a gridded modal heading in place, this fix properly centers the profile modal heading within a grid regime.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/user.20profile.20title.20not.20centered/near/2024749)
| --- | --- |
| ![modal-title-before](https://github.com/user-attachments/assets/4b3b5e6f-efcc-4473-b0e2-c9e0b1be57b3) | ![modal-title-after](https://github.com/user-attachments/assets/1122db9b-12f1-41d1-afc3-c3d657fe30c6) |
<details> …
=> profile_modal: Correctly center title contents.

web/templates/popovers/navbar/navbar_personal_menu_popover.hbs
Handles enter keyboard event for user profile field.
Fixes: [czo](https://chat.zulip.org/#narrow/channel/137-feedback/topic/top.20right.20corner.20.28help.2C.20etc.2E.29/near/2022942)
<details>
</details>
=> personal_menu: Navigate to user profile on enter.

web/src/tippyjs.ts, web/templates/settings/settings_user_list_row.hbs, web/templates/user_profile_modal.hbs
Tooltip changes:
In organization settings
- "Edit user" -> "Manage user"
- "Edit bot" -> "Manage bot"
-  "Deactivate" -> "Deactivate user"
- "Reactivate" -> "Reactivate user"
In profile modal
-  "Manage user" -> "Manage bot" (for bots)
fixes part of #32887 .
| --- | --- |
| ![Before Image](https://github.com/user-attachments/assets/562bd93f-ce81-4ed2-aae9-294195f24e24) | ![After Image](https://github.com/user-attachments/assets/a6bfe1bb-acff-4b20-b118-dc8ce7e195eb) |
| ![Before Image](https://github.com/user-attachments/assets/71737d52-01bf-4e75-a476-95b8463dd5ba) | ![After Image](https://github.com/user-attachments/assets/57db2826-c3b8-4078-9a89-73b42976d907) |
| ![Before Image](https://github.com/user-attachments/assets/a425ab25-b634-4295-9bf1-aae85f6a7500) | ![After …
=> settings: Update activate/deactivate/manage users and bot tooltips.

zerver/lib/event_schema.py
It was pure laziness not to catch this in my
previous relevant commit.
Now I handle it.
The `name` parameter passed into the event checkers will hopefully help developers debug the `test_events.py` tests.
=> event tests: Show the name of the object that's wrong.

web/styles/recent_view.css
12px before:
12px after:
20px before:
20px after:
=> recent_view: Use em for padding width of checkboxes.

docs/development/setup-recommended.md
This commit adds an alternative way to shutdown the zulip WSL2 environment.
[CZO](https://chat.zulip.org/#narrow/channel/19-documentation/topic/Shutting.20Down.20WSL.20environment)
Fixes: 
<details>
</details>
=> setup_docs: Add command to terminate WSL2 environment.

templates/zerver/integrations/giphy.md
Fixes: Part of zulip#29592.
Separated out from #32354.
[Doc link](https://zulip.com/integrations/doc/giphy)
<details>
</details>
=> integration-docs: Update Giphy for new doc format.

templates/zerver/integrations/hubot.md, templates/zerver/integrations/hubot_common.md
Fixes: Part of zulip#29592.
Separated out from #32355.
[Doc link](https://zulip.com/integrations/doc/hubot)
**An use-case of hubot-common**:
[Doc link of an example that uses hubot-common.md](https://zulip.com/integrations/doc/assembla)
<details>
</details>
=> integration-docs: Update Hubot docs for new doc format.

zerver/webhooks/appveyor/view.py, zerver/webhooks/opsgenie/view.py
=> Refactor view functions of Appveyor and Opsgenie

web/src/markdown.ts, web/src/markdown_config.ts, web/src/rendered_markdown.ts, web/tests/markdown_parse.test.cjs, web/tests/rendered_markdown.test.cjs, zerver/lib/mention.py, zerver/tests/test_message_edit.py, zerver/tests/test_message_send.py
This commit does not add highlighting to any pre-existing group mentions for which a user was part of the mentioned group via a subgroup. This only fixes it for mentions moving forward.
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/group.20mention.20not.20highlighted/near/2008541
<details>
</details>
=> mention: Mentions via subgroup should be highlighted.

web/styles/app_variables.css, web/styles/inbox.css, web/styles/recent_view.css
Ideally this UI would use more flex or grid, but for efficiency I'm just switching to em for now.
---
12px before/after
14px before/after
16px before/after
20px before/after
=> inbox: Use em for filter and search boxes.

api_docs/integrations-overview.md
Notes:
- I copy-pasted the Slack webhook instructions. Don't love it, but they are so simple, that I think it's much better to have them on this page than just having a link.
Current: https://zulip.com/help/integrations-overview
<details>
<summary>
Updated
</summary>
</details>
=> help and api docs: Modernize and expand introduction to integrations.

web/src/message_list_tooltips.ts, web/src/topic_popover.ts, web/templates/recipient_row.hbs
discussion: https://chat.zulip.org/#narrow/channel/101-design/topic/UI.20redesign.3A.20recipient.20bar
=> recipient_row: Add icon to open topic popover.

web/src/stream_settings_ui.ts
We were not passing the required variables in `render_stream_settings` in `add_sub_to_table`
and that resulted in FORMAT_ERROR.
We actually do not need to append the html from `render_stream_settings` here as we already
handle opening the stream settings using `open_edit_panel_for_row`, so we remove that code.
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/FORMAT_ERROR.20when.20creating.20new.20channel
<details> …
=> stream-settings: Fix FORMAT_ERROR during stream creation.

web/styles/compose.css
| before             |  after |
:-------------------------:|:-------------------------:
=> compose: Scale compose banner close button with info density setting.

web/templates/settings/organization_permissions_admin.hbs
This checkbox was accidentally removed in #32371.
[CZO](https://chat.zulip.org/#narrow/channel/387-zulip-cloud/topic/Turning.20off.20.22Invitations.20are.20required.2E.2E.2E.22.20on.20Standard.20plan/near/2032359)
<details>
</details>
=> settings: Add checkbox for "realm_invite_required" permission.

zerver/webhooks/slack/view.py
Extracts two commits from #32797.
=> Commits from #32797

web/styles/modal.css
=> poll modal: Fix info density bugs and misaligned input field.

web/src/upload.ts
Fixes #31926.
The tus-js-client fingerprinting feature stores metadata on previously uploaded files in browser local storage, to allow resuming the upload / avoiding a repeat upload in future browser sessions.
This is not a feature we need across browser sessions. Since these local storage entries are never garbage-collected, they can be accessed via the browser console even after logging out, and contain some metadata about previously uploaded files, which seems like a security risk for using Zulip on a public computer.
We use our own implementation of url storage that saves urls in memory instead. We won't be able to retain this history across reloads unlike local storage, which is a tradeoff we are willing to make.
NOTE: I've tested uploading same file twice and making sure that the …
=> upload: Implement InMemoryUrlStorage for tus-js-client.

web/src/user_group_create_members.ts, web/src/user_group_edit.ts, web/src/user_group_edit_members.ts
- First commit is to fix the pills in members list.
- Second commit is to fix the group names in membership status text.
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/roles.20display
<details>
</details>
=> Show display names for system groups.

api_docs/changelog.md, api_docs/message-formatting.md, version.py, web/src/lightbox.ts, zerver/actions/realm_emoji.py, zerver/data_import/import_util.py, zerver/lib/markdown/__init__.py, zerver/lib/mime_types.py, zerver/lib/thumbnail.py, zerver/lib/upload/__init__.py, zerver/lib/upload/base.py, zerver/lib/upload/s3.py, zerver/tests/fixtures/markdown_test_cases.json, zerver/tests/test_import_export.py, zerver/tests/test_markdown_thumbnail.py, zerver/tests/test_thumbnail.py, zerver/views/tusd.py, zerver/views/upload.py, zerver/worker/thumbnail.py
Stacked atop #32776.
Fixes: #32587
Fixes: #24899
<details>
</details>
=> Serve high-resolution transcoded versions of HEIC/TIFF images

zerver/data_import/slack.py, zerver/data_import/slack_message_conversion.py, zerver/tests/test_slack_importer.py, zerver/webhooks/slack/doc.md, zerver/webhooks/slack/tests.py, zerver/webhooks/slack/view.py, zerver/webhooks/slack_incoming/view.py
Backport of:
- #32430
- #32755
- #32972
=> [9.x] integrations: Clean up Slack integration.

web/e2e-tests/user-status.test.ts, zerver/migrations/0001_squashed_0569.py, zerver/migrations/0407_userprofile_user_list_style.py, zerver/models/users.py
This PR sets the default for `user_list_style` to `USER_LIST_STYLE_WITH_AVATAR` so that the
organization level defaults for new users of this setting is set to show avatar in right sidebar for new orgs.
Fixes: https://chat.zulip.org/#narrow/channel/101-design/topic/user.20list.20styling.20defaults/near/2030207
<details>
</details>
=> Show avatar by default in right sidebar for new orgs.

web/src/dialog_widget.ts, zerver/lib/narrow.py, zerver/views/message_fetch.py
=> Some prep commits.

web/src/stream_edit_subscribers.ts, web/src/user_pill.ts, web/styles/input_pill.css, web/styles/rendered_markdown.css, web/templates/input_pill.hbs, web/templates/pm_list_item.hbs, web/templates/user_display_only_pill.hbs, web/tests/user_pill.test.cjs
Fixes: #26831
For easy to differentiate between normal user and a bot . a bot icon is added at right of the bot
Continuing with the PR  #28561 and removed merge conflicts
<details>
<summary>Compose pills</summary>
</details>
<details>
<summary>Sidebar UI</summary>
</details>
<details>
<summary>Channels setting</summary>
</details>
<details>
<summary>DM headers</summary>
</details>
<details>
<summary>Bot Mention pills
</summary>
</details>
<details>
<summary>Dark theme screenshots</summary>
<hr></hr>
<hr></hr>
<hr></hr>
<hr></hr>
</details>
<details> …
=> UI :  Added Bot Icon for bots across the UI.

web/tests/compose.test.cjs, web/tests/compose_validate.test.cjs, web/tests/lib/compose_helpers.cjs
=> node tests: Use FakeComposeBox in more places

web/src/user_group_components.ts, web/src/user_group_create.ts, web/src/user_group_edit.ts, web/src/user_group_edit_members.ts, web/src/user_profile.ts, web/templates/user_group_settings/user_group_settings.hbs
- First commit is to fix searching subgroups from group members list.
- Second commit is to refactor code to use `get_display_group_name` consistenly.
Fixes:  https://chat.zulip.org/#narrow/channel/9-issues/topic/.E2.9C.94.20roles.20display/near/2037624
<details>
</details>
=> Fix searching subgroups from group members list.

web/styles/left_sidebar.css
[CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Channel.20info.20.22leaking.22.20into.20DIRECT.20MESSAGES.20area/near/1996876)
| --- | --- |
| ![channels-heading-bleedthrough-before](https://github.com/user-attachments/assets/0f26e7fe-e346-4f80-8ad2-f1e519010261) | ![channels-heading-after](https://github.com/user-attachments/assets/03af03d2-f097-4c7f-81d5-efff3195e6f8) |
<details> …
=> left_sidebar: Prevent bleedthrough on Channels heading.

web/src/composebox_typeahead.ts, web/src/user_groups.ts, web/tests/composebox_typeahead.test.cjs
- First commit modifies the code to include all the groups, including system groups, with at most 20 members in the DM typeahead.
- Second commit is to show system groups in silent mention typeahead.
https://chat.zulip.org/#narrow/channel/101-design/topic/New.20permissions.20model/near/2029540
<details>
</details>
=> Handle groups in compose box typeahead.

web/src/compose_closed_ui.ts
| --- | --- |
| ![Before Image](https://github.com/user-attachments/assets/6a383bdd-09c1-456b-b89c-b1d27e1e1a74) | ![After Image](https://github.com/user-attachments/assets/20395a4a-43c6-4cf3-9a7b-4f51201b94a2) |
modal:
<details>
<summary>demo</summary>
https://github.com/user-attachments/assets/82a45064-7673-4b0e-9bf1-9f7487da9859
</details>
<details>
</details>
=> compose box: Fix disabled reply button for spectators.

web/src/stream_popover.ts
This commit improves the propagation mode choices by making them smarter and sticky. It remembers the last choice made by the user by storing it in the local storage. The new behavior is as follows:
- Keeps the smart default for the first or last messages.
- Only overwrites the dropdown selection if the current value is "from here" and the last used option was "only one".
Fixes: [CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/most.20recent.20option.20not.20selected.20in.20move.20messages.20modal.3F).
<details>
<summary>Demonstrationt: </summary>
https://github.com/user-attachments/assets/674e36df-75e1-4a1a-80b6-c6dd020bab31
</details>
<details> …
=> move_message: Make propagation mode choices smarter and sticky.

docs/development/setup-recommended.md, docs/development/setup/vscode-vagrant.md, docs/production/system-configuration.md, docs/subsystems/logging.md, docs/testing/continuous-integration.md
=> docs: Fix missing references.

zerver/actions/message_edit.py, zerver/lib/topic.py, zerver/lib/types.py, zerver/tests/test_events.py, zerver/tests/test_message_fetch.py, zerver/tests/test_message_move_topic.py
- First two commits are refactor commits.
- Last commit is the main refactor commit.
<details>
</details>
=> message_edit: Refactor message edit code.

help/status-and-availability.md, zerver/actions/presence.py, zerver/tests/test_presence.py, zerver/views/presence.py
* This PR makes it so that the statistics of users who set their status to invisible are included in the analytics page of the organization.
* Also updated the help page to notify the users that even when they set their status to invisible their stats will be recorded in the organization analytics.
fixes #32605
<details>
</details>
=> presence:Made it so that stats of even invisible users are been recorded

analytics/lib/counts.py, tools/test-backend, zerver/lib/test_helpers.py, zerver/views/message_summary.py, zproject/computed_settings.py, zproject/urls.py
=> message_summary: Add API endpoint to generate narrow summary.

docs/subsystems/html-css.md, docs/subsystems/icons.md, docs/subsystems/index.md
<details>
<summary>
Screenshot
</summary>
</details>
=> contributor docs: Document how to add and modify icons.

api_docs/changelog.md, web/src/stream_topic_history_util.ts, web/tests/stream_topic_history.test.cjs, zerver/lib/topic.py, zerver/openapi/zulip.yaml, zerver/tests/test_message_topics.py, zerver/views/streams.py
[CZO Discussion](https://chat.zulip.org/#narrow/channel/378-api-design/topic/general.20chat/near/2052625)
We missed `users/me/{stream_id}/topics` endpoint while working on #32330
Fixes part of #23291.
<details>
</details>
=> get_stream_topics: Add support for empty topic name.

help/restrict-account-creation.md, help/set-default-channels-for-new-users.md
Current: https://zulip.com/help/set-default-channels-for-new-users
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/restrict-account-creation
<details>
<summary>
Updated
</summary>
</details>
=> help: Update default channels documentation. 

docs/contributing/design-discussions.md
We have an increasing number of design discussions about mobile
these days (which is great), and that means I've started to
regularly point people to this page -- particularly the section
"Guidelines for code contributors" -- as part of pointing them to
the #mobile-design channel to ask a design question.
In that context it seems confusing that it only talks about #design
and not #mobile-design.  We do mention the latter elsewhere on the
page, but I still feel I have to explain the discrepancy when
pointing to this section.  Fix it here instead.
This introduces to our docs the concept of "a design channel",
meaning #design and #mobile-design and sometimes #zulip-terminal.
<details>
Communicate …
=> docs: Clarify design-discussions as to #mobile-design vs. #design.

web/src/add_subscribers_pill.ts, web/src/stream_create_subscribers.ts, web/src/stream_edit_subscribers.ts, web/src/user_groups.ts
We now show role-based system groups in the subscribers typeahead in stream creation and stream edit UI.
<details>
</details>
=> stream-settings: Show system groups in subscribers form typeahead.

tools/lib/capitalization.py, web/src/stream_create.ts, web/src/stream_edit.ts, web/src/stream_ui_updates.ts, web/styles/settings.css, web/templates/settings/group_setting_value_pill_input.hbs, web/templates/stream_settings/stream_can_add_subscribers_group_label.hbs, web/templates/stream_settings/stream_types.hbs
Fixes: https://github.com/zulip/zulip/issues/33156
The first commit adds note as a plain text, there is an alternate version of this PR using a tip instead of plain text at #33160. Either one of this PR should be merged after review and the other closed. 
Point 1:
Point 2:
Point 3:
<details>
</details>
=> Channel settings copy change plain text

help/add-or-remove-users-from-a-channel.md, help/channel-permissions.md, help/configure-who-can-invite-to-channels.md, help/include/sidebar_index.md, web/templates/settings/organization_permissions_admin.hbs
<details>
<summary>
Settings
</summary>
</details>
Current: https://zulip.com/help/add-or-remove-users-from-a-channel
<details>
<summary>
Updated
</summary>
</details>
Current:  https://zulip.com/help/configure-who-can-invite-to-channels
<details>
<summary>
Updated
</summary>
</details>
Notes:
- I'm leaving https://chat.zulip.org/#narrow/channel/19-documentation/topic/add.20-.3E.20subscribe.20to.20channels.3F/near/2055413 as a possible follow-up.
=> Update docs on permissions to subscribe other users to channels, and tweak settings label.

web/styles/modal.css
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/channel.20icon.20spacing.20in.20modal.20heading/near/2055416)
| --- | --- |
| ![created-modal-before](https://github.com/user-attachments/assets/a1ffa0d6-a397-48b6-b26a-78e95b256e6e) | ![created-modal-after](https://github.com/user-attachments/assets/6f165b76-8def-4eed-8c50-ac3ba7780f60) |
<details>
</details>
=> channel_modal: Push back against inherited icon styles.

docs/contributing/review-process.md
[CZO thread](https://chat.zulip.org/#narrow/channel/19-documentation/topic/Defining.20follow-ups.20in.20our.20contributing.20guide/near/2059940)
=> contributor docs: Describe how to handle follow-ups.

help/change-your-email-address.md
Updates the help center article for changing an email address for recent UI updates in the web-app (see #31975 and #32260).
[Current documentation](https://zulip.com/help/change-your-email-address)
---
<details>
</details>
=> help: Update change email address instructions for UI changes.

web/src/settings_notifications.ts
There was a bug when updating email notification batching period setting to a custom value not present in dropdown because "email_notifications_batching_period_minutes" is just a name used for input elements and we do not use it to store the setting value as it is just stored in seconds.
Fixes:  https://chat.zulip.org/#narrow/channel/9-issues/topic/buggy.20.22Delay.20before.20sending.20message.20notification.20emails.22
<details> …
=> settings: Fix updating email notification batching period setting.

zerver/actions/message_edit.py, zerver/lib/attachments.py, zerver/tests/test_message_edit.py, zerver/tests/test_upload.py
https://github.com/zulip/zulip/pull/29380#issuecomment-2010731437
The only remaining point is:
We can't use `event_recipient_ids_for_action_on_messages` here because `attachement.messages` doesn't guarantee to have all messages be in a single conversation -- the generic function expects them to be in a single conversation.
<details>
</details>
=> Add hardening to avoid sending events / removing push notifications from users having no access to message.

puppet/kandra/files/install-aws-cli
=> puppet: Upgrade version of aws tool.

web/src/stream_popover.ts
**Previously, when the user provided an empty topic name, the confirm button was not disabled in both cases: when mandatory topics were enabled and disabled.**
Now:
- **For mandatory topics enabled:** The confirm button is disabled if the topic name is empty or explicitly set to `"(no topic)"`.
- **For mandatory topics disabled:** The confirm button remains enabled, allowing the user to leave the topic name input empty. In this case, the server does not rejects the empty string and the client sets the topic name to `"(no topic)"`.
For more information, see [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/Confirm.20move.20button.20stays.20enable.20when.20topic.20input.20is.200.2E/near/1989468)
https://github.com/user-attachments/assets/a9adb7b6-cf7f-44fc-a185-22707d7940ff …
=> Disable confirm move button when topic input is empty.

help/custom-emoji.md, help/restrict-direct-messages.md, help/restrict-message-editing-and-deletion.md, help/restrict-moving-messages.md, help/restrict-wildcard-mentions.md
Current:
- https://zulip.com/help/custom-emoji#change-who-can-add-custom-emoji
- https://zulip.com/help/restrict-direct-messages
- https://zulip.com/help/restrict-wildcard-mentions
- https://zulip.com/help/restrict-moving-messages
- https://zulip.com/help/restrict-message-editing-and-deletion
<details>
<summary>
Updated
</summary>
</details>
=> help: Update permissions docs for group-based permissions.

web/src/input_pill.ts, web/src/stream_create.ts, web/src/stream_create_subscribers.ts, web/src/stream_create_subscribers_data.ts, web/src/user_group_create_members.ts, web/templates/input_pill.hbs, web/templates/stream_settings/new_stream_user.hbs, web/tests/input_pill.test.cjs, web/tests/stream_create_subscribers_data.test.cjs
Fixes: #33125
Non disabled pill for non admin user:
Non disabled pill for admin user:
<details>
</details>
=> Add creator pill on the stream create screen

web/src/stream_popover.ts
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/move.20message.20channel.20select.20placement
| --- | --- |
| ![image](https://github.com/user-attachments/assets/3600b568-5d7b-4fd1-a449-4a66dbaad2b5) | ![Screenshot from 2025-01-29 18-08-44](https://github.com/user-attachments/assets/9f6778b8-b9c1-4122-994b-da4a9e4f96a5) |
=> move_topic_to_stream_widget: Show dropdown below stream button.

zerver/actions/message_summary.py, zerver/tests/fixtures/litellm/summary.json, zerver/tests/test_message_summary.py, zerver/views/message_summary.py, zproject/computed_settings.py, zproject/default_settings.py, zproject/dev_settings.py, zproject/prod_settings_template.py
=> Topic summary fixups

help/custom-emoji.md
Updates the instructions for adding a custom emoji for the current modal form.
---
[CURRENT DOCUMENTATION](https://zulip.com/help/custom-emoji)
<details>
</details>
=> help: Update add a custom emoji instructions for modal form.

web/src/read_receipts.ts
This removes the "Failed to load read receipts." prefix in the read receipt overlay in case of organizations that have disabled their read receipts.
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/Why.20the.20failure.20message.20on.20disabled.20read.20receipts.2E
| Before                     | After                      |
|----------------------------|----------------------------|
| ![before](https://github.com/user-attachments/assets/17168dd1-d89d-4445-bbf5-c4ce9b724c80) | ![after](https://github.com/user-attachments/assets/43f05c96-34f8-4130-b230-c57d4765be30) |
<details> …
=> message: Remove failure message for disabled read receipts.

web/src/navigate.ts
If the user is navigating via keyboard and the top / bottom of the message is not visible, we scroll instead of selecting the next message to allow user to completely see that message.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/long.20messages.20not.20completely.20readable
=> navigate: Fix user unable to read top / bottom of long messages.

web/src/message_view_header.ts, web/styles/message_view_header.css, web/styles/zulip.css
This commit adds support to render long descriptions on hovering over the narrow description.
Fixes #14729.
[Screencast from 12-13-2024 08:36:07 PM.webm](https://github.com/user-attachments/assets/a25454ee-b6dc-4782-99b7-bd41cda20c88)
<details>
</details>
=> top_navbar: Render long stream description on hover.

help/change-the-channel-description.md
current: https://zulip.com/help/change-the-channel-description
updated:
=> help: Document hovering over long channel descriptions to view them.

web/src/bundles/showroom.ts
This PR uses the same fix as the commit 6776e80, to include `bootstrap.portico.css` and prevent webpack from misordering it from the rest of the portico CSS chunk. This fixes the style inconsistencies in the help docs.
Related PR: #32746.
| ![Screenshot 2025-01-30 at 2 21 38 PM](https://github.com/user-attachments/assets/d97df686-2670-4b3e-9fe7-7a082eaa13b5) | ![Screenshot 2025-01-30 at 2 20 38 PM](https://github.com/user-attachments/assets/235feffc-b3c8-4a76-9074-e20901e6be22) | 
<details> …
=> showroom: Fix misordering of bootstrap.portico.css.

web/styles/popovers.css
Fixes: https://github.com/zulip/zulip/pull/33240#issuecomment-2623193230
| Before  | After  |
|---------|--------|
| ![image](https://github.com/user-attachments/assets/75d06ed6-d579-4190-8d26-55cb5a928d6c) | ![image](https://github.com/user-attachments/assets/a30f1fc8-4444-4446-9208-dfc5a5c4b7b0) |
=> user_profile: Fix deactivated user icon size.

web/src/search_suggestion.ts
Fixes #33246.
| Before             |  After|
:-------------------------:|:-------------------------:
=> searchbox: Avoid showing DM suggestions for topic pill.

help/direct-messages.md, help/reading-strategies.md
We now use "zulip-icon zulip-icon-all-messages" for the direct message feed icon in the left sidebar. Previously the icon used was "fa fa-align-right".
---
[Current documentation](https://zulip.com/help/direct-messages#access-all-dms)
[Current documentation](https://zulip.com/help/reading-strategies#direct-message-feed)
<details>
</details>
=> help: Update for direct message feed icon change in left sidebar.

web/src/user_group_edit.ts, web/templates/user_group_settings/group_permission_settings.hbs, web/templates/user_group_settings/user_group_settings.hbs
We now hide the "Organization permissions", "Channel permissions" and "User group permissions" heading if there are no permissions under that section after removing the permission.
Also, "This group has no assigned permissions" text is shown if the last permission for that group is removed.
<details>
</details>
=> user-groups: Fix live update of permissions panel on removing permission.

CONTRIBUTING.md
Current: https://zulip.readthedocs.io/en/latest/contributing/contributing.html#common-questions
=> contributor docs: Add a question about working on old issues.

api_docs/changelog.md, api_docs/message-formatting.md, version.py, web/src/copy_and_paste.ts, web/src/markdown.ts, web/src/rendered_markdown.ts, web/templates/channel_message_link.hbs, web/templates/topic_link.hbs, web/tests/copy_and_paste.test.cjs, web/tests/markdown.test.cjs, web/tests/markdown_parse.test.cjs, web/tests/rendered_markdown.test.cjs, web/third/marked/lib/marked.cjs, zerver/lib/markdown/__init__.py, zerver/tests/test_markdown.py
[CZO Discussion](https://chat.zulip.org/#narrow/channel/378-api-design/topic/general.20chat/near/2040374)
PR to add support for empty string as a valid topic name in syntaxes for linking to topics and messages in channels.
[Current API Docs](https://chat.zulip.org/api/message-formatting#links-to-channels-topics-and-messages)
<details><summary>Updated API Docs</summary>
</details> 
---
<details>
</details>
=> markdown: Add support for empty string as a valid topic name in syntaxes for linking to topics and messages.

zerver/data_import/import_util.py, zerver/data_import/slack.py, zerver/lib/import_realm.py, zerver/lib/thumbnail.py, zerver/migrations/0660_add_imageattachment_content_type.py, zerver/models/messages.py, zerver/tests/test_markdown_thumbnail.py, zerver/tests/test_slack_importer.py, zerver/tests/test_thumbnail.py, zerver/views/upload.py, zerver/worker/thumbnail.py
=> Thumbnail import

docs/translating/internationalization.md
"Conjugation" applies to verbs, not nouns.
=> contributor docs: Fix a nit.

web/src/group_permission_settings.ts, web/src/settings_config.ts, web/src/ui_init.js, web/templates/settings/organization_permissions_admin.hbs, zerver/views/streams.py
- First commit is to fix the bug of passing incorrect setting value in stream creation event.
- Second commit is to fix newly added settings not showing in "Permissions" panel and adding code to make sure that all new settings are shown as expected.
Fixes:  https://chat.zulip.org/#narrow/channel/9-issues/topic/unknown.20group_id.20error.20on.20creating.20stream.20via.20API
<details>
</details>
=> Fix couple of bugs related to group permission settings.

web/src/css_variables.ts, web/styles/app_variables.css, web/styles/settings.css, web/styles/subscriptions.css, web/templates/settings_overlay.hbs
Sorry that screenshots aren't exactly aligned, I still don't have software set up to do that.
---
12px
| before             |  after |
:-------------------------:|:-------------------------:
14px
| before             |  after |
:-------------------------:|:-------------------------:
16px 
| before             |  after |
:-------------------------:|:-------------------------:
18px 
| before             |  after |
:-------------------------:|:-------------------------:
20px 
| before             |  after |
:-------------------------:|:-------------------------:
=> settings: Use em for header instead of px.

scripts/lib/run_hooks.py
=> run_hooks: Diff to "last" instead of "current" during post-deploy.

web/styles/popovers.css, web/templates/popovers/user_card/user_card_popover.hbs, web/templates/popovers/user_card/user_card_popover_for_unknown_user.hbs
[CZO](https://chat.zulip.org/#narrow/channel/6-frontend/topic/disallowing.20user-selectable.20text.20on.20popovers/near/2063582)
<details>
</details>
=> Make user name selectable.

docs/outreach/overview.md
=> contributor docs: Add link to GSoC 2024 blog post.

tools/test-js-with-node, web/src/left_sidebar_tooltips.ts, web/src/tippyjs.ts, web/src/ui_init.js
[Follow up](https://github.com/zulip/zulip/pull/31433#discussion_r1929299042) PR
<details>
</details>
=> Extract left sidebar tooltips module.

docs/outreach/gsoc.md
=> contributor docs: Update GSoC mobile project for 2025.

web/src/message_view.ts
Extracted first 2 commits from  #32803
=> Improvements to narrow behaviour.

web/src/message_edit.ts, web/src/saved_snippets_ui.ts, web/templates/compose_control_buttons.hbs
This error occurred when opening the saved snippets dropdown while editing a message caused by `get_offset_to_window()` expecting a single JQuery element in the selected set. This function was used on `$(this.dropdown_input_visible_selector)` which is a class selector and can return multiple elements when multiple saved snippets buttons are rendered.
<details>
</details>
=> saved_snippets: Fix JQuery error.

zerver/lib/event_schema.py, zerver/lib/user_groups.py, zerver/tests/test_events.py, zerver/views/realm.py, zerver/views/streams.py, zerver/views/user_groups.py
These commits are all reviewed and will help shrink that PR.
=> Preparatory commits for #33371

docs/outreach/gsoc.md
I expect to add a few more in the coming weeks.
=> docs: Add a few new GSoC project ideas.

docs/outreach/gsoc.md
Please adjust as needed, since I'm kinda guessing based on the project descriptions here.
=> contributor docs: Consistently describe  project hours and difficulty.

zerver/actions/streams.py, zerver/lib/streams.py, zerver/lib/subscription_info.py, zerver/models/streams.py, zerver/tests/test_subs.py
=> stream: Metadata access followups.

web/src/drafts.ts, web/tests/drafts.test.cjs
[CZO bug report](https://chat.zulip.org/#narrow/channel/101-design/topic/general.20chat.20.2F.20default.20topic/near/2085869)
> If you have a draft with a topic that's not set, it looks like we show it as the general chat topic unconditionally in the drafts modal.
With `realm_mandatory_topics = true`:
<details>
</details>
=> drafts: Show empty string as topic when `realm_mandatory_topics=true`.

zerver/actions/message_edit.py, zerver/actions/message_send.py, zerver/actions/streams.py, zerver/lib/markdown/__init__.py, zerver/lib/mention.py, zerver/lib/streams.py, zerver/tests/test_markdown.py, zerver/tests/test_subs.py
`Commit 1`:
markdown: Fix #-mention of private channel's topic made by system bots.
`Commit 2`:
markdown: Fix stream description with topic permalink not rendered.
[CZO thread](https://chat.zulip.org/#narrow/channel/378-api-design/topic/topic.20permalinks/near/2085136)
<details>
</details>
=> Bug fixes related to rendering of #-mentions

web/src/message_summary.ts, web/src/unread_ops.ts, web/templates/topic_summary.hbs, zerver/actions/message_summary.py, zerver/tests/fixtures/litellm/summary.json, zerver/tests/test_message_summary.py
Seems to be working as expected.
=> message_summary: Add markdown support for generated summary.

help/channel-permissions.md, help/configure-who-can-administer-a-channel.md, help/configure-who-can-invite-to-channels.md, help/configure-who-can-unsubscribe-others.md, help/include/channel-admin-permissions.md, help/include/metadata-access-definition.md, help/include/sidebar_index.md, help/subscribe-users-to-a-channel.md, help/unsubscribe-users-from-a-channel.md, web/src/settings_components.ts, web/src/settings_config.ts, web/templates/stream_settings/stream_can_add_subscribers_group_label.hbs, web/templates/stream_settings/stream_types.hbs
- Explain how content access works.
- Label settings more accurately, and remove incorrect notes.
I'm out of time for the day, so I haven't had a chance to:
- Carefully test all changes.
- Write a good commit message.
- Split this into smaller commits (would want help with that anyway).
- Try to understand if any tests need to be updated (probably best left for someone else anyway).
- Take comprehensive screenshots.
Notes:
- For private channels with protected history, I assumed that your history starts from the time when you got content access. Didn't have time to test. If it's not like that, either the implementation or the documentation will need to be tweaked.
<details>
<summary>
Channel settings screenshots (new + existing)
</summary>
</details>
=> channel settings: Clarify channel permission settings.

web/styles/zulip.css
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/different.20field.20widths.20in.20invite.20modal)
|-------|--------|
<details>
</details>
=> styles: Fix different field widths in invite modal.

web/src/color_picker_popover.ts, web/templates/stream_settings/stream_settings.hbs
Fixes #33446
Clicking the "Channel color" label in the stream settings did not open the color picker, unlike other settings where clicking the label triggers the same action as clicking the value. This commit adds an event listener to the label that triggers the associated button's click event, ensuring consistent behavior across all settings.
<details>
</details>
https://github.com/user-attachments/assets/7c4f5a63-2e47-46b8-b149-8735144293f4
=> settings: Make clicking "Channel color" label open color picker

web/src/browser_history.ts, web/src/echo.ts, web/src/filter.ts, web/tests/echo.test.cjs, web/tests/filter.test.cjs
This commit updates the traditional url of a channel-topic narrow to topic permalink upon arrival of new message in the narrow, by using the `with` operator on it.
The requirement for this change arises when we navigate to an empty topic. Since it has no messages yet, we fallback to the traditional channel-topic links. However, when a new message arrives to this empty topic, we want the url to live update to a permalink of the narrow.
This is done as an effort to make sure channel-topic narrows always contain `with` term.
Contains cherry-picked changes as per https://github.com/zulip/zulip/pull/31152#discussion_r1945751414
<details>
Individual …
=> echo: Update channel-topic link to permalink upon new message arrival.

docs/production/video-calls.md
=> docs: Tweak descriptions of Zoom app options.

web/src/admin.ts, web/src/popover_menus_data.ts, web/src/settings_data.ts, web/templates/settings/organization_permissions_admin.hbs, web/tests/settings_data.test.cjs
- First commit is for updating the banner for cloud.
- Second commit is to have server level check in `user_can_summarize_topics`.
<details>
</details>
=> Follow-ups of #33436.

zerver/actions/streams.py, zerver/lib/streams.py, zerver/lib/subscription_info.py, zerver/lib/user_groups.py, zerver/tests/test_subs.py
This PR updates code to optimize computing users who have metadata access via
permission groups so that we do not have to do DB query for each stream to get
recursive members for the groups having permissions.
<details>
</details>
=> streams: Optimize computing users with metadata access.

scripts/lib/upgrade-zulip-stage-3
=> upgrade-zulip: Prevent restarting only Django into inconsistent caching.

help/link-to-a-message-or-conversation.md, help/move-content-to-another-topic.md, help/rename-a-topic.md
- Also note that channel links are permanent.
- Adjust related pages.
=> help: Document permanent topic links. 

web/src/compose_reply.ts
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/.22quote.20message.22.20not.20working.20in.20archived.20channels).
**Commit 1 Changes:**
- Add error handling logic when the error occurs.
<details>
</details>
=> compose_reply: Add error handling when trying to quote a message from archived stream.

web/templates/left_sidebar.hbs
This PR removes aria-hidden for left-sidebar 3 dots menu and as per [conversation](https://chat.zulip.org/#narrow/channel/101-design/topic/left.20sidebar.203-dots.20menus), appropriate aria-labels for left sidebar 3 dots menu has been given.
Fixes: #20284 
<details>
</details>
=> aria-labels: Added aria-labels for left-sidebar 3 dots menu

zerver/tests/test_tornado.py
https://chat.zulip.org/#narrow/channel/43-automated-testing/topic/main.20failing/near/2092140
=> test_tornado: Add nocoverage for task cleanup

zerver/lib/zulip_update_announcements.py
I haven't tested via devtools.
[see CZO](https://chat.zulip.org/#narrow/channel/438-release-management/topic/zulip_updates.20items.20of.20note/near/2091969) for screenshots/discussion
=> updates: Add update message (level=12).

zerver/lib/streams.py, zerver/tests/test_message_flags.py
Commit 1: We're going to be adding a new setting called `can_join_group` soon and it would be good to have this wrapper function ready for it to be used in.
Commit 2: Test refactor to make it more readable.
Fixes: 
<details>
</details>
=> stream: Function to check if user is in groups granting content access.

zerver/lib/cache_helpers.py
This is simply too time-intensive, at scale, to perform during the critical period of an upgrade.  The most performance-critical codepaths (Tornado and presence) have moved to the narrow user cache, which we continue to pre-fill.
=> cache_helpers: Stop pre-filling the non-narrow user cache.

zerver/lib/import_realm.py
The `lock=true` parameter fails, since it is not being run inside of a transaction.  We swap to not using locking, since there is no correctness requirement for a lock here.
=> import_realm: Skip lock=true when enqueuing thumbnailing.

web/styles/search.css
=> search: Fix Ctrl+Backspace whitespace removal on typing.

web/styles/popovers.css, web/styles/reactions.css
at 12px, 14px, 16px, 20px
without search
| --- | --- |
| ![Screen Shot 2025-02-18 at 12 50 05](https://github.com/user-attachments/assets/4b080b92-cc7e-4254-bcca-e72a1fc6b883) | ![Screen Shot 2025-02-18 at 12 57 28](https://github.com/user-attachments/assets/122aca06-7770-4190-a83e-8acc6a373286) |
| ![Screen Shot 2025-02-18 at 12 50 52](https://github.com/user-attachments/assets/6a24f15d-e95c-4f66-ac5e-b5d8a6198c54) | ![Screen Shot 2025-02-18 at 12 55 21](https://github.com/user-attachments/assets/85819f6f-30f5-4ebf-8008-e4fdb6a799d1) |
| ![Screen Shot 2025-02-18 at 12 51 25](https://github.com/user-attachments/assets/c71c249b-b601-4079-b9c2-3ca88a141213) | ![Screen Shot 2025-02-18 at 12 58 16](https://github.com/user-attachments/assets/85556007-3f00-4d3d-9aeb-f9238fe960 …
=> emoji: Scale emoji popover with em.

web/styles/compose.css
=> compose: Fix em calculation errors.

web/styles/modal.css
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/todo.20list.20modal.20side.20scrolling
| Before | After|
| ![image](https://github.com/user-attachments/assets/ca0eef31-677e-4089-9cd2-6301424c7847)| ![image](https://github.com/user-attachments/assets/98b6aee3-be4e-421a-aada-e36b99212f96)| 
<details>
</details>
=> todo_modal: Remove side scrolling in the todo modal.

web/styles/app_variables.css
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark
- https://www.npmjs.com/package/@csstools/postcss-light-dark-function
- [Discussion](https://chat.zulip.org/#narrow/channel/6-frontend/topic/CSS.20light-dark.28.29/near/2095416)
=> app_variables: Use CSS `light-dark()`

web/styles/app_variables.css, web/styles/color_picker.css, web/styles/compose.css
- Followup to #33530.
- [Discussion](https://chat.zulip.org/#narrow/channel/6-frontend/topic/CSS.20light-dark.28.29/near/2096414).
=> app_variables: Fix `light-dark()` conversion of gradients

puppet/kandra/files/hooks/post-deploy.d/zulip_notify_schema_diff.hook, puppet/kandra/manifests/hooks/file.pp, puppet/kandra/manifests/hooks/zulip_notify_schema_diff.pp, puppet/kandra/manifests/prod_app_frontend_once.pp, puppet/zulip/files/hooks/common/zulip_notify.sh, puppet/zulip/files/hooks/post-deploy.d/zulip_notify.hook, puppet/zulip/files/hooks/pre-deploy.d/zulip_notify.hook, puppet/zulip/manifests/hooks/zulip_common.pp, puppet/zulip/manifests/hooks/zulip_notify.pp
=> kandra: Add a hook to notify of local schema drift from merge-base.

help/collaborative-to-do-lists.md, help/format-your-message-using-markdown.md, help/include/to-do-lists-examples.md
Adds a tip for creating a collaborative to-do list via the new compose box button in the markdown formatting article.
Edits the include examples for to-do lists so that the note about marking a task as complete/incomplete is text before the example screenshot.
Revises the collaborative to-do list article for a missing comma, and adjusts some line wrapping.
Fixes #33522.
---
<details>
<summary>Format your message: collaborative to-do lists</summary>
[CURRENT DOCUMENTATION](https://zulip.com/help/format-your-message-using-markdown#collaborative-to-do-lists)
</details>
<details>
<summary>Collaborative to-do lists</summary>
[CURRENT DOCUMENTATION](https://zulip.com/help/collaborative-to-do-lists)
</details>
---
<details> …
=> help: Add create a to-do list via compose box button tip.

web/src/click_handlers.ts, web/src/compose_state.ts, web/src/message_list.ts, web/src/message_list_view.ts, web/src/recent_view_ui.ts, web/src/stream_list.ts, web/styles/message_header.css, web/templates/recipient_row.hbs, web/tests/popover_menus_data.test.cjs
Bug fixes while auditing `if (topic)` types of check.
Commit messages explain the fixes.
<details>
</details>
=> Empty string topic related bugs.

help/direct-messages.md, help/include/send-dm.md, help/typing-notifications.md, zerver/lib/markdown/tabbed_sections.py
@timabbott the first commit can be merged if you want.
@laurynmm  could you please finish the changes I started on the DMs page? Tasks I'm aware of:
- Fleshing out the instructions for viewing DMs from each place, and making sure all the tabs exist.
- Checking if any anchor links need to be updated.
=> help: Update typing notifications and DMs docs.

web/templates/message_controls.hbs
This fixes a flaky failing test introduced by #33550 by preventing the actual stars button from rendering on local echo.
While this stop-gap measure should fix the flake, post-10.0 we probably should revisit the use of checking for the side-effect appearance of `.star` in the DOM, e.g., in `wait_for_fully_processed_message()`, and instead do something to check against the presence of the `.locally-echoed` class.
<details>
</details>
=> stars: Await .zulip-icon-star in the DOM.

scripts/lib/zulip_tools.py, zerver/lib/cache.py
When flushing caches, we want to ensure that even processes which may have a wrong cache-key-prefix know to fetch the latest data from the database.  This is complicated by the cache-key-prefixes being stored on disk, and thus checking that every cache delete is not sufficiently performant.
We store the list of cache-key-prefixes in the cache, itself, with no prefix.  This cache is updated when a new cache-key is written, and is also allowed to lapse after 24 hours.  Updating this global cache entry on new prefix creation ensures that even a not-yet-restarted-into deployment will have its caches appropriatelypurged if changes are made to the underlying data.
However, this both adds a cache-get, as well as multiplies the size of all cache clears; for large bulk clears (e.g. for stream …
=> cache: Flush caches from all known key prefixes.

api_docs/changelog.md, version.py, web/src/composebox_typeahead.ts, web/src/stream_data.ts, web/tests/composebox_typeahead.test.cjs, web/tests/stream_data.test.cjs, zerver/lib/mention.py, zerver/lib/message.py, zerver/lib/streams.py, zerver/lib/subscription_info.py, zerver/lib/user_groups.py, zerver/tests/test_markdown.py, zerver/tests/test_message_edit.py, zerver/tests/test_message_flags.py, zerver/tests/test_message_move_stream.py, zerver/tests/test_message_send.py, zerver/tests/test_reactions.py, zerver/tests/test_subs.py, zerver/views/invite.py, zerver/views/streams.py
=> Extend has_message_access

help/direct-messages.md, help/include/how-to-start-a-new-topic.md, help/include/start-topic-via-left-sidebar.md, help/include/view-dms-left-sidebar.md, help/left-sidebar.md
Notes:
- Add instructions for starting new conversations.
- Update style to be more consistent with other pages.
- Tweaks on other pages are very minor.
Current: https://zulip.com/help/left-sidebar
<details>
<summary>
Updated
</summary>
</details>
=> help: Improve left sidebar documentation.

web/styles/inbox.css
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/search.20box.20in.20Inbox/with/2099323
| --- | --- |
| ![Screenshot 2025-02-23 093841](https://github.com/user-attachments/assets/f49a7cfa-096c-4740-ace1-3c680dbe83cb) | ![Screenshot 2025-02-23 093822](https://github.com/user-attachments/assets/facec305-ad23-456a-b4f8-55f503cf634b) |
=> inbox: Fix width of inbox search input at different window sizes.

web/src/drafts_overlay_ui.ts, web/styles/app_components.css, web/templates/draft.hbs, web/tests/drafts.test.cjs
This pull request introduces a feature to copy drafts in the drafts overlay UI. 
This is completion of the PR #26587.
---
Fixes: [CZO discussion](https://chat.zulip.org/#narrow/stream/137-feedback/topic/copy.20feature.3A.20drafts).
| ![Before](https://github.com/user-attachments/assets/ab51e25e-67d4-404f-bd2a-8fb8ec88d254) | ![After](https://github.com/user-attachments/assets/63e08b3a-ecd4-4dbd-bc3d-2e21eece8b89) |
| ![Before](https://github.com/user-attachments/assets/4390f88e-c602-430b-942e-1671fd7d2580) | ![After](https://github.com/user-attachments/assets/59da0f02-99e1-4d73-b21d-84fb8a1b1d57) |
<details>
<summary>Demo</summary>
https://github.com/user-attachments/assets/dcc53107-0c93-4b34-82b0-9dfae8e181c1 …
=> drafts: Add a copy draft button.

web/src/settings_components.ts, web/templates/settings/organization_settings_admin.hbs
Fixes:  https://chat.zulip.org/#narrow/channel/101-design/topic/Settings.20.2F.20Organization.20settings.20.3E.20Other.20settings/with/2099277
<details>
</details>
=> settings: Rearrange "Other settings" section.

web/src/input_pill.ts
Previously, if an invalid user was entered in the recipient field, the input box would shake to indicate an error but also move the cursor to the message field. This was unintended and disrupted the user experience.
This commit ensures that the focus remains in the recipient field when the input is invalid, preventing premature cursor movement.
**Screen captures:**
|   |   |
|---|---|
|Before|![Screencast_20250223_062533-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/e4fe195e-2b1b-4379-a89e-2bb16516fd80)|
|After|![Screencast_20250223_062123-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/32bf745e-3d7b-4c51-b684-ecd8b4ca2a88)|
<details> …
=> compose: Keep focus on recipient field when input is invalid.

web/src/clipboard_handler.ts, web/src/message_actions_popover.ts, web/src/stream_popover.ts, web/src/topic_link_util.ts, web/src/topic_popover.ts, web/tests/clipboard_handler.test.cjs, web/tests/topic_link_util.test.cjs
Copying link results in both plain text URL and HTML.
Fixes: #31813.
When you copy a link to a stream, topic, or message, it is currently copied to the clipboard in two formats: text/plain, text/html, text/text/x-gfm.
Fixes: 
https://github.com/user-attachments/assets/c3709ff9-09a6-4ced-aafe-001ab2641a89
<details>
</details>
=> popovers: Copied Zulip links include a GitHub Format Markdown variant.

help/quote-or-forward-a-message.md
Current: https://zulip.com/help/quote-or-forward-a-message
Updated:
=> help: Improve "Quote or forward a message" intro.

help/create-a-poll.md, help/format-your-message-using-markdown.md, help/include/polls-examples.md, help/include/polls-intro.md
Creates an intro and an examples md file for the shared content on the "Message formatting" article and "Polls" article.
*No content/rendering of the Polls article is changed, so not including a screenshot below.*
---
<details>
</details>
=> help: Add polls section to "Message formating" article.

api_docs/writing-bots.md
Fixes: #32580 
[Doc link](https://zulip.com/api/writing-bots)
Commit 1 - Clarify `.contains()`
Commit 2 - Document the context manager
<details>
</details>
=> Document the context manager for bot storage

help/change-the-channel-description.md, help/include/go-to-channel.md, help/include/sidebar_index.md, help/introduction-to-channels.md, help/rename-a-channel.md, help/view-channel-information.md, help/view-channel-subscribers.md
=> help: Add a page on viewing channel information from message view.

web/tests/composebox_typeahead.test.cjs
Fixing test failure from
6d30b10b60064b75ab11ef7db44ac1634bcf8a38.
=> composebox_typeahead: Fix failing tests.

api_docs/changelog.md, version.py, zerver/actions/users.py, zerver/lib/events.py, zerver/lib/streams.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_subs.py, zerver/views/streams.py
=> get_streams: Add `include_can_access_content` and rename `include_all_active`

web/src/settings_users.ts
Previously, the role count and user list in the active and deactivated users sections were not updated live upon reactivation/deactivation.
This PR introduces live updates for both the user lists and the corresponding role counts.
Fixes: #33566.
| Before                                                                                      | After                                                                                       |
|---------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| ![before](https://github.com/user-attachments/assets/92a9bf3c-0796-47b0-b2a0-d20aff8d146e) | …
=> settings_users: Live update of user list and role count.

api_docs/group-setting-values.md
Revises some additional text in the main description for clarity.
[CURRENT DOCUMENTATION](https://zulip.com/api/group-setting-values)
---
<details>
</details>
=> api-docs: Describe object format of group-setting as anonymous group.

pyproject.toml, uv.lock, version.py, zerver/forms.py, zerver/lib/test_helpers.py, zerver/lib/zephyr.py, zerver/tests/test_external.py, zerver/tests/test_message_send.py, zerver/tests/test_mirror_users.py, zerver/tests/test_signup.py
[Discussion](https://chat.zulip.org/#narrow/channel/3-backend/topic/uv/near/2102876).
=> Remove py3dns

help/include/sidebar_index.md, help/introduction-to-users.md, help/link-to-a-message-or-conversation.md, help/manage-user-groups.md, help/user-cards.md, help/user-groups.md, help/user-list.md, help/view-group-members.md, help/view-someones-profile.md, zerver/lib/markdown/tabbed_sections.py
<details>
<summary>
Introduction to users
</summary>
</details>
<details>
<summary>
View group members
</summary>
</details>
Current: https://zulip.com/help/user-cards
<details>
<summary>
Updated user cards info
</summary>
</details>
=> help: New and updated pages.

web/styles/message_row.css
This fixes an annoying regression introduced by #33593 that again caused a text reflow after a locally echoed message was acknowledged by the server.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/messages.20reflowing.20after.20local.20echo/near/2102730)
| --- | --- |
| ![reflow-bug-before](https://github.com/user-attachments/assets/8a4faa50-6c0d-4cfb-95f5-b2899a32642a) | ![reflow-bug-after](https://github.com/user-attachments/assets/485ff8db-0c9f-4169-a470-f508733a5c74) |
<details> …
=> stars: Placehold container width in local echo.

web/src/copy_and_paste.ts
See: https://stackoverflow.com/questions/23934656/how-can-i-copy-rich-text-contents-to-the-clipboard-with-javascript/71850835#71850835
Fixes:
https://chat.zulip.org/#narrow/channel/9-issues/topic/pasting.20LaTeX/with/2099736.
=> copy_and_paste: Fix copy pasting LaTeX using navigator and smartly select expressions within math blocks

web/src/clipboard_handler.ts, web/src/copy_and_paste.ts
=> cleanup copy_and_paste

web/templates/stream_settings/new_stream_users.hbs, web/templates/stream_settings/stream_settings_overlay.hbs, web/templates/user_group_settings/new_user_group_users.hbs, web/templates/user_group_settings/user_group_settings_overlay.hbs, web/templates/user_profile_modal.hbs
=> settings: Rename `Filter x` to `Filter` for channel and group settings.

web/styles/popovers.css
This PR makes sure that the top margin is unset from the move messages count paragraph if it is empty, fixing the layout in the move topic modal while renaming a topic.
Fixes: [CZO thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/spacing.20on.20the.20move.20topic.20modal).
|--------------|-------------|
| ![image](https://github.com/user-attachments/assets/e5bff66e-4cdb-46e6-9c8a-e932d0fac654) | ![image](https://github.com/user-attachments/assets/482c156a-ea3a-41e7-a834-f5bb3dccd9dc) |
---
<details> …
=> css: Remove `margin-top` from move messages count if empty.

help/custom-emoji.md, help/include/user-groups-intro.md, help/include/user-roles-intro.md, help/introduction-to-users.md, help/restrict-account-creation.md, help/restrict-bot-creation.md, help/restrict-direct-messages.md, help/restrict-message-editing-and-deletion.md, help/restrict-moving-messages.md, help/restrict-wildcard-mentions.md, help/view-group-members.md, templates/corporate/for/business.html, templates/corporate/for/education.html, templates/corporate/for/open-source.html, templates/corporate/for/research.html
Updates "help/manage-a-user" links that are contextually for general information about users to go to the new "help/introduction-to-users" article.
Adds a link to "Manage a user" in the related articles section of the new intro to users article.
Follow up to #33651.
---
<details>
</details>
=> help: Update links for information about users to new intro article.

web/src/compose_actions.ts, web/src/compose_fade.ts, web/src/compose_fade_helper.ts, web/src/compose_recipient.ts, web/src/compose_setup.js, web/src/compose_state.ts, web/src/compose_ui.ts, web/src/composebox_typeahead.ts, web/src/drafts_overlay_ui.ts, web/src/dropdown_widget.ts, web/src/message_view.ts, web/src/server_events_dispatch.js, web/src/typeahead_helper.ts, web/src/ui_init.js, web/styles/compose.css, web/templates/compose.hbs, web/templates/typeahead_list_item.hbs, web/tests/compose.test.cjs, web/tests/compose_actions.test.cjs, web/tests/compose_fade.test.cjs, web/tests/compose_state.test.cjs, web/tests/compose_ui.test.cjs, web/tests/compose_validate.test.cjs, web/tests/composebox_typeahead.test.cjs, web/tests/dispatch.test.cjs, web/tests/lib/events.cjs, web/tests/message_view.test.cjs
#33581
Addressed https://github.com/zulip/zulip/pull/33465#discussion_r1964122080
<details>
</details>
=> compose: Handle *general chat* in topic box.

web/styles/typeahead.css
Fixes #31392
| --- | --- |
| ![image](https://github.com/user-attachments/assets/231aa9cf-4701-45a3-ba44-94100b977119) | ![Screenshot 2025-02-25 134014](https://github.com/user-attachments/assets/371753d7-7450-40a9-9c0f-acaa9eb06ee9) |
| ![Screenshot 2025-02-25 134041](https://github.com/user-attachments/assets/c6adb4f1-135c-46b5-9c5c-c85b3726f86e)  | ![Screenshot 2025-02-25 134026](https://github.com/user-attachments/assets/08c62593-5dc9-427c-b6bb-1c54a57d65dd) |
=> Fix related to long stream and topic names.

zerver/tests/test_message_summary.py
discussion: [#automated testing > main failing @ 💬](https://chat.zulip.org/#narrow/channel/43-automated-testing/topic/main.20failing/near/2106959)
Tests were failing due to credit usage being capture in the next month instead of current if the current time is last day of the month. To fix this, we mock current time to not be the last day of any month.
=> test_message_summary: Fix failing tests.

web/styles/alerts.css
Fixes: [#redesign project > broader range of font sizes @ 💬](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/broader.20range.20of.20font.20sizes/near/2099767)
| | Connection Alert | Zephyr Alert |
| 12px | ![connection-alert-12px](https://github.com/user-attachments/assets/6b5f086e-7e26-49a2-91bb-c9ba3227b38e) | ![zephyr-alert-12px](https://github.com/user-attachments/assets/81d629f8-4c12-4094-8080-5769fcc145f4) |
| 16px | ![connection-alert-16px](https://github.com/user-attachments/assets/cb288c20-ca62-4721-88dd-64d823ed82ce) | ![zephyr-alert-16px](https://github.com/user-attachments/assets/4c5e9981-d91b-4d84-a401-347198ff62c1) | 
| 20px | ![connection-alert-20px](https://github.com/user-attachments/assets …
=> alerts: Enable font scaling in alert banners.

zerver/tests/test_markdown.py
It's good to verify the claims we are making in the comments before the actual test code block.
Fixes: https://github.com/zulip/zulip/pull/33507#discussion_r1966303815
<details>
</details>
=> test_markdown: Add content and metadata access asserts.

web/src/activity_ui.ts, web/src/buddy_data.ts
[#issues > 🎯 "this conversation" section missing for general chat @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20.22this.20conversation.22.20section.20missing.20for.20general.20chat/near/2107886)
> The "this conversation" section is missing from the right sidebar in the "general chat" topic. Example: [#test here > general chat](https://github.com/#narrow/channel/7-test-here/topic//with/2054670)
<details>
</details>
=> buddy_list: Fix missing 'THIS CONVERSATION' section for 'general chat'.

zerver/webhooks/github/doc.md
Current: https://zulip.com/integrations/doc/github
Updated:
=> integrations: Update GitHub intergation for new configuration UI.

analytics/lib/counts.py
I checked that this also fixes the test failure addressed by #33722.
- Closes #33723.
=> counts: Fix current_month_accumulated_count_for_user bounds

web/templates/settings/organization_permissions_admin.hbs
We don't yet have the documentation that would allow organization administrators to make decisions about what value to use for this experimental setting.
@sahil839 @amanagr FYI.
=> settings: Hide realm topic summarization setting.

docs/overview/release-lifecycle.md, docs/production/mobile-push-notifications.md, docs/production/settings.md, docs/production/upgrade.md, zerver/lib/zulip_update_announcements.py
While working on the changelog, I noticed that the server settings page's docs were very stale, so I put a commit updating those in this PR as well.
We can move it to a near-term follow-up PR if desired, but it probably wants the same folks involved in reviewing/editing it.
=> Release 10.0-beta1 and improve server settings documentation.

web/styles/zulip.css
at 12px, 14px, 16px, 20px
| --- | --- |
| ![Screen Shot 2025-02-20 at 22 08 57](https://github.com/user-attachments/assets/8609f54a-0ecc-4301-ab87-46edc820b9c5) | ![Screen Shot 2025-02-20 at 22 02 27](https://github.com/user-attachments/assets/f11030a3-6e5f-4109-b4bb-8a92956e407d) |
| ![Screen Shot 2025-02-20 at 22 08 48](https://github.com/user-attachments/assets/75c1c4a4-313d-43fb-849e-c31f69b138e0) | ![Screen Shot 2025-02-20 at 22 02 33](https://github.com/user-attachments/assets/5488bc9c-f2be-4217-8dd7-a40fc297f615) |
| ![Screen Shot 2025-02-20 at 22 08 41](https://github.com/user-attachments/assets/9062681d-1549-4852-8332-aef32c9c4e2c) | ![Screen Shot 2025-02-20 at 22 02 41](https://github.com/user-attachments/assets/c667273b-57dc-41fb-9f74-241780e3b3c5) |
| …
=> search: Scale message feed banner text with em.

web/src/click_handlers.ts, web/src/message_view.ts, web/styles/left_sidebar.css, web/styles/portico/stats.css, web/styles/zulip.css
discussion: https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/broader.20range.20of.20font.20sizes/with/2109658
=> tooltip: Remove dead code related to old tooltips system.

web/src/add_subscribers_pill.ts, web/src/group_setting_pill.ts, web/src/user_group_pill.ts, web/styles/input_pill.css, web/templates/input_pill.hbs, web/tests/user_group_pill.test.cjs
Instead of showing count as "N users", we just show the count in parentheses now.
Fixes #33628.
<details>
</details>
=> groups: Update how we show members count in group pills.

docs/documentation/api.md
=> docs: Document new `create-api-changelog` tool.

docs/contributing/continuing-unfinished-work.md
I'm totally fine with examples being adjusted, just think we want something here.
Current: https://zulip.readthedocs.io/en/latest/contributing/continuing-unfinished-work.html#present-your-pull-request
Updated:
=> contributor docs: More guidance on explaining your PR vs. prior ones.

web/styles/rendered_markdown.css
[CZO discussion](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/scaling.20of.20image.20previews/near/2110356)
| Before (16px) | After |
| --- | --- |
| ![thumbnails-before](https://github.com/user-attachments/assets/650cab81-f12a-4238-b0c6-fc60807e5b82) | ![thumbnails-after](https://github.com/user-attachments/assets/656ac2b5-a064-47c4-b991-e9a8c43b8772) |
<details>
</details>
=> thumbnails: Express dimensions in rounded ems.

web/styles/portico/hello.css
I was not able to capture the animation for logo change in my screen capture tool but it is working now.
https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20no.20animation.20on.20zulip.2Ecom.20logos/with/2110187
=> hello: Fix background animation broken for customer logos.

web/styles/modal.css
This PR removes a possible native horizontal scrollbar at certain info-density settings when zooming in or out.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/extraneous.20horizontal.20scroll.20bar.20in.20modal/near/2106708)[#issues > extraneous horizontal scroll bar in modal @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/extraneous.20horizontal.20scroll.20bar.20in.20modal/near/2106708)
| --- | --- |
| ![delete-modal-before](https://github.com/user-attachments/assets/42af904d-30fa-444b-953d-d9fa446b2103) | ![delete-modal-after](https://github.com/user-attachments/assets/9627d659-7973-4f42-a134-ff01991e920d) |
<details> …
=> modals: Prevent possible native horizontal scrollbar.

web/styles/widgets.css
This is for the box with the number in it.
----
12px, 14px, 16px, 20px:
| --- | --- |
| ![Screen Shot 2025-03-03 at 18 19 47](https://github.com/user-attachments/assets/47739085-f0e1-4213-991a-fda72ead0f88) | ![Screen Shot 2025-03-03 at 18 19 17](https://github.com/user-attachments/assets/337883c4-94fc-43fa-9bf7-26652f48bd9b) |
| ![Screen Shot 2025-03-03 at 18 19 54](https://github.com/user-attachments/assets/9b42ddb5-18c6-4676-9764-99dda2474a7b) | ![Screen Shot 2025-03-03 at 18 19 07](https://github.com/user-attachments/assets/d247144c-9d56-4a5a-ae1f-35b24edc8d6b) |
| ![Screen Shot 2025-03-03 at 18 20 01](https://github.com/user-attachments/assets/273842bd-87fc-4688-94f7-94528a79e134) | ![Screen Shot 2025-03-03 at 18 18 …
=> polls: Scale poll votes with info density.

zerver/migrations/0680_rename_general_chat_to_empty_string_topic.py
[#backend > general chat - migration discussion @ 💬](https://chat.zulip.org/#narrow/channel/3-backend/topic/general.20chat.20-.20migration.20discussion/near/2106369)
> So the /near/ links to messages in [#test here > general chat @ 💬](https://github.com/#narrow/channel/7-test-here/topic//near/2105258) don't work following this migration. That deserves investigation -- I'd have expected them to work.
> A solution that might be less hacky would be for the edit history to reflect a move from topic "general chat" to topic "". I.e. instead of retconning the old "general chat" topic as having secretly been "" all along, effectively move the topic from its old home to its new one.
> That would I think more accurately reflect the actual sequence of what happened. And one consequence is that I …
=> migrations: Update `rename_general_chat_to_empty_string_topic` migration.

web/src/filter.ts, web/src/hash_parser.ts, web/src/message_view.ts, web/src/search_suggestion.ts, web/tests/filter.test.cjs, web/tests/hashchange.test.cjs, web/tests/search_suggestion.test.cjs, zerver/lib/narrow.py, zerver/tests/test_message_fetch.py
[CZO thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/is.3Aresolved.20filter.20incorrectly.20hidden.20for.20logged.20out.20users)
Fixes: #33568.
<details>
</details>
=> narrow: Allow spectators to use `is:resolved`.

web/styles/settings.css
| --- | --- |
| ![Screen Shot 2025-03-04 at 12 20 22](https://github.com/user-attachments/assets/45e358e2-cd65-4007-be9d-9d7ff9332bb1) | ![Screen Shot 2025-03-04 at 12 20 52](https://github.com/user-attachments/assets/47b53b1e-8263-49f7-b59b-0221b1fc2393) |
| ![Screen Shot 2025-03-04 at 12 20 04](https://github.com/user-attachments/assets/eb5c730b-38c8-4fc6-9611-7c5641f2141e) | ![Screen Shot 2025-03-04 at 12 21 09](https://github.com/user-attachments/assets/5663a6bf-b2d6-4caa-98b4-da21ffab3872) |
| ![Screen Shot 2025-03-04 at 12 19 42](https://github.com/user-attachments/assets/0af895f4-2412-4da2-baf7-aa20aec0365b) | ![Screen Shot 2025-03-04 at 12 21 34](https://github.com/user-attachments/assets/2e2a4a8f-54bf-4542-bf6f-9a5dae57a16a) |
| …
=> settings: Scale notification sound icon with font size.

scripts/lib/run_hooks.py, scripts/lib/upgrade-zulip-stage-3
The refactoring in 4e28e1d3ffa9 incorrectly switched a check for `if args.from_git` into `if NEW_ZULIP_MERGE_BASE`, which is incorrect -- the merge-base is always defined, it may just match the version.  This led to errors when installing from tarball, without a git repo.
Since the run_hooks command was already set up to take a `--from-git` argument, but was ignoring it, pass down that flag from upgrade-zulip-stage-3 when necessary, and swap the run_hooks logic back to basing the version-resolution logic on that flag.
Fixes: 
<details> …
=> run_hooks: Pass down, and respect, --from-git argument.

web/src/settings_data.ts, web/src/user_group_edit.ts, web/src/user_groups.ts, web/styles/subscriptions.css, web/templates/popovers/user_group_info_popover.hbs, web/templates/user_group_settings/browse_user_groups_list_item.hbs, web/templates/user_group_settings/user_group_settings.hbs, web/templates/user_group_settings/user_group_settings_empty_notice.hbs, web/templates/user_group_settings/user_group_settings_overlay.hbs, web/tests/settings_data.test.cjs
Fixes #32877.
(Dark)
| before.png  | deactivated.png   | all.png   | active.png   |
|-------------|-------------|-------------|-------------|
| ![before.png](https://github.com/user-attachments/assets/77477c8e-9cb5-404e-bd6e-2610ac45dfa5) | ![image.png](https://github.com/user-attachments/assets/3d98b3bd-1eeb-4783-80bc-b7efa283859f) | ![image.png](https://github.com/user-attachments/assets/a88eb00f-e122-4e57-b8e7-daef148beed4) | ![image.png](https://github.com/user-attachments/assets/0a96a2bd-8818-48c2-970d-92a4642afbcd) |
(Light)
| before.png  | deactivated.png   | all.png   | active.png   |
|-------------|-------------|-------------|-------------|
| ![before.png](https://camo.githubusercontent.com/9b7c6eb7c950dc6da825ab2c8e7c910b6ac80e5f77fa52bec1faf1d389565823/68747470733a2f2f636861742e …
=> group_settings: Show all, active and deactivated groups.

web/styles/left_sidebar.css, web/styles/right_sidebar.css
PR makes both `stream cursor` and tab navigation to use same css properties.
Fixes: zulip#32880.
<details>
</details>
=> Redesign selection boxes for keyboard navigation in sidebars

web/styles/input_pill.css
| --- | --- |
| ![Screen Shot 2025-03-04 at 16 03 50](https://github.com/user-attachments/assets/38283c02-6d3f-4903-81ad-71fd0485c5c7) | ![Screen Shot 2025-03-04 at 16 03 17](https://github.com/user-attachments/assets/a20ce278-cb67-46c7-a0e8-6644e5845274) |
| ![Screen Shot 2025-03-04 at 16 03 58](https://github.com/user-attachments/assets/c3280f7c-d1e2-4243-9b68-513f9528d9d1) | ![Screen Shot 2025-03-04 at 16 03 07](https://github.com/user-attachments/assets/d0a6694b-9a3b-4e14-898a-1b1d257a073f) |
| ![Screen Shot 2025-03-04 at 16 04 06](https://github.com/user-attachments/assets/8448742c-efcc-43e6-a312-89a4ab380fea) | ![Screen Shot 2025-03-04 at 16 02 56](https://github.com/user-attachments/assets/39c194ef-7512-47c2-b87a-e0f75884a057) |
| …
=> input_pill: Scale user group pill icon with font size.

web/styles/modal.css
| --- | --- |
| ![Screen Shot 2025-03-04 at 16 27 21](https://github.com/user-attachments/assets/b0381d9e-ff40-4a4b-ad3d-1c4247e069a2) | ![Screen Shot 2025-03-04 at 16 19 06](https://github.com/user-attachments/assets/696e5d8f-850f-4f40-82e6-4b334153bff9) |
| ![Screen Shot 2025-03-04 at 16 27 12](https://github.com/user-attachments/assets/b86d3d4b-662d-4f4a-97eb-66f4c3d58ac0) | ![Screen Shot 2025-03-04 at 16 18 57](https://github.com/user-attachments/assets/9a00070b-469e-4d96-a0c1-10f88a672c1a) |
| ![Screen Shot 2025-03-04 at 16 27 05](https://github.com/user-attachments/assets/4fdf9438-1d0a-41d5-8ba7-f9b0721433b1) | ![Screen Shot 2025-03-04 at 16 18 47](https://github.com/user-attachments/assets/3ead63d3-8e75-4557-8701-367c2665f8c0) |
| …
=> introduce_zulip_view_modal: Scale button with font size.

web/src/user_card_popover.ts
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20blueslip.20error.20clicking.20on.20a.20user.20.28spectator.29)
| ![Screenshot 2025-03-04 at 15 48 21@2x](https://github.com/user-attachments/assets/31293db5-640b-4c8e-815b-5d5709c6cec8) | <img width="1409" alt="Screenshot 2025-03-05 at 5 26 52 PM" src="https://github.com/user-attachments/assets/608d3c61-ae5c-4142-a8e8-9bee4daadf3d" /> |
<details> …
=> presence_data: Skip fetching presence_data in user_card_popover for spectators.

zerver/views/realm.py
This PR ensures the `message_edit_history_visibility_raw` parameter is validated using the policy names defined in the `MessageEditHistoryVisibilityPolicyEnum`, used in the `update_realm()` function in the `zerver/views/realm.py` file.
Follow up of #32840.
Fixes: [PR comment](https://github.com/zulip/zulip/pull/32840#:~:text=I%20also%20fixed%20one%20bug%2C%20which%20is%20that%20there%20was%20no%20validation%20of%20values%20being%20valid%2C%20with%20a%20TODO%20that%20you%20should%20pick%20up%20next%3A).
**Screenshots and screen captures:** _None_.
<details> …
=> zerver: Use Pydantic for `MessageEditHistoryVisibilityPolicyEnum`.

web/src/user_profile.ts, web/styles/popovers.css, web/templates/user_group_list_item.hbs, web/templates/user_stream_list_item.hbs
This commit resolves the misalignment issue for the privacy icons and stream names along with their horizontal alignment with the subscription button. The icons were previously not properly placed with the text, causing a visual discrepancy.
Fixed #31521.
This PR is a continuation of the work done in #31531.
`stream_container` class was added in order for consistent code in the file, along with adding that class helped in aligning the stream (icon + name) in the center of the container.
|Before|After|
|---|---|
|<img width="519" alt="Screenshot 2025-02-17 at 10 40 07 PM" src="https://github.com/user-attachments/assets/0795f7b7-2f1c-4bd0-a619-9017102be966" />|<img width="522" alt="Screenshot 2025-02-17 at 10 38 53 PM" src="https://github.com/user-attachments/assets/64e62ea9-83f4-4788-bdd9-f …
=> user_profile: Align privacy icons with stream names in popover.

web/src/emoji_picker.ts, web/templates/popovers/emoji/emoji_popover_emoji_map.hbs
This PR adds a new mapping for the translated emoji categories as discussed [here](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20emoji.20picker.20internationalization/near/1369477). As per [conversation](https://github.com/zulip/zulip/pull/33109#issuecomment-2605537503), strings for translation are tagged.
Fixes: #21843
<details>
</details>
=> i18n: Add translation tag for emoji section labels

puppet/kandra/manifests/profile/chat_zulip_org.pp
=> kandra: Add zulip-notify hooks for CZO.

web/styles/zulip.css
This prevents applying an inappropriate `margin-right` value in spectator view, which includes a large Log in button.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20navbar.20messed.20up.20for.20spectators/near/2112307)
| --- | --- |
| ![spectator-search-log-in-before](https://github.com/user-attachments/assets/f0c087c6-11d4-471d-be9b-cb655ac153b2) | ![spectator-search-log-in-after](https://github.com/user-attachments/assets/f541169f-5485-4ffa-a829-12cd5609ef07) |
<details> …
=> specator_view: Avoid Search overlap with large Log in button.

help/change-the-channel-description.md, help/include/sidebar_index.md, help/include/tips-for-creating-channels.md, help/link-to-a-message-or-conversation.md, help/pin-information.md, help/view-channel-information.md
We often suggest this to users, so we should actually document it.
https://zulip.com/help/create-channels#tips-for-creating-channels
---
=> help: Document how to pin information in a channel description.

puppet/kandra/files/nginx/zulip-include-app.d/onboarding-video.conf, puppet/kandra/manifests/app_frontend.pp
The sha256 is based on the version from [here](https://chat.zulip.org/#narrow/channel/107-kandra/topic/onboarding.20video.20draft/near/2113929).
=> kandra: Add /static/onboarding-video/ static content.

web/src/user_group_edit.ts, web/styles/subscriptions.css, web/templates/user_group_settings/cannot_deactivate_group_banner.hbs
Follow-up for #33800.
<details>
</details>
=> Add "View permissions" button in deactivation error banner.

CONTRIBUTING.md
=> contributor docs: Better explain taking over abandnoned issues.

web/styles/message_view_header.css
Previously, at screen widths between 425px and 620px, hovering over Inbox description caused misalignment of "Inbox" title and the icon.
This commit resolves it by defining the padding-top in em instead of pixels.
|||
|-|-|
|Before|![Screencast_20250307_012315-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/1b85d696-c00a-4ec6-a198-2b70c639a976)|
|After|![Screencast_20250307_012501-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/1ad1992b-7dd2-4bc2-a194-2792332d82ed)|
<details> …
=> navbar: Fix vertical shift of Inbox title on hover.

templates/corporate/history.md
=> portico: Add Changelog interview to history page.

web/src/buddy_data.ts, web/src/buddy_list.ts, web/src/compose_closed_ui.ts, web/src/narrow_state.ts, web/src/scheduled_messages_feed_ui.ts, web/src/server_events_dispatch.js, web/src/stream_events.ts, web/src/stream_settings_ui.ts, web/tests/buddy_data.test.cjs, web/tests/dispatch_subs.test.cjs, web/tests/narrow_state.test.cjs, web/tests/narrow_unread.test.cjs
Prep commits for work towards [#32959](https://github.com/zulip/zulip/issues/32959):
- Updates comments in `narrow_state.ts` for the fact that we now expect a operand string for a canonical "channel" operator to be the channel ID or an empty string for a current `Filter` object.
- Updates `narrow_state.stream_sub` to use `narrow_state.stream_id`:
- De-duplicates the shared logic between these two functions.
- Catches a subtle bug with how the `narrow_state` data was set up for a test in `buddy_data.test.cjs`.
- Explicitly note and check that `narrow_state.stream_id` can return "NaN" in the case where the channel operand is an empty string.
- Updates two functions in `buddy_data.ts.` to use the updated `narrow_state.stream_sub` function when getting or checked subscriber data as this will …
=> narrow-state: Clarify channel operand functions and documentation for current filter.

web/src/stream_settings_ui.ts, web/src/user_group_edit.ts, web/styles/settings.css, web/templates/stream_settings/stream_creation_form.hbs, web/templates/user_group_settings/user_group_creation_form.hbs
- Replaced `data-dismiss="modal"` attributes with class/ID-based event handling.
- Removed an unused CSS rule which was defined for `button[data-dismiss="modal"]` and there was no `data-dismiss` left in the codebase.
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/6-frontend/topic/cleaning.20up.20of.20data-dismiss.20things.2E/near/2114384)
<details>
</details>
=> modals: Remove `data-dismiss` usage and update cancel actions.

docs/production/video-calls.md
This needs to wait until #33809 is on zulip.com before we can merge it.
=> docs: Update video call links for new configure call provider article.

web/src/copy_messages.ts
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/Ctrl.2BC.20with.20nothing.20selected.20exception
Fixes: 
<details>
</details>
=> copy_messages: noop for empty selection.

help/archive-a-channel.md, help/configure-who-can-invite-to-channels.md, help/configure-who-can-unsubscribe-others.md
Blockers:
- #32475
Otherwise, this is ready.
Current page: https://zulip.com/help/archive-a-channel
Updated (minus unchanged bottom section):
=> help: Document viewing archived channels in settings. 

web/src/copy_messages.ts
This replicates the smart selection
feature that works with selecting a
single expression within a math block
for inline math expressions.
Fixes: #33865.
https://github.com/user-attachments/assets/db94e95b-0b84-43ce-9e81-19f10c263f26
<details>
</details>
=> copy_messages: Extend smart selection for inline math.

web/styles/zulip.css
| --- | --- |
| ![Screen Shot 2025-03-08 at 20 13 07](https://github.com/user-attachments/assets/e633b1d8-a10a-4718-818a-1a206b1fa8c3) | ![Screen Shot 2025-03-08 at 20 11 21](https://github.com/user-attachments/assets/5e08838b-eba7-49cc-81c5-df66c4de3ac1) |
| ![Screen Shot 2025-03-08 at 20 13 20](https://github.com/user-attachments/assets/24dd6e78-9dd9-4f89-9711-6d05e6287b25) | ![Screen Shot 2025-03-08 at 20 11 05](https://github.com/user-attachments/assets/7dab9dbf-1cde-4ca1-9dc9-e5765b5e7a28) |
| ![Screen Shot 2025-03-08 at 20 13 32](https://github.com/user-attachments/assets/6d0b6c6a-9e8a-41da-8392-4b3a1d168412) | ![Screen Shot 2025-03-08 at 20 08 31](https://github.com/user-attachments/assets/41e8a73a-f119-43f9-97c5-b8a5e01d19b1) |
| …
=> topic_edit: Scale spinner with font size.

tools/merge-api-changelogs
Adds a newline after changelog when running `./tools/merge-api-changelogs`.
<details>
</details>
=> tools: Fix `merge-api-changelogs`.

web/styles/inbox.css
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/misaligned.20dropdown.20menu.20in.20.22Recent.20conversttions.22/near/2117529)
| --- | --- |
| ![recents-dropdown-before](https://github.com/user-attachments/assets/affa1b76-c3c6-4a74-83f4-cbc4d8c759a8) | ![recents-dropdown-after](https://github.com/user-attachments/assets/83ec83e1-cf13-4633-8940-78b1fbd5e104) |
| ![inbox-dropdown-before](https://github.com/user-attachments/assets/83ab04ad-81f1-4795-90c2-c84c6cbcf039) | ![inbox-dropdown-after](https://github.com/user-attachments/assets/a6615574-8398-469b-bc80-853ac51722d5) |
<details> …
=> dropdowns: Correct columnar flex alignment in recents, inbox.

web/src/information_density.ts
Discussion here:
https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/Weird.20bug.20possibly.20involving.20calc/near/2113977
=> information_density: Resize page components when changing font size.

templates/zerver/email.html, zerver/actions/invites.py, zerver/lib/email_notifications.py, zerver/lib/send_email.py, zerver/signals.py, zilencer/views.py, zproject/email_backends.py
=> Add Date header to sent emails, based on when they were enqueued

zerver/openapi/zulip.yaml
=> api_docs: Add Changes entry for removing `is_billing_admin`.

web/src/compose_actions.ts, web/src/compose_setup.js, web/src/compose_tooltips.ts, web/src/compose_validate.ts, web/src/composebox_typeahead.ts, web/styles/compose.css, web/tests/lib/compose_helpers.cjs, web/tests/upload.test.cjs
Does what 714def080fb32e0ef2793a7dd1161b3fbee69d78 was trying to do without the side effects.
Fixes: 714def080fb32e0ef2793a7dd1161b3fbee69d78
[czo](https://chat.zulip.org/#narrow/channel/9-issues/topic/Tooltip.20delay.20for.20invalid.20send.20conditions/with/2118984)
Fixes: 
<details>
</details>
=> compose_tooltip: Remove delay for invalid messages.

web/src/invite.ts, web/styles/zulip.css
This PR removes the fix width from multiuse_invite_link and sets it to full so that it can take all the remaining space and copy invite link button gets aligned properly.
- this also changes `copy_invite_link ` to `render_copy_invite_link ` to follow our conventions.
| Before     | ![Changes visible in alignment and hover](https://github.com/user-attachments/assets/b862fb67-21a4-4687-b02a-a6beffebda99)    |
| After  | ![dm](https://github.com/user-attachments/assets/16595ca5-0fe8-48f1-a0f8-6d90cf23a595) |
<details> …
=> invite: Fix alignment of copy-invite-link button in invitation modal.

web/src/list_widget.ts, web/tests/list_widget.test.cjs
I refined the sorting algorithm of recent conversation list so that it works like spreadsheet sorting. Here is the [discussion thread](https://chat.zulip.org/#narrow/channel/6-frontend/topic/sorting.20in.20recent.20conversations/with/2099205) for this issue.
Fixes: #33289
<details>
</details>
=> recent_conversations: Improve sorting behavior.

web/src/message_list_tooltips.ts
If the template_id of the message_control_button
is undefined, we will not render the tooltip at all. 
This might happen, for example,
when a message is past its editable period and
the edit button is not displayed.
<details>
</details>
=> message_list_tooltips: Avoid showing `undefined`.

help/getting-started-with-zulip.md
Current: https://zulip.com/help/getting-started-with-zulip
Updated:
=> help: Link to onboarding video from getting started guide.

zerver/filters.py
=> filters: Do not report AVATAR_SALT, or other salts.

puppet/kandra/files/nginx/zulip-include-app.d/navigation-tour-video.conf, puppet/kandra/manifests/app_frontend.pp
=> kandra: Rename onboarding-video to navigation-tour-video.

web/src/zulip_test.ts
discussion: [#issues > ❓reaction missing in live-update @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.E2.9D.93reaction.20missing.20in.20live-update/near/2121873)
=> zulip_test: Expose function get message from id for debugging.

web/styles/alerts.css
This is a follow-up to commit cd08c628ba99ad98b7d30b29f52d62abe4dc3709, and adds the missing `pointer-events: auto` property to the blueslip error overlay. This makes the blueslip error overlay interactable again.
Fixes: [#issues > cannot close blueslip error overlay](https://chat.zulip.org/#narrow/channel/9-issues/topic/cannot.20close.20blueslip.20error.20overlay)
<details>
</details>
=> alerts: Fix blueslip error overlay not interactable.

help/saved-snippets.md
https://zulip.com/help/saved-snippets
=> help: Document snippet editing.

help/include/sidebar_index.md, help/restrict-moving-messages.md, help/restrict-resolving-topics.md
Modeled after https://zulip.com/help/restrict-moving-messages.
=> help: Document permission to resolve topics.

web/src/banners.ts, web/src/navbar_alerts.ts, web/src/popup_banners.ts
The web/src/banners.ts module, was trigger the window resize event for every banner, which led to unexpected UI bugs and performance issues.
This PR restricts the window resize event to only the navbar banners, where there is a need to recalculate the navbar-fixed-container height and adjust the UI accordingly.
Fixes: [](https://chat.zulip.org/#narrow/channel/9-issues/topic/message.20collapsing.20state.20not.20working.20properly/near/2122900)[#issues > message collapsing state not working properly @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/message.20collapsing.20state.20not.20working.20properly/near/2122900)
<details> …
=> banners: Restrict window resize event calls to navbar banners only.

web/src/compose_validate.ts
Previously, users could send messages before uploads finished, resulting in incomplete messages with "Uploading..." text.
This PR blocks sending until uploads complete.
Fixes: #33986.
[Screen Recording](https://drive.google.com/file/d/1BvN_x_75ZDJk2oyxUXe_0tLE1EkZWcFY/view?usp=sharing)
<details>
</details>
=> upload: Prevent sending messages during file uploads.

templates/corporate/jobs.html
Also update some surrounding context.
<details>
<summary>
Screenshots
</summary>
</details>
=> [WIP] corporate: Post a designer job.

web/src/popup_banners.ts
discussion: https://github.com/zulip/zulip/pull/32803#discussion_r1994486535
=> popup_banners: Don't trigger fade out if the banner is not present.

web/styles/zulip.css, web/templates/dropdown_list.hbs, zerver/openapi/zulip.yaml, zerver/tests/test_saved_snippets.py, zerver/views/saved_snippets.py
- Use `intent="neutral"` in saved snippet edit icon button instead of defining CSS rules.
- If no data is provided to the `saved_snippets/{saved_snippet_id}:patch` endpoint, do no-op instead of throwing error.
Follow-up: #33902.
<details>
</details>
=> Edit saved snippets follow-ups.

web/styles/subscriptions.css
This PR fixes a bug reported on CZO where the group name appears offset to the left by a few pixels compared to the description and other settings.
<table border="1">
<tr>
<th>After</th>
</tr>
<tr>
<th colspan="2">Stream Name (No change)</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<th colspan="2">Group Name</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<details>
</details>
=> Fix the left offset of the group name.

help/configure-who-can-invite-to-channels.md, help/user-groups.md
Addresses [#general > "Who can subscribe anyone to this channel" in public channel](https://chat.zulip.org/#narrow/channel/2-general/topic/.22Who.20can.20subscribe.20anyone.20to.20this.20channel.22.20in.20public.20channel/with/2115205).
=> help: Clarify some permissions info.

web/styles/app_variables.css, web/styles/input_pill.css, web/styles/search.css
for squished pills, at 12px, 14px, 16px, 20px:
| --- | --- |
| ![Screen Shot 2025-03-11 at 15 53 04](https://github.com/user-attachments/assets/1525b8a3-a5b7-40b4-add8-a570d20bd459) | ![Screen Shot 2025-03-11 at 16 05 45](https://github.com/user-attachments/assets/5eed9bb9-8eb5-4ecd-90b3-3d145aacf92a) |
| ![Screen Shot 2025-03-11 at 15 53 53](https://github.com/user-attachments/assets/4fe28b2d-1051-4179-8192-a37c1fa0c496) | ![Screen Shot 2025-03-11 at 16 07 09](https://github.com/user-attachments/assets/f323bace-a014-4476-98df-bed7d05af409) |
| ![Screen Shot 2025-03-11 at 15 54 26](https://github.com/user-attachments/assets/17cff3e0-a433-4545-8be7-38d2347d948c) | ![Screen Shot 2025-03-11 at 16 04 23](https://github.com/user-attachments/assets/54b9c544-0324-46d3-bb88-fdba …
=> user_pill: Use variables for sizing and scale with font-size.

templates/zerver/app/index.html, web/src/popup_banners.ts, web/src/reload.ts, web/src/server_events_dispatch.js
This PR redesigns the reloading application banner to use the new banner styles.
Fixes: #31289
| ![Screenshot 2025-03-18 at 4 20 24 AM](https://github.com/user-attachments/assets/eb506184-9451-408b-9997-61a723a8f5f3) | ![Screenshot 2025-03-18 at 4 11 36 AM](https://github.com/user-attachments/assets/f00fef65-1f4b-4129-8b3f-81f4ef111b81) |
| ![Screenshot 2025-03-18 at 4 20 50 AM](https://github.com/user-attachments/assets/0bf64fa4-8a21-44d8-93a2-bf27e60a4b99) | ![Screenshot 2025-03-18 at 4 10 49 AM](https://github.com/user-attachments/assets/d89d834c-7845-4dee-abf1-3550fed4359f) | 
<details> …
=> popup_banners: Redesign reloading application banner.

help/line-spacing.md, zerver/lib/zulip_update_announcements.py
CZO discussion: [#release management > zulip_updates items of note @ 💬](https://chat.zulip.org/#narrow/channel/438-release-management/topic/zulip_updates.20items.20of.20note/near/2127287)
=> updates: Add update message (level=14).

web/templates/move_topic_to_stream.hbs
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20missing.20translation.20tags/with/2127620
=> move_topic_to_stream: Tag text for translation.

web/src/message_edit.ts, web/styles/message_row.css
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/message.20editing.20save.20button.20shrinks/near/2128429)
| --- | --- |
| ![save-spinner-before](https://github.com/user-attachments/assets/079c267a-d833-42ad-a3c7-2b6a599f6867) | ![save-spinner-after](https://github.com/user-attachments/assets/2767f413-9616-4ed7-958e-2cfa113ab253) |
<details>
</details>
=> message_edit: Preserve width of Save button when showing spinner.

docs/production/settings.md
=> docs: Describe how to configure navigation tour video.

web/styles/compose.css, web/styles/message_row.css
discussion: https://chat.zulip.org/#narrow/channel/101-design/topic/send.20button.20color/with/2128621
Reverts #34036 and #33989
=> Revert send button color to that in 9.x.

zerver/migrations/0695_is_channel_message_stats.py
These extended statistics allow the query planner to know that the prevalence of empty topics is very different in DMs, as opposed to channel messages.  The `ALTER STATISTICS` adjusts the size of the "most common value" list -- it must be large enough to include the empty-topic channel messages to be fully effective.  Having this list be over-large does not carry much risk, however.
The `ANALYZE zerver_message` step may be quite slow.
Fixes: 
<details>
Completed …
=> migrations: Generate statistics for subject vs channel-messages.

templates/zerver/app/index.html
Avoid using deprecated meta tags like apple-mobile-web-app-capable, as they can interfere with proper PWA installation. Safari may fall back to these tags if it can’t load the manifest, leading to an inconsistent and poor app experience.
Instead, this commit adds the mobile-web-app-capable meta tag as suggested by the developer console.
Sources:
https://web.dev/learn/pwa/web-app-manifest#designing_your_pwa_experience https://web.dev/learn/pwa/enhancements#installation_reliability
Fixes: [#issues > 🛠️apple-mobile-web-app-capable deprecated notice in console @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.9B.A0.EF.B8.8Fapple-mobile-web-app-capable.20deprecated.20notice.20in.20console/near/1936308) …
=> web: Replace deprecated apple-mobile-web-app-capable meta tag.

templates/corporate/jobs.html
Notes:
- I couldn't figure out how to get the linter to actually fix the formatting for me (which is messed up from the content being copied over from Paper).
<details>
<summary>
screenshots
</summary>
</details>
=> portico: Add job posting for go-to-market leader.

zerver/lib/zulip_update_announcements.py
- Assumes that we'll make a redirect URL.
- I couldn't get testing to work out for some reason, maybe because I originally had a formatting error?
=> updates: Add update message (level=15).

zerver/webhooks/uptimerobot/view.py
=> uptimerobot: Ensure we do not use body without it being defined.

templates/corporate/history.md
CZO: [#release management > 10.0 release checklist @ 💬](https://chat.zulip.org/#narrow/channel/438-release-management/topic/10.2E0.20release.20checklist/near/2131477)
=> portico: Add 10.0 release and group-based permissions to history.

docs/production/upgrade.md, puppet/zulip/manifests/app_frontend_base.pp, puppet/zulip/templates/nginx/zulip-enterprise.template.erb
=> nginx: Allow adding extra monitoring paths in a localhost.d.

web/styles/app_variables.css, web/styles/banners.css
This PR consists of the following commits:
- **Commit 1:** Converts the pixel values in the banner styling to `em`.
- **Commit 2:** Updates the padding of the label and close button to accommodate the changes in d00b4cb0bdcc2318db454750b232ee7416af1169.
- **Commit 3:** Fixes the banner action buttons vertical alignment.
Fixes: [](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Glitchy.20connection.20error.20popup.20banner/near/2128419)[#issues > 🎯 Glitchy connection error popup banner @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Glitchy.20connection.20error.20popup.20banner/near/2128419)
| Font size | Before | After |
| 12px | ![Screenshot 2025-03-22 at 4 12 …
=> banners: Improve banner scaling with font size.

docs/production/troubleshooting.md, puppet/kandra/files/apt/apt.conf.d/50unattended-upgrades
=> puppet: Exclude pgroonga from unattended-upgrades.

tools/webpack, web/html/5xx-cloud.html, web/webpack.config.ts
=> webpack: Potentially use /etc/zulip/5xx.html for a custom error page.

corporate/tests/test_support_views.py, templates/corporate/support/realm_details.html, zerver/models/realms.py
=> support: Show current billing admins on cloud support page.

web/src/compose_validate.ts
We now use `data-user-group-id` in the function `warn_if_mentioning_unsubscribed_group` to check if a banner for the same group already exists, preventing duplicate warnings when the same group is mentioned multiple times.
Fixes: 
<details>
</details>
=> compose: Prevent duplicate group mention warning banners.

docs/production/upgrade.md
- https://github.com/astral-sh/uv/issues/12461
- https://github.com/astral-sh/uv/issues/12463
- https://chat.zulip.org/#narrow/channel/3-backend/topic/OS.20upgrade.20instructions.20for.20.60uv.60/near/2133719
=> docs: Work around uv bugs in Ubuntu 24.04 upgrade instructions

web/styles/settings.css
The weird behavior when hovering over `x` for the date-type field was happening because of focusing on input/blinking cursor, this PR solves it by setting the z-index for the .remove_date button higher(5).
fixes: #33346
before:
https://github.com/user-attachments/assets/857914ea-9dbf-40e4-8f53-f5f226c5c212
after:
https://github.com/user-attachments/assets/68c18109-6ab1-4f40-862f-779747df4c41
<details>
<summary>light theme</summary>
before:
https://github.com/user-attachments/assets/5dfc8603-2f4d-4095-a743-7baa936b7554
after:
https://github.com/user-attachments/assets/feec360d-b5ff-4bcb-937e-00477d49a351
</details>
<details> …
=> settings_ui: Fix flickering when hovering over "x" in date-type field.

web/src/user_group_edit.ts
Fixes: #33437.
https://github.com/user-attachments/assets/36228d62-cafd-461b-b368-78f15fe2931c
=> user_groups: Persist settings view while switching tabs.

docs/outreach/gsoc.md
Few changes to Terminal GSoC project notes.
Split into multiple commits for clarity. Unsure re text in last commit, but could be squashed with prior or dropped.
**NOTE:** The terminal section of the doc still references 'students' rather than 'contributors', but the rest of the doc also does in a few places, so I left out that change here since I wanted to confirm and then leave that to be swept later if relevant.
<details> …
=> docs/gsoc: Improve text for Terminal projects

zerver/tests/test_subs.py
Without this test, a bug with the rendering logic that was fixed by #34056 went unnoticed.
Fixes part of #34069.
<details>
</details>
=> test_subs: Test rendered content instead of just the content.

corporate/lib/stripe.py, corporate/tests/test_stripe.py
Updates `invoice_plans_as_needed` so that we track customer IDs where we failed to process the invoice due to an error. This allows us to continue invoicing other customers, instead of stopping the process at the first  failure. And it allows us to not invoice any other plans that may be connected to a customer that already had a failure.
**Notes**:
- First two prep commits, pull out the logic for sending internal billing email notices for fixed-price plan renewal reminders and for stale audit log data causing overdue invoices.
- The third prep commit, pulls out the logic for skipping `invoice_plan` for self-hosted customers when the remote server audit log data is stale.
- The final commit adds the error logging to `invoice_plans_as_needed`.
**Tests**:
- There are a few more `# …
=> billing: Improve invoice plans as needed error handling.

web/src/buddy_list.ts
Fixes bug reported here:
https://chat.zulip.org/#narrow/channel/137-feedback/topic/Others.20-.20always.20expanded.20please/with/2138009
=> buddy_list: Make sure we always open Others section during search.

web/src/compose_recipient.ts, web/src/message_edit.ts, web/src/stream_popover.ts
PR to address https://github.com/zulip/zulip/pull/34070#discussion_r2006222280
> We have this meme all over the place, but it’s [unnecessary](https://api.jquery.com/toggleClass/):
> > $topic_not_mandatory_placeholder.toggleClass("visible", $input.val() === "");
<details>
</details>
=> jquery: Simplify `$topic_not_mandatory_placeholder` toggling.

docs/production/upload-backends.md, zerver/management/commands/runtusd.py
Fixes: #34102.
<details>
</details>
=> tusd: Support running without explicit AWS keys.

web/styles/app_variables.css
It was reported that when clicking on "Show all topics" in the left sidebar, scrolling down, and hovering over the topic search box, the topic names appeared to leak above the search box.
The solution here is to mix down the hover color in dark mode so that the color is opaque, using the color of the left sidebar as a base.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/mouseover.20during.20.22show.20all.20topics.22)
| --- | --- |
| ![topic-bleedthrough-before](https://github.com/user-attachments/assets/74370613-cc98-4a9b-ba42-1d50332d2413) | ![topic-bleedthrough-after](https://github.com/user-attachments/assets/caf20e09-89e8-4da0-ad40-0e1d3ac20cb0) |
<details> …
=> left_sidebar: Fix leakage of topics above the search box on hover.

web/src/popup_banners.ts
Changes banner text to "This conversation also has older unread messages. Jump to first unread message?"
Updates button label from "Jump to first unread" to "Jump".
Fixes: 
<details>
</details>
=> ui: Update unread banner text and button label.

web/templates/add_saved_snippet_modal.hbs, web/templates/edit_saved_snippet_modal.hbs
[CZO](https://chat.zulip.org/#narrow/channel/6-frontend/topic/new-style/near/2137987)
<details>
</details>
=> saved_snippets: Remove "new-style" class add/edit modals.

puppet/zulip/files/nginx/zulip-include-common/proxy, puppet/zulip/templates/nginx/zulip-enterprise.template.erb, zerver/management/commands/runtusd.py
=> Better support non-standard ports with tusd

.codespellignore, templates/corporate/jobs.html
Current: https://zulip.com/jobs/
Updates:
=> corporate: Add more detail to job description.

puppet/kandra/manifests/aws_tools.pp, puppet/kandra/manifests/profile/base.pp, puppet/kandra/manifests/teleport/db.pp, puppet/kandra/manifests/teleport/node.pp, puppet/kandra/templates/teleport_db.yaml.template.erb
=> kandra: Extract the Teleport host CA to disk.

web/templates/confirm_dialog/confirm_deactivate_user.hbs
In deactivate user confirm dialog, we hide the count of unexpired invitations of a user when the count is zero.
if count is 0
if count is not zero
if count is 0
if count is 1
if count is > 1
Fixes: #34265
<details>
</details>
=> Don't show 0 invitations in user deactivation modal 

.github/workflows/production-suite.yml
=> actions: Add test upgrade from 10.0.

web/styles/zulip.css, web/third/bootstrap/css/bootstrap.app.css
These removals and few bits of preservation continue the project of eliminating Bootstrap from the app.
Some of the preservation probably kicks the can down the road a bit--ideally we should be moving away from element selectors when possible.
[CZO discussion](https://chat.zulip.org/#narrow/channel/6-frontend/topic/bootstrap.20CSS.20reset.20removal/near/2143927)
<details>
</details>
=> bootstrap: Clean up or preserve styles as needed.

web/styles/compose.css
This PR adds a horizontal line, using the same border-color as other modals, to separate snippets from one another.
[CZO discussion](https://chat.zulip.org/#narrow/channel/137-feedback/topic/Snippet.20UI/near/2137435)
<details>
</details>
=> snippets: Better distinguish snippet content in dropdown.

templates/500.html, web/html/5xx-cloud.html, web/html/5xx.html, zerver/tests/test_signup.py, zerver/views/registration.py
=> web: Sync content of Django and nginx error pages.

web/src/user_card_popover.ts
When user-card-tooltip is visible:
Before
https://github.com/user-attachments/assets/7cae1f5c-6bed-4f26-bcd7-8e7c26e2eaa9
After
https://github.com/user-attachments/assets/6e77bdc0-9785-4e94-be97-e13f120074b9
Clickable area after changes
Discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/unexpected.20behavior.20of.20view.20user.20card.20tooltip/with/2133845
<details>
</details>
=> user-card-tooltip: Open user card when user-card-tooltip visible.

puppet/zulip/templates/nginx/zulip-enterprise.template.erb
Some deployments choose to wrap Zulip's nginx in an outer proxy -- for example, to do custom TLS termination.  In such deployments, the outer proxy is routing to `127.0.0.1:80`; b4fb22ba1bef breaks these configurations, as it switches the `127.0.0.1:80` listener to only serving `/api/internal/` paths.
Switch to serving the whole application over `127.0.0.1:80`.
Fixes: 
<details>
</details>
=> nginx: Serve full app from localhost.

.github/workflows/production-suite.yml, puppet/zulip/templates/nginx/zulip-enterprise.template.erb, web/src/popup_banners.ts, web/styles/app_variables.css, web/styles/compose.css, web/styles/left_sidebar.css, web/templates/confirm_dialog/confirm_deactivate_user.hbs, web/templates/pm_list_item.hbs, zproject/prod_settings_template.py
- #34287
- #34211
- #34188
- #34121
- #34268
- #34238
- #34239
- #34279
- #34294
=> Backport several changes to 10.x

web/styles/app_components.css, web/styles/app_variables.css, web/styles/compose.css, web/styles/dark_theme.css, web/styles/modal.css, web/styles/subscriptions.css
This PR cleans up a lot of contained, low-hanging fruit in the first ~50% of `dark_theme.css` (up to the `.close` selector, which will be removed shortly in a separate PR, in concert with cleaning up the parallel items in `bootstrap.css`).
[CZO discussion](https://chat.zulip.org/#narrow/channel/6-frontend/topic/Deleting.20dark-theme.2Ecss/near/2145089)[#frontend > Deleting dark-theme.css @ 💬](https://chat.zulip.org/#narrow/channel/6-frontend/topic/Deleting.20dark-theme.2Ecss/near/2145089)
<details> …
=> dark_theme: Clean up contained selectors, colors in first half of file.

web/styles/settings.css
This corrects a regression from #34288. Because the background color get set on `<thead>`, we want to make `<thead>` also the sticky container (which makes better sense than making individual `<th>` cells sticky.
| --- | --- |
| ![sticky-table-headings-before](https://github.com/user-attachments/assets/957df524-1ef0-45de-8135-16d3fb5c6f1d) | ![sticky-table-headings-after](https://github.com/user-attachments/assets/082e74cb-aaa4-43cc-929a-b33f0b7fa389) |
<details> …
=> settings: Make all of thead sticky.

web/src/message_list_view.ts, web/styles/message_header.css, web/templates/recipient_row.hbs
This PR shows the bot icon after the bot name in DM headers.
Fixes: #32990
Before changes
After changes
<details>
</details>
=> dm_headers: Show bot icon after bot name.

zerver/lib/test_classes.py
=> test_classes: Mention actual and expected count in assert_length.

web/src/add_subscribers_pill.ts, web/src/pill_typeahead.ts, web/src/stream_create_subscribers.ts, web/src/stream_ui_updates.ts, web/src/typeahead_helper.ts, web/src/user_group_create_members.ts, web/styles/subscriptions.css, web/templates/stream_settings/add_subscribers_form.hbs, web/templates/stream_settings/stream_creation_form.hbs, web/templates/user_group_settings/add_members_form.hbs, web/templates/user_group_settings/new_user_group_users.hbs, web/tests/pill_typeahead.test.cjs, web/tests/typeahead_helper.test.cjs
Some changes pending based on the conversation at https://chat.zulip.org/#narrow/channel/101-design/topic/New.20channel.2Fgroup.20UX.20changes/with/2141849
Fixes #33127 
<details>
</details>
=> Rework UX for adding everyone to a channel or group

web/e2e-tests/message-basics.test.ts, web/src/resize.ts, web/src/stream_settings_components.ts, web/src/stream_settings_ui.ts, web/src/tippyjs.ts, web/src/user_group_edit.ts, web/styles/app_variables.css, web/styles/subscriptions.css, web/templates/stream_settings/stream_settings_overlay.hbs, web/templates/user_group_settings/user_group_settings_overlay.hbs
Prep commits for #34125. Should have no visible changes.
=> settings: Rewrite two-pane settings menu to use shared classnames.

web/src/settings_config.ts, web/styles/settings.css, web/templates/settings/account_settings.hbs, web/templates/settings/organization_user_settings_defaults.hbs, web/templates/settings/preferences.hbs, web/templates/settings/privacy_settings.hbs
This PR moves up the Privacy settings section for Organization to just below General subsection in Default User Settings.
fixes: #33421
| --- | --- |
| ![Before Image](https://github.com/user-attachments/assets/0e7000da-6948-4622-b891-c433d5db1123) | ![After Image](https://github.com/user-attachments/assets/0443760f-8eff-4c68-ad27-427d25431a23) |
<details>
<summary>video</summary>
https://github.com/user-attachments/assets/e70937e0-18ec-4f9c-8e47-aa909db707ca
</details>
<details> …
=> settings: Move up Privacy settings section in Default user settings.

zerver/actions/message_send.py, zerver/lib/user_groups.py
When checking DM permissions, instead of using list of users, we now use set of users to
check if any user is in `direct_message_permission_group` because there can be case
when sender can also be one of the recipients.
<details>
</details>
=> message: Use set instead of list when checking DM permission.

help/include/sidebar_index.md, help/include/user-roles-intro.md, help/moderating-open-organizations.md, templates/corporate/for/communities.html, templates/corporate/for/communities.md, templates/corporate/plans.html, web/styles/portico/portico.css
It's a long page, so I think it's best to pull down the PR, rather than reviewing via screenshots.
Update to https://zulip.com/help/moderating-open-organizations intro:
=> portico: Rewrite /for/communities.

puppet/zulip/files/nginx/zulip-include-common/proxy
Unilaterally adding the port can cause CSRF failures when the port is a default port, and thus optional.  Switch to providing the exact `Host` header that the original request contained.
Fixes: 
<details>
</details>
=> nginx: Relay the same Host: header that nginx saw.

zerver/lib/user_groups.py, zerver/tests/test_user_groups.py
For `check_user_has_permission_by_role`, we were using `user.is_moderator` by default to check whether the user had those priviliges. But that specific function returns false if the user is an admin or an owner. So we check `is_realm_admin` too in that case.
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/Permissions.20Issue.20on.20DM/with/2149627
Also opened [#backend > is_moderator returns false for admins.](https://chat.zulip.org/#narrow/channel/3-backend/topic/is_moderator.20returns.20false.20for.20admins.2E)
<details> …
=> user_groups: Realm admins should be allowed moderator permissions.

zerver/management/commands/runtusd.py, zproject/computed_settings.py
=> Better S3_REGION fallbacks

web/src/filter.ts, web/src/hashchange.ts, web/src/hotkey.js, web/src/inbox_ui.ts, web/src/recent_view_ui.ts, web/src/stream_list.ts, web/src/topic_list.ts, web/src/topic_list_data.ts, web/src/ui_init.js, web/styles/left_sidebar.css, web/templates/filter_topics.hbs, web/templates/inbox_view/inbox_row.hbs, web/tests/filter.test.cjs, web/tests/recent_view.test.cjs, web/tests/stream_list.test.cjs, web/tests/topic_list_data.test.cjs
This has all the commits from #30155 except the one that adds the view, API and backend changes.
=> Prep commits extracted from #30155

scripts/lib/install-uv, uv.lock, version.py, zerver/worker/base.py
=> [10.x] requirements: Upgrade Python requirements

web/styles/app_components.css, web/styles/subscriptions.css
Prep for https://github.com/zulip/zulip/pull/34125, mostly moving CSS around to help that PR be easier to read, and deleting some stale/unhelpful CSS.
=> settings: Clean up and prepare CSS for #34125

docs/documentation/helpcenter.md
=> contributor docs: Update info on icons in the help center.

puppet/kandra/manifests/profile/base.pp
=> kandra: Add a couple useful command-line tools.

docs/production/upload-backends.md, zerver/management/commands/runtusd.py
This works around tus/tusd#322, which in turn is caused by aws/aws-sdk-go-v2#1816.  This requires separate authentication via service account key.
Fixes: #34186.
Fixes: 
<details>
</details>
=> tusd: Use GCS upload backend when the endpoint matches.

web/src/add_group_members_pill.ts, web/src/add_subscribers_pill.ts
We have filtered the group in the get_user_groups argument of set_up_pill_typeahead. We could have done it in `set_up_combined` but that would have made that function non-generic and specific to these two settings. We could also have filtered it in get_all_realm_user_groups by adding an argument on whether to exclude it or not, but that would have been very hard to read and track. This seemed like the better of the options we had.
Fixes https://chat.zulip.org/#narrow/channel/9-issues/topic/.22Nobody.22.20group.20in.20UI.20to.20add.20subscribers.2Fgroup.20members
<details> …
=> settings: Exclude nobody from channel and group settings typeahead.

tools/create-api-changelog, tools/merge-api-changelogs
=> tools: Use .md extension for temporary API changelog files.

help/latex.md
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/.E2.9C.94.20.F0.9F.93.82.20pasting.20LaTeX/near/2129200.
Current: https://zulip.com/help/latex
Updated:
=> help-center: Support to quote and copy-paste LaTeX.

web/src/people.ts, web/tests/activity.test.cjs, web/tests/buddy_list.test.cjs, web/tests/compose_pm_pill.test.cjs, web/tests/compose_validate.test.cjs, web/tests/conversation_participants.test.cjs, web/tests/peer_data.test.cjs, web/tests/people.test.cjs, web/tests/stream_events.test.cjs, web/tests/user_events.test.cjs, web/tests/user_group_pill.test.cjs, web/tests/user_pill.test.cjs, web/tests/user_search.test.cjs
Opening settings and stream settings UI was not working for guests if they could not access all users.
This was because `is_person_active` did not handle inaccessible users correctly, if they were not added
in the users data, when being called in `get_group_members` to render group pills.
<details>
</details>
=> Fix opening settings for guests who cannot access all users.

zerver/tests/test_subs.py, zerver/views/streams.py
This PR addresses the second bullet in
https://github.com/zulip/zulip/pull/31206#issuecomment-2770372984
>Message text should be, e.g.:
>@_Desdemona subscribed you to [#devel](http://localhost:9991/#narrow/channel/11-devel).
>So, silent mention, and I don't think it needs to say "the channel".
<details>
</details>
=> streams: Change text in notification bot DM.

tools/setup/install-tusd
This update was missed in 21eff33875cdfbc0392e97a0375c3f1000413772.
Fixes: 
<details>
</details>
=> tusd: Update development version.

web/src/settings_notifications.ts
Avoids multiple copies of the desktop notification banner being added to the DOM. Appends the banner only if it doesn't already exist.
Fixes: 
https://github.com/user-attachments/assets/c6b36854-fef0-4004-b647-7d6af645806c
<details>
</details>
=> banner: Prevent duplicate desktop notification banners.

templates/zerver/app/index.html
This commit removes a trailing space in the viewport meta tag, which was causing a browser warning:
“Viewport argument key "" not recognized and ignored.”
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/The.20key.20.22.22.20is.20not.20recognized.20and.20ignored.2E)
<details>
</details>
=> meta-tag: Remove invalid space in viewport meta tag.

templates/zerver/emails/digest.html, templates/zerver/emails/digest.txt, templates/zerver/emails/missed_message.html, templates/zerver/emails/missed_message.txt, zerver/lib/digest.py, zerver/tests/test_digest.py, zerver/tests/test_message_notification_emails.py
Fixes: #33190
|  | Before | After |
| HTML formatted | ![WhatsApp Image 2025-01-30 at 20 17 48_f3b552eb](https://github.com/user-attachments/assets/28ad3f3b-d924-4bb2-a290-d6cdc14bc77a) | ![WhatsApp Image 2025-01-30 at 20 21 00_41d314e2](https://github.com/user-attachments/assets/1756909e-73d3-431e-ac24-91ea6f99d3a7) |
| Text format | ![WhatsApp Image 2025-01-30 at 20 18 11_2f85fa1f](https://github.com/user-attachments/assets/e3adbbd2-1d16-404f-8111-d7d3a15b2739) | ![image](https://github.com/user-attachments/assets/c23d20bf-c1e0-46d9-ac03-40bb42638acf) | 
|  | HTML formatted | Text format |
| When both new channel and hot topic messages are present | …
=> email: Apply message content visibility settings to digest too. 

zerver/models/users.py
We no longer fetch can_access_all_users_group using select_related after #34356.
<details>
</details>
=> users: Fix comment for base_bulk_get_user_queryset.

version.py
This parameter was added to the `PATCH /messages/message_id` endpoint in commit e2e0603689e44.
---
<details>
</details>
=> api-version: Bump API version for prev_content_sha256 parameter.

corporate/lib/stripe.py, web/src/base_page_params.ts
The `demo_organization_scheduled_deletion_date` has never been used on the upgrade page, and currently raises a Zod error as what is being sent for the value of that page param is a `Datetime` object, and not that object converted to an integer.
We really only need the boolean value that checks if the demo organization scheduled deletion date is not None for the upgrade page logic, which is set in the context dict for that page, but not in the page params.
*There's still clean up to do on the billing pages for demo organizations, but that can be done in subsequent pull requests.*
---
| --- | --- |
| ![Screenshot from 2025-04-17 16-03-08](https://github.com/user-attachments/assets/d059d2a8-c10b-44ad-9701-d2223fa83dbe)  | ![Screenshot …
=> upgrade: Remove demo_organization_scheduled_deletion_date page param.

web/src/message_list_view.ts
Fixes:
[#feedback > star topics @ 💬](https://chat.zulip.org/#narrow/channel/137-feedback/topic/star.20topics/near/2154292)
=> message_header: Use topic permalink.

zerver/lib/send_email.py, zerver/worker/email_senders_base.py, zproject/default_settings.py
Sending emails synchronously is useful because it reports configuration errors -- but it also means that occasional failures can result in ugly 500's, since those don't retry.
Add a setting which forces all email to go through the `emil_senders` queue, so it can be retried as needed.
Fixes: 
<details>
</details>
=> send_email: Add a flag to force all emails through the queue.

corporate/lib/stripe.py, corporate/tests/test_stripe.py, corporate/views/sponsorship.py, corporate/views/upgrade.py, templates/corporate/billing/demo_organization_billing_disabled.html, templates/corporate/billing/sponsorship.html, templates/corporate/billing/upgrade.html, web/styles/portico/portico_signin.css
Updates the upgrade and sponsorship pages so that, for demo organizations, the forms are not shown. Instead a notice is displayed that the organization needs to be converted to a permanent organization with a link to the relevant help center article/section.
---
| --- | --- |
| ![Screenshot from 2025-04-18 16-06-08](https://github.com/user-attachments/assets/65f25b59-b771-4f51-9b7c-000f07a90d98) | ![Screenshot from 2025-04-22 20-00-00](https://github.com/user-attachments/assets/25b3f6dd-79eb-4ca5-8bc9-f06b4d80e405) |
| ![Screenshot from 2025-04-18 16-05-52](https://github.com/user-attachments/assets/d0700d96-aeab-4438-b3b3-ffb0ae278bc3) | ![Screenshot from 2025-04-22 20-00-28](https://github.com/user-attachments/assets/037b34fa-7aea-4 …
=> corporate: Don't show upgrade and sponsorship forms for demo organizations.

zerver/lib/attachments.py
This was supposed to be in https://github.com/zulip/zulip/pull/34423.
=> attachments: Use early return and improve comments.

web/styles/app_variables.css
Simple fix here: the pixel-to-em conversion for the `--left-sidebar-single-digit-unread-width` variable (which is only used on muted unreads) did not account for the `font-size: 0.5em` value on the muted-unread marker.
Fixes: #34472
| --- | --- |
| ![muted-unreads-before](https://github.com/user-attachments/assets/283033fd-357b-4e9e-b014-173f5779fde3) | ![muted-unreads-after](https://github.com/user-attachments/assets/f4d90bdb-ad5c-4965-affb-bc1d29a9d759) |
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit- …
=> left_sidebar: Align muted unreads with correct em value.

web/styles/banners.css
This PR makes some fine adjustments to the layout of the banners,
- The padding of the banner label is adjusted such that the height of the banner label is equal to the height of the banner action button. This ensures that these banner children elements are vertically aligned while allowing for multi-line banner labels.
- Removes the extra margin used previously for aligning the banner action buttons.
- The padding of the banner close button is also adjusted to match the height of the banner, as a result of the other padding adjustments.
Related to https://github.com/zulip/zulip/pull/34116#discussion_r2018687555.
| Font Size | Screenshot |
| 12px | ![Screenshot 2025-04-18 at 12 48 …
=> banners: Improve banner layout dimensions.

web/src/people.ts, web/tests/people.test.cjs
We consider all inaccessible users as active so this commit fixes is_active_user_for_popover accordingly.
This fixes deactivated icon showing in message avatar for unknown users even when they are active.
Fixes:  https://chat.zulip.org/#narrow/channel/101-design/topic/access.20to.20all.20users.20in.20realm.20.2310970/with/2153530
<details>
</details>
=> Fix deactivated icon being shown in message avatar for inaccessible users.

help/include/edit-organization-profile.md, help/include/organization-profile-intro.md, help/include/organization-type-intro.md, help/organization-type.md
CZO discussion: [#design > organization name](https://chat.zulip.org/#narrow/channel/101-design/topic/organization.20name/with/2161693)
<details>
<summary>
Updated
</summary>
</details>
<details>
<summary>
Updated
</summary>
</details>
=> help: Expand organization profile description.

zerver/lib/webhooks/git.py, zerver/webhooks/gitlab/fixtures/merge_request_hook__merge_request_approval.json, zerver/webhooks/gitlab/fixtures/merge_request_hook__merge_request_unapproval.json, zerver/webhooks/gitlab/tests.py, zerver/webhooks/gitlab/view.py
This pull request introduces support for the 'approval' and 'unapproval' webhook events from gitlab to the Zulip integration.
This implementation includes:
- Handling of the webhook payloads for these events in `zerver/webhooks/gitlab/view.py`.
- Creation of appropriate Zulip message content based on the event type.
- Addition of test cases in `zerver/webhooks/gitlab/tests.py` to ensure correct functionality.
Fixes: https://github.com/zulip/zulip/issues/34222
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html)) …
=> integrations: Handle approval/unapproval for GitLab MRs.

templates/zerver/integrations/include/download-python-bindings.md
Replaced "server" with "system" so that the macro can be used with all integrations with integration scripts, irrespective of whether it needs to be run from a server or a user's machine.
Replaced "bot" with "integration script" to ensure that the integration script is not confused with the Zulip bot user that is created using the UI in the instruction above this instruction.
<details>
<summary><h3>Screenshot</h3></summary>
Example usage: [Git doc](https://zulip.com/integrations/doc/git)
Before:
After:
</details>
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit …
=> integration-docs: Clarify the installation macro.

zerver/lib/onboarding.py
Part of #34447:
>**Welcome bot message**
>
>"Note that this is a [demo organization](http://demo-dzcx2264.zulipdev.com:9991/help/demo-organizations) and will be automatically deleted in 30 days."
->
>"Note that this is a [demo organization](https://github.com/help/demo-organizations) and will be automatically deleted in 30 days, unless it's [converted into a permanent organization](https://github.com/help/demo-organizations#convert-a-demo-organization-to-a-permanent-organization)."
| --- | --- |
| ![Screenshot from 2025-04-25 17-51-13](https://github.com/user-attachments/assets/fefe0df3-0929-472c-a4d5-e54b4d319c9f) | ![Screenshot from 2025-04-25 17-56-19](https://github.com/user-attachments/assets/5891771c-788f-4b4d-99a4-d4684be35b88) …
=> demo-orgs: Expand note about demo organizations in Welcome bot DM.

web/src/invite.ts, web/templates/invite_user_modal.hbs
We only render the informational banners about configuring organization settings for:
- Non-demo organizations
- Users with admin privileges
Follow-up to #34465.
---
| Reusable link | Email invite |
| --- | --- |
| ![Screenshot from 2025-04-25 17-25-44](https://github.com/user-attachments/assets/3bfe29c9-d3f3-4c9a-87ed-ddb2536ffbfd) | ![Screenshot from 2025-04-25 17-25-32](https://github.com/user-attachments/assets/234c01a3-cb0f-4c08-98f5-ad2fb169e910)
| Reusable link | Email invite |
| --- | --- |
| ![Screenshot from 2025-04-25 17-31-19](https://github.com/user-attachments/assets/c78b8438-6412-4f6f-8d7e-8e77f4045c6d) | ![Screenshot from 2025-04-25 17-30-46](https://github.com/user-attachments/assets/8758c15a-142f-4612-a794-714c6293ad0f)
| Reusable …
=> invite-modal: Render banners for non-demo orgs and admin users only.

web/templates/demo_organization_add_email_modal.hbs
Part of #34447:
>**Add email modal**
>Change the "If you haven't updated your name..." banner to plain text that says:
>
>If you haven't updated your name, you may want to do so before inviting other users to join.
Instead of using the "tip" formatting for the note suggesting updating the name for the owner's account before inviting other users, to be just normal text at the top of the modal.
| --- | --- |
| ![Screenshot from 2025-04-25 18-00-54](https://github.com/user-attachments/assets/7da4abc7-d7c4-4660-b272-571a22a20ed2) | ![Screenshot from 2025-04-25 18-00-12](https://github.com/user-attachments/assets/896ec481-4cd6-49dc-a9fe-c3ef514b4ae5)
---
<details> …
=> demo-orgs: Update note about updating name in add email modal.

web/tests/people.test.cjs
Introduced in 51d382f7171aa09bda3bf5a8d1e771d7481ea219, cc @shubham-padia
=> people: Remove stray console.logs that made it into main.

web/src/message_store.ts, web/src/server_events_dispatch.js, web/src/stream_topic_history.ts, web/tests/dispatch_subs.test.cjs, web/tests/message_store.test.cjs, web/tests/stream_topic_history.test.cjs
This PR adds code to live update the message view when user loses access to a stream
and also remove the data of messages from that stream.
Fixes:  https://chat.zulip.org/#narrow/channel/101-design/topic/live.20updating.20message.20view.20when.20losing.20access.20to.20a.20stream/with/2155465
<details>
</details>
=> message_view: Live update on losing access to a stream.

web/tests/lib/index.cjs
[Discussion](https://chat.zulip.org/#narrow/channel/6-frontend/topic/tests.20stop.20running.20in.20--coverage.20with.20async.20call/near/2163304).
=> tests: Assume failure in case the async task vanishes

web/src/tippyjs.ts
Follow up from https://github.com/zulip/zulip/pull/34492#issuecomment-2840881730:
> On the other tooltip, I think we can make it a bit nicer by removing "you must".
This is the tooltip shown when hovering over the **Who can access your email address** setting before the demo organization owner has added an email to their account.
| --- | --- |
| ![Screenshot from 2025-04-30 17-47-03](https://github.com/user-attachments/assets/e76825fe-f207-44eb-98f8-221489280415) | ![Screenshot from 2025-04-30 17-46-48](https://github.com/user-attachments/assets/8301255f-1477-4aa0-aad3-8b52d302fe40)
---
<details> …
=> demo-orgs: Update tooltip for disabled personal email access setting.

templates/zerver/realm_creation_form.html, tools/linter_lib/custom_check.py
**Updates**:
- Removes the placeholder text and hint.
- Adds a link to the help center article about [creating your organization profile](https://zulip.com/help/create-your-organization-profile), which was updated in [#34495](https://github.com/zulip/zulip/pull/34495).
[Relevant CZO design discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/organization.20name/with/2161743)
Fixes #34496.
---
| --- | --- |
| ![Screenshot from 2025-05-01 13-38-59](https://github.com/user-attachments/assets/1fbe2555-9c10-4f10-b80d-ff2276a59167) | ![Screenshot from 2025-05-01 13-39-08](https://github.com/user-attachments/assets/36a48224-8bcf-4e8b-8801-7e4c53247e9c)
---
<details> …
=> create-realm: Simplify name field on new organization form.

web/styles/settings.css
This PR removes the top padding from `.organization-settings-parent`  from org settings elements. This makes vertical spacing consistent with other sections.
Fixes: [czo](https://chat.zulip.org/#narrow/channel/9-issues/topic/too.20much.20vertical.20spacing.20around.20heading.20in.20settings)
| --- | --- |
| ![Before Image](https://github.com/user-attachments/assets/9beb7a35-2344-4833-8bdb-f01be47cee55) | ![After Image](https://github.com/user-attachments/assets/5f966c45-bb80-4d2b-a5e8-b2cc353ff567) |
<details> …
=> settings_ui: Remove top padding from sections for org settings.

web/src/channel.ts, web/tests/channel.test.cjs
=> channel: Remove PATCH as POST workaround

web/src/peer_data.ts
Followup to https://github.com/zulip/zulip/pull/34434#discussion_r2073976037
=> peer_data: Remove extraneous await.

web/src/compose_pm_pill.ts, web/src/compose_validate.ts, web/tests/compose_validate.test.cjs
This should no longer be possible because we validate emails before creating user pills.
=> compose_validate: Remove invalid email messaging.

api_docs/changelog.md, api_docs/include/rest-endpoints.md, tools/merge-api-changelogs, version.py, zerver/lib/mention.py, zerver/lib/message_report.py, zerver/models/realms.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_audit_log.py, zerver/tests/test_message_report.py, zerver/views/message_report.py, zilencer/management/commands/populate_db.py, zproject/urls.py
This PR introduces a new API for message reporting. This API enables the users to report a message to admins and moderators for review.
Fixes part of #20047.
Design discussion: [CZO](https://chat.zulip.org/#narrow/channel/101-design/topic/report.20message.20feature.20.28.2320047.29/with/2034758)
API discussion: [CZO](https://chat.zulip.org/#narrow/channel/378-api-design/topic/message.20report.20.20API.20.2332811/with/2027388)
<details>
<summary>Reported messages (DM, channel message, GDM) updated May 5 2025:</summary>
</details>
<details>
<summary>If opened:</summary>
</details>
<details>
<summary>API doc  (updated April 29, 2025): </summary>
<details>
Communicate …
=> api: Add a new endpoint for message reporting.

analytics/management/commands/populate_analytics_db.py, zerver/actions/create_user.py, zerver/lib/test_classes.py, zerver/migrations/0700_fix_user_role_system_groups.py, zerver/tests/test_auth_backends.py, zerver/tests/test_signup.py, zproject/backends.py
Backports #34510 and #34533. Ref #34573 which tweaks the original migration to support this backport.
=> 10.x: Backport LDAP role sync fixes, including migration

tools/run-dev
Vite introduced allowedHosts config at
https://vite.dev/config/server-options#server-allowedhosts. This caused our help beta dev server to break in case of dev droplets since it's hostname is not specified in the allowed lists. Since we have a way to know our hostname, we do not pass a blanket true for all hostnames in this case.
Full disclosure: I was not able to get allowedHosts: true to get working, but since we might not want to go that way anyways, I didn't dig deep into making it work.
<details> …
=> help-beta: Pass allowedHosts when running dev server.

web/src/typeahead_helper.ts, web/tests/composebox_typeahead.test.cjs, web/tests/typeahead_helper.test.cjs
Work towards https://github.com/zulip/zulip/issues/34244.
=> typeahead_helper: Fetch full subscriber list while sorting.

web/src/server_events_dispatch.js
https://api.jquery.com/toggleClass/
=> server_events_dispatch: Use two-argument toggleClass

corporate/lib/support.py
Follow-up for https://github.com/zulip/zulip/pull/34584#discussion_r2080299035:
> 1 MB is 1000² bytes, not 1024² bytes, which is 1 MiB.
**Updated screenshot**:
---
<details>
</details>
=> support: Fix unit for file upload usage information.

web/styles/message_row.css
Related article: https://adamsilver.io/blog/buttons-shouldnt-have-a-hand-cursor/
Fixes: https://chat.zulip.org/#narrow/channel/137-feedback/topic/.60cursor.3A.20pointer.60.20applied.20to.20whole.20message.20content/with/2167059
|Before | After |
|-----|-------|
|![image](https://github.com/user-attachments/assets/60fc6a33-d6de-46cd-986a-91c0626b6c2d)| ![image](https://github.com/user-attachments/assets/9eb18522-286c-458c-8bf5-968e779a2128)|
<details> …
=> message_row: Remove `cursor:pointer` for messagebox.

puppet/kandra/files/install-ssh-keys, puppet/kandra/manifests/profile/postgresql.pp, puppet/kandra/manifests/profile/prod_app_frontend.pp, puppet/kandra/manifests/profile/staging_app_frontend.pp, puppet/kandra/manifests/ssh_keys.pp
=> kandra: Install multiple root ssh keys on the PostgreSQL primary.

puppet/zulip/manifests/profile/postgresql.pp, puppet/zulip/templates/postgresql/14/postgresql.conf.template.erb, puppet/zulip/templates/postgresql/zulip.conf.template.erb
=> Postgres tuning

web/styles/typeahead.css
This adds a gap--whose initial zero value is mysterious--between the topic and _New_ indicator, when present, in the compose typeahead.
There appear to be no other elements other than the _New_ indicator in this area of the typeahead, so it seems unlikely this should cause unexpected regressions elsewhere.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.22New.22.20topic.20indicator.20too.20close/with/2163199)
| --- | --- |
| ![new-topic-typeahead-before](https://github.com/user-attachments/assets/081ae528-2753-411b-ac6d-600efedccfd4) | ![new-topic-typeahead-after](https://github.com/user-attachments/assets/df83a72a-92d3-4a2e-9832-92d2147a2917) |
<details> …
=> compose_typeahead: Add gap between topic, New indicator.

web/src/invite.ts, web/src/peer_data.ts, web/styles/zulip.css, web/templates/guest_visible_users_message.hbs, web/templates/invite_user_modal.hbs, web/tests/peer_data.test.cjs
=> invite: Fetch full user set for get_unique_subscriber_count_for_streams.

api_docs/construct-narrow.md, api_docs/message-formatting.md, tools/merge-api-changelogs
- Fixed `merge-api-changelogs` tool to update version too, along with the feature level in API docs.
- Fixed feature levels in `api_docs` files.
- Fixed `merge-api-changelogs` tool to update files in `api_docs` folder along with `zulip.yaml`.
<details>
</details>
=> Fix `merge-api-changelogs` tool. 

help-beta/astro.config.mjs, help-beta/package.json, pnpm-lock.yaml, tools/convert-help-center-docs-to-mdx, version.py
This PR will not show icons for included files. The problem there is not with the approach we've taken here but instead, we need to add certain mdx capabilities to included files and not let them be .md files. Nested includes don't work currently for included files, and any other support added via `convert-help-center-to-mdx` won't work. We should address this issue in another PR.
First commit does not directly handle the issue at hand but makes it easier to keep track of imports and adds them to the relevant MDX file in a much more readable way.
<details> …
=> help-beta: Add support for icons

web/styles/message_row.css
Fixes: https://chat.zulip.org/#narrow/channel/137-feedback/topic/.60cursor.3A.20pointer.60.20applied.20to.20whole.20message.20content/near/2172361
`EDITED` label
|-------|-------|
|![EDITED_BEFORE](https://github.com/user-attachments/assets/f84fd271-d87c-4d1b-9d42-9a8817617a06) | ![EDITED_AFTER](https://github.com/user-attachments/assets/e0a8955a-f70b-4d93-b0c1-8f8ddc4779ad)|
`MOVED` label
|-------|-------|
|![MOVED_BEFORE](https://github.com/user-attachments/assets/0ea592d2-4045-4684-b76d-a101453e7d4d)|![MOVED_AFTER](https://github.com/user-attachments/assets/7eb39b0f-7106-4694-9474-4a128a22f49d)
<details>
Communicate …
=> message_row: Add `cursor:pointer` for edit notices.

help-beta/astro.config.mjs, tools/convert-help-center-docs-to-mdx
Earlier, we were just renaming the files in help/include and copying them over. Which meant that none of the mdx features or any of the components we add could be used there. We could also not support nested imports which are a part of the help/include files.
1st commit fixes a bug of FA icons not being rendered properly. The next 3 commits are refactors and the last one modifies things.
<details>
</details>
=> Include files should have all MDX capabilities

web/src/demo_organizations_ui.ts, web/src/invite.ts, web/src/settings_org.ts, web/styles/app_components.css, web/templates/invite_user_modal.hbs, web/templates/settings/auth_methods_settings_admin.hbs, web/templates/settings/convert_demo_organization_form.hbs
Fixes: #34448.
|---|----|
| <img width="594" alt="Screenshot 2025-05-04 at 1 21 24 AM" src="https://github.com/user-attachments/assets/1f734a89-77db-4782-b526-43e26602430d" /> | <img width="595" alt="Screenshot 2025-05-08 at 3 27 52 AM" src="https://github.com/user-attachments/assets/10a2e382-36bb-4d96-995b-a148ff295272" /> |
|<img width="594" alt="Screenshot 2025-05-04 at 1 21 17 AM" src="https://github.com/user-attachments/assets/5eddad25-c8f5-417d-8483-c5833b3b3dbd" /> | <img width="595" alt="Screenshot 2025-05-08 at 3 28 02 AM" src="https://github.com/user-attachments/assets/a1a6833a-492a-4ff9-8fe9-c7147379cb52" /> |
| ![Screenshot from 2025-05-13 14-36-51](https://github.com/user-attachments/assets/242d2844-80fb-4d34-afe2-c08d8e4 …
=> banners: Redesign "configure your email" banners.

web/styles/rendered_markdown.css
This is a follow-up to #34529, which @timabbott [noted](https://github.com/zulip/zulip/pull/34529#issuecomment-2874719599) neglected to include the updated border color on blockquotes as specified for LTR languages.
I have posted some additional concerns about how recent changes to RTL languages work with our system for compiling CSS, which I've posted to [#frontend > &#42;-inline-start properties](https://chat.zulip.org/#narrow/channel/6-frontend/topic/*-inline-start.20properties/with/2173307); those concerns may well warrant additional RTL followups for lists in particular.
| --- | --- |
| ![rtl-blockquotes-before](https://github.com/user-attachments/assets/8c753b99-6b17-4b11-aea0-35b8148162d5) | …
=> markdown: Apply correct color var to RTL blockquotes.

puppet/kandra/manifests/profile/postgresql.pp, puppet/kandra/manifests/profile/prod_app_frontend.pp, puppet/kandra/manifests/profile/staging_app_frontend.pp
=> kandra: Remove PostgreSQL upgrade key.

tools/setup/bootstrap-aws-installer
=> kandra: Install PostgreSQL 17 by default.

templates/zerver/realm_import_post_process.html, templates/zerver/slack_import.html, tools/lib/capitalization.py, tools/linter_lib/custom_check.py, web/src/portico/signup.ts, web/styles/portico/portico_signin.css, zerver/actions/data_import.py, zerver/forms.py, zerver/tests/test_slack_importer.py, zerver/views/registration.py, zerver/worker/deferred_work.py, zproject/default_settings.py, zproject/urls.py
=> Add UI flow to import from slack.

help-beta/astro.config.mjs, help-beta/src/components/KeyboardTip.astro, help-beta/tsconfig.json, tools/convert-help-center-docs-to-mdx
Fixes: #31249
<details>
</details>
=> help-center-stage-2: add support for tip box 

zproject/backends.py
Trying to sync system groups with this would easily lead to database corruption and we should completely disallow it.
https://github.com/zulip/zulip/pull/34641#discussion_r2091652091
=> sync_groups: Don't allow syncing of system groups.

web/src/portico/integrations.ts
Commit 7c485c1302dab4b3adb49fb9d1a9a42f3dc050b8 (#17654) removed this class.
=> integrations: Remove obsolete .integration-create-your-own references

corporate/lib/stripe.py, templates/zerver/emails/find_team.txt, templates/zerver/emails/password_reset.html, templates/zerver/emails/password_reset.txt, templates/zerver/emails/realm_auto_downgraded.html, templates/zerver/emails/realm_auto_downgraded.subject.txt, templates/zerver/emails/realm_auto_downgraded.txt, zerver/actions/users.py, zerver/lib/send_email.py, zerver/views/registration.py, zerver/worker/email_senders_base.py
=> Fix and test that context in emails can round-trip through JSON

puppet/kandra/manifests/profile/postgresql.pp, puppet/zulip/manifests/postgresql_base.pp, puppet/zulip/manifests/postgresql_common.pp, puppet/zulip/manifests/profile/postgresql.pp, puppet/zulip/manifests/supervisor.pp, scripts/setup/upgrade-postgresql
=> upgrade-postgres fixes

help/import-from-slack.md
This can be merged and used for anchor links being added in [#34649](https://github.com/zulip/zulip/pull/34649).
Current: https://zulip.com/help/import-from-slack#export-your-slack-data
Updated:
=> help: Tweak Slack export instructions.

zerver/data_import/slack.py, zerver/lib/import_realm.py, zerver/tests/test_slack_importer.py
These commits fix a few issues we encountered in a complicated Slack import.
=> Batch of minor fixes to Slack imports

web/src/user_card_popover.ts
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/error.20when.20opening.20card.20for.20imported.20user/with/2174656)
<details>
</details>
=> presence_data: Add fallback logic for users with no presence data.

help/archive-a-channel.md, zerver/lib/markdown/help_relative_links.py
Documents #34016 / #33917.
Before: https://zulip.com/help/archive-a-channel#unarchiving-archived-channels
After:
=> help: Document UI for unarchiving a channel.

help/deactivate-a-user-group.md
This PR adds instructions for reactivating a group.
http://localhost:9991/help/deactivate-a-user-group
<details>
</details>
=> help: Add instructions for reactivating a group.

docs/production/postgresql.md, puppet/zulip/files/postgresql/process_fts_updates, puppet/zulip/manifests/profile/standalone_nodb.pp
=> Performance improvements to process_fts_updates

web/styles/portico/portico.css, web/styles/portico/portico_signin.css
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/Inconsistent.20UI.20at.20login.20screen.20of.20demo.20org.20at.20narrow.20screen/with/2165723)
| ![before-subscribe](https://github.com/user-attachments/assets/a57ae19a-0e43-4d1b-9a1a-c71635fcc541)) | ![after-subscribe](https://github.com/user-attachments/assets/a420033e-3f42-4749-8acd-ff07bb14c7c2)) |
| ![before-unsubscribe](https://github.com/user-attachments/assets/68535257-e21e-4584-9a2c-e96e4b464df0) | ![after-unsubscribe](https://github.com/user-attachments/assets/73b73795-7d30-4cef-88f3-e9d712f50dd3)
<details> …
=> Styles: improve the style of login screen

puppet/kandra/files/process_exporter.yaml
=> process_exporter: Monitor the standalone email_server.

templates/zerver/realm_creation_form.html
| --- | --- |
|![image](https://github.com/user-attachments/assets/eee258f6-6d11-4fed-9d87-99a7cdfcdbcf) | ![image](https://github.com/user-attachments/assets/93a0e51a-2a6a-4d3b-a856-f723f21f06fa) |
Followup from #34648
=> realm_creation_form: Change style of import tooltip.

web/templates/settings/organization_permissions_admin.hbs
| Before     | After      |
|------------|------------|
| ![image](https://github.com/user-attachments/assets/4a3db974-703e-4674-9aac-cc058783f09f) | ![image](https://github.com/user-attachments/assets/ed305581-d573-4a4a-b8d1-0a0b36ac130d) |
<details>
</details>
=> organization_settings: Fix label text.

web/src/admin.ts, web/src/hash_util.ts, web/src/server_events_dispatch.js, web/src/user_group_edit.ts, web/templates/user_group_settings/user_group_settings_overlay.hbs
- First commit is a small refactor.
- Second commit is to live update UI when `can_create_user_groups` setting is changed.
- Third commit is to redirect `#groups/new` to `#groups/your` for limited plan realms.
<details>
</details>
=> Live update UI on changing `can_create_user_groups` setting.

zerver/lib/email_notifications.py, zerver/tests/test_email_change.py, zerver/views/user_settings.py
When a demo organization creator confirms their initial email change for their account (i.e., the first time we have an email address for this user), we now schedule the series of onboarding emails via `enqueue_welcome_emails`.
**Notes**:
- If a demo organization is deactivated/deleted before the emails are sent, any scheduled emails are already deleted as part of that process, so it seems fine to schedule them even if the `realm.demo_organization_scheduled_deletion_date` is pending. They may be setting their email address in order to convert the demo organization into a permanent organization before that date.
- We use the current datetime for getting the onboarding schedule for the onboarding emails in this case, instead of the datetime the user joined/created the organization.
--- …
=> demo-orgs: Schedule onboarding, welcome emails when owner adds email.

zerver/lib/zulip_update_announcements.py
I tested the links.
Screenshot:
[#release management > zulip_updates items of note @ 💬](https://chat.zulip.org/#narrow/channel/438-release-management/topic/zulip_updates.20items.20of.20note/near/2178084)
=> updates: Add update message (level=16).

templates/zerver/emails/find_team.html, templates/zerver/emails/find_team.txt, zerver/views/registration.py
This was broken in the refactor in 0078310be76e.
Fixes: 
<details>
</details>
=> find_account: Fix HTML version of email.

web/src/navbar_menus.ts, web/src/popover_menus.ts, web/src/settings_panel_menu.ts, web/src/upload.ts, web/src/user_card_popover.ts, web/src/user_group_popover.ts, web/tests/upload.test.cjs
=> Finish avoiding jQuery sizzle extension `:visible`

zerver/lib/push_notifications.py
In aioapns 4.0, which we upgraded to in acd73535380e, the `key` parameter is treated as the ASCII-armored string contents of the key, not the path to the file with that content.
Read the file ourselves, and pass the string it expects.
Fixes: 
<details>
</details>
=> push_notifications: Update for breaking change in aioapns 4.0.

web/postcss.config.js
[Discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/Profile.20labels.20look.20faint/near/2180588).
=> postcss: Work around postcss-extend-rule incompatibility with :is()

zerver/lib/send_email.py
Servers without any configured credentials raise a NoCredentialsError, which is not a subclass of botocore.exceptions.ClientError, and hence abort the password reset attempt.
Check for if we have any credentials at all before we attempt the API call.
Fixes: 
<details>
</details>
=> send_email: Only attempt suppression list removal with credentials.

web/styles/inbox.css
This PR does a sweep for problem instances of `:focus`, and swaps them with the keyboard-appropriate `:focus-visible` pseudoclass.
[#issues > extraneous selection box in inbox](https://chat.zulip.org/#narrow/channel/9-issues/topic/extraneous.20selection.20box.20in.20inbox/with/2183063)
<details>
</details>
=> inbox: Swap :focus for :focus-visible where necessary.

web/styles/right_sidebar.css
[#issues > emoji status cut off in user list](https://chat.zulip.org/#narrow/channel/9-issues/topic/emoji.20status.20cut.20off.20in.20user.20list/with/2182505)
| --- | --- |
| ![avatar-status-emoji-before](https://github.com/user-attachments/assets/abb9c2e6-b89c-4e2e-b95e-2f27cabe8dbc) | ![avatar-status-emoji-after](https://github.com/user-attachments/assets/fdec7f57-4a4d-4f5a-aeb8-c99745515ba2) |
| ![avatar-status-emoji-hover-before](https://github.com/user-attachments/assets/57c84f85-6dba-4717-b695-0d2c3bf69efa) | ![avatar-status-emoji-hover-after](https://github.com/user-attachments/assets/abfba5ee-15e1-4e20-960e-9278dec55cd0) |
<details> …
=> right_sidebar: Adjust spacing to accomodate status emoji.

templates/zerver/integrations/errbot.md
Fixes: Part of zulip#29592.
Separated out from #32354.
<details>
<summary><h3>Old Screenshots</h3></summary>
Please refer to the screenshots included in the latest update comment.
[Doc link](https://zulip.com/integrations/doc/errbot)
</details>
<details>
</details>
=> integration-docs: Update Errbot for new doc format.

web/src/compose_recipient.ts, web/src/dropdown_widget.ts, web/styles/app_components.css, web/styles/zulip.css, web/templates/dropdown_list.hbs
This PR ensures the hover state appears on the first item in the list by default, without requiring initial arrow key input. It allows navigation through the list using Up/Down arrows while keeping the browser focus in the text input.
Fixes: #33448.
| When Open                     | Arrow Up/Down                | Search                         | 
|-------------------------------|------------------------------|------------------------------|
| ![When Open](https://github.com/user-attachments/assets/f095c0cc-2e03-476d-9772-0444126cde4c) | ![Arrow Up/Down](https://github.com/user-attachments/assets/107de294-12ac-48ca-9a2b-195daa5e14b2) | ![Type](https://github.com/user-attachments/assets/1fbd3a82-381e-44ec-af79-f6fc3210c405) |
<details> …
=> dropdown_widget: Keep focus in input with hover navigation.

tools/convert-help-center-docs-to-mdx
=> help-beta: Convert MD comments to MDX comments.

tools/convert-help-center-docs-to-mdx
If the file names are in Pascal case in the first place, it will decrease mental load for any editor to convert a kebab case name to Pascal case name.
#34765 needs to be reviewed and merged first and then this PR needs to be rebased on top of it. If this PR is getting merged, I would appreciate help with the rebase if it's a conflict-free rebase.
<details>
</details>
=> Help beta include naming

web/src/integration_url_modal.ts
When the override-topic checkbox becomes checked, and the topic-input gets its "hide" class removed, place the cursor inside the textbox.
Close the stream dropdown before processing the selected option, to prevent it overriding the focus.
Previously part of #34353
[Screencast from 2025-06-04 14-01-11.webm](https://github.com/user-attachments/assets/a2aaa8bb-d759-47bd-8e30-3a14763920dd)
<details>
</details>
=> integration-url-modal: Focus on the topic input when it is displayed.

zerver/webhooks/slack/view.py
Currently, the hyperlink on the "Zulip development community" string is not properly formatted. This fixes the formatting on the string.
broken link:
fixed:
<details>
</details>
=> integrations: Fix Slack debugging notification message.

web/src/buddy_list.ts
Follow-up to https://github.com/zulip/zulip/pull/34677#discussion_r2112962338
=> buddy_list: Add clarity around not showing user links when searching.

pyproject.toml
aiosmtpd added types in 1.3.0.
=> mypy: Remove unused exemption for aiosmtpd

zerver/management/commands/export_search.py
Previously, the `export_search` command only supported the legacy `Personal` recipient type for 1:1 direct messages. With this change, the command first checks for a `DirectMessageGroup` for the two users and uses it if present. If not, it falls back to the legacy logic. This keeps compatibility as we migrate 1:1 DMs to use `DirectMessageGroup`.
<details>
</details>
=> export_search: Support --dm option for 1:1 DMs using DM group.

zerver/lib/message.py, zerver/tests/test_message_flags.py
In `get_raw_unread_data`, 1:1 or self messages are added to `pm_dict`. However, if a `DirectMessageGroup` is the recipient, the message is added to `huddle_dict` by default.
To keep API compatibility, we override this behavior by populating `pm_dict` for 1:1 and self DMs when a `DirectMessageGroup` exists. This ensures clients relying on `pm_dict` continue to work during and after the migration.
Fixes: part of issue #25713.
<details>
</details>
=> messages: Add unread 1:1/self DMs to pm_dict if DM group exists.

docs/overview/changelog.md, docs/production/authentication-methods.md, docs/production/management-commands.md, docs/production/mobile-push-notifications.md
Follow-up to https://github.com/zulip/zulip/pull/32553#issuecomment-2536011444:
> **Additional follow-up**:
> - Updating existing links to these help center articles in `docs/` once these changes are in production. See below.
> 
> ```
> $ git grep 'help/roles-and-permissions'
> docs/overview/changelog.md:[roles-and-permissions]: https://zulip.com/help/roles-and-permissions
> docs/production/authentication-methods.md:[user-role-help-center]: https://zulip.com/help/roles-and-permissions
> docs/production/mobile-push-notifications.md:owners](https://zulip.com/help/roles-and-permissions) and billing administrators
> zerver/lib/url_redirects.py:    URLRedirect("/help/roles-and-permissions", "/help/user-roles"),
> zerver/lib/zulip_update_announcements.py: …
```
=> docs: Update links help center links that redirect "/user-roles".

zerver/lib/email_mirror_server.py
The only other flavor we have seen so far is ConnectionResetError, but that is just as much a client error which we should log and move on, and not log an exception for.
Fixes: 
<details>
</details>
=> email_mirror_server: Swallow and log all TLSSetupExceptions.

web/src/message_view.ts
Reproducer:
* Navigate to a channel using `near` link with no recent history such that `all_messages_data` has no history cached for it. The data for this channel narrow is not added to `all_messages_data` to keep the history of `all_messages_data` contiguous.
* Press scroll down button, you will see an error.
Fixed by checking if the message list data is empty before narrowing and asking server for messages if that's the case.
This is hard to test but this is the most likely theory.
=> message_view: Fix error on pressing scroll to latest button.

web/src/drafts_overlay_ui.ts, web/src/messages_overlay_ui.ts, web/src/scheduled_messages_overlay_ui.ts, web/styles/settings.css, web/templates/draft.hbs, web/templates/draft_table_body.hbs, web/templates/scheduled_message.hbs, web/templates/scheduled_messages_overlay.hbs, web/templates/tooltip_templates.hbs, web/tests/drafts.test.cjs
Fixes: #34380.
| Before(Dark) | After(Dark | Before(Light) | After(Light) |
|------|-------|-----|------|
| ![image](https://github.com/user-attachments/assets/485c8531-5739-406b-a3d7-157a516dac99) | ![image](https://github.com/user-attachments/assets/3761efa2-44d9-4fe0-a7d5-fe0870a5c6fe)|![image](https://github.com/user-attachments/assets/74056421-4906-4c5e-978f-8ae443f8200e)|![image](https://github.com/user-attachments/assets/0ba9ab48-488f-43a2-aa51-540e1dac81f0)
For mac, see https://github.com/zulip/zulip/pull/34385#issuecomment-2931024251
| Before(Dark) | After(Dark | Before(Light) | After(Light) |
|------|-------|-----|------|
| ![image](https://github.com/user-attachments/assets/4fea0bc7-5561-486a-bd64-dc3f3b44c851)|![image](https://github.com/use …
=> overlay: Clarify editing UI for drafts and scheduled messages.

web/styles/rendered_markdown.css
To properly increment counters, and display lists of the correct type when nested, we need to use child selectors and not the previous, overly generic descendant selectors.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/numbers.20shown.20for.20unordered.20list/with/2191994)
| --- | --- |
| ![nested-lists-before](https://github.com/user-attachments/assets/892e96ee-7ca4-4843-a23e-75211ddb4730) | ![nested-lists-after](https://github.com/user-attachments/assets/85884555-ef2f-4e3e-8303-aee99c47f28c) |
| ![live-example-before](https://github.com/user-attachments/assets/13b5e510-0e4f-4881-b739-ef03ae6e05f2) | ![live-example-after](https://github.com/user-attachments/assets/811b2d7e-7dff-4d94-a62e-c69883a53384) |
<details> …
=> rendered_markdown: Correct presentation of nested lists.

web/src/onboarding_steps.ts, web/src/state_data.ts, web/src/ui_init.js
=> onboarding_steps: Fix abnormal initialize calling convention

web/styles/app_variables.css
This PR sets the focus outline offset in action and icon buttons to 0, following the discussions at CZO concerning the visuals and jagged corners in some cases when the outline offset was applied.
Fixes: [#design > button keyboard selection indicators @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/button.20keyboard.20selection.20indicators/near/2195982)
| <img width="682" alt="Screenshot 2025-06-18 at 12 39 41 AM" src="https://github.com/user-attachments/assets/4d9ef945-a6f1-4591-afb2-ea1315fe8261" /> | <img width="682" alt="Screenshot 2025-06-18 at 12 39 16 AM" src="https://github.com/user-attachments/assets/f1fe86fe-52ff-457d-af9a-5762d1b09f91" /> |
| <img width="682" alt="Screenshot 2025-06-18 at …
=> buttons: Remove focus outline offset in action and icon buttons.

web/src/message_list_tooltips.ts
This PR removes empty tooltip for the recipient_bar_icon toggle resolve if server takes a bit of time to respond.
**Before:**
[Screencast from 2025-05-21 22-28-13.webm](https://github.com/user-attachments/assets/dd833bcc-531d-456b-b6de-cbe826d03cab)
**After:**
[Screencast from 2025-06-07 13-42-59.webm](https://github.com/user-attachments/assets/6a5cd2c4-f685-4932-b0f7-40f62e1f635d)
<details>
</details>
=> Fix empty tooltip on recipient row resolve topic spinner.

puppet/zulip/manifests/common.pp
This includes an upgrade to Prometheus 3 and Grafana 12.
Fixes: 
<details>
</details>
=> puppet: Upgrade dependencies.

zerver/data_import/slack.py, zerver/views/registration.py
Second commit closes the   last item of #34649
=> Slack import: Import Slackbot as a bot

zerver/views/development/dev_login.py
Showing these realms in the drop down list of realms is not helpful for developers, so we filter them out of the list. Realms that are deactivated without a redirect are still listed.
The redirect is better manually tested, as it's clearer what's going on, by putting the deactivated realm URL in the browser.
| --- | --- |
| ![Screenshot from 2025-06-19 19-19-11](https://github.com/user-attachments/assets/ac3eb7f6-8926-4451-a057-14de0f02e475) | ![Screenshot from 2025-06-19 19-18-36](https://github.com/user-attachments/assets/0c4b3551-f43e-49a3-a3ce-22cb858b31d3)
---
<details>
Individual …
=> dev-login: Filter placeholder realms from a subdomain change.

help/mention-a-user-or-group.md
Updates the "Mention a user or group" article to have a tip that links to the section on how message notifications work for mentions when editing a message's content.
See:
- [#documentation > Update "Mention a user or group" for mention notifications](https://chat.zulip.org/#narrow/channel/19-documentation/topic/Update.20.22Mention.20a.20user.20or.20group.22.20for.20mention.20notifications/with/2198263)
- [#user questions > Does at-mentioning a user in an edit notify them?](https://chat.zulip.org/#narrow/channel/138-user-questions/topic/Does.20at-mentioning.20a.20user.20in.20an.20edit.20notify.20them.3F/with/2197475)
---
<details> …
=> help: Add edit message tip for mentions notifications.

web/src/click_handlers.ts, web/src/stream_popover.ts, web/src/topic_popover.ts, web/styles/left_sidebar.css, web/templates/pm_list_item.hbs, web/templates/stream_sidebar_row.hbs, web/templates/topic_list_item.hbs
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/Clicking.20the.20right.20end.20of.20DM.20list.20items.20doesn't.20work/with/2189918
| ---- | ----|
| ![before](https://github.com/user-attachments/assets/c5b1a126-9790-4106-bb38-16a9537da450)|![dmbox](https://github.com/user-attachments/assets/33869476-781d-4477-860e-548d1819ddc9)| 
| ----  | ---- |
|![before-topics](https://github.com/user-attachments/assets/43205755-5a3e-4370-80ab-afdcc07e08c8)| ![after-topics](https://github.com/user-attachments/assets/2a05f954-19de-4d85-8e39-93de032edf09)| 
| --- | ----|
|![before](https://github.com/user-attachments/assets/4b29a51b-d2af-4599-9152-7618dcd37f86)|![after](https://github.com/user-attachments/assets/c94f29dd-9c83-4a30-b5ae- …
=> left_sidebar: Support clicks outside the row-content.

web/src/hotkey.js
Some browsers trigger a `keydown` event with `key === undefined` on selecting autocomplete suggestion. These are not real keypresses and can be safely ignored.
See: https://issues.chromium.org/issues/41425904
Earlier, not handling it was resulting in error later in the codepath.
Previously:
Now:
https://github.com/user-attachments/assets/d198a9fd-5205-4581-885f-55ee41419ef4
<details>
</details>
=> hotkey: Ignore keydown events with `event.key=undefined`.

templates/zerver/realm_creation_form.html
=> import: Label tweak.

web/styles/message_row.css
Fixes: https://chat.zulip.org/#narrow/channel/137-feedback/topic/.60cursor.3A.20pointer.60.20applied.20to.20whole.20message.20content/near/2203930.
https://github.com/user-attachments/assets/c2a158a6-e601-4e30-8357-82ccc609ce79
https://github.com/user-attachments/assets/5b689ddc-cf2e-4ea5-b586-80e61f4afcc5
<details>
</details>
=> message_row: Add `cursor: pointer` for all control icons.

templates/zerver/social_auth_select_email.html, web/src/portico/signup.ts
This commit makes the accounts in oauth page navigable on `Tab`.
Fixes:zulip#34724.
[Screencast from 2025-06-26 20-46-41.webm](https://github.com/user-attachments/assets/aa8efa57-0764-4b0b-b3de-063a665876d3)
<details>
</details>
=> Fix keyboard navigation on accounts in oauth.

web/src/stream_topic_history_util.ts, web/src/topic_list.ts, web/tests/stream_topic_history.test.cjs, web/tests/topic_list.test.cjs
[CZO bug report
](https://chat.zulip.org/#narrow/channel/9-issues/topic/.22more.20topics.22.20flashing/near/2202286)
* Commit 1: Small improvement
* Commit 2: Add retry mechanism to `stream_topic_history_util.get_server_history`.
* Commit 3: Fix the "show all topic" flashing bug.
<details>
</details>
=> topic_list: Fix "show all topics" flashing. 

help/change-the-channel-description.md, help/change-the-privacy-of-a-channel.md, help/change-your-language.md, help/channel-notifications.md, help/delete-a-topic.md, help/emoji-reactions.md, help/include/create-a-channel-instructions.md, help/introduction-to-channels.md, help/link-to-a-message-or-conversation.md, help/mute-a-channel.md, help/pin-a-channel.md, help/read-receipts.md, help/rename-a-channel.md, help/share-and-upload-files.md, help/start-a-call.md, help/status-and-availability.md, help/subscribe-users-to-a-channel.md, help/unsubscribe-from-a-channel.md
Adds back a tabbed section for mobile, with a note to use the web app instructions for the feature in a mobile device browser and with a link to the Flutter issue, for mobile features that were previously documented and implemented for the React Native app.
**Notes**:
- The updates here correspond to the commits in https://github.com/zulip/zulip/pull/34887 (note that a few features there have been implemented and documented since that was merged).
- Didn't add anything for the [/help/mobile-notifications](https://zulip.com/help/mobile-notifications) documentation that was removed in https://github.com/zulip/zulip/pull/34887/commits/31cc168018f5cf685544f8adc7081f8b3d8f70a7 as these are not web app features.
---
**This one is different from the other …
=> help: Add notes and links for previous mobile features.

web/src/unread_ops.ts
When offline, has_found_newest never ends up being true, and we'd end up falling through to an interleaved banner. We rewrite this logic with an explicit idea of whether we're online, and the following fixes:
- Never display the interleaved view confirmation banner in a conversation view.
- Avoid displaying that banner inaccurately when the actual problem is that we're offline.
- If we're offline, always call do_mark_unread with a list of IDs, such that if its helpers supported local echo (they don't), we will locally echo to the extent possible.
Note that following this change, being offline results in "mark unread" being a noop until you're online again. Better than a weird banner.
See https://chat.zulip.org/#narrow/channel/9-issues/topic/mark.20unread.20strange.20when.20disconnected/nea …
=> unread_ops: Fix mark-as-unread handling of has_found_newest.

docs/subsystems/thumbnailing.md, zerver/management/commands/thumbnail.py
=> thumbnail: Add flag for when thumbnail files are missing.

puppet/zulip/files/postgresql/process_fts_updates, tools/semgrep-py.yml
Although this code was not actually vulnerable as written, we never want to be disabling this Ruff rule, in order to discourage later introduction of vulnerabilities.
Cc @alexmv (#34662).
=> process_fts_update: Fix S608 Possible SQL injection vector

docs/production/management-commands.md
This management command was renamed in commit 7ef1a024db4, but the documentation was not updated at that time.
See [#issues > missing command clear_auth_rate_limit_history](https://chat.zulip.org/#narrow/channel/9-issues/topic/missing.20command.20clear_auth_rate_limit_history/with/2208080).
---
<details>
</details>
=> docs: Fix renamed reset_authentication_attempt_count command.

web/styles/zulip.css
This overscroll-behaviour was changed earlier to fix sliding of message_feed_container but later separate PR addressed root cause for the issue. This overscroll change did end up preventing swipe gesture navigations.
This commit corrects the swipe behaviour for navigations.
Fixes: [#issues > 🎯 Touchpad swiping left/right gestures don't work on CZO @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Touchpad.20swiping.20left.2Fright.20gestures.20don't.20work.20on.20CZO/near/2208095)
[Screencast from 2025-06-30 21-51-27.webm](https://github.com/user-attachments/assets/5f74b66c-3f88-479d-b437-191c9d7e656d)
<details> …
=> app: Allow overscroll on x-axis.

help/code-blocks.md, help/format-a-quote.md, help/latex.md, help/spoilers.md
Follow-up to https://github.com/zulip/zulip/pull/34964#discussion_r2162103973:
Our custom code fence parser for Python-Markdown does not nest fenced code blocks inside list items, but it can be done with 4-space indented code blocks, as long the list item itself also uses 4-space indentation.
**Notes**:
- Used `git grep 'tab|via-markdown'` to find help articles with the issue pointed out in the comment above.
---
| --- | --- |
| <img width="626" alt="Screenshot 2025-06-30 at 19 04 32" src="https://github.com/user-attachments/assets/ed701a95-e822-4975-9903-b790d5046d05" /> | <img width="628" alt="Screenshot 2025-06-30 at 19 03 48" src="https://github.com/user-attachments/assets/ca6f571c-1e61-47ac-b2cf-630f38e5de49" />
| Before | After …
=> help: Fix code block indention in markdown instruction tabs.

web/src/hashchange.ts, web/src/scheduled_messages.ts, web/src/scheduled_messages_feed_ui.ts, web/src/scheduled_messages_overlay_ui.ts, web/src/scheduled_messages_ui.ts, web/templates/scheduled_message.hbs, zerver/actions/scheduled_messages.py, zerver/openapi/zulip.yaml
These commits are all extracted from #35039 to help save re-review work on that pull request.
=> Merge preparatory commits for #35039

zerver/lib/markdown/__init__.py, zerver/tests/test_markdown.py
Fixes https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20video.20preview.20not.20working.20.28Dropbox.29
<details>
</details>
=> Dropbox video

zerver/lib/subscription_info.py, zerver/tests/test_channel_fetch.py, zerver/tests/test_subs.py, zproject/default_settings.py
=> subscription_data: Flesh out partial suscription data sent to client.

web/e2e-tests/lib/common.ts, web/src/compose_send_menu_popover.js
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20compose.20menu.20error.20.28keyboard.20nav.29
=> Compose send menu popover bug fixes.

web/src/dialog_widget.ts, web/styles/app_variables.css, web/styles/modal.css, web/tests/bot_data.test.cjs, zerver/actions/users.py, zerver/tests/test_events.py, zerver/views/users.py
This is a prep PR for #34524.
<details>
</details>
=> prep PR for #34524.

web/e2e-tests/settings.test.ts, web/src/custom_profile_fields_ui.ts, web/src/dialog_widget.ts, web/src/settings_account.ts, web/src/ui_report.ts, web/src/user_profile.ts, web/styles/settings.css
- First commit is a small fix for resetting of notification element class.
- Second commit is a refactor commit.
- Third commit is to fix handling of manual date inputs.
Fixes:  #19936 
<details>
</details>
=> custom-profile-fields: Fix handling of manual date inputs.

web/e2e-tests/lib/common.ts
discussion: https://chat.zulip.org/#narrow/channel/43-automated-testing/topic/main.20failing/with/2210716
=> common: Add a proper delay.

web/src/sidebar_ui.ts
This part of the UI was removed from the sidebar in commit 2feee9d7568826ab53ee46997d181921a3ea0284. There is still unreachable codeblock inside right sidebar.
This PR removes the unreachable code.
<details>
</details>
=> sidebar: Remove realm-description code block in right sidebar.

docs/documentation/api.md, tools/merge-api-changelogs, tools/test-backend, zerver/lib/templates.py, zerver/openapi/merge_api_changelogs.py
Adds support for showing unmerged changelogs in "changelog.md" for testing purposes.
<details>
</details>
=> tools: Add support for viewing updated changelog for testing.

api_docs/http-headers.md, help/create-channels.md
Update the occurrences of channel names that still use backticks to use the convention of bold formatting.
Does not edit channel names that are used to demonstrate format/syntax.
<details>
<summary><h3>Before-After Screenshots</h3></summary>
[HTTP Headers doc link](https://zulip.com/api/http-headers)
[Create channels doc link](https://zulip.com/help/create-channels)
</details>
<details>
</details>
=> docs: Use bold formatting for channel names instead of backticks.

confirmation/models.py, templates/confirmation/confirm_preregistrationuser.html, templates/confirmation/redirect_to_post.html, web/src/portico/confirm-preregistrationuser.ts, web/src/portico/redirect-to-post.ts, web/webpack.assets.json, zerver/actions/invites.py, zerver/actions/user_settings.py, zerver/lib/email_validation.py, zerver/lib/scim.py, zerver/tests/test_auth_backends.py, zerver/tests/test_email_change.py, zerver/tests/test_signup.py, zerver/views/development/email_log.py, zerver/views/registration.py, zerver/views/user_settings.py, zerver/views/users.py, zproject/backends.py, zproject/urls.py
Fixes a few bugs we've recently identified.
=> Fix a few bugs in the email change confirmation flow

help/channel-notifications.md
Follow up for https://github.com/zulip/zulip/pull/35103#issuecomment-3029120122:
> I think this should still be the "Via channel settings" tab. The left sidebar is just a handy way to get there for a channel you're subscribed to. @laurynmm Can you put up a follow-up PR to make that tweak.
| --- | --- |
| <img width="760" alt="Screenshot 2025-07-07 at 10 12 45" src="https://github.com/user-attachments/assets/7d100131-d3a8-4bfa-8074-11bde4db5cad" /> | <img width="762" alt="Screenshot 2025-07-07 at 10 11 20" src="https://github.com/user-attachments/assets/2b4d5137-3a84-4b71-aeb5-4b0c5e2703b6" />
---
<details> …
=> help: Switch tab label for configure single channel notifications.

web/src/add_group_members_pill.ts
On removing a user or group pill from input, the user or group was not being removed from the table. This was because of `onPillRemove` not being set for the pill widget as it was removed by mistake while doing other changes in ec65dad063d835.
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Removing.20members.20from.20picker.20doesn't.20remove.20from.20list/with/2212411
<details> …
=> groups-ui: Fix members list not updating when creating groups.

analytics/tests/test_counts.py, zerver/actions/create_realm.py, zerver/tests/test_message_send.py
When creating a new organization, we now set the default email address visibility setting based on the organization type:
- For the majority of organizations (or if no type was specified), email address visibility is admin only.
- For education organizations, email address visibility is admins and moderators.
- For business organizations, email address visibility is set to all users.
**Notes**:
- There are two prep commits to update analytics tests and a cross realm DM test for sending messages, which depended on getting users via the email field.
- Manually tested in dev environment by creating education (non-profit), open-source and business organizations and verifying new user default settings.
Fixes #34859.
---
<details> …
=> create-realm: Configure default email visibility based on organization type.

.github/workflows/check-feature-level-updated.yml, tools/check-feature-level-updated
In the past, some API documentation changes were merged with unresolved placeholders like "ZF-..." instead of actual feature level numbers. This commit introduces a GitHub Action that scans the API docs for any occurrence of "ZF-". If found, it will fail the CI check and block the commit from being merged into main.
This ensures that all feature level references are properly updated before merging.
<details> …
=> github_actions: Check if feature levels are updated in API docs.

help/search-for-messages.md
In https://github.com/zulip/zulip-flutter/issues/252, we added search to the mobile app. This adds help center documentation for that feature.
**Notes**:
- When testing the feature on my Android device, I noted that the "Enter" key in my device's keyboard was the search icon, so I used that in the instructions. I assume that's true for the iOS app as well, but I couldn't verify that with the screenshots in https://github.com/zulip/zulip-flutter/pull/1662. If it's not, then we should modify the instructions to be accurate for both Android and iOS.
---
[CURRENT DOCUMENTATION](https://zulip.com/help/search-for-messages)
---
<details> …
=> help: Add mobile instructions in "Searching for messages" article.

zerver/actions/message_edit.py
Follow-up for https://github.com/zulip/zulip/pull/34961#discussion_r2195902632
<details>
</details>
=> message_edit: Cleanup empty topic check.

help/share-and-upload-files.md
I thought about adding this as a note to the instruction block above, but I think a dedicated section is better.
- Is it 2,000+ characters or more than 2,000?
Before: https://zulip.com/help/share-and-upload-files
After:
=> help: Document converting pasted text to a file.

zerver/lib/push_notifications.py
Fixes zulip/zulip-flutter#1617.
It turns out that an APNs token (which is a hex string) is equally valid in lower or upper case.  The old app would send the server the lower-case form of the token, but the new app sends the upper-case form.
Because we've been treating tokens case-sensitively, if the user upgrades from the old app to the new, that results in the server and bouncer each having two copies of the token (one lower-case and one upper-case), and therefore sending that device two copies of each notification: zulip/zulip-flutter#1617.
To fix that immediately, have the bouncer drop duplicate tokens before sending the notifications to APNs.
Work is also in progress on fixing this in a better-structured way, by having the database correctly treat tokens as the same when they differ …
=> notifications: Dedupe APNs tokens case-insensitively.

help/edit-a-message.md, help/include/sidebar_index.md, help/message-actions.md, help/view-the-markdown-source-of-a-message.md
Current: https://zulip.com/help/view-the-markdown-source-of-a-message
<details>
<summary>
Updated
</summary>
</details>
Current: https://zulip.com/help/message-actions
<details>
<summary>
Updated
</summary>
</details>
=> help: Update articles on message actions and viewing content.

help/status-and-availability.md
Added in https://github.com/zulip/zulip-flutter/pull/1631.
[CURRENT DOC](https://zulip.com/help/status-and-availability#toggle-invisible-mode)
---
<details>
</details>
=> help: Add mobile instructions for toggling invisible mode.

help/emoji-reactions.md
Flutter issue: https://github.com/zulip/zulip-flutter/issues/740.
<details>
</details>
=> help: Add mobile instructions for viewing who reacted to message.

help/status-and-availability.md, help/view-someones-profile.md
Updates the documentation for the user profile in mobile as well.
[CURRENT DOC](https://zulip.com/help/status-and-availability#view-a-status)
[CURRENT DOC](https://zulip.com/help/view-someones-profile)
---
<details>
</details>
=> help: Add mobile instructions for viewing status emoji and message.

help/channel-feed.md, help/include/manage-configured-topics-mobile.md, help/list-of-topics.md
**Updates**:
- Updates mobile tabs for **topic list** icon.
- Adds mobile tab for **Go to channel feed for a subscribed channel** instructions.
[CURRENT DOC](https://zulip.com/help/channel-feed)
[CURRENT DOC](https://zulip.com/help/list-of-topics)
[CURRENT DOC](https://zulip.com/help/follow-a-topic#manage-configured-topics)
---
<details>
</details>
=> help: Update mobile tabs for channel feed and topic list icons.

help/change-the-channel-description.md, help/pin-information.md, help/rename-a-channel.md
These instructions were updated in #35156, but we want to use the tooltip text in the help center when describing icons. So, here we update the instructions for the icon to edit a channel's name and description for that.
[CURRENT DOC](https://zulip.com/help/pin-information)
[CURRENT DOC](https://zulip.com/help/change-the-channel-description)
[CURRENT DOC](https://zulip.com/help/rename-a-channel)
---
<details> …
=> help: Fix description of edit channel name and description icon.

help-beta/src/styles/main.css
Fixes #35126.
Before:
After:
<details>
</details>
=> help-beta: Nested lists should not have 1rem margin.

analytics/management/commands/update_analytics_counts.py, puppet/zulip/templates/cron.template.erb, scripts/restart-server, zerver/lib/management.py, zerver/management/commands/fetch_tor_exit_nodes.py, zerver/management/commands/promote_new_full_members.py, zerver/management/commands/send_zulip_update_announcements.py
=> Cron deploy lock

help-beta/src/styles/main.css
Fixes https://github.com/zulip/zulip/issues/35123.
Before:
After first commit (without border removal):
After both commits (with border removal):
<details>
</details>
=> help center stage 3: Adjust section heading sizing

web/src/filter.ts, web/tests/filter.test.cjs
Fixes: [#issues > search suggestion for channels operator for spectators. @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/search.20suggestion.20for.20channels.20operator.20for.20spectators.2E/near/2203484)
| Before| After|
| ![image](https://github.com/user-attachments/assets/6a64d6a7-9fd1-470a-99b5-a650d4d2aef4)| ![image](https://github.com/user-attachments/assets/5b4af4ef-0632-4cad-912f-0ee2f656a6a6)| 
<details> …
=> filter: Update title for spectators and guests when using `channels:public` filter.

templates/corporate/for/communities.md
=> portico: Add quotes to /for/communities.

zerver/lib/streams.py, zerver/views/streams.py
Fixes: Points 1, 3 from https://github.com/zulip/zulip/pull/33405#issuecomment-3064452310
I plan on fixing the 2nd point in the branch for #33405, once these commits are merged.
<details>
</details>
=> streams: Prep commits for channel creation.

web/styles/input_pill.css
Follow-up for #35277.
| <img width="890" height="159" alt="image" src="https://github.com/user-attachments/assets/9c30dac6-eb03-4079-ae14-0830a429b501" /> | <img width="893" height="223" alt="image" src="https://github.com/user-attachments/assets/dab7f6b6-b0de-4e62-b2cf-32659574de53" /> |
| <img width="881" height="199" alt="image" src="https://github.com/user-attachments/assets/1a4ed4a3-53d5-41de-8d51-cb3b1cde10ae" /> | <img width="870" height="192" alt="image" src="https://github.com/user-attachments/assets/cce163b6-0dcb-4b29-8795-da6ebf768732" /> |
| <img width="879" height="174" alt="image" src="https://github.com/user-attachments/assets/25d35e71-78cf-49ce-8848-29bb5f931830" /> | <img width="886" height="232" alt="image" …
=> pill_container: Fix background color in dark theme.

help-beta/astro.config.mjs, help-beta/package.json, help-beta/src/route_data.ts, help-beta/tsconfig.json, pnpm-lock.yaml, version.py
Fixes https://github.com/zulip/zulip/issues/35115.
<details>
</details>
=> help center stage 3: Add SEO support to the new help center. 

web/src/peer_data.ts, web/src/stream_data.ts, web/src/stream_types.ts, web/tests/compose_validate.test.cjs, web/tests/peer_data.test.cjs, web/tests/pill_typeahead.test.cjs, web/tests/stream_pill.test.cjs, zerver/lib/home.py, zerver/lib/subscription_info.py, zproject/default_settings.py
Work towards https://github.com/zulip/zulip/issues/34244, followup to #34838
=> peer_data: Use sub.subscriber_count for get_subscriber_count.

analytics/tests/test_counts.py, zerver/lib/push_notifications.py, zerver/lib/test_classes.py, zerver/openapi/python_examples.py, zerver/openapi/zulip.yaml, zerver/tests/test_handle_push_notification.py, zerver/tests/test_push_notifications.py, zerver/tests/test_push_registration.py, zilencer/views.py
I decided it's worth having CI run on these.
=> Preparatory commits extracted from #35289

web/src/lightbox.ts
0229f73 introduced a bug wherein while caching the media assets keyed using the message id, previews of media from composebox which also used same codepath attempted to find the message id from the asset. This resulted in error.
This is fixed by making sure that compose previewable assets are never cached nor attempted to fetch from cache since they don't have a message id yet.
Fixes: [](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Composebox.20image.20previews.20don't.20work/with/2222110)[#issues > 🎯 Composebox image previews don't work](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Composebox.20image.20previews.20don't.20work/with/2222110)
<details>
(variable …
=> lightbox: Fix media asset preview in composebox.

scripts/lib/run_hooks.py
=> run_hooks: Make post-deploy hooks be best-effort.

templates/corporate/comparison_table_integrated.html
=> portico: Add new features to comparison table.

web/src/people.ts, web/src/settings.ts, web/src/user_profile.ts, web/templates/settings/admin_human_form.hbs, web/templates/settings/edit_bot_form.hbs, web/templates/settings/profile_settings.hbs
- First commit fixes the `maxlength` attribute of name input in "Profile" panel.
- Second commit adds `maxlength` attribute to name inputs in "Manage user" and "Manage bot" modals.
<details>
</details>
=> Add and fix `maxlength` attribute values for name inputs.

web/src/channel_folders.ts, web/src/hotkey.js, web/src/inbox_ui.ts, web/src/inbox_util.ts, web/src/server_events_dispatch.js, web/src/stream_popover.ts, web/src/tippyjs.ts, web/styles/app_variables.css, web/styles/inbox.css, web/templates/inbox_view/inbox_folder_row.hbs, web/templates/inbox_view/inbox_folder_with_channels.hbs, web/templates/inbox_view/inbox_list.hbs, web/templates/inbox_view/inbox_row.hbs, web/templates/inbox_view/inbox_stream_header_row.hbs, web/templates/popovers/left_sidebar/left_sidebar_stream_actions_popover.hbs, web/tests/channel_folders.test.cjs
Inbox doesn't update right when channel folders are renamed or updated for channels. I can open a separate PR to do that.
=> Inbox redesign to use channel folders.

zerver/lib/zulip_update_announcements.py
I haven't run the update script, in case I need to do it after updating the message.
=> updates: Add update message (level=19).

web/src/stream_edit_subscribers.ts, web/src/tippyjs.ts, web/src/user_group_edit_members.ts, web/src/user_profile.ts, web/styles/popovers.css, web/styles/subscriptions.css, web/templates/stream_settings/add_subscribers_form.hbs, web/templates/stream_settings/stream_members.hbs, web/templates/stream_settings/stream_subscription_request_result.hbs, web/templates/user_group_settings/add_members_form.hbs, web/templates/user_group_settings/user_group_members.hbs, web/templates/user_group_settings/user_group_membership_request_result.hbs
Fixes: #34347
[CZO Thread](https://chat.zulip.org/#narrow/channel/101-design/topic/New.20channel.2Fgroup.20UX.20changes/with/2149812)
Related thread: [#frontend > #34347 rework subscribe users confirmations](https://chat.zulip.org/#narrow/channel/6-frontend/topic/.2334347.20rework.20subscribe.20users.20confirmations/with/2193352)
| Unsubscribing from a channel |
|---|
|![image](https://github.com/user-attachments/assets/e6c0ec90-b1de-4335-92fc-7f3f53f258a4)|
| Subscribing to a channel, users lte five |
|-----|
|![image](https://github.com/user-attachments/assets/c3ce662c-6d83-451d-80bd-dab86ed86af1)|
| Subscribing to a channel, users more than five |
|----|
|![image](https://github.com/user-attachments/assets/bb34c2f2-0d0d-48db-997c-3c86ce4cb202)|
| All users already subscribed to …
=> Rework channel/group subscribe  confirmation

help/include/left-sidebar-conversations.md, help/reading-strategies.md, help/star-a-message.md
Sweep for button labels that are still in the help center in all-caps.
After changes:
```
% git grep '\*\*[A-Z][A-Z]' help/                      
help/add-a-custom-linkifier.md:   **URL template**.
help/animated-gifs-from-giphy.md:1. Under **Compose settings**, select a rating for **GIPHY integration**.
help/bots-overview.md:Each bot has a **name**, **profile picture**, **email**, **bot type** and **API key**.
help/bots-overview.md:* The **API key** is how the bot identifies itself to Zulip. Anyone with the
help/code-blocks.md:   **URL template**.
help/connect-through-a-proxy.md:1. Either enter a URL for **PAC script**, or fill out **Proxy rules** and
help/connect-through-a-proxy.md:URL for the **PAC script**.
help/desktop-notifications.md:1. Toggle the checkboxes for **Channels** and …
```
=> help: Update button labels that are not lower case in documentation.

help/general-chat-topic.md, help/include/send-dm.md, help/include/start-topic-via-left-sidebar.md, help/introduction-to-channels.md, help/left-sidebar.md, help/logging-in.md, help/resolve-a-topic.md, help/unsubscribe-from-a-channel.md, help/user-groups.md
Updates **plus** and **checkmark** icon descriptions in help center for tooltip text.
**Notes**:
- `git grep '*\*\plus' help/ ` returns no results after these changes.
- `git grep '*\*\check' help/ ` only return results for polls and to-do lists as those buttons don't have tooltip text.
---
[CURRENT DOC](https://zulip.com/help/general-chat-topic#sending-a-message-to-the-general-chat-topic)
[CURRENT DOC](https://zulip.com/help/direct-messages#send-a-dm)
[CURRENT DOC](https://zulip.com/help/introduction-to-topics#how-to-start-a-new-topic)
[CURRENT DOC](https://zulip.com/help/introduction-to-channels#browse-and-subscribe-to-channels)
[CURRENT DOC](https://zulip.com/help/left-sidebar#start-a-new-direct-message-conversation)
[CURRENT …
=> help: Use tooltip text for plus and checkmark icon descriptions.

zerver/data_import/slack_message_conversion.py
It's rare, but sometimes we see floats in this field.
=> slack: Handle float "ts" in attachment info.

help/manage-user-groups.md
[#documentation > manage user groups documentation](https://chat.zulip.org/#narrow/channel/19-documentation/topic/manage.20user.20groups.20documentation)
Updates the instructions for **Configure who can create groups** and **Configure who can administer all user groups** for the new groupings in the organizations permissions tab of the settings overlay.
[current documentation](https://chat.zulip.org/help/manage-user-groups#configure-who-can-create-user-groups)
---
<details> …
=> help: Update section name for org-level user group permission settings.

analytics/lib/counts.py, analytics/tests/test_counts.py
To maintain API compatibility during and after the migration to direct message groups for 1:1 and self messages, update the analytics count query to treat DM groups of size 2 or less as private messages.
<details>
</details>
=> analytics: Support DM groups in count message type query.

eslint.config.js, help-beta/src/components/ZulipNote.astro, help-beta/src/styles/main.css, tools/convert-help-center-docs-to-mdx
Commit 1:
[#documentation > new help center: regressions @ 💬](https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20regressions/near/2224664)
Before:
After:
Commit 2:
[#documentation > new help center: regressions @ 💬](https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20regressions/near/2224674)
Before:
After:
Commit 3:
[#documentation > new help center: regressions @ 💬](https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20regressions/near/2225676)
Before:
After:
<details> …
=> Help beta regression fix

web/src/condense.ts
After narrowing to a long unread message, the message gets marked as read and can be collapsed when rerender happens since the cutoff of read message is different.
Fixed by tracking which messages were unread during initial render and using the unread cutoff for them until user narrows again.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Double.20rerender.20causing.20messages.20to.20be.20collapsed/with/2226432
=> condense: Fix long unread message collapses after initial render.

docs/production/scim.md, zerver/lib/scim.py, zerver/lib/scim_filter.py, zerver/lib/user_groups.py, zerver/tests/test_scim.py, zerver/views/streams.py
=> SCIM group sync preparatory commits

zerver/webhooks/grafana/view.py
=> grafana: Be more forgiving of missing alert keys.

zerver/lib/events.py
Fixing bug reported here:
https://chat.zulip.org/#narrow/channel/343-kandra-errors/topic/KeyError.3A.20'subscribers'/near/2226586
=> events: Consider partial_subscribers key in apply_event.

web/styles/inputs.css, web/styles/left_sidebar.css
This ensures single-line filter inputs in the left sidebar.
While we could allow the `is: resolved` pill to shrink, I've opted in this iteration to keep it always open, as I believe that would be less confusing/distracting to users as they type text to filter further.
| --- | --- |
| <img width="1800" height="1600" alt="input-filter-lsb-before" src="https://github.com/user-attachments/assets/18fc36dc-fb01-4232-b862-929df5789ef6" /> | <img width="1800" height="1600" alt="input-filter-lsb-after" src="https://github.com/user-attachments/assets/fadd129b-c707-4219-a17f-e04ad2cd32c1" /> |
<details> …
=> left_sidebar: Hold topic filter inputs to a single line.

zerver/lib/push_notifications.py, zerver/lib/test_classes.py, zerver/migrations/0740_pushdevicetoken_apns_case_insensitive.py, zerver/models/push_notifications.py, zerver/tests/test_push_notifications.py, zilencer/migrations/0067_remotepushdevicetoken_apns_case_insensitive.py, zilencer/models.py, zilencer/views.py
=> Make token case-insensitive with APNs

help/create-your-organization-profile.md, help/include/organization-type-intro.md, help/organization-type.md
Fixes
https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20Includes.20inside.20list.20item The macro works fine for the current help center. But for the new help center, the macro has a paragraph tag already, when it is part of a list item, the margin inserted by starlight causes spacing issue. We can override the margin for this specific case when we have the ability to modify the MDX directly. Issue for that: #35407. Until then, we remove this macro since it's only used it two places to have proper spacing.
Affected pages of the current help center look the same as before:
The macro was being used here in the new help center, this has remain unchanged:
This list was loose, it is now tight after removing the macro: …
=> help: Remove organization-type-intro macro.

zerver/actions/create_user.py, zerver/lib/message_report.py, zerver/lib/zulip_update_announcements.py, zerver/tests/test_message_report.py, zerver/tests/test_new_users.py, zerver/tests/test_subs.py, zerver/tests/test_zulip_update_announcements.py, zerver/views/streams.py
This PR updates code to send messages to "general chat" topic if streams used for
announcements for "New user signups", "New created streams", "Moderation requests"
and "Zulip updates" have topics policy set to allow only "general chat" messages.
<details>
</details>
=> streams: Handle empty topic only streams being used for announcements.

web/src/inbox_ui.ts
Used the same method used to fix it in recent view.
based on https://github.com/zulip/zulip/pull/35152#issuecomment-3091231697
=> inbox_ui: Fix scroll jumb when coming back when scrolled down.

zerver/lib/narrow.py, zerver/migrations/0742_usermessage_zerver_usermessage_is_private_unread_message_id.py, zerver/models/messages.py, zerver/tests/test_message_fetch.py, zerver/views/message_fetch.py
=> Optimize DM fetches

zerver/lib/push_notifications.py, zerver/tests/test_e2ee_push_notifications.py, zilencer/lib/push_notifications.py, zilencer/views.py
PR to address:
Fixes part of #35368 
<details>
</details>
=> push_notification: Add support to configure priority and push_type. 

zerver/lib/email_notifications.py, zerver/lib/url_encoding.py, zerver/tests/test_message_notification_emails.py
To maintain API compatibility during and after the migration to use `DirectMessageGroup` for 1:1 messages, we render the email notification for missed 1:1 DMs using `DirectMessageGroup` with the same format as messages sent to a `Personal` recipient.
<details>
</details>
=> notification: Use existing email format for missed 1:1 DM via DM group.

zerver/lib/event_schema.py, zerver/lib/event_types.py
- Cc @Vector73 (#33739)
- [Discussion](https://chat.zulip.org/#narrow/channel/3-backend/topic/realm_billing.20event/near/2229269)
=> event_types: Remove nonexistent realm_billing event

tools/check-schemas, zerver/lib/event_schema.py, zerver/lib/event_types.py, zerver/tests/test_events.py
- Cc @opmkumar (#33024)
- [Discussion](https://chat.zulip.org/#narrow/channel/378-api-design/topic/typing.20notifications.20for.20editing.20messages/near/2229274.2E01)
=> event_types: Combine typing_edit_message variants

zerver/lib/event_types.py
=> event_types: Add missing default EventPushDevice.error_code = None

zerver/lib/event_schema.py
- Cc @saubhagya-patel (#32840, #34226)
=> event_schema: Fix Enum validation in check_realm_update

pyproject.toml, uv.lock, version.py, zerver/lib/upload/__init__.py, zerver/lib/upload/base.py, zerver/lib/upload/local.py, zerver/lib/upload/s3.py, zerver/tests/test_tusd.py, zerver/tests/test_upload.py, zerver/tests/test_upload_local.py, zerver/tests/test_upload_s3.py, zerver/views/upload.py
=> uploads: Attempt to guess character set for text/plain.

help/rename-a-topic.md, zerver/lib/markdown/tabbed_sections.py
**Notes**:
- Updates the **Rename a topic** article to use tabs for the different instructions.
- Adds a mobile tab with a link to the issue for adding a "Move topic" button to the topic actions sheet in the mobile app (https://github.com/zulip/zulip-flutter/issues/1439).
- Adds a new tabbed section for **Via message recipient bar**.
---
[current doc](https://zulip.com/help/rename-a-topic)
---
<details>
</details>
=> help: Add mobile tab for "Rename a topic" instructions.

zerver/lib/push_notifications.py, zerver/tests/test_e2ee_push_notifications.py, zilencer/lib/push_notifications.py, zilencer/views.py
CZO Discussion: [#api design > E2EE push notifications @ 💬](https://chat.zulip.org/#narrow/channel/378-api-design/topic/E2EE.20push.20notifications/near/2229005)
Explanation in commit message.
Fixes part of #35368.
<details>
</details>
=> push_notification: Send a list of push request data replacing a map.

web/src/settings_components.ts, web/src/stream_create.ts, web/src/stream_edit.ts, web/src/stream_settings_ui.ts, web/templates/stream_settings/stream_permissions.hbs, web/templates/stream_settings/stream_settings.hbs
- First commit is to channel settings UI not opening [reported here](https://chat.zulip.org/#narrow/channel/9-issues/topic/channel.20settings.20don't.20open/with/2216020)
- Second commit is to enable channel folders UI in prod.
<details>
</details>
=> Fix stream settings UI not opening

web/src/message_edit_history.ts
There is a possibility that the overlay was closed while the request was being processed.
Fixes #35237.
<details>
</details>
=> message_edit_history: Return early if overlay is closed.

zerver/management/commands/makemessages.py
Commit d8a36d07022a590710afd84bfdff5a2d530db71e (#18075) should have removed this.
=> makemessages: Remove vestigial custom JavaScript extraction

web/src/stream_edit.ts
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20put.20focus.20in.20channel.20folder.20name.20field/near/2231435
<details>
</details>
=> streams-ui: Focus on name input after opening folder creation modal.

help-beta/astro.config.mjs
=> help-beta: Correct casing for sidebar sections.

help/deactivate-your-organization.md, tools/convert-help-center-docs-to-mdx
Fixes
https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20support.20email.20variable.20conversion
<details>
</details>
=> help-beta: Add support for converting {{ support_email }} variable. 

help/include/saml-login-button.md, help/saml-authentication.md
Our current conversion script does not work well with inserting flattened steps in indented lists. Adding support for indented lists would be non-trivial. Flattened steps are inserted either in case of files or relative/setting links. I used this (  +)\{ regex to test for instances where we might need to insert Flattened steps in an indented block. Turns out saml-login-button.md is the only includes that faces the issue only in saml-authentication.md.
There was no strong reason for these sub-lists to be ordered lists and we decided to turn it into unordered list. Discussion at https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20numbering.20regression/near/2232242
Before:
After:
<details> …
=> help: Use unordered lists for sub-lists in saml-authentication.md.

help/change-the-color-of-a-channel.md, help/include/topics-intro.md, help/moving-to-zulip.md
=> help: Tweaks noticed while reviewing help-beta.

help-beta/src/styles/main.css
We should ideally be having this styling on class, but there is no default class for li elements inside an ol. Maybe the best thing here is to attach classes at different places if possible once have some spare time after the important post cutover issues are done.
Before:
After:
<details>
</details>
=> help-beta: Add more spacing b/w ordered list steps.

web/styles/rendered_markdown.css
This fixes a regression on message-opening images that do not include text.
| --- | --- |
| <img width="1520" height="1800" alt="textless-image-before" src="https://github.com/user-attachments/assets/36020c05-750a-409e-a30c-647c09ec1428" /> | <img width="1520" height="1800" alt="textless-image-after" src="https://github.com/user-attachments/assets/4ae4e834-0bef-496d-a95f-ea07408ecf8d" /> |
<details> …
=> rendered_markdown: Correct alignment on textless images.

web/styles/left_sidebar.css
[#issues > 🎯 overly-tempting Filter channels input @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20overly-tempting.20Filter.20channels.20input/near/2233444)
| --- | --- |
| <img width="660" height="422" alt="expanded-dms-before" src="https://github.com/user-attachments/assets/ac1d3bc9-4850-40d3-87a3-852f6d1cd77c" /> | <img width="660" height="422" alt="expanded-dms-after" src="https://github.com/user-attachments/assets/72d8e80c-6b93-4a03-9769-5934198f0303" /> |
| <img width="660" height="422" alt="collapsed-but-highlighted-dms-before" src="https://github.com/user-attachments/assets/004ff775-648d-40e7-b0c2-0a09a9769045" /> | <img width="660" height="422" alt="collapsed-but-highlighted-dms-after" …
=> left_sidebar: Open up space between DMs, filter input.

web/src/drafts_overlay_ui.ts, web/styles/drafts.css, web/templates/draft_table_body.hbs
This PR fixes an assertion error on pressing "Enter" in drafts UI when there are no drafts.
Also added a commit to fix the deletion banner layout.
| ------ | ------ |
| <img width="1309" height="356" alt="image" src="https://github.com/user-attachments/assets/16f72a92-ea79-4043-bbfc-1f2ba0543f5e" /> | ![Peek 2025-07-29 07-07](https://github.com/user-attachments/assets/8e70a397-7390-4122-8fa2-1d0df25daadf) |
<details>
</details>
=> drafts-ui: Fix pressing "Enter" when there are no drafts.

help/reading-conversations.md
In #35473, I missed the use of `help/include/reading-conversations.md` in the main [**Reading conversations**](https://zulip.com/help/reading-conversations) article, which caused the intro section to be doubled; see before screenshot below. That documentation bug is on `main`, but not yet in production.
After these changes, `git grep` shows that `help/includ/conversation-definition.md` is not used in any of the articles that also uses `help/include/reading-conversations.md`:
```console
git grep 'reading-conversations.md'              
help/getting-started-with-zulip.md:{!reading-conversations.md!}
help/reading-conversations.md:{!reading-conversations.md!}
help/reading-strategies.md:{!reading-conversations.md!}
git grep 'conversation-definition.md' …
```
=> help: Fix intro section of "Reading conversations" article.

web/templates/settings/organization_user_settings_defaults.hbs
Fixes #35546.
<details>
</details>
=> default-user-settings: Remove the configuration banner for non-admin users.

help/bots-overview.md
[#documentation > new help center: bullet list spacing @ 💬](https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20bullet.20list.20spacing/near/2233125)
Revises the extra details about outgoing webhook bots to be one paragraph instead of two.
[CURRENT DOC](https://zulip.com/help/bots-overview#bot-type)
| Current | New |
| --- | --- |
| <img width="757" height="519" alt="Screenshot 2025-07-30 at 13 01 39" src="https://github.com/user-attachments/assets/5cab78bd-622c-4104-b155-a4d9aa47a470" /> | <img width="778" height="557" alt="Screenshot 2025-07-30 at 13 03 53" src="https://github.com/user-attachments/assets/7c2e07ac-19f7-4ce4-a5ff-319a3e783f77" />
---
<details> …
=> help: Make extra content about outgoing bots one paragraph.

help/include/modify-link-text.md, help/share-and-upload-files.md
=> help: Move tip about changing uploaded file name into instructions.

web/src/compose_actions.ts
This fixes faulty logic with `===` and `||` in JavaScript, which was basically making low-attention rows non-existent, especially in topic replies.
This is somewhat related to [#issues > 🎯 compose box destination not faded for new users](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20compose.20box.20destination.20not.20faded.20for.20new.20users).
<details>
</details>
=> compose: Correct faulty logic for determining attention state.

help-beta/package.json, tools/convert-help-center-docs-to-mdx
=> help-beta: Run format step in the conversion tool.

help-beta/package.json, help-beta/src/.remarkrc.js, pnpm-lock.yaml, tools/convert-help-center-docs-to-mdx, version.py
Built on top of https://github.com/zulip/zulip/pull/35588, rebase this after that is merged.
<details>
</details>
=> help-beta: All lists should start with one after conversion. 

help/scim.md
We are porting the current help center docs to the new help center. Porting the display_host variable to the new help center is a tricky task and it is not worth to put in the effort for that just for 3 uses of that variable.
Current help center:
New help center:
<details>
</details>
=> help: Use Zulip Cloud and self-hosting URLs instead of display_host.

web/src/left_sidebar_navigation_area.ts
This fixes https://github.com/zulip/zulip/pull/35075#discussion_r2232052221. 
Using an inline `??` seems to be a simpler choice than the options mentioned in the comment.
Fixes part of #35494.
Fixes: 
<details>
</details>
=> left_sidebar_navigation_area: Reduce the use of `??`.

web/src/inbox_ui.ts
It is possible for us to scroll user back to top of view if they scroll before the render is complete and we haven't called `revive_current_focus` yet.
This fixes it by wrapping the render and revive logic in a single animation frame so that any scroll requests are delayed until we have completed both of them.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Inbox.20view.20scroll.20position.20issues/with/2236625
=> inbox_ui: Fix scroll jump after initial render.

zerver/actions/message_edit.py, zerver/actions/message_send.py, zerver/tests/test_message_move_topic.py
When moving messages, the notification messages should be automatically marked as read for the user who moved the messages.
CZO discussion: [#issues > "mark as read" when moving topic](https://chat.zulip.org/#narrow/channel/9-issues/topic/.22mark.20as.20read.22.20when.20moving.20topic)
Fixes: 
<details>
</details>
=> message_move: Mark notification messages as read for acting user.

zerver/lib/upload/__init__.py, zerver/tests/test_upload.py
UTF-8 is far and wide the dominant encoding, so we assume that encoding if we have more than 66% confidence -- this allows it to be guessed even for short files.  ISO-8859-1 caps at 73% confidence, so we assume that if it's the best option and it hits that max. Otherwise, we still require 90% confidence.
Fixes: 
<details>
</details>
=> upload: Adjust minimum encoding confidence thresholds.

help-beta/src/styles/main.css, tools/convert-help-center-docs-to-mdx
=> help-beta: Make loose ordered lists tight in the conversion tool.

zerver/lib/transfer.py, zerver/tests/test_transfer.py, zerver/tests/test_upload_s3.py
Fixes: #35029.
<details>
</details>
=> Fix transfer-to-s3 to handle thumbnails

help/code-blocks.md
[#documentation > new help center: regressions @ 💬](https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20regressions/near/2238275)
Corrects the Markdown syntax used to show how to set no default code block language.
| Current | New |
| --- | --- |
| <img width="1107" height="496" alt="Screenshot From 2025-08-07 17-25-01" src="https://github.com/user-attachments/assets/e2d074f0-b696-4c7a-b26c-cee21702df59" /> | <img width="979" height="490" alt="Screenshot From 2025-08-07 17-26-28" src="https://github.com/user-attachments/assets/ed6c4c5e-5224-42c5-ac05-e3dccf845422" />
---
<details> …
=> help: Fix Markdown syntax for setting no default code block language.

web/src/channel_folders.ts, web/src/left_sidebar_navigation_area.ts, web/src/stream_list.ts, web/src/stream_list_sort.ts, web/tests/stream_list_sort.test.cjs
This addresses everything left in #35494 except tests.
=> Channel folders: Code cleanup tasks

help/schedule-a-reminder.md
https://zulip.com/help/schedule-a-reminder
=> help: Document message reminder note feature.

docs/contributing/reporting-bugs.md, docs/contributing/suggesting-features.md, docs/development/using.md, docs/overview/architecture-overview.md, docs/overview/release-lifecycle.md, help/add-a-custom-linkifier.md, help/mobile-app-install-guide.md, help/support-zulip-project.md, templates/corporate/development-community.md
Updates links in the help center and developer documentation to go to the `zulip-flutter` repo, instead of the `zulip-mobile` repo.
**Notes**:
- The final commit removes the zulip-mobile repo linkifier from the development community page ([link](https://zulip.com/development-community/#linking-to-github-issues-and-pull-requests)). It seemed fine to just remove this at this point in time even though the linkifier will remain on CZO.
- There's still one link in the help center to the `zulip-mobile` repo, which is for the Andriod legacy app APK download instructions.
- There are still a few places to look at before #35643 is marked as resolved:
- The main `CONTRIBUTING.md` file has a link to @gnprice's `git-log` secret documented in the `zulip-mobile` repo …
=> documentation: Update links to go to zulip-flutter repo.

web/styles/inbox.css, web/templates/inbox_view/inbox_folder_row.hbs
| --- | --- |
| <img width="918" height="836" alt="Screenshot from 2025-08-10 15-14-31" src="https://github.com/user-attachments/assets/e5bf20f4-0c63-4f64-bc01-501da7b9d6fb" /> | <img width="918" height="836" alt="Screenshot from 2025-08-10 15-14-17" src="https://github.com/user-attachments/assets/fa3bc73f-a904-4318-aff8-cfc8952eeacd" /> |
=> inbox: Match style of inbox view unread count folder to left sidebar.

docs/production/upgrade.md
=> docs: Explain how and when to terminate `manage.py process_queue --all`.

web/src/compose_actions.ts, web/src/scheduled_messages_overlay_ui.ts, web/src/stream_data.ts, web/tests/compose_actions.test.cjs
- First commit is to fix seeing scheduled msgs UI when some messages in inaccessible streams.
- Second commit is to fix restoring draft in inaccessible stream.
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/guest.20restoring.20drafts.20of.20unsubscribed.20streams/with/2240565
<details>
</details>
=> Fix drafts and scheduled messages in streams that are no longer accessible.

help/configure-a-custom-welcome-message.md, help/include/sidebar_index.md, help/invite-new-users.md, help/moderating-open-organizations.md, starlight_help/astro.config.mjs
Documents the changes in #32862. I'm assuming we'll fix #35664.
<details>
<summary>
Screenshots
</summary>
</details>
=> help: Document configuring a custom welcome message.

web/src/stream_list.ts, web/src/stream_list_sort.ts, web/src/unread.ts, web/styles/left_sidebar.css, web/templates/stream_list_section_container.hbs, web/tests/stream_list.test.cjs
=> stream_list: Show mention indicator in section headings.

help/scim.md, templates/corporate/comparison_table_integrated.html, templates/corporate/pricing_model.html
=> help and portico: SCIM group sync

scripts/restart-server
=> start-server: Warn on deploy mismatch if it is a noop.

help/read-receipts.md
Updates **Read receipts** help center doc for mobile instructions on viewing who has read a message.
Relevant Zulip Flutter issue and PR:
- issue: https://github.com/zulip/zulip-flutter/issues/667
- PR: https://github.com/zulip/zulip-flutter/pull/1706
---
[CURRENT DOC](https://zulip.com/help/read-receipts)
---
<details>
</details>
=> help: Update mobile tab for "View who has read a message".

help/mention-a-user-or-group.md
Adds mobile instructions for inserting a user or group mention when composing a message.
Relevant Zulip Flutter issue and PR:
- issue: https://github.com/zulip/zulip-flutter/issues/233
- PR: https://github.com/zulip/zulip-flutter/pull/1775
**Notes**:
- Potential follow-up is updating the doc for [open the compose box](https://zulip.com/help/open-the-compose-box) to have a section for the mobile app that we can link to.
---
[CURRENT DOC](https://zulip.com/help/mention-a-user-or-group#from-the-compose-box)
--
<details> …
=> help: Add mobile instructions for user mention in compose box.

help/share-and-upload-files.md
Adds a section on sharing files from other apps on Zulip mobile. The Android tab has instructions for the feature and the tab for iOS links to the zulip-flutter issue for implementing this feature on the mobile app for that platform.
Relevant Zulip Flutter issue and PR:
- issue: https://github.com/zulip/zulip-flutter/issues/53
- PR: https://github.com/zulip/zulip-flutter/pull/1774
**Notes**:
- The instruction for picking a recipient (channel/topic or direct message) could probably use a little revision. Currently, it's a bit information dense.
---
[CURRENT DOC](https://zulip.com/help/share-and-upload-files) - not on the mobile tab for uploading files
*Checked new help center due to Zulip logo icon*
---
<details> …
=> help: Add mobile instructions for sharing files on Android.

web/src/click_handlers.ts, web/src/pm_list.ts, web/src/stream_list.ts, web/src/topic_list.ts, web/styles/left_sidebar.css, web/styles/message_header.css, web/styles/right_sidebar.css, web/templates/pm_list_item.hbs, web/templates/presence_row.hbs, web/templates/recipient_row.hbs, web/templates/stream_sidebar_row.hbs, web/templates/topic_list_item.hbs
Fixes: #34959.
| Topics|
|----|
|![select-topics-fix](https://github.com/user-attachments/assets/9275e286-b44d-470a-a1a6-51469bcf33f2)|
|DM box|
|------|
|![dmbox](https://github.com/user-attachments/assets/c88282d7-9110-4902-8cbe-c53abedda13d)|
|Buddy list|
|-----|
|![buddy-list](https://github.com/user-attachments/assets/20d2031c-5828-4917-a9af-add552017ef6)|
|Message header|
|--------|
|![message-header](https://github.com/user-attachments/assets/b1d0ec1b-eaca-436e-affd-8ec94dfc9392)|
=> links: Improve text selection.

web/src/left_sidebar_tooltips.ts
This PR shows the folder name in a tooltip when a folder name is too long to be shown completely in the left sidebar. 
This works exactly like tooltips on long channel names.
Fixes: zulip#35582.
**After:**
[Screencast from 2025-08-13 03-14-47.webm](https://github.com/user-attachments/assets/98b48917-75f0-48da-abf0-d49e409fd731)
<details>
</details>
=> Show tooltip on long folder names in left sidebar.

templates/zerver/development/dev_tools.html, tools/run-dev
When running the dev server, astro/starlight makes a lot of requests on the base URL, which are not scoped to /starlight_help. We need to host the dev server on it's own port for it to work well. This commit fixes that.
Fixes: [#documentation > new help center: run-dev options @ 💬](https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20run-dev.20options/near/2238128)
<details> …
=> starlight_help: Forward to help_center_port in case of dev server.

web/src/hotkey.js
This PR fixes the operand argument type passed in for showing message list.
Fixes: [#issues > navigating between topics in same channel throws error @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/navigating.20between.20topics.20in.20same.20channel.20throws.20error/near/2246182)
<details>
</details>
=> hotkey: Fix argument type for narrow filter.

.github/workflows/production-suite.yml
=> ci: Test upgrades from 11.0.

puppet/zulip/manifests/profile/app_frontend.pp, scripts/reload-clients
When run from cron, reload-server (and thus reload-clients) picks up the `HTTP_proxy` environment variable, which redirects HTTP requests through Smokescreen -- which prevents localhost requests.  This results in clients never getting sent reload events.
Explicitly unset proxies when talking to localhost in reload-clients.
-----
puppet: Skip client reloads during weekly restarts.
Weekly restarts do not deploy any new client code, so there is no reason to push clients to reload.
Fixes: 
<details> …
=> reload-clients: Ensure that Smokescreen does not interfere with reloads.

docs/production/upgrade.md
=> docs: Add upgrade instructions for Debian 12 -> 13.

zerver/lib/push_notifications.py
PR to address:
> Consider parsing bouncer responses using Pydantic: https://github.com/zulip/zulip/pull/35139#discussion_r2224012914
Fixes part of #35368.
<details>
</details>
=> push_notifications: Parse `push/e2ee/notify` response using Pydantic.

help/change-organization-url.md
=> help: Document the redirect that subdomain changes leave.

eslint.config.js, starlight_help/src/.remarkrc.js, starlight_help/src/components/KeyboardTip.astro, starlight_help/src/components/NavigationSteps.astro, starlight_help/src/components/ZulipTip.astro
=> starlight_help: Add comments + some code cleanup

tools/check-schemas, web/src/activity_ui.ts, web/src/presence.ts, web/src/server_events_dispatch.js, web/tests/activity.test.cjs, web/tests/buddy_data.test.cjs, web/tests/dispatch.test.cjs, web/tests/lib/events.cjs, web/tests/presence.test.cjs, zerver/lib/home.py
Adds support for processing modern presence events in the web client.
CZO discussion: [#api design > presence rewrite @ 💬](https://chat.zulip.org/#narrow/channel/378-api-design/topic/presence.20rewrite/near/2244435)
<details>
</details>
=> events: Add support for processing modern presence event in web client.

web/src/lightbox.ts
We use the same "v" key for opening and closing the lightbox overlay.
We already have code to open and close the lightbox overlay in `hotkey.ts`.
Having another keydown handler for closing the overlay resulted in a bug
where the overlay was just not being opened because the second handler
was immediately called to close the overlay was immediately called after the first.
Fixes #35868.
<details>
</details>
=> lightbox: Use single keydown handler for toggling overlay.

help/change-your-language.md
Current:  https://zulip.com/help/change-your-language
Updated:
=> help: Explain translation %s.

web/styles/app_components.css, web/styles/app_variables.css
Followup to https://github.com/zulip/zulip/pull/33297/files#r1951862116
=> app_components: Use variable for default dropdown widget button.

help/introduction-to-channels.md
Expands the mobile tab for "Browse and subscribe to channels" to include information about subscribing to a channel via a link and the long-press channel menu.
Relevant CZO discussion: [#documentation > subscribe to a channel - adding mobile instructions #F1790](https://chat.zulip.org/#narrow/channel/19-documentation/topic/subscribe.20to.20a.20channel.20-.20adding.20mobile.20instructions.20.23F1790)
[CURRENT DOC](https://zulip.com/help/introduction-to-channels)
---
<details> …
=> help: Expand browse & subscribe to a channel mobile tab information.

.github/workflows/production-suite.yml, docs/overview/changelog.md, docs/production/install.md, docs/production/upgrade.md, help/configure-a-custom-welcome-message.md, help/configure-default-new-user-settings.md, help/set-default-channels-for-new-users.md, puppet/zulip/manifests/profile/app_frontend.pp, scripts/reload-clients, tools/linter_lib/custom_check.py, web/shared/icons/user-circle-idle.svg, web/src/hotkey.js, web/src/lightbox.ts, web/src/portico/signup.ts, web/src/server_events_dispatch.js, web/src/stream_edit.ts, web/src/stream_settings_ui.ts, web/src/stream_ui_updates.ts, web/src/topic_list.ts, web/styles/app_variables.css, web/templates/stream_settings/browse_streams_list_item.hbs, web/templates/stream_settings/stream_permissions.hbs, web/templates/stream_settings/stream_settings.hbs, web/templates/user_group_settings/browse_user_groups_list_item.hbs, web/tests/dispatch.test.cjs, zerver/lib/reminders.py, zerver/management/commands/export_search.py, zerver/tests/test_reminders.py, zproject/computed_settings.py
These are all clean backports that we definitely want in 11.1.
- #35855
- #35839
- #35810
- #35800
- #35780
- #35806
- #35814
- #35829
- #35809
- #35768
- #35756
- #35763
- #35797
- #35886
- #35871
- #35847
=> Backport several changes to the 11.x branch

help/change-organization-url.md
Before: https://zulip.com/help/change-organization-url
After:
=> help: Clean up intro wording.

api_docs/group-setting-values.md, zerver/openapi/zulip.yaml
- First commit to fix the incorrect group-setting value fields [#api design > groups redesign @ 💬](https://chat.zulip.org/#narrow/channel/378-api-design/topic/groups.20redesign/near/2247218)
- Second commit is to mark `server_supported_permission_settings` field as stable [#api design > server_supported_permission_settings @ 💬](https://chat.zulip.org/#narrow/channel/378-api-design/topic/server_supported_permission_settings/near/2250402)
<details> …
=> Update API docs related to group permission settings.

web/src/settings_exports.ts
| <img width="892" height="629" alt="image" src="https://github.com/user-attachments/assets/76ddcec9-c7ca-4e5e-8154-c45ce3ed9d05" />  | <img width="892" height="629" alt="image" src="https://github.com/user-attachments/assets/0747cf8b-fc0a-4380-bef5-5c13eb994bf4" />  |
| <img width="892" height="629" alt="image" src="https://github.com/user-attachments/assets/b13a5958-6214-478d-b3c3-311b1af270e2" /> | <img width="892" height="629" alt="image" src="https://github.com/user-attachments/assets/5b28e002-3256-4a2f-977d-ce3b1d57efb6" />  |
| <img width="892" height="629" alt="image" src="https://github.com/user-attachments/assets/501b8d26-95a6-4923-b4ce-422f475db212" /> | <img width="892" height="629" alt="image" …
=> settings_export: Fix plural strings in export confirmation modal.

web/src/search_pill.ts
Earlier, we removed topic display name for empty topic operand when query was for topic autocomplete. But we should make sure that we only do this for the last search term in the suggestion which corresponds to the typed query and not any previously selected entered search term. Also recently we removed subset suggestions, so can safely check it for last search term for all suggestions.
This PR fixes this by checking if the topic suggestion is the last search_term in the suggestion/search_terms.
Fixes: [#issues > ✔ 🎯 pills in typeahead tweaks @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.E2.9C.94.20.F0.9F.8E.AF.20pills.20in.20typeahead.20tweaks/near/2215875) and improves #35210
|**Before:**|**After:**|
|-|-|
|<img width="352" height="121" …
=> search_suggestion: Fix empty topic suggestion topic display name.

web/e2e-tests/message-basics.test.ts, web/src/activity_ui.ts, web/src/list_cursor.ts, web/src/sidebar_ui.ts, web/src/user_search.ts, web/tests/list_cursor.test.cjs
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/sidebar.20sections.20keyboard.20nav/with/2252104
=> Don't select left sidebar header as first row when searching.

starlight_help/src/content/docs/include/_NumberedListsExamples.mdx
The list inside the code block should not have any Steps component inside it, since that is reserved for our MDX, not the formatting guide for the Zulip apps.
<details>
</details>
=> help: Remove incorrectly inserted steps component in code blocks.

starlight_help/src/content/docs/add-a-custom-linkifier.mdx, starlight_help/src/content/docs/bots-overview.mdx, starlight_help/src/content/docs/code-blocks.mdx, starlight_help/src/content/docs/custom-certificates.mdx, starlight_help/src/content/docs/deactivate-your-organization.mdx, starlight_help/src/content/docs/desktop-app-install-guide.mdx, starlight_help/src/content/docs/format-a-quote.mdx, starlight_help/src/content/docs/import-from-mattermost.mdx, starlight_help/src/content/docs/import-from-rocketchat.mdx, starlight_help/src/content/docs/import-from-slack.mdx, starlight_help/src/content/docs/include/_ImportHowUsersWillLogIn.mdx, starlight_help/src/content/docs/latex.mdx, starlight_help/src/content/docs/linking-to-zulip.mdx, starlight_help/src/content/docs/saml-authentication.mdx, starlight_help/src/content/docs/schedule-a-reminder.mdx, starlight_help/src/content/docs/scim.mdx, starlight_help/src/content/docs/share-and-upload-files.mdx, starlight_help/src/content/docs/spoilers.mdx
=> Escaping in help/

tools/lib/capitalization.py, web/src/navbar_alerts.ts, web/src/portico/showroom.ts
=> Backport #35772

package.json, pnpm-lock.yaml, starlight_help/package.json, starlight_help/src/.remarkrc.js, tools/format-mdx, tools/lint, version.py
[Discussion](https://chat.zulip.org/#narrow/channel/19-documentation/topic/lint.20fix.20reverts.20some.20changes.20from.20.2335941/near/2254822)
Cc @shubham-padia
=> lint: Don’t auto-fix with remark unless requested

starlight_help/src/content/docs/export-your-organization.mdx
Current: https://chat.zulip.org/help/export-your-organization/
<details>
<summary>
Updated
</summary>
</details>
=> help: Add more links to self-hosted export instructions.

tools/zulip-export/zulip-export, web/src/message_edit.ts, web/src/message_helper.ts, web/src/message_store.ts, web/src/recent_view_ui.ts, web/src/server_message.ts, web/src/submessage.ts, web/tests/message_edit.test.cjs, web/tests/message_events.test.cjs, web/tests/popover_menus_data.test.cjs, web/tests/submessage.test.cjs
Prep work for typescript conversions
=> message: Fix up some fields that were missing during typescript work

docs/production/requirements.md, docs/production/system-configuration.md, docs/subsystems/performance.md
=> docs: Document Tornado sharding configurations.

zerver/lib/cache.py
This ensures that the new choice of zstd compression does not break the previous, still-running, install during upgrades when the list of cache_key_prefixes is updated.
Fixes: 
<details>
</details>
=> cache: Write cache_key_prefixes without any compression.

web/src/compose.js, web/tests/compose.test.cjs
Followup to https://github.com/zulip/zulip/pull/35921#discussion_r2320358287
=> compose: Remove Zephyr mirroring custom logic.

tools/run-dev, zerver/management/commands/runtornado.py, zproject/computed_settings.py, zproject/sentry.py
=> Tornado Sentry

zerver/data_import/slack.py
Fixes: errors importing messages sent by bots, or threads whose parent is a bot message
<details>
Consider the following messages JSON (taken from real data, redacted):
```json
[
{
"subtype": "bot_message",
"text": "",
"attachments": [
{
"fallback": "Open Slack to cast your vote in this Simple Poll",
"title": "Should we do a thing?",
"id": 1,
"color": "6ecadc",
"fields": [
{
"title": "",
"value": ":one: Yes :thumbsup:\n\n",
"short": false
},
{
"title": "",
"value": ":two: No :thumbsdown:\n\n",
"short": false
},
{
"title": "",
"value": ":three: Abstain :spock-hand:\n\n",
"short": false
}
],
"mrkdwn_in": [
"fields"
]
},
{
"callback_id": "12345678-1234-1234-1234-123456789abc",
"fallback": "Open Slack to cast your vote in this Simple Poll",
"id": 2,
"color": "6ecadc",
"actions": [
{
"id": …
```
=> Fix errors importing messages from bots

docs/documentation/api.md, docs/overview/architecture-overview.md, docs/overview/changelog.md, docs/translating/finnish.md, docs/tutorials/new-feature-tutorial.md, templates/zerver/development/dev_tools.html, tools/lib/capitalization.py, tools/linter_lib/custom_check.py, web/src/portico/help.ts, zerver/lib/onboarding.py, zerver/openapi/zulip.yaml, zerver/tests/test_middleware.py, zerver/tests/test_tutorial.py
Fixes https://chat.zulip.org/#narrow/channel/101-design/topic/help.20center.20capitalization
<details>
</details>
=> help: Do not treat `Help Center` as a proper noun.

zerver/lib/email_mirror_server.py
=> email_mirror_server: Drop privileges before attaching file handler.

docs/documentation/api.md, docs/documentation/helpcenter.md, docs/documentation/integrations.md, docs/documentation/overview.md
The help center documentation now uses astro/starlight, so the contributor documentation is updated here for the general changes to that documentation, such as where to find files, and features and components used in that documentation.
Moves features that are still used for integrations and API docs, to those guides, e.g., tabbed sections and our macros system, so that we still have documentation for those systems/features.
**Notes**:
- The automated testing section needs an update for the move to astro/starlight, but that can be done in a follow up or separate PR.
*Screenshots can also be found in the RTD run of CI.*
<details>
<summary>Overview page changes</summary>
</details>
<details>
<summary>API page - main changes</summary>
</details>
<details> …
=> docs: Update writing documentation for starlight help center.

web/src/pygments_data.ts, web/src/realm_playground.ts, web/src/recent_view_ui.ts, web/src/topic_list.ts
=> typescript fixups

tools/test-js-with-node, web/src/channel_folders.ts, web/src/left_sidebar_navigation_area.ts, web/src/list_cursor.ts, web/src/settings_data.ts, web/src/stream_list.ts, web/tests/channel_folders.test.cjs, web/tests/left_sidebar_navigation_area.test.cjs, web/tests/list_cursor.test.cjs, web/tests/settings_data.test.cjs, web/tests/stream_list.test.cjs
=> channel folders: Finish test TODOs

web/styles/image_upload_widget.css
"Upload profile picture" and similar text shown when hovering over the image shows
a blue outline while clicking on it and same blue outline is shown when clicking on the
delete button ("x") as well. This commit updates the CSS to remove that outline.
Before 
[Screencast from 2025-09-24 15-08-06.webm](https://github.com/user-attachments/assets/052d5210-3546-48d8-9687-58c174b6382c)
After
[Screencast from 2025-09-24 15-09-45.webm](https://github.com/user-attachments/assets/ff036538-b9f6-4b52-8bea-644978611ac7)
<details> …
=> image_upload_widget: Remove blue outline when clicking.

web/src/narrow_state.ts, web/src/search_suggestion.ts
**Notes**:
- Prior to these changes the only callers of `narrow_state.pm_emails_string` were `narrow_state.pm_ids_string` and `search_suggestions.suggestions_for_current_filter`.
- The search suggestions were checking for whether to add a default channel or "is:dm" suggestion to an empty search bar with a current message list filter, so the `narrow_state.narrowed_by_topic` and `narrow_state.narrowed_by_pm_reply` work for that check.
- Removing `pm_emails_string` is helpful because it was less clear that the function could return a value that was not a valid direct message recipient (i.e., a valid list of known user emails).
- Updates the comment in `pm_ids_string` to note that there's a case where the operand value does not return a valid list of user IDs.
---
<details> …
=> narrow-state: Move "pm_emails_string" logic to "pm_ids_string".

starlight_help/astro.config.mjs, starlight_help/src/styles/main.css
Fixes https://chat.zulip.org/#narrow/channel/19-documentation/topic/left.20sidebar.20icon.20for.20external.20links.3F/with/2257078
These links should also open in a new window.
<details>
</details>
=> help: Add external link icon as suffix in sidebar for external links.

web/src/buddy_data.ts, web/src/buddy_list.ts, web/src/message_list_view.ts, web/src/peer_data.ts, web/src/stream_data.ts, web/src/stream_edit_subscribers.ts, web/src/stream_events.ts, web/src/stream_pill.ts, web/src/typeahead_helper.ts, web/tests/activity.test.cjs, web/tests/buddy_list.test.cjs, web/tests/dispatch_subs.test.cjs, web/tests/lib/buddy_list.cjs, web/tests/peer_data.test.cjs, web/tests/stream_events.test.cjs
=> peer_data: Add clarity for when we do/don't have the full subscriber set.

zerver/lib/export.py, zerver/lib/import_realm.py, zerver/management/commands/export_search.py, zerver/openapi/curl_param_value_generators.py, zerver/tests/test_import_export.py
Make more use of iterators to store less of the database in memory.
<details>
</details>
=> Stream exports

docs/subsystems/widgets.md, tools/test-js-with-node, web/src/submessage.ts, web/src/widgetize.ts, web/src/widgets.js, web/src/zform.ts
This PR is built on top of  #36048 which should be merged first, and is only the last commit. I'll rebase and remove conflicts once that PR is merged.
=> zform: Convert module to typescript.

tools/lib/capitalization.py, web/src/info_overlay.ts, web/src/markdown.ts, web/src/server_events_dispatch.js, web/templates/keyboard_shortcuts.hbs, web/tests/dispatch.test.cjs
=> Translate keyboard shortcuts

Dockerfile-postgresql, docs/production/deployment.md, docs/production/install.md, docs/production/system-configuration.md, docs/subsystems/release-checklist.md, tools/ci/Dockerfile.prod, web/src/compose_recipient.ts, web/src/compose_setup.js, web/src/inbox_ui.ts, web/src/recent_view_ui.ts, web/src/settings_config.ts, web/src/stream_list.ts, web/src/ui_init.js, web/src/views_util.ts, web/styles/compose.css, web/styles/inbox.css, web/templates/settings/organization_permissions_admin.hbs, zerver/data_import/slack.py, zerver/lib/email_mirror_server.py, zerver/webhooks/gitlab/doc.md
- #35826
- #35969
- #36060
- #36026
- #36060
- #36063
- #36067
- #36068
- #36077
- #36123
- #36127
- #36132
- #36135
- #36151
- #36161
- #36168
=> Backport several changes to 11.x

tools/test-js-with-node, web/src/compose_actions.ts, web/src/compose_recipient.ts, web/src/compose_setup.ts, web/src/dialog_widget.ts, web/src/filter.ts, web/src/message_events.ts, web/src/ui_init.js, web/tests/compose_video.test.cjs
Built on top of #36050, merge that first.
=> compose_setup: Convert module to typescript.

web/src/onboarding_steps.ts
Earlier, transient errors while marking an onboarding step as read resulted in blueslip reporting - which is not required.
This commit updates the logic to retry with backoff in case of error.
Did manual testing for both success & error case.
<details>
</details>
=> onboarding_steps: Retry with backoff when marking a step as read fails.

web/styles/app_components.css, web/styles/app_variables.css, web/styles/compose.css, web/styles/dark_theme.css, web/styles/settings.css, web/styles/subscriptions.css
Addresses first 3 points of #35881. For the box-shadow rules of the 4th point. Those exist only in dark theme, so light-dark won't work. I'm not sure how to fix that, so I've left that out of this PR.
Built on top of #36138, any commit numbering below does not include that commit in the numbering.
Commit 1 (subscriber list box):
| --- | ---- |
| <img width="711" height="186" alt="subscriber_list_dark_before" src="https://github.com/user-attachments/assets/aad445b8-fa10-48fd-a828-b3f3ec8a8d70" /> | <img width="711" height="186" alt="subscriber_list_dark_after" src="https://github.com/user-attachments/assets/2a0da13a-1682-4d96-b722-7945c527aeb1" /> |
| <img width="711" height="186" alt="subscriber_list_light_before" …
=> subscriptions: Use light-dark() for .subscriber-list-box.

docs/production/install.md, docs/production/mobile-push-notifications.md, zerver/tests/test_push_notifications.py, zilencer/views.py
=> Better remote server registration email errors

package.json, pnpm-lock.yaml, puppet/zulip/files/nginx/zulip-include-frontend/app, starlight_help/astro.config.mjs, tools/run-dev, version.py
Test prod instance deployed on https://139.59.67.174/help/.
<details>
</details>
=> Help canonical

starlight_help/src/route_data.ts
Partially fixes #35110.
Should only be merged after #36098 
We ideally want this only for self hosted installations since we want to point them to the right canonical URL. But we can have this for all pages since for zulip.com, this will be a self referencing URL.
<details>
</details>
=> help: Add canonical URL pointing to zulip.com.

web/styles/app_components.css, web/styles/app_variables.css, web/styles/settings.css, web/templates/settings/linkifier_settings_admin.hbs, web/templates/settings/playground_settings_admin.hbs, web/templates/settings/preferences_emoji.hbs, web/templates/settings/preferences_information.hbs
Before:
After: 
<details>
</details>
=> css: Use --color-background-modal-bar for .grey-box
