zulip/zulip

web/styles/zulip.css

discussion: [#redesign project > broader range of font sizes @ 💬](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/broader.20range.20of.20font.20sizes/near/2108463)
| --- | --- |
| 14px |
| ![image](https://github.com/user-attachments/assets/97aa534c-ae6b-4c9e-8171-062cf91baa53) | ![image](https://github.com/user-attachments/assets/4af1e593-1bd8-4202-a4b3-afee7698a07e) |
| 16px |
| ![image](https://github.com/user-attachments/assets/f17cc6ad-91a6-4d42-894b-a2e2bdb258bb) | ![image](https://github.com/user-attachments/assets/c59eceaa-958b-4757-b75a-2370fe751848) |
| 20px |
| ![image](https://github.com/user-attachments/assets/9f63fdbb-e3f6-47b3-bab2-545deaa92158) | ![image](https://github.com/user-attachments/assets/f77e62e3-3dd8-4014-bd69-877b788c8c97) | …

Scale scroll to bottom icon with font size. 

---

web/src/bootstrap_typeahead.ts
web/src/composebox_typeahead.ts

Description via the commit message:
> Previously, via commit ecf557e, the logic for the click action on the
> input field was added to the typeahead to aid with the interaction
> when the user changes the position of the cursor — targeted at the
> compose box where there could be multiple instances of typeahead.
> 
> This commit adds an option to disable the rendering of typeahead when
> the user navigates within the input element via clicks — suitable for
> single input elements where we don't expect multiple typeaheads.
Fixes: [CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20topic.20editing.20typeahead.20UX)
| ![topic_typeahead_before](https://github.com/user-attachments/assets/a8c …

typeahead: Improve topic editing typeahead UX

---

web/src/presence.ts
web/tests/presence.test.cjs

We don't always know about every user id. So, our code should reflect the same.
Fixed by refactoring the function to use User object a function parameter and let the called get the user object if possible. This reduces duplicate calculation to get user object too.

presence: Fix exception on trying to get user from ID.

---

web/src/list_widget.ts
web/src/recent_view_ui.ts

This is just a bug fix based on observation that we would only be updating rows that are rendered and not all of them. This can potentially lead to rows being rendered twice but is hard to observe since newly updated topics usually are the top of the recent view.
discussion: [#issues > 🎯 ❓Duplicates in recent view](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20.E2.9D.93Duplicates.20in.20recent.20view/with/2033239)

recent_view: Avoid rendering rows before user scrolls to them.

---

web/styles/settings.css
web/templates/components/action_button.hbs
web/templates/components/icon_button.hbs
web/templates/settings/account_settings.hbs
web/templates/settings/alert_word_settings.hbs
web/templates/settings/bot_settings.hbs
web/templates/settings/organization_profile_admin.hbs
web/templates/settings/profile_settings.hbs

In this PR, I have restyled the button present in Personal settings and a few in Organization Settings.
Commit 1:
> Add a new bot, Add alert word: action-button-quiet-brand
Commit 2:
> "Preview profile": action-button-quiet-brand
> Pencil for email editing: action-button-quiet-brand
Change your password: action-button-quiet-brand
Deactivate account: action-button-quiet-danger
Manage your API key: action-button-quiet-brand
Commit 3:
>Restyle "Deactivate organization" as action-button-quiet-danger
Fixes part of :  #33130.
| **Location**  | **Before** | **After (At 12px)** | **After (At 16px)** | **After (At 20px)** |
|---------------|-----------|--------------------|--------------------|--------------------|
| Preview profile          | <img width="223" …

organization_settings: Restyle many sea-green buttons to action-button-quiet-brand.

---

help/include/when-to-start-a-new-topic.md
help/introduction-to-topics.md

Current: https://zulip.com/help/introduction-to-topics
Updated/new sections:

help: Improve explanation of Zulip's topics for users from other apps.

---

web/src/compose_paste.ts
zerver/tests/fixtures/katex_test_cases.json

This is better than using `.katex` as sometimes
the selection range starts from the `.katex-mathml`.
Since `.katex-mathml` is always the immediate child of `.katex`, this filtering/replacement change will make copy pasting inline expressions better.

compose_paste: Use `katex-mathml` for filtering.

---

docs/production/upgrade.md

- Arrange info more cleanly into sections.
- Avoid duplicating git versions documentation.
I went over the first few sections pretty thoroughly and read the next few, but did not read [Upgrading the operating system](https://zulip.readthedocs.io/en/stable/production/upgrade.html#upgrading-the-operating-system).
CZO discussion: [#documentation > documentation for super old versions](https://chat.zulip.org/#narrow/channel/19-documentation/topic/documentation.20for.20super.20old.20versions/with/2108486)

docs: Improve Upgrade Zulip documentation.

---

web/src/stream_popover.ts
web/src/unread_ops.ts
web/templates/popovers/left_sidebar/left_sidebar_stream_actions_popover.hbs

This commit adds an option to show `Mark all messages as unread` when all unmuted messages in the channel are read.
fixes #33067.
| read | unread |
| --- | --- |
| ![Before Image](https://github.com/user-attachments/assets/c85393c2-7fd5-4dd4-bc4a-8f1a7f867c37) | ![After Image](https://github.com/user-attachments/assets/93b142cf-9f64-4b4c-b24a-e255d55664dd) |
<details>
<summary>demo</summary>
https://github.com/user-attachments/assets/428ab269-3c9f-4571-94a5-134594763e77
</details> 
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html …

left_sidebar: Show `Mark all messages as unread` in channel popover.

---

web/src/css_variables.ts
web/src/realm_logo.ts
web/styles/app_variables.css
web/styles/zulip.css

This PR better presents the navbar elements in and outside of the "Use full width" setting, and with regard to the manual hiding of the left sidebar. Essentially, we now handle breakpoints and layout shifts the same, regardless of the "Use full width" setting--which setting now effectively only removes the otherwise-enforced `max-width` on the UI.
The PR also hides descriptions below a certain minimum screen size. While this approximates what's called for in #33685, a better engineered solution will likely require a container query and possibly a gridded presentation, so that we can maintain an ellipsis-free view/channel name
Fixes: #30619; fixes #33715. Provides partial, interim fix for #33685.
Things tested:
* Resizing window width with different font sizes
* Resizing window with and …

navbar: Better align middle column and logo elements.

---

web/src/buddy_data.ts
web/src/presence.ts
web/src/user_card_popover.ts
web/templates/popovers/user_card/user_card_popover.hbs
web/tests/buddy_data.test.cjs

This pull request introduces changes to enhance the user presence functionality and refactor the user card popover handling. The user card now pops up instantaneously when clicked and re-renders once the user's last active data is fetched.
When a user's card is opened, the web app fetches presence data for users who have been idle for an extended period. 
Initially, it displays `Loading...` if no `last_active` data is available, and this value is updated as soon as the data fetch is completed.  
See the attached screenshot below for the new behavior.
Fixes: #31037.
<details>
<summary>Loading Indicator: </summary>
</details>
<details>
<summary>Exact date after fetch is completed: </summary>
</details>
<details> …

presence_data: Fetch presence data when user card is opened.

---

web/src/bootstrap_typeahead.ts
web/src/composebox_typeahead.ts
web/styles/typeahead.css

This was moved to the bottom in 3e3deb2, but the naming had not been updated.
Followup to #33584.

typeahead: Rename header text as more accurate footer text.

---

web/src/typeahead_helper.ts
web/tests/composebox_typeahead.test.cjs
web/tests/typeahead_helper.test.cjs

Fixes #32987
We place bot matches below group and user matches in the typeahead list.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/935c1205-8a98-49c5-8111-9489a1114176) | ![Screenshot 2025-02-25 090746](https://github.com/user-attachments/assets/c7e7cc2b-49a4-442a-b318-c6087462a2b7) |

typeahead: Place bots below group matches.

---

web/styles/subscriptions.css

This was causing issues with the red icon having the wrong height and centered buttons looking weird at narrow screens.
Further discussion here:
https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20UI.20issues.20in.20channel.20settings.20.28narrow.20windows.29/near/2105436
| --- | --- |
| ![Screen Shot 2025-03-03 at 14 55 44](https://github.com/user-attachments/assets/c54e66a0-ea9d-4d1e-883e-55124ab66ee9) | ![Screen Shot 2025-03-03 at 14 57 29](https://github.com/user-attachments/assets/d505e115-907a-4a5a-bc99-75ea6641afe6) |
| ![Screen Shot 2025-03-03 at 14 55 28](https://github.com/user-attachments/assets/d2b8ff82-4a4b-4570-8df4-8504b3add687) | ![Screen Shot 2025-03-03 at 14 59 59](https://github.com/user-attachments/assets/dc0c6cd5-7282-4cfb-aa43-da469 …

subscriptions/user_groups: Remove custom styling for <=500px screens.

---

web/src/compose.js
web/src/compose_setup.js
web/src/compose_state.ts
web/src/compose_ui.ts

In preview mode, background updates to the compose box don’t refresh the preview. For example, canceling an ongoing file upload after activating preview mode still shows "uploading".
To fix this, we modified `show_preview_area` function to accept an argument for skipping initialization and only re-rendering, then called it on compose text area's `change` event listener.
Fixes [#33589](https://github.com/zulip/zulip/issues/33589)
Before | After
--- | ---
<details> …

compose: fix preview not being updated when compose textarea is updated

---

web/src/unread_ops.ts
web/styles/zulip.css
web/templates/skipped_marking_unread.hbs

Displays a notice to inform users when the "Mark as unread from here" action is unable to mark some messages as unread because they are in unsubscribed streams.
This PR attempts to complete the original work done by https://github.com/zulip/zulip/pull/26634 completion candidate PR.
Fixes: https://github.com/zulip/zulip/issues/23470
Discussion: [CZO](https://chat.zulip.org/#narrow/stream/101-design/topic/not.20marked.20as.20unread.20banner/near/1627530)
[CZO design discussion](https://chat.zulip.org/#narrow/stream/3-backend/topic/update.20has_message_access.3F/near/1638961)
[CZO api design](https://chat.zulip.org/#narrow/stream/378-api-design/topic/Not.20marked.20unread.20banner/near/1635508)
Dark Mode:
Light Mode:
<details> …

Notify user when messages in unsubscribed streams are not marked as unread #23470

---

web/styles/right_sidebar.css

This improves the grid definition on the buddy list popover to ensure the full width is displayed on Safari. There is no effect from this on other browsers.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/User.20List.20Style.20Menu.20styling.20Issue.20in.20Safari/near/2111081)
| Safari, Before | Safari, After |
| --- | --- |
| ![user-list-style-safari-before](https://github.com/user-attachments/assets/653ae406-fc1e-48e2-b69d-fabf003e40cd) | ![user-list-style-safari-after](https://github.com/user-attachments/assets/30ce26e3-5eb8-4d4c-9b76-fd5c3446a63c) |
| Firefox, Before | Firefox, After (no change) |
| --- | --- |
| ![user-list-style-ff-before](https://github.com/user-attachments/assets/06180041-4666-4e83-a573-511ceed45708) | …

right_sidebar: Improve grid on list-style menu.

---

web/styles/app_components.css
web/styles/compose.css
web/styles/zulip.css
web/templates/dropdown_list.hbs

This PR improves the saved snippets UI through the following ways:
- Reduces the space between the saved snippet title and description for a more interconnected feel.
- Changes the delete icon from the old font-awesome icons to using the new icon button component.
- Adds line-clamping to the saved snippet description to display two lines of text instead of one, presenting the user with more context.
Fixes: [#design > saved snippets UI tweaks @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/saved.20snippets.20UI.20tweaks/near/2110624)
| ![Screenshot 2025-03-04 at 8 12 32 PM](https://github.com/user-attachments/assets/8e6ae960-146b-4ee1-a9a3-be182f60f38d) | ![Screenshot 2025-03-04 at 8 10 …

saved_snippets: Improve saved snippets UI.

---

help/marking-messages-as-read.md
help/marking-messages-as-unread.md

This is a follow-up to #33067.
Current: https://zulip.com/help/marking-messages-as-read
<details>
<summary>
Updated
</summary>
</details>
---
Current:  https://zulip.com/help/marking-messages-as-unread
<details>
<summary>
Updated
</summary>
</details>
---
Follow-up idea that came up while working on this: [#design > When to show Mark all messages as unread on channel popover @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/When.20to.20show.20Mark.20all.20messages.20as.20unread.20on.20channel.20popover/near/2111219)

help: Document marking a whole topic or channel as unread.

---

web/src/stream_edit.ts
web/styles/subscriptions.css

Built off of #33538 (which is the first commit here) -- the before images are from that PR and the after images are after this PR is layered on top of that.
At 20px it scrolls in this screenshot, but on most screens it wouldn't scroll, the screenshot screen height is just short. Though I am wondering if it makes sense to make the email text smaller so it's less likely to overflow at larger font-sizes.
| before | after | 
| --- | --- |
| ![Screen Shot 2025-02-18 at 18 08 05](https://github.com/user-attachments/assets/515260ea-e619-4806-b7d7-beba811f6d9c) | ![Screen Shot 2025-02-20 at 12 54 20](https://github.com/user-attachments/assets/56bb9ca7-91e3-4513-90d5-6d2b08c3e75b) |
| ![Screen Shot 2025-02-18 at 18 08 24](https://github.com/user-attachments/assets/e79e2069-6d23-45a5-ae5f-ab06760a74 …

subscriptions: Scale copy email icon with font size.

---

web/src/buddy_list.ts

Previously the count was sometimes incorrect because we were subtracting unsubscribed participants from the subscriber count, getting values that were too low (and sometimes negative!)
This count is displayed in the hover tooltip and section headers.
Fixes #33452

buddy_list: Fix incorrect user count in the right sidebar.

---

web/src/stream_popover.ts
web/templates/modal_banner/topic_already_exists_warning_banner.hbs
web/templates/move_topic_to_stream.hbs

Moving messages is a powerful tool that helps organize conversations and keep them in place. However, moving messages to an existing topic can be messy and create a confusing flow of conversation which is difficult to undo. We should warn users before moving a topic.
Fixes: #31151.
<details>
<summary>Moving Messages</summary>
</details>
<details>
<summary>Moving Topic</summary>
</details>
<details>
</details>

topic_move: Add warning banner if moving messages to existing topic.

---

web/styles/settings.css

| --- | --- |
| ![Screen Shot 2025-03-04 at 11 00 10](https://github.com/user-attachments/assets/a9edb7d6-4bf3-435a-80cd-3ebf329fca1a) | ![Screen Shot 2025-03-04 at 10 59 40](https://github.com/user-attachments/assets/1617b926-d465-4d54-afa9-0ef0b07bb38e) |
| ![Screen Shot 2025-03-04 at 11 00 20](https://github.com/user-attachments/assets/f45613d4-2533-40e0-969c-072e81dd2330) | ![Screen Shot 2025-03-04 at 10 59 28](https://github.com/user-attachments/assets/8c2d1691-5c15-426e-9e54-07f770564e03) |
| ![Screen Shot 2025-03-04 at 11 00 28](https://github.com/user-attachments/assets/a5537591-82fd-4f15-8e24-f0f79f09cf46) | ![Screen Shot 2025-03-04 at 10 58 52](https://github.com/user-attachments/assets/f5d5da03-751a-4226-950a-853b3499db93) |
| …

stream settings: Scale advanced configuration toggle icon with font size

---

zerver/actions/streams.py
zerver/lib/user_groups.py
zerver/tests/test_events.py
zerver/tests/test_invite.py
zerver/tests/test_markdown.py
zerver/tests/test_message_edit.py
zerver/tests/test_message_flags.py
zerver/tests/test_message_move_stream.py
zerver/tests/test_message_send.py
zerver/tests/test_reactions.py
zerver/tests/test_subs.py
zerver/tests/test_user_groups.py
zerver/views/streams.py

Commit 1 is a minor bug fix + refactor: 
Passing the user group object in case of named user group is fine for `do_change_stream_group_based_setting`. But for anonymous groups, if the code path calling that function is not creating a new anonymous user group, it has to modify the user group by itself before calling that function. In that case, if `old_setting_api_value` is not provided, `old_user_group` is calculated false, since the group id has not changed for the stream, but the group membership has changed. old_setting_api_value will be the same as new_setting_api_value in such a case. It is better to accept the new setting value as either an int or UserGroupMembersDict, so that `do_change_stream_group_based_setting` can decide what to do with that argument.
Commit 2:
Fixes part of …

stream: Send stream create/delete event on group setting change. 

---

web/styles/app_components.css
web/styles/buttons.css
web/styles/compose.css
web/styles/inbox.css
web/styles/message_row.css
web/styles/portico/billing.css
web/styles/portico/hello.css
web/styles/portico/integrations.css
web/styles/portico/navbar.css
web/styles/portico/portico.css
web/styles/portico/portico_signin.css
web/styles/settings.css
web/styles/subscriptions.css
web/styles/widgets.css

https://github.com/kristerkari/stylelint-high-performance-animation/issues/216 was fixed upstream.
- Followup to #32109

styles: Remove obsolete ‘transition: none …’ workaround

---

web/styles/recent_view.css

| --- | --- |
| ![Screen Shot 2025-03-04 at 11 14 54](https://github.com/user-attachments/assets/33af3d08-7c8d-4866-a209-5f5693dc1afc) | ![Screen Shot 2025-03-04 at 11 09 52](https://github.com/user-attachments/assets/acefbcb5-68f7-4288-991d-83124c25b22a) |
| ![Screen Shot 2025-03-04 at 11 15 11](https://github.com/user-attachments/assets/bf1119d6-4057-4a2f-bad5-447b41067679) | ![Screen Shot 2025-03-04 at 11 10 08](https://github.com/user-attachments/assets/fdcd1346-5120-4daf-b5a6-306c7a2963a0) |
| ![Screen Shot 2025-03-04 at 11 15 29](https://github.com/user-attachments/assets/e0237dc0-c8ee-40f3-92a2-5bbae6579f53) | ![Screen Shot 2025-03-04 at 11 10 32](https://github.com/user-attachments/assets/e0013548-152c-4376-a831-e6c610746929) |
| …

recent_view: Scale unread icon with font size on small screens.

---

web/styles/zulip.css

Lock icon at 12px, 14px, 16px, 20px:
| --- | --- |
| ![Screen Shot 2025-03-04 at 12 38 29](https://github.com/user-attachments/assets/e089ef56-f00a-44fa-b827-f196023c5691) | ![Screen Shot 2025-03-04 at 12 49 43](https://github.com/user-attachments/assets/6ba7c8d6-1c79-440b-ba73-ad0c3c8492b7) |
| ![Screen Shot 2025-03-04 at 12 41 53](https://github.com/user-attachments/assets/36825cc1-b73c-4111-8fa5-0c7e7c64c7b3) | ![Screen Shot 2025-03-04 at 12 47 56](https://github.com/user-attachments/assets/96626daf-9036-4b7e-b433-8c8dfe9339e5) |
| ![Screen Shot 2025-03-04 at 12 42 31](https://github.com/user-attachments/assets/827ef444-7474-412d-a833-caf0f465a5f3) | ![Screen Shot 2025-03-04 at 12 50 54](https://github.com/user-attachments/assets/188c425b-9d36-4cf7-83bd-e4565dcc149e) …

stream_narrow: Scale icon in sub/unsub message with font size.

---

help/deactivate-a-user-group.md
help/include/sidebar_index.md
help/manage-user-groups.md
web/templates/user_group_settings/cannot_deactivate_group_banner.hbs

The help center commit is ready for integration review.
<details>
<summary>
New page
</summary>
</details>
In the second commit, we need to add a "View permissions" button to the banner. @sahil839 could you please take care of that? Now that we have a group permissions panel, we don't need to summarize the group's permissions here. (I also didn't try to figure out if the `<p>` tags are what's causing extra space below the banner text.)

help and groups: Document group deactivation process better.

---

web/src/filter.ts
web/tests/filter.test.cjs

This PR shows the string "Muted user" instead of muted user's name in DM's navbar.
fixes: #33673
|                                    |               Private DMs                    |
| Before     | ![Changes visible in alignment and hover](https://github.com/user-attachments/assets/52b3e7fb-06c0-48af-a7f7-23a23233c5e4)    |
| After  | ![dm](https://github.com/user-attachments/assets/4c5d6bcd-fc93-4373-87d2-04465ff0d299) |
|                                    |                message groups                  |
| Before     | ![Changes visible in alignment and …

navbar: Show "Muted user" instead of muted user's name.

---

zerver/actions/message_edit.py
zerver/tests/test_message_move_stream.py
zerver/tests/test_message_move_topic.py

Fixes #33719
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20live-update.20when.20moving.20messages.20to.20unsubscribed.20channels/with/2107928
Tested by moving message from public to pubic stream where user is not subscribed to new stream.

Fix moved message update not sent to non subscribers of new public stream.

---

web/src/css_variables.ts
web/styles/left_sidebar.css
web/styles/message_row.css

This fixes two issues noted by @alya:
* Icons in the condensed VIEWS row are no longer piled on top of each other
* Action icons are properly hidden for narrower messages, thanks to a new container query
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/Right.20sidebar.20width/near/2111710)
| Condensed views, 12px, before | Condensed views, 12px, after |
| --- | --- |
| ![12-px-condensed-views-at-576w-before](https://github.com/user-attachments/assets/9bdc0e0a-648e-4c16-b191-7f8ed9274e7d) | ![12-px-condensed-views-at-576w-after](https://github.com/user-attachments/assets/badc4c76-2e0e-47fd-9d83-03582b6b0031) |
| Condensed views, 16px, before | Condensed views, 16px, after (no change)|
| --- | --- |
| …

layout: Correct condensed VIEWS icons, and action icons at narrow message widths.

---

puppet/kandra/files/nagios4/conf.d/services.cfg
puppet/zulip/manifests/app_frontend_base.pp
scripts/lib/check_rabbitmq_queue.py
tools/test-backend
zerver/lib/digest.py
zerver/lib/send_email.py
zerver/management/commands/deliver_scheduled_emails.py
zerver/tests/test_email_log.py
zerver/tests/test_email_notifications.py
zerver/tests/test_example.py
zerver/tests/test_invite.py
zerver/tests/test_queue_worker.py
zerver/tests/test_signup.py
zerver/tests/test_users.py
zerver/worker/deferred_email_senders.py
zerver/worker/email_senders_base.py

`deliver_scheduled_emails` tries to deliver the email synchronously, and if it fails, it retries after 10 seconds.  Since it does not track retries, and always tries the earliest-scheduled-but-due message first, the worker will not make forward progress if there is a persistent failure with that message, and will retry indefinitely. This can result in excessive network or email delivery charges from the remote SMTP server.
Switch to delivering emails via a new queue worker.  The `deliver_scheduled_emails` job now serves only to pull deferred jobs out of the table once they are due, insert them into RabbitMQ, and then delete them.  This limits the potential for head-of-queue failures to failures inserting into RabbitMQ, which is more reasonable than failures speaking to a complex external …

deliver_scheduled_emails: Use a queue, instead of infinite retries.

---

corporate/tests/test_support_views.py
web/e2e-tests/settings.test.ts
zerver/forms.py
zerver/lib/exceptions.py
zerver/lib/streams.py
zerver/lib/users.py
zerver/openapi/zulip.yaml
zerver/tests/test_bots.py
zerver/tests/test_example.py
zerver/tests/test_realm.py
zerver/tests/test_signup.py
zerver/tests/test_subs.py
zerver/tests/test_users.py
zerver/views/users.py

This PR standardizes "already in use" error messages for consistency across the codebase.  
- Replace `"Email '{email}' already in use"` with `"Email is already in use."`  
- Use a shared class(`EmailAlreadyInUseError`) for displaying this error message.  
Ensure consistency across all "already in use" messages:  
- `"Channel name already in use"` → `"Channel name is already in use."`  
- `"Name is already in use!"` → `"Name is already in use."`  
- `"Subdomain already in use. Please choose a different one."` →  
`"Subdomain is already in use. Please choose a different one."`  
**Fixes:** #33629 
---
_
---
<details>
</details>

errors: Improve consistently of error messages about name/channel/email/username/subdomain in use

---

web/src/list_widget.ts
web/src/recent_view_ui.ts
web/src/ui_init.js

Fixes #23005
Update rendered time in recent view when user comes back after being idle.

recent_view: Update rendered time when user becomes active.

---

web/e2e-tests/drafts.test.ts
web/src/buddy_data.ts
web/src/inbox_ui.ts
web/src/narrow_title.ts
web/src/people.ts
web/src/pm_list_data.ts
web/src/realm_playground.ts
web/src/scheduled_messages_overlay_ui.ts
web/src/util.ts
web/tests/buddy_data.test.cjs
web/tests/people.test.cjs
web/tests/realm_playground.test.cjs
web/tests/util.test.cjs

This PR continues the work left in #28453. 
This PR brings internationalization by replacing the inconsistent .join(", ") with Intl.ListFormat for accurate and localized list formatting, using a common utility function.
**#28453 is correct and requires correctly rebasing it. The only thing that lacks is correct testing. The `format_array_as_list` function fails tests because the `get_pygments_typeahead_list_for_settings` test previously did not take `user_settings.default_language` into consideration, so I have added that as well.**
</br>
<br/>
Fixes: #26936 
<details> …

Web: Use Intl.ListFormat instead of .join(", ")

---

templates/corporate/comparison_table_integrated.html

Notes:
- Snippets placement within its section is a bit arbitrary.
- I intend to think separately about permissions features, and /for/X pages.

portico: Update features table.

---

web/styles/search.css

I chose 16px instead of 14px as the base size because it looks better to me like that, and also I think I was working on the search bar redesign at 16px so it was probably designed that way.
---
| --- | --- |
| ![Screen Shot 2025-03-04 at 16 46 17](https://github.com/user-attachments/assets/6bfe1376-e989-4c0e-bad4-bd9e4bbde164) | ![Screen Shot 2025-03-04 at 16 44 31](https://github.com/user-attachments/assets/172d8264-5b40-4b23-ae4b-38dd225d9e47) |
| ![Screen Shot 2025-03-04 at 16 46 26](https://github.com/user-attachments/assets/e10a3297-75ed-4d25-a082-c1a1dc3cb327) | ![Screen Shot 2025-03-04 at 16 44 13](https://github.com/user-attachments/assets/95f0b2f4-49dd-4a95-930e-5630958e2c5d) |
| ![Screen Shot 2025-03-04 at 16 46 …

search: Scale search icon in header on short screens.

---

web/styles/subscriptions.css

There are no other CSS rules with this id name and also no grep results for "subscriptions" that have it as an html id, so it seems pretty safe to say this id is no longer being used.
This PR has no visual changes, and is just part of an effort to remove pixel font-size declarations in the codebase.

subscriptions: Remove stale reference to #subscriptions.

---

web/styles/zulip.css

The divider was removed in b53836d.

styles: Remove stale CSS for spectator login divider.

---

web/styles/message_row.css

This was introduced in 5d293c82cdab77308d296 but shortly after 60aa58dfb99a9aa4fa renamed the use of zulip-icon-more-vertical to zulip-icon-more-vertical-spread, so the CSS classname is no longer being used there.
See also, the TODO from 60aa58d:
> TODO: If this alternate version moves forward, there are still styles
> in this PR referring to the other vdots version. So be sure to clean
> those up.

message_row: Remove stale CSS for zulip-icon-more-vertical.

---

web/src/ui_init.js

Left sidebar can contain links empty topics. If user clicks on them, we add `with` operator to the narrow if the topic is empty.
Reproducer:
* Click on a topic in left sidebar.
* Delete all the messages in the topic.
* Click on the topic again.

ui_init: Don't add `with` operator if topic has no messages.

---

web/styles/search.css

Instead of wrapping query to next line, we let it be hidden. User can still use mouse or arrow keys to see the end of the text they typed.
discussion: [#redesign project > broader range of font sizes @ 💬](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/broader.20range.20of.20font.20sizes/near/2105334)
| --- | --- |
| ![Screenshot 2025-03-05 170052](https://github.com/user-attachments/assets/579e0f2b-3283-4c71-8f20-a9e15275a99d) | ![Screenshot 2025-03-05 170036](https://github.com/user-attachments/assets/0e278c4d-7c86-491d-a0e1-b767c98d0447) |

search: Don't wrap query to next line.

---

zerver/lib/cache.py

With 6k users and 7 deployments.  Before:
```
In [2]: %time delete_user_profile_caches(UserProfile.objects.filter(realm_id=6), 6)
(still going after 60min)
```
After:
```
In [2]: %time delete_user_profile_caches(UserProfile.objects.filter(realm_id=6), 6)
CPU times: user 3.34 s, sys: 508 ms, total: 3.85 s
Wall time: 3.91 s
```

Switch to batched cache-clearing in `cache_delete_many`

---

zerver/lib/cache.py
zerver/tests/test_cache.py

Failure to update the cache should log an exception but continue.
Fixes: 
<details>
</details>

cache: Do not fail the request on cache-set failures.

---

scripts/lib/zulip_tools.py

The cron jobs are potentially wrapped by Sentry, which logs "cron failures" and sends emails.  We would like those failures to only be when the cron job itself failed to run successfully -- not when the underlying metric is outside of its normal range.  We would like to differentiate a failure of the monitoring infrastructure from a failure of what it is monitoring.
Swap to return 0 on everything except "unknown" results.

nagios: Change the cron jobs to exit 0 for all ok/warning/critical.

---

web/styles/input_pill.css

Previously we had things like this:
which now look like this:
Note that this applies to all input fields, and words wrap when they're too long for the input field.

input_pill: Don't wrap words mid-word unless they're wider than input.

---

web/src/compose.js
web/src/compose_ui.ts
web/src/message_edit.ts

A recent commit added a condition in `render_and_show_preview` to skip rendering if the compose box’s preview mode wasn’t active. This broke preview mode in message editing, as it relies on the same function.
This commit fixes the issue by refactoring `render_and_show_preview` to accept an element instead of hardcoding `#compose` when checking for preview mode, and updates its usages accordingly.
[CZO Thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20preview.20broken.20in.20message.20editing)
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/ …

message_edit: Fix broken preview

---

web/styles/components.css

Though it's difficult to confirm, we're pretty sure this is always overridden. Regardless, we don't want to have fixed pixel font sizes and it's better if the default is the default font size instead of 12px.
Further discussion:
https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/broader.20range.20of.20font.20sizes/near/2113503

tippy: Remove default fixed font size.

---

web/src/composebox_typeahead.ts

This PR makes sure to suggest *general chat* topic on typing "general chat" in compose recipient box.
| <img width="232" alt="Screenshot 2025-03-05 at 12 52 23 PM" src="https://github.com/user-attachments/assets/8c7eb32d-dcda-4055-90f8-42147417e77d" /> | <img width="213" alt="Screenshot 2025-03-05 at 12 20 14 PM" src="https://github.com/user-attachments/assets/be931f4d-56e5-48b1-a6ab-c8b18ae70d88" />
| <img width="214" alt="Screenshot 2025-03-05 at 12 55 24 PM" src="https://github.com/user-attachments/assets/8dbb55a7-5c50-4da2-a0eb-91fdbce1e95e" /> | <img width="216" alt="Screenshot 2025-03-05 at 12 42 24 PM" src="https://github.com/user-attachments/assets/c5e0ae73-d5bc-4845-84a3-7e0ebf618192" />
| <img width="220" …

composebox: Typing "general chat" should suggest empty string topic.

---

web/src/message_list_hover.ts
web/src/postprocess_content.ts
web/styles/rendered_markdown.css
web/tests/lib/index.cjs
web/tests/postprocess_content.test.cjs
zerver/lib/markdown/__init__.py
zerver/tests/test_link_embed.py
zerver/tests/test_markdown.py

This PR corrects the alignment of the play button on video thumbnails, and does so in a way that ensures a uniform play-button presentation regardless of video type (uploaded, YouTube, or otherwise embedded).
It also writes logic to request the higher-resolution `/mqdefault.jpg` thumbnail available from [the YouTube API](https://developers.google.com/youtube/v3/getting-started#Sample_Partial_Requests), so that YouTube previews should no longer be letterboxed as frequently or presented at dinky sizes, especially when users specify a larger font-size. Adjustments to post-processing on the content ensures older `default.jpg` thumbnails get rewritten. While that might cause a double request, the `default.jpg` thumbnails are so few bytes that I expect this would be negligible. 
[CZO …

rendered_markdown: Present various thumbnail and play-button improvments.

---

web/styles/app_variables.css
web/styles/zulip.css

This is part of an effort to remove all pixel font sizes from most stylesheets. We won't scale this with font size because the flatpickr doesn't scale with font size.

flatpickr: Use constant variable for font-size.

---

web/src/alert_words.ts
web/src/compose_notifications.ts
web/src/composebox_typeahead.ts
web/src/message_helper.ts
web/src/narrow_banner.ts
web/src/people.ts
web/src/user_profile.ts
web/tests/alert_words.test.cjs

This does lookups by email address, which is very much a legacy way to do things, and could throw exceptions if trying to lookup details on an unknown user ID.

people: Remove is_current_user legacy helper.

---

web/src/emoji_picker.ts
web/src/popover_menus.ts

This was happening since the conditions for `reference` being hidden assumed that the reference was in message feed which excludes the navbar and compose box area.
To fix it, we only set `show_as_overlay_if_reference_hidden_at_trigger` as `true` if the reference is inside the message feed.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/detached.20emoji.20picker

emoji_picker: Fix opening as overlay when triggered via composebox.

---

web/src/click_handlers.ts
web/src/message_edit_history.ts
web/src/message_list_tooltips.ts

Previously, clicking on the bouncing "..." (indicating an ongoing edit) did not open the edit history modal, even when the message had prior edits. This made it difficult for users to view the edit history while an edit was in progress.
This commit updates the behavior so that if a message has an edit history, clicking on the bouncing "..." will open the edit history modal, just as clicking on the "EDITED" notice does. If no prior edits exist, the indicator doesn't show any tooltip.
|Without previous edits|With previous edits|
|---------------------------------|----------------------------|
|![image](https://github.com/user-attachments/assets/249350f6-b92c-41fc-b397-58562f50ccd0)|![image](https://github.com/user-attachments/assets/7b727578-268c-474a-be8 …

message_editing: Make bouncing "..." open edit history modal on click.

---

web/styles/app_variables.css
web/styles/popovers.css

This doesn't have any visual changes and is part of an effort to remove px font sizes from most stylesheets.

user_popover: Use variable for sizes in user popover menu. 

---

web/styles/typeahead.css

discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AFchannel.20descriptions.20vertically.20misaligned.20in.20typeahead/with/2114093
20px:
| --- | --- |
| ![Screenshot 2025-03-06 103057](https://github.com/user-attachments/assets/ef136c66-0813-408f-bba5-6d27bb39a837) | ![Screenshot 2025-03-06 103040](https://github.com/user-attachments/assets/c1aac60b-1882-4617-91e9-bf621cd35802) |
| ![Screenshot 2025-03-06 103104](https://github.com/user-attachments/assets/1d215d18-88ef-438c-bf3b-f0d1b09d3a28) |  ![Screenshot 2025-03-06 103031](https://github.com/user-attachments/assets/61d59c6d-4dfa-4180-8676-66e089ef1c9c) |
14px:

typeahead: Fix alignment of secondary text in channel typeaheads.

---

web/styles/dark_theme.css
web/styles/recent_view.css

Using character index for changing icon is not reliable, so we use `background-image` to change the icon being displayed here.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20moons.20instead.20of.20dots.20.3F.3F/with/2114059
No visual change, just restored the original behaviour.
| no hover | hover |
| --- | --- |
| ![Screenshot 2025-03-06 100759](https://github.com/user-attachments/assets/e76c60ce-da77-4a61-b782-f3d69ffdca3f) | ![Screenshot 2025-03-06 100752](https://github.com/user-attachments/assets/06b80291-6f94-455f-9dcc-e24883ff4d01) |
| ![image](https://github.com/user-attachments/assets/dd7c6ffb-91c7-4a15-b820-b2dd21989325) | ![image](https://github.com/user-attachments/assets/9024f48a-3311-400a-aec6-0e5255bfe510) |

recent_view: Make icon change on hover for visibility indicator robust.

---

web/src/compose_recipient.ts

PR to fix [#issues > 🎯 general chat topic overlapping placeholders @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20general.20chat.20topic.20overlapping.20placeholders/near/2106453)
> The "general chat" placeholder seems to be overlapping with "Enter a topic (skip for general chat)" here.
After fixing the above bug; composing message in another topic (not necessarily "") resulted in:
Fixed that in the second commit. We can squash the two commits, I don't have a strong opinion here :)
<details> …

composebox: Fix overlapping placeholder in recipient box for topic="".

---

web/styles/reactions.css

We align bottom border radius with that of the popover to get border to appear around the bottom edges.
`height` was not required on `emoji-picker-popover` as the height is already being limited by `.emoji-popover-emoji-map` which is enough to get the scrolling effect on overflow.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/e721a491-8709-4f36-b75f-27347c0cf933) | ![image](https://github.com/user-attachments/assets/b8d871a3-4b00-49d8-8e1a-56477534d9eb) |

reactions: Fix bottom border missing.

---

web/src/popover_menus.ts

This PR fixes the issue  where the popover menus would disappear on very small screen. This is done by changing its property to bottom when viewed on mobile/small screen. This still retains the functionality of popover_menus appearing on top of element for normal screen and handles issue where it would disappear on small screen.
This PR addresses the issue from scratch, independent of the previous assignee's work, as their post-review changes did not fully resolve the problem. My approach differs from the previous one, which inadvertently introduced a new issue—popover menus always appearing at the bottom of an element. I resolved this by ensuring that popovers only behave this way on smaller screens, preserving the intended functionality.
Fixes: #29472 …

Popover menus: Fix disappearing popover on small screens.

---

web/styles/app_variables.css
web/styles/compose.css

These styles are no longer warranted, owing to:
* A scrolling button area for the compose buttons (and relative, em-based sizing of the compose buttons)
* Planned removal of the "Compact mode" toggle and a more robust info-density UI in #33831
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/Information.20density.3A.20dense_mode/near/2114485)
| Compose buttons below 400px, before | After (larger, but better target areas) |
| --- | --- |
| ![with-less-dense-mode-rule](https://github.com/user-attachments/assets/f13b4681-be9a-460b-ac54-d1aac9df3ba9) | ![removed-less-dense-mode-rule](https://github.com/user-attachments/assets/067101ce-f379-42c7-8488-c30f591945fa) |
| With `.more-dense-mode` rules | After (no change) |
| --- | --- | …

dense-modes: Clean up obsolete CSS related to .more-dense-mode, less-dense-mode.

---

web/src/composebox_typeahead.ts
web/src/topic_link_util.ts
web/tests/composebox_typeahead.test.cjs
web/tests/topic_link_util.test.cjs

In #30071, we generated fallback markdown link for channel or topic names which
would produce broken `#**channel>topic**` syntax. 
This broke the feature where after selecting a channel link (`#**channel**`), we could
open the topic list by typing `>`, or even the more recent #32217.
This PR restores those features.
Some part of #33013 is also taken.
Fixes: #32556 
<details>
</details>

Show topic list typeahead even when a fallback md link is generated.

---

puppet/zulip/manifests/app_frontend_base.pp

This is already installed on a lot of systems, and is used indirectly when upgrading Zulip from Git.

puppet: Add gettext to dependencies for app instances.

---

web/styles/zulip.css
web/templates/empty_feed_notice.hbs
web/tests/message_view.test.cjs

Previously, when searching for extremely long queries, they would overflow beyond the screen.
This PR fixes the bug by ensuring that long search queries do not overflow.
Fixes: #29568
Fixes: 
<details>
</details>

Prevent overflow of long search queries from the screen.

---

help/configure-call-provider.md
help/include/sidebar_index.md
help/start-a-call.md
templates/corporate/comparison_table_integrated.html
templates/zerver/integrations/big-blue-button.md
templates/zerver/integrations/jitsi.md
web/templates/settings/organization_settings_admin.hbs
zerver/openapi/zulip.yaml

@laurynmm Could you please finish this transition? I think we need to review these links, and update as needed. For configuring links, linking to the overall page rather than a subsection seems mostly fine, now that it just has a brief intro.
```
templates/zerver/integrations/big-blue-button.md:You're done! Zulip's [call button](/help/start-a-call) will now create
templates/zerver/integrations/big-blue-button.md:[video call provider]: /help/start-a-call#changing-your-organizations-video-call-provider
templates/zerver/integrations/jitsi.md:[jitsi-server-url]: /help/start-a-call#configure-a-self-hosted-instance-of-jitsi-meet
templates/zerver/integrations/zoom.md:box](/help/start-a-call).
templates/zerver/integrations/zoom.md:- [How to start a call](/help/start-a-call) …
```

help: Split out call provider config into separate page.

---

web/styles/compose.css

This PR makes some grid and flexbox improvements to the recipient row, and establishes a shared `normal` line-height on the stream button and topic input. While those do not follow the app's info-density settings, neither does the compose box itself.
I attempted yet again to replicate the low-res emoji issue in #31153, but was unable to do so. I have, however, presented screenshots below that suggest the emoji lines are undisturbed by the other improvements here.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20issues.20with.20topic.20box.20height/near/2113434)
_The crux of the issue here, with mismatched stream-picker and topic box heights, is easy to spot with an exaggerated line height (here, 300):_ …

compose: Improve recipient row and collapsed compose buttons.

---

web/styles/reactions.css

Initialy, both emoji search container and catalog were displayed which made popper position the popover for double the height than real. When search container was hidden `onMount`, the popover position was not updated which results in arrow being detached from the popover.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20triangle.20next.20to.20emoji.20button/with/2115620

emoji_popover: Fix arrow detached with the popover.

---

web/src/server_events_dispatch.js

This is a follow-up to #30425, addressing
https://github.com/zulip/zulip/pull/30425#discussion_r1882887744
Sorting is done using JavaScript's `Array#sort`.
<details>
</details>

server_events_dispatch: Sort array entries.

---

web/styles/settings.css

at 12px and 20px:
| --- | --- |
| ![Screen Shot 2025-03-05 at 16 52 09](https://github.com/user-attachments/assets/5590e78f-d68c-426d-83b7-2dc6c863d83e) | ![Screen Shot 2025-03-05 at 16 52 27](https://github.com/user-attachments/assets/75eb09c9-8f64-4b2b-81b0-89da9c00bc35) |
| ![Screen Shot 2025-03-05 at 16 51 47](https://github.com/user-attachments/assets/252336e1-b699-4073-980d-bb46e1550153) | ![Screen Shot 2025-03-05 at 16 52 42](https://github.com/user-attachments/assets/652abc76-bf3e-4888-8051-64b918ad5517) |
And for narrower screens the input shrinks:

settings: Adjust widths in change email modal with font size.

---

docs/overview/index.md
docs/overview/release-lifecycle.md
docs/overview/roadmap.md
docs/production/upgrade.md

To-dos:
- @laurynmm Could you please do a pass on links to the lifecycle page? I might have broken some anchor links, and it's possible some links to the overall page have a nice anchor to use now.
- @gnprice The mobile app roadmap section is a stub, but I think that's not a blocker for merging this.

docs: Clean up release lifecycle doc. 

---

web/styles/app_variables.css
web/styles/settings.css

[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20settings.20modal.20borders/near/2111930)
_The dark-mode settings list looks to be missing a border,
but that's just owing to the border color's similarity to the subheader._
| Dark, before | Dark, after |
| --- | --- |
| ![settings-list-dark-before](https://github.com/user-attachments/assets/c10477c3-41ef-485b-9821-46481c232a29) | ![settings-list-dark-after](https://github.com/user-attachments/assets/8e25bc74-bbe8-4ab3-b162-1f34b582f74e) |
| ![preferences-dark-before](https://github.com/user-attachments/assets/7e29516c-9011-4289-8b3e-dc70ff15b71a) | ![preferences-dark-after](https://github.com/user-attachments/assets/7d5d2f81-1880-4d5b-b6b4-d7e383883f60) |
| Light, before …

settings: Correct heights, borders for mobile scales.

---

web/styles/zulip.css

This improves icon alignment in the channel picker, both at very large line-heights and at smaller ones, too. 
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20channel-picker.20dropdown.20items.20alignment/near/2115328)
_There are some slight but not-uniform shifts at 122 line-height. Note that those are not uniform across all rows. Ideally, I think, post-10.0, we might look at getting a padlock icon that is sized and plays better with the globe and hash icons._
| --- | --- |
| ![channel-picker-200-before](https://github.com/user-attachments/assets/2cb6b355-c9c6-4942-9151-23439b951bd4) | ![channel-picker-200-after](https://github.com/user-attachments/assets/b54f2e92-dccf-499e-8c33-a247845a2584) |
| …

channel_picker: Better align privacy icons with shifting line height.

---

web/src/compose_tooltips.ts

Previously, the tooltip was triggered by the entire message controls row, which also contains the options button. This caused overlapping tooltips as the options button has its own tooltip.
This commit resolves the issue by applying the tooltip only to the send button.
Fixes: [CZO Discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/send.20button.20tooltip.20hangs.20around/with/2116318)
| -------- | ------- |
|![send_button_tooltip_before](https://github.com/user-attachments/assets/1f5de3da-8e11-408d-8da0-17ae3538a737) | ![send_button_tooltip_after](https://github.com/user-attachments/assets/c0f5d949-86cb-4126-bae8-003151277b79) |
<details> …

compose_tooltips: Fix send button tooltip

---

web/styles/rendered_markdown.css

Because older YouTube preview images behind Camo cannot be modified to request a larger image, this fix enables a larger thumbnail display for previously linked videos.
[CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/preview.20size.20on.20previously.20posted.20videos/near/2116085)
| Legacy thumbnails, before | Legacy thumbnails, after |
| --- | --- |
| ![legacy-youtube-before](https://github.com/user-attachments/assets/9d6d8847-ac74-4797-8efa-b06eacbf2e95) | ![legacy-youtube-after](https://github.com/user-attachments/assets/69dd70c9-995e-4427-9741-f9339c93b017) |
| New thumbnails, before | New thumbnails, after (no change) |
| --- | --- |
| ![new-youtube-before](https://github.com/user-attachments/assets/060c8bee-7d07-412c-bc92-44 …

rendered_markdown: Allow legacy YouTube thumbnails to size up.

---

web/styles/message_row.css

While I couldn't quite replicate the misalignment reported on CZO, the fixes here improve the size and layout of message-edit buttons generally--largely because this rids a hard-coded 28px height on the button areas, and allows them to grow with the flexbox containing the countdown timer.
[CZO issue](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/line.20height.20options/near/2115175)
_Showing 14px and 20px, both at an exaggerated 200 line-height (no change at 14px):_
| --- | --- |
| ![message-edit-14-200-before](https://github.com/user-attachments/assets/2a7675a3-0c47-4196-ab32-3efe406d7d6e) | ![message-edit-14-200-after-no-change](https://github.com/user-attachments/assets/c6ad4f49-9116-449e-8cf7-a62b1e59c359) |
| …

message_edit: Allow Save/Cancel buttons to properly size and flex.

---

web/styles/app_components.css
web/styles/app_variables.css
web/styles/recent_view.css

While motivated largely by sort icons appearing much higher than the text at large line heights, which this PR addresses, this also simplifies the display of sort icons, making absolute positioning unnecessary (and actually a detriment to vertical alignment).
One of the consequences of those changes is that this eliminates a hover shift, easily visible on the Custom emoji settings, on certain columns (in that case, the Authors column).
This also opens up the space for the unread-sort column in Recent conversations. Obviously the area is still in need of a design pass, but this gets us into a better state.
[CZO discussion](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/line.20height.20options/near/2116113)
| Recent conversations, …

tables: Fixes to sorting and alignment in Recent views and Settings.

---

web/styles/reactions.css
web/styles/settings.css

This makes some improvements to the settings UI and to the code behind app-wide presentation of emoji (though no changes are visible outside the settings UI).
[CZO discussion](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/line.20height.20options/near/2116113)
| --- | --- |
| ![emoji-settings-before](https://github.com/user-attachments/assets/5ca42085-b024-47cd-9b48-93fa0c2e46a1) | ![emoji-settings-after](https://github.com/user-attachments/assets/715bf889-c65e-41bc-b607-15d404761d40) |
| ![emoji-reactions-before](https://github.com/user-attachments/assets/bfb66eb8-9438-48f5-ad4e-7564f7ce9d43) | ![emoji-reactions-after](https://github.com/user-attachments/assets/7031cb2f-6d27-467f-bea8-474c181d4712) |
| …

emoji: Allow emoji space, including alt_code, to better scale.

---

docs/production/upload-backends.md
help/share-and-upload-files.md

Note: We don't currently hide the UI in mobile apps. @chrisbobbe is filing a Flutter app issue.
https://zulip.com/help/share-and-upload-files

help and docs: Document how to disable file uploads on a server.

---

web/src/filter.ts
web/src/unread_ops.ts
web/templates/confirm_dialog/confirm_mark_as_unread_from_here.hbs
web/tests/filter.test.cjs

Fixes #31292.
[CZO thread](https://chat.zulip.org/#narrow/stream/137-feedback/topic/unintentionally.20marking.20messages.20as.20unread/near/1638015)
Known number: (All Fetched)
- N < 50 - no confirmation dialog
- N >= 50 - confirmation dialog with the number of messages
Unknown number:
- N < 10 - no confirmation dialog
- N >= 10 - confirmation dialog with the minimum number of messages, rounded down to the nearest multiple of 25.
[Screen recording for the known number cases](https://github.com/user-attachments/assets/dcdf611d-0d6b-4538-b779-193df443ef4e)
[Screen recording for the unknown number confirmation dialog](https://github.com/user-attachments/assets/eaff8556-93d1-4c9a-a000-7eaf9eda3a60)
Screenshot for the unknown number case (and its threshold) …

unread_ops: Add confirm_dialog to bulk mark unread in interleaved views.

---

web/styles/subscriptions.css

It didn't seem to preserve the way things look at 14px, but I also think it looks fine in the after screenshots. I can come back to this with more care or tweaks if the after screenshots don't look good enough.
----
channel settings at 12px, 14px, 16px, 20px:
| --- | --- |
| ![Screen Shot 2025-03-05 at 15 05 35](https://github.com/user-attachments/assets/8289cca0-9b91-42c1-be24-a9facfc9a6bc) | ![Screen Shot 2025-03-06 at 11 37 20](https://github.com/user-attachments/assets/c67186c7-d9ac-4f1f-b206-ed6830c17838) |
| ![Screen Shot 2025-03-05 at 15 05 25](https://github.com/user-attachments/assets/f809e458-77eb-431f-bdc0-2286525aee5d) | ![Screen Shot 2025-03-06 at 11 37 33](https://github.com/user-attachments/assets/69d3621c-4def-424f-a444-0e8a40279385) |
| ![Screen Shot …

settings: Standardize right panel button height for streams/usergroups.

---

web/styles/right_sidebar.css
web/templates/right_sidebar.hbs

Discussion here:
https://chat.zulip.org/#narrow/channel/101-design/topic/right.20sidebar.20design.20tweaks.20.20.2332976/near/2115335
All screenshots at 16px. I can share them at other font sizes if that's desired. I did do some manual testing at other font sizes.
**Generic screenshot**
| avatars |  no avatars |
| ---- | --- |
| <img width="267" alt="image" src="https://github.com/user-attachments/assets/b0083959-1bae-4310-a1e5-dfdb8ee81621" /> |  <img width="270" alt="image" src="https://github.com/user-attachments/assets/47851855-d517-48ac-b0cb-a1dc8620bbf2" /> |
**No headers**
| avatars |  no avatars |
| ---- | --- |
| <img width="265" alt="image" src="https://github.com/user-attachments/assets/5a924c7a-ba68-48ee-a5bd-8612aa9d850c" /> |  <img width="273" alt="image" …

right_sidebar: Remove invite users icon at bottom of buddy list.

---

templates/zerver/app/index.html
tools/test-js-with-node
web/src/buttons.ts
web/src/message_fetch.ts
web/src/popup_banners.ts
web/src/server_events.js
web/src/ui_init.js
web/styles/alerts.css
web/styles/app_variables.css
web/styles/banners.css
web/styles/buttons.css
web/styles/zulip.css
web/tests/server_events.test.cjs

This PR serves as the base commit for the Popup banners and redesigns the connection error banner.
Fixes: #31282
| ![Screenshot 2025-03-05 at 12 31 53 PM](https://github.com/user-attachments/assets/3e507a03-b36e-4165-b2a2-794e1a22a8aa) | ![Screenshot 2025-03-05 at 12 21 28 PM](https://github.com/user-attachments/assets/ffeb5199-a92a-4a5b-aa12-cac2aeddcae7) | 
| ![Screenshot 2025-03-05 at 12 32 11 PM](https://github.com/user-attachments/assets/575280ad-e8f9-41ae-9138-463266b1ca35) | ![Screenshot 2025-03-05 at 12 20 57 PM](https://github.com/user-attachments/assets/708ee2d7-a49c-4575-b398-a9459667ce8a) | 
**Animation and stacking order:**
https://github.com/user-attachments/assets/bcceba43-126c-44b5-8d24-f2bf86dcdaf9 …

popup_banners: Redesign connection error banner.

---

zerver/models/realms.py

This isn't a configuration that's useful, and it seems marginally helpful to make it hard to end up in a state where this is the empty set.

realms: Require a non-empty set of users who can manage billing.

---

web/src/user_group_edit.ts
web/styles/subscriptions.css
web/templates/user_group_settings/user_group_settings.hbs

This PR adds a banner to make it super clear when a group is deactivated. Banner details:
- Color: yellow
- Text: This group is deactivated. It can't be mentioned or used for any permissions.
this also disables the 'Permissions' tab for the deactivated groups.
fixes: #33803.
| Dark Theme | Light Theme |
| --- | --- |
| ![Dark Theme](https://github.com/user-attachments/assets/2cef88fc-1cef-4fcd-a7ea-d03bffb20212) | ![After Image](https://github.com/user-attachments/assets/dd6b07fa-6e83-4f8f-90e2-eeced7778727) |
<details> …

user_groups: Add banner to make it clear when a group is deactivated.

---

web/src/user_group_components.ts
web/src/user_group_edit.ts
web/styles/subscriptions.css
web/templates/user_group_settings/user_group_settings.hbs
web/templates/user_group_settings/user_group_settings_overlay.hbs

prerequisite: #33812
Commit 1: Removes the ban icon from the group setting section.
Commit 2: Adds the ban icon to the top next to `#user_group_settings_title`
Commit 3: Ensures  `#user_group_settings_title` is visible for smaller widths.
| small width (active group) | small width (deactivated group) | 
|-----|-------|
|![image](https://github.com/user-attachments/assets/dd31b790-9042-4323-b704-b395e4b633d3)|![image](https://github.com/user-attachments/assets/89244902-8d78-451e-bde6-8bf32b2b32b2)|

user_groups: Remove fa-ban icon for deactivated group settings.

---

zerver/lib/export.py
zerver/lib/import_realm.py
zerver/tests/test_import_export.py

Commit 1) Export of mirror dummy users, as rare as it might be, was broken. Their related objects were not exported at all, resulting in missing objects such as `UserPresence` and, in particular, `Recipient` - meaning `user_profile.recipient` was `None` for them after importing - making these `UserProfile`s broken.
Commit 2) The export/import code for `SavedSnippet` was incomplete.
Detailed explanation in commit messages.

Fix export of mirror dummy users and SavedSnippet

---

web/src/left_sidebar_navigation_area.ts
web/styles/left_sidebar.css
web/tests/left_sidebar_navigation_area.test.cjs

This PR hides sidebar menu option button instead of showing it with "Mark all messages as read" option, for home view when there are no unread messages.
related [czo](https://chat.zulip.org/#narrow/channel/101-design/topic/When.20to.20show.20Mark.20all.20messages.20as.20unread.20on.20channel.20popover)
| Before     | ![Changes visible in alignment and hover](https://github.com/user-attachments/assets/1ed0fee9-0519-4a03-8e16-1268da48312b)    |
| After  | ![dm](https://github.com/user-attachments/assets/3adb4630-3b40-49a4-af89-b7fdc451d402) |
<details>
<summary>light theme</summary>
| …

left_sidebar: Hide menu option for home view if all messages are read.

---

web/styles/compose.css

This restores the original design for the DM picker, so that it does not grow alongside a multi-line DM pill recipient container.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20channel.20picker.20dropdown.20stretches.20in.20DMs/near/2118202)
| Before | After (no change on single-line DM) |
| --- | --- |
| ![dm-picker-single-line-before](https://github.com/user-attachments/assets/709bde53-857f-4d4a-8126-2d8c97b1a9cf) | ![dm-picker-single-line-after](https://github.com/user-attachments/assets/15389f94-e930-46e2-8f6f-6f2cd873d023) |
| ![dm-picker-multi-line-before](https://github.com/user-attachments/assets/2a4f335b-7a8b-4ed7-86a4-5ead08304ca1) | ![dm-picker-multi-line-after](https://github.com/user-attachments/assets/6a24 …

compose: Hold DM picker, topic marker to top recipient line.

---

web/src/settings_bots.ts

This PR changes the default selected option in the bot type dropdown to "Incoming webhook" when creating a new bot. The order of options in the dropdown remains unchanged.
Fixes: #33740
**Modification details:**
- Modified `web/src/settings_bots.ts` to set the default bot type 
- Added `$("#create_bot_type").val(INCOMING_WEBHOOK_BOT_TYPE);` in the form initialization
- Implemented the change in TypeScript rather than template markup
https://github.com/user-attachments/assets/7ffb4d6a-327b-4b1f-a1fe-1e606b59e671
<details> …

Settings: Make 'Incoming webhook' the default bot type 

---

web/src/message_edit.ts
web/styles/zulip.css
web/templates/recipient_row.hbs

This commit also changes the width of the spinner so that the resolve icon and spinner take up the same width.
| --- | --- |
| ![Screen Shot 2025-03-10 at 15 03 38](https://github.com/user-attachments/assets/210f1bab-3c28-451c-81ea-be4b1e3be7d0) | ![Screen Shot 2025-03-10 at 14 57 41](https://github.com/user-attachments/assets/8b576753-bb3b-4341-b0f3-b12573b6d3c9) |
| ![Screen Shot 2025-03-10 at 15 03 32](https://github.com/user-attachments/assets/58d31055-e35c-410a-a9df-4892d80d6a5c) | ![Screen Shot 2025-03-10 at 14 57 35](https://github.com/user-attachments/assets/d4fc423f-13ea-46a6-882a-4a63ba5f0966) |
| ![Screen Shot 2025-03-10 at 15 03 27](https://github.com/user-attachments/assets/ac741e58-7f95-4c9f-b1ae-4878625accbe) | ![Screen Shot …

message_edit: Scale resolve topic spinner with font size.

---

web/src/compose_paste.ts
web/tests/compose_paste.test.cjs

compose_paste: Remove title formatting more carefully.
Refines within_single_html to consider nodes
with textContent.
Fixes: #31218.

compose_paste: Remove title formatting carefully

---

web/src/compose_actions.ts

Reproducer:
* Upload a file.
* Close compose box before upload is finished.
* Open compose box.
Send message button is disabled without any error in this state. Fixed by resetting the send button state when compose box is closed.

compose_actions: Fix send button disabled without any error.

---

web/templates/settings/organization_permissions_admin.hbs

This PR adds a help (`?`) link next to the "Who can manage plans and billing" setting.
Fixes : [#33922](https://github.com/zulip/zulip/issues/33922)
- Displays a help link based on the hosting type:
- **Zulip Cloud orgs**: Links to `/help/zulip-cloud-billing`
- **Self-hosted orgs**: Links to `/help/self-hosted-billing`
- Uses `{{#if is_plan_self_hosted}}` to determine the correct link.
This improves user accessibility by providing direct documentation links.
- Verified that the correct link appears for both **cloud** and **self-hosted** deployments.
- Manually tested UI behavior.
Let me know if any changes are needed! 🚀
<details> …

settings: Add help link to who can manage plans and billing.

---

web/tests/compose_paste.test.cjs

For context, https://github.com/zulip/zulip/issues/33569 appears to have been fixed
unintentionally by https://github.com/zulip/zulip/pull/33691.
This just adds a test to verify the expected
behavior when it comes to pasting from the
Mac terminal as described by the reproduction
steps in https://github.com/zulip/zulip/issues/33569.
We might still end up with some edge case in
the future, that might not work as expected.
CZO: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20surprising.20line.20breaks.20when.20copy-pasting.20.2333569/near/2119422
Co-authored-by: Kislay Verma <kislayuv27@gmail.com>
Fixes: #33569

compose_paste: Add test to verify pasting from Mac.

---

web/src/dropdown_widget.ts
web/styles/zulip.css
web/templates/dropdown_list.hbs

Previously, the dropdown had a bug where the first item was highlighted regardless of the selected option.
This PR fixes the bug, ensuring that the
selected option is now correctly highlighted.
[Screencast from 2025-01-19 23-09-02.webm](https://github.com/user-attachments/assets/c381081e-86c3-415a-809c-80a127e59a32)
<table>
<tr>
<th>
Open with keyboard
</th>
<th>
Open with mouse
</th>
</tr>
<tr>
<td>
[Screencast from 2025-01-29 00-26-36.webm](https://github.com/user-attachments/assets/08ce953e-edf2-4000-acf9-eba4d0e1915f)
</td>
<td>
[Screencast from 2025-02-02 01-00-38.webm](https://github.com/user-attachments/assets/b60d43b5-7665-4164-89f9-73b914727bf2)
</td>
</tr>
</table>
Fixes: #33066
<details> …

Improve dropdown select highlighting in inbox/conversation selection menu.

---

web/styles/modal.css

This PR fixes the modal for conifguring domains for emails by overwriting the width of modal_text_input of `add-realm-domain-widget`.
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Allowed.20domains.20modal).
| Before | After (at 12 px) | After (at 16 px) | After (at 20 px) |
|--------|--------|--------|--------|
| <img width="606" alt="Screenshot 2025-03-11 at 10 46 21 PM" src="https://github.com/user-attachments/assets/e8d3c22f-ebd5-44e0-997a-61cd8a1dcc9b" /> | <img width="456" alt="Screenshot 2025-03-11 at 10 37 35 PM" src="https://github.com/user-attachments/assets/454a9080-bcb0-4e54-b5ba-269a22976ffe" /> | <img width="598" alt="Screenshot 2025-03-11 at 10 37 54 PM" …

domains_modal: Fix width of modal_text_input.

---

web/styles/recent_view.css

This adds an em-based `min-width` to the unread header to prevent the sort icon from annoyingly shifting to its own line at certain viewport widths.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/arrow.20on.20hovering.20unread.20message.20icon.20in.20recent.20conversation/near/2119072)
| --- | --- |
| ![unread-header-before](https://github.com/user-attachments/assets/e59839cd-f98d-4d04-81ab-d81668ad884f) | ![unread-header-after](https://github.com/user-attachments/assets/1dc2397b-c477-4b28-85ad-d667421f1c6d) |
<details> …

recent_view: Hold unread header to a minimum width.

---

web/styles/rendered_markdown.css

This PR more precisely positions the play button, avoiding a fast but ultimately sub-pixel-error-prone use of `height: 100%` and `width: 100%` coupled with background-image centering.
It seems this bug only reproduced on videos at certain sizes/aspect ratios, which is likely why the bug did not reproduce uniformly in Brave or the Chrome Desktop app. A [problem video from CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/arrow.20on.20hovering.20unread.20message.20icon.20in.20recent.20conversation/near/2119072) made for easy replication of the bug in dev. Outside the hover state, at 16px/1em, the `::after` area reported itself as 153.6px × 102.4px; by huge contrast, in the hover state, it reported its area as 192px × 128px. It seems all but certain that the subpixel sizing in that …

video_thumbnails: Precisely size, place play button.

---

web/styles/message_row.css

Rather than setting `height: 100%`, we set an em-based height that always matches the height of the Send button in the compose box. Flexbox in the area continues to do its job maintaining the height and alignment of other elements.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/Reduced.20height.20of.20Save.20button.20in.20message.20edit.20box.2E/near/2119699)
_At minimum, default, and maximum font size/line height values:_
| --- | --- |
| ![message-edit-min-before](https://github.com/user-attachments/assets/1e2583fe-12a2-486e-b647-3cc85b4ef9d9) | ![message-edit-min-after](https://github.com/user-attachments/assets/2a605c88-b5b6-4792-8a94-e754627c33c3) |
| ![message-edit-default-before](https://github.com/user-attach …

message_edit: Match button height to compose Send button.

---

scripts/lib/check_rabbitmq_queue.py

c5200e8b05b2 switched `digest_emails` from sending emails by inserting into the ScheduledEmail table, and being processed later by `deliver_scheduled_emails`, to inserting into the
`deferred_email_senders` RabbitMQ queue.  This moved it from being in an unmonitored table, to a monitored queue.
This slightly improved throughput -- but began paging, since the backlog was now in a monitored form.  Increase the paging thresholds to not page for expected behaviour.
<details> …

check_rabbitmq_queue: Increase deferred_email_senders paging thresholds.

---

web/src/settings_org.ts
web/src/stream_edit.ts
web/src/user_group_edit.ts
web/tests/settings_org.test.cjs

Currently, if we click on `Save Changes` button, it proceeds through the following steps:
1. It shows `Save Changes` text with `data-status="unsaved"`.
2. When we click on it, the text becomes `Saving` with `data-status="saving"`.
3. Then, it shows `Saved` with `data-status="saved"`.
4. Just after this, for a fraction of second, it again shows `Save Changes` with `data-status="unsaved"`.
Now, if the network is slow , we can get an error message on clicking over the button **at every step** as it again tries to call the API and the change has already been taken place.
In this PR, i'm changing the target of the on click event, hence the possibility of errors gets eliminated except for the **`Step 4`** i.e, by again clicking over the `Save changes` button that shows for a fraction of …

Make saving indicator not clickable while saving.

---

web/styles/compose.css

Channels with long names take up too much room on the recipient row. This improves the layout descriptions and width constraints in the area to fix the display of long channels, while leaving shorter channel names undisturbed.
CZO discussion
| Before | After (no change for `#test` channel) |
| --- | --- |
| ![long-channel-before](https://github.com/user-attachments/assets/7a5d9a93-6c02-486a-bc10-26e3d22fb63a) | ![long-channel-after](https://github.com/user-attachments/assets/b3311352-3c75-4e40-93f2-32e08b1cf1f4) |
| ![short-channel-before](https://github.com/user-attachments/assets/d4497b47-f30e-4868-a9db-98997a2c8f62) | ![short-channel-after-no-change](https://github.com/user-attachments/assets/754c2140-c60f-44e7-b6ba-b73ea7d3759e) |
<details> …

compose: Refine the space occupied by the channel.

---

web/e2e-tests/realm-linkifier.test.ts
web/src/add_subscribers_pill.ts
web/src/banners.ts
web/src/navbar_alerts.ts
web/src/popup_banners.ts
web/src/portico/showroom.ts
web/src/settings_org.ts
web/src/stream_ui_updates.ts
web/src/user_group_edit.ts
web/templates/components/action_button.hbs
web/templates/dialog_change_password.hbs
web/templates/settings/account_settings.hbs
web/templates/settings/admin_realm_domains_list.hbs
web/templates/settings/alert_word_settings.hbs
web/templates/settings/bot_settings.hbs
web/templates/settings/data_exports_admin.hbs
web/templates/settings/default_streams_list_admin.hbs
web/templates/settings/emoji_settings_admin.hbs
web/templates/settings/linkifier_settings_admin.hbs
web/templates/settings/organization_profile_admin.hbs
web/templates/settings/playground_settings_admin.hbs
web/templates/settings/profile_field_settings_admin.hbs
web/templates/settings/profile_settings.hbs
web/templates/settings/realm_domains_modal.hbs
web/templates/stream_settings/add_subscribers_form.hbs
web/templates/stream_settings/stream_creation_form.hbs
web/templates/topic_edit_form.hbs
web/templates/user_group_settings/add_members_form.hbs
web/templates/user_group_settings/new_user_group_users.hbs
web/templates/user_group_settings/user_group_creation_form.hbs

Commit 1:
>Previously, we were using **type** to describe the **attention** level of the
>action button. We want to rename the type parameter to attention
>as we need the type parameter separately for describing the type of
>button.(suggested by @sayamsamal )
Commit 2:
>Restyle all the remaining `sea-green` button of organization settings including the ones in the table header.
Commit 3
>Restyle all the `sea-green` button of channel and group settings.
>Also, restyled `cancel` button to match the current UI.
Fixes part of #33130.
**Commit 2**
| **Location**           | **Before(at 16 px)** | **After (At 12px)** | **After (At 16px)** | **After (At 20px)** |
|------------------------|-----------|--------------------|--------------------|------------------ …

Restyle buttons in settings.

---

web/src/user_profile.ts
web/templates/settings/admin_human_form.hbs

Since only owners can deactivate other owners, we hide Deactivate button on owners profile when admins are using the ui.
fixes: #33910.
| --- | --- |
| ![Before Image](https://github.com/user-attachments/assets/704bbe48-8f6f-46ac-9e21-44c222b4de6b) | ![After Image](https://github.com/user-attachments/assets/753935f7-e482-493c-afcb-ba274b0e1340) |
<details>
</details>

settings: Hide deactivate button of owner for admins.

---

web/src/stream_settings_data.ts
web/tests/stream_data.test.cjs

Selecting an archived stream from the announcement dropdown widgets caused an error because we are not allowed to send messages in archived streams. With this PR, we exclude the archived stream from rendering in the dropdown.
> **NOTE**: Archived "devel" named channel to demonstrate the changes.
<details>
</details>

Exclude archived streams from notification_stream_options.

---

api_docs/changelog.md
version.py
web/src/message_edit_history.ts
web/src/message_events.ts
web/src/message_list_tooltips.ts
web/src/message_list_view.ts
web/src/message_store.ts
web/src/server_message.ts
web/templates/edited_notice.hbs
web/templates/message_edit_notice_tooltip.hbs
web/tests/message_list_view.test.cjs
zerver/lib/message.py
zerver/openapi/zulip.yaml
zerver/tests/test_message_edit.py
zerver/tests/test_message_move_topic.py

This will allow clients to display MOVED/EDITED indicators, and their tooltips, without interacting with the `edit_history` section of message objects, which we plan to remove in the future.
Supporting that requires both introducing both last_moved_timestamp, and changing the definition of last_edit_timestamp to not include message moves, which involves recalculating it at the API layer.

message_edit: Add last_moved_timestamp.

---

api_docs/changelog.md
api_docs/construct-narrow.md
help/search-for-messages.md
version.py
web/src/filter.ts
web/src/narrow_banner.ts
web/src/search_suggestion.ts
web/templates/search_description.hbs
web/templates/search_operators.hbs
web/tests/filter.test.cjs
web/tests/message_view.test.cjs
web/tests/search_suggestion.test.cjs
zerver/lib/narrow.py
zerver/tests/test_message_fetch.py

1st commit fixes the issues existing with `-in:home` search operator.
Previously, mentions from muted channels were incorrectly excluded when narrowed down to `-in:home`. Additionally, messages from all muted topics were missing in the results.
This commit solves the above listed issues.
2nd commit adds `-is:muted` as an alias of `in:home`.
Referenced PR: #31077.
Fixes: #16943.
Search suggestions
Help menu
<details> …

search: Add is-muted search operator. 

---

web/styles/rendered_markdown.css

This PR is motivated by code-span text that appears to sink below the baseline on certain displays (most reliably, the desktop app on an external monitor). Note in the screenshots below, however, that the adjustment in this PR does not seem to uniformly change baselines everywhere--though it does appear to improve text that is most obviously below the baseline.
CZO discussion
_At 20px font-size, 1.4 line-height:_
| Desktop app, before | Desktop app, after |
| --- | --- |
| ![desktop-app-before](https://github.com/user-attachments/assets/d804513c-798a-472f-b59b-bfc02f06c292) | ![desktop-app-after](https://github.com/user-attachments/assets/f800b3a1-bdc7-4318-bed1-464d03e3bb46) |
| Firefox, before | After (no baseline shift apparent) |
| --- | --- |
| …

rendered_markdown: Scale code-span padding with font size.

---

web/src/message_list_hover.ts

That `span.edit_content` does not exist in the DOM (`edit_content` is a class on a `<div>`, not a `<span>`) may well be part of why we've continued to see reflow errors under certain conditions.
Whether this fixes that or not, clearly we're trying to find and empty a non-existent element here.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.E2.9D.93messages.20reflowing.20after.20local.20echo/near/2120105)
<details> …

message_hover: Correct for non-existant span selector.

---

help/include/mute-unmute-intro.md
help/search-for-messages.md
web/templates/search_operators.hbs

Messages in muted channels may not be muted, so the documentation was previously not quite accurate.

help: Document is:muted search filter better.

---

web/styles/search.css

Users' names were being cut off.
before (bottom of g is cropped off):
after:

search: Increase line height for user pills.

---

web/src/settings_account.ts
web/src/settings_ui.ts
web/styles/app_components.css
web/styles/settings.css

Most instance of `loading_indicator_text` in settings are actually overwritten by a style for `.alert-notification .loading_indicator_text` font size inherit, but I found one case where that wasn't true and took screenshots there.
If I were more confident this was the only place the font size wasn't being overridden, I'd make the CSS rule more specific to only apply to this case.
---
| --- | --- |
| ![Screen Shot 2025-03-05 at 16 44 26](https://github.com/user-attachments/assets/4bf3dd9d-60fa-4871-866c-cbcdb66d57a5) | ![Screen Shot 2025-03-05 at 16 36 39](https://github.com/user-attachments/assets/4053574c-859b-4afa-ac7a-28b897515fec) |
| ![Screen Shot 2025-03-05 at 16 44 17](https://github.com/user-attachments/assets/c32a3a01-2a42-4ab5-b20c-4c …

settings: Scale save loading spinner with font size.

---

help/configure-default-new-user-settings.md
help/dark-theme.md
help/font-size.md
help/include/sidebar_index.md
help/line-spacing.md

Blocked on:
- #33831
Note that this should be tested with the new icons; I'm not totally sure if I used them correctly.
Current: https://zulip.com/help/font-size
<details>
<summary>
Updated (based on planned changes in #33953)
</summary>
</details>
<details>
<summary>
New line spacing page
</summary>
</details>

help: Document new font size and line spacing options.

---

web/src/composebox_typeahead.ts
web/src/people.ts
web/tests/composebox_typeahead.test.cjs

Fixes: #30817
Just fixes some tests and conflicts for #31321

composebox_typeahead: Show CrossRealmBots in the typeahead list.

---

web/styles/app_components.css
web/styles/zulip.css

This PR isolates changes originally from #33889 so as to only affect their intended dropdown, the channel picker.
Additionally, it improves icon-alignment on multi-line channels (single line channels are slightly improved too, especially private channels marked by the lock icon).
CZO issues:
* [#issues > 🎯 misaligned dropdown menu in "Recent conversations" @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20misaligned.20dropdown.20menu.20in.20.22Recent.20conversations.22/near/2118152)
* [#issues > 🎯 channel-picker dropdown items alignment @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20channel-picker.20dropdown.20items.20alignment/near/2118057)
| Non-channel-picker widgets, before | After |
| --- | --- | …

Recipient dropdown isolation

---

web/src/information_density.ts

Previously, the tooltips for information density buttons incorrectly used "pt" as the font size postfix, while the actual unit being used is "px":
Since points (pt) and pixels (px) are different units (px ≠ px), this commit updates the tooltips to display the correct one.
*Screenshots:*
|-------- | -------- |
| ![image](https://github.com/user-attachments/assets/5e9cb90c-380d-4306-8599-46a025c7cb75) | ![image](https://github.com/user-attachments/assets/3d779772-4dd3-4880-b572-edb3620aac9f) |
|-------- | -------- |
| ![image](https://github.com/user-attachments/assets/16a2e4ec-f31d-4ba5-b700-0b5e2645d109) | ![image](https://github.com/user-attachments/assets/12cf7568-920f-4c7d-aeae-01604ba347fe) |
|-------- | -------- |
| …

information_density: Update tooltip text to show correct unit

---

api_docs/changelog.md
api_docs/include/rest-endpoints.md
version.py
web/src/saved_snippets.ts
web/src/saved_snippets_ui.ts
web/src/server_events_dispatch.js
web/src/tippyjs.ts
web/styles/compose.css
web/styles/zulip.css
web/templates/dropdown_list.hbs
web/templates/edit_saved_snippet_modal.hbs
web/tests/dispatch.test.cjs
web/tests/lib/events.cjs
web/tests/saved_snippets.test.cjs
zerver/actions/saved_snippets.py
zerver/lib/event_schema.py
zerver/lib/event_types.py
zerver/lib/events.py
zerver/openapi/python_examples.py
zerver/openapi/zulip.yaml
zerver/tests/test_events.py
zerver/tests/test_saved_snippets.py
zerver/views/saved_snippets.py
zproject/urls.py

<p>
| state | dark | light |
| without hover | ![Screenshot 2025-03-13 145415](https://github.com/user-attachments/assets/ab73d5c3-ad3a-4f02-a481-8383c24cdee5) | ![Screenshot 2025-03-13 145517](https://github.com/user-attachments/assets/fbb58ee7-1d56-4f3d-9422-48722bc4871e) |
| hover | ![Screenshot 2025-03-13 145424](https://github.com/user-attachments/assets/95347883-fd5a-4a70-ac72-ba8318400060) | ![Screenshot 2025-03-13 145527](https://github.com/user-attachments/assets/f5ec4b99-acad-4060-bd62-4b9c2560cbef) | 
</p>
</details> 
Fixes #33708.
<details> …

saved_snippets: Add support for editing saved snippets.

---

web/src/gear_menu.ts
web/src/personal_menu_popover.ts
web/src/popover_menus.ts

When changing font size using controls in personal menu popover and gear menu popover for spectators, font size of popover is not change so that buttons do not shift.
Also, arrow shown with the popover is removed once font-size is changed, as popover will be detached from the element which was clicked to open it.
[Discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/information.20density.20UI.20for.2010.2E0/near/2120997)
<details> …

popovers: Keep font size of popover constant once it is opened.

---

web/src/filter.ts
web/src/search.ts
web/tests/filter.test.cjs

Fixes #31315.
We want to parse sender:me with the email when turning it into a pill, but not before then so that "Sent by me" is still the search string in the suggestions.

filter: Validate and parse sender:me when turning into a pill.

---

web/styles/message_row.css
web/styles/rendered_markdown.css

This PR makes some very minor but significant adjustments to message-box spacing to better tolerate top-row alignment of EDITED/MOVED markers, action icons, and timestamps even when the message box opens with non-paragraph content (that is, elements other than paragraphs and ordered/unordered lists).
Note that in fixing the alignment issues here, the focus ring does appear visually closer to the top of especially heading one and heading two elements. However, it maintains a uniform space from the action icons and other materials, presenting a more uniform look overall.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20message.20action.20buttons.20misaligned.20w.2F.20header.20in.20first.20line/with/2113656)
_Showing both …

message_view: Better tolerate different opening Markdown elements.

---

web/src/compose_banner.ts
web/src/compose_validate.ts
web/src/composebox_typeahead.ts
web/src/ui_init.js
web/templates/compose_banner/compose_mention_group_warning.hbs
web/tests/composebox_typeahead.test.cjs

Added a warning banner when a user mentions a group (non-silent) where none of the members are subscribed to the current stream. The banner informs the user that the mention won't notify anyone.
Further on clicking on the group name opens up group card.
Fixes #33545.
<details>
</details>

mentions: Warn on non-silent group mentions with unsubscribed members.

---

web/src/message_edit.ts
web/styles/zulip.css
web/templates/topic_edit_form.hbs

This PR consists of two commits:
- **Commit 1**: Update save button to neutral + quiet button style.
- **Commit 2**: Adds a hidden topic_value_mirror span element, and uses that to dynamically set the width of the input field to the width of the topic text inside it + some cushion.
Fixes: #33844.
**No input - Placeholder text**
**No input - Placeholder text in non-English**
**Responsive inline topic edit input**
<details> …

Tweak inline topic editing UI

---

web/styles/message_row.css

The bug occurred because clicking on .message-editing-animation was not triggering the click on .edit-notifications. This commit sets the height of .message-editing-animation from 5px to 0, which resolves this bug.
Fixes: #33950
<details>
</details>

message_editing: Fix unclickable area in bouncing "..."

---

web/src/banners.ts
web/src/message_fetch.ts
web/src/message_view.ts
web/src/popup_banners.ts

I think this should mostly work but might still require some tweaks after some broader testing.
Tested by setting `MAX_UNREAD_MESSAGES` to `10` and reducing `message_fetch.consts` to single digits.

Improve experience for when `old_unreads_missing` and navigating to first unread.

---

web/styles/compose.css
web/styles/message_row.css

discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20incorrect.20hover.20behavior.20on.20.22send.22.20button/with/2122914
Order of button state in screenshots is:
Normal
Hover 
Focus
| --- | --- |
| ![Screenshot 2025-03-14 074724](https://github.com/user-attachments/assets/539c5323-d7a6-47af-88ec-e56325700c7a) | ![Screenshot 2025-03-14 074320](https://github.com/user-attachments/assets/3e61ec09-3dfc-491c-ac4f-3b0b56059efa) |
| ![Screenshot 2025-03-14 074701](https://github.com/user-attachments/assets/52507b93-babe-44cc-bcd5-e3242723e9f2) | ![Screenshot 2025-03-14 074344](https://github.com/user-attachments/assets/c40d11a0-601f-4eff-bdd8-b2a440e2884b) |
| ![Screenshot 2025-03-14 074748](https://github.com/user-attachments/assets/11f2140f-5e9b-4 …

compose: Use standard primary button colors for compose send button.

---

web/src/hotkey.js

Fixes a bug introduced in 96eb49d / #33697, which broke the hotkey for custom emoji.

hotkey: Fix upvote first emoji shortcut for custom emoji.

---

templates/zerver/app/index.html
web/src/alert_popup.ts
web/styles/alerts.css

This PR restructures the alerts area so that the `.banner-wrapper` appears inside the `.alert-box` class--similar to existing structures in `#navbar-fixed-container`. This avoids the Safari bug with `container:` interfering with `position: fixed` and the like.
Additionally, this makes some necessary style and behavior improvements to allow `.alert-box` to continue to be shared with the portico.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/Safari.20keyboard.20nav.20not.20scrolling.20to.20unread/near/2121123)
| Safari `n` behavior, before | Safari `n` behavior, after |
| --- | --- |
| ![safari-n-behavior-before](https://github.com/user-attachments/assets/bfe9d58c-3304-4b2b-9a2f-bb54ac24b129) | …

alerts: Correct for Safari container regression.

---

web/styles/message_row.css

When viewing messages near date separators at certain zoom levels (60-90%),
the message focus ring was getting clipped at the bottom. This removes the
background-color from .date_row which prevents the visual clipping.
This fix follows the same approach used in [#25806](https://github.com/zulip/zulip/pull/25806) for a similar issue,
where removing the background color allows the focus ring to properly render
beyond container boundaries without being cut off by rendering boundaries.
Fixes: [Message focus box is cut off at the bottom. #33571](https://github.com/zulip/zulip/issues/33571) 
| **Before** | **After** |
|------------|----------|
| ![Screenshot 2025-03-14 131023](https://github.com/user-attachments/assets/adbb8f22-aeb0-4057-9e0e-ec4ede1ba7df) | …

message_row: Fix message focus ring cutoff near date headers.

---

web/styles/message_row.css
web/templates/message_edit_form.hbs

This PR sets a 28px height on action buttons (Save, Cancel, and Close), and also sets a minimum width based on the English Cancel button at 16px.
Additionally, a focus ring is only shown on `:focus-visible`, preventing the flash of a ring when clicking any of these buttons.
Finally, this corrects for unwanted bottom margin on the edit form that was being inherited from Boostrap 💀
CZO issues:
* [#redesign project > 🎯 "save" / "cancel" buttons for message editing @ 💬](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/.F0.9F.8E.AF.20.22save.22.20.2F.20.22cancel.22.20buttons.20for.20message.20editing/near/2122825)
* [#issues > 🎯 close button height @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20close.20button.20height/near/2123546) …

action_buttons: Correct to Vlad's specifications.

---

docs/production/system-configuration.md
puppet/zulip/manifests/app_frontend_base.pp
puppet/zulip/templates/supervisor/zulip.conf.template.erb
scripts/nagios/check-rabbitmq-consumers

This generalizes from thumbnail_workers, to include any other queue. We only additionally choose to document `email_senders_workers`, however, since other queues are not guaranteed to work correctly with multiple consumers.
<details>
</details>

puppet: Allow for arbitrary queues to have more than one worker.

---

web/src/message_edit_history.ts
web/templates/message_edit_history.hbs
web/templates/message_history_overlay.hbs

When an organization has restricted viewing message history to only moves, we want to make sure the message history overlay is consistent with that setting in the web app.
**Updates**:
- When viewing any change that altered both the channel and topic of the message, we now show the channel change before the topic change. See screenshots for edit and move history to see this one change.
- If only move history can be viewed, the overlay's header is now "MESSAGE MOVE HISTORY".
- If only move history can be viewed, instead of showing the original message content at the top, we now show the original channel and topic.
**Questions**:
- For the original channel and topic entry, I thought it looked best with the green highlighting. We could also not have any highlighting on those. See final …

message-edit-history: Update web app overlay for showing move history only.

---

web/src/settings_users.ts
web/src/user_events.ts

Previously, deactivating a bot from the bots tab without loading
the users tab caused a blueslip error because update_view_on_deactivate
tried to render uninitialized role dropdowns from a realm_user event.
This PR fixes this by passing is_bot to update_view functions
and only rendering dropdowns for non-bots if they’re initialized.
Fixes: [#issues > 🎯 Role count not updating in user and deactivated user l... @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Role.20count.20not.20updating.20in.20user.20and.20deactivated.20user.20l.2E.2E.2E/near/2122277)
<details> …

settings_users: Conditionally render dropdowns for non-bots.

---

help/include/add-users-to-a-group.md
help/include/remove-from-a-group.md
help/include/right-sidebar-user-card.md

Note:
- The instructions don't perfectly match the field label, which also includes the user's name. I think it's OK? Seems more awkward to include it as a variable somehow.

help: Add instructions for adding user to groups via profile.

---

help/contact-support.md
help/support-zulip-project.md

Notes:
- We should generally point to detailed instructions, rather than giving super-abbreviated instructions in-line.
- I did leave a note about emailing us if you have private feedback to share; I think it's more useful than not, but it could arguably be dropped.
Current: https://zulip.com/help/contact-support#product-feedback
Updated:

help: Point to better resources for how to give feedback.

---

web/styles/popovers.css

popovers: Fix bug where tippy was getting cut off in usergroup list.

---

zerver/lib/message.py
zerver/lib/narrow.py
zerver/tests/test_message_fetch.py
zerver/views/message_fetch.py

This mirrors the restrictions in `zerver.lib.message.bulk_access_stream_messages_query`, in order to prevent leftover `UserMessage` rows from granting access to messages the user was previously allowed to access but no longer is.
This was developed as an extra hardening measure for [CVE-2024-27286](https://blog.zulip.com/2024/03/19/zulip-server-8-3-security-release/).

narrow: Add access restrictions to get_base_query_for_search

---

web/styles/app_components.css
web/styles/settings.css
web/styles/subscriptions.css

Changes:
* Scale width of "general/personal/subscriber" tabs with font size (and similar for user groups)
* Scale X button on the discard button with font size
* Left pane is always 40% width and right pane is always 60% width (previously it was 50/50 at wider screen sizes). This simplifies some CSS and also ensures there's enough space at larger font-sizes for the save/discard buttons to appear beside setting section headings without overflowing onto the next line (which was happening when the X icon got bigger)
**screenshots of subscriptions at 12/14/16/20 px**
| --- | --- |
| ![Screen Shot 2025-02-20 at 15 13 53](https://github.com/user-attachments/assets/7cd8d9b3-a344-466e-8182-a7aba113bc86) | ![Screen Shot 2025-02-20 at 15 21 …

settings modal: Fix a few info density related issues

---

web/styles/zulip.css

Fixes issue reported here:
https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20channel.20picker.20icon.20alignment/near/2122798
screenshots at 12px, 14px, 16px, 20px, all at +2 line-height (I've confirmed that it fixes similar issues at -2 line-height)
| --- | --- |
| ![Screen Shot 2025-03-14 at 14 00 44](https://github.com/user-attachments/assets/0b02ec00-96cc-42b0-a674-7545085bf1b8) | ![Screen Shot 2025-03-14 at 13 59 35](https://github.com/user-attachments/assets/c1c4e777-a65f-4c0c-aabc-414c06fefdfe) |
| ![Screen Shot 2025-03-14 at 14 01 39](https://github.com/user-attachments/assets/afd91d37-2276-4f0b-9ef8-831cf1abbe7c) | ![Screen Shot 2025-03-14 at 13 57 54](https://github.com/user-attachments/assets/84baca14-3b71-4f95-bdca-eca9f4a0b645) |
| …

channel_picker: Align icon by keeping constant line-height.

---

zerver/actions/streams.py
zerver/actions/users.py
zerver/lib/events.py
zerver/lib/streams.py
zerver/lib/subscription_info.py
zerver/lib/user_groups.py
zerver/tests/test_event_system.py
zerver/tests/test_home.py
zerver/tests/test_user_groups.py
zerver/views/streams.py

- First commit is a preparatory refactor.
- Second commit is to optimize computing stream group setting values.
Fixes:  #32561
<details>
</details>

register: Optimizing computing stream group setting values.

---

web/src/echo.ts
web/src/message_events.ts
web/src/message_events_util.ts

Auto scrolling to view the new message is not working. 
This bug was introduced in 238c35f2af9f7d3ef63609f55cee5f4d2d78ffd0. 
Fixed by passing `messages_are_new` in the relevant functions.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20autoscroll.20behavior/with/2122331

message_list: Fix list not scrolling when new message is added.

---

tsconfig.json
web/src/activity.ts
web/src/billing/billing.ts
web/src/compose_recipient.ts
web/src/dropdown_widget.ts
web/src/group_permission_settings.ts
web/src/integration_url_modal.ts
web/src/lightbox.ts
web/src/saved_snippets_ui.ts
web/src/settings_exports.ts
web/src/settings_org.ts
web/src/settings_users.ts
web/src/stream_data.ts
web/src/stream_edit.ts
web/src/stream_popover.ts
web/src/stream_settings_ui.ts
web/src/stream_types.ts
web/src/user_group_edit.ts
web/src/user_profile.ts
web/src/views_util.ts
web/tests/recent_view.test.cjs

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-8.html#the---erasablesyntaxonly-option
> Recently, Node.js 23.6 unflagged [experimental support for running TypeScript files directly](https://nodejs.org/api/typescript.html#type-stripping); however, only certain constructs are supported under this mode. Node.js has unflagged a mode called `--experimental-strip-types` which requires that any TypeScript-specific syntax cannot have runtime semantics. Phrased differently, it must be possible to easily erase or “strip out” any TypeScript-specific syntax from a file, leaving behind a valid JavaScript file.
>
> That means constructs like the following are not supported:
>
> - `enum` declarations
> - `namespace`s and `module`s with runtime code
> - parameter properties in …

Convert TypeScript enums to unions; enable erasableSyntaxOnly

---

web/src/buttons.ts
web/src/popup_banners.ts
web/styles/buttons.css

This fixes the 3rd checkpoint of #33924:
> - [ ] Show the text "Try now" button label instead of the loading indicator on the button on hover, since the user can request a retry. Button should still work in this situation.
This enables the retry button even when the loading indicator is being shown, and hides the loading indicator in favor of the original button content to indicate that the button is still interactable.
Fixes part of #33924.
<details>
Completed …

connection_error_banner: Hide loading indicator on hover.

---

web/src/stream_popover.ts
web/styles/popovers.css
web/templates/move_topic_to_stream.hbs

Earlier, we used to show "general chat" as the placeholder.
This PR adds support to show "Enter a topic (skip for general chat)" as the placeholder when topic is not mandatory in the move-topic-new-topic input box.
We show "general chat" (as we show in compose topic input box) when move-topic-new-topic input box is not focused and topic="".
Fixes: #33846.
<details>
</details>

move_topic: Improve placeholder when topic is not mandatory.

---

web/src/message_list_hover.ts
web/styles/message_row.css
web/templates/edit_content_button.hbs
web/templates/message_controls.hbs

Doing a lot of DOM manipulation on message hover leads to tooltips being not hidden / displayed when they should be.
This commit is an attempt to optimize that code to do minimal updates.
@karlstolley requesting a review from you here.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20random.20edit.20message.20tooltips.20appearing/with/2124294

message_list_hover: Optimize code for show edit message icon.

---

web/src/stream_data.ts
web/src/stream_settings_data.ts
web/styles/modal.css
web/templates/confirm_dialog/confirm_deactivate_stream.hbs
web/templates/stream_settings/stream_settings.hbs
web/tests/stream_data.test.cjs

- First commit is to show archive button to channel admins as well.
- Second commit is to update the way we show warning about stream being used for announcements.
Fixes:  #33379
<details>
</details>

Show archive buttons to channel admins as well.

---

web/src/compose_actions.ts
web/src/compose_recipient.ts
web/src/compose_setup.js
web/src/compose_tooltips.ts
web/src/compose_validate.ts
web/tests/compose.test.cjs
web/tests/compose_actions.test.cjs
web/tests/compose_validate.test.cjs
web/tests/upload.test.cjs

Compose send tooltip was not correctly displayed when the compose box was in an invalid state.
We significanlty improve the logic for displaying the tooltip here to provide a more robust experience to the user.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.F0.9F.9B.A0.EF.B8.8F.20incorrect.20hover.20behavior.20on.20.22send.22.20button/with/2125622
Things tested:
Empty compose state 
Restore compose content from draft:
Recipient change to DM:
Not required topics:
Posting permission:
Uploading image:
Empty channel:
Message length exceeded:

compose: Fix buggy tooltip on validation.

---

web/styles/search.css
web/styles/zulip.css

This PR corrects the search-icon grid below 768px so that it doesn't overlap the items in the right column.
In spectator view, this also improves the right-hand alignment of the standalone search icon.
Fixes: #34007
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20navbar.20messed.20up.20for.20spectators/near/2113761)
| Spectator, before | Spectator, after |
| --- | --- |
| ![search-icon-spectator-before](https://github.com/user-attachments/assets/3afac6e1-3d03-4960-8468-b6b816ef0e1a) | ![search-icon-spectator-after](https://github.com/user-attachments/assets/4b4fc5df-d988-4187-821c-2ecb23ffbf99) |
| Logged in, before | Logged in, after (no change, but note simplified grid) |
| --- | --- |
| …

search: Improve search-icon layout, spectator alignment.

---

web/src/sidebar_ui.ts

Fixes: #34007 
<details>
Before : 
https://github.com/user-attachments/assets/3aa6c8b7-9cb6-40f1-bd44-fc9037b329b2
Following this, the procedure below can reproduce the behaviour (irrespective of browser):
Login using any username (say AARON).
Hide the right-sidebar which will add right-sidebar key to localStorage.
Logout and observe that UI was overriding .
After :
https://github.com/user-attachments/assets/551a4184-b35e-4e7a-9135-91e720c3eaef
in web/src/sidebar_ui.ts
I have added !page_params.is_spectator , so now in logged out view the ui looks fine 
if (ls.get("right-sidebar") && !page_params.is_spectator) {
$("body").addClass("hide-right-sidebar");
}
When a user hides the right sidebar while logged in and …

spectator: Don't apply right-sidebar hiding for spectators

---

web/src/compose_setup.js
web/src/compose_validate.ts
web/styles/message_row.css
web/tests/compose_actions.test.cjs
web/tests/compose_validate.test.cjs

When I adjusted 4fbf91c135cf6267217ebfdc679e95650e722b66 to no longer do a full re-validation on every character typed, that unmasked bugs in how the compose_setup handler code and compose_validate split responsibility for validating 0-length messages.
The user-facing result was the send button not enabling properly when starting to type.
Fix this by moving the 0-length message validation into compose_validate, where we already handle issues of too-long messages, sharing the same basic logic for determining when to do a full validate() call.
A benefit of this reworking is now all of the logic for handling the `invalid` class is in one place in validate, rather than split with the compose_setup module.

compose_validate: Fix buggy separated handling of empty compose box.

---

web/src/compose_setup.js
web/src/message_edit.ts
web/src/settings_org.ts

The `propertychange` event is [deprecated](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa743134%28v%3Dvs.85%29?utm_source=chatgpt.com) and was only supported in older versions of Internet Explorer. It is also not listed among the available [jQuery events](https://api.jquery.com/category/events/).
With this commit, I have replaced all instances of `propertychange` with the standard `change` event.
<details> …

input: Remove usage of `propertychange` event.

---

web/src/buttons.ts
web/src/message_fetch.ts
web/src/popup_banners.ts
web/src/server_events.js

This PR is a completion PR for #33974 and completes the first two checkpoints of #33924:
> - [ ] Change the banner text to:
> > Unable to connect to Zulip. Trying again in {x} seconds… [Try now]
> - [ ] Show a loading indicator on the button any time that a retry is currently in progress.
Changes from #33974:
- Simplifies the logic to prevent the two codepaths opening the connection error banner.
- Modifies the `message_fetch: Synchronize message fetch attempts.` commit and removes the `load_messages_attempts` variable since as @timabbott mentioned that `message_fetch`, unlike `server_events` does not have a singleton module -- you can have several fetches for different parameters running at the same time. This way the `load_messages` remains a recursive function which can be called with …

Improve connection error banner and prevent glicthy open/close of the banner.

---

zerver/actions/message_send.py
zerver/views/streams.py
zerver/views/user_groups.py

When a user was getting subscribed to a private stream, the stream name was not linkified since acting_user was not passed. We also pass the acting user in user_groups.py, even though it doesn't introduce any behavioural change.
This commit does not attempt to pass acting user in similar message functions and just focuses on fixing the problem of a private stream not being linkified.
Fixes: 
<details>
</details>

message: Add acting_user to internal_prep_private_message.

---

web/src/compose_validate.ts

This will help us debug sentry error when compose send button is unexpectedly in a disabled state.

compose_validate: Add additional debug info on invalid compose state.

---

web/src/popover_menus.ts

Since the reference element can be removed from DOM, we rely on `popper` here to access the tippy instance which is reliable.
Reproduced the bug by deleting the user `li` from the right sidebar after opening the user card. Then, scrolling the right sidebar to move the reference position out of view. This might happen in a real environment when an event rerenders the right sidebar.

popover_menus: Fix tippy `instance` being undefined.

---

web/styles/compose.css

This removes a light-mode-only (effectively) `:focus-visible` color from the Send button. It also specifies `outline: 0` on `:focus-visible`. While that's taken care of in the `:focus` state, this will save us some pain as we move to more uniformly applying the `:focus-visible` pseudoclass to keyboard navigation.
This does not remove the `--color-background-info-primary-action-button-active` variable, as that is used in the button showroom.
[CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20keyboard.20selection.20makes.20compose.20button.20darker/near/2126834)
| --- | --- |
| ![send-focus-dark-before](https://github.com/user-attachments/assets/485b0eff-2b2f-4969-bab4-ac7f40e7f282) | …

compose: Correct focus-visible styles on Send button.

---

web/styles/recent_view.css

This PR enables avatars, their vertical padding, and border-radius to scale with the font size.
[CZO discussion](https://chat.zulip.org/#narrow/channel/431-redesign-project/topic/broader.20range.20of.20font.20sizes/near/2127357)
_Showing 12px, 16px, and 20px; note better vertical alignment at the otherwise unchanged 16px:_
| --- | --- |
| ![recent-avatars-12px-before](https://github.com/user-attachments/assets/883aba2c-14c3-41c7-816c-1e30f51f387e) | ![recent-avatars-12px-after](https://github.com/user-attachments/assets/b38e1dc8-6528-4315-b41f-549b77278cf9) |
| ![recent-avatars-16px-before](https://github.com/user-attachments/assets/f84d911c-e109-423d-b794-33f3c2f90f90) | ![recent-avatars-16px-after](https://github.com/user-attachment …

recent_view: Enable avatars and overflow marker to scale.

---

web/src/compose_validate.ts
web/src/util.ts
web/tests/compose_validate.test.cjs
web/tests/util.test.cjs

With mandatory_topics enabled.
Earlier, sending messages to `"(no topic)"` and `"general chat"` didn't show the "Topics are required in this organization." error message.
The message-send operation used to fail silently.
This PR fixes the bug.
<details>
</details>

compose_validate: Fix topic required error message not shown.

---

web/src/message_edit_history.ts
web/templates/message_history_overlay.hbs

The message history overlay header now matches the tooltip of the button used to get there.
Fixes: #34005 
| Tooltip | Overlay header |
| --- | --- |
| <img width="361" alt="image" src="https://github.com/user-attachments/assets/31345335-35f3-49e3-afa3-bba4cdc82355" /> | <img width="836" alt="image" src="https://github.com/user-attachments/assets/e384167e-43c9-49d8-bbd7-5af360fa9349" /> |
| Tooltip | Overlay header | 
| --- | --- |
| <img width="382" alt="image" src="https://github.com/user-attachments/assets/7a4c5bde-a0fb-4b47-9e90-4ec06a896aa5" /> | <img width="829" alt="image" src="https://github.com/user-attachments/assets/9bda4e2a-4389-4278-a4f5-38cc5820d0a5" />|
| Tooltip | Overlay header |
| --- | --- |
| <img width="417" alt="image" …

message_history: Improve overlay header.

---

web/src/buttons.ts
web/src/message_fetch.ts
web/src/popup_banners.ts

discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Glitchy.20connection.20error.20popup.20banner/with/2122090
Fixes the errors described by @alya here:
- If I press "try now", after that fails, it tells me that the next attempt will be soon/in 5 seconds/etc.. I would expect it to still be in 30 seconds or whatever if that's where we're at in the retry frequency.
- I saw the timer go down to 5 seconds and then just jump to 17 seconds, and then later down to 16 seconds and jumping to 25 seconds. This is after I'd pressed "try now" a few times, so I dunno if the banner was lying to me at that point? (see above)
- Less important, but the spinner seems to freeze for a moment when it first appears. This is if I don't press anything.

Fix bugs related to connection error banner.

---

zerver/lib/name_restrictions.py
zerver/tests/test_signup.py

Renames `WHITELISTED_EMAIL_DOMAINS` to `OVERRIDE_ALLOW_EMAIL_DOMAINS` as the set of email domains that are allowed even if they are in the set of disposable email domains.
---
<details>
</details>

signup: Add "airsi.de" as an allowed email domain.

---

web/e2e-tests/copy-messages.test.ts
web/src/copy_messages.ts
web/src/hotkey.js
web/src/ui_init.js
web/styles/rendered_markdown.css

@_**Anders Kaseorg|699** [said](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20Copying.20clears.20the.20selection/near/2118741):
>My suggestion though is *never* to `preventDefault` the Ctrl+C keyboard event. We should leave Ctrl+C alone, register a global listener for the [`copy` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event) (the real one, not a synthetic one), and use `event.clipboardData.setData` if we need to do something strange.
Tries to implement this comment by @andersk. 
Fixes: #33949.
This attempts to use a global copy
event listener instead of triggering
the copy handler on Ctrl+C.
Also fixes [#issues > 📂 pasting LaTeX @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20pasting.20LaTeX/near/2120422)

copy: Use a global copy event listener.

---

zerver/tests/test_realm_export.py
zerver/views/realm_export.py

We have not see noticeable impact due to export size.
Fixes: 
<details>
</details>

realm_export: Support up to 20GB of data via the UI.

---

web/styles/compose.css

This PR fixes the overflowing icon in compose box as reported in [#issues > ❓buttons spilling out of compose box when zoomed out](https://chat.zulip.org/#narrow/channel/9-issues/topic/.E2.9D.93buttons.20spilling.20out.20of.20compose.20box.20when.20zoomed.20out/with/2128249) which occurs due to issues in border and margin.
|Before|After|
|----------|-------|
|![image](https://github.com/user-attachments/assets/c1fbac86-f341-4a8b-a68c-2cc8d93ea1ba)|![image](https://github.com/user-attachments/assets/5d5b815e-7b9f-4de6-bbae-07df53e54be3)|
[CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/.E2.9D.93buttons.20spilling.20out.20of.20compose.20box.20when.20zoomed.20out/with/2128249)
<details> …

Overflowing compose button

---

web/src/stream_settings_ui.ts
web/src/user_group_components.ts
web/src/user_group_edit.ts
web/styles/subscriptions.css

This commit makes the following changes to improve the display of long stream titles in the stream creation and user group settings UI:
- Uses `display: -webkit-box` and `line-clamp` properties to show the title upto two lines, and end with `...` if it exceeds.
- Updates icon `font-size` to align with text size.
- Updates `margin` and `line-height` to make it visually better.
[CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/long.20channel.20name.20in.20creation.20flow/with/2122698)
|Before|After|
|----------|-------|
|![image](https://github.com/user-attachments/assets/40de51d2-417e-4e64-848e-4bfcce1181e9)|![image](https://github.com/user-attachments/assets/ff587edc-2779-4f92-84c3-e186552e48f2)| …

stream_settings: Improve handling of long stream titles in UI.

---

api_docs/changelog.md
version.py
web/src/compose.js
zerver/actions/message_send.py
zerver/lib/addressee.py
zerver/lib/topic.py
zerver/migrations/0696_rename_no_topic_to_empty_string_topic.py
zerver/openapi/zulip.yaml
zerver/webhooks/slack_incoming/tests.py
zilencer/management/commands/populate_db.py

Commit 1: [#backend > general chat and database indexes @ 💬](https://chat.zulip.org/#narrow/channel/3-backend/topic/general.20chat.20and.20database.20indexes/near/2128773)
Commit 2: Migration `"(no topic)"` -> `""`
Commit 3: Server should interpret `"(no topic)"` as empty string
Commit 4: The bug I mentioned in my check-in, yesterday.
<details>
</details>

migration: Rename "(no topic)" to empty string topic.

---

scripts/lib/create-production-venv
tools/build-release-tarball
tools/lib/provision.py
tools/python-warnings.bash

Build warnings are unfortunately very common in third-party packages. They’re difficult to reliably detect since packages don’t always build from source, and they can’t be whitelisted on a per-package basis since they’re all attributed to setuptools or an anonymous code string.

provision: Ignore Python warnings while building requirements

---

zerver/models/realms.py

It's not obvious why this should be different from the permission for moving topics.

models: Change default for can_resolve_topic_group.

---

templates/zerver/app/index.html
zerver/views/home.py

Fixes #34010
From version 132, Firefox now defaults to not resize the viewport content but only the visual viewport. While this works well in Chrome Android, it creates a buggy experience in Firefox Android where the compose box is hidden under keyboard.
To fix it, we rollback to resizing content when keyboard is shown on Firefox Android.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20Keyboard.20hides.20composebox.20on.20mobile.20web.20on.20Firefox/with/2124110

home: Fix compose box not visible on focus in Firefox Android.

---

web/templates/settings/notification_settings.hbs

Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/SETTINGS.2F.20NOTIFICATIONS.20breaking.20at.20full.20size.2E)
**Before starts breaking  after 14 px:**
**After** 
| Font-size | UI |
|------|-------|
| At 12px |  <img width="650" alt="Screenshot 2025-03-20 at 7 10 34 PM" src="https://github.com/user-attachments/assets/0d217d59-0195-4302-acf2-c818b1f89282" /> | 
| At 16px | <img width="864" alt="Screenshot 2025-03-20 at 7 10 16 PM" src="https://github.com/user-attachments/assets/c6ac5aff-54c5-4ec8-a420-4ed43f40396b" /> |
| At 20px | <img width="1034" alt="Screenshot 2025-03-20 at 7 10 59 PM" src="https://github.com/user-attachments/assets/f10e902a-1d7b-4ff9-921b-c0bea4ce5bf9" /> |
<details> …

notification_settings: Fix the misalignment of topic notification header.

---

web/src/stream_settings_ui.ts
web/styles/subscriptions.css
web/templates/stream_settings/selected_stream_title.hbs

At 19px:
| --- | --- |
| ![image](https://github.com/user-attachments/assets/52bdc9d0-8188-4c9e-ae7c-44cca11d7876) | ![Screenshot from 2025-03-23 19-57-12](https://github.com/user-attachments/assets/2e605f0b-c957-479c-ac09-e457693795e4) |
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/channel.20settings.20UI.20header.20bugged

Fix channel settings overlay header at 18px font size.

---

zerver/lib/i18n.py
zerver/views/registration.py

If there were no users found for `find_team`, we need to provide a default langauge for the email as one cannot be extracted from `UserProfile` in this case.
Tested by finding account and checking server log with / without this commit on http://zulipdev.com:9991/accounts/find/ 
`
2025-03-21 12:38:52.500 WARN [zulip.send_email] Missing language for email template 'zerver/emails/find_team'
`
was only logged without this commit.

registration: Fix language code missing for `find_team` emails.

---

web/src/message_list_view.ts

Previously, the edited notice was not displayed when a user revealed an edited message sent by a muted user. This commit ensures that the notice appears correctly in such cases.
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/Can't.20see.20the.20.22EDITED.22.20label.20for.20muted.20user.20messages/with/2131135
| Before | After|
| ![before](https://github.com/user-attachments/assets/02af4d0d-21f5-47db-8386-0b06d15d34d2)| ![after](https://github.com/user-attachments/assets/d48dff66-cf73-46cc-85b9-e9e2b972dc7d)| 
<details> …

message_edit: Show edited notice when revealing a muted user's message.

---

web/src/composebox_typeahead.ts
web/tests/composebox_typeahead.test.cjs

We add a "New" label at the end of query which doesn't match any of the existing topic to help user identify when they are linking to a topic which doesn't exist.
discussion: [#design > wrapping compose topic link typeahead @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/wrapping.20compose.20topic.20link.20typeahead/near/2113499)
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c33e8997-6b2e-4b91-94cf-5314db648836) | ![Screenshot from 2025-03-21 10-23-03](https://github.com/user-attachments/assets/50fdd044-2843-4b85-b7fa-6ac7f0ae826b) |

composebox_typeahead: Add "New" label to non existant topics.

---

zerver/tests/test_signup.py
zproject/backends.py

Apparently, while we set our own maximum password length of 100 characters, zxcvbn had a hardcoded maximum length of 72 characters, and threw an exception if that was exceeded.
The fact that we're discovering this now would suggest that nobody has previously attempted a password between 72 and 100 characters in length.

backends: Fix exception with password lengths above 72.

---

web/src/server_events_dispatch.js
web/src/stream_list.ts
web/src/stream_list_sort.ts
web/src/typeahead_helper.ts
web/src/ui_init.js
web/tests/stream_list.test.cjs
web/tests/stream_list_sort.test.cjs

discussion: https://chat.zulip.org/#narrow/channel/137-feedback/topic/inactive.20channels.20despite.20Never/with/2134382
Tested by deleted all the messages in a channel and then running `./manage.py update_channel_recently_active_status`.
After that tested that different settings inactive channel management work as expected.

Fix channel demote inactives setting being ignored.

---

scripts/lib/install

This prevents the venv from ending up with references to /root.
- https://chat.zulip.org/#narrow/channel/9-issues/topic/manage.2Epy.20email_mirror.20-.20permission.20issue.20in.20docker.20v10/near/2134286

install: Move ourself to deployments path before creating venv

---

web/src/message_view.ts

Showing this banner in every view can be annoying. As a first step, we only show it in conversation view to reduce the banner spam.

message_view: Only show just to unread banner in conversation views.

---

web/src/poll_widget.ts
web/templates/widgets/poll_widget.hbs
web/tests/poll_widget.test.cjs

This PR makes it possible to add poll options even when the poll has no title/question.
Also this does removes the tip shown on polls without questions.
changes:
- removes `.poll-author-help` divs to remove the tip shown for user.
- also removes the .poll-author-help from poll_widget.test.cjs
- removed can_vote condition and always show `Add option` button.
fixes: #33672
| Before     | ![Changes visible in alignment and hover](https://github.com/user-attachments/assets/30c8dc28-64fe-408f-a7a8-344e6441b252)    |
| After  | ![dm](https://github.com/user-attachments/assets/0f614bd2-1bac-4789- …

widgets: Fix not showing add poll option  when poll has no title.

---

web/src/compose_banner.ts
web/src/compose_setup.js
web/src/compose_validate.ts
web/src/tippyjs.ts
web/tests/compose_actions.test.cjs
web/tests/compose_validate.test.cjs
web/tests/upload.test.cjs

Made some code changes to perform all the check in `validate` only and set error messages there.
States tested:
* No channel selected
* Topic missing
* No permission to post in channel
* No permission to use wildcard mentions
* DM recipient missing / invalid
* DM not allowed for recipient.
* No message content
* Message too long
* Upload in progress.

Fix compose send disabled without error tooltip.

---

web/src/click_handlers.ts
web/src/message_edit.ts
web/styles/compose.css
web/styles/message_row.css

When I cancel an ongoing upload while in preview mode, returning to the editing still shows "Uploading..":
What I have found is this: 
- When an upload is cancelled we use [`text-field-edit's`](https://www.npmjs.com/package/text-field-edit) `replaceFieldText` method for replacing the "Uploading.." text with the old text. 
- When we activate preview mode in editing, we set the textarea's display to none using jquery's `hide()` method & for some reason `replaceFieldText` does not work when the text area's display is set to none (I have tested this separately).
To address this issue, I replaced the `hide()` method with some custom css to hide the textarea without setting it's display to none (negative z-index, 0 height).
Fixes: [#issues > Stale syntax upon cancelling upload in …

message_edit: Fix preview issues in editing

---

web/styles/inbox.css

This PR improves the internationalization on the dropdown filters in both Inbox and Recent Views.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/view.20type.20dropdown.20width)
_Note that the English filter gets slightly smaller; that's owing to previous brittle eyeballed values._
| --- | --- |
| ![russian-filters-recents-before](https://github.com/user-attachments/assets/3126e444-0a84-4c27-8ba6-ebe7049746b6) | ![russian-filters-recents-after](https://github.com/user-attachments/assets/a670ac05-9aa7-4dd5-acae-e1fb33b7478c) |
| ![russian-filters-before](https://github.com/user-attachments/assets/439614fb-65e3-40c2-abb4-389598c4e95a) | ![russian-filters-after](https://github.com/user-attachments/assets/d470d7cb-842a-4 …

home_views: Let Recents/Inbox view filter fit content.

---

web/styles/subscriptions.css

`max-width` was not working correctly here. Removing it gets us in good state.
Bug was introduced in [#34133](https://github.com/zulip/zulip/pull/34133)
| --- | --- |
| ![Screenshot from 2025-03-25 08-39-07](https://github.com/user-attachments/assets/c456d85d-e4c5-404f-8a22-3d464260efff) | ![Screenshot from 2025-03-25 08-38-15](https://github.com/user-attachments/assets/6c4b6ea8-8d7a-40d5-a146-ed54dd6d8fd7) |
| ![Screenshot from 2025-03-25 08-39-04](https://github.com/user-attachments/assets/25308dac-3a33-48dc-80be-942e9fd16cb1) | ![Screenshot from 2025-03-25 08-38-19](https://github.com/user-attachments/assets/f4002537-5132-481a-a021-c2e66c9d6e88) |

channel_settings: Fix channel name incorrect hidden.

---

web/src/ui_init.js

Previously, clicking a topic link on small devices did not close the sidebar, and it had to be manually closed. This PR fixes that by calling `sidebar_ui.hide_streamlist_sidebar()` when a topic link is clicked on screens smaller than the `md` breakpoint.
Addresses [CZO Thread](https://chat.zulip.org/#narrow/channel/9-issues/topic/Sidebar.20doesn't.20hide.20on.20mobile.20devices.20when.20opening.20a.20topic/with/2132110)
| --------- | --------- |
| ![sidebar_doesnt_close_when_clicking_on_topic](https://github.com/user-attachments/assets/3153ee69-df82-4061-bd94-c266c7daed81) | ![topic_link_after](https://github.com/user-attachments/assets/39ad8ca7-1d79-4e39-a90b-358f452a05d4) |
<details> …

ui_init: Hide sidebar when clicking a topic link on small devices.

---

web/src/message_fetch.ts
web/src/message_list.ts
web/tests/message_list.test.cjs

show ` You are not subscribed to  #xyz. Subscribe` bookend on channel or topic which are not subscribed and have no messages.
fixes #33209
| **before**       | **after**                | 
|--------------------|--------------------------------|
| ![image](https://github.com/user-attachments/assets/a3c7148c-cd82-428f-9238-b2785073bdff)| ![image](https://github.com/user-attachments/assets/ff0e2238-6538-4a88-8650-fa203ec122d7)|
<details>
</details>

message_fetch: Update trailing bookend for empty message lists

---

web/src/compose_closed_ui.ts
web/src/inbox_ui.ts
web/src/message_view.ts
web/src/recent_view_ui.ts
web/tests/compose_closed_ui.test.cjs

Fixes the "reply to the current conversation" button text when the compose box is closed not updating for the focused row in the Inbox or Recent Conversations view. This was broken in https://github.com/zulip/zulip/commit/f630272b4c614a8ebf18877b94fbaa6076ec64e2 when the current message list was set to undefined for non-message views.
Also, does some general refactoring and clean up of the function that sets the button text for these message recipients and it's callers.
---
| --- | --- |
| ![Screenshot from 2025-03-24 19-23-56](https://github.com/user-attachments/assets/0a6be6dc-70c5-4135-92a3-517abc16c4ce) | ![Screenshot from 2025-03-24 19-23-19](https://github.com/user-attachments/assets/72136000-2a3d-4b03-9f61-0353cbe0cd4b) |
| …

compose-closed-ui: Fix reply button text for Inbox and Recent Conversations views.

---

web/src/drafts.ts

This was likely a longstanding issue that wasn't caught because we required topics on CZO. The new logic ensures topic match even for empty string (general chat) topics.
[CZO report](https://chat.zulip.org/#narrow/channel/9-issues/topic/drafts.20moved.20to.20.22general.20chat.22/near/2133842):
> A couple of times this morning I've seen the following happen:
> * There's a message in *general chat* in some channel. (#**mobile-dev-help**, then #**mobile**.)
> * I hit "r" to reply.
> * The compose box gets filled in with a draft that I definitely didn't write for "general chat" — it looks like I wrote it for some other thread in the same channel.

drafts: Fix bug opening drafts in 'general chat'.

---

web/styles/left_sidebar.css

This fixes a subtle but extremely annoying alignment issue on Safari on iOS/macOS that would leave new unreads (going from 0 to 1+, either when new messages are received or a message is marked unread) out of alignment on the stream row with respect to topic rows below. 
The root of this issue seems to be that Safari does not calculate `:empty` inside of `:has()`. The fix here instead uses the more reliable `.hide` class instead.
| --- | --- |
| ![safari-misaligned-unreads-before](https://github.com/user-attachments/assets/dc60d547-1612-4b8f-aaf7-7ba03d91300e) | ![safari-misaligned-unreads-after](https://github.com/user-attachments/assets/7a8da191-8634-4b86-8e96-bd98cd3fb4f1) |
<details> …

left_sidebar: Avoid misaligned unreads on Safari.

---

zerver/tests/test_scheduled_messages.py

Updates `zerver/tests/test_scheduled_messages.py` to use f-strings when setting message content from a variable.
---
<details>
</details>

scheduled-message-tests: Use f-strings for setting message content.

---

web/src/user_group_edit.ts

Fixes part of #33730.
<details>
</details>

user_group_edit: Update permissions panel on subgroup edit.

---

web/templates/recipient_row.hbs

[CZO Bug report - first message](https://chat.zulip.org/#narrow/channel/9-issues/topic/general.20chat.20missing.20from.20header.20bar.20in.20search.20view/near/2135677)
Searching for a word that appears in a message in a empty string topic via the search box resulted in a message view where the topic names in the recipient_row were empty string instead of `realm_empty_topic_display_name`.
This PR fixes that bug.
<details>
Completed …

recipient_row: Fix empty string topic display in keyword search view.

---

corporate/lib/decorator.py
corporate/tests/test_remote_billing.py
zerver/lib/request.py
zerver/middleware.py

A few of our decorators use HTTP headers to detect whether to serve a JSON error or redirect to a login page. Fix them to do so correctly.

Parse Accept header correctly

---

web/src/message_edit.ts
web/templates/message_moved_widget_body.hbs

For realms that allow _general chat_ topics (the realm doesn't require topics in channel messages), when we move a message from a topic to _general chat_ using the "Move only this message" option a confirmation toast is shown. We currently don't show _general chat_ in the link of the confirmation toast as we show in the message moved notice link.
This PR adds support to show _general chat_ in the link of the confirmation toast when a message is moved to it.
Fixes: [#issues > general chat topic not shown in message move toast @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/general.20chat.20topic.20not.20shown.20in.20message.20move.20toast/near/2133592).
| Description            | Before | After | …

message_move: Show "general chat" in link of confirmation toast.

---

web/src/message_edit.ts

[CZO Bug report](https://chat.zulip.org/#narrow/channel/9-issues/topic/general.20chat.20missing.20from.20header.20bar.20in.20search.20view/near/2135677)
Earlier, for `topic=""` and `mandatory_topics=False`, the inline topic edit input field width was not set correctly when the inline topic edit was started for the first time.
This resulted in overflowing placeholder.
<details> …

inline_topic_edit: Fix inline topic edit input field width for topic="".

---

web/styles/subscriptions.css
web/templates/stream_settings/stream_settings.hbs

at 16px, with widths 800px 900px 1300px (change only at middle width)
| --- | --- |
| ![Screen Shot 2025-03-26 at 14 14 46](https://github.com/user-attachments/assets/267410e2-e956-4252-a53c-b9c0d8f586cd) | ![Screen Shot 2025-03-26 at 13 14 44](https://github.com/user-attachments/assets/9667ee8d-e91a-4a89-b2e1-004b77a8b4ba) |
| ![Screen Shot 2025-03-26 at 14 13 09](https://github.com/user-attachments/assets/91641a8e-f0e9-4e86-95e2-ab066192c853) | ![Screen Shot 2025-03-26 at 14 17 42](https://github.com/user-attachments/assets/5111f774-8d5b-45c0-8898-f42d8a7e4e52) |
| ![Screen Shot 2025-03-26 at 14 14 53](https://github.com/user-attachments/assets/218da1a1-03af-4277-ae78-8d74c66650ac) | ![Screen Shot 2025-03-26 at 13 14 …

stream_settings: Move muted channels help text to below header.

---

web/src/compose_actions.ts
web/src/narrow_state.ts
web/src/typing_events.ts

When we have the "channel", "topic" and "with" operators in the narrowed view, we still want to identify that as a view where opening the compose box would be replying to the "channel" and "topic" combination.
**Notes**:
- The first commit is a prep commit to use the validated version of `narrow_state.stream_id` when we're checking for typing events in a channel and topic conversation. Manually testing this change caused me to notice that typing notifications in channels weren't working.
- The second commit updates `narrow_state.narrowed_by_topic_reply` to filter out the "with" operator, like we do in `narrow_state.narrowed_by_pm_reply`.
- The third commit fixes the only bug I could find when reviewing the functions that call `narrowed_by_topic_reply` and `narrowed_by_reply` for the …

narrow-state: Filter out "with" operator for narrowed_by_topic_reply.

---

zerver/tests/test_message_topics.py

PR to address https://github.com/zulip/zulip/pull/32330#discussion_r1906201785
> This sort of test should probably pass a short fetch_event_types to make the test do ~20x less work; too many do_events_register calls without that slows down the test suite.
<details>
</details>

test_message_topics: Optimize test by limiting `fetch_event_types`.

---

tools/test-js-with-node
web/src/integration_branch_pill.ts
web/src/integration_url_modal.ts
web/src/invite.ts
web/styles/app_variables.css
web/styles/input_pill.css
web/templates/settings/generate_integration_url_filter_branches_modal.hbs

Follow-up to: #33754
(I was more than halfway done when the previous PR was merged, so I followed through with the original idea of adding branch pills.)
Removed the "comma-separated" bracketed suffix, because though this does not have typeahead, we start with the default value "main", so it should be clear that valid entries are pills.
(Would we still want to tell users that only commas and enter keys add the input pill, as opposed to other keys like tab and space, to be clear?)
The branch values are retained even if the "Send notifications for all branches" is checked on (hiding the branch filtering UI), and is unchecked again.
Also includes some minor refactoring to the email pill widget in `invite.ts` in the second commit.
<details>
<summary><h3>Screenshots:</h3></summary>
<h3>Default …

Add input-pill for branches in integration-URL modal

---

web/styles/left_sidebar.css
web/templates/pm_list_item.hbs

Following a very similar technique as for multiline topics (#32341), this PR introduces multiline DMs--which as the screenshots show might either be for group DMs or for users with very long usernames.
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/multi-line.20DMs.20in.20left.20sidebar/near/2137632)
| --- | --- |
| ![dms-area-before](https://github.com/user-attachments/assets/def1c921-edca-4507-a08c-8e45c6bf84fd) | ![dms-area-after](https://github.com/user-attachments/assets/0ff71876-a38d-483e-8a82-b6d892addc9e) |
<details> …

left_sidebar: Present two-line DM rows.

---

templates/corporate/apps.html
web/src/portico/landing-page.ts
web/styles/portico/landing_page.css
zerver/lib/github.py
zerver/tests/test_github.py

| --- | --- |
| ![Screenshot from 2025-03-27 08-50-41](https://github.com/user-attachments/assets/dfacc296-a698-467a-b1f3-73da4363122f) | ![image](https://github.com/user-attachments/assets/bd7496ee-ce73-46fe-aa14-6c9da7a5176e) |
Testing that clicking on both links downloads the advertised version of the app.

Provide arm64 app build by default for macOS.

---

tools/test-api

Fixes CI - it was failing due to the API test for organization exports, which was returning an error due to there being no Organization Owners with consent to private data export.

test-api: Make desdemona consenting to private data export.

---

zerver/lib/events.py
zerver/lib/home.py
zerver/lib/subscription_info.py
zerver/tests/test_subs.py

It returns just bots for now.
Discussed here: https://chat.zulip.org/#narrow/channel/378-api-design/topic/Extending.20include_subscriber.20for.20parse.20subscriber.20data/with/2141527
Part of  #34244

subscription_info: Add option to get partial subscribers.

---

help/inbox.md
help/include/inbox-instructions.md
help/include/recent-conversations.md

Fixes #27191.
---
Current: https://zulip.com/help/reading-strategies#finding-a-conversation-to-read
These changes also impact inbox and recent conversations documentation pages.
Updated:
---
Current: https://zulip.com/help/inbox
Updated:

help: Improve inbox and recent conversations docs.

---

web/src/buddy_list.ts
web/src/hotkey.js

Reproducer
* Log out
* Go to a topic where after narrowing, we have to load more messages. (We see an error "cannot show user id at this position"
* Press `w`  to see error - "Cannot highlight key for ListCursor"

Fix errors related to user search in logged out view.

---

web/styles/compose.css

This corrects for an incorrectly collapsing picker area.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/issue.20in.20compose.20select.20recipient.20widget/near/2140740)
_No change on the channel picker, even with long channel names:_
| --- | --- |
| ![dm-many-recipients-before](https://github.com/user-attachments/assets/38a96eab-4431-4889-bf2c-fe6e2fd90992) | ![dm-many-recipients-after](https://github.com/user-attachments/assets/286b514d-a8e7-40db-bfce-3013f10553fe) |
| ![picker-long-channel-before](https://github.com/user-attachments/assets/4b6c73f3-c8ca-4928-9d03-ddf006676abe) | ![picker-long-channel-after](https://github.com/user-attachments/assets/a1d99e42-002b-4cb8-bd3f-b3ecbb868fb5) |
<details> …

compose: Prevent picker from collapsing.

---

puppet/zulip/files/nginx/zulip-include-frontend/uploads-internal.conf

This prevents a thundering herd for videos -- if a very large video is posted to a channel with many active clients, all of them simultaneously request it, to provide the in-feed preview image. While these requests come with a `Range` header which is intended to limit the request to just the first couple MB, nginx ignores this header when making its request to the upstream -- so it can obtain and cache the whole file locally.  This results in multiple competing requests for the whole content from S3, all racing to store the content in the cache.
Use cache slicing to split the content cache into chunks of 5MB; the cache is filled one slice at a time, as needed based on the byte ranges that clients request.  Clients making requests without a `Range` header are provided with the content …

nginx: Use cache slicing to prevent thundering herds for video thumbs.

---

web/src/navigate.ts

Fixes #32970
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20long.20messages.20not.20completely.20readable
When navigating from a short message to a tall message via up keypress, we used to jump to the top of the message. This doesn't align with user's expectation that up / down keypress will let them see the entire message feed.
To fix it, we can `page_up` which scrolls up the correct amount and then our message selection logic kicks in to select the correct message on screen.

navigate: Fix up keypress behaviour when a long prev message.

---

web/styles/app_variables.css
web/styles/message_row.css
web/styles/rendered_markdown.css

By adjusting the padding on likely link-containing blocks (paragraphs and lists), and offsetting that padding as needed, we can ensure the proper display of focus rings on links without compromising the way we expect the message area to be laid out and spaced.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/link.20focus.20outlines.20at.2020px)
_Showing 20/-2; 16/0; and 12/+2:_
| --- | --- |
| ![focus-ring-20--2-before](https://github.com/user-attachments/assets/82fb4da0-5bd5-43df-81ce-400f02d27be4) | ![focus-ring-20--2-after](https://github.com/user-attachments/assets/868cddcf-3756-48dd-bff3-51676554df9f) |
| ![focus-ring-16-0-before](https://github.com/user-attachments/assets/18f08332-aeef-4a10-8c50-f5d9978e0365) | …

rendered_markdown: Adjust content blocks for link focus ring.

---

web/styles/message_row.css
web/styles/rendered_markdown.css

This PR does three things:
1. It better targets first child paragraph blocks in `.message_content` with more specific selectors.
2. It restores padding that was accidentally (?) removed from non-sender-containing messages in #33985.
3. It adjusts the message-box grid definition to account for the restored padding, ensuring that stars/hover controls remain optimally aligned regardless of what content opens a message (the original aim of #33985).
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/Spoiler.20alignment)
| --- | --- |
| ![corrected-message-box-before](https://github.com/user-attachments/assets/ce505362-1c85-480b-8863-2661c48420cd) | ![corrected-message-box-after](https://github.com/user-attachments/assets/843 …

message_row: Content box improvements and corrections.

---

templates/zerver/app/index.html

This will help us revert back to `resizes-visual` on Firefox Android when the bug is fixed.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/Keyboard.20hides.20composebox.20on.20mobile.20web.20on.20Firefox/with/2140295
report - https://bugzilla.mozilla.org/show_bug.cgi?id=1943053

app: Track keyboard overlaps with compose box bug as a TODO.

---

puppet/zulip/templates/postgresql/13/postgresql.conf.template.erb
puppet/zulip/templates/postgresql/14/postgresql.conf.template.erb
puppet/zulip/templates/postgresql/zulip.conf.template.erb

PostgreSQL 10 and later can adjust their TLS configuration without a restart, with `SELECT pg_reload_conf()` or `pg_ctlcluster 16 main reload`.
-----
Ironically, of course, this adjustment will trigger a server restart.

postgresql: Remove inaccurate comment.

---

web/shared/icons/sort-arrow-down.svg
web/styles/app_components.css
web/styles/recent_view.css
web/templates/recent_view_table.hbs
web/templates/settings/active_user_list_admin.hbs
web/templates/settings/alert_word_settings.hbs
web/templates/settings/attachments_settings.hbs
web/templates/settings/bot_list_admin.hbs
web/templates/settings/data_exports_admin.hbs
web/templates/settings/deactivated_users_admin.hbs
web/templates/settings/default_streams_list_admin.hbs
web/templates/settings/emoji_settings_admin.hbs
web/templates/settings/invites_list_admin.hbs
web/templates/settings/muted_users_settings.hbs
web/templates/settings/playground_settings_admin.hbs
web/templates/settings/user_topics_settings.hbs
web/templates/stream_settings/new_stream_users.hbs
web/templates/stream_settings/stream_members_table.hbs
web/templates/user_group_settings/new_user_group_users.hbs
web/templates/user_group_settings/user_group_members_table.hbs

This PR rids Zulip of a fairly well-buried FontAwesome use. While that is a worthy goal in and of itself, the motivation behind the change here is to avoid irksome column-width shifts when hovering over column headers, caused by the previous insertion of an icon via `::after` and `content:`. When column headers were narrower than the content they marked, this shift always presented itself.
With the settings tables adjusted, it only made sense to give the same better-looking arrow treatment to the recent view.
Note that the `sort-arrow-down.svg` icon is effectively a duplicate of `arrow-down.svg`.
CZO issues:
* [#issues > column expands unnecessarily (Muted users)](https://chat.zulip.org/#narrow/channel/9-issues/topic/column.20expands.20unnecessarily.20.28Muted.20users.29)
* [#issues > …

sortable_tables: Place new arrows on all settings tables, recent conversations.

---

web/styles/message_row.css

| ------ | ----- |
| ![before](https://github.com/user-attachments/assets/7d3fa57e-bfd7-4b17-8f67-8276b08244f7)|![after](https://github.com/user-attachments/assets/0a490d13-878c-4238-a69c-0feecb3a71e5) |
Fixes: [#feedback > Copy button for View Original Message](https://chat.zulip.org/#narrow/channel/137-feedback/topic/Copy.20button.20for.20View.20Original.20Message)

message_row: Restore copy button in edit textbox.

---

zerver/lib/subscription_info.py
zerver/lib/types.py
zerver/tests/test_subs.py

We're doing this so that the client can keep track of which channels it might need to request full subscriber data from, and which already have full subscriber data.
As discussed [here]([#api design > trimming subscriber data #34244 @ 💬](https://chat.zulip.org/#narrow/channel/378-api-design/topic/trimming.20subscriber.20data.20.2334244/near/2142215))
Part of  #34244

subscription_info: Send partial subscriber info to client separately.

---

web/styles/app_components.css
web/styles/message_row.css
web/styles/zulip.css

`visibility` cannot be animated since it is a boolean.
Composition for some transition still fails which seems related to how the browser's rendering engine works to reduce load on CPU when performing animations.
Not sure if it is worth digging more here. 
discussion: https://chat.zulip.org/#narrow/channel/6-frontend/topic/message_control_button.20animations/with/2140570
Comparison when scrolling combined feed:
| --- | --- |
| ![Screenshot from 2025-03-31 09-59-48](https://github.com/user-attachments/assets/341acfea-e95e-46d3-96db-19748922adc3) | ![Screenshot from 2025-03-31 11-09-08](https://github.com/user-attachments/assets/a68a03cb-0ac4-4463-8b18-a7df349ca25e) |

css: Remove unused transition property.

---

web/src/upload.ts
web/tests/upload.test.cjs

While uploading a file, if you close the compose box, and reopen it, compose send button remains disabled due to upload in progress being true.
To fix it, we update upload status for compose when upload is cancelled.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/leaked.20uploading.20files.20state

upload: Fix send button disabled when compose is closed during upload.

---

web/e2e-tests/stream_create.test.ts
web/src/stream_create_subscribers.ts
web/src/user_group_create_members.ts
web/templates/stream_settings/new_stream_user.hbs
web/templates/user_group_settings/new_user_group_subgroup.hbs

This PR updates the "Add" and "Remove" buttons in the channel/group creation modal to use the action button component.
Fixes part of #33027.
**Channel Creation**
| ![Screenshot 2025-03-24 at 10 19 45 AM](https://github.com/user-attachments/assets/332f3bd5-d3db-45f8-acee-7ee6d710d8e5) | ![Screenshot 2025-04-03 at 5 58 45 PM](https://github.com/user-attachments/assets/2de4fea5-9a90-41d1-a208-310b5087a037) | 
| ![Screenshot 2025-03-24 at 10 16 19 AM](https://github.com/user-attachments/assets/4ccb869b-d2a6-40e7-a9ec-bd9c3c6c2bb9) | ![Screenshot 2025-04-03 at 5 59 07 PM](https://github.com/user-attachments/assets/19118e11-2a37-46ac-9d42-4baf3f2f0c78) | 
**Group Creation**
| …

settings: Update add/remove buttons on channel/group creation.

---

web/src/user_profile.ts
web/styles/dark_theme.css
web/styles/modal.css
web/styles/popovers.css
web/templates/user_profile_modal.hbs

This PR updates the modal header buttons to use the icon button component.
Fixes part of #33027.
**1. Normal User**
| ![Screenshot 2025-03-24 at 10 27 31 AM](https://github.com/user-attachments/assets/1c77c903-e4f7-4092-b2a8-52b18248bd33) | ![user_profile_header_buttons-light-after](https://github.com/user-attachments/assets/1d292544-9682-43d2-ad3a-35a70f4f0032) |
| ![Screenshot 2025-03-24 at 10 27 22 AM](https://github.com/user-attachments/assets/5a4e3d5b-8616-4dca-921d-f55245f833be) | ![user_profile_header_buttons-dark-after](https://github.com/user-attachments/assets/eb075bdd-200e-4785-a7a4-d4b7c3e74848) | 
**2. Bot User**
| ![Screenshot 2025-03-24 at 10 28 …

user_profile_modal: Use icon button component for modal header buttons.

---

web/src/stream_popover.ts

This PR solves bugs being found in moving messages/topics in the move topic modal.
Fixes: [#issues > mis-alignment of typeahead in move topic/messages modal](https://chat.zulip.org/#narrow/channel/9-issues/topic/mis-alignment.20of.20typeahead.20in.20move.20topic.2Fmessages.20modal).
---
**First commit**: [message_move: Initialize ResizeObserver for Rename topic modal.](https://github.com/zulip/zulip/pull/34203/commits/00691cc9eb4fdeb173d816612aa1394af1fe61e4)  
Steps to reproduce:  
1. Ensure the current user has permission only to rename a topic.  
2. In a channel (e.g., `#test`), create 2-3 topics with the same initial characters (e.g., 1, 12, 123).  
3. Open the "Rename Topic" modal from the left sidebar for a topic (e.g., 1).  
4. In the "Rename Topic" field, type another topic with …

message_move: Fix some bugs found in moving messages/topics.

---

api_docs/changelog.md
version.py
zerver/actions/users.py
zerver/openapi/zulip.yaml
zerver/tests/test_events.py

Fixes #34245.
<details>
</details>

users: Send peer_remove on deactivating user.

---

web/styles/app_components.css
web/styles/app_variables.css
web/styles/dark_theme.css

This PR includes two fixes mentioned in comments on #34263:
1. It fixes a bleed-through bug in Chrome where the underlying table background would appear at certain points between table-header cells. (This fix also removes the need for `!important` on the `:hover` style, and does some nice cleanup--including some unreachable styles--in `dark_theme.css`.)
2. It prevents table headers or their sort icon from wrapping onto a second line. Because tables are scrollable when they don't entirely fit in the viewport, the potentially wider columns are arguably nicer looking than their collapsing counterparts.
| --- | --- |
| ![table-headings-light-before](https://github.com/user-attachments/assets/8a0830a9-1f66-4e5a-bb81-5b54ea8f1ddb) | …

settings_tables: Fix background color, heading collapsing.

---

zerver/views/registration.py

We need `corporate_enabled` and some other params to render 500 error page which is not passed when using `server_error`, as it only contains our custom inserted `DEFAULT_PAGE_PARAMS`.
We render the page with `zulip_default_context` to fix this.
discussion: https://github.com/zulip/zulip/pull/34187#issuecomment-2777250602

registration: Fix 500 error pages rendered without context.

---

web/src/peer_data.ts
web/src/stream_data.ts
web/src/stream_types.ts
web/tests/stream_data.test.cjs

Work towards #34244. This shouldn't change production at all, since we only send partial_subscribers when a dev flag is set.

peer_data: Process partial_subscriber data.

---

web/src/group_permission_settings.ts
web/src/server_events_dispatch.js
web/src/settings_components.ts
web/src/user_group_edit.ts
web/tests/lib/example_settings.cjs
web/tests/user_groups.test.cjs

- First commit is to refactor live update code for group permission settings.
- Second commit is to live update UI on updating `can_manage_all_groups` setting.
- Third commit is to disable checkbox when permission cannot be removed due to setting not being allowed to set to nobody group.
Fixes part of #33730. 
<details>
</details>

Minor fixes for group settings.

---

web/src/stream_edit_subscribers.ts
web/src/user_group_edit_members.ts
web/src/user_profile.ts
web/styles/popovers.css
web/styles/subscriptions.css
web/templates/components/action_button.hbs
web/templates/stream_settings/stream_member_list_entry.hbs
web/templates/user_group_list_item.hbs
web/templates/user_group_settings/user_group_subgroup_entry.hbs
web/templates/user_profile_modal.hbs
web/templates/user_profile_subscribe_widget.hbs
web/templates/user_stream_list_item.hbs

This PR updates the remove and unsubscribe buttons in user profile modal, channel settings and user group settings to use the action button component.
Fixes part of #33027.
| ![Screenshot 2025-03-28 at 2 00 09 AM](https://github.com/user-attachments/assets/dec3fab1-0dfd-4035-8e93-f01399becda8) | ![Screenshot 2025-03-28 at 1 55 40 AM](https://github.com/user-attachments/assets/48aad621-c92f-4633-9c55-8a29defba530) |
| ![Screenshot 2025-03-28 at 1 59 47 AM](https://github.com/user-attachments/assets/a447eb0f-5902-4356-b49e-1d96c4cf2ba9) | ![Screenshot 2025-03-28 at 1 58 22 AM](https://github.com/user-attachments/assets/4c789845-e6dd-429b-a49b-853ceadb0013) |
| ![Screenshot 2025-03-28 at 2 00 …

settings: Update remove/unsubscribe buttons to action button component.

---

zerver/actions/user_settings.py
zerver/tests/test_audit_log.py

We forgot to store the actual values in the audit log, making these logs not very helpful in actually auditing a user's email change history.

do_change_user_email: Store old and new email in the audit log.

---

web/styles/app_variables.css
web/styles/compose.css
web/styles/dark_theme.css

This PR cleans up dark theme for all references to the compose banners (`.main-view-banner`).
With this work, `dark_theme.css` drops from ~725 lines down to ~585 lines.

dark_theme: Clean up compose banners.

---

zerver/actions/message_send.py
zerver/lib/cache.py
zerver/lib/email_mirror.py
zerver/lib/user_groups.py
zerver/models/groups.py
zerver/models/users.py
zerver/tests/test_auth_backends.py
zerver/tests/test_email_mirror.py
zerver/tests/test_example.py
zerver/tests/test_invite.py
zerver/tests/test_message_send.py
zerver/tests/test_subs.py
zerver/tests/test_user_groups.py
zerver/views/user_groups.py

- First commit is a refactor commit.
- Second commit is to not prefetch DM permission group settings.
Fixes part of #33677. 
<details>
</details>

Avoid prefetching DM permission group settings.

---

web/src/banners.ts
web/src/buttons.ts
web/src/settings_components.ts
web/src/settings_org.ts
web/src/types.ts
web/styles/app_components.css
web/styles/dark_theme.css
web/styles/settings.css
web/styles/subscriptions.css
web/templates/settings/account_settings.hbs
web/templates/settings/notification_settings.hbs
web/templates/settings/organization_user_settings_defaults.hbs
web/templates/settings/preferences_general.hbs
web/templates/settings/settings_save_discard_widget.hbs
web/tests/settings_org.test.cjs

This PR updates the save and discard buttons in the setting modals to use redesigned button styles along with the new loading indicator.
Fixes: [#issues > 🎯 save/discard buttons misaligned on some browsers @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20save.2Fdiscard.20buttons.20misaligned.20on.20some.20browsers/near/2124637)
| ![Screenshot 2025-03-20 at 2 55 42 AM](https://github.com/user-attachments/assets/bc0ba408-32b5-4c17-afc5-f7c4bd047a1c) | ![Screenshot 2025-03-20 at 2 54 44 AM](https://github.com/user-attachments/assets/77393ef1-517e-4607-925a-d7543bfb641c) |
| ![Screenshot 2025-03-20 at 2 56 15 AM](https://github.com/user-attachments/assets/5658a59b-d256-4ad7-a234-3544d373f5b2) …

settings: Update save and discard buttons to redesigned button styles.

---

web/src/stream_popover.ts
web/styles/popovers.css
web/templates/move_topic_to_stream.hbs

This PR adds an `x` button to the topic field in the move topic/move messages modal.
Fixes: #33729.
<details>
<summary> Added `x` button to topic field in move topic/move messages modal.</summary>
| Description                          | Screenshot |
|--------------------------------------|------------|
| Move topic/messages modal           | ![Move topic/messages modal](https://github.com/user-attachments/assets/91a3ca2d-10c0-46a9-8f8a-4c93dd86e020) |
| Rename topic modal                   | ![Rename topic modal](https://github.com/user-attachments/assets/cd06de71-feb3-434e-a8bf-7253718d35d3) |
| `x` button is hidden for empty topic field - move topic modal | ![`x` button hidden - move topic modal](https://github.com/user-attachments/assets/c219ce68-53 …

popovers: Add an `x` button to topic field in move topic/move messages modal.

---

web/src/user_card_popover.ts
web/templates/message_avatar.hbs

User card popover was not displayed even when "View user card" tooltip is visible in some areas. To fix it, we introduce a wrapper element which has the same trigger area as the tooltip.
We don't directly use the `view_user_card_tooltip` element to trigger popover since tippy doesn't play nice with two tippy instances attached to the same element.
clickable area for both user card tooltip and popover (aside from user name)

user_card: Fix mismatch between tooltip and popover trigger area.

---

web/e2e-tests/admin.test.ts
web/src/settings_components.ts

This PR prevents the save button in the save discard widget from showing the "Saved" label when the user has made some other changes in the settings while the saving process was in action — which resulted in the "Save changes" label in the save button, and thus shouldn't be replaced with "Saved".
This PR also fixes the failing puppeteer tests in `web/e2e-tests/admin.test.ts` which was introduced in https://github.com/zulip/zulip/pull/34081.
Fixes: [#issues > 🎯 save/discard buttons misaligned on some browsers @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20save.2Fdiscard.20buttons.20misaligned.20on.20some.20browsers/near/2148415)
| …

settings: Prevent save discard widget override.

---

web/e2e-tests/admin.test.ts

Fixes: [#issues > 🎯 save/discard buttons misaligned on some browsers @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20save.2Fdiscard.20buttons.20misaligned.20on.20some.20browsers/near/2148415)
<details>
</details>

tests: Fix admin.test.ts puppeteer test case failing.

---

web/src/server_events_dispatch.js

Groups UI is now live updated when can_manage_all_groups is changed.
Backported a04ee8a8b84a from #34205.
<details>
</details>

Backported live update fix from #34205.

---

web/src/resize.ts
web/src/stream_create.ts
web/src/stream_settings_ui.ts
web/src/user_group_create.ts
web/src/user_group_edit.ts
web/styles/app_variables.css
web/styles/subscriptions.css
web/templates/stream_settings/stream_creation_form.hbs
web/templates/user_group_settings/user_group_creation_form.hbs

prep for #34125
We need this height to be flexible based on if the subheader has overflowed into two rows or not, and our method of doing this (with existing examples in the buddy list and stream list) is to calculate what the height should be when a window is loaded or resized.

settings: Calculate height of create modal through javascript.

---

web/src/postprocess_content.ts
web/styles/app_variables.css
web/styles/dark_theme.css
web/styles/rendered_markdown.css
web/tests/postprocess_content.test.cjs

This PR makes use of image dimensions on thumbnails in order to present thumbnails without a gray box around them, except in the case of "dinky" images.
Previously, images were held to a 12em × 8em box. The consequence of that was that the same size image in landscape orientation would appear physically larger than the same size but in portrait orientation.
To fix for that, the previous 12em × 8em box is here replaced for image thumbnails as a 10em × 10em box, meaning that neither portrait nor landscape images are favored in terms of which appears visibly larger.
A planned follow-up to this PR is to present image galleries using flexbox (a draft effort of this is in #31689), but to reduce churn and make these changes easier to review and burn in on CZO, the `inline-block`-style …

thumbnails: Better size and present thumbnails in message area.

---

templates/zerver/base.html

This seems to be required for [webpack-dev-server 5.2.1](https://github.com/webpack/webpack-dev-server/releases/tag/v5.2.1), for reasons that have not yet been made public. This relies on the `Access-Control-Allow-Origin: *` header that we already set for static content in both development and production.
[Discussion](https://chat.zulip.org/#narrow/channel/49-development-help/topic/create.20new.20realm.20not.20loading.20CSS/near/2150761). MDN documentation: [`crossorigin`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/crossorigin), [`Access-Control-Allow-Origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Access-Control-Allow-Origin).

webpack: Use CORS requests for stylesheets

---

zerver/actions/streams.py
zerver/tests/test_events.py
zerver/tests/test_subs.py
zerver/tests/test_users.py

Earlier, we used to send a single event for all web-public and public streams. But public streams can have guests, which means the peer user ids for each of them can be different based on which guests are subscribed to which channel.
In the previous code, we were using the last stream id from another loop to get subscribers, which was causing a lot of non-deterministic failures in our test, since that stream id could keep on changing. Moreover, it doesn't make much sense to use that id here. This commit still keeps around the optimisation for public channels with non-guest users. It will send one event for all public channels with non-guest users, one for web public channels and for the rest of the channels it will send an event for each channel with a different set of peer user ids. …

streams: Send different peer events for web & non-web public streams.

---

zerver/lib/narrow.py
zerver/tests/test_message_fetch.py

The `type_id` is the id of a `UserProfile`, `Stream`, or `DirectMessageGroup`, not the id of a type.

narrow: Fix get_base_query_for_search access restrictions

---

web/styles/left_sidebar.css
web/templates/more_topics.hbs

This PR adds href attribute so that pressing the Enter key works on the anchor element.
https://github.com/user-attachments/assets/5c09d0f0-9d1f-4c0d-80d1-9aa1569bfbfb
<details>
</details>

left_sidebar: Fix Enter key behavior on "Show all topics" link.

---

web/src/settings_notifications.ts
web/templates/settings/notification_settings.hbs

Display a yellow warning banner in the desktop notifications settings when browser permissions are not granted (default/denied states).
Hide the "Send a test notification" button when permission state is "default" or "denied".
Fixes: [Link](https://github.com/zulip/zulip/issues/33222)
Dark Theme:
Light Theme:
When clicked on Enable Permissions button:
When Notifications allowed Send a Test Notification button is made visible:
<details> …

settings: Show desktop notifications warning when permissions needed.

---

puppet/kandra/manifests/profile/chat_zulip_org.pp
puppet/kandra/manifests/profile/smokescreen.pp
puppet/kandra/templates/prometheus/prometheus.yaml.template.erb
puppet/zulip/templates/supervisor/smokescreen.conf.erb

This prevents errors if Smokescreen is running on a host with more than 10 Tornado shards.
Fixes: 
<details>
</details>

smokescreen: Move metrics port from the default 9810, to 4760.

---

web/src/drafts_overlay_ui.ts
web/src/messages_overlay_ui.ts
web/src/scheduled_messages_overlay_ui.ts
web/templates/draft.hbs
web/templates/scheduled_message.hbs
web/tests/drafts.test.cjs

discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.22Restore.20Draft.22.20tooltip.20in.20drafts.20overlay.2E
To avoid restore tooltip of message from being displayed outside the overlay, we define a boundary, outside which the tooltip cannot exist. Popper library is smart enough to render the tooltip correctly by respecting the provided boundary and flipping the tooltip placement if required.
**before:**
**after:**
**Top placement:**
**bottom placement**
**top placement when message doesn't fit in scrollable space.**
**Schedule message overlay**

message_overlay: Fix restore tooltips detached with message content.

---

web/src/topic_list.ts
web/styles/left_sidebar.css

This PR corrects some bugs introduced in #34340 that broke topic filtering (stale references to `#filter-topic-input`, which that PR removed). It also removes what appear to be unnecessary `#stream_filters` components to the left sidebar CSS, whose extremely high specificity prevented existing CSS intended to hide the topic-grouping brackets when zoomed in.
I've also added a subtle fix to keep the filter input box from butting up against the righthand edge of the highlighted channel area, when filtering in that state.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/Topic.20filtering.20is.20broken/near/2152018)
| --- | --- |
| ![left-sidebar-filtering-bugs-before](https://github.com/user-attachments/assets/9fe997a4-39 …

left_sidebar: Fix bugs that broke topic filtering.

---

zerver/models/messages.py

[#backend > general chat - migration discussion @ 💬](https://chat.zulip.org/#narrow/channel/3-backend/topic/general.20chat.20-.20migration.20discussion/near/2111414):
> We no longer need the zerver_message_edit_history_id index added in 0679... in 0680..., should we add a new migration to remove that index or we want to keep that:
> I think that migration may be helpful for other things, so no reason to remove it.
PR to remove a misleading comment regarding `zerver_message_edit_history_id` index.
<details> …

messages: Drop misleading comment on `zerver_message_edit_history_id` idx.

---

web/styles/zulip.css

change 'z' logo dimensions so that it scales according to chosen font size.
Fixes: #34266 
<details>
</details>

message_feed UI: Update logo dimensions for better scalability.

---

zerver/actions/create_user.py
zerver/actions/message_send.py
zerver/actions/streams.py
zerver/lib/email_mirror.py
zerver/lib/message.py
zerver/lib/streams.py
zerver/lib/user_groups.py
zerver/lib/users.py
zerver/models/users.py
zerver/tests/test_email_mirror.py
zerver/tests/test_event_system.py
zerver/tests/test_invite.py
zerver/tests/test_message_send.py
zerver/tests/test_signup.py
zerver/tests/test_subs.py
zerver/tests/test_user_groups.py
zerver/tests/test_users.py

- First two commits are refactor commits.
- Last commit is to update code to not prefetch setting.
<details>
</details>

Do not prefetch `can_access_all_users_group` setting in user queries.

---

web/src/popup_banners.ts

This PR updates the connection error banner label to "Unable to connect to Zulip. Trying to reconnect!" when the the user manually retries the connection via the "Try now" button and when the retry time is less than 5 seconds.
Fixes: [](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Glitchy.20connection.20error.20popup.20banner/near/2127631)[#issues > 🎯 Glitchy connection error popup banner @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Glitchy.20connection.20error.20popup.20banner/near/2127631)
| ![Screenshot 2025-03-21 at 8 34 47 PM](https://github.com/user-attachments/assets/fc8927f6-32be-4848-9a76-51b1f7476e9b) | ![Screenshot 2025-04-12 at 4 27 …

popup_banners: Update connection error banner label.

---

web/src/compose_banner.ts
web/src/compose_recipient.ts
web/src/compose_state.ts
web/src/compose_validate.ts
web/src/message_events.ts
web/templates/compose_banner/topic_moved_banner.hbs
web/templates/inline_topic_link_label.hbs

This PR adds the INFO compose banner for new channel/topic when the recipient is updated when topic is moved.
banner details:
- Text: The topic you were composing to ([# channel > topic](https://github.com/zulip/zulip/issues/33445)) was moved, and the destination for your message has been updated to its new location.
- Color: blue
- Buttons: just an `x`
fixes: #33445
| Dark Theme     | ![Changes visible in alignment and hover](https://github.com/user-attachments/assets/1849b339-fde4-4f12-bd56-11be3e68f4be)    |
| Light Theme  | ![dm](https://github.com/user-attachments/assets/81a5d987-216a-416e-8860-d8b9ab27a644) |
| Empty …

compose: Add banner when topic is moved and recipient is updated.

---

web/src/narrow_banner.ts
web/tests/message_view.test.cjs

Fixes #31601
This pull request updates the channel feed to display different text for muted topics. The changes ensure that users can don't get confused when there is a message only in the muted topics.
When the topics are not muted (same): 
|Before|After|
|----|----|
|<img width="1440" alt="Screenshot 2024-09-15 at 9 23 47 PM" src="https://github.com/user-attachments/assets/4e32e365-945a-435e-83e6-2cac28a01c18">|<img width="1440" alt="Screenshot 2024-09-15 at 9 23 47 PM" src="https://github.com/user-attachments/assets/4e32e365-945a-435e-83e6-2cac28a01c18">|
When the topics are muted: 
|Before|After|
|----|----|
|<img width="1440" alt="Screenshot 2024-09-15 at 9 26 57 PM" src="https://github.com/user-attachments/assets/c97274e8-0d57-49fc-b0ea-be56310eff68">|<img width="1440" …

feed: Modify the channel feed text for muted topics.

---

docs/subsystems/schema-migrations.md

The following error mentioned in [Schema migrations doc](https://zulip.readthedocs.io/en/latest/subsystems/schema-migrations.html#:~:text=Another%20important%20note)
```shell
django.db.utils.OperationalError: cannot ALTER TABLE "table_name" because it has pending trigger events
```
Saying:
> the reason is often that these operations were incorrectly mixed
is very ambiguous, so I did my search to find the actual cause for that error, hence better understandability and experience for our developers.
See [Information source](https://support.atlassian.com/confluence/kb/upgrade-failed-with-the-error-message-error-cannot-alter-table-content-because-it-has-pending-trigger-events/#:~:text=for%20all%20constraint.-,Cause,-By%20default%2C%20the)
See [updated …

doc: Add an error explanation in schema migrations.

---

web/src/bootstrap_typeahead.ts
web/src/stream_edit_subscribers.ts
web/src/stream_settings_components.ts
web/src/user_groups.ts
web/templates/confirm_dialog/confirm_unsubscribe_private_stream.hbs

- First commit is to fix warning in modal when unsubscribing last user from a private stream.
- Second commit is to not show the modal when user can subscribe again to the private stream.
- Third commit is to not show typeahead on clicking on the disabled input.
Screenshots for modified warning in first commit
| When last user is someone else | When last user is the user themselves|
| --------- | --------- |
|![Screenshot from 2025-04-14 09-19-21](https://github.com/user-attachments/assets/0066170d-0ee8-44c1-b059-2659913c61b5) |![Screenshot from 2025-04-14 09-17-38](https://github.com/user-attachments/assets/a5107baa-e166-4f8f-a13f-22763f4b544c) |
Changes in second commit
| --------- | ------- | …

Minor fixes in stream settings UI.

---

zerver/actions/streams.py
zerver/migrations/0210_stream_first_message_id.py
zerver/tests/test_digest.py
zerver/tests/test_events.py
zerver/tests/test_import_export.py
zerver/tests/test_message_send.py
zerver/tests/test_retention.py
zerver/tests/test_subs.py
zerver/tests/test_user_topics.py

A Prep-PR to [stream: Add subscriber_count field.](https://github.com/zulip/zulip/pull/34308)
Explicitly pass the fields to be updated, This increases performance but most importantly prevents overwriting the db-saved value of `subscriber_count` field (added in #34308) with the in-memory default value of 0,
since `subscriber_count` will **only** be updted via db.
Migrate some tests to use `do_` functions instead of direclty modifying the state.

tests: clean tests and pass update_fields to all stream.save() 

---

help-beta/.gitignore
help-beta/astro.config.mjs
help-beta/package.json
help-beta/src/middleware.ts
pnpm-lock.yaml
tools/convert-help-center-docs-to-mdx
version.py

Run `./tools/build-help-center` to test this.
Fixes: https://github.com/zulip/zulip/issues/31252
One of our major use cases for file imports is to have bullet points as partials to import at different places in the project. But when importing the file with Astro, it creates its own lists. So we merge lists together if they have nothing but whitespace between them.
There were some talks to use a component called FlattenList that would flatten the list inside it, but that would also flatten lists that were nested on purpose. This approach while feeling a bit hacky would not flatten nested lists.
The uneven spacing between the bullet points is not related to this issue and can be tackled separately at …

help-center-stage-2: Add support for including files.

---

templates/zerver/base.html
web/webpack.config.ts

This middleware in webpack-dev-server 5.2.1 appears to be intended to
plug some undisclosed browser-specific vulnerability that allows
stealing code from closed-source projects.
- [Discussion](https://chat.zulip.org/#narrow/channel/49-development-help/topic/create.20new.20realm.20not.20loading.20CSS/near/2150761).
- Followup to #34359.

webpack: Disable cross-origin-header-check middleware

---

zerver/actions/streams.py
zerver/lib/streams.py
zerver/tests/test_subs.py
zerver/views/streams.py

This PR solves the issue which is described in this [comment](https://github.com/zulip/zulip/issues/30212#issuecomment-2246375514) as the original issue was already solved by updating the translation.
Note: "Channel created" event messages aren't sent for public_protected_history channels available only in Zephyr realms. This is an existing behaviour and this PR doesn't change that.
as the Previous PR #31009 for this issue was near completion I only had to fix conflicts.
[CZO discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/.F0.9F.93.82.C2.A0.20Inconsistent.20localization.20in.20new.20channel.20notif.20.2330212)
Fixes: #30212
<table border="1">
<tr>
<th>Before/main branch</th>
<th>After/issue#30212 branch</th>
</tr>
<tr>
<td><img …

Construct new channel notification message as a whole string rather than gluing strings together

---

web/styles/app_variables.css
web/styles/message_row.css
zerver/tests/test_muted_users.py

This PR fixes a regression introduced in #34354, which did not remove a compounding opacity value made unnecessary by the `color-mix()` function.
Additionally, this corrects misspelled CSS variables and some test variables: `mesaage` > `message`.
CZO discussion
_Bookends:_
| --- | --- |
| ![bookend-light-before](https://github.com/user-attachments/assets/b13f4d1e-2c40-44a0-a0de-91fda3e76233) | ![bookend-light-after](https://github.com/user-attachments/assets/8cc83c2d-9597-4514-8ac3-0e3cfd9d510a) |
| ![bookend-dark-before](https://github.com/user-attachments/assets/14c4bd40-71d7-46f4-8a72-abd85c60a619) | ![bookend-dark-after](https://github.com/user-attachments/assets/383ee3a5-ee36-4c76-84b4-87fe81e20670) |
_Datelines:_
| Before | …

message_feed: Correct regression on dateline, bookend borders.

---

api_docs/changelog.md
web/src/click_handlers.ts
web/src/message_edit.ts
web/src/util.ts
web/tests/util.test.cjs
zerver/actions/message_edit.py
zerver/lib/exceptions.py
zerver/lib/utils.py
zerver/openapi/python_examples.py
zerver/openapi/zulip.yaml
zerver/tests/test_message_edit.py
zerver/views/message_edit.py

Similar to group based setting values, we expect
the client to send the previous content alongwith
the edited content to the edit message endpoint.
We reject the request incase the previous content
doesn't match the current message content, which
could happen in case two users simultaneously edit a message
(to be implemented in #33051).
This PR is a prep to #33051.
*Intentionally disabling the message edit event so that two clients are no longer synced, then trying to edit the message*
<details> …

message_edit: Check previous message content to prevent races.

---

web/src/portico/showroom.ts
web/styles/banners.css

Changes:
- Updates the **banner-link** class to have "text-decoration: none" set, instead of underline.
- Updates the desktop notification banner text in the devtools testing of banners in `showroom.ts` to match what's currently used in `navbar_alerts.ts`, so that the only place that the **banner-link** class is currently used is on the demo organization deletion deadline alert.
| Where | Screenshot |
| --- | --- |
| Current banner in web app | ![Screenshot from 2025-04-17 15-47-19](https://github.com/user-attachments/assets/dc63eb5b-98e1-4524-b435-56d556e35a69) |
| Banner in showroom before changes | ![Screenshot from 2025-04-17 15-45-12](https://github.com/user-attachments/assets/96d6826c-f8ca-4785-b1df-689789739ca6) |
| Banner in showroom after …

navbar-banners: Update banner-link class for no underline (without hover).

---

corporate/lib/activity.py

Show "Fixed" as the rate with `CustomerPlan.fixed_price` is not `None` in the support activity charts.
| --- | --- |
| ![Screenshot from 2025-04-21 13-26-36](https://github.com/user-attachments/assets/2fefdbfa-7140-4da5-9083-544fcb42f7cc) | ![Screenshot from 2025-04-21 13-26-09](https://github.com/user-attachments/assets/cef751d0-eff0-4977-8844-1545b7c9364e) |
---
<details>
</details>

corporate: Show "Fixed" as rate for fixed-rate plans in activity charts.

---

web/src/compose_validate.ts

Fixes: [](https://chat.zulip.org/#narrow/channel/101-design/topic/validation.20tooltip.20in.20message.20edit.20same.20as.20compose.3F/near/2149696)[#design > validation tooltip in message edit same as compose? @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/validation.20tooltip.20in.20message.20edit.20same.20as.20compose.3F/near/2149696)
| Message length exceeded | Time limit expiry AND message length exceeded |
|-------|-------|
| ![message-length-exceeded-1744339530524](https://github.com/user-attachments/assets/d16bffdd-8d11-4faf-8629-d93093bde1ce)| ![time-limit-expired-plus-long-message-1744339704525](https://github.com/user-attachments/assets/22fba21b-ca61-4f87-9b8a-0a38d22965f8)|
| Message Length Exceeded | Time limit expiry AND …

Add save btn tooltip for exceeded message length

---

web/src/hotkey.js
web/tests/hotkey.test.cjs

Previously, when in anonymous login, pressing the "view original message" button showed the original message and allowed copying it. However, the corresponding keyboard shortcut ('e') did not work as expected and a login pop-up appeared instead.
Now, by fixing the UI features' permissions for anonymous users, by adding "edit_message" as a feature they can perform, they are allowed to use the 'e' keyboard shortcut as intended.
Additionally, I added a test to ensure the bug is properly fixed.
Fixes: #33838 
What happened before the fix:
https://github.com/user-attachments/assets/eabc1f06-2556-4626-9edc-190aeced3acc
What happens now, after the fix:
https://github.com/user-attachments/assets/dc70973c-5774-4562-b950-76d6f2587892
<details> …

keyboard_UI: fix #33838 'e' keyboard shortcut for anonymous user.

---

zerver/openapi/zulip.yaml

Adds "Present if realm is present in fetch_event_types" to the fields in the `POST /register` response that are added to the state data via `fetch_initial_state_data` in the `if want("realm")` block.
[Relevant CZO conversation](https://chat.zulip.org/#narrow/channel/412-api-documentation/topic/.60.2Fregister.60.3A.20fields.20missing.20.22Present.20if.20.5B.E2.80.A6.5D.22.3F/near/1707782)
<details>
<summary>API docs diff</summary>
```diff
diff -r -B -u current_api_html/register-queue.html new_api_html/register-queue.html
--- current_api_html/register-queue.html	2025-04-18 13:31:15.468052537 +0200
+++ new_api_html/register-queue.html	2025-04-18 13:30:35.622051689 +0200
@@ -856,13 +856,15 @@
</li>
<li>
<p><code>realm_date_created</code>: <span class="api-field-type">integer</span></p> …
```

api-docs: Add note about realm being present in fetch_event_types.

---

web/styles/settings.css
web/templates/settings/preferences_information.hbs
web/templates/settings/preferences_navigation.hbs
web/templates/settings/settings_numeric_input.hbs

This PR removes the `thinner` CSS class from the "Play animated images" setting. It applies the class to the "Show unread counts for" setting, since the next setting, "Show counts for starred messages" is related to it.
Hence, the bottom margin for the "Play animated images" setting is changed to `20px` (initially it was `10px`). 
For the "Show unread counts for" setting, the bottom margin is set to `10px` (initially it was `20px`), since the next setting, "Show counts for starred messages", is related to it.
Fixes: [#34226 (comment)](https://github.com/zulip/zulip/pull/34226#discussion_r2026449812).
- In Personal settings > Preferences:
| Description | Before | After |
|-------------|--------|-------|
| "Home view" setting | …

css: Remove `.thinner` class used in Settings > Preferences.

---

zerver/lib/message.py

[#automated testing > main failing @ 💬](https://chat.zulip.org/#narrow/channel/43-automated-testing/topic/main.20failing/near/2157045)
> This is probably a real bug of some sort, at least I'd hope that test_unreads_case_insensitive_topics is written correctly to look for bugs in the handling of that:
> File "/__w/zulip/zulip/zerver/tests/test_event_system.py", line 850, in test_unreads_case_insensitive_topics
self.assertEqual(result["unread_msgs"]["streams"][0]["topic"], "case DOES not MATTER")
^^^^^^^^^^^^^^^^^
File "/__w/zulip/zulip/zerver/lib/test_classes.py", line 289, in assertEqual
raise AssertionError(
^^^^^^^^^^^^^^^^^
AssertionError: Actual and expected outputs do not match; showing diff.
-CASE does NOT matter
+case DOES not MATTER
I wasn't able to replicate/verify this locally, …

unread_data: Ensure deterministic ordering of unread message rows.

---

api_docs/changelog.md
api_docs/roles-and-permissions.md
version.py
web/src/message_edit.ts
web/src/people.ts
web/src/popover_menus_data.ts
web/src/user_events.ts
web/tests/message_edit.test.cjs
web/tests/people.test.cjs
web/tests/user_events.test.cjs
zerver/actions/message_edit.py
zerver/lib/events.py
zerver/lib/user_groups.py
zerver/lib/users.py
zerver/models/users.py
zerver/openapi/zulip.yaml
zerver/tests/test_subs.py
zerver/tests/test_users.py
zerver/views/development/dev_login.py

This PR could use some testing for moderator related features to make sure we haven't introduced any regressions. That should be done after a code review though I think, since it would be easier to spot any potential mistakes with code first in this case.
<details>
</details>

users: Return true for admins for is_moderator.

---

web/src/postprocess_content.ts
web/styles/rendered_markdown.css
web/tests/postprocess_content.test.cjs

This PR introduces new processing to place adjacent images into a single container, which then gets displayed as a flexbox. This is the most minimal implementation, and apart from reduced but now horizontally and vertically uniform space between rows of wrapping images, there are no visual changes here except in cases of images appearing inside of lists. Those images now display in their own block, and not inline with list content (an unintentional side-effect of the `display: inline-block` scheme used previously).
This PR also fixes a regression on RTL messages introduced in #34208, where extra lefthand margin on images was not removed. However, _all_ RTL styles are removed in this PR, as flexbox respects the `.rtl { direction: rtl; }` style declared near line 958 of `zulip.css`, making …

thumbnails: Present thumbnails in flexbox galleries.

---

zerver/lib/attachments.py
zerver/tests/test_subs.py
zerver/tests/test_upload.py

Fixes https://chat.zulip.org/#narrow/channel/9-issues/topic/Can't.20view.20images.20in.20private.20channel.2E
<details>
</details>

attachments: Allow seeing attachments to users with content access.

---

web/src/invite.ts
web/styles/app_variables.css
web/styles/input_pill.css
web/templates/invite_user_modal.hbs

**Updates**:
- Only show the notification banners about setting up the organization information after the owner has set their email.
- Disable the submit button at all times if the owner hasn't set their email.
- Disable the email pill input div if the owner hasn't set their email.
**Notes**:
- When we remove `contenteditable: true` from the input div for the email address pills, we now also add a class to the `pill-container` div so that we can set a height on that element.
- I added a color variable so that the email input div wouldn't be an inconsistent color in light mode with the other disabled elements.
---
| --- | --- |
| ![Screenshot from 2025-04-24 17-21-00](https://github.com/user-attachments/assets/b1674a83-6ef3-4c65-afaa-f …

demo-orgs: Fix invite user modal when owner hasn't set an email address.

---

zerver/lib/rest.py
zerver/tests/test_bots.py

This will help audit the usage of this in chat.zulip.org and Zulip cloud.
Fixes part of #1403.
<details>
</details>

rest_api: Add logging to REST path.

---

help/manage-user-groups.md

I think this is good enough for documenting #34453, and we don't need to add dedicated instructions at this point to cover this + adding channel members.
Current: https://zulip.com/help/manage-user-groups#add-user-groups-to-a-group
Updated:

help: Document option to add the members of a group to a group.

---

templates/zerver/app/index.html
web/styles/inbox.css

discussion: https://chat.zulip.org/#narrow/channel/6-frontend/topic/text-decoration.3A.20underline/with/2161343
before:
after:
hover:

Remove underline from Inbox view recent conversation link.

---

web/styles/app_variables.css

The banner grid layout for the medium and small variants has 4 rows, while the previously described `grid-template-areas` only had the placement information for the first 3 rows.
This commit adds the spatial description of the banner elements in the the final row, fixing the alignment of the banner elements in the cases where there are no action buttons and only the banner label.
Related PR: #34433
| ![Screenshot 2025-04-18 at 1 10 24 AM](https://github.com/user-attachments/assets/b8666e9c-c572-419f-9285-1b978e9c2ea2) | ![Screenshot 2025-04-18 at 1 10 58 AM](https://github.com/user-attachments/assets/c5e72057-667b-4bb8-b0da-a3728f8388b1) | 
<details> …

banners: Fix banner grid layout for medium and small variants.

---

web/e2e-tests/settings.test.ts
web/src/alert_words_ui.ts
web/styles/settings.css
web/templates/settings/alert_word_settings.hbs
web/tests/alert_words_ui.test.cjs

This PR converts the alert words removal status alert to a banner component.
I have also opened #34432, for the layout issues I faced while working on this banner which has no buttons in it.
Fixes: [#frontend > bootstrap CSS reset removal @ 💬](https://chat.zulip.org/#narrow/channel/6-frontend/topic/bootstrap.20CSS.20reset.20removal/near/2145855)
| ![Screenshot 2025-04-18 at 2 14 27 AM](https://github.com/user-attachments/assets/88676c59-5810-497e-b59e-740fe8c36b82) | ![Screenshot 2025-04-18 at 2 13 08 AM](https://github.com/user-attachments/assets/8c003c43-c89a-4557-900d-830355b85c74) |
| ![Screenshot 2025-04-18 at 2 14 33 AM](https://github.com/user-attachments/assets/be4b0caa-2fef-4587-b4bb-f7666af55d3b) | …

alert_words: Use banner to indicate alert words removal status.

---

tools/linter_lib/custom_check.py
web/src/postprocess_content.ts
web/styles/app_variables.css
web/styles/rendered_markdown.css
web/tests/postprocess_content.test.cjs

This PR is an immediate followup to #34488. It does two primary things:
1) It opens up the height of the preview area to accommodate two lines of text each for the title and description at a +2 line-height as set by users.
2) It removes the past fading technique and instead clamps the line with an ellipsis.
Also removed here is a `text-shadow` effect that was too subtle to notice in light or dark mode. 
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/URL.20previews/near/2161694)
| --- | --- |
| ![long-titles-pr-original](https://github.com/user-attachments/assets/9336a04b-929d-4e5b-8278-8142456f8fa1) | ![long-titles-pr-proposed](https://github.com/user-attachments/assets/ad7230c8-cc59-4a81-8635-aa646a8ae13e) …

url_previews: Clamp title, description text to two lines each.

---

web/src/spectators.ts
web/tests/hotkey.test.cjs

Fixes unused import warning on running hotkey node tests. This was introduced in #34314.

hotkey: Fix warning about unused `login_to_access` import.

---

zerver/actions/create_user.py
zerver/lib/test_classes.py
zerver/tests/test_auth_backends.py
zerver/tests/test_signup.py
zproject/backends.py

This was broken, due the mechanism simply using our
is_guest/is_realm_admin/etc. role setters, but failing to adjust system
group memberships - resulting in corrupted database state.
We need to ensure that change_user_role is called for setting user role.
There are two relevant codepaths that run the sync based on
AUTH_LDAP_USER_FLAGS_BY_GROUP and thus need to get this right:
1. manage.py sync_ldap_user_data
2. Just-in-time user creation when a user without a Zulip account logs
in for the first using their ldap credentials. After
get_or_build_user returns, django-auth-ldap sees that the user
account has just been created, and proceeds to run ._populate_user().
Now that both user.save() and do_change_user_realm will be getting
called together, we need to ensure this always happens …

ldap: Fix the syncing of user role via AUTH_LDAP_USER_FLAGS_BY_GROUP.

---

zerver/data_import/slack_message_conversion.py
zerver/tests/fixtures/slack_message_conversion.json
zerver/webhooks/slack/tests.py
zerver/webhooks/slack_incoming/view.py

This PR aims to make `render_block` and ` render_attachments` be reusable (primarily for the Slack importer)  and clean up any duplicative functions(`replace_links` & `replace_formattings`) in `slack_incoming`. 
---
- This means, moving `render_block` and ` render_attachments` from `slack_incoming` to `slack_message_conversion`. (Done)
- Make `render_block` and ` render_attachments` compatible with `convert_slack_formatting` instead of `replace_links` & `replace_formattings` from `slack_incoming` (Commit: e919327bb1b529deb3daa5d74825d1ce5d6cd933). 
However, if one tries to use the current regex in `convert_slack_formatting` directly in `slack_incoming`, some tests will fail:
<details>
<summary>
Running tests in slack_incoming with previous `convert_slack_formatting` regex:
</summary> …

slack: Refactor Slack text formatters.

---

web/src/add_group_members_pill.ts
web/src/add_subscribers_pill.ts
web/src/stream_create_subscribers.ts
web/src/stream_edit_subscribers.ts
web/src/user_group_create_members.ts
web/src/user_group_edit_members.ts

- First commit is to fix "Expand" button not visible in group pills in group creation form when pill is created without selecting an option from typeahead.
- Second commit is a small refactor of `add_group_members_pill.create_item_from_text`.
- Third commit is to have single function instead of two separate `create` and `create_without_add_button`.
<details>
</details>

Fix group pill expand button and refactor code to handle subscribers and members pill widget.

---

web/src/tippyjs.ts

Part of #34447:
>**Manage your API key button**
>Add a tooltip to this button when disabled: "Add an email to create your API key."
There was already a tooltip for this disabled button, so updated the text for that, with a slight adjustment from the suggested text in the issue (see above). The user has an API key; we are just restricting access to it until they add an email and password to their account for the demo organization. Adding an email does not create an API key.
Also, there is another disabled setting on this page with a tooltip (see screenshots below). Checking to see if we want to adjust that text at all as well or keep it the same.
| --- | --- |
| ![Screenshot from 2025-04-25 …

demo-orgs: Update tooltip text for disabled manage API key button.

---

web/src/demo_organizations_ui.ts
web/src/navbar_alerts.ts
web/src/portico/showroom.ts
web/tests/demo_organizations.test.cjs
web/tests/navbar_alerts.test.cjs

Part of #34447:
> **Navbar banner**
> Text: remove all links
> Buttons:
>  - Learn more
>      - low emphasis
>      - link to /help/demo-organizations
>  - Convert
>      - medium emphasis
>      - opens conversion modal
**Notes**:
- Only includes the "Convert" button that opens the conversion modal for organization owners. All other users just have the button with the link to the help center.
- Also updates the demo organization banner in the devtools showroom code to match the changes to the implemented banner. I'm not sure if these are still useful to keep in sync or if we just want to keep an example of each type of banner. If it's the latter, then we could also just remove this banner from that page.
---
| Description | Screenshot |
| --- | --- | …

demo-org: Update navbar alert banner to have buttons, instead of links.

---

web/styles/left_sidebar.css

This PR uses the same quarter-pixel adjustment to avoid bleedthrough around sticky headers as was used in #32906.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/bleedthrough.20in.20.22all.20conversations.22.20view/near/2146978)

left_sidebar: Correct for bleedthrough on zoomed-in channel.

---

web/styles/settings.css

This corrects the display of long channels in org settings.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/long.20one-word.20channel.20name.20breaks.20announcement.20settings/near/2163246)
_No change for short channel names:_
| --- | --- |
| ![long-channels-before](https://github.com/user-attachments/assets/db47a78f-0525-4663-a0c1-49195c8bd60e) | ![long-channels-after](https://github.com/user-attachments/assets/7ad82e70-5b46-4c8f-b576-55b4511383bc) |
| ![short-channels-before](https://github.com/user-attachments/assets/3d6a7569-f5db-4d4c-80e2-66d6332b2784) | ![short-channels-after](https://github.com/user-attachments/assets/f539a034-2745-485d-a320-56d055060644) |
<details> …

org_settings: Correctly display long channel names.

---

web/templates/settings/convert_demo_organization_form.hbs

As noted in https://github.com/zulip/zulip/issues/34448#issuecomment-2843755963:
> Thinking about this one, I think we can just make it text instead of a banner. We can make the text:
> > Everyone will need to log in again at the new URL for your organization.
>
> I think we don't need any of the text that's currently there above the form -- it's actually confusing, because not just users and messages are preserved, but everything else, too. So let's just drop that note.
| --- | --- |
| ![Screenshot from 2025-05-01 11-41-59](https://github.com/user-attachments/assets/99f87946-e6f6-4999-925a-17b531b920fa) | ![Screenshot from 2025-05-01 11-34-36](https://github.com/user-attachments/assets/d7f0b7b5-b20e-4980-9b31-e9372b294247)
*Tip …

demo-orgs: Update convert form text to be clearer.

---

web/templates/settings/account_settings.hbs

I think we don't need to emphasize these actions with a brand color; neutral seems more appropriate.

settings: Change button intents on account & privacy panel.

---

tools/setup/build_pygments_data
tools/setup/lang.json
web/src/composebox_typeahead.ts
web/src/typeahead_helper.ts
web/styles/zulip.css
web/templates/typeahead_list_item.hbs
web/tests/composebox_typeahead.test.cjs
web/tests/realm_playground.test.cjs
web/tests/typeahead_helper.test.cjs

This PR
- Replace the blank option with an italicized option that's the current default language, if there is one selected with "default" label.
- Make the "text" option more informative by adding (no highlighting) to the label.
- Remove the hint for "text".
- Prioritize as left to right, before start typing: blank/default language, text, quote, spoiler, math, everything else...
Note: Since this PR is increasing the rankings of priority languages, we have to run `tools/setup/build_pygments_data` to generate data with new rankings.
fixes: #33682
| --- | --- |
| ![Before Image](https://github.com/user-attachments/assets/2a0a1426-9f64-4f8c-89f7-077af1ad7569) | ![After Image](https://github.com/user-attachments/assets/dce041a1-a957-4805-a …

typeahead: Replace code block language hint text with more clear options

---

web/src/drafts.ts
web/templates/draft.hbs
web/tests/drafts.test.cjs

This PR improves the header name for drafts and shows "No DM recipients" as a placeholder when recipients aren't specified.
[czo thread](https://chat.zulip.org/#narrow/channel/101-design/topic/header.20bar.20when.20recipient.20isn't.20fully.20specified)
| --- | --- |
| ![Before Image](https://github.com/user-attachments/assets/eb4bef87-dc31-4220-b14d-c115fd1b6404) | ![After Image](https://github.com/user-attachments/assets/9c939d7d-555b-444d-957c-2bea75bd9075) |
<details> …

drafts: Add placeholders when direct message recipients aren't specified.

---

web/src/activity_ui.ts
web/src/buddy_list.ts
web/src/peer_data.ts
web/templates/buddy_list/section_header.hbs
web/tests/activity.test.cjs
web/tests/peer_data.test.cjs

Work towards #34244.
Note that this doesn't show the right counts when the counts appear, because #34246 isn't complete. But that's fine, because none of this is in production yet. We can double check functionality after that change is complete.
This should change nothing in production. Use `env PARTIAL_SUBSCRIBERS=1 ./tools/run-dev` to see changes locally.

    buddy_list: Fetch full subscriber data before showing user counts.

---

web/src/server_events_dispatch.js
web/src/stream_events.ts
web/src/stream_settings_ui.ts
web/src/stream_ui_updates.ts
web/tests/dispatch.test.cjs
web/tests/stream_events.test.cjs

- First commit is a refactor commit.
- Second commit is to fix live update of UI for adding subscribers.
<details>
</details>

Fix live update of UI on changing group settings.

---

web/src/buddy_list.ts
web/src/peer_data.ts
web/src/util.ts
web/tests/peer_data.test.cjs

Merge [#34259](https://github.com/zulip/zulip/pull/34259) first -- this PR is just the last commit.
Work towards https://github.com/zulip/zulip/issues/34244.

peer_data: Add ability to retry failed subscriber fetch.

---

web/src/dialog_widget.ts
web/src/settings_ui.ts

[`Omit<…, "undefined">`](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys) removes the `"undefined"` key from an object. The intention was clearly [`Exclude<…, undefined>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#excludeuniontype-excludedmembers) which removes `undefined` from a union, or [`NonNullable<…>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#nonnullabletype) which removes both `undefined` and `null`. However, it’s simpler here to provide the expected type directly.
Cc @LaPulgaaa (#29263).

web: Fix nonsensical use of TypeScript `Omit<>`

---

puppet/kandra/templates/prometheus/grok_exporter.yaml.template.erb

We already had one for `/api/v1/tus/...`, but not the bare `/api/v1/tus/` which is used to initiate the upload.
Fixes: 
<details>
</details>

kandra: Add a pattern grouping for /api/v1/tus/.

---

web/src/compose_validate.ts
web/src/composebox_typeahead.ts
web/src/stream_data.ts
web/tests/compose_validate.test.cjs
web/tests/peer_data.test.cjs

Work towards #34244.
To test these changes locally, use `env PARTIAL_SUBSCRIBERS=1 ./tools/run-dev`, and to see the delay add `await new Promise((resolve) => setTimeout(resolve, 1000));` before the call to the server in `maybe_fetch_stream_subscribers`.

compose_validate: Fetch subscribers before warning about mentioning unsubscribed user or group

---

web/src/compose_validate.ts
web/src/composebox_typeahead.ts
web/src/peer_data.ts
web/tests/compose_validate.test.cjs
web/tests/peer_data.test.cjs

Work towards #34244.
This is the only call to `peer_data.is_subscriber_subset`, so after this commit all calls to that function work with our new model for partial subscriber data.
To test these changes locally, use `env PARTIAL_SUBSCRIBERS=1 ./tools/run-dev`, and to see the delay add `await new Promise((resolve) => setTimeout(resolve, 1000));` before the call to the server in `maybe_fetch_stream_subscribers`.

compose_validate: Fetch all subscribers before private channel warning.

---

templates/zerver/portico_error_pages/user_deactivated.html
zerver/tests/test_email_change.py
zerver/views/user_settings.py

Currently, when a deactivated user tries to access the change email link (generated when their account is still active), a JSON error message will be shown.
This adds a new portico error page for the user-deactivated error. Now, `confirm_email_change` renders a portico error page when the user trying to change their email is deactivated.
[CZO](https://chat.zulip.org/#narrow/channel/101-design/topic/change.20email.2C.20deactivated.20user.20error.20.2320227)
Fixes #20227.
| ![image](https://github.com/user-attachments/assets/21d6ac7a-bb77-40b8-bf08-4099795c3373) |![image](https://github.com/user-attachments/assets/1f11387a-746e-45f8-a656-03337d2d0617) | 
<details>
(variable …

email_change: Make "user deactivated" error have UI.

---

web/src/stream_ui_updates.ts

Earlier, permission in edit panel of channel settings was not the same as that of org permission, specifically for public channel option.
We have `update_stream_privacy_option` to enable/disable the option and previously we were updating for only private and web public.
Fixes:zulip#34526.
<details>
</details>

stream_edit: Org permission not reflecting in channel permission.

---

web/src/stream_settings_ui.ts
web/src/user_group_edit.ts
web/styles/subscriptions.css
web/templates/stream_settings/stream_settings.hbs
web/templates/user_group_settings/user_group_settings.hbs

Fixes: #34253.
| Location | **Before (At 16px)** | **After (At 12px)** | **After (At 16px)** | **After (At 20px)** |
|----------|----------------------|----------------------|----------------------|----------------------|
| Stream Settings | <img width="423" alt="Screenshot 2025-04-15 at 1 21 12 AM" src="https://github.com/user-attachments/assets/c6abc3a2-a79b-4ebf-9630-e97e03400de1" /> | <img width="187" alt="Screenshot 2025-04-15 at 1 14 07 AM" src="https://github.com/user-attachments/assets/34360d7d-c2bb-4ca8-ab1c-429bd0092d3f" /> | <img width="206" alt="Screenshot 2025-04-15 at 1 14 53 AM" src="https://github.com/user-attachments/assets/112d6c02-b442-4470-bad7-f9cecfdfc132" /> | <img width="259" alt="Screenshot 2025-04-15 at 1 15 17 AM" …

settings: Redesign buttons in channel and group settings.

---

web/tests/compose.test.cjs

It doesn't make sense that there would be no compose pill user ids if there were compose pill emails, and there needs to be permission to send a direct message or the message won't successfully send.
This was working before because `user_ids_string` ended up empty in `validate_private_message`, which incorrectly returned true for `check_dm_permissions_and_get_error_string`.

compose: Fix broken logic in 'finish' test.

---

zerver/webhooks/slack/view.py

Currently the Slack integration uses a duplicate of `replace_link` since it was previously a part of `convert_slack_formatting` in `slack_message_conversion`. It was refactored out recently, so this uses the real `replace_link`.

integrations: Clean up `replace_link` in Slack webhook.

---

zerver/migrations/0700_fix_user_role_system_groups.py
zerver/migrations/0701_merge.py

This follows our usual backporting scheme, occurring e.g. in #31468. We make the migration depend on the last migration in 10.x, and create a merge migration to avoid having multiple leafs.

migration: Prepare for backporting of migration 0700.

---

templates/zerver/integrations/include/change-zulip-config-file.md

Use the context variable `zulip_url` instead of `api_url` to remove the '/api' suffix.
<details>
<summary><h3>Screenshot</h3></summary>
Example usage: [Git doc](https://zulip.com/integrations/doc/git)
See the last line of the code block setting the `ZULIP_SITE` value.
Before:
After:
</details>
<details>
</details>

integration-docs: Update URL in change-zulip-config-file macro. 

---

zerver/openapi/zulip.yaml

Follow-up to #32811.
**Updates**:
- Fixes the version of Zulip in the main changes note for this new endpoint.
- Revises the main description and the parameter/error descriptions.
---
---
<details>
</details>

api-docs: Revise POST report-message endpoint descriptions.

---

web/src/demo_organizations_ui.ts
web/src/navbar_alerts.ts
web/styles/app_components.css
web/styles/app_variables.css
web/templates/settings/demo_organization_warning.hbs

Fixes #34447 (all other points in issue have been completed in other pull requests):
> **Top of org settings banner**
> Use the same banner as in the navbar (color, buttons, etc.).
>
> Text: remove all links
> Buttons:
>  - Learn more
>      - low emphasis
>      - link to /help/demo-organizations
>  - Convert
>      - medium emphasis
>      - opens conversion modal
**Notes**:
- Migrates the demo organization warning that's shown on all the tabs for organization settings to use the shared banner code, so the color variables for the demo organization warning are no longer needed.
- There are a few differences in the `Banner` used in org settings and the `AlertBanner` used in the navbar alerts, so there's some duplication between the two modules.
- With a narrow browser window the banner's …

demo-orgs: Use banners for org settings demo organization warning.

---

web/src/tippyjs.ts
web/templates/stream_settings/add_subscribers_form.hbs
web/templates/user_group_settings/add_members_form.hbs

This PR adds tooltip on the disbaled "Add" button in group and channel settings.
- The permissions tooltip takes precedence over this new tooltip.
- We are only showing one tooltip at a time.
- Unlike the permissions tooltip, this tooltip is on the button, not on the entire input field.
Fixes: #34325.
| Permissions disabled tooltip | Add button tooltip |
|-----|-----|
| <img width="523" alt="Screenshot 2025-04-17 at 3 30 45 AM" src="https://github.com/user-attachments/assets/96b9703a-9180-4425-b313-12f974461a98" /> | <img width="820" alt="Screenshot 2025-04-26 at 1 37 25 AM" src="https://github.com/user-attachments/assets/d2f841d6-6a1c-4fc8-8b32-fbbc8e2775fd" /> |
| <img width="714" alt="Screenshot 2025-04-17 at 3 31 16 AM" …

tooltips: Show tooltip on disabled "Add" button in group and channel settings.

---

web/src/compose_pm_pill.ts
web/tests/drafts.test.cjs

If we stub out `set_from_emails` as a noop, then setting the private recipient is a noop and doesn't need to happen.

drafts: Remove noop setting of private_message_recipient in tests.

---

corporate/lib/support.py
corporate/tests/test_support_views.py
templates/corporate/support/realm_details.html

**Notes**:
- Implemented on Zulip Cloud support view only since this information isn't relevant for self-hosted support actions.
- Looking up the realm's currently used upload space adds 3 database queries to the support view test as there is no `RealmCount` data for the upload quota used in the test. And therefore `installation_epoch` is called for the realm.
- With `RealmCount` upload quota used data, only 2 additional database queries would be made for the realm's support view data.
| Case | Screenshot |
| --- | --- |
| Uploaded videos, upload quota is None | ![Screenshot from 2025-05-08 17-07-18](https://github.com/user-attachments/assets/1e416ec9-1f55-4c92-bbea-6ff2a2b3a513)
| No uploads, upload quota is None | ![Screenshot from 2025-05-08 …

support: Show file upload usage compared to realm upload quota.

---

web/src/stream_ui_updates.ts
web/templates/stream_settings/stream_settings.hbs

Fixes:  [CZO](https://chat.zulip.org/#narrow/channel/101-design/topic/buttons.20in.20channels.20menu/near/2168977)
|----|---|
| <img width="219" alt="Screenshot 2025-05-07 at 11 58 38 PM" src="https://github.com/user-attachments/assets/c7723bcd-9d28-4fe4-96b3-dd75443a6730" />| <img width="223" alt="Screenshot 2025-05-07 at 11 38 25 PM" src="https://github.com/user-attachments/assets/1e11491c-6fbb-4c91-8c2e-8223844516a3" /> |
<details>
Completed …

buttons: Modify the styles of buttons in stream settings.

---

web/src/stream_data.ts
web/src/stream_popover.ts
web/tests/stream_data.test.cjs

This PR includes the unsubscribed channels in move topics/messages dropdown. From the [conversation](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20Channels.20to.20suggest.20when.20moving.20topics/with/2101733), all the channels (subscribed as well as unsubscribed) to which the user has content access will be shown in the move selector dropdown.
A new function ```get_sorted_stream_with_content_access()``` has been created to return subscribed channels first, followed by unsubscribed ones, with each group sorted individually.
With these changes, some tests were failing, so I have made some necessary changes in the tests in order to ensure that they pass.
Fixes: #33670 
<details>
(variable …

channels: Include unsubscribed channels in move selectors.

---

web/src/upload.ts
web/tests/upload.test.cjs

Both of these handlers immediately hide the banner, so the difference between `.on()` and `.one()` doesn’t matter.

upload: Avoid unnecessary .one() usage to simplify test

---

web/src/compose_send_menu_popover.js

An empty jQuery object is still truthy.
Cc @sayamsamal (#27705).

compose_send_menu_popover: Fix check for closed popover

---

tools/test-js-with-node
web/src/compose.js
web/src/server_events.js
web/src/server_events_state.ts
web/src/state_data.ts
web/src/transmit.js
web/src/ui_init.js
web/tests/compose.test.cjs
web/tests/transmit.test.cjs

This should allow more TypeScript conversion to proceed without blocking on #32792.

server_events: Extract interface for compose, transmit to new module

---

web/src/postprocess_content.ts
web/styles/app_variables.css
web/styles/rendered_markdown.css
web/tests/postprocess_content.test.cjs

This PR adjusts the alignment and spacing on lists and blockquotes, and the color of the border on block quotes, in line with @terpimost's [Figma spec](https://www.figma.com/file/jbNOiBWvbtLuHaiTj4CW0G/Zulip-Web-App?node-id=2038%3A130639).
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/updating.20lists.2C.20blockquotes.20to.20spec/near/2164267)
Fixes [high-priority remaining parts](https://github.com/zulip/zulip/issues/22022#issuecomment-2828766009) of #22022
**Screenshots and screen captures** (updated 2025-05-08):
| --- | --- |
| ![firefox-markers-light-before](https://github.com/user-attachments/assets/7579d51a-d8e6-4bde-a5d3-9e36129c95aa) | ![firefox-markers-light-after](https://github.com/user-attachments/assets/b913b965-eda3-4d02-83b8-08bd …

markdown: Adjust list, blockquote styles to spec.

---

web/src/inbox_ui.ts

Fixed by hiding inbox view empty text when channel view is visible. To ensure normal inbox view empty text is hidden, we make it think there is visible unread topics.
| --- | --- |
| ![Screenshot from 2025-05-13 14 05 50](https://github.com/user-attachments/assets/5beb2147-c565-4203-970f-abb628bf38f4) |![Screenshot from 2025-05-13 14 04 47](https://github.com/user-attachments/assets/cf9e754e-b17b-4dd6-879b-4433127c77fb) |

inbox_ui: Fix empty view text for both channel and normal view visible.

---

web/src/user_events.ts
web/styles/zulip.css
web/templates/navbar.hbs
web/tests/composebox_typeahead.test.cjs
web/tests/popover_menus_data.test.cjs
web/tests/upload.test.cjs
web/tests/user_events.test.cjs

* Fixes part of #19123 (graceful blocking of gravatar for navbar avatar only)
* Removes some apparently unneeded lines in tests
This issue was initially reported for the avatar uploader widget being broken when using uBlock Origin to block gravatar. However, the scope was expanded in the discussion to include all similar outcomes of blocking the gravatar domain. I decided to start with the avatar (and user menu button) being invisible (though still clickable) in the navbar. Since it's my first PR for Zulip I decided to keep it simple and stick to that.
For my fix I used the grey background (as `timabbot` suggested for the avatar uploader). Though as an alternate idea, we could have the placeholder be zulip-icon-user or something similar. It would fit in with the rest of the navbar. LMK if …

Handle gravatar domain blocked for navbar avatar

---

web/src/resize.ts
web/src/stream_settings_ui.ts
web/src/user_group_edit.ts
web/styles/settings.css
web/styles/subscriptions.css
web/templates/stream_settings/stream_creation_form.hbs
web/templates/stream_settings/stream_settings_overlay.hbs
web/templates/user_group_settings/user_group_creation_form.hbs
web/templates/user_group_settings/user_group_settings_overlay.hbs

Prep work for #34125.
The only visual changes from this PR should be:
1. More even padding on the footer (from `two_pane_settings: Clean up padding and width on creation window footer.`)
2. Heights set on the modal body being more accurate, improving the scrolling experience.

settings: Prep commits for grid rewrite for two pane overlay.

---

web/src/user_group_edit.ts
web/templates/user_group_settings/user_group_settings.hbs

This commit changes the intent of "Leave group" to neutral color (grey), while keeping "Join group" brand-colored.
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/101-design/topic/buttons.20in.20channels.20menu/near/2171470).
|---|---|
| <img width="166" alt="Screenshot 2025-05-13 at 10 38 37 PM" src="https://github.com/user-attachments/assets/b5512060-0df1-4e41-8b87-f7f824a7f1ed" /> | <img width="165" alt="Screenshot 2025-05-13 at 10 38 57 PM" src="https://github.com/user-attachments/assets/90ccf38d-16f6-4e64-b9af-5e01463ef648" /> |
<details> …

buttons: Modify the styles of buttons in user group settings.

---

web/src/topic_link_util.ts
zerver/actions/message_edit.py
zerver/actions/message_send.py
zerver/lib/topic_link_util.py
zerver/tests/test_topic_link_util.py
zerver/views/streams.py

We implement a minimal version of the frontend `topic_link_util.ts` in the backend to
handle topic links in notification bot messages etc, which are prone to the same errors as fixed in #30071.
We also mimic the channel name slugging behaviour in `internal_url.ts`.
This module explicitly requires the stream id from the caller, which the frontend module computed with the help
of `stream_data`.
The test cases added for this module are the same as those in `topic_link_util.test.cjs` (though some parts are excluded).
TODO: Add support for message links (using the `@` syntax)
We use the module to generate topic links in notification bot messages and a few other places. 
Fixes: #34608
CZO: [#issues > 📂 Link to topic with backticks in notification message @ …

Port `topic_link_util.ts` to python.

---

help/deactivate-your-organization.md

Before: https://zulip.com/help/deactivate-your-organization
After:
I think the notice about domain reuse should be restored via #34630.

help: Clean up "Deactivate your organization" help page.

---

help/configure-automated-notices.md
help/marking-messages-as-read.md
help/resolve-a-topic.md

Documents #33599 / PR #34226 .
Before: https://zulip.com/help/marking-messages-as-read
After:
----
Before: https://zulip.com/help/configure-automated-notices#notices-about-topics
After:
----
Before: https://zulip.com/help/resolve-a-topic
After:

help: Document new setting for marking resolved topic notices as read.

---

api_docs/changelog.md
version.py
web/src/user_group_edit.ts
web/styles/subscriptions.css
web/templates/user_group_settings/user_group_settings.hbs
zerver/openapi/zulip.yaml
zerver/tests/test_user_groups.py
zerver/views/user_groups.py

- First commit adds API support for reactivating groups.
- Second commit adds UI to reactivate group.
- Third commit is to live update UI when deactivating group.
- Last commit is a small alignment fix.
Fixes:  #23568.
<details>
</details>

Add support for reactivating groups.

---

web/src/peer_data.ts
web/src/stream_edit_subscribers.ts
web/styles/subscriptions.css
web/templates/stream_settings/stream_members.hbs
web/tests/peer_data.test.cjs

Work towards #34244.
Now that we're supporting partial subscriber data, we might need to fetch the full list of subscribers when opening the subscribers tab of the edit channel modal.
This commit handles a slow load with a loading spinner while we fetch the data, and also makes sure to ignore the data if it's received after it stops being relevant (in case the user has another stream's data open).
Tested that regular `./tools/run-dev` works fine.
To test these changes locally, use `env PARTIAL_SUBSCRIBERS=1 ./tools/run-dev`, and to see the loading screen add `await new Promise((resolve) => setTimeout(resolve, 1000));` before the call to the server in `maybe_fetch_stream_subscribers`. 
Note that the subscriber counts in the left pane of the channels settings modal will be wrong until …

stream_edit: Fetch subscribers before showing subscriber tab.

---

zerver/tests/test_auth_backends.py
zproject/backends.py

This extracts the core general group-syncing logic, which is independent of any LDAP-specific concerns, to a separate function. This allows the use of this core logic for group sync in other authentication backends.
The code also gets a bit cleaned up in the process to make it more readable (with some readability tweaks to the log strings as well).

ldap: Extract sync_groups function from sync_groups_from_ldap.

---

web/src/settings_components.ts
web/src/stream_create.ts
web/src/ui_util.ts
web/styles/settings.css
web/templates/stream_settings/stream_types.hbs
web/tests/settings_org.test.cjs

Fixes: [#issues > custom retention period settings UI bug @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/custom.20retention.20period.20settings.20UI.20bug/near/2168324)
| ![Screenshot 2025-05-15 at 3 28 39 PM](https://github.com/user-attachments/assets/415238f0-6de7-42bc-b895-65afa2818aca) | ![Screenshot 2025-05-15 at 3 26 05 PM](https://github.com/user-attachments/assets/102b9d64-a349-4e41-87ed-32af9652af5a) |
| ![Screenshot 2025-05-15 at 3 28 20 PM](https://github.com/user-attachments/assets/cebebc7a-4d3e-4d94-b0c1-98d04c62abcb) | ![Screenshot 2025-05-15 at 3 27 00 PM](https://github.com/user-attachments/assets/1575d096-4e10-4f5b-ad30-dc0c2498faa9) | 
| …

settings: Fix message retention period related save/discard widget bugs.

---

templates/zerver/realm_creation_form.html

I changed the string, as the previous one was hard to understand when "Don't import" is selected. It's now:
@amanagr Could you tweak this PR to use the same below-the-field tip styling as we use elsewhere:

new: Tweak import tip.

---

scripts/setup/configure-rabbitmq

`rabbitmqctl await_startup` does not retry to wait for the Erlang runtime to start, only to wait for the RabbitMQ application to start once Erlang is running.
Cc @alexmv (#30275).
Fixes a `vagrant up --provision` race condition:
```console
$ vagrant up --provision
…
default: + sudo -- scripts/setup/configure-rabbitmq
default: Error: unable to perform an operation on node 'rabbit@ed8d1f15d6a5'. Please see diagnostics information and suggestions below.
default: 
default: Most common reasons for this are:
default: 
default:  * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
default:  * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
default:  * Target node is not running …
```

configure-rabbitmq: Restore startup retry loop

---

web/e2e-tests/lib/common.ts
web/src/compose.js
web/src/compose_actions.ts
web/src/compose_fade.ts
web/src/compose_pm_pill.ts
web/src/compose_recipient.ts
web/src/compose_reply.ts
web/src/compose_state.ts
web/src/compose_ui.ts
web/src/compose_validate.ts
web/src/drafts.ts
web/src/drafts_overlay_ui.ts
web/src/message_view.ts
web/src/narrow_state.ts
web/src/people.ts
web/src/reload.ts
web/src/reload_setup.js
web/src/scheduled_messages_ui.ts
web/src/user_card_popover.ts
web/src/zulip_test.ts
web/tests/compose.test.cjs
web/tests/compose_actions.test.cjs
web/tests/compose_pm_pill.test.cjs
web/tests/compose_state.test.cjs
web/tests/compose_ui.test.cjs
web/tests/compose_validate.test.cjs
web/tests/drafts.test.cjs
web/tests/narrow_state.test.cjs
web/tests/people.test.cjs

Fixes #34468.
note: This PR migrates drafts and composebox, but not messages or narrow terms (which still use emails).
> the drafts data structures in the web app still have a legacy model wherein they store DM recipients as a list of API email addresses and convert those into user IDs. We should just be storing user IDs.
>
> We need to be careful to migrate this to avoid breaking historical drafts.
To avoid breaking historical drafts, drafts with emails are converted to drafts with user ids when we fetch them.
Note that reverting back with user_id drafts will cause parsing issues (do we want to still store the emails for a bit to prevent this?)

drafts: Migrate web app data structures to use a list of user IDs, not API emails, for private_message_recipient

---

corporate/lib/stripe.py

Properly track the current invoicing status using `invoicing_status` and `invoiced_through` fields.

stripe: Fix bugged tracking of invoicing status of plan.

---

help-beta/astro.config.mjs
help-beta/src/components/KeyboardTip.astro

The reason we were doing string manipulation was that when using the keyboard icon for KeyboardTip.astro, we were getting a blank spot if the fill was not sent to currentColor. This commit instead passes the currentColor for the imported unplugin icon directly. This commit only addresses this specific component, any other instances of the icon color being same as the page color still remain and this commit does not solve that.
Fixes: https://github.com/zulip/zulip/pull/34644#discussion_r2091785559
<details> …

help-beta: Pass fill property to component instead of str manipulation.

---

zproject/backends.py

This is an obvious bug/typo introduced in
2cd6f07ffe9666547bdb79fd3a938756d55d860b.

sync_group: Fix incorrect reference to ldap_logger.

---

web/styles/app_variables.css
web/styles/buttons.css

This PR contains 2 commits:
- Commit 1: Improves button outline on focus by tweaking the outline color, width and offset.
- Commit 2: Adds hover state styles to focus state styles.
Fixes: [#design > button keyboard selection indicators @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/button.20keyboard.20selection.20indicators/near/2126847)
| ![Screenshot 2025-04-24 at 5 49 46 AM](https://github.com/user-attachments/assets/9bfd65dc-7db4-4196-8de5-9e5798e00dae) | ![Screenshot 2025-04-24 at 5 54 18 AM](https://github.com/user-attachments/assets/974ea4b7-ad7b-4e80-b49a-3cdd70b7eb0d) |
| ![Screenshot 2025-04-24 at 5 54 51 AM](https://github.com/user-attachments/assets/46c5ab59-6947-4110-92ae-d1a845d7a7ff) | …

buttons: Improve button outline on focus state.

---

web/src/buddy_data.ts
web/src/message_events.ts
web/src/message_util.ts
web/src/recent_view_ui.ts
web/src/stream_popover.ts
web/src/stream_topic_history.ts
web/src/util.ts
web/templates/modal_banner/unsubscribed_participants_warning_banner.hbs
web/tests/stream_topic_history.test.cjs

In Move messages and Move topic modals, Show a warning banner if any of current topic participants are NOT subscribed to the destination stream.
Fixes #33627
1. While user is viewing the conversation (most common case).
2. User is moving a topic while viewing the conversation of **another**, this is was very important test because it makes sure that fetched participants do NOT get confused with the currently viewed conversation's participants. 
3. Recent, Inbox, Combined, Mentions and Starred views.
1. Conversation has no participants
2. Destination channel does NOT change
3. Destination channel changes (appears) then user comes back to the same channel or any other channel that has all the participants subscribed to (disappears) 
4. User subscribes …

move_topic_modal: Add unsubscribed participants warning banner.

---

zerver/lib/users.py
zerver/models/users.py
zerver/tests/test_users.py
zproject/computed_settings.py

Server can now send partial data to the client to help in developement. We don't want this to be widely used right now, hence no documentation changes have been made.
discussion: https://chat.zulip.org/#narrow/channel/378-api-design/topic/defer.20loading.20user.20data/with/2175031

events: Add option to send partial data.

---

web/src/user_group_edit.ts
web/styles/subscriptions.css

- First commit is to fix a typo.
- Second commit fixes empty panel text being shown even when groups are present.
- Third commit is to fix view shown when clicking "Cancel" button in groups creation UI for mobile widths.
- Fourth commit is to not open group in right panel when leaving the group by clicking on checkmark.
Fixes:  https://chat.zulip.org/#narrow/channel/9-issues/topic/group.20settings.20UI.20bug/with/2177144
| | Before | After |
| -------- | ------- | -------- |
| Empty panel text change | ![first-commit-before](https://github.com/user-attachments/assets/f5d75fb7-6ebf-4dc3-a4ca-796f144c0952) | ![first-commit-after](https://github.com/user-attachments/assets/694e50d8-7f57-489e-9bea-f59a8a0f847d) |
| Closing creation UI | …

Miscellaneous fixes in groups UI.

---

web/src/message_view.ts

Discussion here: [#frontend > buddy list search, subscriber fetch @ 💬](https://chat.zulip.org/#narrow/channel/6-frontend/topic/buddy.20list.20search.2C.20subscriber.20fetch/near/2176502)

buddy_list: Clear search bar when the narrow changes.

---

web/src/narrow_state.ts
web/src/stream_data.ts
web/src/sub_store.ts
web/tests/buddy_data.test.cjs
web/tests/drafts.test.cjs
web/tests/pill_typeahead.test.cjs
web/tests/typeahead_helper.test.cjs

This PR removes unnecessary use of override_rewire across, and creates data instead of mocking functions returning that data.
Fixes part of: #32326
<details>
</details>

Clean up unnecessary use of rewires for node tests part 1

---

docs/documentation/api.md
tools/create-api-changelog

Added link to documentation when creating unmerged changelog file using `create-api-changelog` and updated docs for `create-api-changelog` tools.
<details>
</details>

tools: Update docs for create-api-changelog tool.

---

zerver/lib/email_notifications.py
zerver/tests/test_message_notification_emails.py

It is possible that a demo organization owner will receive a direct message from a bot when they haven't yet added an email to their account, e.g., the Notification bot sends a reminder about watching the intro to Zulip onboarding video (noticed this exact situation causing an in the dev environment when working on demo organization updates).
Adds a check and early return in `handle_missedmessage_emails` for this demo organization owner case.
---
<details> …

demo-orgs: Check owner email for missed message emails.

---

web/.browserslistrc
web/styles/rendered_markdown.css

This PR does two things:
1. It follows guidance from @andersk for updating `.browserslistrc` to permit logical properties, such as `margin-inline-start`. In so doing, the PR corrects a regression on lists in RTL languages (see screenshots below).
2. It removes the remaining `.rtl` references from `rendered_markdown.css`, shifting previous right/left shifts to their logical properties for margin, padding, and border, as appropriate.
I believe we will need to keep the `rtl` class in the rendered markdown area, as that is responsible for setting the `direction: rtl` value in `zulip.css`--which is what makes the logical properties here work. What we will *not* need are future styles that directly reference the `.rtl` class itself.
[CZO …

markdown: Move to logical properties for i18n.

---

web/styles/app_variables.css
web/styles/rendered_markdown.css

This PR removes different background colors on thumbnails, previously based on extreme aspect ratios. Now, all thumbnails take the lower-contrast background color previously reserved for thumbnails that show more background (extremely narrow, extremely small, and--given that landscape images are allowed to grow to whatever width they like--truly, extremely wide images). This also uses the higher-contrast hover color, to leave as little doubt as possible when a user has hovered over a thumbnail.
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/consolidating.20thumbnail.20background.20colors/near/2178389)
| --- | --- |
| ![thumbnail-backgrounds-light-before](https://github.com/user-attachments/assets/21b07510-660 …

thumbnails: Use more muted background, high-contrast hover.

---

web/styles/app_variables.css
web/styles/typeahead.css

This PR subtly increases the contrast of user circles in both light and dark mode, and also adjusts the contrast in highlighted typeahead elements so that offline circles have the same apparent contrast as their non-highlighted counterparts.
[CZO discussion](https://chat.zulip.org/#narrow/channel/101-design/topic/empty.20presence.20bubbles.20in.20typeahead/near/2170914)
| --- | --- |
| ![dark-mode-sidebar-before](https://github.com/user-attachments/assets/8aee938c-0ddd-47d9-b5ac-de9d8485d709) | ![dark-mode-sidebar-after](https://github.com/user-attachments/assets/46b73ee7-81a6-4f7b-96a0-2a06b46c7556) |
| ![light-mode-sidebar-before](https://github.com/user-attachments/assets/6698bed6-de9c-4763-9fbd-90c1b30db7ec) | …

user_circles: Bump up offline contrast, esp. in typeahead highlights.

---

web/src/tippyjs.ts
web/templates/settings/organization_permissions_admin.hbs
zerver/lib/demo_organizations.py
zerver/tests/test_realm.py
zerver/views/realm.py

Until a demo organization owner sets an email address, we want to restrict other users from joining the organization. Therefore, we disable changing the invite required setting for the organization until they set their email address. Otherwise, the owner could share the demo organization URL with someone and they could create an account via the homepage.
[Relevant CZO discussion](https://chat.zulip.org/#narrow/channel/3-backend/topic/demo.20organizations.3A.20setting.20org.20owner.20email/near/2169294)
**Notes**:
- I used the same tooltip handler that we have for the email visibility dropdown setting in the account and privacy tab in personal settings for demo organizations.
- Alternatively, we could use the `tooltip_message` field for the settings checkbox in the template, and …

demo-orgs: Disable removing "invite required to join" until email set.

---

zerver/data_import/mattermost.py
zerver/lib/utils.py
zerver/tests/test_mattermost_importer.py
zerver/tests/test_rocketchat_importer.py

message processing log:
```
2025-05-21 02:45:20.003 INFO [] Processed messages up to 35 / 35
```
html2text falied log:
```
2025-05-21 05:00:02.140 WARN [] Error converting HTML to text. Message content: 'Xxxxxxx!'; continuing
```
Fixes: [ ](https://chat.zulip.org/#narrow/channel/31-production-help/topic/Slow.20data.20conversion.20from.20Mattermost.20backup.2E/with/1912233)[#production help > Slow data conversion from Mattermost backup.](https://chat.zulip.org/#narrow/channel/31-production-help/topic/Slow.20data.20conversion.20from.20Mattermost.20backup.2E/with/1912233)
<details> …

mattermost_import: Log when processing messages and add try-except block.

---

tools/ci/production-build

[Discussion](https://chat.zulip.org/#narrow/channel/43-automated-testing/topic/main.20failing/near/2178664).

production-build: Bump es-check language version to es2022

---

zerver/worker/email_senders_base.py

Some codepaths send an event with `realm_id=None` -- which we still must trim out of the event, even if we do not add a `realm` value for them.
Fixes: 
<details>
</details>

email_senders: Handle a None realm_id.

---

web/src/settings_notifications.ts

This corrects a mobile Safari issue that would fail to render the Notification settings pain when the desktop-notifications banner could not be updated (unnecessary in a mobile context).
To make this issue more obvious in the future, the function has also been renamed from `update_notification_banner` to `update_desktop_notification_banner`.
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/buggy.20settings.20UI.20navigation.20on.20Safari.20.28mobile.20web.29.20.2334668/near/2176123)
Fixes #34668
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit- …

settings: Correct for missing `Notification` object in mobile.

---

zerver/data_import/slack.py
zerver/data_import/slack_message_conversion.py
zerver/tests/test_slack_importer.py

This PR adds support for handling Slack integration bot messages. Previously, this type of message wasn't supported because Slack's integration bots aren't Slack users, so we couldn't create a dummy Zulip user to send those messages during conversion.
Prep PRs:
- #32162
- #32164
- #32163
Fixes: #31162
<details>
<summary>
- #31930 
| Slack | Zulip |
| ![image](https://github.com/user-attachments/assets/cf5ae327-fb18-47ea-a292-4e89643333fc) | ![image](https://github.com/user-attachments/assets/985e839c-e23c-4ba8-bec0-eafb311bb199) |
| ![image](https://github.com/user-attachments/assets/7553a2b6-af10-4d1b-9263-039d0ea53509) | ![image](https://github.com/user-attachments/assets/fbbdbedc-b0d7-4920-9ca9-2cc9bbfba521) |
| …

slack_import: Support converting Slack's integration bot messages.

---

package.json
pnpm-lock.yaml
version.py
web/src/upload.ts
web/tests/upload.test.cjs

Fixes
https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Attachment.20re-upload.20fails/with/2121989.
<details>
</details>

upload: Duplicate upload should succeed.

---

web/src/activity_ui.ts
web/src/buddy_list.ts
web/styles/right_sidebar.css
web/templates/right_sidebar.hbs
web/tests/user_search.test.cjs

Work towards https://github.com/zulip/zulip/issues/34244.
Simulated with 5 sec fetch delay:

buddy_list: Fetch all subscribers before showing search results.

---

templates/zerver/deactivated.html
zerver/tests/test_signup.py
zerver/views/auth.py

If a realm's data has been scrubbed, update the deactivated realm to note the URL can be reused, but not that the realm can be reactivated.
**Notes**:
- Updates the template for context variables that are no longer used:
- `"deactivated_redirect"`  removed from context dict in #34072.
- `"deactivated_domain_name"` removed from template in #30057.
- The test could potentially be moved to `zerver/tests/test_realm.ScrubRealmTest`.
---
| Context | Image |
| --- | --- |
| Data not deleted | ![Screenshot from 2025-05-28 13-03-12](https://github.com/user-attachments/assets/76258c3d-a4a6-40da-b8c2-7028fb63e352) |
| Data deleted | ![Screenshot from 2025-05-28 18-07-13](https://github.com/user-attachments/assets/3bde9e01-6898-4c53-9147-471ff21d81af)
| Context | …

templates: Update deactivated organization template for deleted data.

---

zerver/lib/email_mirror.py
zerver/tests/test_email_mirror.py

Observed in emails from Nordic countries, the prefix `SV:` is used instead of `RE:`
This commit also allows the email mirror to remove it automatically.
<details>
</details>

email_mirror: Also strip "SV:" from subject

---

web/styles/zulip.css

This improves removing the `.copy-paste-text` from the document flow, correcting a weird highlighting bug without (apparently, based on my non-Linux testing) impacting pastable output.
[#issues > Timestamp selection area](https://chat.zulip.org/#narrow/channel/9-issues/topic/Timestamp.20selection.20area/with/2183111)
| --- | --- |
| ![selected-text-highlight-before](https://github.com/user-attachments/assets/bb82007d-aa80-4592-a26f-61155eb8c444) | ![selected-text-highlight-after](https://github.com/user-attachments/assets/d9ea5a75-c2f8-4b3d-8cb3-6b0ac80438d3) |

copy_paste: Remove .copy-paste-text from document flow.

---

tools/screenshots/generate-integration-docs-screenshot

This PR refactors the script in preparation for adding support for generating screenshots of integrations without fixtures (all non-webhook integrations) in the following PRs.
<details>
<summary><h3>Screenshot of `--help`</h3></summary>
Old:
New:
</details>
<details>
</details>

generate-integration-docs-screenshot script improvements

---

tools/screenshots/generate-integration-docs-screenshot
zerver/integration_fixtures/nagios/service_notify.json
zerver/lib/integrations.py
zerver/tests/test_integrations.py

Continued from #34780. The first 8 commits with the prefix "generate-integration-docs-screenshot" are from the other PR, and can be ignored for the review here.
1. Removes the existing infrastructure for fixtureless integrations in the screenshot script, and performs refactors.
2. Adds the new framework.
**Previous system**: Each fixtureless integration has its screenshot config in its own file in `zerver/integration_fixtures/<integration_name>/<fixture_file_name>`. These fixtures are used only for generating screenshots, and only contain - topic and message, in a JSON format.
**New system**: The screenshot configs of all the fixtureless integrations are tracked in a single dictionary (like the existing `WebhookScreenshotConfig`) in `integrations.py`. This simplifies the code logic by …

Support generating screenshots of fixtureless integrations

---

web/src/left_sidebar_navigation_area.ts
web/src/unread.ts

It was reported that there was no option to mark messages as read when only unread messages in muted streams and topics remained.
This happened because the logic to show or hide the sidebar menu icon relied solely on the home view count, which excludes unread messages in muted streams and topics.
This PR fixes the issue by including the count of unread messages in muted streams and topics when determining whether to show or hide the sidebar menu icon.
Fixes: #34682
<details> …

left_sidebar: Show sidebar menu icon for muted unread messages.

---

web/styles/zulip.css

This corrects a bug in current versions of Safari where it's possible to use a trackpad or touchscreen to scroll the message area under the left sidebar (and off the screen).
I'm not aware of any side-effects to this, and it seems like we wouldn't want overscroll on the x-axis (whereby, when things are working as expected, the whole UI jogs and slides back into position). The original style for prohibiting y-axis overscroll dates back to a78dc4a2bd5ae8735276d6e650bb2ec6de8440c4
[CZO issue](https://chat.zulip.org/#narrow/channel/9-issues/topic/Sliding.20of.20message_feed_container.20over.20the.20left-sidebar/with/2184913)
| --- | --- |
| ![overscroll-x-before](https://github.com/user-attachments/assets/7829b3ef-0a4d-4301-9c32-66575c090 …

app: Disallow overscroll on x-axis.

---

web/src/compose.js
web/src/drafts.ts
web/src/drafts_overlay_ui.ts
web/styles/drafts.css
web/templates/draft_table_body.hbs
web/templates/drafts_list.hbs
web/tests/compose.test.cjs
web/tests/drafts.test.cjs

Previously, deleting drafts was too easy, which could result in
accidentally losing important information.
This commit adds a green confirmation banner showing "N drafts were
deleted" and "Undo" button to restore deleted drafts.
Fixes: #32995.
| Screenshot                                    |
|---------------------------------------------|
| ![draft](https://github.com/user-attachments/assets/41b80342-5fb1-400c-96c3-51074da0f7d6) |
Recording of Interaction: [Link](https://github.com/user-attachments/assets/6058337a-c96c-4d8d-b327-a3025ac9f802)
<details> …

drafts: Add confirmation banner and undo option for drafts deletion.

---

templates/zerver/landing_nav.html
templates/zerver/login.html
web/styles/portico/navbar.css
web/styles/portico/portico_signin.css

this PR about improving the position of the "forgot your password" and "signup" actions. make it more user-friendly.
moving the "forgot your password" action to more closer to password input for UX. also add the user prompt before signup to guide user. 
**Before:**
**After:**
<details>
</details>

improving position of "forgot password" in login page

---

web/src/buddy_list.ts
web/templates/buddy_list/view_all_subscribers.hbs
web/templates/buddy_list/view_all_users.hbs
web/templates/right_sidebar.hbs
web/tests/lib/buddy_list.cjs

Fixes https://chat.zulip.org/#narrow/channel/9-issues/topic/buddy.20list.20view.20all.20users.20appears.20twice. Earlier, we were appending view all users link using JQuery.append, so when `render_view_user_list_links` is called twice, `view all users` appears twice. It is better show the link using the `hide` since that will make the link appear once regardless of how many times `render_view_user_list_links` is called.
`view_all_users.hbs` is only used once, but we should still keep it around as a partial in order to not make the right sidebar hbs cluttered to read
NOTE: If this exact approach (using the `hide` class) looks good, we should also replace appends in the same file with similar approach.
<details> …

buddy_list: Use class to show/hide view all users instead of append.

---

web/src/list_widget.ts
web/src/settings_users.ts
web/templates/settings/deactivated_users_admin.hbs

Previously, the placeholder text displayed incorrectly after applying filters.
This commit refactors `list_widget` to check if combinations of filters applied, such as role and search filters. It ensures that the correct placeholder message is displayed.
Fixes: #32971.
| **Before**                          | **After**                           |
|-------------------------------------|-------------------------------------|
| ![Before Image](https://github.com/user-attachments/assets/834d1444-e764-4d99-9796-7bf52f7bc9a2) | ![After Image](https://github.com/user-attachments/assets/0c4cebb3-d488-4cde-b744-770757d1bfc5)   |
<details> …

list_widget: Fix placeholder for unmatched deactivated user filters.

---

web/src/settings_profile_fields.ts
web/styles/settings.css
web/templates/settings/add_new_custom_profile_field_form.hbs
web/templates/settings/edit_custom_profile_field_form.hbs

This PR is based upon original work done in PR #30267, where an extra bug was fixed in 1st commit which was not supposed to be good approach to maintainers ([see here](https://github.com/zulip/zulip/pull/30267#issuecomment-2260358411)).
I fixed that bug in an additional PR #32619 using different approach.
Rest of the code change is same as previous.
Fixes: #28607.
<details>
<summary>For Dark Mode: </summary>
| ![Before](https://github.com/user-attachments/assets/bd020017-b4c3-4741-a023-6fade115d4a2) | ![After](https://github.com/user-attachments/assets/dc148d3a-0cb2-4fa3-a85a-2c55d7c8cd16) |
| ![Before](https://github.com/user-attachments/assets/116e1251-4894-43ea-8cc7-a51f159bcd00) | …

Add "Alphabetize choices" button for "List of options" type custom profile fields.

---

web/src/people.ts
web/src/settings_data.ts
web/tests/activity.test.cjs
web/tests/buddy_list.test.cjs
web/tests/compose.test.cjs
web/tests/compose_pm_pill.test.cjs
web/tests/conversation_participants.test.cjs
web/tests/settings_data.test.cjs
web/tests/stream_events.test.cjs
web/tests/user_events.test.cjs
web/tests/user_group_pill.test.cjs
web/tests/user_search.test.cjs
zerver/models/realms.py

See [#issues > buddy list performance issue @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/buddy.20list.20performance.20issue/near/2183130) for background.
@evykassirer @amanagr FYI. I think it's possible the second commit might need to be replaced with caching the value (and invalidating when settings/group memberships change) with the deferred user loading functionality, but am not sure.

Optimize is_person_active

---

web/src/filter.ts
web/src/search_suggestion.ts
web/tests/filter.test.cjs

Previously, typing "channels: public" would show "Channels public" in the typeahead, which was especially confusing because we'd show "All public channels" until the term was completely typed out.

search: Show correct description string for public channels.

---

web/src/search_pill.ts
web/src/search_suggestion.ts
web/tests/search.test.cjs
web/tests/search_suggestion.test.cjs

Prevents this from being possible:

search: Prevent terms from being duplicated in typeahead or pill input.

---

help/collaborative-to-do-lists.md
help/create-a-poll.md
help/saved-snippets.md
help/schedule-a-message.md
help/view-and-edit-your-message-drafts.md
web/src/settings_profile_fields.ts
web/src/tippyjs.ts
web/styles/app_components.css
web/styles/drafts.css
web/styles/modal.css
web/styles/settings.css
web/templates/draft.hbs
web/templates/draft_table_body.hbs
web/templates/poll_modal_option.hbs
web/templates/scheduled_message.hbs
web/templates/settings/default_stream_choice.hbs
web/templates/settings/profile_field_choice.hbs
web/templates/todo_modal_task.hbs

Fixes: #34378.
| Location | **Before (At 16px)** | **After (At 12px)** | **After (At 16px)** | **After (At 20px)** |
|----|----------------------|---------------------|----------------------|----------------------|
| Delete all drafts | <img width="280" alt="c1r1" src="https://github.com/user-attachments/assets/cee284ab-63f3-4cc4-9019-89dcd04ce062" /> | <img width="245" alt="c2r1" src="https://github.com/user-attachments/assets/50889824-d257-4607-a1b8-d6406469c134" /> | <img width="250" alt="c3r1" src="https://github.com/user-attachments/assets/360e08c3-b3ea-4f6c-8389-80ef29d9046a" /> | <img width="324" alt="c4r1" src="https://github.com/user-attachments/assets/9c762350-d9a3-4af9-a95a-5826c90aeab4" /> |
| Delete a draft | <img width="127" alt="c1r2" …

trash-icon: Replace remaining fa-trash icons with zulip-icon-trash and update buttons.

---

web/src/settings.ts
web/src/settings_config.ts
web/src/settings_notifications.ts
web/styles/settings.css
web/templates/dropdown_widget.hbs
web/templates/settings/notification_settings.hbs
web/templates/settings/notification_settings_checkboxes.hbs
web/templates/settings/organization_settings_admin.hbs
web/templates/settings/stream_specific_notification_row.hbs
web/tests/settings_config.test.cjs

This PR adds an option to change the notification settings of a channel from default to custom in the Notifications menu of Personal settings.
**Placeholder behavior of the widget**: If no channel has been added to the notification table (there are no channels for which the user has customized the notifications), the initial placeholder value is "Customize a channel". Once a channel is added to the table, the placeholder is changed to "Customize another channel". - [CZO thread](https://chat.zulip.org/#narrow/channel/101-design/topic/notification.20settings.20for.20muted.20streams/near/2051962).
Fixes: #19849.
[CZO thread](https://chat.zulip.org/#narrow/stream/101-design/topic/notification.20settings.20for.20muted.20streams/near/1256417).
<details> …

settings: Add option to customize channel notifications in Personal settings > Notifications.

---

web/src/demo_organizations_ui.ts
web/src/gear_menu.ts
web/src/navbar_alerts.ts

Follow-up from https://github.com/zulip/zulip/pull/34805#discussion_r2127587148.
Renames the function called to open the web app modal to convert a demo organization to a permanent organization to instead be `show_convert_demo_organization_modal`, as "do_" functions in the codebase typically means it's called after any checks/dialogs.
---
<details>
</details>

demo-orgs: Rename do_convert_demo_organization frontend function.

---

tools/screenshots/generate-integration-docs-screenshot
zerver/lib/integrations.py
zerver/lib/webhooks/common.py

I came across some failing integrations when I was working on the `generate-integration-docs-screenshot` script.
These integrations error out on running `./tools/screenshots/generate-integration-docs-screenshot --all` or  `./tools/screenshots/generate-integration-docs-screenshot --integration integ-name`.
Error message
```
{'result': 'error', 'msg': "Missing the HTTP event header 'X-GitHub-Event'", 'header': 'X-GitHub-Event', 'code': 'MISSING_HTTP_EVENT_HEADER'}
```
Error message
```
{'result': 'error', 'msg': "Missing 'event' argument", 'var_name': 'event', 'code': 'REQUEST_VARIABLE_MISSING'}
```
---
Other integrations that raise errors when used with `generate-integration-docs-screenshot`:
- Slack - `{'result': 'error', 'msg': 'Internal server error'}`
- Dialogflow - `{'result': …

Fix bugs in generating screenshots of integrations

---

web/src/filter.ts
web/tests/filter.test.cjs

Fixes
https://chat.zulip.org/#narrow/channel/9-issues/topic/Starred.20messages.20view.20performance/near/2184251. Anchor for starred messages was `first_unread` and the query to find first_unread in a user's starred messages can turn out to be expensive. This commit ensures that we default to newest instead since first_unread is not of important for the starred messages view. By excluding starred messages from using `first_unread`, it will default to newest based on the logic in message_view.ts.
Fixes: 
<details> …

filter: Do not set anchor as `first_unread` for starred messages view.

---

web/src/list_util.ts
web/src/portico/integrations.ts
web/src/portico/signup.ts
web/src/stream_edit.ts
web/src/stream_settings_ui.ts
web/src/user_status_ui.ts

More work related to [#frontend > Upgrading hotkey patterns @ 💬](https://chat.zulip.org/#narrow/channel/6-frontend/topic/Upgrading.20hotkey.20patterns/near/2184097)
Manually tested the UX related to these code changes.
<details>
</details>

Replace the deprecated `keypress` with `keydown`.

---

api_docs/changelog.md
version.py
web/src/settings_data.ts
web/src/user_group_edit.ts
web/tests/settings_data.test.cjs
zerver/lib/user_groups.py
zerver/openapi/zulip.yaml
zerver/tests/test_user_groups.py
zerver/views/user_groups.py

Fixes #33804.
We still do not allow permission settings to be set to deactivated groups.
Subgroup add/remove has also been tested.
In terms of structuring the commit, we could have had different commits for add/remove changes or 4 different commits for join, leave, add, remove. For 4 different commits, it would take more effort to make just join work without changes to how add works.
For different commits b/w add and remove, since the combined commit was not significantly large, I decided not to have different commits so that I can remove `!` from `assert.ok(!permission_func(deactivated_group.id));` in `settings_data.test.cjs` without thinking about an intermediate state to pass the tests that will be removed in the end.
Leave group, add and remove …

Groups: Can perform any join, leave, add, remove for deactivated group.

---

web/shared/src/typeahead.ts
web/src/composebox_typeahead.ts
web/src/people.ts
web/src/typeahead_helper.ts

Fixes: 
| Query | Before | After|
|------|-------|-------|
|`@aaron` | ![image.png](https://chat.zulip.org/user_uploads/2/8f/ZiGamYUdcJ6xd3LYA9N4BlwA/image.png) |![image.png](https://chat.zulip.org/user_uploads/2/20/EUPyCPamEZhXmZh0gpHK6U00/image.png) |
|`@peter` | ![image.png](https://chat.zulip.org/user_uploads/2/6f/wDg9GS12ZvIzsHrCcY_raj9p/image.png) |![image.png](https://chat.zulip.org/user_uploads/2/ab/IhIkUK69wMEXUb5gCwSZpBIp/image.png) |
|`@michael10012` | ![image.png](https://chat.zulip.org/user_uploads/2/3c/Q7Ftwj4mVHD8K589dFvsuwQR/image.png) |![image.png](https://chat.zulip.org/user_uploads/2/49/OAzkoIHL4jk90v2uwYuMVMzr/image.png) |
|`@m` | ![image.png](https://chat.zulip.org/user_uploads/2/67/xCpQqXqrghXsr-ahjrFAR_NQ/image.png) …

typeahead: Cache diacritic-less names for performance.

---

pyproject.toml
scripts/setup/upgrade-postgresql
uv.lock
version.py
zerver/lib/message.py
zerver/lib/user_groups.py
zerver/migrations/0001_squashed_0569.py
zerver/migrations/0366_group_group_membership.py
zerver/migrations/0514_update_usergroup_foreign_keys_to_namedusergroup.py
zerver/models/groups.py
zerver/models/realms.py
zerver/models/recipients.py

https://docs.djangoproject.com/en/5.2/releases/5.2/
Requires investigation:
> Adding [`EmailMultiAlternatives.alternatives`](https://docs.djangoproject.com/en/5.2/topics/email/#django.core.mail.EmailMultiAlternatives.alternatives) is now only supported via the [`attach_alternative()`](https://docs.djangoproject.com/en/5.2/topics/email/#django.core.mail.EmailMultiAlternatives.attach_alternative) method.
Possibly useful:
> The [`shell`](https://docs.djangoproject.com/en/5.2/ref/django-admin/#django-admin-shell) management command now automatically imports models from all installed apps.
> The new [`django.db.models.CompositePrimaryKey`](https://docs.djangoproject.com/en/5.2/ref/models/fields/#django.db.models.CompositePrimaryKey) allows tables to be created with a primary key consisting of …

requirements: Upgrade Django from 5.1.10 to 5.2.3

---

web/styles/app_components.css
web/styles/app_variables.css
web/styles/dark_theme.css
web/styles/modal.css
web/styles/settings.css
web/styles/widgets.css
web/styles/zulip.css

This PR brings light mode explicitly in league with dark mode, which owing to a `color: inherit` value in `dark_theme.css` was using the default text color.
Rather than crossing our fingers with more `color: inherit`, or deleting the `color:` property on affected selectors, I've opted to explicitly set the default-text color value.
Additionally, another commit corrects a pixel-based size for chevrons on our customized `<select>` elements, allowing them to scale and better match their button-based select/widget-launcher counterparts. While neither the chevron shapes nor their righthand alignment are pixel-perfect, their differences now are much less apparent--especially at larger font sizes.
CZO issues:
* [#issues > status text box greyed …

inputs: Correct text colors, custom select chevrons.

---

help/change-the-channel-description.md
help/change-the-privacy-of-a-channel.md
help/change-your-language.md
help/channel-notifications.md
help/delete-a-topic.md
help/direct-messages.md
help/emoji-reactions.md
help/include/create-a-channel-instructions.md
help/introduction-to-channels.md
help/link-to-a-message-or-conversation.md
help/marking-messages-as-read.md
help/mobile-notifications.md
help/mute-a-channel.md
help/pin-a-channel.md
help/read-receipts.md
help/rename-a-channel.md
help/share-and-upload-files.md
help/start-a-call.md
help/status-and-availability.md
help/subscribe-users-to-a-channel.md
help/unsubscribe-from-a-channel.md
static/images/help/mobile-check-icon.svg
static/images/help/mobile-chevron-left.svg
static/images/help/mobile-plus-icon.svg
static/images/help/mobile-video-icon.svg
static/images/help/mobile-x-icon.svg

Part of https://github.com/zulip/zulip/issues/34748 and https://github.com/zulip/zulip-flutter/issues/715.
**Notes**:
- These are all commits that basically only remove mobile tab instructions from the help center for features that are not yet implemented in the Flutter app.
- Each commit links to the issues in the Flutter repository that are tracking those features (some more generally than  others).
- As these changes only delete content not including screenshots of these changes. See diff of rendered help center docs below.
- Relevant CZO discussions:
- [#documentation > updating mobile docs for Flutter app](https://chat.zulip.org/#narrow/channel/19-documentation/topic/updating.20mobile.20docs.20for.20Flutter.20app/with/2183497)
- [#documentation > Flutter updates: delete message …

help: Remove mobile instructions for features not in Flutter app launch.

---

web/src/settings_notifications.ts
web/styles/app_components.css
web/templates/settings/notification_settings.hbs

- This commit adds the `banner-wrapper` class to the parent container of the banner.
- Added `margin-bottom: 10px` to the banner to improve its appearance.
- Placed the event listener at the correct location with the $container element so that it binds only once. Previously, it was being bound every time the settings page was loaded, causing multiple event listeners to be attached to the same element.
- Additionally, the banner was not rendering when opening Org settings > DEFAULT USER SETTINGS directly,
and this has been fixed by ensuring the banner is rendered correctly.
- Also, if the banner gets rendered in the DEFAULT USER SETTINGS after opening personal settings first, the button click is not working, which is now fixed.
Fixes: …

settings-banner: Fix bugs in the rendering of the desktop notification banner.

---

web/src/people.ts

This avoids parsing error when the error response is not in the expected format.

people: Use safePrase to parse error response.

---

templates/zerver/slack_import.html
web/src/portico/signup.ts
zerver/actions/data_import.py
zerver/data_import/slack.py
zerver/lib/exceptions.py
zerver/tests/test_slack_importer.py
zerver/views/registration.py

Addresses more points from #34649
discussion: https://chat.zulip.org/#narrow/channel/191-kandra-support/topic/Slack.20import/with/2192069
> Converting Slack data… This may take a while.
**Done**
> 2025-05-15 20:10:39.219 INFO [zr] 127.0.0.1       GET     200   3ms (db: 0ms/3q) /json/realm/import/status/6eq5nbqf6d3j3klblz3ur32a (unauth@root via Mozilla)
**Fixed to navigate user back to file upload page and show an error**
**Removed slack bot**
**Fixed**

More tweaks to slack import process.

---

zerver/tests/test_subs.py

This commit fixes the use of `/json/...` by replacing it with the correct `/api/v1/...`. Also removes
unnecessary `login_user` call when using `api_patch`.
<details>
</details>

test_subs: Fix syntax errors in tests.

---

help/configure-where-you-land.md
help/include/sidebar_index.md
help/marking-messages-as-read.md

Fixes: [#documentation > Flutter updates: open message feeds at feature](https://chat.zulip.org/#narrow/channel/19-documentation/topic/Flutter.20updates.3A.20open.20message.20feeds.20at.20feature/with/2195616)
Notes:
- @laurynmm It would be great to get your review on this one, even if it's been merged already. In particular, I wasn't sure if we have standard for the "pick an option" instruction on mobile. I didn't want to re-list them here, as one of the option names is quite long, and also we don't normally list options in the body of the instructions.

help: Document new "Open message feeds at" mobile configuration.

---

web/templates/settings/add_new_bot_form.hbs
web/templates/settings/edit_outgoing_webhook_service.hbs

This updates the `interface` field in the "Manage bot" modal for service bots to have a label consistent with the one in the "Add a new bot" modal.
Fixes: [#design > Service bot triggers UI @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/Service.20bot.20triggers.20UI/near/2196664)
|![image](https://github.com/user-attachments/assets/8148bb49-399b-4529-ba7a-a7cf59606f85) | ![image](https://github.com/user-attachments/assets/229455c9-dca9-4607-924d-0a2a04be4a73)| 
|![image](https://github.com/user-attachments/assets/574ee8ce-443d-4b09-b916-df7588cbb0df) | ![image](https://github.com/user-attachments/assets/989e0a20-0286-43f7-95c5-770ebae14c05)|
<details> …

user_profile: Fix the field for outgoing webhook bots `interface`.

---

web/templates/settings/account_settings.hbs

This was done mistakenly by me in one of my PRs.
`aria-hidden` is already set to `aria-hidden="true"` in the `icon_button.hbs` partial, so it was being unnecessarily passed again in the partial call.
Fixes: 
<details>
</details>

icon_button: Clean up extra parameter.

---

web/styles/input_pill.css
web/styles/search.css

This bug was created in #34629 when we removed the transparent border (which became not transparent on focus).
Reported on CZO here: [#issues > missing focus indicators on user pills @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/missing.20focus.20indicators.20on.20user.20pills/near/2193813)
| screenshots |
| -- |
| <img width="364" alt="image" src="https://github.com/user-attachments/assets/a7748c98-2d1f-43a4-bb2e-81fc37f4df2e" /> |
| <img width="238" alt="image" src="https://github.com/user-attachments/assets/5a4ccde1-cb35-4ff9-9f56-df02995fd006" /> |
| <img width="258" alt="image" src="https://github.com/user-attachments/assets/9895c87c-3ae5-409c-8984-3916d8b0eb58" /> |
| <img width="521" alt="image" src="https://github.com/user-attachments/assets/48dfe13a-4aa1-401d-ba72-5fe …

input_pill: Fix bug where focus indicator wasn't showing.

---

zerver/lib/message.py
zerver/lib/message_report.py
zerver/tests/test_message_report.py

To maintain API compatibility during and after the migration to use `DirectMessageGroup` for 1:1 messages, we need to build the existing report message format when reporting 1:1 DMs using `DirectMessageGroup`.
<details>
</details>

report_message: Use existing template for reporting 1:1 DM via DM group.

---

web/src/topic_link_util.ts
web/tests/topic_link_util.test.cjs
zerver/lib/topic_link_util.py
zerver/tests/test_topic_link_util.py

This PR:
- adds support for empty topic names and message links in the backend `topic_link_util` module.
- adds support for empty topic names in the frontend `topic_link_util` module.
The modules in frontend and backend slightly differ in implementation but produce the same syntaxes for almost test cases except when generating stream links in the frontend, which recently started depending on the user setting  `web_channel_default_view`. (The backend module doesn't yet access user settings)
*It was not possible to render the "general chat" in italics as we do not support that inside markdown `[]()`.*
<details> …

Improve topic_link_util module.

---

web/src/compose_paste.ts

This prevents the case when we have text like
`[abcd](url)` in the compose box and the "url" part
is selected, and we paste a link copied from message actions popover.
<details>
</details>

compose_paste: Don't paste formatted text at md link marker.

---

zerver/views/development/registration.py
zerver/views/registration.py

Creating a demo organization will not require the user to set either an email or password, so explicitly set the password field to not be required for that case.
Updates the form submitted in the development environment login page to create a new demo organization to not send a password value.
**Notes**:
- I included the assertion for the development environment here, but that might not be needed. We have the same assertion earlier in the registration helper when the email value in the form is an empty string. So since we'll need to update that before launching the feature as complete, it seemed fined to include it here as well.
- Tested creating demo organizations in the development environment and went through the process of adding the owner email, inviting users and converting the demo …

demo-orgs: Make password not required for demo organization creation.

---

corporate/lib/support.py
corporate/tests/test_support_views.py
templates/corporate/support/realm_details.html
templates/corporate/support/support.html
web/styles/portico/activity.css

Updates the forms and information that is shown in the support panel for Zulip Cloud organizations:
- Active realms no longer have a "Scrub realm" button.
- Placeholder realms, that are deactivated and have a redirect URL for the newer subdomain only show that information.
- Deactivated realms have the "Scrub realm" button, no longer have sponsorship forms, and only have the management form to reactivate the realm.
- Scrubbed realms have no forms or buttons and show brief text about the state of the realm.
Also, fixes a bug with how realms associated with a realm reactivation confirmation object were shown, and makes how the realm name / subdomain are shown for confirmation objects consistent with the realm detailed information header.
---
| Before | …

support: Revise view for deactivated, placeholder and scrubbed Zulip Cloud realms

---

web/src/stream_popover.ts
web/templates/modal_banner/unsubscribed_participants_warning_banner.hbs

[CZO discussion](https://chat.zulip.org/#narrow/channel/9-issues/topic/Some.20topic.20participants.20banner.20when.20moving.20one.20message/with/2183841)
For example, in a topic which has many participants unsubscribed to the destination stream, but we are only moving a single message sent by "Prospero", the following banner appears

move_topic_modal: Only include senders of the messages being moved in warning banner.

---

zerver/tests/test_channel_permissions.py
zerver/tests/test_subs.py

This PR moves tests for checking channel administering permission based on `can_administer_channel_group`
setting to `test_channel_permissions.py`.
<details>
</details>

Move administering permission tests to `test_channel_permissions.py`.

---

zerver/actions/streams.py
zerver/tests/test_subs.py

Sending messages to a deactivated stream is not allowed with the exception of notices sent in "channel events" topic.
Earlier, notice sent to a deactivated stream when it is deactivated was working correctly but it was resulting in an error in the following cases:
* Renaming stream
* Changing stream description
* Changing message retention period
* Changing posting permission
* Changing access permission
This PR makes sure to send notice successfully in those cases.
Error previously:
> ERR  [] Error queueing internal message by notification-bot@zulip.com: Not authorized to send to channel 'support'
Now:
<details> …

streams: Fix error while sending notice in deactivated stream.

---

zerver/actions/message_delete.py

Fixes: [#backend > do_delete_messages assumes messages from same stream &amp; topic @ 💬](https://chat.zulip.org/#narrow/channel/3-backend/topic/do_delete_messages.20assumes.20messages.20from.20same.20stream.20.26.20topic/near/2199272)
I have wrote  a bit long commit description to explain the issue in the commit only .
<details>
</details>

message_delete: Fix flaky 'do_delete_messages' function.

---

web/src/compose_actions.ts
web/src/compose_recipient.ts
web/src/compose_setup.js
web/src/stream_color.ts
web/styles/app_variables.css
web/styles/compose.css
web/styles/input_pill.css
web/templates/compose.hbs
web/tests/compose.test.cjs
web/tests/compose_actions.test.cjs

This draft experimental PR matches recipient buttons and inputs to the compose box's background color except when a user is a) hovering over the area, after a brief delay (we want to avoid hover effects on incidental pointer traversal through the recipient row), or b) the user has focused the topic area, suggesting that they might be working with the topic in some way, whether editing, clearing, or simply just activating the topic box. Opening the channel picker and choosing a different channel likewise cancels the muted state.
As of 2025-06-17, the below issues have been addressed, and modified privacy-icon colors are behaving as expected--without any kind of intercession by JavaScript for hover or theme-switching states:
As of 2025-06-16, the PR has a delicate commit for displaying …

compose: Avoid highlighting recipient elements when composing.

---

web/styles/popovers.css

Fixes #34772  
Adjusted the overflow properties of the GIF container.  
Changed the color of the triangular tip at the bottom to match the color of the GIPHY logo bar just above it.
| ![image](https://github.com/user-attachments/assets/f1b5a32f-c7d8-438f-a070-a77480f4e8a9) | ![image](https://github.com/user-attachments/assets/02941e32-06cf-482c-a3aa-09b649bef128) |
---
<details>
<summary><strong>Self-review checklist</strong></summary>
**Communicate decisions, questions, and potential concerns**
**Individual commits are ready for review** ([commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html))
**Completed manual review and testing of the following:**
</details>

css: Fix overflow and color issues in GIF popover (#34772).

---

api_docs/running-bots.md
docs/documentation/integrations.md
help/include/how-to-invite-users-to-join.md
help/scim.md
templates/zerver/integrations/capistrano.md
templates/zerver/integrations/hubot.md
templates/zerver/integrations/include/change-zulip-config-file.md
templates/zerver/integrations/redmine.md
zerver/tests/test_docs.py
zerver/views/documentation.py
zerver/webhooks/helloworld/doc.md
zerver/webhooks/zapier/doc.md

Major steps:
1. Update the subdomain value used in the context property `zulip_url` from "yourZulipDomain" to "your-org".
2. Add new context properties for just the subdomain and the host, and use them.
3. (Commits 3 and 4) Make manual replacements for scenarios where we can't use the context property - Zulip Cloud examples, and the RTD docs.
4. Update sample URLs and bot emails in integration docs (does not include docs that are pending an update, because some of them have pretty repetitive occurrences, which are planned to be removed during their update).
Only help, API docs and policies can use the documentation context properties. RTD docs cannot.
This PR also includes a commit that updates one sample API key in the Hubot doc. It only updates 1 doc because all the other integration …

Make the example Zulip URLs uniform in docs

---

web/styles/compose.css

This corrects the presentation of the "Select a channel" label in the channel picker, reducing space that would otherwise be used to offset the label from an icon (which this label, of course, does not have).
[#design > always-open compose box @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/always-open.20compose.20box/near/2202340)
| --- | --- |
| ![select-a-channel-before](https://github.com/user-attachments/assets/ab742ff2-7abd-45b6-934e-9c116adf7c11) | ![select-a-channel-after](https://github.com/user-attachments/assets/c4871ebe-e967-40bf-a2d0-550067c9531d) |
<details> …

compose: Set grid-area for iconless channel label.

---

web/styles/widgets.css
web/templates/widgets/poll_widget_results.hbs

This PR makes the text of poll options clickable, sensibly, by using the `<label>` element. This has the added benefit of making polls more accessible to assistive technologies, too.
[#feedback > Clicking poll text should vote](https://chat.zulip.org/#narrow/channel/137-feedback/topic/Clicking.20poll.20text.20should.20vote/with/2190989)
_Interactions (note, as always, that the arrow cursor is an artifact of macOS's screen recording; users will see a pointer icon):_
_This change does not interfere with text selection, [a concern that Tim expressed](https://chat.zulip.org/#narrow/channel/137-feedback/topic/Clicking.20poll.20text.20should.20vote/near/2193286):_
_The slight leftward shift in the name reflects a new flexbox regime in the area, where …

widgets: Make poll options clickable.

---

templates/zerver/accounts_accept_terms.html
templates/zerver/register.html
web/styles/portico/portico_signin.css

Fixed by using the same set of classes we use to show error when verifying the form locally.
| --- | --- |
| ![Screenshot from 2025-06-24 13-04-31](https://github.com/user-attachments/assets/002a2ffe-4595-4a89-8099-90d1c0e64003) | ![Screenshot from 2025-06-24 13-04-21](https://github.com/user-attachments/assets/94a78ff9-c482-49d0-8f37-c27fb841c485) |

register: Fix ToS error overlapping with subscribed checkbox text.

---

api_docs/changelog.md
api_docs/message-formatting.md
version.py
web/styles/rendered_markdown.css
zerver/lib/markdown/__init__.py
zerver/tests/test_markdown.py

Fixes #32640.
The URL structure for a shared link has changed since this function was returned and this commit makes sure our code is in compliance with that structure.
The concept of an album doesn't exist anymore and folders exist in-lieu of that.
For dropbox links that are folders on non-image files, we show previews same as any other link previews. It is not possible to get information about the shared link except whether it is a file or folder. So for title and description for that linked preview, we use `Dropbox file` or `Dropbox folder` respectively.
Earlier, we were just having raw=1 as the query param to get the image file if required, but now for every dropbox sharing link, preserving query params is important (otherwise we get a 404), this commit makes changes to address that. …

Fix Dropbox image previews

---

help/moderating-open-organizations.md
help/move-content-to-another-channel.md
help/restrict-moving-messages.md
help/setting-up-zulip-for-a-class.md

Documents #34867.
Current: https://zulip.com/help/restrict-moving-messages
<details>
<summary>
Updated
</summary>
</details>
---
Current: https://zulip.com/help/move-content-to-another-channel
<details>
<summary>
Updated
</summary>
</details>

help: Document channel-specific permissions to move messages.

---

web/templates/settings/add_emoji.hbs

Fixes: 
Autocomplete discussion: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/Selecting.20from.20suggestions.20gives.20error.2E/with/2197953)
Button redesing discussion: [CZO](https://chat.zulip.org/#narrow/channel/6-frontend/topic/Upload.20avatar.20buttons.20in.20.22Add.20emoji.22.20modal.2E/with/2197944)
| Before | After(light) | After (Dark) | 
|---|--|--|
| <img width="246" alt="Screenshot 2025-06-19 at 10 17 49 AM" src="https://github.com/user-attachments/assets/c87a82b7-7938-4f34-a9a6-32d2e2a644ec" /> | <img width="242" alt="Screenshot 2025-06-19 at 9 40 33 AM" src="https://github.com/user-attachments/assets/e54fb22f-9d74-454d-a265-4005d09a598b" /> | <img width="228" alt="Screenshot 2025-06-19 at 9 41 05 AM" …

Redesign buttons and disable autocomplete in Add-emoji modal.

---

zerver/worker/deferred_email_senders.py

This name seems to have been copied from
zerver.worker.email_senders.ImmediateEmailSenderWorker, but deferred is the opposite of immediate.
Cc @alexmv (#24564).

deferred_email_senders: Correct worker class name

---

zerver/actions/create_user.py

These comments miss to mention adding to user groups on the list of things done with the new user account.

process_new_human_user: Update comments.

---

api_docs/changelog.md
help/subscribe-users-to-a-channel.md
version.py
web/src/add_subscribers_pill.ts
web/src/compose_setup.js
web/src/state_data.ts
web/src/stream_edit_subscribers.ts
web/src/stream_popover.ts
web/src/subscriber_api.ts
web/src/tippyjs.ts
web/src/user_profile.ts
web/templates/stream_settings/stream_members.hbs
zerver/lib/events.py
zerver/openapi/zulip.yaml
zerver/tests/test_channel_creation.py
zerver/tests/test_home.py
zerver/tests/test_subs.py
zerver/views/streams.py
zproject/default_settings.py

When someone adds another user to a channel, we send the user that was added a Notification Bot message to let them know.
This PR adds an option for whether or not this message is sent. If the number of newly added users is more than 100, 
we don't send notifications.
- The checkbox unchecks and becomes disabled if the number of users to be added to the channel crosses the limit (100).
- If the number of users then reduces, the checkbox becomes enabled again, but is left unchecked.
Fixes #31189
[#api design > options for notifying new channel subscribers @ 💬](https://chat.zulip.org/#narrow/channel/378-api-design/topic/options.20for.20notifying.20new.20channel.20subscribers/near/2199784)
<details>
*I have set the max limit to 2 users for …

channel: Add option to notify users newly added to a channel.

---

help-beta/astro.config.mjs
help-beta/src/components/NavigationSteps.astro
tools/build-help-center
tools/convert-help-center-docs-to-mdx
zerver/lib/markdown/help_settings_links.py

Fixes #31253 and #31254.
We are using `SHOW_SETTINGS_LINK` as the env variable to set if we want to show relative settings link or non-linked markdown instructions. We are not trying to determine `SHOW_SETTINGS_LINK` by ourselves. See https://chat.zulip.org/#narrow/channel/49-development-help/topic/Passing.20sitename.20for.20astro.20project.20in.20production.2E for more details.
Until the cutover happens, we would need to manually update the mapping in both the astro component and the python file, but since that mapping is not frequently changed, that is a tradeoff we can make.
Fixes: 
```
{start_tabs}
{tab|via-personal-settings}
{settings_tab|your-bots}
1. Click **Add a new bot**.
1. Fill out the fields, and click **Add**.
```
from …

help-beta: Introduce NavigationSteps component for settings/relative links. 

---

zerver/tests/test_auth_backends.py
zerver/views/auth.py

When a user was joining via a multi-use invitation link, using one of the social auth methods (e.g. Login with Google), the intended group memberships configured on the multi-use invite would be ignored.

Fix users not getting added to groups when joining via multi-use invite link with social auth

---

web/styles/zulip.css

Ugh. This simple fix to a bone-headed error I made on #34758 corrects the seemingly unrelated odd behavior originally reported at [#issues > ✔ Sliding of message_feed_container over the left-sidebar](https://chat.zulip.org/#narrow/channel/9-issues/topic/.E2.9C.94.20Sliding.20of.20message_feed_container.20over.20the.20left-sidebar/with/2184913)
The mistake in #34758 was pulling the `.copy-paste-text` off to the far right, when it should've gone off to the far left.
In addition to the slide-over behavior that caused on iPad/Safari, I discovered a 1:1 correlated bug that presented in Firefox, which defaults to "Fit to page width" when printing. Those before and after screenshots are presented below.
Fixes part of [#issues > whole-screen scroll when clicking into DMs on …

copy_paste: Offset to the left, not the right.

---

web/src/unread_ops.ts

Earlier, when we had unread banner in message list and user marks all messages as read for topic, unread banner would persist even though we had no unread messages in current message list.
This commit hides unread banner when there are no unreads just like we show banner when unread messages appear in message list.
Fixes:zulip#33866.
<details>
</details>

Fix unread banner not hiding when marking topic as read.

---

web/src/channel_folders.ts
web/src/hash_util.ts
web/src/hashchange.ts
web/src/stream_create.ts
web/src/stream_settings_ui.ts
web/tests/channel_folders.test.cjs

Part of work on https://github.com/zulip/zulip/issues/31972.https://github.com/zulip/zulip/issues/31972, discussed on CZO here: [#frontend > create a channel within a folder @ 💬](https://chat.zulip.org/#narrow/channel/6-frontend/topic/create.20a.20channel.20within.20a.20folder/near/2203887)[#frontend > create a channel within a folder @ 💬](https://chat.zulip.org/#narrow/channel/6-frontend/topic/create.20a.20channel.20within.20a.20folder/near/2203887)
https://github.com/user-attachments/assets/e946064c-4088-4687-ae8c-d4d6cad688ef

channel_folders: Let a new channel in a folder be created through a hash.

---

web/src/sidebar_ui.ts

sidebar_ui: Remove unused hide_unread_counts passed to left sidebar.

---

web/src/settings_exports.ts

Removed the search box from filter_by_consent dropdown in the exports panel as it has only two options.
Fixes: #35028
|![image](https://github.com/user-attachments/assets/8e90941c-ba23-430a-ae7e-c0d6755927b7)| ![image](https://github.com/user-attachments/assets/167156d5-ab9c-4b02-aae9-54a8cbbd5c03) |
<details>
**Communicate decisions, questions, and potential concerns**
**Individual commits are ready for review** ([commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html))
**Completed manual review and testing of the following:**
</details>

settings_ui: Remove search box from dropdown in exports panel

---

web/src/unread_ops.ts

This commit ignores the near operator when comparing with current message list filter terms which may have near operator.
Extension to this https://github.com/zulip/zulip/pull/34713#issuecomment-3014266546
Fixes: zulip#33866.
<details>
</details>

unread_ops: Fix filter term check for current narrow when bulk update.

---

web/src/compose_recipient.ts
web/src/compose_reply.ts
web/src/compose_setup.js
web/src/compose_state.ts
web/src/compose_validate.ts

It was reported that when forwarding messages, the channel picker and the topic resolved banner were displayed simultaneously, with the channel picker being over the banner. This did not look well as the channel picker hid some left part of the banner.
This PR fixes the bug by displaying the banner only when the channel picker is not open.
<table border="1">
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Fixes: #33449
<details> …

 Hide topic resolved banner when channel picker is open.

---

web/src/left_sidebar_tooltips.ts
web/templates/left_sidebar.hbs

Discussed here:
https://chat.zulip.org/#narrow/channel/101-design/topic/channel.20folders.20in.20left.20sidebar.20.2331972/near/2202343

left_sidebar: Don't show 'add channels' in tooltip if that's not allowed

---

web/src/tippyjs.ts
web/src/todo_widget.ts
web/styles/widgets.css
web/templates/widgets/todo_widget.hbs

We want to prevent users from adding a duplicate or empty task to the todo list. For this purpose, we disable the "Add task" button in both the cases.
**Before** 
**After** 
**Before** 
**After** 
Fixes: #20211 
<details>
</details>

todo_widget: Disable "Add task" button when a task cannot be added.

---

web/styles/subscriptions.css
web/templates/stream_settings/browse_streams_list_item.hbs
web/templates/user_group_settings/browse_user_groups_list_item.hbs

**Commit 1:**
The "sub_unsub_status" spinner was inside the div with the "check" class
, causing the tooltip to appear over the spinner, which should only be
visible on the check icon.
This commit moves the "sub_unsub_status" spinner div outside, ensuring
the tooltip is now visible only when hovering over the check icon.
**Commit 2:**
When there is only one user group, the tooltip appears on the upper side
of the "group-row" and gets hidden.
This commit sets `overflow: visible`, causing the tooltip position to
invert when there is only one user group.
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/Hidden.20tooltip.20in.20the.20user.20group.20settings.2E/with/2197344)
|--|----|
| <img width="375" alt="Screenshot …

tooltips: Fix incorrect tooltip on the spinner.

---

web/src/compose_reply.ts

This fixes an accidental change introduced in #32578. Forwarding a message and choosing DM should result in an empty recipient box instead of showing current
recipients.
<details>
</details>

compose_reply: Empty DM recipient box on forwarding message.

---

web/src/narrow_banner.ts
web/src/narrow_error.ts
web/templates/empty_feed_notice.hbs
web/tests/message_view.test.cjs

Previously, we included channel, topic, sender name and search qeries (if present) in the empty feed banner.
With this PR, we will now not include channelm topic and sender name and only display the search queries.
- Changed "Some common words were excluded from your search." to "Common words were excluded from your search::
- if stop words are present, the banner will look as follows:
>No search results.
>Common words were excluded from your search:
>the bananas
- If stop words are not present, the banner will look as follows:
> No search results.
Fixes: #34872
<details> …

Clean up placeholder text when no search results are found .

---

web/styles/left_sidebar.css

This fixes a double fade bug reported here:
https://chat.zulip.org/#narrow/channel/9-issues/topic/muted.20inactive.20channels/near/2209364

left_sidebar: Fade inactive streams in the same way as muted streams.

---

zerver/openapi/zulip.yaml

In the `zulip.yaml` file, the commit
54b5182 - user_groups: Add API support to reactivate a user group was merged without updating the feature level to the correct format. This commit fixes that feature level.
Fixes: [](https://chat.zulip.org/#narrow/channel/9-issues/topic/incorrect.20feature.20level.20in.20zulip.2Eyaml.20file/with/2211479)[#issues > incorrect feature level in zulip.yaml file](https://chat.zulip.org/#narrow/channel/9-issues/topic/incorrect.20feature.20level.20in.20zulip.2Eyaml.20file/with/2211479).
|--------------|-------------|
| ![image](https://github.com/user-attachments/assets/c9bcb427-d6ba-413a-b7f7-bf245d2cd976) | ![image](https://github.com/user-attachments/assets/0913d01a-a1ec-4e7a-8430-225da4f311fe) |
--- …

api: Fix incorrect feature level format in `zulip.yaml` file.

---

web/styles/left_sidebar.css

This introduces a minor bit of justification to ensure that unread markers remain properly aligned in the left-sidebar grid, no matter how many digits the (hidden) unread count climbs to (screenshots below are with three digits).
[#issues > hiding unread counts doesn't work for muted channels @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/hiding.20unread.20counts.20doesn't.20work.20for.20muted.20channels/near/2211519)
| --- | --- |
| ![masked-home-unread-before](https://github.com/user-attachments/assets/16e4725c-4887-4354-8c34-172d2ac4b9ed) | ![masked-home-unread-after](https://github.com/user-attachments/assets/899243e2-41f2-4776-9e2f-83087dda9762) |
<details> …

home_view: Correctly justify unread marker.

---

zerver/lib/markdown/__init__.py
zerver/lib/topic_link_util.py
zerver/lib/url_encoding.py
zerver/tests/test_message_fetch.py
zerver/tests/test_reminders.py
zerver/tests/test_url_encoding.py

This is a prep PR to fix #31100, it;
- standardize the encoding function we use in `topic_link_utils.py` and `url_encoding.py`.
- refactors an `encode_user_ids`.
- refactors an `encode_user_full_name_and_id`.
discussion: [#backend > Fix narrow URLs in exported messages.](https://chat.zulip.org/#narrow/channel/3-backend/topic/Fix.20narrow.20URLs.20in.20exported.20messages.2E/with/2208096)
<details>
</details>

url_encoding: Standardize narrow url encoding methods.

---

web/src/bootstrap_typeahead.ts
web/src/composebox_typeahead.ts
web/src/custom_profile_fields_ui.ts
web/src/filter.ts
web/src/pill_typeahead.ts
web/src/search.ts
web/src/search_suggestion.ts
web/src/settings_playgrounds.ts
web/src/topic_list.ts
web/src/typeahead_helper.ts
web/tests/composebox_typeahead.test.cjs
web/tests/pill_typeahead.test.cjs
web/tests/search.test.cjs
web/tests/search_suggestion.test.cjs
web/tests/typeahead_helper.test.cjs

Context: https://chat.zulip.org/#narrow/channel/101-design/topic/search.20typeahead.20highlighting/near/2188093
<blockquote>
I think overall I'd probably be fine with removing it. A few reasons:
* We don't do that with typeahead these days and that feels Fine.
* No highlighting seems better when you're matching on something that doesn't actually appear in the title or description.
* It's a little bit visually messy to have random characters being bold.
</blockquote>
I'm also generally in favor of simpler code/UX where complexity doesn't add that much.

search: Remove highlighting in search typeahead.

---

web/templates/user_group_settings/user_group_subgroup_entry.hbs

Fixes: [CZO](https://chat.zulip.org/#narrow/channel/101-design/topic/buttons.20in.20tables/near/2213481).
<details>
</details>

x-icon: Fix alignment of x-icon in user group subgroup.

---

web/styles/modal.css
web/styles/settings.css

This commit aligns the channel privacy icons displayed for channels with custom notifications in the notifications table in Personal settings.
Fixes: [#issues > misaligned channel privacy icon in modal, notification table](https://chat.zulip.org/#narrow/channel/9-issues/topic/misaligned.20channel.20privacy.20icon.20in.20modal.2C.20notification.20table/with/2192394).
- For personal settings > Notifications:
|--------------|-------------|
| ![image](https://github.com/user-attachments/assets/fd6896ee-55fc-491d-a16b-4bbe1c8865a0) | ![image](https://github.com/user-attachments/assets/275ea417-f837-4b00-b474-e1b203775e14) |
- For the first stream created modal:
|Font size | Before | After |
|--------------|--------------|-------------|
| …

css: Align channel privacy icons in Personal settings > Notifications and modals.

---

web/src/compose_recipient.ts

This fixes an incorrect `true` value being returned by `composing_to_current_topic_narrow()` in places like the combined feed (the function was returning comparison values without considering whether `narrow_state.stream_name()` was undefined to begin with--a state that indicates we are *not* in a topic narrow, no matter how the other values evaluate).
Additionally, the `composing_to_current_private_message_narrow()` state had not been accounted for previously in the low-attention-span logic (meaning that DMs in true DM narrows were begin set to low-attention by virtue of the bug in `composing_to_current_topic_narrow()`), but is now here to ensure DM recipient-rows are set with the correct attention level in the compose box.
[#issues > 🎯 DM recipients deemphasized …

compose: Correct low-attention logic for combined feeds.

---

web/e2e-tests/message-basics.test.ts
web/src/filter.ts
web/src/search.ts
web/src/search_pill.ts
web/src/search_suggestion.ts
web/styles/search.css
web/templates/search_description.hbs
web/templates/search_list_item.hbs
web/tests/filter.test.cjs
web/tests/search.test.cjs
web/tests/search_suggestion.test.cjs

Fixes #34750.
Note that this change removes query highlighting for users, see [CZO](https://chat.zulip.org/#narrow/channel/101-design/topic/search.20typeahead.20highlighting/near/2187269) for context discussion on that and [#34832](https://github.com/zulip/zulip/pull/34832) for a PR removing all highlighting (which we'll probably merge first).
| --- | --- |
| <img width="628" alt="image" src="https://github.com/user-attachments/assets/f624ef1c-2764-4234-bbab-eb714bfe6e8b" /> | <img width="629" alt="image" src="https://github.com/user-attachments/assets/36f43483-d015-4f33-8cad-4d7e57d9d8fc" /> |
| <img width="639" alt="image" src="https://github.com/user-attachments/assets/d7d9fec3-ae7d-4f3d-ad36-ab4b58a1c423" /> | <img width="628" alt="image" …

Use pills in search typeahead

---

zerver/actions/message_edit.py
zerver/tests/test_message_edit.py

This commit adds a feature, wherein when someone moves a user's message to be the first message in a topic, and the user has the Automatically follow topics initiated enabled, then the new topic will also be followed by the user.
Similarly, if the user has Automatically unmute topics initiated enabled, the moved topic would also be unmuted.
This is done through a new function -
apply_automatic_unmute_follow_topics_policy.
Fixes #28408
<details> …

topics: Apply automatic follow/unmute when message moved to new topic.

---

docs/overview/changelog.md
docs/production/authentication-methods.md
zerver/lib/test_helpers.py
zerver/tests/test_auth_backends.py
zerver/views/auth.py
zerver/views/registration.py
zproject/backends.py
zproject/computed_settings.py
zproject/default_settings.py
zproject/prod_settings_template.py

Adds support for syncing group memberships for a user when logging in
via SAML. The list of group memberships is passed by the IdP in the
zulip_groups SAML attribute in the SAMLResponse.
Still missing:
This has been tested with Okta, where it just takes adding this in the app's configuration UI:
and it passed a list of names of all the groups the user belongs to, during login. I need to also figure out how to do this with with Auth0.

saml: Implement group sync upon user login. 

---

tools/lib/capitalization.py
web/src/compose_banner.ts
web/src/compose_paste.ts
web/src/ui_init.js
web/src/upload.ts

When pasting a long piece of text into the compose box (or message edit textarea), we show a banner giving an option to put the text into a file and upload it.
The banner is only shown if the text is larger than `MINIMUM_PASTE_SIZE_FOR_FILE_TREATMENT`, and would cause the total message size to exceend
`realm.max_message_length`.
If the user chooses to "convert to file", the textarea content is
restored to its state before pasting and a file with the pasted
content is uploaded. The banner is hidden as
soon as any change is made to the textarea content to
avoid inconsistent state and confusion.
Fixes #33107.
Earlier work: #34642
This PR implements the suggestion in [#feedback > Dialog for posting text files ("Slack text snippets") @ …

compose_paste: Convert large pasted text into uploaded text file.

---

web/src/settings_components.ts
web/src/settings_org.ts
web/src/settings_preferences.ts
web/styles/settings.css
web/templates/settings/language_selection_widget.hbs
web/templates/settings/notification_settings.hbs

This PR modifies the Preferences button to an action button in neutral, and 'Send a test notification' into a medium-emphasis neutral action button.
Fixes: #34535
Fixes: 
| ![before-subscribe](https://github.com/user-attachments/assets/ec36f9c4-f9b9-424f-bd85-7de4e782b930) | ![after-subscribe](https://github.com/user-attachments/assets/0c4414ad-2cb3-4d46-9550-34b25e51a126) |
| ![before-unsubscribe](https://github.com/user-attachments/assets/4751db48-b167-4fa7-bded-f1305f3da3dd)) | ![after-unsubscribe](https://github.com/user-attachments/assets/1d4c7cbd-f1b4-4d89-b686-d81825918bd3) |
<details> …

buttons: Redesign buttons in personal settings.

---

web/src/stream_list.ts
web/templates/go_to_channel_list_of_topics_tooltip.hbs

When in topic narrow, hovering over the topic's channel, should correctly show where it would navigate to.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20wrong.20tooltip.20on.20channel
Tested that if the user setting it show list of topics, we show the list of topics tooltip, otherwise go to channel feed tooltip. Note this only works when in a topic narrow and hovering over the topic's channel.

stream_list: Fix misleading tooltip.

---

web/src/click_handlers.ts

This PR adds a check for instance and stops user status hover from destroying user popover instance.
Fixes: zulip#35175.
**After:**
[Screencast from 2025-07-09 02-27-50.webm](https://github.com/user-attachments/assets/3d474eb5-2867-49dd-b3d7-202eaddd3abc)
<details>
</details>

tooltips: Don't destroy user popover instance on user status hover.

---

zerver/lib/typed_endpoint.py
zerver/tests/test_user_groups.py

This PR adds error message for handling "dataclass_type" pydantic errors. An example when
this occurs is when group setting value passed to update the setting is invalid like group ID is
passed directly and not in an object with "new" field and other invalid values as well.
<details>
</details>

typed_endpoint: Handle "dataclass_type" pydantic errors.

---

web/src/compose_closed_ui.ts
web/tests/compose_closed_ui.test.cjs

This pull request improves the user interface behavior when composing messages by fixing the new topic tooltip in the compose box.
* Removed the call to `update_buttons_for_non_specific_views()` to avoid redundant updates when the selected message stream ID is defined.
* Added a reference to the `$reply_button` and modified the tooltip content logic to check the state of `$reply_button` instead of `$new_conversation_button`.
Fixes: [CZO](https://chat.zulip.org/#narrow/channel/9-issues/topic/.22Start.20new.20conversation.22.20tooltips.20lagging.3F/near/2040122)
<details>
<summary> Before: </summary>
</details>
<details>
<summary> After: </summary>
</details>
<details> …

new_topic: Fix the new topic tooltip in the compose box.

---

help/general-chat-channels.md
help/general-chat-topic.md
help/include/select-channel-view-general-advanced.md
help/include/sidebar_index.md
help/require-topics.md

Current: https://zulip.com/help/require-topics, https://zulip.com/help/general-chat-topic
<details>
<summary>
Screenshots (updated + new page)
</summary>
---
---
</details>
Notes:
- I think we don't need to rename the "Require topics in channel messages" label in the left sidebar.
- I think we don't need to change any compose instructions to account for general-chat-only channels.

help: Document channel-specific "general chat" permissions.

---

corporate/lib/stripe.py
corporate/tests/stripe_fixtures/free_trial_upgrade_by_invoice--Event.list.1.json
corporate/tests/stripe_fixtures/free_trial_upgrade_by_invoice--Event.list.2.json
corporate/tests/stripe_fixtures/free_trial_upgrade_by_invoice--Event.list.3.json
corporate/tests/stripe_fixtures/free_trial_upgrade_by_invoice--Invoice.create.1.json
corporate/tests/stripe_fixtures/free_trial_upgrade_by_invoice--Invoice.finalize_invoice.1.json
corporate/tests/stripe_fixtures/free_trial_upgrade_by_invoice--Invoice.list.1.json
corporate/tests/stripe_fixtures/free_trial_upgrade_by_invoice--Invoice.pay.1.json
corporate/tests/test_stripe.py

This was a result of us moving `billing_cycle_anchor` ahead in time of the `LicenseLedger` entry the customer paid for. Thus, this confused our logic in thinking that customer hasn't paid for the current billing cycle.

stripe: Fix free trial pay by invoice customer billed twice.

---

templates/corporate/support/current_plan_details.html

For fixed-price plans, we show **Plan has a fixed price.** in place of the line for the per license rate, which is:
> **Price per license**: $XX.XX
In order to format that more like the other lines in the plan details, we change that bold sentence to now be:
> **Plan type**: Fixed price.
**Notes**:
- Listening for and receiving billing webhook events in the dev environment is not working on my computer at the moment, so I can't create example screenshots. But, since this is just a string change that's been discussed, I thought it would be fine to put these changes up without screenshots.
---
<details> …

support: Follow general styling for showing fixed price plan info.

---

zerver/tests/test_message_report.py

Fixes: [#automated testing > test_channel_message_report backend test flake](https://chat.zulip.org/#narrow/channel/43-automated-testing/topic/test_channel_message_report.20backend.20test.20flake/with/2216731)
<details>
</details>

message_report: Fix flaky tests.

---

web/src/compose_closed_ui.ts

This attempts to correct a case where the `show()` logic on inbox_ui fails to update the label text of the closed compose-box reply button, especially on an empty inbox, making the action of clicking on the reply button confusing, as it presents an empty compose box with the channel picker open.
From my investigation, there was nothing in that code path to update the label when navigating into Inbox from a DM or topic view. But I'm not fully certain that this is the correct solution; it may just be papering over a lapse in logic elsewhere.
| --- | --- |
| ![dm-to-inbox-after](https://github.com/user-attachments/assets/6da157e1-8b56-4b5d-a269-22c80bfc2189) | ![dm-to-inbox-before](https://github.com/user-attachments/assets/9b808ed4-e5bc …

inbox: Update reply-button label via show().

---

corporate/views/support.py
templates/zerver/deactivated.html
web/src/portico/signup.ts
zerver/lib/subdomains.py
zerver/tests/test_signup.py
zerver/views/auth.py

If the `deactivated_redirect` belongs to the same domain as `EXTERNAL_HOST`, automatically redirect, otherwise just point user to the new URL.

auth: Only automatically redirect for same domain redirects.

---

web/styles/message_row.css

It was observed that the bot icon in the message area appeared misaligned with the bot name, positioning slightly lower. This PR fixes the UI bug by correctly aligning the bot icon with the bot name.
Fixes: #32992
<details>
</details>

Correctly align the bot icon in message area.

---

web/src/compose_actions.ts
web/src/compose_tooltips.ts
web/src/message_edit.ts
web/src/tippyjs.ts
web/templates/compose_control_buttons.hbs
web/tests/compose_actions.test.cjs

This PR groups the tooltips for compose box formatting buttons so that the delay only applies to the first button you hover.
This allows two things:
- Smooth transitions of the tippy between many different reference element targets
- Elements with tooltips next to each other that have a delay can be "grouped" so they appear to share a timeout, which greatly improves UX.
- Previously , the tooltips of formatting buttons were treated independently and each of them had their own delays which doesn't feel smooth while hovering.
Fixes: #24825.
Previous PR Reference: #28387.
| Status  | Behaviour |
|---------|------------------------------------------------------------------------------------------|
| Before  | …

tooltips: Group tooltips for smooth transition.

---

docs/index.md
docs/outreach/overview.md

Current page: https://zulip.readthedocs.io/en/latest/
Updated:
(+ full index)

docs: Clean up index page.

---

help/archive-a-channel.md
help/change-the-channel-description.md
help/channel-posting-policy.md
help/configure-who-can-administer-a-channel.md
help/configure-who-can-invite-to-channels.md
help/configure-who-can-subscribe.md
help/configure-who-can-unsubscribe-others.md
help/include/create-a-channel-instructions.md
help/message-a-channel-by-email.md
help/message-retention-policy.md
help/pin-information.md
help/rename-a-channel.md
help/restrict-moving-messages.md
help/restrict-resolving-topics.md
web/templates/stream_settings/stream_permissions.hbs

This sets up the pattern for updating the help center for the changes in #35148.
@laurynmm Could you please take this over to apply it to all the channel settings under advanced configuration?
We might decide to fiddle with the wording for the "Click **Advanced configuration**..." instruction, but that'll be trivial to do.
Before: https://zulip.com/help/configure-who-can-subscribe
After:

help: Update "who can subscribe" page for new channel settings UI.

---

web/src/left_sidebar_navigation_area_popovers.ts
web/src/unread.ts
web/src/unread_ops.ts
web/styles/settings.css
web/templates/confirm_dialog/confirm_mark_all_as_read.hbs
web/templates/popovers/left_sidebar/left_sidebar_all_messages_popover.hbs
web/templates/popovers/left_sidebar/left_sidebar_inbox_popover.hbs
web/templates/popovers/left_sidebar/left_sidebar_recent_view_popover.hbs
web/tests/unread_ops.test.cjs

The PR updates the read messages confirmation modal by introducting a dropdown. The dropdown offers the following options:
> - [ ]  Muted topics
> - [x] Topics you don't follow (default)
> - [ ] All messages
Below the dropdown, a line dynamically displays the count of messages that will be marked as read based on the selected option:
> N message(s) will be marked as read.
The message count updates automatically when the selection changes.
</br>
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/77db911a-afea-46df-ac4f-b41d02a5fde9" width="300"></td>
<td><img src="https://github.com/user-attachments/assets/cda86ea6-43c4-475b-b97a-ed1ba8028530" width="300"></td>
</tr>
<tr>
<td><img …

modal: Add options for which messages are mark as read.

---

help/view-the-exact-time-a-message-was-sent.md

Updates the [View the exact time a message was sent](https://zulip.com/help/view-the-exact-time-a-message-was-sent) help center article.
---
<details>
</details>

help: Add mobile view message exact timestamp documentation.

---

zerver/tests/test_auth_backends.py
zerver/views/auth.py
zerver/views/registration.py
zproject/backends.py

In 40956ae4c524416e07399ceffa742e2671bed77f we implemented group sync via SAML during sign in and sign up. The sign up implementation used a session variable group_memberships_sync_map to plumb through the sync information to the registration codepath, to execute group sync after user creation.
We can use a more robust approach instead, and just amend groups on the `PreregistrationUser` object that's going to be used for registration.

saml: Don't put group_memberships_sync_map in the session.

---

zerver/lib/users.py
zerver/tests/test_bots.py

Currently `check_valid_bot_config` checks if `config_options` has a falsy value to determine whether an integration is invalid or not. But, what it actually does is check whether an exists in WEBHOOK_INTEGRATIONS, and it has at least one WebhookConfigOption.
It should instead, check if `config_options` is `None` to determine whether an integration is invalid or not.
Related discussion: [#integrations > Auto populate integration bot avatar feature](https://chat.zulip.org/#narrow/channel/127-integrations/topic/Auto.20populate.20integration.20bot.20avatar.20feature/with/1797079)
<details> …

users: Fix `check_valid_bot_config` bug.

---

web/src/compose_state.ts

This fixes a bug where if you send a message with leading newlines, you can't edit it until you've reloaded the browser.

compose_state: Strip leading newlines to match server.

---

api_docs/changelog.md
api_docs/message-formatting.md
version.py
web/src/markdown.ts
zerver/actions/message_edit.py
zerver/actions/message_send.py
zerver/lib/markdown/__init__.py
zerver/lib/mime_types.py
zerver/lib/thumbnail.py
zerver/tests/fixtures/markdown_test_cases.json
zerver/tests/test_markdown.py

Previouly, there was no option to play the inline audio files within the web app without downloading or leaving the browser.
This commit adds option to render inline audio files that use the syntax `![title](url)`.
Fixes #27007
<details>
</details>

markdown: Render inline audio files using the `![title](url)` syntax.

---

web/src/filter.ts
web/src/search.ts
web/src/search_pill.ts
web/styles/search.css
web/templates/input_pill.hbs

Removes extra space in suggestion pills, changes description html for channel operator and removes operand in autocomplete topic suggestion pill
Fixes: [#issues > 🎯 pills in typeahead tweaks @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20pills.20in.20typeahead.20tweaks/near/2215874)
**After:**
[Screencast from 2025-07-11 01-54-15.webm](https://github.com/user-attachments/assets/b63b3327-2bb1-4d7f-9c40-bbdeeb5aab67)
<details>
Completed …

Search typeahead pills small fixes.

---

zerver/actions/user_settings.py
zerver/actions/users.py
zerver/lib/send_email.py
zerver/tests/test_users.py
zerver/views/unsubscribe.py

This commit is a preparatory step for allowing organization owners to reset user preferences(#31474), refactors the `clear_scheduled_emails` function to support bulk operations.
Prep PR of #33701.
<details>
</details>

email: Bulk clearing of scheduled emails for multiple users.

---

zerver/lib/event_schema.py
zerver/lib/event_types.py
zerver/views/navigation_views.py

This PR aligns the `navigation_view` event type with the Python event schema classes.
The schema validation script constructs class names from event types, so this change ensures that the `navigation_view` event type matches the expected `EventNavigationView*` class names.
It also adds the `"scheduled"` built-in view fragment, which was missed in PR [#32528](https://github.com/zulip/zulip/pull/32528).
<details>
</details>

Fix navigation_view event class mapping and complete built-in views.

---

web/src/overlays.ts

This PR attempts to fix a bug with the settings overlay displaying an apparently empty pane when the settings overlay is reopened.
[#issues > empty settings @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/empty.20settings/near/2219337)
<details>
</details>

settings_overlay: Remove the settings-section show class on close.

---

zerver/lib/message.py

The Flutter mobile apps don't collapse repeated spaces into single spaces the same way HTML text does, so leading/trailing whitespace in these automated messages end up rendering weirdly.
The regex previously didn't handle a corner case that appears in the latest message.

remove_single_newlines: Fix double-space issue.

---

help/marking-messages-as-read.md
zerver/openapi/zulip.yaml

Documents  #30025 / #32102.
The tip about scrolling is actually contingent on what type of view you're in and your settings, but I think it's OK. If it doesn't work automatically, you'll see a banner. So I left it in.
Current: https://zulip.com/help/marking-messages-as-read#mark-all-messages-as-read
Updated:

help: Document new options for which messages are marked as read.

---

web/src/click_handlers.ts
web/src/hotkey.js
web/src/inputs.ts
web/src/stream_list.ts
web/src/topic_list.ts
web/styles/app_variables.css
web/styles/dark_theme.css
web/styles/input_pill.css
web/styles/inputs.css
web/styles/left_sidebar.css
web/templates/filter_topics.hbs

This follow-up PR replaces the current left sidebar topic list filter input implementation with the redesigned input_wrapper
component.
This PR also serves as the base for supporting inputs using the search_pill_widget, and thus adjusts the previously defined logic at certain places to ensure that the input pills are handled and displayed accurately.
Other changes in the PR:
- Fixes input color values deviating from the design.
- Stretch filter inputs in the left sidebar to fill available space on right. ([#issues > show all topics spacing @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/show.20all.20topics.20spacing/near/2215476))
- A prep commit moving the color variables of input pill to `app_variables.css`; away from `dark_theme.css`.
- Noticed some out of place selectors as …

left_sidebar: Standardize topic list filter input.

---

web/src/copy_messages.ts
web/templates/draft.hbs
web/templates/reminder_list.hbs
web/templates/scheduled_message.hbs

Fixes: https://github.com/zulip/zulip/pull/35097#issuecomment-3058834909
Before:
https://github.com/user-attachments/assets/f78e6c70-b5d7-482a-ad88-9a834ffd7001
After:
https://github.com/user-attachments/assets/67d277e0-3c40-4f78-b592-5353ef30d071
https://github.com/user-attachments/assets/75f1e3e9-381f-4bd4-a4a8-1aa679a7cc94
https://github.com/user-attachments/assets/67c9fe42-c267-4605-8f0f-a8b900d46a6f

copy_messages: Prevent blueslip error while copying overlay message header.

---

web/styles/settings.css
web/styles/subscriptions.css

This PR fixes the background color of pill containers in dark theme by removing hard-coded values for `background-color` in `settings.css` and `subscriptions.css`. This bug was introduced in a4dd8e515d05cf5a3dacf4da5ea0936de614cdab.
<p>
| <img width="602" height="328" alt="image" src="https://github.com/user-attachments/assets/efa62648-7296-40a7-9cba-186d2568375a" /> | <img width="537" height="302" alt="image" src="https://github.com/user-attachments/assets/8a7c7ebf-c9cb-4ebc-b25b-838ce7f8fa8e" /> |
| <img width="619" height="600" alt="image" src="https://github.com/user-attachments/assets/bb8a58a1-cfda-4426-9720-1d08fd06fe34" /> | <img width="602" height="578" alt="image" …

pill_container: Fix background-color in dark theme.

---

web/src/settings_data.ts
web/src/stream_list.ts
web/styles/left_sidebar.css
web/templates/stream_sidebar_row.hbs
web/tests/stream_list.test.cjs

Previously, the unmuted unread counts were still being shown in the left sidebar, despite setting the "Show unread counts for" to "No channels".
Fixes: [#issues > 🎯 hiding unread counts doesn't work for muted channels @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20hiding.20unread.20counts.20doesn't.20work.20for.20muted.20channels/near/2207895)
Verona-> Unmuted stream
Venice-> Muted stream
Zulip -> Muted stream with unmuted unreads.
| Setting | Before | After |
| No channels | ![image](https://github.com/user-attachments/assets/3cf27e8d-9904-456b-b964-53e2858a4c1c) | ![image](https://github.com/user-attachments/assets/a0b6f1b8-1e41-468d-9535-da15891e6280) |
| Unmuted channels and topics | …

left_sidebar: Fix unread counts showing for muted channels.

---

web/src/message_edit.ts
web/src/message_list_hover.ts

To fix the glitch, we use timeout to reevaluate what buttons should be there in message controls.
To test the PR, we can set the message edit time limit to 1 minute, send a message and keep the mouse over the sent message.
Fixes: #15810
<details>
</details>

Fix glitch when hovering a message as its editing window expires 

---

web/src/topic_list.ts

The topic filter typeaehad behavior that we merged in #24200 was very in your face and annoying when trying to do basic filtering. Here we change it to require `is:` to trigger, while also cleaning up some problems with the implementation.

Make the topic filtering typeahead reasonably usable

---

zerver/lib/narrow.py
zerver/tests/test_message_fetch.py
zerver/views/message_fetch.py

The changes in this PR are almost identical to PR #25818, which had a small bug that only appeared once rebased on top of 5151dd7ff849f54236038c484b19d50703c627a9. In #25818, `add_narrow_conditions` labels the query for the topic name column as "escaped_topic_name" but downstream, we expect the label to still be "subject". Commit ea83c911e9de97ba53276267728d9d297c10b25d subsequently rolled #25818 back.
The difference in this PR is a small fix that updates the other adjacent codes to also use and expect "escaped_topic_name" instead of "subject".
| <img width="432" height="759" alt="image" src="https://github.com/user-attachments/assets/55a8b1fc-6b96-4f65-a06b-493a3d4d5554" />| <img width="467" height="758" alt="image" …

narrow: Fix topic highlighting issue with apostrophes in search.

---

web/src/compose_validate.ts

The topic moved compose warning banner should not shown when the topic in compose recipient box is only resolved or unresolved.
Fixes #35082.
<details>
</details>

compose_validate: Don't show topic moved banner on topic resolve.

---

eslint.config.js
help-beta/astro.config.mjs
help-beta/src/components/Head.astro
help-beta/src/scripts/client/adjust_mac_kbd_tags.ts
web/src/common.ts

Fixes #31287.
These tags are not limited to just KeyboardTip, so we want to run the transformation on all html.
We need to run the transformation client-side since the user's keyboard style is only known at that time.
We had to override the HEAD component since that's what starlight recommends to do if we want to include local assets on every page. If we were using a remote js file, we could have modified the head config option provided by starlight.
The script file to adjust the tags is mostly just copy-paste of the original function to adjust for the lack of JQuery. Most of the comments are also copy-pasted.
One change in the new script is to just use ⌘ symbol directly instead of using zulip-icon since we don't have any centering problems in the new help center. …

help-beta: Adjust kbd tags if the user is using a mac style keyboard.

---

help/import-from-slack.md
zerver/data_import/slack.py
zerver/tests/test_slack_importer.py

Fixes: #27661.
discussion: [#user questions > What to do with Slack imported topics?](https://chat.zulip.org/#narrow/channel/138-user-questions/topic/What.20to.20do.20with.20Slack.20imported.20topics.3F/with/1804899)
Thread topic name is thread date + a snippet of the original message (45 characters in total) if it's more than that, the topic name will cut off
truncated topic name because the snippet is too long:
documentation changes: `/help/import-from-slack` 
| Previous | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/42d51d23-3d48-4861-86ed-43c7e7dbfee0) | ![image](https://github.com/user-attachments/assets/cf6e805c-a8ec-47f3-9d96-8d8f81b9940a) |
Some edge cases:
- Text formatting syntax in topic name <img width="728" …

slack_import: Update topic name format for Slack threads.

---

web/styles/subscriptions.css
web/styles/zulip.css
web/templates/draft_table_body.hbs
web/templates/feedback_container.hbs
web/templates/settings/add_new_custom_profile_field_form.hbs
web/templates/settings/edit_custom_profile_field_form.hbs
web/templates/settings/generate_integration_url_modal.hbs
web/templates/stream_settings/stream_settings.hbs

Fixes part of #35006.
Fixes: 
| **Location**                  | **Before**                                                                                 | **After**                                                                                 |
| ----------------------------- | ------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------------- |
| **Select all draft**          | ![Before](https://github.com/user-attachments/assets/da97e5cf-3511-4392-a3ce-2525b3dc4554) | ![After](https://github.com/user-attachments/assets/94246e74-5371-49aa-87a4-399a94e74a39) |
| **Alphatesze choice**         | …

buttons: Redesign some old-style buttons with rounded class.

---

help-beta/astro.config.mjs

Slug was mentioned for the two entries in question as if they were normal help pages, but they were external links and should have been mentioned accordingly.
<details>
</details>

help-beta: Fix incorrectly linked entries in sidebar.

---

help-beta/astro.config.mjs

NOTE: First commit is from https://github.com/zulip/zulip/pull/35321, please help rebase if that is already merged at the time of review.
In some cases, some of the starlight css was inserting a margin top of 1rem to the svg tag inserted by unplgin-icons. We make the top margin 0 explicitly to make sure that extra margin is not added.
Before:
After:
<details>
</details>

help-beta: Remove top margin from unplugin icons.

---

corporate/lib/decorator.py
zerver/lib/request.py
zerver/middleware.py
zerver/tests/test_thumbnail.py
zerver/views/upload.py

~~This should probably wait until Django 5.2.4 (expected July 2) due to [Django #36447 “HttpRequest.get_preferred_type misorders types when more specific accepted types have lower q”](https://code.djangoproject.com/ticket/36447).~~ We upgraded to 5.2.4 in #35260.
- Followup to #34336.

request: Use Django 5.2 HttpRequest.get_preferred_type

---

help-beta/package.json
help-beta/src/.remarkrc.js
help-beta/tsconfig.json
help/format-your-message-using-markdown.md
help/link-to-a-message-or-conversation.md
help/support-zulip-project.md
help/using-zulip-for-a-class.md
pnpm-lock.yaml
version.py

NOTE: First commit is from #35321, please help rebase if that is already merged at the time of review.
Partially fixes https://github.com/zulip/zulip/issues/35129.
Prettier could not be used because of prettier issue number 12209, not linked here to avoid spam backlinks on the original issue. Prettier does not have support for mdx v2 and v3.
The starting set of rules for this file were borrowed from https://github.com/wooorm/remark-preset-wooorm, some of the rules that we did not want were removed from the starting set. None of the rules were giving an error on the starting set, but some rules that were giving lots of warnings on the generated mdx were removed, we can add them back later as and when required.
We have not inserted this in the main lint tool, we should do that in the final …

help-beta: Add linting for MDX files.

---

web/src/emoji_picker.ts
web/src/user_status_ui.ts
web/styles/user_status.css
web/templates/set_status_overlay.hbs

Previously, due to a logic issue, the clear status icon did not appear when there is only selected emoji in the status—it appeared only when status text was present.
This PR fixes the bug and now the clear status icon disappears only when neither status text nor a selected emoji is present.
**Before** 
https://github.com/user-attachments/assets/d7bbdc5a-5529-41df-bec4-201db1df533c
**After**
https://github.com/user-attachments/assets/98ed35f9-b5e8-4ea2-aa7d-8936d01bbb22
Fixes: #35176
<details>
Completed …

user_status_ui: Show remove status icon when only emoji is present.

---

api_docs/include/rest-endpoints.md
zerver/openapi/zulip.yaml
zerver/tests/test_user_status.py
zerver/views/presence.py
zproject/urls.py

This PR creates API new endpoint that allow admin to update the user status. It also contain the documentation and test case.
Fixes:  #33139 
<details>
</details>

api: Allow admins to update user status.

---

web/src/popover_menus.ts

Fixes #35150
Fixed by adding more fallback options.
Reproduced by clicking on left sidebar or inbox channel popover triggers at the bottom right corner.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.93.82.20Channel.20settings.20sometimes.20unreachable.20on.20mobile.20.2335150
| --- | --- |
|<img width="841" height="699" alt="Screenshot from 2025-07-21 10-08-44" src="https://github.com/user-attachments/assets/6d7bd00c-abbe-4bd8-a095-1c6590715e6e" /> | <img width="841" height="699" alt="Screenshot from 2025-07-21 10-08-07" src="https://github.com/user-attachments/assets/4f03901a-6048-4d76-a3bb-9d3e3806300f" /> |
|<img width="841" height="699" alt="Screenshot from 2025-07-21 10-08-36" src="https://github.com/user-attachments/assets/4015be98-418b-4 …

popover_menus: Fix channel popover displayed out of visible area.

---

web/styles/portico/billing.css

billing: Fix loading spinner not aligned on upgrade page.

---

web/src/topic_list.ts

When the contenteditable div in the topic list filter is empty, the browser adds a `<br>` element to it, which interferes with the ":empty" selector in the CSS — responsible for showing the placeholder and hiding the clear button in the input field. Hence, we detect this case of an empty contenteditable div and clear the content of the div to ensure that the CSS styles are applied correctly.
Fixes: https://github.com/zulip/zulip/pull/35194#issuecomment-3070965779
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.ht …

topic_list: Fix bug related to br element in empty contenteditable div.

---

zerver/actions/scheduled_messages.py
zerver/lib/addressee.py
zerver/lib/message.py
zerver/tests/test_scheduled_messages.py

When using a direct message group as the recipient for 1:1 or self DMs, we need to ensure the `read_by_sender` [parameter](https://github.com/zulip/zulip/blob/10.x/zerver/actions/scheduled_messages.py#L61-L63) is set correctly when scheduling a message.
<details>
</details>

scheduled_messages: Set read_by_sender for self-DMs using DM group.

---

web/src/click_handlers.ts
web/src/hotkey.js
web/src/inputs.ts
web/src/stream_list.ts
web/src/topic_list.ts
web/src/user_search.ts
web/styles/app_variables.css
web/styles/inputs.css
web/styles/recent_view.css
web/templates/components/input_wrapper.hbs
web/tests/user_search.test.cjs

This PR consists of the following commits:
- Commit 1: Adds the `input-close-filter-button` class to the clear filter button as suggested in https://github.com/zulip/zulip/pull/35194#discussion_r2205777827
- Commit 2: Fixes the vertical alignment of the recent view filter input.
- Commit 3: Replaces borders in the inputs with outlines for focus indicators, aiding with calculations (https://github.com/zulip/zulip/pull/35194#discussion_r2205791661)
- Commit 4: Fix icon alignment for multi-line inputs.
- Commit 5: Moves input blur on escape logic to hotkey.js module. ([#issues > 🎯 Escape keyboard handling in "Filter topics" input @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Escape.20keyboard.20handling.20in.20.22Filter.20topics.22.20input/near/2225832))
Fixes: …

filter_inputs: Improvements for filter input elements.

---

web/src/stream_list.ts
web/styles/left_sidebar.css
web/tests/stream_list.test.cjs

This gives us more control, for example `show()` was adding `display: inline-block;` to channels after unhiding them which was overriding other code (added for channel folders in upcoming code) that was trying to hide the channels.
CZO: [#issues > 🎯 channel folder toggle not responding after zoom in @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20channel.20folder.20toggle.20not.20responding.20after.20zoom.20in/near/2221871)

stream_list: Hide channels on zoom-in using .hide instead of hide().

---

zerver/lib/user_groups.py
zerver/tests/test_user_groups.py

[#backend > get_recursive_group_members duplicate entries @ 💬](https://chat.zulip.org/#narrow/channel/3-backend/topic/get_recursive_group_members.20duplicate.20entries/near/2166003)

get_recursive_group_members: Use DISTINCT in the query.

---

web/src/inbox_ui.ts

discussion: https://chat.zulip.org/#narrow/channel/101-design/topic/channel.20folders.20UI.3A.20Inbox/with/2225780
Inbox can suddenly scroll to top due to a rerender when user is trying to scroll down. A possible caues for this is `move_focus_to_visible_area` being triggered on scroll but the element located using:
```
document.elementFromPoint(inbox_center_x, inbox_row_below_filters);
```
being out of view. To fix it, we try to locate the element in the same animation frame. This will remove the possibility of element being out of view when we try to set focus to it.

inbox: Attempt to fix inbox scrolling to top unexpectedly.

---

templates/zerver/app/index.html
web/src/inbox_ui.ts
web/styles/inbox.css

* Focus ring is not longer displayed without user input.
* If user starts using mouse after using keyboard once, we are not guarenteed to get a focus ring since `focus-visible` state is not controlled by us but is determined by the browser.
* Focus is set on the first row  by default - (It can be a folder row).
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20inbox.20initial.20keyboard.20selection/with/2226815
TODO:

Improve inbox keyboard navigation experience.

---

zerver/lib/exceptions.py
zerver/openapi/zulip.yaml
zerver/views/push_notifications.py

CZO Discussion: [#api design > E2EE - error raised by server @ 💬](https://chat.zulip.org/#narrow/channel/378-api-design/topic/E2EE.20-.20error.20raised.20by.20server/near/2220692)
> error will be raised by server when client tries to register and server can't connect with bouncer
> That seems reasonable; though maybe we want that to have a code; the client may want special understanding for that situation.
> if the server isn't configured for notifications, then that's definitely a situation we'll be interested in handling explicitly in the client.
Fixes part of #35368.
<details> …

register_push_device: Add an error code to push-not-configured error.

---

web/styles/input_pill.css

This PR fixes background color pill container of "Users" type custom profile fields when they can't be edited by non-admin users.
| <img width="551" height="166" alt="image" src="https://github.com/user-attachments/assets/1a8de191-a774-4f2c-9531-ee4fc01809bd" />| <img width="505" height="247" alt="image" src="https://github.com/user-attachments/assets/e0acf078-615d-4f32-8e9d-b1f263f9fc2b" /> |
| <img width="522" height="181" alt="image" src="https://github.com/user-attachments/assets/20981904-5f69-4d21-9d19-7412e1cb034f" /> | <img width="534" height="165" alt="image" src="https://github.com/user-attachments/assets/853345bc-a765-4cdb-8354-de23edd54f23" /> | 
<details> …

pill_container: Remove hardcoded HSL value from input_pill.css.

---

api_docs/changelog.md
zerver/openapi/zulip.yaml

Updates the changelog entries for feature levels 404 and 392, and revises the descriptive text for the `topics_policy` channel and realm level settings.
The feature level 404 changes were originally added in commit a77fc6aa7921.
The feature level 392 changes were originally added in commit deaa43c7e6104.
---
**[API changelog](https://zulip.com/api/changelog)**
**[topics_policy field](https://zulip.com/api/get-streams#response) on Stream and Subscription objects in API docs**
**[realm_topics_policy field](https://zulip.com/api/register-queue) on register response API doc**
**org-level [topics_policy field](https://zulip.com/api/get-events#realm-update_dict) on get events API doc**
**[topics_policy …

api-docs: Revise feature level 404 and 392 changes entries.

---

web/src/inbox_ui.ts

`is_waiting_for_revive_current_focus` should be set to `true` when inbox is hidden so that it be correctly checked when it inbox is displayed later.

inbox: Fix `is_waiting_for_revive_current_focus` not being reset.

---

web/styles/left_sidebar.css

I have been unable to reproduce the error reported at [#issues > 🎯 "channels" selection box cut off](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20.22channels.22.20selection.20box.20cut.20off), but the some of the CSS removed in this PR may help with the situation.
Here is a breakdown of the removed lines' origins:
```
#left_sidebar_scroll_container {
outline: none;           // Added originally in 6f9e97921d39e87637c654337c77daa809080c7b,
// though there is no reason that a <div> element would take an
// outline/focus to begin with.
overflow: hidden auto;   // Added originally in d4e1f0a9a88d1da4e6f11d1603b3a313d4426bb9,
// as part of a clear-search button that has long since been 
// superseded; hiding the overflow-x here could very well be
// what makes the …
```

left_sidebar: Attempt to correct selection-box cutoffs.

---

web/src/compose_actions.ts
web/src/compose_recipient.ts
web/src/compose_ui.ts

This commit fixes a bug on iPad/Safari that caused the entire viewport to scroll wildly when navigating to lengthy DM conversations.
As Aman & I discussed on a call this morning, there should be no ill side-effects to deferring focus, as that should be the last thing to happen after all other calculations and rendering have taken place.
[#issues > 🎯 whole-screen scroll when clicking into DMs on iPad](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20whole-screen.20scroll.20when.20clicking.20into.20DMs.20on.20iPad)
_There appears to be a slight flutter in the After capture, in going from Desdemona et al. back to Hamlet, but that seems to be exaggerated based on the point at which the mov-to-gif converter sampled the video._
| Before | …

compose: Defer triggering focus.

---

web/src/portico/showroom.ts
web/styles/app_variables.css
web/styles/banners.css
web/templates/components/banner.hbs

This PR improves the responsiveness of normal banners by adopting a flexbox layout for the label and action buttons. This change better accommodates varying text lengths and button counts in the banners, due to the natural flowy nature of flexboxes.
The key logic shift involves using `flex-basis` to manage layout transitions: the label and the group of action buttons now wrap to separate lines when the label's width is less than 60% of the banner query container's width (60cqw).
This PR also updates the CSS for navbar banners to align with the new flexbox layout between the label and the group of action buttons, while also ensuring that the layout behavior of these banners remains consistent with the previous implementation.
Test the PR locally by using …

banners: Improve responsiveness in normal banners.

---

README.md
templates/corporate/team.html

Fixes #35350.
We've moved to using `,` in numbers over 1,000 in the blog post, so I did that here as well.

docs and portico: Update contributor numbers.

---

web/styles/left_sidebar.css

This PR corrects a couple of issues with the left sidebar filter inputs:
* It hides a scroll artifact that may be visible on operating systems like macOS when "always show scrollbars" or similar is selected.
* It corrects for an annoying ellipsis bug in Safari that makes it impossible to see or scroll to the end of long inputs.
[#issues > left-sidebar topic input issues](https://chat.zulip.org/#narrow/channel/9-issues/topic/left-sidebar.20topic.20input.20issues)
_Scroll artifacts:_
| --- | --- |
| <img width="640" height="250" alt="scroll-artifact-before" src="https://github.com/user-attachments/assets/ee67e4f8-197d-452a-9d19-66abc4db18b3" /> | <img width="640" height="250" alt="scroll-artifact-after" …

leflt_sidebar: Topic filter-input fixes.

---

web/styles/search.css

`min-width: unset` is overriding the user pill min-width value.
This PR fixes this by prioritizing this min-width rule for user pill.
Fixes: [#issues > Search bar compression @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/Search.20bar.20compression/near/2223993)
**Before:**
**After:**
<details>
</details>

search: Fix user pill min-width overridden by parent rule.

---

tools/test-js-with-node
web/src/message_actions_popover.ts
web/src/message_delete.ts
web/src/message_edit.ts
web/src/popover_menus_data.ts
web/src/topic_popover.ts
web/tests/message_delete.test.cjs
web/tests/message_edit.test.cjs
web/tests/stream_data.test.cjs

Extracts message delete function in a new file `message_delete.ts`.
Follow-up for https://github.com/zulip/zulip/pull/35045#discussion_r2207446204.
<details>
</details>

message_delete: Refactor message delete functions in a new file.

---

web/src/inbox_ui.ts
web/src/recent_view_ui.ts

We focus on the middle row instead of the top which is what we use for recent view. Recent view doesn't have this problem, AFAIK, so hopefully this will fix it.

inbox: Attemp to fix inbox scrolling to top on scrolling down.

---

eslint.config.js
help-beta/src/components/KeyboardTip.astro

Commit 1 fixes failing tests on existing main.
Commit 2:
We do not want icon + `Keyboard Tip:` to occupy it's own row. Our approach for this component and most of the logic is similar to ZulipTip. We prefer having separate components for note, tip and keyboard tip, that is why we have duplicated code between ZulipTip and KeyboardTip, we should think about having a single underlying component for both to avoid duplication in the future.
We do not have any cases of non paragraph content in keyboard tip, so we have removed that chunk of code when copying over logic from ZulipTip.
<details> …

help-beta: Make icon + Keyboard Tip: a prefix instead of header.

---

web/styles/recent_view.css
web/templates/recent_view_row.hbs

This PR fixes an odd and ironic bug (given that line-clamping is a WebKit-native thing) where Safari always incorrectly applies an ellipsis to usernames in 1:1 DM rows, no matter the length of the username or the amount of space available in the Topics column to display it.
[#issues > Safari truncates 1:1 DM usernames in recents](https://chat.zulip.org/#narrow/channel/9-issues/topic/Safari.20truncates.201.3A1.20DM.20usernames.20in.20recents)
_Safari:_
| --- | --- |
| <img width="2694" height="2016" alt="safari-recent-widest-before" src="https://github.com/user-attachments/assets/01c86968-1b7c-4e9a-a316-c5ec26249896" /> | <img width="2694" height="2016" alt="safari-recent-widest-after" …

recent_view: Correct a Safari bug with line-clamping.

---

zerver/lib/event_types.py

Commit c049259d077b3ba9c1348cd8da278107149d6ee0 (#33739) should have removed this completely, rather than merely removing its is_billing_admin member.
- Cc @Vector73 (#33739).

event_types: Remove defunct PersonIsBillingAdmin

---

web/templates/recent_view_table.hbs

We no longer show keyboard shortcuts in placeholders.
We could consider adding a tooltip (with a long delay).

recent: Follow current pattern for placeholder text.

---

web/src/hotkey.js
web/styles/left_sidebar.css
web/templates/left_sidebar.hbs
web/templates/more_pms.hbs

This PR consists of multiple commits aimed at improving the keyboard navigation (certain links were not tab-able and certain links did not react to ENTER key being pressed) and fixes the focus styles for certain other links.
Fixes: [](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Tab.20from.20topic.20filter.20not.20working.20as.20expected)[#issues > 🎯 Tab from topic filter not working as expected](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Tab.20from.20topic.20filter.20not.20working.20as.20expected) and several other issues with keyboard navigation/focus styles in the left sidebar on debugging.
| ![stream_topic_list-before](https://github.com/user-attachments/assets/ …

left_sidebar: Fix keyboard navigation and focus styles for left sidebar items.

---

web/src/pm_list.ts

`clear_search` doesn't reset the filter text which causes the issue, hence fixed by clearning the filter text here.
Here are the steps to reproduce:
In the sidebar, under "Direct Messages" click "More Conversations"
In the "Filter direct messages" box, enter some search term
Without clearing the search term, click "Back to channels"

pm_list: Fix dm filter not cleared on zooming out.

---

web/src/compose.js
web/src/compose_banner.ts

Since this is the only INFO banner that needs to be cleared on clearing compose box, I've added a
function specific to it.
<details>
</details>

compose_banners: Clear `convert_pasted_text_to_file` on sending message.

---

zerver/lib/push_notifications.py

PR to address https://github.com/zulip/zulip/pull/35432#discussion_r2229763718
> we'll want to release with DEVELOPMENT guard removed next week.                        
<details>
</details>

push_notification: Remove dev guard from send E2EE notification codepath.

---

help/connect-through-a-proxy.md
help/getting-started-with-zulip.md
help/include/reading-conversations.md
help/reading-strategies.md

[#documentation > new help center: headings](https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20headings)
**Updates**:
- Revises headers in "Connect through a proxy" to be sequential.
- Inlines headers and updates shared content include file used in "Reading strategies" and "Getting started with Zulip" articles.
---
| Current | New |
| --- | --- |
| <img width="759" height="1057" alt="Screenshot 2025-07-26 at 16 37 27" src="https://github.com/user-attachments/assets/96ecc95e-c2f5-48c4-94a3-cf90a439fc63" /> | <img width="756" height="995" alt="Screenshot 2025-07-26 at 16 38 21" src="https://github.com/user-attachments/assets/a3f66a32-65d4-4221-b6cf-43a37701ee71" />

help: Inline h4 headers that are directly after h3 headers.

---

help/emoji-reactions.md
help/include/go-to-draft-messages.md
help/include/go-to-reminders.md
help/include/go-to-scheduled-messages.md

When reviewing the new help center docs, noticed that some of the instruction blocks did not have a space between the icon and the label (reactions view, drafts, scheduled messages, reminders). This is not as visible in the current help center, but definitely an improvement in the new help center...
| --- | --- |
| <img width="747" height="342" alt="Screenshot 2025-07-26 at 16 15 50" src="https://github.com/user-attachments/assets/4247c37f-d2d2-453d-be5b-96e9670d83ac" /> | <img width="751" height="342" alt="Screenshot 2025-07-26 at 16 25 30" src="https://github.com/user-attachments/assets/b6a867dd-e4c7-492d-9b81-e00e0a62003c" />
---
**Current help center screenshots:**
| --- | --- |
| <img width="757" height="347" alt="Screenshot 2025-07-26 at 16 15 …

help: Add missing space after icons in instruction blocks.

---

web/styles/app_variables.css
web/styles/search.css

[#design > search typeahead background](https://chat.zulip.org/#narrow/channel/101-design/topic/search.20typeahead.20background)
| Before | After (no change in light mode) |
| --- | --- |
| <img width="1860" height="650" alt="search-bar-light-before" src="https://github.com/user-attachments/assets/67d83c9c-e7c8-4710-acb6-8e0eab91cdd9" /> | <img width="1860" height="650" alt="search-bar-light-after--no-change" src="https://github.com/user-attachments/assets/5de3b3a8-a841-41b5-a2a6-5f4f31a6d2f4" /> |
| <img width="1860" height="650" alt="search-bar-dark-before" src="https://github.com/user-attachments/assets/088b83d2-1e2b-4431-a6a1-750ef0b5514f" /> | <img width="1860" height="650" alt="search-bar-dark-after" …

search: Tune colors to Vlad's proposals.

---

zerver/lib/push_notifications.py
zerver/lib/test_classes.py
zerver/tests/test_e2ee_push_notifications.py
zerver/tests/test_handle_push_notification.py
zerver/tests/test_push_notifications.py

First commit: Small change to return early in legacy codepath. - See commit message.
Second commit: Tests improvement.
<details>
</details>

test_e2ee_push_notification: Improve tests to cover more cases.

---

web/src/stream_edit_subscribers.ts
web/src/user_group_edit_members.ts
web/templates/components/banner.hbs
web/templates/components/membership_banner.hbs
web/templates/components/subscription_banner.hbs
web/templates/stream_settings/stream_members.hbs
web/templates/stream_settings/stream_subscription_request_result.hbs
web/templates/user_group_settings/user_group_members.hbs
web/templates/user_group_settings/user_group_membership_request_result.hbs

Fixes:
https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20User.20add.20success.20banner.20squashed/near/2229035.
We switch to using the banner template to avoid regressions caused by changes in the original banner template which aren't duplicated in the subscription result templates for channel/groups.
The original issue was caused by the introduction of the `.banner-content` class, which wasn't present in the user/group result templates in d00cf1a0e85c19a1238ce438fa67909afa9b3325.
|----|-----|
|<img width="720" height="155" alt="image" src="https://github.com/user-attachments/assets/5258f104-62da-4303-aeb7-121842b5c720" />| <img width="737" height="313" alt="image" src="https://github.com/user-attachments/assets/70cfcc3d-6545-4e39-aa88-6e833fe2880a" …

settings: Fix text overflow in banners.

---

zerver/actions/message_edit.py
zerver/tests/test_message_move_topic.py

Previously, when there were two topics -- A and B, and a user follows topic A, then when messages of topic B are merged into topic A then topic A loses its follow status.
This is fixed by updating the algorithm for getting the visibility policy after merge to be followed in the above case.
Fixes #35226
Fixes: 
<details>
</details>

topics: Follow topics that are merged into even after merge.

---

web/src/favicon.ts
web/src/inbox_ui.ts
web/src/message_list_view.ts
web/src/recent_view_ui.ts
web/src/stream_popover.ts
web/src/unread_ops.ts
web/templates/favicon.svg.hbs
web/templates/inbox_view/inbox_row.hbs
web/templates/modal_banner/unsubscribed_participants_warning_banner.hbs
web/templates/recent_view_row.hbs
web/templates/recipient_row.hbs
web/templates/skipped_marking_unread.hbs
web/templates/stream_settings/copy_email_address_modal.hbs

This updates variable names to clearly denote that they are HTML strings which should not be escaped like other variables in the templates.
These variables are renamed from `variable` to `variable_html`.
Some might sound more natural by prefixing with `html_`, suggestions are welcome.
The last commit replaces the use of  `{{{` with `{{` because I did not find any instance of  `description`  in HTML format.
Fixes:  https://github.com/zulip/zulip/pull/34912#issuecomment-3091355122

web: Refactor variables to indicate markup.

---

web/styles/app_variables.css
web/styles/inbox.css
web/templates/inbox_view/inbox_folder_row.hbs
web/templates/inbox_view/inbox_stream_header_row.hbs

This PR implements the light-mode chevron colors (based on the `--grey-600` color) and collapsed-state opacity Vlad has called for; it interpolates a dark-mode scheme using the brighter `--grey-300` color.
[#design > channel folders UI: Inbox @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/channel.20folders.20UI.3A.20Inbox/near/2229545)
Vlad's [Figma file](https://www.figma.com/design/jbNOiBWvbtLuHaiTj4CW0G/Zulip-Web-App?node-id=8733-68284&t=otdkL0LuC5GIBVqu-0)
_With header colors on folder rows, and Vlad's spec'd colors on channel rows:_
| Light mode | Dark mode |
| --- | --- |
| <img width="1106" height="700" alt="inbox-chevrons-header-colors-light" src="https://github.com/user-attachments/assets/962b32c3-58be-40a5-b95e-cf5b73a8ba55" /> …

inbox: Color chevrons according to Vlad's Figma spec.

---

help-beta/src/components/KeyboardTip.astro
help-beta/src/scripts/client/adjust_mac_kbd_tags.ts
help-beta/src/styles/main.css
web/styles/app_variables.css

Commit 1:
Fixes https://github.com/zulip/zulip/issues/35122.
The existing colors were attracting too much attention.
Design discussion was done on https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20design.
Commit 2:
Fixes https://github.com/zulip/zulip/issues/35118.
Visual tuning for this was done on a call, some of it was done in https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20design
For dark theme, we use the same color as we use in styling `.tooltip-hotkey-hint`. For light theme, we brainstormed a color that looked fine to us. Padding and font-size was also experimented and set. Since we just took inspiration from `tooltip-hotkey-hint` and did not use the same styling i.e. tweaked them, we do not add any …

help-beta: Change color for asides and change styling for keyboard shortcuts.

---

web/src/stream_settings_ui.ts

It's an administrator action to edit channel folder membership, so it doesn't make sense to update the user view for this action.
Fixes #35493.

left_sidebar: Don't scroll stream into view on folder update.

---

web/src/inbox_ui.ts
web/src/stream_list_sort.ts

We're changing this so that in views like inbox (which only shows locations with unreads), it feels a bit weird for it to possibly only have a "DIRECT MESSAGES" and then "OTHER CHANNELS" section, if your only unreads are in non-pinned folders.
More discussion here:
https://chat.zulip.org/#narrow/channel/101-design/topic/channel.20folders.20in.20left.20sidebar.20.2331972/near/2231091

left_sidebar: Rename OTHER CHANNELS folder to CHANNELS.

---

help/include/set-status.md
help/status-and-availability.md

Updates the mobile documentation for setting and clearing a user status.
Relevant mobile issue: https://github.com/zulip/zulip-flutter/issues/198
[CURRENT DOC](https://zulip.com/help/status-and-availability#statuses)

help: Add mobile instructions for setting and clearing user status.

---

web/src/compose_notifications.ts
web/src/message_view.ts

discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20view.20jumping.20to.20the.20top.20unexpectedly/with/2231100

Fix user jumping to top when sending a message in a `near` narrow with `old_unreads_missing`.

---

help/desktop-notifications.md
help/email-notifications.md
help/hide-message-content-in-emails.md
help/mobile-notifications.md

Note:
- We'll need to add a link to the help center documentation from production docs, but I think that's easier to do once this PR has been deployed?

help: Update notifications docs, including E2EE.

---

help/configure-unread-message-counters.md
web/src/left_sidebar_navigation_area.ts
web/src/server_events_dispatch.js
web/src/settings_config.ts
web/src/sidebar_ui.ts
web/src/stream_list.ts
web/styles/left_sidebar.css
web/tests/dispatch.test.cjs

Fixes #35326. More details in individual commit messages.

Apply hide unread summary count setting only to the home view & clean up related CSS

---

api_docs/integrations-overview.md
help/deactivate-or-reactivate-a-user.md
help/status-and-availability.md
tools/convert-help-center-docs-to-mdx

[help-beta: Stop asides from making a tight list loose.](https://github.com/zulip/zulip/pull/35534/commits/39d64945f0f843d103d1c1d878fe3eb68360c14b)
A lot of our admonition declaration had an empty new line in the beginning which was getting ported over in the conversion. This caused the asides to unintentionally mark a tight list as loose which we do not want.
[help: Make loose lists tight.](https://github.com/zulip/zulip/pull/35534/commits/52b4f911e8b1cccf8fa7a03c4f5f02bf7390f824)
I missed converting `integrations-overview.md` since it was a file in `api_docs` without realising that we had a symlink in help/ that pointed to that file. I'm not sure how the other two files were missed but we corrrect here nonetheless.
We have a few files where we have blank lines before tables and tips, …

help-beta: Fix loose bullet list spacing where possible

---

web/tests/left_sidebar_navigation_area.test.cjs
web/tests/stream_list.test.cjs

These became unused in #35075 (cc @evykassirer).
```console
$ tools/test-js-with-node
…
running test left_sidebar_navigation_area
You asked to mock /srv/zulip/web/src/scheduled_messages.ts but we never saw it during compilation.
You asked to mock /srv/zulip/web/src/message_reminder.ts but we never saw it during compilation.
…
running test stream_list
You asked to mock /srv/zulip/web/src/group_permission_settings.ts but we never saw it during compilation.
You asked to mock /srv/zulip/web/src/unread_ui.ts but we never saw it during compilation.
```

tests: Remove unused mocks

---

help-beta/astro.config.mjs

Updates the sidebar in the new help center for what is currently in `help/include/sidebar_index.md`, specifically for the **Organization settings** section:
| Current | New |
| --- | --- |
| <img width="281" height="400" alt="Screenshot 2025-07-30 at 20 44 35" src="https://github.com/user-attachments/assets/144ccbbb-3b6d-4f90-a1dc-52bf8e52575a" /> | <img width="285" height="456" alt="Screenshot 2025-07-30 at 20 44 05" src="https://github.com/user-attachments/assets/02a23c17-2776-4161-915a-7ec3c0a409b9" />

new-help-center: Update left sidebar for current help center state.

---

web/src/compose.js
web/src/drafts.ts

Came across this error while working on another PR.
If we are sending a message with characters less than `MINIMUM_MESSAGE_LENGTH_TO_SAVE_DRAFT` and message send fails, it shows an error as it tries to update the draft state.
This commit fixes this behaviour by only updating draft state if we had saved a copy of the message as draft.
**Before:**
[Screencast from 2025-07-25 22-25-53.webm](https://github.com/user-attachments/assets/d2d6358c-ab17-4689-a395-a4254ed45360)
**After:**
[Screencast from 2025-07-28 01-15-13.webm](https://github.com/user-attachments/assets/e760e201-d9a8-4269-a711-a01606d677da)
<details> …

message_send: Fix update draft error when message send fails.

---

help/configure-automated-notices.md
help/include/automated-dm-channel-subscription.md
help/include/automated-notice-channel-event.md
help/include/configure-resolved-notices-marked-as-read.md
help/move-content-to-another-channel.md
help/resolve-a-topic.md

In the help center, we want these two system bots to be referred to as names:
- capitalize both words
- no bold
- no links
- no "the" before the bot's name
[#documentation > bot name styling](https://chat.zulip.org/#narrow/channel/19-documentation/topic/bot.20name.20styling)
**Notes**:
- The references to "Welcome Bot" in the help center were all fine with the guidelines above, so the changes are all for "Notification Bot", which is mentioned more.
---
[CURRENT DOC](https://zulip.com/help/configure-automated-notices)
[CURRENT DOC](https://zulip.com/help/subscribe-users-to-a-channel)
[CURRENT DOC](https://zulip.com/help/rename-a-channel)
[CURRENT DOC](https://zulip.com/help/move-content-to-another-channel)
[CURRENT …

help: Standardize Welcome Bot and Notification Bot styling.

---

tools/convert-help-center-docs-to-mdx

Use the icon's name, in camelcase, with the suffix "Icon" for icon class names in the new help center documentation. E.g., `zulip-icon-external-link` becomes `ExternalLinkIcon` and `fa fa-plus` becomes `PlusIcon`.
[#documentation > new help center: Icon class names](https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20Icon.20class.20names)
**Notes**:
- After building the help-beta docs with these changes and calling `pnpm run format` on that directory, there were no syntax errors reported for duplicate identifiers. Therefore, none of the zulip and 'fa fa' icons with the same name (e.g., download and pencil) are imported/used in the same file.
| --- | --- |
| `import ZulipIconsDownload from "~icons/zulip-icon/download"` | `import …

help-beta: Adjust icon class names in the conversion process.

---

help/change-the-color-of-a-channel.md
help/channel-folders.md
help/left-sidebar.md
help/pin-a-channel.md

We'll probably want to add some notes about when to use the new left sidebar setting, but let's do that as a follow-up.
<details>
<summary>
Screenshots
</summary>
[other sections]
</details>

help: Document folders in the left sidebar setting + misc. touch-ups.

---

web/src/settings_notifications.ts
web/templates/settings/notification_settings.hbs

As @alya notes in PR #34491 that "This banner should not appear in org settings, only in personal settings"
Fixes: [Thread Link](https://github.com/zulip/zulip/pull/34491#issuecomment-3137137775).
<details>
</details>

desktop-notification-banner: Remove the banner form the org settings.

---

zerver/lib/push_notifications.py

This doesn’t exist when `ZILENCER_ENABLED` is `False`.
- Cc @prakhar1144 (#35139)
- [Discussion](https://chat.zulip.org/#narrow/channel/2-general/topic/Zulip.2011.2E0.20upgrades/near/2236632)

push_notifications: Guard reference to RemotePushDevice

---

web/src/stream_list.ts

This PR ensures that the focus on the topic list search box is only triggered when the user clicks on the "SHOW ALL TOPICS" button, and not when the narrow changes. This prevents unwanted focus behavior when switching between different narrows/views which interfered with the focus states of the compose box.
Fixes: [#issues > 🎯 "Filter topics" incorrectly gaining focus with back @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20.22Filter.20topics.22.20incorrectly.20gaining.20focus.20with.20back/near/2236393)
| ![topic_filter_focus_behavior-before](https://github.com/user-attachments/assets/5f4adcc8-9685-4566-9730-cd480a718e74) | ![topic_filter_focus_behavior-after](https://github.com/user-att …

stream_list: Fix focus behavior for topic list search box.

---

help-beta/src/components/NavigationSteps.astro

Because some of the raw icon files have a trailing new line, add the raw icon svg to the data used for the `NavigationStep` component and format the label with the trimmed icon svg.
Relevant CZO converasation: [#documentation > new help center: icons that are links](https://chat.zulip.org/#narrow/channel/19-documentation/topic/new.20help.20center.3A.20icons.20that.20are.20links)
**Notes**:
- There's a prep commit to update the import icon class names to better match help center content icon class names ([#documentation > ✔ new help center: Icon class names](https://chat.zulip.org/#narrow/channel/19-documentation/topic/.E2.9C.94.20new.20help.20center.3A.20Icon.20class.20names)).
- The final commit adds the icon for the non-relative link settings instruction for selecting either …

help-beta: Add icons to NavigationSteps data.

---

web/src/left_sidebar_navigation_area.ts
web/src/sidebar_ui.ts
web/styles/left_sidebar.css
web/templates/left_sidebar.hbs

[#design > unread counts in condensed views](https://chat.zulip.org/#narrow/channel/101-design/topic/unread.20counts.20in.20condensed.20views), with initial discussion at [#feedback > show unreads when collapsing VIEWS](https://chat.zulip.org/#narrow/channel/137-feedback/topic/show.20unreads.20when.20collapsing.20VIEWS/with/2234548)
| --- | --- |
| <img width="660" height="422" alt="condensed-views-with-unreads-home-view-active-before" src="https://github.com/user-attachments/assets/4a053b65-95a6-4897-8977-6ae60bd327c9" /> | <img width="660" height="422" alt="condensed-views-with-unreads-home-view-active-after" src="https://github.com/user-attachments/assets/693067ad-3917-435e-adf5-364a9a1bcad5" /> |
<details> …

left_sidebar: Show home unread count in condensed views.

---

web/src/compose_setup.js
web/tests/compose.test.cjs
web/tests/compose_video.test.cjs

This pull request makes it so any message being written saves as a draft when the user switches tabs.
The update_draft function from drafts.ts is called in the on-blur handler for window to prevent message loss. 
Fixes [#35262: Save open draft on window blur](https://github.com/zulip/zulip/issues/35262)
**Screen capture**
https://github.com/user-attachments/assets/f8c50ce6-55e6-4f89-b18f-1979a8653de5
An example of typing a message, switching tabs, and the message saving as a draft.
<details>
Completed …

Save messages as drafts when window loses focus

---

web/src/postprocess_content.ts
web/styles/rendered_markdown.css
web/tests/postprocess_content.test.cjs

This PR does a number of cosmetic things to inline audio players:
* It reverts changes from #35257 that attempted to use fragile shadow-DOM styling to modify native audio players with limited success and the likelihood of ongoing maintenance headaches
* It instead allows native audio players to render as they do in whatever browser is displaying them; if we want a more uniform cross-browser experience and better control over how players are rendered, a well-maintained third-party audio player is the likely solution here
* It attaches wraps `<audio>` elements in a span with a `.media-audio-wrapper` class, and also attaches a `.media-audio-element` class to the `<audio>` element itself
* It vertically aligns audio players to `middle`, which was [the design-discussion …

audio_player: Fixups to present browser-native players.

---

web/src/settings_banner.ts

Fixes: [Comment](https://github.com/zulip/zulip/pull/34491/commits/7019e293dece899368a98d20ca7957248f2a7e64#r2248335886)
Instead of defining three separate banner objects with mostly identical properties, dynamically construct the buttons array and intent based on user permissions and organization type.
Also changed "Upgrade to access" button text to just "Upgrade" for consistency.
|---|---|
| <img width="453" height="60" alt="Screenshot 2025-08-03 at 10 49 24 PM" src="https://github.com/user-attachments/assets/fa3f549d-2d8a-4ccc-a569-6f93636185c6" /> |<img width="415" height="64" alt="Screenshot 2025-08-03 at 10 34 00 PM" src="https://github.com/user-attachments/assets/33ef2288-67e5-439f-ae02-43ee69643532" /> |
Fixes: 
<details> …

upgrade-banners: Refactor upgrade banners.

---

web/src/dropdown_widget.ts
web/styles/app_components.css
web/templates/dropdown_list_container.hbs

This PR remove the `button` and `rounded` class from `sticky-bottom-option button`, which don't do much useful.
Added some additional rules on the `sticky-bottom-option` which were previously there via `button` class.
Also rename `sticky-bottom-option` to `sticky-bottom-option-button`.
Fixes:  [Comment](https://github.com/zulip/zulip/issues/35006#issuecomment-3085758087)
| State | Before | After |
|--|---|---|
| Normal | <img width="348" height="61" alt="Screenshot 2025-08-07 at 3 38 41 PM" src="https://github.com/user-attachments/assets/488a30e1-32ce-4120-9471-0ddbc30d42b3" /> | <img width="326" height="54" alt="Screenshot 2025-08-07 at 3 35 00 PM" src="https://github.com/user-attachments/assets/960b267c-513e-464d-bac7-e3277c33f398" /> |
| Hovered | …

buttons: Redesign sticky-bottom-option button.

---

web/styles/app_components.css
web/styles/app_variables.css
web/styles/left_sidebar.css

Discussed here: [#frontend > muted vs unmuted mention indicator @ 💬](https://chat.zulip.org/#narrow/channel/6-frontend/topic/muted.20vs.20unmuted.20mention.20indicator/near/2238070)
~~**Looking for feedback on if this is a good level of opacity.**~~

left_sidebar: Make muted mention indicator more faded than unmuted.

---

tools/lib/capitalization.py
tools/test-js-with-node
web/src/topic_filter_pill.ts
web/src/topic_list.ts
web/src/topic_list_data.ts
web/styles/left_sidebar.css
web/templates/input_pill.hbs
web/tests/topic_list_data.test.cjs

This PR addresses several improvements related to how pills are implemented and displayed:
* **Replaces usage of `search_pill`** with a minimal wrapper module (`topic_filter_pill.ts`), similar to the approach used in `web/src/integration_branch_pill.ts`.
* **Refactors `get_typeahead_search_term`** to use `data-syntax` attribute instead of relying on text/string matching to determine filtering logic.
* **Restores display of description labels** instead of raw syntax in the pill UI, now that filtering logic is decoupled from the displayed text.
Fixes part of: #35284.
| After | Before |
|-----|--|
| <img width="330" height="56" alt="Screenshot 2025-07-28 at 6 41 52 PM" src="https://github.com/user-attachments/assets/13305690-d662-44ab-be35-dfdf57c94360" …

Further clean up the topic list filtering typeahead logic.

---

web/src/buddy_list.ts

Reported here: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20sidebar.20keyboard.20nav.20doesn't.20skip.20collapsed.20sections/near/2214081

buddy_list: Skip collapsed section users during keyboard navigation.

---

web/styles/left_sidebar.css

This PR replaces top margin with top padding to avoid clipping tall glyphs in the DM rows, as reported in the issue below, and also topic rows, where the same approach to space was causing the same clipping.
Fixes: [](https://chat.zulip.org/#narrow/channel/9-issues/topic/tall.20characters.20cut.20off.20in.20left.20sidebar.20DMs)[#issues > tall characters cut off in left sidebar DMs](https://chat.zulip.org/#narrow/channel/9-issues/topic/tall.20characters.20cut.20off.20in.20left.20sidebar.20DMs)
| --- | --- |
| <img width="760" height="1240" alt="clipped-chars-before" src="https://github.com/user-attachments/assets/8e2c96dc-c848-4c91-9c60-bfeb191c5cf5" /> | <img width="760" height="1240" alt="clipped-chars-after" …

left_sidebar: Avoid clipping tall glyphs in DM groups, topics.

---

web/styles/compose.css

This PR makes sure that keyboard focus within the recipient row overrides the low-attention styles.
Fixes: [#design > recipient fading logic @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/recipient.20fading.20logic/near/2241251)
| --- | --- |
| ![low-att-keyboard-before](https://github.com/user-attachments/assets/46546e8c-caf3-4d6b-8d18-d52b9009075c) | ![low-att-keyboard-after](https://github.com/user-attachments/assets/d581413f-4832-4fc9-a3ad-848940458dd6) |
<details> …

compose: Suppress low-attention styles with keyboard focus.

---

web/src/channel_folders.ts
web/src/stream_edit.ts
web/templates/stream_settings/stream_permissions.hbs
web/tests/channel_folders.test.cjs

This PR -
- Adds a ? link to /help/channel-folders to the "Channel folder" channel setting.
- When there are no channel folders configured, for users who are not organization administrators/owners, replaces the setting label and dropdown with:
>  There are no channel folders configured in this organization. [[?]](https://github.com/help/channel-folders)
Fixes: zulip#35596.
| **Before** | **After** |
|------------------|----------------|
| <img width="547" height="115" alt="Screenshot from 2025-08-06 22-42-38" src="https://github.com/user-attachments/assets/04e2276c-f39e-4594-b427-3ab6df8225f2" /> | <img width="558" height="124" alt="Screenshot from 2025-08-06 22-25-54" src="https://github.com/user-attachments/assets/cdff138f-47f7-4e4f-be6d-f7507995ce4b" …

Improve channel folders setting UI.

---

web/styles/left_sidebar.css

Reported here: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20broken.20unread.20marker.20w.2F.20.22No.20channels.22.20configuration/near/2241414
I'm pretty sure this has been a bug ever since channel folders were introduced!

left_sidebar: Hide counts in section header when no unreads.

---

zerver/lib/test_classes.py
zerver/openapi/zulip.yaml
zerver/views/streams.py

Discussion:
https://chat.zulip.org/#narrow/channel/378-api-design/topic/Channel.20creation.20should.20return.20the.20channel.20ID/near/2240040.

zerver: Drop support for Zulip API emails in channel creation.

---

web/src/stream_settings_ui.ts
web/templates/stream_settings/stream_settings.hbs

This PR passes the `realm_has_channel_folders` properly to the templates.
Fixes bug from #35629
**After:**
<details>
</details>

Stream settings channel folders permissions fix

---

api_docs/changelog.md
tools/check-schemas
version.py
zerver/actions/presence.py
zerver/lib/event_schema.py
zerver/lib/event_types.py
zerver/lib/events.py
zerver/openapi/zulip.yaml
zerver/tests/test_events.py
zerver/tornado/django_api.py
zerver/tornado/event_queue.py
zerver/tornado/views.py

If the client has passed a value for `presence_last_update_id` in `client_capabilities` in its `/register` request, the server will send presence events in the modern format to that client. Otherwise, the legacy format is used.
<p>
**/api/get-events#presence**
**/api/register-queue#parameter-client_capabilities**
</p>
</details>
CZO discussion: [#api design > presence rewrite @ 💬](https://chat.zulip.org/#narrow/channel/378-api-design/topic/presence.20rewrite/near/2223670)
<details> …

events: Add support for sending presence events in modern format.

---

web/styles/zulip.css

This commit was not included correctly in the recently merged #35658. It scopes the alignment changes so that the snippet selector UI is not disturbed.

dropdown_lists: Scople alignment tweaks to folder selector.

---

web/styles/inbox.css

This fixes a subtle alignment issue with unreads in the DM header row versus the actual DM rows that follow.
Fixes: [#issues > 🎯 inbox direct messages unread count alignment](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20inbox.20direct.20messages.20unread.20count.20alignment)
| --- | --- |
| <img width="2200" height="1600" alt="dm-header-unread-alignment-before" src="https://github.com/user-attachments/assets/231a4829-82d2-4f56-a63a-984f460ac67f" /> | <img width="2200" height="1600" alt="dm-header-unread-alignment-after" src="https://github.com/user-attachments/assets/7cd8b7e0-6513-407f-bb49-bab87d92fed9" /> |
<details> …

inbox: Move lefthand padding to avoid disturbing grid.

---

help/scim.md

quick tweaks to #35694
Fixes a couple of typos and rewords the "nested groups" paragraph a bit.

help: Tweaks to SCIM group sync documentation wording.

---

web/src/settings.ts
web/src/settings_org.ts
web/styles/settings.css
web/styles/zulip.css

This PR aims solves the following follow-ups from #32862, as mentioned in issue #35664:
> - We could make the "View message" button open in a new tab. This seems simplest and would be quite easy, so we should > default to that as a first step.
> - We could do something to preserve what you've typed in the textarea, even after the overlay is closed. This may be a 
> finicky, since we'd need it to reopen with that changed text and a save/change widget.
Fixes: #35664.
- "View message" button opens the message in a new tab:
- Unsaved welcome bot message is saved on closing the overlay. The message is restored if we open the overlay again.
---
<details>
Communicate …

org_settings: Preserve custom Welcome Bot message when testing or viewing message.

---

web/src/ui_util.ts
web/styles/app_components.css
web/styles/left_sidebar.css

Reported here: [#issues > 🎯 @ marker on expanded folder @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20.40.20marker.20on.20expanded.20folder/near/2241907)

Hide mention marker on expanded folder

---

web/src/sidebar_ui.ts

The zoomed in topic list search doesn't work if user searches something and presses `enter` on `Show all topics` after navigating via keyboard.
Fixed by not triggering `input` event on left sidebar search input which seems to confuse the zoomed in topic search.
Reproducer:
* Search a term in left sidebar.
* Navigate to show all topics
* We are navigated to zoomed in topics but search doesn't work.

sidebar_ui: Fix broken zoomed in topic list.

---

help/unsubscribe-from-a-channel.md

Updates the mobile tab instructions for unsubscribing from a channel.
Relevant Flutter issue and PR:
- issue: https://github.com/zulip/zulip-flutter/issues/1224
- PR: https://github.com/zulip/zulip-flutter/pull/1790
**Notes**:
- While it's also possible to subscribe to a channel via the channel actions menu in the mobile app, there isn't a way to currently browse unsubscribed channels.
- Flutter issue for that is https://github.com/zulip/zulip-flutter/issues/188.
- CZO conversation about how to potentially document the subscribe action at: [#documentation > subscribe to a channel - adding mobile instructions #F1790](https://chat.zulip.org/#narrow/channel/19-documentation/topic/subscribe.20to.20a.20channel.20-.20adding.20mobile.20instructions.20.23F1790).
--- …

help: Add mobile instructions for unsubscribing from a channel.

---

web/styles/banners.css
web/templates/components/banner.hbs

Previously, the Handlebars template rendered the action buttons container only when buttons were present. This commit changes the approach to always render the container but hide it in CSS when it is empty, using the :empty pseudo-class.
Follow-up of #35670.
<details>
</details>

banners: Hide empty banner-action-buttons using CSS.

---

zerver/actions/message_edit.py
zerver/tests/test_events.py
zerver/tests/test_link_embed.py
zerver/worker/embed_links.py

Doing this generally, in markdown rendering, broke things because we're not consistent about if `mentions_user_ids` is "any user, no matter how they're mentioned" (as we need it for UserMessage flags) or "users that are specifically mentioned" (as we use it for event construction)

embeds: Propagate group membership before updating UserMessage flags.

---

web/src/sidebar_ui.ts

This happens since the don't exclude the row which toggles muted / inactive channels from all_rows, while user is searching and hence selections box ends up there while navigating to the muted / inactive channel row.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AFkeyboard.20navigation.20not.20working.20w.2F.20muted.2Finactive.20channels/with/2243202

sidebar_ui: Fix selection box disappears while navigating to muted row.

---

zerver/lib/push_notifications.py

This reverts #26594, due to unexpected ConnectionClosed errors observed in Django.
Fixes: 
<details>
</details>

push_notifications: Revert parallel-device sending.

---

web/src/topic_list.ts

Fixes bug reported here: [#issues > Left sidebar filter widget hiding @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/Left.20sidebar.20filter.20widget.20hiding/near/2244418)

topic_list: Enable left sidebar search when closing topic list.

---

templates/corporate/history.md

Current: https://zulip.com/history/
Updated screenshots:

portico: Extend /history events to August 2025.

---

zerver/actions/message_delete.py
zerver/actions/message_edit.py
zerver/actions/message_flags.py
zerver/actions/message_send.py
zerver/actions/uploads.py
zerver/lib/attachments.py
zerver/lib/email_notifications.py
zerver/lib/message.py
zerver/lib/message_report.py
zerver/lib/push_notifications.py
zerver/lib/reminders.py
zerver/lib/test_classes.py
zerver/models/messages.py
zerver/models/scheduled_jobs.py
zerver/tests/test_message_delete.py
zerver/tests/test_message_fetch.py
zerver/tests/test_retention.py
zerver/views/message_edit.py

This avoids a potential unnecessary message.recipient fetch required by is_stream_message(). is_stream_message() methods precedes the addition of the denormalized is_channel_message column and is now unnecessary.
In practice, we usually fetch Message objects with `.recipient` already, so I don't expect any notable performance impact here - but it's still a useful change to make.

message: Use .is_channel_message column instead of is_stream_message().

---

web/e2e-tests/drafts.test.ts
web/src/click_handlers.ts

CZO: [#issues > Link clicks are blocked when something is selected @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/Link.20clicks.20are.20blocked.20when.20something.20is.20selected/near/2244013)
This fixes the problem which happens when the following is true:
1. Composebox is open.
2. You select something on the page.
3. You click on some link.
Currently doing this will prevent the default click behavior which is not right and can get quite annoying.
We now switch to a more robust check which only prevents the click behavior on a link when the click lies inside the link which is selected, instead of blocking it when any selection exists.
Before: 
https://github.com/user-attachments/assets/ee4a463e-5cd6-4668-a7ef-6a83bfbfdf86
After: …

links: Fix unnecessary blocking of click behavior.

---

web/src/activity.ts
web/src/inbox_ui.ts
web/src/message_viewport.ts
web/src/overlay_util.ts
web/src/realm_logo.ts
web/src/recent_view_ui.ts
web/src/resize.ts
web/src/views_util.ts
web/tests/activity.test.cjs

[#kandra js errors > $scroll_container initialization @ 💬](https://chat.zulip.org/#narrow/channel/464-kandra-js-errors/topic/.24scroll_container.20initialization/near/2239892)
<details>
</details>

dom_selectors: Replace `html` selectors with `:root`, `document`.

---

zerver/views/streams.py

This reverts commit f119c3378981df50cc43e8ca7b2cbfd4031c38e4. With 51cef01c2921c9c35369f00052c1cba0c0ac35d2 merged, there is no need to fetch .recipient here, as it won't be accessed by the delete messages codepath.

delete_in_topic: Don't unnecessarily fetch .recipient.

---

pyproject.toml
tools/test-backend
uv.lock
version.py
zerver/actions/streams.py
zerver/lib/cache.py
zerver/lib/display_recipient.py
zerver/lib/markdown/__init__.py
zerver/lib/message.py
zerver/lib/message_cache.py
zerver/lib/singleton_bmemcached.py
zerver/lib/zstd_level9.py
zerver/tests/test_markdown.py
zerver/tests/test_reactions.py
zproject/computed_settings.py

This slightly reduces the access times for get_members with a hot cache -- on a 6000-user realm, p50 decreases from 521ms to 499ms, with a similar drop in p90.  The memcache storage space drops from 108288 bytes to 67168, saving 38%.  Real-life savings are expected to be closer to 10% -- this is a test realm with users which are all somewhat similar.
get_messages access times for hot caches are unchanged, but for cold caches, p50 for a 1400-message fetch drops from 581ms to 520ms.  The outliers are quite notable (especially as this is single-threaded and without nginx involved) especially as the time does not appear to be in memcached or postgres.  They're not new, or affected notably by this change, however.

memcached performance tweaks, zstd usage

---

zerver/tests/test_e2ee_push_notifications.py
zilencer/lib/push_notifications.py

PR to address: https://github.com/zulip/zulip/pull/35139#discussion_r2224020504
Fixes part of #35368
<details>
</details>

push_notifications: Use `SentPushNotificationResult` dataclass.

---

zerver/lib/reminders.py
zerver/tests/test_reminders.py

We must not intermix Markdown strings which are ready for the message, with format strings which we intend to interpolate on.
Fixes: 
<details>
</details>

reminders: Stop interpolating user-provided values in format string.

---

web/styles/message_row.css

Earlier, slow-send-spinner was working correctly for message with messagebox-includes-sender. Any subsequent messages with slow-send-spinner would result in broken animated because of rules not applying properly.
This PR fixes this behaviour by applying the rules for all messagebox-content and fixing the animation.
|**Before:**|**After:**|
|-|-|
|<video src="https://github.com/user-attachments/assets/a73b2450-4984-4505-bc3a-0206508786a5" />|<video src="https://github.com/user-attachments/assets/7a97b84e-719f-42ae-9416-8a0d01225958" />|
|<img width="241" height="145" alt="Screenshot from 2025-08-22 22-57-32" src="https://github.com/user-attachments/assets/d8227523-01fc-4d5e-b2c7-515688d3bff8" />|<img width="241" height="145" alt="Screenshot from …

css: Fix slow-send-spinner not applying on all messagebox-content.

---

zproject/computed_settings.py

zulip_groups is a special attribute, for the group sync feature, and will always be read from the SAMLResponse if it's present and group sync is enabled.
Listing it in extra_attrs is a misconfiguration that results in confusing behavior. See #35787.

saml: Don't allow listing zulip_groups in extra_attrs in IdP config.

---

zerver/openapi/zulip.yaml
zerver/tests/test_subs.py
zerver/views/streams.py

These are follow-ups to #31206:
- The first commit fixes a bug where stream notification messages were not being sent along with the DMs. The stream messages are fewer in number and won't be a big load on the server.
- The second commit introduces a test case for the sake of completion.
<details>
</details>

Improvements to the logic to avoid sending notification bot DMs on channel sub.

---

web/src/stream_list_sort.ts
web/tests/stream_list_sort.test.cjs

This stopped being used after 78a3ef56e437a9d705b027813e3cffe54f2a93d1.

stream_list_sort: Remove stream list row navigation code.

---

web/src/ui_init.js
web/src/user_events.ts
web/styles/zulip.css

This PR fixes a UI issue with the navbar avatars when the users have transparent portions of their background, causing the background of the avatars to be shown along with the actual users avatar. 
After discussions, this change also includes the removal of the square background border for the avatar image placeholder in the navbar aside from the gray background color of the avatar placeholder.
Fixes: https://github.com/zulip/zulip/issues/34466
#design thread Discussion: https://chat.zulip.org/#narrow/channel/101-design/topic/Don't.20show.20background.20behind.20transparent.20avatars.20in.20navbar/with/2206414
**Before (Fully opaque avatar):**
**Before (Transparent avatar):**
**After (Fully opaque avatar):**
**After (Transparent avatar):**

 Don't show background behind transparent avatars in navbar

---

web/src/buddy_data.ts
web/src/hash_util.ts
web/src/inbox_ui.ts
web/src/people.ts
web/src/pm_list_data.ts
web/src/user_card_popover.ts
web/tests/message_view.test.cjs
web/tests/people.test.cjs

Extracted from last commit in #34834 (as the first 2 have already been merged).
For further progress on extracting the rest of #34834, waiting for a definite reply of [#frontend > filter operand type: number or string? @ 💬](https://chat.zulip.org/#narrow/channel/6-frontend/topic/filter.20operand.20type.3A.20number.20or.20string.3F/near/2203962)

Changes to reduce usage of `email` property of user in frontend.

---

web/src/topic_popover.ts

This PR updates the topic URL in the message header topic menu popover, introduced in feedb6ea2de8e9e4ac1370e0d1fca719d4598623 to a permalink having a `with` operator attached to it.
Fixes: [#issues > copy link to topic URL doesn't have "with" operator @ 💬](https://chat.zulip.org/#narrow/channel/9-issues/topic/copy.20link.20to.20topic.20URL.20doesn't.20have.20.22with.22.20operator/near/2248021)
| Topic URL — Before | Topic URL — After |
| `[#Denmark > big WEB APP isn't running](http://localhost:9991/#narrow/channel/4-Denmark/topic/big.20WEB.20APP.20isn't.20running)` | `[#Denmark > big WEB APP isn't running](http://localhost:9991/#narrow/channel/4-Denmark/topic/big.20WEB.20APP.20isn't.20running/with/51)` | 
<details> …

topic_popover: Update topic URL to permalink for message header popover.

---

web/src/inbox_ui.ts
web/src/stream_list_sort.ts

channel_folders: Don't label section OTHER if there are no folders above it.

---

web/src/click_handlers.ts

Previously, clicking on links with the composebox open didn't close it.
7391a2983fa8d338d19a73c318b79d57e07ad635 introduced a bug where the composebox focus logic wasn't triggered at all if drag evidence wasn't present on the target.
We now do a `e.target.closest("a").length > 0` check like before and only prevent the default click behavior if dragging on the target link is detected.
This allows normal link clicks to trigger the
previous composebox focus trigger logic.
Fixes: https://chat.zulip.org/#narrow/channel/9-issues/topic/composebox.20closes.20when.20going.20to.20recent.20conversations
**Before:**
https://github.com/user-attachments/assets/4ba68783-5f1a-48be-96b8-4957f5343b66
**After:** …

composebox: Fix composebox closing on clicking links.

---

zerver/openapi/zulip.yaml

Fixes part of #35213 
> Once we integrate https://github.com/zulip/zulip/pull/35139, I expect we'll want to go through our API documentation for the old protocol and mark it all as deprecated/legacy.
Remaining endpoints to deprecate ([#api design > unregister push device](https://chat.zulip.org/#narrow/channel/378-api-design/topic/unregister.20push.20device/with/2250939)):
* https://zulip.com/api/remove-apns-token
* https://zulip.com/api/remove-fcm-token
---
<details> …

api_docs: Mark legacy mobile notifications endpoints as deprecated.

---

puppet/zulip/manifests/supervisor.pp

This was added in 6975417acfa8, to support `zmirror` deployments, which are no longer necessary.
Fixes: 
<details>
</details>

puppet: Stop using an unnecessary concat.

---

api_docs/include/rest-endpoints.md
zerver/openapi/curl_param_value_generators.py
zerver/openapi/zulip.yaml
zerver/tests/test_openapi.py

Adds a link to `/api/get-file-temporary-url` in response to @chrisbobbe's request.
[#api documentation > get-file-temporary-url in left sidebar](https://chat.zulip.org/#narrow/channel/412-api-documentation/topic/get-file-temporary-url.20in.20left.20sidebar)

api_docs: Add sidebar link to get-file-temporary-url.

---

web/src/resize.ts
web/styles/app_variables.css
web/styles/recent_view.css

In addition to matching the heights of all of the recents filters, this also adjusts the filter-widget dropdown to look like the filter input. Other recents filters are left as-is, deferring that work as part of a planned design pass.
[#design > recents filters layout, design](https://chat.zulip.org/#narrow/channel/101-design/topic/recents.20filters.20layout.2C.20design/with/2251809)
| --- | --- |
| <img width="1000" height="1600" alt="recent-filters-narrow-before" src="https://github.com/user-attachments/assets/1064a7f1-4d8c-4fb4-9539-8f1f43969c12" /> | <img width="1000" height="1600" alt="recent-filters-narrow-after" src="https://github.com/user-attachments/assets/2875736f-88ab-4416-a706-8985b7445c39" /> |
| <img width="2000" …

recents: Bring filters into concord with left, right sidebars.

---

zerver/lib/import_realm.py
zerver/tests/test_import_export.py

The import code wasn't setting subscriber_count at all, resulting in a value of 0 when dealing with imports from 3rd party apps. We run this unconditionally, also for imports from Zulip, since this ensures we won't inherit incorrect values, if the data we're import has them - e.g. due to some bugs that affected the server the data came from.

import: Set Stream.subscriber_count for imported channels.

---

starlight_help/src/components/Footer.astro

When we copied over the logic for the footer from the previous help center, I forgot to remove the double curly braces which were getting rendered as is in astro.
<details>
</details>

starlight_help: Do not use double curly braces for email address.

---

zerver/views/documentation.py
zproject/default_settings.py

`settings.ZULIP_SERVICES_URL` is used to contruct curl example for `/api/register-remote-push-device`.
On zulip cloud `settings.ZULIP_SERVICES_URL=None`, it resulted in 500 error on visiting that page.
This commit fixes the bug by using "https://push.zulipchat.com" as the default value if `settings.ZULIP_SERVICES_URL=None`.
The doc already mentions that the endpoint is meant to be used by self-hosted servers, so the default value makes sense if `ZULIP_SERVICES_URL=None`.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-disci …

api_docs: Fix 500 error on `/api/register-remote-push-device`.

---

web/styles/dark_theme.css

The feedback container doesn't have a border so it doesn't make sense to have a border color defined for the dark theme, and the hover color change on the `a` tag was an unintended side effect of commit d73a5d06c0e68d02822996be8bfa64253b788c93, which while correcting the hover effect on the typeaheads, also affected the link hover styles in the feedback container.
This PR, due the reasons mentioned above, removes the entire CSS block related to the feedback container from web/styles/dark_theme.css.
Fixes: Part 4 of #35880.
| <img width="920" height="228" alt="Screenshot 2025-09-09 at 4 35 32 PM" src="https://github.com/user-attachments/assets/54a594ba-9176-4099-b3ee-76821b4a574f" /> | <img width="920" height="228" …

dark_theme: Clean up feedback container styles.

---

web/styles/app_variables.css
web/styles/dark_theme.css
web/styles/widgets.css

NOTE: The mismatch between After/Before of the TODO widget in dark mode is because previously a `opacity: 0.7` was being applied to all the states of the checkbox in the `dark_theme.css`. When inspecting from a visual perspective, it was mostly only meant for the unchecked + unhovered state of the checkbox but was bleeding into other states of the checkbox as an unintentional consequence of the way the CSS was written.
Fixes: Part 2 of #35880.
<details><summary>Poll Widget</summary>
<p>
| Light + Hovered | <img width="1802" height="1024" alt="Screenshot 2025-09-09 at 12 19 31 PM" src="https://github.com/user-attachments/assets/5f1f3af2-e888-4eeb-8421-b5184c45aebf" /> | <img width="1802" height="1024" alt="Screenshot 2025-09-09 at 12 …

dark_theme: Cleanup todo and poll widgets.

---

web/src/bundles/app.ts
web/src/popover_menus.ts
web/styles/app_variables.css
web/styles/dark_theme.css
web/styles/popovers.css
web/styles/tooltips.css

This PR cleans up the Tippy box styles from `web/styles/dark_theme.css`, and also has a follow-up commit removing the unused "light-border" which was no longer in use, since all of our current popovers either use the "popover-menu" theme or the "dropdown-widget" theme.
Fixes: Part 5 of #35880.
| Desc | Header | Header |
| No theme | <img width="498" height="216" alt="Screenshot 2025-09-11 at 7 43 27 PM" src="https://github.com/user-attachments/assets/51b93107-0f32-4a02-88de-f5c85bf549f6" /> | <img width="498" height="216" alt="Screenshot 2025-09-11 at 7 42 37 PM" src="https://github.com/user-attachments/assets/68e10345-1eca-4513-b227-bc02c9bd5485" /> |
| Dropdown widget theme | <img width="512" height="554" alt="Screenshot …

dark_theme: Clean up Tippy box styles.

---

web/src/inbox_ui.ts
web/src/recent_view_ui.ts
web/src/views_util.ts

If one of the filters is focused or if we cannot determine the current focus location, any rerender call will scroll user to top.
Fixed by only scrolling to top when navigating from other views and when we don't have a cached scroll position.
Tested by calling `complete_rerender` at 1s intervals.
discussion: https://chat.zulip.org/#narrow/channel/9-issues/topic/.F0.9F.8E.AF.20Inbox.20view.20scroll.20position.20issues/with/2257437

inbox: Fix user scrolling to top on rerender if filters are focused.

---

starlight_help/src/components/NavigationSteps.astro
starlight_help/src/content/docs/channel-feed.mdx
starlight_help/src/content/docs/introduction-to-channels.mdx
web/e2e-tests/lib/common.ts
web/src/hash_util.ts
web/src/stream_edit.ts
web/src/stream_settings_ui.ts
web/src/stream_ui_updates.ts
web/src/tippyjs.ts
web/templates/popovers/left_sidebar/left_sidebar_stream_setting_popover.hbs
web/templates/stream_settings/stream_settings_overlay.hbs
web/templates/subscribe_to_more_streams.hbs
web/tests/stream_settings_ui.test.cjs

This PR replaces "Not subscribed" tab in stream settings with "Available" tab where
only streams which the user can subscribe to are shown.
Fixes #35919.
<details>
</details>

stream-settings: Replace "Not subscribed" tab with "Available" tab.

---

zerver/lib/notification_data.py
zerver/tornado/event_queue.py

In https://github.com/zulip/zulip/pull/35965 we added `push_device_registered_user_ids` to `message` & `update_message` event.
Zulip servers with such events in their event queues when upgraded to the new version set `push_device_registered_user_ids` to empty list, which is incorrect - it leads to no push notification sent.
This commit adds compatibility code to handle such events. The newly introduced `push_device_registered` check is used only for events with `push_device_registered_user_id` present in them.
<details>
Individual commits are ready for review (see [commit discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-di …

event_queue: Add compatibility code for `push_device_registered_user_ids`. 

---

templates/zerver/deactivated.html

This helps clarify that normal members cannot reactivate the org by contacting us.
| --- | --- |
| <img width="801" height="407" alt="Screenshot from 2025-09-24 14-27-31" src="https://github.com/user-attachments/assets/f1f0d930-1a5b-485f-9d61-67a0a118b670" /> | <img width="801" height="407" alt="image" src="https://github.com/user-attachments/assets/826b7ad3-6a28-4915-9983-0a3881f6abab" /> |

deactivated_org: Direct org members to contact org admins.

---

web/src/message_events.ts

Followup to https://github.com/zulip/zulip/pull/32492#discussion_r1878636631

message_events: Use MessageEditHistoryEntry type.

---

web/styles/inbox.css

This avoids an odd gap at the bottom of DM and folder groups when the last channel in a folder is expanded. It also preserves a space that probably should remain between the collapsed bottom-most channel and the folder name below (compare the space around the INFORMATION folder heading in the screenshots below).
[#issues > visual gap at the bottom of folder in inbox](https://chat.zulip.org/#narrow/channel/9-issues/topic/visual.20gap.20at.20the.20bottom.20of.20folder.20in.20inbox/with/2265164)
| --- | --- |
| <img width="1800" height="1600" alt="inbox-gaps-before" src="https://github.com/user-attachments/assets/a896e7cf-fbad-44ef-942b-bfb4efec4300" /> | <img width="1800" height="1600" alt="inbox-gaps-after" …

inbox: Correct margin declaration to avoid odd gap.

---

web/styles/inbox.css

If all channels in a folder are muted, then this margin is present in "Standard view", without there being any folder present.
Fixed by only applying margin if the folder has any header or rows that are not hidden by filters.
This is an alternative fix to #35962 which was reverted in #36123.

inbox: Avoid extra margin from folders hidden by filters.

---

zerver/lib/email_mirror.py
zerver/tests/test_email_mirror.py

Emails to missed-message email addressees which are marked "auto-replied" are clearly auto-replies, and will not contribute usefully to the conversation.  We also ignore "auto-generated" emails to missed-message addresses, as they must actually be auto-replies which are misclassifying themselves, as missed-message addresses are not meant to be targets for any auto-generated emails.
We accept auto-generated and auto-replied emails to stream incoming email addresses, as auto-generated emails to those are clearly useful, and auto-replied emails are unexpected enough to allow (given that Zulip does not produce outgoing emails From: stream email addresses).
Fixes: 
<details> …

email_mirror: Drop missed-message emails which are autogenerated.

---

web/src/compose_ui.ts
web/src/narrow_banner.ts
web/templates/reply_recipient_label.hbs
web/tests/compose_closed_ui.test.cjs
web/tests/message_view.test.cjs

Fixes: [#mobile-design > placeholder for messages to yourself](https://chat.zulip.org/#narrow/channel/530-mobile-design/topic/placeholder.20for.20messages.20to.20yourself/with/2265885)

compose and feed: Improve label for DMs to yourself.

---

templates/zerver/development/dev_help.html
templates/zerver/development/dev_tools.html
templates/zerver/development/help_center_instructions_macro.html
tools/lib/test_server.py
tools/run-dev
web/styles/portico/dev_help.css
web/webpack.dev-assets.json
zerver/tests/test_docs.py
zerver/views/development/help.py
zproject/dev_urls.py

Instead of repurposing `--help-center-dev-server` as discussed on CZO, I have added `--only-help-center` as an additional option instead giving the freedom for people with higher spec machines to run the dev server side by side to the zulip app.
I tested all 3 flags with run-dev. For `--help-center-static-build` and `--help-center-dev-server`, I also checked whether typing a non existed help URL would lead to the new default error page and it did not. 
Devtools page:
Invalid path:
/help/status-and-availability:
/help root:
<details> …

help: Add default help page when astro server is not running in development

---

web/src/postprocess_content.ts
web/tests/postprocess_content.test.cjs

This PR represents a major reorganization and refactor of how Zulip postprocesses content. This will improve this area of the codebase significantly, and should make it trivial to postprocess forthcoming Markdown inline images without a lot of acrobatics. Among the improvements here:
1. Link processing is now detached from image processing, resulting in code that is easier to digest--and that reflects the division in link vs. image tests introduced in #36052
2. Download processing is now properly part of link processing, rather than an odd branch off of image processing.
3. Image processing (apart from image galleries, which are still handled as a separate loop) is now handled in a single loop, entirely based on what comes down from the server. Previous logic was a mix of server- and …

postprocess: Clean up and refactor embed, link, and image postprocessing.

---

web/src/stream_list.ts

We shouldn't include muted topics from unmuted channels in the inactive/muted toggle count, since those unreads aren't in the inactive/muted section. This fixes that.
Reported here: https://github.com/zulip/zulip/issues/36011#issuecomment-3327042885

stream_list: Fix inactive/muted count bug.

---

web/src/drafts.ts
web/styles/zulip.css
web/templates/draft.hbs
web/tests/drafts.test.cjs

This PR handles the empty channel placeholder for drafts saved without a channel selected. When these drafts also do not have a topic, we display "No topic selected" in tandem with "No channel selected", since we are unable to access the channel configuration to determine if we should display **realm_empty_topic_display_name**.
Follow-up PR for #34455.
CZO Discussion: [#design > header bar when recipient isn't fully specified @ 💬](https://chat.zulip.org/#narrow/channel/101-design/topic/header.20bar.20when.20recipient.20isn't.20fully.20specified/near/2127548)
| <img width="1798" height="1340" alt="Screenshot 2025-09-24 at 3 22 05 PM" src="https://github.com/user-attachments/assets/861fef81-85d8-4648-8833-91337b8a7ed …

drafts: Add placeholder text for drafts with no channel selected.

---

puppet/zulip/manifests/postgresql_base.pp
puppet/zulip/templates/postgresql/pgroonga_setup.sql.template.erb
scripts/setup/create-pgroonga.sql
tools/setup/postgresql-init-dev-db

Backport to 6.x:
- part of #26097
in an effort to fix python-zulip-api CI:
- zulip/python-zulip-api#878

[6.x] pgroonga: Remove now-unnecessary 'GRANT USAGE' statement.

---

zerver/lib/email_notifications.py
zerver/lib/timestamp.py
zerver/signals.py
zerver/tests/test_message_notification_emails.py

discussion: https://chat.zulip.org/#narrow/channel/137-feedback/topic/global.20times.20in.20emails/with/2268077
| --- | --- |
| <img width="1409" height="705" alt="image" src="https://github.com/user-attachments/assets/a5a9da07-e6a1-41e4-8d05-977a59b2dee8" /> | <img width="1411" height="764" alt="Screenshot from 2025-10-01 15-53-01" src="https://github.com/user-attachments/assets/ade16cc2-2889-41fe-9aed-6c327985f25b" /> |

Convert datetime in missed message emails to user's local time as a readable string.

---

tools/build-release-tarball
tools/release-tarball-exclude.txt

We don't include starlight_help/dist_no_relative_links since that is only useful for zulip.com and zulip.com doesn't use tarballs for deployment.
<details>
</details>

help: Include dist in release tarball and exclude source code.

---

web/styles/search.css

Reported here:
https://chat.zulip.org/#narrow/channel/9-issues/topic/extraneous.20box.20when.20clicking.20on.20search.20pill.20in.20typeahead/near/2268435

search: Remove outline for focused pills in the typeahead.

---

web/styles/input_pill.css
web/styles/settings.css
web/styles/subscriptions.css

This extends existing styling for pills for search and org permissions, to fix a bug in the invite users modal. Continues work in #34371, which tested other input elements.
Fixes bug reported here:
https://chat.zulip.org/#narrow/channel/9-issues/topic/pasting.20invite.20email.20addresses

pill_input: Use flex-grow 1 on all input pills.

---

scripts/lib/upgrade-zulip-from-git

Before:
```
File "/home/zulip/deployments/2025-10-07-19-23-54/./scripts/lib/upgrade-zulip-from-git", line 153, in <module>
commit_hash = subprocess.check_output(
File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.10/subprocess.py", line 526, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--verify', 'refs/tags/moose']' returned non-zero exit status 128.
During handling of the above exception, another exception occurred:
File "/home/zulip/deployments/2025-10-07-19-23-54/./scripts/lib/upgrade-zulip-from-git", line 166, in <module>
commit_hash = …
```

upgrade-zulip-from-git: Provide better error message on a bad refname.
